### ISSUE TITLE
Permanent names

### ISSUE THREAD

**Issue by dennismckinnon** [tendermint/tendermint#100]
There are use cases when an entry in the namereg would be desired to be permanent without excessive cost of buying the name til the end of time.

for example ABI storage on chain when creating a contract you might want to make a permanent abi entry so the dapp is essentially self describing.

There are a couple questions to answer:

How do we properly control this - likely answer another permission but without the ability to write a forwarding snative contract... 
What kind of constraints are there? I'm betting none except those imposed by the magical non-existent contract above
What is the policy of overwriting the permanent entry? - Anyone with permanent name (pname) seems to contradict the whole premise. Writer seems reasonable. Maybe pname-del should be another permission?

**Comment by jaekwon** [comment]
I'm thinking that buying the name until the end of time should be cheap.  Just about anyone should able to afford say 256 years of the name.  Say, $1 times 256, so $256 to register it for the maximum?

**Comment by ebuchman** [comment]
Ya right now it's way to expensive. I'm thinking we can bring it down a couple orders of magnitude (maybe divide current system by 256). But 256 for the maximum seems awfully cheap no?

**Comment by ebuchman** [comment]
move to https://github.com/eris-ltd/eris-db
