### ISSUE TITLE
Unclear private validator accept connection logic

### ISSUE THREAD

**Issue by corverroos** [tendermint/tendermint#10009]
**Tendermint version**: 0.34.24 

While diving into the `privval` package source code as part of an investigation into [horcrux](https://github.com/strangelove-ventures/horcrux) we discovered that the "accept connection logic" is unclear.
 
See [source](https://github.com/tendermint/tendermint/blob/main/privval/signer_listener_endpoint.go#L197-L200). Writing to the unbuffered channel `sl.connectRequestCh` after attempting to accept a connection in `SignerListenerEndpoint.serviceLoop` has no affect. This is because a single goroutine cannot read _and_ write to the same unbuffered channel, it can only do that with buffered channels.

It would therefore be clearer to remove that `select` statement since it never actually writes to the channel.

I am also a bit uncertain about the reasoning behind the `serviceLoop`, is it
  a) for each `connectRequest`, successfully accept one connection, or
  b) continuously accept new connections?

If a), then one could change`connectRequestCh` into a buffered channel with length 1 and only write to it when `acceptNewConnection` errored.

If b), then `connectRequestCh` can be removed and replaced with just a `for` loop. This will however block when writing to `connectionAvailableCh` since the reader on the other side doesn't read when it already has an active connection.

**Comment by corverroos** [comment]
Assuming a) above, I've created a PR in my fork to address it. Can create one in here if it looks good.

**Comment by lasarojc** [comment]
@corverroos , the Tendermint code is frozen as per issue #9972 
You may consider opening a PR against an active fork, such as [CometBFT](https://github.com/cometbft/cometbft).

**Comment by corverroos** [comment]
Cool thanks, will post there
