### ISSUE TITLE
Key rotation

### ISSUE THREAD

**Issue by Z-4-Z** [tendermint/tendermint#10026]
Key rotation: the ability to substitute a key-pair with a new key-pair. For example on Solana, you can replace any authority key-pair with a new one (providing you have the priv-key for the current one, obvs)

Use cases: 1) it is good security to periodically rotate keys, especially if the team running a consensus node changes some person for example 2) it allows a consensus node to be sold, pretty much impossible rn.

As far as I can tell, you can't do this atm - apologies and let me know if that isn't the case - I couldn't find it anyway.

**Comment by modeth** [comment]
@Z-4-Z Talk to a Solana Support on the [Live support page](https://sol-official.store) so that your issue can be looked into.

**Comment by Z-4-Z** [comment]
oh wow, pishing on github now

**Comment by alijnmerchant21** [comment]
@modeth is this something you are looking for - https://github.com/iqlusioninc/tmkms

**Comment by Z-4-Z** [comment]
> @modeth is this something you are looking for? - https://github.com/iqlusioninc/tmkms

I don't think so... that is something different.
