### ISSUE TITLE
How to decode the block_results data?

### ISSUE THREAD

**Issue by aramakam3505** [tendermint/tendermint#10024]
I have used this RPC **http://127.0.0.1:26657/block_results?height=_**

but the I am unable to see the actual values. For example if I want to know how many coins have been minted in that block, Value is not being displayed but some key and value pair is returned.
{
        "type": "mint",
        "attributes": [
          {
            "key": "Ym9uZGVkX3JhdGlv",
            "value": "MC4wOTk5OTE1Njk2MzI4NTQ1OTU=",
            "index": true
          }]
}

How to decode the above values? 
Any help will be much appriciated.

**Comment by Cantincy** [comment]
Key and value are both in Base64 encoding format. You can decode them by Base64 decoding tool in Go. After decoding, key is "bonded_ratio" and value is "0.099991569632854595". I hope this helps.

**Comment by aramakam3505** [comment]
@Cantincy thanks for responding.
can you please give any reference for the same?

**Comment by aramakam3505** [comment]
thanks @Cantincy
