### ISSUE TITLE
Any suggestion for how to do  authority management using tendermint core?

### ISSUE THREAD

**Issue by jdHehe** [tendermint/tendermint#1002]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by zramsay** [comment]
that would likely be handled at the app level rather than tendermint core. Check out https://tendermint.com/community for a place to discuss these things. Feel free to open an issue with a specific bug or feature request
