### ISSUE TITLE
How to update validators in a live network?

### ISSUE THREAD

**Issue by jdHehe** [tendermint/tendermint#1003]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by ebuchman** [comment]
Are you using a specific app?

If building your own, the app decides how to do it by returning changes to the validator set in the EndBlock response. You can see an example, the PersistentDummy, here: https://github.com/tendermint/abci/tree/master/example/dummy

Please open a new issue if you find a bug in the validator changing.
