### ISSUE TITLE
Clarification/documentation: commit round value

### ISSUE THREAD

**Issue by swojo** [tendermint/tendermint#10041]
According to the documentation ( [data structures](https://github.com/tendermint/tendermint/blob/v0.34.24/spec/core/data_structures.md#commit) ), the commit round should always be greater than 0 but we are obtaining commit rounds of 0 from tendermint (v0.34.24). Since the light client's commit signature matches, it does not seem to be a question of an incorrect commit/block being sent to the light client. Moreover, the [consensus spec](https://github.com/tendermint/tendermint/blob/v0.34.24/spec/consensus/signing.md?plain=1#L103) indicates that a round value of 0 is valid. 

Can the commit round indeed be zero or is there a different problem in this scenario?

**Comment by cason** [comment]
Unfortunately, this document is providing an imprecise information. The round field in a `Commit` cannot be negative (in the code: https://github.com/cometbft/cometbft/blob/v0.34.x/types/block.go#L872).

Every height in the consensus algorithm starts from round 0, and indeed most heights are decided at round 0. 

Thank you for catching this inconsistency, we will it fix the documentation.
