### ISSUE TITLE
How to stop creating empty blocks?

### ISSUE THREAD

**Issue by llwinner** [tendermint/tendermint#10049]
I launched a new chain, and changed each validator's config.toml, set create_empty_blocks = false.
But when I run the chain, the empty blocks were still created. After 4k empty blocks were created, it cost me 80MB space
How to stop creating empty blocks?

**Comment by lasarojc** [comment]
Does your app state change after processing an empty block?

**Comment by llwinner** [comment]
@lasarojc I use ignite cli to create a chain, I do nothing, just a empty chain. But the chain create empty blocks automatically. I can't stop that by setting  create_empty_blocks = false. A lot of people had the same problem since 2019.

**Comment by lasarojc** [comment]
Hi @llwinner 
Pls provide the sequence of steps you used to create the chain, including the version of ignite CLI. We'll try to repro here.

**Comment by llwinner** [comment]
@lasarojc 
My ignite version:
Ignite CLI version:		v0.26.1
Ignite CLI build date:		2023-01-24T18:50:18Z
Ignite CLI source hash:		d2a2e287c176ba010557f0b8fbaa198cdeee928d
Ignite CLI config version:	v1
Cosmos SDK version:		v0.46.7
Your OS:			linux
Your arch:			amd64
Your go version:		go version go1.20.6 linux/amd64
Your uname -a:			Linux llwinner-virtual-machine 5.19.0-50-generic #50-Ubuntu SMP PREEMPT_DYNAMIC Mon Jul 10 18:24:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Your cwd:			/home/llwinner/spn/23/config
Is on Gitpod:			false

and the steps are:
1. run ignite network chain publish github.com/ignite/example on the first virtual machine
2. run ignite network chain init 32, ignite network chain join 32 --amount 95000000stake on the second virtual machine
3. run ignite network request list 32 on the first virtual mathine
4. run ignite network request approve 32 1,2 on the first virtual machine
5. run ignite network chain launch 32 on the first virtual machine
6. run ignite network chain prepare 32 on the second virtual machine
