### ISSUE TITLE
Provide a test case template to users

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1005]
I've noticed a trend where user submit a bug, but she does not have time to write a test case. Maybe it would be helpful to provide a **test case template** like Ruby on Rails does (https://gist.github.com/Envek/5360783, https://github.com/rails/rails/blob/master/activerecord/examples/simple.rb)

Maybe it is also worth exploring https://github.com/coreos/etcd/tree/master/tools/functional-tester in order to move from bash to Golang.

**Comment by jackzampolin** [comment]
Closing this issue as it requires a fundamental re-architecture of our testing infra to realize.
