### ISSUE TITLE
P2P clients sharing the same IP should not be considered as duplicate

### ISSUE THREAD

**Issue by arno01** [tendermint/tendermint#10052]
## Summary

> Tendermint used `v0.34.21` / cosmos-sdk `v0.45.9`

P2P clients sharing the same IP should not be considered as duplicate.

## Problem Definition

Because Tendermint (i.e. RPC, P2P module) filters the peers (P2P peers) based on the client's `remote_ip` (*ignoring the remote ephemeral port), it creates the following limitations when running in K8s (or behind NAT):
* [when RPC P2P (`26656/tcp`) port is directly exposed via K8s's `hostPort`] one can't connect more than a single client (validator/rpc) with the same public IP to the RPC; (RPC Error: `INF Inbound Peer rejected err="filtered CONN<184.105.162.170:64562>: duplicate CONN<184.105.162.170:64562>"`, where `184.105.162.170` is a public IP that can be shared by multiple tenants/clients)
* [when RPC P2P (`26656/tcp`) port is exposed via the K8s ingress (e.g. `ingress-nginx-controller`) or any other load balancer or when it is behind the NAT] only a single client (validator/rpc) can connect to the RPC as the `remote_ip` *always* gets derived (by the RPC) from the internal IP of the ingress for *any* public IP.  (RPC Error: `INF Inbound Peer rejected err="filtered CONN<10.233.108.119:50064>: duplicate CONN<10.233.108.119:50064>" module=p2p numPeers=2`, where `10.233.108.119` is the IP of the ingress/LB/NAT)

## Proposal

- **\*** That wouldn't be an issue if Tendermint wouldn't only look at the `IP` but at the `IP:PORT` when deciding on whether the p2p client is unique.

## Additional info

Code paths:

* https://github.com/tendermint/tendermint/blob/35581cf54ec436b8c37fabb43fdaa3f48339a170/p2p/errors.go#L55
* https://github.com/tendermint/tendermint/blob/35581cf54ec436b8c37fabb43fdaa3f48339a170/p2p/switch.go#L831
* https://github.com/tendermint/tendermint/blob/35581cf54ec436b8c37fabb43fdaa3f48339a170/p2p/transport.go#L392

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Vijay-K-2003** [comment]
Is this a GFI? I would like to try to work on this @arno01

**Comment by arno01** [comment]
> Is this a GFI? I would like to try to work on this @arno01

I think so, good luck!

**Comment by Vijay-K-2003** [comment]
Could you please help me with the process to reproduce this situation?

**Comment by arno01** [comment]
> Could you please help me with the process to reproduce this situation?

You can test either scenario:

## 1) NAT

1. `HostA`: Start tendermint app server;
2. `HostB` (behind NAT, sharing the same public IP as `HostC`): Connect tendermint app client to `HostA`;
3. `HostC` (behind NAT, sharing the same public IP as `HostB`): Connect tendermint app client to `HostA`;

As soon as you reach point 3. you will hit the `duplicate CONN` error as the tendermint app server will see the same public IP (except for the remote ports which never overlap) from the `HostC` as `HostB` used.

## 2) Behind the load-balancer (K8s ingress-nginx controller / nginx LB / haproxy / ... any load-balancer pretty much)

1. `HostA`: Start tendermint app server listening over `127.0.0.1:26656` instead of `0.0.0.0:26656`;
2. `HostA`: Deploy LB (any load balancer you like) listening at 26656/tcp over a known public IP and forwarding the incoming connections to the tendermint app server that listens over `127.0.0.1:26656`;
3. `HostB`: Connect tendermint app client to `<Public-IP-Of-HostA>:26656`;

As soon as you reach point 3. you will hit the `duplicate CONN` error as the tendermint app server will only see the incoming IP of the load-balancer which is always same (except for the remote ports which never overlap).
