### ISSUE TITLE
ResultUnconfirmedTxs should include height

### ISSUE THREAD

**Issue by tuloski** [tendermint/tendermint#10069]
## Summary

As title.

## Problem Definition

When requesting unconfirmed txs we should be able to request it for a specific height or at at least the result should include the hight of the answer (I think ANY request should include height TBH). Because AFAIK there is no method to understand at which height the unconfirmed_txs belong to.
Due to delays in the network I can maybe request unconfirmed_txs at block N, then when the node receives the request it already moved to block N+1 and I get the unconfirmed_txs for block N+1 without knowing.

**Comment by melekes** [comment]
feel free to open issue here https://github.com/cometbft/cometbft/
