### ISSUE TITLE
Is it achievable to deploy smart contracts in tendermint?

### ISSUE THREAD

**Issue by Aatom1** [tendermint/tendermint#10076]
I'm trying to create an application about federated learning in tendermint. One of my ideas is to use smart contracts to automate processes such as training task release, model upload and aggregation, reward and punishment mechanisms, etc. However, I have no idea how to achieve smart contracts after view the cods. Is it possible to deploy smart contracts?

**Comment by tuloski** [comment]
You should look at CosmWasm.

**Comment by Aatom1** [comment]
> You should look at CosmWasm.

Thank you very much for your help！
