### ISSUE TITLE
rpc: '/tx' to return merkle proofs for tx results

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1008]
`/tx` should be able to return Merkle proof for the Result as well as the Tx itself

**Comment by melekes** [comment]
this is done.

**Comment by ebuchman** [comment]
Don't think so.

Currently we can return proof that the tx is in the Merkle tree in the block.

But this is about a proof for the result of the tx being in a Merkle tree in the block (https://github.com/tendermint/tendermint/blob/master/types/results.go#L53)

**Comment by melekes** [comment]
Oops, sorry
