### ISSUE TITLE
panic: post failed: Post "http://127.0.0.1:26657": EOF

### ISSUE THREAD

**Issue by cantincy** [tendermint/tendermint#10082]
I want to produce 200,000 blocks(1 MB for one block) by submitting transactions via rpc client. But when the height reached about 30,000, the rpc client throwed a panic: post failed: Post "http://127.0.0.1:26657": EOF. 

I tried to restart submitTx.go, but after producing dozens of blocks, the rpc client still throwed the panic.

Tendermint version: 0.34.24

I changed the MaxGas in BlockParam as 50 to ensure one block holds 50 txs. To ensure one block is 1 MB, so every tx is about 20970 B.

The codes in submitTx.go are as follows:
```
package main

import (
	"context"
	"flag"
	"github.com/tendermint/tendermint/rpc/client/http"
	"github.com/tendermint/tendermint/types"
	"time"
)

const size = 20970

var blockNum int

func main() {
	flag.IntVar(&blockNum, "n", 0, "the number of blocks to produce")  // go run submitTx.go -n=200000
	flag.Parse()

	for h := 0; h < blockNum; h++ {        // produce blockNum blocks
		cli, err := http.New("http://127.0.0.1:26657", "/websocket")
		if err != nil {
			panic(err)
		}
               
                // submit 50 txs (block gas is 50 and tx gas is 1, so there are 50 txs in a block)
		for i := 0; i < 50; i++ {       
			tx := make(types.Tx, 0, size+30)
			for len(tx) < size {
				tx = append(tx, time.Now().String()...)
			}
			_, err = cli.BroadcastTxSync(context.Background(), tx)
			if err != nil {
				panic(err)
			}
		}
		time.Sleep(time.Millisecond * 200)
	}
}
```

**Comment by sergio-mena** [comment]
@cantincy you can try https://github.com/cometbft/cometbft/, which is a fork of Tendermint
