### ISSUE TITLE
Broken link on First Tendermint App

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1013]
https://tendermint.readthedocs.io/en/master/getting-started.html

https://tendermint.readthedocs.io/en/master/introduction.rst#ABCI-Overview

**Comment by zramsay** [comment]
fixed in https://github.com/tendermint/tendermint/commit/882c25f2923c57fb140c2288f74972b49ff5e890 ... re-built the docs and it's fixed on RTD master
