### ISSUE TITLE
lite: clarify the docs on "Static" and also perhaps use a more intuitive name

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#1018]
I was just combing through package lite and noticed we have a struct called "Static"

The docs for it say "Static assumes a static set of validators, set on initilization and checks against them. The signatures on every header is checked for > 2/3 votes against the known validator set upon Certify

Good for testing or really simple chains. Building block to support real-world functionality."

Perhaps we could give it a name such as "StaticValidatorsChecker"? I didn't know what to make of "Static"

Also perhaps we could update the docs a little more

"StaticValidatorsChecker assumes a static set of validators, that are set on initilization and it checks against them. The signature on every header is checked for > 2/3 votes against the known validator set upon every invocation of its method Certify

It is good for testing or for use with really simple chains. It is a buuilding block to support real-world functionality." -- let's perhaps add some more content to "real-world functionality"?

**Comment by odeke-em** [comment]
Also a minor nit that we can clear up while here is change
https://github.com/tendermint/tendermint/blob/d14ec7d7d2f407433070665536994e0a1eafab4b/lite/static.go#L13
to
```go
var _ Certifier = (*Static)(nil)
```

**Comment by ethanfrey** [comment]
It was `StaticCertifier`, then I renamed the package when importing into tendermint from light-client, so it was `certifiers.Static` to limit redundancy.

@adrianbrink  then renamed the package to lite, but didn't change the names. Maybe he can finish that cleanup?

Is StaticCertifier / DynamicCertifier / InquiringCertifier clear enough for you?

**Comment by zramsay** [comment]
closed in #1081
