### ISSUE TITLE
lite: ValKeys.Change should check that its index isn't out of range lest waste memory copying

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#1019]
I was just reading the code in https://github.com/tendermint/tendermint/blob/d14ec7d7d2f407433070665536994e0a1eafab4b/lite/helpers.go#L32-L37

notice that in there we always assume that we'll be passed in the right ith index, let's fix this by adding an out of bounds check before even allocating, to make it
```go
func (v ValKeys) Change(i int) ValKeys {
    if i < 0 || i >= len(v) {
       // Handle this problem
       return nil //, error perhaps?
    }
   cv := make(ValKeys, len(v))
   copy(cv, v)
   cv[i] = crypto.GenPrivKeyEd25519().Wrap()
   return cv
}
```
and the above error fixing also makes us wonder if perhaps that method should return an error. I know the usual style here is to panic, but perhaps it isn't too late to change that signature to properly send back a nil ValKeys and an error.

**Comment by xla** [comment]
@jaekwon Is this still relevant after the lite refactors?
