### ISSUE TITLE
lite: memStoreProvider should use binary/range search for GetByHeight

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#1021]
Just by reading the code I noticed that the only place that we seem to be mutating is by appending to it then subsequently sorting byHeight at
https://github.com/tendermint/tendermint/blob/d14ec7d7d2f407433070665536994e0a1eafab4b/lite/memprovider.go#L54-L55

However, GetByHeight performs a linear search each time
https://github.com/tendermint/tendermint/blob/d14ec7d7d2f407433070665536994e0a1eafab4b/lite/memprovider.go#L64-L70
which in the code above always assumes the best case. IMO this doesn't do much to guarantee us speed and cuts out the benefits of sorting each time. Let's make this a binary/range search because no matter how many items are inserted in there, the worst case for the binary/range search will always be O(log(n)) while the current code is linear and to show the impact of this change:
If there are are 1million byHeight entries:

n=len(m.byHeight)|maxIterations(Linear search)|maxIterations(Binary search)
---|---|---
10|10|4
100|100|7
1000|1000|10
10000|10000|14
100000|100000|17
1000000|1000000|20

and here is the code that we can use to fix this, it is also shorter and magnitudes more efficent
```go
// Since it is already sorted by largest to lowest in StoreCommit
i := sort.Search(len(m.byHeight), func(j int) bool {
    return m.byHeight[j].Height() <= h
})
```

and for more information, please read https://en.wikipedia.org/wiki/Binary_search_algorithm

**Comment by ethanfrey** [comment]
Yes, Emanuel, you are right.

This was designed for clients that wouldn't have many headers, maybe 500 tops. And I wasn't so worried about in memory iteration performance.

But if you want to make a proper binary search and add a few tests, it would be a great addition. Also maybe optimize the insert. 

My code went for simplicity and correctness first. Performance second. Designed to add it later, but not always implemented.

**Comment by ethanfrey** [comment]
Also the majority of the cases, we will search for the most recent or one of the eg. 5 most recent headers. In this case, I think a reverse linear search may be faster than a binary search

**Comment by odeke-em** [comment]
@ethanfrey thank you for the background information, and in deed you are spot on, when we have little data, linear search shines as you'll see in this PR benchmark shoot out results in PR https://github.com/tendermint/tendermint/pull/1043.

I've also optimized the insertion to lazily sort(so not sorting on every insertion).

However, when things get large, binary search finna save us. So Python explored such tradeoffs and their current sorting algorithm switches to the different sorts depending on the amount of data available https://en.wikipedia.org/wiki/Timsort

**Comment by odeke-em** [comment]
Alright, fixed by PR https://github.com/tendermint/tendermint/pull/1043, thanks everyone for the engagement!
