### ISSUE TITLE
`tendermint version` breaks semver string parsers

### ISSUE THREAD

**Issue by paulperegud** [tendermint/tendermint#1023]
**BUG REPORT**

**Tendermint version**
`0.14.0-'88f5f21d'`

**What happened**:
`$ tendermint version`
`0.14.0-'88f5f21d'`

**What you expected to happen**:
`$ tendermint version`
`0.14.0-88f5f21d`

**Anything else do we need to know**:
`tendermint version` produces a string that breaks semver parsers. According to specification version string should not contain quotes ('). Problem appears at least with tendermint binary that can be downloaded from https://github.com/tendermint/tendermint/releases

**Comment by zramsay** [comment]
closed in #1024, thanks @paulperegud

**Comment by ebuchman** [comment]
lol woops. thanks
