### ISSUE TITLE
consensus: ValidateBlock is called 4 times per block

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1032]
maybe the blockExecutor can cache the result so we only effectively do the validation once ...

**Comment by ebuchman** [comment]
During fast-sync, we run VerifyCommit twice (once to know its legit, and once in the ApplyBlock under validateBlock)

**Comment by jackzampolin** [comment]
Sounds like the first step here is benchmark the increase in performance of this change.
