### ISSUE TITLE
'/status' endpoint reporting unreliable

### ISSUE THREAD

**Issue by nickray** [tendermint/tendermint#1033]
BUG REPORT

I am running several gaia validators on gaia-1 testnet. Version 0.3.0 According to `/status` endpoint they use:

```
      "version": "0.12.0",
      "other": [
        "wire_version=0.7.1",
        "p2p_version=0.5.0",
        "consensus_version=v1/0.2.2",
        "rpc_version=0.7.0/3",
```

Environment: Centos 7.4 64bit

I don't have a repro, however after a restart the `latest_*` metrics were not updated in the `/status` endpoint, while the log files showed that blocks were coming in.

```
    "latest_block_hash": "859C8D1A040C100FE5F51735ECD42E365A8908E1",
    "latest_app_hash": "947AF562D8B75C86E8C08685FA7F32467CDA0EF1",
    "latest_block_height": 74532,
    "latest_block_time": 1514517557177000000,
```

After another restart, the metrics were updated again.

**Comment by ebuchman** [comment]
Is it possible something was caching the old results? What kind of http client are you using? And you couldn't reproduce ?

**Comment by greg-szabo** [comment]
Old issue, closing. Please reopen if encountered again.

**Comment by ebuchman** [comment]
Is this reproducible? I'll close for now, please re-open with more details if you know how to reproduce. Thanks.
