### ISSUE TITLE
adding new validator problem

### ISSUE THREAD

**Issue by promer111** [tendermint/tendermint#1050]
Hello. 
We use ethermint and tendermint.

First, we ran 4 node as vp. 
after then, we want add new node as vp on previously configured chain for 4 node.
but,  new node don't attend on chain as a vp node.
(we follow add validator section on tendermint documentation)

non-vp node can easily appended existing chain. 
but vp can not added.

is this a bug?

**Comment by adrianbrink** [comment]
@promer111 Ethermint does not have the functionality yet for staking and validator set changes. We will be adding that functionality in Q1 of this year.
