### ISSUE TITLE
Allow ABCI app to return ordering of transactions in CheckTx

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1064]
We need to decide whether the application should handle transaction ordering or whether Tendermint core takes care of that. This is related to how fees are distributed and whether Tendermint core understands fees. 

I am proposing that the application can return an ordering for transactions by which the mempool is sorted. This makes the ABCI protocol more flexible for application developers, since it allows them to arbitrarly order their transaction instead of just ordering them by fees in Tendermint core.

**Comment by ethanfrey** [comment]
This is done by exposing gas and fees. I was against the names of gas and fees, preferring cost and benefit or other generic terms.

Basically, gas/cost should provide a good estimate of how much time the tx will take.

fees/benefit ranks the relative importance. this can be done by counting fees, adding a large number when certain "admin" keys sign a transaction, adding numbers for certain classes of actions that are very important (eg. processing epoch changes), etc.

They are both just integers, so abci developers should feel free to return any metric they want there.

I discuss this more here: https://github.com/tendermint/tendermint/issues/1065#issuecomment-355579105

**Comment by jaekwon** [comment]
What @ethanfrey said.  Tendermint orders transactions, and if your transaction has insufficient gas it currently just gets rejected and ignored.  That's all we'll do for the launch, besides letting the user add exchange rates in a file.  Please consult Sunny.
