### ISSUE TITLE
Genesis file changes for Mainnet launch

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1066]
For mainnet launch we need to gather two pieces of information "the validation pub key" and "signed tx bytes with a bonding transaction". 

The proposal is that we have a repo with a blank genesis file. If anyone wants to become a validator they open a PR with their newly and securely generated validation key address. Furthermore they need to include signed transaction bytes of a bonding transaction that bonds to their validation key.

This requires changes to the genesis file structure. This was discussed during today's validator meeting. @rigelrozanski @Greg-Szabo @zmanian Gautier Jim and @jolesbi  were present.

Also, the forecast is that gaia-5 might be mainnet. :-)

**Comment by rigelrozanski** [comment]
yes, this reflects our discussion earlier - we will need to create a mini tool to generate the signed TX for the genesis in gaia - this should maybe even be a hidden command as it will get used so infrequently. But the premise is this signed transaction will be run at the initialization before the first block and effectively verify that the proposed validator pubkey and associated power is coming from the coins which are also in the genesis file, the transaction will move those coins to a bonded account just as gaia normally operates. Such a cool idea

**Comment by adrianbrink** [comment]
Also, we need to start combining the genesis files for Gaia and Tendermint. 

Also, I would vote to combine both processes and run them all in one process. So by issuing `gaia node start` it automatically starts Tendermint Core too. The user provides one genesis file and then gives it to gaia and it just works.

**Comment by rigelrozanski** [comment]
gaia already run tendermint in-proc? client needs to be a second process no doubt... am I missing something?

**Comment by ebuchman** [comment]
Does this actually require changes to the Tendermint genesis.json? Or is it something we can do in the app_options part? I'm going to presume the latter and close this. Please re-open a new issue with clarity as to what exactly needs to change in tendermint genesis.json if anything. Thanks.

**Comment by rigelrozanski** [comment]
Yeah can occur in app options.
