### ISSUE TITLE
Document how fees and costs are handled and how they affect transaction ordering

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1072]
Can you elaborate on where this fee/cost/tx_order stuff is heading? I.e. what does it mean for core users that don't use COSMOS and have no concept of cost/fee in their abci app / domain.

I was reading the thread about ordering tx' and quite stunned that you considered this to be done via a cost/fee logic.
If you bake this into core, how will users / abci-implementers that don't have such a cost concept be able to allow ordering?

**Comment by melekes** [comment]
> I was reading the thread about ordering tx' and quite stunned that you considered this to be done via a cost/fee logic.

do you have other ideas about how to implement transaction ordering?

**Comment by srmo** [comment]
@melekes No. Just vague ideas. Until now, ordering was for me the thing that is done by the actual proposer. Per default, the order transactions have arrived in the mempool.
Remember, the "Tendermint in a nutshell" always spoke about being able to provide a custom ordering logic for the proposer, which will probably be handled via ABCI. 
Again, the ABCI app seems to be the only one able to say what "order" means. So if you use an ABCI app that has no concept of cost/fee, it seems counterintuitive to implement ordering in such a way.

You could now think of having the proposer callback the ABCI-App to have the app weigh transactions with a cost or even have tx' only broadcasted when they have a cost attached. But this will require apps without a cost concept to come up with the need to artificially add such a concept.

Counterargument would be that using such an artificial concept is the same as a custom ordering logic, only that it is called "cost" in the context of core. 
I.e. having a set of tx and assign each tx a distinct, ascending index for ordering may be considered semantically equivalent to assigning each tx a distinct, ascending "cost".

Am I on the wrong track here?

At this point, I'm not really talking about mempool ordering (checkTx) as this might not make as much sense/be something completely different, and is already discussed in another iirc.

**Comment by melekes** [comment]
@srmo see https://github.com/tendermint/abci/issues/57

also some bits from our slack:

```
Wouldn't it be better if the app just returns an ordering. So maybe just
type Result struct {
Priority int64
}
and the app can return an arbitrary number, and core takes the lowest ones as the most important ones.
That way we don't couple of to Denoms and Amounts, but the app can just decide based on their internal state which transactions are more important.

After other verbal discussions, I always thought we went towards Gas/Value or something like that.. how much compute time vs. how much importance. And abstract them out, so other (eg. permissioned) chains can use other metrics to rate value.

We can also do this in the app, as SetOption with no side effect in deliver but only checktx... handle exchanging on the app, and return a single value, yes it's possible.  But I think we still want Tendermint to handle a lot of concerns around pricing and prioritization, like auto adjusting its min price based on what it sees in its mempool, hooking up to any exchange rate provider, and also allocate resources like reserve storage space or memory space...  And we want to maybe in the future make the mempool accountable and that will be easier if we include the primary data.

This feature seems only for public chains with fees. Private chains would want other priorities. And I am not sure if it would make sense to map that to a Coin.

Maybe we do want a number and a type for that use case as well? Maybe we should just rename it to more general than Coin.

I don't think hooking up to am exchange should be built into tendermint, but sure, allow it to be added.

You guys did a great job with a truly generic abci interface that doesn't enforce staking logic or TX format or much and allows control to the abci app. Tendermint core needs no changes.

I just see this as the first example of tailoring tendermint abci to one specific use case, and feel that while we must support it, we should not limit to it.
```

**Comment by srmo** [comment]
Thanks for the heads up. The snippet you provide does a better job at verbalising my concerns. 
The reason for me bringing this up is what is also described in your link.
Users or tendermint core like us, that don't have concepts of coins/fees/gas get pretty nervous when it reads that such things might move to core. One of our primary reasons for choosing tendermint was that it *does not* require such things. We didn't want to be tied to some monetary concept that has no sense in our problem domain (talking private chain here).
For me personally, I want to be able to describe tendermint with it's amazing punchline, that it is "just" a "consensus mechanism for replicated state machines" and not "[...] which requires coins/fees/gas and some hablubla" - again, this last point is pretty personal and emotionally driven :)

**Comment by ebuchman** [comment]
We removed fee: https://github.com/tendermint/tendermint/pull/2043
