### ISSUE TITLE
Wrong Block.Header.AppHash error when I send the first transaction.

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#1077]
Tpye: BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): v0.10.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Blockfreight

**Environment**:
- **OS** (e.g. from /etc/os-release): Linux Alpine
- **Install tools**: Docker, Kubernetes (Client: GitVersion:"v1.9.0" and Server: GitVersion:"v1.8.0") and Glide
- **Others**:

**What happened**: When I send the first transaction, Tendermint breaks with the following error: 
```bash
I[01-07|21:52:30.851] Executed block                               module=state height=38 validTxs=0 invalidTxs=0
I[01-07|21:52:30.856] Committed state                              module=state height=38 txs=0 hash=
I[01-07|21:52:32.270] Executed block                               module=state height=39 validTxs=0 invalidTxs=0
I[01-07|21:52:32.292] Committed state                              module=state height=39 txs=0 hash=64D34790D11476107B0AFE9A14076EEE11607E97
E[01-07|21:52:33.369] enterPrevote: ProposalBlock is invalid       module=consensus height=40 round=0 err="Wrong Block.Header.AppHash.  Expected 64D34790D11476107B0AFE9A14076EEE11607E97, got "
E[01-07|21:52:33.505] CONSENSUS FAILURE!!!                         module=consensus err="Panicked on a Consensus Failure: enterPrecommit: +2/3 prevoted for an invalid block: Wrong Block.Header.AppHash.  Expected 64D34790D11476107B0AFE9A14076EEE11607E97, got " stack="goroutine 1137 [running]:\nruntime/debug.Stack(0xc4218a52d8, 0xb53760, 0xc422d7b140)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func1(0xc4211ca340)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:508 +0x57\npanic(0xb53760, 0xc422d7b140)\n\t/usr/local/go/src/runtime/panic.go:491 +0x283\ngithub.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.PanicConsensus(0xb53760, 0xc422d7b120)\n\t/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/errors.go:39 +0xf3\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterPrecommit(0xc4211ca340, 0x28, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:1031 +0x1979\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc4211ca340, 0xc422d61300, 0xc420151000, 0x40, 0xc4218a5b00, 0xc4218a5b20, 0x42a549)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:1410 +0x1100\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc4211ca340, 0xc422d61300, 0xc420151000, 0x40, 0x0, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:1325 +0x59\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc4211ca340, 0xb82f00, 0xc422956848, 0xc420151000, 0x40)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:576 +0x589\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc4211ca340, 0x0)\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:530 +0x6ea\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/go/src/github.com/tendermint/tendermint/consensus/state.go:248 +0x10d\n"
```

**What you expected to happen**: This error is caused by the app hash not being transmitted by the initial pod, which creates the transaction. This is not happening per the log printing expected <HASH> got "". I expected the hash to be transmitted, and for the transaction to be validated, and then replicated between the seeds.

**How to reproduce it** (as minimally and precisely as possible):  To setup the environment follow the step-by-step below: 
```
1. Install Glide (if you have not done that)
curl https://glide.sh/get | sh

2. Download Blockfreight Tools Project
go get github.com/blockfreight/tools

3. Go to the folder with the app.yaml file responsible to create Pods.
cd $GOPATH/src/github.com/blockfreight/tools/blockfreightnet-kubernetes/examples/blockfreight/

4. Run the file
kubectl create -f app.yaml
```

![image](https://user-images.githubusercontent.com/5904751/34655391-fa1aedcc-f45c-11e7-97cc-c76267017c5d.png)

```

5. Check if all pods are running
kubectl get pods

```
![image](https://user-images.githubusercontent.com/5904751/34655399-32b20896-f45d-11e7-8f7e-cf88cc684f4a.png)

Once they are all running, this is how I am testing my app and getting the error:
```
1. Access a Pod
kubectl exec -it bftx-0 --container app -- /bin/bash

2. Go to the app folder
cd ../go/src/github.com/blockfreight/go-bftx/

3. Create a transaction (it returns the UID of the transaction, you will need this ID to the next commands)
bftx construct bf_tx_example.json
```
![image](https://user-images.githubusercontent.com/5904751/34655419-7f2e2b8c-f45d-11e7-9a80-253aec292d75.png)
```

4. Sign the transaction
bftx sign <ID-RETURN-ON-STEP-3>
```
![image](https://user-images.githubusercontent.com/5904751/34655422-a8077040-f45d-11e7-9fa3-d9c175348512.png)
```

5. Broadcast the transaction
bftx broadcast <ID-RETURN-ON-STEP-3>
```
![image](https://user-images.githubusercontent.com/5904751/34655432-c55c5ff2-f45d-11e7-9a99-a035c67ad901.png)
```

6. Commit it
bftx commit
```
![image](https://user-images.githubusercontent.com/5904751/34655438-e970f420-f45d-11e7-8e8d-96ee703a9481.png)
```

7. Exit the pod.
exit

8. Get the logs from the pod you have sent a transaction: 
kubectl logs -c tm -f bftx-0
```
![image](https://user-images.githubusercontent.com/5904751/34655441-fe52456a-f45d-11e7-93a1-c74f3749d356.png)

**Anything else do we need to know**: No

**Comment by adrianbrink** [comment]
So you are running your own application or Merkleeyes?

**Comment by gianfelipe93** [comment]
Yes, I have my own Golang app.

**Comment by adrianbrink** [comment]
Mh, so a pod does not create itself a transaction. 

The pods are validation nodes that come to consensus over transactions send by clients. 

A standard flow would be.
1. Start the network and all pods
2. A client signs and sends a transaction
3. Tendermint core gossips that transaction and plays it against all nodes.

I don't fully understand why you manually invoke `Commit` on the application (using probably the abci-cli). Normally you only send a transaction to Tendermint core with `broadcast_tx` and then Tendermint core invokes commit itself when it has created a new block.

**Comment by gianfelipe93** [comment]
What I did earlier today to make it works was changing my broadcast function to send the transaction to the RPC broadcast_tx_sync instead of using the abci broadcast function.

Does it make sense ? (I am not sure if this is what I just suggested)

**Comment by adrianbrink** [comment]
You should never send transactions directly to the ABCI app. The only RPC interface that clients should use is `Tendermint RPC`. Try that and see if it works.

**Comment by gianfelipe93** [comment]
Yeah, that is the one I was using. I used Tendermint RPC ‘broadcast_tx_sync’ to send a transaction it looked like it was working. I will keep testing tomorrow and if something goes wrong I’ll update here.

**Comment by adrianbrink** [comment]
Okay. I'll close it for now. If you find a bug with Tendermint tomorrow, let's reopen it.

**Comment by gianfelipe93** [comment]
I believe that the apphash problem is solved, however I have got a new problem. When I send a transaction to a Pod, the transaction can be found only in that Pod’s database. This means that the transaction is not being replicated to the other pods' databases.

Is the goal to replicate each transaction from the Pod's database to all other Pod databases?

**Comment by adrianbrink** [comment]
How have tested that the tx is only in one pod. Which endpoint are you using to query Tendermint core?
