### ISSUE TITLE
rpc/client: why does SignClient use *int64 for arguments

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#1078]
I was just reading through the lite code and I have a question:
why does rpc/client.SignClient use *int64 as a height argument yet we don't seem to be mutating the height pointer
https://github.com/tendermint/tendermint/blob/cf426111876e78a341f73fdb459d166dc513d725/rpc/client/interface.go#L46-L53

The first guess I can think of is that perhaps we are using that in order to be able to send over RPC arguments and detect if we've sent over no-height i.e `height: null` but if that's the reason, then we are leaking information about the underlying implementation to the API level.

I don't see any height pointer setting:
Not in HTTPClient
https://github.com/tendermint/tendermint/blob/381fe19335ba8825e04d1d0fefa5cac709bb7178/rpc/client/httpclient.go#L199-L206

Nor in LocalClient
https://github.com/tendermint/tendermint/blob/381fe19335ba8825e04d1d0fefa5cac709bb7178/rpc/client/localclient.go#L111-L113

https://github.com/tendermint/tendermint/blob/381fe19335ba8825e04d1d0fefa5cac709bb7178/rpc/core/blocks.go#L352-L364

**Comment by melekes** [comment]
I think it is made that way so we can proxy call to core.Block/Commit/...

https://github.com/tendermint/tendermint/blob/master/rpc/core/blocks.go#L196

```
// Get block at a given height.
// If no height is provided, it will fetch the latest block.
func Block(heightPtr *int64) (*ctypes.ResultBlock, error) {
``

**Comment by melekes** [comment]
> i.e height: null but if that's the reason, then we are leaking information about the underlying implementation to the API level.

i think it is a consequence. like client might send null, but our implementation will check for it.

**Comment by melekes** [comment]
Go does not have types like `LatestHeight | Int`. I think it's ok to use a pointer here for this purpose. Please reopen if you have a better idea.
