### ISSUE TITLE
lite: GetCertifiedCommit never actually certifies commit due to invalid return ignoring returned err

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#1079]
I was just reading through the lite/proxy code and noticed this in GetCertifiedCommit

https://github.com/tendermint/tendermint/blob/381fe19335ba8825e04d1d0fefa5cac709bb7178/lite/proxy/query.go#L118-L119

The above I believe was an innocent mistype/copy+paste error but it invalidates the entire purpose of certifying commits and if I am reading that code right, irrespective of the result of certifying always returns a nil error. This to me is a potential vulnerability as long as we can get a commit with the same height as passed in.

Let's avoid this by fixing it to
```go
if err := cert.Certify(commit); err != nil {
    return empty, err
}
return commit, nil
```

and also let's gut out the weird named return signature whose purpose I believe was to have `empty` defined but that's iffy, could we please make it
```
func GetCertifiedCommit(h int64, node rpcclient.Client,
	cert lite.Certifier) (lite.Commit,error) {
 
       var empty lite.Commit
```

**Comment by adrianbrink** [comment]
Yep, probably our first vulnerability. :-)
