### ISSUE TITLE
Build & distribution process suggestions

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1090]
Refs #837, #966 

### 1. Test the same binary we are distributing

benefits: **+more confidence that we're shipping what we've tested**

how old distribution process look like: run tests (`make test_integrations`) ++ build a binary (inside docker), distribute (`make dist`)

how new distribution process will look like: build a binary (inside docker), copy it into test container, run tests, distribute it if success (`make dist`)

Alternative: checksum code before running `make test_integrations` and check it before running `make dist`.

Assumption: we're assuming something might happen between those two steps (`make test_integrations` and `make dist`)

**Comment by zramsay** [comment]
The Jenkins testing pipeline builds the binary once then copies it to each job. Don't know if it's safe to assume it doesn't change when copied between jobs

**Comment by zramsay** [comment]
using jenkins helped me very easily find the bug in #792, which was in the p2p tests

**Comment by zramsay** [comment]
should we compress this and #837 into actionable items for the SRE team?

**Comment by zramsay** [comment]
see ^ above issue
