### ISSUE TITLE
RPC event subscription problems

### ISSUE THREAD

**Issue by mappum** [tendermint/tendermint#1099]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.15.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
gaia

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS High Sierra
- **Install tools**:
- **Others**:

**What happened**:
When subscribing to events via websocket RPC, I'm getting a single empty JSON object as a response, and no event responses.

**What you expected to happen**:
An error if I'm using the pubsub query incorrectly, otherwise I should see event data.

**How to reproduce it** (as minimally and precisely as possible):

main.js:
```js
let Tendermint = require('tendermint')
let rpc = Tendermint('ws://localhost:46657')

rpc.subscribe({ query: "tm.events.type = 'NewBlock'" }, (err, event) => {
  console.log(err, event)
})
```

```sh
$ npm install tendermint
$ node main.js
```

**Anything else do we need to know**:
I can't find docs for this, but a cursory reading of the code made me think this was the correct new way to subscribe.

**Comment by ebuchman** [comment]
Just tested and it works with `"tm.event = 'NewBlock'"`

Please re-open if you still having trouble.

**Comment by ebuchman** [comment]
https://github.com/tendermint/tendermint/issues/1100

**Comment by minhxtran** [comment]
If i am using curl to do this what would it look like?

**Comment by mappum** [comment]
@minhxtran You won't be able to do this through curl, since event subscription only works through Websocket and not plain HTTP.

You may want to look at the [js-tendermint](https://github.com/mappum/js-tendermint) repo.

**Comment by minhxtran** [comment]
> @minhxtran You won't be able to do this through curl, since event subscription only works through Websocket and not plain HTTP.
> 
> You may want to look at the [js-tendermint](https://github.com/mappum/js-tendermint) repo.

Thanks for the clarification.
