### ISSUE TITLE
where  is gossip code ?

### ISSUE THREAD

**Issue by wadelee1986** [tendermint/tendermint#1101]
where  is gossip code ?

is it p2p directory ?

**Comment by melekes** [comment]
p2p directory, yes. https://github.com/tendermint/tendermint/tree/master/p2p

for what's being gossiped, see reactors:

```
./consensus/reactor.go
./consensus/types/reactor.go
./evidence/reactor.go
./blockchain/reactor.go
./p2p/pex_reactor.go
./mempool/reactor.go
```

Check out our developer chat https://riot.im/app/#/room/#cosmos:matrix.org

**Comment by wadelee1986** [comment]
thanks a lot.

**Comment by wadelee1986** [comment]
where  is gossip's core logic in p2p directory ?

**Comment by melekes** [comment]
what do you mean by core logic?

**Comment by wadelee1986** [comment]
core logic:  gossip's message sync

I just found some listener、connection、peer、switch、reactor API code; can't find gossip's message sync in whole network
