### ISSUE TITLE
[Question] Tendermint ABCI Client x Tendermint RPC Client

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#1109]
Hi Guys,

Question: What is the difference between ABCI Client and RPC Client and when should I use one or another ?

Thank you!

**Comment by ebuchman** [comment]
The ABCI Client is effectively just for testing your ABCI app independent of Tendermint. 

You should never use the ABCI client if Tendermint is running. Tendermint plays the role of the ABCI client in a normal system by sending ABCI requests to the application. For normal operation, use the Tendermint RPC.

If you're testing your app without Tendermint running, you can use the ABCI cli - but it's really most useful when you're testing a new implementation of an ABCI server.

I'll close this, but feel free to re-open if you need.

**Comment by gianfelipe93** [comment]
Thank you @ebuchman
