### ISSUE TITLE
Missing binary downloads for tendermint 0.15

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1110]
Ahoi,

we still have no binary download links on the release page for "Leo".
Are they in the pipeline or did I miss a new download location?

Cheers!

**Comment by srmo** [comment]
ping

**Comment by adrianbrink** [comment]
https://github.com/tendermint/tendermint/releases/tag/v0.15.0

Done :-)

@srmo

**Comment by srmo** [comment]
Great! Thanks :)
