### ISSUE TITLE
Contamination of Apache license due to use of GPL reference  code 

### ISSUE THREAD

**Issue by johndpope** [tendermint/tendermint#1111]
@timtadh Tim Henderson created the original Merkle code which is license under GPL.
7032d3b84a33db3b4c7b8334ff37312e050b27e3

Unfortunately - all derivative works become GPL. 

Copyright 2013, Licensed under the GPL version 2. Please reach out to me directly if you require another licensing option. I am willing to work with you.

https://github.com/timtadh/data-structures

![screen shot 2018-01-17 at 11 07 56 am](https://user-images.githubusercontent.com/289994/35052906-bb4913aa-fb76-11e7-9cdb-058a1abae6d4.png)

fyi - @jaekwon

**Comment by johndpope** [comment]
related 
https://github.com/tendermint/tendermint/issues/239

https://github.com/tendermint/tendermint/issues/225

**Comment by jaekwon** [comment]
Thank you John!  We'll reach out to Tim or figure out another way to resolve this issue.

**Comment by timtadh** [comment]
fyi I replied to @jaekwon 's email. We will resolve it offline. Thanks @johndpope for finding this.
