### ISSUE TITLE
How can I change Tendermint version?

### ISSUE THREAD

**Issue by pavlovdog** [tendermint/tendermint#1113]
I've installed Tendermint with `go get github.com/tendermint/tendermint/cmd/tendermint`, so now I've `tendermint version 0.15.0`. For some reason, I need to get previous version `0.14.0` so I'm trying to checkout and reinstall Tendermint with `glide install && go install ./cmd/tendermint`. `glide install` works great, but there is an error with `go install ./cmd/tendermint`.

What am I doing wrong? Thanks in advance!

**Environment**:
- **OS** (e.g. from /etc/os-release):
```bash
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **GO version**:
```bash
$ go version
go1.9 linux/amd64
```

**How to reproduce it** (as minimally and precisely as possible):
```bash
$ cd $GOPATH/src/github.com/tendermint/tendermint
$ git tag -l # E.g. v0.14.0
$ git checkout tags/v0.14.0
$ glide install # Works great
$ go install ./cmd/tendermint
vendor/gopkg.in/go-playground/validator.v9/baked_in.go:4:2: cannot find package "context" in any of:
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/vendor/context (vendor tree)
	/usr/lib/go/src/context (from $GOROOT)
	/home/pavlovdog/go/src/context (from $GOPATH)
vendor/golang.org/x/net/http2/go17.go:13:2: cannot find package "net/http/httptrace" in any of:
	/home/pavlovdog/go/src/github.com/tendermint/tendermint/vendor/net/http/httptrace (vendor tree)
	/usr/lib/go/src/net/http/httptrace (from $GOROOT)
	/home/pavlovdog/go/src/net/http/httptrace (from $GOPATH)
```

**Comment by zramsay** [comment]
try `glide cc` (clear cache) before `glide install`

**Comment by pavlovdog** [comment]
@zramsay same errors

**Comment by zramsay** [comment]
try this script: https://gist.github.com/zramsay/4bca8907a97ad825c30cfdc6f72ba97b
on a fresh DO instance
(change `v0.15.0` to 14)

**Comment by pavlovdog** [comment]
@zramsay It didn't work for me :-1:. Also I found a solution (works for me, hope it helps someone else) - for some reason my approach didn't work with `v0.14.0`, but there are no troubles with `v0.13.0`.

**Comment by zramsay** [comment]
what didn't work with that script?
