### ISSUE TITLE
update the WIKI

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1114]
there's a lot of good, valuable information in there. Some is a little outdated; most is worth keeping

NOTE: this wiki is mostly deprecated and left for archival purposes. Please see the [documentation website](http://tendermint.readthedocs.io/en/master/) which is built from the [docs directory](https://github.com/tendermint/tendermint/tree/master/docs). Additional information about the specification can also be found in that directory.

**Comment by adrianbrink** [comment]
What do you think about retiring the wiki and turning it off in favour `docs/` and rtd.io ?
Personally I feel that most wikis are always out of date and there is no clear workflow on how to keep them up to date or work with external contributors.

**Comment by zramsay** [comment]
well we can leave it on, still a lot of things that link to it, and there's some really nice archival stuff. I was basically going to leave it untouched, add links to RTD, and mark as mostly deprecated

**Comment by zramsay** [comment]
cleaned it up and put:
```
NOTE: this wiki is mostly deprecated and left for archival purposes. Please see the [documentation website](http://tendermint.readthedocs.io/en/master/) which is built from the [docs directory](https://github.com/tendermint/tendermint/tree/master/docs). Additional information about the specification can also be found in that directory.
```
atop most pages
