### ISSUE TITLE
[p2p] question about mconnection

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1119]
https://github.com/tendermint/tendermint/blob/develop/p2p/connection.go#L143-L152

```
	var channelsIdx = map[byte]*Channel{}
	var channels = []*Channel{}

	for _, desc := range chDescs {
		channel := newChannel(mconn, *desc)
		channelsIdx[channel.desc.ID] = channel
		channels = append(channels, channel)
	}
	mconn.channels = channels
	mconn.channelsIdx = channelsIdx
```

Why we have both a map and a slice here? Do we need order here? Otherwise why we can't just iterate over `channelsIdx`?

**Comment by ebuchman** [comment]
Good point. I think we can probably just iterate over `channelsIdx` and don't actually need `channels`.

**Comment by ebuchman** [comment]
Let's keep both since it's minor and might as well preserve order and have the lookup
