### ISSUE TITLE
p2p: Check peers have certain channels

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1148]
Configure what minimal set of channels a peer must have for us to connect with them

Builds on https://github.com/tendermint/tendermint/pull/1049

**Comment by ebuchman** [comment]
We can make this a post launch issue if we change the code to require peers have all the same reactors as us (which should be fine for launch, but will need modification if/when we start adding/removing reactors)

**Comment by ebuchman** [comment]
Minimum reactors running for different nodes types:

- Validator - Consensus, Evidence, Mempool
- Sentry - Consensus, Evidence, Mempool
- Seed - Consensus, Evidence, PEX
- Full node - Consensus, Evidence, PEX, Mempool, Blockchain

So clearly, the absolute minimum is `Consensus, Evidence`, but I don't think we want to encourage turning off the mempool or blockchain either. So really the only thing to currently support is all reactors, or all reactors except PEX, which is what we already have.

So it seems like we can just make the minimum "everything but PEX" for now.

Alternatively, we might not even need to communicate the required reactors at all, since we all know they're required by protocol version, and only communicate the optional services, but it seems like there's no harm in explicitly communicating all of them, like we already do.

**Comment by ebuchman** [comment]
> how can we do that if we don't turn off the mempool reactor and we don't want to communicate the txs.

Yeh, we can probably add an option to the config to not run the mempool. But we're starting to consider whether it would be better to define "modes" of running Tendermint with particular configurations - like seed, sentry, validator, etc.

In the meantime, you can set `mempool.broadcast = false` and `mempool.size = <something small>`.

**Comment by guagualvcha** [comment]
Hi, for Sentry node, it is connected to trusted nodes(validators), for performance consideration, we would like it always run in fast sync mode and never active consensus reactor,  even apply blocks with no verification of apphash. Any ready solution or plan for this? thks

**Comment by ebuchman** [comment]
> even apply blocks with no verification of apphash

Not currently. Would you be open to writing an ADR for this, explaining the reasoning, the pros and cons, and how it might be implemented?
