### ISSUE TITLE
consensus: TestReactorValidatorSetChanges fails non-deterministically

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1149]
- https://circleci.com/gh/tendermint/tendermint/2972
- https://circleci.com/gh/tendermint/tendermint/2977

**Comment by jaekwon** [comment]
I captured all the goroutines' stack traces at time of error, after the following modifications:

* Change vendor/github.com/tendermint/abci/examples/dummy/ to use MemDB (to rule out GoLeveldb isseus)

Then I ran this specific test in a loop, 10 simultaneous runs at a time (to emulate slowness on circle).  Eventually I get the failure, and captured the stack traces:

https://gist.github.com/jaekwon/1b747bd7b2e163f4dfa827428afbdab5

So, one of those go-routines is maybe the culprit.

**Comment by jaekwon** [comment]
Ethan is working on fixing the pong/pong system to keep the following invariant: Receive() methods shall never block.  We'll then see if that makes the nondeterministic failures go away.

**Comment by ebuchman** [comment]
Is this with the pong block fix on develop?!

**Comment by jaekwon** [comment]
Develop still potentially blocks on ping.  Receive() must never block.

Also we might as well scan all of our Receive() implementations to ensure that none of them block.  We might find more bugs.

Checked:
- [ ] p2p/pex
- [ ] consensus
- [ ] blockchain
- [ ] mempool
- [ ] evidence

**Comment by melekes** [comment]
Great thread!

> Can you incorporate these changes/TODOs into your work with the memory leak too ?

sure thing

**Comment by melekes** [comment]
```
	// never closes. always safe to send on
	evpool.evidenceChan <- evidence
```
https://github.com/tendermint/tendermint/blob/develop/evidence/pool.go#L111

this can block and leak memory potentially.

**Comment by melekes** [comment]
Also, the fact that we check if consensus reactor is running and do not check the same thing in other reactors, seems odd.

```
	if !conR.IsRunning() {
		conR.Logger.Debug("Receive", "src", src, "chId", chID, "bytes", msgBytes)
		return
	}
```

**Comment by melekes** [comment]
```
			conR.conS.peerMsgQueue <- msgInfo{msg, src.ID()}
```

https://github.com/tendermint/tendermint/blob/develop/consensus/reactor.go#L249
we might block here for some time

**Comment by ebuchman** [comment]
Replaced by https://github.com/tendermint/tendermint/issues/1210
