### ISSUE TITLE
Which source for Crypto/RNGs is used on *nix systems?

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1150]
Is tendermint using dev/random for seeding in it's crypto functions? If yes, is this configurable? We found several issues in our Java App in VM environments where due to the blocking nature of dev/random the application showed erratic runtime behavior. 
Solution was to switch to dev/urandom, which is perfectly fine, especially after reading and understanding https://www.2uo.de/myths-about-urandom/

So that's where the concern is comming from. Please clarify :)

**Comment by odeke-em** [comment]
Hello @srmo, thank you for the question!

So in Go, we use crypto/rand.Reader whose rules of reading are
https://github.com/golang/go/blob/851e98f0ee59d3027ec82363aedc741ad14100f9/src/crypto/rand/rand.go#L11-L18
```go
// Reader is a global, shared instance of a cryptographically
// strong pseudo-random generator.
//
// On Linux, Reader uses getrandom(2) if available, /dev/urandom otherwise.
// On OpenBSD, Reader uses getentropy(2).
// On other Unix-like systems, Reader reads from /dev/urandom.
// On Windows systems, Reader uses the CryptGenRandom API.
var Reader io.Reader
```
So no, we draw from /dev/urandom and not /dev/random.

Hope this helps?

/cc @ebuchman @melekes @jaekwon

**Comment by srmo** [comment]
Sounds good. Thanks for the answer though I was confused by:
> // On Linux, Reader uses getrandom(2) if available, /dev/urandom otherwise.
But checking the man page revealed what you said. Still reads a bit odd in the go lib.
Thanks again!
