### ISSUE TITLE
TODO notes from spec

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1152]
https://github.com/tendermint/tendermint/blob/27ef3489a0018b1dfba0a5c97219c2cd4842afe6/docs/specification/new-spec/spec-notes.md
- Remove BlockID from Commit
- Actually validate the ValidatorsHash
- Move blockHeight=1 exception for LastCommit to ValidateBasic

Latest
- blockchain/state.md#ConsensusParams
- blockchain/state.md -> details of an implementation of `State` with persistence.
- reactors/block_sync/impl.md#TODO -> `How does the switch from bcR to conR happen? Does conR persist blocks to disk too? What is the interaction between the consensus and blockchain reactors?`

**Comment by ebuchman** [comment]
I think this can be closed.

Some of it is addressed in https://github.com/tendermint/tendermint/pull/2343.

Others have already been addressed or aren't that important or are captured elsewhere
