### ISSUE TITLE
p2p/config: options to require/not-require auth

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1157]
For public networks, we only want to work with peers that we can authenticate. 

On private networks, it's not a requirement, because folks might authenticate their connections via means external to Tendermint, like a VPN.

**Comment by melekes** [comment]
I would be in favor of enabling auth by default and providing the config option to disable it. Like `config.P2P.SkipAuthentication`.

**Comment by melekes** [comment]
```
type PeerConfig struct {
	AuthEnc bool `mapstructure:"auth_enc"` // authenticated encryption
```

So all we need to do here is to expose `AuthEnc` in P2P config?

**Comment by ebuchman** [comment]
No not quite. Currently we have an option to enable/disable the authenticated encryption. But we don't necessarily actually authenticate properly unless we check the pubkey against the node ID. 

So I think we need to:

- expose AuthEnc in the P2P config
- if AuthEnc is true, dialed peers must have a node ID in the address and it must match the persistent pubkey from the secret handshake

I guess on a private network, if you're using a VPN, you don't also need Tendermint to perform encryption

**Comment by srmo** [comment]
How would the blacklisting/whitelisting of peers work during runtime for this?

**Comment by melekes** [comment]
> How would the blacklisting/whitelisting of peers work during runtime for this?

blacklisting/whitelisting will continue to work as usually

**Comment by melekes** [comment]
> dialed peers must have a node ID in the address and it must match the persistent pubkey from the secret handshake

how somebody can figure ID out before secret handshake was established?

**Comment by melekes** [comment]
I think the fact that ID can change in between calls complicates the code

```
func (p *peer) ID() ID {
	return PubKeyToID(p.PubKey())
}
```

caller here does not know ^^^

**Comment by ebuchman** [comment]
> how somebody can figure ID out before a secret handshake was established? plus it is changing every time

It shouldn't change every time. We should now have a persistent `node_key.json` in the ~/.tendermint/config. Maybe we should update that to include the pubkey so we can easily see it , or add some command to simplify this (like we have `tendermint show_validator`).

**Comment by ebuchman** [comment]
> I think the fact that ID can change in between calls complicates the code

How can it change ?

**Comment by melekes** [comment]
> now have a persistent node_key.json in the ~/.tendermint/config

haven't seen this.. ok, I will search for it

> Maybe we should update that to include the pubkey so we can easily see it , or add some command to simplify this (like we have tendermint show_validator).

yeah, I did that already (`show_node_id` cmd)

**Comment by melekes** [comment]
> How can it change ?

```
	if !p.nodeInfo.PubKey.Empty() {
		return p.nodeInfo.PubKey
	} else if p.config.AuthEnc {
		return p.conn.(*tmconn.SecretConnection).RemotePubKey()
	}
```

because underlying PubKey changes. for example, auth_enc = true. we establised a connection, but have not performed a handshake yet (`p.conn.(*tmconn.SecretConnection).RemotePubKey()`). After handshake is done, pubkey - `p.nodeInfo.PubKey`

**Comment by greg-szabo** [comment]
Since this was moved to done, I'm closing it.
