### ISSUE TITLE
Problems in setting up a simple tendermint network with an ABCI example app

### ISSUE THREAD

**Issue by MarcoFavorito** [tendermint/tendermint#1159]
BUG REPORT

**Tendermint version** 0.15.0-381fe19
**ABCI app** `abci-cli` 0.9.0

**Environment**:
- **OS**

		NAME="Ubuntu"
		VERSION="16.04.3 LTS (Xenial Xerus)"
		ID=ubuntu
		ID_LIKE=debian
		PRETTY_NAME="Ubuntu 16.04.3 LTS"
		VERSION_ID="16.04"
		HOME_URL="http://www.ubuntu.com/"
		SUPPORT_URL="http://help.ubuntu.com/"
		BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
		VERSION_CODENAME=xenial
		UBUNTU_CODENAME=xenial

- **Install tools**: 
    - `make --version`: `GNU Make 4.1 Built for x86_64-pc-linux-gnu`
    - `go version`: `go1.9.2 linux/amd64`

**What happened**:
I set up a simple private local testnet with 4 tendermint nodes and the `dummy` ABCI app. At the first transaction committed, the nodes didn't agree on the hash and start to yield an error like the following:

        enterPrevote: ProposalBlock is invalid
        module=consensus height=4 round=0 err="Wrong Block.Header.AppHash.
        Expected FB7887E3848F26AD43C2AE773AEFA743E265B46D, got 21EEC33BF49E0F8FDFB333A5A63F1FA88E0229CB"

**What you expected to happen**:
I expect that the 4 nodes agree on the committed transaction. It seems that the transaction is proposed more than once (see below when testing with `abci-cli counter`)

**How to reproduce it** (as minimally and precisely as possible):
- make a new directory and enter in it;
- I use this script to set up the nodes:

		rm mytestnet -R
		IP=0.0.0.0
		AA=tcp://$IP
		SEEDS="$IP:46656,$IP:46666,$IP:46676,$IP:46686"
		echo $SEEDS
		tendermint --home .tendermint testnet mytestnet

		gnome-terminal --geometry=+0+0 -e "bash -c 'echo node_0;  tendermint node --home mytestnet/mach0/ --rpc.laddr="$AA:46657" --p2p.laddr="$AA:46656" --p2p.seeds=$SEEDS; exec $SHELL'"
		gnome-terminal --geometry=+0-0 -e "bash -c 'echo node_1;  tendermint node --home mytestnet/mach1/ --rpc.laddr="$AA:46667" --p2p.laddr="$AA:46666" --p2p.seeds=$SEEDS; exec $SHELL'"
		gnome-terminal --geometry=-0+0 -e "bash -c 'echo node_2;  tendermint node --home mytestnet/mach2/ --rpc.laddr="$AA:46677" --p2p.laddr="$AA:46676" --p2p.seeds=$SEEDS; exec $SHELL'"
		gnome-terminal --geometry=-0-0 -e "bash -c 'echo node_3;  tendermint node --home mytestnet/mach3/ --rpc.laddr="$AA:46687" --p2p.laddr="$AA:46686" --p2p.seeds=$SEEDS; exec $SHELL'"

- in another terminal, type `abci-cli dummy` or `abci-cli counter` 
- in another terminal, type  `curl -s 'localhst:46667/broadcast_tx_commit?tx="1"'`

**Anything else do we need to know**:
These are some screenshot documenting my error:
- just after launched the script:
![image](https://user-images.githubusercontent.com/9467617/35440577-47355b1e-02a0-11e8-8129-ef9dd24c44ea.png)

- just after launched the abci app `e.g. abci-cli dummy`
![image](https://user-images.githubusercontent.com/9467617/35441040-45664b02-02a2-11e8-8acf-418cf21b0adb.png)
![image](https://user-images.githubusercontent.com/9467617/35441050-4dd77400-02a2-11e8-9d0c-42c77f8f632d.png)

- after executing `curl -s 'localhost:46657/broadcast_tx_commit?tx="0"'`:
![image](https://user-images.githubusercontent.com/9467617/35441150-a923d916-02a2-11e8-94c0-a81fc358d4c4.png)
![image](https://user-images.githubusercontent.com/9467617/35441160-b0624b04-02a2-11e8-90cf-814f280592f7.png)

in the case of `abci-cli counter`, the output after the `broadcast_tx_commit` is the following:
![image](https://user-images.githubusercontent.com/9467617/35441268-1f7dfe0c-02a3-11e8-9812-57a589ffd658.png)
![image](https://user-images.githubusercontent.com/9467617/35441272-24ae5dae-02a3-11e8-838e-50ea98f31e1f.png)

What I've missed? There is some setup error somewhere?

**Comment by mdyring** [comment]
All tendermint processes seems to be talking to same app instance. Solved in chat..

**Comment by ltfschoen** [comment]
@MarcoFavorito Thanks for the inspiration. I created a Shell Script that launches multiple tabs for each of the Tendermint Testnet Nodes in this commit https://github.com/ltfschoen/tendermint-elixir/commit/2721de8847697e06ddaaaddc5c4810fb04cce506

**Comment by zramsay** [comment]
> solved in chat

closing

@mdyring was solution something that could be added to the docs?

**Comment by mdyring** [comment]
@zramsay It might be worth clarifying in docs (if it is not mentioned), that there should be a 1:1 relationship between tendermint and app processes.

Problem above was that multiple tendermint processes were talking to the same app process on the host machine.
