### ISSUE TITLE
Stream events to postgres for indexing

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1161]
Currently we use an in-process indexer over leveldb to index txs by tag (ie. so we can get tx history for a given account). It's design plan is here: https://github.com/tendermint/tendermint/pull/548

Instead, we should be streaming txs to an external process using postgresql to index everything.

There's some related discussion here: https://github.com/tendermint/tendermint/issues/674
and an early PR here: https://github.com/tendermint/tendermint/pull/548

I'm closing those in favor of a more focused issue and a future PR.

Note we should continue using leveldb as is for the blockchain and the state - we're just moving the extra tx indexing  (so we can support lots of light clients from a single node and do whatever queries on txs).

**Comment by srmo** [comment]
It would be really great if you can keep the internal indexer as backup.
We favor tendermint core especially because it is one self contained binary (+ abci server) without the need of additional services.

**Comment by ebuchman** [comment]
We will definitely keep the internal indexer as backup/default, so not to worry! This is just so we have the option to support much higher load as well :)

**Comment by jackzampolin** [comment]
I think @alexanderbez is working on this.

**Comment by ebuchman** [comment]
He is in https://github.com/alexanderbez/juno

Bez can you give some more colour here on if juno is or can be a full on replacement for tendermint's in-process indexing?

**Comment by marbar3778** [comment]
With the application now being able to control which txs to index we could allow applications to inject their own indexer when Tendermint is used as a library, the current indexer would be the default. The node operator would just specify if they want to index or not. This takes away some granular control.

**Comment by marbar3778** [comment]
Many block explorers do this already via subscribing to the websocket. I would propose we either close this or implement a simple out of protocol app that connects to the websocket and write to postgres.

**Comment by erikgrinaker** [comment]
>Many block explorers do this already via subscribing to the websocket.

I don't believe the websocket support resuming, so it will lose data if the client disconnects for whatever reason. I don't think the event infrastructure guarantees delivery either. If we want to use Websockets for this, we should add resume support and guaranteed delivery.

**Comment by marbar3778** [comment]
> I don't believe the websocket supports resuming, so it will lose data if the client disconnects for whatever reason. I don't think the event infrastructure guarantees delivery either. If we want to use Websockets for this, we should add resume support and guaranteed delivery.

Yup, we can add these instead of making a new indexer for in protocol.

**Comment by tomtau** [comment]
related tool that may potentially make use of this: https://github.com/crypto-com/chain-indexing

**Comment by marbar3778** [comment]
Its amazing to see old issues closed 😢
