### ISSUE TITLE
Unable to communicate with Elixir ABCI App

### ISSUE THREAD

**Issue by ltfschoen** [tendermint/tendermint#1166]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.15.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/ltfschoen/tendermint-elixir

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):
N/A

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 10.12.6
- **Install tools**: See Installation steps in Readme at the project repository https://github.com/ltfschoen/tendermint-elixir
- **Others**:
Elixir v1.6.0 `elixir --version`
Erlang v9.2 `erl --version`
Make 4.2.1 `make --version`

**What happened**:

I've been trying to build an Elixir ABCI Application using ABCI Server (Erlang). I've written a detailed Readme of setup and configuration steps here https://github.com/ltfschoen/tendermint-elixir. I'm able to Start/Stop the ABCI Server (Erlang), but the actual Elixir ABCI Application does not appear to be responding to calls to its `check_tx`, `deliver_tx` or `query` functions. After running the ABCI Server (Erlang) in Interactive Elixir (IEx) REPL with `{ok, _} = BlockchainTendermint.start_server` (function defined in https://github.com/ltfschoen/tendermint-elixir/blob/master/blockchain_tendermint/lib/blockchain_tendermint.ex), when I then run Integration Tests with `abci-cli test` or cURL requests like `curl -s 'localhost:46658/status'` it gives me error `Stopping abci.socketClient for error: EOF module=abci-client connection=query`. If I try making a call using ABCI-CLI with something like `abci-cli check_tx "0x00" --address tcp://localhost:46658 --abci "socket" --log_level "debug" --verbose`, then in the same Terminal window it displays:
```
I[01-27|11:19:05.527] Starting socketClient  module=abci-client impl=socketClient
E[01-27|11:19:05.541] Stopping abci.socketClient for error: EOF  module=abci-client
```

And in the IEx Bash Terminal it shows ABCI Server (Erlang) server logs as follows:
```
22:19:05.555 [error] GenServer #PID<0.164.0> terminating
** (FunctionClauseError) no function clause matching in :abci.e_msg_ResponseCheckTx/3
    (abci_server) src/abci.erl:505: :abci.e_msg_ResponseCheckTx({:reply, "Initialised Chain"}, "", :undefined)
    (abci_server) src/abci.erl:1414: :abci.e_mfield_Response_check_tx/3
    (abci_server) src/abci_server.erl:126: :abci_server.send_response/2
    (abci_server) src/abci_server.erl:119: :abci_server.handle_requests/2
    (abci_server) src/abci_server.erl:83: :abci_server.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.4966>, <<1, 5, 74, 3, 10, 1, 0, 1, 2, 26, 0>>}
State: {:state, #Port<0.4966>, :ranch_tcp, "", BlockchainTendermint}
 
22:19:05.558 [error] Ranch listener BlockchainTendermint had connection process started with :abci_server:start_link/4 at #PID<0.164.0> exit with reason: {:function_clause, [{:abci, :e_msg_ResponseCheckTx, [{:reply, "Initialised Chain"}, "", :undefined], [file: 'src/abci.erl', line: 505]}, {:abci, :e_mfield_Response_check_tx, 3, [file: 'src/abci.erl', line: 1414]}, {:abci_server, :send_response, 2, [file: 'src/abci_server.erl', line: 126]}, {:abci_server, :handle_requests, 2, [file: 'src/abci_server.erl', line: 119]}, {:abci_server, :handle_info, 2, [file: 'src/abci_server.erl', line: 83]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
```

I've created a Shell Script https://github.com/ltfschoen/tendermint-elixir/blob/master/launch_testnet_nodes.sh that runs Multiple Tendermint Testnet Nodes (4 of them) on different ports in separate Bash Terminal tabs, but upon loading they all display `E[01-27|11:27:18.050] Stopping abci.socketClient for error: EOF module=abci-client connection=query`

**What you expected to happen**:

I expect to be able to communicate with `check_tx`, `query` or `deliver_tx` functions defined in the Elixir ABCI Application and seek assistance in that regard.

**How to reproduce it** (as minimally and precisely as possible):

Follow the setup instructions in the Readme of my repository at https://github.com/ltfschoen/tendermint-elixir

**Comment by ebuchman** [comment]
Some notes:

- You should only run your ABCI app with one client: either Tendermint or the abci-cli, never both.
- `curl -s 'localhost:46658/status'` should not work. `/status` is an endpoint on the Tendermint RPC on default port 46657, but there's no reason to be exposing HTTP on your ABCI application server port

If you run your ABCI app without Tendermint, does `abci-cli echo "hello"` work ?  

Are you using the latest version of the `abci-cli` (ie. 0.9.0)? Make sure to pull the latest master in that repo and run `make get_vendor_deps && make install`

Also make sure that you're using the most recent version of the protobuf file when building your elixir app!

**Comment by ltfschoen** [comment]
@ebuchman Thank you for your feedback. Yes without making any changes to my code, after I run `iex -S mix` to start Interactive Elixir (REPL), then compiling my Elixir ABCI Application with `c("lib/blockchain_tendermint.ex")`, then starting the ABCI Server (with Erlang bindings) by calling `BlockchainTendermint.start_server`, and then opening a new Bash Terminal window and running `abci-cli echo "hello"`, I get the following response:
```bash
$ abci-cli echo "hello"
I[02-01|05:45:24.829] Starting socketClient                        module=abci-client impl=socketClient
-> code: OK
-> data: hello
-> data.hex: 0x68656C6C6F
```

Yes, I'm using the latest ABCI-CLI version, it returns:
```bash
$ abci-cli version
0.9.0
```

I will try reinstalling ABCI-CLI and Protocol Buffers https://github.com/tendermint/abci/blob/master/README.md#install

**Comment by ebuchman** [comment]
That's great news! It means at least the basics are working.

What happens when you do the same with `abci-cli check_tx 0xabcd` ?

**Comment by zramsay** [comment]
@ltfschoen sounds like you got it working. re-open (and feel free to answer @ebuchman question) if you encounter further issues.
