### ISSUE TITLE
few clarifications

### ISSUE THREAD

**Issue by silviucpp** [tendermint/tendermint#1170]
Hello,

1. Using ABCI over ABCI-socket it's pretty ok but can cause issues with some antivirus's that might block the connection between the tendermint and the application. In order to limit this problem you need to sign the apps with a valid certificate that imply additional costs. 

I'm not a go developer but I saw that's fairly easy in go to export functions and to build as shared library that can be used in many languages that supports c++ modules (java, erlang, objective c, etc). Is this feature supported in tendermint ? I didn't saw any //export and also no documentation regarding this.

2. What are the limitations a node has while it's using fast-sync ? can you query for old transactions, blocks and so on ? how you can detect if a node it's up to date in ABCI ? I don't find the documentation too clear in this direction

3. What's the proper seeding mechanism peoples needs to use in production when they are using tendermint. In bitcoin fork coins you can use the https://github.com/sipa/bitcoin-seeder

4. There is any way to get the validator public ip from a node ?

Kind regards,
Silviu

**Comment by ebuchman** [comment]
>  In order to limit this problem you need to sign the apps with a valid certificate that imply additional costs.

Yeh wow. We'll probably get to this one day...

> fairly easy in go to export functions and to build as shared library that can be used in many languages

Can you clarify what you're trying to do ? You want to use Tendermint in-process from another language besides Go? Currently that's not supported, but maybe one day. 

> What are the limitations a node has while it's using fast-sync

You can query for everything. Only limitation is that if you try to do `/broadcast_tx_commit` it will hang until the node is fully caught up, and might timeout if it takes too long. 

>  how you can detect if a node it's up to date in ABCI 

You can't. Only way is to check the `syncing` field in the `localhost:46657/status`.

> What's the proper seeding mechanism peoples needs to use in production when they are using tendermint

We just added a "seed mode" to the Peer Exchange Reactor. It's on develop, and will be released in 0.16. So you can run your Tendermint node in Seed Mode and use that as a seed so new peers can find other peers.

> There is any way to get the validator public ip from a node ?

Not really. Node try to self report their own IPs. But there's nothing in the software that ties IP addresses to validator pubkeys.

I'll close this, but feel free to open new issues for individual points if you feel something needs to be addressed.

Thanks!

**Comment by silviucpp** [comment]
@ebuchman  thanks a lot for your answers I'll try to come up with some other questions which are not clear in docs soon
