### ISSUE TITLE
Make Tendermint Core a compatible Plasma client

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1174]
Tendermint Core is an ideal Plasma client. It allows for arbitrary/complex state instead of just UTXO set style chains.

Tendermint Core needs to be able to receive an external validator set. So one solution could be that Tendermint Core can be configured to listen on a socket for the latest state of the validator set. A service can then listen to an Ethereum staking contract and push those changes into Tendermint Core. If Ethereum ever goes split-brain Tendermint will just hold. The service has to implement some finality threshold. The nice thing with this approach is that it does not require validator set changes to go through consensus and that the validator set is determined completely outside of the application.

@zmanian @ethanfrey

**Comment by zmanian** [comment]
Here is my main reasoning when getting a validator set via query to a contract is okay. 

If the views of the validators are inconsistent by more the 33% of voting power, than the system should just top until view consistency is achieved.

OTOH, validation of validator changes via geth light client is strong from a liveness point of view.

**Comment by adrianbrink** [comment]
What do you mean by `via query`?

**Comment by zmanian** [comment]
I mean polling the contract ABI for queries of the current state of the consensus contract during every tendermint consensus round

**Comment by milosevic** [comment]
I am not sure we can allow validator set changes during the height/round execution.

**Comment by milosevic** [comment]
It's actually between heights. We can safely only change validator set between heights. So at the end of the block, ABCI app would need to update the validator state based on the contract state, and return it to Tendermint. We need to ensure that each validator will receive the same validator list from the contract. If I am not wrong changes to the validator set in staking contract would also need to be somehow synchronised by the ABCI app, i.e., it would not be possible to withdraw bonded tokens freely. Is this true, or I am misunderstanding something?

**Comment by zmanian** [comment]
The unbonding time would be enforced on the Etherum chain

**Comment by milosevic** [comment]
In the Hub staking module, validator set changes are atomic, i.e., they are happening when the block is committed and they are based on the content of the block. During the height h1 we have the validator set V1, and then when the block for the height h1 is committed, we transition from validator set V1 to validator set V2 by applying some deterministic function on the block for h1. In case of having staking module as an Ethereum smart contract, we need to enforce the same invariants, i.e., the validator set should consistently change upon Tendermint block commit. So one idea would be to have smart contract only queues staking transactions on Ethereum chain (without applying it to the staking state) until ABCI app post transaction on Ethereum chain that the block is committed. This transaction would then trigger executing all buffered transactions and apply them to the staking state that is then returned to the ABCI app and then to Tendermint. Problem with this approach is the fact that Tendermint can't proceed before this transaction is finalised on Ethereum chain. But this can be made more performant by doing this process not on every Tendermint block commit, but after every K block. @zmanian Is this design you had in mind?

**Comment by adrianbrink** [comment]
Tendermint Core should not block on Ethereum. 

Currently, we transition from V1 to V2 based on the contents of the block at H1.

I would propose that instead of transitioning based on the contents of H1, Tendermint Core requests validator updates from an external service. So when H1 is committed, TMC requests the new validator set. It doesn't care where that comes from, and if it isn't consistent for >2/3 of them then the chain halts the next block.

Example:
* TMC commits H1 with VS1.
* TMC requests VS2.
* TMC receives VS2.
* TMC commits H2 with VS2.

The service that TMC connects to needs to ensure that they all agree on the next validator set. It can cause split-brain. For example, it could be a service that listens to Ethereum and assumes that only block+100 is final.

**Comment by milosevic** [comment]
There are some properties that staking smart contact need to satisfy so security of Tendermint chain holds. During the execution of height H, the bonded tokens of the current validator set do not change. This is important as voting power of the validators is defined by the bonded tokens, and voting power of validator cannot be changed during the consensus instance execution. They are allowed to change only after Tendermint commits block height H and asks for validator set for height H + 1. Furthermore, the returned validator set should be the same at all validators, otherwise security properties of Tendermint does not hold.

**Comment by adrianbrink** [comment]
Awesome. I think we agree.

In my mind the best thing would be if Tendermint Core just asks for a validator set in a way that is safe with consensus. If the service it asks is faulty (every validator receives a different validator set) we just halt.

The VS-service has to ensure that the validator set is correct.

**Comment by milosevic** [comment]
I think it's a bit more tricky. If VS-service returns different validator set to different validators, we can have fork. For example, we have 10 validators p1 to p10, and VS-Service returns to p1 to p5 (p1, p2, p3, p4 and p5) and to p6 to p10 (p6, p7, p8, p9 and p10). In that case the two group of validators will create two forks and from Tendermint point of view there is nothing wrong. My feeling is that validator need to run Ethereum full node and to implement locally VS-service based on the state of Ethereum chain.

**Comment by adrianbrink** [comment]
I like your last point (full Ethereum node). How would that integrate with Tendermint Core?

**Comment by ebuchman** [comment]
> The nice thing with this approach is that it does not require validator set changes to go through consensus and that the validator set is determined completely outside of the application.

Sounds like a recipe for breaking all consensus guarantees. 

Can you clarify why we want some external process to be able to change the validator set and how you think this can be achieved without this consensus critical data passing through consensus ?

**Comment by ebuchman** [comment]
If we want validator updates to come from eg. another chain, we can have the app process the latest state of that chain (ie. be a light client of that chain) and trigger the validator sets itself. I'm not seeing a need to change anything in Tendermint. 

I believe this issue has come up before and we had the same conclusion. What am I missing ?

**Comment by adrianbrink** [comment]
It can be from a discussion I had with @zmanian around avoiding going through consensus to pass consensus changes and instead rely on a completely external source.

The more I am thinking about it though, the harder it seems and you are right that it sounds like the perfect recipe to break all consensus guarantees. I think the safest way is to handle this in the application and reuse the relaying process from `peggy` in order to inject the latest Ethereum state into the application.

The relayer component runs a full Ethereum node and witnesses the state of the staking contract. After a finality threshold, it sends a transaction, signed by a key that is attributable to a validator (every validator runs their own relayer component with a unique key). We accumulate votes for the same event inside the application and once >2/3 of the valset have signed off on changing the valset, we process it in the next block.

**Comment by ebuchman** [comment]
Closing this. If there's something concrete we need to add to Tendermint in the short term, please open a new one
