### ISSUE TITLE
Testnet Errors

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1175]
`46.101.158.43 is on Gaia-2` This IP does not appear in the config.toml file that we used.

`104.155.152.81 is on Gaia-3000` This IP does not appear in the config.toml file that we used.

`module=p2p address=198.211.124.237:46656 err="Error during handshake/read: read tcp 46.101.201.137:49210->198.211.124.237:46656: read: connection reset by peer"`
What does this mean?

`module=p2p address=165.227.137.156:46656 err="Error creating peer: dial tcp 165.227.137.156:46656: getsockopt: connection refused"` 
This IP isn't in the config.toml file.

**Comment by MikeSofaer** [comment]
E[01-30|17:43:48.535] Failed to dial peer                          module=p2p address=165.227.246.236:46657 err="Error creating peer: read tcp 172.31.28.156:41972->165.227.246.236:46657: i/o timeout"
E[01-30|17:43:58.412] Failed to dial peer                          module=p2p address=138.197.145.116:46656 err="Error creating peer: dial tcp 138.197.145.116:46656: getsockopt: connection refused"
E[01-30|17:43:58.522] Failed to dial peer                          module=p2p address=45.77.53.208:46656 err="Error creating peer: dial tcp 45.77.53.208:46656: getsockopt: connection refused"
E[01-30|17:43:58.530] Failed to dial peer                          module=p2p address=165.227.137.156:46656 err="Error creating peer: dial tcp 165.227.137.156:46656: getsockopt: connection refused"
E[01-30|17:43:59.253] Failed to add peer                           module=p2p address=67.207.78.91:46656 err="Duplicate peer"
E[01-30|17:44:01.336] Failed to dial peer                          module=p2p address=138.197.185.72:46656 err="Error creating peer: dial tcp 138.197.185.72:46656: i/o timeout"
E[01-30|17:44:01.337] Failed to dial peer                          module=p2p address=165.227.224.27:46656 err="Error creating peer: dial tcp 165.227.224.27:46656: i/o timeout"
E[01-30|17:44:01.337] Failed to dial peer                          module=p2p address=188.226.174.245:46656 err="Error creating peer: dial tcp 188.226.174.245:46656: i/o timeout"
E[01-30|17:44:28.413] Failed to dial peer                          module=p2p address=138.197.145.116:46657 err="Error creating peer: dial tcp 138.197.145.116:46657: getsockopt: connection refused"
E[01-30|17:44:28.539] Failed to dial peer                          module=p2p address=45.77.53.208:46656 err="Error creating peer: dial tcp 45.77.53.208:46656: getsockopt: connection refused"
E[01-30|17:44:31.259] Failed to dial peer                          module=p2p address=96.43.232.202:46656 err="Error creating peer: dial tcp 96.43.232.202:46656: getsockopt: no route to host"
E[01-30|17:44:31.336] Failed to dial peer                          module=p2p address=34.217.69.240:46656 err="Error creating peer: dial tcp 34.217.69.240:46656: i/o timeout"
E[01-30|17:44:31.336] Failed to dial peer                          module=p2p address=188.226.174.245:46656 err="Error creating peer: dial tcp 188.226.174.245:46656: i/o timeout"
E[01-30|17:44:31.337] Failed to dial peer                          module=p2p address=138.197.185.72:46656 err="Error creating peer: dial tcp 138.197.185.72:46656: i/o timeout"

**Comment by MikeSofaer** [comment]
E[01-30|17:45:29.301] Failed to add peer                           module=p2p address=46.101.158.43:46656 err="Peer is on a different network. Got gaia-2, expected gaia-3001"

**Comment by adrianbrink** [comment]
Generally the IPs in the error messages I get don't contain the IP addresses that are used in the config.toml file.

**Comment by zramsay** [comment]
`138.197.145.116` is me; feel free to remove

**Comment by adrianbrink** [comment]
Ahh, interesting. So @ebuchman illuminated the errors.

Some validators didn't switch IP addresses between running testnets. So the old validators from gaia-2 tried to connect to the new testnet and then started gossiping the wrong IPs into it.
