### ISSUE TITLE
Semantics of "currate too low" error messages and what to do

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1177]
We sometimes see "curRate too low" error messages in the logs, especially during resyncing of a node.
What's the semantic of that? Why is it an error? What to do about it and how can we reason about the state of such a node or the chain at all?
This goes hand in hand with Connection closed for peer errors where it is not clear if such connections have been recovered in a later stage.

Edit: we are still on 0.12 but will see what happens when we manage to migrate to current 0.15

From riot:

> could you create an issue on Github if you can't find any info on curRate
> we should probably output curRate, not only "curRate is low"
> 
> I think it means connection is slow between this node and some peer
> "rate" comes from https://github.com/tendermint/tmlibs/tree/master/flowrate
> curRate - speed with which we get blocks from peer
> msg is badly written anyway

**Comment by ebuchman** [comment]
Basically we set a minimum recv rate in the fast sync to ensure we're receiving blocks from a peer fast enough. It's currently hardcoded to 10kB/s. Perhaps that's too high. If a peer is not sending us data at at least that rate, we consider them to have timedout and we disconnect. 

We should make this more robust and improve the message.

Thanks.

**Comment by melekes** [comment]
Let's take a really old DSL modem - with upload speed 128 Kbps ~ 15 KB/s. https://www.att.net/speedtiers

45ms or less for regional round trips within North America
90ms or less for transatlantic round trips between London and New York.

so (if we assume the above stats from att was measured in US, which seems to be the case), the worst should be transatlantic upload approximately at half speed - 7.5 KB/s.

**Comment by srmo** [comment]
That’s what bothers me. We might see this in local vm network setups or internet/cloud  setups where it is unlikely to hit such low speeds. So there’s an urge to think there’s more going an besides a slow connection. 

The clarification mentioned by ebuchman seems to go in the right direction. A quick bulletpoint list on what an ordinary user could do to analyse/find the root cause would be very helpful (like: measure the connection between peers using xyz with protocol TCP and ...)

**Comment by melekes** [comment]
I changed the message to show current rate (as well as min), so you will be able to see it.

**Comment by melekes** [comment]
To measure conn speed use [iperf](https://github.com/esnet/iperf) https://www.cyberciti.biz/faq/how-to-test-the-network-speedthroughput-between-two-linux-servers/ or netcat (nc).

**Comment by srmo** [comment]
Ok, thank you for the pointer. 
We’ll probably do some testruna

**Comment by srmo** [comment]
Ok, thank you for the pointer.
Best would be to have a parallel measurement between nodes and see if curRate is true :)

**Comment by ebuchman** [comment]
I believe https://github.com/tendermint/tendermint/pull/1194/files addresses this. Looks like a much better error message - thanks folks 👯
