### ISSUE TITLE
split immutable and mutable parts of priv_validator.json

### ISSUE THREAD

**Issue by nickray** [tendermint/tendermint#1181]
**FEATURE REQUEST**

Hi guys,

it's a production problem to mix the address/pubkey/privkey of the validator with the `last_*` state in one file. For instance, in a Kubernetes setup the immutable part should be a Secret, and the mutable state part should be backed up.

It would also be good to
* move config.toml, genesis.json and immutable part of priv_validator.json in a config/ subdirectory
* move addrbook.json and mutable part of priv_validator.json into data/ subdirectory
* add `--config` and `--data` flags to override `--home` in `tendermint node` and `gaia node start`

Can we get this done (in spirit)?

**Comment by zramsay** [comment]
- most of bullet point 1 was done in #792 (not released yet, still on develop)
- refactor of `priv_validator.json` (move mutable part in data, improve security (e.g., not plaintext) is coming (edited title of this issue for that)
- bullet point 3 is #928

**Comment by ebuchman** [comment]
Thanks for this important issue. As mentioned some of the points have already been addressed on develop.

Have you seen the ADR for the new priv validator? https://github.com/tendermint/tendermint/blob/priv_val/docs/architecture/adr-008-priv-validator.md

Perhaps you'd like to comment on that. The plan is for "secure" use of a validator to happen out of process, utilizing a HSM. In any case, even if using an in-memory/on-disk key, it will be the responsibility of that separate process to ensure separation between immutable/mutable data here.  For this reason the key will continued to be lumped in with the last_* info in one file for the insecure mode. Does that sound ok ?

**Comment by nickray** [comment]
I hadn't! That's great to have an explicit interface.

Regarding this issue, I don't see what's preventing you from changing the supported `PrivValidatorUnencrypted` to use two files though? With the imutable part ending up in --config, the mutable part up in --data (in terms of [issue 928]https://github.com/tendermint/tendermint/issues/928)).

Is ther an ETA for ADR 008?

**Comment by ebuchman** [comment]
Yeh that's not a bad idea. Let's do it. 

ETA is after next release. 0.16 will hopefully be out this week, and then its all about the validator :)

**Comment by ebuchman** [comment]
This is done now :)

**Comment by xla** [comment]
![yeah](https://media.giphy.com/media/9EVZWCxypKQxi/giphy.gif)
