### ISSUE TITLE
refactor `lite` so iavl dependency is outside tendermint core

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1183]
`lite` shouldn't depend on `iavl`. It should *only* be concerned with Tendermint related data structures (ie. block headers, votes, validators, etc.).

Ie. see commented out code https://github.com/tendermint/tendermint/blob/develop/lite/proxy/query.go#L86

**Comment by ethanfrey** [comment]
Fair enough, I guess it also means to move the proxy into cosmos-sdk.
Or produce a generic proof format that tendermint can understand

**Comment by ebuchman** [comment]
Ideally we keep the proxy in tendermint and just remove the iavl dependent code. 

Folks can then run `tendermint lite` and get everything they need but just handle the app state proof deserialization and verification themselves (since all the validator/tendermitn stuff is already handled). Possibly also the Go API in lite/query could accept a function that does it all for you - at least Tendermint still wouldnt depend on iavl.

**Comment by ebuchman** [comment]
Note proxy has low coverage https://github.com/tendermint/tendermint/issues/1017

**Comment by ebuchman** [comment]
Also see https://github.com/tendermint/tendermint/issues/970

**Comment by ebuchman** [comment]
See conversation in https://github.com/tendermint/tendermint/pull/1213.

That PR just removed the `tendermint lite` command and the `lite/proxy` package completely. That's not what we want. What we want is to refactor the `lite/proxy` package a bit to remove the iavl dependency. It can be injected by consumers, but it's useful to have the general purpose lite client setup in Tendermint. Apps can determine how the application state proofs are deserialized/verified themselves.

**Comment by xla** [comment]
@jaekwon What's the state of this after the lite refactor? Do we want iavl in tendermint or cosmos?

**Comment by ebuchman** [comment]
Looks like we have this as is. Tendermint does not depend on IAVL.
