### ISSUE TITLE
Upgrade go-crypto and go-wire to develop

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1186]

**Comment by ebuchman** [comment]
Ok, this can happen at a more leisurely pace now that the new API was merged to master on go-wire (https://github.com/tendermint/go-wire/blob/master/CHANGELOG.md#073-mar-2-2018). 

See a first take at some updates in https://github.com/tendermint/tendermint/pull/1265.

We can keep trying to cherry-pick from https://github.com/tendermint/tendermint/pull/1221 but I went pretty far with that before the overhead became too great so most likely we just pick up continuing to make changes like `BinaryBytes -> MarshalBinary` as we come by them or as we feel like it.

Once we're using the new API exclusively, it will be a much smaller and more manageable PR to actually upgrade for the new go-wire format (and type registrations)

**Comment by ebuchman** [comment]
stale
