### ISSUE TITLE
p2p/conn/: prevent abuse from peer sending too much pings

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1190]
https://github.com/tendermint/tendermint/blob/develop/p2p/conn/connection.go#L448

```go
		case packetTypePing:
			// TODO: prevent abuse, as they cause flush()'s.
			c.Logger.Debug("Receive Ping")
			select {
			case c.pong <- struct{}{}:
			case <-c.quit:
				break FOR_LOOP
			}
```

**Comment by ebuchman** [comment]
Chatting with @xla we wondered why even bother with ping/pong in the first place if we're already assuming TCP and TCP can do this for us ?

**Comment by xla** [comment]
Unfortunately tcp keepalive is not part of the standard and can not be relied on.

**Comment by xla** [comment]
@melekes We follow-up in #1744 and it's unclear if a large amount of flushes causes any issues.

**Comment by melekes** [comment]
Ok, cool
