### ISSUE TITLE
evidence: Update end comment needs clarification on mutex locking

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#1192]
I was just auditing the code when I noticed this comment https://github.com/tendermint/tendermint/blob/381fe19335ba8825e04d1d0fefa5cac709bb7178/blockchain/pool.go#L82-L83

which says "NOTE: shouldn't need the mutex"

However, we have a mutex Locking the entire routine and only unlocking on deferral
https://github.com/tendermint/tendermint/blob/381fe19335ba8825e04d1d0fefa5cac709bb7178/evidence/pool.go#L72-L73

Did we mean to say that at that point, the EvidencePool should ALWAYS be running non-concurrently? If so, this is a data point that we might need to consider in testing. If not, let's remove that comment. If we are going to have other people auditing the code, the last thing we want is for anyone to waste time cooking up an attack only to realize that it was an ambigious/unintended comment.

**Comment by ebuchman** [comment]
`evidence` package still needs some love: https://github.com/tendermint/tendermint/issues/1012

**Comment by ebuchman** [comment]
Thanks, removed in https://github.com/tendermint/tendermint/pull/1628
