### ISSUE TITLE
evidence: pool#AddEvidence calls LoadValidators twice

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1195]
1. https://github.com/tendermint/tendermint/blob/develop/evidence/pool.go#L98
2. https://github.com/tendermint/tendermint/blob/develop/evidence/pool.go#L92 -> https://github.com/tendermint/tendermint/blob/develop/state/validation.go#L104

**Comment by marbar3778** [comment]
@cmwaters @melekes is this still applicable? I see we are loading validators twice still. Once on the [creation of the pool](https://github.com/tendermint/tendermint/blob/58113e31aefd6275047549705d245605747a9287/evidence/pool.go#L758-L758) & another time when we [add evidence](https://github.com/tendermint/tendermint/blob/58113e31aefd6275047549705d245605747a9287/evidence/pool.go#L166-L166).  

we don't have permalinks for the above links so I cant see where we were calling it before

**Comment by cmwaters** [comment]
We are still doing this twice as far as I can see and there might be some redundancy there - don't know how significant it is though. I will look into it tomorrow

**Comment by melekes** [comment]
no longer the case
