### ISSUE TITLE
Testnet coins

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#120]
If you want to try the testnet, you'll need some coins.  This is how developers get coins.

Rules: 
- You must be an active GitHub developer with open source activity.
- You must post a single comment here.  No lengthy discussions.
- Only the first 50 commenters will receive testnet coins.
- There will be 21M total testnet coins.  The first 25 will receive 10K.  The next 25 will receive 8K.
- You must not exchange testnet coins for monetary value.

Bonus:
- Code a better method of invitation so we stop using GitHub.

If you have any questions, email me at `jae@tendermint.com`, or post another issue.  Email me for a Tendermint slack invitation, where most of the discussions happen.

```
go get -u github.com/tendermint/tendermint/cmd/tendermint
tendermint gen_account
```

Or, download the binaries from https://github.com/tendermint/tendermint/releases/tag/0.1
Then, paste the address and pubkey here, e.g. 

```
address: 415C4BEFE3B293BD46D0ED67D145316A4EDB5D4B
pub_key: [1,"4A4A870EE4122CFC07D3124C03C1C0B6018DC780CEC22C65307E9C8F0E50AB9E"]
```

**Comment by jaekwon** [comment]
address: 9FCBA7F840A0BFEBBE755E853C9947270A912D04
pub_key: [1,"8E41940E7DB59A470E09BEA6F51895B1C590569E49499298965EE86ED8570B45"]
referrer: @jaekwon

**Comment by jtremback** [comment]
Why only the first 50?

**Comment by devrandom** [comment]
```json
{
"address":"F171824590D69386F709E7B6704B369C5A370D60",
"pub_key":[1,"0D7C1688A108DD30C1BDF6FF011CE104E420D54981F8E7BBFF71565737D8BCD8"]
}
```

**Comment by zmanian** [comment]
"address":"56EFE746A13D9A6054AC89C3E2A361C2DB8B9EAE","pub_key":[1,"FCC4F45B621E23BBF8A1577883618C56995BB8DA36E3F6D0C6A4F13FBC029C5F"]

**Comment by PaulCapestany** [comment]
```json
{
"address":"7C2E032D8407EDF66A04D88CF0E1D9B15D98AE2D",
"pub_key":[1,"B138E682395C81B1094E8509A09DF0B08702A0D71A9DAD587CA8EC7C5197F845"]
}
```

**Comment by rguikers** [comment]
{
  "address": "636EF5823E082AD66EBC203FD4DFB1031F0C61CA",
  "pub_key": [1,"77D84C7044460A0A7098B4E4BEB8AE36026151928A33A64FFF777D3BDC544B9A"]
}

**Comment by nwams** [comment]
{
"address":"9008419E6351360A59B124E707E4CA2A5BFB9BE6","pub_key":[1,"581B37441B5EB28A9EC24B0925B2FF2F72A600AA275BF24BCA7D35C310BDBF3A"],"priv_key":[1,"D4FEA753748A0D6CDC956D3486A38BD570FD227706876136207C41C50A1D042B581B37441B5EB28A9EC24B0925B2FF2F72A600AA275BF24BCA7D35C310BDBF3A"]
}

**Comment by nwams** [comment]
{
"address":"9008419E6351360A59B124E707E4CA2A5BFB9BE6",
"pub_key":[1,"581B37441B5EB28A9EC24B0925B2FF2F72A600AA275BF24BCA7D35C310BDBF3A"]
}

**Comment by jsp282** [comment]
{"address":"C78F48919B8A4030AD3E5ED643F8D2302E41953D","pub_key":[1,"B7C79A838759B35D89EFC9B7A2E4AABE3BA0EFAC9889344761BC62A2988C9077"]}

**Comment by techgangboss** [comment]
{
"address":"5290AC90CE2422DDC3F91F6A246F7E3C542EA51A",
"pub_key":[1,"8E3A98177D65A0B0C59446ED666826284DBFA518310130FA72EC2A50AC6A3D1F"]
}

**Comment by alfwatt** [comment]
{
"address":"73E5662FA08281DD669B5F01948233896CB12320","pub_key":[1,"66F89E8A7216DECDD2D5C834273C32AE6C363E20D8573A2895C71AE9435C7DED"]
}

**Comment by bloo** [comment]
```
address: 342D6664A0D70B1FAFBD864317932D1F1650EAE5
pub_key: [1,"9E6C6B584A94727AA72AD6A5DFD71FDDDC6DB3291CF86C2F61384FAC9F8DE005"]
```

**Comment by ebuchman** [comment]
```
{
"address":"964B1493BBE3312278B7DEB94C39149F7899A345",
"pub_key":[1,"F6C79CF0CB9D66B677988BCB9B8EADD9A091CD465A60542A8AB85476256DBA92"]
}
```

**Comment by adrianbrink** [comment]
This should probably be closed until there is a new public testnet.
