### ISSUE TITLE
Fixes for p2p memory leak and pong 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1205]
See comments from @jaekwon in https://github.com/tendermint/tendermint/pull/1173/files and https://github.com/tendermint/tendermint/pull/1095/files

**Comment by melekes** [comment]
1. https://github.com/tendermint/tmlibs/pull/150
2. https://github.com/tendermint/abci/pull/191

**Comment by ebuchman** [comment]
Comments on https://github.com/tendermint/tendermint/pull/1173/files are addressed in https://github.com/tendermint/tendermint/pull/1209

Some of https://github.com/tendermint/tendermint/pull/1095/files is addressed in https://github.com/tendermint/tendermint/pull/1209, but see ongoing discussion in https://github.com/tendermint/tendermint/pull/1095/files
