### ISSUE TITLE
Make sure Receive never blocks

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1210]
Following up from https://github.com/tendermint/tendermint/issues/1149

See anton's comments there re:

- Evidence reactor 
- Consensus reactor use of IsRunning
- Consensus reactor sending on peerMsgQueue

**Comment by greg-szabo** [comment]
I think this error in test runs belong here:
https://ci.interblock.io/view/08%20-%20CI/job/02.Test.Unit/36/console

**Comment by ebuchman** [comment]
Hmm these links don't work for me

**Comment by greg-szabo** [comment]
Oh, I renamed the jobs. Here are the correct links:

https://ci.interblock.io/view/08%20-%20CI/job/02.Compile.UnitTest/36/console
https://ci.interblock.io/view/08%20-%20CI/job/02.Compile.UnitTest/37/console

Make sure you click "Full log" to see everything.

**Comment by ebuchman** [comment]
Replaces https://github.com/tendermint/tendermint/issues/260 , which says:

```
Make mempool reactor drop txs if mempool gets locked or blocks.
Make consensus reactor drop msgs if consensus blocks. Ensure that consensus can progress despite dropped messages.
Make sure other reactors don't block.
Document go-p2p reactor to say that reactors cannot block. Add comments on all Receive() implementations as well.
```

**Comment by jackzampolin** [comment]
Closing in favor of https://github.com/tendermint/tendermint/issues/2888
