### ISSUE TITLE
make /validators RPC endpoint report the effective validator set

### ISSUE THREAD

**Issue by pdobacz** [tendermint/tendermint#1211]
**FEATURE REQUEST?** (not sure):

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
`v0.15.0`

**Environment**:
- **OS** (e.g. from /etc/os-release):
linux

**What happened**:
If I change the validator set in such a way, that the consensus halts, the `validators` rpc endpoint still points to the "last non-halted" set.

I kinda get the point why (there hasn't been a block that would allow the new validator hash to propagate), but it isn't too usable, since in such cases (like halting of the chain) I cannot really check the *effective* validator set, that drives the consensus (or lack thereof).

**What you expected to happen**:
`validator` endpoint report the effective validator set (in this case - the "halting one")

**How to reproduce it** (as minimally and precisely as possible):
use [dummy_persistent](https://github.com/tendermint/abci/tree/master/example/dummy#persistentdummyapplication) example app:
```
tendermint node --log_level "*:info" --proxy_app persistent_dummy
```

Check validators
```
http 'http://localhost:46657/validators'
```

Send a `val:pubkey1/power1` that halts the consensus:
```
http 'http://localhost:46657/broadcast_tx_sync?tx="val:01F0710E97A3C69F853FFA6A3BE415D4C5C5187220D69602794CD7A952FC400D10/1234"'
```

See that consensus halts (validator set changed), but
```
http 'http://localhost:46657/validators'
```
returns old stuff.

**Comment by adrianbrink** [comment]
The validator RPC endpoint should return the latest information from EndBlock. So if the validator set changes in EndBlock and halts consensus, Tendermint RPC still should return the new (and halting) validator set from the rpc.

**Comment by ebuchman** [comment]
@pdobacz can you check my comments in the PR #1463 please ?

In short, we shouldn't change what validator set is returned here. If you need the current set, see dump_consensus_state. But we can include the changes from EndBlock in this end point.

Does that help ? :)

**Comment by pdobacz** [comment]
@ebuchman Yep, looks like `dump_consensus_state` will do the trick, wasn't aware of this, so I went straight for `validators`. Thank you!
