### ISSUE TITLE
Improve logging context information

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#1212]
Inspired by a [conversation](https://github.com/tendermint/tendermint/pull/1204#discussion_r167392392) in #1204  is this proposal to improve the information carried in every log line. In essence each log line should provide enough context so that an operator can infer origin and meainng, even when looked at in isolation in a remote place. From the original conversation:

> Usually thinking about in what remote ends logs can end up in typical infrastructure I try to imagine what vital info is needed to make sense of it when consumed in some log infrastructure remote from the origin. Additionally how each log line can interpreted by itself without context of the lines before or after. As the logger is passed from the outside to the inside in the program we can enrich the keyvals with information as well which subsystems don't need to care about. A standard set of fields I try to surface, most of them which can easily be achieved with Dynamic Contextual Values from the go-kit log package:

Propsed set of standard fields:

* **caller**: https://godoc.org/github.com/go-kit/kit/log#Caller
* **timestamp**: https://godoc.org/github.com/go-kit/kit/log#pkg-variables
* **revision**: compile flag: https://github.com/tendermint/tendermint/blob/master/Makefile#L10
* **job**: `tendermint` in our case
* **task**: `node`for the node command
* **service**: what we pass to `cmn.NewBaseService(...)` e.g.: `privValidatorSocketServer`
* **err**: set if error present

***

*All field names are up for discussion and can be adjusted according to some sane strategy.*
*Proper error propagation and messages are important for the overall goal but exceeds the scope of this issue*

**Comment by tessr** [comment]
The team discussed this today, and we'd like to move forward on it (although it hasn't been put on the roadmap yet) so I'm removing the S:proposal label. 

I think the proposed keys are a good starting point. It would also be interesting to solicit feedback from validators and other operators. What might be most helpful to people running Tendermint?

**Comment by marbar3778** [comment]
`tmLogger.Error` is currently treated the same as `Error` and `Errorf` from the std lib. It would be nice to have `tmLogger.Error` for strings and `tmlogger.Errorf` when formatting is needed.
