### ISSUE TITLE
What is the meaning of "Cannot add non-routable address"

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1215]
After having troubles with pex in 0.15 release, I've resorted to 0.12 where I now see
Cannot add non-routable address 192.168.55.xx.
It's a simple VirtualBox setup with 3 debian VMs.
Each node reports the other 2 nodes as non-routable. 
Each node is configured to have the other 2 nodes as seed.

What is the meaning of that? Is that a problem? What to do about it?

`2018-02-15_21:42:15.75976 E[02-15|21:42:15.759] Cannot add non-routable address 192.168.55.11:46656 module=p2p book=/etc/tendermint/node/addrbook.json
2018-02-15_21:42:15.75977 E[02-15|21:42:15.759] Cannot add non-routable address 192.168.55.12:46656 module=p2p book=/etc/tendermint/node/addrbook.json
`

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/develop/p2p/netaddress.go#L189

I think this code was just copied from btcd.

You can turn off strict routability by setting `addr_book_strict` to `false`.

```
[p2p]
addr_book_strict=false
```

**Comment by ebuchman** [comment]
You should also be able to get around it by adding them to `private_peer_ids` if you're using a recent enough version
