### ISSUE TITLE
How to test tendermint basecoin using tm-bench

### ISSUE THREAD

**Issue by devashish-laitkor** [tendermint/tendermint#1217]
Till now we are using tm-bench for test dummy application on multiple nodes. We are trying to use basecoin for our application and before using it we want to sure about its performance. So we trying to setup basecoin on multiple nodes (currently using 4 nodes) and test it using tm-bench. But unfortunately, we couldn't find such documents that can guide us how to setup basecoin on multiple nodes and test it using tm-bench.

Till now we are using following commands for run tm-bench for dummy application:- 

Stablishing p2p connection on all four node

`tendermint node --proxy_app=dummy --p2p.seeds=11.11.11.11:46656,22.22.22.22:46656,33.33.33.33:46656,44.44.44.44:46656`

Run tm-bench test from different node

`tm-bench -T 5 -v -r 200 -c 4 11.11.11.11:46657,22.22.22.22:46657,33.33.33.33:46657,44.44.44.44:46657`

And we get successful result on it

https://s.nimbus.everhelper.me/share/1475743/x7xeszvcywahred9oy7s

**But now we want to test it for basecoin. Any help will be appreciated.**

Regards

**Comment by melekes** [comment]
You'll need to change tm-bench to produce transactions, which are accepted by basecoin (I mean the format). Because, right now, tm-bench just sends "random" bytes https://github.com/tendermint/tools/blob/master/tm-bench/transacter.go#L206.

**Comment by devashish-laitkor** [comment]
Hi, 
Thanks for the response, But I need help from scratch, Means how can I setup tenderment ready for basecoin.
For example currently, I am we are running tendermint for dummy application `--proxy_app=dummy ` so what I need to do so that I can run tendermint for basecoin `--proxy_app=basecoin`

Regards

**Comment by melekes** [comment]
basecoin is deprecated btw. see https://github.com/cosmos/cosmos-sdk

**Comment by harshsinghiitd** [comment]
@devashish-laitkor  can you please share how you did tm-bench for test dummy application on multiple nodes. It would be very helpful.
Thanks

**Comment by melekes** [comment]
@harshsinghiitd check out https://tendermint.com/docs/tools/benchmarking.html

**Comment by harshsinghiitd** [comment]
I'm new to tendermint. This link states **tm-bench only works with build-in `kvstore` ABCI application** but i'm using dummy app, and I want to use tm-bench for test dummy application on multiple nodes.

**Comment by melekes** [comment]
kvstore == dummy app. they are the same thing

If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org) 💬
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint) 🧵
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚
