### ISSUE TITLE
Lower debug message level for error `Ignoring connection from self`

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#1219]
Feature request:

Tendermint logs error `ignoring connection from self` regularly. However, the binary has no way of knowing its own IP (except if we start collecting it when this error occurs) and PEX will gossip the IP regularly. Hence the error message becomes noise, with no real information. Some clients might even keep their own IP in config.toml which adds to the confusion.

Example:
```
Feb 13 12:18:54 gg-node0 tendermint[12069]: E[02-13|17:18:54.455] Failed to add peer                           module=p2p address=198.211.124.112:46656 err="Ignoring connection from self"
```

Short-term workaround:
This message should be a DEBUG level message.

Long-term solution:
When this error message happens, the IP address should be stored for the process to be able to account for itself. Since this requires a whole lot of other discussions, I'm advising to archive this as an idea and only work on it if other (more important) benefits arise.

**Comment by melekes** [comment]
This should be solved by https://github.com/tendermint/tendermint/pull/1350
