### ISSUE TITLE
integrations tests to hunt for deadlocks, memory leaks, etc.

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1222]
For instance, to capture things like https://github.com/tendermint/tendermint/issues/938.

Here are some useful tests: https://github.com/tendermint/tendermint/pull/1202/files

We can probably write lots more!

**Comment by ebuchman** [comment]
@greg-szabo re our convo - this is the kind of thing we should have running automatically so we can find potentially deadlocks and races lurking in the code.

would be great if the tests were just run continuously for master (and develop ?) and logs collected and an issue opened if ever something goes wrong ...

**Comment by jackzampolin** [comment]
Closing this as overly general.
