### ISSUE TITLE
logging []byte

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1227]
Seems the default is gross, eg. `D[02-20|04:45:02.876] Received bytes                               module=p2p peer=159.65.184.144:46656 chID=0 msgBytes="\u0002\u0001\u0006\u0001\u0001(fe04bb17203565c251f581a6011e65066de9d4c0\u0001\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd.e\ufffd\ufffd\ufffd@\u0001\u0001(6998a70a7ee966a0abb384d569e38ef6caae602f\u0001\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffdA\ufffd\ufffd\ufffd@\u0001\u0001(f29e60649cf8c9ba092b988155f3b0b273b8333d\u0001\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd\ufffd@\u0001\u0000\u0001\u0010\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\ufffd\ufffdR\ufffd\u0` ...

Should/can the logger auto encode this as hex ?

**Comment by melekes** [comment]
> Should/can the logger auto encode this as hex ?

default encoding for unknown types is `%v`. I would not complicate that further (using `reflect` or something...). If you want hex, well... just use `fmt.Sprintf("%X", []byte{...})`

**Comment by odeke-em** [comment]
@ebuchman @melekes this is similar to https://github.com/tendermint/tendermint/issues/1207 which was resolved by @ebuchman's commit https://github.com/tendermint/tendermint/commit/f4feb7703b584209e69e40b06c981ecc86b75291
 so that's a start
