### ISSUE TITLE
Remove IP from addrbook if we're adding IP plus ID

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1228]
```
2018-02-20T05:38:28Z box4450.localdomain docker/local_testnet_3[15473]: I[02-20|05:38:28.485] Added new address                            module=p2p book=/go/src/github.com
/tendermint/tendermint/test/p2p/data/mach3/core/config/addrbook.json address=fbc1209802dd5c8e0f05618efd18a581f78291b9@172.57.0.102:46656 total=2
2018-02-20T05:38:28Z box4450.localdomain docker/local_testnet_3[15473]: I[02-20|05:38:28.485] Added new address                            module=p2p book=/go/src/github.com
/tendermint/tendermint/test/p2p/data/mach3/core/config/addrbook.json address=172.57.0.102:46656 total=3
```

2 cases:
1) 172.57.0.102, then fbc1209802dd5c8e0f05618efd18a581f78291b9@172.57.0.102
We should check if IP without ID exists and just remove it after we've added ID@IP.

2) fbc1209802dd5c8e0f05618efd18a581f78291b9@172.57.0.102, then 172.57.0.102
Linear search for `([a-z0-9]+@)?172.57.0.102`?

Refs https://github.com/tendermint/tendermint/pull/1214#issuecomment-366876229

**Comment by ebuchman** [comment]
oh, if AuthEnc is true, we should only accept addrs with IDs.

**Comment by ebuchman** [comment]
I think maybe we want to require all addresses come with an ID no matter what. If auth_enc=false, then the ID can be whatever folks want, and we dont authenticate it. But it's hard to write the code to support both having and not having the ID
