### ISSUE TITLE
Double signing tool

### ISSUE THREAD

**Issue by pdobacz** [tendermint/tendermint#1229]
**FEATURE REQUEST**

Provide a way to simulate a byzantine validator attempting to double-sign.

This tool should make Tendermint Core supply a non-empty `Evidence` list in `byzantine_validators` on `BeginBlock`.

The purpose of this would be demoing (or integration-testing) punishment and/or preventive measures taken by the ABCI app.

Submitting the issue to `tendermint/tendermint` as it conceptually seems to fit better here, however this may evolve into a standalone tool (possibly in `tendermint/tools`?).

**Comment by zmanian** [comment]
The easiest thing I can think of is generating a new block proposal at a different height than currently exists.

**Comment by ebuchman** [comment]
Actually easiest is probably to just reset your priv_validator and start tendermint. You'll try to re sign for an old block :)

**Comment by pdobacz** [comment]
Thanks! Re

> reset your priv_validator and start tendermint

What's the simplest configuration of validators/nodes where this can actually work?

Doing this sounds a little bit unwieldy though. If this is to become the standard practice of double signing for tests, maybe the exact steps to reproduce the double-sign could be documented somewhere?

**Comment by ebuchman** [comment]
Ok it's not as easy I thought. Someone should make a tool :)
