### ISSUE TITLE
Add retry functionality when verifying seed existence

### ISSUE THREAD

**Issue by RobertDiebels** [tendermint/tendermint#1230]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

I would like to suggest that Tendermint implements a retry mechanism when verifying the existence of seeds.

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
All.

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
None.

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):
Unknown,

**Environment**:
- **OS** (e.g. from /etc/os-release): N/A
- **Install tools**: Kubernetes
- **Others**: Kubernetes

**What happened**:
Tendermint crashes if it is unable to locate one of its seeds.

**What you expected to happen**:
I expect Tendermint to retry finding its seeds instead of terminating.

**How to reproduce it** (as minimally and precisely as possible):
If necessary I can put my Kubernetes configuration online for you to test. However I believe the below example is enough.

**Anything else do we need to know**:
Below you can find a description of the use case for this FEATURE REQUEST.

**Use case**
I am trying to create a Kubernetes cluster with Hyperledger Burrow which uses Tendermint under the hood.

In my configuration each Tendermint/Burrow node is represented by a Pod.
Each Pod is tied to a Kubernetes Service which gives it a unique FQDN.

I've written some code that checks the cluster configuration and sets the seeds configuration for each Burrow/Tendermint node to the FQDN of all the other nodes.

This all functions perfectly fine. 

**Problem this feature would solve**
However, the problem with the Kuberntes use case is as follows. Each Burrow/Tendermint node requires their seeds to be up before it the node itself can function.

Because a Kubernetes Pod is unreachable when one of its containers crashes the nodes never find each other. I'll illustrate this with the steps Kubernetes follows when starting Pods.

Lets say I have 3 Tendermint/Burrow nodes which is equivalent to 3 Kubernetes Pods.
Here all the nodes have all nodes as seeds.

1. The network configuration is loaded.
2. Kubernetes starts launching the pods.
3. Pod 1 loads and starts the Tendermint/Burrow container.
4. Pod 2 loads and starts the Tendermint/Burrow container.
5. Pod 1 starts verifying its seeds are up.
6. Pod 2 starts verifying its seeds are up.
7. Pod 3 is not up yet. So Pod 1 crashes and Pod 2 crash.
8. Pod 3 loads and starts checking its seeds.
9. Pod 3 starts verifying its seeds are up.
10. Pods 1 and 2 are no longer up so Pod 3 crashes.
11. Continues until randomness allows the Pods to find each other.

To stop this from happening I would have to ensure that the Pods are always up. Regardless of a Tendermint/Burrow node being in an error state or not.

Assuming that Kubernetes Pods only terminate if all containers have crashed. I could force this behaviour by:

1. ~~Adding a container to the pod that is always up but does nothing.~~ (Tried it. Doesn't work)
2. ~~In some way wrapping Tendermint/Burrow. Then catch process termination and restart the process. This way the Pod never crashes and is always reachable on its FQDN.~~ (Tried it. It worked but the logs were a mess.)
3. Split pods into Peer nodes and Seed nodes and delay launching of Peers until Seeds have been confirmed. (This works. Also removes all responsibility from Tendermint and launching order towards anyone using Tendermint. Which I think is preferable over the added functionality.)

~~The first solution forces me to add bloat-ware to my Cluster.~~ The second solution tampers with the node's running states. Since I have no way of knowing whether Tendermint crashed do to a network error or for instance a configuration error.
 
Either way both solutions are highly undesirable. 

**Side-note**
Before starting this attempt I checked the mint-net Kubernetes template. What I understood from reading the template is that it is trying to avoid not being able to find the seeds by using Nginx and creating the configuration during cluster run-time.

In my use-case I have already created the necessary configuration before launching the cluster. As far as I know this is the preferred way of managing application configuration in Kubernetes.
Because it allows you to use Kubernetes configuration resources such as ConfigMaps and Secrets. These resources are managed by Kubernetes so updating them is much easier compared to creating configuration at cluster run-time.

If you have any questions I will be glad to answer.

**Comment by RobertDiebels** [comment]
**Implementation request**
If this issue gets picked up I would like to request the ablity to set the timeout between retries via the Tendermint configuration.

**Reason**
Sometimes Kubernetes takes quite a while to start a Pod. Having control over the timeout allows a Tendermint admin/user to account for startup times.

**Side-note**
I don't know the performance of Kubernetes regarding Pod start-up times when the amount of Pods to start is large. Supposedly Kubernetes can handle thousands of Pods at a time so I'm not to worried.
Thought I'd mention this since a user controlled retry-timeout will only work properly if you can reliably estimate Pod startup times.

**Comment by RobertDiebels** [comment]
I added a third solution. I'm now checking the the type of node I'm launching first. That way a user has control over when Peers or Seeds come up and the network doesn't crash.

You can consider the issue closed on my end.

**Comment by nickray** [comment]
Are you using a Deployment or a StatefulSet for this?

**Comment by RobertDiebels** [comment]
@nickray Right now I'm using plain pods which is sufficient for my purposes. Because I don't need them to get back up after failure.

**Comment by melekes** [comment]
```
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
```

**Comment by RobertDiebels** [comment]
@melekes Regarding the annotation. Some extra information from the [ServiceSpec documetation](https://v1-8.docs.kubernetes.io/docs/api-reference/v1.8/#servicespec-v1-core).

"The primary use case for setting this field is to use a StatefulSet's Headless Service to propagate SRV records for its Pods without respect to their readiness for purpose of peer discovery."

I can't use a StatefulSet because that will require me to generate configuration during scheduling. 
I'd like to avoid generation because it won't allow me to update the configuration, something ConfigMaps and Secrets do allow.

I can understand not wanting to do a retry. This way it becomes the client's responsibility to ensure the seeds are up.

Thanks for adding the error message though! That will disambiguate things when the error occurs :D .
