### ISSUE TITLE
Break out PrivValidatorConfig

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#1231]
As the amount of aspects grow we want to have configurable for the private validator it would make sense to break it out into it's own type.

**Comment by zramsay** [comment]
see #1181

**Comment by greg-szabo** [comment]
Duplicate of #1181

**Comment by ebuchman** [comment]
This is not the same as #1181.

This is about the Config file and having a separate PrivValidatorConfig for configuration options related to the priv validator.

This is distinct from the content of the PrivValidator itself.

**Comment by ebuchman** [comment]
I wonder if this should be in the config.toml or or the priv_validator.json? We don't have a coherent story for the priv_validator.json right now when we're using an external signer, it just becomes a meaningless thing. If we can sync it with the external process and have it be the config for it, that might make more sense.

**Comment by ebuchman** [comment]
This issue should simultaneously address concerns from #3105, #3099, #3009, #2657 w.r.t configuration data. Seems to make sense that the priv_validator_key.json can manage this stuff?

**Comment by jackzampolin** [comment]
Didn't we do a bunch of work on priv_validator? Closing this issue as I'm pretty sure its been addressed.
