### ISSUE TITLE
write_heap_profile RPC

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#1232]
This RPC is mentioned http://localhost:46657/write_heap_profile in https://blog.cosmos.network/debugging-the-memory-leak-in-tendermint-210186711420

In case it is not removed before release, it should certainly be configurable if this is available or not (and disabled by default)

While a valuable debugging tool, it seems a bad idea to allow any RPC user to be able to write files.

**Comment by ebuchman** [comment]
It is disabled by default.

To enable, use `--rpc.unsafe` :)

**Comment by mdyring** [comment]
Phew. 👍
