### ISSUE TITLE
TestByzantine non-deterministic failure

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1234]
[test_integrations (35).log](https://github.com/tendermint/tendermint/files/1742885/test_integrations.35.log)

https://circleci.com/gh/tendermint/tendermint/3160#artifacts/containers/0

**Comment by ebuchman** [comment]
Should be fixed by #1683

**Comment by Liamsi** [comment]
bubbled up again in https://github.com/tendermint/tendermint/pull/3351#issuecomment-467357000

**Comment by cmwaters** [comment]
Closing this as being stale. Feel free to open this up again if people experience this particular failure again
