### ISSUE TITLE
TestMempoolProgressAfterCreateEmptyBlocksInterval nondeterministic failure

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1235]
=== RUN   TestMempoolProgressAfterCreateEmptyBlocksInterval
I[02-21|02:50:16.536] Starting EventBus                            module=events impl=EventBus
I[02-21|02:50:16.536] Need to set a buffer and log message here for sanity. module=consensus startTime=2018-02-21T02:50:16.546353284Z now=2018-02-21T02:50:16.536843095Z
I[02-21|02:50:16.537] enterNewRound(1/0). Current: 1/0/RoundStepNewHeight module=consensus 
I[02-21|02:50:16.537] enterPropose(1/0). Current: 1/0/RoundStepNewRound module=consensus 
D[02-21|02:50:16.537] This node is a validator                     module=consensus 
I[02-21|02:50:16.537] enterPropose: Our turn to propose            module=consensus proposer=8E3E687E1777DD8300331FD405A67FDF340944E7 privValidator="PrivValidator{8E3E687E1777DD8300331FD405A67FDF340944E7 LH:0, LR:0, LS:0}"
I[02-21|02:50:16.541] Signed proposal                              module=consensus height=1 round=0 proposal="Proposal{1/0 1:CA838CA6074F (-1,:0:000000000000) {/7A49C02CD103.../} @ 2018-02-21T02:50:16.538Z}"
D[02-21|02:50:16.544] Signed proposal block: Block{
  Header{
    ChainID:        tendermint_test
    Height:         1
    Time:           2018-02-21 02:50:16.537578262 +0000 UTC m=+3.440418958
    NumTxs:         0
    TotalTxs:       0
    LastBlockID:    :0:000000000000
    LastCommit:     
    Data:           
    Validators:     46C2D0C09AD6406E49105ABCA35D636C384AF134
    App:            
    Conensus:       0B8CEF95EC57AC2D96038FD0AE3901C14FAE8E73
    Results:        
    Evidence:       
  }#902D8F150FF9E03DF9F2F4CDDE47285267380454
  Data{
    
  }#
  Data{
    
  }#
  Commit{
    BlockID:    :0:000000000000
    Precommits: 
  }#
}#902D8F150FF9E03DF9F2F4CDDE47285267380454 module=consensus 
I[02-21|02:50:16.544] Starting TimeoutTicker                       module=consensus impl=TimeoutTicker
D[02-21|02:50:16.544] Starting timeout routine                     module=consensus 
D[02-21|02:50:16.545] Received tick                                module=consensus old_ti="{Duration:0s Height:0 Round:0 Step:RoundStepUnknown}" new_ti="{Duration:100ms Height:1 Round:0 Step:RoundStepPropose}"
D[02-21|02:50:16.545] Timer already stopped                        module=consensus 
D[02-21|02:50:16.545] Scheduled timeout                            module=consensus dur=100ms height=1 round=0 step=RoundStepPropose
I[02-21|02:50:16.549] Received complete proposal block             module=consensus height=1 hash=902D8F150FF9E03DF9F2F4CDDE47285267380454
I[02-21|02:50:16.550] enterPrevote(1/0). Current: 1/0/RoundStepPropose module=consensus 
I[02-21|02:50:16.550] enterPrevote: ProposalBlock is valid         module=consensus height=1 round=0
I[02-21|02:50:16.556] Signed and pushed vote                       module=consensus height=1 round=0 vote="Vote{0:8E3E687E1777 1/00/1(Prevote) 902D8F150FF9 {/7C73FF959DC9.../} @ 2018-02-21T02:50:16.551Z}" err=null
D[02-21|02:50:16.556] addVote                                      module=consensus voteHeight=1 voteType=1 valIndex=0 csHeight=1
I[02-21|02:50:16.559] Added to prevote                             module=consensus vote="Vote{0:8E3E687E1777 1/00/1(Prevote) 902D8F150FF9 {/7C73FF959DC9.../} @ 2018-02-21T02:50:16.551Z}" prevotes="VoteSet{H:1 R:0 T:1 +2/3:902D8F150FF9E03DF9F2F4CDDE47285267380454:1:CA838CA6074F BA{1:X} map[]}"
D[02-21|02:50:16.559] enterNewRound(1/0): Invalid args. Current step: 1/0/RoundStepPrevote module=consensus 
I[02-21|02:50:16.559] enterPrecommit(1/0). Current: 1/0/RoundStepPrevote module=consensus 
I[02-21|02:50:16.561] enterPrecommit: +2/3 prevoted proposal block. Locking module=consensus hash=902D8F150FF9E03DF9F2F4CDDE47285267380454
I[02-21|02:50:16.565] Signed and pushed vote                       module=consensus height=1 round=0 vote="Vote{0:8E3E687E1777 1/00/2(Precommit) 902D8F150FF9 {/EE836F67E02A.../} @ 2018-02-21T02:50:16.561Z}" err=null
D[02-21|02:50:16.565] addVote                                      module=consensus voteHeight=1 voteType=2 valIndex=0 csHeight=1
I[02-21|02:50:16.568] Added to precommit                           module=consensus vote="Vote{0:8E3E687E1777 1/00/2(Precommit) 902D8F150FF9 {/EE836F67E02A.../} @ 2018-02-21T02:50:16.561Z}" precommits="VoteSet{H:1 R:0 T:2 +2/3:902D8F150FF9E03DF9F2F4CDDE47285267380454:1:CA838CA6074F BA{1:X} map[]}"
D[02-21|02:50:16.568] enterNewRound(1/0): Invalid args. Current step: 1/0/RoundStepPrecommit module=consensus 
D[02-21|02:50:16.568] enterPrecommit(1/0): Invalid args. Current step: 1/0/RoundStepPrecommit module=consensus 
I[02-21|02:50:16.569] enterCommit(1/0). Current: 1/0/RoundStepPrecommit module=consensus 
I[02-21|02:50:16.574] Finalizing commit of block with 0 txs        module=consensus height=1 hash=902D8F150FF9E03DF9F2F4CDDE47285267380454 root=
I[02-21|02:50:16.576] Block{
  Header{
    ChainID:        tendermint_test
    Height:         1
    Time:           2018-02-21 02:50:16.537 +0000 UTC
    NumTxs:         0
    TotalTxs:       0
    LastBlockID:    :0:000000000000
    LastCommit:     
    Data:           
    Validators:     46C2D0C09AD6406E49105ABCA35D636C384AF134
    App:            
    Conensus:       0B8CEF95EC57AC2D96038FD0AE3901C14FAE8E73
    Results:        
    Evidence:       
  }#902D8F150FF9E03DF9F2F4CDDE47285267380454
  Data{
    
  }#
  Data{
    
  }#
  Commit{
    BlockID:    :0:000000000000
    Precommits: 
  }#
}#902D8F150FF9E03DF9F2F4CDDE47285267380454 module=consensus 
I[02-21|02:50:16.580] Executed block                               height=1 validTxs=0 invalidTxs=0
I[02-21|02:50:16.580] Committed state                              height=1 txs=0 appHash=
I[02-21|02:50:16.580] Recheck txs                                  module=mempool numtxs=0 height=1
I[02-21|02:50:16.581] enterNewRound(2/0). Current: 2/0/RoundStepNewHeight module=consensus 
D[02-21|02:50:16.581] Received tick                                module=consensus old_ti="{Duration:100ms Height:1 Round:0 Step:RoundStepPropose}" new_ti="{Duration:-94.45µs Height:2 Round:0 Step:RoundStepNewHeight}"
D[02-21|02:50:16.582] Scheduled timeout                            module=consensus dur=-94.45µs height=2 round=0 step=RoundStepNewHeight
D[02-21|02:50:16.582] Received tick                                module=consensus old_ti="{Duration:-94.45µs Height:2 Round:0 Step:RoundStepNewHeight}" new_ti="{Duration:1s Height:2 Round:0 Step:RoundStepNewRound}"
D[02-21|02:50:16.583] Scheduled timeout                            module=consensus dur=1s height=2 round=0 step=RoundStepNewRound
I[02-21|02:50:17.583] Timed out                                    module=consensus dur=1s height=2 round=0 step=RoundStepNewRound
D[02-21|02:50:17.583] Received tock                                module=consensus timeout=1s height=2 round=0 step=RoundStepNewRound
I[02-21|02:50:17.584] enterPropose(2/0). Current: 2/0/RoundStepNewRound module=consensus 
D[02-21|02:50:17.584] This node is a validator                     module=consensus 
I[02-21|02:50:17.584] enterPropose: Our turn to propose            module=consensus proposer=8E3E687E1777DD8300331FD405A67FDF340944E7 privValidator="PrivValidator{8E3E687E1777DD8300331FD405A67FDF340944E7 LH:1, LR:0, LS:3}"
D[02-21|02:50:17.588] Received tick                                module=consensus old_ti="{Duration:1s Height:2 Round:0 Step:RoundStepNewRound}" new_ti="{Duration:100ms Height:2 Round:0 Step:RoundStepPropose}"
D[02-21|02:50:17.588] Timer already stopped                        module=consensus 
D[02-21|02:50:17.588] Scheduled timeout                            module=consensus dur=100ms height=2 round=0 step=RoundStepPropose
I[02-21|02:50:17.688] Timed out                                    module=consensus dur=100ms height=2 round=0 step=RoundStepPropose
--- FAIL: TestMempoolProgressAfterCreateEmptyBlocksInterval (2.05s)
panic: We shouldnt be stuck waiting [recovered]
	panic: We shouldnt be stuck waiting

goroutine 532 [running]:
testing.tRunner.func1(0xc420e1e000)
	/usr/local/go/src/testing/testing.go:711 +0x5d9
panic(0xd578a0, 0x1021820)
	/usr/local/go/src/runtime/panic.go:491 +0x2a2
github.com/tendermint/tendermint/consensus.ensureNewStep(0xc420cfe6c0)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:321 +0x165
github.com/tendermint/tendermint/consensus.TestMempoolProgressAfterCreateEmptyBlocksInterval(0xc420e1e000)
	/go/src/github.com/tendermint/tendermint/consensus/mempool_test.go:52 +0x428
testing.tRunner(0xc420e1e000, 0xfaa680)
	/usr/local/go/src/testing/testing.go:746 +0x16d
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:789 +0x569
exit status 2
FAIL	github.com/tendermint/tendermint/consensus	5.501s
make: *** [test_integrations] Error 1

**Comment by ebuchman** [comment]
Got it again:

--- FAIL: TestMempoolProgressAfterCreateEmptyBlocksInterval (0.14s)
panic: We should be stuck waiting, not moving to the next step [recovered]
	panic: We should be stuck waiting, not moving to the next step

goroutine 697 [running]:
testing.tRunner.func1(0xc4214f41e0)
	/usr/local/go/src/testing/testing.go:742 +0x567
panic(0xd403e0, 0x1011f40)
	/usr/local/go/src/runtime/panic.go:505 +0x24a
github.com/tendermint/tendermint/consensus.ensureNoNewStep(0xc420e6e0c0)
	/go/src/github.com/tendermint/tendermint/consensus/common_test.go:314 +0x14e
github.com/tendermint/tendermint/consensus.TestMempoolProgressAfterCreateEmptyBlocksInterval(0xc4214f41e0)
	/go/src/github.com/tendermint/tendermint/consensus/mempool_test.go:51 +0x405
testing.tRunner(0xc4214f41e0, 0xf9bce8)
	/usr/local/go/src/testing/testing.go:777 +0x16e
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:824 +0x565
FAIL	github.com/tendermint/tendermint/consensus	2.953s
Exited with code 1

**Comment by jackzampolin** [comment]
Have we seen this lately? Closing as likely gone.
