### ISSUE TITLE
Improve DumpConsensusState

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1238]
Improve ability to understand what's going on:

- Use strings for step
- Show more about history  ? (eg. how certain rounds progressed, who signed/didnt)
- More?

**Comment by nickray** [comment]
Is it conceptually possible to add the validator pubkeys to the `peer_round_states` section? If so, I would ask for that. I'm trying to monitor whether validators are up or down, but can't associate the `Validators` set with these peers.

**Comment by ebuchman** [comment]
It's tricky, and wouldnt necessarily be safe unless we get the validator key to sign something to prove it ... but this would be incredibly useful. Maybe we can figure out something for it.

**Comment by nickray** [comment]
I don't quite understand. Wouldn't you be getting the peers' round states via messages signed with their keys? Or is this just gossip?

**Comment by ebuchman** [comment]
Correct - there's no way to distinguish right now a msg that came from the peer vs one that was just forwarded by the peer but originated elsewhere

**Comment by ebuchman** [comment]
Done in https://github.com/tendermint/tendermint/pull/1514

Also opened https://github.com/tendermint/tendermint/issues/1516 for the more specific issue of self reporting on validator address
