### ISSUE TITLE
Signed Builds

### ISSUE THREAD

**Issue by martindale** [tendermint/tendermint#1240]
When releases are created, we should have an easily verifiable authentication mechanism for distributed binaries.  Some key set, shared publicly and widely available (included in the source and available in the UI, as well as published on an SSL-enabled domain, potentially even included in a `TXT` record on the domain), should be used to sign each build and recommended as a verification mechanism (perhaps even automated, if an updated is available).

While discussing in person, an idea for an "alert tool" also emerged, mimicking Bitcoin's original alert mechanism.  This could be used to broadcast important security notifications.

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/837

**Comment by xla** [comment]
Closed in favour of #837
