### ISSUE TITLE
[rpc] no https support 

### ISSUE THREAD

**Issue by SaifRehman** [tendermint/tendermint#1241]

**Comment by srmo** [comment]
@SaifRehman can you please try and describe what this is supposed to mean? RPC endpoint security?
Please try to at least get rid of the boiler plate text :)

**Comment by SaifRehman** [comment]
Yes exactly. Yesterday when i was giving my talk on tendermint in IBM Cloud summit there were questions around it's security and one of them was "no https support in RPC Endpoints", I wasnt able to answer that. Also there was a question about security in Cosmos, they said by this you will be making blockchain decentralised, can you explain on that as well.
Here is my following implementation using tendermint which i presented: https://github.com/SaifRehman/tendermint-chat-app/
can i make a pull request to make this example added in tendermint repo?

**Comment by melekes** [comment]
> Here is my following implementation using tendermint which i presented

awesome! very nice readme btw

> can i make a pull request to make this example added in tendermint repo?

we certainly can put it on https://tendermint.com/ecosystem. the repo is https://github.com/tendermint/tendermint.com

> Also there was a question about security in Cosmos

could you expand on that? you mean when one zone gets hacked or what exactly?

**Comment by SaifRehman** [comment]
Hi @melekes pleasure to hear from you. 

> we certainly can put it on https://tendermint.com/ecosystem. the repo is https://github.com/tendermint/tendermint.com
Yes please that would be lovely! Also, I am working on containersing tedermint application and deplying it to kubernetes 

>could you expand on that? you mean when one zone gets hacked or what exactly?

I presented the idea of tendermint/cosmos network in IBM Cloud Developer Summit in Dubai, that is to combine blockchain network to make internet of blockchain. there were two questions
1) tendermint testrpc api did not supported https
2) It will not be truly decentralised and will be prone to attack as you will be able to attack the main hub. There is a concept about hubs and zones in cosmos which they think it will be vulnerable

**Comment by melekes** [comment]
> It will not be truly decentralised and will be prone to attack as you will be able to attack the main hub. There is a concept about hubs and zones in cosmos which they think it will be vulnerable

initially there will be only one hub (Cosmos hub), so they may be right in a sense that it's a SPOF (single point of failure). But 1) Cosmos hub itself is 100 validators/machines all equiped with DDOS protection and following best security practices ideally 2) Later there will be many hubs

does that make sense?

**Comment by SaifRehman** [comment]
@melekes . Great make sense to me, I couldnt answer that question in the event. I want to equip more knowledge on tendermint and want to contribute to it as well. It looks promising to me. I have experience in both private and public blockchain (Fabric and Ethereum).

- Also it would be lovely if my app can be on the tendermint website

**Comment by SaifRehman** [comment]
@melekes can you also provide me with some learning material I can go through to learn more about it?

**Comment by melekes** [comment]
I'd like to emphasise that Cosmos is not Tendermint. Tendermint is an engine, which powers Cosmos Hub.

https://cosmos.network/ (whitepaper https://cosmos.network/about/whitepaper)
https://tendermint.com/ (docs https://tendermint.readthedocs.io/projects/tools/en/master/)

**Comment by SaifRehman** [comment]
@melekes got you, thank you for sharing the link. Is there a way I can contribute to tendermint, right now I am working on deploying tendermint application to IBM cloud as containers

**Comment by zramsay** [comment]
> is there a way I can contribute to tendermint

Yes, see https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Atendermint+label%3A%22help+wanted%22

Also, this PR (https://github.com/tendermint/aib-data/pull/72) adds your app to https://tendermint.com/ecosystem

**Comment by melekes** [comment]
Many ways! Depending on what you want to do? We have many dev tasks, ops tasks.

**Comment by SaifRehman** [comment]
@zramsay shall I give a pull request for my app to be added on tendermint repo?

**Comment by nickray** [comment]
@SaifRehman I don't quite understand the https problem? You can just put a reverse proxy like nginx in front of the RPC endpoint and terminate SSL there?

**Comment by melekes** [comment]
^^^ looks like a way to go. I am gonna close this.

**Comment by ebuchman** [comment]
Yes I think leaving HTTPS to be an ops concern for now is the right approach. Stick nginx in front - it handles this stuff better than we ever could :)
