### ISSUE TITLE
Run network tests on release

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1249]
Would be great to run network tests for each release. 

TODO from code: https://github.com/tendermint/tendermint/blob/432a7276e24afd0620d76d43110d35d0604802b9/test/test.sh#L56

That way we'll ensure there is no performance degradation.

**Comment by melekes** [comment]
Not quite. We want to benchmark each release and compare the results with the current master to see if performance decreases/increases.

**Comment by jackzampolin** [comment]
Closing this in favor of the benchmarking work @thanethomson and @milosevic are doing.
