### ISSUE TITLE
Docker support, not able to access txServerPort, using lotionjs

### ISSUE THREAD

**Issue by SaifRehman** [tendermint/tendermint#1253]
Here is the link to my code 
[dockerfile](https://github.com/SaifRehman/tendermint-chat-app/blob/master/blockchain/Dockerfile)
[Project Link](https://github.com/SaifRehman/tendermint-chat-app/)
I want to containerize my app
any suggestion or help will be appreciated

**Comment by odeke-em** [comment]
Hello there @SaifRehman, thank you for sharing your app, it is great and exciting to check out!

So we have Dockerized Tendermint already, please see https://github.com/tendermint/tendermint/blob/2cc63069c63bc6b1238cdc69f32310097c62afda/DOCKER/README.md

/cc @ebuchman @adrianbrink @melekes

**Comment by melekes** [comment]
I'll mark this as resolved.
