### ISSUE TITLE
Block commit acknowledgement

### ISSUE THREAD

**Issue by kansi** [tendermint/tendermint#1254]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
FEATURE REQUEST

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.13.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): Arch
- **Install tools**:
- **Others**:

### Description
The `commit` api in ABCI proxy app is used to successfully record transactions and return an updated `app_hash` but this doesn't necessarily ensure that the block has been commited by Tendermint, for example an error could occur mid flight while returning the `commit` response back to Tendermint. To generalize the concern, the proxy app is not aware if the `commit` response was successfully processed by Tendermint.

To handle the above situation and to definitively uncover Tendermint's world view one could use the following methods,

1. Use the block information passed during `begin_block` to know that the last block was successfully processed. The drawback with this approach is that until the next `begin_block` is executed the ABCI proxy app cannot be sure if the current `commit` call was successfully processed by Tendermint.

2. Use HTTP `http://localhost:46657/status` to get the state of system as seen by Tendermint. The drawback with this approach is that when Tendermint is restarted the HTTP api is not avaiable until it has connected to the ABCI proxy app i.e. even the `GET` api methods are not avaiable until the connection is established.

### Possible solutions

1. Following from point **1.** one could propose another api for proxy ABCI app i.e. `commit_ack` which is executed after the response from `commit` has been successfully processed. This api could pass the new block height, updated app hash and maybe updated/effective list of validators as arguments to `commit_ack`. (there should be no response expected by Tendermint from this api)

2. Following from point **2.** there could be another HTTP `GET` api which returns Tendermint's knowledge of the world state i.e. this API would be available even if the ABCI connection is not yet established. To put it more clearly this API would be same as `/status` API but it gives Tendermint's world view knowldege in response and is avaiable regardless of ABCI proxy app connection status.

**Comment by ebuchman** [comment]
This is handled by Tendermint's replay logic when there is a restart and is the purpose of the `Info` abci message. If the app ran Commit but Tendermint crashed before writing the new AppHash to disk, Tendermint will notice that the app is one block ahead of its internal state during the Info handshake and will take necessary actions. For this particular case, see https://github.com/tendermint/tendermint/blob/master/consensus/replay.go#L309

**Comment by ebuchman** [comment]
Can you clarify if an actual bug resulted from this behaviour or if you are just identifying it as a possible concern? 

If the former, please give some details on the bug. If the latter, it should be solved by the ABCI handshake when Tendermint/App first connect. Perhaps that needs to be better documented - Apps definitely need to implement the Handshake (ie. `Info`) correctly for this to work!

Thanks

**Comment by kansi** [comment]
> This is handled by Tendermint's replay logic when there is a restart and is the purpose of the `Info` abci message.

@ebuchman The situation I am describing cannot be resolved by replaying. To describe the concern in a little more detail, 
- The `commit` api should be used by ABCI proxy app to persist the state to disk.
- Once the `commit` api has been successfully executed it returns the new app hash back to Tendermint.
- From the ABCI proxy app's prespective the `commit` was successfully executed but the proxy app doesn't know if the response of the `commit` api was successfully received and processed by Tendermint.
- Here if Tendermint fails to write the new hash for whatever arbitrary reason then there is a state inconsistantcy between Tendermint and the ABCI proxy app i.e. the ABCI proxy app is ahead of Tendermint.
- From the ABCI proxy app's perspective the `commit` was successfull because it returned the new app hash back to Tendermint. But from Tendermint's perspective there was some arbitrary failure while writing the new hash so the block commit wasn't successfull.
- In such a scenario Tendermint upon restart will call `Info` on the ABCI proxy app with will return last block height and app hash which it thinks were successfull. This response will not match with what Tendermint's expecting because for Tendermint the `commit` failed.
- Even if Tendermint tries to replay the block it would cause a lot of issues because from the ABCI proxy app's perspective these transactions have already been processed.

I hope I have clarified my concern well enough. Please let me know if there is any more clarity required or if my understanding regarding the above concern is misplaced.

**Comment by ebuchman** [comment]
Wonderful! Thank you for describing the case so clearly. This is exactly the case handled by https://github.com/tendermint/tendermint/blob/master/consensus/replay.go#L309

In this case, Tendermint "pretends" to replay the block through a `mockApp`. It has all the ABCI responses saved, and it also knows the latest commit hash because it got it from `Info`. It absolutely will not execute the block on the real ABCI app a second time, as that would indeed "cause a lot of issues" :)

Curious how you came to this. Was it just from thinking through the semantics of Commit? Bravo! This was a tricky piece to implement, but we do have tests for it - please read through the logic in replay.go if you're interested!

I will close this issue because I'm quite convinced this case is handled correctly. If you are not, please feel free to re-open, ideally with some demonstration of a bug.

Thanks!

**Comment by kansi** [comment]
@ebuchman Thanks for pointing to the code, really appriciate it :) 

Though I am not really good at reading Golang code I think I understand the logic there. I just have one last query,

- `storeBlockHeight` : This is the height that is passed during `end_block`?
- `stateBlockHeight`: Once `commit` is executed successfully `storeBlockHeight` becomes `stateBlockHeight`?

Is my understanding correct?
