### ISSUE TITLE
smoke test links in spec once stable

### ISSUE THREAD

**Issue by Chjango** [tendermint/tendermint#1261]
the spec has been in constant flux, many links were added as placeholders. Once we confirm (ping @milosevic, @ebuchman) that the layout of the spec is stable, @zramsay will ensure links are up to date

**Comment by zramsay** [comment]
where did you find the link to that readme?

**Comment by srmo** [comment]
There are several such broken links in the current master doc.
Have a look at http://tendermint.readthedocs.io/projects/tools/en/master/specification/new-spec/encoding.html?highlight=XXX%3A%20This%20is%20changing%20

Those pages containig those broken links and `XXX`-Todo markers appear in search results often as `}`

**Comment by zramsay** [comment]
updated issue title and body

**Comment by zramsay** [comment]
@milosevic or @ebuchman does the content in `/docs/specification/new-spec` overrule the .rst files in `/docs/specification` ?

**Comment by zramsay** [comment]
@srmo how did you arrive at that link? building the docs gives `/home/zicter/goApps/src/github.com/tendermint/tendermint/docs/specification/new-spec/encoding.md: WARNING: document isn't included in any toctree`

and I can't seem to arrive at that page no matter where I click on the built docs. Did you enter that URL manually in the browser?

**Comment by zramsay** [comment]
nvm figured it out :paintbrush:
