### ISSUE TITLE
PROPOSAL: move dependencies into tendermint

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1262]
- tmlibs
- abci
- go-crypto
- go-wire
- iavl

**Comment by ebuchman** [comment]
Mmm I wasn't thinking IAVL since Tendermint actually doesn't depend on it at all. 

Maybe we can move IAVL into the SDK.

**Comment by ebuchman** [comment]
I think we should also collapse the `cosmos` and `tendermint` organizations into a single `allinbits` organization :)

Then we can start building the All in Bits brand independently from the product brands. All in Bits is a company. Tendermint is a product. All in Bits should have its own website that talks about the company and can list the products its working on, linking to Tendermint, Cosmos-SDK, Ethermint, etc. Would be great to stop calling the company Tendermint too. Tendermint is a product. Our company is much more. Woo!

**Comment by ebuchman** [comment]
The answer is no.

go-wire because the goal is to have it be adopted independently as proto4.

abci because we want other consensus engines to use it.

tmlibs and go-crypto because other top level projects will allegedly use them.

Cool beans.

**Comment by adrianbrink** [comment]
What do you think about consolidating repos under the `tendermint` organisation?

**Comment by xla** [comment]
Why do we fear having wire as a package in tendermint hurting adoption?

**Comment by ebuchman** [comment]
Because people won't think of wire as a general purpose serialization package, they'll think it's only useful in the context of Tendermint.

@jaekwon wants it to be independent so that folks will see it as a standalone project they can use independent of any Tendermint stuff.
