### ISSUE TITLE
consensus: add test for ValidBlock mechanism

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1263]
https://github.com/tendermint/tendermint/pull/1142 solves a liveness bug in the Tendermint algorithm but we don't have a test for it yet. 

One simple test would be to ensure we propose the last block we used to unlock. 

A more advanced test would capture the old livelock behaviour where a byzantine node can force us to never commit if proposers are free to choose whatever block they want (and not the last one they used to unlock).

**Comment by cmwaters** [comment]
@ebuchman do you know if we wrote tests for this case?
