### ISSUE TITLE
p2p: prevent multiple connections from same IP

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1264]
Currently we allow multiple connections from the same IP because we only enforce uniqueness via the ID.

We shouldn't allow more than one connection from the same IP. Perhaps we should even limit the number of connections from an IP block (we used to do this).

**Comment by ebuchman** [comment]
Reference for why we should do this: https://bitcoinmagazine.com/articles/researchers-explore-eclipse-attacks-ethereum-blockchain/

**Comment by odeke-em** [comment]
For the TL;DR:

<img width="609" alt="screen shot 2018-03-01 at 10 01 53 pm" src="https://user-images.githubusercontent.com/4898263/36885573-9df7e4b4-1d9c-11e8-8c2e-690a485047c0.png">

**Comment by ebuchman** [comment]
Adding PoW to the handshake should actually help with this somewhat (https://github.com/tendermint/tendermint/issues/1045). At least that will make them do work for every connection.

**Comment by ebuchman** [comment]
Started this in #1520

**Comment by ebuchman** [comment]
Done in #1520 thanks @xla
