### ISSUE TITLE
p2p: Fix flaky TestSwitchReconnectsToPersistentPeer

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#1266]
Our CI runs keep failing non-determinstically in the p2p package, we should remove the flakiness. The specific error is:

```
ok  	github.com/tendermint/tendermint/lite/files	1.644s	coverage: 87.0% of statements
--- FAIL: TestSwitchReconnectsToPersistentPeer (0.03s)
	Error Trace:	switch_test.go:282
	Error:      	Expected value not to be nil.
	Test:       	TestSwitchReconnectsToPersistentPeer
FAIL
```

**Comment by ebuchman** [comment]
I think this is in `p2p` not `lite`:

```
tendermint$ ack TestSwitchReconnectsToPersistentPeer
p2p/switch_test.go
259:func TestSwitchReconnectsToPersistentPeer(t *testing.T) {
```

**Comment by xla** [comment]
Of course, copy error. Fixed title and description.

**Comment by odeke-em** [comment]
@xla could you please provide a link to where it is failing in CI?

On my Macbook Pro, I tried running 100 tests in succession, but no failure yet, so I stepped it up to 1000 tests and file descriptor reusage finally gave up
```shell
$ go test -run=TestSwitchReconnectsToPersistentPeer -count=1000
2018/03/11 00:11:03 Failed to accept conn: accept tcp 127.0.0.1:50562: accept: too many open files
exit status 1
FAIL	github.com/tendermint/tendermint/p2p	61.250s
```

**Comment by xla** [comment]
@odeke-em It happens regularly on CI in branches with unrelated changes : 

https://circleci.com/gh/tendermint/tendermint/4089#tests/containers/3

**Comment by odeke-em** [comment]
Thank you @xla!

**Comment by ebuchman** [comment]
We can trace the functions and objects.

The reader in the mconn is a bufio.Reader: `bufReader:   bufio.NewReaderSize(conn, minReadBufferSize)`

We call `wire.ReadByte` on this:

```
func ReadByte(r io.Reader, n *int, err *error) byte {
	var buf [1]byte
	ReadFull(buf[:], r, n, err)
	return buf[0]
}
```

where ReadFull is: 

```
// Read len(buf) from r
// Increment n and set err accordingly.
func ReadFull(buf []byte, r io.Reader, n *int, err *error) {
	if *err != nil {
		return
	}
	n_, err_ := io.ReadFull(r, buf)
	*n += n_
	*err = err_
}
```

It doesn't look like the buffer is of length 0, so it's unclear why this is returned EOF :(

**Comment by xla** [comment]
@ebuchman Did you find a way of reliably triggering the test fail?

**Comment by ebuchman** [comment]
I just run about 5 instances of `yes &> /dev/null &` to keep the CPU busy then:

```
go test -race -v -run ReconnectsToPer -count 100 &> peer.log
```

Fails pretty reliably in the first 100. Sometimes it takes a few hundred.

**Comment by xla** [comment]
It doesn't seem to happen on `master`.

**Comment by xla** [comment]
Gathering more errors during failed runs;

```
E[03-19|11:14:20.655] Connection failed @ recvRoutine (reading byte) peer=127.0.0.1:35643 conn=MConn{127.0.0.1:35643} err="read tcp 127.0.0.1:54084->127.0.0.1:35643: use of closed network connection"
```

**Comment by ebuchman** [comment]
```
E[03-19|11:14:20.655] Connection failed @ recvRoutine (reading byte) peer=127.0.0.1:35643 conn=MConn{127.0.0.1:35643} err="read tcp 127.0.0.1:54084->127.0.0.1:35643: use of closed network connection"
```

I think this one is expected because we're testing closing the connection. This is the error I expect to see from closing the conn, not the empty `EOF` we're seeing for weird reasons.

Not showing on master is certainly an important clue!

**Comment by xla** [comment]
@ebuchman Updated the output, have a hunch that the error printed on the first line is not the original error but the one overwrote further down in the `recvRoutine` as we use a `var err error` for the entire loop.

**Comment by xla** [comment]
So in essence masking the original error here.

**Comment by ebuchman** [comment]
Hmm ok.

I think https://github.com/tendermint/tendermint/pull/1226 might be a good culprit for where this may have been introduced

**Comment by ebuchman** [comment]
This diff makes the issue go away:

```
diff --git a/p2p/peer_test.go b/p2p/peer_test.go
index 45e2b045..cebd7050 100644
--- a/p2p/peer_test.go
+++ b/p2p/peer_test.go
@@ -1,6 +1,7 @@
 package p2p
 
 import (
+       "bufio"
        golog "log"
        "net"
        "testing"
@@ -149,6 +150,8 @@ func (p *remotePeer) accept(l net.Listener) {
                if err != nil {
                        golog.Fatalf("Failed to create a peer: %+v", err)
                }
+               bufReader := bufio.NewReaderSize(pc.conn, 1000)
+               bufWriter := bufio.NewWriterSize(pc.conn, 1000)
                _, err = pc.HandshakeTimeout(NodeInfo{
                        PubKey:     p.PrivKey.PubKey(),
                        Moniker:    "remote_peer",
@@ -168,5 +171,6 @@ func (p *remotePeer) accept(l net.Listener) {
                        return
                default:
                }
+               _, _ = bufReader, bufWriter
        }
 }
```

I do not understand this at all!!!

**Comment by ebuchman** [comment]
@xla seems to have figured this one out in #1338. See the explanation there!

Basically the GC closed the connection when the reference was dropped. Which explains why the  bufio wrappers fixed it too
