### ISSUE TITLE
Do we really need max size of cs.WAL to be 1GB?

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1268]
Isn't it too large? In case of failure, we may need only last few blocks. Why are keeping the others?

**Comment by ebuchman** [comment]
We don't need more than a few blocks, but if the latest block is dragging on across many rounds, we might want all those rounds. 

So the estimate of how much to keep should be based on having ~100 validators and ~100 rounds, say.

**Comment by ebuchman** [comment]
Also I think we need to make the WAL writing more efficient because right now nothing stops us from writing the same message twice

**Comment by ebuchman** [comment]
To document in https://github.com/tendermint/tendermint/issues/1494
