### ISSUE TITLE
Should Genesis file move to ABCI?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1271]
The app is going to need basically everything in the genesis file, so RequestInitChain should effectively contain the genesis file components.

Ie. see https://github.com/cosmos/cosmos-sdk/issues/565

Ideally we can just marshal it to json and back direct from the protobuf generated struct, but maybe we'll need an intermediary struct.

**Comment by jaekwon** [comment]
No.

**Comment by jaekwon** [comment]
We could just pass in the whole genesis.json bytes to the app.  Then we can go-wire unmarshal it there.

Adopting protobuf is a kind of regression that isn't needed... we should invest in go-wire instead of porting things over to protobuf, or maintaining two versions.

**Comment by ebuchman** [comment]
I've added the genesis file fields to the RequestInitChain: https://github.com/tendermint/tendermint/pull/1667

Seems better than just passing a blob
