### ISSUE TITLE
http client websocket: nil websocket client

### ISSUE THREAD

**Issue by aastein** [tendermint/tendermint#1277]
The example documented here does not work for me. 

https://github.com/tendermint/tendermint/blob/c8a2bdf78ba7aaaf4284fa78c1b9b05c5e7342bc/rpc/core/events.go#L60

This line `client.Subscribe(ctx, "test-client", query, txs)` fails because it calls `w.ws.Subscribe(ctx, q)` while `w.ws` is nil here:

https://github.com/tendermint/tendermint/blob/c8a2bdf78ba7aaaf4284fa78c1b9b05c5e7342bc/rpc/client/httpclient.go#L254

To handle this I tried calling `client.OnStart()` before `client.Subscribe()` to initialize w.ws, but the server throws an error here:

https://github.com/tendermint/tendermint/blob/c8a2bdf78ba7aaaf4284fa78c1b9b05c5e7342bc/rpc/lib/server/handlers.go#L541

**Comment by melekes** [comment]
Have you tried to connect to your websocket by other means? I mean if it fails with "failed to read request", then it must be something wrong with your websocket connection.
