### ISSUE TITLE
lite: ValidatorSet.VerifyCommitAny should use proper quorum and validate commit message in context of new validator sets

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#1287]
Update function of the dynamic certifier (https://github.com/tendermint/tendermint/blob/develop/lite/dynamic_certifier.go#L70)
of the light client is updating the validator set based on the new Commit message. 

Before updating the validator set, two checks need to be done:

1) current validator set has signed the commit message with more that 1/3 of the voting power (of the current validator set). This proves that at least single correct validator from the current validator set has signed the commit message
2) validate the commit message in the context of new validator set, i.e., >2/3 of the voting power from the new validator set has signed the commit.

These checks are supposed to be implemented by function VerifyCommitAny, see https://github.com/tendermint/tendermint/blob/develop/types/validator_set.go#L288. 

Current implementation does not implement correctly these checks; 2) is not implemented at all, and 1) uses wrong quorum, i.e, it requires that >2/3 of the current validator set signs the commit message. As validator set can change (less than 1/3 of validators per change), we can't ensure that the commit signed by the new validator set contains >2/3 signature from the old validator set. The two sequential validator sets overlap at least in more than >1/3 of validators, and this is sufficient to check 1).

**Comment by xla** [comment]
@jaekwon Is this still relevant with the latest ltie refactors?
