### ISSUE TITLE
wrong set size: 2 vs 1

### ISSUE THREAD

**Issue by filippetroviccc** [tendermint/tendermint#1289]
Hi,
We want to connect two tendermint validators in local network.

We started first node with command:

`tendermint --home ~/Desktop/tendermint node --proxy_app=dummy`

And second node with command:

`tendermint --home ~/Desktop/tendermint2 node --p2p.seeds="0.0.0.0:46656" --proxy_app=dummy`

And we followed this tutorial for this: https://github.com/tendermint/tendermint/blob/master/docs/using-tendermint.rst

But we get: `Error in validation module=blockchain "Invalid commit -- wrong set size: 2 vs 1"`

And to add that we sucesfully conencted two non-validator peers.

tendermint version: 0.14

And to add that we tryed p2p.persistent_peers insted of p2p.seeds but console logs unknown flag.

**Comment by filippetroviccc** [comment]
@zramsay I want to use ethermint after i connect multiple node so I can't :(

**Comment by greg-szabo** [comment]
If both nodes need to be validators, most probably your genesis.json file doesn't contain both public keys. Or more probable: it contains on one of the nodes but it doesn't contain it on the other.

**Comment by ebuchman** [comment]
To clarify - you must have the same genesis file in each home directory. The genesis file determines the number of validators
