### ISSUE TITLE
sync: Node should go back to fast-syncing when lagging significantly

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#129]
My laptop went to sleep, woke up, and started slow-syncing, which is slow to catch up and wastes peer resources unnecessarily.  It would be better to go back to fast-syncing.

Also, switching from fast-sync to slow-sync is slow, i wonder if it could be much faster.

**Comment by adrianbrink** [comment]
@ebuchman Has fast syncing been implemented or is this still open?

**Comment by ebuchman** [comment]
Fast syncing is on by default. We switch it off when we're caught up. This is about switching it back on if for some reason we start to lag far behind (eg. maybe the network was disconnected for a while but the processes never crashed)

**Comment by iphucc** [comment]
> Fast syncing is on by default. We switch it off when we're caught up. This is about switching it back on if for some reason we start to lag far behind (eg. maybe the network was disconnected for a while but the processes never crashed)

Still need a patch?

**Comment by ebuchman** [comment]
Yes, but it's unclear exactly how we should do this - would you mind writing up an overview of how to do it before submitting a patch? Thanks!

**Comment by iphucc** [comment]
> Yes, though it's not the highest priority. Also it's unclear exactly how we should do this - would you mind writing up an overview of how to do it before submitting a patch? Thanks!

There are three patches, not all related to BackToFastSync, please take a look.
I hope the code is simple enough, then I don't have to explain it because my poor English.

**Comment by iphucc** [comment]
> Yes, though it's not the highest priority. Also it's unclear exactly how we should do this - would you mind writing up an overview of how to do it before submitting a patch? Thanks!

Can you improve this pull-request for me, according to the standard of CONTRIBUTING?

**Comment by marbar3778** [comment]
Blocked on fast-sync implementation.

**Comment by ccconnor** [comment]
Seems tendermint is way slower than bitcoin in syncing? Although fast-sync has been turned on. Is there any test data? How fast should it be?

**Comment by ebuchman** [comment]
It depends largely on the application. Also note validating bitcoin consensus only requires checking proof of work, while tendermint requires verification of all the validator signatures, which is much more expensive.

**Comment by ccconnor** [comment]
@ebuchman In fact, it's cosmos that I sync. According to [this](https://tendermint.com/docs/tendermint-core/fast-sync.html), I thought it would be much faster.

**Comment by ebuchman** [comment]
the Cosmos app has some well known bottlenecks in the DB used at the application layer that are likely a significant factor in this - see eg. https://github.com/cosmos/cosmos-sdk/issues/2131
