### ISSUE TITLE
tendermint testnet fail

### ISSUE THREAD

**Issue by pj0579** [tendermint/tendermint#1290]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug

**Tendermint version**: 0.16.0
**ABCI app** :0.9.0
**Environment**:
- **OS** macOs13.0.0
- **Install tools**:glide
- **Others**:

**What happened**:
tendermint testnet
panic: Panicked on a Crisis: open mytestnet/mach0/config/080033051: no such file or directory

**What you expected to happen**:
4 nodes

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
other commands is all right（tendetmint node，tendermint init and so on）

**Comment by melekes** [comment]
1) Replace `--p2p.seeds=$SEEDS; \` with `--p2p.persistent_peers=$SEEDS; \`
2) Looks like you don't have genesis file. Please make sure you have a genesis file in every directory
3) Don't forget to create dir for tendermint `mkdir -p "$TESTNET_ROOT_DIR/$TESTNET_FOLDER/$NODE_0_NAME"`
4) Use `TMHOME` env variable instead of `--home`

**Comment by pj0579** [comment]
thx,  but <code>tendermint testnet</code>  will make four genesis files and four folders actually.

**Comment by pj0579** [comment]
<code>tendermint testnet</code>   need  to add a genesis file by myself?

**Comment by ArvonHuang** [comment]
Hi, have you fixed this problem? I got the same problem as you .

**Comment by ArvonHuang** [comment]
`go get tendermint `

**Comment by odeke-em** [comment]
I can reproduce this on develop just by running
```shell
$ tendermint testnet
```

In the meantime perhaps we need a better error message

**Comment by odeke-em** [comment]
I've mailed out https://github.com/tendermint/tendermint/pull/1303, this'll be fixed in the next release. Thank you very much @pj0579 for reporting this!

**Comment by odeke-em** [comment]
@pj0579 thank you for the report, we've fixed this in PR https://github.com/tendermint/tendermint/pull/1318 which is currently on develop and perhaps might be merged soon to master.

**Comment by ebuchman** [comment]
Thanks @odeke-em - closing as it's on develop. Hopefully will cut a release to master this week :)
