### ISSUE TITLE
Add RPC endpoint for checking health

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1296]
`/health`, which returns 200 OK if this instance is making blocks, otherwise - 500.

**Comment by melekes** [comment]
go ahead, sure!

**Comment by nickray** [comment]
I don't think (longterm) that a health endpoint should check whether blocks are made, since that concerns the health of the chain and not the node. But great to implement to endpoint!

**Comment by srmo** [comment]
Is it possible to give an additional state for "making progress but behind chain"?

**Comment by r8d8** [comment]
It's just health check, only 2 states - `healthy/unhealthy`
There is `\status` endpoint - should be enough for more detailed inspection, or @srmo  I am getting you wrong?

**Comment by melekes** [comment]
Fixed a few thing in https://github.com/tendermint/tendermint/pull/1337

I will leave this issue open because I think we still want to implement @srmo request (showing whenever the node lags behind the rest of the network) based on other peers heights (peerState) and this node height (blockStoreHeight). For that we'll need to add config variable (UnhealthyHeightLag)

**Comment by ebuchman** [comment]
Can we consolidate https://github.com/tendermint/tendermint/issues/726 into here ? 

Lets have the /health endpoint return our height and the height for all our peers. each peer can have its nodeID and moniker. it can also have its validator address once we do #1516

**Comment by melekes** [comment]
> Lets have the /health endpoint return our height and the height for all our peers. each peer can have its nodeID and moniker. it can also have its validator address once we do #1516 

Don't think we should duplicate info. We have other endpoints for that. `/health` needs to be lightweight and only report that something is wrong (node lags behind). then a person will go and use `/net_info` and other RPC endpoints to figure stuff out.

**Comment by zramsay** [comment]
`/health` exists. open a new issue if it needs new features/modification
