### ISSUE TITLE
p2p: exponential back-off followup

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1304]
See review in https://github.com/tendermint/tendermint/pull/1292

- [x] Document the new functionality in the p2p spec (especially https://github.com/tendermint/tendermint/pull/1292#discussion_r173665125)
- [x] Add TODO in test (needs control over time -
 https://github.com/tendermint/tendermint/pull/1292#commitcomment-28038530)
- [x] consolidate the 2 "max retries" mechanisms (https://github.com/tendermint/tendermint/pull/1292#discussion_r173665070)

**Comment by melekes** [comment]
> consolidate the 2 "max retries" mechanisms (#1292 (comment))

@ebuchman and me agreed it's fine to have both mechanisms a) if we book becomes full, after 3 attempts the address is gone b) if the book is not full, we attempt to connect for ~1.5day.
