### ISSUE TITLE
Consolidate 5 tendermint repos into 1

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1309]
Heres a list of Pros and Cons of having Tendermint split into 5 repos (tendermint, abci, go-wire, go-crypto, tmlibs):

## PROS

1) shorter import paths
2) gives the sense that these are all standalone independent projects that evolve independently (this is important for go-amino and abci, but not really for go-crypto or tmlibs)
3) develop branches can accumulate breaking changes without needing to update all dependents for them immediately 

## CONS

1) Extra overhead of updating dependency manager or copying files into `vendor` when developing locally
2) Extra overhead of updating dependency manager across repos in sequence when merging code to develop
3) Issues/PRs in dependency repos are often forgotten about or poorly tracked
4) Changes in dependencies can have effects that are not well tested by the local unit tests and are only discovered to be broken once they're used in Tendermint itself
5) Extra overhead of release management on each repo (changelog, versions, release tags)
6) Development in an independent repo is less likely to consider how changes effect dependents leading to weaker backward compatibility

Seems to me a no brainer to merge them all into one. The only serious argument is "accumulating breaking changes on develop". But really, we should:

1) make fewer breaking changes, and pay more attention to backwards compatibility to ease upgrades or at least allow them to be done iteratively
2) If large breaking changes are needed, we can always just duplicate a package within the monorepo, make the changes there, and port things over as we see fit.

If anyone thinks I'm missing anything, please add!

**Comment by xla** [comment]
![approved](http://i0.kym-cdn.com/photos/images/original/000/302/170/685.png)

> make fewer breaking changes, and pay more attention to backwards compatibility to ease upgrades or at least allow them to be done iteratively
> If large breaking changes are needed, we can always just duplicate a package within the monorepo, make the changes there, and port things over as we see fit.

Aliases in Go 1.9 should ease with those migrations as well. Bringing the packages closer together will also surface breaking changes faster and therefore we can make it merge criteria that develop has to compile. If we get in the habit of smaller incremental changes on top of that we should be able to chew through those larger refactors in less time compared to the current setup.

While doing so we should rethink our repo structure as it is quite an assortment of concerns and currently our packages are interleaved with docs, scripts, etc. This [project-layout](https://github.com/golang-standards/project-layout) seems workable, in essence:

```
tendermint/
    cmd/
        priv_validator/
        tendermint/
    pkg/
        blockchain/
        config/
        consensus/
        ...
    vendor/
```

**Comment by ebuchman** [comment]
Yes I like the project layout proposal.

Following up on the consolidation idea - we had some further discussion today. Here are some salient points:

- There are a number of things in `tmlibs` that should just move into Tendermint, like the `Service` and the Timers, the events package, and maybe more
- go-amino will stand alone as it's own repository
- go-crypto will move into tmlibs
- ABCI may or may not move into Tendermint

One significant concern raised was around versioning. A benefit of having separate repos is that they can be versioned and updated independently (of course there are drawbacks to this as well). For instance, suppose tmlibs/db moved to Tendermint, but it's also used by the SDK. If the SDK needs some update to it, then the SDK will be forced to use whatever else is in the latest Tendermint code. 

I think the action items (moving some items from tmlibs to Tendermint, and moving go-crypto to tmlibs) will be a significant help. We can continue to re-evaluate this down the road :)

**Comment by xla** [comment]
Doing it in small increments sounds like the least painful way. You hinted at the following:

* [service.go](https://github.com/tendermint/tmlibs/blob/master/common/service.go) -> tendermint/tendermint
* [repeat_timer](https://github.com/tendermint/tmlibs/blob/master/common/repeat_timer.go) -> tendermint/tendermint
* [throttle_timer.go](https://github.com/tendermint/tmlibs/blob/master/common/throttle_timer.go) -> tendermint/tendermint
* tendermint/go-crypto -> tendermint/tmlibs
* abci -> tendermint/tendermint ?

Anything else we immediately see being worth moving around?

**Comment by ValarDragon** [comment]
I think tendermint/go-wire would also be a good thing to merge into tmlibs. Last week there was an error when using the develop branch of go-crypto with the develop branch of go-wire, which merging the repos should hopefully solve.

**Comment by ValarDragon** [comment]
In my earlier comment I didn't realize that go-wire was just renamed to go-amino. 

I would also argue against one of the pros "develop branches can accumulate breaking changes without needing to update all dependents for them immediately". Last week I was trying add some stuff to go-crypto, and it was quite confusing that go-wire (now go-amino)'s develop branch was not what was needed for go-crypto's develop branch. I think merging more things into tmlibs will help alleviate this.

**Comment by ebuchman** [comment]
Basically anything that is only used by Tendermint should be moved into Tendermint. So this will also include:

- autofile
- clist
- events
- flowrate
- pubsub

> I think merging more things into tmlibs will help alleviate this.

I tend to agree, but we'll be keeping go-amino separate for now.

**Comment by tomc974** [comment]
@ebuchman I'm looking for some not too difficult tasks to start contributing to Tendermint. Is it ok for you if I take care of moving `autofile` and friends from `tmlibs` to `tendermint`? While doing so, should I use the new project layout (i.e. move them to `pkg` directory?)

**Comment by ebuchman** [comment]
Thanks @tomc974 but we're still discussing how to go about this, so might be best to be done by someone internally.

For instance I'm again thinking we should move the entire tmlibs to tendermint. Cutting hotfix releases of Tendermint with changes to tmlibs while ignoring whatever breaking thing is on develop is no more work than cutting releases of tmlibs independently of tendermint. In fact it will net out to less work. 

So again I don't see a strong benefit to have tmlibs in its own repo. Sure the SDK uses it, but it also uses Tendermint, and we find our selves in situations where we need to update both tmlibs and tendermint to get a fix into the SDK, which seems silly...

**Comment by xla** [comment]
@ebuchman Should we attempt this sooner than latter?

**Comment by ebuchman** [comment]
Discussed with @jaekwon. Let's move everything into tendermint except go-amino and tmlibs/db. tmlibs/db should be merged with IAVL into go-db (or maybe a better name ... bring back merkleeyes ?)

**Comment by ebuchman** [comment]
Tagging https://github.com/tendermint/go-crypto/issues/60 and https://github.com/tendermint/iavl/issues/46

**Comment by ebuchman** [comment]
Proposed folder structure for Tendermint:

```
- pkg
- docs
- cmd
- scripts
- networks
- test
- docker
```

**Comment by ebuchman** [comment]
Here are the steps to merge one repo into another:

- add the new repo as a remote, eg. `git remote add abci https://github.com/tendermint/abci`
- fetch the remote branches eg. `git fetch -a abci`
- checkout a new branch to do the dirty work, `git checkout -b merge-city`
- delete all the files ;) `git rm -rf ./* && git commit -m "delete everything"`
- merge the other repo `git merge --allow-unrelated-histories abci/develop`
- move it all into the right folder: `mkdir abci && git mv * abci && git commit -m "mv abci files to abci dir` ... (this will fail but the pseudo code is what matters ;) )
- revert the "delete it all commit"

TADA!

**Comment by zramsay** [comment]
this is done! see #1793 for dealing with the "fallout" from this move :)
