### ISSUE TITLE
p2p: Channels are JSON encoded as base64 byte string

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1310]
Channels are `[]byte` because they're literally an array of indivdiual bytes but we want to see the numbers themselves when json encoded not the garbage base64 string.

So maybe we just need to change to `[]int8` or even `[]int` ... 

Ie. see the /status output: `      "channels": "QCAhIiMwOAA=",`

**Comment by odeke-em** [comment]
@ebuchman we could improve this by defining a channel as a type and then override json.MarshalJSON and json.UnmarshalJSON methods such as as https://play.golang.org/p/GKrkeGCg8LI or inlined:

```go
package main

import (
	"encoding/json"
	"log"
	"reflect"
)

type Channel []byte

var _ json.Marshaler = (Channel)(nil)
var _ json.Unmarshaler = (*Channel)(nil)

type data struct {
	Channel1 []byte
	Channel2 Channel
	Name     string
}

func (c Channel) MarshalJSON() ([]byte, error) {
	return json.Marshal(string(c))
}

func (c *Channel) UnmarshalJSON(b []byte) error {
	var str string
	if err := json.Unmarshal(b, &str); err != nil {
		return err
	}
	*c = []byte(str)
	return nil
}

func main() {
	log.SetFlags(0)
	din := &data{Channel1: []byte("foo"), Channel2: []byte("foo"), Name: "test"}
	blob, err := json.Marshal(din)
	if err != nil {
		log.Fatalf("encoding: %v", err)
	}
	dout := new(data)
	if err := json.Unmarshal(blob, dout); err != nil {
		log.Fatalf("decoding: %v", err)
	}
	if !reflect.DeepEqual(dout, din) {
		log.Fatalf("\ngot= %+v\nwant=%+v\n", dout, din)
	}
}
```

**Comment by odeke-em** [comment]
Actually @ebuchman we can use common.HexBytes https://godoc.org/github.com/tendermint/tmlibs/common#HexBytes for this purpose.

**Comment by odeke-em** [comment]
I'll go with what is already implemented i.e. common.HexBytes and if need be we can switch to the JSONNiceBytes approach previously suggested.

**Comment by ebuchman** [comment]
heh - you were right. HexBytes is the simplest and possibly best thing to do here :)

Fixed in https://github.com/tendermint/tendermint/pull/1511
