### ISSUE TITLE
tendermint installing problem

### ISSUE THREAD

**Issue by hzl666123** [tendermint/tendermint#1316]
Cannot get a bunch of files when installing:

**Environment**:
- **OS** (e.g. from /etc/os-release): win-64bit
- **Install tools**:cmd
- **Others**:

**What happened**:
![image](https://user-images.githubusercontent.com/37364378/37453045-7681a7f0-2871-11e8-8c73-a65473ae1b8b.png)

looking forward to the reply.

**Comment by nuistzj2014** [comment]
I have the similar problem below:

->go get github.com/tendermint/tendermint/cmd/tendermint
->package github.com/tendermint/go-wire/data: cannot find package "github.com/tendermint/go-wire/data"

**Comment by Bric3d** [comment]
go-wire was renamed amino, and all dependencies broke.

**Comment by xla** [comment]
On `develop` this is fixed by #1314

**Comment by xla** [comment]
@hzl666123 Make sure you run `make get_vendor_deps` and use `make insall` for installation of the binaries.

**Comment by odeke-em** [comment]
Hello there @hzl666123, @xla provided a nice remedy in  https://github.com/tendermint/tendermint/issues/1316#issuecomment-373411718, please take a look.

**Comment by ebuchman** [comment]
Please use the Makefile commands, ie `make get_vendor_deps` and `make install` to install Tendermint.

Closing. Please re-open if still having issues.
