### ISSUE TITLE
ErrVoteInvalid 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1327]
Introduce ErrVoteInvalid type to clarify which errors result in disconnection from a peer.

```
type ErrVoteInvalid struct{
  *Vote
  msg string
}
```

See https://github.com/tendermint/tendermint/issues/1281

**Comment by melekes** [comment]
Note there is already `ErrAddingVote` 
https://github.com/tendermint/tendermint/blob/d0beaba7e8a5652506a34b5fab299cc2dc274c02/consensus/state.go#L587
which is basically `ErrVoteInvalid` except it does not hold vote pointer

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/2871
