### ISSUE TITLE
ensure vm conforms to YP spec

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#134]
eg. BALANCE should push 0 for nil account rather than throwing

**Comment by holiman** [comment]
I've spent a lot of time auditing the Ethereum VM mechanics, and there are some discrepancies. One example is that the Ethereum VM ensures that `JUMP` cannot jump into data-segments. I skimmed the tendermint source code, and it appear that tendermint would in fact allow that. Example:

     PUSH32 5b 5b 5b 5b ... JUMP 05

The current VM implementation would jump right into the data of `PUSH32`, which the Ethereum VM would not. From the YP, regarding `JUMPDEST` (page 11):

>All such positions must be on valid instruction boundaries, rather than sitting in the data portion of PUSH operations and must appear within the explicitly defined portion of the code (rather than in the implicitly defined STOP operations that trail it).

**Comment by jaekwon** [comment]
Hi Holiman, thanks for the heads up!

What about this line?

https://github.com/tendermint/tendermint/blob/develop/vm/vm.go#L913

**Comment by ebuchman** [comment]
Funny I was just talking to Vitalik about this Wednesday in the context of scalability; I believe its something they fixed around the time we ported the VM to tendermint. Jae, I think the point is that we allow the jumpdest to be in push data, which makes static analysis much harder / impossible. We may want to reconsider rebasing the current go-eth VM into tendermint to take advantage of some of the work theyve been doing over the last few months.

**Comment by holiman** [comment]
@jaekwon: the 5b in my example is the opcode for jumpdest, so the line would not stop it.

What they do is go through the program once and determine all valid jumpdests.

**Comment by jaekwon** [comment]
Oh yes.  Ok, lets see what it takes to pull out the go-eth VM as a standalone application.

**Comment by jaekwon** [comment]
Will go ahead with this soon.
