### ISSUE TITLE
Discuss potential tracing options for Tendermint 

### ISSUE THREAD

**Issue by t-bast** [tendermint/tendermint#1342]
Tracing makes it a lot easier to debug distributed systems.
A good introductory video of Jaeger that explains the concepts: https://blog.openshift.com/openshift-commons-briefing-82-distributed-tracing-with-jaeger-prometheus-on-kubernetes/

The way I use Tendermint (and I probably won't be the only one) is that I have a UI that calls a frontend service that accepts requests, will translate those into Tendermint transactions and broadcast them.
In some cases I might have multiple layers before it reaches Tendermint.
Then Tendermint will call my Tendermint App via the ABCI to commit blocks.
With a tracing system I'm currently able to trace everything up until it reaches Tendermint, then it's a black-box, then I can trace what happens when Tendermint calls my Tendermint App.

I think it would have a lot of value if Tendermint was able to accept and expose distributed traces.
The two main projects are currently [OpenCensus](https://opencensus.io/) and [OpenTracing](http://opentracing.io/), the most popular OpenTracing implementation seems to be Jaeger.

In the case of Tendermint is becomes very interesting because nodes can be controlled by different actors. But context propagation would allow us to have a deep insight into what's happening inside TM Core (and even across the whole Tendermint cluster), if there are current bottlenecks and if so where they are.

The design of tracing systems nicely decouples trace generation from data collection, so Tendermint could simply generate the data, propagate tracing context if present, and let end users choose which exporter they want to use (if they are interested in collecting those traces).

It's quite a bit of work and requires a good knowledge of the Tendermint codebase so I don't know who could work on that and when (or even if other people than myself are interested in something like that), but I thought it was worth starting a discussion.

**Comment by jackzampolin** [comment]
I think this is something @thanethomson is working on in his suite. Closing this in favor of that work
