### ISSUE TITLE
consensus: non-deterministic test failure halt

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1345]
https://circleci.com/gh/tendermint/tendermint/4765?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by melekes** [comment]
https://circleci.com/gh/tendermint/tendermint/4802

**Comment by ebuchman** [comment]
consensus tests just halt: 

https://circleci.com/gh/tendermint/tendermint/4886?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jackzampolin** [comment]
Closing, please reopen if there is a reproducible case.
