### ISSUE TITLE
lite, lite/errors: move a bunch of errors into lite/errors to make them sentinels and easily comparable

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#1360]
Suggested in https://github.com/tendermint/tendermint/pull/1300#discussion_r173808603 by @xla and advocated too by @ebuchman in https://github.com/tendermint/tendermint/pull/1300#pullrequestreview-105564057

Let's simplify the lite/errors package, improve the comparability of errors, figure out which we'd like to export and sentinelize them.

In the past though there has been pushback about which exporting errors and making them variables so perhaps let's select the most meaningful and common errors and export those.

**Comment by jackzampolin** [comment]
This will get handled in the currently in-progress refactor of the lite client.
