### ISSUE TITLE
Questions about gossip layer

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#1365]
1. In RoundState we don't keep information about proposals from previous rounds (except the
locked block), only votes. So if we are at round 7, and our peer is at round 5,
what is a point in sending him messages from round 5 as we can't provide
him a proposal from round 5?

2. In case a peer is at the smaller round, Gossip Data Routine can only send
him block parts in case PartSetHeader is the same. Otherwise, if a node is
lagging behind we don't do anything. The routine goes to sleep mode. So why we don't try to bring him to a higher round (our current round)?

3. In case a peer is lagging behind (at a smaller height), we are sending them block parts, but not
those that are decided but those that corresponds to a peer current
Proposal message (based on peer round state), which might be completely wrong. But we know the decided block at this point so why we don't send parts from that block? I guess the reason is that this is (based on current implementation) seen as incorrect behaviour as we don't know what our peer is sending us. Maybe we should be thinking about splitting data distribution from consensus logic. A node can just post partset headers for values he is interested in and then
peers can provide corresponding blocks. Height could be used there just to
prioritise what block parts to send first. In case we know the decided block
and peer is not yet aware of the committed block, we need to have a mechanism to inform our peer that he is interested in block parts from that committed block.

4. Gossip vote routine: https://github.com/tendermint/tendermint/blob/develop/consensus/reactor.go#L683
 If our peer is in a bigger round than we are, we don't send
any message to him. In a gossip mesh this will block messages from higher round
to pass through before a peer is brought up to speed. Does this make sense?
Our ultimate goal at the gossip layer is ensuring validators can communicate timely. The current logic does not necessarily reflect this.

**Comment by ebuchman** [comment]
1.  Remember Votes aren't for proposals, they're for blocks. So you don't need to see the proposal to commit. Once you see +2/3 precommits for a block, you'll start trying to fetch the block parts directly, so you never need the proposal.

Here's how it happens. we receive +2/3 precommits, and go to enterCommit, but we detect that we don't have a proposal block, so we set up to get it: https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1126

Then we fire our CommitStepMessage and tryFinalize will run. The tryFinalize will fail, but the CommitStepMessage will cause the peer to update its prs for us to note that we have the proposal block: https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L1231

The the peer will prioritize sending us block parts: https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L497

Isn't that something ?!

On a related note, we do need to put the proposer in the header, and we may need a way to check that the block we're committing was proposed by the right proposer (if not, it means +2/3 are fraudulent, but it would still be good to know ...).

2. I think the answer to (1) addresses it, though we might be able to do something much more efficient here with a good round-skipping system ...

3. It should be rare that a peers at an old height and seeing proposals from the incorrect round there. But in any case, they'll soon see +2/3 precommit for the height, that will cause them to update their proposal block, and then they'll start receiving it (same mechanism as (1) ). 

> Maybe we should be thinking about splitting data distribution from consensus logic. A node can just post partset headers for values he is interested in and then
peers can provide corresponding blocks ...  In case we know the decided block
and peer is not yet aware of the committed block, we need to have a mechanism to inform our peer that he is interested in block parts from that committed block.

Currently the RoundStep/CommitStepMessages is used to say "hey I'm looking for this block". And the way you tell a node they're looking for a committed block is by getting them the +2/3 precommits, and then they'll want it and ask for it. It might be tricky to better separate the block and vote sharing systems, but it could make things easier to understand.

4. The idea with this system is to only forward information other validators need, so if you're ahead of me in a rounds, there isn't really anything of particular value I can give you, I don't think. Well, other than possibly detecting a +1/3 fork (ie. a commit at a previous round). Probably need to consider that re https://github.com/tendermint/tendermint/issues/200, so thanks for raising

**Comment by milosevic** [comment]
>> Here's how it happens. we receive +2/3 precommits, and go to enterCommit, but we detect that 
>>  we don't have a proposal block, so we set up to get it:
 >> https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1126

>> Then we fire our CommitStepMessage and tryFinalize will run. The tryFinalize will fail, but the 
>> CommitStepMessage will cause the peer to update its prs for us to note that we have the 
>> proposal block: 
>> https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L1231

>> The the peer will prioritize sending us block parts: 
>> https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L497

>> Isn't that something ?!

This is true. However, note that the peer will send us block parts by L497 only if a peer hasn't progress to a new height in which case it will reset rs.ProposalBlockParts. But it will keep providing data using https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L514, although slower as it will need to touch the disc for each part so it will be much slower than the part with L497. We might want to try to maximise sending block parts while it is still in the memory (maybe reset Proposal earlier, for example as soon as it sees Precommit message for a different value or when it sees Polka for a different value), or keep data in memory for some time while we are at L497 in case we are helping peer to catch up.

**Comment by xla** [comment]
@milosevic Are parts of this still relevant or can we close it? If not what actionable items we have that we could turn into issues?

**Comment by xla** [comment]
@milosevic Are parts of this still relevant or can we close it? If not what actionable items we have that we could turn into issues?

**Comment by milosevic** [comment]
@xla It can be closed. The important thing is that we need to improve gossip protocol to ensure faster catchup in case a peer is lagging behind in terms of rounds. I will create an issue, just need to clarify few more things before.

**Comment by ebuchman** [comment]
Shall we close?
