### ISSUE TITLE
Subscribe on delivertx tag doesn't work

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#1369]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.16.0-c8a2bdf7

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

https://github.com/confio/weave
(mycoind)

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.4
- **Install tools**:
- **Others**:

**What happened**:

I add tags to my custom app on DeliverTx, and search for them over rpc.
Works well.

I subscribe to those same tags with `/subscribe` and never get notified.
If I subscribe to all tx with `/subscribe`, it does work...

**What you expected to happen**:

I expected the behavior documented in the godoc:

```
// Tendermint provides a few predefined keys: tm.event, tx.hash and tx.height.
// Note for transactions, you can define additional keys by providing tags with
// DeliverTx response.
//
//		DeliverTx{
//			Tags: []*KVPair{
//				"agent.name": "K",
//			}
//	  }
//
//		tm.event = 'Tx' AND agent.name = 'K'
//		tm.event = 'Tx' AND account.created_at >= TIME 2013-05-03T14:45:00Z
//		tm.event = 'Tx' AND contract.sign_date = DATE 2017-01-01
//		tm.event = 'Tx' AND account.owner CONTAINS 'Igor'
```

I found nice unit tests for search, which worked well, but not for subscriptions.

**How to reproduce it** (as minimally and precisely as possible):

You can work through the demo on https://github.com/confio/weave-js/blob/master/README.md

The error is in the last section "Searching and subscribing to tx", of course, you need to run the server locally and create a few tx first....

If I search with query: `cash='0918829CE2E3B4F0B1B61EB2309E311CF496199D'`, I get a list of transactions that modified the wallet belonging to that address.

If I subscribe with query: `tm.event = 'Tx'` before sending a Tx, I get the tx as desired.

If I subscribe with query `tm.event = 'Tx' AND cash='0918829CE2E3B4F0B1B61EB2309E311CF496199D'`, I never get an event.

Since the given tx matches on search with that string, and clearly generates and event, and we are supposed to be able to subscribe based on the DeliverTx tags, I would expect a callback from this as well.

**Anything else do we need to know**:

I showed it to @melekes personally, assuming I was doing something wrong and needed another keyword or two, and he said I seemed to be doing it right, but tendermint rpc seemed to have broken.

**Comment by ethanfrey** [comment]
From config.toml:

```
# Comma-separated list of tags to index (by default the only tag is tx hash)
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags. Note this may be not
# desirable (see the comment above). IndexTags has a precedence over
# IndexAllTags (i.e. when given both, IndexTags will be indexed).
index_all_tags = true
```

These tags must be indexed as the queries returned matches in `/tx_search`.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/f699b5b6270e1196a7c3867811078456dc39a608/types/event_bus.go#L104

this may be it... before it used to be the string, so string("account") -> "account". But now it's []byte, so string([]byte{base 64 encoded string}) -> "Xn(_N" or something like that

**Comment by ethanfrey** [comment]
ahhh.... good call.

**Comment by melekes** [comment]
So, during last Christmas we changed KVPair keys and values to be just []byte arrays https://github.com/tendermint/abci/pull/167.

> Perhaps using []byte makes us more vigilant in validating the input before accepting it

right now there is no validation at all! so we'll need to add that. maximum we can do is limit the max key and value sizes.

right now we assume that both key and value are strings or can be converted to strings

https://github.com/tendermint/tendermint/blob/6a1f550611180d9e6432473570f0b59246b12169/state/txindex/kv/kv.go#L384

this change fixes the issue above

https://github.com/tendermint/tendermint/blob/6a1f550611180d9e6432473570f0b59246b12169/types/event_bus.go#L104

but numbers still don't work right now `{Key: []byte("bar"), Value: []byte("1")}`

yields

```
panic: Incomparable types: []uint8 ([49]) vs int64 (1)

goroutine 22 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub/query.match(0xc42006489a, 0x3, 0x945104, 0x9451a0, 0xc4208b1870, 0x86, 0xc4205f92f0, 0xc420064701)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub/query/query.go:313 +0xc7a
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub/query.(*Query).Matches(0xc4208d20c0, 0xc4205f92f0, 0xc4200254f8)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub/query/query.go:202 +0x3ed
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub.(*state).send(0xc4200257d0, 0x9b5d00, 0xc4208ad900, 0xc4205f92f0)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub/pubsub.go:290 +0xc1
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub.(*Server).loop(0xc4208af8f0, 0xc4205f9020, 0xc4205f9050)
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub/pubsub.go:230 +0x153
created by github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub.(*Server).OnStart
        /home/vagrant/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/pubsub/pubsub.go:205 +0xad
exit status 2
```

to be continued...

**Comment by ethanfrey** [comment]
The major use case for tags right now i watching a wallet.
If we tell devs to hex-encode the wallet address before adding it to the tag, then it can work with the string tag match.

That should be enough for devs (also gaiad) to get basic subscriptions working, while a larger fix with support for more types is discussed.

And yes, the key and value must both be legal values to parse in the query string.

**Comment by melekes** [comment]
Let's wait for @jaekwon to comment on this.

My proposal is to bring back types as `TypedKVPair`

```
type TypedKVPair struct {
  string key
  enum valueType {
    string 1
    int 2
    ...
  }
  string valueString
  string valueInt
```

I am still wondering about the benefits of []byte in this case

1) app sends us kvpair as bytes
2) we store these bytes (no limit for size)
3) when we try to match, we do our best to guess the type and panic if something is wrong

As opposite to what I’ve done initially:

1) app sends us tags constrained by protobuf types
2) we store them
3) no problems while matching

One more thought on this. We probably don't want people putting random things in tags (like smart contracts or whatever). Tags are supposed to be small units of data we use to tag transactions and match queries against.

**Comment by melekes** [comment]
Ok, we discussed this with Jae and decided to try and work around strings right now (given necessary type conversions "string" -> int, "string" -> date for example). "For plugin-indexers, we can configure the index to be optimized for the expected type… I think that’s where the performance matters more."

Other options that were discussed:

* use protobuf3 like STPair, or use Amino the same way but also skip encoding 0's.
```
type STPair struct {
  key string
  value TypedValue
}

type TypedValue struct {
  Int64 *int64
  String *string
}
```

## Perfomance analysis

Protobuf3 takes like 300 ns to parse a simple KVPair anyways.
```
func BenchmarkUnmarshalProtobuf(b *testing.B) {
    b.StopTimer()
    kv := &KVPair{
        Key:       "something",
        ValueType: 2,
        ValueInt:  1234,
    }
    out, err := proto.Marshal(kv)
    if err != nil {
        b.Error(err)
    }
    kv2 := &KVPair{}
    b.StartTimer()

    for i := 0; i < b.N; i++ {
        err := proto.Unmarshal(out, kv2)
        if err != nil {
            b.Error(err)
            return
        }
    }

}

func BenchmarkUnmarshalProtobuf2(b *testing.B) {
    b.StopTimer()
    kv := &KVPair2{
        Key:   "something",
        Value: "1234",
    }
    out, err := proto.Marshal(kv)
    if err != nil {
        b.Error(err)
    }
    kv2 := &KVPair2{}
    b.StartTimer()

    for i := 0; i < b.N; i++ {
        err := proto.Unmarshal(out, kv2)
        if err != nil {
            b.Error(err)
            return
        }
        _, err = strconv.Atoi(kv2.Value)
        if err != nil {
            b.Error(err)
            return
        }
    }

}
```

```
BenchmarkUnmarshalProtobuf-4         5000000           298 ns/op
BenchmarkUnmarshalProtobuf2-4        5000000           312 ns/op
```

test2 uses KVPair2 which is just string key and string value.
They’re basically the same performance wise.
Atoi takes at most 50ns or so, 25ns for short numbers. Date parsing will take longer...
