### ISSUE TITLE
Unable to connect to testnet

### ISSUE THREAD

**Issue by jarvis18** [tendermint/tendermint#1383]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

No information on connecting to testnet 

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):0.16.0-c8a2bdf7

**ABCI app** (name for built-in, URL for self-written if it's publicly available):self-written

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release):Linux 16.04
- **Install tools**:tendermint,gaia,cosmos

**What happened**:Couldn't connect to testnet

**What you expected to happen**:I expected to connect to already existing testnet

**How to reproduce it** (as minimally and precisely as possible):Try connecting to testnet

**Logs (you can paste a part showing an error or attach the whole file)**:
panic: Panicked on a Crisis: open mytestnet/mach0/config/513716239: no such file or directory
goroutine 1 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.PanicCrisis(0xb9c2c0, 0xc420972330)
	/var/lib/jenkins/workspace/03.Build.Package/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/errors.go:35 +0xf3

**`/dump_consensus_state` output for consensus bugs** :can't find

**Anything else do we need to know**:From @Sentinelgroup

**Comment by melekes** [comment]
Thank you for reporting this! The problem has been fixed in 0.17. Please give it a go. If the error persists, be sure to reopen this issue.

**Comment by melekes** [comment]
See https://github.com/tendermint/tendermint/issues/1290 for details.

**Comment by jarvis18** [comment]
Is there a global testnet running or the "tendermint testnet" works just to create our own testnet
