### ISSUE TITLE
Most recent docker build on docker hub is 0.15

### ISSUE THREAD

**Issue by coriolinus** [tendermint/tendermint#1388]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.16.0, 0.17.0, 0.17.1

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
N/A

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):
N/A

**Environment**:
- **OS** (e.g. from /etc/os-release):
    N/A
- **Install tools**:
    N/A
- **Others**:
    N/A

**What happened**:
<https://hub.docker.com/r/tendermint/tendermint/> shows releases only up to 0.15

**What you expected to happen**:
That link includes proper Dockerfiles for 0.16.0, 0.17.0, 0.17.1

**How to reproduce it** (as minimally and precisely as possible):
Visit the link

**Anything else do we need to know**:

This looks like it may duplicate #1288, but the desired resolution is a bit different. Agree that auto-building proper dockerfiles per release is a best practice and the way of the future, but there's real work happening in the meantime. Until that's all set up, I'd like it if someone were to manually add proper Dockerfiles for at least 0.16.0 and 0.17.1.

**Comment by melekes** [comment]
Since I can't do that anymore, I am gonna assign @greg-szabo :)

**Comment by melekes** [comment]
Done. https://hub.docker.com/r/tendermint/tendermint/tags/
