### ISSUE TITLE
`show_node_id` should return error if TM home is not initialized

### ISSUE THREAD

**Issue by kidinamoto01** [tendermint/tendermint#1393]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

v0.17.1
**ABCI app** (name for built-in, URL for self-written if it's publicly available):

-
**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): macOs
- **Install tools**: dep
- **Others**:

**What happened**:
when I set --home to some non-existent folder, node id is still displayed on the screen.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

tendermint show_node_id --home=~/.gaia4

**Logs (you can paste a part showing an error or attach the whole file)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:
`show node id`command should give hint on wrong home path rather just generate a random key.

**Comment by ebuchman** [comment]
Hmm, the default behaviour for Tendermint if no home folder exists is to create one with a default config and node key. If you then later run `tendermint init`, it will not override the node_key, but will generate the priv_validator and genesis for you.

Sounds like you're suggesting that all `tendermint` commands (except `tendermint init`) should fail if the home dir doesn't exist.

**Comment by kidinamoto01** [comment]
yes, we must initialize `tendermint`before running other `tendermint` commands

**Comment by melekes** [comment]
Fixed on develop.
