### ISSUE TITLE
tendermint CGO_ENABLED not explicitly set

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#1395]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report.

## Expected behaviour:
A binary built on one linux_amd64 system can run on another linux_amd64 system. (Static linking.)

## Current behaviour:
A binary built on one linux_amd64 system might not run on another linux_amd64 system. (Dynamic linking.)

## Description:

The build is kicked off with `make build`.

Although we don't use CGO in the tendermint code (AFAIK), it is not explicitly disabled. This becomes apparent when you build the binary on alpine linux.

```
~/go/src/github.com/tendermint/tendermint # ldd /x/tendermint/tendermint_alpine37
	/lib/ld-musl-x86_64.so.1 (0x7f9f63b98000)
	libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f9f63b98000)
```

Alpine linux links to its own muslC library which is not available in Ubuntu or CentOS, hence the binary is not portable.

The current automation builds the binary in CentOS, which uses glibc (together with Ubuntu and other distributions):

```
[root@centos test]# ldd tendermint/tendermint_6f9956990c444d53f62f2a3905ed410cfe9afe77_linux_amd64
	linux-vdso.so.1 =>  (0x00007ffcd8767000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f1c7b56b000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f1c7b1a8000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1c7b791000)
```

When `CGO_ENABLED=0` is explicitly set, the CentOS/Ubuntu build process statically links the binary and makes it compatible with Alpine.

## Solution:
Add `CGO_ENABLED=0` in the`Makefile` `build` target.

**Comment by melekes** [comment]
Thanks Greg!
