### ISSUE TITLE
phantom peers

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1402]
Seems its still the case sometimes that even after a peer disconnects we don't notice and they hang around in our peers list and show up in `/net_info`.

Observing this on the latest testnet.

**Comment by ebuchman** [comment]
I wonder if this might be solved by https://github.com/tendermint/tendermint/pull/1687 ?

**Comment by xla** [comment]
Let's close until re-appears.

**Comment by xla** [comment]
Test for in #1744
