### ISSUE TITLE
Failed to authenticate peer. Dialed 0.0.0.0:46656, but got peer with ID...

### ISSUE THREAD

**Issue by ArvonHuang** [tendermint/tendermint#1408]
I executed cmds as below ：
```
tendermint node --consensus.create_empty_blocks=false --proxy_app=127.0.0.1:46659 --rpc.laddr=tcp://0.0.0.0:46657 --p2p.laddr=tcp://0.0.0.0:46656 --p2p.seeds=tcp://0.0.0.0:46656,tcp://0.0.0.0:36656,tcp://0.0.0.0:26656,tcp://0.0.0.0:16656 --home=/usr/local/softwares/mytestnet/mach0

tendermint node --consensus.create_empty_blocks=false --proxy_app=127.0.0.1:46659 --rpc.laddr=tcp://0.0.0.0:36657 --p2p.laddr=tcp://0.0.0.0:36656 --p2p.seeds=tcp://0.0.0.0:46656,tcp://0.0.0.0:36656,tcp://0.0.0.0:26656,tcp://0.0.0.0:16656 --home=/usr/local/softwares/mytestnet/mach1

tendermint node --consensus.create_empty_blocks=false --proxy_app=127.0.0.1:46659 --rpc.laddr=tcp://0.0.0.0:26657 --p2p.laddr=tcp://0.0.0.0:26656 --p2p.seeds=tcp://0.0.0.0:46656,tcp://0.0.0.0:36656,tcp://0.0.0.0:26656,tcp://0.0.0.0:16656 --home=/usr/local/softwares/mytestnet/mach2

tendermint node --consensus.create_empty_blocks=false --proxy_app=127.0.0.1:46659 --rpc.laddr=tcp://0.0.0.0:16657 --p2p.laddr=tcp://0.0.0.0:16656 --p2p.seeds=tcp://0.0.0.0:46656,tcp://0.0.0.0:36656,tcp://0.0.0.0:26656,tcp://0.0.0.0:16656 --home=/usr/local/softwares/mytestnet/mach3
```

and i got problem 

key log is 
`I[04-03|08:45:49.328] Dialing peer                                 module=p2p address=0.0.0.0:26656
E[04-03|08:45:49.339] Failed to dial peer                          module=p2p address=0.0.0.0:26656 err="Failed to authenticate peer. Dialed 0.0.0.0:26656, but got peer with ID 08ee388c55db7e6ddc127e604d3b1ed271946670"
E[04-03|08:45:49.339] Error dialing seed                           module=p2p err="Failed to authenticate peer. Dialed 0.0.0.0:26656, but got peer with ID 08ee388c55db7e6ddc127e604d3b1ed271946670" seed=0.0.0.0:26656
I[04-03|08:45:49.339] Dialing peer                                 module=p2p address=0.0.0.0:36656
E[04-03|08:45:49.344] Failed to dial peer                          module=p2p address=0.0.0.0:36656 err="Failed to authenticate peer. Dialed 0.0.0.0:36656, but got peer with ID 8cba4a221a1afb15267a223423e5e8bd32c33378"
E[04-03|08:45:49.344] Error dialing seed                           module=p2p err="Failed to authenticate peer. Dialed 0.0.0.0:36656, but got peer with ID 8cba4a221a1afb15267a223423e5e8bd32c33378" seed=0.0.0.0:36656
I[04-03|08:45:49.344] Dialing peer                                 module=p2p address=0.0.0.0:16656
E[04-03|08:45:49.380] Failed to dial peer                          module=p2p address=0.0.0.0:16656 err="Failed to authenticate peer. Dialed 0.0.0.0:16656, but got peer with ID 271e3dd3c928bf867971fa956392b264916087e2"
E[04-03|08:45:49.380] Error dialing seed                           module=p2p err="Failed to authenticate peer. Dialed 0.0.0.0:16656, but got peer with ID 271e3dd3c928bf867971fa956392b264916087e2" seed=0.0.0.0:16656
I[04-03|08:45:49.380] Dialing peer                                 module=p2p address=0.0.0.0:46656
I[04-03|08:45:49.396] Ignoring inbound connection: error while adding peer module=p2p address=127.0.0.1:33550 err="Error during handshake/write: write tcp 127.0.0.1:16656->127.0.0.1:33550: write: broken pipe"
E[04-03|08:45:49.404] Failed to dial peer                          module=p2p address=0.0.0.0:46656 err="Failed to authenticate peer. Dialed 0.0.0.0:46656, but got peer with ID 99b886c236af33f5050881610ec34c98885df0f5"
E[04-03|08:45:49.404] Error dialing seed                           module=p2p err="Failed to authenticate peer. Dialed 0.0.0.0:46656, but got peer with ID 99b886c236af33f5050881610ec34c98885df0f5" seed=0.0.0.0:46656
E[04-03|08:45:49.404] Couldn't connect to any seeds                module=p2p 
`

can anyone help to fix this problem? Thx very much

**Comment by ArvonHuang** [comment]
The version is v0.17.16f99569

**Comment by ArvonHuang** [comment]
i have read change log of 0.17 and found that 
`[p2p] when auth_enc is true, all dialed peers must have a node ID in their address`
so i set auth_enc  to false in config.toml and i can start tm peers seccussfully.

however , if i leave auth_enc default , how can i  start tm peers seccussfully.

thx.

**Comment by melekes** [comment]
You need to prepend each peer with it's ID respectively:

```
tendermint node --consensus.create_empty_blocks=false --proxy_app=127.0.0.1:46659 --rpc.laddr=tcp://0.0.0.0:46657 --p2p.laddr=tcp://0.0.0.0:46656 --p2p.seeds=tcp://99b886c236af33f5050881610ec34c98885df0f5 @0.0.0.0:46656,tcp://8cba4a221a1afb15267a223423e5e8bd32c33378 @0.0.0.0:36656,tcp://08ee388c55db7e6ddc127e604d3b1ed271946670@0.0.0.0:26656,tcp://271e3dd3c928bf867971fa956392b264916087e2@0.0.0.0:16656 --home=/usr/local/softwares/mytestnet/mach0
```

**Comment by Deegrin** [comment]
Is there any other way to get the node ID? I've been using a script that initializes with `tendermint node` and then reading/writing the configuration files from there.
