### ISSUE TITLE
Fixes to and for Light Client Spec

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1413]
Light Client spec has been merged: https://github.com/tendermint/tendermint/pull/1336

The following remain TODO:

- [ ] update how the spec handles the UNBONDING PERIOD (need a new condition so if unbonding period has passed, we flame out and revert back to social consensus to get a new validator hash)
- [ ] implement the LastHeader RPC call in Tendermint, or provide a convenience function to simulate it, so we can get the latest header with a given validator height
- [x] change the validator change mechanism so the validator set changes at H+2 (instead of H+1) for changes returned during block H
- [ ] possibly improve the notation/clarity in the spec, especially around global mutable variables vs local variables

**Comment by jackzampolin** [comment]
Still need the lite client spec. This should get prioritized.
