### ISSUE TITLE
broadcast_tx_sync

### ISSUE THREAD

**Issue by Ajita24** [tendermint/tendermint#1415]
Hello
I am in study phase of tendermint and abci applications.
I am unable to understand that how the endpoints broadcast_tx_async and broadcast_tx_sync dealt with? I am using kvstore as a abci and successfully send transaction using the broadcast APIs i.e these two endpoints as stated in http://tendermint.readthedocs.io/projects/tools/en/master/using-tendermint.html?highlight=api  , but please guide as to where is the actual code(api code) for these endpoints which is executed.

Please guide. Some help would be highly appreciated.

**Comment by melekes** [comment]
Hey @Ajita24! The code for broadcast_* RPC endpoints can be found here https://github.com/tendermint/tendermint/blob/7a5060dc520e1b014570bd15e3f15c4f6f3f8d66/rpc/core/mempool.go

Hope that helps!

Also, you can ask such questions in our chat https://riot.im/app/#/room/#cosmos:matrix.org. Please join!
