### ISSUE TITLE
Tendermint's rpc api docs

### ISSUE THREAD

**Issue by SaifRehman** [tendermint/tendermint#1416]
Can I please get documentation of tendermint's rpc api, what each one does etc. 
@ebuchman

**Comment by melekes** [comment]
Duplicate of #691

**Comment by melekes** [comment]
@SaifRehman wanna help us out with #691 ?

**Comment by SaifRehman** [comment]
of course yes! how do i contribute with the docs?

**Comment by melekes** [comment]
There is no docs, so you'll have to create them. You can find an example here https://github.com/hypothesis/h/tree/master/docs/_extra/api-reference ([how it looks](https://h.readthedocs.io/en/latest/api-reference/))

**Comment by SaifRehman** [comment]
cool, ill take on this!

**Comment by zramsay** [comment]
@SaifRehman track #691, we should have a well-documented RPC within a week
