### ISSUE TITLE
state: save initial validator set

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1418]
See new RPC functionality: https://github.com/tendermint/tendermint/pull/1391/files#diff-01c03d72f0bd4f05ffc5f13d12361244R100

Apparently we can't just call sm.LoadValidators because if we do before the first block we get a panic since the initial validators aren't present.

If we save the initial validator set, then we can simplify that logic and just call LoadValidators instead of first checking cs.GetValidators

**Comment by cmwaters** [comment]
I'm closing this because I don't think it is relevant anymore. The state store will throw an error instead of panicking which is then handled by the RPC. Speak up if you disagree
