### ISSUE TITLE
[pubsub/query] jsquery query language

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1421]
See https://github.com/tendermint/tendermint/pull/835#issuecomment-347034138

https://github.com/postgrespro/jsquery

**Comment by jackzampolin** [comment]
I think with the postgres indexing issue and @alexanderbez 's work on the GraphQL server we can close this.

**Comment by melekes** [comment]
This is independent from indexing.

**Comment by tessr** [comment]
@melekes is this something you still think we should do?

**Comment by melekes** [comment]
probably not
