### ISSUE TITLE
Different app hash for same block

### ISSUE THREAD

**Issue by kansi** [tendermint/tendermint#1422]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Documentation request.

### Description
During the commit phase the ABCI proxy app returns the "app_hash" to Tendermint. It unclear from the docs how tendermint uses this app hash apart from re-syncing/re-playing the blocks on the ABCI proxy app. More specifically, is it necessary that each node return the same app hash for a given block `B1`. 

#### Consider the following scenario
Consider a sitatution where the network wishes to upgrade their ABCI proxy app from `v1.0` to `v2.0` wherein for a given block `B1` the `v1.0` returns a different app hash as compared to `v2.0`. So,  different nodes might return a different app hash depending on their ABCI proxy app version (i.e. `v1.0` or `v2.0`)

It is unclear as to how Tendermint will behave under such a circumstance?

NOTE: If I have missed some documentation kindly point me towards the same.

**Comment by ebuchman** [comment]
Yes it's critical that they return the same app hash. If not, they will not be able to agree on the next block, because the AppHash returned by Commit is included in the next block!

**Comment by melekes** [comment]
https://github.com/tendermint/abci/pull/227
https://github.com/tendermint/tendermint/pull/1468
