### ISSUE TITLE
Suggestions for improving consensus rate in Tendermint core

### ISSUE THREAD

**Issue by ragjunk** [tendermint/tendermint#1426]
**This is a suggestion for improvement**

Here's a proposal, courtesy of @StorecoinTeam, to minimize the peer-to-peer communication overhead in the Tendermint core. It leverages Tendermint's ABCI protocol to implement a "shared mempool" where the nodes collaboratively "order" incoming transactions. During the consensus round, the proposer dequeues the transactions from the shared mempool. The proposal is available here - https://github.com/StorecoinProject/Basil

**Comment by cloudinertia** [comment]
In order to maintain "shared mempool", there still needed tendermint-like consensus for verify it. 

> But such malicious behavior is easy to detect because the malicious peer would produce a longer sequence in a given period of time (such as between consensus rounds) compared to the honest peers. (from https://github.com/StorecoinProject/Basil)

I think it's to weak statement. As a common user, I want more noble reasoning such as "shared mempool is about N times faster than original one" or "from logical argument we can trust shared mempool at certain condition".

**Comment by ragjunk** [comment]
> In order to maintain "shared mempool", there still needed tendermint-like consensus for verify it.
Please see the approach described in the proposal, which uses a sequence of sha256 hashes to "order" transactions. Each validator node runs this sequence independent of others. As each node receives transactions, it "embeds" it in the sequence and writes it to the shared mempool. Each entry in the shared mempool is also signed by respective validators, so it can be associated with who created that entry. The proposer can simply walk the sequence to retrieve the ordered transactions from multiple validators. This requires no additional consensus.

> I think it's too weak statement.
Assume each of the N validator nodes receives one transaction. In the original TM core, each node broadcasts the transactions to all other nodes, resulting in (N^2 - N) messages. For example, if N  = 5, there will be 20 messages. In this approach, each validator nodes writes to shared mempool, so there will be only N messages. Of course, there is a "local computation" required to create the sequence, which is not there in the original TM core. But unstable communication is generally what drags the performance down.

While not mentioned in the proposal, this behavior can be completely optional. If the specific ABCI interfaces are implemented, TM core uses it; otherwise it falls back to existing behavior.

**Comment by ebuchman** [comment]
I don't understand why it's called "Shared Mempool". 

Currently, everyone broadcasts all mempool txs, so with enough time, everyone will see the same txs, though its possible they'll see them in different orders.

In this proposal, it looks like the nodes don't gossip the mempool transactions at all. Why would the resulting mempool be called "shared" if the transactions aren't being shared?

**Comment by ebuchman** [comment]
Why is it called a shared mempool if nothing is being shared?

**Comment by ebuchman** [comment]
Thanks for this - in an effort to clean up our issues, I'm going to close this for now. 

Later this year we will revisit options for optimizing the consensus.

Thanks!
