### ISSUE TITLE
Issue while Setting up Tendermint and abci

### ISSUE THREAD

**Issue by Ajita24** [tendermint/tendermint#1427]
Hello

I cloned the tendermint code and setup the abci also.
While creating a p2p connection between two servers with this command:

`Tendermint command: tendermint node --p2p.persistent_peers=18.xxx.xxx.xx:46656,18.xxx.xxx.xxx:46656`

Both server have genesis.json compiled with both server public keys

 I am facing this issue:
`I[04-06|12:22:15.281] Dialing peer  module=p2p address=18.194.143.153:46656
E[04-06|12:22:15.283] Failed to dial peer module=p2p address=18.194.143.153:46656 err="Failed to authenticat peer. Dialed 18.194.143.153:46656, but got peer with ID a2db1baac0329361133fe61aba6436e90d93c4fe"
E[04-06|12:22:15.283] Error dialing seed   module=p2p err="Failed to authenticate peer. Dialed 18.194.143.15346656, but got peer with ID a2db1baac0329361133fe61aba6436e90d93c4fe" seed=18.194.143.153:46656
E[04-06|12:22:15.283] Couldn't connect to any seeds  module=p2p
I[04-06|12:22:15.283] Ignoring inbound connection: error while adding peer module=p2p address=18.194.143.153:36302 err="Error during andshake/read: EOF"`

https://www.screencast.com/t/3TJKMSVZU3

Please guide.

**Comment by melekes** [comment]
Yes, so you either need to set `auth_enc` to `false` in `config.toml` (_note this is only recommended if you use VPN in production_) OR prefix all the host:port pairs with respective ID (which can be obtained by running `tendermint show_node_id`).
