### ISSUE TITLE
Addrbook.json is not filled

### ISSUE THREAD

**Issue by eeonevision** [tendermint/tendermint#1434]
PEX is true.
Three peers were found and connected successfully.
<img width="449" alt="screen shot 2018-04-08 at 3 43 17 pm" src="https://user-images.githubusercontent.com/4333321/38468508-c43dfa52-3b4f-11e8-9c10-7288fbb7edfc.png">

**Comment by eeonevision** [comment]
So, maybe I didn't understood right, but if I started third peer node with defined in p2p.persistent_peers two other nodes, they should be appeared in addrbook?

**Comment by ebuchman** [comment]
Yes they should

**Comment by eeonevision** [comment]
Hm, I connected the peers with
```
 --p2p.persistent_peers=e5f85ef6e11dc3f8028b5798d8bab3f22c338936@ip:port,18ac756356409b0a03406b90017cf6879aa9bbd8@ip:port,5573601e54b49d8a78319262b53292d1243d761d@ip:port
```

but the addrbook is still empty.
```
{
	"key": "b4952be708709f8aebf7fcdb",
	"addrs": []
}
```
parts of config:
```
# Path to address book
addr_book_file = "config/addrbook.json"

# Set true for strict address routability rules
addr_book_strict = true

# Set true to enable the peer-exchange reactor
pex = true
```

What's wrong?

**Comment by eeonevision** [comment]
log:
```
leadschain-validator-develop    | I[04-11|12:56:40.683] Saving AddrBook to file                      module=p2p book=/tendermint/config/addrbook.json size=0
leadschain-validator-develop    | I[04-11|12:57:10.681] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=3 numDialing=0 numToDial=10
leadschain-validator-develop    | I[04-11|12:57:10.681] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{172.16.8.220:49870} 4b3471dc20af61bedd0b2ca0d06ebdb08e87107e in}"
leadschain-validator-develop    | I[04-11|12:57:40.681] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=3 numDialing=0 numToDial=10
leadschain-validator-develop    | I[04-11|12:57:40.681] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{172.16.8.230:38486} 92be39d5367bdb5e36cfb936d7fb457da5f21bc7 in}"
```

**Comment by melekes** [comment]
Do you see lines like "Added new address"?

**Comment by eeonevision** [comment]
Only "added our address to addrbook.json", but file is still empty

**Comment by melekes** [comment]
I will investigate tomorrow.

**Comment by eeonevision** [comment]
I have no other logs, except the row: "... add our address to addrbook..."

**Comment by melekes** [comment]
Please make sure your addresses are routable https://github.com/tendermint/tendermint/blob/c0610b2c3273144be09db263fe073477e7de56f3/p2p/netaddress.go#L200. Otherwise, you can turn this check by setting `addr_book_strict` to `false`

**Comment by eeonevision** [comment]
Thanks! I use internal network, that is not routable )

**Comment by bpiv400** [comment]
Should I need to wait several minutes before addrbook.json gets written or is it written when: 

`... add our address to addrbook..` prints in the logs.
