### ISSUE TITLE
p2p: certain peer errors should cause us to remove the address

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1444]
If we can't reach a peer, we should keep the address around.

However, if we successfully connect to the remote endpoint but fail to handshake or otherwise we should remove the peer from the address book so we don't keep trying.

This is really just an optimization (if we fail to connect enough times, we'll boot the peer), but it will make for a better UX

Also might be nice to remember peers we've removed from the addrbook for some time so we can avoid reconnecting

**Comment by melekes** [comment]
> If we can't reach a peer, we should keep the address around.

what for?

So, currently, we remove the address if the peer is not available (16 attempts) or it fails authentication.

> Also might be nice to remember peers we've removed from the addrbook for some time so we can avoid reconnecting

https://github.com/tendermint/tendermint/pull/4548 does exactly that

**Comment by tessr** [comment]
I think this is covered by #4548. I'm going to consider this issue closed!
