### ISSUE TITLE
[p2p] error when try to run tendermint in multiple node mode

### ISSUE THREAD

**Issue by hiberabyss** [tendermint/tendermint#1445]
When try to start tendermint in multiple nodes mode via docker with following configuration:

```
command: ['node', '--p2p.persistent_peers=tm_node1:46656', '--moniker=tm_node1', '--proxy_app=kvstore', '--consensus.create_empty_blocks=false']
```

Following error will occur:

```
E[04-09|22:24:20.914] Error in peer's address                      module=p2p err="Error in address tm_node2:46656: Address (tm_node2:46656) does not contain ID"
```

My `tendermint` version is:
```
tmuser@tm_node2:~$ tendermint version
0.18.0-4930b61a
```

**Comment by eeonevision** [comment]
Check https://github.com/tendermint/tendermint/issues/1408

**Comment by melekes** [comment]
@hiberabyss yeah, either set `auth_enc` to `false` (not recommended for production unless you're using VPN) or prefix all your IP:PORT pairs with ID (ID@IP:PORT).

https://tendermint.readthedocs.io/projects/tools/en/develop/using-tendermint.html#peers

**Comment by hiberabyss** [comment]
@melekes , seems set `auth_enc` to false did not work, while now could use `tendermint show_node_id` to get the ID and set it as prefix.

Thanks!

**Comment by melekes** [comment]
> seems set auth_enc to false did not work

I will investigate
