### ISSUE TITLE
writing revision should overwrite previous

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#145]
currently the Makefile is using >> to append. Shouldn't we just overwrite?

**Comment by jaekwon** [comment]
oh ic.  I wanted a log so we can go back and debug issues across deploys.  Lets do whatever is reasonable.

**Comment by ebuchman** [comment]
ahh that's not a bad idea. I wanted something we could see in the `/status` rpc. maybe we should support both? a `revision` file to be shown in the node_info and a `revision_history` for debugging (which will require access to the file system)
