### ISSUE TITLE
Threshold/Shared Signatures per Validator

### ISSUE THREAD

**Issue by mossid** [tendermint/tendermint#1457]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

In trustless network, if one of the validator nodes is attacked, there is not much thing that the validator can do. For example in Cosmos Hub, if one of the validators are attacked and their privkey is stolen, they will lose all of their assets(and credit from the delegators) bonded on the chain and there will be no way to recover them.

If we treat tendermint light client as a "signature", a validator can organize their own subnetwork for failsafe signing. For example, they can form a subnetwork consists of 10 nodes running on Tendermint. When a new block is generated on the mainnet, all of the nodes in the subnet works just like as it was on the mainnet and verifies the block. But after the local nodes made a consensus, the collective signature which contains agreement of more than +2/3 of keys in the subnet is constructed and then broadcasted to the mainnet as a single validator's vote.

Also as they are using Tendermint for the subnetwork, they can easily drop the node that is attacked and replace them with a new key(unless more than 1/3 is stolen). The mainnet only have to update the subnet's pubkey set(or a BLS signature if we support it) when more than +1/3 of the keys are changed, which will happen very rarely. So in most case, that validator will considered as a normal validator but using multisig.

I'm not sure how much modification is needed on Tendermint to enable this, but it will increase the stability of the validators sacrificing a little speed performance.

**Comment by xla** [comment]
Related to #1319

**Comment by jackzampolin** [comment]
Closing this in favor of #1319, @mossid please reopen if I'm wrong.
