### ISSUE TITLE
lite: Node discovery for light clients

### ISSUE THREAD

**Issue by faboweb** [tendermint/tendermint#1462]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Commit 4930b61a381b9fb9bc530eb5deb56ea6429a1c3a

Light clients will need to connect to a full node. Currently we only now about seed nodes in the genesis. If we have many light clients this will DDOS the seed nodes. So we need a way to get discovered full nodes on the network to distribute load.

Proposal by @melekes:
I think we can hardcode an address like `seed.tendermint.io`, which returns an IP of the seed (internally doing round-robin between a list of seeds we know). LC connects to this seed and calls `/peers?count=1&biasTowardsGoodPeers=100`

**Comment by MattWangming** [comment]
Hi there, @faboweb do you know anything updated on this node discovery function for light clients? Could this feature be released in the latest version or any further planning releases?
