### ISSUE TITLE
Should we avoid using magical number >2/3 in the code and docs?

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#1469]
Tendermint docs and code refer to +2/3, more than 2/3, less than 1/3 etc. Would it make more sense using terms such as f (maximum amount of voting power owned by faulty processes), N total voting power, and then have somewhere stated that n = 3f+1. Then we can refer to various majorities as f+1, 2f+1, >f etc and it is deterministic what is meant.

**Comment by milosevic** [comment]
I would suggest using terms which have intuitive meaning. For example:
maxVotingPowerOfFaultyProcesses
totalVotingPower

weakCertificatePower
Weak certificates are sets with at least f+1 voting power. 
Weak certificates prove that at least one correct process did something. 

quorumCertificatePower
Quorum certificates are sets with at least 2f+1 voting power.
Quorum certificates have two important properties:

Intersection: any two quorums have at least one correct process in common. 
Availability: there is always a quorum available with no faulty replicas.

I am fine with +2/3, that's clear what it means. But when I see less than 1/3, I am wondering if it should be equal to 1/3 or less than 1/3. Or less than 2/3. It is not clear to me what is meant precisely with that. If you instead refer to less than weakCertificatePower or less than maxVotingPowerOfFaultyProcesses, it is very precise what it means and to what value it corresponds.

**Comment by marbar3778** [comment]
Don't think this is as relevant in the implementation, but in the spec. For the implementation, we should go with what the developers are comfy with. Closing this, if you believe it's still relevant, reopen it.
