### ISSUE TITLE
Send list of validators to abci app

### ISSUE THREAD

**Issue by aastein** [tendermint/tendermint#1472]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  FEATURE REQUEST

Send the list of validator's public keys of the pervious block to the abci app.

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.17.1

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/ovrclk/akash/

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it): 0.7.1

**Anything else do we need to know**:
Where would you suggest to implement this? In BeginBlock or EndBlock or other?

**Comment by melekes** [comment]
Why do you need a list?

Note we're sending Absent validators here https://tendermint.readthedocs.io/projects/tools/en/master/abci-spec.html?highlight=AbsentValidators#beginblock

**Comment by aastein** [comment]
In Akash, the current proposer per round is chosen to send certain transactions. Akash also needs validators to be added or removed while the system is live.

To validate the transactions we need either the set of validators and the final round number per block or the final proposer per block.

**Comment by aastein** [comment]
In Akash the block creator, who is also the first proposed, is chosen to send certain transactions. Validators need to check that for a given block, these transactions were created by the previous block's creator. One way to determine the block creator is by the list of validators and the round state. It would be sufficient for Akash if the block creator was added to the block header, but any other solution, like sending the list of validators, is fine as well. Our goal is to implement a solution which will be supported by Tendermint.

**Comment by melekes** [comment]
Will https://github.com/tendermint/tendermint/issues/1134 be sufficient for your needs?

**Comment by aastein** [comment]
That would be perfect. It is currently being worked on?

**Comment by ebuchman** [comment]
Yes we need this for Cosmos launch. Expect it soon.
