### ISSUE TITLE
[windows] Error: While parsing config: (30, 17): invalid escape sequence: \g

### ISSUE THREAD

**Issue by vieiralc** [tendermint/tendermint#1491]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**: 
- **OS** (e.g. from /etc/os-release): windows 10
- **Install tools**:
- **Others**:

**What happened**: I run the command tendermint init and so far everything was ok, then I run tendermint node and now it gives me this error:

![image](https://user-images.githubusercontent.com/19657718/39148911-d3b00bfe-4713-11e8-985d-2a6d9fed1820.png)

this is my config.toml:

![image](https://user-images.githubusercontent.com/19657718/39148977-145d49be-4714-11e8-8564-65a712432826.png)

**Comment by a13xander96** [comment]
I got this error too on windows only, for some reason changing double quote to single quote(" to ') fixed the problem for me.

**Comment by ebuchman** [comment]
```
	defaultConfigFilePath  = filepath.Join(defaultConfigDir, defaultConfigFileName)
	defaultGenesisJSONPath = filepath.Join(defaultConfigDir, defaultGenesisJSONName)
	defaultPrivValPath     = filepath.Join(defaultConfigDir, defaultPrivValName)
	defaultNodeKeyPath     = filepath.Join(defaultConfigDir, defaultNodeKeyName)
	defaultAddrBookPath    = filepath.Join(defaultConfigDir, defaultAddrBookName)

```

Maybe we need to use "path" instead here ?

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/1423 (same bug)

**Comment by vieiralc** [comment]
@a13xander96 I had to change every single quote (" to ') to fix the problem
