### ISSUE TITLE
docs: notes about running a production system

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1494]
Should touch on things like:
- logging options 
- the consensus WAL (https://github.com/tendermint/tendermint/issues/1513)
- DoS exposure (https://github.com/tendermint/tendermint/issues/1512)
- Bounding resource usage (https://github.com/tendermint/tendermint/issues/1512)
- summary of useful endpoints for monitoring / debugging
- summary of what certain log statements mean
- summary of how restarts are handled (eg if ABCI app crashes, Tendermint needs to be restarted #243)
- summary of how Tendermint responds to signals and what guarantees are observed (https://github.com/tendermint/tendermint/issues/1330)
- notes about future plans for blockchain bloat
- notes about expected ops requirement re rpc server, firewalls, networking, etc.
- network config parameters and max size parameters

**Comment by ebuchman** [comment]
Note about WAL size: https://github.com/tendermint/tendermint/issues/1268

**Comment by melekes** [comment]
> notes about future plans for blockchain bloat

you mean the disk should be sufficiently large to accommodate future growth?

**Comment by ebuchman** [comment]
> you mean the disk should be sufficiently large to accommodate future growth?

More so notes about how eventually we'll have state-dumps and state-sync so we can throw away old blockchain history

**Comment by zramsay** [comment]
#1618
