### ISSUE TITLE
Set the genesis as a (preset) hash in config.toml and fetch the genesis.json file from nodes

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#15]
Yeah.

Also, might as well uncomment the SeedNode.  That will make onboarding easier.

**Comment by xcthulhu** [comment]
Use ipfs for this?

**Comment by jaekwon** [comment]
Yeah we could.  What does IPFS integration look like?

**Comment by kumavis** [comment]
Here's the go client
https://github.com/jbenet/go-ipfs

**Comment by ebuchman** [comment]
id rather use a name reg chain for this. willing to assume from here on out one will exist? i also added a genesis route to the rpc so we can probably close this

**Comment by jaekwon** [comment]
neat.
