### ISSUE TITLE
Clarify MaxNumPeers

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1501]
MaxNumPeers only affects number of incoming connections. The number of outgoing connections is limited by address book - 1000 (needAddressThreshold). We should either rename it to `MaxNumInPeers` or rewrite the code.

**Comment by ebuchman** [comment]
what about `defaultMinNumOutboundPeers = 10` ? once we have that many, we don't dial any more

**Comment by melekes** [comment]
Oh, right. So it's 50 (MaxNumPeers) + 10 (defaultMinNumOutboundPeers)

**Comment by ebuchman** [comment]
fixed in #1519
