### ISSUE TITLE
Ensure each channel has capacity defined

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1503]
```
func (bcR *BlockchainReactor) GetChannels() []*p2p.ChannelDescriptor {
	return []*p2p.ChannelDescriptor{
		{
			ID:                  BlockchainChannel,
			Priority:            10,
			SendQueueCapacity:   1000,
			RecvBufferCapacity:  50 * 4096,
			RecvMessageCapacity: maxMsgSize,
		},
	}
}
```

vs

```
func (memR *MempoolReactor) GetChannels() []*p2p.ChannelDescriptor {
	return []*p2p.ChannelDescriptor{
		{
			ID:       MempoolChannel,
			Priority: 5,
		},
	}
}
```

**Comment by odeke-em** [comment]
Hello @melekes, what's the security implication here? I am just asking for an articulation as last weekend or sometime back I was thinking of a way to cause a deadlock by overwhelming peers with random/spurious broadcasts. It'd be nice to see if someone came to a similar conclusion or if perhaps this is something new too :)

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/e832d22cb3d80d71e8e7baad10d68718afdf2425/p2p/pex/pex_reactor.go#L248

A: I wonder if we can remove for pex channel because it's essentially the same thing
limit on queue == rate-limiter
