### ISSUE TITLE
Can we dynamically add validator node in Tendermint cluster ?

### ISSUE THREAD

**Issue by ArvonHuang** [tendermint/tendermint#1517]
FEATURE REQUEST
Can we dynamically add validator nodes in Tendermint cluster ?
I mean i firstly deploy a test network to four validator nodes , can i latter add validator nodes ? 
Thx very much.

**Tendermint version** 
`0.19.1-26f633ed`

**Comment by zramsay** [comment]
Yes you can, see http://tendermint.readthedocs.io/en/master/using-tendermint.html#adding-a-validator

Please re-open if that doesn't help

**Comment by ArvonHuang** [comment]
I mean in a live network how can i  dynamically add validator nodes, thx

**Comment by ArvonHuang** [comment]
@zramsay

**Comment by ArvonHuang** [comment]
I mean in a live network how can i dynamically add validator nodes, thx

@zramsay

**Comment by hxzqlh** [comment]
@ArvonHuang you need impl it in your abci app.See `https://github.com/tendermint/abci/blob/master/example/dummy/persistent_kvstore.go#L68` as reference.

**Comment by ArvonHuang** [comment]
@hxzqlh  thx , bug it is a 404 page.

**Comment by xla** [comment]
@ArvonHuang New location: 
https://github.com/tendermint/tendermint/blob/master/abci/example/kvstore/persistent_kvstore.go
