### ISSUE TITLE
Remove AuthEnc config option

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1518]
It would be a nice boost to the cleanliness of some p2p code if we didn't even support this option. 

The consequence is that everyone will have to have IDs along with address in order to connect to peers. This should effectively be true anyways. But maybe some folks wanted to use their own VPN for encrypting connections and not have Tendermint do another layer of encryption ...

I think it's probably worth it to remove the option to turn this off, so that Tendermint always provides authenticated encryption and you need to know the ID of the peers you're dialing.

If you really think you need to set AuthEnc=false, please speak now

**Comment by xla** [comment]
Removed in #1671
