### ISSUE TITLE
ABCI ResponseException

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1522]
Closes out https://github.com/tendermint/tendermint/issues/1220.

But see details in https://github.com/tendermint/abci/issues/195

**Comment by jackzampolin** [comment]
needs more details.

**Comment by ebuchman** [comment]
More details linked from https://github.com/tendermint/abci/issues/195

Not sure we need an open issue for it but probably something to track on the list of potential ABCI improvements ...
