### ISSUE TITLE
enterPrevote: ProposalBlock is invalid error Wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by nchennan** [tendermint/tendermint#1536]
tendermint version 0.14.0-88f5f21

ethermint version 0.5.3-768a6ee

go-ethereum: 1.6.7-stable

I am trying to modify the node binding account and reward the node;

Error message：

`enterPrevote: ProposalBlock is invalid module=consensus height=2 round=36 err="Wrong Block.Header.AppHash. Expected E2D0CB08B09E6B3E87835BA8CC60CAA6C4442E414CA86B0F4F89A6AE3E6973CE, got 71EA679D901E05BD387E05B436326F7001C6C96EF81309BF0498E479EBCDC333"`

The modified code is as follows：

```
package minerRewardStrategies

import (
	"github.com/ethereum/go-ethereum/common"
)

// RewardConstant is a possible strategy
type RewardConstant struct {
	coinbase string
}

// Receiver returns which address should receive the mining reward
func (r *RewardConstant) Receiver() common.Address {
	return common.HexToAddress(r.coinbase)
}

func (r *RewardConstant) SetReceiver(address string) {
    r.coinbase = address;
}
minerRewardStrategies :=  &minerRewardStrategies.RewardConstant{};
	ks := node.AccountManager().Backends(keystore.KeyStoreType)[0].(*keystore.KeyStore)
    minerRewardStrategies.SetReceiver(ks.Accounts()[0].Address.String()) 

	// Create Strategy
	strategy := &emtTypes.Strategy{
		minerRewardStrategies,
		&validatorStrategies.TxBasedValidatorsStrategy{},
	}
	// Create the ABCI app
	ethApp, err := abciApp.NewEthermintApplication(backend, rpcClient, strategy)
```
Hope to get your help and tell you how to change it ，thanks you！

**Comment by ebuchman** [comment]
This is an ethermint issue. Please re-open on the ethermint repo. 

That said, Ethermint is not currently maintained as we will be rebuilding it within the Cosmos-SDK framework, so unfortunately we may not be able to help you with this right now. Sorry about that.
