### ISSUE TITLE
why call  "bcR.BaseReactor.OnStart()"   in  OnStart()  ?

### ISSUE THREAD

**Issue by wadelee1986** [tendermint/tendermint#1537]
file: github.com/tendermint/tendermint/blockchain/pool.go

// BlockchainReactor handles long-term catchup syncing.
type BlockchainReactor struct {
	p2p.BaseReactor
       ...........
}

// OnStart implements cmn.Service.
func (bcR *BlockchainReactor) OnStart() error {
	if err := bcR.BaseReactor.OnStart(); err != nil {
		return err
}

**Comment by ebuchman** [comment]
you're right we don't need to call it
