### ISSUE TITLE
May be this is a bug if proposer is not the same one in 4 nodes when one of four validator startup later

### ISSUE THREAD

**Issue by Hugo-Huang** [tendermint/tendermint#1541]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Maybe a bug

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.15.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
irrelevant

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):
irrelevant

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:
irrelevant

**What happened**:
I use cmd as follow:
./tendermint node --p2p.seeds=192.168.3.4:46656,192.168.3.13:46656,192.168.3.29:46656,192.168.3.30:46656 --proxy_app=dummy
There are 4 nodes, and they are set as validator in genesis.json. Step as follows:
1.start up first 3 IP node
2. run several minutes, maybe some heights need more than one round
3.start up the last IP node, it would sync by func poolRoutine() in blockchain/reactor.go
then is my question:
How to ensure the proposer of  4  nodes is the same one? I only find the validators(*types.ValidatorSet) of State changed by func IncrementAccum() in updateState() in state/execution.go. func IncrementAccum() in enterNewRound() in consensus/state.go just changes runtime value of RoundState.
But I think they are not enough to answer the question, so I think maybe it is a bug.

**What you expected to happen**:
the proposer of  4  nodes is the same one

**How to reproduce it** (as minimally and precisely as possible):
Do it as the description upon
**Logs (you can paste a part showing an error or attach the whole file)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:
why not use LastValidators of State? What's the difference between of them?

Thank you

**Comment by ebuchman** [comment]
I think you're right!

**Comment by Hugo-Huang** [comment]
May be you can get the latest ValidatorSet by LastValidators of State. Expect the bug to be fixed as soon as possible.

**Comment by ebuchman** [comment]
Also noted we need more tests here (^).

Also, re you're last comment, we're adding proposer to the header and making round available to the app: https://github.com/tendermint/tendermint/issues/1134#issuecomment-388462850

**Comment by Hugo-Huang** [comment]
Yes, you are right. I have read the code carefully.  The only way to change(or save)  ConsensusState.state is run func updateToState() in consensus/state.go. Then getting the state which was saved last time in func finalizeCommit() by “cs.state.Copy()” when need update block height. So the Validators(ValidatorSet) is consistent at the same height. But on the other hand, the final proposer in the final round of one height may be not the propose which final saved to state(when more than one round in a height), it only ensure that the origin Validators is same on the same height. @ebuchman
