### ISSUE TITLE
Deterministic builds with CGO_ENABLED=1

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#1545]
Find a way to build with CGO deterministically across platforms, so we can use e.g. CLevelDB, and integrate any necessary libraries (musl-libc?) into the build process.

**Comment by cwgoes** [comment]
With no change, build isn't even deterministic at the moment:

```
# BELOW - go version natively
go version
go version go1.10.1 linux/amd64
GOCACHE=off CGO_ENABLED=0 go build -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD`" -tags 'tendermint' -o build/tendermint ./cmd/tendermint/
# BELOW - sha256sum of tendermint binary built natively
sha256sum build/tendermint
a67be075abd897d0a400a09a76413965e9e295ea6c18f8ac5a7baac3902aa0a3  build/tendermint
cd DOCKER && make build_check
make[1]: Entering directory '/home/cwgoes/working/cosmos/tendermint/DOCKER'
docker build --quiet --no-cache -t "tendermint/tendermint:check" -f Dockerfile.check .
sha256:ca205bf5c18425ddfdc9ef3681e6418b4902a65b2d31c276a5d536fcdfa0e7ab
# BELOW - go version in Docker
docker run tendermint/tendermint:check go version
go version go1.10.1 linux/amd64
# BELOW - sha256sum of tendermint binary built in Docker
docker run tendermint/tendermint:check sha256sum /go/bin/tendermint
0a700d6996923453bcdd890b2bdd86b899f5916d53169e4c82a42194ce9e3bc9  /go/bin/tendermint
docker rmi -f tendermint/tendermint:check
Untagged: tendermint/tendermint:check
Deleted: sha256:ca205bf5c18425ddfdc9ef3681e6418b4902a65b2d31c276a5d536fcdfa0e7ab
Deleted: sha256:70ed322f09c4609d957a70c919ba2e64623466851728f755b8dd0952a4f474f6
Deleted: sha256:ff636c25a39e730547c6a24a5b4c9d1e2d34e1d21fd680b539155dfd8031e591
Deleted: sha256:afacdb9f76ba6b162d366675b0aa14999c6c31f2a7e4b9e50b8a5c048ffe8f87
Deleted: sha256:e6885c661c3a640362f4a0e8d8c376e1050b40f208d55413ef8522349aa0ca2d
Deleted: sha256:ee00e89541768bdc46491af22cfb07503bf1b19337b33f0323a589712b7efe0b
Deleted: sha256:afd475058622f52f361cb376daf011d9c0dd9cc86e56816fa7bd517fab458968
make[1]: Leaving directory '/home/cwgoes/working/cosmos/tendermint/DOCKER'
```

**Comment by cwgoes** [comment]
Seems to be nontrivial unless we require identical GOPATHs, ref https://github.com/golang/go/issues/16860

**Comment by zmanian** [comment]
Let's require identical GOPATHs!

**Comment by melekes** [comment]
> "With no change, build isn't even deterministic at the moment:"

you're (or any other person releasing TM) supposed to build Tendermint inside docker or any other reproducible env.

**Comment by cwgoes** [comment]
> Let's require identical GOPATHs!
> you're (or any other person releasing TM) supposed to build Tendermint inside docker or any other reproducible env.

Great, agreed, will update the PR.

**Comment by melekes** [comment]
We're used to build inside docker, but later decided to remove this logic for security? reasons.

**Comment by cwgoes** [comment]
Deterministic build with [Nix](https://nixos.org/nix/) build seems to work.

You can run either `make build_nix` (will require that you have Nix installed) or `make build_nix_docker` (will require that you have Docker installed). Installing Nix is [easy](https://nixos.org/nix/download.html) (and Nix is lightweight, unlike Docker).

Run on the state of this PR (which has `CGO_ENABLED=1`):

`sha256sum build/tendermint`

```bash
```

To-do:
- [ ] Ensure Godep => Nix works seamlessly
- [ ] Allow building from modified code without committing (maybe)
- [ ] Ensure CGO is actually being used, test CLevelDB

**Comment by Liamsi** [comment]
On macos running `make build_nix` fails with:
```
/nix/store/vvzyx5ymmjnc0vbx0axr1vzbnnlx4jmh-tendermint-unstable-2018-05-10-bin
rm -rf build && mkdir build && cp result-bin/bin/* build && unlink result-bin
sha256sum build/tendermint
make: sha256sum: No such file or directory
make: *** [build_nix] Error 1
```
The command is just named differently on macos.

If I run `shasum` (or openssl) I get another hash:
```
shasum -a 256 build/tendermint 
6c1d06ca0905669c0cd564bdceaca98bfbbf47a31b1c9ebf1819751a0c543c9b  build/tendermint

openssl sha256 build/tendermint                               
SHA256(build/tendermint)= 6c1d06ca0905669c0cd564bdceaca98bfbbf47a31b1c9ebf1819751a0c543c9b
```

**Comment by greg-szabo** [comment]
CGO_ENABLED=1 introduces the following dependencies that need to be taken into consideration:
1. The build becomes dynamically linked and (the linux build) will not run on all and every linux distros. (Find the switch to set the C compiler to statically linked libraries to overcome this.) For example building on ubuntu will build a binary that cannot be run on alpine linux, because of the dynamically linked glibc libraries missing from alpine. The same is true the other way around with the muslc libraries.
2. "Deterministic builds" is a misnomer. Because of the above, we have to choose a specific C library set and build with those to get the same build. If we document the exact environment (GOPATH, GOROOT, C library name and version, Go version) then you can build the same binary. You can't say "use this tool" and be done with it, because even between tool version you might find differences.

**Comment by cwgoes** [comment]
We've decided against this for now.
