### ISSUE TITLE
types: update tx hash to use SHA256 and no amino

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1547]
Currently the tx hash is computed as `RIPEMD160(amino_encode(tx))`

This has the effect of just prefixing the varint length before hashing.

We should avoid doing this, for simplicity (ie. just the hash of the underlying tx - it would already be encoded with something like amino at the app level).

Also we should move to SHA256[:20]

**Comment by mdyring** [comment]
Strongly agree here on both points: using SHA256 instead of RIPEMD160 as well as removing amino_encode and just hashing the user-provided tx bytes.

It should be trivial for anybody to calculate the tx hash based on the information already available (tx raw bytes in an arbitrary encoding).

**Comment by jaekwon** [comment]
Ok, as long as we still hash the tx first.  It's necessary for blinding, and uniformity of usage of simple-hash.

The new behavior should have identical behavior has tmlibs/merkle SimpleHashFromByteSlices, so we need to make updates there as well (generally everywhere in tmlibs/merkle).  The implementation in tendermint is just an optimized copy/implementation from tmlibs/merkle -- lets keep it that way.
