### ISSUE TITLE
Conflicting vote is not propagated to peers 

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#1552]
If a process receives some vote v from process p, and then forward it to its peers and therefore set it in the corresponding peer state (PeerRoundState), it will not reset the corresponding entry in the peer state upon receiving conflicting vote. The conflicting vote is added to the evidence pool, but it is not forwarded at the gossip level (unless it is part of 23majority and then the corresponding entry is reset because of VoteSetBitsMessage mechanism). 

Shouldn't the peer state entry be reset in case conflicting vote is received, so the vote can be propagated by the gossip vote routine?

**Comment by ebuchman** [comment]
@milosevic isn't this dealt with by the maj23 mechanism?

**Comment by milosevic** [comment]
I guess the question raised by this issue is whether we want to ensure that conflicting votes are propagated also in case they are not part of 23majority. Maybe it is not needed in case this is dealt at the evidence reactor level. Once conflicting vote is part of 23majority we propagate it with maj23 mechanism.

**Comment by cmwaters** [comment]
I think this should be the responsibility of the evidence reactor to handle. I'm going to close this issue.
