### ISSUE TITLE
I was unable to install tendermint

### ISSUE THREAD

**Issue by atheesh1** [tendermint/tendermint#1556]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release):Ubuntu 16.04
- **Install tools**:
- **Others**:

**What happened**:Giving dependency errors

**What you expected to happen**:Want to install tendermint

**How to reproduce it** (as minimally and precisely as possible):

**Logs (you can paste a part showing an error or attach the whole file)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:please give us proper instruction doc to install go & tendermint

**Comment by zramsay** [comment]
this should work on a fresh Ubuntu instance:
https://gist.github.com/zramsay/4bca8907a97ad825c30cfdc6f72ba97b

**Comment by ebuchman** [comment]
https://tendermint.readthedocs.io/en/master/install.html (as linked from the README).

Did you follow these directions ?

**Comment by melekes** [comment]
```
cd $GOPATH/src/github.com/tendermint/tendermint
make get_tools
make get_vendor_deps
make install
```

should work. please reopen if it doesn't
