### ISSUE TITLE
docs: proposer selection

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1558]
The [proposer selection spec](https://github.com/tendermint/tendermint/blob/master/docs/specification/new-spec/reactors/consensus/proposer-selection.md) mentions the goals but not the algorithm.

We should add in the algorithm and move the explanation/intuition below (spec shouldnt be concerned with the explanation)

**Comment by ebuchman** [comment]
Need to explain the algorithm, with Accum, and how it works across rounds and heights

**Comment by ebuchman** [comment]
Related: https://github.com/tendermint/tendermint/issues/2890

**Comment by jackzampolin** [comment]
Isn't this just stake weighted round robin? I'm assuming this is a call for more detail there. Calling @gamarin2

**Comment by gamarin2** [comment]
We are focusing on SDK docs atm, but I am keeping this issue in mind for after

**Comment by ebuchman** [comment]
Can we consider this done re #3140 and the spec now in https://github.com/tendermint/spec/blob/master/spec/reactors/consensus/proposer-selection.md ?

**Comment by tessr** [comment]
> Can we consider this done re #3140 and the spec now in https://github.com/tendermint/spec/blob/master/spec/reactors/consensus/proposer-selection.md ?

Yes.
