### ISSUE TITLE
Tests for syncing across round skips and valset changes 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1559]
https://github.com/tendermint/tendermint/issues/1541 made it clear that we dont have tests for syncing when there were round skips in the consensus.

We should write tests that ensure we can fast sync and switch to consensus successfully across a variety of conditions, namely round skips during the consensus (ie. it doesnt commit until round > 0) and validator set changes

**Comment by ebuchman** [comment]
We also need to test fast sync switch to consensus with create_empty_blocks=false to catch things like #1754

**Comment by jackzampolin** [comment]
I think no_empty_blocks and fast_sync both require significant refactor. Closing this issue.
