### ISSUE TITLE
P2P networking failure: testnet node disconnects, only reconnects when restarted

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#1562]
My `gaia-5000` testnet node, running untouched for about a week, spontaneously disconnected itself (somehow) from the other testnet nodes, leaving it unable to participate in consensus. After several hours of the node remaining in this state, I dumped some logs and restarted `gaiad`. Upon restarting `gaiad`, without any other action, the node reconnected, caught up to the latest network state, and begin participating in consensus again.

Gaiad version: 0.16.0-dev-7ef5e90
OS: Ubuntu 16.04 LTS

Gaiad logs just show a lot of peer dial failures.

Output of `dump_consensus_state` prior to restart: https://gist.github.com/cwgoes/b81062a6f78c7d813284f5e0971f6574

Output of `net_info` prior to restart: https://gist.github.com/cwgoes/fe7d274a529fa625377486e8372333c7

**Comment by ebuchman** [comment]
Looks like there's some bug around having the wrong proposal block.

The block committed at height 141293 is slightly different than your proposal_block, despite being committed in the same round (round 2). 

So it seems like you got enough precommits, but had the wrong proposal block, and were then never able to set up to get the correct proposal block!

**Comment by ebuchman** [comment]
do you have the logs from this one ?

**Comment by cwgoes** [comment]
No, sorry, but I do have the logs from the other one - https://github.com/tendermint/tendermint/issues/1575#issuecomment-389354375

**Comment by ebuchman** [comment]
Closing in favor of #1575 (believe its the same issue)
