### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by wannabit-jayb** [tendermint/tendermint#1578]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT 

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OS High Sierra version 10.13
- **Install tools**: go version go1.10.2 darwin/amd64
- **Others**: dep 

**What happened**:

I try to install Tendermint by following this [guide](http://tendermint.readthedocs.io/projects/tools/en/master/install.html).

I made sure that I installed `go` and set the `GOPATH`.

I also installed `dep` for dependency management as the official document says so.

I use below command to install Tendermint and below log is what I am encountering with.

```
go get -u github.com/tendermint/tendermint/cmd/tendermint
```

**Logs (you can paste a part showing an error or attach the whole file)**:

```
# github.com/tendermint/tendermint/p2p
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:57:6: undefined: common.IsASCIIText
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:57:39: undefined: common.ASCIITrim
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:61:7: undefined: common.IsASCIIText
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:61:29: undefined: common.ASCIITrim
# github.com/tendermint/tendermint/types
../../../go/src/github.com/tendermint/tendermint/types/event_bus.go:70:43: undefined: pubsub.NewTagMap
../../../go/src/github.com/tendermint/tendermint/types/event_bus.go:117:39: undefined: pubsub.NewTagMap
```

**Comment by wannabit-jayb** [comment]
I just noticed this below statement on the official guide.

```
Note that even though go get originally failed, the repository was still cloned to the correct location in the $GOPATH.
```

So, this is not an error? 

```
# github.com/tendermint/tendermint/p2p
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:57:6: undefined: common.IsASCIIText
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:57:39: undefined: common.ASCIITrim
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:61:7: undefined: common.IsASCIIText
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:61:29: undefined: common.ASCIITrim
# github.com/tendermint/tendermint/types
../../../go/src/github.com/tendermint/tendermint/types/event_bus.go:70:43: undefined: pubsub.NewTagMap
../../../go/src/github.com/tendermint/tendermint/types/event_bus.go:117:39: undefined: pubsub.NewTagMap# github.com/tendermint/tendermint/p2p
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:57:6: undefined: common.IsASCIIText
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:57:39: undefined: common.ASCIITrim
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:61:7: undefined: common.IsASCIIText
../../../go/src/github.com/tendermint/tendermint/p2p/node_info.go:61:29: undefined: common.ASCIITrim
# github.com/tendermint/tendermint/types
../../../go/src/github.com/tendermint/tendermint/types/event_bus.go:70:43: undefined: pubsub.NewTagMap
../../../go/src/github.com/tendermint/tendermint/types/event_bus.go:117:39: undefined: pubsub.NewTagMap
```

**Comment by ebuchman** [comment]
DId you put `$GOPATH/bin` on your path? you should see `$GOPATH/bin/tendermint` after you ran `make install`.

Reopen if there's still issues

**Comment by padmaja9** [comment]
hello,
  I have installed Go from the following link https://www.digitalocean.com/community/tutorials/how-to-install-go-1-7-on-centos-7
  After installing tendermint and when i do make get_tools, i'm getting the following error
make: *** No rule to make target `get_tools'.  Stop.
what can be the problem here?

**Comment by xla** [comment]
@padmaja9 Make sure to run `make get_tools` from within the tendermint directory. If the issue still persists please open an issue with detailed descriptions.

**Comment by wannabit-jayb** [comment]
@xla 
I am testing on Ubuntu 18.04 and macOS High Sierra. 
Keep getting the following error message when I make get_tools `$ make get_tools`

Ubuntu 18.04
```
...
.....
get "gopkg.in/alecthomas/gometalinter.v2/vendor/gopkg.in/yaml.v2": verifying non-authoritative meta tag
github.com/gogo/protobuf (download)
github.com/square/certstrap (download)
Makefile:77: recipe for target 'get_tools' failed
make: *** [get_tools] Error 1
```
macOS High Sierra
```
...
.....
get "gopkg.in/alecthomas/gometalinter.v2/vendor/gopkg.in/yaml.v2": verifying non-authoritative meta tag
github.com/gogo/protobuf (download)
github.com/square/certstrap (download)
unexpected directory layout:
	import path: github.com/codegangsta/cli
	root: /Users/JayB/go/src
	dir: /Users/JayB/go/src/github.com/square/certstrap/vendor/github.com/codegangsta/cli
	expand root: /Users/JayB/go/src
	expand dir: /Users/JayB/go/src/github.com/square/certstrap/vendor/github.com/codegangsta/cli
	separator: /
make: *** [get_tools] Error 1
```

What would be the problem here?

**Comment by ebuchman** [comment]
Did you get this resolved? What version of Go?

**Comment by sankar37** [comment]
I am getting the same error when I follow the instructions from the https://tendermint.readthedocs.io/en/v0.21.0/install.html. What is the alternative to this issue?

**Comment by sankar37** [comment]
I am getting the same error when I follow the instructions from the https://tendermint.readthedocs.io/en/v0.21.0/install.html. 

I have set the path $GOPATH/bin as well

My Go Version is 1.13.4

Also I am runing this command from inside tendermint directory

Any help on this? Is this an issue still ?

**Comment by sankar37** [comment]
Instead of using "make get_tools" command used "make tools".

**Comment by Tinrry** [comment]
how to fix `make get_vendor_deps`
![image](https://user-images.githubusercontent.com/16282255/94360577-edf71780-00e0-11eb-972f-ed1823300029.png)

**Comment by rachit77** [comment]
check if your Go env variables are as follows for the terminal you are working on:

```
export GOROOT=/usr/local/go
export GOPATH=/home/ubuntu/go
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:$GOPATH/bin
```
This solved the above error for me.

**Comment by punit-j** [comment]
Getting `zsh: command not found: tendermint` while running `tendermint version` on macOS Sonoma 14.2.

I even updated the `.bash_profile` and added `export PATH="$PATH:$HOME/go/bin/tendermint"`, but it does nothing.
