### ISSUE TITLE
How to use `tags` to query staking transaction

### ISSUE THREAD

**Issue by shiliang-woo** [tendermint/tendermint#1583]
Hello,

I am on gaia-5001, and i'd like to use tags for searching.

I have changed the `config.toml` to 
```
index_tags = "action,sender,recipient"

# When set to true, tells indexer to index all tags. Note this may be not
# desirable (see the comment above). IndexTags has a precedence over
# IndexAllTags (i.e. when given both, IndexTags will be indexed).
index_all_tags = true
```
but, i did
```
gaiacli txs --tag "action='delegation'"
gaiacli txs --tag "sender='<myaddress>'"
```

and it returns nothing.

I'd love more information about tags. and thank you so much

**Comment by ebuchman** [comment]
@cwgoes

**Comment by cwgoes** [comment]
@shiliang-woo Thanks for your investigation! You want to use `action = "delegate"`, not `action = "delegation"`, but we might have another issue on our end, as I when I run that command I see:

```bash
gaiacli txs --tag "action='delegate'"
ERROR: Unregistered interface types.Tx
```

Tracking that issue here: https://github.com/cosmos/cosmos-sdk/issues/1014

**Comment by shiliang-woo** [comment]
@cwgoes 
Ok, i see the problem here. i think the 'sender'& 'recipient' tags are not working neither.

**Comment by ebuchman** [comment]
Closing for https://github.com/cosmos/cosmos-sdk/issues/1014
