### ISSUE TITLE
Bad name

### ISSUE THREAD

**Issue by vance** [tendermint/tendermint#16]
I thought it was a service to decentralize voting on tinder dates. After that, I thought it was some sort of steak (tenderloin). Once I read the splash page, the words describing de-insentivizing  energy consumption etc. all fell into background as i pictured thin slices of  juicy mint-flavored roast beef dripping out of my wallet.

**Comment by jaekwon** [comment]
Congrats!
You've just won a spot on the validator spot.
Please respond with your home address and bank information.

**Comment by xcthulhu** [comment]
I myself was lead to believe it was some kind of Turing complete mojito...

**Comment by jaekwon** [comment]
will fix

**Comment by ebuchman** [comment]
@vance @changetip love the art work, have a cookie!

**Comment by changetip** [comment]
Hi @vance, @ebuchman sent you a Bitcoin tip worth a cookie (5,928 bits/$1.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/648459)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**
