### ISSUE TITLE
Links to spec out of date

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#1608]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST (kind of)

The links to the spec in the corresponding markdown files are not up to date. For example:
https://github.com/tendermint/tendermint/blob/develop/p2p/README.md 
(this is the development branch, same on the master branch)

**Tendermint version** 
development/master

**How to reproduce it** (as minimally and precisely as possible):
e.g, follow any link on https://github.com/tendermint/tendermint/blob/develop/p2p/README.md 

cc @zramsay

**Comment by zramsay** [comment]
#1611
