### ISSUE TITLE
Replay blocks committed by new dynamic validators

### ISSUE THREAD

**Issue by ldmberman** [tendermint/tendermint#1620]
Consider the following situation.

At genesis there are 3 nodes. Later, the nodes commit a transaction and add a dynamic validator by specifying it in the `EndBlock`. Now there are 4 nodes and they commit a transaction. At this point if yet another (5th) validator attempts to join the network it will fail to replay the last block committed by the 4th node it does not know and there is no way to make it know.

Specifically, it fails in `VerifyCommit`:

```
"Invalid commit -- wrong set size: %v vs %v", valSet.Size(), len(commit.Precommits)
```

There are ways to solve the problem on the application layer. Nevertheless, it seems feasible and reasonable to adjust the replay functionality to avoid this particular trap. There can be an RPC endpoint accepting the validator data and a block height. Then, upon replaying the block of the corresponding height, the node can update the state to include the new validator before applying the block. 

Looking forward to your feedback.

**Comment by ebuchman** [comment]
Can you clarify if this is an issue with tendermint syncing blocks over the network or tendermint syncing blocks with the application after a restart ? 

Some more logs might help elucidate that. If its the former, it sounds like a new unexpected bug, because people sync validator changes with our public testnets all the time.

If its the later, then yes, this is actually a known bug from some time ago with a TODO in the code: https://github.com/tendermint/tendermint/blob/master/consensus/replay.go#L355. Of course you can fix it from your app by returning the most recent block data on the Info command. That said, we will still fix it :)

Thanks!

**Comment by ldmberman** [comment]
It should be an issue with network syncing - we reproduced it without restarting the application. If I understand it correctly it fails here - https://github.com/tendermint/tendermint/blob/master/blockchain/reactor.go#L281. Logs were full of the `Invalid commit -- wrong set size: 3 vs 4` messages reporting 4 precommits but only 3 validators known to this node. If I am not mistaken it compares precommits from the height+1 block received from the network with the validator set at the height+0 block.

Regarding the application restart, are you referring to the situation when `appBlockHeight` <= `stateBlockHeight` < `storeBlockHeight`? These 2 code paths seem to lead here https://github.com/tendermint/tendermint/blob/master/state/validation.go#L65, so there should have been a slightly different log message in this case. By the way, the check right before `VerifyCommit` and the one inside `VerifyCommit` are identical.

Returning the last block height from the app should fix the application sync but does not seem to help with the network sync. I am not actually sure now if an application-side fix is at all possible. At BigchainDB we drafted [an election mechanism](https://github.com/bigchaindb/BEPs/pull/44) to manage dynamic validators, which solves some coordination issues, but in case the initial sync happens without consulting the ABCI proxy app, we can't do much in this regard.

Does it make sense?

Thank you!

**Comment by ebuchman** [comment]
Thanks for the clarification. 

> are you referring to the situation when appBlockHeight <= stateBlockHeight < storeBlockHeight?

More so `appHeight < stateHeight <= storeHeight `, ala https://github.com/tendermint/tendermint/blob/master/consensus/replay.go#L319

You're right, if theres issues in the network sync, there probably isn't much that can be done in the app to fix it.

That said, I'm having trouble identifying the issue. The BlockchainReactor code runs the full state transition (including validator set changes) and I can sync a node from scratch using fast_sync on the gaia testnet through multiple validator set changes (see https://github.com/tendermint/tendermint/issues/1623#issuecomment-391733836).

Maybe there's some more information that can help ?

**Comment by ldmberman** [comment]
I assembled a local Tendermint cluster and did not manage to reproduce the issue..

I'll investigate further if we have a problem on the application side and get back to you tomorrow.

Sorry for the false alarm.

**Comment by ldmberman** [comment]
I reproduced the error on the local cluster - it actually happens during the network sync but it's not a Tendermint bug. The problem we had was that our application only tried to include the new validator into an older block, but not the one where the validator joined. I believe, the issue can be closed - sorry for the false alarm again.

Also, could you, please, tell if I got the following right:

- A node can try to include a new validator (via `EndBlock`) into every block. Even if the majority does not accept the new validator, the corresponding blocks will be successfully committed if they are valid and voted for by the majority.
- A node can include an existing validator - it won't affect the consensus in any way.

Thanks a lot!

**Comment by ldmberman** [comment]
Yes, it does, thank you!

I was mistakenly thinking that Tendermint can tolerate an extra validator set update request.
