### ISSUE TITLE
TestPEXReactorAddRemovePeer() in pex_reactor_test.go is confusing

### ISSUE THREAD

**Issue by idoor88** [tendermint/tendermint#1621]
This is from conversion on riot:
idoor:
In TestPEXReactorAddRemovePeer function of pex_reactor_test.go, addPeer increase book size by 1, but removePeer does not decrease book size by 1, any reason for that? Thanks

melekes:
because removing peer from pex reactor does not result in removing it from the address book
test is confusing a bit, I agree
maybe we should drop all assert.Equal(t, size+1, book.Size()) except the first one after AddPeer
want to make a PR?

**Comment by idoor88** [comment]
I Will make pull request

**Comment by ebuchman** [comment]
Thanks!
