### ISSUE TITLE
Fast_sync stalls on gaia-5001

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#1623]
Start a new full node on `gaia-5001`

Default `config.toml` has `fast_sync =true`;

Sync stops < 10,000 blocks.

Restart with `fast_sync =false` 

Node is syncing nicely.

**Comment by kevlubkcm** [comment]
seems like the BlockchainReactor does not update the ValidatorSet, so when a block is validated by someone outside the genesis set, it blows up? im still getting familiar with the code so dont quote me 😕

**Comment by ebuchman** [comment]
Going to close this for https://github.com/tendermint/tendermint/issues/1624
