### ISSUE TITLE
Evidence reactor disconnects peers if it cant find height for evidence

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1624]
This is a problem for nodes that aren't caught up - they will receive evidence for blocks they don't have yet, think the evidence is invalid, and thus disconnect the peer: https://github.com/tendermint/tendermint/blob/master/evidence/reactor.go#L99

Maybe we need to limit this behaviour during fast sync ? 

Might be related to https://github.com/tendermint/tendermint/issues/1623

**Comment by zmanian** [comment]
On one of my validator nodes, I tried to disable fast sync and this caused be to be unable to connect to any peers.

Unsure if related.

**Comment by ebuchman** [comment]
> On one of my validator nodes, I tried to disable fast sync and this caused be to be unable to connect to any peers.

You ran a validator with `--fasy_sync=false` and couldnt connect to any peers ? what kind of errors ?

**Comment by zmanian** [comment]
no errors but just zero peers. I think I can reproduce!
