### ISSUE TITLE
Incorporate App version into NodeInfo

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1627]
The NodeInfo handshake checks that the Tendermint versions are compatible, but not the app.

Perhaps the app should be able to specify a validity filter on the version received, like it does with IPs and IDs - `/p2p/filter/version/<version>`. 

The app's own version should be returned in Info and incorporated into the node's own NodeInfo.

**Comment by xla** [comment]
Having this in the next release together with other breaking changes in `p2p`.
