### ISSUE TITLE
Code Execution!

### ISSUE THREAD

**Issue by androlo** [tendermint/tendermint#163]
Hello. This might be the wrong place, in that case sorry.

Very excited that You talk about maybe breaking smart-contract execution out into a separate program (noticed in the VM issue). Extremely excited in fact. Been going over various different transaction engines / blockchain clients lately because of issues I encountered (EVM related, not Tendermint). Been reading a bunch of papers (including tendermint) + going over code and building / testing some chains and code/tx processing tools like Ethereum, HydraChain, LMAX, graphene/bitshares, etc.

This mostly has to do with private/consortium chains that are run and maintained by businesses, so maybe isn't that interesting. I'm looking at the extremes; Ethereum with its public chain and VM, on one side, and high throughput tx processing engines on the other, and I then try to pick the best of both to make a smart-contract execution system that is suitable for business chains (efficient, secure, flexible, and easy to test and benchmark). Would gladly report some findings if needed. It's all sourced, of course. I also got a bunch of code, including a tx executor service for Tendermint that uses its CallTx's and Accounts etc., but gonna polish it some more.

Nice video on tendermint btw.

**Comment by jaekwon** [comment]
Thank you, Androlo.  Are you on our slack yet?  Drop me an email and I'll add you so we can test this out.

**Comment by ebuchman** [comment]
TMSP !
