### ISSUE TITLE
[blockchain] Punish peer for any block we did not expect

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1639]
in blockchain/pool.go:

```
requester := pool.requesters[block.Height]
if requester == nil {
   // a block we didn't expect.
   // TODO:if height is too far ahead, punish peer
```

A: why not punish peer for any block we did not expect?
E: is this old ? I cant find these comments anymore. also can you find where we implemented this ? perhaps theres discussion there … not immediately sure why we dont just always punish for unexpected block …
A: I implemented this some time ago
E: yeh right. so wheres that initial block with the TODO from ? and can you find the discussion that let to not punishing every time ?
A: https://github.com/tendermint/tendermint/commit/0bbf38141a6498f661d6c956c9f45066c312d90e
can't find any refs to github issues

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/2896
