### ISSUE TITLE
docs: events, query, pubsub

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1643]
We need to document how the Tendermint events, tagging, and indexing systems work. This should include:

- how the tx tags are indexed
- how the query language works and how to query for tags
- basic websocket usage
- how to subscribe to events via websockets
- how to subscribe to specific tags via websockets

**Comment by melekes** [comment]
https://tendermint.github.io/slate/#subscribe
https://godoc.org/github.com/tendermint/tendermint/rpc/core#Subscribe

**Comment by melekes** [comment]
> basic websocket usage

do you mean teaching people about websocket protocol or/and language specific clients? should we even do that?
