### ISSUE TITLE
Error when trying to connect validators

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#1644]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT (maybe)

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):0.15.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/blockfreight/go-bftx

**Environment**:
- **OS** (e.g. from /etc/os-release): Linux
- **Install tools**:
- **Others**:

**What happened**: I am trying to connect 4 validators hosted on Azure but I am getting the following error: 
```
E[05-30|00:54:58.893] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
E[05-30|00:55:02.805] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
E[05-30|00:55:06.823] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
E[05-30|00:55:10.847] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
```

I Googled about this error and found this:  `https://github.com/tendermint/tendermint/issues/1291#issuecomment-371730427` 

So I checked that all validators has the same genesis.json in the directory `/tendermint/genesis.json`:
```
{
    "genesis_time": "2016-04-26T22:00:00Z",
    "chain_id": "chain-IdealX",
    "validators": [{
            "pub_key": {
                "type": "ed25519",
                "data": "50E962E540E6AAB6996613560C87B74FBAB3EB6CC102E5BAC615B7B7ED5682CF"
            },
            "power": 10,
            "name": "bftx0"
        },
        {
            "pub_key": {
                "type": "ed25519",
                "data": "3D9DA3A242C5B95767FA24BFB76E907930087B87907C5480FB85F22315D3E859"
            },
            "power": 10,
            "name": "bftx1"
        },
        {
            "pub_key": {
                "type": "ed25519",
                "data": "0EDE6DFCC429D03E539A975A604FEB20994D50A9259E2A0F20A9533556074BBC"
            },
            "power": 10,
            "name": "bftx2"
        },
        {
            "pub_key": {
                "type": "ed25519",
                "data": "04E7495A468B07DCC5E19974E5200720C5FB94AD9D2AD32DE2B8CBE130347926"
            },
            "power": 10,
            "name": "bftx3"
        }
    ],
    "app_hash": ""
}
```

However, the request `<VALIDATOR_DNS>/genesis` returns me a different genesis.json for each Validator, e.g.:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "genesis": {
      "genesis_time": "2016-04-26T22:00:00Z",
      "chain_id": "chain-IdealX",
      "consensus_params": {
        "block_size_params": {
          "max_bytes": 22020096,
          "max_txs": 100000,
          "max_gas": -1
        },
        "tx_size_params": {
          "max_bytes": 10240,
          "max_gas": -1
        },
        "block_gossip_params": {
          "block_part_size_bytes": 65536
        },
        "evidence_params": {
          "max_age": 100000
        }
      },
      "validators": [
        {
          "pub_key": {
            "type": "ed25519",
            "data": "3D9DA3A242C5B95767FA24BFB76E907930087B87907C5480FB85F22315D3E859"
          },
          "power": 10,
          "name": "bftx-0"
        }
      ],
      "app_hash": ""
    }
  }
}
```

I am not sure if the error is happening because each node's got actually a different genesis.json - if it's where would it be? - or if it's something else.

**What you expected to happen**: All nodes to connect to each other.

**How to reproduce it** (as minimally and precisely as possible):
1. Install minikube and kubectl - https://kubernetes.io/docs/setup/pick-right-solution/
2. go get github.com/blockfreight/tools
3. cd `$GOPATH/src/github.com/blockfreight/tools/blockfreightnet-kubernetes/examples/blockfreight`
4. minikube start
5. `kubectl create -f app.yaml
* After a few minutes * 
6. kubectl logs bftx-0 tm

**Logs (you can paste a part showing an error or attach the whole file)**:
```
E[05-30|00:54:58.893] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
E[05-30|00:55:02.805] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
E[05-30|00:55:06.823] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
E[05-30|00:55:10.847] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (46414441363836353343394145383630464543374635313344384142373836353946434630463035) does not match address (3F1C1D8777B896698046DAE5C33DE97B96D96B97) for vote.ValidatorIndex (0): Invalid validator address"
```

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**: There's one more thing that it's not clear why it's happening, I am declaring the seeds in the config.toml but I don't know where this IP's are coming from because they are not set in the seeds:
```
E[05-30|00:54:56.588] Failed to dial peer                          module=p2p address=104.40.184.24:888 err="Error creating peer: dial tcp 104.40.184.24:888: i/o timeout"
E[05-30|00:54:56.588] Failed to dial peer                          module=p2p address=23.100.9.206:888 err="Error creating peer: dial tcp 23.100.9.206:888: i/o timeout"
E[05-30|00:54:56.588] Failed to dial peer                          module=p2p address=104.42.55.250:888 err="Error creating peer: dial tcp 104.42.55.250:888: i/o timeout"
E[05-30|00:54:56.588] Failed to dial peer                          module=p2p address=13.78.21.108:888 err="Error creating peer: dial tcp 13.78.21.108:888: i/o timeout"
E[05-30|00:54:56.589] Failed to dial peer                          module=p2p address=104.42.127.139:888 err="Error creating peer: dial tcp 104.42.127.139:888: i/o timeout"
E[05-30|00:54:56.589] Failed to dial peer                          module=p2p address=13.78.17.181:888 err="Error creating peer: dial tcp 13.78.17.181:888: i/o timeout"
E[05-30|00:54:56.589] Failed to dial peer                          module=p2p address=104.25.6.13:888 err="Error creating peer: dial tcp 104.25.6.13:888: i/o timeout"
E[05-30|00:54:56.589] Failed to dial peer                          module=p2p address=40.112.134.29:888 err="Error creating peer: dial tcp 40.112.134.29:888: i/o timeout"
```

Is it related to the `Invalid validator address` error ?

**Comment by ebuchman** [comment]
> 0.15.0

This is old. You should upgrade to 0.19.6

> I am not sure if the error is happening because each node's got actually a different genesis.json - if it's where would it be? - or if it's something else.

All nodes must have the same genesis.json. If the `/genesis` endpoint is returning different genesis data, then that explains your problem. Need to ensure the root directory of each node has the correct genesis.

> I am declaring the seeds in the config.toml but I don't know where this IP's are coming from because they are not set in the seeds:

What do you mean here? How are you declaring seeds ?

**Comment by gianfelipe93** [comment]
Thank you for your help @ebuchman 

Does Tendermint container must be in the same version that ABCI Tendermint dependency ? 
For example, can I use the docker image of Tendermint version 0.19.6 and use tendermint dependency 0.15 in the ABCI App ?

Is there a default tendermint root directory or it's is a environment variable that I have to create ?

I am declaring the seeds in the config.toml: 
```
proxy_app = "tcp://127.0.0.1:46658"
moniker = "anonymous"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"
[rpc]
laddr = "tcp://0.0.0.0:46657"
[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "VALIDATOR_DNS1, VALIDATOR_DNS2 ,VALIDATOR_DNS3, VALIDATOR_DNS4"
```

But those IPs that are failing to dial peer are not any of the validators IP.

Again, thank you for your help and I am sorry if it's still confusing.

**Comment by ebuchman** [comment]
> Does Tendermint container must be in the same version that ABCI Tendermint dependency ?
For example, can I use the docker image of Tendermint version 0.19.6 and use tendermint dependency 0.15 in the ABCI App 

The versions should match

> Is there a default tendermint root directory or it's is a environment variable that I have to create ?

~/.tendermint. Or set $TMHOME. 

Have you read https://tendermint.readthedocs.io/en/master/using-tendermint.html ?

**Comment by ebuchman** [comment]
yes use `--log_level=debug`

Presumably those addressses correspond to the DNS seeds or the persistent peers. Are you sure they are all correct and listening on 888 ?

**Comment by gianfelipe93** [comment]
thanks, I will use this option `--log_level=debug` 

I have only 4 validators so I reckon there should be only these four IPs:
- 40.112.134.29
- 191.237.254.156
- 52.232.117.56
- 52.243.57.132

I don't know where all others IPs are coming from. Do you know if it might be something related to Tendermint ? 

I am forwarding the port 888 to the port 46656, which is the right port to connect seeds, is there any alternative way to test this connection ?

Thank you for your help :)

**Comment by ebuchman** [comment]
Are there other nodes on the network? OId nodes on an old network ? Tendermint gossip peers but it has to get them from somewhere ...

Something must be wrong in your config or networking setup.

Make sure you can reach your nodes with normal networking tools

**Comment by gianfelipe93** [comment]
Hey @ebuchman 

My transactions are reaching my validators now, however they're not been confirmed.

1. http://bftx3.blockfreight.net:24365/unconfirmed_txs
1. http://bftx3.blockfreight.net:24365/unconfirmed_txs
1. http://bftx3.blockfreight.net:24365/unconfirmed_txs

**Comment by gianfelipe93** [comment]
Hey @ebuchman

I noticed that the file addrbook.json has many IP's. How does Tendermint use this file ?

In addition, I noticed that my transaction are been replicate over the 4 validators, however they are not been confirmed. I can see them if I go to the RPC route `/unconfirmed_txs`.

Do you what might be the reason ?

**Comment by melekes** [comment]
> I don't know where all others IPs are coming from. Do you know if it might be something related to Tendermint ?

I suspect those are old containers IPs. because you're mounting the same directory and Tendermint is using addrbook.json to store peer IPs, when you start it again (with different set of IPs), Tendermint will try to connect to IPs from the addrbook and fail (because old containers are down obviously).

**Comment by gianfelipe93** [comment]
I will close it for now since I reckon I sorted it.

Thank your all guys for your help !
