### ISSUE TITLE
Change `Commit` to consist of just signatures

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1648]
Currently, every block includes a LastCommit which is the set of +2/3 Precommit votes for the last block.

Note votes include validator address, index, blockID, as well as signature.

All of that information is redundant except for the signature - thus we could make blocks significantly smaller if we only included the signature in the Commit, instead of the whole vote.

**Comment by milosevic** [comment]
Note that the similar optimisation can be used at the gossip level to exchange votes. Instead of sending single vote, we can send set of the votes for the same value by sending data once and then signature for every vote.

**Comment by ebuchman** [comment]
Currently we have about ~100 redundant bytes per vote. In a block with 100 validators, that means up to 10kB in unnecessary space with every block. With blocks every 5s, that's over a MB of useless storage every 10 minutes, or a GB every week. 

#3245 takes some first steps towards resolving this.

We currently rely on getting a full Vote out of the Commit in a few places:
- when rebuilding the last vote set in `reconstructLastCommit` upon starting the ConsensusState
- when gossiping commit votes in the ConsensusReactor

For now, we can easily convert a CommitSig back to a Vote for this cases. In the future, we'll need to provide more info (eg the Commit and the ValidatorSet) in order to reconstruct votes.

**Comment by ebuchman** [comment]
Another step taken in #3275. Once the Commit can memoize the ValidatorSet, it shouldn't be hard to finish this up. Cool!

It would be super cool if we could make the change somehow based on a block version, so it could be done in a backwards compatible way (ie. would still work with blockchains from before the change, on the older block version). We should look into what that might take a bit more, but could be alot.

Another note, we should consider the naming. Is `CommitSig` the right name? What about in the commit, it's currently called `Precommits []*CommitSig` but maybe it should be something like `PrecommitWitnesses []*CommitSig`? Or should it just be `CommitSigs []*CommitSig` ? See https://github.com/tendermint/tendermint/pull/3245#discussion_r253581631

**Comment by ebuchman** [comment]
Note https://github.com/tendermint/tendermint/pull/3298#issuecomment-463151147 - we need to modify the commit structure to indicate which block a commit was for, since we currently include commits for different blocks (just requiring +2/3 is for the same block, namely "this" one).

**Comment by ebuchman** [comment]
We should probably include #2840 as part of completing this, as it allows us to remove the timestamp from the CommitSig as well, making the blocks even smaller, and setting us up better for signature aggregation.

**Comment by ebuchman** [comment]
This has become a meta issue tracking a number of sub issues:

- #3591 - Encode empty votes differently than just nil
- #3484 - Write tests with wrong or nil blockid
- #3596 - Do we need validator address in the vote?  

Sub-issues won't be tracked in milestones unless/until they are active pieces of work.

**Comment by b00f** [comment]
What if inside the vote we can wrap `signed_block_id`. So in this case validators should sign block-id first, then put it inside vote and then again sign the vote. In commit phase we can only use `signed_block_id` as commit and remove all redundant information. 
I believe time inside vote is very helpful to calculate median time.

**Comment by ebuchman** [comment]
I think we need the signature in the blocks to include the other info to properly validate them and detect evidence.

As for time, we need to use a proposer based time instead of the median, as outlined in https://github.com/tendermint/tendermint/issues/2840

**Comment by b00f** [comment]
AFAIK, evidence means a validator signs two blocks at the same height. So an evidence should includes these information:
1- block_id at main fork
2- Validator signature @ block_id
3- Byzantine block 
4- validator signature @ byzantine block_id
both 1 and 3 have same block height. 

Evidence can be a transaction with these parameters and anyone who sees these information can send an evidence tx.  
In my thought still blocks can only includes block_id and signed_block_id. Votes are useful for polka.

**Comment by ebuchman** [comment]
If the signature in the evidence isn't for a given height, how do you know it's a double sign? Just because a validator signed for X at height A, but Y ultimately got committed for height A, doesn't mean that validator was faulty.

**Comment by b00f** [comment]
My thought is based on this scenario (please let me know if I am wrong):
The main fork has blocks M, X, X+1, ... with C[m], C[x], C[x+1], ...
The byzantine fork (hidden fork) has M, Y, Y+1, ... with C[m], C[y], C[y+1],...
C here means Commits (only validator signatures)

So a faulty validator has signed for both X, Y and both blocks are committed. Then a slasher tx (with the evidence data) can be sent to the main fork and punish the faulty validator at main fork.

**Comment by jackzampolin** [comment]
Excited to see this!!!

**Comment by b00f** [comment]
probably can be linked with https://github.com/tendermint/tendermint/issues/2252

**Comment by melekes** [comment]
> Or should it just be CommitSigs []*CommitSig ?

simpler the better
