### ISSUE TITLE
Make State.* fields atomic

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#165]
State now is mutated in place, so the fields need to be modified/read atomically.

**Comment by ebuchman** [comment]
or we don't expose it and enforce a single reader/writer ? from the way the cs is set up now it looks like that's right (there's only one go-routine that reads the state), and the only thing using GetState() is an rpc call that should be getting it from the blockstore instead

**Comment by adrianbrink** [comment]
Is this still an issue?

**Comment by odeke-em** [comment]
@adrianbrink not really. From a quick audit of the code, I see
- Bytes(): we need a read lock at minimum
https://github.com/tendermint/tendermint/blob/7682ad9a60162dd17fd6f61aeed7049a8635ac78/state/state.go#L218-L220
- GetValidators() might need a read lock too https://github.com/tendermint/tendermint/blob/7682ad9a60162dd17fd6f61aeed7049a8635ac78/state/state.go#L262-L265
- Params() needs a read lock too
https://github.com/tendermint/tendermint/blob/7682ad9a60162dd17fd6f61aeed7049a8635ac78/state/state.go#L267-L273

**Comment by ebuchman** [comment]
As of v0.15 `State` is intended to be immutable and copied every time it changes. No longer used as a pointer.
