### ISSUE TITLE
question with get_vendor_deps

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1660]
$ make get_vendor_deps
--> Running dep
dep: WARNING: Unknown field in manifest: prune
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export github.com/ebuchman/fail-test: unable to update repository: : command failed: [git fetch --tags --prune origin]: exit status 255
Makefile:51: recipe for target 'get_vendor_deps' failed
make: *** [get_vendor_deps] Error 1
zhr@ubuntu:~/go/src/github.com/tendermint$ make install
CGO_ENABLED=0 go install -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD`" -tags 'tendermint' ./cmd/tendermint
fatal: not a git repository (or any of the parent directories): .git
cmd/tendermint/main.go:9:2: cannot find package "github.com/tendermint/tendermint/cmd/tendermint/commands" in any of:
	/usr/src/github.com/tendermint/tendermint/cmd/tendermint/commands (from $GOROOT)
	/home/zhr/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands (from $GOPATH)
cmd/tendermint/main.go:10:2: cannot find package "github.com/tendermint/tendermint/config" in any of:
	/usr/src/github.com/tendermint/tendermint/config (from $GOROOT)
	/home/zhr/go/src/github.com/tendermint/tendermint/config (from $GOPATH)
cmd/tendermint/main.go:11:2: cannot find package "github.com/tendermint/tendermint/node" in any of:
	/usr/src/github.com/tendermint/tendermint/node (from $GOROOT)
	/home/zhr/go/src/github.com/tendermint/tendermint/node (from $GOPATH)
cmd/tendermint/main.go:7:2: cannot find package "github.com/tendermint/tmlibs/cli" in any of:
Makefile:23: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by zramsay** [comment]
seems like you're having troubles connecting to Github. Try running this script: https://gist.github.com/zramsay/4bca8907a97ad825c30cfdc6f72ba97b

on a fresh Ubuntu instance on Digital Ocean

**Comment by ying2025** [comment]
Ok, I will try it in this way

**Comment by ying2025** [comment]
zhr@ubuntu:~/goApps$ REPO=github.com/tendermint
zhr@ubuntu:~/goApps$ go get $REPO
package github.com/tendermint: invalid github.com/ import path "github.com/tendermint"
zhr@ubuntu:~/goApps$ REPO=github.com/tendermint/tendermint
zhr@ubuntu:~/goApps$ go get $REPO
package github.com/tendermint/tendermint: mkdir /root/goApps: permission denied
zhr@ubuntu:~/goApps$ sudo go get $REPO
can't load package: package github.com/tendermint/tendermint: no Go files in /home/zhr/go/src/github.com/tendermint/tendermint

**Comment by Liamsi** [comment]
the last message you are seeing means that the last attempt worked. There are in fact no go files in the root repo. But the repo should still have been cloned to `/home/zhr/go/src/github.com/tendermint/tendermint`.  It's pretty weird that you have to sudo to write into this dir though.

**Comment by ying2025** [comment]
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ make get_vendor_deps
--> Running dep
dep: WARNING: Unknown field in manifest: prune

**Comment by ying2025** [comment]
It has the same question when I try with https://gist.github.com/zramsay/4bca8907a97ad825c30cfdc6f72ba97b

**Comment by ying2025** [comment]
This is the dep location
![image](https://user-images.githubusercontent.com/28092539/40815958-abeace10-657c-11e8-9693-f09cda65119d.png)

**Comment by melekes** [comment]
I suspect that `golang.org` is still unaccessible in China. Refs https://github.com/golang/go/issues/8870

Please use VPN (recommended) or try replacing `golang.org/x/crypto/ripemd160` package url with `golang.google.cn/x/crypto/ripemd160`

```
[[override]]
  name = "golang.org/x/crypto"
  packages = [
    "curve25519",
    "nacl/box",
    "nacl/secretbox",
    "openpgp/armor",
    "openpgp/errors",
    "poly1305",
    "ripemd160",
    "salsa20/salsa"
  ]
  revision = "b0697eccbea9adec5b7ba8008f4c33d98d733388"
  source = "golang.google.cn/x/crypto"
```

**Comment by ying2025** [comment]
This is the path /home/zhr/goApps/src/github.com/tendermint/tendermint/vendor/golang.org/x/crypto/ripemd160.
I donnot find Gopkg.toml in this path.
![image](https://user-images.githubusercontent.com/28092539/40885252-8adfaf9e-6755-11e8-913e-bc87518327c4.png).

![image](https://user-images.githubusercontent.com/28092539/40885267-cc87b77a-6755-11e8-996b-0e84b6eab7fe.png)
And It located in this path "/home/zhr/goApps/src/github.com/tendermint/tendermint"
![image](https://user-images.githubusercontent.com/28092539/40885330-c633e94c-6756-11e8-9de0-58b07fc335a3.png)

I cannot find "crypto " in this path  /home/zhr/goApps/src/github.com/golang/dep/vendor/golang.org/x.

![image](https://user-images.githubusercontent.com/28092539/40885336-dcf08348-6756-11e8-91e0-cc9a8ae00b7d.png)

**Comment by ying2025** [comment]
It is normal when install cosmos-sdk using "make get_vendor_deps". 
zhr@ubuntu:~/goApps/src/github.com/cosmos/cosmos-sdk$ make get_vendor_deps
--> Running dep ensure
dep: WARNING: Unknown field in manifest: prune
Gopkg.lock was already in sync with imports and Gopkg.toml
(1/49) Wrote github.com/spf13/jwalterweatherman@master
(2/49) Wrote github.com/tendermint/abci@v0.10.3
(3/49) Wrote github.com/spf13/cast@v1.2.0
(4/49) Wrote github.com/ebuchman/fail-test@master
(5/49) Wrote github.com/mitchellh/mapstructure@master
(6/49) Wrote github.com/pmezard/go-difflib@v1.0.0
(7/49) Wrote github.com/pkg/errors@v0.8.0
(8/49) Wrote github.com/pelletier/go-toml@v1.1.0
(9/49) Wrote github.com/tendermint/go-amino@0.9.9
(10/49) Wrote github.com/davecgh/go-spew@v1.1.0
(11/49) Wrote gopkg.in/yaml.v2@v2.2.1
(12/49) Wrote github.com/spf13/cobra@v0.0.3
(13/49) Wrote github.com/tendermint/ed25519@master
(14/49) Wrote github.com/bgentry/speakeasy@v0.1.0
(15/49) Wrote github.com/fsnotify/fsnotify@v1.4.7
(16/49) Wrote github.com/btcsuite/btcd@master
(17/49) Wrote github.com/go-logfmt/logfmt@v0.3.0
(18/49) Wrote github.com/spf13/pflag@v1.0.1
(19/49) Wrote github.com/spf13/viper@v1.0.2
(20/49) Wrote github.com/rcrowley/go-metrics@master
(21/49) Wrote github.com/stretchr/testify@v1.2.1
(22/49) Wrote github.com/syndtr/goleveldb@master
(23/49) Wrote github.com/go-kit/kit@v0.6.0
(24/49) Wrote github.com/go-stack/stack@v1.7.0
(25/49) Wrote github.com/spf13/afero@v1.1.0
(26/49) Wrote github.com/golang/snappy@master
(27/49) Wrote github.com/gorilla/websocket@v1.2.0
(28/49) Wrote github.com/golang/protobuf@v1.0.0
(29/49) Wrote github.com/gogo/protobuf@v1.0.0
(30/49) Wrote github.com/inconshreveable/mousetrap@v1.0
(31/49) Wrote github.com/jmhodges/levigo@master
(32/49) Wrote github.com/hashicorp/hcl@master
(33/49) Wrote github.com/mattn/go-isatty@v0.0.3
(34/49) Wrote github.com/tendermint/go-crypto@v0.6.2
(35/49) Wrote github.com/kr/logfmt@master
(36/49) Wrote github.com/tendermint/go-wire@v0.7.3
(37/49) Wrote github.com/howeyc/crc16@master
(38/49) Wrote google.golang.org/genproto@7fd901a49ba6a7f87732eb344f6e3c5b19d1b200
(39/49) Wrote github.com/magiconair/properties@v1.8.0
(40/49) Wrote github.com/tendermint/tmlibs@v0.8.3
(41/49) Wrote golang.org/x/crypto@master
(42/49) Wrote golang.org/x/net@master
(43/49) Wrote google.golang.org/grpc@v1.7.5
(44/49) Wrote github.com/gorilla/context@v1.1.1
(45/49) Wrote golang.org/x/text@v0.3.0
(46/49) Wrote golang.org/x/sys@master
(47/49) Wrote github.com/gorilla/mux@v1.6.2
(48/49) Wrote github.com/tendermint/iavl@v0.7.0
(49/49) Wrote github.com/tendermint/tendermint@v0.19.7-rc0

**Comment by melekes** [comment]
> dep: WARNING: Unknown field in manifest: prune

you can ignore this WARNING

> This is the path /home/zhr/goApps/src/github.com/tendermint/tendermint/vendor/golang.org/x/crypto/ripemd160. I donnot find Gopkg.toml in this path.

This folder does not have to contain `Gopkg.toml`. It's only projects who are using https://github.com/golang/dep, have `Gopkg.toml` in their root directories.

> Is anythin wrong ?

do you still experience errors or you managed to fix them?

**Comment by ying2025** [comment]
Yes I have

**Comment by melekes** [comment]
> Yes I have

have errors?

**Comment by ying2025** [comment]
Firstly
![image](https://user-images.githubusercontent.com/28092539/40903369-bb7d7e42-6809-11e8-828f-636886b7017a.png)

**Comment by ying2025** [comment]
GOROOT=/usr/lib/go-1.10 #gosetup
GOPATH=/home/zhr/goApps #gosetup
/usr/lib/go-1.10/bin/go build -i -o /tmp/___go_build_github_com_tendermint_tendermint github.com/tendermint/tendermint #gosetup
can't load package: package github.com/tendermint/tendermint: no Go files in /home/zhr/goApps/src/github.com/tendermint/tendermint

Compilation finished with exit code 1

**Comment by melekes** [comment]
use `make build` or `go build ./cmd/tendermint`. If you're using IDE, you can setup custom build command in Setting -> Build

**Comment by ying2025** [comment]
I have make bulid before I run it in IDE

**Comment by ying2025** [comment]
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ make build
CGO_ENABLED=0 go build -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD`" -tags 'tendermint' -o build/tendermint ./cmd/tendermint/

**Comment by ying2025** [comment]
This is the GOPATH that I set
![image](https://user-images.githubusercontent.com/28092539/40903716-eedbcc84-680a-11e8-9696-3933bd33dd66.png)

**Comment by melekes** [comment]
If you wanna change this behaviour https://github.com/tendermint/tendermint/issues/1660#issuecomment-394256449, you MUST change default build cmd from `go build` to `go build ./cmd/tendermint`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Check out `Build, Execution, Deployment` tab.

**Comment by ying2025** [comment]
I donnot change "Build, Execution, Deployment tab". I donnot know what I should check ?

**Comment by ying2025** [comment]
I am considering that why it cannot 
can't load package: package github.com/tendermint/tendermint: no Go files in /home/zhr/goApps/src/github.com/tendermint/tendermint

**Comment by melekes** [comment]
https://www.jetbrains.com/help/go/install-and-set-up-product.html#first-run

If you need to adjust your run configuration or create a new one for running or testing, use Run/Debug Configurations.

On the main menu, select Run | Edit Configurations.

In the Run/Debug Configurations dialog, click add and from the list that opens, select the appropriate configuration.

The Go Build type is equal to go build command.
The Go Test type is equal to go test. Make sure to select the test framework your tests use: gotest, gocheck or gobench.
The Go App Engine type lets you run Go App Engine applications. Note, it requires your Go module to use a Go AppEngine SDK.

Specify the run configuration options. You can also specify Before Launch options, for example, you can add a Go command that you want to run before executing the created configuration. Click OK.
On the main menu, select Run | Run or press ⇧⌘F10.

**Comment by ying2025** [comment]
Ok, I will try it now

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/40906253-db40c28a-6812-11e8-89ea-fabb9c58b48c.png)

**Comment by melekes** [comment]
> Is it success ?

yes, congratulations! 🎆

**Comment by gauthamzz** [comment]
While doing `make get_vendor_deps` the command gets stuck and nothing is happening afterwards. No error as well. It shows only `--> Running dep` and then nothing happens?

Everything till `make get_tools` is working.

Using Ubuntu 18.04 terminal inside windows 10.

**Comment by zramsay** [comment]
it can take a while the first time, without printing anything to the screen. how long are you waiting?

**Comment by gauthamzz** [comment]
Like 3-4 hours, i kept it on and slept on it and its not working. 

I just want to use the abci-cli, everything else is working using the binary release which i am using at the moment. Is there any way to use abci-cli using like that?

**Comment by ebuchman** [comment]
Any chance you're in China? 

You don't see any output with `dep ensure -v` ? 

You can try installing the abci-cli with `make install_abci`

**Comment by gauthamzz** [comment]
I'm in India but i am under a proxy server. But had set proxy using export http://proxy:port etc. 

When i do `dep ensure -v` nothing comes.

while doing `make install_abci`  the following error comes.

````
 libs/log/logger.go:6:2: cannot find package "github.com/go-kit/kit/log" in any of:                                          
        /usr/lib/go-1.10/src/github.com/go-kit/kit/log (from $GOROOT)                                                       
        /home/gautham/go/src/github.com/go-kit/kit/log (from $GOPATH)                                                       
libs/log/tm_logger.go:8:2: cannot find package "github.com/go-kit/kit/log/level" in any of:                                 
        /usr/lib/go-1.10/src/github.com/go-kit/kit/log/level (from $GOROOT)                                                 
        /home/gautham/go/src/github.com/go-kit/kit/log/level (from $GOPATH)                                                 
libs/log/testing_logger.go:7:2: cannot find package "github.com/go-kit/kit/log/term" in any of:                             
        /usr/lib/go-1.10/src/github.com/go-kit/kit/log/term (from $GOROOT)                                                  
        /home/gautham/go/src/github.com/go-kit/kit/log/term (from $GOPATH)                                                  
libs/log/tmfmt_logger.go:12:2: cannot find package "github.com/go-logfmt/logfmt" in any of:                                 
        /usr/lib/go-1.10/src/github.com/go-logfmt/logfmt (from $GOROOT)                                                     
        /home/gautham/go/src/github.com/go-logfmt/logfmt (from $GOPATH)                                                     
abci/types/types.pb.go:7:8: cannot find package "github.com/golang/protobuf/proto" in any of:                               
        /usr/lib/go-1.10/src/github.com/golang/protobuf/proto (from $GOROOT)                                                
        /home/gautham/go/src/github.com/golang/protobuf/proto (from $GOPATH)                                                
abci/types/types.pb.go:11:8: cannot find package "github.com/golang/protobuf/ptypes/timestamp" in any of:                   
        /usr/lib/go-1.10/src/github.com/golang/protobuf/ptypes/timestamp (from $GOROOT)                                     
        /home/gautham/go/src/github.com/golang/protobuf/ptypes/timestamp (from $GOPATH)                                     
libs/common/date.go:7:2: cannot find package "github.com/pkg/errors" in any of:                                             
        /usr/lib/go-1.10/src/github.com/pkg/errors (from $GOROOT)                                                           
        /home/gautham/go/src/github.com/pkg/errors (from $GOPATH)                                                           
abci/cmd/abci-cli/abci-cli.go:12:2: cannot find package "github.com/spf13/cobra" in any of:                                 
        /usr/lib/go-1.10/src/github.com/spf13/cobra (from $GOROOT)                                                          
        /home/gautham/go/src/github.com/spf13/cobra (from $GOPATH)                                                          
libs/db/go_level_db.go:8:2: cannot find package "github.com/syndtr/goleveldb/leveldb" in any of:                            
        /usr/lib/go-1.10/src/github.com/syndtr/goleveldb/leveldb (from $GOROOT)                                             
        /home/gautham/go/src/github.com/syndtr/goleveldb/leveldb (from $GOPATH)                                             
libs/db/go_level_db.go:9:2: cannot find package "github.com/syndtr/goleveldb/leveldb/errors" in any of:                     
        /usr/lib/go-1.10/src/github.com/syndtr/goleveldb/leveldb/errors (from $GOROOT)                                      
        /home/gautham/go/src/github.com/syndtr/goleveldb/leveldb/errors (from $GOPATH)                                      
libs/db/go_level_db.go:10:2: cannot find package "github.com/syndtr/goleveldb/leveldb/iterator" in any of:                  
        /usr/lib/go-1.10/src/github.com/syndtr/goleveldb/leveldb/iterator (from $GOROOT)                                    
        /home/gautham/go/src/github.com/syndtr/goleveldb/leveldb/iterator (from $GOPATH)                                    
libs/db/go_level_db.go:11:2: cannot find package "github.com/syndtr/goleveldb/leveldb/opt" in any of:                       
        /usr/lib/go-1.10/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOROOT)                                         
        /home/gautham/go/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOPATH)                                         
crypto/merkle/simple_map.go:6:2: cannot find package "github.com/tendermint/go-amino" in any of:                            
        /usr/lib/go-1.10/src/github.com/tendermint/go-amino (from $GOROOT)                                                  
        /home/gautham/go/src/github.com/tendermint/go-amino (from $GOPATH)                                                  
abci/types/application.go:4:2: cannot find package "golang.org/x/net/context" in any of:                                    
        /usr/lib/go-1.10/src/golang.org/x/net/context (from $GOROOT)                                                        
        /home/gautham/go/src/golang.org/x/net/context (from $GOPATH)                                                        
abci/types/types.pb.go:21:2: cannot find package "google.golang.org/grpc" in any of:                                        
        /usr/lib/go-1.10/src/google.golang.org/grpc (from $GOROOT)                                                          
        /home/gautham/go/src/google.golang.org/grpc (from $GOPATH)                                                          
Makefile:60: recipe for target 'install_abci' failed                                                                        
make: *** [install_abci] Error 1   
```                `

**Comment by ebuchman** [comment]
Are you able to build other go projects successfully? Maybe try updating your version of Go and dep? Not exactly sure what the problem is ...

**Comment by melekes** [comment]
Make sure your the Tendermint repo is located at `/home/gautham/go/src/github.com/tendermint/tendermint`
