### ISSUE TITLE
Tendermint on non-deterministic signatures

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1664]
Tendermint's logic hasn't been vetted for non-deterministic signatures. It needs to be investigated if the current logic holds for non-determinstic signatures. The signer can always create multiple valid signatures on the same message in both secp and ed25519

**Comment by ebuchman** [comment]
We should write tests for this in the `consensus` pkg and probably in the `lite` package and document the relevant behaviour around this for any code that handles signatures.
