### ISSUE TITLE
Why do we have non-deterministic signatures detected, if we're using deterministic signatures

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1665]
Currently both of our signature implementations (ecdsa-rfc6979*, eddsa) are determinstic. However on a testnet, I setup two validators both with the same private key, and we got this error on a different validator:
```
E[05-31|22:35:44.815] Error attempting to add vote                 module=consensus err="Existing vote: Vote{3:6DB70BE14EC0 856/00/2(Precommit) A3CC327836C9 /3485477804D5.../ @ 2018-05-31T22:35:44.576Z}; New vote: Vote{3:6DB70BE14EC0 856/00/2(Precommit) A3CC327836C9 /09CF83A3DCC7.../ @ 2018-05-31T22:35:44.646Z}: Non-deterministic signature"
```
Where did this error come from, since we're using only deterministic signature algorithms in go-crypto?

* RFC6979 is making the nonce for ecdsa deterministically chosen.

**Comment by ebuchman** [comment]
It's because the timestamps are different. Not sure the error really needs to change for this.

That said we're going to remove the timestamp from being signed, so that won't happen
