### ISSUE TITLE
Wrong result  of validator's Accum when node recovery to communicate with other node 

### ISSUE THREAD

**Issue by solderain** [tendermint/tendermint#1666]
**Tendermint code version 0.16**

![image](https://user-images.githubusercontent.com/4144738/40818822-a6c91a90-658b-11e8-9974-fbead5766d89.png)

Above code , since the current node may miss some vote round  at the same height , have to update validatorSet's Accum when it gets well , so that it select right proposer .  

But notice the code of Robin-Round selection implemention as below : 
![image](https://user-images.githubusercontent.com/4144738/40819383-63fc1f62-658d-11e8-9ad1-e41a9a9c06d8.png)

It will miss ( round-cs.round - 1) times  votepower for each validator . How does that node select the right proposer ?

**Comment by melekes** [comment]
Do you have a test case at hand? Care to write one?

**Comment by ebuchman** [comment]
Note proposer selection across heights is independent from that across rounds.

If I'm proposer for (H, 0), and you're proposer for (H, 1), you're also proposer for (H+1, 0).

I opened a new issue to document this better: https://github.com/tendermint/tendermint/issues/1668

If you have a test case, please re-open the issue. 

Thanks for reviewing the code :)

**Comment by solderain** [comment]
Got it , thanks everyone
