### ISSUE TITLE
Maybe some validator prevote nil due to proposalBlock is null (no wait for proposer broadcast proposal then send msg for pervote at once)  in the first few rounds

### ISSUE THREAD

**Issue by solderain** [tendermint/tendermint#1674]
tendermint version 0.16 
![image](https://user-images.githubusercontent.com/4144738/40873475-3804ff6c-6693-11e8-86f7-b0e6f5ff45b3.png)

Base on the above code "enterpropose" , found the proposer will execute prevote while it finish propose a proposal at once .  however ， if other validator receive the msg for prevote first  but not receive  msg for ProposalMessage  yet  , so it will provote nil for current round. follow the bellow code 
![image](https://user-images.githubusercontent.com/4144738/40873532-4d9a872e-6694-11e8-8a16-a70d402f2a0c.png)

So , how to assure the order  of proposalMessage and prevoteMessage ?

**Comment by ebuchman** [comment]
It's an asynchronous system, so we can't guarantee it. But validators wait "TimeoutPropose" before they enterPrevote to give time to receive the proposal. If they receive a prevote from someone before the proposal, that's fine, they will still wait the TimeoutPropose to receive the proposal. Only if they receive +2/3 prevotes before TimeoutPropose will they move on.

Thanks for the question!
