### ISSUE TITLE
Problem with  tendermint node --proxy_app=kvstore

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1678]
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint init
NOTE[06-04|01:28:00] Initialized tendermint                   module=main genesis=/home/zhr/.tendermint/genesis.json priv_validator=/home/zhr/.tendermint/priv_validator.json
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint node --proxy_app=kvstore
NOTE[06-04|01:28:07] Loaded PrivValidator                     module=types file=/home/zhr/.tendermint/priv_validator.json privValidator="PrivValidator{50B4FA5F48443DD373EC3D71C4A791C28EC11315 LH:0, LR:0, LS:0}"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tendermint/go-common.Connect(0x7ffe5e988349, 0x7, 0x28000000000002, 0x33, 0xb, 0x410eb2)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/net.go:11 +0xc5
github.com/tendermint/abci/client.(*socketClient).OnStart(0xc420090000, 0x60, 0xc42001b4a0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:68 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc420090000, 0x0, 0xc42001b4a0, 0xc4204a8fc0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/abci/client.NewSocketClient(0x7ffe5e988349, 0x7, 0xc4204b4100, 0x0, 0x0, 0xc4200bb708)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:57 +0x23c
github.com/tendermint/abci/client.NewClient(0x7ffe5e988349, 0x7, 0xac2e46, 0x6, 0x0, 0x2, 0xc4204a8f80, 0x4, 0x4)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/client.go:49 +0x17a
github.com/tendermint/tendermint/proxy.(*remoteClientCreator).NewABCIClient(0xc4204ae4b0, 0xc4204b41b0, 0xd40c90, 0xc4204a8f80, 0xf02a00)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/client.go:57 +0x55
github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc4204b4120, 0xc42000c840, 0x15)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/multi_app_conn.go:78 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc4204b4120, 0x0, 0x0, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/tendermint/node.NewNode(0xec7480, 0xc42049c700, 0xc420091ea0, 0xeba520, 0xc4204ae4b0, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:68 +0x47a
github.com/tendermint/tendermint/node.NewNodeDefault(0xec7480, 0xc42049c700, 0x1)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:51 +0xba
github.com/tendermint/tendermint/node.RunNode(0xec7480, 0xc42049c700)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:350 +0x4fa
main.main()
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:42 +0x2e4

**Comment by melekes** [comment]
tendermint 0.8.0 is too old and no longer supported. please upgrade to 0.19.X https://github.com/tendermint/tendermint/releases/tag/v0.19.7

**Comment by ying2025** [comment]
It happens the same thing when I download the "tendermint_0.19.7_linux_amd64.zip"
![image](https://user-images.githubusercontent.com/28092539/40949081-cdb9feb0-689e-11e8-9777-e580e96ece05.png)
![image](https://user-images.githubusercontent.com/28092539/40949103-f6443f80-689e-11e8-870c-51170159313f.png)

**Comment by melekes** [comment]
Could you please paste the stack trace as text, not image?

**Comment by ying2025** [comment]
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint init
NOTE[06-05|17:37:28] Initialized tendermint                   module=main genesis=/home/zhr/.tendermint/genesis.json priv_validator=/home/zhr/.tendermint/priv_validator.json
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint node --proxy_app=kvstore
NOTE[06-05|17:37:40] Loaded PrivValidator                     module=types file=/home/zhr/.tendermint/priv_validator.json privValidator="PrivValidator{0DA6A6801EE474373CB53C066C1CE3F47BE22AB8 LH:0, LR:0, LS:0}"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tendermint/go-common.Connect(0x7fffd5f18317, 0x7, 0x13000000000002, 0x33, 0xb, 0x410eb2)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/net.go:11 +0xc5
github.com/tendermint/abci/client.(*socketClient).OnStart(0xc420492000, 0x60, 0xc42001b4a0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:68 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc420492000, 0x0, 0xc42001b4a0, 0xc42048d280)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/abci/client.NewSocketClient(0x7fffd5f18317, 0x7, 0xc4204a2000, 0x0, 0x0, 0xc4200bb708)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:57 +0x23c
github.com/tendermint/abci/client.NewClient(0x7fffd5f18317, 0x7, 0xac2e46, 0x6, 0x0, 0x2, 0xc42048d240, 0x4, 0x4)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/client.go:49 +0x17a
github.com/tendermint/tendermint/proxy.(*remoteClientCreator).NewABCIClient(0xc42048ee70, 0xc4204a2090, 0xd40c90, 0xc42048d240, 0xf02a00)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/client.go:57 +0x55
github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc4204a2000, 0xc420487160, 0x15)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/multi_app_conn.go:78 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc4204a2000, 0x0, 0x0, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/tendermint/node.NewNode(0xec7480, 0xc420487180, 0xc420493900, 0xeba520, 0xc42048ee70, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:68 +0x47a
github.com/tendermint/tendermint/node.NewNodeDefault(0xec7480, 0xc420487180, 0x1)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:51 +0xba
github.com/tendermint/tendermint/node.RunNode(0xec7480, 0xc420487180)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:350 +0x4fa
main.main()
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:42 +0x2e4

**Comment by ebuchman** [comment]
```
goroutine 1 [running]:
github.com/tendermint/go-common.Connect(0x7fffd5f18317, 0x7, 0x13000000000002, 0x33, 0xb, 0x410eb2)
/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/net.go:11 +0xc5
```

Looks like you are still using Tendermint v0.8.0....

**Comment by ying2025** [comment]
But I have replace "tendermint " with the file of  "tendermint_0.19.7"  
![image](https://user-images.githubusercontent.com/28092539/41011808-28982802-6971-11e8-85f8-311abb3f1cc7.png)
