### ISSUE TITLE
tendermint node --proxy_app=kvstore Problems

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1682]
It happens the same thing when I download the "tendermint_0.19.7_linux_amd64.zip" and replace tendermint with "tendermint_0.19.7"
![image](https://user-images.githubusercontent.com/28092539/40949283-e680cf36-689f-11e8-9cd5-e15dc9ccf760.png)

![image](https://user-images.githubusercontent.com/28092539/40949081-cdb9feb0-689e-11e8-9777-e580e96ece05.png)
![image](https://user-images.githubusercontent.com/28092539/40949103-f6443f80-689e-11e8-870c-51170159313f.png)
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint init
NOTE[06-04|17:58:54] Initialized tendermint                   module=main genesis=/home/zhr/.tendermint/genesis.json priv_validator=/home/zhr/.tendermint/priv_validator.json
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$  tendermint node --proxy_app=kvstore
NOTE[06-04|17:59:09] Loaded PrivValidator                     module=types file=/home/zhr/.tendermint/priv_validator.json privValidator="PrivValidator{0F57EF8B569F1DD4C738452A7066DBD6C7FF843E LH:0, LR:0, LS:0}"
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/tendermint/go-common.Connect(0x7ffd525f3331, 0x7, 0x19000000000002, 0x33, 0xb, 0x410eb2)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/net.go:11 +0xc5
github.com/tendermint/abci/client.(*socketClient).OnStart(0xc420470000, 0x60, 0xc420469020)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:68 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc420470000, 0x0, 0xc420469020, 0xc420018e40)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/abci/client.NewSocketClient(0x7ffd525f3331, 0x7, 0xc420478300, 0x0, 0x0, 0xc4200bf708)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/socket_client.go:57 +0x23c
github.com/tendermint/abci/client.NewClient(0x7ffd525f3331, 0x7, 0xac2e46, 0x6, 0x0, 0x2, 0xc420018e00, 0x4, 0x4)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/abci/client/client.go:49 +0x17a
github.com/tendermint/tendermint/proxy.(*remoteClientCreator).NewABCIClient(0xc420465d40, 0xc420478360, 0xd40c90, 0xc420018e00, 0xf02a00)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/client.go:57 +0x55
github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart(0xc4204782d0, 0xc42012d620, 0x15)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/proxy/multi_app_conn.go:78 +0x3e
github.com/tendermint/go-common.(*BaseService).Start(0xc4204782d0, 0x0, 0x0, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/go-common/service.go:96 +0x2c2
github.com/tendermint/tendermint/node.NewNode(0xec7480, 0xc42012cc40, 0xc420091860, 0xeba520, 0xc420465d40, 0x0)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:68 +0x47a
github.com/tendermint/tendermint/node.NewNodeDefault(0xec7480, 0xc42012cc40, 0x1)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:51 +0xba
github.com/tendermint/tendermint/node.RunNode(0xec7480, 0xc42012cc40)
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/node/node.go:350 +0x4fa
main.main()
	/build/tendermint-J_eVDl/tendermint-0.8.0+git20170113.0.764091d/obj-x86_64-linux-gnu/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:42 +0x2e4

**Comment by melekes** [comment]
Please stop creating duplicate issues. I've told you, you are using the old version of Tendermint (0.8.0).

![tendermint_node_--proxy_app_kvstore_problems_ _issue__1682_ _tendermint_tendermint](https://user-images.githubusercontent.com/1282182/40958211-84f87368-68a9-11e8-9f56-b784b755be4c.png)

If you want to use newer version, do:

```
$ rm -rf /goApps/src/github.com/tendermint/tendermint
$ rm -rf /goApps/bin/tendermint
$ mkdir -p /goApps/src/github.com/tendermint/tendermint
$ cd /goApps/src/github.com/tendermint/tendermint
$ git clone https://github.com/tendermint/tendermint.git
$ make get_tools
$ make install
$ rm -rf ~/.tendermint
$ tendermint unsafe_reset_all
$ tendermint node --proxy_app=kvstore
```

**Comment by ying2025** [comment]
I reinstall it as you say. But it is still 0.8.
![image](https://user-images.githubusercontent.com/28092539/41018693-a4428ed6-698d-11e8-81f7-4d2caf1a22cd.png)
![image](https://user-images.githubusercontent.com/28092539/41018851-8434fb78-698e-11e8-9345-b1fe4693d577.png)
![image](https://user-images.githubusercontent.com/28092539/41018977-43a4f486-698f-11e8-88c5-1fb857595458.png)

**Comment by ying2025** [comment]
And I try to switch a new branch , but why it still is 0.8
![image](https://user-images.githubusercontent.com/28092539/41019981-aedc6e60-6993-11e8-88c6-8dcb771f2c22.png)

**Comment by ying2025** [comment]
I install by "git clone https://github.com/tendermint/tendermint.git"

**Comment by zramsay** [comment]
@ying2025 from your terminal run the command `which tendermint` and paste the output here

**Comment by ying2025** [comment]
It located /usr/tendermint. I have remove it. And now it is ok. Thank your team.

**Comment by ying2025** [comment]
Maybe I have install a binary causing this situation happened.
