### ISSUE TITLE
dep ensure not working

### ISSUE THREAD

**Issue by xblocksys** [tendermint/tendermint#1684]
I use dep to manage dependency

**I run under command**
$ dep ensure -add github.com/tendermint/tendermint

**Error Message**
v0.19.8: Could not introduce github.com/tendermint/tendermint@v0.19.8, as its subpackage github.com/tendermint/tendermint does not contain usable Go code (*build.NoGoError).. (Package is required by (root).)

I think that your project include relative path.

**Comment by melekes** [comment]
root directory does not contain any Go code. If you want to use tendermint as a library, you need to add subpackages:

```
dep ensure -add github.com/tendermint/tendermint/types
```

Please reopen if that does not work for you.
