### ISSUE TITLE
Ability to run seed node without an app

### ISSUE THREAD

**Issue by slavaboiko** [tendermint/tendermint#1686]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST:

I would like to see possibility to run tendermint in a Seed Mode without having application attached to it.
Meaning: using seed node for pure node discovery.
The current project requires to have data (using BigchainDB with tendermint) to be stored only on the network participants and to be able to have node discovery. 
Currently, if you run seed node without an app, it's constantly erroring and doesn't appear to be working.
I would like to have possibility to enable node discovery without providing an ABCI application along with it.

**Tendermint version** : 0.19.2

**ABCI app** : BigchainDB

**Environment**: Docker with Ubuntu

**What happened**: Errors connecting to the app

**What you expected to happen**: Seed node running successfully

**How to reproduce it** (as minimally and precisely as possible): enable seed_mode and don't point it to any app

**Logs (you can paste a part showing an error or attach the whole file)**:
```
E[06-05|10:21:26.084] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
```

**Comment by ebuchman** [comment]
me too!!

**Comment by kidinamoto01** [comment]
it could be an App which constantly does handshakes with peers and asks for new peer address.

**Comment by slavaboiko** [comment]
can seed node have different app then other nodes?

**Comment by ebuchman** [comment]
> can seed node have different app then other nodes?

Technically no. The results it returns must match those returned by the main app otherwise there will be consensus failure.

That said we should add a mode that ignores the state execution and just takes whatever the blockchain says as fact. Then you can have whatever app you want

**Comment by srmo** [comment]
Uhm, consider a network where the only node you see is the seed node (because of some network partitioning / routing problem / whatever).
As each node is required to relay / broadcast message from the chain (including votes+proposals), how will you be able to trust such a node? Given that this network scenario isn't only relevant here. Just wondering how the seed node itself will trust the packages it sees without being able to verify appState.

**Comment by jackzampolin** [comment]
If you need one its here: https://gitlab.com/polychainlabs/tenderseed
