### ISSUE TITLE
Can we run a localnet with more than 4 nodes?

### ISSUE THREAD

**Issue by mohamedGr** [tendermint/tendermint#1691]
Hi,

I would like to run tendermint on a localnet (using the `make localnet-start` command) with more than 4 nodes. Is that possible? If yes, could you please tell me what are the steps required to do that?

Thank you for your help

**Comment by melekes** [comment]
1. add new nodes in `docker-compose.yml`
2. modify the number of validators in `localnet-start`

```
	@if ! [ -f build/node0/config/genesis.json ]; then docker run --rm -v $(CURDIR)/build:/tendermint:Z tendermint/localnode testnet --v 4 --o . --populate-persistent-peers --starting-ip-address 192.167.10.2 ; fi
```

`--v 4` to whatever you want

**Comment by melekes** [comment]
Next time please ask you question on https://stackoverflow.com/questions/tagged/tendermint or Riot chat (https://riot.im/app/#/room/#tendermint:matrix.org) since it's not really an issue.
