### ISSUE TITLE
consensus: replace synchronous events system with a function call

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1692]
Following up on https://github.com/tendermint/tendermint/issues/951 and https://github.com/tendermint/tendermint/issues/1495

Currently the ConsensusState notifies the ConsensusReactor of messages to broadcast using a synchronous event system.

Instead, we should use an `update` method in the ConsensusState (ala https://github.com/tendermint/tendermint/issues/1495#issuecomment-393140116) to process incoming messages and return any messages to broadcast to peers.

**Comment by jackzampolin** [comment]
Closing this in favor of the currently in progress refactor of the reactors
