### ISSUE TITLE
Bounding resource usage in Tendermint

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#1696]
General idea is overall understanding and control of resources used for processing of every kind of message. This is the preliminary thoughts based on discussions with @melekes.

- RPC:
  - public APIs, submit part. No limit on data length. We need to have limit on
  request size. We want to constrain number of open connections. Connections
  can be one shot (http) or persistent (websocket). For persistent connections,
  we want to limit number of outstanding requests in a period of time. If client
  submits over broadcast_commit then it is necessary in addition to constrain number
  of outstanding requests as each request requires creating request context so consumes
  resources.
  - public APIs, query part. Rate limit number of calls for every endpoint. Bound response size.
  - public APIs, subscribe. Bound number of open subscriptions.

Peer connection management:
- persistent connections to k peers. We bound maxNumberOfPeers. We don't accept
more connections than this number. There is also a bound on number of outgoing connections.
For each connection we want to constrain resources used per message type and
put limit on message size.

Question: Do we want to have global contract on resource usage, i.e., what part of available
bandwidth will be used for Mempool messages, how much for consensus, fast sync, etc.
The follow up question is how we can enforce this. Is this static setup or it should be
adapted based on node state and the state of its peers.

Question: Do we want to have separate connections for sending and receiving of messages?

CPU: We want to know number of go routines and correlation with number of peers and
number of client connections and subscriptions. Number of go routines should be bounded.
Performance analysis of Tendermint should be done. We want to understand number and usage of
routines, and what are the bottlenecks.

Memory: Memory usage should be bounded and consistent. Profiling of memory usage is
needed. Correlation with number of peers and number of client connections and subscriptions should be determined.

Disk usage: We want to place constraint on reading/writing to disk.

**Comment by xla** [comment]
Addition

Network: Usage of bandwidth should be able to be capped.

Question: Do we want to promote feedback about reasons for rejections (i.e. max number of peers hit) as part of the protocol?

**Comment by milosevic** [comment]
@xla This is very good question. We discussed it with @melekes also. My feeling is that this should be part of the protocol, as honest node should understand why someone disconnected from him if he is doing everything properly. This is especially important if you take into account that percentage of resources used on particular activity will most probably be configurable. So there need to be some sort of network consensus on "correct" and "fair" values of these parameters so network as a whole behave in the optimal way, and this should probably be part of the protocol.

**Comment by xla** [comment]
Related #1740
