### ISSUE TITLE
Allow to specify inbound peer for which we always accept connections

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1700]
Sentry nodes should be able to specify inbound peer-ids that are always accepted without regards for max peer limits.

@ebuchman @xla We talked about it today.

**Comment by jackzampolin** [comment]
think we call this persistent peer, closing.

**Comment by ebuchman** [comment]
This is a bit different. This is saying that even if we have full connections, we should still accept connections from certain peers. It's over and above persistent peers.

It's especially important if sentries lose connection to their validator, but fill up their peer slots, and then the validator can't dial back in.

**Comment by ebuchman** [comment]
Is this resolved by ADR-50 and #4176 ?

**Comment by marbar3778** [comment]
yes
