### ISSUE TITLE
Allow persistent peers to be private

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1705]
It should be possible to add a peer to `persisent_peers` and to `private_peer_ids` at the same time. I may want to connect to @ebuchman and @jaekwon privately and tell neither of them the other ones IP.

**Comment by melekes** [comment]
Merged to develop. Will be shipped with 0.22.5 or next breaking release.

**Comment by Creamers158** [comment]
Am using sentinel v0.1.0 on sentinel-turing-1 testnet. Seems that a 
sentry with a peer to both persistent_peers and private_peer_ids is 
still gossiped to to the network in some cases @xla 
(Can't put my finger on it myself but not doing so solved my problem, also some cosmos validators agree with this argument)

**Comment by marbar3778** [comment]
I haven't observed private peers being gossiped in public networks nor in internal testing.

To the original question, would it be beneficial for `/dial_peers` to have a private flag in which a user can set if it would like the peers to be private as well?

**Comment by melekes** [comment]
> To the original question, would it be beneficial for /dial_peers to have a private flag in which a user can set if it would like the peers to be private as well?

It makes sense to support `private` and `unbounded` flags because we already support `persistent` bool flag from the API perspective.

**Comment by melekes** [comment]
an old one 🧓 good job @marbar3778 💪
