### ISSUE TITLE
Ensure that IP addresses that are received from private peers are not gossiped through the PEX

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1706]
If I receive IPs from a peer that I declared as private, my node should never gossip those IPs, but it still may connect to them.

@jaekwon @ebuchman

**Comment by melekes** [comment]
Hm... I am pretty sure this is the case right now. Do you have any proof of the opposite scenario?

**Comment by ebuchman** [comment]
We don't gossip the address `addrP` of the private peer itself, but if we receive an address `addrQ` from that private peer, we might gossip `addrQ`.

**Comment by melekes** [comment]
Oh, right. Sorry for asking stupid questions.

**Comment by melekes** [comment]
Rejecting part is done https://github.com/tendermint/tendermint/pull/2032
"but it still may connect to them." this is harder

**Comment by adrianbrink** [comment]
Nice, thank you @melekes

**Comment by ebuchman** [comment]
Can we close this?
