### ISSUE TITLE
No address property  for validator  in  "ResponseEndBlock"

### ISSUE THREAD

**Issue by solderain** [tendermint/tendermint#1708]
Tendermint 0.16
There is a way to update ValidatorSet when finish callback endBlock via return updateValidators , but there is no address property for validator in ResponseEndBlock ?
![image](https://user-images.githubusercontent.com/4144738/41102613-e590b568-6a99-11e8-95dc-33b804048707.png)

**Comment by ebuchman** [comment]
You *must* provide the PubKey to Tendermint.

We just released v0.20.0 where the Address is included as well, but you still MUST provide the PubKey to Tendermint.

**Comment by solderain** [comment]
Read code again , notice the validator's address value is hash(PubKey) , not the real IP Address , right ? @ebuchman

**Comment by ebuchman** [comment]
Right this is a cryptographic address, not an internet address

**Comment by solderain** [comment]
Got it , thank you very much !
