### ISSUE TITLE
First Tendermint App is failing "Error reading message: proto: bad wiretype ...

### ISSUE THREAD

**Issue by flockonus** [tendermint/tendermint#1709]
**Is this a BUG REPORT**

**Tendermint version** 0.19.9-057e076c (installed today)

**Environment**:
- **OS** (e.g. from /etc/os-release): macos 10.13.4
- **Install tools**:  go version go1.10.1 darwin/amd64

**What happened**:
Followed http://tendermint.readthedocs.io/en/master/install.html to install tendermint, it worked, even the last section to run, seems like it's running as blocks are being mined.

But then at [First Tendermint App](http://tendermint.readthedocs.io/en/master/getting-started.html) won't go through.
The step `abci-cli kvstore` seems to initialize by itself.
But on a new terminal window I run `tendermint init; tendermint node` and but get:

```
$ tendermint node
I[06-07|17:46:29.083] Starting multiAppConn                        module=proxy impl=multiAppConn
I[06-07|17:46:29.083] Starting socketClient                        module=abci-client connection=query impl=socketClient
I[06-07|17:46:29.084] Starting socketClient                        module=abci-client connection=mempool impl=socketClient
I[06-07|17:46:29.084] Starting socketClient                        module=abci-client connection=consensus impl=socketClient
I[06-07|17:46:29.086] ABCI Handshake                               module=consensus appHeight=0 appHash=
I[06-07|17:46:29.086] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
E[06-07|17:46:29.086] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
I[06-07|17:46:29.087] Stopping socketClient                        module=abci-client connection=consensus impl=socketClient
```

First terminal window logs:

```
$ abci-cli kvstore
I[06-07|17:46:24.974] Starting ABCIServer                          module=abci-server impl=ABCIServer
I[06-07|17:46:24.974] Waiting for new connection...                module=abci-server
I[06-07|17:46:29.084] Accepted a new connection                    module=abci-server
I[06-07|17:46:29.084] Waiting for new connection...                module=abci-server
I[06-07|17:46:29.084] Accepted a new connection                    module=abci-server
I[06-07|17:46:29.085] Waiting for new connection...                module=abci-server
I[06-07|17:46:29.085] Accepted a new connection                    module=abci-server
I[06-07|17:46:29.085] Waiting for new connection...                module=abci-server
E[06-07|17:46:29.086] Connection error                             module=abci-server error="Error reading message: proto: bad wiretype for field types.RequestInitChain.Time: got wiretype 2, want 0"
```

**Comment by ebuchman** [comment]
What version of abci-cli ? We just released v0.11 which works with Tendermint v0.20, but need to use abci-cli v0.10 for Tendermint v0.19

**Comment by flockonus** [comment]
@ebuchman just downloaded the whole kit yesterday:

$ abci-cli version
0.11.0

**Comment by flockonus** [comment]
thanks for the info, i pulled the latest master from tendermint and installed again, now it works.

It was probably just a matter of terrible timing of pulling the 2 parts that were temp. in different versions.

**Comment by mh739025250** [comment]
I meet the same problem today.
The Tendermint version is v0.23.0 and the abci-cli version is 0.12.0.

**Comment by rubiconluke** [comment]
I'm seeing this issue now: Tendermint v0.23.0 and abc-cli version is 0.12.0. Did something break again?

**Comment by ebuchman** [comment]
Did you already have abci-cli installed?

We merged the ABCI repo into tendermint to lower development overhead.

See the updated docs: https://tendermint.com/docs/app-dev/getting-started.html#first-tendermint-app

If you run `make install_abci` from tendermint you should get the right version of abci-cli. It will still say v0.12.0 but that's a bug, we forgot to bump the version: https://github.com/tendermint/tendermint/issues/2266

Please let us know if that still doesn't work. Thanks!

**Comment by mh739025250** [comment]
@ebuchman 
Thank you for info. I reinstalled the abci-cli by `make install_abci`, and it sloved the problem.

**Comment by rubiconluke** [comment]
@ebuchman
Thanks for the info. Works fine now.
