### ISSUE TITLE
Don't send PubKey in RequestBeginBlock

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1712]
See the new ADR! https://github.com/tendermint/tendermint/pull/1711 - line https://github.com/tendermint/tendermint/pull/1711/files#diff-404a968fa4fd1a4f4ea21c40b513bc53R181

- Don't send Pubkey in RequestBeginBlock because they're big and we would be sending them all each time (!)
- Don't send Address in ResponseEndBlock because we don't need it.

**Comment by melekes** [comment]
1) done in https://github.com/tendermint/tendermint/pull/2074
2) should we change anything on Tendermint side except docs? created https://github.com/tendermint/tendermint/pull/2117

**Comment by ebuchman** [comment]
I think it's worth being more explicit in the types.

ie. make SigningValidator just contain address, power, and signed_last_block instead of containing a generic Validator where the pubkey is supposed to be empty.

I think we could then also remove address from the Validator message. 

Then it's super clear in the message structure what you get and what you need to return (ie. get addresses on BeginBlock, return PubKeys everywhere else)

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/2156
