### ISSUE TITLE
If you only have a seed, and its down, tendermint p2p crashes

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1716]
I only had one seed in the config.toml, 
`seeds = "80a35a46ce09cfb31ee220c8141a25e73e0b239b@cosmos.cryptium.ch:46656"`

I ran `gaiad start`. The seed was down, and I got the following error message:
```
I[06-08|09:08:46.084] Starting AddrBook                            module=p2p book=/root/.gaiad/config/addrbook.json impl=AddrBook
ERROR: Error{`failed to start PEXReactor` (cause: Error looking up host (cosmos.cryptium.ch): lookup cosmos.cryptium.ch on 67.207.67.2:53: no such host)}
```
Apparently, tendermint shouldn't have crashed here, according to adrian.

**Comment by ebuchman** [comment]
We should confirm the case, but I think if we have an empty address book and no persistent peers and the seed fails, there's not much to do but shut down . We could print a more friendly message that explains this situation

**Comment by xla** [comment]
We should retry the seed instead of bailing.

**Comment by ValarDragon** [comment]
The current behavior here is:
```
// return err if user provided a bad seed address
	// or a host name that we cant resolve
	if err := r.checkSeeds(); err != nil {
		fmt.Println("3")
		return err
	}
```
And `err` is returned if there is a single seed you can't reach. This means you require that all seeds you have be online.
I think the correct behavior should be: 

if addrbook needs more peers, and the addressbook is empty, then we should enforce that at least one seed is online. Whenever we dial seeds, dial all programmed seeds regardless of whether or not they were online when node was started.

If addressbook is empty +  no online seeds, then we should bail out imo w/  a helpful error message. (They likely need to get one peer on their own through other means OR get new seeds. I think constantly retrying would be more confusing)

This requires a new method for determining if the address book is empty. Can I go ahead and implement this?

**Comment by xla** [comment]
@ValarDragon Sounds reasonable, let's go with your proposal.
