### ISSUE TITLE
New `tendermint-peers` binary

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1723]
To solve the problem of https://github.com/tendermint/tendermint/issues/1516, let's write a simple tool that queries each peer to get its self-reported validator key and print a nice table of the peers with their node id, ip address, validator key, moniker, how long we've been connected.

**Comment by zramsay** [comment]
see comment in https://github.com/tendermint/tendermint/issues/1908#issuecomment-402746760

**Comment by jackzampolin** [comment]
I think https://gitlab.com/polychain/tenderseed does a bit of this. Also this is out of scope for this particular repo. Closing.
