### ISSUE TITLE
Problem with  tendermint node --proxy_app=/var/run/abci.sock

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1724]
I donnot know what it failed to connect, although I donnot install abci-client.

```
@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint node --proxy_app=/var/run/abci.sock
I[06-09|01:41:26.889] Starting multiAppConn                        module=proxy impl=multiAppConn
I[06-09|01:41:26.889] Starting socketClient                        module=abci-client connection=query impl=socketClient
E[06-09|01:41:26.889] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:41:29.889] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:41:32.891] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:41:35.892] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
^FE[06-09|01:41:38.893] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
^C
ubuntu:~/goApps/src/github.com/tendermint/tendermint$ curl http://localhost:46657/broadcast_tx_commit?tx=\"abcd\"
curl: (7) Failed to connect to localhost port 46657: Connection refused
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ curl http://localhost:46657/status | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 46657: Connection refused
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/bin/json_pp line 45.
ubuntu:~/goApps/src/github.com/tendermint/tendermint$ curl http://localhost:46657/status | json_pp | grep latest_app_hash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to localhost port 46657: Connection refused
malformed JSON string, neither array, object, number, string or atom, at character offset 0 (before "(end of string)") at /usr/bin/json_pp line 45.
```

**Comment by ying2025** [comment]
Now I try again. It encounter another question as following.
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint node --proxy_app=/var/run/abci.sock
I[06-09|01:57:36.859] Starting multiAppConn                        module=proxy impl=multiAppConn
I[06-09|01:57:36.859] Starting socketClient                        module=abci-client connection=query impl=socketClient
E[06-09|01:57:36.859] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:57:39.860] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:57:42.861] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:57:45.862] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:57:48.862] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:57:51.863] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:57:54.864] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:57:57.865] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
E[06-09|01:58:00.866] abci.socketClient failed to connect to /var/run/abci.sock.  Retrying... module=abci-client connection=query
^C
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ tendermint node --proxy_app
ERROR: flag needs an argument: --proxy_app
zhr@ubuntu:~/goApps/src/github.com/tendermint/tendermint$ curl http://localhost:46657/broadcast_tx_commit?tx=\"abcd\"
curl: (7) Failed to connect to localhost port 46657: Connection refused

**Comment by melekes** [comment]
Please ensure that you are running application and it's listening for connections on `/var/run/abci.sock`.
