### ISSUE TITLE
Whether tendermint can install in window ?

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#1725]
Is there any detial documen ?

**Comment by melekes** [comment]
No, there is no document. You can try one of the Windows binaries https://github.com/tendermint/tendermint/releases/tag/v0.20.0 or compile it yourself. But we currently do not provide any guarantees as to whenever Tendermint will work on Windows or not. We are hoping that people interested in getting Tendermint to work on Windows will help us a bit. In fact, that is already happening (https://github.com/tendermint/tendermint/pull/1719). 

Please use our Riot chat https://riot.im/app/#/room/#tendermint:matrix.org to ask such questions next time. We also have a forum https://forum.cosmos.network/ for more deep discussions.

**Comment by ying2025** [comment]
Ok, thank you very much
