### ISSUE TITLE
Provide JSON Schema for RPC Endpoints

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1730]
**FEATURE REQUEST**

Using non-go languages to work with tendermint RPC Endpoitns requires to manually create the endpoint json representations for requests and responses.
This is usually done by using sample data generated manually or from your https://tendermint.github.io/slate/ page

This is error prone as one might not actually see each and every variation possible in those examples.
Suggestion: provide JSON Schema defining the requests and responses.
It's language agnostic and should enable 3rd parties to easily create their representations as they see fit, without worrying if they got every request/response right.

See http://json-schema.org/
https://blog.apisyouwonthate.com/openapi-and-json-schema-divergence-part-1-1daf6678d86e

Granted, there seems to be some debate on how and if this relates to OpenAPI and which one to choose. I've seen some swagger related stuff in OpenAPI but that's where my limited knowledge in this area ends.

Discuss! Happy to hear your thoughts :)

**Comment by xla** [comment]
Thanks for bringing this up, it's a re-occurrng conversation we have recently as more and more integrates on the shape of the data and the documentation of endpoints (which currently is done manually). This is a great issue for someone to get their feet wet and contribute for the first time, happy to about a PR.

**Comment by jackzampolin** [comment]
Any RPC refactor will address this issue. Closing.
