### ISSUE TITLE
The choice of peer to pull block from in fast sync mode might not be optimal

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#1734]
The relevant code is here:
https://github.com/tendermint/tendermint/blob/2e0466d1c851e51b1323a094a9ebd6c357700d0c/blockchain/pool.go#L305-L324

Note that the algorithm for selecting a peer from whom next block is pulled is chosen by iterating over peers and picking a first peer that satisfies the following condition: 
`peer.numPending < maxPendingRequestsPerPeer and peer.height >= height`, where height is the height of the block we are missing and want to pull in. 

This algorithm might lead to the request placement that is not optimal. In case iteration over map is deterministic and always returns the same sequence, it will send request to the first peer from the list (if peer's height is greater than height) until maxPendingRequestsPerPeer - 1 requests are sent, and no request will be sent to other peers. Then it will start sending requests to a second peer, etc.

There are several different approaches how the problem of request for block placement can be made that might lead to better fast sync time, for example, randomly picking peer, or ensuring that requests are sent uniformly to all peers that have blocks, or taking into account how fast we are getting blocks from our peers and giving preference to faster peers, or sending one request at a time to each peer initially and then based on response tine adapting, etc.

**Comment by jaekwon** [comment]
Thank you @milosevic.  Golang implements map a bit differently than other languages... it ensures that iteration is random (not necessarily cryptographically random, but random enough for cases like this)... given that, do you think we need to make more changes?

**Comment by milosevic** [comment]
Thanks for clarifying this @jaekwon. We don't need to make changes for now, this was the major concern I had regarding this. We might at some point try to make peer selection based on available network resources, how fast peers respond, etc, but we are fine short term.

**Comment by milosevic** [comment]
Closed for https://github.com/tendermint/tendermint/issues/2026.
