### ISSUE TITLE
Cann't update Validator's VotePower  by response the updateValidators to Tendermint Core

### ISSUE THREAD

**Issue by solderain** [tendermint/tendermint#1753]
## Refer to that : #1489  , but still cann't update validator's votePower ,  not sure what the root cause is 

Tendermint : 0.16 
Env : Just start one Tendermint Core node in my laptop 
genesis.json :
![image](https://user-images.githubusercontent.com/4144738/41455763-df94b1e2-70b0-11e8-9568-d6c04035cca8.png)

Try to update the Validator's votePower , make a updateValidator response to EndBlockRequest in ABCI:
![image](https://user-images.githubusercontent.com/4144738/41455546-15155f2a-70b0-11e8-9337-f1d37a674e95.png)

Add some log  to execution.go-->func  updateValidators :
![image](https://user-images.githubusercontent.com/4144738/41455923-75231d98-70b1-11e8-9b37-6c446ad2f0ae.png)

get the follow log :
![image](https://user-images.githubusercontent.com/4144738/41455946-9537c2b4-70b1-11e8-9723-ff9168587d97.png)

But found cann't hit exist validator Via address , the validator's votepower does  not be updated .

**Comment by xla** [comment]
@solderain Thanks for the report. Please make sure to verify this the bug against the latest release and avoid using screenshots for code and log sharing.

**Comment by solderain** [comment]
Ok, will paste code snippet or log hereafter

**Comment by solderain** [comment]
@xla  Upgrade Tendermint core to 0.22 ,  and upgrade  abci that application is dependent  to 0.12  ,  try to update spec validator's votepower , get the folllowing log in tendermint core :
`
[07-04|12:17:34.261] Updates to validators                        module=state updates="[{\"address\":\"\",\"pub_key\":\"LDJ3QzU0bFA5eXZpTXBzeVZNbkowbzJQWW1aQ0RFdjUveUtkbEI2OEs5NDg9\",\"power\":20}]"
E[07-04|12:17:34.262] Error on ApplyBlock. Did the application crash? Please restart tendermint module=consensus err="Commit failed for application: Error changing validator set: Invalid size for PubKeyEd25519. Got 45, expected 32"
  `

**Comment by solderain** [comment]
@xla  Make sure created the new genesis.json file by command "tendermint init " under new version  , the key  just copy from that file ，see below : 

{
  "genesis_time": "2018-07-03T12:25:42.62797702Z",
  "chain_id": "test-chain-OzkRg4",
  "consensus_params": {
    "block_size_params": {
      "max_bytes": "22020096",
      "max_txs": "10000",
      "max_gas": "-1"
    },
    "tx_size_params": {
      "max_bytes": "10240",
      "max_gas": "-1"
    },
    "block_gossip_params": {
      "block_part_size_bytes": "65536"
    },
    "evidence_params": {
      "max_age": "100000"
    }
  },
  "validators": [
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "2wC54lP9yviMpsyVMnJ0o2PYmZCDEv5/yKdlB68K948="
      },
      "power": "10",
      "name": ""
    }
  ],
  "app_hash": ""
}

**Comment by melekes** [comment]
> Whether encode pubkey by go-amino is required ?

it's not required anymore. 

```
message Validator {
  bytes address = 1;
  PubKey pub_key = 2 [(gogoproto.nullable)=false];
  int64 power = 3;
}

message PubKey {
  string type = 1;
  bytes  data = 2;
}
```

PubKey is now a type string ("ed25519") and raw pubkey bytes.

**Comment by melekes** [comment]
Give ^^ a try and, if any issues arise, tell us and we will reopen this issue. I'll close it in the meantime.
