### ISSUE TITLE
Debug output color scheme to dark - not visible in console

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1760]
**Bug**
Maybe it's more of a feature request to somehow be able to have a sane color for debug output, maybe even automagically adjust it according to shell settings?

**Tendermint version**
0.20.0-27bd1dea

**Environment**:
- OSX
- oh-my-zshell /zsh
- loglevel debug for * in config.toml

**What happened**:
Debug logoutput is not visible in cmd line, probably due to color tags.
Marking the output sections reveals them. Changing my background color to something really light works too.
Seems as if it matches my background color of 0x002933

**What you expected to happen**:
Is there a way to have a more sane approach to text coloring? 

Changed background color of terminal
<img width="715" alt="differentcolor" src="https://user-images.githubusercontent.com/7474512/41508035-2bd740cc-723e-11e8-82ae-edcabb31ddcb.png">

Debug visible after selecting
<img width="719" alt="marked" src="https://user-images.githubusercontent.com/7474512/41508036-2bf15444-723e-11e8-9030-427aa758b7a8.png">

Debug output not visibile
<img width="716" alt="inv" src="https://user-images.githubusercontent.com/7474512/41508037-2c0c0c76-723e-11e8-8d68-04aa7cd994f0.png">

**Comment by xla** [comment]
@ebuchman @melekes We should get rid of any color coding and move to structured logging as proposed in #1212. There is no reason we have this as surface to support.

@srmo Sorry for hijacking your issue, but I think this is a good indication that our logging is not ideal. It should not impose such problems on users. So rather we should not have any color coding and leave that up to auxiliary tools.

**Comment by melekes** [comment]
> There is no reason we have this as surface to support.

Except that it helps to spot errors more easily.

> It should not impose such problems on users

we can change the color of "debug" messages to default one.

**Comment by marbar3778** [comment]
Lets use the default coloring of the logger, there is no need to spend time adding more features if we already have removing the custom logger in our sights.

**Comment by alexanderbez** [comment]
zerolog already adds color FYI (for non-JSON)

**Comment by marbar3778** [comment]
we are migrating to zerolog, we can close this
