### ISSUE TITLE
[mempool] cache_size=0 gives Panic in WSJSONRPC

### ISSUE THREAD

**Issue by yuomii** [tendermint/tendermint#1761]
BUG REPORT:

**Tendermint version**:
0.20.0-27bd1dea

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore App

**Environment**:
- Windows
- Binary release package
- 4 Nodes on localhost - 3 validators 1 non validator

**What happened**:
If you try to commit a transaction by BROADCAST_TX_SYNC over Websocket and cache_size is set to 0 in the config.toml you get Panic in WSJSONRPC.
In the documentation this is described as a valid option:
[https://tendermint.readthedocs.io/projects/tools/en/master/app-development.html?#replay-protection](url)
**What you expected to happen**:
Block should be build on new tx

**Logs (you can paste a part showing an error or attach the whole file)**:
`E[06-18|07:20:14.200] Panic in WSJSONRPC handler module=rpc-server protocol=websocket remote=127.0.0.1:55799
err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 1560 [running]:\nruntime/debug.Stack(0xbb8220, 0xbaf920, 0x1298550)\n\t
/home/jslave/goroot/src/runtime/debug/stack.go:24 +0xae\ngithub.com/tendermint/tendermint/rpc/lib/server.(*wsConnection).readRoutine.func1(0xc044cbbea0)\n
\t/home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:538 +0x9a\npanic(0xbaf920, 0x1298550)\n
\t/home/jslave/goroot/src/runtime/panic.go:502 +0x237\ngithub.com/tendermint/tendermint/mempool.(*txCache).Push(0xc0420f6f40, 0xc045d52800, 0x2710, 0x2712, 0xc044bdd800)\n
\t/home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/mempool/mempool.go:487
+0xee\ngithub.com/tendermint/tendermint/mempool.(*Mempool).CheckTx(0xc042136780, 0xc045d52800, 0x2710, 0x2712, 0xc045d70c20, 0x0, 0x0)\n
\t/home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/mempool/mempool.go:215
+0xc9\ngithub.com/tendermint/tendermint/rpc/core.BroadcastTxSync(0xc045d52800, 0x2710, 0x2712, 0x0, 0x0, 0x0)\n
\t/home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/rpc/core/mempool.go:93 +
0xcc\nreflect.Value.call(0xb8e460, 0xdfd5b8, 0x13, 0xc9f35a, 0x4, 0xc044cb0f20, 0x1, 0x1, 0x1, 0x0, ...)\n
\t/home/jslave/goroot/src/reflect/value.go:447 +0x970\nreflect.Value.Call(0xb8e460, 0xdfd5b8, 0x13, 0xc044cb0f20, 0x1, 0x1, 0x1, 0x1, 0x0)\n
\t/home/jslave/goroot/src/reflect/value.go:308 +0xab\ngithub.com/tendermint/tendermint/rpc/lib/server.(*wsConnection).readRoutine(0xc044cbbea0)\n
\t/home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:607
+0x544\ncreated by github.com/tendermint/tendermint/rpc/lib/server.(*wsConnection).readRoutine.func1\n
\t/home/jslave/workspace/02.Fetch.Binary@3/go/src/github.com/tendermint/tendermint/rpc/lib/server/handlers.go:540 +0x2ae\n"`

**Anything else do we need to know**:
After the panic i killed all nodes. I changed the cache_size in every config.toml to 100k again. I rebooted the nodes aftwerwards. Incoming tx were still not being proposed or evaluated. I had to call unsafe_reset_all on every node in order to be able to commit new tx's again.

**Comment by ebuchman** [comment]
Whoops, thanks for reporting. 

Should be fixed in v0.20.1-rc0. Can you confirm and close this if so ? 

Thanks

**Comment by yuomii** [comment]
Confirmed
