### ISSUE TITLE
`sync_info.syncing` should be renamed `sync_info.catchingUp`

### ISSUE THREAD

**Issue by nylira** [tendermint/tendermint#1767]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version**: 0.20.0

**ABCI app**: gaia-6002

**Environment**: N/A

**What happened**:

Visit http://nylira.net/status, check out `sync_info.syncing`. I think that `syncing: true` should be renamed `catchingUp: true`.

`syncing` is too ambiguous of a term. People are confused by this. It can mean "your node is catching up to the latest block" or "your node is currently in sync with the peer nodes".

`catchingUp` on the other hand, is clear. People will not mistake `catchingUp = true` to mean the  node is on the latest block.

**Comment by xla** [comment]
@nylira This is addressed in #1797 but needs some upstream (cosmos-sdk) changes as well.
