### ISSUE TITLE
Fire NewBlock event after saving in case app process crashes

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#177]
For when the app crashes while committing a block, make sure NewBlock event doesn't get fired twice while we wait for the app to come back.

We will have to do more work to be able to exec txs from the last place that the app failed, to ensure that we don't end up with duplicate events.  Shouldn't be too hard, we just need to be able to reset the app state to the latest hash, and then replay the same txs while ignoring events.

**Comment by ebuchman** [comment]
If we use a cache, and don't flush it until the block completes, then we shouldnt have to worry about duplicate events from txs

**Comment by adrianbrink** [comment]
@ebuchman Has this been dealt with in the referenced issues?

**Comment by ebuchman** [comment]
This is something we should review. I think there's a case where the event fires twice.

**Comment by jackzampolin** [comment]
Is this still an issue? Going to preemptively close. Please reopen if issue persists.
