### ISSUE TITLE
Introduce queryCache to ease memory usage

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1770]
AST for a single query can take ~ 700kB (https://github.com/tendermint/tendermint/blob/master/libs/pubsub/query/query.peg.go#L121). That's a lot. We either need to make it smaller by switching to another library (PEG parser) or introduce `queryCache` - LRU cache of the last N queries. Most probably clients will use the same queries to subscribe, so not building the same AST probably makes sense.

LRU - can we use a library like https://github.com/hashicorp/golang-lru? no? Do we have one already? Simple map with a lock then?

**Comment by jackzampolin** [comment]
cc @ultraeric

**Comment by marbar3778** [comment]
Some DBs have options integrated to help with this. 

With goleveldb we could make use of https://github.com/syndtr/goleveldb/blob/master/leveldb/opt/options.go#L300-L313 and add the provided bloomfilter.

**Comment by alexanderbez** [comment]
If we do end up using an LRU cache, or any similar variant, use https://github.com/hashicorp/golang-lru as it has many types and options.

**Comment by JayT106** [comment]
Is any conclusion for this issue? go switching lib or LRU cache, if we do use an LRU cache, is `N` hardcoded or configurable?
And this cache is for both TxIndexer and BlockIndexer, right? So is the best place to add the LRU instance in the `Environment` struct?

**Comment by marbar3778** [comment]
@tychoish, I would like to hear your take on this one. You worked in the DB world for a while.

**Comment by creachadair** [comment]
Since https://github.com/tendermint/tendermint/pull/7319, query processing is no longer a substantial contributor to memory or CPU profiles.
