### ISSUE TITLE
Initalization with weak subjectivity

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1771]
Tendermint needs an option to be initialized using a trusted socially verified validator set hash. This is part of the security model for proof of stake blockchains. Without, they are subject to long-range-nothing-at-stake-attacks. UX is roughly the same as for light clients: https://github.com/cosmos/cosmos-sdk/issues/1275#issuecomment-398574947

**Comment by xla** [comment]
@ebuchman Should this be adressed before launch?

**Comment by ebuchman** [comment]
Yep

**Comment by srmo** [comment]
I like this idea!
Can we think about something like having the abci app respond with the excepted hash of validators, like it responds with appHash?
Any early ideas how this could work with rotating/moving validator sets?

**Comment by ebuchman** [comment]
Some thoughts on this.

First, this will only become a problem once +1/3 of the validators from some point in time have finished unbonding. So this is at least 3 weeks, if not much longer, after launch. 

Second, it's not clear how exactly we want to approach this. A short term solution is clear communication and burdening the user with messaging like `DO NOT USE THIS NODE UNTIL YOU HAVE VERIFIED THE VALIDATOR HASH. SEE https://something-about-this.com FOR DETAILS`. Then users should be aware that they can't trust their own full nodes until they have verified the validator hash socially.

A longer term solution might look like some kind of standard for websites to report the validator set hash and height for a chain at some frequency. Then we could add a config option to tendermint that includes a list of trusted websites input by the user. Tendermint can then query these sites according to the standard and check that they all agree with each other and with what the node itself is seeing. If not, it will log an error and exit, and the user will have to take some manual action to rectify.

**Comment by ebuchman** [comment]
Of course we can also include a manual option where folks can input the expected validator hash and height at startup time, so that no external co-ordination or querying is required.

**Comment by jackzampolin** [comment]
Needs spec too.

**Comment by marbar3778** [comment]
closing this issue with #3989 being merged.

**Comment by melekes** [comment]
Multiple comments in https://github.com/tendermint/tendermint/pull/3989 needs to be addressed before we can close this I believe.
