### ISSUE TITLE
When will the release of tendermint 0.20 be released?

### ISSUE THREAD

**Issue by yangdongju** [tendermint/tendermint#1773]
When will the release of tendermint 0.20 be released?

**Comment by xla** [comment]
@yangdongju Thanks for reaching out, [v0.20.0](https://github.com/tendermint/tendermint/releases/tag/v0.20.0) has been release almost two weeks ago. Please do not use issues for such concerns and instead join and ask in our [riot chat](https://riot.im/app/#/room/#tendermint:matrix.org)
