### ISSUE TITLE
Plasma and "Internal" Transactions in ABCI Apps

### ISSUE THREAD

**Issue by iantanwx** [tendermint/tendermint#1776]
**FEATURE REQUEST**

**Background**

This issue relates to the implementation of an ABCI app that is able to function as a Plasma child chain. My company is presently developing such an ABCI app, and I am opening this issue as a means to seek the opinions of the TM team on the matter, and, if necessary, contributing a PR(s) to help expedite its resolution.

As you know, in view of the existing Plasma-related specifications (see https://ethresear.ch/t/minimal-viable-plasma/426 and https://ethresear.ch/t/plasma-cash-plasma-with-much-less-per-user-data-checking/1298), a UTXO bookkeeping model is necessary. The complexities of a Plasma-compliant UTXO model are, I believe, well-known to the TM team, as some of you are in the Plasma implementers' call, which we have been following.

However, implementing a Plasma chain is somewhat awkward with the current ABCI interface, which I explain below.

**Problem**

In the context of Tendermint, the current ABCI interface leads to some awkwardness for an app implementing Plasma when so-called coinbase (transactions that are not the result of user input) or otherwise "special" transactions (such as `deposit` and `exit` transactions) are involved.

The simplest example to my mind would be validator incentives.  When `DeliverTx` or `EndBlock` is called, it is trivial for the app to respond by simply pushing the necessary UTXOs onto the existing UTXO set. However, these UTXOs are not explicitly included in the blockchain itself (i.e., they are part of app state, and have not passed through the full-blown consensus mechanism).

However, as a result, the UTXO set will contain UTXOs that were not explicitly part of an in-consensus transaction. While it is possible to maintain consistency between the blockchain and the UTXO set, I enumerate my solutions and the reasons why they are awkward below.

**Solution 1: Auxiliary app state-based plasma chain**

This was the first (naive) solution that I implemented. In this solution, all UTXOs that are added or spent from the UTXO set are specifically added to a `PlasmaStore`, that maintains an auxiliary chain for the sole purpose of broadcasting its blocks to the root chain. This includes the so-called "coinbase" UTXOs that are not part of the TM blockchain. 

However, I have serious doubts about this approach, since it is likely to lead to complexities keeping the auxiliary chain contained in `PlasmaStore` in sync with the canonical chain maintained by TM core itself, especially in the event that the business logic for creating such transactions is potentially non-deterministic.

While it is certainly possible for the auxiliary chain's blocks/transactions to keep references to the Tendermint blocks that lead to their creation (either by way of block hash or merkle root), this approach seems cumbersome, especially if 3rd party validators wish to "watch" the child chain and ensure that Plasma blocks broadcasted to the root chain smart contract are in fact provably consistent with the in-consensus blocks and transactions on the child chain.

**Solution 2: Broadcast "internal" transactions to TM core**

This was the other solution, inspired by the `ethermint` approach to relaying Ethereum transactions to TM core.

In this solution, whenever an "internal" UTXO needs to be created, the proposer of the current block is responsible for broadcasting a transaction or transactions to TM core as needed in order to ensure that the tendermint chain and plasma chain are completely consistent. Logic in `CheckTx` is used to ensure that the transaction is valid (i.e., signed by the proposer, is the semantically correct, etc.) Note that this also involves informing the ABCI app of the block proposer, which I just temporarily hacked in as a means of conducting this experiment. I understand that this is a feature that is coming soon to TM core.

This approach has the welcome effect of ensuring that all of the coinbase transactions are passed through the full consensus process, and are not instead added as part of application state. As a result it is much easier to broadcast these transactions directly to the root chain smart contract and/or maintain a "compressed" auxiliary chain comprised of Plasma-friendly blocks that 100% reflect the TM core blockchain, that can then be broadcast to the root chain.

This does however, seem to be a little bit hacky to me, and perhaps not very idiomatic, although I do not think this has the same potential to break consensus guarantees in the same way as Solution 1. Further, I think it preferable, as is the case in Bitcoin, to ensure that coinbase transactions are at index 0 of the block, for consistency and verification purposes. This solution does not guarantee any ordering for the coinbase transactions, since they may reach the mempool after other user-generated transactions.

**Proposed Solution**

In order to keep things idiomatic, I propose adding a `ProposeTx` method to the ABCI interface that can be called _before_ `mempool.Reap` at this line: https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L906

The proposed transactions received from `ProposeTx` can then be pushed onto the top of the transactions received from `mempool.Reap`, and therefore passed through the _full_ consensus mechanism.

I understand this proposal involves significant engineering complexity. I am therefore happy to open a PR with a working implementation of the above solution, should the TM team feel it is a viable and idiomatic approach to the problem. I am also very much open to any criticism or suggestions if there is indeed a better and simpler way to achieve what we are trying to build that I may have myopically missed. Thanks for your time, and for building Tendermint!

**Comment by iantanwx** [comment]
Thanks for taking the time to read the proposal,  @ebuchman. I'll follow up in the first half of the week with the ADR pull request. I presume the ADR should be in a separate PR than the ADR one?

**Comment by melekes** [comment]
There are some comments in https://github.com/tendermint/tendermint/pull/1813#pullrequestreview-137356196 which need to be addressed.

**Comment by iantanwx** [comment]
Hey @melekes, sorry about the delay - I just joined a new company, so I've been super busy at work. I'll address the comments in the next week.

**Comment by jackzampolin** [comment]
Closing this as dead ☠️
