### ISSUE TITLE
Importing github.com/tendermint/tendermint

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#1777]
I was trying to import a couple of `tendermint` packages into a golang project:

```
"github.com/tendermint/tendermint/rpc/client"
"github.com/tendermint/tendermint/rpc/core/types"
```

I got the following error after running `dep init && go run main.go`: 

```
# github.com/jackzampolin/cosmos-scorecard/vendor/google.golang.org/genproto/googleapis/rpc/status
vendor/google.golang.org/genproto/googleapis/rpc/status/status.pb.go:111:28: undefined: proto.InternalMessageInfo
```

I tracked this down to `tendermint` using a specific revison of the `google.golang.org/genproto` library. I was able to avoid the issue by adding an override to my `Gopkg.toml` but this is not good for most users.  

```
[[override]]
  name = "google.golang.org/genproto"
  revision = "7fd901a49ba6a7f87732eb344f6e3c5b19d1b200"
```

**Comment by melekes** [comment]
I am curious what's the solution for this looks like? try to remove `genproto` import from `rpc/client. 

_Note it's coming from `rpc/grpc`. `rpc/test/helpers` defines a couple of helpers (one of them for grpc). the `rpctest` package is used in `rpc/client`._

**Comment by jackzampolin** [comment]
It looks like from the error that the `proto.InternalMessageInfo` type is undefined in master. Maybe they changed the naming?

**Comment by ebuchman** [comment]
You can remove this error and the need to version the genproto by updating protobuf to v1.1.0, but then our grpc test fails :)

Would be amazing if someone could fix it. See note in https://github.com/tendermint/tendermint/pull/1942/files#diff-836546cc53507f6b2d581088903b1785R80

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/1944
