### ISSUE TITLE
pubsub/query.(*QueryParser).Init allocates lot of memory when a plenty of failure(checkTx) happened

### ISSUE THREAD

**Issue by kenhousdyc** [tendermint/tendermint#1778]
Hello,

I met a problem when I studied and tried to wrote a new app with tendermint core, when a plenty of incorrect tx be sent, the tendermint would run out of memory.  Then I modified kvstore to make CheckTx response a failure always, and it's reproduced.  Followings are my test env, and what I changed for kvstore.

This is CheckTx() what I changed to:
func (app *KVStoreApplication) CheckTx(tx []byte) types.ResponseCheckTx {
	return types.ResponseCheckTx{Code: code.CodeTypeBadNonce}
}

The version of Tendermint and ABCI are:
Tendermint: v0.20.0
ABCI: v0.11.0
OS: CentOS Linux 7 (Core)
go version: go1.10.2 linux/amd64

The steps what I did:
1. modify kvstore CheckTx() to send CodeTypeBadNonce always
2. build abci and tendermint
3. run tendmint and abci kvstore
4. run a test function keeping to send tx to abci
5. keep looking at system memory using "top" command, then you would see the memory of tendermint allocated keep growing

Followings are the heap message from pprof, anyone give me a favor?   Thanks.

howing nodes accounting for 20.01GB, 99.62% of 20.08GB total
Dropped 70 nodes (cum <= 0.10GB)
      flat  flat%   sum%        cum   cum%
   19.99GB 99.55% 99.55%    20.01GB 99.62%  github.com/tendermint/tendermint/libs/pubsub/query.(*QueryParser).Init
    0.01GB 0.071% 99.62%    20.02GB 99.71%  github.com/tendermint/tendermint/libs/pubsub/query.New
         0     0% 99.62%    20.02GB 99.71%  github.com/tendermint/tendermint/libs/pubsub/query.MustParse
         0     0% 99.62%    20.04GB 99.77%  github.com/tendermint/tendermint/rpc/core.BroadcastTxCommit
         0     0% 99.62%    20.04GB 99.79%  github.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1
         0     0% 99.62%    20.04GB 99.79%  github.com/tendermint/tendermint/rpc/lib/server.makeHTTPHandler.func2
         0     0% 99.62%    20.03GB 99.75%  github.com/tendermint/tendermint/types.EventQueryTxFor
         0     0% 99.62%    20.04GB 99.79%  net/http.(*ServeMux).ServeHTTP
         0     0% 99.62%    20.04GB 99.79%  net/http.(*conn).serve
         0     0% 99.62%    20.04GB 99.79%  net/http.HandlerFunc.ServeHTTP
         0     0% 99.62%    20.04GB 99.79%  net/http.serverHandler.ServeHTTP
         0     0% 99.62%    20.04GB 99.77%  reflect.Value.Call
         0     0% 99.62%    20.04GB 99.77%  reflect.Value.call
         0     0% 99.62%    20.04GB 99.77%  runtime.call64
(pprof) exit

**Comment by melekes** [comment]
Hi! Do you think https://github.com/tendermint/tendermint/issues/1755 may be the same issue? If yes, then could you try the latest develop branch and see if the issue goes away?

**Comment by kenhousdyc** [comment]
Hi, Melekes,

Yes, that patch works.  Thanks.
