### ISSUE TITLE
Why are two blocks created? (First, Transaction occurred) 

### ISSUE THREAD

**Issue by qkrwnsgh1288** [tendermint/tendermint#1783]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** : 0.20.0-c84be3b8

**ABCI app** (name for built-in, URL for self-written if it's publicly available): kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release): ProductName:	
Mac OS X
ProductVersion:	10.13.5
BuildVersion:	17F77
- **Install tools**:
git
- **Others**:

**What happened**:
I set "create_empty_blocks = false" in the "config.toml" file after "tendermint init". All except this is the default state.
In this state, I executed the command "tendermint node --proxy_app kvstore", so two blocks were created first.

1. The first block is thought of as a genesis block, and I do not know why the second block is created. (I think this is to confirm the genesis block... Is that right?)

2. Then, two blocks were created to generate the transaction. I have a transaction in one block, and I do not know why another block after it happens.

> I[06-21|02:23:19.189] Block{
>   Header{
>     ChainID:        test-chain-9HUwPf
>     Height:         3
>     Time:           2018-06-21 02:23:19.183178847 +0000 UTC
>     NumTxs:         1
>     TotalTxs:       1
>     LastBlockID:    DD22E696ABC02584BB6CF5BEB16883ED76445FE2:1:F2658D478C12
>     LastCommit:     4069967A677C67933CB10C1D6E736D4E0EFFF41F
>     Data:           1EB1347A48B490C41BF131F660602F7B8E32D366
>     Validators:     C34CF7C08DAEE6271E7FEDF4B3514D11B80835A9
>     App:            0000000000000000
>     Consensus:       F66EF1DF8BA6DAC7A1ECCE40CC84E54A1CEBC6A5
>     Results:
>     Evidence:
>   }#0B4B6E94ADA801B1F45523BD5DD0EF2F05095CD9
>   Data{
>     Tx:Tx{616263}
>   }#1EB1347A48B490C41BF131F660602F7B8E32D366
>   Data{
> 
>   }#
>   Commit{
>     BlockID:    DD22E696ABC02584BB6CF5BEB16883ED76445FE2:1:F2658D478C12
>     Precommits: Vote{0:977FD753C2E3 2/00/2(Precommit) DD22E696ABC0 /EC1FA373554E.../ @ 2018-06-21T02:22:24.957Z}
>   }#4069967A677C67933CB10C1D6E736D4E0EFFF41F
> }#0B4B6E94ADA801B1F45523BD5DD0EF2F05095CD9 module=consensus

Shortly after

> I[06-21|02:23:20.201] Block{
>   Header{
>     ChainID:        test-chain-9HUwPf
>     Height:         4
>     Time:           2018-06-21 02:23:20.190440214 +0000 UTC
>     NumTxs:         0
>     TotalTxs:       1
>     LastBlockID:    0B4B6E94ADA801B1F45523BD5DD0EF2F05095CD9:1:52DB4CC4AD7B
>     LastCommit:     BD4E7B5671AD92BCDBDF38FEB8B606FB398F5EB9
>     Data:
>     Validators:     C34CF7C08DAEE6271E7FEDF4B3514D11B80835A9
>     App:            0200000000000000
>     Consensus:       F66EF1DF8BA6DAC7A1ECCE40CC84E54A1CEBC6A5
>     Results:        C479B3B281039B6A3A6C9F7685A2C3948FA4DCA3
>     Evidence:
>   }#601134002FC7DBAA5B06C19A47934FBA4ACF67F9
>   Data{
> 
>   }#
>   Data{
> 
>   }#
>   Commit{
>     BlockID:    0B4B6E94ADA801B1F45523BD5DD0EF2F05095CD9:1:52DB4CC4AD7B
>     Precommits: Vote{0:977FD753C2E3 3/00/2(Precommit) 0B4B6E94ADA8 /F53697EBAC63.../ @ 2018-06-21T02:23:19.187Z}
>   }#BD4E7B5671AD92BCDBDF38FEB8B606FB398F5EB9
> }#601134002FC7DBAA5B06C19A47934FBA4ACF67F9 module=consensus

please answer about my question.

**Comment by ebuchman** [comment]
From https://github.com/tendermint/tendermint/blob/develop/docs/using-tendermint.md#no-empty-blocks:

> In the former case, blocks will be created when there are new transactions or when the AppHash changes.

Txs in block H cause AppHash to change in H+1

**Comment by qkrwnsgh1288** [comment]
My question is why another block is created after the block being created when the transaction occurs. (genesis block also)
Is this a bug or is it intended?
If this is the intent, why did it work like this?
