### ISSUE TITLE
Two blocks are created in one transaction (or when genesis block created).

### ISSUE THREAD

**Issue by qkrwnsgh1288** [tendermint/tendermint#1788]
Why another block is created after the block being created when the transaction occurs. (genesis block also)
Is this a bug or is it intended?
If this is the intent, why did it work like this?

I've asked before, but I think I received an answer regardless of my question.
so ask again.

**Comment by melekes** [comment]
This is something we call a proof block

https://github.com/tendermint/tendermint/blob/3e1baf68f83dc1da2afa1cb8b7458e39369a563c/consensus/state.go#L765-L774

**Comment by melekes** [comment]
Next time please ask you question on https://stackoverflow.com/questions/tagged/tendermint or Riot chat (https://riot.im/app/#/room/#tendermint:matrix.org) since it's not really an issue.

**Comment by ebuchman** [comment]
Txs included in block H cause the AppHash to change in H+1. If you want proofs with the new AppHash, you need to sign the new AppHash, but signatures for block H+1 are only included in H+2. Hope that makes sense.

**Comment by qkrwnsgh1288** [comment]
Thank you for your deliberate comment ~!
