### ISSUE TITLE
docs: port 46657 is appearing in read the docs, but should be 26657

### ISSUE THREAD

**Issue by tpmccallum** [tendermint/tendermint#1789]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): Linux Ubuntu 18.04
- **Install tools**: Used the documentation from readthedocs, each of my steps are written in this gist  https://gist.github.com/tpmccallum/19659848f96d832b31fa73e9b493d378

**What happened**: When I ran the command curl localhost:46657/broadcast_tx_commit?tx=0x00 I got the following error

curl: (7) Failed to connect to localhost port 46657: Connection refused

**What you expected to happen**: I expected a json response as per the documentation

**How to reproduce it** (as minimally and precisely as possible): Follow these instructions on gist
https://gist.github.com/tpmccallum/19659848f96d832b31fa73e9b493d378

**Logs (you can paste a part showing an error or attach the whole file)**:

**Config (you can paste only the changes you've made)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:

I checked to see which ports are listening on my Tendermint installation using netstat -an | grep "LISTEN "

It seems that port 26657 was listening (not port 46657). The documentation at http://tendermint.readthedocs.io/projects/tools/en/master/getting-started.html says to use port 46657. 

One thing is for sure though, when I use the following command (using port 26657) I actually get the json response which I was expecting. 

```

{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "check_tx": {
      "fee": {}
    },
    "deliver_tx": {
      "fee": {}
    },
    "hash": "213492C0C6FC5D61497CF17249DD31CD9964B8A3",
    "height": 136
  }
}

```
A search in this GitHub shows results for both port 46657 and port 26657. Not sure what the best path to take is. Does Tendermint use both of these or are we in a transition from 46657 to 26657 (and the docs have not caught up)?

Many thanks
Tim

**Comment by ValarDragon** [comment]
We're currently in a transition from 46657 to 26657. Master was just upgraded to use 26657, but the docs should have been updated. This is strange. I'm not sure where the read the docs code is located, but this needs to be changed there. Thanks for reporting this.

**Comment by xla** [comment]
Maybe @zramsay can help with the stale docs.

**Comment by zramsay** [comment]
the docs have been re-built and are up to date (except for tm-bench/monitor), which is fixed in the PR linked above

**Comment by tpmccallum** [comment]
Thank you!
