### ISSUE TITLE
types.Signer missing on testnet setup

### ISSUE THREAD

**Issue by mark-lester** [tendermint/tendermint#179]
Can't follow the testnet setup instructions, I get 
mcl@mcl-LIFEBOOK-AH512:~/git/tender$ tendermint node
Error reading PrivValidator from /home/mcl/.tendermint/priv_validator.json: Cannot read unregistered interface type types.Signer
have we lost that file somehow ?.

Also tiny typo on http://tendermint.com/posts/tendermint-socket-protocol/
start of last paragraph before A Note on Determinism, missing I.

**Comment by ebuchman** [comment]
Hi Mark,

This should be fixed on latest master. Please pull and try again. If not, re-open the issue. Thanks!

**Comment by jaekwon** [comment]
Thanks Mark!  Fixing the typo too.

**Comment by mark-lester** [comment]
that worked fyi
 

    On Thursday, 14 January 2016, 17:34, Jae Kwon <notifications@github.com> wrote:
 

 Thanks Mark! Fixing the typo too.—
