### ISSUE TITLE
Add more metrics

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1791]
Let's accumulate metrics we want to add here.

- rpc.ws_connections from https://github.com/tendermint/tendermint/pull/1781
- block time should probably be a gauge, not histogram (reason: with histogram, you won't see those spikes https://github.com/tendermint/tendermint/issues/1835#issuecomment-402054099)

**Comment by ebuchman** [comment]
Tagging https://github.com/cosmos/cosmos-sdk/issues/2169

**Comment by jackzampolin** [comment]
Closing this issue as non actionable.

**Comment by melekes** [comment]
We should at least add/update metrics from the issue's description.

**Comment by marbar3778** [comment]
followup to https://github.com/tendermint/tendermint/pull/4263, it was requested to expose the metrics that were added in that pr for the entire validator set.
