### ISSUE TITLE
Crypto/ed25519: Use assembly instructions in signing

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1792]
*Feature Request*
If we ever have any of our testing suites bottlenecked by signature creation time, we can use the Amd64 Cmov instruction to save ~11% of signing time* on the relevant architecture. We would just be cherrypicking this commit: https://github.com/agl/ed25519/pull/11/. @donovanhide has already written it in such a way that it compiles using assembly on amd64, and otherwise falls back to default to pure go implementation. The downside of merging this is that we now have assembly in our ed25519 implementation, which is harder to reason about. 

*11% accounts for 1% of the benchmarks in that pr being saved by unrolling FeZero, FeOne, which I've done in a seperate PR.

**Comment by marbar3778** [comment]
https://twitter.com/FiloSottile/status/1336410618535014404?s=20

seems if we fork https://github.com/golang/crypto/blob/master/ed25519/ed25519.go and migrate it to use https://pkg.go.dev/filippo.io/edwards25519 we can get a greater increase in performance than 10%.
