### ISSUE TITLE
Consolidate metadata for merged repos

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#1793]
After the merge of projects like abci, crypto and tmlibs we should consolidate licenses, build infrastructure, tests, docs and commands.

#1782
#1790 
#1842

**Comment by zramsay** [comment]
`make install_abci` ?

**Comment by ValarDragon** [comment]
Which changelog should be updated? The package changelog, or tendermints?

**Comment by zramsay** [comment]
i think the changelog in each the abci/libs/crypto should be consolidated into the one Tendermint changelog. I'll tackle that eventually as part of this issue, which will be completed in many little PRs, starting with #1886

**Comment by zramsay** [comment]
files to consolidate:

```
abci/
    Dockerfile.develop
    Makefile
    README.md
    scripts/
    tests/
    version/
crypto/
    CHANGELOG.md
    Makefile
    README.md
libs/
    circle.yml
    Makefile
    README.md
    CHANGELOG.md
    test/
    test.sh
    version/
    version.go
```

**Comment by zramsay** [comment]
this is basically done. @ebuchman suggests we leave the README and CHANGELOG with some notes and I agree. Last thing left is to harmonize the tests.
