### ISSUE TITLE
mempool: wasteful tx broadcasting

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1798]
Currently, every valid tx received by a node is sent to each of its peers, regardless of whether that peer has it or not, even if that peer was the original sender of the tx.

This results in a lot of wasted bandwidth and spamming the log message:

``` 
I[06-22|22:07:31.670] Could not check tx                           module=mempool tx=25CF190AB603E698BFFD8FD72F35E28FBE13057E err="Tx already exists in cache"   
```

At the least, we should be able to record which peer originally sent us a tx and not send it back to them.

We should also consider adding a new message type so peers can indicate which txs they already have, though this is more tricky.

**Comment by ValarDragon** [comment]
Would it be hard to prevent broadcasting to the peer who sent it to you? (I have no idea how this part of the codebase is structured) If not, could that actually be moved to pre-launch. I'm playing around with tm-bench on a cluster, and I think this contributes a non-neglible amount to the delay. (Albeit that is with only 4 peers, as the number of peers scales up, not sending it to the peer who you received the tx from becomes less impactful)

**Comment by srmo** [comment]
Why does this become less impactful with growing number of peers? I would say it's even more important. In a full meshed network, given N nodes, a node j might receive a message from N-1 nodes and therefor re-broadcast it to N-1 nodes. With the fix, you will reduce the amount of messages by N-1 so it scales with N.

**Comment by milosevic** [comment]
I was thinking also about this after reviewing Mempool. Ack based mechanism is more tricky as transactions are []byte for Tendermint. This would probably require adding some sort of generic header for each transaction so we have more concise way to say what transactions we already have. We can then append to each transaction a pair validatorId:sequenceNum, so we can ack multiple txs with a single counter. Furthermore, the most efficient gossip protocols are mix of push and pull based. For example, if we add hop counter, we can push the first few hops and then rely on pulling for further hops.    
  
Part of the problem might also be the fact that we broadcast transactions in the order received. This might be related with FIFO guarantees we are enforcing with Mempool (these guarantees need to be clarified, documented and justified clearly). So if a process send txA to its peers at time t, they will receive it most probably at similar time, so there is a high chance that they will be pushing it to it's peers at the more or less similar time further. As currently we rely only on block commit to remove txs from the Mempool, sequentially gossiping txs potentially cause lot of duplication and wasted bandwidth. I was wondering if adding a bit of randomness in the choice of txs being gossiped might help a bit. This is potential short term improvement in case we don't want to add more complex algorithm for tx gossiping.

**Comment by jlandrews** [comment]
So I started looking into this, and I'm currently thinking through a variant of the "Plumtree" algorithm (http://asc.di.fct.unl.pt/~jleitao/pdf/srds07-leitao.pdf) that I think could work well here.

The idea is to have sender specific minimum spanning trees constructed for pushing messages down exactly once, and have hashes of messages sent down non tree edges. Any nodes which received a hash but didn't get the actual message would then request the message from the node who sent them the hash first, and that edge would be added to the MST for that sender.

The part I'm still working through is where to store the tree information / make routing decisions. Option one is to have the tree stored by the original sender, which would require info about pulls to get from the leaves back to the source for tree repair. It would also mean that broadcast messages would need to include information about the tree itself, so receiving nodes could correctly relay the message. This could be done in a way similar to that of onion routing, where each layer of the path is stripped off at each node.

The other option is to have nodes add edges locally as they are pulled from. This would require nodes to store more data though, we would likely use a map from sender to a partition of the neighbor set into tree and non tree edges. The second option seems like it could open up new DDOS prevention options as well though, as it could allow nodes to whitelist which senders can push messages to them, and through which edges, while any other message being pushed would be cause to disconnect the edge.

**Comment by jlandrews** [comment]
Thinking about sentry nodes and just realized that we should definitely try to do the simple fix of not sending things back to the peer that sent them to you. For sentry <-> validator connections this will reduce traffic by half, since currently every message is being echoed back.

**Comment by melekes** [comment]
> We can for example add to TxMessage a pair validatorId:sequenceNum, where validatorId is the node id and a correct process initialises TxMessage with its id and it's local sequence number if he received tx outside the gossip. Then we can ack multiple txs with a single counter. Note that tolerating Byzantine faults would require additional thinking in this case.

I've had exactly the same idea today, lol https://github.com/tendermint/tendermint/pull/2778#discussion_r251314108

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/2778 to develop.

**Comment by melekes** [comment]
I'm leaving this open to discuss&develop other possible improvements including

> We should also consider adding a new message type so peers can indicate which txs they already have, though this is more tricky.

and pull-push model

**Comment by ebuchman** [comment]
Let's close it for other issues like #2484 and #2147 or a new one more specifically for the pull/push stuff.

**Comment by melekes** [comment]
Okay 😄
