### ISSUE TITLE
server config instructions

### ISSUE THREAD

**Issue by mark-lester** [tendermint/tendermint#180]
I dont have a DigitalOcean account, I'm on AWS. I dont mint getting one just for the fun of it but what I really want to do is work out how the config game works in mintnet, which as I dont currently speak go is tough.
I appreciate that documenting a moving target is futile, but any advice is appreciated.

**Comment by ebuchman** [comment]
hi mark, mintnet accepts the same flags as docker-machine does. use `docker-machine create --help` to see the necessary flags for your cloud provider of choice. Then, eg `mintnet create -- --driver=amazon --other-amazon-flags ...` The `--` after `create` is bash for `everything after this should be passed through as args`, so the flags are not parsed by mintnet, but curried through to docker-machine. hope that helps.

**Comment by mark-lester** [comment]
thanks

    On Tuesday, 19 January 2016, 15:22, Ethan Buchman <notifications@github.com> wrote:
 

 hi mark, mintnet accepts the same flags as docker-machine does. use docker-machine create --help to see the necessary flags for your cloud provider of choice. Then, eg mintnet create -- --driver=amazon --other-amazon-flags ... The -- after create is bash for everything after this should be passed through as args, so the flags are not parsed by mintnet, but curried through to docker-machine. hope that helps.—

**Comment by mark-lester** [comment]
Hey guys,
I'm getting close now.I used tendermint gen_validator on both my laptop and my cloud server to make priv_validator.jsonI stuck these public keys in my genesis.json. and stuck the opposite IPs in seeds in config.toml.But I hacked the genesis.jsons, who's heritage is uncertain, to have the same chain:"test-chain-ben" instead of the 6 char value. And of course it goes   

INFO[01-20|15:59:39] Failed adding peer                       module=p2p address=52.30.173.169:46656 conn=&{conn:{fd:0xc211078000}} error="Peer is on a different network. Got test-chain-vMjLze, expected test-chain-yn6Oof"

how do I get these both to use the same chain, and how do I determine what that chain is (though I can see what the values should be obviously form the above line, I still need them to be the same).

I accept that I am going to need to want a test network of at least 4 or 5 machines before long, so I am going to have to start using docker, but for now I'd just like to get two tendermint nodes to talk and play some simple games before moving on. 


    On Tuesday, 19 January 2016, 15:22, Ethan Buchman <notifications@github.com> wrote:
 

 hi mark, mintnet accepts the same flags as docker-machine does. use docker-machine create --help to see the necessary flags for your cloud provider of choice. Then, eg mintnet create -- --driver=amazon --other-amazon-flags ... The -- after create is bash for everything after this should be passed through as args, so the flags are not parsed by mintnet, but curried through to docker-machine. hope that helps.—

**Comment by ebuchman** [comment]
Hi mark.

If you run `tendermint init`, you'll get a default genesis.json and priv_validator. You can use `tendermint gen_validator` and add the pubkey to the genesis, and change the genesis chain name. Make sure the same genesis is on both the laptop and remote box, in their respective `~/.tendermint` folders, and that the seeds are correct.

Alternatively, you can use `mintnet init` to do it for you. eg. `mintnet init --machines "mach[1-2]" /path/to/some/dir` will create all the necessary files in /path/to/some/dir. Other mintnet commands (create, start) will create machines and start tendermint on them using the /path/to/some/dir. Or, you could copy the dirs yourself so you can play, as you say, using your laptop and remote box.

**Comment by mark-lester** [comment]
read the error message Mark.It's complaining about the "Network". On my dev I have  Network:test-chain-yn6Oof 
but on my cloud I get  Network:test-chain-vMjLze 
 where does this get set ?.

    On Wednesday, 20 January 2016, 17:35, Ethan Buchman <notifications@github.com> wrote:
 

 Hi mark.If you run tendermint init, you'll get a default genesis.json and priv_validator. You can use tendermint gen_validator and add the pubkey to the genesis, and change the genesis chain name. Make sure the same genesis is on both the laptop and remote box, in their respective ~/.tendermint folders, and that the seeds are correct.Alternatively, you can use mintnet init to do it for you. eg. mintnet init --machines "mach[1-2]" /path/to/some/dir will create all the necessary files in /path/to/some/dir. Other mintnet commands (create, start) will create machines and start tendermint on them using the /path/to/some/dir. Or, you could copy the dirs yourself so you can play, as you say, using your laptop and remote box. —

**Comment by ebuchman** [comment]
should be the `chain_id` field in the ~/.tendermint/genesis.json. Do those match on the two machines?

**Comment by mark-lester** [comment]
humf, 
Here is my ~/.tendermint/genesis.json, it's made by mintnet init as you can see. It's the same story on my remote, same genesis of course, and yet I get Network:test-chain-vMjLze, so not as in genesis.json and inconveniently not the same as my dev machine.The only other genesis.json on the remote is at src/github.com/tendermint/tendermint/config/tendermint/genesis.json, and that of course still doent have the value tendermint node comes up with in the log.

 {"genesis_time":"2016-01-19T14:15:10.460Z","chain_id":"chain-0KDyyz","validators":[{"pub_key":[1,"5CA54C7B769A263D1F0F5A951FBECA1FB83826A0A91997A2696C467F00E60C09"],"amount":1,"name":"mach1"},{"pub_key":[1,"52269751BCC49B918B6C8B455F95E05EEAD9EA531A623E8E0874E8D9E358050C"],"amount":1,"name":"mach2"},{"pub_key":[1,"1D672C4A5689E6A0E3CDCA6524CFEC0550610CB62FE77CDB533320CACA256572"],"amount":1,"name":"mach3"},{"pub_key":[1,"48D4176877273400FEA535B4AFAC80128C75CA2C6054EA81E9898244DA852788"],"amount":1,"name":"mach4"}],"app_hash":""}

 

    On Thursday, 21 January 2016, 0:23, Ethan Buchman <notifications@github.com> wrote:
 

 should be the chain_id field in the ~/.tendermint/genesis.json. Do those match on the two machines?—

**Comment by mark-lester** [comment]
it doesnt matter what I do to genesis.json, I always get node saying it's on Network:test-chain-yn6Oof on dev, and on my other machine I always get test-chain-vMjLze , no matter what I try.
```
NOTE[01-21|09:17:09] Started node                             module=node nodeInfo="&{PubKey:PubKeyEd25519{462AE3C071BBCF973D89A67ED61A71D4BD508F0125B2393E5B6DBB10CF4F9418} Moniker:devel Network:test-chain-yn6Oof RemoteAddr: ListenAddr:192.168.1.195:46656 Version:0.5.2 Other:[p2p_version=0.3.0 rpc_version=0.4.0 wire_version=0.5.0 rpc_addr=0.0.0.0:46657]}"
```
I crudely searched for "test-chain", and all I could find was this https://github.com/tendermint/tendermint/blob/master/cmd/tendermint/init.go#L14
, which is true, if I go tendermint init it will cook me a genesis.json that goes chain: test-chain-random string. It's a different number again to the one that node insists on using, but the main point here is I just need to get the two machines to use the same network, and I have no way of setting it.
Apologies for the saga, I hope we're genuinely cleaning some fluff up and not my stupidity.

**Comment by mark-lester** [comment]
I am now a go hacker.
I had stuff in data, I had to zap all that.
stuff happens now.

**Comment by ebuchman** [comment]
ah of course! the chain_id is saved in the data so if you're starting things over defntly need to clear ~/.tendermint/data. apologies for not suggesting that earlier, I take it for granted sometimes. All good?

**Comment by mark-lester** [comment]
yeah we're moving. I need to get my head round docker now, we're networking, you need loads of machines dont ya.
