### ISSUE TITLE
Runtime error on project that uses tendermint - panic: http: multiple registrations for /debug/requests

### ISSUE THREAD

**Issue by flockonus** [tendermint/tendermint#1801]
**BUG REPORT**

**Tendermint version**: 27bd1deabe4ba6a2d9b463b8f3e3f1e31b993e61 / v0.20.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS
- **Install tools**: go 1.10.1
- **Others**: 

**What happened**:
We have a project that imports tendermint libs:

```
        "github.com/tendermint/abci/types"
	"github.com/tendermint/tendermint/rpc/client"
	tmtypes "github.com/tendermint/tendermint/types"
```

Tendermint is not vendored in this project, it's relying on the system Tendermint.

The problem is that when executing we get this error:

```
panic: http: multiple registrations for /debug/requests

goroutine 1 [running]:
net/http.(*ServeMux).Handle(0x1e49a60, 0x18554f3, 0xf, 0x19f8560, 0x19a0fb8)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:2353 +0x239
net/http.(*ServeMux).HandleFunc(0x1e49a60, 0x18554f3, 0xf, 0x19a0fb8)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:2368 +0x55
net/http.HandleFunc(0x18554f3, 0xf, 0x19a0fb8)
	/usr/local/Cellar/go/1.10.1/libexec/src/net/http/server.go:2380 +0x4b
github.com/tendermint/tendermint/vendor/golang.org/x/net/trace.init.0()
	/Users/fps/go/src/github.com/tendermint/tendermint/vendor/golang.org/x/net/trace/trace.go:115 +0x42
panic: http: multiple registrations for /debug/requests
```

**What you expected to happen**:
It seems that inside tendermint it's vendored `golang.org/x/net/trace/` and because of it's init function it's bugging things out and execution becomes impossible like that.

Perhaps a suggestion is that would make sense to remove golang.org/x from vendored in this case?

cc @gdamore who found this issue and proposed the solution

**Comment by melekes** [comment]
I am confused. Are you using any dependency manager? If not, why there is a `vendor` dir in the first place? You can just remove it completely. If you do use something like dep or glide, it should figure out this conflict (and tendermint should be inside your project's `vendor` directory, not inside your GOPATH).

**Comment by gdamore** [comment]
I think tendermint was built using a dependency manager.  We weren't using
one for our project.

**Comment by melekes** [comment]
> I think tendermint was built using a dependency manager

oh, I see. Then just remove the `vendor` dir. 

In Go, it can be hard to develop multiple projects. I am personally using docker&vagrant to sandbox each project, so their dependencies are not intersecting (because Go won't resolve conflicts for you.. i.e. 1st project requires library version 1.X, 2nd requires 1.Y. it will just use master).

**Comment by flockonus** [comment]
Thank you for the suggestion of isolating @melekes , i'll try it out and agree it's more of a Go dependency management than Tendermint.
