### ISSUE TITLE
[feature request] Allow change of loglevels during runtime

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1802]
**FEATURE REQUEST**

It would be amazing if you could allow changing loglevels during runtime.
It would allow a user to enable debugging or info on any component and if analysis is done, switch back to a more sane level (error or the like) on the fly without the need of restarting everything, especially when you have an external abci app.

I've come to love such features as they are present in the logback framework we are using in our Java apps. In this case, the framework uses dedicated log-configuration files that can be reloaded by the framewok in a configurable interval to check for changes. 

One could also think of an RPC config endpoint, which allows such changes (maybe even more config options to change on the fly?)

**Comment by bradyjoestar** [comment]
I'm try to solve this issue ,but I found the implement of the SetLogger 
```
func (dbp *DBProvider) SetLogger(logger log.Logger) {
	dbp.logger = logger.With("label", dbp.label)
}
```

It is passed by the value not pointer ,
how about  solving it by resetting logger of every running service? For example:
```
mempoolLogger := logger.With("module", "mempool-disabled")
mempool.SetLogger(mempoolLogger)
```
if we disabled the `module=mempool` log.

**Comment by jackzampolin** [comment]
Closing as `wont-fix` 🕶

**Comment by ebuchman** [comment]
@jackzampolin do you not think this is something we should support if an external contributor wanted to help make it happen?
