### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by AzimAzlie** [tendermint/tendermint#1807]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Logs (you can paste a part showing an error or attach the whole file)**:

**Config (you can paste only the changes you've made)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:

**Comment by ValarDragon** [comment]
Was this an accident?
