### ISSUE TITLE
crypto/ed25519: Batch verification

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1809]
Description:
Bernstein mentions in the ed25519 paper that batch verification can be done using a multi-scalar exponentiation algorithm such as pippengers or bos-corter. Bos-Corter is used in his benchmarks, since its easier to implement and uses less memory (he was primarily concerned with fitting things inside the L1 processor cache in that paper). Using bos-corter, he found that the time per signature halved when batch verifying 64 signatures under 64 different pubkeys. This only improves as the number of signatures being batch verified increases. Also note that this requires one random number to be chosen per signature. I suggest implementing this via bos-corter for now, and benchmark pippengers at a later date.

Further optimizations
* Using the same public key multiples times in a batch verification. For every signature here, the group operations are one 253 bit scalar mul, and one 128 bit scalar mul. If we re-use the same public key multiple times in a batch verification, we can just add the 253 bit scalars for those public keys together, so the second signature in effect only contributes one 128 bit scalar mul. (There are still more group operations and randomness needed for that signature, just no scalar mul)
* #1784 - will reduce time taken here by `> 20%`, since decompression isn't getting sped up, plus the window is going to be recomputed for each pubkey.
* https://github.com/tendermint/ed25519/pull/9 - implementation detail which may carry over speedups here

Things needed:
* We need a fast heap implementation. 
* Actually implementing this
* Optimizing said implementation
* Figuring out the API, in a way that we can quickly detect the same pubkey was reused. Sorting would be too slow I think. This may be something that should be handled on the tendermint side for fast syncing, as opposed to being done in crypto/ed25519.
* Getting the implementation reviewed, since this affects signature verification

**Comment by marbar3778** [comment]
would this be sufficient https://github.com/oasislabs/ed25519/blob/master/batch_verify.go for use when fast sync reactor is in use?

Is the idea here to also have batch verification while in the consensus reactor?

**Comment by zmanian** [comment]
Yes this would be a great use case for the oasis library.

**Comment by hdevalence** [comment]
In re: the checklist in the issue above, the underlying curve library used by `ed25519consensus` has a multiscalar multiplication API, so it's not necessary to implement Bos-Coster yourself, etc.

All that's required is to port the Rust implementation I made for `ed25519-zebra` to Go, tracked in this issue: https://github.com/hdevalence/ed25519consensus/issues/5

That implementation uses a hashmap to store batch entries, so it automatically adapts to coalesce terms from signatures with the same verification key:

![benchmark](https://www.zfnd.org/images/coalesced-batch-graph.png)

In Zebra, we used futures to allow transparent batching ([more details](https://doc.zebra.zfnd.org/tower_batch/index.html)) but I'm not sure how well this would translate to Go.
