### ISSUE TITLE
missing Comparable method for Type

### ISSUE THREAD

**Issue by mark-lester** [tendermint/tendermint#181]
can't install right now
 go get github.com/tendermint/tendermint/cmd/tendermint
# github.com/tendermint/go-wire
src/github.com/tendermint/go-wire/reflect.go:972: fieldType.Comparable undefined (type reflect.Type has no field or method Comparable)

**Comment by ebuchman** [comment]
are you using go version 1.3? Tendermint expects at least 1.4, but best to use the latest, which is 1.5

**Comment by mark-lester** [comment]
ah, I thought we were on 1.5 but this says
go versiongo version go1.2.1 linux/amd64

thanks.


    On Saturday, 23 January 2016, 17:03, Ethan Buchman <notifications@github.com> wrote:
 

 are you using go version 1.3? Tendermint expects at least 1.4, but best to use the latest, which is 1.5—
