### ISSUE TITLE
crypto: Move armor into the sdk

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1821]
The only place armor.go is used in all of our repositories is inside of the sdk for encrypting/decrypting keys. Now that the crypto relevant to the keys is in the sdk (or coming soon w/e ledger pr is merged), armor should be moved there as well.

**Comment by ebuchman** [comment]
Not sure about this - we may need to use it to encrypt the node_key and priv_validator used in tendermint ...

**Comment by ValarDragon** [comment]
Sounds like a good thing to do!
