### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by olegomano** [tendermint/tendermint#1825]
BUG REPORT

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
BigchainDB

**Environment**:
- environment: Linux ip-172-31-26-47 4.9.85-37.55.amzn1.x86_64 #1 SMP Mon Mar 5 19:00:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 
- 1GB Ram
- os: amazon linux
- install tools: Docker

We have a long running BigchainDB node that was running successfully for around 2 weeks. Today the whole system became unresponsive due to out of memory issues. We could not run bash commands because the system would fail to allocate memory for them. Docker commands would fail and complain about failing to allocate memory. According to Top most of the memory on the system was being used by the tendermint process. 

Our system only has 1GB of RAM. Is running out of memory like this something to be expected? If so what is the recommended amount of RAM we should have, and how does memory usage scale with utilization. 

Top command 
```

31651 root      20   0  991m 405m    4 D  0.0 40.8   2:26.62 ws_to_ten

31295 999       20   0  997m  42m    0 S  0.3  4.3  29:41.57 mongod  

31650 root      20   0  501m  40m    0 S  0.0  4.1   0:00.24 ws      

31537 root      20   0  500m  39m    4 S  0.3  4.0   6:58.46 bigchaind

31652 root      20   0  499m  38m   12 S  0.0  3.9   0:00.17 exchange
```
```

docker ps
-bash: fork: Cannot allocate memory
```
```

        /usr/lib/golang/src/runtime/asm_amd64.s:360 +0xab fp=0x7fff0a6f31f0 sp=0x7fff0a6f31e8 pc=0x4598bb

runtime.(*mheap).alloc(0x171cea0, 0x1, 0x7fff0a01002a, 0x4598bb)

       /usr/lib/golang/src/runtime/mheap.go:732 +0xa1 fp=0x7fff0a6f3240 sp=0x7fff0a6f31f0 pc=0x425981

runtime.(*mcentral).grow(0x171ec70, 0x0)

       /usr/lib/golang/src/runtime/mcentral.go:232 +0x94 fp=0x7fff0a6f3288 sp=0x7fff0a6f3240 pc=0x4184d4

runtime.(*mcentral).cacheSpan(0x171ec70, 0x1736f40)

       /usr/lib/golang/src/runtime/mcentral.go:106 +0x33a fp=0x7fff0a6f32d0 sp=0x7fff0a6f3288 pc=0x41803a

runtime.(*mcache).refill(0x7fbe64de7000, 0x7fff0a6f332a, 0x414a77)

       /usr/lib/golang/src/runtime/mcache.go:123 +0xa4 fp=0x7fff0a6f3300 sp=0x7fff0a6f32d0 pc=0x417b94

runtime.(*mcache).nextFree.func1()

       /usr/lib/golang/src/runtime/malloc.go:557 +0x32 fp=0x7fff0a6f3328 sp=0x7fff0a6f3300 pc=0x456762

runtime.systemstack(0x7fff0a6f3360)

       /usr/lib/golang/src/runtime/asm_amd64.s:360 +0xab fp=0x7fff0a6f3330 sp=0x7fff0a6f3328 pc=0x4598bb

runtime.(*mcache).nextFree(0x7fbe64de7000, 0x2a, 0x4598bb, 0x414889, 0x7fff0a6f33b8)

       /usr/lib/golang/src/runtime/malloc.go:556 +0xa9 fp=0x7fff0a6f3388 sp=0x7fff0a6f3330 pc=0x413889

runtime.mallocgc(0x180, 0xf0bc00, 0x7fbe64de7001, 0x7fff0a6f34f0)

       /usr/lib/golang/src/runtime/malloc.go:711 +0x6f0 fp=0x7fff0a6f3430 sp=0x7fff0a6f3388 pc=0x414150

runtime.newobject(0xf0bc00, 0x20000000)

       /usr/lib/golang/src/runtime/malloc.go:840 +0x38 fp=0x7fff0a6f3460 sp=0x7fff0a6f3430 pc=0x414498

runtime.malg(0x8000, 0xf6ac50)

       /usr/lib/golang/src/runtime/proc.go:2910 +0x31 fp=0x7fff0a6f34a0 sp=0x7fff0a6f3460 pc=0x436d41

runtime.mpreinit(0x1715980)

       /usr/lib/golang/src/runtime/os_linux.go:303 +0x2d fp=0x7fff0a6f34c8 sp=0x7fff0a6f34a0 pc=0x42bc1d

runtime.mcommoninit(0x1715980)

       /usr/lib/golang/src/runtime/proc.go:546 +0xad fp=0x7fff0a6f3500 sp=0x7fff0a6f34c8 pc=0x4307bd

runtime.schedinit()

       /usr/lib/golang/src/runtime/proc.go:482 +0x5f fp=0x7fff0a6f3540 sp=0x7fff0a6f3500 pc=0x43050f

runtime.rt0_go(0x7fff0a6f3648, 0x2, 0x7fff0a6f3648, 0x0, 0x7fbe64447c05, 0x0, 0x7fff0a6f3648, 0x200000000, 0x45d2c0, 0x0, ...)

       /usr/lib/golang/src/runtime/asm_amd64.s:175 +0x1eb fp=0x7fff0a6f3548 sp=0x7fff0a6f3540 pc=0x45969b
```

**Comment by melekes** [comment]
What Tendermint version are you using?

We recently fixed a bunch of memory leaks, so if you're using an older version of Tendermint, this is expected. 1GB is the minimal requirement, but maybe not optimal for performance (depending of course on the size of deployment, avg. transaction size, etc.)

**Comment by olegomano** [comment]
We are on version 0.20

**Comment by melekes** [comment]
Can you try the latest version and see if it fixes the problem?

**Comment by melekes** [comment]
If not, can you attach a heap dump (use `curl 'localhost:26657/unsafe_write_heap_profile?filename="/tmp/1.prof"'` to create one; note this requires running tendermint with `--rpc.unsafe`)?

Also, output of `kill -6 <PID>` would be super useful.

We can do it ourselves if you provide a script or instructions for replicating the issue.

**Comment by melekes** [comment]
We haven’t gotten a response to our questions above.

_With only the information that is currently in the issue, we don’t have enough information to take action. We’re going to close this but don’t hesitate to reach out if you have or find the answers we need. If you answer our questions above, a maintainer will reopen this issue._
