### ISSUE TITLE
meta: recommend pasting logs in pastebin or similar for issues

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1826]
Many issues have extremely long output which we ask for in the issue template, which is necessary for debugging. However, these issues being extremely long makes it hard to scroll the issue / read the surrounding context. Could the issue template be changed to recommend putting long logs / config files inside of a pastebin / ghostbin / equivalent service? 

If we recommend pastebin, then we can easily update issues to snip out logs into pastebins. I think its more work to try to take a section of logs, and then save it to a file and then attaching it to the github issue.

**Comment by melekes** [comment]
Agree. Do you want to update the template?
