### ISSUE TITLE
Validator address no longer is generated automatically

### ISSUE THREAD

**Issue by KrzysiekJ** [tendermint/tendermint#1829]
**Tendermint version** 0.21.0-46369a1a

The commit 42626d9e16ff7eab2c0647d76b7825ed29de3abe added generation of public key and address from private key of validator. While it is still possible to not specify public key in `priv_validator.json`, omitting address results in the following error:

```
No addresses to dial nor connected peers. Falling back to seeds module=p2p
```

Since address is redundant, it would be nice to allow it to be omitted.

Refs #500.

**Comment by ebuchman** [comment]
Ah, that log line is an unrelated coincidence.

The real problem is the following line:

```
I[06-29|21:53:50.617] This node is not a validator                 module=consensus addr= pubKey=PubKeyEd25519{30BA2B9ECF42550D427A5BA69A5D3E88066F3B22487B4649D78DF597DA0EB7DC}
```

The node things its not a validator because the empty address isn't in the validator set.

We should make it so when the PrivValidator is loaded, all fields are populated properly. Should be an easy fix.

**Comment by melekes** [comment]
Will be in the next release (> 0.22.0).
