### ISSUE TITLE
Write a test for IPv6

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1833]
1) establishing connection + basic communication
2) addrbook handles IPv6 IPs properly
3) pex handles IPv6 IPs properly

**Comment by thanethomson** [comment]
Looking at #3711 and the thread way back from #738, could we say that IPv6 support is well-tested enough yet? Or do we still need to write additional specific tests?

I was wondering after looking at the code [over here](https://github.com/tendermint/tendermint/pull/3711/files#diff-91e8069d5cb91a5b3067a01482559679R101) that automatically resolves IP addresses. Locally I added an additional test case to `TestNewNetAddressString`:

```go
{"localhost resolution", "tcp://deadbeefdeadbeefdeadbeefdeadbeefdeadbeef@localhost:8080", "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef@127.0.0.1:8080", true},
```

And the result was:

```
--- FAIL: TestNewNetAddressString/localhost_resolution (0.00s)
	Error Trace:	netaddress_test.go:72
	Error:      	Not equal: 
	            	expected: "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef@127.0.0.1:8080"
	            	actual  : "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef@[::1]:8080"
	Test:       	TestNewNetAddressString/localhost_resolution
```

The underlying resolver behind `net.LookupIP` might arbitrarily prefer IPv6 addresses, which could be problematic if our IPv6 support isn't well-tested enough.

**Comment by jackzampolin** [comment]
cc @sabau
