### ISSUE TITLE
Write a test for #1795

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1834]
See https://github.com/tendermint/tendermint/pull/1795

**Comment by jackzampolin** [comment]
cc @sabau

**Comment by tessr** [comment]
lol:

![Screen Shot 2020-10-29 at 6 43 51 PM](https://user-images.githubusercontent.com/773524/97611627-b698c500-1a16-11eb-8b74-90664e86be6d.png)

_***_two and a half years later_***_ 

I'm not even sure what the root bug was, and we have a lot of new testing in place, so I'm going to close this. We can open a fresh issue if we see this again.
