### ISSUE TITLE
consensus: WAL isn't shut down properly

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1839]
See https://github.com/tendermint/tendermint/blob/f760c24ff0df7cd150ca1e10a16cdc70110fac79/consensus/state.go#L301

By this point, IsRunning will always be false, so the cs.wal.Wait is never called. But it also looks like the WAL is never even stopped? 

This came up because the SDK tests fails non-deterministically sometimes because the autofile panics. Those tests start and stop Tendermint nodes in process.

**Comment by melekes** [comment]
Done in https://github.com/tendermint/tendermint/commit/af703620d4423478968ab602716a2a51cbb02ac6#diff-80343e80650fe43a4394fc26afd5cb3b

**Comment by melekes** [comment]
What about this stop?

https://github.com/tendermint/tendermint/blob/f760c24ff0df7cd150ca1e10a16cdc70110fac79/consensus/state.go#L605

Do you still have a stack trace of the panic mentioned above?

**Comment by ebuchman** [comment]
Seems I missed that. I may have been wrong to add the Stop where I did - it's not even clear that was actually the issue anymore. But it does seem the IsRunning is always false by then, so that Wait() call never happens. I believe removing the IsRunning caused it to hang, too.

**Comment by melekes** [comment]
> But it does seem the IsRunning is always false by then, so that Wait() call never happens

true, but removing it does not achieve anything other then deleting 3 lines of code.
