### ISSUE TITLE
libs/common: non-deterministic test failure in repeat timer

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1844]
```
--- FAIL: TestRepeatTimerReset (0.14s)
	repeat_timer_test.go:129: expected to receive tick after reset
```

Showed up in the tmlibs merge https://github.com/tendermint/tendermint/pull/1842

**Comment by melekes** [comment]
also, keep in mind that repeat timer is leaking memory in Tendermint

**Comment by ebuchman** [comment]
closing for https://github.com/tendermint/tendermint/issues/1976
