### ISSUE TITLE
p2p: support DNS in ExternalAddress

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1845]
PR https://github.com/tendermint/tendermint/pull/1843 adds support for an ExternalAddress that should be dialed by peers to reach us, but it currently resolves to an IP right away because this is how the NewNetAddress functions work, which means we can't tell peers to dial us on a domain.

We should fix this, but it's part of the larger story of p2p refactor

**Comment by melekes** [comment]
I think this is a part of https://github.com/tendermint/tendermint/issues/1521. No need in a separate issue.

**Comment by ebuchman** [comment]
Sure
