### ISSUE TITLE
ABCI: Custom application data in block header

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1855]
original issue: https://github.com/tendermint/abci/issues/259

**Comment by melekes** [comment]
@b00f could you please review 
https://github.com/iantanwx/tendermint/blob/5cf4bbe42ccb269453ce84d67e4cfa16a6ce54f3/docs/architecture/adr-012-ABCI-propose-tx.md and see if it satisfies the use case?

**Comment by melekes** [comment]
> However during committing a block, the application maybe need to store some information related to delivered txs. I don't think we can do it with ProposerTx.

You can. This is exactly what `ProposeTx` does. It allows you to include additional txs into the block with any data you want (fee, ...).

**Comment by b00f** [comment]
If I am not mistaken during committing a block mempool is locked for that round.
For example when the block is committing, Application wants to save extra information about that specific block. 
The idea behind `ProposerTx` is awesome and it can help application to have extra control (specially for Plasma architecture). 
However when application wants to have some custom data to be save on that round at committing phase what do you suggest?

**Comment by melekes** [comment]
> If I am not mistaken during committing a block mempool is locked for that round.

correct

> However when application wants to have some custom data to be save on that round at committing phase what do you suggest?

it responds to `ProposeTx` ABCI call with the tx carrying this custom data.

**Comment by b00f** [comment]
During commit mempool is locked: 
> Before calling Commit, Tendermint will lock and flush the mempool, ensuring that all existing CheckTx are responded to and no new ones can begin.

https://github.com/tendermint/tendermint/blob/5ff65274b84ea905787a48512cc3124385bddf2f/docs/app-dev/abci-spec.md#checktx

By the way, How can application access to this data just by getting block header information?

**Comment by melekes** [comment]
> By the way, How can application access to this data just by getting block header information?

You're right. There's no way. You'll have to fetch the whole block.

**Comment by ebuchman** [comment]
You can get just the block header for eg. block 1 using `http://localhost:26657/blockchain?minHeight=1&maxHeight=1`

**Comment by jackzampolin** [comment]
Sounds like this isn't something we want.

**Comment by melekes** [comment]
BeginBlock, EndBlock and each DeliverTx now includes `events` field, which allows you to add any application specific data. 

See https://github.com/tendermint/tendermint/blob/ab0835463f1f89dcadf83f9492e98d85583b0e71/docs/spec/abci/abci.md#events (or https://tendermint.com/docs/spec/abci/abci.html#events when v0.32.0 is out)
