### ISSUE TITLE
ABCI: use proto3 timestamp

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1857]
and document the semantics of Header.Time.

original issue https://github.com/tendermint/abci/issues/267 opened by @coriolinus

and https://github.com/tendermint/abci/issues/275

**Comment by ebuchman** [comment]
Leaving open to note that we still need to properly document how we handle time

**Comment by melekes** [comment]
> Leaving open to note that we still need to properly document how we handle time

Are you talking about that we should have a document/ADR with current state and plans for median time? https://github.com/tendermint/tendermint/issues/2013 and https://github.com/tendermint/tendermint/issues/2112

Or a note saying "Currently, Tendermint does not perform any validity checks on `Time` when accepting a proposal block"

**Comment by ebuchman** [comment]
> Are you talking about that we should have a document/ADR with current state and plans for median time?

Yes - we have a spec for BFT time but we also need to make sure we make consistent use of time across the codebase and always encode it the same way.

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/2013
