### ISSUE TITLE
ABCI: add codespace string to error code

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1858]
original issue: https://github.com/tendermint/abci/issues/272

**Comment by ValarDragon** [comment]
Is this blocked on having the ADR written, per the original issue?

**Comment by melekes** [comment]
What about the Log/Info fields? Aren't they enough?

**Comment by cwgoes** [comment]
> What about the Log/Info fields? Aren't they enough?

They're non-deterministic, right? (at least, that's what's marked in the `.proto` files).

**Comment by ebuchman** [comment]
Closing for #2557
