### ISSUE TITLE
ABCI: add Priority to ResponseCheckTx

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1861]
original issue: https://github.com/tendermint/abci/issues/277

TL:DR;

We don't use the fee field and its likely just confusing.

We can add backwards compatible `priority` (instead of fee) later.

Note priority is better than fee because it lets the app do the math on how to rank order transactions, rather than forcing that into tendermint (ie. if we return fee, priority would be fee/gas)

**Comment by ebuchman** [comment]
See #1997

**Comment by ebuchman** [comment]
Re-opening because we need to add priority

**Comment by cwgoes** [comment]
Is this slated for the next release? We'd like to implement the non-consensus minimum fee downstream for the next SDK release as it's a requirement for GoS.

**Comment by ebuchman** [comment]
@cwgoes afaik the min fee doesnt require co-ordination from tendermint: https://github.com/cosmos/cosmos-sdk/issues/1921#issuecomment-417483614

**Comment by cwgoes** [comment]
> @cwgoes afaik the min fee doesnt require co-ordination from tendermint: cosmos/cosmos-sdk#1921 (comment)

OK, makes sense, thanks!

**Comment by marbar3778** [comment]
Closing in favor of issue https://github.com/tendermint/spec/issues/162. Spec work is required prior to implementation
