### ISSUE TITLE
libs/cli: --home should expand paths

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1869]
original issue: https://github.com/tendermint/tmlibs/issues/173

e.g., `~` doesn't work

**Comment by VenkatDatta** [comment]
Hi @zramsay , I think `~` is handled by shell itself.
Tried: tendermint init --home ~/test
It was able to resolve the path.
Let me know if i'm understanding the issue wrong

**Comment by ValarDragon** [comment]
I'm not really sure thats true. 
```bash
$ tendermint init --home=~/potato
```
created a new folder `~` in the current directory, and then a folder named potato in there. 

I'm on Ubuntu 16.04, using gnome-terminal-server as my terminal emulator.

**Comment by ebuchman** [comment]
Yeh this seems to work.
