### ISSUE TITLE
eliminate dependency on GCC

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1870]
original issue: https://github.com/tendermint/tmlibs/issues/176

see also #1162

**Comment by ValarDragon** [comment]
From various discussions, I think we're moving towards no cross-compilation iirc. The reason being, eventually we're going to be unable to do this, as we depend on more and more new cryptography. For example, we'd likely have to bring in Rust for BLS.

**Comment by ValarDragon** [comment]
Closing due to the above, please re-open if we still do intend to support cross-compilation long term.
