### ISSUE TITLE
Inconsistency in transaction processing

### ISSUE THREAD

**Issue by PradeepSalanki** [tendermint/tendermint#1875]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.22.0  https://hub.docker.com/r/tendermint/tendermint/tags/

**ABCI app** (name for built-in, URL for self-written if it's publicly available): 
https://github.com/PradeepSalanki/abci-test/blob/master/server.js

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS High Sierra Version 10.13.5 (17F77)
- **Install tools**: Docker Version 18.03.1-ce-mac65 (24312)
- **Others**:
A network setup with 4 validator nodes(running on different machines) and 1 Non-validator node(genesis.json and persistent-peers same as 4 validator nodes). 

**What happened**:
When 2 validator nodes were stopped, the transactions posted to non-validator node's RPC endpoint by the following command
curl -s 'localhost:26657/broadcast_tx_sync?tx="AB11"'
curl -s 'localhost:26657/broadcast_tx_sync?tx="AB12"'
curl -s 'localhost:26657/broadcast_tx_sync?tx="AB13"'

This results in 3 unconfirmed txs in http://localhost:26657/num_unconfirmed_txs in Non-Validator node (As expected)
However when 1 validator node was started again (total 3 validators) the number of unconfirmed txs on each of the validator nodes were 2 instead of 3 and only those 2 txs were processed. 
The non-validator node still shows 1 unconfirmed tx and its never gets processed(removed from mempool). 
**What you expected to happen**:
All the unconfirmed txs in the non-validator node should be broadcasted to all the connected nodes in the network and validator nodes should process the transactions.

**How to reproduce it** (as minimally and precisely as possible):
Disconnect 2 validator nodes out of 4. Post transactions from non-validator node's RPC endpoint.

**Logs (you can paste a small part showing an error or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
proxy_app = "tcp://ipaddressofmachine:26658" (could not connect to the ABCI server otherwise)
persistent_peers = "dfff700f7be5e8622037273c4a4cd8a540265058@10.10.1.71:26656,5fca1eb1e53cec2efd9d50f44df315fb1158546a@10.10.1.225:26656,b49af44130ee1fd7b489334d86c6360f387297ca@10.10.1.199:26656,b824b8595b478f7fee4ef45b0ca01a6a629a5f2d@10.10.1.207:26656"
**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:

**Comment by melekes** [comment]
Could you attach some logs here?

**Comment by ebuchman** [comment]
I'm so far not able to reproduce it - I tried locally using `make localnet-start` to start a 4-validator cluster and then running `tendermint node` locally with the kvstore to join that network.  I can send lots of txs just fine through that non validator node. If I shutdown 2 validators, send txs to the non-validator, they linger in the mempool (as expected) and get gossiped to the other 2 validators (as expected). If I then bring 1 validator back online, they soon make a block and commit the txs, emptying from everyone's mempool.

Are there more details you can provide for how to reproduce? 

Also, are you using `create_empty_blocks=false` ?

**Comment by PradeepSalanki** [comment]
@melekes Sorry I couldn't get a chance to run the network setup again(All the machines were not available). I will try to do it again and update the logs here. 
@ebuchman I do not know if it makes a difference if you run the setup with docker. Will it be possible for you to test the setup  with docker image tag v0.22.0 and js-abci? Yes, I used `create_empty_blocks=false`.

**Comment by PradeepSalanki** [comment]
Tried the setup with docker image v0.22.4 and did not face the issue. The unconfirmed transactions from a non-validator node are being relayed to the 2 validators nodes and it's being processed when any of the 2 validator nodes(stopped earlier) join in. However, the nodes keep disconnecting and need to be restarted to connect to the peers again. Attached a screenshot if it's of any help. Closing for the uncleared transactions issue.

<img width="800" alt="screen shot 2018-07-17 at 23 01 43" src="https://user-images.githubusercontent.com/6400446/42845185-711eb96e-8a15-11e8-9e8a-2ff5a1aabd7a.png">

<img width="801" alt="screen shot 2018-07-17 at 23 00 06" src="https://user-images.githubusercontent.com/6400446/42845126-47c5db6a-8a15-11e8-8492-ab85a265612b.png">

<img width="797" alt="screen shot 2018-07-17 at 23 00 29" src="https://user-images.githubusercontent.com/6400446/42845124-4797a3bc-8a15-11e8-9db7-609431f1748a.png">

<img width="798" alt="screen shot 2018-07-17 at 22 53 14" src="https://user-images.githubusercontent.com/6400446/42844845-851fe02e-8a14-11e8-8e1f-dbbd3b62b83a.png">
