### ISSUE TITLE
EOF error in case of ABCI server down with 1 Validator

### ISSUE THREAD

**Issue by Amardeepsuri** [tendermint/tendermint#1878]
**BUG REPORT**

**Tendermint version** 0.22.0

**ABCI app** : https://github.com/Amardeepsuri/server.js

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OSX 10.13.5 (17F77)
- **Install tools**: Docker Version 18.03.1-ce-mac65 (24312)
- **Others**: Visual Studio Code

**What happened**: I set up the network with ONE Validator and ONE ABCI server ( custom code mentioned above). I then used the CURL command (curl -s 'localhost:26657/broadcast_tx_sync?tx="AB12"') to post a transaction to the network ( Screenshot 1). The block is created and works as expected. 
Now the ABCI server goes down for this particular Validator and the connection is lost with an Internal Error EOF as in the second screenshot). I now try to post a transaction which does not go through.
I bring back the ABCI server online again but still this Validator does not sync up with server and gives back the EOF error abci.socket error ( screenshot 3).

**What you expected to happen**: The validator should sync up with the ABCI server when it is back online without EOF error and should sync asap. Transactions and creation of blocks should work.

**How to reproduce it**:
1. Set up ONE Validator node with ONE ABCI server for it.
2. Post a transaction and the block will be made.
3. Remove or stop the ABCI server connected to that Validator.
4. Try to post the transaction again ( EOF error starts here)
5. Try to post again after the ABCI server is up (still the error).

**Logs**:1.
![1](https://user-images.githubusercontent.com/40795411/42220655-e13d5846-7ecf-11e8-9e26-2f6179765a57.png)
2. 
![2](https://user-images.githubusercontent.com/40795411/42220948-b2dccc2e-7ed0-11e8-87e6-8dc2548dfd98.png)
3.
![3](https://user-images.githubusercontent.com/40795411/42221150-688b2494-7ed1-11e8-869d-d455361a0711.png)

**Config**:
proxy_app = "tcp://10.10.1.199:26658"

**Comment by ebuchman** [comment]
So Tendermint actually can't handle restarting ABCI apps internally without restarting Tendermint as well. What's supposed to happen is Tendermint will print an error saying that the ABCI app went down and thus it needs to be restarted, but looks like that didn't happen here.

**Comment by melekes** [comment]
This can be the same issue as https://github.com/tendermint/tendermint/issues/1890. @Amardeepsuri can you try https://github.com/tendermint/tendermint/pull/1891 and see if EOF goes away?

**Comment by Amardeepsuri** [comment]
Thanks Anton, One question from my side is that do we also have the equivalent implementation in the JS-ABCI or JS drivers? I wrote my ABCI client is JS and in #1891 I saw changes from you in GO.

**Comment by melekes** [comment]
There is a https://github.com/tendermint/js-abci, but I don't think you have to change anything. the error seems to be purely on Tendermint side.

**Comment by ebuchman** [comment]
@Amardeepsuri can you confirm is this is solved for you with the changes from #1891 ? They have been released in v0.22.4 and shouldn't require any changes on your part (it's purely a Go client side problem, afaik)

**Comment by Amardeepsuri** [comment]
Yes the problem is solved for me. Thank you. Sorry for late reply, was in vacation.
