### ISSUE TITLE
libs/pubsub: make message tags available to subscribers

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1879]
original issue: https://github.com/tendermint/tmlibs/issues/143

see ^ for lengthy discussion

**Comment by melekes** [comment]
We definitely want to send tags alongside the msg. The first "obvious solution" seems like a good way to go.

> A solution I like better is to drop the message/tag distinction and make a message a key-value map, as if everything were a tag:

I don't see how this plays with the current query specification (e.g. "atom_count > 5"). 

```
Publish(ctx context.Context, keyvals... interface{}) error
```

I have a msg ("Hi") and atom_count: 6. Of course, we can encode the latter as a string `atom_count=6`, but that would require parsing (before matching) and not really efficient.

@Bric3d still want to help?

**Comment by melekes** [comment]
Done in https://github.com/tendermint/tendermint/pull/3227.
