### ISSUE TITLE
Crypto: Simplify SimpleProofFrom*

### ISSUE THREAD

**Issue by liamsi** [tendermint/tendermint#1889]
SimpleProofFromMap could be made a wrapper around SimpleProofFromHashers (moved from https://github.com/tendermint/go-crypto/issues/122):

https://github.com/tendermint/tendermint/blob/dfa9a9a30a666132425b29454e90a472aa579a48/crypto/merkle/simple_proof.go#L15-L50

**Comment by marbar3778** [comment]
> SimpleProofFromMap could be made a wrapper around SimpleProofFromHashers (moved from [tendermint/go-crypto#122])

Both these functions have since been removed from the codebase. 

Reopen this issue if there is still more to be done
