### ISSUE TITLE
Just a simple question

### ISSUE THREAD

**Issue by ochang19** [tendermint/tendermint#189]
What is the difference between  '2/3-any' and '2/3-one'?

Let me know specifically,

Thx in advance

**Comment by ebuchman** [comment]
Great question! +2/3-any means we've seen 2/3 or more votes for *any* block or for nil. So it might mean that 1/3 voted nil and 1/3 voted for some block. While +2/3-one means 2/3 or more votes for a single block. In the former case, we've heard from a quorum, but we don't have consensus on a single block. In the latter case, we've heard from a quorum expressing consensus on a single block (or nil).

Hope that helps!
