### ISSUE TITLE
crypto/merkle: SimpleMerkle should differentiate between interior & leaf nodes

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#1892]
See 
https://github.com/tendermint/tmlibs/pull/211#issuecomment-391102658
https://github.com/tendermint/tmlibs/pull/211#issuecomment-391044446

Moved over from https://github.com/tendermint/go-crypto/issues/107 (contains more pointers).

**Comment by tarcieri** [comment]
For simple Merkle Trees, it might be worth adopting the RFC 6962 format outright: https://tools.ietf.org/html/rfc6962#section-2.1

This would get you interop with all of the extant RFC 6962 libraries in various languages, e.g. for inclusion proof building/verification.

I feel like the RFC 6962 format is what people generally end up making for Merkle Trees anyway, especially when addressing this particular problem, but often not in name even if they are identical (or nearly identical) on the wire...

There are a few Go implementations to choose from:

https://github.com/google/trillian/tree/master/merkle
https://github.com/NebulousLabs/merkletree

**Comment by ebuchman** [comment]
@ValarDragon can we prioritize this?

**Comment by Liamsi** [comment]
I chatted with @ValarDragon about this: He already started the refactoring but didn't push commits yet. There are still tests that need fixing etc.

**Comment by ebuchman** [comment]
Awesome thanks Dev!

**Comment by ValarDragon** [comment]
The steps of this change AFAICT are:

- [x] Change implementation which uses hashers everywhere to use pure byte slices
- [ ] Switch proofs from taking in the value as a hash to instead take the value as bytes (refactor throughout the codebase) 
- [ ] Use a different leaf hash and inner node hash
- [ ] Use the different split point algorithm and use trillian test vectors (implemented already in #2302)

In the second and third step, the question arises of what do we want to do about tx hash. Should it be the leaf hash, or the pure hash of the tx?

**Comment by ebuchman** [comment]
> In the second and third step, the question arises of what do we want to do about tx hash. Should it be the leaf hash, or the pure hash of the tx?

I think tx hash should be the pure hash. It will become a leaf hash only when used in the tree. 

Does that make sense? It feels wrong to have the merkle tree subtelties leak into the tx hash form for users

**Comment by tarcieri** [comment]
I think it's totally fine to build the Merkle tree out of the transaction hashes, FWIW (i.e. make the content of the Merkle tree leaves a transaction hash, rather than the original transaction)

**Comment by ebuchman** [comment]
Mostly complete in #2713. See follow up in #3120

**Comment by ebuchman** [comment]
@ValarDragon from what I can tell all the boxes in https://github.com/tendermint/tendermint/issues/1892#issuecomment-428832094 were completed in #3120, correct?
