### ISSUE TITLE
state:  err if 0 power validator is added to the validator set 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1893]
We recently caught a bug in the SDK where a validator update was returned for a validator with 0 power that wasn't already part of the validator set (https://github.com/cosmos/cosmos-sdk/issues/1470). Tendermint ended up adding this validator to the set but with 0 power. 

It's the responsibility of the application to not do this (it needs to track the validator correctly), but Tendermint can help by throwing an error right away rather than allowing a 0 power validator.

**Comment by melekes** [comment]
Should we also check for negative power? Right now it will add a validator with negative power too.

**Comment by melekes** [comment]
Done.
