### ISSUE TITLE
rpc/core: update slate docs for Amino v0.10.1, turning ints to strings in responses

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1896]
Need to update all documentation of results so it matches, now that integers are output as strings.

Note we still accept integers as input in the rpc (don't need to be strings)

**Comment by zramsay** [comment]
- move docs/examples/getting-started.md to docs/quick-start.md

**Comment by zramsay** [comment]
#2488

**Comment by melekes** [comment]
Merged to develop.
