### ISSUE TITLE
Proposal for dynamically selecting the number of validators in Tendermint

### ISSUE THREAD

**Issue by svaishnavy** [tendermint/tendermint#1900]
**FEATURE REQUEST** :

This is a proposal for dynamically choosing the number of validators when using Tendermint consensus engine. Let's say we fix the block time to be 5 seconds or 10 seconds, the validator count could increase or decrease based on the moving average of the block times over a certain period. Thus Tendermint would be able to dynamically add/reduce validators based on blocktimes rather than fixing the number at 100 or 300. This is very much like bitcoin changing the hashrate every two weeks. The market/algorithm would decide the number of validators. If the Tendermint algorithm improves and communication overhead decreases, the validators would proportionally increase.

If this is something Tendermint team would consider beneficial, I would be open to seeing how to implement this.

As this is a feature request or improvement proposal, I am not answering other questions on issue template.

**Comment by melekes** [comment]
Note this is cosmos-sdk, not Tendermint. Should probably be moved there.

**Comment by ebuchman** [comment]
Tendermint itself doesn't enforce limits on the number of validators - this is purely an application level concern. You could suggest this on the cosmos-sdk repo but we won't be able to consider it pre Cosmos Hub launch.

Thanks!
