### ISSUE TITLE
Change to consensus params missing in changeLog

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#1901]
Did I miss it or didn't the change of consensus params not make it into 0.22?
AFAIK, params like block size have moved from config.toml into genesis.
This seems like a rather breaking change.
I was unable to find a hint in the changelog about that.
Did I just miss it?

**Comment by melekes** [comment]
Looks like we missed it. Thanks for pointing it out!

**Comment by melekes** [comment]
> Also this "max_packet_msg_size" was changed to "max_packet_msg_payload_size" right? Or was this unintentional?

it was intentional. we reverted back. was my mistake
