### ISSUE TITLE
Make error messages into exported constants

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1917]
It would be useful to have error messages be constants. So instead of having a hardcoded error in locations such as "Ciphertext decryption failed" we could instead have a constant `ErrIncorrectSymmetricKey`, which then returns the associated message.

Advantages of doing this are that error messages won't have to be copy pasted in multiple locations, enabling greater consistency. (They could even be fmt strings, intended for use with Sprintf) It also enables changing error messages in downstream applications (i.e. the sdk) for certain things, without having to hardcode the error message string. (I.e. what was proposed here: https://github.com/cosmos/cosmos-sdk/pull/1498/files#diff-e06d391a9610d619adfece2a88bd83caR173)

I think this would best be achieved by making a set of constant error message keys and values in each module. (As opposed to one set for the entire application)

**Comment by marbar3778** [comment]
This has already been started, but we should go through the codebase and make sure there are no hardcoded errors.

**Comment by valkyr13** [comment]
is this issue still available to be assigned?
