### ISSUE TITLE
Move `unsafe_*` rpc commands to independent devops server

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#193]

**Comment by adrianbrink** [comment]
Could you provide an explanation here?

**Comment by ebuchman** [comment]
We currently have only one RPC server that serves multiple needs: info, broadcasting tx, admin. The `unsafe_` commands should not be exposed the same way as the others. So we need some kind of way to permission up the server, possibly by having a second server on a different port with some kind of auth so that only the authenticated can call `unsafe_` commands. Lets talk about this at retreat

**Comment by adrianbrink** [comment]
Mh, would it already enough if instead of auth we disable it by default and the user then has to set a flag to enable it, plus it is only accessible from localhost?

**Comment by ebuchman** [comment]
Yes, possibly. Not a bad approach.

**Comment by thanethomson** [comment]
Is the need for this issue addressed by the `rpc.unsafe` parameter in the `config.toml` file now, or does this justify a broader discussion around AuthZ for the Tendermint RPC interface?

**Comment by ebuchman** [comment]
I think we want to enable the unsafe endpoints on a different port so folks can have the main routes exposed to the public and the unsafe routes only exposed locally. I suppose it justifies a broader discussion for the RPC

**Comment by jackzampolin** [comment]
Closing this in favor of #3367
