### ISSUE TITLE
docs: Make mac osx installation script

### ISSUE THREAD

**Issue by kiddyboots216** [tendermint/tendermint#1931]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): v 0.22.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac oSX
- **Install tools**:
- **Others**:

**What happened**:
errors, unable to tendermint

**What you expected to happen**:
what dev said would happen

**How to reproduce it** (as minimally and precisely as possible):
run sudo sh ./installation_script_ubuntu.sh on mac osx
**Logs (you can paste a small part showing an error or link a pastebin, gist, etc. containing more of the log file)**:
https://pastebin.com/AgYgMs1B
**Config (you can paste only the changes you've made)**:
mac osx
**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:

**Comment by kiddyboots216** [comment]
@ValarDragon

**Comment by ValarDragon** [comment]
The issue here is that its an ubuntu script which uses `apt` everywhere. We should ideally make an OS X installation script. Not sure if anyone has a clean mac install to test with though.

**Comment by jackzampolin** [comment]
I have a relatively clean mac we could test on too. Happy to take this.
