### ISSUE TITLE
tools: update / replace / fix mintnet-kubernetes

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1941]
original issue: https://github.com/tendermint/tools/issues/72
cc @SurabhiBorgikar

**Comment by marbar3778** [comment]
@fedekunze any chance you want to pick this up? ❤️

**Comment by fedekunze** [comment]
what is this about? is this like a side tool? what is its purpose?

**Comment by marbar3778** [comment]
we have a k8s setup but it is heavily outdated. https://github.com/tendermint/tendermint/blob/059a03a66a0d950b5e4c8956145ce708d239a182/tools/mintnet-kubernetes/README.rst#L15-L15. I was wondering if you would want to update it to the latest version of K8s. The purpose is if someone wants to use Tendermint in a K8s env for testing. We don't use it as it's outdated but if it were updated we would use it.

**Comment by tessr** [comment]
We should just delete the kubernetes tooling if it's outdated/unusable. WDYT @marbar3778 @fedekunze?

**Comment by marbar3778** [comment]
lets delete the k8s stack. its outdated.
