### ISSUE TITLE
throw in contract results in stuck unconfirmed transaction

### ISSUE THREAD

**Issue by benjaminbollen** [tendermint/tendermint#195]
From Eris slack:
> Alex Tranqui [9:41 AM] 
> Q: I noticed that when I call a contract method which throws (either from `epm.yaml` or `app.js`), the TX gets stuck in the unconfirmed TX and I need to kill the node to recover. I’m running 0.11.1 still , so I don’t expect any deep analysis, but just conceptually for now, what is the expected behaviour when a throw pops up? I was expecting the TX to be aborted and cleaned up from the unconfirmed TX. I’ll check it on 0.11.3 when it’s out.

I believe this direct level to test this would be tendermint integration tests, assuming it is a mempool issue.  Should equally be addressed at the Eris stack level, but will require progress on the eris integration tests.

**Comment by ebuchman** [comment]
i don't believe this is relevant post tmsp refactor. please re open if I'm wrong
