### ISSUE TITLE
libs: A bug in bit_array.go may cause crash

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1952]
moved from: https://github.com/tendermint/tmlibs/issues/226
cc @Hugo-Huang

**Comment by ValarDragon** [comment]
This doesn't panic. 
```
func TestString(t *testing.T) {
	var nilBitArray *BitArray
	x := nilBitArray.String()
	fmt.Println(x)
}
```

There are no errors, it just returns what is expected. (`nil-BitArray`)
