### ISSUE TITLE
Revive json2wal tool

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#1954]
Refs https://github.com/tendermint/tendermint/pull/1934#discussion_r201574829

I am not sure we will be able to find it in the Git history, but anyway should be easy to write it from the ground up.

**Comment by ebuchman** [comment]
json2wal? You mean wal2json? It's still in `scripts`

**Comment by melekes** [comment]
No, I mean `json2wal`. A script that turns json into binary wal (opposite of `wal2json`).

**Comment by ebuchman** [comment]
What's the use case again ?

**Comment by ebuchman** [comment]
Oh so we can compose test wals?

**Comment by melekes** [comment]
1) tool is mentioned in https://github.com/tendermint/tendermint/blob/e398962d873d5474e3ce0f4ba3eaed26b670fbf3/docs/tendermint-core/running-in-production.md#wal-corruption it's supposed to help user restore corrupted WAL file
2) compose test wals

**Comment by melekes** [comment]
Merged to develop.
