### ISSUE TITLE
 crypto/symmetric: Change algo from xsalsa20poly1305 to xchacha20poly1305 

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1955]
**Feature Request**
Ref: https://github.com/tendermint/go-crypto/issues/138

Basically the title. Currently we encrypt our private keys created gaiacli via nacl's secretbox which is xsalsa20poly1305. We should switch this to our hkdfchacha20poly1305 AEAD (#135)? This also lets us remove the nacl dependency. Discussed with @zmanian, we thought it would be a good idea. This is an upgrade that can happen in a backwards compatible manner. (i.e. we can deprecate a standard, and upgrade it over the course of a release)

**Comment by ValarDragon** [comment]
I think this makes more sense to switch to xchacha20poly1305, due to standardization.

**Comment by ValarDragon** [comment]
Sorry I know I was advocating for doing this prelaunch earlier, but if we want to just adopt a standard for private key storage, then I think it makes sense to upgrade to the standard all at once postlaunch.

**Comment by marbar3778** [comment]
@ValarDragon is this applicable in tendermint? Seems to be SDK related?

Note: they are absorbing the keys from tendermint used in the SDK.

**Comment by ValarDragon** [comment]
You're right, its SDK related! And also obsolete with the usage of builtin key management.

(Used to be relevant in tendermint as we'd provide the crypto primitive here)
