### ISSUE TITLE
crypto: completely remove dependency on amino for signatures

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1957]
Ref https://github.com/tendermint/go-crypto/issues/125, https://github.com/tendermint/go-crypto/issues/121

The reason we should upgrade: ~Currently the amino coding is path dependent (hence things broke when we switched the repo), this is bad.~ We don't want to use amino / protobuf, since that is less space efficient and upgradability doesn't make sense here. Most cryptosystems define canonical encoding formats anyway. Upgradability doesn't matter here, since if there is something that changes how the pubkeys are internally encoding, that means the respective crypto libraries need to be updated. For systems with security parameters, either their are already publically agreed upon parameters (i.e. elliptic curves), so changing those requires a new key type, or they are included in the pubkey canonical encoding (i.e. RSA modulus size). If there is a critical change that needs to upgrade the encoding format, I argue that it should have a different enum type, rather than using the existing enum type. 

My proposal for how we should do pubkey encoding:

We make an enum for pubkey types. (value being a uint). We use var uint encoding, and we marshal / unmarshal these pubkeys as 
`varuint(PUBKEY_TYPE_CONSTANT) || canonical pubkey encoding`
We also include the pubkey type constant when hashing to get addresses. 

Signatures can be encoded as raw byteslices, and be parsed by their respective pubkey. (This means removing the Signature struct / interface)

Privkeys can be encoded in the native format. Since the privkeys satisfy interfaces, this can later accommodate future caching for efficiency purports. 

/cc @cwgoes , @Liamsi

**Comment by Liamsi** [comment]
Quick remark to:

>  Currently the amino coding is path dependent (hence things broke when we switched the repo), this is bad.

How so? The prefix bytes are derived by the registered name (not the path of the struct in question). See RegisterConcrete / RegisterInterface in codec.go. 

That said, I'm generally in favour of moving to standard encoding formats for keys (not for sending them around but for actually storing them).

> Privkeys can be encoded in the native format. 

What is the native format here?

**Comment by ValarDragon** [comment]
> How so? The prefix bytes are derived by the registered name (not the path of the struct in question). See RegisterConcrete / RegisterInterface in codec.go.

Oh, my bad. I thought it was caused by the interface locations changing. You're right then. 

> What is the native format here?

I meant the canonical format as defined by the cryptosystem / agreed upon by implementers. That should be documented on a per cryptosystem basis. You're right though, we need to go from the set of bytes into the exact privkey type. I think using the same pubkey enum type would be fine. I'm not too worried about privkey encoding standardization though, so I'm not that opposed to amino being used there. (Ideally would like to use something as close to the cryptosystems canonical encoding as possible)

**Comment by ValarDragon** [comment]
Talked to Jae. 

We agreed on making Signatures marshalled how amino normally marshals `[]byte` (i.e. not an interface)

We concluded that using standard amino encoding for pubkeys is for the better. The space savings in state aren't that significant (3 bytes per key), and there are way more optimizations we can do in state that'll be more impactful then updating the pubkeys and breaking the easy compatibility. (i.e. not duplicating the address in accounts)

/cc @xla @ebuchman thoughts on making signatures an `[]byte` (not an interface)

**Comment by ValarDragon** [comment]
Relevant commit included in v23.0 release.
