### ISSUE TITLE
Change ed25519 and bcrypt to be forked off golang/x/crypto

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1959]
Ref: https://github.com/tendermint/go-crypto/issues/60

/cc @ebuchman

**Comment by ValarDragon** [comment]
I can see two ways of doing this. One is we fork the entire `x/crypto`, redo our changes, and see the upstream updates directly.

The other is we keep our current fork of ed25519 (agl's library, x/crypto is basically the same + 2 updates which I've already made PR's for). We also then fork bcrypt and maintain that as a repo. 

I think having the seperate ed25519 and bcrypt forks is fine. The issue we ran into with the tendermint repos is that we were developing actively on all of them at once. With ed25519/bcrypt, they should be extremely stable. (Any updates they have should not be breaking)

**Comment by ebuchman** [comment]
Why would we keep separate forks?

**Comment by ValarDragon** [comment]
We could have a single `x/crypto` fork, I'm not at all opposed to that.

**Comment by ebuchman** [comment]
Ok I made one: https://github.com/tendermint/crypto

It has the update for bcrypt and I updated  #2090 to use it. 

Also opened a fork of bip39 rather than copying it in. So #2090 has both pkgs removed :)

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/pull/2558
