### ISSUE TITLE
Error signing vote 

### ISSUE THREAD

**Issue by vizkits** [tendermint/tendermint#196]
Hi,

When running the dummy app, I got "Error signing vote" after connecting the peer nodes. Am I doing anything wrong? Appreciate your help!

Below is the log on the seed node:

ubuntu@ip-172-30-0-20:~/gocode/bin$ tendermint node
NOTE[03-13|02:01:49] Loaded PrivValidator                     module=types file=/home/ubuntu/.tendermint/priv_validator.json privValidator="PrivValidator{BF1948E0DFAB6E858465942D60115A3FC4F3B38A LH:330, LR:0, LS:3}"
NOTE[03-13|02:01:52] Added Listener(@172.30.0.20:46656)       module=node
NOTE[03-13|02:01:52] ConsensusReactor                         module=consensus fastSync=true
NOTE[03-13|02:01:52] Started node                             module=node nodeInfo="&{PubKey:PubKeyEd25519{85A67C77A997A163F6495374D3DB13EAB5BD368FAD2E2A2B407D811B578491A3} Moniker:anonymous Network:chain-p735et RemoteAddr: ListenAddr:172.30.0.20:46656 Version:0.6.0 Other:[wire_version=0.6.0 p2p_version=0.3.1 rpc_version=0.5.0/2 rpc_addr=0.0.0.0:46657]}"
NOTE[03-13|02:01:52] Starting RPC HTTP server on tcp socket 0.0.0.0:46657 module=rpcserver
NOTE[03-13|02:02:12] Peer handshake                           module=p2p peerNodeInfo="&{PubKey:PubKeyEd25519{684028E01EC591509219E22454EC6FF01C0CCD515FDA376607483CE2D2DCC0F0} Moniker:anonymous Network:chain-p735et RemoteAddr: ListenAddr:172.30.0.18:46656 Version:0.6.0 Other:[wire_version=0.6.0 p2p_version=0.3.1 rpc_version=0.5.0/2 rpc_addr=0.0.0.0:46657]}"
NOTE[03-13|02:02:12] Added peer                               module=p2p peer="Peer{MConn{172.30.0.18:38473} 684028E01EC5 in}"
NOTE[03-13|02:02:12] Receive                                  module=blockchain src="Peer{MConn{172.30.0.18:38473} 684028E01EC5 in}" chID=40 msg="[bcStatusResponseMessage 0]"
NOTE[03-13|02:02:12] IsCaughtUp: true                         module=blockchain height=1 maxPeerHeight=0
NOTE[03-13|02:02:12] Time to switch to consensus reactor!     module=blockchain height=1
NOTE[03-13|02:02:12] SwitchToConsensus                        module=consensus
NOTE[03-13|02:02:12] Ignoring updateToState()                 module=consensus newHeight=1 oldHeight=1
NOTE[03-13|02:02:12] enterNewRound(1/0). Current: 1/0/RoundStepNewHeight module=consensus
WARN[03-13|02:02:15] enterPrevote: ProposalBlock is nil       module=consensus
WARN[03-13|02:02:15] Error signing vote                       module=consensus height=1 round=0 vote="Vote{1/00/1(Prevote) 000000000000#PartSet{T:0 000000000000} /000000000000.../}" error="Height regression in SignVote"

**Comment by jaekwon** [comment]
Hi vizkits, the error message is "Height regression in SignVote".  It looks like you wiped the ~/.tendermint/data directory, while keeping around the ~/.tendermint/priv_validator.json file, which includes the last-signed height/round/step to prevent accidental double-signing.  Does that ring a bell?

**Comment by vizkits** [comment]
Thanks Jae for the prompt reply, that does explain why it worked after I re-generated new keys. So what is the proper way to reset/clear the blockchain after switching the app on each node? For example, I was running counter app, then I'd like to switch to my own app, do I need to clear all the blocks generated?

**Comment by jaekwon** [comment]
There's the `tendermint unsafe_reset_all` command.  It's undocumented but implemented.

**Comment by vizkits** [comment]
Thanks!
