### ISSUE TITLE
libs/common: RepeatTimer issues

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1976]
- [ ] non-deterministic test-failure (#1844)
- [ ] another test-failure (https://github.com/tendermint/tendermint/issues/2119)
- [ ] memory leak (#1867)
- [ ] race condition (#1868)

**Comment by melekes** [comment]
also https://github.com/tendermint/tendermint/pull/2073#issuecomment-408012300

**Comment by xla** [comment]
Also #2119

**Comment by ValarDragon** [comment]
This is probably related: https://github.com/golang/go/issues/26741

**Comment by marbar3778** [comment]
RepeatTimer was removed here: https://github.com/tendermint/tendermint/pull/3429, Closing issue
