### ISSUE TITLE
ABCI: ResponseCheckTx and ResponseDeliverTx expects single-coin Fee

### ISSUE THREAD

**Issue by AdityaSripal** [tendermint/tendermint#1997]
ABCI API Change Request:

Currently the ResponseCheckTx and ResponseDeliverTx structs both have a Fee attribute of type `common.KI64Pair`.  This assumes that a single coin is used for the transaction fee which is an assumption not shared by the Cosmos-SDK as seen in `StdFee` and `FeeCollectionKeeper` in x/auth module which expects `sdk.Coins` for the FeeAmount.

Changing the Fee attribute in the ABCI response to `[]common.KI64Pair` will allow the response and the corresponding sdk.Result to represent multicoin fees. This will make the ABCI more extensible and in-line with the cosmos SDK.

**Comment by AdityaSripal** [comment]
From discussion with @sunnya97:

Rather than include anything about FeeCoins into the response, we create a `Priority` uint that could be used in the future to order transactions from mempool

It's upto the application to calculate the Priority

**Comment by ebuchman** [comment]
Yeh! Closing for https://github.com/tendermint/tendermint/issues/1861
