### ISSUE TITLE
crypto: keys generated from ed25519 generate have insufficient security

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1999]
Currently the ed25519 `Generate` code for deterministic key generation is the following: 
```
func (privKey PrivKeyEd25519) Generate(index int) PrivKeyEd25519 {
	bz := cdc.MustMarshalBinaryBare(struct {
		PrivKey [64]byte
		Index   int
	}{privKey, index})
	newBytes := crypto.Sha256(bz)
	newKey := new([64]byte)
	copy(newKey[:32], newBytes)
	return PrivKeyEd25519(*newKey)
}
```

Its not clear if this is our own custom scheme. It seems weird to me that the last 32 bytes of the produced new private key are nil. These last 32 bytes are definitely used within signing, and knowing that these are null bytes makes signature forgery significantly easier. (the `r` term in the ed25519 equation would be public) Haven't ran through the equation yet, but it appears to me that this definitely enables signature forgery.

cc @Liamsi

**Comment by ValarDragon** [comment]
Just confirmed, this does indeed enable a trivial signature forgery attack.

**Comment by ValarDragon** [comment]
I believe this enables a private key recovery attack after a single signature.

**Comment by ebuchman** [comment]
Last 32 bytes are supposed to be the pubkey.

**Comment by ValarDragon** [comment]
EDIT to original post: This wouldn't enable attacks after a single signature, I forgot that eddsa hashes your private key before doing anything with it. That being said, this does halve the security going into the hash function.

> Last 32 bytes are supposed to be the pubkey.

This doesn't make sense to me. The public key is public, therefore the last 32 bytes could easily be derived from the first 32 bytes / the original public key.
