### ISSUE TITLE
Enable tendermint p2p port to be run behind LB

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#2007]
## Summary
Currently it is not possible to load balance the RPC Port (`26656`)

## Problem Definition
This is good for 2 usecases:
- Validators running sentry nodes
- Large deployments wanting to provide a small number of endpoints

## Proposal
Change the p2p layer so that, with some configuration, you can run the process behind a load balancer.

There are a couple of old issues (#865, #869) that sound like they might contain parts of this discussion.

cc @greg-szabo

**Comment by jackzampolin** [comment]
I think this forum post also contains some information related to the issue

**Comment by srmo** [comment]
This isn’t RPC, but the p2p con, or did i misread it?

**Comment by xla** [comment]
Can we close this in favour of #1521?

**Comment by jackzampolin** [comment]
Yes @xla Thank you for finding the right one!

**Comment by jackzampolin** [comment]
closing in favor of #1521
