### ISSUE TITLE
consensus: BFT time

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2013]
Replaces previous issue #1146. See extensive discussion there.

A previous PR (#1615) implemented a proposer based time that would change Tendermint's liveness guarantees. Instead, we should revert to the original design of using the median from timestamps in precommits. The downside is that timestamps in precommits means we can't aggregate signatures, but we can reassess when we're ready for signature aggregation (sometime in 2019).

There is a [spec](https://github.com/tendermint/tendermint/blob/develop/docs/spec/consensus/bft-time.md).

We should consider recovering some of the changes from #1615 
- various comment fixes
- time.Now().Round(0).UTC() for all calls to time
- Use  time.RFC3339Nano (https://github.com/tendermint/tendermint/issues/2037)

**Comment by ebuchman** [comment]
As part of this we also need to make sure we make consistent use of time across the codebase and always encode it the same way. Closing https://github.com/tendermint/tendermint/issues/1857 for this

**Comment by zmanian** [comment]
@tarcieri suggests looking at Hybrid Logical Clocks.
https://cse.buffalo.edu/tech-reports/2014-04.pdf

**Comment by tarcieri** [comment]
There's a Go implementation of Hybrid Logical Clocks here:
https://github.com/cockroachdb/cockroach/tree/master/pkg/util/hlc

**Comment by ebuchman** [comment]
@tarcieri do you think this is something we need to worry about for launch? For now we just use an `iota` parameter to ensure out votes come "after" the block time (ie. https://github.com/tendermint/tendermint/pull/2203/files/#diff-3baf47c64847a8fb8aaa8cc2e088513bR518). If our node is behind, it's our responsibility as the operator to fix its clock. 

I'll close this, but feel free to continue here or in the follow up issue #2309

**Comment by tarcieri** [comment]
@ebuchman not for launch, but I think it's a neat idea in general
