### ISSUE TITLE
Additional empty blocks creation during initChain and posting tx

### ISSUE THREAD

**Issue by PradeepSalanki** [tendermint/tendermint#2020]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.22.4

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
private ABCI app

**Environment**:
- **OS** (e.g. from /etc/os-release):macOS High Sierra v10.13.6 (17G65)
- **Install tools**:
- **Others**:

**What happened**:
The initChain process is creating blocks of height 2 and any further transactions done with the tendermint rpc endpoint creates 3 blocks.

**What you expected to happen**:
The init should create block of height 1 and any tx should create one block (depending on the number of txs being processed via delivertx).

**How to reproduce it** (as minimally and precisely as possible):

**Logs (you can paste a small part showing an error or link a pastebin, gist, etc. containing more of the log file)**:
<img width="815" alt="init block 1" src="https://user-images.githubusercontent.com/6400446/43007075-96739ef4-8c37-11e8-9e3c-ad09e85b3cbf.png">
<img width="817" alt="init block 2" src="https://user-images.githubusercontent.com/6400446/43007074-963dae66-8c37-11e8-992c-675e83c792f1.png">
<img width="817" alt="transaction block 1" src="https://user-images.githubusercontent.com/6400446/43007073-960a2e60-8c37-11e8-8cb1-8af8c372cb0d.png">
<img width="815" alt="transaction block 2" src="https://user-images.githubusercontent.com/6400446/43007072-95ddc898-8c37-11e8-8832-3cc013d1f7f6.png">
<img width="814" alt="transaction block 3" src="https://user-images.githubusercontent.com/6400446/43007071-95b193ea-8c37-11e8-96cb-0f2adf6f5ee8.png">

**Config (you can paste only the changes you've made)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:
Is there a documentation I can refer to why additional beginBlock are being requested and how to handle that.

**Comment by srmo** [comment]
Can we please stop adding logs as screenshots?

To your question: are you using create_empty_blocks=false?

**Comment by PradeepSalanki** [comment]
Yep will provide a link next time and yes I am using create_empty_blocks=false.

**Comment by srmo** [comment]
Ok, than this should be expected behavior. For every block containing a transaction, and if there are no more transactions to process, tendermint will create an empty block.
This is done to verify the appStateHash, as the Appstate for height N is persisted in a block at height N+1. At this stage, the logic will compare the appState of block N with the appState of the new empty block N+1, if they are the same, tendermint will stop producing empty blocks.

So if you see multiple empty blocks built, although you have `create_empty_blocks=false` and the interval at 0, if you change your appstate on empty blocks, tendermint will continue to build empty blocks. Sadly, I can't copypasta from your screenshots :P

**Comment by srmo** [comment]
EDIT: I deleted my previous comment as it was just plain wrong. Yes, you are right. The observed behavior should not happen in your case. AppHash for height 1 + 2 are the same, but both are empty. So protocol dictates that no additional empty block should have been created.

Please poste your config.toml

**Comment by melekes** [comment]
The first block is a genesis block. The second one is what we call a proof block. It's created so the genesis app hash is signed right away.

Note, there can be another reason to create a proof block (app hash change) https://github.com/tendermint/tendermint/issues/1788#issuecomment-399567101

https://github.com/tendermint/tendermint/blob/94e8252607997df7494000a91d621b221763d2d3/consensus/state.go#L758-L767
