### ISSUE TITLE
crypto: proposal for how to handle need for symmetric cryptography

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2023]
### Context
We need a symmetric cipher to handle how we encrypt keys in the sdk. (And potentially other things in tendermint, ref #1821)

Currently we use xsalsa20poly1305 (an AEAD), and just read random nonces to produce a symmetric cipher. I think this is a good way to do it for what we're doing. 

### Proposal
We should have an interface in the root crypto module, called symmetric, which has the following methods:
```
type Symmetric interface {
	Encrypt(plaintext []byte) (ciphertext []byte, err error)
	Decrypt(ciphertext []byte) (plaintext []byte, err error)
}
```

Then we should make a single module, "symmetric". It should have a struct which implements the symmetric interface from a given AEAD. (By creating the nonce randomly from OS randomness)

Then we can just use the nacl/secretbox directly as an AEAD and pass that into said symmetric struct. (There would be helper methods and stuff to make the API easier)

If this sounds good, or if it would be easier to comment on an implementation, I can go ahead and implement it. (Shouldn't take long) 

/cc @Liamsi

**Comment by yutianwu** [comment]
hi, @ValarDragon , do you have any plan to implement this feature, because we are working on encrypt private key file and it is very important for us. I have not decided how to do that yet but I think I will use a AEAD like applied in ethereum. 

Here is my issue, https://github.com/tendermint/tendermint/issues/2657, do you have any suggestions?

**Comment by creachadair** [comment]
@ValarDragon Is this issue still relevant? The `xsalsa20poly1305` package has been unused for some time, and gone since #7691), and I don't see any obvious dependencies on symmetric ciphers in the existing codebase.

**Comment by ValarDragon** [comment]
Yeah I think we can close this
