### ISSUE TITLE
dep: Allow a set of versions for cobra and viper

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2025]
Would it make sense to change cobra and vipers entries in the toml to be ranges of versions, instead of specific versions? This would it make it easier to use those libraries in downstream applications. (As currently importing tendermint locks you to using that specific version)

This would look like changing 
```
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "=0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
version = "=1.0.0"
```
to be 
```
[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1-0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
version = "1.0.0-1.0.2"
```

I definitely understand the desire to pin to exact versions for stability, but I wonder for libraries like these, if its worth the trade-off of limiting the downstream users.

**Comment by melekes** [comment]
I am in favor of doing this.

**Comment by ebuchman** [comment]
Yikes. Will this pin us to the latest in the range? What's the issue for downstream users, they have to `[override]` ?

**Comment by ValarDragon** [comment]
Yes, using a range will by default pin us to the latest in the range. (Note develop is now using this version anyways)

Downstream users would have to use an override, however its not clear that they can. The dep guide heavily cautions against overrides, and it seems like an anti-pattern. If using an override here were okay, why would we expect the end user to figure that out, rather than just support that version here.

**Comment by marbar3778** [comment]
Doesn't seem this is relevant anymore as go.mod is being used. @melekes can we close this issue?

**Comment by melekes** [comment]
Yep, thanks @marbar3778 👍
