### ISSUE TITLE
Create blockchain-reactor ADR to address several raised concerns 

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2026]
There have been several concerns and suggestion for improvement of blockchain reactor:
- comments in https://github.com/tendermint/tendermint/pull/1805
- https://github.com/tendermint/tendermint/issues/766
- https://github.com/tendermint/tendermint/issues/1734

**Comment by marbar3778** [comment]
I believe this has been addressed in ADR-040 & ADR-043, will close,
