### ISSUE TITLE
speed up some tests

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2038]
Selection of some of the longer tests:

```
ok      github.com/tendermint/tendermint/abci/example   5.116s
ok      github.com/tendermint/tendermint/consensus      10.331s
ok      github.com/tendermint/tendermint/libs/clist     15.246s
ok      github.com/tendermint/tendermint/libs/common    4.877s
ok      github.com/tendermint/tendermint/lite/client    5.579s
ok      github.com/tendermint/tendermint/p2p/conn       11.065s
ok      github.com/tendermint/tendermint/p2p/pex        9.321s
ok      github.com/tendermint/tendermint/rpc/lib        8.039s
ok      github.com/tendermint/tendermint/rpc/lib/client 8.579s
```

**Comment by ValarDragon** [comment]
If all of the things which these tests are testing is important (I haven't checked myself) we could do one of the following:

Use an integration test flag (https://github.com/cosmos/cosmos-sdk/issues/1665) 

Split these tests up in circle.

**Comment by ValarDragon** [comment]
For `libs/common` it appears that the cause for it taking two seconds is that the following tests wait for a second to complete:
```
--- PASS: TestParallelAbort (1.00s)
--- PASS: TestRepeatTimer (1.00s)
--- PASS: TestRepeatTimerReset (1.89s)
```
Whether that time needs to be spent there is worthy of investigation.

**Comment by marbar3778** [comment]
@melekes @ebuchman do you guys still want the tests faster? I see this was merged https://github.com/tendermint/tendermint/pull/2154. If so, can we close this issue?

**Comment by ebuchman** [comment]
Sure we can always come back if its a problem.
