### ISSUE TITLE
p2p: Peers listed as private_peer_ids should always be able to connect ahead of unlisted peers when connection slots are saturated

### ISSUE THREAD

**Issue by joe-bowman** [tendermint/tendermint#2041]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Tendermint version** 0.22.2

**ABCI app** gaiad 0.22.0

**Environment**:
- **OS** Ubuntu 18.04
- **Install tools**:
- **Others**:

A sentry `A` with `max_num_peers` set to an arbitrary value `x` (default in gaiad 0.22.0 was 50), and specifying a single host `B` in `private_peer_ids` (and reciprocally `B` specifies `A` in `persistent_peers`), `x` connection slots on host `A` can be saturated by external/public peers, at which point connection attempts from B are rejected.

Possibly solutions could be that peers listed under `private_peer_ids` should either be treated with a higher weight than unlisted connections, or have reserved slots.

## Steps to Reproduce
In our case, both `A` and `B` are running since block 0; but B is currently 2000 (at  block_height of c9000) blocks behind. Logs specify lots of connection attempts from `B` to `A`, but connections are rejected.

Workaround is to set `max_num_peers` arbitrarily high, but this is not scalable (peering with every node in the network to ensure that you can talk to your neighbour is far from optimal!)

(Moved from https://github.com/cosmos/cosmos-sdk/issues/1737)

**Comment by xla** [comment]
Candidate for #2067

**Comment by melekes** [comment]
We added `unconditional_peer_ids` to combat this not so long ago. See ADR-50 and [the associated PR](https://github.com/tendermint/tendermint/pull/4176).
