### ISSUE TITLE
p2p: process handshakes asynchronously

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2047]
Reported by an auditor.

New connections are currently accepted synchronously, so any new connection must wait until the last one is setup before it can start. This may allow an attacker to prevent a node from acquiring new peers.

We should also check and reject connections from duplicate IPs right away, rather than waiting for after the handshake.

**Comment by ValarDragon** [comment]
Is this an issue with synchronicity, or that the connection setups aren't processed in parallel?

**Comment by ebuchman** [comment]
> Is this an issue with synchronicity, or that the connection setups aren't processed in parallel?

We should process the connections in parallel.

> Also what does rejecting a duplicate IP right away mean precisely.

It means right after we accept a connection from the listener, we should check the remote IP on it so we don't bother doing the handshake if its the same as a peer we already have. Note we won't have an ID yet because we won't yet have done the authenc handshake.

**Comment by xla** [comment]
#2006 is now #2067

**Comment by ebuchman** [comment]
Fixed!
