### ISSUE TITLE
consensus: peer can be marked good after a single message

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2048]
Reported by an auditor.

PeerState.Stats are used to track how many votes/blockparts for a unique height a peer has given us. When they hit 10k, we mark the peer as "good" and preferentially connect to it.

We initialize PeerState.Stats with zeros, and then only update if the Height of the vote/blockpart is higher than the latest:  https://github.com/tendermint/tendermint/blob/05a76fb517f50da27b4bfcdc7b4cf185fc61eff6/consensus/reactor.go#L1089-L1095

Problem is we don't validate that votes/parts contain non-negative values for height. If the first msg from a peer is a vote with negative height, we'll return the  latest value, which is 0. But when we check the return value, we check `% 10000 == 0`, which passes for 0, so we mark the peer good right away!

Note we want to use `%` and not `>` because peers can become "ungood" probabilistically if there's lots of good peers and they should have a chance to keep proving themselves. Alternatively we could use `> 10000` and just reset the counter to 0 every time a peer is marked good.

Main thing we need to fix is validating the reactor messages so we don't have negative numbers. But we should also make sure the logic is more defensive, like a modulus guarding a "marked good" should be smarter about accidentally being triggered right away.

**Comment by ValarDragon** [comment]
I don't understand why we don't validate that its a valid vote (i.e. for an existing validator), or a valid block part before improving the peers score.
`Alternatively we could use > 10000 and just reset the counter to 0 every time a peer is marked good.`
This sounds good to me. I don't like the idea that the amount you have to "reprove" yourself isn't strictly correlated to your overall "score" if you were previously proven. Removing the periodicity here seems like a good first step in that regard!

**Comment by ebuchman** [comment]
> I don't understand why we don't validate that its a valid vote (i.e. for an existing validator), or a valid block part before improving the peers score.

Uh, that's a very fine point. Looks like the current code is all kinds of broken. Not only do we need to verify that it's valid, but that's its unique information we haven't already seen. That's supposed to be the point of the mechanism (according to the spec). We'll need the `RecordXxx` to be called from within the ConsensusState, where the info is actually validated and added to the vote set or part set.

**Comment by ValarDragon** [comment]
> @xla and I were discussing some improvements to the ConsensusState that would involve splitting out the piece that collects votes and parts into something like a ConsensusExecutor so that the ConsensusState can more directly reflect the formal spec. Calling RecordXxx would then happen in the ConsensusExecutor

This sounds like a great idea to me! This seems like a good way to split up the logic. I suppose this should first be written up into an ADR?

**Comment by milosevic** [comment]
> I'd recommend being careful about boundaries between software components (consensus state shouldn't know what address book is).

Fully agree here @melekes . That's why I wanted to open the discussion in PR. Even passing Peer feels wrong as consensus state doesn't care about Peer and probably shouldn't have possibility to directly send messages.

**Comment by xla** [comment]
> This sounds like a great idea to me! This seems like a good way to split up the logic. I suppose this should first be written up into an ADR?

Dropped the ball on this, it's coming.

**Comment by ebuchman** [comment]
Simple proposal: https://github.com/tendermint/tendermint/pull/2388#discussion_r217420113

Ie. open a new channel between reactor/state just for the state to communicate successful unique adds of parts and votes. reactor has a new routine to read off this channel and update the peer states

**Comment by ebuchman** [comment]
Fixed in #2388
