### ISSUE TITLE
tx_search doesn't seem to respect "tx.height>21"

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#2051]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG_REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

v0.21.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

I had indexing on, and can search for matches on custom keys, but when I search for an obvious hit like "tx.height>21" or "tx.height<500000", it returns no matches. This also happens when I combine this with a tx tag search that returned a result without the tx.height range condition.

**What you expected to happen**:

I expected tx.height less than and greater than to return valid matches. This did work in an earlier version of tendermint. I am pretty sure it worked in 0.17. I don't know if I tested this since 0.19, so I am not sure where regression.

**How to reproduce it** (as minimally and precisely as possible):

Use a height range in tx_search.

**Logs (you can paste a small part showing an error or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:

Looked at https://github.com/tendermint/tendermint/blob/dfa9a9a30a666132425b29454e90a472aa579a48/state/txindex/kv/kv.go#L156-L177 and a brief look at the code seemed to show it only handling tx.height= not < or > operators, which I am sure were intended design at one point.

**Comment by ethanfrey** [comment]
Okay, here is a simple way to reproduce:


Server setup:
```
$ tendermint version
0.23.0-013b9cef
$ mkdir ~/tmsearch
$ tendermint --home ~/tmsearch/ init
$ TM_TX_INDEX_INDEX_ALL_TAGS=true tendermint node --home ~/tmsearch --proxy_app=kvstore --log_level=state:info,rpc:info,*:error
```

Client:

Query on tag returns. expected result 
Query on height return nothing (exact match or range).
Query with tag and height returns 400... ???
```
$ curl http://localhost:26657/broadcasttx_commit?tx=\"foo\"
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "check_tx": {},
    "deliver_tx": {
      "tags": [
        {
          "key": "YXBwLmNyZWF0b3I=",
          "value": "amFl"
        },
        {
          "key": "YXBwLmtleQ==",
          "value": "Zm9v"
        }
      ]
    },
    "hash": "2C26B46B68FFC68FF99B453C1D30413413422D70",
    "height": "98"
  }
}

$ curl "http://localhost:26657/tx_search?query=\"app.creator='jae'\""
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "txs": [
      {
        "hash": "2C26B46B68FFC68FF99B453C1D30413413422D70",
        "height": "98",
        "index": 0,
        "tx_result": {
          "tags": [
            {
              "key": "YXBwLmNyZWF0b3I=",
              "value": "amFl"
            },
            {
              "key": "YXBwLmtleQ==",
              "value": "Zm9v"
            }
          ]
        },
        "tx": "Zm9v"
      }
    ],
    "total_count": "1"
  }
}

$ curl "http://localhost:26657/tx_search?query=\"tx.height>20\""
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "txs": [],
    "total_count": "0"
  }
}

$ curl "http://localhost:26657/tx_search?query=\"tx.height=98\""
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "txs": [],
    "total_count": "0"
  }
}

$ curl "http://localhost:26657/tx_search?query=\"app.creator='jae' AND tx.height>20\""

400 Bad Request
```

**Comment by ethanfrey** [comment]
@melekes 
Does cosmos voyager not also make use of this functionality?
If there is another way to get the history, especially to query for updates since last time online, please share it with me and I will use that instead.

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/2324.
