### ISSUE TITLE
v0.22.5 is broken due to amino v0.11.1  

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2053]
v0.22.5 doesn't work (ie. `tendermint init && tendermint node --proxy_app=dummy` will panic immediately.

It seems to be due to the upgrade from v0.10.1 to v0.11.1 of amino.

**Comment by ValarDragon** [comment]
These amino errors showed up in my secret connection PR basically all tests failed, until I downgraded to 0.10.1. So I guess circle did catch these on new PR's?

**Comment by ebuchman** [comment]
So, it turns out I was using `dep ensure` rather than `make get_vendor_deps`. Using the latter, it actually works, the difference being the latter doesnt update Gopkg.lock, just uses the existing one. But I don't understand why amino v0.11.1 works if we do `make get_vendor_deps` but only v0.10.1 if we do `dep ensure` !

**Comment by ebuchman** [comment]
So it turns out this is only half true. Using `make get_vendor_deps`, it works fine. The problem is the toml updated for v0.11, but the lock file didn't, and the make command ignores the toml.

**Comment by ebuchman** [comment]
Not a real issue for folks using `make get_vendor_deps` and fixed in #2056 anyways

**Comment by ebuchman** [comment]
Tagging @Liamsi @jaekwon to take note that apparently some work will be required to upgrade Tendermint to Amino v0.11
