### ISSUE TITLE
During a stress, the height on a non-validator freezes, lags behind the validator's, before catching up

### ISSUE THREAD

**Issue by maxim-levy** [tendermint/tendermint#2057]
**BUG REPORT**

**Tendermint version**
`0.22.4-c64a3c74`

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
`kvstore`

**Environment**:
- **OS** (from /etc/os-release): `Amazon Linux AMI, 2018.03, rhel fedora`
- **Platform**: each node runs on an `m4.4xlarge` instance, AWS
- **Topology**: 1-validator, 1-non-validator, 1-bench
- **Others**:

**What happened**:
Initially the consensus nodes run with no load. These progress in parallel (`create_empty_blocks = true`), one can see (using the `tm-monitor`) that the height is in-sync and the block time is just around 1000ms. Then something strange happens when on a separate host I run `tm-bench` towards the validator (using the default parameters) for 30 seconds. The height on the non-validator node stops increasing and stays constant  till approximately 20 seconds after the end of the stress. Then the hight on the non-validator node grows rapidly till it catches up with the validator. See a screen recording [here](https://youtu.be/2JPWnPJbFUc).

**What you expected to happen**:
The most of the time the nodes stay on almost the same height.

**How to reproduce it** (as minimally and precisely as possible):
Just use a trivial network described.

**Logs**: `consensus:debug,*:error `
 * validator: https://gist.github.com/maxim-levy/2d241647d36b13fa45ec01243f7e28cd
 * non-validator: https://gist.github.com/maxim-levy/9d40495fd59f02b22d103421d5245b7d
 
**Config (you can paste only the changes you've made)**:
no changes were made, the config was generated by 
`docker run tendermint/tendermint testnet --v 1 --n 1 --o myTmHome --starting-ip-address 10.0.0.10`

**`/dump_consensus_state` output for consensus bugs**: the dump is after the phenomena occured
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "round_state": {
      "height": "3571",
      "round": "0",
      "step": 1,
      "start_time": "2018-07-25T06:14:29.751789257Z",
      "commit_time": "2018-07-25T06:14:28.751789257Z",
      "validators": {
        "validators": [
          {
            "address": "80E896E05A3539458BDCC329CA4C74F2EFE744FA",
            "pub_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "tlW/Zvub4t3XuTbyROnXi1J3csITCyzto2lm1tvA5aE="
            },
            "voting_power": "1",
            "accum": "0"
          }
        ],
        "proposer": {
          "address": "80E896E05A3539458BDCC329CA4C74F2EFE744FA",
          "pub_key": {
            "type": "tendermint/PubKeyEd25519",
            "value": "tlW/Zvub4t3XuTbyROnXi1J3csITCyzto2lm1tvA5aE="
          },
          "voting_power": "1",
          "accum": "0"
        }
      },
      "proposal": null,
      "proposal_block": null,
      "proposal_block_parts": null,
      "locked_round": "0",
      "locked_block": null,
      "locked_block_parts": null,
      "valid_round": "0",
      "valid_block": null,
      "valid_block_parts": null,
      "votes": [
        {
          "round": "0",
          "prevotes": [
            "nil-Vote"
          ],
          "prevotes_bit_array": "BA{1:_} 0/1 = 0.00",
          "precommits": [
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{1:_} 0/1 = 0.00"
        }
      ],
      "commit_round": "-1",
      "last_commit": {
        "votes": [
          "Vote{0:80E896E05A35 3570/00/2(Precommit) 9D9526C242A6 /8B468EBAFFA0.../ @ 2018-07-25T06:14:28.747Z}"
        ],
        "votes_bit_array": "BA{1:x} 1/1 = 1.00",
        "peer_maj_23s": {}
      },
      "last_validators": {
        "validators": [
          {
            "address": "80E896E05A3539458BDCC329CA4C74F2EFE744FA",
            "pub_key": {
              "type": "tendermint/PubKeyEd25519",
              "value": "tlW/Zvub4t3XuTbyROnXi1J3csITCyzto2lm1tvA5aE="
            },
            "voting_power": "1",
            "accum": "0"
          }
        ],
        "proposer": {
          "address": "80E896E05A3539458BDCC329CA4C74F2EFE744FA",
          "pub_key": {
            "type": "tendermint/PubKeyEd25519",
            "value": "tlW/Zvub4t3XuTbyROnXi1J3csITCyzto2lm1tvA5aE="
          },
          "voting_power": "1",
          "accum": "0"
        }
      }
    },
    "peers": [
      {
        "node_address": "500d4f1c5087a0dd55cbad839a629ee859c979a0@10.0.0.11:26656",
        "peer_state": {
          "round_state": {
            "height": "3570",
            "round": "0",
            "step": 8,
            "start_time": "2018-07-25T06:14:28.939145815Z",
            "proposal": false,
            "proposal_block_parts_header": {
              "total": "1",
              "hash": "CDAFCBEE986747C02B555D4E790A748B237A084B"
            },
            "proposal_block_parts": "_",
            "proposal_pol_round": "-1",
            "proposal_pol": "_",
            "prevotes": "_",
            "precommits": "x",
            "last_commit_round": "0",
            "last_commit": "x",
            "catchup_commit_round": "0",
            "catchup_commit": "x"
          },
          "stats": {
            "last_vote_height": "3548",
            "votes": "177",
            "last_block_part_height": "0",
            "block_parts": "0"
          }
        }
      }
    ]
  }
}

```
**Anything else do we need to know**:
Seems to be related to #1920

**Comment by maxim-levy** [comment]
The blocks till 135 have no data, then on the non-validator side one sees `Received block part from wrong height` starting from block-135. Is that suspicious?

**Comment by melekes** [comment]
```
rg "Received block part from wrong height" non-validator.log | wc -l
     238
```

That's a lot of parts from an earlier height(s). Given we send a block part only once? we shouldn't see such messages.

**Comment by maxim-levy** [comment]
it appears that `cs.Height` is `height+1`

**Comment by maxim-levy** [comment]
The problem seems to be related to some stale configuration files - can't reproduce it anymore...
