### ISSUE TITLE
p2p connect error

### ISSUE THREAD

**Issue by wangxiangjun88** [tendermint/tendermint#2062]
I deployed tendermint node on k8s ,4 validator node with extranet address.when i run these 4 nodes ,something with wrong.it report that " read: connection reset by peer" like this .who can tell me what i shoud do ? thank you!!

2018-07-25 10:17:35,568 DEBG 'tendermint' stdout output:

```
  | I[07-25\|10:17:35.568] Ignoring inbound connection: error while adding peer module=p2p address=10.129.0.1:41586 err="Error{read tcp 10.130.1.5:26656->10.129.0.1:41586: read: connection reset by peer}"
  |  
  | 2018-07-25 10:17:35,724 DEBG 'tendermint' stdout output:
  | I[07-25\|10:17:35.723] Ignoring inbound connection: error while adding peer module=p2p address=10.130.0.1:4642 err="Error{read tcp 10.130.1.5:26656->10.130.0.1:4642: read: connection reset by peer}"
```

**Comment by melekes** [comment]
Could you provide more than 2 lines of logs?

**Comment by xla** [comment]
@wangxiangjun88 Thanks for bringing this up, but the issues are not the right forum for this kind of report. Please use the riot channel or stackoverflow to clarify setup questions/problems.

**Comment by wangxiangjun88** [comment]
@melekes 
![menu saveimg savepath20180726091656](https://user-images.githubusercontent.com/24696061/43235924-db1e1efe-90b4-11e8-8444-2a91fc63a938.jpg)
all logs are same.
these 4 nodes are all pod and they all have externnet address. pod ip is local net address.

**Comment by ebuchman** [comment]
You may need to set `addr_book_strict=false`
