### ISSUE TITLE
P2P Refactor

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#2067]
In its current implementation the separation of concerns betweeen different components (AddrBook, Peer, PEX, Switch) is not solid, for reference see #1325, #1356. This comes at no surprise as this is one of the oldest packages in the codebase with almost 4 years of history. Over time different requirements have been tried to fit in and the scope of the package expanded, especially given its center role in the entire codebase. Additionally, a range of potential security issues surfaced (#2046, #2047) through external audits which could be addressed with structural changes and better separation.

In here we track the progress of the P2P improvements and try to gather all relevant issues, designs and docs.

**Comment by ebuchman** [comment]
Some original thoughts about this in https://github.com/tendermint/tendermint/issues/1325.
Some of that has already been addressed, some is just pointers to take another look at the AddrBook and to clearing up the interplay between pex/seeds/persistent-peers/addrbook

**Comment by ebuchman** [comment]
Replacing #2046 by noting here that we need to be able to write better tests for that.

**Comment by ValarDragon** [comment]
We discussed to post potential future p2p improvements here as well. Here are some from the top of my head that are worth doing / considering.

* Use Noise for SecretConnection
* Send mempool txs in batches, and then use compression to mitigate the bandwidth. (The p2p change being adding compression for sufficiently large msgs)
* Change tx gossip algorithm https://github.com/tendermint/tendermint/issues/1798
* Enhance the peer scoring metrics
* Adapt block propagation to not send the block, just an ordered list of tx hashes, with optimistic sends of a few txs you think they may not have. Then have nodes request missing tx hashes from peers. (https://bitcoincore.org/en/2016/06/07/compact-blocks-faq/)
* Until we implement compact-blocks (which will be a while), compress block data before splitting into parts
* Use QUIC instead of TCP
* #Very postlaunch, consider modifying QUIC to not need message ordering. We'd have to switch from chacha to xchacha, but thats not a big deal.

**Comment by ValarDragon** [comment]
I had the chance to talk to @rargulati at SFBW. He gave some extremely helpful insight into switching to libp2p. One of the examples he gave was making our address book align with the libp2p peer store's addrbook interface. Then we could just switch that piece over quite easily in the future (https://github.com/libp2p/go-libp2p-peerstore). We could then switch over the peer-store in isolation.

He had also suggested that other than the peer store, libp2p still has some inter-dependencies between its other modules so it would probably be best to switch over everything else all at once. There are other interfaces we can align, to make the switch easier. Here is a tracking issue for some of the libp2p inter-dependencies: https://github.com/libp2p/go-libp2p/issues/445. He also recommended looking at how Ethereum is switching over in Whisper, to see how they're doing their upgrade.

/end conversation summarization

I now feel more convinced that switching to libp2p is a good idea. The QUIC support is being worked on, so if were using libp2p that should become much easier to integrate!

Looking through the peerstore godocs, https://godoc.org/github.com/libp2p/go-libp2p-peerstore, it has a few upsides, and a few properties which we'd need to assess if we can integrate their well or not. The upside is we get support for multiple protocols. This will probably be useful for the versioning we want, and also ipv4 / ipv6. It also has built-in support for some cool latency based metrics. The downside is that PeerInfo doesn't have built in support for arbitrary "score" metrics which we do want. (Though another question is do we really need a score for any peer that isn't persistent? What circumstances would one accidentally mess up here?) This can be built using `PeerMetadata`, or we could just fork that PeerInfo struct.

 We should investigate this peer store implementation more and the libp2p ecosystem. Its not clear to me how private peers are handled, but I'm certain they have a mechanism to deal with them. (just thats not part of the peerstore implementation)

**Comment by erikgrinaker** [comment]
We should improve auto-detection of advertised addresses, decouple it from the listen (bind) address, and filter advertisement of non-routable addresses (e.g. `192.168.0.0/16`) to peers on other networks. I wrote some initial thoughts on this here: https://github.com/tendermint/tendermint/pull/3516#issuecomment-587555940.

**Comment by erikgrinaker** [comment]
Submitted an ADR on the P2P refactor scope in #5592.

**Comment by zmanian** [comment]
If we do end switching out the p2p handshake, we should look using or forking the `lnd` brontide package as Noise implementation.

https://github.com/lightningnetwork/lnd/tree/c1c4b84757dd5b1e1fcb285b4a1fa6a56b35432c/brontide

**Comment by erikgrinaker** [comment]
Superseded by #5670.
