### ISSUE TITLE
Running my first TMSP application - 1:1 (0): no match found error on `append_tx abc`

### ISSUE THREAD

**Issue by stuartweir** [tendermint/tendermint#207]
Hey! I'm new here.

I was just trying to get up to speed with a bit of this, and checked out this link: http://tendermint.com/tutorials/run-your-first-tmsp-application/

Setup:
- MacBook Pro 2015
- Go 1.6

Process:
I started `dummy`, then ran `tmsp-cli console` in another window. Ran through the steps,
```> echo hello
> info
> commit
> append_tx abc
> info
> commit```

When I get to `append_tx abc`, I get this error: 
`1:1 (0): no match found`

In the `dummy` window, it shows this: 
```Accepted a new connection
Waiting for new connection...```

Did I miss a step? I feel like I did, but rereading through that link above makes me feel like I didn't. Anyway, thanks for your help!

-Stu

**Comment by jaekwon** [comment]
Hi Stu,

The linked tutorial is fixed.  It should be `append_tx "abc"` or `append_tx x001122`

**Comment by stuartweir** [comment]
Hi Jae,

Thanks, for updating the site! It worked :)
