### ISSUE TITLE
libs/flowrate: non-deterministic failure in tests 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2078]
libs/flowrate/io_test.go 

```
--- FAIL: TestReader (0.44s)
	io_test.go:93: r.Status(2)
		expected: {true 2018-07-26 22:51:45.84 +0000 UTC 200ms 100ms 20 2 100 100 100 100 0 0s 0.000%}
		got     : {true 2018-07-26 22:51:45.84 +0000 UTC 200ms 80ms 20 2 100 100 100 100 0 0s 0.000%}
	io_test.go:93: r.Status(3)
		expected: {true 2018-07-26 22:51:45.84 +0000 UTC 300ms 200ms 20 3 0 90 67 100 0 0s 0.000%}
		got     : {true 2018-07-26 22:51:45.84 +0000 UTC 300ms 180ms 20 3 0 90 67 100 0 0s 0.000%}
```

From https://circleci.com/gh/tendermint/tendermint/17342?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ValarDragon** [comment]
Got a different variation on the error here: https://circleci.com/gh/tendermint/tendermint/17656#tests/containers/1
```
=== RUN   TestReader
--- FAIL: TestReader (0.08s)
	io_test.go:67: r.Read(b[10:]) returned ahead of time (80.277029ms)
```

**Comment by ValarDragon** [comment]
Now I got one on TestWriter (https://circleci.com/gh/tendermint/tendermint/20100#tests/containers/2)
```
--- FAIL: TestWriter (0.48s)
	io_test.go:147: w.Status(1)
		expected: {true 2018-08-14 19:28:06.5 +0000 UTC 500ms 100ms 100 5 200 200 200 200 0 0s 100.000%}
		got     : {true 2018-08-14 19:28:06.5 +0000 UTC 500ms 80ms 100 5 200 200 200 200 0 0s 100.000%}
FAIL
```

**Comment by Liamsi** [comment]
Seen again in: https://circleci.com/gh/tendermint/tendermint/50585#tests/containers/2

**Comment by Liamsi** [comment]
Seen again on develop: https://circleci.com/gh/tendermint/tendermint/56022#tests/containers/2

**Comment by tessr** [comment]
Going to close this since we cleaned up a lot of non-deterministic tests; will reopen if we see it again.
