### ISSUE TITLE
Tendermint should fail gracefully when all validators are revoked

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#2084]
Version: Tendermint 0.22.8
ABCI app: Cosmos SDK / Gaia 0.23.1
Network type: one-validator local testnet
Config type: default config
Expected behavior: Tendermint halts and informs user that no validators are in the validator set
Observed behavior: Tendermint crashes with an interface conversion error

https://gist.github.com/cwgoes/bedbdf51845850ea456e656a5c68c164

**Comment by ebuchman** [comment]
Closing for #3224
