### ISSUE TITLE
Add a `use_seed` to tendermint start

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2086]
Currently if you have a persistent peer, you won't ping your seed nodes for peers. For sentries they should still ask the seed nodes for peers on their first startup, even if they already have a persistent peer. (For their validator connection)

 I think the easiest way to achieve this would be to add a `--use_seed` flag to the start command. The desired functionality would be that if use_seed is true, all known seed nodes are queried regardless of the status of addrbook.json.

**Comment by melekes** [comment]
I feel like if we keep adding these flags, we'll end up with a complex scheme nobody understands. Maybe we should consider adding single `--sentry` flag?

**Comment by ValarDragon** [comment]
That sounds better to me! 

I do feel like we can keep adding flags as well, as long we organize them very well (i.e. don't show them all on `tendermint help`, have separate sub-commands) But I don't think this command would warrant its own new flag. (Unless it was part of a `tendermint config` sub-command, whose sole purpose was to emulate changing the relevant variable in the config file)

**Comment by xla** [comment]
Another option is to break the operations of nodes up into distinct sub-commands, esp. with the advent of best-practices how to operate different node types we could encode that, e.g.:  `tendermint sentry`, `tendermint seed`, `tendermint validator`.

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/issues/2237
