### ISSUE TITLE
consensus: improve common_test.go setup

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2089]
Working on the evidence tests in https://github.com/tendermint/tendermint/pull/2088 required unrolling the setup functions so we could properly set the state and the evidence pool. 

These functions could be cleaned up and ideally the object graph for testing the consensus state / reactor made smaller.

Note we're overwriting the stateDB in `newConsensusStateWithConfigAndBlockStore`, which hasn't mattered because the consensus tests have not depended on the state. But to validate evidence you have to look up a validator set in the state, so we needed a proper stateDB in #2088 .

**Comment by marbar3778** [comment]
@tychoish and @cmwaters do you believe this can be closed. I know you two have been doing test refactors.

**Comment by cmwaters** [comment]
Consensus tests haven't really been touched. I'd sway to leaving this open
