### ISSUE TITLE
How does client know if a tx was committed or not?

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#209]
Presently the client will only know out outcome of CheckTx in the mempool and not the final state once included in a block. This is very useful information for the client to decide what further action (if any) is required.

Some initial discussion from slack:

mdyring [4:08 PM]
@jae is there any way to know if a tx is eventually accepted into a block? I think that would be very useful to know, considering that CheckTx can only provide an early rejection or "preliminary" accept. So I imagine the node that is asked to broadcast the tx via the RPC, can track the tx and let the client know once it is finally accepted or rejected in the commited block.
 
jae [4:33 PM] 
not yet.  shouldn’t be hard to implement though.  In state/execution.go, execBlockOnProxyApp needs to use evsw…
some questions though…. like, what about timeouts?  e.g. what should happen if a million requests aren’t getting committed?
  
jae [4:35 PM]
I suppose the listener needs to accept a “timeout”, but a timeout response does not imply that the tx won’t get committed later.
 
mdyring [4:35 PM] 
I imagine that a tx will be included in the current block, next one or not at all?

jae [4:35 PM] 
that’s not how the mempool is implemented… a tx will get broadcast to peers, and may eventually propagate

**Comment by tomtruitt** [comment]
Is this an issue still with BroadcastTX?

**Comment by ebuchman** [comment]
yes. will implement as rpc command `broadcast_tx_commit`. at that point I'll open another issue for how to do that with more flexibility (ie. some kind of receipt based model)

**Comment by ebuchman** [comment]
addressed in https://github.com/tendermint/tendermint/pull/233

follow https://github.com/tendermint/tendermint/issues/237 for alternative approach
