### ISSUE TITLE
p2p: start dialing peers sooner

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2093]
A new node with no peers will dial a seed and get a list of addresses, but then it seems to wait a while before it dials any of them. 

Would be much nicer if it knew to dial them right away

**Comment by ValarDragon** [comment]
Is it fine to do an O(N) scan through the seeds to check if the source address for your new peer is a seed node?

**Comment by xla** [comment]
@ValarDragon see comment in the PR.
