### ISSUE TITLE
TMSP handshake message

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#211]
To establish max tx size, max block size, etc.
May retrofit the Info message for this purpose.
Tmcore configuration is not sufficient esp if the app cannot handle large tx sizes.
Renegotiate upon app upgrade.

**Comment by mdyring** [comment]
As added bonus, if possible it would be nice to get some (static) info on the tendermint node in the handshake.

For instance, moniker or pubkeys for votes might be interesting for various tmsp applications. Moniker mainly for display purposes, but maybe the vote pubkey might be interesting for some use cases (maybe inside txs to prove that you can sign with one of the validator key, maybe to seed the application state).

**Comment by mdyring** [comment]
Could potentially be used for https://github.com/tendermint/tendermint/issues/227

**Comment by ebuchman** [comment]
Let's use Info message for the handshake.

Currently, RequestInfo has no fields. I wonder if there may be other times Tendermint will want to grab some app Info in a way that distinguishes it from the handshake or from using Query. Let's leave this for now.

The tmsp.ResponseInfo should include:

```
// last block processed
BlockHeight int
BlockHash []byte
AppHash []byte

// config info
MaxBlockSize // block size in bytes
MaxBlockSizeTx // block size in txs
MaxTxSize // tx size in bytes
```

Protocol:

- tendermint tmsp-client dials the app
- tendermint sends tmsp.RequestInfo
- app sends tmsp.ResponseInfo
- tendermint fetches the block from the blockStore, checks the block hash and app hash
- if tendermint doesn't have the block, or the hash/apphash don't match, send tmsp.RequestInfo a second time
- if it fails a second time, panic or exit  - this way we give the app a chance to fall back on something more conservative, or even to say "give me whatever you got"
- if tendermint has the block and the hashes check out, replay all later blocks.
- if the block height is 0 and the hash is empty, tendermint will replay everything

NOTE: the app may have processed an AppendTx for block H+1 but not finished committing the block. When restarted, it's block height will still be H and any AppendTx from H+1 will be replayed.

**Comment by jaekwon** [comment]
Cool.  But why would the app respond differently the second time?  An implicit convention?  Seems strange to break the deterministic state machine contract.

**Comment by ebuchman** [comment]
> Seems strange to break the deterministic state machine contract.

Is it breaking it? Calling Info once updates the internal state of the app so calling it a second time will give a different result.

**Comment by mdyring** [comment]
Silly question of the hour, I might not be @ bleeding edge of development: 
How does the app know the last blockhash? As far as I can tell, only height are sent in RequestBeginBlock and RequestEndBlock

**Comment by ebuchman** [comment]
Totally relevant question. This will depend on us actually passing the Header in the BeginBlock message
