### ISSUE TITLE
spec/BFT: Slashing for being wildly off median to discourage Byzantine behavior 

### ISSUE THREAD

**Issue by AdityaSripal** [tendermint/tendermint#2112]
I believe there needs to be slashing for being too far off the median. 

If there isn’t, then there is no disincentive for validators to just lie about the time if they think they can benefit from it. Normally with BFT systems, going against the consensus imposes economic cost. Thus, one must get 2/3 (in PoS) to coordinate for individual byzantine behavior to be economically profitable. If there is no disincentive to lying about time for one’s own benefit, then individual validators can shift their personal time for their own benefit (maybe speeding up their time till spends are enabled for example) without any downside. It's true that shifting personal time doesn't affect anything unless enough people do it because we are using median. However, there is no downside for an individual to start this attack on their own and try to convince other validators to eventually join in as well. If enough validators decide to do this on their own, then the time can be manipulated by these validators without any concerted coordination effort and there is no economic cost to failing to get a majority to join in on the attack.

Since the median approach will be the first implementation of BFT time in Cosmos Hub, I believe slashing condition for being too far off the median should be implemented to discourage going against consensus which is how most BFT systems (PoW or PoS) work.

**Comment by jlandrews** [comment]
So we've talked about this a bit, and I'm trying to think through how this would be implemented. It seems like there's two options:

1. Slash for being outside some fixed range of the median. ie slash for more than 1 hour difference
2. Slash for being outside some statistically derived range. ie slashed for being outside two standard deviations from median.

The problem I see with the second one is that with something like time, it seems like most votes will be very tightly clustered at the correct time, so any small clock drift could lead to serious slashing of non-malicious behavior. On the other hand, slashing when outside some fixed time distance could work, but it seems pretty arbitrary how we pick that time, and it would mean that within that time range people were still free to pick points away from the true time without penalty.

**Comment by AdityaSripal** [comment]
>  Can you please explain a precise scenario where lying about time could be problematic?

An example would be having validators individually shift their times forward in order to speed up the time when sends will be enabled (assuming we use BFT time to trigger that event).
Since we will use BFT time in our application to trigger certain events, validators with an interest in seeing some event happen earlier or later could manipulate their personal time accordingly  (while still preserving Time monoticity). Of course, if less than 1/2 choose to do this; the attack is meaningless since we are using the median.

> median approach works as we assume that there is at most 1/3 of faulty processes to satisfy Monotonicity. Under this assumption, we don't care what faulty guys are doing, if they are within 1/3 bound. If we have more than 1/3 of processes lying about time we are in a different system model, and the question is what we can do in such a model, and what is a new bound. 

This is definitely true, I'm not disputing this at all. My worry is that the strength of this assumption is weakened by the fact that there is no economic cost to lying (being far off the median).

With BFT consensus, I can trust this assumption because you either accumulate enough voting power to succeed or you lose economic value.
In PoS, trying a malicious attack and failing to get enough stake to go along with it leads to getting slashed.
In PoW, trying a malicious attack and failing to get 51% of hash power behind it leads to losing the cost of electricity.
Thus the optimal action for any individual actor is to be honest, as being dishonest is almost certainly going to lead to losing economic value.

With the current BFT time spec, individuals can choose to manipulate their personal clocks without any risk of losing economic value. Thus, the game-theoretical incentives that gird the assumptions of BFT consensus aren't present in BFT time.

> We also need to formally define the property that needs be satisfied regarding precision of BFT time with respect to real time.

You're right, should have been less loose with my definition. Here, I don't mean we should slash if you are far from the real time, I think its reasonable to slash if you are far from the median time. It's possible in this case to get slashed if you are closest to real time and everyone else is off but so long as there are at most 1/3 processes that are faulty and we pick a large enough acceptable range, this shouldn't be a problem i think.

>  Slashing helps if we have clear model of correct behaviour. It is quite tricky to do it with time.

Agreed, there is definitely the risk that honest processes can get slashed for being too far off the median. I believe if we make our acceptable bounds large enough this isn't a problem, but how those bounds should be calculated, I don't know yet.


Let me know if I'm missing something. Definitely interested in discussing this further, since secure BFT time is a really cool feature to have!

**Comment by cwgoes** [comment]
If we slash for being off the median time, won't validators often know (if they've seen enough prevotes/precommits already) what time they can "get away with", or (perhaps worse), whether they could purposely vote a different time and get another validator slashed? Without any kind of commit-reveal scheme (unless we have that? I'm not too familiar with the BFT time implementation) this seems problematic.

**Comment by ValarDragon** [comment]
A commit-reveal scheme makes sense to me between the prevotes and precommits.

However I agree with Zarko, I'd prefer this be given a formal treatment before adding any slashing conditions. For example, none of the proposed schemes here included the concept of what round we are on. That seems absolutely necessary in the model of "fixed windows" of your time, due to partial synchrony.

**Comment by ValarDragon** [comment]
Imo, if we are in agreement about treating this quite formally, I think we should remove this from the launch milestone. Its a complex research topic, and we should not try to rush a solution.

**Comment by ebuchman** [comment]
This will be resolved by https://github.com/tendermint/tendermint/issues/2840

**Comment by ebuchman** [comment]
Closing for #2840
