### ISSUE TITLE
pex: Non-deterministic test failure

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2119]
All tests were passing on #2114, then I squashed the relevant commits, and TestPEXReactorRunning failed.

https://circleci.com/gh/tendermint/tendermint/17926#tests/containers/2

This test passes locally.

**Comment by ValarDragon** [comment]
Not sure if this helps, but I think this is getting caused by `c.pingTimer` being `nil`. I don't really have any idea what would cause this though.

**Comment by xla** [comment]
One explanation would be that `OnStop` is called before `OnStart` or the latter is never called.

**Comment by melekes** [comment]
Let's close in favor of #1976
