### ISSUE TITLE
TMSP -> BAPI (GRPC/socket)

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#212]
Instead of the flat fieldspace that we have, actually have multiple request/response types, prefixed by the type (instead of using "oneof").

**Comment by mdyring** [comment]
Might be worth considering GRPC instead of socket+protobuf, as suggested by Tom Truitt: http://www.grpc.io/docs/

**Comment by jaekwon** [comment]
`tendermint node --bapi <grpc/socket>`

- [ ] implement basic GRPC app in NodeJS && split message types into distinct types
- [ ] implement TMSP GRPC mode

**Comment by ebuchman** [comment]
see https://github.com/tendermint/tmsp/tree/protobuf
and https://github.com/tendermint/tendermint/tree/new_protobuf for progress
