### ISSUE TITLE
mempool: Benchmark the operations

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2122]
Currently I suspect that we are using inefficient data structures for the tasks at hand. (e.g. Scanning an entire linked list to check for duplicate tx, many other data structures can do this task far more efficiently with other trade offs) The current implementation will likely cause significant performance bottle necks if the mempool has many txs, and I suspect this does have a huge impact on the system performance.

However we should first have concrete benchmarks before optimizing the code base.

**Comment by tychoish** [comment]
Sorry for not linking this better in the moment, but https://github.com/tendermint/tendermint/pull/6418 gets the existing high level benchmarks in to order, and also fixes an obvious problem. I'm going to make a second PR in a few moments to add another benchmark for "adding a duplicate transaction." Preliminary testing is that duplicate transactions have no additional overhead relative to adding  same cost (in terms of the data structures) as adding a new transaction.

I think that would cover the scope of this ticket, but I think we're in a good position to use these tests to validate the performance impact of other changes in the future.

**Comment by ValarDragon** [comment]
Awesome! (And nice work on the reap speedup =))

I think the main thing we should later write benchmarks for is time delay for parallel txs being added with underlying check tx's having variable time. (And time until a reap terminates when many check txs are also being added in parallel, since there is a mutex contention IIRC)
