### ISSUE TITLE
max_block_size_txs ignored under some circunstances

### ISSUE THREAD

**Issue by DavidSanMar** [tendermint/tendermint#2125]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.22.8-40d6dc2e

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

BigchainDB 2.0 b3

**Environment**:
- **OS** (e.g. from /etc/os-release):
CentOS release 6.9 (Final)
- **Install tools**:
Binary
- **Others**:

**What happened**:

I built a 4 node network, with "max_block_size_txs = 30" in the 4 of them since the very beggining.

In certain circunstances, a huge block is generated, bypassing the max_block_size_txs configuration.

I came across with one of the nodes running out of disk space, hence App doesn't validate txs in that node (but is connected to the other 3 of the network).

**What you expected to happen**:

The remaining three should continue to check txs or stop working or whatever, but never ever ignore the max_block_size_txs configuration.

**How to reproduce it** (as minimally and precisely as possible):

Set a 4 node bigchaindb network with the said tendermint binary. Make one of them to have a little less of disk space than the other 3.

Send transactions (sync or async) until disk in problematic node is full.

See the other remaining nodes blocks to grow.

**Logs (you can paste a small part showing an error or link a pastebin, gist, etc. containing more of the log file)**:

None

**Config (you can paste only the changes you've made)**:

max_block_size_txs = 30

**`/dump_consensus_state` output for consensus bugs**

None

**Anything else do we need to know**:

Referred here by the BigchainDB team.

It seems to me really strange that max_block_size_txs is ignored in some circunstances (no matter what they are), but it seems to work in other circunstances.

**Comment by DavidSanMar** [comment]
I just realized that max_block_size_txs was moved to genesis.json. Damn me :-(

https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md#0220

**Comment by melekes** [comment]
Hi! We removed `max_block_size_txs` in favor of consensus params in genesis file.

```
## 0.22.0

*July 2nd, 2018*

BREAKING CHANGES:
- [config]
    * Remove `max_block_size_txs` and `max_block_size_bytes` in favor of
        consensus params from the genesis file.
```

To enforce max block size you will need either 1) change default in genesis file

```
{
  "genesis_time": "XXXX",
  "chain_id": "XXXX",
  "consensus_params": {
    "block_size_params": {
      "max_txs": "30"
    }
  }
```
*if your have just created it*

or change the default via `ResponseEndBlock` https://tendermint.com/docs/app-dev/abci-spec.html#endblock

**Comment by DavidSanMar** [comment]
@melekes  Thank you, just realized seconds ago ;-)
