### ISSUE TITLE
p2p/pex: Connect to more than 10 peers

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2130]
https://github.com/tendermint/tendermint/blob/eaa137512cddbb691bb301102c8355ea2a4e47e9/p2p/pex/pex_reactor.go#L364

PEX should respect `min`, but try to connect to as many peers as possible (up to `max`)

### What you are seeing
It's been reported that in normal mode (!seed, pex enabled) a node stops trying to connect to other peers after it has =10 outbound connections.

### What you expect to see
Node should connect up to `MaxNumPeers` and only then stop any attempts.

**Comment by melekes** [comment]
Of course! Sorry

**Comment by ebuchman** [comment]
Sorry I didn't really check in with this earlier.

There's a good reason we only dial min and not all the way to max - it's so we can leave a lot of room to accept new connections.

We might want to expose minNumOutbound peers to the config, but I don't think we should get rid of it. That will just make it harder for new peers to join the network.

Is there some reason we think we need to keep dialing more than some min amount which is less than the max? Or was the reasoning just not clearly explained?

**Comment by mdyring** [comment]
I discussed this with @melekes on Riot.

I have configured max_num_peers = 256 for gaia-7005 and would expect to see the number of peers increase until the limit is reached or no known, unconnected peers exist.

It is unclear from config.toml, that there is a minimum number of peers as well, after which nothing will happen.

Stopping at some lower number of peers seems counter-intuitive, there might be good reason for wanting to connect to as many peers as possible.

IMHO it makes sense to just use the max_num_peers and then remove the minimum. This will provide maximum control for the user.

**Comment by ValarDragon** [comment]
Why not have a `maxOutboundPeers` and `maxInboundPeers` in addition to max peers. That seems like it will give a high degree of configurability while also being easy to understand.

**Comment by mdyring** [comment]
@ValarDragon yeah just edited my reply after I re-read (and understood ;-) what @ebuchman commented.

**Comment by melekes** [comment]
> There's a good reason we only dial min and not all the way to max - it's so we can leave a lot of room to accept new connections.

This is an internal knowledge and should be visible to the end user either in config or logs.

Although we're designing Tendermint for Cosmos, I don't think we should make any assumptions about desired network topology, but instead, give the ability to regulate it or/and make it public knowledge.

**Comment by mdyring** [comment]
Looks great - thanks!

**Comment by ebuchman** [comment]
Believe this was addressed by #2169
