### ISSUE TITLE
Create an ADR for lite/provider

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#2133]
See: https://github.com/tendermint/tendermint/pull/1815/files#r205110595

We should refactor lite/* after launch, to save components of the full commit rather than the whole full commit itself.  This refactor should start with an ADR that describes the new interfaces.

Post-launch, as it doesn't affect the chain itself so upgrading is relatively easy.

Probably also should include ADR for InquiringCertifier (to be renamed as DynamicVerifier).

**Comment by marbar3778** [comment]
> @mossid and I have been working on an abstract definition of a light client in ICS 2, which may be helpful here as well (especially in the ADR) - https://github.com/cosmos/ics/tree/master/spec/ics-002-consensus-verification

From PR #3577

**Comment by melekes** [comment]
> Probably also should include ADR for InquiringCertifier (to be renamed as DynamicVerifier).

^^^

It also makes sense to write about concrete structs like PersistentProvider, ConcurrentProvider, etc.

**Comment by cwgoes** [comment]
Two more notes:
- Can we specify how interfaces will be shared between the sequential & bisecting clients?
- Can we specify how interfaces will be shared between the client making network requests (in full nodes / light clients running on computers) & the write-only client (for IBC)?

**Comment by melekes** [comment]
"I need to add documentation or justification for deprecating the verifier interface and making the dynamicverifier a provider, so that should be added as an ADR as well." Jae

**Comment by melekes** [comment]
![liteclient1](https://user-images.githubusercontent.com/1282182/63248200-dca1d180-c277-11e9-9028-8a5458ca6c1d.png)

1. Think we should move ConcurrentProvider to verifying package (do we even need a separate vefifying package?)
2. `verifier` should be moved to where it's used

**Comment by melekes** [comment]
Wrote how I think minimal setup should look like:

```go
	sources = []Provider{
		lclient.NewHTTPProvider(chainID, remote1),
		lclient.NewHTTPProvider(chainID, remote2),
	}
	dv, err := NewDynamicVerifier(
		chainID,
		TrustOptions{TrustPeriod: 336 * time.Hour},
		sources,
	)
	require.NoError(t, err)

	err = dv.Verify(newHeader)
	require.NoError(t, err)
```

- at least two sources are required for security
- default trusted provider is used. otherwise it can be passed as an option
```go
sources, Trusted(lite.NewDBProvider(memDBFile, dbm.NewMemDB()))
```

**Comment by melekes** [comment]
Provider interface:

```go
type Provider interface {
	ChainID() string
	LatestFullCommit() (FullCommit, error)
	GetFullCommit(height int64) (FullCommit, error)
}
```

LatestFullCommit allows users to get the latest header. GetFullCommit allows introspection.

**Comment by melekes** [comment]
![Screenshot 2019-08-21 at 13 44 55](https://user-images.githubusercontent.com/1282182/63421578-e105f000-c419-11e9-8729-721bff0f40bd.png)
Here is the proposed directory structure ^. Providers grouped in one package, errors moved into main package, verifying provider renamed to client (i.e. `lite.Client`)

also I don't understand why we need this whole pendingVerifications in ConcurrentUpdatingProvider https://github.com/tendermint/tendermint/blob/806e8d20773069c4bb9d33ef6d0547258cbcfbad/lite/concurrent_provider.go#L14. Yes, we should make lite.Client safe for concurrent usage, but can't think of the reason why multiple verifications attempts should exist in parallel (feels like a premature optimization)

**Comment by zmanian** [comment]
I was talking to @cwgoes about how this spec needs to change to accommodate sharing logic between the IBC light client and tendermint light client.

The Provider Interface looks like it can be fulfilled by either an lazy provider that does HTTP requests to get data or an eager provider that is constructed from data submitted in a transaction.

The Trust Store will also need to by an interface that can fulfilled either by a local trust store that stores state about the last trusted header in leveldb or a trust store that stores state in a Keeper

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3911

**Comment by marbar3778** [comment]
@melekes is this completed?

**Comment by melekes** [comment]
no. I will try to write about choices made tomorrow. thanks for reminding me!
