### ISSUE TITLE
How to add a node in a live cluster network?

### ISSUE THREAD

**Issue by ArvonHuang** [tendermint/tendermint#2138]
FEATURE REQUEST
Hi all, supposed i have deployed a 4-node cluster network , if i want add an extra node which can be a 
 validator or non-validator , what should I do. Thx very much.  

**Tendermint version** 
0.20+

**ABCI app** 
0.11+

**Environment**:
centos7

**Comment by zramsay** [comment]
hi @ArvonHuang the information you're looking for ca be found here:
https://github.com/tendermint/tendermint/blob/master/docs/tendermint-core/using-tendermint.md#adding-a-non-validator 

Re-open the issue is this doesn't help

**Comment by ebuchman** [comment]
You need to use EndBlock in your application to update the validator set. See

- https://tendermint.com/docs/app-dev/app-development.html#endblock
- https://tendermint.com/docs/app-dev/abci-spec.html#endblock

**Comment by ebuchman** [comment]
You can always add a non-validator node at any time just by having the genesis file and adding some peers using --p2p.seeds and/or --p2p.persistent_peers
