### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by andreaturli** [tendermint/tendermint#214]
Looking at https://drone.io/github.com/tendermint/tendermint/1043

but if I reproduce the steps with travis ci, drone.io or manually in my osx, it fails with a message like the following 
https://travis-ci.org/andreaturli/tendermint/builds/130210842
and
https://drone.io/github.com/andreaturli/tendermint/3

Any idea?

**Comment by andreaturli** [comment]
new README helps with that! thanks

**Comment by jaekwon** [comment]
Also fixed the underlying issue which was a bad dependency tree.  Fixed!
