### ISSUE TITLE
404 Error - Tendermint / Docs

### ISSUE THREAD

**Issue by stevenventimiglia** [tendermint/tendermint#2142]
The line, "Follow the installation instructions to get up and running quickly", has a link that results in a 404 error.

**Incorrect URL:**
https://github.com/tendermint/tendermint/blob/master/docs/introduction/install

**Correct URL:**
https://github.com/tendermint/tendermint/blob/master/docs/introduction/install.md

**Comment by zramsay** [comment]
thanks for the report; #2143 and #2181
