### ISSUE TITLE
test_persistence: non-deterministic non-halting

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2155]
CI for https://github.com/tendermint/tendermint/pull/2152 didn't complete because the `test_persistence` job seemed to go on for ever. Here is the output:
[build_18829_step_104_container_0.txt](https://github.com/tendermint/tendermint/files/2260692/build_18829_step_104_container_0.txt)

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/5388

**Comment by erikgrinaker** [comment]
This test was removed in #5453, replaced by new end-to-end tests.
