### ISSUE TITLE
Running on mobile

### ISSUE THREAD

**Issue by joeblew99** [tendermint/tendermint#216]
Hey all,

I was wondering if anyone has tried compiling it for android / ios using gomobile ?
This is something that interest me, and i could help on that.

**Comment by ebuchman** [comment]
This would be great! We have not directly, but the eris folk have been working on this with eris-db, which imports tendermint, eg. https://github.com/eris-ltd/eris-db/pull/137

**Comment by joeblew99** [comment]
Ah that sounds really promising.

I just contacted one of the developers who is in berlin, like me. Will see if he wants to collaborate.

Either way I will look into it.

I was also wondering if I could ask you some high level questions. I am a systems architect type of programmer and toying with applying this to real world things.

**Comment by ebuchman** [comment]
sure what's your email? we'll add you to our slack

**Comment by joeblew99** [comment]
@ebuchman i emailed you.

thanks. will close this issue as its noise

**Comment by wighawag** [comment]
Hi, I am interested in running tendermint on mobile too. Did you made progress ?

**Comment by melekes** [comment]
```
https://github.com/golang/go/wiki/Mobile
I don't know if anybody tried to use TM to build an app, but it should work in theory
```

**Comment by ethanfrey** [comment]
AFAIK, there is no progress here. Only two known issues. 

One is that tendermint doesn't work on 32 but architectures. This is a known issue, but ignored. And most modern mobile devices also use 64 but arm.

We did try to port the tendermint light client with go mobile, which pulled in a number of the libraries, such as crypto. It seemed to work locally, but we had trouble as the http connections were getting dropped. But this seemed to be standard behavior on ios, to enforce https. 

It was only an experimental project and we didn't spend too much time.

If someone has a week full time, and knows the native platform development issues, as well as go, it should be doable. We are focusing on launch of cosmos hub now, and will not work on this for a few more months. But if you want to try, please do and I can offer some advice.

**Comment by njmurarka** [comment]
Any progress on Tendermint on mobile? I only write this because it is now 2019 and perhaps alot has happened since.

**Comment by marbar3778** [comment]
The lite client could be used for this. There is a rust impl of the lite client being worked on which will hopefully be able to be compiled to wasm and then used wherever. 

This isnt a current priority at the moment but would love to hear your use case

**Comment by njmurarka** [comment]
Thanks for the quick reply here -- I love what I am reading about the current implementation of Tendermint and the associated ecosystem of Cosmos and by no means have I gone down all the rabbit holes yet. Many videos and web-blogs later, I think I am still learning things.

I am looking at the idea of building a decentralized product around Tendermint, where "public nodes" can be be either PC's (Mac, Linux, etc) but it is intriguing to also have the ability for a mobile device like the average "current" iPhone or Android or iPad also be able to run as a "node". This of course requires the ability to run not just Tendermint, but also the application that  sits on each node, and any other requirements. But the big question here is the Tendermint part -- can that even run on a mobile device? If so, will that instance be a validator? Or some other type of "player" in the ecosystem? 

Is there some role that this smart phone owner could take on by running the software, that helps the network, and thereby justifies this smart phone owner to earn some sort of token? I read up about delegators, validators, and light nodes, but don't know nearly enough. Is a "light client" the same as a "light node"? What makes it "light"?

Many questions, I know but this might get a fruitful conversation going and I might be interested in taking on some role with respect to getting this to work properly on mobile.

**Comment by ethanfrey** [comment]
Running a node has large bandwidth requirements. And especially a validator requires low latency. I personally don't see this as compatible with mobile (but could work on a home pc). Running a light client or LCD rest server on mobile would be useful IMO

**Comment by njmurarka** [comment]
Agreed, @ethanfrey, with respect to bandwidth requirements and latency requirements. I will add (despite not having used or profiled the additional power requirements) that it is not a good fit for mobile due to the drain on battery.

That having been said, the use case I am more interested in is people being able to use their devices while at rest, either at the office or at home, etc. Someplace the device is ideally plugged in and on a WiFi connection.

**Comment by yogitalande** [comment]
Hi, need help on running Tendermint Node on Android, can someone guide?
