### ISSUE TITLE
Implement multisig ADR

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2163]
This issue is for tracking this in the current project board. See #1960 for proposal.

**Comment by ValarDragon** [comment]
Ref https://github.com/tendermint/tendermint/pull/2164#pullrequestreview-145289993
What remains:
* For the threshold multisig, complete switching everything to table driven tests, with explicit checks on the recursive case. Adapt ADR to note the recursive case is allowed
* Implement weighted multisig
* Consider using compact bit array marshalling for marshalling the multisignature object.
* Make the compact bit array JSON elements and struct element names align.

**Comment by alexanderbez** [comment]
Note, getting a `Pubkey` back from a bech32-ified string does not work in the Cosmos SDK because the bech32 string is too long (> 90 chars).
