### ISSUE TITLE
Slow internet?! when running tendermint on the same PC

### ISSUE THREAD

**Issue by wangxiangjun88** [tendermint/tendermint#2165]
when I deploy one node on my computer(win10), i use --proxy_app=kvstore the simple example to start the node.when i commit one tx and succeed.then next  when i visit baidu.com or some other website. it responses slowly,sometimes it loses connection.why?other computer don't have this problem.

**Comment by wangxiangjun88** [comment]
I deployed one tendermint node on my computer which system is win10. I start the node with command that "tendermint.exe --home data node --proxy_app=kvstroe".The node runs normally.when i use "http://localhost:26657/broadcast_tx_commit?tx="hello"".it responsed ok.But at this time,when I visit some common websites like www.baidu.com .it lose the connection. then i visit the website again,it is ok.
there is only one node,so the tx will not be transfered to outer node.This problem only occurs on my computer.Other computer do not have this problem.

**Comment by wangxiangjun88** [comment]
Losing the connection is that i can not visit website normally in a few seconds
As long as I commit one tx,then i can not visit common websites in a few seconds.
But if i do not  commit tx. I can visit website normally.
Now i replace the wireless network card with usb lan ,the problem is not exist.
I just wonder if the action of committing tx  triggers something in my computer.

**Comment by wangxiangjun88** [comment]
I even can not ping gateway,it shows time out in that few seconds.

**Comment by ValarDragon** [comment]
My guess would be your in a computational strained environment, and that this is independent of the internet connection itself.

**Comment by zramsay** [comment]
what ^ @ValarDragon said. closing for now
