### ISSUE TITLE
go get github.com/tendermint/tmsp/cmd/... fails

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#217]
Using instructions on the tutorial @ http://tendermint.com/guide/run-your-first-tmsp-application/ :

$ go get github.com/tendermint/tmsp/cmd/...
\#github.com/tendermint/tmsp/types
gocode/src/github.com/tendermint/tmsp/types/types.pb.go:1327: undefined: grpc.SupportPackageIsVersion2

**Comment by ebuchman** [comment]
should be fixed. reopen if not. thanks!
