### ISSUE TITLE
wrong max-peers in gaiad

### ISSUE THREAD

**Issue by dlguddus** [tendermint/tendermint#2170]
gaiad v0.23.1
1. set max-peers-num to 10 for node A
2. my peer num was 1 for node A
3. gaiad logging maxpeernum 0
4. in node B, i included node Ain persistent peers
5. in node A i keep saw error already filled maxnumpeer so cannot add peer for node B
6. in node A, i changed maxpeernum from 10 to 40
7. node B added in node A as a peer.

node A pex false, 1 persistent peer, 26656 open to only 2 ip, it is a relay node.
node B pex false 1 persistent peer 26656 open to only 1 ip which is node A, it is a validator node.

wrong display of maxpeernum
wrong number of maxpeernum when gaiad decide whether it will add the peer or not.

**Comment by melekes** [comment]
Thank you for raising this! The issue has been fixed in https://github.com/tendermint/tendermint/pull/2169

**Comment by ValarDragon** [comment]
Fixed in #2169! Please post again if this problem persists for you on develop.
