### ISSUE TITLE
p2p: non-deterministic TestPEXReactorRunning

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2176]
Triggered by https://github.com/tendermint/tendermint/pull/2174 (no code changes!)

```
ok  	github.com/tendermint/tendermint/node	1.165s	coverage: 70.8% of statements
--- FAIL: TestPEXReactorRunning (10.03s)
	pex_reactor_test.go:445: expected all switches to be connected to at least 2 peer(s) (switches: 0 => {outbound: 0, inbound: 1}, 1 => {outbound: 1, inbound: 1}, 2 => {outbound: 2, inbound: 0}, )
FAIL
coverage: 74.4% of statements
FAIL	github.com/tendermint/tendermint/p2p/pex	19.736s
```

**Comment by ebuchman** [comment]
Got this again. Here's the full test output: https://gist.github.com/ebuchman/1714aab96ea2bb2b465203f471589b7d

**Comment by ebuchman** [comment]
Still getting this (eg. https://circleci.com/gh/tendermint/tendermint/59449#tests/containers/3)

**Comment by tessr** [comment]
Going to close this since we did a bunch of cleanup on non-deterministic tests earlier this year (+ I think we are saying goodbye to the PEX soon anyways)
