### ISSUE TITLE
crypto: Switch tmhash to AVX2 sped up SHA2

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2186]
I don't really see a reason not to. It would be a drop-in replacement from this repo: https://github.com/minio/sha256-simd/. (Results are fully compatible)

This provides a 10x speedup on architectures that support it. The only reason I can foresee to not do this would be a security concern / lack of auditing regarding the correctness of output. If its passing all test vectors its probably going to be correct on most output though. #postlaunch I think it would be a good idea to seriously consider using it / audit correctness if we're worried about that.

This is based upon Intel's multibuffer crypto library https://github.com/intel/intel-ipsec-mb.

**Comment by marbar3778** [comment]
Gonna move this to proposal. It looks like a sound transition but would like to hear from others

**Comment by erikgrinaker** [comment]
What percentage of block processing time is taken up by hashing? If it's small (<10%) I'd say we should just keep it simple and stick with the stdlib.

**Comment by ValarDragon** [comment]
It'll vary greatly per app. and the percentage spent on block processing will increase as more computational speedups are integrated. E.g. For Blockchains that have a SNARK for computation mitigation, hashes dominate CPU time. (Especially if its a stateless blockchain) Something similar applies for blockchains that verify many L2's.

Interesting Data-heavy data points in the cosmos ecosystem would be 
* lazyledger (/cc @liamsi), where the full node/proposer work should be large block hashing + RS code generation (I think should be dominated by the RS code with one core, but with many cores block hash should dominate atm)
* Big chain DB: IIUC, the whole chain is state updates with limited computation/just signatures?

**Comment by liamsi** [comment]
@musalbas didn't you experiment with sha256-simd for the fraud-proofs (or a related) paper and dropped in favour of the go standard implementation?

**Comment by liamsi** [comment]
Oh I see, the support for sha intrinsics were added after the experiments in the paper: https://github.com/minio/sha256-simd/pull/37#issuecomment-451607827

Might be worth to reconsider this for more modern (intel) CPUs.

**Comment by musalbas** [comment]
There's no downsides of use sha256-simd as a drop-in replacement as far as I'm aware, only upsides.
