### ISSUE TITLE
mempool cache: use a fast hash

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2187]
Tx hashes aren't consensus critical. AFAIK, they are only used to know if your transaction appeared on chain. A second use case being considered is within the mempool to save on memory stored. 

For the latter use-case, it definitely makes sense to use a faster hash. We could use https://en.wikipedia.org/wiki/HighwayHash, which is 30x faster than the standard SHA2. (Source: https://blog.minio.io/highwayhash-fast-hashing-at-over-10-gb-s-per-core-in-golang-fee938b5218a?gi=34fcf777b99e). Its not a cryptographic hash (as it hasn't received enough review / analysis yet), however I believe that the authors are currently analyzing it, and have proven security against differential analysis. Using something fast for the mempool is likely safe, since the worst that can happen is one tx gets marked as a duplicate (and which one gets marked as dupe depends on order received, so its likely that one proposer will eventually get one correct one).

Its significantly harder to find collisions between txs than it is to find collisions in random messages, since signatures bottleneck the amount of txs you can create. Because of this, it may be worth considering even using HighwayHash for normal TxHashes. This is a much more minute point, so we should use the faster hash for the mempool cache at least.

Highway hash is 10x faster than blake2b on a single core. For language support, highway hash has bindings for `C, Golang, Rust, Python3, JS`.

**Comment by ValarDragon** [comment]
Oh good point, your right. Then nevermind, we should just use this suggestion for the mempool cache. But #postlaunch ofc :)

**Comment by JekaMas** [comment]
I have a prototype of this idea about cache generator - https://github.com/JekaMas/nicecache . The example can be seen https://github.com/JekaMas/nicecache/blob/master/example/testvalue_nicecache.go

The main storage is simply preallocated array (not slice) with a bunch of mutexes to reduce lock time. Any key is mapped into an index in the array and simple GC is implemented.

For hashing I used as simple and fast as possible github.com/dgryski/go-farm

**Comment by ValarDragon** [comment]
So sorry for the late response! This looks incredible, and really well designed! I like how theres separate bucket sizes and multiple indices per bucket. I think we should definitely use this for a lot of our caches. For most of the stack its preferrable for its speed properties. Here in particular, it looks way better due to how it handles locking. Having our cache lock on each addition is quite bad atm :)

This probably isn't that significant, but just out of curiosity what is the space overhead of the mutex per bucket? I also don't think we have a need for the `expiredTime` field. Is that something we can not generate?

@ebuchman Is it fine to integrate generated code to mitigate the cache locking time near-term? If nothing else, I think we should do this as part of the new mempool design https://github.com/tendermint/tendermint/issues/2147#issue-347673061, it would enable us to get a quick cache again without any asymptotic hits.

This is distinct from using a fast hash, we should still do that as we fundamentally just don't want a large number of bytes for every cache entry. (Since they can effectively be arbitrarily large)

**Comment by JekaMas** [comment]
@ValarDragon 
Thanks for the review! It'd be great if the cache helps us to have better asymptotic for mempool.

I'd rather add feature to disable `expiredTime` option and use alternative GC without `expiredTime`. It'll save some memory.

The second thing I can do is adding computation of amplification factor to know the price of fast cache.

What can be done next is adding pool generators for keys and objects.

Than I can add more tests to be sure that everything is stable. And start intergating cache generator into mempool.

First three issues I can done in 2-3 weeks and then start intergation+mempool benchmarking.

**Comment by ValarDragon** [comment]
That sounds great! I don't think any of that should block integration into our mempool cache. The thing about the mempool cache in particular is that we don't depend on the actual cache part being lightning fast (I was mostly asking about those things out of curiosity), it not locking is far more important. The txs themselves aren't placed into the cache, its the hash of the txs, since the txs could potentially be in the hundreds of KB. Hashing that tx will take significantly longer than most of the actual work in the cache lookup.

I think this cache is something that we can integrate once there is an option to disable `expiredTime` as you suggested! (@ebuchman thoughts here?) I do prefer simplifying the cache logic with that.

> What can be done next is adding pool generators for keys and objects.

That sounds like a cool property for caches in general! That doesn't really matter here / shouldn't block integration, since as I mentioned above the time the actual cache lookup takes is negligible compared to the time it takes to hash it.

**Comment by JekaMas** [comment]
@ValarDragon Sorry for late response. I'm  implementing disabling expired Time this week and than going to integrate cache in one week more.

**Comment by ebuchman** [comment]
Sorry for tuning in late here.  nicecash looks like a cool project, though I'm not sure it makes sense here especially since we don't actually store values in our cache, we just check membership (ie "have we seen this transaction before?"). So it might be a bit overkill for our purposes.

It's probably not a problem to adopt HighwayHash instead of SHA2 in this cache, which is what this issue was originally about. That said, HighwayHash is young, and while collisions are unlikely and not consensus critical, if they ever do happen they may be difficult to detect and hard to debug. So at least I wouldn't think it's worth considering until its proven to be a significant resource hog in the profiler, and there's probably lots of other things to address in the mempool first.

That said, and following in the spirit of similar discussions like https://github.com/tendermint/tendermint/issues/476#issuecomment-454462464, we should work towards making it easier to experiment with alternative reactors without forking the repo, so that we can have a standard core implementation that is maybe not the fastest, and experiment with alternative implementations more freely. Over time the core one will evolve to incorporate ideas from the alternatives. Opened https://github.com/tendermint/tendermint/issues/3176 to track this idea.

**Comment by marbar3778** [comment]
This has overlap with https://github.com/tendermint/tendermint/issues/6539. If and when the mentioned issue would be merged this would be up to the application developer.
