### ISSUE TITLE
config.toml file is different as compared to standard. tried to hardcode values but still doesn't work.

### ISSUE THREAD

**Issue by adityanalge** [tendermint/tendermint#2189]
Tendermin Version - 0.8.0
abci-cli Version - 0.12.0
go version - go1.10.3

Environment - 
OS - Linux Ubuntu Virtual Machine

I followed the guide for installation (https://tendermint.readthedocs.io/projects/tools/en/master/install.html) exactly as it said. Even uninstalled and reinstalled GO, Tindermint as well as abci-cli.

For some reason my config.toml file has different IP addresses as compared to the one on the guide.
I tried setting the values myself but still didn't work. I got different errors both time. I have attached screenshots below.

I am trying the latest version because I am doing it today.

I have attached both screenshots below

![error1](https://user-images.githubusercontent.com/25779007/43871098-099ca9d2-9b49-11e8-957f-77292f542685.png)

![error2](https://user-images.githubusercontent.com/25779007/43871108-15be925c-9b49-11e8-83f6-0adc33439ea4.png)

**Comment by melekes** [comment]
Hey. Thank you for giving Tendermint a try! But you're using a really old version, which is not supported anymore (0.8.0). Please upgrade to the latest version https://tendermint.com/docs/introduction/install.html#reinstall.

**Comment by melekes** [comment]
Closed due to inactivity. If the suggested fix does not work for you or you have any additional questions, please comment on this issue.

**Comment by adityanalge** [comment]
Thanks for the reply. Downloading from the link did fix the issue.
