### ISSUE TITLE
libs/common: Spliti it up into submodules

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2191]
I think its better to not make common a mono-module. A couple of the benefits: Improves the godocs / autocomplete, its more clear exactly what downstream applications are using. 

Making huge mono-modules is an anti-pattern AFAICT. It also increases the size of binaries if anyone is just using a sub-component of common in a downstream application. (i.e. using it as a library, as we intended)

**Comment by melekes** [comment]
Agree, but having too many sub-packages can be cumbersome

**Comment by Liamsi** [comment]
Many of the features in common are not used or can be replaced by packages in the sdt library. Then, it would not be cumbersome anymore... 
@marbar3778

**Comment by marbar3778** [comment]
Seems we are in agreement here 👍

**Comment by marbar3778** [comment]
closing this in favor of #4147
