### ISSUE TITLE
libs/common: Remove Fmt

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2193]
Currently we have the following function in `libs/common/string.go`, which is actually used throughout our codebase:

```
// Like fmt.Sprintf, but skips formatting if args are empty.
var Fmt = func(format string, a ...interface{}) string {
	if len(a) == 0 {
		return format
	}
	return fmt.Sprintf(format, a...)
}
```
This doesn't make sense to use for efficiency purports. You should never be calling `fmt.Sprintf` if you have no arguments. (Nil is an argument that gets formatted). (This is the exact reason theres `fmt.Printf` and `Println`, and `errors.New` and `fmt.Errorf`) Therefore there isn't a good use case for this to replace. We should just use `fmt.Sprintf` directly and avoid the indirection.

There isn't really a conflation between when to use `fmt.Sprint` and `fmt.Sprintf` (one is format string, the other isn't). There may be some confusion between `fmt.Errorf` and `errors.New` (hence this being an explicit thing golint warns about), however this should be taken care of within our errors library, and not have an assoc. publically exported API which is used directly throughout our codebase.

**Comment by melekes** [comment]
We've been slowly doing it in every PR for six months or so. So I would say this proposal is accepted.

**Comment by melekes** [comment]
Merged to develop.
