### ISSUE TITLE
tm-bench tool sends twice the size of set tx size

### ISSUE THREAD

**Issue by shahbazn** [tendermint/tendermint#2202]
Running the following test `tm-bench -T 20 -c 16 -s 400 localhost:26657 -broadcast-tx-method async` actually sends transactions of size 800

This line seems to be the problem 
https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/tools/tm-bench/transacter.go#L166

**Comment by ValarDragon** [comment]
Hrmm. I was under the impression that the actual tx was hex decoded. If thats not the case, either we should pick a more space efficient encoding scheme, or halve the size going into `t.Size`. (I'm not too sure what the time per hex encode vs b64 encode, we do want updating the encoding to be efficient)

I'm leaning towards halving t.Size. https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/tools/tm-bench/transacter.go#L165

**Comment by ebuchman** [comment]
The RPC requires hex (ie. size*2), but the txs in the block should be the size expected. Is there actually a bug here then?

**Comment by ValarDragon** [comment]
There is no bug here then.

**Comment by ValarDragon** [comment]
The bytes aren't getting decoded from hex. 
I modified the block printer to return the literal representation, and it returned this: 
`0000000000000000de0f0000000000004215fa52fd2738dd8d17ad1897c4f660f3bdb7db05000000ffe08b8e284614ebcfce`.

**Comment by ValarDragon** [comment]
The kvstore should hex decode the values, or we should stop hex encoding them in tm bench

**Comment by ValarDragon** [comment]
i'm not really sure why we want the kvstore to only accept hex encoded input. I think it makes more sense to stop encoding as hex in tm-bench, and drop the expectation of hex encoding input the kvstore.
