### ISSUE TITLE
libs/clist: Make remove automatically detachprev and detach next

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2207]
Ref:
```golang
// CONTRACT: Caller must call e.DetachPrev() and/or e.DetachNext() to avoid memory leaks.
// NOTE: As per the contract of CList, removed elements cannot be added back.
func (l *CList) Remove(e *CElement) interface{} {
```
The caller should not have to call detach on the previous element, or the next element. This is confusing, and I can't see any reason why we wouldn't want these to detach. For reference, the golang standard list automatically detaches prev and next. AFAICT  _all_ current usages of our CList have memory leaks. They all only call `DetachPrev` and don't call `DetachNext`.

**Comment by JayT106** [comment]
@alexanderbez @ValarDragon just looking at this issue, the mempool V0/V1 uses CList.
 Do you think it's still true for detaching the prev and the next element when removing an element?

**Comment by alexanderbez** [comment]
Yes @JayT106. If you want to give a PR a shot, I'd be happy to review :)

**Comment by JayT106** [comment]
> Yes @JayT106. If you want to give a PR a shot, I'd be happy to review :)

Sure!
