### ISSUE TITLE
Missing images in new docs

### ISSUE THREAD

**Issue by siman** [tendermint/tendermint#2214]
New docs at URL (https://tendermint.com/docs/) miss that miss images that can be found in old docs (https://tendermint.readthedocs.io/projects/tools/en/master/index.html)

## A screenshot of **old** docs with image:

![Old docs](https://user-images.githubusercontent.com/153928/44060685-1bae92c0-9f5e-11e8-8e8d-6d6dea81ce56.jpg)

## A screenshot of **new** docs with no image:

![New docs](https://user-images.githubusercontent.com/153928/44060716-3ab5cb0c-9f5e-11e8-9989-88b96a3a5a96.jpg)

**Comment by melekes** [comment]
Merged to develop.
