### ISSUE TITLE
gaiad becomes unresponsive after pong timeout error on sentry nodes

### ISSUE THREAD

**Issue by gojun077** [tendermint/tendermint#2216]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Version bundled with *cosmos-sdk* `v0.23.1`

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): Amazon Linux 2 (RHEL-variant)
- **Install tools**: golang 1.10.3
- **Others**: 2 vCPU, 8GB RAM

**What happened**:
After gaiad has been running for some time (1~2 days) it suddenly has errors connecting to peers. After consecutive connection errors Connection failed @ sendRoutine module=p2p...pong timeout, MConnection module p2p and Peer module p2p are stopped as well as gossip and query routines for peer module consensus. Once these modules stop gaiad is still running but is in an inactive (zombie?) state and emits no more output. Stopping and restarting gaiad solves this issue.

**What you expected to happen**:
I expect `gaiad` to run normally; it it has a problem, I expect it to exit gracefully. In this case however, `gaiad` doesn't die or emit any more messages to syslog.

**Have you tried the latest version**: yes/no
no

**How to reproduce it** (as minimally and precisely as possible):
Run a public sentry node with `gaiad` git tag `v0.23.1` on testnet *gaia-7005*. Run your sentry for 24~48 hours. If you notice that your node is no longer writing to disk (< 100 writeOPS per second) your node is no longer following the latest block and `n_peers` will be 0. I am running sentries in the AWS ap-northeast-2 Seoul region and have seen this issue 3 times.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
Before `gaiad` becomes totally unresponsive it emits the following in syslog:

```
Aug 11 07:30:39 sentry0 gaiad[8700]: I[08-11|07:30:39.433] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{54.180.18.1:26656} 5b29669228c5573b5dc7dcb67453c45d7cebdfdd out}"
Aug 11 07:30:39 sentry0 gaiad[8700]: I[08-11|07:30:39.478] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{54.180.18.1:26656} 5b29669228c5573b5dc7dcb67453c45d7cebdfdd out}"
Aug 11 07:30:42 sentry0 gaiad[8700]: I[08-11|07:30:42.306] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{54.180.18.1:26656} 5b29669228c5573b5dc7dcb67453c45d7cebdfdd out}"
Aug 11 07:30:49 sentry0 gaiad[8700]: E[08-11|07:30:49.227] Connection failed @ sendRoutine              module=p2p peer=5.135.2.82:26656 conn=MConn{5.135.2.82:26656} err="pong timeout"
Aug 11 07:30:49 sentry0 gaiad[8700]: I[08-11|07:30:49.228] Stopping MConnection                         module=p2p peer=5.135.2.82:26656 impl=MConn{5.135.2.82:26656}
Aug 11 07:30:49 sentry0 gaiad[8700]: E[08-11|07:30:49.228] Stopping peer for error                      module=p2p peer="Peer{MConn{5.135.2.82:26656} e4e20e7d2e5ca67b5f5f264e20dc1d94ea77945c ou...="pong timeout"
Aug 11 07:30:49 sentry0 gaiad[8700]: I[08-11|07:30:49.228] Stopping Peer                                module=p2p peer=5.135.2.82:26656 impl="Peer{MConn{5.135.2.82:26656} e4e20e7d2e5ca67b5f5f2...4ea77945c out}"
Aug 11 07:30:49 sentry0 gaiad[8700]: I[08-11|07:30:49.261] Stopping gossipDataRoutine for peer          module=consensus peer="Peer{MConn{5.135.2.82:26656} e4e20e7d2e5ca67b5f5f264e20dc1d94ea77945c out}"
Aug 11 07:30:49 sentry0 gaiad[8700]: I[08-11|07:30:49.291] Stopping gossipVotesRoutine for peer         module=consensus peer="Peer{MConn{5.135.2.82:26656} e4e20e7d2e5ca67b5f5f264e20dc1d94ea77945c out}"
Aug 11 07:30:49 sentry0 gaiad[8700]: I[08-11|07:30:49.686] Stopping queryMaj23Routine for peer          module=consensus peer="Peer{MConn{5.135.2.82:26656} e4e20e7d2e5ca67b5f5f264e20dc1d94ea77945c out}"
```

Of course, even when `gaiad` is operating normally errors such as the above occur when communicating with bad peers.

**Config (you can paste only the changes you've made)**:

`pex = true`
`seed_mode = true`

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**
N/A - not a consensus bug

**Anything else we need to know**:
When I set `pex = false` and `seed_mode = false` in `~/.gaiad/config/config.toml` I do not have this issue with `gaiad`

This issue was moved from https://github.com/cosmos/cosmos-sdk/issues/1946

**Comment by ebuchman** [comment]
Thanks for the report. Have you seen it with `pex=true` and `seed_mode=false` ?

**Comment by gojun077** [comment]
I will test with `pex=true` and `seed_mode=false` on another sentry node and let you know the results.

**Comment by gojun077** [comment]
This error no longer seems to occur in tendermint `v0.23.0` (cosmos-sdk `v.0.24.1`). Closing issue.
