### ISSUE TITLE
Closed issues

### ISSUE THREAD

**Issue by tomtruitt** [tendermint/tendermint#222]
I this list can be cleaned up maybe?

**Comment by ebuchman** [comment]
hm? did you just open an issue asking us to clean up our issues?!

**Comment by tomtruitt** [comment]
Ha is that a faux pas? My bad! Trying to see what is open and not and getting confused. I imagine a lot of people will be examining this stuff now. Meant it outta love brotha

**Comment by ebuchman** [comment]
Cool. Appreciated. Made some updates (see slack for live feed). Gonna close this.
