### ISSUE TITLE
Choosy validator problem

### ISSUE THREAD

**Issue by b00f** [tendermint/tendermint#2220]
Consider I am a validator and now is my turn to make a block in the current height. I should make a proposal and send to other validators to vote on it. The problem is I am a "choosy validator". It means I don't like to pick up all transactions. I just like to include some specific transactions base on my taste. How can I do it with the current implementation?

The return of `CheckTx` simply says that the transaction is correct or not. I am looking for third option. The transaction may be correct but I am not interested to pick it up. 
I hope I could explain my idea....

**Comment by ValarDragon** [comment]
Supporting this is post launch, and still up for discussion. This is in effect censoring things on chain. 

I think one way to do this would be to add a priority function to abci txs, and have these not be committed in any Merkel root. Then you can mod the sdk to achieve this. (This has utility outside of censorship, e.g. you want to optimize your mempool profits based on a different metro than the default. Priority could account for ed255 sigs vs secp in a situation where you feel gas costs don't adequately handle it, etc.)

**Comment by b00f** [comment]
Application can give a weight to each tx (let's call it priority). I think it is a good solution.
I also don't understand why abci tx has involved in Gas. Application should handle if a tx run out of the gas.

Let me know if you need a hand on doing it. I am pleased to help you on implementing it.
