### ISSUE TITLE
node:state copy nil

### ISSUE THREAD

**Issue by xieyiwen** [tendermint/tendermint#2223]
**Tendermint v0.23** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**101.132.96.156:26657** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
CentOS 7 X64
- **Install tools**:
docker

- **Others**:

**What happened**:
invalid memory address or nil pointer dereference

**What you expected to happen**:
i running five node in my Cloud Elastic Compute Service

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```shell
vendor/github.com/tendermint/tendermint/types.(*ValidatorSet).Copy(0x0, 0xc420157a70)
        /Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/types/validator_set.go:76 +0x29
vendor/github.com/tendermint/tendermint/state.State.Copy(0xc4208232f0, 0xe, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/state/state.go:68 +0x8c
vendor/github.com/tendermint/tendermint/node.NewNode(0xc420095320, 0x11f8fc0, 0xc4201c0280, 0x11ebfe0, 0xc420730660, 0xc42015e570, 0x1158508, 0xc42015e580, 0x11f7700, 0xc42015e5a0, ...)
        /Users/envin_xie/gopath/src/universe-chain/src/vendor/github.com/tendermint/tendermint/node/node.go:268 +0x13ff
p/cmd/yuanbenlian/commands.glob..func4(0x1743120, 0xc4207a0030, 0x0, 0x3, 0x0, 0x0)
```
**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by melekes** [comment]
Are you trying to run Tendermint 0.23 with an old state (created by Tendermint < 0.23)? 0.22.X and 0.23.0 are not compatible. Have you run `tendermint unsafe_reset_all`?

**Comment by xieyiwen** [comment]
solution：change go-amino's version to v0.10.1
