### ISSUE TITLE
rename tmsp -> bcgi ?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#223]
Possible names:
- BCGI: Blockchain Gateway Interface (like CGI, the common gateway interface for webservers)
- BGI: same as above
- BPI: Blockchain Programming Interface (like API)
- BAPI: Blockchain Application Programming Interface

I'm leaning towards BCGI

**Comment by mdyring** [comment]
I am not sure the G(ateway) part of CGI makes a lot of sense, plus CGI seems in this day and age a rather date technology.

I'd vote for BAPI in favor of BCGI as most people understand "API".

**Comment by jaekwon** [comment]
We might regret it if BAPI is better used to describe something else, like the client facing API.  Also, noobs will ask us how to use BAPI from javascript. I vote for BCGI.

**Comment by jaekwon** [comment]
Greg Schepers suggested Serverside Blockchain API.  SBAPI.
Later we can have CBAPI, if we want?

**Comment by silasdavis** [comment]
I like TMSP, I think I see that you're trying to broaden the implied applicability, but TMSP does encapsulate a certain view of a blockchain app, even if that goes beyond TMBFT.
declared

In any case, CGI just has bad vibes (who uses that now?), and only a mother could love SBAPI.

If you changed it to TSP, then everyone could call it "Teaspoon".

**Comment by jaekwon** [comment]
Hah! <3 Teaspoon.

**Comment by ebuchman** [comment]
ahaha teaspoon! its like the consensus logic spoonfeeds txs to the application ....

**Comment by ebuchman** [comment]
ABCI it is !

**Comment by tomtruitt** [comment]
I'll miss tmsp 😭

**Comment by tomtruitt** [comment]
the king is dead! long live the king!
