### ISSUE TITLE
Tendermint "modes"

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2237]
Consider implementing "modes" of the Tendermint node with particular settings of the configuration to simplify the config surface exposed to users.

This could include at least the following modes:
- dev/unsafe
- seed
- full
- sentry
- validator

**Comment by marbar3778** [comment]
Quick go at possible modes, any feedback is appreciated. 

**Unsafe**
- all reactors
- rpc (expose all routes)
**Fullnode (default)** 
- Not defining a sentry node here as this is not something TM knows about
- all reactors
- rpc (secure set of rpc connections)
- No privval.json
**Seed**
- P2P
- Blockchain
- State
- Evidence
- Lite
- rpc (secure set of rpc connections)
   - could possibly be reduced even more
**Seed —stripped**
- https://gitlab.com/polychainlabs/tenderseed
- https://github.com/tendermint/tendermint/issues/1686
- P2P
**Validator**
- all reactors
- rpc (secure set of rpc routes)
- Two options for privval
    - On init you create a privval.json
    - On init no privval is created and you must do subsequent steps to create a privval.json (preferred)

**Comment by ebuchman** [comment]
Great start - what about normal full node?

Also what should default of `tendermint init` be ? I would say full node.

Then maybe we have like `tendermint init validator` and some flags for controlling the initialization.

Also we might anyways want to move key material into a `~/.tendermint/keys` dir instead of leaving it in `config`. The `config` could/should continue to contain pubkey info, but the privkeys should live elsewhere.

**Comment by marbar3778** [comment]
>Great start - what about normal full node?

is normal full node different than > **Fullnode (default)**

**Comment by thanethomson** [comment]
So the idea is to have all modes built into a single binary, and config will determine which mode to instantiate?

**Comment by marbar3778** [comment]
yes a single binary, dont think it would make sense to ship have multiple binaries, at least for now. The config will be the same for now, I believe, with some minor changes for the key as mentioned by bucky. When you run `tendermint init` this would default to fullnode and then `tendermint init validator` would init a validator.  It could be just different `node.go` files.

**Comment by jackzampolin** [comment]
Very excited to see this moving forward. This would be a huge win for operators.

**Comment by marbar3778** [comment]
There is interest in a stateless node. This would have to be thought out, but I can see the benefits from it.

**Light Node(stateless)**
- Most reactors (without state)
- rpc (secure set of rpc connections)
- No privval.json

**Comment by ebuchman** [comment]
> is normal full node different than > Fullnode (default)

Whoops yes.

> There is interest in a stateless node

Interesting - sounds similar to a sequential light client, just one that's participating in gossip. Not sure yet if that might open some attacks at the gossip layer ...

**Comment by dlguddus** [comment]
Hi. We planned to implement #4059 to provide validators better risk management feature. @marbar3778 suggested to relate this issue to generalize our spec. 

I think it is a great abstraction to have modes, but it looks like not an imminent feature to implement at the moment. We will comeback to this issue after 1~2 months when we finalize other implementations.

**Comment by melekes** [comment]
"For sentries they should still ask the seed nodes for peers on their first startup, even if they already have a persistent peer." https://github.com/tendermint/tendermint/issues/2086

**Comment by marbar3778** [comment]
With the addition of state-sync and block pruning the default full node mode may have to broken into two different node types. A full node now means both archival node and a node that has pruned blocks. Two new modes may be full archival that would state-sync then back-fill or fast-sync from genesis and node, which will just be a node with pruned blocks

**Comment by dongsam** [comment]
> With the addition of state-sync and block pruning the default full node mode may have to broken into two different node types. A full node now means both archival node and a node that has pruned blocks. Two new modes may be full archival that would state-sync then back-fill or fast-sync from genesis and node, which will just be a node with pruned blocks

In [ADR 052: Tendermint Mode](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-052-tendermint-mode.md) defined before [state-sync](https://github.com/tendermint/tendermint/pull/4705) is added, there are three types mode: fullnode, validator, and seednode. Should we add new mode called `archival` node which be added `statesync.Reactor` to fullnode? I am currently developing ADR-052

**Comment by dlguddus** [comment]
> With the addition of state-sync and block pruning the default full node mode may have to broken into two different node types. A full node now means both archival node and a node that has pruned blocks. Two new modes may be full archival that would state-sync then back-fill or fast-sync from genesis and node, which will just be a node with pruned blocks

I think for state-sync, there should exist various options to be chosen, and those options should be controlled by configure but not by defining them into separate modes. I think fullnode or validator node will both wants to customize its state-sync options, and I feel this is not the dimension of "mode", but it should be dimensions of "node configuration". 

I imagine different kinds of option such as, 
"only state-sync from persistent peers or private peers"
"only provide snapshot to persistent peers or private peers"

these are customizing configure and not for separate "mode" i believe.

How do you think? @marbar3778

**Comment by marbar3778** [comment]
I think for now since we have a way to backfill then what is in the ADR is fine. Just state sync should be added to the modes that need it (validator, full node)

**Comment by erikgrinaker** [comment]
Modes should probably be designed in tandem with #4644.

**Comment by dongsam** [comment]
> Modes should probably be designed in tandem with #4644.

@erikgrinaker When do you think about #4644's development schedule? 
the alpha version for Modes has already been completed based on [ADR 052](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-052-tendermint-mode.md), and we were planning to open the PR after complete the development detail by next week, should we redesign it?

**Comment by erikgrinaker** [comment]
We haven't hashed out a post-Stargate roadmap yet, but possibly within the end of the year.

I think modes will work as a layer on top of phases, such that the reactors/components being enabled will be the intersection of the mode and phase. I suggest you keep working on the PR, and we can discuss this further during code review - phases can be added on later.

I'm not sure what the best approach would be in terms of combining them, but we may want to translate modes into concrete settings instead of having mode switches everywhere, and do something similar with phases, to avoid combinatorial explosion. But this is something that can be refactored later as well, when we have a better sense of what we need.

**Comment by cmwaters** [comment]
Having finished up the tendermint modes work (see here https://github.com/tendermint/tendermint/pull/6241 and here https://github.com/tendermint/tendermint/pull/6061) are there any outstanding aspects that we want to address or should we close this issue

**Comment by marbar3778** [comment]
Looks good to me!! Let's close this, we can open new issues that encapsulate other things that need to be done if any
