### ISSUE TITLE
Deterministic build: Lock binary dependencies

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2238]
Our Makefile uses a `GOTOOLS` array to list the binary dependencies written in Go that can be easily fetched/built with `go get`, however it doesn't provide any way to specify which version of said binaries to use.

This can lead to unwanted changes due to updated binaries, eg. when updating ABCI - https://github.com/tendermint/tendermint/pull/2159#discussion_r210593697

**Comment by ebuchman** [comment]
What's the deal with the protobuf output there anyways, with all the `XXX` prefixed struct fields. Is that really what we want?

**Comment by silasdavis** [comment]
You can remove a lot of that with gogo proto: https://github.com/gogo/protobuf/blob/master/extensions.md (search XXX).

**Comment by ebuchman** [comment]
Closing for #2550
