### ISSUE TITLE
RoundState can be marshalled to JSON, but not unmarshalled

### ISSUE THREAD

**Issue by silasdavis** [tendermint/tendermint#2241]
[`RoundState`](https://github.com/tendermint/tendermint/blob/master/consensus/types/round_state.go#L60) can be marshalled by amino as is done by the consensus RPC but cannot be unmarshalled. The problematic field is `Votes` where `HeightVoteSet` does it's own thing with various bit fields for human readability: https://github.com/tendermint/tendermint/blob/master/consensus/types/height_vote_set.go#L238-L253.

Ideally this text format should be reversible by a `UnmarshalJSON` method or be produced by something other than `MarshalJSON`

**Comment by tessr** [comment]
I _think_ this should be fixed by the removal of Amino. Closing for now, let me know if the issue persists.
