### ISSUE TITLE
Add evidence through RPC

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2252]
Currently evidence is only added to the evidence pool from the consensus layer, as this is typically where evidence is first detected. However evidence can also potentially be detected by light-clients and we need to provide a way for them to submit that to nodes. We should add a new `/broadcast_evidence` endpoint (open to better naming) that takes all the relevant information - height, round, validator address, blockID, and two conflicting signatures.

As part of this, we should also add a tool for generating conflicting signatures to simplify testing. cc https://github.com/cosmos/cosmos-sdk/issues/2111

**Comment by jackzampolin** [comment]
I think following our endpoint naming this would be part of the slashing module and would be called:

```
POST /slashing/validators/{validator_addr}/evidence
```

**Comment by ebuchman** [comment]
Maybe in the SDK's REST API. But Tendermint doesn't have a REST API surface, so would be different here: https://tendermint.github.io/slate/

**Comment by jackzampolin** [comment]
Ah! Thats right. This is on the wrong repo 🙊

**Comment by mossid** [comment]
`report_evidence` for the name?

**Comment by ebuchman** [comment]
Perhaps we stick with `/broadcast_evidence` for consistency with `/broadcast_tx_` ?

**Comment by ebuchman** [comment]
Note we shouldn't call the endpoint `duplicate_vote`. It should just be `broadcast_evidence` and should take an `Evidence` interface, since we're going to need to support new types of evidence (eg. at least #3244) very soon.

**Comment by melekes** [comment]
> As part of this, we should also add a tool for generating conflicting signatures to simplify testing. cc cosmos/cosmos-sdk#2111

This part is still missing.

**Comment by ebuchman** [comment]
Closing for #3913
