### ISSUE TITLE
/dial_peers should not drop existing connections

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#2253]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
gaia v0.24.0

**What happened**:
Calling /dial_peers RPC with an existing peer leads to a disconnect and re-dial of said peer.

**What you expected to happen**:
Since a connection is already established, I'd expect nothing to happen and the dial request to be silently ignored. For bonus points the RPC could return a status indicating it was ignored.

**Why is this useful?!**
It is well suited for [home-baked peer discovery](https://forum.cosmos.network/t/sentry-node-architecture-overview/454/44?u=mdyring), for instance in a sentry node setup.

**Comment by ebuchman** [comment]
It leads to disconnection of the existing connection? Or it attempts to dial the peer again and disconnects the new connection?

**Comment by mdyring** [comment]
Mmm, that is not clear to me since I just noticed the log message. 

If https://github.com/tendermint/tendermint/commit/684a7457cf2569c6d054e5906d76d8566b43249b is included in the next gaia release, I will test again and see if the issue remains. :-)
