### ISSUE TITLE
Is is possible to sniff encrypted network packets? And is it correct "duplicated peers"?

### ISSUE THREAD

**Issue by GiovanniCapizzi** [tendermint/tendermint#2254]
I need for an educational project in my University to see what happens between nodes in tendermint. I'm trying using 4 virtual machine (virtualbox) attached to a internal bridge connection in my computer and wireshark to see TCP packets. I read about the feature auth_enc which was removed June of this year. How can I see traffic through the network to reach consensus of network?

Every machine is configured with a static ip and with testnet command. Every node has it own configuration (node 0,1,2,3) and they communicate regularly. I also configured the config.toml with fixed peers but I have also this problem:

```
[08-21|20:59:41.169] Dialing peer                                 module=p2p address=2126d35e1f027ca29e0ca662c37ef23d9144ff7a@192.168.137.102:26656
I[08-21|20:59:41.171] Error reconnecting to peer. Trying again     module=p2p tries=15 err="Duplicate peer ID 2126d35e1f027ca29e0ca662c37ef23d9144ff7a" addr=2
126d35e1f027ca29e0ca662c37ef23d9144ff7a@192.168.137.102:26656
I[08-21|20:59:42.840] Dialing peer                                 module=p2p address=6281e2a8ba7bcfe6e5553911aff19c37911e013f@192.168.137.103:26656
I[08-21|20:59:42.845] Error reconnecting to peer. Trying again     module=p2p tries=15 err="Duplicate peer ID 6281e2a8ba7bcfe6e5553911aff19c37911e013f" addr=6
281e2a8ba7bcfe6e5553911aff19c37911e013f@192.168.137.103:26656
I[08-21|20:59:43.472] Ignoring inbound connection: error while adding peer module=p2p address=192.168.137.100:48588 err="Duplicate peer ID 8078fda83179be725b8
fe64b953fe880e7dd97f7
```

But they seems to exchange data regularly infact I ask with a ABCI query (with some key, value) to each node, it gives me "exits"

**Comment by ebuchman** [comment]
> I read about the feature auth_enc which was removed June of this year. 

It used to be that folks could set `auth_enc=false` if they didn't want to encrypt the connections. We decided to remove that so the connections are always encrypted.

> How can I see traffic through the network to reach consensus of network?

If you set the `--log_level=debug`, you should see all messages. But I don't think there's a way to do it with external tools because you have to decrypt the messages.

> with fixed peers but I have also this problem:

It's not necessarily a problem, since sometimes we try to connect to peers we already have. If every node has connections to 3 others (check `/net_info`) and they're making blocks, everything is working.

Does that answer all your questions?

**Comment by GiovanniCapizzi** [comment]
Yes, that's resolve almost everything, thank you! I also just found a solution to see traffic through my virtual box machines :) it's encrypted but if  `--log_leve=debug` works it's quite enough. Let me try this and I will update this post, then we can consider this as closed 👍 

![immagine](https://user-images.githubusercontent.com/18178022/44435219-3d3bf700-a5af-11e8-890a-2d8935f7e850.png)

**Comment by GiovanniCapizzi** [comment]
I enabled logs and I think that will be enough to comment packet exchanges between my machines, thank you. If there is also other that could be useful for this situation please let me know, otherwise you can set this to closed. Thank you so much for your answer!

**Comment by ebuchman** [comment]
By default the "peer exchange" (pex) reactor is active and tries to find more peers by constantly querying other peers. If you don't know about enough peers, it will always try to find "more addresses" by sending "pexRequest" message to a random peer. See details in the [specification](https://github.com/tendermint/tendermint/blob/master/docs/spec/reactors/pex/pex.md) and the [code](https://github.com/tendermint/tendermint/blob/master/p2p/pex/pex_reactor.go#L362).

Let me know if I should re-open the issue, or feel free to open another.

Also, would love if you told the community about what you're working on over on the forum: https://forum.cosmos.network/

Cheers!
