### ISSUE TITLE
Close connection when stopping WsClient.

### ISSUE THREAD

**Issue by ruseinov** [tendermint/tendermint#2258]
Currently we are using a WsClient in this manner, to monitor tendermint and collect metrics:
```
func(c *rpcClient.WSClient) error {
		if c.IsRunning() {
			c.Stop() // panics on close c.ResponsesCh when not started (=nil)
		}
```
But `c.Stop()` does not close the underlying connection, which results in tendermint logging these errors:
```
E[08-22|09:35:58.903] Error closing connection                     module=rpc-server protocol=websocket remote=127.0.0.1:52428 err="close tcp 127.0.0.1:46657->127.0.0.1:52428: use of closed network connection"
```

My proposal would be to add `c.conn.Close()` to `func (c *WSClient) OnStop() {}` or `Stop()` .
I can contribute this myself too.
Let me know what you think.

FYI @ethanfrey

**Comment by bradyjoestar** [comment]
I got the same error when I bring up a lite-proxy and close it.
```
E[08-22|14:42:06.760] Failed to read request                       module=rpc-server protocol=websocket remote=127.0.0.1:60420 err="websocket: close 1006 (abnormal closure): unexpected EOF"
E[08-22|14:42:06.761] Error closing connection                     module=rpc-server protocol=websocket remote=127.0.0.1:60420 err="close tcp 127.0.0.1:26657->127.0.0.1:60420: use of closed network connection"

```

**Comment by ethanfrey** [comment]
I agree we should close the underlying connection. I worked on some of this code many moons ago, but the ws connection was working before I touched it and I never really played with the disconnects.

I have seen those messages like @bradyjoestar before but always assumes the client didn't try to close. As @ruseinov shows, it happens even with well-behaved clients. It would be good to get a little more polish on the websockets, as this is the only way to get events as well.

@xla were you working on this as well?

**Comment by ruseinov** [comment]
@ethanfrey I would be glad to contribute this small fix if the decision is to move forward.

**Comment by ValarDragon** [comment]
Please do contribute a PR! I can't see a significant reason why we wouldn't want to close the session, so seems like a bug to me.

**Comment by ruseinov** [comment]
@ValarDragon will do

**Comment by melekes** [comment]
See discussion in the PR https://github.com/tendermint/tendermint/pull/2271#discussion_r212797222

**Comment by melekes** [comment]
> But c.Stop() does not close the underlying connection, which results in tendermint logging these errors:
> E[08-22|09:35:58.903] Error closing connection                     module=rpc-server protocol=websocket remote=127.0.0.1:52428 err="close tcp 127.0.0.1:46657->127.0.0.1:52428: use of closed network connection"

the error indicates an attempt to close already closed connection (e.g. second, third attempt, client trying to close conn closed by the server earlier).

**Comment by melekes** [comment]
Have you managed to replicate the issue? **By issue here I mean `client.Stop()` not closing the underlaying connection.**

**Comment by ruseinov** [comment]
Hello @melekes, haven't had the time to dig into it yet. tests seem to pass and we were also using older versions of tendermint, so I would close this one and revisit if it pops up again.

**Comment by melekes** [comment]
Ok, fair.
