### ISSUE TITLE
crypto: Endianess of nonce in secret connection

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#2263]
Currently, the nonces used in secret connection are 12 bytes / 96 bits and basically a big endian encoded counter:
https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/p2p/conn/secret_connection.go#L335-L344

For the sake of consistency (ChaCha20 is all little endian) it would be great to change the nonce encoding to little endian, too.

Additionally to that, a counter using a simple 64-bit (unsigned) integer should be sufficiently large. It will not overflow in practice and we should have rekeyed long before it happens.

We should then also encode the chunk size [here] using little endian, too.

Related discussion: https://github.com/tendermint/kms/pull/38#discussion_r212392950

[here]: https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/p2p/conn/secret_connection.go#L125-L127

cc @tarcieri @ValarDragon

**Comment by melekes** [comment]
This is not done, right?

**Comment by Liamsi** [comment]
It actually is: https://github.com/tendermint/tendermint/pull/2264/files#diff-86a753d5ca0a72f329d3e0f4c7ac2895R126
I think this can be closed now.
