### ISSUE TITLE
Bump ABCI version

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2266]
Since ABCI got merged into tendermint, we've been saving the development overhead, but we've failed to independently increment the version for the abci-cli. This is potentially the cause of https://github.com/tendermint/tendermint/issues/1709#issuecomment-415568007

The tendermint/version should import the tendermint/abci/version so it's a top level artifact, and we need to make sure we increment it properly for changes to abci-cli (and ABCI). 

Tagging https://github.com/tendermint/tendermint/pull/2160

**Comment by zramsay** [comment]
why not drop the seperate abci version and sync it  with tendermint? same for tools binaries.

cc #1908

**Comment by ValarDragon** [comment]
I think we should consider moving ABCI back into its own repo postlaunch. We want anyone to be able to implement their own consensus protocol with fast-finality that inherits ABCI, to then be able to use our state machine. (e.g. someone can make their own hub using dfinity consensus)

**Comment by ebuchman** [comment]
This was done in https://github.com/tendermint/tendermint/pull/2343.

> I think we should consider moving ABCI back into its own repo postlaunch. We want anyone to be able to implement their own consensus protocol with fast-finality that inherits ABCI, to then be able to use our state machine. 

Sure, that was the reason it was its own repo for so long, but its not worth the multi-repo overhead while its still changing. Once it stabilizes and we stop making breaking changes and have a better sense of how to plug in another consensus, we can consider moving it back out. 

Meanwhile, it doesn't really make a difference whether you're importing `github.com/tendermint/abci` or `github.com/tendermint/tendermint/abci` ...
