### ISSUE TITLE
deprecate readthedocs

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2267]
RTD content is outdated. Now that we have https://tendermint.com/docs/, we should reduce the RTD content to a single page that says the docs have moved and provide the link. Is there a way to do this without breaking all the existing RTD links?  @zramsay

**Comment by zramsay** [comment]
In #2280 and by setting the RTD configuration, this page will show v0.23.0, which has [this file](https://github.com/tendermint/tendermint/blob/v0.23.0/docs/index.rst) which shows the below:

![screenshot from 2018-08-26 09-30-19](https://user-images.githubusercontent.com/8304391/44628710-5c21ec80-a913-11e8-9513-eb884ea182b5.png)

New builds are disabled and previous versions are left as archives.

**Comment by melekes** [comment]
Merged to develop.
