### ISSUE TITLE
Ability to replay txs from LevelDB on startup

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#227]
This would allow an application to not persist its state but just rely on tx replay on startup to restore the last state.

Typical use-case would be to re-initialize the state after code changes / upgrades. It seems a good idea to do a replay vs. letting the app persist the state itself (do snapshots etc), as it will force the upgraded application to demonstrate that it can gracefully process all old txs.

Not knowing the internals of what Tendermint stores, it might be possible to determine the point from where to replay based on the application hash returned in the first commit() after the TMSP connection is etablished.. Alternatively something simple as just passing a commandline parameter which will force this behaviour on initial connect after startup.

**Comment by ebuchman** [comment]
Perhaps the best thing to do is let the app pass some ReplayFromAfterHeight integer in the handshake, and tendermint will replay all txs from after that height.

**Comment by mdyring** [comment]
As I recall, tendermint expects the application to return an empty hash in the initial commit() on startup (otherwise it logs a warning). So I think it would be sufficient, that if the app returns an empty hash, tendermint will replay everything from the beginning.

**Comment by ebuchman** [comment]
I'd rather be explicit and give the option to replay from some height since replaying from the beginning will get crazy on long running apps.

**Comment by mdyring** [comment]
Yeah it would be better, but requires a handshake mechanism :-)

**Comment by ebuchman** [comment]
I think that's a good thing. We can check versions for compatibility and much more.

**Comment by ebuchman** [comment]
This is implemented here https://github.com/tendermint/tendermint/pull/265

Upon connecting, tendermint calls tmsp.Info, which now returns some information about the last block. Tendermint will replay all blocks above the last block.
