### ISSUE TITLE
Slight cleanup of prometheus metrics while adding a couple of new ones

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#2272]
To keep things nice and tidy, I suggest adjusting the name of prometheus metrics to reflect their namespace. Specifically:

consensus_* -> tendermint_consensus_*
mempool_size -> tendermint_mempool_size
p2p_peers -> tendermint_p2p_peers

If the Gaia App then wants to expose metrics, it can use gaia_*.

Some additional metrics would be very helpful. So for bonus points:
* Add tendermint_latest_block_height corresponding to /status sync_info instead of (or in addition to) tendermint_consensus_block_height.
* Add tendermint_catching_up (0/1), combined with above makes keeping an eye on syncing nodes easier.
* Add (tagged per peer) tendermint_p2p_peer_receive_bytes_total, tendermint_p2p_peer_transmit_bytes_total
* Add per peer bytes data waiting in transmit buffer: tendermint_p2p_peer_pending_transmit_bytes (useful for diagnosing "Send failed" instead of spamming the log)

For platinum membership:
* Histograms providing (per peer) similar information as /net_info SendMonitor and RecvMonitor.

**Comment by jackzampolin** [comment]
The only thing that might be an issue is the cardinality in `tendermint_p2p_peer_transmit_bytes`. The number of peers will be relatively high (~1000s), but I understand it's needed for debugging, and can be managed.

Would love to see these stats!

**Comment by xla** [comment]
For the first part of the request I would like to expand on why I think prefixing is not coming with any gains. Gaiad embeds tendermint and by transitive property offers its surface each of the current prefixes (consensus, mempool, p2p) are vital parts of the binary, indiscriminately of the origin. The proposed additional prefixes would only be meaningful if we assume potetntial collision, which is not foreseeable as the cosmos-sdk codebase would have additional consensus, p2p, etc. metrics to expose. Having tendermint as a prefix in the metrics of a Gaiad binary is just leaking information.

@mdyring Your line of argumentation is that it is clean/tidy, could you expand on this given my points from above?

**Comment by mdyring** [comment]
Absolutely, I mean clean/tidy from the perspective of the end-user and not from a software development perspective (for which I agree with your points above).

From an end-user perspective: when running Prometheus today, the metric names used today are mixed in between all other metrics that are scraped from other nodes. So not just those running gaia for instance.

Usually metrics are presented to the user as a list, so it is helpful to have a prefix to make it clear which metrics are logically grouped together:

![prometheus-metrics](https://user-images.githubusercontent.com/18033781/44906559-8a3d6d00-ad15-11e8-9818-b9a600314ce9.png)

A good reference is https://prometheus.io/docs/practices/naming/ for guidelines on naming.

**Comment by xla** [comment]
@mdyring I see your point, this is indeed a problem. Tendermint should provide a default prefix and when embedded by other software (e.g. Gaia) should accept a different prefix as part of the configuration.

**Comment by ValarDragon** [comment]
> The number of peers will be relatively high (~1000s), but I understand it's needed for debugging, and can be managed. Just something to keep in mind when adding tags.

I don't think having nodes manage 1000 peer connections is planned, or potentially ever feasible. We would have to restructure the tx broadcast model very heavily for this to work at that scale, so it likely isn't on the table for awhile. So this metric may be reasonable to add.

**Comment by mdyring** [comment]
![image](https://user-images.githubusercontent.com/18033781/48301876-e16d7400-e4f4-11e8-9ada-898edff9f3a8.png)

Thanks for the nice new metrics. :-)
