### ISSUE TITLE
ABCI, mempool: Add priority function

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2275]
The ABCI Priority function is so that given a tx, the mempool can query the application for what the fee and the gas for the provided tx is. (This could optionally provide message type, and signature type as well. The result of Priority should not appear in state, so full nodes could adjust this)

Then in the mempool, we would have a function which takes the size of a tx, allocated gas, and it will return whether or not the fee is sufficient to be placed in the mempool. This is yet another check that can happen before the ABCI Check. This check would also be enforced in rechecking.

e.g.
```
// size = len(tx)
func (mem *Mempool) SufficientFee(res <abci query response>, txSize int) bool {
// Parameters chosen to illustrate the point, not actually suggested implementation
  if res.Fee > 1000 + res.Gas*10 + txSize*5 {
   return true
 }
return false
}
```
The purpose of making it a separate function is to ease tuning this / doing fancier things like basing it off a rolling average of the last 1000 txs totally feasible. (Any full node could just edit this function)

/cc @ebuchman we discussed adding the priority function prelaunch in a way so that we can test ABCI protobuf upgrades on a live network. We want this included prelaunch, just so that mempool sorting can be done in a non-breaking manner. (#2147)

**Comment by ebuchman** [comment]
Seems we can close this, but we do want to add Priority field to ResponseCheckTx https://github.com/tendermint/tendermint/issues/1861
