### ISSUE TITLE
Handling changed file permissions 

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#2285]
In autofile and in fsdb files are created with read-write permissions for the file owner (`0600`). If they are opened again, we do not check if the same restrictve file permissions still hold:

https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/libs/autofile/autofile.go#L116-L123

and:

https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/libs/db/fsdb.go#L202-L206

We should at least check that the permissions did not change (e.g. by accident) and enforce the intended perms (via chmod). Another approach would be to error in this case and tell the user to change the file perms (to make the user aware that sth. funky has happend here).

Will submit a small PR for both cases which silently fixes the permission in case they were changed.

(see https://github.com/tendermint/security/issues/5 and https://github.com/tendermint/security/issues/1)

**Comment by melekes** [comment]
See https://github.com/tendermint/tendermint/pull/2286#issuecomment-418281846

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/2286
