### ISSUE TITLE
libs: clist should explictly fail if max list len is reached

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#2288]
In the unlikely case that someone plans to use the linked-list implementation in libs/clist in a way which would lead to overflow max `int` it will behave funky as the underlying `len` field (an `int`) would wrap around. It is used in the mempool and the mempool can be configured to have a certain max. TX len. The input isn't validated yet and the config could theoretically impose a maximum which is larger than a clist can hold: https://github.com/tendermint/tendermint/issues/2232 

IMHO, even if the config is validated, it is  reasonable to be explicit about how many elements a clist can hold (and fail if someone tries to exceed that). This can be achieved by checking if `len` < `MaxInt ` before pushing new elements. (Even though we might run out of memory before seeing this ever happen).

Also, it could be reasonable to change the `len`type from `int` to `uint`.

https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/libs/clist/clist.go#L298-L319

See also: https://github.com/tendermint/security/issues/2

**Comment by melekes** [comment]
Merged to develop.
