### ISSUE TITLE
crypto: Use CombinedMult to speedup Secp256k1 verification

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2290]
In ECDSA you calculate `u_1*G + u_2*Pubkey`. There are standard algorithms to compute this faster than performing each operation individually. In fact, the golang ECDSA verification will automatically use this function if the curve has such a method, and it is named "CombinedMult". We should implement this, and cache in the verification speed savings. (This is quite standard for most elliptic curves to implement, I'm actually surprised ours doesn't)

**Comment by marbar3778** [comment]
closing as secp has moved to the SDK

**Comment by ValarDragon** [comment]
(moved to https://github.com/cosmos/cosmos-sdk/issues/7052)
