### ISSUE TITLE
Support read-only operations on GoLevelDB

### ISSUE THREAD

**Issue by alessio** [tendermint/tendermint#2292]
Not all CLI commands in `gaiacli` require to acquire locks on the storage backends. Though presently the only way to create a `github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/db.GoLevelDB` instance is calling `NewGoLevelDB()`, which in turn calls `github.com/syndtr/goleveldb/leveldb.OpenFile()` with `nil` flags.

I'll propose a patch shortly.

**Comment by jackzampolin** [comment]
This is needed to address key database locking issues in the SDK. I think this approach is a good one.

**Comment by alessio** [comment]
Sure, e.g.:
* https://github.com/cosmos/cosmos-sdk/blob/develop/client/keys/list.go#L39

It should be required to acquire a lock to just listing keys.

**Comment by melekes** [comment]
Merged to develop.
