### ISSUE TITLE
Fix specification issues in the paper

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2297]
https://github.com/tendermint/spec/issues/37
https://github.com/tendermint/spec/issues/36

https://github.com/tendermint/spec/issues/22
https://github.com/tendermint/spec/issues/21
https://github.com/tendermint/spec/issues/20

**Comment by milosevic** [comment]
PR is here https://github.com/tendermint/spec/pull/38.

**Comment by ebuchman** [comment]
@milosevic good to close this?
