### ISSUE TITLE
Specify min/max amount/time of transactions per block

### ISSUE THREAD

**Issue by wolfposd** [tendermint/tendermint#230]
Would be nice to speicify a minimum or maximum amount of transactions in the config file per block.
Currently Tendermint "spams" blocks with 0 transactions.

Or otherwise configure a time in between block-creations, like one block every ~5 seconds

**Comment by ebuchman** [comment]
you can configure approximate time (in milliseconds) between blocks by setting `timeout_commit = 5000` in the config. Not making blocks if there are no transactions is a little trickier, as we'd probably need to implement an additional heartbeat mechanism. Something for us to keep in mind for sure.

**Comment by srmo** [comment]
Is there a reason why we would want empty blocks at all?

**Comment by ebuchman** [comment]
Other than as a heavy-weight pulse, no I don't think so. 

As a pulse, there may be things that happen at the end of each block (not from a transaction), and you may want those to happen on a (at least approximately) regular schedule.

**Comment by ebuchman** [comment]
For instance, the logic in the TMSP StartBlock/EndBlock messages, which run every block.

**Comment by srmo** [comment]
Thanks, I see. I was wondering about the "create empty blocks" behavior, as it eats diskspace without actually doing anything.

**Comment by wolfposd** [comment]
> As a pulse, there may be things that happen at the end of each block (not from a transaction), and you may want those to happen on a (at least approximately) regular schedule. 

Shouldnt periodic events be handled by the application itself, as they are usually application-logic dependant and not tied to block-creation?

taking bitcoin as an example, the periods for block-creation are somewhere between 8-15minutes, so anybody running off of bitcoin naturally has their own timer-threads for application logic

**Comment by ebuchman** [comment]
Yes that's right, but only for local, non-deterministic application logic. Any logic that needs to be replicated on every node (ie. stuff that happens in TMSP messages) must pass through consensus, and hence must come in blocks.

**Comment by srmo** [comment]
Seeing it as a heart-beat mechanism is nice, sure. But take 10 nodes running for a year. They would produce 2TB for "heartbeat"-only. That sounds unreasonable. Also, joining nodes after a few days already requires already synching tens of thousands of pure empty blocks. Consider this for a long running chain. Sure, one might argue that a block chain that produces no transactions in a year may be pointless, but I usually refrain from "Will not happen" scenarios.

**Comment by jaekwon** [comment]
10 nodes running for a year is around 10Gb of signatures.  And yes, we'll figure out some pruning system soon.

**Comment by srmo** [comment]
On a sidenote: We are about to do a little demo of our early prototype. This setup will use 2 nodes setup locally and also contain demonstrating loosing one node and entering a transaction on the running node. Now, for demo purposes we can workaround the time required to catch-up after re-starting the 2nd node, but it will get hard to explain in the long run, why empty blocks would require "so much" time to be replayed, i.e. why empty blocks are there at all. In a simple run through, it takes the re-started node 10-30 seconds to catch up, depending on how long it was down, how long it took the demonstrator to enter the transaction.
A workaround for potential production-use is to have several nodes per customer, to avoid this catch-up lag.

This is also related to https://github.com/tendermint/tendermint/issues/183

If there's anything we as Tendermint/GO Newbies can do to help in adding this enhancement, let us know.

**Comment by AaronShea** [comment]
+1 to this issue. The number of empty blocks hinders the possible application of an idea I plan to use Tendermint for. Keeping the chain size down is something I think should be kept in mind, as clients may not like the idea of having huge amounts of data that is "useless" to them.

**Comment by ebuchman** [comment]
Closing in favor of https://github.com/tendermint/tendermint/issues/246
