### ISSUE TITLE
Tx indexing flag doesn't show actual indexing behaviour

### ISSUE THREAD

**Issue by faboweb** [tendermint/tendermint#2304]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
SDK 0.24.2

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
The status node_info.other.tx_index doesn't show actual indexing.

Example (on Gaia 8001):
103.72.145.36:26657 shows tx-index=on but doesn't index txs.
195.201.141.141:26657, 51.38.113.60:26657 shows tx-index=on and indexes txs.

**What you expected to happen**:

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by xla** [comment]
Validated locally that the information reported in the status endpoint is correct and reflects the configuraiton.

Additionally queried for one of the transactions in question and could confirm it is present on one of the nodes: http://195.201.141.141:26657/tx?hash=0x04C9AE23F7054F768376502813C9BAD30758805E

This endpoint will only return if an indexer is enabled.
https://github.com/tendermint/tendermint/blob/013b9cef642f875634c614019ab13b17570778ad/rpc/core/tx.go#L76-L79

**Comment by ebuchman** [comment]
Confirmed locally that disabling the tx_indexer in the config shows it as `off` in the /status endpoint.

Also can lookup the tx `0x04C9AE23F7054F768376502813C9BAD30758805E` on all nodes listed.

```
103.72.145.36:26657 shows tx-index=on but doesn't index txs.
```

Can you clarify why you think this? Eg. http://103.72.145.36:26657/tx?hash=0x04C9AE23F7054F768376502813C9BAD30758805E seems to work

**Comment by faboweb** [comment]
The error shows when using the Cosmos SDK - LCD to query for my txs using the `/txs` endpoint: `/txs?tag=recipient_bech32=%27cosmosaccaddr1falnyplarnyy06uyazsfmu3tv4wf26lgqnxy6w%27`

**Comment by ebuchman** [comment]
Can we close this? Seems to be an issue with the SDK

**Comment by faboweb** [comment]
Sure.
