### ISSUE TITLE
Testing Tendermint performance with BigchainDB V2.0 (tm-bench)

### ISSUE THREAD

**Issue by Amardeepsuri** [tendermint/tendermint#2305]
I am trying to test the performance or throughput of a network with Tendrmint V0.23.0 and BigchainDB V2.0. I already have some initial results setting up a 2 node network which reached about 250 Transactions per second. For this benchmark I used Bigchaindb benchmark tool.

I would now like to use tendermiint's tool which tm-bench to do a similar benchmarking and to verify the results on the same configurations. I did not find any documentations or steps to use tm-bench as such.

I need help to use tm-bench with Docker considering that Bigchaindb and Tendermint containers are running. I basically would like to run tm-bench tool in docker.

Thans in advance for the help in this case.

**Comment by Amardeepsuri** [comment]
Thanks for your reply @melekes . I saw this link earlier, but could not figure out how to run it in docker. Clearly I cannot run tm-bench -T 10 -r 1000 localhost:26657 directly. Do I need to install . additional dependencies before I run this command assuming I already have Tendermint and BigchainDb containers running in Docker?

**Comment by melekes** [comment]
It will look something like

```
docker run -it --rm -v "/tmp:/tendermint" tendermint/tendermint init
docker run -it --rm -v "/tmp:/tendermint" -p "46657:46657" --name=tm tendermint/tendermint
```

I will respond later with more details.

**Comment by Amardeepsuri** [comment]
Thanks, looking forward to more details. I will also give it a try :)

**Comment by melekes** [comment]
Updated my answer.

**Comment by Amardeepsuri** [comment]
Thanks a lot @melekes , I will give it a try :)

**Comment by Amardeepsuri** [comment]
As soon as I run the command 
`docker run -it --rm --link=tm tendermint/bench tm:26657`
It stops my Tendermint container, I have attached a screenshot for it? Can you please suggest me what to do in this case or what changes should I make? Thanks in advance @melekes 
<img width="1325" alt="screen shot 2018-09-03 at 08 48 35" src="https://user-images.githubusercontent.com/40795411/44971590-746aba80-af56-11e8-89b7-92da228e30cb.png">

**Comment by melekes** [comment]
https://hub.docker.com/r/tendermint/bench/ is outdated. you need to build your own image (there a `make build-docker` Makefile target)

**Comment by Amardeepsuri** [comment]
There seems to be some problem with docker build file, I have issues building an image
<img width="741" alt="screen shot 2018-09-03 at 12 14 35" src="https://user-images.githubusercontent.com/40795411/44981505-100a2400-af73-11e8-8b5e-1cf861c232d9.png">
<img width="1257" alt="screen shot 2018-09-03 at 12 14 44" src="https://user-images.githubusercontent.com/40795411/44981552-2f08b600-af73-11e8-9ecf-047acf59cddb.png">

**Comment by melekes** [comment]
You need to execute `make get_tools & get_vendor_deps` https://tendermint.com/docs/introduction/install.html

**Comment by Amardeepsuri** [comment]
I am getting the error `undefined reference to `gccgoRealSyscall'` still on running `make install` command
![screen shot 2018-09-19 at 15 45 19](https://user-images.githubusercontent.com/40795411/45757262-3989a780-bc23-11e8-8d36-fde480037af4.png)

**Comment by melekes** [comment]
What is the Go version you're using? Have you tried reinstalling Golang?

**Comment by Amardeepsuri** [comment]
I am using version 1.10 and I tried to reinstall it. Should I move to version 1.11?
![screen shot 2018-09-20 at 11 00 33](https://user-images.githubusercontent.com/40795411/45807785-8bced500-bcc4-11e8-950e-362710db7447.png)

**Comment by melekes** [comment]
Have you tried installing `gcc` (`sudo apt-get update && sudo apt-get install gcc`)? From the looks of it, the error seems to be related to missing C import

**Comment by Amardeepsuri** [comment]
Still facing some problems, maily with setting $GOPATH and $GOROOT, can you suggest what values should I use for them?

**Comment by zramsay** [comment]
https://github.com/tendermint/tendermint/wiki/Setting-GOPATH

**Comment by Amardeepsuri** [comment]
Could get tm-bench installation to work.
After running tm-bench command I got the following result-
<img width="626" alt="screen shot 2018-09-21 at 14 26 14" src="https://user-images.githubusercontent.com/40795411/45881141-9368a980-bdaa-11e8-811a-84544de6099e.png">
whereas I could see the transactions in the tendermint logs. What can be the problem here or what am I doing wrong?
Docker ps result-
![screen shot 2018-09-21 at 14 27 08](https://user-images.githubusercontent.com/40795411/45881172-b430ff00-bdaa-11e8-8cd5-0c220b978586.png)

**Comment by Amardeepsuri** [comment]
I am still struggling with the above issue, any help in this regard will be appreciated:) @melekes @zramsay
