### ISSUE TITLE
MaxBytes follow up

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2308]
Original issue to change MaxTxs to MaxBytes: https://github.com/tendermint/tendermint/issues/2035

PR: https://github.com/tendermint/tendermint/pull/2184

Follow up from final review in #2184:

- the computed maximums don't seem right 
- handle TxSize (either remove it or actually enforce it, and allow negative/0 default of maxDataBytes based on BlockSize)
- update the docs
- few other code suggestions in that review

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/2318

**Comment by melekes** [comment]
I think TxSize is a good param to have. Otherwise, you don't have a way to limit incoming txs which can be bad.

**Comment by ebuchman** [comment]
More done in https://github.com/tendermint/tendermint/pull/2364.

More follow up in https://github.com/tendermint/tendermint/issues/2382
