### ISSUE TITLE
Follow up on BFT time

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2309]
Original Issue: https://github.com/tendermint/tendermint/issues/2013.
PR: https://github.com/tendermint/tendermint/pull/2203

See various minor improvements requested in final review: https://github.com/tendermint/tendermint/pull/2203/#pullrequestreview-151569189

Also noting that we might want to consider hybrid logical clocks some time down the road (not for launch): https://github.com/tendermint/tendermint/issues/2013#issuecomment-417138153

Related: proposer  BFT time: #2840

**Comment by ebuchman** [comment]
We should also add better documentation about time to explain the formats and note that we use proto3 timestamp for most serialization, but RFC3339Nano for canonical time when signing (https://github.com/tendermint/tendermint/issues/2037)

**Comment by cmwaters** [comment]
Coming back to this issue, the decision was made to implement proposer based timestamps. The spec can be found here: https://github.com/tendermint/spec/tree/master/spec/consensus/proposer-based-timestamp. We can use #2840 to track the progress
