### ISSUE TITLE
Implement MaxGas

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2310]
As of #2184 we limit the size of the block in bytes.

Additionally, we'd like to limit the size of the block in terms of some application controlled quantifier of resources, called "gas". 

Each DeliverTx returns an amount GasUsed. The total GasUsed by the block must be less than the BlockSize.MaxGas consensus param.

Each CheckTx returns an amount GasWanted. The Application must enforce GasUsed < GasWanted. We must track the GasWanted in the mempool so we can reap txs within the gas limit.

Reap should be limited by Gas & Bytes - whichever limit is reached first.

**Comment by ebuchman** [comment]
So the mempool reaping side of this is done in #2360. We still need to do the mempool filtering piece, to reject txs with gasWanted > maxGas. Technically the app should be aware of the maxGas and could handle this for us by returning non-zero code.

We also need to decide how to handle blocks that use more gas than the maximum, which is possible since we don't execute blocks before committing them. Some possible solutions:
- run CheckTx for blocks before voting on them 
- let the application handle it (ie. once gas limit is reached, all additional txs return non-zero codes)
- do something else funky on the tendermint side

Note this problem is closely related to https://github.com/tendermint/tendermint/issues/2175

**Comment by ValarDragon** [comment]
We can't add "gasWanted" into the pre-existing filter, as that is called before checkTx. The initial thought I had was to add a second filter to the mempool for the gas stuff. This may make the API more confusing though. Would just adding a second filter for gasWanted be fine?

**Comment by ebuchman** [comment]
Oh interesting. Yeh maybe we want a preFilter and postFilter?

**Comment by ebuchman** [comment]
Oh interesting. Yeh maybe we want a preFilter and postFilter?

**Comment by ValarDragon** [comment]
Sounds like a good idea to me. I can write a PR for this later tonight.

**Comment by ebuchman** [comment]
So the decision ala #2384 is to leave the consensus piece of this to the application. So this was closed by #2385
