### ISSUE TITLE
expose consensus params over RPC

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2311]
Like `/validators?height=X`, we should be able to query for `/consensus_params?height=X`

**Comment by scriptonist** [comment]
Hey @ebuchman, I'm currently checking out tendermint, I would love to work on this if I can ask some dumb questions :smile:  Along the way.

**Comment by melekes** [comment]
@srmo they can be changed the same way validators list is updated - via EndBlock https://tendermint.com/docs/app-dev/abci-spec.html#endblock

**Comment by ebuchman** [comment]
@scriptonist yes please! and surely your questions are due more to a failure on our part to document something than anything else :)

**Comment by scriptonist** [comment]
Any average time for `make test` to run to completion ?
Encountered these errors on running `make test` https://gist.github.com/scriptonist/acf4897f9d4c73b4cae15ed679bc019c

**Comment by ebuchman** [comment]
It takes a minute or so on my mac to complete `make test`. You're on a linux box? Does the install work? Is there more to the log than what's pasted? It just timed out or ?

**Comment by scriptonist** [comment]
I'm on a linux box

**Comment by scriptonist** [comment]
I'm on a linux box,
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

Linux drogon 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
`make install` works like a charm.
I've updated https://gist.github.com/scriptonist/acf4897f9d4c73b4cae15ed679bc019c with the whole log.Hope It brings in some value.

**Comment by melekes** [comment]
Looks like OOM killer stopped tests because they took a lot of memory. I'd investigate further by running tests for each package separately (`go test -race ./XXX`)

**Comment by scriptonist** [comment]
`go test -race -v ./...` works fine :smiley:

**Comment by scriptonist** [comment]
@melekes @ebuchman Any past PR's which can serve as a reference for this?

**Comment by ebuchman** [comment]
Maybe see this commit (e2e87460444ba0c8097c416da9b91734f74af498) from this PR (https://github.com/tendermint/tendermint/pull/618) - at least there we introduced the ability to query for validators at any height through the RPC. We want a similar endpoint for querying the consensus params

**Comment by vaibhavchellani** [comment]
i think we can close this ? @ebuchman

**Comment by ebuchman** [comment]
Sure can! Thanks!
