### ISSUE TITLE
mempool: return error when WAL fails

### ISSUE THREAD

**Issue by ldmberman** [tendermint/tendermint#2319]
`mempool.CheckTx` (used by the `BroadcastTxAsync` and `BroadcastTxSync` RPC handlers) does not return an error when it fails to persist the transaction.

https://github.com/tendermint/tendermint/blob/9e940b95ad4d27efab60d0d49278db5acb2a3b7e/mempool/mempool.go#L248-L260

As a result, transactions can be lost and there is no good way to learn about it.

I did not reproduce it for real, judging by the code so could have possibly overlooked something, looking for your feedback.

**Comment by ldmberman** [comment]
Thank you for the clarification.

**Comment by ebuchman** [comment]
The txs do get logged to the wal file but we don't actually use it in any programmatic way right now - it's just a kind of manual safe guard.

You're right though, we probably should be returning errors here.
