### ISSUE TITLE
Filter out empty addresses in persistent_peers list

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2320]
```
persistent_peers = "<Member 1 node id>@<Member 1 hostname>:26656,<br />
<Member 2 node id>@<Member 2 hostname>:26656,<br />
<Member N node id>@<Member N hostname>:26656,"
```

gets us

```
Address () does not contain ID
```

we shouldn't even consider "" as an address! when validating persistent_peers and seeds, we should filter out empty strings.

**Comment by james-ray** [comment]
Hi,do you mean we should add some code in the place below?

func (sw *Switch) DialPeersAsync(addrBook AddrBook, peers []string, persistent bool) error {
	//add some logic to filter the peers? handle empty string?
	netAddrs, errs := NewNetAddressStrings(peers)
	// only log errors, dial correct addresses
	for _, err := range errs {
		sw.Logger.Error("Error in peer's address", "err", err)
	}

Should I do it right now?

**Comment by melekes** [comment]
Merged to develop.
