### ISSUE TITLE
should cs.LockedBlock = cs.ProposalBlock be modified to deep clone?

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#2321]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
I think a locked block may be overwriiten if the proposalBlock changed in the next rounds. Thus, when the original block reached a polka, it cannot find the block (Because the lockedBlock share the same pointer with proposalBlock , the proposalBlock may be overwritten in the next rounds).At this case, it needs to reset the ProposalBlockParts to re-fetch the block. As the code shown below:

```
// If we don't have the block being committed, set up to get it.
	if !cs.ProposalBlock.HashesTo(blockID.Hash) {
		if !cs.ProposalBlockParts.HasHeader(blockID.PartsHeader) {
			logger.Info("Commit is for a block we don't know about. Set ProposalBlock=nil", "proposal", cs.ProposalBlock.Hash(), "commit", blockID.Hash)
			// We're getting the wrong block.
			// Set up ProposalBlockParts and keep waiting.
			cs.ProposalBlock = nil
			cs.ProposalBlockParts = types.NewPartSetFromHeader(blockID.PartsHeader)
		} else {
			// We just need to keep waiting.
		}
	}
```

**What you expected to happen**:
I'm not sure if it's on the concerning of the low performance of deep copy compared with shallow copy. If it's this case, I understand.

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by ebuchman** [comment]
Are you saying that since they share a pointer, when we set `cs.ProposalBlock = nil` we also accidentally set `cs.LockedBlock = nil` ? This wouldn't be true, because the pointers themselves are different (ie. they are distinct fields in a struct), even if the object they point to is the same (and we don't mutate the block).

**Comment by james-ray** [comment]
actually, I mean the following place,when we finished receiving a proposal:
In the function addProposalBlockPart

if added && cs.ProposalBlockParts.IsComplete() {
		// Added and completed!
		_, err = cdc.UnmarshalBinaryReader(cs.ProposalBlockParts.GetReader(), &cs.ProposalBlock, int64(cs.state.ConsensusParams.BlockSize.MaxBytes))
		if err != nil {
			return true, err
		}

so the cs.ProposalBlock will be overwriiten, so will the cs.LockedBlock

**Comment by james-ray** [comment]
Sorry, seems I was wrong. It seems that cs.ProposalBlock will allocate a new space in the logic above, not overlap with cs.LockedBlock.  Thanks for the guidance

**Comment by ebuchman** [comment]
Cool, thanks for doing a critical reading of the code!
