### ISSUE TITLE
Troubleshooting Guide w/ FAQ

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2328]
common problems encountered when installing / running / configuring tendermint.

include: 
- addr_book_strict=false on local networks

**Comment by tessr** [comment]
@marbar3778 do you have ideas for further frequently-encountered problems? if not, I'm just going to close this issue (especially since our address book management will completely change with the p2p refactor)

**Comment by marbar3778** [comment]
I am in favor of closing this. We have added quite a few docs since this issue was opened and we will be adding more.
