### ISSUE TITLE
p2p_peers (prometheus) does not match /net_info RPC n_peers 

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#2332]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
gaiad 0.24.2-0bf061b7

**What happened**:
p2p_peers prometheus gauge for a peer does not match the number of peers reported via /net_info RPC (n_peers).

The number reported by p2p_peers is consistently lower than n_peers.

**What you expected to happen**:
Numbers should match. ;-)

**How to reproduce it** (as minimally and precisely as possible):
Run gaiad with empty config and use /dial_peers RPC to dial peers.

```
PEER=nodeid@ip:port
curl -s -G "http://localhost:26657/dial_peers?persistent=false" --data-urlencode "peers=[\"${PEER}\"]"
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

![prometheus](https://user-images.githubusercontent.com/18033781/45076425-8c734300-b0ea-11e8-8e7c-76245937a813.png)

Compare to the below net_info dump from val1.cph1.validator.network:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "listening": true,
    "listeners": [
      "Listener(@10.255.254.2:26656)"
    ],
    "n_peers": "3",
    "peers": [
   ...
```
**Config (you can paste only the changes you've made)**:
No changes to default config (empty persistent_peers and seeds).

**Comment by ebuchman** [comment]
I think it's possible that `stopAndRemovePeer` is called multiple times for the same peer. the `sw.peers.Remove` doesn’t return anything, so we don’t check if it actually took effect, and then we call `metrics.Peers.Add(-1)` no matter what, which could explain how the metrics count dips below the real count. 

How `stopAndRemovePeer` is getting called multiple times remains an issue. Would be great if we could figure out how to replicate this in a test.

**Comment by ebuchman** [comment]
Ok there are defntly cases where this can happen - ie. the peer connection fails, so the connection object triggers the onError, but then a reactor detects the failed peer, and also calls StopPeerForError. This would result in the stopAndRemovePeer being called twice.

**Comment by ebuchman** [comment]
Ok I believe this is fixed in https://github.com/tendermint/tendermint/pull/2969 :)

**Comment by ebuchman** [comment]
Stoked to have this fixed. Stay tuned for release!
