### ISSUE TITLE
remove send/recv rates from p2p in favour of back-pressure based throttling

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2338]
As per https://github.com/tendermint/tendermint/issues/1752#issuecomment-401275491:

> We should communicate with peers as fast as possible and only start to throttle if we experience backpressure from a peer

And https://github.com/tendermint/tendermint/issues/1752#issuecomment-418732061:

> One of the key features of Tendermint is to be lightning fast,
but the default values for send_rate and recv_rate are going in the opposite direction.

**Comment by tychoish** [comment]
This was removed as part of the P2P refactor, and should not be an issue moving forward.
