### ISSUE TITLE
Returning != OK from CheckTx() leads to hang

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#234]
INFO[07-06|11:53:51] Block{
  Header{
    ChainID:        test-chain-JY3bDs
    Height:         55
    Time:           2016-07-06 11:53:51.343 -0400 EDT
    NumTxs:         0
    LastBlock:      9DB818910F2F62F7F3F4810EAFA12FBA205D4A48
    LastBlockParts: PartSet{T:1 FA3344BEE329}
    LastCommit:     663875B2005172DBD8CF75E0A4E44A787E1512A3
    Data:
    Validators:     54E49D143CE2B83A9A17D9A9BCF10C7E45AF32AD
    App:            BBAD362C2CB31C0719B850BF3209263D325152A240E12247BE8F5B5AA5DC5F72
  }#66E74DE09C0D50686EFCDBF6A1A18DC3254E46A4
  Data{

  }#
  Commit{
    Precommits: Vote{54/00/2(Precommit) 9DB818910F2F#PartSet{T:1 FA3344BEE329} /CD6FBCEC5549.../}
  }#663875B2005172DBD8CF75E0A4E44A787E1512A3
}#66E74DE09C0D50686EFCDBF6A1A18DC3254E46A4 module=consensus
INFO[07-06|11:53:51] TODO: Do something with changedValidators module=state LOG15_ERROR= LOG15_ERROR="Normalized odd number of arguments by adding nil"
INFO[07-06|11:53:51] ExecBlock got 0 valid txs and 0 invalid txs module=state
INFO[07-06|11:53:51] Recheck txs                              module=mempool numtxs=0
INFO[07-06|11:53:52] Bad Transaction                          module=mempool res="&{CheckTx:code:BadNonce }"
INFO[07-06|11:53:52] Timed out                                module=consensus dur=999.818809ms height=56 round=0 step=RoundStepNewHeight
NOTE[07-06|11:53:52] enterNewRound(56/0). Current: 56/0/RoundStepNewHeight module=consensus
INFO[07-06|11:53:52] enterPropose(56/0). Current: 56/0/RoundStepNewRound module=consensus
INFO[07-06|11:53:52] enterPropose: Our turn to propose        module=consensus proposer=E77D9A4028441496E2E72FC6BE96808961B29B67 privValidator="PrivValidator{E77D9A4028441496E2E72FC6BE96808961B29B67 LH:55, LR:0, LS:3}"
INFO[07-06|11:53:55] Timed out                                module=consensus dur=3s height=56 round=0 step=RoundStepPropose

**Comment by ebuchman** [comment]
this should be fixed on `broadcast_commit` and `grpc_fix` branches

**Comment by mdyring** [comment]
Confirmed fixed, thanks!
