### ISSUE TITLE
docs: add specification to docs side bar

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2348]
The `Tendermint Core -> Block Structure` contains a link to one file in the spec, but it doesn't appear otherwise possible to find the other files in the spec on the website

**Comment by ebuchman** [comment]
Could be an improvement as part of https://github.com/tendermint/tendermint/issues/2143

**Comment by ebuchman** [comment]
We should also move the abci-spec into the docs/spec folder and deduplicate the docs/spec/software/abci.md

**Comment by ebuchman** [comment]
ABCI docs refactor was completed and included in https://github.com/tendermint/tendermint/pull/2350 - see opening comment there for PRs where it all happened

**Comment by zramsay** [comment]
consolidating in #2143 since it's part of the sidebar re-org
