### ISSUE TITLE
some readme links are broken

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2357]
- `Quick Start -> Single Node` is broken link
- `Resources -> Tendermint Core` points to ReadTheDocs
- `Resources -> Applications -> Ethermint` points to old ethermint

Some other things point to ReadTheDocs, and others point to github pages. We should fix all this and probably point more to the tendermint.com/docs/ website :)

**Comment by melekes** [comment]
Merged to develop.
