### ISSUE TITLE
Unable to inject own Key Type 

### ISSUE THREAD

**Issue by bgrieder** [tendermint/tendermint#2358]
Tendermint version 0.23.1

I would like to inject my own Public and Private key types because I do not want to use the ED25519 curve.

The embedded doc mentions it is possible to inject its own private validator as long as it implements the `types.PrivValidator` interface.

Unfortunately, this is currently impossible. 

The `typesGenesisDoc`requires an array of validators which can be bootsrapped using something like

```go
genDoc.Validators = []types.GenesisValidator{{
			PubKey: privValidator.GetPubKey(),  // <-- this pulls the "new" Public Key
			Power:  10,
		}}
```

The `Node` is instantiated using a (massive) `NewNode(...)` function that attempts to serialize the `GenesisDoc` in the state DB using a piece of code that does

```go
	genDoc, err := loadGenesisDoc(stateDB)
	if err != nil {
		genDoc, err = genesisDocProvider()
		if err != nil {
			return nil, err
		}
		// save genesis doc to prevent a certain class of user errors (e.g. when it
		// was changed, accidentally or not). Also good for audit trail.
		saveGenesisDoc(stateDB, genDoc)  // <---- THE PROBLEMATIC CALL
	}
```

To serialize the doc, `amino`is called. 
Unfortunately `amino`requires all serializable "concrete" types to be pre-registered and the piece of code that does this is, is located in the `wire.go` file in the `node` package in an `init()` call, namely

```go
var cdc = amino.NewCodec()

func init() {
	cryptoAmino.RegisterAmino(cdc) // <--- this registers all the types
}
```
As currently written, there is no way to inject custom types either by getting hold of `cdc`, which is private to the package, or via a provided callback.

I believe this static initialization should be revisited and `cdc` should be instantiated early and injected in the new node as part of the `NewNode` function parameters.

**Comment by bgrieder** [comment]
The problem is pretty widespread. There are many files, usually named `wire.go` that register types in the `init()` function.
This causes two problems 1) a lot of duplicated calls to the types registration 2) the inability to inject your own types.

To fix 1) I guess the only robust solution is to used injection (much like is down for `StateDB` rather than using static initialization. I have tried but the impact on existing function signatures is very significant, especially around `State`. This would be worth the effort though to avoid bad unmarshalling surprises in the future by re-centralizing his code around a single function and instance.

To fix 2) without going to injection, the first thing that can be done is to have type registration **not** done in `init()` but rather doing deliberate registration calls pretty early in the code. I am targeting the `DefaultNewNode()` function in particular.

I am close to have a working solution for 2 and will submit a PR

Having the ability to inject types gives the ability to  use your own elliptic curve and associated key pairs. Not all elliptic curves are born equal and there are things that cannot be done using the provided Ed 25519 and secp256k1 (such as Pairing Based Cryptography)

**Comment by ValarDragon** [comment]
I've brought up this same point before. Our solution is (going to be) to add an ability for you to add your own pubkey types to be registered everywhere. 

I don't understand why this being done in init is bad though. If we add a new "RegisterCustomPubkey", which updates the default cdc in `crypto/encoding/amino`, and registers it in every subsequent call to `RegisterCrypto`, you could just `RegisterCustomPubkey` in an init function within your app, and there should be no problems right?

> Having the ability to inject types gives the ability to use your own elliptic curve and associated key pairs. Not all elliptic curves are born equal and there are things that cannot be done using the provided Ed 25519 and secp256k1 (such as Pairing Based Cryptography)

Are you working on trying to integrate PBC into the consensus layer? If so, thats awesome! We've been working on plans for how to integrate BLS to optimize the gossip layer + just have a single signature in the header. If your working on this, I can make a better effort to write down the thoughts so far somewhere. (We've punted working on this internally until post-launch)

**Comment by bgrieder** [comment]
>If we add a new "RegisterCustomPubkey", which updates the default cdc in crypto/encoding/amino, and registers it in every subsequent call to RegisterCrypto, you could just RegisterCustomPubkey in an init function within your app, and there should be no problems right?

This relies on a sequencing of the init() functions but fine ! I will hold on the PR then. I noticed though that the amino registration is not enough, I had to implement a converter from `crypto.PubKey` to the protobuf `abci.PubKey` in protobuf.go, something like

```go

// SetCustomPubKeyConverter sets a custom converter that converts crypto.PubKey to abci.PubKey
// when using a type of crypto.Pubkey which not one of the system defaults (keys for curves
// Edwards 25519 and 'bitcoin' Secp256k1
//
// The converter should panic if the key type is unknown
func (t *tm2pb) SetCustomPubKeyConverter(converter func(pubKey crypto.PubKey) abci.PubKey)  {
	t.customPubKeyConverter = converter
}

// XXX: panics on nil or unknown pubkey type
func (t *tm2pb) PubKey(pubKey crypto.PubKey) abci.PubKey {
	switch pk := pubKey.(type) {
	case ed25519.PubKeyEd25519:
		return abci.PubKey{
			Type: ABCIPubKeyTypeEd25519,
			Data: pk[:],
		}
	case secp256k1.PubKeySecp256k1:
		return abci.PubKey{
			Type: ABCIPubKeyTypeSecp256k1,
			Data: pk[:],
		}
	default:
		if t.customPubKeyConverter == nil {
			panic(fmt.Sprintf("unknown pubkey type: %v %v", pubKey, reflect.TypeOf(pubKey)))
		}
		return t.customPubKeyConverter(pubKey)
	}
}
```

> Are you working on trying to integrate PBC into the consensus layer? 

Yes... and no. Yes as part of our application but I was not planning on changing transactions signature yet to be honest. But why not, BLS is trivial to implement once you have PBC available.
My first worry is to avoid multiple keys for the same node

**Comment by ebuchman** [comment]
Related: https://github.com/tendermint/tendermint/issues/2083

**Comment by bgrieder** [comment]
@ValarDragon I tried to re-implement the types registration with minimum code impact + along the lines you suggested i.e. a `RegisterCustomPubkey` than can be called from an implementer custom app `init()`function

After several ugly workarounds, I doubt this is ever going to be doable. 

The main difficulty is that in Go, as soon as you `import`a package, the `init()`method of that package is run, **before** the init() of your package is run.

For instance importing `github.com/tendermint/tendermint/types` (or anything that imports it) in the app main package will trigger the init() method in wire.go of that package and register the default types, before you had any chance to register yours.
It is actually very hard to write anything that does *not* import that package since custom converters in TM2PB and PB2TM (which import that package) need to be registered early on.

Even if you make it work, any re-ordering or change of your initialization will break it, as is typically the case when writing a test (which is what #2083 is about).

Please prove me wrong. If not, I believe you should look at going all the way to the injection of a single amino codec instance, which will seriously reduce the risk of registering twice the same type with different definitions, ease test writing and improve setup performance at the expense of slightly longer methods and functions signatures.

**Comment by ebuchman** [comment]
We probably want to move away from using `init` functions here altogether and explicitly passing in codecs, but would be nice if we could somehow do this iteratively so it didn't have to happen in a single giant PR.

**Comment by bgrieder** [comment]
@ebuchman @ValarDragon **Fork**: I made a fork which gives me the ability to register my own types for the validator (`crypto.PubKey`) and the node (`p2p.NodeKey`). 
The modifications basically consist in
- adding the ability to inject converters to `tm2pb`and `pb2tm` as described above
- replacing the `init()` functions in the `wire.go` files of the various packages with something like
  
```go
var cdc = amino.NewCodec()

// RegisterAminoDefaults registers with amino the types used by default with Commands
func RegisterAminoDefaults() {
	RegisterAmino(cryptoAmino.RegisterAmino)
}

// RegisterAmino is used to register types with amino that are used by Commands
// see cryptoAmino.RegisterAmino() for an example registration
func RegisterAmino(register func(cdc *amino.Codec) ) {
	register(cdc)
}
```

then in `node.DefaultNewNode`, the types are registered by hand using 

```go
func DefaultNewNode(config *cfg.Config, logger log.Logger) (*Node, error) {
	// register the default types with Amino
	types.RegisterAminoDefaults()
	RegisterAminoDefaults()
	sm.RegisterAminoDefaults()
	evidence.RegisterAminoDefaults()
	p2p.RegisterAminoDefaults()
	conn.RegisterAminoDefaults()
	privval.RegisterAminoDefaults()
...
}
```

It is not pretty but it has minimal code impact and it gives the ability to register whatever types you wish by implementing your own `NewNode`. 

This appears to work fine but needs to be further reviewed by people more familiar than I am with the tendermint code. I can make a PR if you wish.

I can even go one step further by instantiating a single amino codec instance, registering all types on it then in the various packages set the package global `cdc` pointers to point to the the single instance. It is not "full" injection but goes one step further and does not affect any other existing code files than those already patched.

@ValarDragon **PBC** use. My use of PBC is to do mostly two things for now: blind signatures and zero-knowledge proofs (on the elliptic curve used with PBC). I do not use SNARKS (and find them way too complicated (for me :)))

Do I understand that you want to replace the current scheme to collect 2/3 of the votes by a threshold signature scheme ?

**Comment by bgrieder** [comment]
@ebuchman @ValarDragon Is there any progress on this ?

**Comment by ebuchman** [comment]
Bumping this from current milestone as we're evaluating how best to improve the amino situation.

**Comment by marbar3778** [comment]
there has been quite a bit of work to get the repo to a point where this issue could be tackled. There are still a few places where ed25519 is hardcoded, but these are simple changes. We should start to think of a way for users to inject there own key type, I think this will come up more and more often in the near future.

**Comment by marbar3778** [comment]
closing this for now. We would like to best support the key types in the repo. We have plans on adding bls in there as well. 

If people would still like to inject their custom key type, please comment here or open a new issue with your usecase.
