### ISSUE TITLE
Fast sync from state and fork from specific block

### ISSUE THREAD

**Issue by yutianwu** [tendermint/tendermint#2365]
Hi, Ethereum implements a fast sync mode which just downloads blocks and state from peers and without executing txs in blocks. And this mode came improve the sync speed significantly as it doesn't need to run txs. Here is the [pr](https://github.com/ethereum/go-ethereum/pull/1889).

Because tendermint produces blocks faster than etherum, if we sync blocks and run txs in them, it can be very slow to catch up too many blocks.

Besides fast sync, we may need to fork our chain from specific block if there is a severe bug in our dapp. 

So I have a rough idea here:
1. we can download blocks and state dbs from peers.
2. and restart nodes from specified block for fork.

Can we provide such a mode like ethereum?

**Comment by ebuchman** [comment]
For Cosmos-SDK apps, we currently recommending just dumping the latest state and starting a new blockchain from that. We've done it many times now on the gaia testnets. See https://github.com/cosmos/cosmos-sdk/blob/master/cmd/gaia/app/app.go#L196 for where we do it.

We'd like to implement a generic state sync mechanism in tendermint - tracking in https://github.com/tendermint/tendermint/issues/828

Will close this in the meantime. Thanks!
