### ISSUE TITLE
tendermint rpc server does not accept integer id for request

### ISSUE THREAD

**Issue by whitered** [tendermint/tendermint#2366]
JSONRPC2 specification allows to specify request ID as a number: https://www.jsonrpc.org/specification#request_object

> An identifier established by the Client that MUST contain a String, Number, or NULL value if included.

However tendermint rpc server will return an error if ID is anything but a string.

**Comment by melekes** [comment]
Supporting multiple types complicates things so much (see https://github.com/tendermint/tendermint/pull/2811). I don't think it's difficult to transform integer to string on a client, no? **I'd vote for ignoring this requirement in favor of simplicity (both client & server)**.

**Comment by tomtau** [comment]
It's not difficult -- it was just that JSON-RPC client library we had was keeping track of requests by numeric IDs on different places, was incrementing them etc., so it'd require quite a few changes to convert back and forth.

Anyway, it's probably not a big deal if this requirement isn't supported -- if it is decided, it'll be good to document that Tendermint doesn't fully follow the JSON-RPC specs.

**Comment by melekes** [comment]
ok, I was exaggerating a little bit, but these things freak me out. Thanks for contributing though! I appreciate it. And we shouldn't move our problems onto clients.
