### ISSUE TITLE
Include block size and consensus time information in BlockMeta 

### ISSUE THREAD

**Issue by ackratos** [tendermint/tendermint#2367]
In terms of contains more block information within response for `// curl 'localhost:26657/block?height=10'`, I wonder whether community agree with include block size and consensus time into block meta? (This might be useful for provide information for blockchain browser and monitor the performance of chain)

```
// BlockMeta contains meta information about a block - namely, it's ID and Header.
type BlockMeta struct {
	BlockID BlockID `json:"block_id"` // the block hash and partsethash
	Header  Header  `json:"header"`   // The block's Header
}
```

For implementation, the block size hight be easy to add. But as different validators have its local commit time, I thought make BlockID carry such information that only be proposer node's local time for each block. (so that we know from proposer point of view, how long it takes +2/3 consensus)

**Comment by ebuchman** [comment]
So the number of txs is already included in the header, and the size of the block is roughly `BlockID.PartsHeader.Total * BlockPartSize`, where BlockPartSize is now fixed to 64kB. 

As for time, you can compare the timestamp between this block and the previous one - the timestamps are now BFT times (we take the median of the timestamps in the votes for the last block).

I don't think we should change the BlockMeta struct, but we could consider improving the design of the RPC if it's well thought out. 

Given the above, can we close this, or you still think we need to change something?

**Comment by ackratos** [comment]
@ebuchman thanks for your kind reply.

Regarding the consensus time, I am fine with difference between two blocks

But regarding to the block size, it seems the parts are not aligned to 64K. For following function, if len(data) is 5 bytes, there will be only one part whose size is 5 bytes isn't it?

```
// Returns an immutable, full PartSet from the data bytes.
// The data bytes are split into "partSize" chunks, and merkle tree computed. 
func NewPartSetFromData(data []byte, partSize int) *PartSet {
	// divide data into 64kb parts.
	total := (len(data) + partSize - 1) / partSize
	parts := make([]*Part, total)
	parts_ := make([]merkle.Hasher, total)
	partsBitArray := cmn.NewBitArray(total)
	for i := 0; i < total; i++ {
		part := &Part{
			Index: i,
			Bytes: data[i*partSize : cmn.MinInt(len(data), (i+1)*partSize)],
		}
		parts[i] = part
		parts_[i] = part
		partsBitArray.SetIndex(i, true)
	}
	// Compute merkle proofs
	root, proofs := merkle.SimpleProofsFromHashers(parts_)
	for i := 0; i < total; i++ {
		parts[i].Proof = *proofs[i]
	}
	return &PartSet{
		total:         total,
		hash:          root,
		parts:         parts,
		partsBitArray: partsBitArray,
		count:         total,
	}
}
```

I think the accurate block size can be calculated at node side (but make a non-go client (blockchain explorer) app understand how to unmarshal animo is an unnecessary burden isn't it?
```
// Size returns size of the block in bytes.
func (b *Block) Size() int {
	bz, err := cdc.MarshalBinaryBare(b)
	if err != nil {
		return 0
	}
	return len(bz)
}
```

> I don't think we should change the BlockMeta struct, but we could consider improving the design of the RPC if it's well thought out.

I agree, my point is the response of RPC should contains size information (I don't care whether its included in BlockMeta or a higher level wrapped in RPC response)

How about we retitle this issue into "include block size in bytes in blocks rpc response"? (I am also fine to close this and start a new one log this feature requirement. Actually I can help contribute the implementation if you have an idea acceptable for tendermint maintainer).

**Comment by ebuchman** [comment]
> How about we retitle this issue into "include block size in bytes in blocks rpc response"? (I am also fine to close this and start a new one log this feature requirement. Actually I can help contribute the implementation if you have an idea acceptable for tendermint maintainer).

This sounds good. Want to close this and open a new issue? Thanks!

**Comment by ebuchman** [comment]
Closing for #3188
