### ISSUE TITLE
Ubuntu bash installation root permission requirement.

### ISSUE THREAD

**Issue by Uzair1995** [tendermint/tendermint#2372]
While installing on Ubuntu it requires permission for the root access which is not required in my experience. You just need to replace GOPATH=/root/goApps with GOPATH =/home/{username}/goApps. This would remove the requirement of install it in the root, and the program will function as it is suppose to be.

**Comment by Uzair1995** [comment]
Forgot to mention I was referencing this file:
https://github.com/tendermint/tendermint/blob/master/scripts/install/install_tendermint_ubuntu.sh

**Comment by ValarDragon** [comment]
The reason for the root requirement was more so for installing make. That could be worked around though, e.g. by only installing it to a single user. Would you like to submit a PR?

**Comment by Uzair1995** [comment]
Very well. I will create a pull request... Its just a small change btw.

**Comment by melekes** [comment]
Merged to develop. Thanks!
