### ISSUE TITLE
Compress block before gossipping to peers

### ISSUE THREAD

**Issue by adagys** [tendermint/tendermint#2375]
Would be good to have the ability to compress a block before it gets proposed to peers.

In our use-case individually compressed transactions are 2kb in size. Using Snappy compression over a batch of (pre-compressed) transactions yields an additional compression ratio of ~2.

I tried hacking it in to Tendermint, and observed a significant throughput increase: from ~200 to ~500 TPS

**Comment by adagys** [comment]
I believe it does provide deterministic encoding, and wrt decompression bombs they claim that it's "designed not to crash in the face of corrupted or malicious input", but that would require some closer investigation.

**Comment by ebuchman** [comment]
Very interesting - would you be willing to write an [ADR](#2313 ) about it? Would be helpful to have some context on what other projects might be doing, what the landscape of compression options looks like, their tradeoffs, and a proposed solution for us.

**Comment by ValarDragon** [comment]
Ideally we'd be able to drop-in different compression algorithms via consensus parameter in config. So we just need reasoning for which to choose by default. I think we just need to make sure that our compression algorithm is fast, protects against adversarial input creating in-ordinate amounts of memory usage, and we have a way to ensure it throws an error quickly once the decompressed value is exceeding the block size limit. The last item should be easy to tack onto almost any decompression algorithm, we'd have to make sure the protocol meets the protection against large memory usage. We can probably add these last two protections onto any library if its not already provided though, so it probably makes more sense to optimize for the compression rate vs decompression time.

I'm pretty excited about getting compression integrated into Tendermint though, seems like a brilliant idea, and shouldn't be hard to integrate.

**Comment by ValarDragon** [comment]
Just benchmarked snappy compression ratio. Compressing the block data on a block containing 10 gaia single input single output txs, Snappy on average yielded a 24.5% compression ratio. On a block with 50 such txs, Snappy yielded a 27% compression ratio on average. I'll try running it with more tx variety, but the compression is sufficiently fast that I think this does make a lot of sense to integrate into block propagation. I've started working on an ADR for this, just want to give some indication that its looking quite promising!

**Comment by srmo** [comment]
Good stuff. Some of our use-cases generate txs up to 30-50kB so we started with  lz4 compression on the app level before broadcasting txs.

**Comment by ValarDragon** [comment]
I never got around to running it on a greater tx variety. (Absolutely should be done pre-integration) 

I think in the short term we should use snappy since it gives a good compression rate, and has _super_ fast decompression. Once we have transfers enabled for a month or two, we can build a really nice corpus, and then use Zstd: https://github.com/facebook/zstd. We would have part of the p2p configuration be supplying this corpus file. With a corpus file, zstd does a _terrific_ job of high rate compression, high speed compression and high speed decompression. (Their general case benchmarks on all of the above blow snappy out of the water, as expected due to having a corpus)

**Comment by erikgrinaker** [comment]
I would suggest simply compressing the entire P2P stream. Data is already compressed on disk by LevelDB. The P2P API should probably support explicit flushing/buffering to allow a reasonably large chunk of data to be compressed - alternatively we could use a timer to automatically buffer and flush, but that would introduce additional latency.

**Comment by ValarDragon** [comment]
It doesn't seem clear to me that you'd want to compress each communication stream in the same way. 

In particular, a single tx may likely be mostly 'incompressible data' so attempts at compressing without a tailored corpus may increase size. 

Whereas at the block level, you probably want a distinct corpus.

**Comment by ValarDragon** [comment]
Also not sure to what level tx level privacy is a concern, but you do run the risk of adversaries doing compression-ratio attacks on batched mempool gossips, to trace the flow of other peoples txs on the network.

(sample compression-ratio attack: https://en.wikipedia.org/wiki/CRIME)
