### ISSUE TITLE
docs: re-organize sections / sidebar & improve landing page

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2376]
- ~~main page should have a small section for each section in the sidebar: `Getting Started, Core, Tools, Networks, Apps, Research`~~
- ~~you should be able to link directly to one of these sections, rather than "the first subsection within them"~~ this would make sense only if each section had a readme and its own landing, which is overkill
- ~~Include Spec in Sidebar (orig issue: #2348)~~

Getting Started
- first subsection is called Tendermint. Should be called Quick Start and link places to find more advanced starts!

Using Tendermint
- we should reconcile the structure of this section with the larger "Tendermint Core" section:
protocol stuff can probably in a separate Specification section
- add more info about Upgrading to new versions (e.g., #2390)

original issue: #2143

**Comment by ebuchman** [comment]
> this would make sense only if each section had a readme and its own landing, which is overkill

I'm finding it much more useable if we have these, so I added them in #2522. Would be awesome if the main sidebar section headers could link to these as well!

> first subsection is called Tendermint. Should be called Quick Start and link places to find more advanced starts!

Fixed in #2522.

I think we should close this and open a new one for fixing the `Tendermint Core/Using Tendermint` stuff
