### ISSUE TITLE
docs: improve Validator documentation

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2377]
- Adding a Validator -> should become two sections called:
    - "Adding a Validator at Genesis"
    - "Adding a Validator at Runtime"
        - this needs to be written and explained how to update the validator set using EndBlock in the application
        - needs to link to the EndBlock section of the app developers guide
    - This also needs to be easier to find - currently its doesn't even make it into the sidebar its so burried under TendermintCore->UsingTendermint->TendermintNetworks->AddingAValidator

Validators
- document how the priv_validator.json works
- document how an out-of-process validator like the KMS is supposed to work
- include link to how to add validators section of Using Tendermint

original issue: #2143

**Comment by marbar3778** [comment]
closing this as more instructions on how to setup a validator has been added.
