### ISSUE TITLE
docs: improve Networks documentation

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2378]
- instead of "Deploy a Testnet", just make "Local Docker Testnet" and "Manual Deployment" subsections of "Tendermint Networks"
- ~~Fast Sync belongs under "Tendermint Core"~~

sync with https://github.com/cosmos/cosmos-sdk/pull/2271

original issue: #2143

**Comment by zramsay** [comment]
note to also sync as required with Networks documentation in SDK repo

**Comment by ebuchman** [comment]
Done in https://github.com/tendermint/tendermint/pull/2522
