### ISSUE TITLE
docs: improve AppDev guide / organize ABCI documentation

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2379]
- Can be simplified and make better use of the abci README and specification.md file in the repo
- EndBlock
   - needs an update, no longer true about max +1/3
   - need to stress the change must have gone through consensus
   - explain that you have to return the full pubkey and link to somewhere that specifies what that looks like

original issue: #2143

**Comment by zramsay** [comment]
currently we have:

```
abci/README.md
docs/app-dev/*
docs/spec/abci/*
```

@ebuchman has been moving stuff to the latter location and there is also lots of duplicate information. My proposal is to:

1. slim down `abci/README.md` to a quick overview and links to `docs/abci/spec/`, i.e., remove all "content"
2. continue deprecation/deduplication of a few files in `docs/app-dev/` and focus on practical stuff while linking to `spec/abci` for everything else

**Comment by zramsay** [comment]
#3000

**Comment by tessr** [comment]
@marbar3778 shall we close this one too? a lot of the links are out of date, and I think it's captured by your planned docs refactor

**Comment by marbar3778** [comment]
Yea, lots of the docs have moved/edited and will be edited.
