### ISSUE TITLE
Align reactor max msg sizes with relevant max data sizes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2381]
Each reactor has hard coded msg size maximums checked in `decodeMessage`, called from `Receive`. 

We should align these (ie. make them functions of) the maximum size of underlying data being sent in each reactor. Eg.

- blockchain: max block size
- consensus: max block part size
- mempool: max block data size
- evidence: max evidence size
- pex: max size of X addresses ...

**Comment by marbar3778** [comment]
@melekes can you confirm if this is still applicable. I recall you did some work on this

**Comment by melekes** [comment]
`decodeMessage` was removed, so no.
