### ISSUE TITLE
add invalidtxs bitarray to header

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2383]
Follow up from https://github.com/tendermint/tendermint/issues/2175

Since we currently allow blocks to include invalid txs, we should include `LastResultsBitArray` in the header, with size equal to the number of txs in the last block, where bits are set to `1` for invalid txs - so a fully valid block corresponds to a `LastResultsBitArray = 0`. 

Since we now include ProposerAddress in the header, we can easily verify when a proposer proposed an invalid block - ie. ProposerAddress at block `H` proposed an invalid block if block `H+1` has `LastResultsBitArray != 0`.

We should write a small ADR for this. 

The context in [ADR-022](https://github.com/tendermint/tendermint/blob/develop/docs/architecture/adr-022-abci-errors.md#context) is relevant here.

**Comment by ebuchman** [comment]
Question: do we really need this in the header, or can we just provide proofs using the LastResultsHash that's already there?

**Comment by ebuchman** [comment]
Note this also relates to the MaxGas problem - should apps be expected to track when DeliverTx exceeds the max gas for the block?

**Comment by xla** [comment]
Should we close this in favour of the checkTx changes?

**Comment by cwgoes** [comment]
> So it could still be valuable to have this in the header, but I think we need a better sense of the concrete lite-client use case before moving forward with it, especially so if we move forward with the checkTx changes

I think this is quite useful if it indicates that `CheckTx` succeeded but `DeliverTx` failed (more useful than if it indicates that one of them failed but you don't know which) - any kind of order-dependent state interactions (DEX order settlement, fungible/nonfungible asset auction, timelocked-asset transfer) are likely to pass `CheckTx` but possibly fail `DeliverTx` depending on when exactly they get executed in a block relative to other transactions.

**Comment by ebuchman** [comment]
> and often these failures are ones light clients might want to know about so that they can retry the transactions or alert the user.

Agree. Question is whether this bit-array needs to go directly in the header, or if proofs using the LastResultsHash (merkle tree of {Code, Data}) will suffice

**Comment by cwgoes** [comment]
> Agree.  Question is whether this bit-array needs to go directly in the header,  or if proofs using the LastResultsHash (merkle tree of {Code, Data})  will suffice

I see - what's the advantage of the former - verification efficiency?

**Comment by ebuchman** [comment]
Yes I think so. I've been trying to get @ValarDragon or @sunnya97 to write a design results proofs that accounts for all this: https://github.com/tendermint/tendermint/issues/1007#issuecomment-413917763

**Comment by ebuchman** [comment]
Copying over some thoughts from @james-ray in #2384 :

> maybe we can use an array such as invalidTxs: [ 1,3,7] which contains the invalid txs' Indexes of the block instead of using a bitArray?
> Also , maybe we can use a OutOfGasTxIndex : 800 to show the txs after 800 are all not executed due to out of block limited gas.

**Comment by ebuchman** [comment]
Also note, it looks like punishing bad proposers for invalid txs and/or blocks exceeding the max gas can happen entirely on the application side without any changes to Tendermint. We should continue discussion about this proposal, but it would only be relevant for lite-clients, still needs some design, and may not need to happen in the very short term.

**Comment by ValarDragon** [comment]
I don't really like adding a bit-array of invalid txs in the header. Lite clients should be using tags, which won't get added if deliver tx fails. I agree with @sunnya97 that we should just slash for failing check txs.

**Comment by ebuchman** [comment]
Ok. 

So the question is whether lite-clients should be able to get a cheap proof of the set of *all* txs that returned non-zero codes in a block. It doesn't seem particularly important at first glance, though it is important to be able to cheaply prove that *some* txs are invalid, and we can do that, since we have a Merkle tree of results, we can just verify one or a few.

I think we can close this and focus on #1007. Will summarize in ADR-029, namely that handling invalid txs and gas limits is entirely the responsibility of the application, and to see ADR-032 for more on lite-client result proofs.
