### ISSUE TITLE
License Concerns

### ISSUE THREAD

**Issue by AaronShea** [tendermint/tendermint#239]
I'm planning on building a product which makes calls to the tendermint peer client, as each client is going to be a peer node on the network.
The software also involved in this product is entirely incompatible with GPL. I cannot disturbte GPL code with this software at all. 
I saw the homepage said AGPL.. though the license file states GPLv3

Any chance the license in the core could change to something like the Mozilla or Apache license? Even LGPL would calm the possible issue with adopting tendermint into a product.

**Comment by jaekwon** [comment]
Hi Aaron, most users of TendermintCore won't need to modify TendermintCore, but interface with it via network protocols like the HTTP/JSON-RPC API, or the TMSP API.  In these cases, GPLV3 shouldn't matter.

If you need to compile everything into a single Golang program, we could designate API endpoints as LGPL.  But otherwise the GPL-ness of TendermintCore shouldn't matter at all.

Also related for TMSP: https://github.com/tendermint/tendermint/issues/225

**Comment by AaronShea** [comment]
I understand, I was looking for confirmation from your team first. I know there have been cases where a GPL covered program communicating via something like pipes can be considered depending on the GPL code and a case could be made to force the main program to be under GPL.

**Comment by ebuchman** [comment]
Can you point us to these cases please? As far as we know, communicating with GPL over a socket does not cause your program to be infected with GPL.

**Comment by AaronShea** [comment]
Reading the GPL FAQ under
https://www.gnu.org/licenses/gpl-faq.html#MereAggregation

> By contrast, pipes, sockets and command-line arguments are communication mechanisms normally used between two separate programs. So when they are used for communication, the modules normally are separate programs. 

> But if the semantics of the communication are intimate enough, exchanging complex internal data structures, that too could be a basis to consider the two parts as combined into a larger program.

**Comment by ebuchman** [comment]
Oh boy! I think we can make a strong argument that these are clearly separate programs and that they can even function independently. Furthermore, we tend to refrain from communication internal data structures - most of the arguments passed (txs) are just byte arrays as far as TendermintCore is concerned, and all interpretation is defined by the application.

**Comment by AaronShea** [comment]
Very well, thank you for the reassurance!
I figured I would bring up the issue just to be perfectly clear.

**Comment by ebuchman** [comment]
Great! Does this mean you are okay building a non-GPL app powered by Tendermint?

It is defntly our intention to allow non-GPL applications to be powered by Tendermint Core. I'm not sure who would be responsible for initiating a lawsuit over licenses, but we have neither the time, money, nor inclination to do so :D

**Comment by AaronShea** [comment]
I'll be moving forward with trying out tendermint for my application. I've been looking around for solutions and came across this project, and it seemed to fit the bill nicely.
And if would be the Free Software Foundation who would come after those who violate the GPL.

**Comment by ebuchman** [comment]
Wonderful. If you'd like to join our slack, shoot me an email at ethan@tendermint.com. 

We will see about getting a signed statement from the FSF stating that this is all kosher.

**Comment by jaekwon** [comment]
There's too much confusion about the GPL, especially with regards to whether a TMSP app is a separate application or not.  It looks like LGPLv3 kinda works better, but it's got issues too.  What a mess.

We just changed the license to Apache2.0.
