### ISSUE TITLE
Refactor node 'other' info from array to object 

### ISSUE THREAD

**Issue by fedekunze** [tendermint/tendermint#2391]
If you want to get a node's `other` information (such as the [/status](https://tendermint.github.io/slate/?shell#status) endpoint) you have to parse the array items:

```
"other": [
"amino_version=0.12.0",
"p2p_version=0.5.0",
"consensus_version=v1/0.2.2",
"rpc_version=0.7.0/3",
"tx_index=on",
"rpc_addr=tcp://0.0.0.0:26657"
]
```

**Proposal**: Change the array to object and change `tx_index` from `on/off` to boolean value.

```
"other": {
"amino_version": "0.12.0",
"p2p_version": "0.5.0",
"consensus_version": "v1/0.2.2",
"rpc_version": "0.7.0/3",
"tx_index": true,
"rpc_addr": "tcp://0.0.0.0:26657"
]
```

**Comment by melekes** [comment]
Merged to develop.

**Comment by fedekunze** [comment]
thanks @melekes @xla !
