### ISSUE TITLE
Testnet experiences connection issues under load

### ISSUE THREAD

**Issue by philipstanislaus** [tendermint/tendermint#2392]
Thank you for your outstanding work on Tendermint! 

Our team is building THORChain on top of Tendermint using Cosmos. In our initial load tests, we noticed that under heavy load nodes start to loose connections. After some time, nodes give up to reconnect and eventually block creation halts.

We are considering to commit resources to improve Tendermint's robustness – but first need to understand a bit better what is going on here.

**Tendermint version**

```
tendermint_version=0.22.8-d542d2c3
amino_version=0.10.1
p2p_version=0.5.0
consensus_version=v1/0.2.2
rpc_version=0.7.0/3
```

**ABCI app**

https://github.com/thorchain/THORChain

**Environment**:

- **OS** (e.g. from /etc/os-release): 
```
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```
- **Install tools**: See Cosmos SDK
- **Others**: EC2 `c5d.18xlarge` instances running on AWS, all connected using their internal IP addresses for low latency.

**What happened**:

On 9/11/2018, 19:43 UTC the blockchain stopped producing blocks. Until that point, it produced 351,609 blocks with a total of 22,373,891 txs. Around 52 minutes earlier, one of the validators (node0) lost connection. Eventually, all other nodes gave up on reconnecting too. Right now, they are all stuck at different block heights:

```
node0: 351588 from 2018-09-11T18:51:37.882205811Z
node1: 351609 from 2018-09-11T19:43:18.054503634Z
node2: 351609 from 2018-09-11T19:43:18.054503634Z
node3: 351609 from 2018-09-11T19:43:18.054503634Z
```

Please find detailed logs of all 4 validators below.

Analyzing these logs, I found that there were many connection failures, e. g. node1 had the error `Connection failed @ sendRoutine` 61 times and the error `Send failed` 140 times in a 24 hour period.

**Setup** 

We have 4 validators running THORChain, an application based on Cosmos with slight tweaks. I have uploaded all the `config.toml` and `genesis.json` here: https://github.com/swishlabsco/tendermint-testnet-issues/tree/master/2018-09-11_testnet_disconnects_under_load/config . We use a [script](https://github.com/thorchain/THORChain/tree/master/cmd/thorchainspam) to produce a load of around 500 TPS. Running the scripts at 100 TPS does not seem to lead to issues – but that needs to be verified.

**What you expected to happen**:

Nodes not do disconnect

**Have you tried the latest version**: 

No, we are using the latest Cosmos SDK (v0.23.1) which depends on Tendermint v0.22.8

**How to reproduce it** (as minimally and precisely as possible):

Put a lot of load on a testnet until connection issues occur. We use a spam script to create load, which you can find here: https://github.com/thorchain/THORChain/tree/master/cmd/thorchainspam

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

(Logs have ~1 GB in total, so I uploaded them to AWS S3)

Node0: https://s3.us-east-2.amazonaws.com/tendermint-testnet-issues/log-node0.txt
Node1: https://s3.us-east-2.amazonaws.com/tendermint-testnet-issues/log-node1.txt
Node2: https://s3.us-east-2.amazonaws.com/tendermint-testnet-issues/log-node2.txt
Node3: https://s3.us-east-2.amazonaws.com/tendermint-testnet-issues/log-node3.txt

**Config (you can paste only the changes you've made)**:

https://github.com/swishlabsco/tendermint-testnet-issues/tree/master/2018-09-11_testnet_disconnects_under_load/config

**node command runtime flags**:

`thorchaind start`

**`/dump_consensus_state` output for consensus bugs**

https://github.com/swishlabsco/tendermint-testnet-issues/tree/master/2018-09-11_testnet_disconnects_under_load/dump_consensus_state

**Comment by ebuchman** [comment]
Thanks for all the details here!

One thing to note is all the `Send failed` are happening on the mempool channel (ie. `channel=48`, which corresponds to 0x30, ie. https://github.com/tendermint/tendermint/blob/develop/mempool/reactor.go#L19). The logs also show lots of txs being rejected because the mempool is full. So perhaps reducing the mempool size and/or the rate of sending txs will help here. In any case, the connections shouldn't all just eventually fail here, so we'll have to investigate further to figure out what's going wrong.

As for the node heights:

```
node0: 351588 from 2018-09-11T18:51:37.882205811Z
node1: 351609 from 2018-09-11T19:43:18.054503634Z
node2: 351609 from 2018-09-11T19:43:18.054503634Z
node3: 351609 from 2018-09-11T19:43:18.054503634Z
```

Comparing to the logs you sent, it doesn't seem correct. Ie. logs for node0 do show block 351609 at 19:44:07. And node1's logs only seem to go to block 351600 at 19:21:58. Can you clarify?

Further looking into logs for node1, I notice some weird behaviour that could indicate some kind of race condition in the peer reconnection routine that could be related to https://github.com/tendermint/tendermint/pull/2327. Namely, after running it through `grep "p2p" | grep "cd01f386bc5812178a861a4e0e604245950fb013"`, which gives me all p2p messages related to the peer cd01f386bc5812178a861a4e0e604245950fb013, I see:


```
E[09-11|15:41:27.083] Stopping peer for error                      module=p2p peer="Peer{MConn{172.31.47.83:26656} cd01f386bc5812178a861a4e0e604245950fb013 out}" err="pong timeout"
I[09-11|15:41:27.083] Stopping Peer                                module=p2p peer=172.31.47.83:26656 impl="Peer{MConn{172.31.47.83:26656} cd01f386bc5812178a861a4e0e604245950fb013 out}"
I[09-11|15:41:27.084] Reconnecting to peer                         module=p2p addr=cd01f386bc5812178a861a4e0e604245950fb013@172.31.47.83:26656
I[09-11|15:41:27.084] Dialing peer                                 module=p2p address=cd01f386bc5812178a861a4e0e604245950fb013@172.31.47.83:26656
I[09-11|15:41:27.085] Successful handshake with peer               module=p2p peer=172.31.47.83:26656 peerNodeInfo="NodeInfo{id: cd01f386bc5812178a861a4e0e604245950fb013, moniker: node2, network: genesis-alpha [listen 172.31.47.83:26656], version: 0.22.8 ([amino_version=0.10.1 p2p_version=0.5.0 consensus_version=v1/0.2.2 rpc_version=0.7.0/3 tx_index=on rpc_addr=tcp://0.0.0.0:26657])}"
I[09-11|15:41:27.085] Starting Peer                                module=p2p peer=172.31.47.83:26656 impl="Peer{MConn{172.31.47.83:26656} cd01f386bc5812178a861a4e0e604245950fb013 out}"
I[09-11|15:41:27.956] Added peer                                   module=p2p peer="Peer{MConn{172.31.47.83:26656} cd01f386bc5812178a861a4e0e604245950fb013 out}"
I[09-11|15:43:30.066] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{172.31.47.83:26656} cd01f386bc5812178a861a4e0e604245950fb013 out}"
I[09-11|15:45:00.066] We need more addresses. Sending pexRequest to random peer module=p2p peer="Peer{MConn{172.31.47.83:26656} cd01f386bc5812178a861a4e0e604245950fb013 out}"
I[09-11|15:45:32.087] Error reconnecting to peer. Trying again     module=p2p tries=0 err="Error{read tcp 172.31.35.123:33852->172.31.47.83:26656: i/o timeout}" addr=cd01f386bc5812178a861a4e0e604245950fb013@172.31.47.83:26656
```

Notice the last line indicates there was an error reconnecting to a peer we already reconnected too, without the peer being stopped again, which doesn't make sense. Is it possible some log lines could be missing?  We might need to take a closer look at how the persistent peers routine plays with the PEX reactor's dialing new peers.

**Comment by philipstanislaus** [comment]
@ebuchman sorry for not coming back to you earlier – it seems my answer to your question did not get sent: 

> I checked the logs again, and they are indeed from the right nodes. I retreived block heights from the `/status` RPC endpoint, but clearly the log files show different data.

**Comment by philipstanislaus** [comment]
Few new insights: 

* Restarted the nodes without resetting anything. 
* Block production stopped again after a few minutes. 

**Q3/Q4** Missing log lines are caused by log rate limiting. 

```
Okt 09 12:50:07 ip-172-31-5-77.us-east-2.compute.internal thorchaind[2390]: I[10-09|12:50:07.262] Added good transaction                       module=mempool tx=CFB8625403BC53CD82221B09B750F2479E319469 res="&{CheckTx:log:\"Msg 0: \" gas_used:3990 tags:<key:\"sender\" value:\"t0accaddr148ed4m84nnhkwvml3ggvwuq8p0qn4t5a497vrv\" > tags:<key:\"recipient\" value:\"t0accaddr1glgvqunpld6k2t4jz04j70zvqc75pfz9s9m6x3\" > fee:<> }" total=14
Okt 09 12:50:29 ip-172-31-5-77.us-east-2.compute.internal dhclient[2211]: XMT: Solicit on eth0, interval 117590ms.
Okt 09 12:50:34 ip-172-31-5-77.us-east-2.compute.internal systemd-journal[1384]: Suppressed 1098 messages from /system.slice/thorchaind.service
Okt 09 12:50:34 ip-172-31-5-77.us-east-2.compute.internal thorchaind[2390]: I[10-09|12:50:34.700] Added good transaction                       module=mempool tx=7C997F36DCF9D11073BF1409ED1E28CEADB148A7 res="&{CheckTx:log:\"Msg 0: \" gas_used:3990 tags:<key:\"sender\" value:\"t0accaddr1zy683mv92zy3dezrh4xsesr0kajl4p32tmmguz\" > tags:<key:\"recipient\" value:\"t0accaddr1vn0mrvxkp036t87s6g3fjd5eszk03pn5qjmhgn\" > fee:<> }" total=675
```

**Q5** The same error occured, this time with a bit more context in the logs: 
```
Okt 09 12:50:04 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: E3E02382F244ED304649D68D801D5EF988084E80 (239 bytes)
Okt 09 12:50:04 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: 02650070EE17ABA57300AB40729FCD8494C3199D (183 bytes)
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile.(*Group).checkHeadSizeLimit(0xc4207975e0)
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: /Users/philipstanislaus/go/src/github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile/group.go:225 +0xa9
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile.(*Group).processTicks(0xc4207975e0)
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: /Users/philipstanislaus/go/src/github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile/group.go:207 +0x2d
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: created by github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile.(*Group).OnStart
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: /Users/philipstanislaus/go/src/github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile/group.go:105 +0x3f
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: thorchaind.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: Unit thorchaind.service entered failed state.
Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: thorchaind.service failed.
Okt 09 12:50:13 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: thorchaind.service holdoff time over, scheduling restart.
Okt 09 12:50:13 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: Started thorchaind.
Okt 09 12:50:13 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: Starting thorchaind...
```

The error statements contain my local $GOPATH (`/Users/philipstanislaus/go`) which does not exist on the server side. Any idea why?

**Comment by melekes** [comment]
> Does (or could) Tendermint use a worker process to offload CPU intensive work like checkTx and deliverTx to other cores and keep one core free for these functions?

Golang scales pretty well with the number of cores

> Additionally, when I run /dump_consensus_state, I get no response from node0 and node3 (I eventually killed the request after a few hours)

next time please provide the output of `kill -6 <PID>`. https://github.com/tendermint/tendermint/issues/1772#issuecomment-410074054 might be related.

**Comment by melekes** [comment]
> Where does this runtime error come from? => see below

We will need a stack trace and error message. Otherwise, it's impossible to tell why Tendermint had crashed.

**Comment by philipstanislaus** [comment]
> > Does (or could) Tendermint use a worker process to offload CPU intensive work like checkTx and deliverTx to other cores and keep one core free for these functions?
> 
> Golang scales pretty well with the number of cores

It scales well, just wondering whether we can keep a networking/IO goroutine more responsive even if the CPU utilization is at 100%. Not sure how Go handles these cases. 

> > Additionally, when I run /dump_consensus_state, I get no response from node0 and node3 (I eventually killed the request after a few hours)
> 
> next time please provide the output of `kill -6 <PID>`. [#1772 (comment)](https://github.com/tendermint/tendermint/issues/1772#issuecomment-410074054) might be related.

Unclear whether I understood you correctly. Running: 
```bash
> curl -f http://18.223.204.76:26657/dump_consensus_state
```
And then killing the curl request gives me: 
```bash 
> kill -6 51807
> echo "$?"
0
```

**Comment by philipstanislaus** [comment]
> > Where does this runtime error come from? => see below
> 
> We will need a stack trace and error message. Otherwise, it's impossible to tell why Tendermint had crashed.

I can't find an error message in the logs. Will restart another testnet with Cosmos SDK v0.24.2.
> ```
> Okt 09 12:50:04 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: E3E02382F244ED304649D68D801D5EF988084E80 (239 bytes)
> Okt 09 12:50:04 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: 02650070EE17ABA57300AB40729FCD8494C3199D (183 bytes)
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile.(*Group).checkHeadSizeLimit(0xc4207975e0)
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: /Users/philipstanislaus/go/src/github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile/group.go:225 +0xa9
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile.(*Group).processTicks(0xc4207975e0)
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: /Users/philipstanislaus/go/src/github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile/group.go:207 +0x2d
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: created by github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile.(*Group).OnStart
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal thorchaind[2387]: /Users/philipstanislaus/go/src/github.com/thorchain/THORChain/vendor/github.com/tendermint/tendermint/libs/autofile/group.go:105 +0x3f
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: thorchaind.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: Unit thorchaind.service entered failed state.
> Okt 09 12:50:12 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: thorchaind.service failed.
> Okt 09 12:50:13 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: thorchaind.service holdoff time over, scheduling restart.
> Okt 09 12:50:13 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: Started thorchaind.
> Okt 09 12:50:13 ip-172-31-12-75.us-east-2.compute.internal systemd[1]: Starting thorchaind...
> ```
> The error statements contain my local $GOPATH (`/Users/philipstanislaus/go`) which does not exist on the server side. Any idea why?

Do you have any idea why my local $GOPATH might be in the stacktraces? Is that expected because it was built no my machine?

**Comment by ebuchman** [comment]
> Do you have any idea why my local $GOPATH might be in the stacktraces? Is that expected because it was built no my machine?

Yes.

> kill -6 51807

If you run this for the PID of the tendermint process, it will kill the process and dump the complete stack trace in the original terminal the process was running it. Having that info would be super helpful for us since it will show every go-routine running and where the thing might be blocked.

**Comment by philipstanislaus** [comment]
Closing this for now, will reopen when the error reoccurs.
