### ISSUE TITLE
Consider using golang's concurrent map where applicable

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2400]
As of go 1.9, it offers a map safe for concurrent usage. From the map's docs:

The [concurrent] Map type is optimized for two common use cases: (1) when the entry for a given key is only ever written once but read many times, as in caches that only grow, or (2) when multiple goroutines read, write, and overwrite entries for disjoint sets of keys. In these two cases, use of a Map may significantly reduce lock contention compared to a Go map paired with a separate Mutex or RWMutex. 

Link to golang's concurrent map: https://golang.org/pkg/sync/#Map

**Comment by Liamsi** [comment]
cc @marbar3778

**Comment by marbar3778** [comment]
Do we have a problem with cache contention, if so I can look into changing this? seems this is the greatest use case for `sync.Map`

there are some performance degradations when using `sync.Map` until you hit a greater amount of cores used

@ValarDragon

**Comment by ValarDragon** [comment]
I'm not sure, the sync map is only used for `peer.Data`, I'm not familiar with its usage throughout the entire p2p stack.

**Comment by 188751671** [comment]
Hi guys.  I don't understand what "entries for disjoint sets of keys" means.  Could you explain more?
"multiple goroutines read, write, and overwrite entries for disjoint sets of keys."
