### ISSUE TITLE
Use Fsm to manage consensusState?

### ISSUE THREAD

**Issue by bradyjoestar** [tendermint/tendermint#2406]
Currently the state of Consensus are managed by  different function such `enterNewRound`,`enterPropose`,and so on.

The program runs well and robust, but should we use [fsm](https://github.com/looplab/fsm) to manage all the state of consensus?

It will bring extra risk and certainly a big change but benifit from fsm.

**Comment by ebuchman** [comment]
Yep, it's a good idea - we had a long conversation about it and other ideas in https://github.com/tendermint/tendermint/issues/1495.

We've been meaning to summarize the latest state of our thinking on this. @xla and I worked on a design to dramatically improve separation of concerns in the `consensus` package and align the implementation much closer to the spec that @milosevic has been working on (https://github.com/tendermint/spec).

We'll make sure to write up our thoughts on that in a new issue soon. In the meantime I'll close this. Thanks!
