### ISSUE TITLE
[tm-bench] runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by WALL-E** [tendermint/tendermint#2409]
tendermint version: 0.23.1-9e940b95

Steps to reproduce:

[vagrant@dev tm-bench]$tm-bench -T 10 -r 10 -s 39 localhost:26657
panic: runtime error: slice bounds out of range

goroutine 13 [running]:
main.generateTx(0x0, 0x0, 0x27, 0xf7ec95a0bcd06a05, 0x11c84eadb4a4a45b, 0x20, 0xc4200fcb00, 0xc420705d58)
	/home/vagrant/gocode/src/github.com/tendermint/tendermint/tools/tm-bench/transacter.go:266 +0x263
main.(*transacter).sendLoop(0xc42055ea00, 0x0)
	/home/vagrant/gocode/src/github.com/tendermint/tendermint/tools/tm-bench/transacter.go:165 +0x2fb
created by main.(*transacter).Start
	/home/vagrant/gocode/src/github.com/tendermint/tendermint/tools/tm-bench/transacter.go:82 +0x186

**Comment by ValarDragon** [comment]
Oh, we probably should improve that error. Currently tm-bench is set to have a minimum of 40 bytes. (As a Signature + an Address would be larger)

**Comment by WALL-E** [comment]
@ValarDragon has been updated over

**Comment by melekes** [comment]
> Currently tm-bench is set to have a minimum of 40 bytes. (As a Signature + an Address would be larger)

do we really need this artificial bounds? can't we just check if it's > 0

**Comment by melekes** [comment]
If someone want's to test Tendermint with 2 bytes tx, I'll say she has a full right to do that.

**Comment by ValarDragon** [comment]
Sure, we could make the first few bytes the counter (if thats not how it is already) and then truncate. With 2 bytes though, you'll overflow that in any meaningful tm-bench test, and probably will get unexpected results of new txs already being in the cache or still being in the mempool.

I do think 3 bytes is the minimum for any real benchmark.

Until we get around to fixing that though, I'd opt to just make a more user-friendly error msg as the PR does.

**Comment by melekes** [comment]
Merged to develop. Follow-up https://github.com/tendermint/tendermint/issues/2416
