### ISSUE TITLE
Validators can run with Secp256k1 pubkeys

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2414]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
23.1

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Cosmos SDK develop

**What happened**:
Blocks were built with a validator with a Secp256k1Pubkey

**What you expected to happen**:
No blocks to be built / there to be an error or panic

**How to reproduce it** (as minimally and precisely as possible):
Take a gaia genesis file, replace the validator pubkey with a secp one, e.g:
```
"pub_key": {
        "type": "tendermint/PubKeySecp256k1",
        "value": "AmmUPwalYvC/zycpMeUy5X8pPU6oE7DFbu5fo3y8nAoY"
      }
```

We probably should check the key type on `types.NewValidator`, make this a consensus param, or make the consensus codec only know about ed25519 and not secp. I'm leaning towards making this a consensus param, since there is interest in using other signature schemes.

**Comment by ValarDragon** [comment]
If we're making this a consensus parameter, it probably shouldn't be enforced in `types.NewValidator`. Where / when should it be checked? On every validator set update?

**Comment by ebuchman** [comment]
- [ ] Add ValidatorPubkeyTypes to ConsensusParams - #2636 
- [ ] Enforce ValidatorPubkeyTypes in the State

**Comment by ebuchman** [comment]
Completed in https://github.com/tendermint/tendermint/pull/2739
