### ISSUE TITLE
docs: switch to Swagger for RPC

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2419]
blocking on https://github.com/cosmos/cosmos-sdk/pull/2215 
i.e., waiting to see how the SDK does it (and the Jenkins process running smoothly) then we'll port it over.

**Comment by zramsay** [comment]
#1730 and #2880

**Comment by zramsay** [comment]
note: no longer blocking

**Comment by safareli** [comment]
Using swager would be great as it would allow others to generate client library in desired language!

Is there any updates on this, like is it gonna happen in close future or if this WIP already?

**Comment by safareli** [comment]
This should be closed as of #3880

**Comment by marbar3778** [comment]
just need to switch it out on the website then I believe we can close this. Aiming to do that this week.
