### ISSUE TITLE
Error to compile types.proto

### ISSUE THREAD

**Issue by 6kamens** [tendermint/tendermint#2429]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.24.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release): window
- **Install tools**:
- **Others**:

**What happened**:
I want to start GRPC in c# but I cannot compile types.proto .

**What you expected to happen**:
c# .net core file    types.cs and typesGrpc.cs

**Have you tried the latest version**: yes/no 
yes

**How to reproduce it** (as minimally and precisely as possible):

.nuget\packages\Grpc.Tools\1.15.0\tools\windows_x64\protoc.exe --csharp_out Downloads --grpc_out Downloads types.proto --plugin=protoc-gen-grpc=.nuget\packages\Grpc.Tools\1.15.0\tools\windows_x64\grpc_csharp_plugin.exe

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

github.com/gogo/protobuf/gogoproto/gogo.proto: File not found.
google/protobuf/timestamp.proto: File not found.
github.com/tendermint/tendermint/libs/common/types.proto: File not found.
types.proto: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
types.proto: Import "google/protobuf/timestamp.proto" was not found or had errors.
types.proto: Import "github.com/tendermint/tendermint/libs/common/types.proto" was not found or had errors.
types.proto:60:3: "google.protobuf.Timestamp" is not defined.
types.proto:162:12: "common.KVPair" is not defined.
types.proto:172:12: "common.KVPair" is not defined.
types.proto:182:12: "common.KVPair" is not defined.
types.proto:188:12: "common.KVPair" is not defined.
types.proto:232:3: "google.protobuf.Timestamp" is not defined.
types.proto:293:3: "google.protobuf.Timestamp" is not defined.

**Anything else we need to know**:
For example file from GRPC website I can compile it normally but by the same command I cannot compile types.proto .

**Comment by ebuchman** [comment]
Looks like you may need to use the include directive. Ie. in our makefile, we use 

```
INCLUDE = -I=. -I=${GOPATH}/src -I=${GOPATH}/src/github.com/gogo/protobuf/protobuf
```

as part of the call to `protoc`. See https://github.com/tendermint/tendermint/blob/master/Makefile#L43

**Comment by ebuchman** [comment]
Closing this. Let us know if you still have trouble.
