### ISSUE TITLE
Use stdlibs heap instead of the heap in common

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2432]
Currently the only place we use our own heap implementation is for the validator set. We could easily refactor to utilize to use the stdlibs heap implementation, which would likely end up being more efficient. (As that does the O(N) heapify unlike our code which does an `N log(N)` process. If the stdlib's heap interface is deemed as a pain to implement, then we should adapt cmn.Heap to utilize the stdlib's heap implementation imo.

**Comment by Liamsi** [comment]
cc @marbar3778
