### ISSUE TITLE
NodeInfoOther fix

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2433]
Looking at https://github.com/tendermint/tendermint/pull/2426/files#diff-f2fefc7a06ea0d1e0a910196901e50aaR86

- `other.AminoVersion` is in there twice
- `.String()` method is missing `RPCAddress`
- we don't set `RPCAddress` when we create the NodeInfoOther in node.go

**Comment by melekes** [comment]
Oh, thanks for spotting this! It looks like we will need at least 2 reviews going forward before merging.
