### ISSUE TITLE
Unresponsive to signal interupts while sleeping for genesis time

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2434]
As of https://github.com/tendermint/tendermint/pull/2389 we sleep until the genesis time is reached, but we don't set up our signal catching until we start the node, so we don't respond to CTRL-C while sleeping. We should probably use a select statement over a ticker and signal channel instead of the sleep.

**Comment by xla** [comment]
Alternatively can't we setup our signal trapping earlier?

**Comment by melekes** [comment]
Merged to develop.
