### ISSUE TITLE
Convergence off AppVersion

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#2448]
From https://github.com/tendermint/tendermint/pull/2435#issuecomment-422973724

> Current thinking is no, under the assumption that we want to be able to sync a peer across multiple app versions. But this also means we don't know if we're actually compatible with a peer when we connect to them, since they could be on an old height/version, and we won't find out until we actually disagree on blocks somewhere.

> More prudent might be to consider tracking the correct version for each height, and enforcing that on peers, and having peers update each other when their version changes, but this sounds a bit complected, so maybe our initial assumption needs to be challenged.

How will we communicate AppVersion changes?
Do we need to convergent and sync to a unified one?

- [ ] lay out pros and cons for different approaches
- [ ] compile solution with most merrit into ADR

**Comment by marbar3778** [comment]
In https://github.com/tendermint/tendermint/pull/5031 appVersion was added to consensusparams. This seems to be enough convergence.
