### ISSUE TITLE
fastsync's peerTimeout is too small

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2456]
Block's default maxSize is 21M
https://github.com/tendermint/tendermint/blob/d419fffe18531317c28c29a292ad7d253f6cafdf/types/params.go#L55-L61

but in fastsync mode, peerTimeout only 15 Second, this need network speed > 1M/s， which is strict in product circumstance, which may lead fastsync to failed.
https://github.com/tendermint/tendermint/blob/d419fffe18531317c28c29a292ad7d253f6cafdf/blockchain/pool.go#L49

I suggest peerTimeout should simply make longer，or adjust dynamically with current fetching block‘s size.

**Comment by goolAdapter** [comment]
As the BlockPool.removeTimedoutPeers done the timeout logic，which eliminate the peers below 7.5 KB/s, so bpPeer.onTimeout should not directly set the didTimeout flag. I'll make a PR for this.

**Comment by xla** [comment]
@goolAdapter Thanks, appreciated!
