### ISSUE TITLE
fastsync may stuck by a wrong block

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2457]
When VerifyCommit failed, the logic only redo the first block request,  but the wrong block may was the second one. In this situation, didProcess will always empty loop in the next moment .
https://github.com/tendermint/tendermint/blob/d419fffe18531317c28c29a292ad7d253f6cafdf/blockchain/reactor.go#L300-L312

**Comment by ebuchman** [comment]
Merged!
