### ISSUE TITLE
fastsync should separate from the blockchain directory

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2458]
The blockchain directory’ duty was represented by store.go,  and the fastsync(reactor.go, pool.go) have a little puzzle here, should they move to a new directory named fastsync?

**Comment by ebuchman** [comment]
Great point! Once upon a time we thought about just moving the store piece out and combining it with the storage stuff in `state` into a new `store` pkg. Worth reconsidering. Might also be nice to change the name so its more clearly the `fastsync` reactor or similar.

**Comment by melekes** [comment]
> Once upon a time we thought about just moving the store piece out and combining it with the storage stuff in state into a new store pkg. 

`store` pkg now exists.

Closing in favor of https://github.com/tendermint/tendermint/issues/4594.
