### ISSUE TITLE
Start{GRPC,HTTP{,AndTLSServer}}Server would benefit from a concurrency-friendly design

### ISSUE THREAD

**Issue by alessio** [tendermint/tendermint#2463]
`StartGRPCServer()`, `StartHTTPServer()`, and `StartHTTPAndTLSServer()` spawn goroutines that wrap their respective `Serve()` calls and return `net.Listener` and `error` values that live in the main function's body.
Consequently, although the error returned from `Serve()` is logged, it is never passed back to the client.
This behaviour makes it impossible for the caller to adequately handle errors returned by the underlying calls and, more importantly, may lead the process to hang indefinitely.

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/2791. Thanks @alessio 🧀
