### ISSUE TITLE
libs/common: Remove TrapSignal()

### ISSUE THREAD

**Issue by alessio** [tendermint/tendermint#2464]
It is quite conventional in the UNIX world to return `128 + signal code` upon exit due to a signal, so I'd suggest `TrapSignal()` call os.Exit(128 + int($signalcode)) instead of `os.Exit(1)`

**Tendermint version**: develop

**ABCI app**: Gaia

**Environment**: `Ubuntu 18.04`

CC'ing @jaekwon, who appears to be the original author of the function.

**Comment by ValarDragon** [comment]
Cc @xla who I believe was suggesting just deleting trap signal entirely, as every caller needs to handle logs and which exit codes to catch differently.

**Comment by xla** [comment]
What @ValarDragon said, let's get rid of this piece alltogether. Thanks for raising the issue @alessio, totally agree with the assessment. Reframed the issue as we want to remove it for the following issues:

* logging should never been done unconditionally in library code
* exit codes should be meaningful
* signals should be tied into proper functionality
  * config reload
  * graceful teardown of resources

**Comment by Liamsi** [comment]
cc @marbar3778

**Comment by melekes** [comment]
TrapSignal is much more flexible right now.
