### ISSUE TITLE
sort validators in validator set hash by power

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2478]
Currently the validator set hash has the validators sorted by address. If it was sorted by power, it would be simpler for lite clients to verify signatures in order of most power to least power, and stop once they hit 2/3rds of power. While this is already possible when sorting by address, it takes less internal nodes to prove this if they are sorted by power. (Assuming we don't send repeat internal nodes, as that would be silly) I can draw a diagram of this if that would be helpful for the docs.

This would mean that a power update for a validator will require recomputing more internal nodes within the merkle tree, but that seems like a reasonable trade-off. Instead of it taking log n hashes to update, it may now take at most `2(log n) - 1` hashes. (Less if there are more repeated internal nodes, as will be likely, since large power updates seem unlikely)

When gossiping, we communicate the validator set index, thus it is irrelevant if the local storage is done by power or by address. If there is a reason for requiring efficient indexing by address (i.e. for RPC), we can maintain two arrays in the validator set object (one sorted by power, one by address), and only do merkelization / consensus with the one that is by power.

**Comment by melekes** [comment]
Great proposal 👍 Interestingly enough both in light client and state/validation.go (validating incoming block) we do a comparison after we sum all voting powers https://github.com/tendermint/tendermint/blob/2be4b0fe050f04ca5126d51e9bec0fc7ea8aaa25/types/validator_set.go#L634

**Comment by melekes** [comment]
A lot of our tests depend on a sorting method. We can rewrite them to be less fragile, but it will take time.

**Comment by melekes** [comment]
> If there is a reason for requiring efficient indexing by address (i.e. for RPC), we can maintain two arrays in the validator set object (one sorted by power, one by address), and only do merkelization / consensus with the one that is by power.

We use `ValidatorSet#GetByAddress (`rg "GetByAddress" -g '!*_test.go'`) and `ValidatorSet#HasAddress` (`rg "HasAddress" -g '!*_test.go'`) in a number of places. Both of them use  sort.Search (binary search) to find the address and its index in the sorted array.

**Comment by melekes** [comment]
accepted
