### ISSUE TITLE
Mempool: replay txs after crashing

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#248]
A WAL would allow us to save txs in case the process crashes, though details of playback are tricky since some will be committed and some wont. Additionally, it can be used to replay txs received while the proxyApp is down

**Comment by ebuchman** [comment]
mempool saves txs to disk ala https://github.com/tendermint/tendermint/commit/642a24dc9c4fe8f44035a753e4213c9554151e08

open issue what to do about replaying txs

**Comment by adrianbrink** [comment]
@ebuchman Has this been resolved?

**Comment by ebuchman** [comment]
Nope :)

**Comment by ebuchman** [comment]
Closing this for now. It's more a concern for non-public deployments. We'll probably have to revisit it some time down the road when a user needs it. Meanwhile it will get documented in https://github.com/tendermint/tendermint/issues/1494
