### ISSUE TITLE
docs: Document optimal configuration per environment

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2481]
In enterprise setting with small clusters (for example up to 20 nodes) the most preferable option is probably disabling mempool broadcasting and pushing this responsibility to client. We should clarify this option in the documentation.

**Comment by xla** [comment]
Might be good to surface the setups we have heard and advise on a per environment basis. Dimensions to look at size, connectivity, locality and security model.

**Comment by marbar3778** [comment]
Not sure how much value this will add as we will still get questions to what we think is best. This can vary from one enterprise to another with the same network size. The best we can do is thoroughly document options a node operator has. Teams can reach out if they have more specific questions.

**Comment by marbar3778** [comment]
In working with a couple teams and running nodes on various networks, it is best to leave this documentation up to the application. Tendermint can run with 2-4 gb of ram, but an application may require 8gb minimum. Saying Tendermint requires x could confuse people. 

We can only document how to turn off and on various features. 

Closing this issue for the above reasons.
