### ISSUE TITLE
App centric interpretation of concepts

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2483]
Current Tendermint documentation and interpretation of concepts is block centric, i.e., concepts are explained with a relation to a corresponding block. This is a well known source of confusion and misunderstanding. We will list here just few examples from the current spec:

- https://github.com/tendermint/tendermint/blob/develop/docs/spec/abci/abci.md#query, check description of Height field in both request and response. 
"The block height from which data was derived. Note that this is the height of the block containing the application's Merkle root hash, which represents the state as it was after committing the block at Height-1"

- https://github.com/tendermint/tendermint/blob/develop/docs/spec/blockchain/blockchain.md#header, check description of LastCommitHash ("commit from validators from the last block") or AppHash ("state after txs from the previous block")

In this proposal the idea is to interpret concepts from the application perspective, i.e., make it app centric. Tendermint is BFT SMR (state machine replication) middleware which is used to replicate deterministic applications. An application that is being replicated is transitioning between versions (heights) where each version is committed by a block at the corresponding height. Block is also used to provide input (list of transactions) for a next version (height). Furthermore, block is decided by the currently committed validator set. As in Tendermint application is responsible for changes to the validator set, the application at height h defines validator set version h. The validator set version h is committed by the block at height h; therefore it is used to decide content of the next block, i.e., block h+1. 

This idea is illustrated on the following diagram (Picture in better resolution can be found here: 
[App centric api.pdf](https://github.com/tendermint/tendermint/files/2414723/App.centric.api.pdf))

![image](https://user-images.githubusercontent.com/1465543/46004827-23149d80-c0b4-11e8-863a-4be33b12d1eb.png)

With this approach the examples from above are now interpreted as follows:

- Query for height h returns the state at the height h committed by the block h. 

- Given a Header for height h we have the following interpretation of fields:

       // prev block info
	LastBlockID BlockID

      // hashes from the app output at the height h; input committed by block h-1
      AppHash            []byte //  the (current) app state at height h 
     LastResultsHash    []byte // root hash of all results from the txs that are executed by application 
                                         at height h (txs are committed in block h-1) 
     NextValidatorsHash []byte // the validator set at height h. It is used to commit block h+1.

      ValidatorsHash     []byte // the validator set that commits this block 
      Q: Do we need this field as it is present in the previous block as NextValidatorsHash?
      
       // hashes of block data
	LastCommitHash []byte // commit from validators at height h-1
        DataHash       []byte // Merkle root of transactions (that are input for app at height h+1)

**Comment by cwgoes** [comment]
Thanks, this sounds possibly much clearer from an ABCI application developer's perspective.

> As in Tendermint application is responsible for changes to the validator set, the application at height h defines validator set version h. The validator set version h is committed by the block at height h; therefore it is used to decide content of the next block, i.e., block h+1.

Isn't this no longer true since `NextValSet` - wouldn't it be: "The validator set version h is committed by the block at height h and is used to decide content of block h + 2"?

**Comment by milosevic** [comment]
> Isn't this no longer true since `NextValSet` - wouldn't it be: "The validator set version h is committed by the block at height h and is used to decide content of block h + 2"?

+2 in the current explanation comes from the fact that txs that affect val set changes that are part of block h will be used to decide content of block h+2. In this proposal the idea is to talk only about committed valset (the one that is currently in power and decides blocks) and the next one or tentative that is not committed yet. Once committed it will decide the content of the next block. In practice this means that txs that affect val set proposed in block h will be committed in the block h+1, and therefore block h+2 will be committed by the new val set. Does this answer to your question?

**Comment by cwgoes** [comment]
> +2 in the current explanation comes from the fact that txs that affect val set changes that are part of block h will be used to decide content of block h+2. In this proposal the idea is to talk only about committed valset (the one that is currently in power and decides blocks) and the next one or tentative that is not committed yet. Once committed it will decide the content of the next block. In practice this means that txs that affect val set proposed in block h will be committed in the block h+1, and therefore block h+2 will be committed by the new val set. Does this answer to your question?

I see, it does, thanks. The diagram is particularly helpful.

**Comment by Liamsi** [comment]
Maybe I've missed this in the docs somewhere but I couldn't find the rationale behind the "deferred" execution model (why was the decision made the proposers don't execute the block before they propose it). I think a sentence or two in the tendermint docs would be appropriate.
