### ISSUE TITLE
Write up ADR for mempool thread design

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#2484]
The idea we had converged on at the end of the convo was basically to have a concurrent tree with sorting enabled for storing the bulk of the mempool, with txs verified independently. However, each validator should also maintain a few "threads" of txs. The idea of a "thread" is that these are all verified to pass CheckTx when ran sequentially. (So the proposer can basically instantly propose its highest value thread) This is unlike the mempool, as the mempool constantly changes ordering.

When initially building a thread, you make it sorted by value. If you detect that you are proposing soon, you check to see if your mempool contains any txs with greater fees than what you have in the thread. Suppose there are `n` better txs in the mempool than whats in the thread. Then you remove the last `n` txs from the thread, and put these new ones.

The idea behind multiple threads is to reduce re-computation when you receive another persons block. There is a lot of design work for how to optimally do this thread concept. Please note that this thread design can be done incrementally. Phase 1 may just have a single thread, and a slightly slower update process right before you Reap. Later phases can incorporate more threads, and more improvements for incremental updates, and detection for when you will be proposing soon.

_Originally posted by @ValarDragon in https://github.com/tendermint/tendermint/issues/2147#issuecomment-424087749_

**Comment by marbar3778** [comment]
@alexanderbez this closed with mempool v1?

**Comment by alexanderbez** [comment]
I'm not really sure what this issue is trying to achieve tbh. In the mempool v1 we keep a main thread-safe store (map) while building indexes on top of it, such as a gossip index and priority index.
