### ISSUE TITLE
Argument `--create_empty_block=false` does not work as excepted

### ISSUE THREAD

**Issue by ggarri** [tendermint/tendermint#2487]
**Tendermint version**: 0.23.1-9e940b95

**ABCI app**: Internal project

**Environment**:
- **OS**: 4.15.0-34-generic #37-Ubuntu
- **Install tools**: `geth`
- **Others**: N/A

**What happened**:
New Block has been created with `0 trxs` even when the flag `consensus.create_empty_blocks_interval=false`

**What you expected to happen**:
I expect from Tendermint node to not generate new Block meanwhile there are not new transaction in `mempool`

**Have you tried the latest version**: yes

**How to reproduce it**: Run a private network with a single node

**Logs**:
```
I[09-25|16:12:58.335] waitForTxs                                   module=consensus height=291 round=0 value=true
I[09-25|16:12:58.335] needProofBlock                               module=consensus height=291 round=0 value=true
I[09-25|16:12:58.335] enterPropose(291/0). Current: 291/0/RoundStepNewRound module=consensus height=291 round=0
I[09-25|16:12:58.335] enterPropose: Our turn to propose            module=consensus height=291 round=0 proposer=083CACB8C7F67055643D80540795E6A83DA85079 privValidator="PrivValidator{083CACB8C7F67055643D80540795E6A83DA85079 LH:290, LR:0, LS:3}"
I[09-25|16:12:58.338] Signed proposal                              module=consensus height=291 round=0 proposal="Proposal{291/0 1:99DA1C94B251 (-1,:0:000000000000) 054673BE9088 @ 2018-09-25T16:12:58.336026829Z}"
I[09-25|16:12:58.340] Received proposal                            module=consensus proposal="Proposal{291/0 1:99DA1C94B251 (-1,:0:000000000000) 054673BE9088 @ 2018-09-25T16:12:58.336026829Z}"
I[09-25|16:12:58.342] Received complete proposal block             module=consensus height=291 hash=9DBADA1EEF6EF8037E28C20081F6D32358CA2FF5
I[09-25|16:12:58.342] enterPrevote(291/0). Current: 291/0/RoundStepPropose module=consensus 
I[09-25|16:12:58.342] enterPrevote: ProposalBlock is valid         module=consensus height=291 round=0
I[09-25|16:12:58.344] Signed and pushed vote                       module=consensus height=291 round=0 vote="Vote{0:083CACB8C7F6 291/00/1(Prevote) 9DBADA1EEF6E EE25F15C381B @ 2018-09-25T16:12:58.342598126Z}" err=null
I[09-25|16:12:58.346] Added to prevote                             module=consensus vote="Vote{0:083CACB8C7F6 291/00/1(Prevote) 9DBADA1EEF6E EE25F15C381B @ 2018-09-25T16:12:58.342598126Z}" prevotes="VoteSet{H:291 R:0 T:1 +2/3:9DBADA1EEF6EF8037E28C20081F6D32358CA2FF5:1:99DA1C94B251(1) BA{1:x} map[]}"
I[09-25|16:12:58.346] enterPrecommit(291/0). Current: 291/0/RoundStepPrevote module=consensus height=291 round=0
I[09-25|16:12:58.346] enterPrecommit: +2/3 prevoted proposal block. Locking module=consensus height=291 round=0 hash=9DBADA1EEF6EF8037E28C20081F6D32358CA2FF5
I[09-25|16:12:58.348] Signed and pushed vote                       module=consensus height=291 round=0 vote="Vote{0:083CACB8C7F6 291/00/2(Precommit) 9DBADA1EEF6E 478365C2085A @ 2018-09-25T16:12:58.346686475Z}" err=null
I[09-25|16:12:58.350] Added to precommit                           module=consensus vote="Vote{0:083CACB8C7F6 291/00/2(Precommit) 9DBADA1EEF6E 478365C2085A @ 2018-09-25T16:12:58.346686475Z}" precommits="VoteSet{H:291 R:0 T:2 +2/3:9DBADA1EEF6EF8037E28C20081F6D32358CA2FF5:1:99DA1C94B251(1) BA{1:x} map[]}"
I[09-25|16:12:58.350] enterCommit(291/0). Current: 291/0/RoundStepPrecommit module=consensus height=291 commitRound=0
I[09-25|16:12:58.350] Commit is for locked block. Set ProposalBlock=LockedBlock module=consensus height=291 commitRound=0 blockHash=9DBADA1EEF6EF8037E28C20081F6D32358CA2FF5
I[09-25|16:12:58.351] Finalizing commit of block with 0 txs        module=consensus height=291 hash=9DBADA1EEF6EF8037E28C20081F6D32358CA2FF5 root=6134703BB806AD5E446DB2559B28D1B13D3787B16990B57EFBE5FF248A87B7E0
```

**Config**:N/A

**node command runtime flags**: `--consensus.create_empty_blocks=false`

**`/dump_consensus_state` output for consensus bugs**: N/A

**Anything else we need to know**:
Method [**needProofBlock**](https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L795) always returns `True`. because `lastBlockMeta.Header.AppHash` and `cs.state.AppHash` are never equal. That happens because the the ABCI App uses current system timestamp as part of the header object, causing that every consecutive block header different and therefore every `AppHash`.

**Comment by ggarri** [comment]
Hi @ebuchman , just one question regarding the issue I reported. Is there any use case where `create_empty_block=false` carries an actual action of not creating empty blocks? As far as I have seen debugging Tendermint code *needProofBlock* will never return False, because Block Headers needs to include the current system timestamp otherwise it fails, and if we add same timestamp into two block it also throws an exception.

Would you mind to provide me a bit more of context on why `needProofBlock` returns True if two consecutive block has different `AppHash`? Is there any logic reason to not wait for transactions there even when it was told to Tendermint service to do so? I had been testing with the following implementation:

```
func (cs *ConsensusState) needProofBlock(height int64) bool {
	if height == 1 {
		return true
	}

	return false
}
```

And Tendermint service seems to work as expected, for my understanding ofc. 

Thanks in advance for you time :)

**Comment by ebuchman** [comment]
> As far as I have seen debugging Tendermint code needProofBlock will never return False, because Block Headers needs to include the current system timestamp otherwise it fails, and if ABCI App add same timestamp into two block it also throws an exception.

Not sure what timestamp has to do with this. `needProofBlock` only returns true if the app hash changed. The reason for this is to support proofs. If you have a tx in block H that changes the state to X, the new app hash will only be included in block H+1. If after your tx is committed, you want to get a lite-client proof for the new state (X), you need the new block to be committed in order to do that because the new block has the new app hash for the state X. That's why we make a new (empty) block if the app hash changes. 

Make sense?

**Comment by ggarri** [comment]
Yes it makes sense, but the problem on the current implementation of `needProofBlock` is that even if block H does not include new transaction and the state in block H+1 is exactly the same that method returns true causing two empty block to be committed into the chain, and the process repeat in an infinitive loop of empty blocks.

The timestamp is the root cause of that, because the AppHash of block H and block H+1 are different because both blocks are including as part of their BlockHeader the current system timestamp. And that is why I was wondering in which case the use of `--create_empty_block=false` is helping to not chain empty block. 

According to your explanation we only need to commit the block `H+1` with not transactions in it, ONLY when block `H` contains at least one transaction which cause a chain on the local state. am I right? If so, wouldn't it be a better way to do that replacing the comparative of AppHash by something a bit more sophisticate?

**Comment by ebuchman** [comment]
> AppHash of block H and block H+1 are different because both blocks are including, as part of their BlockHeader, the current system timestamp. 

The BlockHeader is a function of the timestamp, but the AppHash does not have to be. For instance, the AppHash in the `kvstore` app is not a function of the timestamp, just the transaction data.

> and the process repeat in an infinitive loop of empty blocks.

Are you saying this always happens? If the AppHash doesn't change, when an empty block is committed, then the block production should stop until a new tx comes. If you store block headers in the app state, then yes, this is a problem.

> don't rely on AppHash and instead we check if previous block included at least one transaction

The reason we rely on AppHash is because the state could change during an empty proofBlock, so if we want proofs of the new state, we have to make another block. Relying on the AppHash changing is a bit of a hack for solving this, since apps may want to have their AppHash change every block without Tendermint making infinite blocks - hence #1909 .

We could remove the dependence on AppHash in the meantime, and only make blocks if there are transactions (or evidence). It means we won't have proofs for time-dependent transitions in the empty proofBlock, but perhaps that is worth it to eliminate the confusion in this feature.

**Comment by ebuchman** [comment]
Closing this for #1909. Added a note there about how we could improve this in the short term.
