### ISSUE TITLE
Separate IndexerService from Tendermint core

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2491]
The IndexerService is IO intensive，and easy to suffer from DDOS(TxIndex.Search may scan full db). It's content was duplicately stored by blockstore and stateDB，which blockstore have Block for Tx and stateDB have ABCIResponses for ResponseDeliverTx.

So it's safe to remove the index data.  It's better to separate IndexerService to a independent service? this may improve performance.

As a result,  TxSearch not support by the core, IndexerService can implement with mysql.

**Comment by melekes** [comment]
Hi! Thank you for raising this issue. We're aware of extensive IO and have plans to

1) improve existing indexer by changing the underlying DB structure https://github.com/tendermint/tendermint/issues/1835#issuecomment-421062709
2) support external indexer https://github.com/tendermint/tendermint/issues/1161

I've created a separate issue for KV indexer to avoid doing full scans https://github.com/tendermint/tendermint/issues/2492

**Comment by ebuchman** [comment]
> stateDB have ABCIResponses for ResponseDeliverTx.

Note this is only true for the latest block to support recovery from crash failure. The state does not store abci responses for more than one block (so its not duplicating whats stored in the indexer). The indexer is the only place we store the transaction results for all past blocks.

**Comment by goolAdapter** [comment]
@ebuchman thanks，but ApplyBlock save ABCIResponses at each height, was there something I misunderstand? the statedb will prune dynamically?
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/state/execution.go#L66-L87

**Comment by ebuchman** [comment]
Whoops looks like I was wrong about that! Thanks for noticing. We should definitely try to do some deduplication there!
