### ISSUE TITLE
Re-think the binaries structure

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2495]
original comment: https://github.com/tendermint/tendermint/issues/1908#issuecomment-402746760

proposal:

```
abci-cli -> tendermint abci
tm-monitor -> tendermint tools monitor
tm-bench -> tendermint tools bench
tendermint-peers -> tendermint peers
```

the last option is from #1723

can perhaps drop the `tools` and just go `tendermint monitor/bench`

**Comment by xla** [comment]
All in favour of conslidating commands. Proposal seems sound.

**Comment by thanethomson** [comment]
Followed the trail to this issue from #3327. Do we still want one binary to rule them all? What are the tradeoffs here?

Some of the pros:
1. Simpler interface for developers and users. Just get one binary and you're good to go.
2. Simpler release process for Tendermint (especially if benchmarking/monitoring/debugging tooling is built into the executable).

Some of the cons:
1. Increased attack surface through increased complexity.
2. Does not allow for functionality (e.g. `tm-bench`) to evolve independently as easily.
3. Will require a good look at, and rework of, the UX of the various tools we want to incorporate into the Tendermint core binary. For example, `tm-bench` uses Golang's built-in `flag` package, whereas Tendermint core itself uses `cobra`/`viper`. If we consolidate functionality, we should not be using different packages to achieve the same functionality.

I suppose the question then becomes, what's the heuristic we use to decide whether something should be part of the Tendermint core binary, or should it be an external tool?

**Comment by marbar3778** [comment]
this would increase the binary size, if I'm not mistaken and I recently closed an issue about the binary being to big.

**Comment by thanethomson** [comment]
Yeah I wouldn't be too concerned about binary size. I'm more concerned about the other issues, like opening ourselves up to other kinds of security problems. e.g. if someone can compromise a box running a validator, even as a non-privileged user, could they do something with the Tendermint tools to compromise security that they wouldn't have been able to do if the tools weren't built into the Tendermint binary?

**Comment by melekes** [comment]
I generally agree with https://github.com/tendermint/tendermint/issues/2495#issuecomment-518771904. But there's no question to me whenever we should include debugging tool into tendermint. Having default monitor would be good for first time users, but that's not as important.

**Comment by ebuchman** [comment]
One option is to consolidate everything and release that binary, but also provide a compile option, eg. `make build_prod`, for people to build their own binaries that don't include these tools.  

Of course it will mean changes to those tools will go at tendermint pace, but if we also integrate them into Tendermint's CI process, it's probably for the better.

**Comment by marbar3778** [comment]
tm-bench & tm-monitor have recently been removed. 
Currently what is left is abci-cli (not sure if it's used) and tm-signer-harness which are on there own. I think the current structure is fine. If people disagree then please reopen this issue.

**Comment by melekes** [comment]
> abci-cli (not sure if it's used)

we should remove it too imho
