### ISSUE TITLE
rpc: Make /health smarter

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2496]
Original issue: https://github.com/tendermint/tendermint/issues/1296

We now have `/health` endpoint, which returns 200 OK if everything is OK. If Tendermint crashed, you wouldn't get anything.

Modern load-balancers can balance requests not only based on the status code but by reading and analysing the request's body.

`/health` endpoint should return 

1. node's height & max peer height - to indicate if the node is lagging behind the network
2. number of RPC requests in-flight (?)

**Comment by marbar3778** [comment]
believe these would be better suited in the `/status` route instead of here. this issue https://github.com/tendermint/tendermint/issues/3983 encapsulates it quite well, will close this in favor of the before mentioned issue
