### ISSUE TITLE
Need signals to application layer when start/end of fast-sync

### ISSUE THREAD

**Issue by Thunnini** [tendermint/tendermint#2498]
I want to create metrics for basic modules and my custom modules on cosmos-sdk.  But without recognizing fast sync, metrics will be strange until finishing catching up. In tendermint, it seemed that recording metrics is started after fast sync ends. But in application layer, I have no way to know whether I'm in fast sync or not. So metrics drawn in cosmos-sdk will look very strange during the initial fast-sync state. I want to skip tracking up metrics during fast-sync state.

My idea is to signal the start/end of fast-sync state to the application layer via SetOption abci. However, the SetOption abci does not seem to be currently used. And I can not be sure that the setOption abci is intended for this purpose...

**Comment by ebuchman** [comment]
Is it sufficient to use the `.result.sync_info.catching_up` in the `/status` end point? This is also now exposed (on develop) on the prometheus metrics under `fast_syncing`.

**Comment by Thunnini** [comment]
@ebuchman Then perhaps I should query the tendermint for a fast sync status periodically, but it does not seem to be a good way. And maybe I can not see the status of prometheus in application layer. It is likely that users will be able to draw a graph by creating a query that ignores other values ​​according to fast sync metrics. Personally, I do not think this is a good way either.

**Comment by ebuchman** [comment]
> My idea is to signal the start/end of fast-sync state to the application layer via SetOption abci. However, the SetOption abci does not seem to be currently used. And I can not be sure that the setOption abci is intended for this purpose...

This actually sounds reasonable. We don't currently use SetOption, but it could be valuable to set it, perhaps with key="sync_mode" and value={"consensus", "blockchain", "handshake", "state"}. One important consideration is that using SetOption should not impact the state machine itself, only operational concerns like metrics.

**Comment by ebuchman** [comment]
Another option is to fire a new event type when we switch to consensus. This might be simplest.

**Comment by JayT106** [comment]
@marbar3778 could you please assign this issue to me? thanks!
