### ISSUE TITLE
DSL for consensus testing

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#250]
we can even use a simple process calculus without mobility or replication as a base for this.

**Comment by ebuchman** [comment]
Would benefit from https://github.com/tendermint/tendermint/issues/1495

**Comment by ebuchman** [comment]
Should be able to test things like https://github.com/tendermint/tendermint/issues/1575 where the block is committed but someone doesnt see it and moves to the round where they're the proposer and propose something else - they should eventually commit the right thing!

**Comment by jackzampolin** [comment]
Going to close this issue as we are using formal verification for this.
