### ISSUE TITLE
Some performance benchmark viewpoint

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2504]
I have make some performance test. 
1、When use the default setting
```
tm-bench -T 10 -r 10000 -v localhost:26657

Stats          Avg       StdDev     Max      Total     
Txs/sec        2709      1924       5000     27091     
Blocks/sec     0.700     0.458      1        7      
```
2、Because the default MempoolConfig.Size == 5000, mempool will discard txs when it's full, change the value to 50000
```
tm-bench -T 10 -r 10000 -v localhost:26657

Stats          Avg       StdDev     Max      Total     
Txs/sec        3578      2986       6902     35782     
Blocks/sec     0.600     0.490      1        6     
```
3、There's print so many logs, like "WSJSONRPC" and "Added good transaction" in console, redirect it to file, the performance is improved.
```
tm-bench -T 10 -r 10000 -v localhost:26657

Stats          Avg       StdDev     Max       Total     
Txs/sec        5199      7845       21108     51992     
Blocks/sec     0.400     0.490      1         4      
```
4、Just comment the log, because it's only uesed for info. the Throughput up to 6711/s
```
tm-bench -T 10 -r 10000 -v localhost:26657

Stats          Avg       StdDev     Max       Total     
Txs/sec        6711      10825      29816     67107     
Blocks/sec     0.300     0.458      1         3    
```
5、At this time, the bottleneck is consensus wal, each msg wrote to wal for crash recover.
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/consensus/state.go#L612-L625
while input massive txs, for example 10000, each tx size is 250. the block size nearly 2.5M, split to 40 parts, cause 40 sync.
it's seems can reduce the sync for internalMsgQueue, because local blockParts can treat as a whole previously. 
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/consensus/state.go#L915-L918
this can improve performance significant.
```
tm-bench -T 10 -r 15000 -v localhost:26657
Stats          Avg       StdDev     Max       Total      
Txs/sec        13078     7919       19351     130779     
Blocks/sec     0.800     0.400      1         8    
```
As the wal used only for crash(was I misunderstand?), I think it can use a memfile to replace the wal, we can only write the latest consensus process step, reset it after committed. this can simplify the design, and improve performance a little.

by the way, the default proposal timeout 3s seems too small when input massive txs, it's easy to meet #1745

**Comment by ebuchman** [comment]
Thank you very much for this! The WAL is necessary for recovering from crash and for debugging. If something goes wrong (eg. byzantine behaviour like precommitting without seeing a polka), it's the only place where we persist the consensus state info right now.

That said, I think it's correct that we don't need to sync the block parts, only our votes.

**Comment by goolAdapter** [comment]
@ebuchman ，thank you，but I think debugging is a offline task. as #2491，I still insist that other disk IO task should separate from tendermint core，this is important to improve throughput, which is finally 
 limited by the disk io. 
as an example, it's better to have an accompany machine deploy logserver, indexserver, debugserver etc，network io is easy to meet 100K iops and 1G/s in local data center.

**Comment by melekes** [comment]
Thank you @goolAdapter for testing Tendermint 👍 We incorporated many of your findings since Sept. 2018 (e.g. Tendermint no longer does fsync for every consensus message and does not produce that many log messages)
