### ISSUE TITLE
Evidence store may leak resource

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2515]
there is a leak, iter need defer iter.Close().
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/evidence/store.go#L100-L101

by the way, https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/evidence/store.go#L82-L85
should replace with reversing trick to eliminate temp slice.
```
for i := len(a)/2-1; i >= 0; i-- {
	opp := len(a)-1-i
	a[i], a[opp] = a[opp], a[i]
}
```
I'll make a PR for this issue.

**Comment by melekes** [comment]
Merged to develop. Thanks!
