### ISSUE TITLE
Is it possible to receive two precommits almost the same time and trigger cs.tryFinalizeCommit(height)  twice?

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#2517]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
func (cs *ConsensusState) enterCommit(height int64, commitRound int) {
	logger := cs.Logger.With("height", height, "commitRound", commitRound)

	if cs.Height != height || cstypes.RoundStepCommit <= cs.Step {
		logger.Debug(fmt.Sprintf("enterCommit(%v/%v): Invalid args. Current step: %v/%v/%v", height, commitRound, cs.Height, cs.Round, cs.Step))
		return
	}
	logger.Info(fmt.Sprintf("enterCommit(%v/%v). Current: %v/%v/%v", height, commitRound, cs.Height, cs.Round, cs.Step))

	defer func() {
		// Done enterCommit:
		// keep cs.Round the same, commitRound points to the right Precommits set.
		cs.updateRoundStep(cs.Round, cstypes.RoundStepCommit)
		cs.CommitRound = commitRound
		cs.CommitTime = tmtime.Now()
		cs.newStep()

		// Maybe finalize immediately.
		cs.tryFinalizeCommit(height)
	}()

**What you expected to happen**:
Do we need to add atomic cas mechanism to be more rigorous handling the concurrency?

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by goolAdapter** [comment]
Hi, I have just read this code, may have some opinions.
you are right, tryFinalizeCommit may trigger more than once, but once it was succeeded，because Height was incremented,  the next enterCommit will immediately return.
enterCommit  will always executed in receiveRoutine，so enterCommit  must not simultaneous.

**Comment by james-ray** [comment]
I think we can add atomic.CompareAndSet in cs.updateRoundStep(cs.Round, cstypes.RoundStepCommit)
and make this method return true or false.  
If false, which means someone has already modified the status. Now the code can directly return without to call cs.tryFinalizeCommit(height)

**Comment by goolAdapter** [comment]
There is no other routine can updateRoundStep concurrently， it's not wrong to add atomic.CompareAndSet， but I think it's unnecessary.

**Comment by james-ray** [comment]
Thanks for the reminding. I've read the code , you are right . Because msgs are serialized in receiveRoutine, so it would be no problem.
