### ISSUE TITLE
lib's event implement have some flaw 

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2518]
**This issue doesn't exist in the current runtime, but as an base lib, I think it's better to more robust.**

Lib event designed for multi routine, but AddListenerForEvent and RemoveListener manipulate listener and eventCell in different order.
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/libs/events/events.go#L76-L78
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/libs/events/events.go#L94-L98

consider two routine，A call AddListenerForEvent and B call RemoveListener  simultaneous.
```
B -> listener.SetRemoved()
A -> eventCell.AddListener(listenerID, cb)
A -> listener.AddEvent(event)
B -> for _, event := range listener.GetEvents() {
		evsw.RemoveListenerForEvent(event, listenerID)
}
```
At this time, Listener added by A will not be clean up. the fix is to try AddEvent first, only when AddEvent succeeded, eventCell can AddListener.

by the way，eventCell.FireEvent is easy to deadlock, as lock's range is uncontrollable when run callback.
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/libs/events/events.go#L169-L175

**Comment by melekes** [comment]
note: we'll get rid of the `events` package in https://github.com/tendermint/tendermint/issues/1692

**Comment by xla** [comment]
Merged to develop.
