### ISSUE TITLE
Support sticky leaders

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#252]
We could support sticky (proposer till they are skipped) or pseudo sticky (proposer for N blocks unless skipped) leaders. The proposer would need to be included in the block header (https://github.com/tendermint/tendermint/issues/251) and evidence for skipping proposers would need to make it into the blockhash (ala Tendermint v2)

**Comment by adrianbrink** [comment]
What is the benefit of having sticky leaders?

**Comment by ebuchman** [comment]
Performance (one leader can queue up lots of txs and everyone knows who the leader is for a while). Many other consensus algos have a stick leader so the leader only changes if theres a timeout or byzantine behaviour detected.

**Comment by jackzampolin** [comment]
This seems to be a long way off from being implemented. Closing this issue as out of scope.
