### ISSUE TITLE
test_p2p: non-deterministic test fail

### ISSUE THREAD

**Issue by goolAdapter** [tendermint/tendermint#2520]
I have not change any code influence p2p for https://github.com/tendermint/tendermint/pull/2519, but p2p test failed, was these knowed before?
https://circleci.com/gh/tendermint/tendermint/26704#build-parameters/containers/0

**Comment by goolAdapter** [comment]
yes, It's occasional, I rerun it, it's passed.

**Comment by melekes** [comment]
I see little point in such issues. There's almost zero chance to understand/figure out the problem based on the logs above (i.e. you need Tendermint instance logs and looks like we do not store them 😞 currently)

**Comment by ebuchman** [comment]
You're right, thanks. Opened an issue: https://github.com/tendermint/tendermint/issues/2554
