### ISSUE TITLE
abci: Remove TotalTxs from BlockHeader

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2521]
The TotalTxs is a nice stat, but doesn't seem like it needs to be sent in every block. This isn't needed for lite client verification, so I think we should remove it from the header.

I think we should also remove `NumTxs`, again a nice stat but isn't needed for lite clients. All full nodes can derive it from the block data.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/issues/952

`It's a useful thing to easily be able to know how many transactions have been sent and also provides every transaction a global integer index`

**Comment by ValarDragon** [comment]
Thanks for finding why it was introduced! I feel like both of those are things that the state machine can and should handle. Feels like it very unnecessary p2p / lite client storage requirement.

**Comment by ebuchman** [comment]
@AFDudley iirc you had initially requested this. Do you agree with Dev here, or do you think it's important to keep it in the header?

**Comment by marbar3778** [comment]
I do agree with @ValarDragon that this is not necessary in the block header.  and the application can handle it.  @ebuchman @melekes should we move this out of the proposal stage and someone can pick it up?

**Comment by melekes** [comment]
Let's remove it

**Comment by AFDudley** [comment]
> @AFDudley iirc you had initially requested this. Do you agree with Dev here, or do you think it's important to keep it in the header?

Sorry for the insanely slow reply. The purpose of this was to make the headers compatible as a drop-in replacement for raft. We did it as an experiment, I'm sure over the years the theory around the headers has changed. 

For historical purposes, here is the gasket:
https://github.com/vulcanize/raft2tmsp

Here is an example of it being used in a production codebase:
https://github.com/vulcanize/cockroach_new/tree/raft2tmsp

We ended up going in a completely different direction with our work, so feel free to removes these fields.

Thanks asking I really appreciate it.

**Comment by ebuchman** [comment]
> should we move this out of the proposal stage and someone can pick it up?

It's a quite simple change but it's block protocol breaking (the worst kind!) and should happen with other such changes like #1648

**Comment by ebuchman** [comment]
Should we really remove the NumTx field as well? https://github.com/tendermint/tendermint/pull/3783#discussion_r302819561

**Comment by marbar3778** [comment]
Is there a reason for it to be there when its in the block? I can't think of a reason to duplicate data.

**Comment by ebuchman** [comment]
It's not in the block explicitly, only implicitly as `len(block.Data.Txs)`

**Comment by marbar3778** [comment]
Is there a case where you would need to check `numTxs` where you don't have the block?

**Comment by ebuchman** [comment]
Is it valuable for a lite client to know how many txs are in a block without having to receive them? Doesn't look like BTC or ETH have this in the header, for some reason I thought they did. 

It might be valuable to at least know if a block is empty, but they can just look at the merkle root to see if its the empty hash or not. 

Perhaps if we took an alternative approach to block gossipping that was based around txs instead of block parts (ie. so we could avoid gossipping txs in blocks that were already sent in mempool) this might be valuable to know how many txs are in a block before receiving it. But that seems like a far off optimization that would probably break other things anyways :)

**Comment by ValarDragon** [comment]
The advantage / purpose of https://github.com/tendermint/tendermint/issues/1892 is that the lite client doesn't need to know ahead of time the number of txs / per block for safety.
