### ISSUE TITLE
docs: improve the Tendermint Core and Using Tendermint layout

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2523]
- [x] Deduplicate the protocol stuff (blocks, validators, p2p, lite-client) and link to the spec instead
- [ ] Info about upgrading (eg. #2390)
- [x] Probably move some stuff from AppDev here (eg. events, tx indexing)

Replaces the rest of https://github.com/tendermint/tendermint/issues/2376

**Comment by marbar3778** [comment]
>     * Info about upgrading 

until, we roll out a better upgrade story in tendermint I would say we can close this. When the new feature lands we will update the docs accordingly
