### ISSUE TITLE
Align proposer logic with spec

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2529]
if proposer(h_p , round_p ) = p then 
    if validValue_p != nil then
        proposal ← validValue_p 
    else
        proposal ← getValue()
    broadcast ⟨PROPOSAL, h_p , round_p , proposal, validRound_p⟩.

More details can be found in https://github.com/tendermint/spec.

**Comment by ebuchman** [comment]
@milosevic can you clarify how our current implementation differs right now?

**Comment by milosevic** [comment]
In defaultDecideProposal, we first check if we have locked block, and this is what we propose; if locked block is not set we propose validBlock (if set). See https://github.com/tendermint/tendermint/blob/37928cb9907a60ae79d5b387d1d89ffc43dc07d8/consensus/state.go#L892-L904. This is wrong as proposal should only be based on validBlock ( see spec).

**Comment by ebuchman** [comment]
Fixed in #2642. Thanks!
