### ISSUE TITLE
give tmsp app the latest header

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#253]

**Comment by ebuchman** [comment]
not sure the best way to do this. passing in the header itself means we need to duplicate the data type in protobuf. if we want tmsp to support other consensus algorithms, or even other versions of tendermint, that might mean different headers, and it would be a pain for an app to have to plan for that. An alternative is to let the app request fields from the header that it wants only if/when it wants it, but that brings its own breed of complexity

**Comment by jaekwon** [comment]
how about we add the following fields to BeginBlock?

* Header []byte
* HeaderType string

and Tendermint can pass in the json bytes for the header, with "json" as header type.

**Comment by ebuchman** [comment]
does the HeaderType need to be in the request? or can it just be config level. its not something that should change during a connection. Just like `AppendTx(tx []byte)`, maybe all we need to do is `BeginBlock(header []byte)`?

Alternatively, what if we just make it a oneof using protobufs, and then new headers can be introduced down the road. That way there's no additional codec to worry about other than the protobuf.

**Comment by ebuchman** [comment]
closing in favour of https://github.com/tendermint/tendermint/issues/302. header is passed in beginblock via https://github.com/tendermint/tendermint/pull/265
