### ISSUE TITLE
Invisible code samples in docs on Tendermint.com site

### ISSUE THREAD

**Issue by siman** [tendermint/tendermint#2536]
Tendermint docs are broken: code samples have a white-color font on white background.

Just check this page: 
https://www.tendermint.com/docs/indexing-transactions.html

Here is a screenshot of the above URL where I have selected all text on a page to show where the background and font are white:

![image](https://user-images.githubusercontent.com/153928/46420638-2a354e80-c739-11e8-9a87-f0648fd3a7b3.png)

**Comment by zramsay** [comment]
that's an old file that's been moved, how did you arrive at this link? the correct file is https://tendermint.com/docs/app-dev/indexing-transactions.html and the codeblock is visible

**Comment by siman** [comment]
I got there from Google.
It makes sense to add HTTP 301 redirects for old-format URLs.

**Comment by zramsay** [comment]
thanks. closing; we're tracking this on the devops team
