### ISSUE TITLE
Use fixed lengths in and finalize sign bytes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2545]
In #1622 we resolved to change sign bytes to amino, and to use fixed size fields so HSMs can easily read height and round from the data, and thus prevent double signing.

We switched to amino in #2459. We still need to make the values fixed length.

See the draft ADR-024 from PR #2445 for much more details

**Comment by jleni** [comment]
Would it be possible to include a very simple Vote serialization test? 
Output blobs would be useful to run HSMs signing tests.

**Comment by xla** [comment]
> Would it be possible to include a very simple Vote serialization test?
> Output blobs would be useful to run HSMs signing tests.

@Liamsi Maybe you can consider this.

**Comment by Liamsi** [comment]
Sure, will do! I understood this is what @ebuchman suggested in https://github.com/tendermint/tendermint/issues/2508, too.

**Comment by jleni** [comment]
The order is also important. If we have variable sized fields before, the offset will vary.

**Comment by Liamsi** [comment]
Sure, I'll stick to the offsets we agreed on. I just wanted to make sure that for your use-case only the SignBytes matter.

**Comment by ebuchman** [comment]
Done
