### ISSUE TITLE
Follow up on ADR-024

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2546]
See review and various TODOs in https://github.com/tendermint/tendermint/pull/2445#pullrequestreview-161854982 and

**Comment by marbar3778** [comment]
In 0.34 we migrated tendermint to 0.34. In this change we made the canonical types backwards compatible. This follow up would break these, do we want to still do this in the next or other major releases? 

cc @ebuchman @liamsi

**Comment by ebuchman** [comment]
Not sure these follow ups are material but in any case I guess we're prioritizing not breaking the signing

**Comment by tessr** [comment]
We're planning on switching privval to use GRPC. Will ADR 24 still be relevant once privval uses GRPC?

**Comment by marbar3778** [comment]
Yes, but we should reevaluate the ADR before. There are some areas that may not be necessary.

**Comment by marbar3778** [comment]
The current design has diverged from the current ADR. I will open a PR that mentions this.

**Comment by creachadair** [comment]
@ebuchman It's not clear what the action items are for this issue. The comments on the linked PR appear to be related to encoding, but I can't tell which comments are being followed up on here. Do you recall the context? (Or if not, any objections if I close this?)
