### ISSUE TITLE
p2p: TestSwitches hangs for a while

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2555]
The `TestSwitches` hangs on

```
I[10-05|18:57:50.954] Added peer                                   peer="Peer{MConn{pipe} a619efa041025e96926da905a3a24921e4bfa941 in}"
I[10-05|18:57:50.954] Added peer                                   peer="Peer{MConn{pipe} 0045be99097a0af42250bb08a3e0a58ad040d218 in}"
D[10-05|18:57:50.954] Broadcast                                    channel=0 msgBytes=6368616E6E656C207A65726F
D[10-05|18:57:50.954] Broadcast                                    channel=1 msgBytes=6368616E6E656C20666F6F
D[10-05|18:57:50.954] Broadcast                                    channel=2 msgBytes=6368616E6E656C20626172
D[10-05|18:57:50.954] Send                                         peer=0x14984c0 channel=0 conn=MConn{pipe} msgBytes=6368616E6E656C207A65726F
D[10-05|18:57:50.954] Send                                         peer=0x14984c0 channel=1 conn=MConn{pipe} msgBytes=6368616E6E656C20666F6F
D[10-05|18:57:50.954] Send                                         peer=0x14984c0 channel=2 conn=MConn{pipe} msgBytes=6368616E6E656C20626172
```

Nothing happens until one of the peers sends a ping, which seems to cause buffer to flush and the test to complete.

Perhaps we're not starting the connections properly in the test switch?

**Comment by goolAdapter** [comment]
I think I finded the reason, defaultFlushThrottle  was time.Millisecond measurement， but mConfig.FlushThrottle plus it with another time.Millisecond， so the actual FlushThrottle is 1000x times than expect.
https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/p2p/switch.go#L105-L107

https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/p2p/conn/connection.go#L28-L31

I can make a PR for this.

**Comment by melekes** [comment]
Merged to develop. Let's see if the issue goes away.

**Comment by ebuchman** [comment]
Fixed! Thanks!
