### ISSUE TITLE
Implement IPC as an alternative option to SecureConnection

### ISSUE THREAD

**Issue by Slamper** [tendermint/tendermint#2563]
Ref: https://github.com/tendermint/kms/issues/57

An IPC channel (UNIX socket) between KMS and a tendermint validator node should serve the use case where validators deploy the KMS next to a validator node on the same host.

This could allow for a connection with less overhead complexity thereby increasing reliability.

I could take care of the issue and in the course of this also fix the SecureConnection implementation which is currently broken.

Since the underlying TCP socket is already built in (and can be shared with SecureConnection) I will not need to introduce a lot of unnecessary overhead.

**Comment by ValarDragon** [comment]
Its not clear to me that we want to support unencrypted IPC. Are there benchmarks for the overhead complexity you refer to? Chacha20 is extremely quick, it doesn't feel like this should be an issue. Whereas the alternative, unencrypted IPC, has caused many security issues in the past across many different projects.

Also what do you mean by `SecureConnection implementation which is currently broken.`, whats broken about it?

**Comment by Slamper** [comment]
@ValarDragon

The complexity was referring to complexity of the implementation / reliability rather than computational complexity.

Having a network socket + self implemented encrypted connection is too much added complexity over a simple Unix socket for the reward. Especially if the KMS is running on the same host.

For the broken part please take a look at my PR. Connection deadlines were implemented in the wrong way and keepalive was not working.

**Comment by ValarDragon** [comment]
I do still feel like we should authenticate the data. The overhead here would be an HMAC and an initial key exchange. I guess the system is probably unsafe anyway against any sort of physical tampering, so this isn't _needed_, but this does leave open a bit of low-hanging fruit for such an adversary.

**Comment by amrali** [comment]
Isn't it also a low hanging fruit to protect it? To properly secure the keys used to authenticate and encrypt messages between the validator and the KMS is more complex than protecting that simple UNIX socket.

Compromise of any node (validator or KMS) means the connection is compromised, regardless to what we use.

Compromise of the medium/connection is easier for a UNIX socket compared to SecureConnection, but easier is a poor term to describe this, to give an example, if we compare compromising seccomp or any other kernel security to cryptographic security, sure a cryptosystem is more secure than this. But what we are talking about is compromise of several systems and software layers before you can attack the KMS host. I think the cryptosystem adds incremental security there and doesn't act as a primary security barrier for preventing comm channel/medium compromise.

**Comment by ValarDragon** [comment]
```
To properly secure the keys used to authenticate and encrypt messages between the validator and the KMS is more complex than protecting that simple UNIX socket.
```
How so? Its defense in depth, just keeping the keys within memory for the devices suffices. I agree theres no need for encryption, just a MAC works.

The threat model in the current use case would be to eliminate fault attacks from a physical attacker, but I guess there isn't really a set of physical adversaries who could tamper with data on this line, but not actually tamper with the KMS itself. So I agree with you.

**Comment by amrali** [comment]
I guess I can't disagree with a simple MAC, it's a rather simple addition. Any preferable algorithm?

**Comment by ValarDragon** [comment]
We still need to add a MAC to the scheme, right?

**Comment by ebuchman** [comment]
Opened a new issue https://github.com/tendermint/tendermint/issues/3099
