### ISSUE TITLE
ConsensusParams.Evidence.MaxAge should be time, not height

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2565]
Currently, `ConsensusParams.Evidence.MaxAge` is the maximum age, in heights, of a valid piece of evidence. Ie. if its 1000, and we're at block 5000, only evidence since block 4000 will be considered valid.

Now that we have BFT time, we should change this to be time based rather than height based.

**Comment by ebuchman** [comment]
It should be the same Timestamp format used in the header (ie. google's "WellKnownType.Timestamp" thing)

**Comment by ValarDragon** [comment]
Oh theres a well known type for duration. I think we should use that instead. (Fundamentally we want a time duration, not a single point in time which is what timestamps are for)

https://developers.google.com/protocol-buffers/docs/reference/csharp/class/google/protobuf/well-known-types/duration

**Comment by melekes** [comment]
I made a PR earlier https://github.com/tendermint/tendermint/pull/2606, but closing it because of the https://github.com/tendermint/tendermint/issues/2653.

**Comment by ebuchman** [comment]
It sounds like addressing #2653 properly will happy post launch and require larger discussion.

Meanwhile, we should probably adopt the hybrid approach - support both MaxAgeDuration and MaxAgeHeight and only reject evidence if it is both too old in height and duration. That way if validators lie about time, at least evidence will still be valid for some number of heights.

**Comment by melekes** [comment]
> support both MaxAgeDuration and MaxAgeHeight and only reject evidence if it is both too old in height and duration.

What could happen is people will be setting MaxAgeDuration because it's more natural and leave MaxAgeHeight as is, which will lead to bad consequences if validators manipulate with time.

> That said, actually, we can probably leave this as is for now. Thanks.

Should we close this then?

**Comment by melekes** [comment]
> Now that we have BFT time, we should change this to be time based rather than height based.

I'd vote for closing this since we're planning to switch back to "proposer's timestamp".

**Comment by ebuchman** [comment]
We'd still want to change this I think, no?

**Comment by marbar3778** [comment]
In the last core dev session, it seemed https://github.com/tendermint/tendermint/issues/2840, was in the discussion phase. So it may be beneficial to take the hybrid approach for this release if we do want to include this. Otherwise seems this and https://github.com/tendermint/tendermint/issues/2840 need to be discussed further before implementation.

**Comment by ebuchman** [comment]
Yup, we were also discussing using a hybrid approach involving both time and height

**Comment by marbar3778** [comment]
@ebuchman @melekes should this go into an ADR before the change is made or are we fine with moving this forward. 
If not can the idea be summarized and the reasoning if it has changed since: https://github.com/tendermint/tendermint/issues/2565#issuecomment-432896645.
