### ISSUE TITLE
Enable CORS on RPC API

### ISSUE THREAD

**Issue by arturalbov** [tendermint/tendermint#2582]
Is there any way to enable CORS on Tendermint node RPC API?
I want to have an ability to sign and send transactions to node directly from browser.
I really don't want to start some proxy server
Thanks

**Comment by jackzampolin** [comment]
@hleb-albau That should work! Can you open a PR?

**Comment by melekes** [comment]
PR with a fix/feature was merged to develop. Will be shipped with 0.26.2 release (check the changelog).
