### ISSUE TITLE
state: add more tests for block validation

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2589]
See all the TODOs in `state/validation_test.go` once #2560 is merged

**Comment by thanethomson** [comment]
```go
/*
	TODO(#2589):
	- test Block.Data.Hash() == Block.DataHash
	- test len(Block.Data.Txs) == Block.NumTxs
*/
func TestValidateBlockData(t *testing.T) {
}
```

@ebuchman are the tests required above in [state/validation_test.go#L74](https://github.com/tendermint/tendermint/blob/develop/state/validation_test.go#L74) not already implicitly tested through [calls to blockExec.ValidateBlock()](https://github.com/tendermint/tendermint/blob/develop/state/validation_test.go#L68) in the `TestValidateBlockHeader` test? See [types/block.go#L85](https://github.com/tendermint/tendermint/blob/develop/types/block.go#L85) and [types/block.go#L130](https://github.com/tendermint/tendermint/blob/develop/types/block.go#L130), which seem to be tested by [state/validation_test.go#L47](https://github.com/tendermint/tendermint/blob/develop/state/validation_test.go#L47) and [state/validation_test.go#L52](https://github.com/tendermint/tendermint/blob/develop/state/validation_test.go#L52), respectively.
