### ISSUE TITLE
merkle/simpleMap: remove hash of the value parameter

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2593]
Line in reference: https://github.com/tendermint/tendermint/blob/ee7b3d260e35c656290caace6255bee3a639a2bc/crypto/merkle/simple_map.go#L30

Despite the comment there, there is no advantage to this in our current usage. For everything were taking a simple map of, a hash is of the same size or larger than the value. So this will just increase net size. Worse, this adds another `proof` in the tree. 

I think we should prioritize fixing this prelaunch, as otherwise we need to special case our proof logic for these maps. (I.e. thats a bug that exists now, but would be resolved by changing this) Its an easy fix, and most of the work is in updating the test cases.

**Comment by ebuchman** [comment]
> Despite the comment there, there is no advantage to this in our current usage. For everything were taking a simple map of, a hash is of the same size or larger than the value. 

Is this still true? We don't seem to be using this construction anywhere in Tendermint. 

Is it really needed in the SDK? @mossid @cwgoes @jaekwon ? I would prefer to get rid of it entirely and not have a fromMap at all.

**Comment by cwgoes** [comment]
We do not use `simpleMap` anywhere directly in the SDK (the package is never imported), unless it's used by a higher-level Tendermint package automatically.

**Comment by ebuchman** [comment]
```
store/rootmultistore.go
415:    return merkle.SimpleHashFromMap(m)
```

It's just used for the Merkle root of the stores in the multistore.

**Comment by erikgrinaker** [comment]
I suggest we remove this from Tendermint, and if the SDK needs it they can put it in their tree.

**Comment by marbar3778** [comment]
It would useful for this to be moved to the SDK as this function will be moved there.
