### ISSUE TITLE
merkle/simple_map: Switch sort to be stable

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2596]
Simple_Map sorts the keys using an unstable sort. (IntroSort) The issue with unstable sort is that every language will probably have the instability done in a different manner. This could make non-golang implementations unnecessarily harder.

We're not sorting much, so the speed difference is negligible compared to a signature verification for example.

**Comment by ValarDragon** [comment]
Oh wait, this may never actually be a problem, since stability only matters when theres duplicate keys. I guess its a question of should simple_map panic if theres a duplicate key, or should it switch to stable sort.

**Comment by marbar3778** [comment]
simpleMap was recently removed from tendermint.
