### ISSUE TITLE
Make sure reactors don't block

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#260]
- Make mempool reactor drop txs if mempool gets locked or blocks.
- Make consensus reactor drop msgs if consensus blocks.  Ensure that consensus can progress despite dropped messages.
- Make sure other reactors don't block.
- Document go-p2p reactor to say that reactors cannot block.  Add comments on all Receive() implementations as well.

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/1210
