### ISSUE TITLE
Don't merkelize the hash of consensus params

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2602]
The current code is:
```
func (params *ConsensusParams) Hash() []byte {
	return merkle.SimpleHashFromMap(map[string][]byte{
		"block_size_max_bytes":    cdcEncode(params.BlockSize.MaxBytes),
		"block_size_max_gas":      cdcEncode(params.BlockSize.MaxGas),
		"evidence_params_max_age": cdcEncode(params.EvidenceParams.MaxAge),
	})
}
```
i.e. its a merkle tree of those 3 parameters. The overhead of 2 proofs (even 1 proof) does not make the trade-off in terms of space saved. Thus there should be no merkelization here. It would make sense to revisit this only if many more parameters are included here, which would be a breaking change anyway.

**Comment by ebuchman** [comment]
Fixed in #2609
