### ISSUE TITLE
Make types.Txs [][]byte instead of []Tx

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2603]
I believe Tx and `[]byte` can be used interchangeably, but the same is not true for `[][]byte` and Txs. This causes some efficiency losses for copying between the two.

**Comment by ebuchman** [comment]
This is a shame - I like having stronger types than []byte. @xla any thoughts on how this might be handled better? The challenge is to avoid having to do eg. https://github.com/tendermint/tendermint/pull/2635/files#diff-a9cbec9a4f9f0903f5e9d965be0e3d76R34

**Comment by ebuchman** [comment]
Also fix:
- [ ] https://github.com/tendermint/tendermint/pull/2635/files#diff-a9cbec9a4f9f0903f5e9d965be0e3d76R34

**Comment by marbar3778** [comment]
If preprocess Block is accepted into Tendermint this issue may not be applicable anymore as the key of the transaction will need to be provided by the application.
