### ISSUE TITLE
crypto fork: consider a url like golang.tendermint.com/x/crypto

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2608]
Following up on https://github.com/tendermint/tendermint/pull/2558

Currently, the imports use `golang.org/x/crypto` and we leave comments that we actually forked it. We could make the comments clearer (https://github.com/tendermint/tendermint/pull/2558#pullrequestreview-163640233), but even better would be a custom URL (https://github.com/tendermint/tendermint/pull/2558#discussion_r223272109), though this requires the URL to actually exist else `dep` will throw.

We should create `golang.tendermint.com/x/crypto`, redirect it to the godoc, and replace the imports in the code

**Comment by Liamsi** [comment]
I think this was addressed in https://github.com/tendermint/tendermint/pull/3027. 
We do not use the fork anymore.
