### ISSUE TITLE
merkle/simpleHashFromHashes: Switch it to an iterative method

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2611]
Currently its implemented in a recursive manner. This would end up being faster if done in an iterative manner. Ref: https://github.com/tendermint/tendermint/blob/7b48ea1788878d02c84b714c06640d595aa0b90e/crypto/merkle/simple_tree.go#L47

**Comment by brapse** [comment]
There is now an Iterative version of `SimpleHashFromByteSlices` but it has yet to show any performance benefits. Cf. [#3530] for some notes and analysis as to why.
