### ISSUE TITLE
merkle: Create a `SimpleHashFromByters`

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2612]
Currently txs and evidence re-implement merkelization to avoid extra allocations. We can DRY this by making another method for merkelization which accepts an array of byters. This simplifies implementation of RFC 6962. (ref #1892)

**Comment by ValarDragon** [comment]
Oh it turns out golang doesn't allow ever type casting a slice from one type to another. We probably have to live with the memory allocation inefficiency for Evidence List and Txs in the short term then. (We can convert Tx to []byte to fix that one at least) For evidence this should not be a problem, since were capping at 2 evidence per block.

**Comment by ebuchman** [comment]
Fixed in #2635 - thanks Dev!
