### ISSUE TITLE
consensus: PickVoteToSend assumes peer has vote before checking result of Send

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2615]
In `PickVoteToSend`, we mark the peer as having the vote we're going to send:

```go
	if index, ok := votes.BitArray().Sub(psVotes).PickRandom(); ok {
		ps.setHasVote(height, round, type_, index)
		return votes.GetByIndex(index), true
	}

```

But this happens before we actually try to send it. If sending fails, we will have incorrectly marked the peer as having the vote:

```go
	if vote, ok := ps.PickVoteToSend(votes); ok {
		msg := &VoteMessage{vote}
		ps.logger.Debug("Sending vote message", "ps", ps, "vote", vote)
		return ps.peer.Send(VoteChannel, cdc.MustMarshalBinaryBare(msg))
	}
```

We should check the result of `ps.peer.Send` before calling `ps.setHasVote`

**Comment by milosevic** [comment]
I thought we already have issue created for this.

**Comment by ebuchman** [comment]
Do we ?

**Comment by milosevic** [comment]
Wasn't able to find it :) Maybe we just discussed it but forgot to create an issue.
