### ISSUE TITLE
PolRound in the Proposal would be current round if we have received a PoLc first

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#2619]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
```
I[10-12|01:56:03.427] Timed out                                    module=consensus dur=731.198506ms height=2 round=0 step=RoundStepNewHeight
I[10-12|01:56:06.541] Added to prevote                             module=consensus vote="Vote{3:CEA8A844ABA1 2/00/1(Prevote) 000000000000 E0322472171A @ 2018-10-12T01:56:06.417693385Z}" prevotes="VoteSet{H:2 R:0 T:1 +2/3:<nil>(0.25) BA{4:___x} map[]}"
I[10-12|01:56:06.670] Added to prevote                             module=consensus vote="Vote{0:637118B2857E 2/00/1(Prevote) 000000000000 A3449335CF0E @ 2018-10-12T01:56:06.421549542Z}" prevotes="VoteSet{H:2 R:0 T:1 +2/3:<nil>(0.5) BA{4:x__x} map[]}"
I[10-12|01:56:06.670] Added to prevote                             module=consensus vote="Vote{2:C85DE319A387 2/00/1(Prevote) 000000000000 3EF33AA6675A @ 2018-10-12T01:56:06.422306323Z}" prevotes="VoteSet{H:2 R:0 T:1 +2/3::0:000000000000(0.75) BA{4:x_xx} map[]}"
I[10-12|01:56:06.670] enterNewRound(2/0). Current: 2/0/RoundStepNewHeight module=consensus height=2 round=0
I[10-12|01:56:06.671] enterPropose(2/0). Current: 2/0/RoundStepNewRound module=consensus height=2 round=0
I[10-12|01:56:06.671] enterPropose: Our turn to propose            module=consensus height=2 round=0 proposer=9EAB913B0BAA789D119F53D7B4E852AEDB755219 privValidator="PrivValidator{9EAB913B0BAA789D119F53D7B4E852AEDB755219 LH:1, LR:0, LS:3}"
I[10-12|01:56:06.736] Signed proposal                              module=consensus height=2 round=0 proposal="Proposal{2/0 1:38C2D72FAE7F (0,:0:000000000000) 1DD332CEA42E @ 2018-10-12T01:56:06.671331082Z}"
I[10-12|01:56:06.736] enterPrecommit(2/0). Current: 2/0/RoundStepPropose module=consensus height=2 round=0
I[10-12|01:56:06.736] enterPrecommit: +2/3 prevoted for nil.       module=consensus height=2 round=0
I[10-12|01:56:06.778] Signed and pushed vote                       module=consensus height=2 round=0 vote="Vote{1:9EAB913B0BAA 2/00/2(Precommit) 000000000000 981E92BBB27F @ 2018-10-12T01:56:06.737001924Z}" err=null
E[10-12|01:56:06.811] Error with msg                               module=consensus height=2 round=0 type=*consensus.ProposalMessage peer= err="Error invalid proposal POL round" msg="[Proposal Proposal{2/0 1:38C2D72FAE7F (0,:0:000000000000) 1DD332CEA42E @ 2018-10-12T01:56:06.671331082Z}]"
I[10-12|01:56:06.861] Received a block part when we're not expecting any module=consensus height=2 round=0 index=0 peer=
I[10-12|01:56:06.878] Added to precommit                           module=consensus vote="Vote{1:9EAB913B0BAA 2/00/2(Precommit) 000000000000 981E92BBB27F @ 2018-10-12T01:56:06.737001924Z}" precommits="VoteSet{H:2 R:0 T:2 +2/3:<nil>(0.25) BA{4:_x__} map[]}"
I[10-12|01:56:06.879] Added to precommit                           module=consensus vote="Vote{2:C85DE319A387 2/00/2(Precommit) 000000000000 9CE22F04295B @ 2018-10-12T01:56:06.692477996Z}" precommits="VoteSet{H:2 R:0 T:2 +2/3:<nil>(0.5) BA{4:_xx_} map[]}"
I[10-12|01:56:06.879] Added to precommit                           module=consensus vote="Vote{3:CEA8A844ABA1 2/00/2(Precommit) 000000000000 2F81A37743D2 @ 2018-10-12T01:56:06.572292861Z}" precommits="VoteSet{H:2 R:0 T:2 +2/3::0:000000000000(0.75) BA{4:_xxx} map[]}"
```

**What you expected to happen**:
the function in height_vote_set.go:
```go
// Last round and blockID that has +2/3 prevotes for a particular block or nil.
// Returns -1 if no such round exists.
func (hvs *HeightVoteSet) POLInfo() (polRound int, polBlockID types.BlockID) {
	hvs.mtx.Lock()
	defer hvs.mtx.Unlock()
	for r := hvs.round; r >= 0; r-- {
		rvs := hvs.getVoteSet(r, types.VoteTypePrevote)
		polBlockID, ok := rvs.TwoThirdsMajority()
		if ok {
			return r, polBlockID
		}
	}
	return -1, types.BlockID{}
}
```

There are 2 problems.
1.we should not count current round.  the for loop should be r := hvs.round -1
2.we should judge the polBlockID.IsZero()

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by james-ray** [comment]
I mean,  this log 

E[10-12|01:56:06.811] Error with msg module=consensus height=2 round=0 type=*consensus.ProposalMessage peer= err="Error invalid proposal POL round" msg="[Proposal Proposal{2/0 1:38C2D72FAE7F (0,:0:000000000000) 1DD332CEA42E @ 2018-10-12T01:56:06.671331082Z}]"

shouldn't happen

**Comment by milosevic** [comment]
PolInfo should probably be removed as ValidRound and ValidBlock are providing us the same functionality. See https://github.com/tendermint/tendermint/issues/2646.

**Comment by james-ray** [comment]
@milosevic 
what about these codes in reactor.go , the peerState: ps.PRS.ProposalPOLRound 

if ps.PRS.ProposalPOLRound == round {
			switch type_ {
			case types.PrevoteType:
				return ps.PRS.ProposalPOL
			case types.PrecommitType:
				return nil
			}
		}

Actually, I don't see the point of ps.PRS.ProposalPOL. I mean, if the current proposal is just the lockedBlock, then we don't need send the previous round's PoLc of the lockedBlock to other peers. We should do the opposite, that is, if the current proposal isn't the lockedBlock we have, we keep sending out the prevotes of the LockedBlock we have, if we confirm the peers has received all the prevotes we have, we can then send out the LockedBlockParts to the peer.

Thanks very much for pointing out my any misunderstanding

**Comment by ebuchman** [comment]
Thanks @james-ray - a couple things that would help:

- please include Tendermint version/branch information and description about the setup whenever you open an issue with logs
- use 3 back ticks like  "```" both above and below any code blocks to make them easier to read. Include the language name in the top one for highlighting:  

  \```go
  func ABC() {}
  \``` 


As for your question:

> Because naturally they will accept current round's proposalBlock.

This is only true after GST, which is some time we don't know when, so we can't assume it's always true.

That said it does look like there may be a related bug here, as the same issue is reported in https://github.com/tendermint/tendermint/issues/2702

**Comment by ebuchman** [comment]
Let's close this for #2646
