### ISSUE TITLE
rs.LastCommit should be rs.LastVotes (HeightVoteSet)

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#262]
Since the first known commit round could differ from node to node, in order to make LastCommit work best, we should really keep track of not just our subjective last commit round, but other rounds as well (e.g. the whole HeightVoteSet), so that when a peer's subjective last commit round is R, we can send it additional votes for R.  The current behavior is that we don't send any additional LastCommit votes if our subjective commit rounds differ.

Or, we might think of other mechanisms for auto-inactivating validators that doesn't solely on the blockchain's Commits.

**Comment by ebuchman** [comment]
@jaekwon @milosevic is this still relevant? I don't think we have different commit rounds anymore

**Comment by xla** [comment]
@jaekwon Is this still relevant as described above?

**Comment by jackzampolin** [comment]
Closing this issue as solved.
