### ISSUE TITLE
There is no correlation between BlockPartsHeader and POL fields in Proposal

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2623]
In case a block is retransmitted, i.e., POLRound >= 0, we don't check if the proposed block corresponds to POLBlockID. In other words, you can use POL mechanism to unlock block at processes so any other block can be proposed. We currently retransmit block always in a new round, but we could consider avoid doing this in case a peer already have this block (for example, lockedBlock or validBlock are equal to proposed block). In this case after Proposal message is received, we can check if we already have block and notify at the gossip level that we already have block proposal. 
This could potentially significantly save bandwidth for rounds > 0 when block from previous rounds is being retransmitted. In that case we do want to constrain that proposed block need to correspond to POLBlockID.

**Comment by milosevic** [comment]
Yep. As sending block proposal is probably the biggest piece of data we send, we probably want to try to avoid sending it whenever is possible. I am trying to understand how far we can push this as consensus is done completely on BlockID, so at least in some cases we could send the corresponding block asynchronously and proceed at the consensus level only with BlockIDs without waiting for block to be received. But definitely post-launch issue.

**Comment by tessr** [comment]
@milosevic is this still of interest? should we move this issue to the spec repo?
