### ISSUE TITLE
0.26.0 Release

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#2624]
This is an issue to track blocking PRs for the 0.26 release

- [x] [#2540](https://github.com/tendermint/tendermint/pull/2540)
- [x] [#2556](https://github.com/tendermint/tendermint/pull/2556)
- [x] [#2598](https://github.com/tendermint/tendermint/pull/2598)
- [x] #2468
- [x] #2618 
- [x] #2682
- [x] Update changelog for https://github.com/tendermint/tendermint/pull/2609#pullrequestreview-164880282

**Comment by ebuchman** [comment]
We also may want to address https://github.com/tendermint/tendermint/issues/2618

**Comment by jackzampolin** [comment]
Added!

**Comment by jackzampolin** [comment]
Looks like all the issues here are wrapped up! Looking forward to an `0.26` release! 🎉

**Comment by ebuchman** [comment]
RC0 tagged. Will probably merge some fixes before final release.
