### ISSUE TITLE
Add timeout for each transaction

### ISSUE THREAD

**Issue by xiaoxiaff** [tendermint/tendermint#2631]
For now if a transaction runs for more than one block time it will result in failed to propose a block. Even more if there exists some bugs which causes the transaction running for a long time, that node will deny all incoming service. Wrap transactions with timeout so it will not failed when transaction runs into timeout situation.

**Comment by ebuchman** [comment]
> For now if a transaction runs for more than one block time

Can you clarify what this means? How can a tx run for more than one block? You mean in the mempool?

I think for now this is something that could be handled at the application layer. But maybe some more info would be useful here.

**Comment by xiaoxiaff** [comment]
> Can you clarify what this means? How can a tx run for more than one block? You mean in the mempool?

Sure, we got a bug report about `big.Rat.SetString`. In our application we use `big.Rat.SetString` to process user input. When user type in a really large number, `10e99999999999` for example, the application needs more than 1 min to process which will leads to DoS. I believe if there has some timeout mechanism this kind of issue can be prevent.

**Comment by ValarDragon** [comment]
I think we just need to let that sort of bug halt the chain. Consensus faults from using a max time-out approach on delivering txs is far more worrisome imo. I think it would make sense to support this for the mempool, but not for whats delivered on chain.

**Comment by xiaoxiaff** [comment]
> It could still take awhile, so maybe we should consider adding some kind of timeout on CheckTx so if we don't get the response within the timeout, we mark it as a failure.

I agree to add a timeout on CheckTx and mark it as failure if timeout.

> Meanwhile, you can deal with it at the application layer and just return an error if the timeout expires application-side.

Actually Cosmos team doesn't like timeout in application layer because process time is different for each nodes. Since tendermint has commit timeout I think add it to tendermint would be better than application.

> I think we just need to let that sort of bug halt the chain. Consensus faults from using a max time-out approach on delivering txs is far more worrisome imo. I think it would make sense to support this for the mempool, but not for whats delivered on chain.

I am not sure about this because we want this to be implemented is to prevent such bugs leading to DoS of that node. If this tx halts the chain then this kind of bugs is much worse for the application.

**Comment by ebuchman** [comment]
> Actually Cosmos team doesn't like timeout in application layer because process time is different for each nodes. 

Oh but this is only relevant for CheckTx, not DeliverTx, as far as I understand, so it's just a local subjective measurement anyways. If one node times out of CheckTx and another doesn't, that's fine.

Certainly we can't have a timeout in DeliverTx, that would cause a consensus failure :)

**Comment by xiaoxiaff** [comment]
> Oh but this is only relevant for CheckTx, not DeliverTx, as far as I understand, so it's just a local subjective measurement anyways. If one node times out of CheckTx and another doesn't, that's fine.

Yeah and if CheckTx has such protection would be great!

**Comment by tessr** [comment]
Reading through these comments, it's a little hard to know what was concluded here - I _think_ there's no change to be made, so I'm going to close this issue as part of a push to clean up old issues, but feel free to reopen if anything is outstanding.
