### ISSUE TITLE
Remove 'Error{...}' from cmnError format

### ISSUE THREAD

**Issue by fedekunze** [tendermint/tendermint#2643]
currently the SDK (cosmos/cosmos-sdk#2445) and voyager (cosmos/voyager#1131) need to parse the `err.data` formatted as JSON to display the correct message. To receive the plain text we need to remove `Errors{...}` from the following line and just return `err.data` with the message:

https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/libs/common/errors.go#L149

**Comment by jackzampolin** [comment]
Closing this as complete.
