### ISSUE TITLE
privval: Follow-up to #2568

### ISSUE THREAD

**Issue by xla** [tendermint/tendermint#2651]
#2568 improved the `privval` package significantly, some small follow-ups are necessary to enable the added functionality and keep clarity in the separation of the package:

* [ ] add configuration to decide which privval implementation to use
* [ ] clear file naming for signers and clients
* [ ] small code cosmetics (newlines, inline of error checks)

Refs #2563

**Comment by ebuchman** [comment]
I'm not sure what the first point is about, but I think it can be more or less subsumed by #1231.

The second point is handled in #2923. I'm not sure there's much more for the third point, but in any case some minor cosmetic improvements are coming in #2923. So I'll close this for now.

@Liamsi or @xla let me know if I'm missing something here.

**Comment by xla** [comment]
> I'm not sure what the first point is about, but I think it can be more or less subsumed by #1231. It might mean to move code from https://github.com/tendermint/tendermint/blob/v0.27.4/node/node.go#L854 into the `privval` pkg, but that can probably be subsumed by #3104.

Agreed. No other points missing from my view. 💃
