### ISSUE TITLE
mempool: Move interface to mempool package

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2659]
Currently the mempool interface is defined in the state package. This has a couple downsides, one is that the mempool package can't compile time check that it implements the desired interface. Additionally its non-intuitive where the interface is getting defined. This originally made more sense as it was to avoid state having to import the mempool package, but now it has to anyway for the precheck filters.

I propose that we make the mempool package a similar design pattern to the crypto package. We would have the interfaces defined in `/mempool`, along with the common precheck filters. We then have a separate package for every mempool implementation. This allows us to more easily experiment with / build out the new mempool data structures iteratively, and that nodes can elect to run different versions. It also helps for nodes who want to modify the mempool, which is a fairly natural thing to expect nodes to want to do.

 `state` and `node` would only know about the top level package import, and therefore not import any of the implementation detail-specific mempool code as well.

**Comment by ValarDragon** [comment]
I think we should make the `/mempool` package have the interface, filters, and reactor, but the reactor calls a method `mempool.BroadcastRoutine(peer)` for gossiping. The mempool would then decode the message type. I think this will make it straightforward to upgrade the mempool data structure, and broadcasting method, in an isolated manner.

**Comment by melekes** [comment]
Q:

- should we move CListMempool to a separate package (`/clist`)?
- what should we do with reactor's mempool interface?

currently, it's defined as:

```go
type MempoolWithWait interface {
	Mempool
	TxsFront() *clist.CElement
	TxsWaitChan() <-chan struct{}
	ReapMaxTxs(n int) types.Txs
}
```

maybe we should move TxsWaitChan to Mempool interface and write a simple iterator which won't expose *clist.CElement.

ReapMaxTxs is used by rpc in UnconfirmedTxs and by reactor for testing.

**Comment by Liamsi** [comment]
> should we move CListMempool to a separate package (/clist)?

I think, yes. 

> what should we do with reactor's mempool interface?
> should we do anything with rpc/core/pipe#Mempool interface?

We should re-think if we actually need those as separate interfaces? The Clist mempool-thingy implements them all (?!) And it is the only implementation... Where it makes sense we can create smaller interfaces to capture functionality to keep the mempool interface small?

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3524 was merged to develop.
