### ISSUE TITLE
p2p persistent_peers are not connected

### ISSUE THREAD

**Issue by saikumar-neelam** [tendermint/tendermint#2685]
I was unable to connect to my two local systems whose ip address are 10.40.40.222 and 10.40.20.232 .
while starting node it is throwing an issue like inbound peer rejected. 10.40.40.222 is my local system and 10.40.20.232 is virtual machine.

- Tendermint 0.25.0-0c9c3292
- Centos 7.4 (e.g. from /etc/os-release):

I was unable to connect to my two local systems whose ip address are 10.40.40.222 and 10.40.20.232.
Have you tried the latest version: yes

![image](https://user-images.githubusercontent.com/44022482/47290106-87773e00-d61b-11e8-9844-ea7f3b2cca29.png)

```
Config file for 10.40.40.222
# Comma separated list of seed nodes to connect to
seeds = "6d201878e5ee075d33512df8872c6414e1aa2b89@10.40.20.232:26656"
create_empty_blocks = false

Config file for 10.40.20.232
# Comma separated list of seed nodes to connect to
seeds = "6d201878e5ee075d3oighdk784hb34ytg334df24@10.40.40.222:26656"
create_empty_blocks = false


tendermint node --proxy_app=kvstore --p2p.persistent_peers=462c859d83c1a8d0184e15cc1ba7431ccc5f3db4@10.40.40.222:26656,6d201878e5ee075d33512df8872c6414e1aa2b89@10.40.20.232:26656:
```

**Comment by melekes** [comment]
If you just want to connect 2 peers, you don't need seeds. _Seed nodes are nodes who are constantly scanning the network and used by other nodes as a source of peers._ Update your config to use `persistent_peers` instead of seeds:

```
Config file for 10.40.40.222

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "6d201878e5ee075d33512df8872c6414e1aa2b89@10.40.20.232:26656"

Config file for 10.40.20.232

# Comma separated list of nodes to keep persistent connections to
persistent_peers = "6d201878e5ee075d3oighdk784hb34ytg334df24@10.40.40.222:26656"
```

**Comment by saikumar-neelam** [comment]
@melekes 
Am i need to add the self nodeid@host:port also in the persistent_peers

**Comment by melekes** [comment]
**No.** But if you add, Tendermint will just ignore it.

**Comment by melekes** [comment]
Join our dev chat https://riot.im/app/#/room/#tendermint:matrix.org 🤖
