### ISSUE TITLE
Skip prevote phase in round 0, lock proposal block directly and precommit

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#2691]
In round 0, we lock the proposal block directly when we finish receiving it without PoLC of round0, and send out precommit for it, without sending prevote.  If we timeout in receiving the proposal block of round 0, we precommit nil. In later rounds, n-f prevotes for another block can make us unlock our lock in round 0.
Benefit: If the network goes well, most consensus can finish in round 0 with just 1 step, thus one step's broadcasting and collecting time is reduced.
Disadvantage: A little different handling logic in round 0.
Safety Proof: A node's first precommit without PoLC does not violate its previous precommits. (It has no previous precommit)
Liveness: We adopt this first precommit without PoLC mechanism only in round 0 to ensure liveness. Otherwise, if we let first precommit without PoLC in any round, some round may not have enough prevotes.

**Comment by james-ray** [comment]
I've seen #2462 , seems like we plan to change current architecture to Disruptor. It's a great work.
I wonder these 3 things which one you think I should do first?
1. Waiting for #2462 code refactoring complete, and do the optimization based on the new architecture.
2. Modify the spec, try to write a new draft.
3. Do the code optimization of this proposal. Especially Proposal 1, I think it's easy to get it done.

**Comment by james-ray** [comment]
Here is my some thoughts about Tendermint’s safety proof, it is based on: If there are 2/3+ precommits of any round, then there weren’t 2/3+ prevotes of other block in later rounds. This assertion is based on the following 3 rules: (honest nodes must obey these rules, malicious nodes can do anything)
Rule 1: Precommit equals to a commitment of lock
If one node has received a non-nil precommit from another node, that node must have locked the block that he precommitted for.
Rule 2: Rule of Prevote
If one node has locked a block, he must prevote for that block in later rounds, until he unlocks and lock to a new block, then he must prevote for that new block in later rounds.
Rule 3: Rule of Unlock
If one node has received 2/3+ prevotes  for another block of a round which is greater than his locked round, he can unlock his locked block, and lock to the new one.  Note, if he has already sent out a Precommit of his locked block, which means he has relocked that block at that round, then if he received 2/3+ prevotes of that round after he sent out Precommit, he cannot do the unlock and lock, because the round of 2/3+ prevotes is equal to his locked round, not greater than.
	
	So, if our optimizations don’t break any of the 3 rules, its safety is still secured. 

	Optimization 1: In round 0, when we finish receiving Round0's ProposalBlock, we lock that block directly and enterPrecommit, then we try to gather 2/3+ precommits of that block. If there are, we enterCommit. If there are 2/3+ precommit any, we timeout and enterRound1.
In round 1 and later rounds, we should not enterPrecommit directly, we should prevote normally.  Any later round’s 2/3+ prevotes for another block can make us unlock round0’s block and lock to the new one, and set LockedRound to the new round.

Benefit: If the network goes well, most consensus can finish in round 0 with just 1 step
Safety Proof: The major change is we lock round0’s block without PoLC(proof of lock: 2/3+ prevotes of that round). In later rounds, when we do the unlock and lock, we still need the PoLC of that round. So we need to discuss: **when a node don’t have any locked block, is it safe for the algorithm to let him claim he has locked a block without PoLC**? I think it is safe, because precommit any block when he hasn’t made any precommit before does not break any of the 3 rules. Similarly, prevote any block when he hasn’t made any precommit before does not break any of the 3 rules either.
Disadvantage: It complexes the implementation of algorithm, right now we have mechanism of broadcast our maj23 block and our PoLC. However, if any node can lock a block without PoLC(if it is his first lock), then he may not able to broadcast his PoLC. So to simplify, we apply this first lock only in round 0, so we can treat round 0’s locked block is always without PoLC.

**Comment by james-ray** [comment]
Proposal 2 also slightly modified current implementation. That is: currently we only precommit current round's Proposal Block. If we modify this to: **we can precommit for our locked round of previous round, does it violate any safety rule**? I think it doesn't, for precommit is a kind of commitment, I send my current locked block commitment, that's reasonable. Right now at a round if we get 2/3+ prevotes and they don't have a maj23, we will precommit nil, I think it is safe that we precommit our previous round's locked block instead.

But only let him precommit previous round's locked block doesn't make much difference, we should also let locked block get broadcasted in any round. In this way, the locked block and proposal block can be broadcasted in the network simultaneously. At a height, we at most have 2 locked blocks broadcasted simultaneously, 3 locked blocks are impossible. What's more, any node who knows a higher priority locked block can interrupt the transmit at any time. For example, A is sending to B his round 2's locked block, suddenly A knows there is a round 3's PoLC, he can interrupt the transmit, and starts to send to B this new PoLC and the new block. So can B, if B knows a higher round's PoLC, he can tell A he doesn't need that round 2's Locked block any more.  

I think we can still retain the POLRound in Proposal, it is like a claim, claim that his proposal block is locked in which round. Later he needs to send to other nodes the PoLC of that round to prove the lock.    But even if we are not a proposer of that round, we should still be able to send out the claim, right now we have VoteSetMaj23Message, but it is only used to better transfer PoLC, I think it would be better to transfer the locked block afterwards.

**Comment by james-ray** [comment]
Let me state my points in short:
Theorem of Tendermint:
If there are 2/3+ precommits of a specific block in any round, there will not be 2/3+ prevotes for another block in later rounds.
This is based on the following three rules:
Rule 1: Precommit is equal to a commitment of locking
If a node has received a non-nil precommit from another, it must have locked the block that it precommitted for.
Rule 2: Rule of Prevote
If a node has locked a block, it must prevote for that block in later rounds until it unlocks and locks to a new block. Then, it must prevote for the new block in subsequent rounds.
Rule 3: Rule of Unlock
If a node has received the PoLC (Proof of Lock, which means 2/3+ prevotes for a specific block) for another block in round r that is greater than its locked round, it can unlock its locked block and lock to the new one. If the 2/3+ prevotes are for the same block as its locked block, it can relock the block. In both cases, its locked round is updated to r.
The two optimizations are stated below.
Optimization 1: A node can lock the proposal block of round 0 directly without collecting 2/3 prevotes of that block. Once it has received the full block of round 0, it directly sends out a precommit for it.
Safety Proof: The first lock without PoLC does not violate any of previous commitments. Since it is the first lock, there is no commitment before.
Optimization 2: If a node does not obtain the given round's PoLC and it is time to precommit, it can precommit its locked block (if it has one) instead of precommitting nil. Moreover, we give the locked block and its PoLC a chance to broadcast in any round instead of only in their own rounds.
In the current implementation of Tendermint, when a node enters round r, it only receives the proposal block of the round, and cannot receive blocks of other rounds. Moreover, it can only precommit for the proposal block of the given round, or for none at all.
Imagine the scenario where half of the nodes are locked on block A in round 0 and the other half are not locked on any block in round 0. In round 1, the former half can receive the proposal block B of round 1, but they prevote for block A according to Safety Rule 2. The latter half of the nodes that are not locked on any block prevote for B when they receive the full block of B. We see that it is impossible for neither A nor B to reach 2/3+. Round 1 is thus doomed to fail.
Optimization 2 is used to solve this problem. We let the half of the nodes that have locked to A precommit to A instead of precommitting ni. And we also give A an opportunity to transfer in round 1 so that the other half of the nodes can receive it even in round 1. Thus, A can get 2/3+ precommits, and a consensus is possible at the end of round 1.
Safety Proof: Let a node relock his previously locked block such that his commitment is not violated. Although this complicates things because a node’s locked round may be different from the round of the PoLC of its locked block, this can be solved using a network transfer mechanism.

**Comment by james-ray** [comment]
This proposal seems may kill liveness when a malicious block proposer broadcasts two or more proposals and blocks in round 0.
I think for times but it seems no solution to carry this thought on.

**Comment by ebuchman** [comment]
These kinds of optimizations are tricky, and should probably have their specifications and proofs fleshed out further in another repo or medium before they are raised as issues here. Can we close this in the meantime?

**Comment by james-ray** [comment]
Yes, please close this, thanks for the attention on this!
