### ISSUE TITLE
Add a checked integer type

### ISSUE THREAD

**Issue by liamsi** [tendermint/tendermint#2692]
We need a way to prevent/detect over-/underflows and act on the cases where they can happen:

Independent from the underlying integer type we will use (#2684), we will have to check that we do do not over- or underflow when doing any arithmetic. It would be nice, if we'd make it harder to miss checking for such cases. This issue proposes the following:

Add a `CheckedInteger` type which is a simple type alias to the underlying int type (name is up for discussion). 

This type alias should have methods for (checked) addition, subtraction (and any other operation we need). This would be similar to what other languages provide, e.g. [Rust](https://rust-num.github.io/num/num_traits/ops/checked/trait.CheckedAdd.html). In case of an overflow the operation should return an error (a bool might also work; I'm against panic'ing but this is also an option). Having these methods prevents users of those types to do any unchecked arithmetic (unless they explicitly cast back to the underlying type).

Types which we serialize should use this integer type directly (instead of the vanilla int). Amino can still properly decode/encode this (reflection gives back the underlying int type).

This checks are additional to the validation proposed in: https://github.com/tendermint/tendermint/issues/2683

**Comment by Liamsi** [comment]
started working on this here: https://github.com/tendermint/tendermint/compare/develop...checked_ints?expand=1
Probably way too early for a review but if someone like to have look into the general direction...

**Comment by ebuchman** [comment]
I think it might be too early to be working on this

**Comment by Liamsi** [comment]
I thought it might be relevant for Game of Stakes, that's why I started working on it. If it's not relevant there, I'll wait till we want to continue working on this.

**Comment by ebuchman** [comment]
Let's do https://github.com/tendermint/tendermint/pull/2711 instead for now

**Comment by erikgrinaker** [comment]
We discussed this in today's Tendermint call. We agree with the sentiment, i.e. that we should guard against overflow/underflow everywhere, but feel like a separate type that would have to be used throughout our code is a bit heavy-handed. An alternative might be to use native ints, but have a linter that warns about use of unchecked arithmetic.

**Comment by tessr** [comment]
Wrote up a new issue (linked) to capture the linter approach, and I'll close this one.
