### ISSUE TITLE
how to retrieve multiple values stored under same key? 

### ISSUE THREAD

**Issue by vanipolnedi** [tendermint/tendermint#2700]
can we able to retrieve multiple values stored under same key or only updated value of that particular key in tendermint ??? . when i'm querying ...getting only updated value . if we cant retrieve multiple values of same key ...is there any alternative to this ??

**Comment by vanipolnedi** [comment]
@melekes i'm using /abci_query  for querying  and kvstore application

**Comment by melekes** [comment]
It's not possible with the current code, but you can write your own kvstore application with the desired feature. You'll need to modify `DeliverTx` to check if the key already exists and `Query` to return multiple values.

**Comment by melekes** [comment]
Join our dev chat https://riot.im/app/#/room/#tendermint:matrix.org 🤖

**Comment by vanipolnedi** [comment]
@melekes  thank u for the response . i had one more doubt.......from where the block data is fetched when i do http://localhost:26657/block?height="1"

**Comment by melekes** [comment]
the block storage (levelDB database):`$TMHOME/data/blockstore` / `~/.tendermint/data/blockstore`

**Comment by minhxtran** [comment]
I am looking for the same feature.

**Comment by vanipolnedi** [comment]
@minhxtran  u can refer this link : [https://github.com/tendermint/tendermint/issues/2708](this link)

**Comment by minhxtran** [comment]
> @minhxtran u can refer this link : [https://github.com/[/issues/2708](https://github.com/tendermint/tendermint/issues/2708)]
I made the changes and when I query I am not getting any results for my key. Do I have to recompile the code to apply the config changes?

**Comment by vanipolnedi** [comment]
@minhxtran  which api endpoint are u using for querying abci_query or tx_search???... once recompile and query using tx_search . i think u wont get the expected results if u query using abci_query

**Comment by minhxtran** [comment]
> @minhxtran which api endpoint are u using for querying abci_query or tx_search???... once recompile and query using tx_search . i think u wont get the expected results if u query using abci_query
I used both RPC and HTTP to do the query.  I opened an issue with the description: https://github.com/tendermint/tendermint/issues/2783
