### ISSUE TITLE
Make cryptography amino routes match ABCI routes

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2701]
The amino routes should be whats currently used in ABCI. The `tendermint` prefix in amino routes will unnecessarily break compatibility with other potential consensus algorithms or make other consensus algorithms crypto more confusing. This also allows to align the ValidatorParams and amino routes, as mentioned in #2636.

origin: https://github.com/tendermint/tendermint/pull/2636/comment#issuecomment-432918586_

**Comment by ValarDragon** [comment]
Another alternative is that we could make the amino routes a specific function of the ABCI name. I.e. `Tendermint/PubKey` + `Name`. Though I still think we should exclude the `Tendermint/` prefix, and capitilazation may be weird with such a function.

**Comment by ebuchman** [comment]
When I wrote:

> We should be consistent here - either we add the amino routes to the base pubkey types, or we use the simple names in the validator pubkey types...

I just meant consistent within ABCI. I think we should leave the amino registration names as is for now, and keep the abci type names simple, and use the abci names rather than the amino names in #2636.

So I think we can close this.
