### ISSUE TITLE
where block data is stored in tendermint 

### ISSUE THREAD

**Issue by padmaja9** [tendermint/tendermint#2708]
when a transaction with same key is done twice with different values,does the new value override the old value or does it store somewhere.
             I mean when i'm querying based on height i'm getting the data but i'm unable to understand from where the data is fetched .For example at height=1 , i'm storing data as "key=abc" and at height=2, data is "key=def". when i use   localhost/abci_query?data="key"   ....i'm getting output as "def" but when i query based on height=1 i'm getting "abc" as result but i want both the results to be displayed.Any suggestions ?

**Comment by ebuchman** [comment]
Blockchain data is in ~/.tendermint/data/blockstore.db.

The kvstore doesn't actually store any data on disk itself (it just replays all txs from tendermint every time you restart it). Use the `--proxy_app=persistent_kvstore`, and it will store state in `~/tendermint/data/kvstore.db/`. 

`/abci_query` is only intended to return results from a given height, with proofs that it's true for that height. For each height you want to know the value, you'd make a different query, and each would have its own proof.

Note the `kvstore` returns an `app.key` tag with every tx, so you can query the transaction indexer for all txs that changed a key. So if I've been setting the key `mykey` with `/broadcast_tx_sync?tx=\"'mykey'=somevalue\"`, then I can query for all the txs that changed that key like:

```
curl "http://localhost:26657/tx_search?query=\"app.key='mykey'\""
```

Note for this to work, you need to enable indexing in the config. Set `index_all_tags = true` or set `index_tags = "app.key"`.

Closing this, but let us know if you have any issues.

**Comment by minhxtran** [comment]
> Blockchain data is in ~/.tendermint/data/blockstore.db.
> 
> The kvstore doesn't actually store any data on disk itself (it just replays all txs from tendermint every time you restart it). Use the `--proxy_app=persistent_kvstore`, and it will store state in `~/tendermint/data/kvstore.db/`.
> 
> `/abci_query` is only intended to return results from a given height, with proofs that it's true for that height. For each height you want to know the value, you'd make a different query, and each would have its own proof.
> 
> Note the `kvstore` returns an `app.key` tag with every tx, so you can query the transaction indexer for all txs that changed a key. So if I've been setting the key `mykey` with `/broadcast_tx_sync?tx=\"'mykey'=somevalue\"`, then I can query for all the txs that changed that key like:
> 
> ```
> curl "http://localhost:26657/tx_search?query=\"app.key='mykey'\""
> ```
> Note for this to work, you need to enable indexing in the config. Set `index_all_tags = true` or set `index_tags = "app.key"`.
> 
> Closing this, but let us know if you have any issues.

I am interested in this and followed your instruction but when I run the query I get no result back, any advice?

**Comment by ebuchman** [comment]
Did you:

- set `index_all_tags` or `index_tags` in your config?
- run the correct app (ie. the kvstore)?
- send a transaction?
