### ISSUE TITLE
config: include all fields from the struct in the template

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#2712]
Based on #dev-tendermint conversation:
let's set the `allow_duplicate_ip = true` by default in the tendermint code and document that optionally this can be set to false to raise security on public networks.

Based on how the team feels about it, we could also change the config to "deny_duplicate_ip" and keep it false by default...

The benefit of this change is that developers will have an easier time setting up local networks on their machines.

As mentioned above, it's still highly advised for public networks to set this to true. Maybe we should add that in the documentation.

**Comment by ValarDragon** [comment]
> The benefit of this change is that developers will have an easier time setting up local networks on their machines.

I don't understand the problem of expecting developers to read the config file. I think we should optimize for the safety of public networks with our defaults. An interesting proposal would be to make a way to initialize a default "development" config, and a default "public network" config, and a default "private network" config. Until we get time to do that, I am strongly in favor of making `allow_duplicate_ip=false` by default.

**Comment by greg-szabo** [comment]
Well, I guess I'm coming from my limited point of view: I went through the config file several times with each release and this value wasn't there. (I guess it must have been introduced recently.) It's a breaking change compared to how it was before introducing it for reasons that don't apply yet for most of our use-cases. (It will soon, hopefully.)
Anyone coming to me (see StackOverflow) with the question of "why doesn't it work" was blindsided, if they used any earlier versions of tendermint.

I guess what I'm expecting is some kind of security model that tells us how tendermint behaves by default so we don't run into this kind of "oh, that's not what we had in mind" scenarios.

The proposed multiple-configs idea in #2237 seems an interesting solution for this. That would give us a set of "default values" for each use-case so the built-in defaults wouldn't count that much.

**Comment by ebuchman** [comment]
So it looks like it's already the case that this is true by default, and has been since it was introduced in v0.19.7 on May 31, at least in Tendermint, but it's not being written to the config file for `gaiad`. The reason is because gaiad uses the `config.WriteConfigFile`, which uses a TOML template from Tendermint that doesn't include this parameter!

So we need to update the defaultConfigTemplate in `config/toml.go` to match all the fields in the Config struct, or any in-process users of Tendermint will get incomplete config files.

If we ever change the default in Tendermint, it will be in the context of #2237 (I added `dev/unsafe` as a mode there).

**Comment by melekes** [comment]
> So we need to update the defaultConfigTemplate in config/toml.go to match all the fields in the Config struct, or any in-process users of Tendermint will get incomplete config files.

went through the template today. it's up to date with the current config.

**Comment by melekes** [comment]
`allow_duplicate_ip` is now set to false by default. https://github.com/tendermint/tendermint/pull/2992
