### ISSUE TITLE
p2p: trying to reconnect despite already being connected

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2716]
In DialPeersAsync, we check if we're already dialing the peer, but not if we're already connected to them. Then we sleep a random amount before actually dialing them. 

Since the PEX doesn't know about persistent peers, it's possible for the PEX to be dialing or even to have already connected to a peer during this time. Then the DialPeersAsync will try to dial, and when it fails, it will keep trying to reconnect, even if we're already connected!

I think this might also explain https://github.com/tendermint/tendermint/issues/2332

I think we want to centralize dialing into a single location so that these kind of races aren't possible.

**Comment by ebuchman** [comment]
Note we tried to address this once before but looks like it was insufficient: https://github.com/tendermint/tendermint/pull/2327

**Comment by melekes** [comment]
I moved IsDialingOrExistingAddress check into DialPeerWithAddress [here](https://github.com/tendermint/tendermint/pull/3011)

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3011 to develop.

**Comment by ebuchman** [comment]
Are we sure that a race still isn't theoretically possible? 

And shouldn't we still do:

> I think we want to centralize dialing into a single location so that these kind of races aren't possible.

**Comment by melekes** [comment]
> Are we sure that a race still isn't theoretically possible?

The chance is low, but still possible I guess.

**Comment by ebuchman** [comment]
Ok opened https://github.com/tendermint/tendermint/issues/3540
