### ISSUE TITLE
Mempool WAL is still created by default in home directory, leads to permission errors

### ISSUE THREAD

**Issue by Thunnini** [tendermint/tendermint#2717]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.25.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10 Home

**What happened**: Error happened when started
panic: Panicked on a Sanity Check: Error opening Mempool wal file: file: [\.tendermint\data\mempool.wal/wal]
expected file permissions: -rw-------, got: -rw-rw-rw-

goroutine 1 [running]:
github.com/tendermint/tendermint/libs/common.PanicSanity(0xd38000, 0xc001e84080)
        C:/Users/yunjh/go/src/github.com/tendermint/tendermint/libs/common/errors.go:224 +0xbf
github.com/tendermint/tendermint/mempool.(*Mempool).InitWAL(0xc001d36e60)
        C:/Users/yunjh/go/src/github.com/tendermint/tendermint/mempool/mempool.go:221 +0x160
github.com/tendermint/tendermint/node.NewNode(0xc00020f320, 0x1036d80, 0xc0001a1c20, 0xc000838ec0, 0x102a800, 0xc0001529c0, 0xc0008390f0, 0xf75368, 0xc000839100, 0x1035800, ...)

**Anything else we need to know**:
This was solved by annotating this line.
https://github.com/tendermint/tendermint/blob/cd172acee82aa2aa9c34735eb8f65827c943b623/libs/autofile/autofile.go#L132
https://github.com/tendermint/tendermint/blob/cd172acee82aa2aa9c34735eb8f65827c943b623/libs/db/fsdb.go#L215

It seems to be related to [this](https://stackoverflow.com/questions/33445727/how-to-control-file-access-in-windows).

**Comment by ebuchman** [comment]
I've been getting this bug on linux too, thanks for reporting.

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/2758. Will be a part of `0.26.1` release.
