### ISSUE TITLE
Is it possible to connect different nodes consisting different tendermint versions in a cluster?

### ISSUE THREAD

**Issue by saikumar-neelam** [tendermint/tendermint#2719]
### Persistent peers or seeds between different nodes with different tendermint versions
Hi,
         I have installed tendermint on 7 different systems but with different versions. Is it possible to connect all.

Thanks in Advance,
Regards,
Sai Kumar

**Comment by ebuchman** [comment]
This is a work in progress and depends on the versions ... In general, the answer is no. In specific cases, yes. We are working on improving backwards compatibility to expand the number of cases.

Anything with the same MAJOR and MINOR version should work together - eg. v0.22.0 and v0.22.8 will work together. If they don't, that's a bug.

Different MINOR versions will typically not work together - eg. v0.24.0 and v0.25.0.
