### ISSUE TITLE
Fire NewBlock event after BlockStore.SaveBlock

### ISSUE THREAD

**Issue by silasdavis** [tendermint/tendermint#273]
Currently the `NewBlock` event is fired here:

https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1229

Before `SaveBlock` is called:

https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1262

This means that if you are subscribing to the NewBlock even and expecting the block to be committed and final (this is what the log output suggests), but you query the consensus engine then there is a period where the block store's height lags the latest `BlockMeta`s height. Noticed this in testing. Not disastrous, but a bit of a wrinkle. Is there any reason why we can't postpone the NewBlock event firing until after the block is saved and tendermint has fully advanced its state?

If not I will make a pull request. I'm thinking of putting it here: https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1267.

**Comment by ebuchman** [comment]
Thanks silas. Nice that your testing caught this :). This is related to https://github.com/tendermint/tendermint/issues/177 and is being address on the [handshake branch](https://github.com/tendermint/tendermint/tree/handshake). The save block will happen before the block is run against the app, and the fire event will happen last, after the state is saved.

**Comment by silasdavis** [comment]
Note this was also mooted in #177

**Comment by silasdavis** [comment]
Ah great
