### ISSUE TITLE
Performance comparison of secp256 between go-ethereum and btcd

### ISSUE THREAD

**Issue by yutianwu** [tendermint/tendermint#2734]
REF: https://github.com/cosmos/cosmos-sdk/issues/2640#issuecomment-434591267

hi, I compared performance of secp256 verifying signatures between go-ethereum and btcd. I found that go-ethereum improves about 30% over btcd.

I used my laptop(MacBook Pro (15-inch, 2018), 2.2 GHz Intel Core i7) to test. Below are the results.

go ethereum:
```go
func BenchmarkVerifySignature(b *testing.B) {
	pubKey, secKey := generateKeyPair()
	msg := randentropy.GetEntropyCSPRNG(32)
	sig, _ := Sign(msg, secKey)

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		VerifySignature(pubKey, msg, sig[:64])
	}
}
```
result:
```
goos: darwin
goarch: amd64
pkg: github.com/ethereum/go-ethereum/crypto/secp256k1
BenchmarkVerifySignature-12    	   10000	    150459 ns/op
PASS
```

btcd:
```go
func BenchmarkSignature_Verify(b *testing.B) {
	privKey, _ := NewPrivateKey(S256())
	pubKey := privKey.PubKey()
	msg := randentropy.GetEntropyCSPRNG(32)
	sig, _ := privKey.Sign(msg)

	b.ResetTimer()

	for i := 0; i < b.N; i++ {
		sig.Verify(msg, pubKey)
	}
}
```
result:
```
goos: darwin
goarch: amd64
pkg: github.com/tendermint/btcd/btcec
BenchmarkSignature_Verify-12    	    5000	    232010 ns/op
PASS
```

the performance is very important because if there are many txs, it will cost a lot of time to verify signatures in `AnteHandler`. So can we move to the version of ethereum?

**Comment by ebuchman** [comment]
go-ethereum uses libsecp256k1 from bitcoin. they just copied the code into their repo. we should look to do the same. I'll close this for https://github.com/tendermint/tendermint/issues/3163. thanks!
