### ISSUE TITLE
Encode more information in prevote/precommit_bit_array in /consensus_state

### ISSUE THREAD

**Issue by kevlubkcm** [tendermint/tendermint#2742]
Right now the prevote/precommit_bit_array only tells us if a vote was received. 
If we added just a little more information, then we probably wouldn't need to parse the `prevotes`/`precommits` arrays

It would be nice to distinguish a few cases:
* Proposed the block
* Vote for the current proposal
* Vote for nil
* Maybe some other error votes
* No vote

As discussed with @ebuchman maybe use `p` to denote the proposer, `y` to denote a vote for current proposal, `x` for nil vote, `_` for no vote received, `e` for a vote in some other state (probably an error vote).

**Comment by LaPetiteSouris** [comment]
@kevlubkcm Hi, newbie to project here, I can take a look into this. 

A few questions, from the [consensus_state doc](https://docs.tendermint.com/master/rpc/#/Info/consensus_state), the following response is given

```JSON
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "round_state": {
      "height/round/step": "1262197/0/8",
      "start_time": "2019-08-01T11:52:38.962730289Z",
      "proposal_block_hash": "634ADAF1F402663BEC2ABC340ECE8B4B45AA906FA603272ACC5F5EED3097E009",
      "locked_block_hash": "634ADAF1F402663BEC2ABC340ECE8B4B45AA906FA603272ACC5F5EED3097E009",
      "valid_block_hash": "634ADAF1F402663BEC2ABC340ECE8B4B45AA906FA603272ACC5F5EED3097E009",
      "height_vote_set": [
        {
          "round": 0,
          "prevotes": [
            "Vote{0:000001E443FD 1262197/00/1(Prevote) 634ADAF1F402 7BB974E1BA40 @ 2019-08-01T11:52:35.513572509Z}",
            "nil-Vote"
          ],
          "prevotes_bit_array": "BA{100:xxxxxxxxxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} 169753436/170151262 = 1.00",
          "precommits": [
            "Vote{5:18C78D135C9D 1262197/00/2(Precommit) 634ADAF1F402 8B5EFFFEABCD @ 2019-08-01T11:52:36.25600005Z}",
            "nil-Vote"
          ],
          "precommits_bit_array": "BA{100:xxxxxx_xxxxx_xxxx_x_xxx_xx_xx_xx__x_x_x__xxxxxxxxxxxxxx_xxxx_xx_xxxxxx_xxxxxxxx_xxxx_xxx_x_xxxx__xxx} 118726247/170151262 = 0.70"
        }
      ],
      "proposer": {
        "address": "D540AB022088612AC74B287D076DBFBC4A377A2E",
        "index": 0
      }
    }
  }


```

Right now the node only returns those information get from `VoteSet` . What precisely do we want to add in `precommits` and `prevotes` ?
