### ISSUE TITLE
uninitialized variable

### ISSUE THREAD

**Issue by iceming123** [tendermint/tendermint#2745]
An uninitialized variable named cs.LockedBlock is used in the consensus/state file enterprocommint function  line 1100 "if cs.LockedBlock.HashesTo(blockID.Hash) " at the latest version.

**Comment by melekes** [comment]
`HashesTo()` returns `false` if `cs.LockedBlock` is `nil`.

https://github.com/tendermint/tendermint/blob/59b75d3f28e4ade0a0d6f15724ee8c656f8bd0b9/types/block.go#L226-L234

I would prefer if we use https://en.wikipedia.org/wiki/Null_object_pattern, but that will require some time, which we don't have (at least now).

**Comment by melekes** [comment]
Feel free to open new issues if you find something suspicious besides ^^^. Cheers!
