### ISSUE TITLE
Couldn't connect to any seeds  module=p2p   

### ISSUE THREAD

**Issue by bobio2018** [tendermint/tendermint#2757]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.25.0-0c9c3292

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Not sure

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:
MacOS High Sierra version 10.13.6

**What happened**:

When running on single node, I see below error "Couldn't connect to any seeds  module=p2p" periodically

**What you expected to happen**:
Expect no errors?

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
Running on single node mode

```
tendermint init
tendermint node --proxy_app=kvstore
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
I[11-05|13:11:57.586] Indexed block                                module=txindex height=10316
I[11-05|13:11:58.485] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[11-05|13:11:58.485] No addresses to dial nor connected peers. Falling back to seeds module=p2p 
E[11-05|13:11:58.485] Couldn't connect to any seeds                module=p2p 
I[11-05|13:11:58.587] Timed out                                    module=consensus dur=997.419ms height=10317 round=0 step=RoundStepNewHeight
```

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by zramsay** [comment]
That's expected behaviour since you're running a single node blockchain. Your chain should still be producing blocks, yeah?

**Comment by melekes** [comment]
@bobio2018 note there's no such thing as "single node" deployment in Tendermint. It only makes sense for local development and trying stuff out as a first time user. We can change the log level from `Error` to `Info` however. Do you want to submit a PR?

**Comment by bobio2018** [comment]
thank you everyone, closing the ticket now.
