### ISSUE TITLE
Cannot search tags within a range of blocks

### ISSUE THREAD

**Issue by fumecow** [tendermint/tendermint#2759]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.25.0-0c9c3292

**Environment**: LotionJS
- **OS** (e.g. from /etc/os-release): Linux
- **Install tools**: npm

**What happened**:

Issuing a query with an inequality comparison for tx.height results in a string comparison.  Specific example is the following query:
```
tx_search?query="event='value' AND tx.height>=15"
```
results in matches:
```
15, 15545, 15555, 151808...
```
and the following query
```
tx_search?query="event='value' AND tx.height<100000"
```
returns an empty array []

What this means is that every attempt to query for tags within a range (which by definition includes a > and < operator) will return an empty array.

**What you expected to happen**:

tx.height should be compared as an integer so tags can be queried in a range of blocks.  It appears that tx.height is stored as a string in the transaction which is perhaps the underlying problem:

```
{
        "hash": "75B0775C6003225B456F1975817DADB97B00F90A",
        "height": "154248",
        "index": 0,
...
}
```

**Comment by melekes** [comment]
The handling logic seems to be correct https://github.com/tendermint/tendermint/blob/59b75d3f28e4ade0a0d6f15724ee8c656f8bd0b9/state/txindex/kv/kv.go#L374. Will try to go deeper

**Comment by melekes** [comment]
Do you index `tx.height` tag? (config.toml#tx_index#index_tags / index_all_tags)

**Comment by mjackson001** [comment]
yes - index_all_tags is set

**Comment by fumecow** [comment]
yes - index_all_tags is set

**Comment by hleb-albau** [comment]
@melekes Same behavior. However, events fired in new blocks are propagated in pubsub.

**Comment by ebuchman** [comment]
Fixed on develop. Should be in v0.26.4
