### ISSUE TITLE
pex create secret connection error and report EOF error

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#2763]
master branch ,my full node connected to seed node, and report 
```
Receive  Ignoring inbound connection: error while adding peer module=p2p address=127.0.0.0:18116   err=Error{EOF}   and block for a while.
```
The problem in `p2p/conn/secret_connection.go`,  the two handshake task is running in parallel, while it should happend in sequence. And function `UnmarshalBinaryLengthPrefixedReader` do not block while there is no message from connection.
 The source code:
```
func shareEphPubKey(conn io.ReadWriteCloser, locEphPub *[32]byte) (remEphPub *[32]byte, err error) {

	// Send our pubkey and receive theirs in tandem.
	var trs, _ = cmn.Parallel(
		func(_ int) (val interface{}, err error, abort bool) {
			var _, err1 = cdc.MarshalBinaryLengthPrefixedWriter(conn, locEphPub)
			if err1 != nil {
				return nil, err1, true // abort
			}
			return nil, nil, false
		},
		func(_ int) (val interface{}, err error, abort bool) {
			var _remEphPub [32]byte
			var _, err2 = cdc.UnmarshalBinaryLengthPrefixedReader(conn, &_remEphPub, 1024*1024) // TODO
			if err2 != nil {
				return nil, err2, true // abort
			}
			return _remEphPub, nil, false
		},
	)

	// If error:
	if trs.FirstError() != nil {
		err = trs.FirstError()
		return
	}

	// Otherwise:
	var _remEphPub = trs.FirstValue().([32]byte)
	return &_remEphPub, nil
}
```

**Comment by guagualvcha** [comment]
This issue can assign to me

**Comment by guagualvcha** [comment]
@ebuchman Could you have a look about thins issue, thks.

**Comment by ebuchman** [comment]
> the two handshake task is running in parallel, while it should happend in sequence

Why should it happen in sequence? I'm not sure the handshake structure is the actual issue here since it works properly in most cases. That error message might take a bit more digging, but maybe I'm missing something?

**Comment by ebuchman** [comment]
Oh I think this might be https://github.com/tendermint/tendermint/issues/2092 / https://github.com/tendermint/tendermint/issues/1988

**Comment by guagualvcha** [comment]
Yes, you can close this.

**Comment by guagualvcha** [comment]
I turn off seed_mode and the problem still exists.  Error message like this:
```
I[11-07|08:14:23.367] Inbound Peer rejected                        
module=p2p err="auth failure: secrect conn failed: EOF, src: 172.22.23.12:59834" numPeers=1
```

**Comment by guagualvcha** [comment]
It it because of Elb health check....
