### ISSUE TITLE
Different state.LastValidators sets

### ISSUE THREAD

**Issue by holygits** [tendermint/tendermint#2768]
Tendermint requires > 2/3 of voting power from validators to commit a block
What happens if the set of commits is different between nodes while still being > 2/3.

As an example, consider a network of 3 nodes A,B and C with equal voting power
and the following set of commits / validation messages on the same Block

```
Node A has commits from: {A, B}
Node B has commits from: {B, C}
Node C has commits: {A, C}
```

An operation like `MedianTime()` will produce different results on each node.
Will this produce a fork due to different blockhash and differing BFT clock values on each node?

This situation could easily occur in a larger network due to delay, partitions, etc.

**Comment by ebuchman** [comment]
We distinguish between "canonical" and "subjective" commits. The latter is what each validator sees locally when they decide to commit a block. The former is what is included by the proposer of the next block in the LastCommit field of the block. This is what makes it canonical and ensures everyone agrees on it, even if its different from the first +2/3 votes they saw that caused them to commit a block. Each block contains a canonical +2/3 commit for the previous block. See the `canonical` field in the `/commit` rpc endpoint which switches from `false` to `true` for block H once block H+1 has been committed :)

We should definitely document this better.

**Comment by holygits** [comment]
Ah, makes complete sense. Thanks for clarifying
