### ISSUE TITLE
RoundState CommitTime is never anything other than zero

### ISSUE THREAD

**Issue by silasdavis** [tendermint/tendermint#277]
The only value write to `RoundState.CommitTime` is here: https://github.com/tendermint/tendermint/blob/e36e79a47470be3f00d75551514de6ac69e73df9/consensus/state.go#L523 

And as such the `CommitTime` is always zero. Seem like there should be a write somewhere in consensus once precommits surpass 2/3 of validators as seen by the node.

**Comment by ebuchman** [comment]
Thanks, already noted: https://github.com/tendermint/tendermint/issues/187

**Comment by silasdavis** [comment]
ah sorry I'll try to not to duplicate in future
