### ISSUE TITLE
`tendermint testnet buddy` command

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2772]
I often find myself wanting to connect two nodes on my local machine for testing. To do so I copy `~/.tendermint` to `~/.tendermint2` and make the following modifications to `~/.tendermint2`:

- remove the `node_key.json` and `priv_validator.json`
- `s/2665/2666/g` in config.toml to change the ports to not conflict
- add the first node as a persistent peer in config.toml
- set ` addr_book_strict = false`

It would be wonderful if we had a single command that just did all this at once. For instance `tendermint testnet buddy` or something that would copy the ~/.tendermint to ~/.tendermint2 and make those changes. Would make it super easy to test things :)

**Comment by melekes** [comment]
Why don't you use `tendermint testnet --v=2` for that?

**Comment by greg-szabo** [comment]
I'm not sure if this was thought out well. Anton's comment is valid. Even a `tendermint testnet --template=~/.tendermint` would work.

**Comment by ebuchman** [comment]
I don't know why that didn't occur to me. Obviously didn't think it through. Thanks guys
