### ISSUE TITLE
Search order sometimes incorrect for Txs that occur on the same block

### ISSUE THREAD

**Issue by fumecow** [tendermint/tendermint#2775]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.25.0-0c9c3292

**Environment**: LotionJS
- **OS** (e.g. from /etc/os-release): Linux
- **Install tools**: npm

**What happened**:
ABCI tx_search results do not always return Txs in the order they were executed in the case where multiple Txs are added to the same block with the same search tag.

The 'index' field in the tx_search results is correct, but they are out of order when queried as a block.

A specific example happened where there were 5 Txs with the identical search tag submitted on the same block, but when queried the order was: 2, 5, 3, 0, 4 (there were also tags present on the block that did not match the tx_search terms).  This indicates the first tag (index=0) on the block was actually returned 4th in the tx_search results, etc.

**What you expected to happen**:
Desirable for tx_search results to always come back in the order the original Txs were processed.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): 
Generate a block with multiple Txs and query for those Tx using the ABCI tx_search command.  The problem seems to occur often but can't guarantee it always happens.

**Config (you can paste only the changes you've made)**:
index_all_tags set to true in config.

**Comment by ebuchman** [comment]
Merged to develop. Should be in v0.26.4
