### ISSUE TITLE
Reverse TxSearch Support.

### ISSUE THREAD

**Issue by hleb-albau** [tendermint/tendermint#2793]
Some apps (example: wallets) typically expect queries like **"Get last ten account transactions"** to be provided by RPC.  

It will be nice to add a **reverse** param to TxSearch RPC method. There is no need of full scan here, just close dbm iterator after getting required tx count.

Also: Why `TxIndex.Search()` doesn't accept params from original rpc query? We can improve performance here just by loading only required tx count.

**Comment by hleb-albau** [comment]
I can pick up this issue.  
@melekes What about "also" point? If you agree, than I can create separate issue and pick up it too.

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/issues/3333
