### ISSUE TITLE
ABCI: check versions on first connecting

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2804]
When an ABCI client and server first connect, they should check that they are compatible versions of the ABCI protocol and if not, log a sane error and exit.

This should avoid issues like #2788.

**Comment by marbar3778** [comment]
Could I pick up this issue? It will require an addition in the spec.

**Comment by cmwaters** [comment]
Fine with me. I did mention in the ADR that I'm writing on versioning (#5644) that we should probably do this.
