### ISSUE TITLE
Initial BeginBlock contains invalid votes and differs on replay

### ISSUE THREAD

**Issue by KrzysiekJ** [tendermint/tendermint#2810]
**Tendermint version**: 0.26.0-c086d0a3

**ABCI app**: https://ercoin.tech

**Steps to reproduce**:

1. Clone the [Ercoin repository](https://gitlab.com/Ercoin/ercoin) (current master: `0c6cedda6bdae870a70655`).
2. Install prerequesites as described in README.
3. Add the following line after [line 109 in `src/ercoin_abci.erl`](https://gitlab.com/Ercoin/ercoin/blob/0c6cedda6bdae870a70655524e008a80d1c1f170/src/ercoin_abci.erl#L109):
```erlang
    io:format("Votes at height ~w: ~w~n", [Data#data.height + 1, Votes]),
```
4. `make app`
5. Generate a testnet by running `make testnet` and entering the following data options:
```erlang
#{accounts_opts =>
      [#{address => "OeFZLmb5xrqc60U+/xztZxnVj3SSpKmIWzlz5U83oJU=",
         valid_for => 3600 * 24,
         balance => 100000000000000},
       #{address => "Hdu8UaISmnbiFzTtjagRNJS+FxKi72aUCW0RRsaDIiU=",
         valid_for => 3600 * 24 * 365,
         locked_for => 3600 * 24 * 365,
         balance => 1}],
 epoch_length => 3600}.
```
6. Run the ABCI server: `make run`.
7. Run Tendermint: `tendermint node --home ~/.ercoin/`.
8. Wait a few blocks and stop Tendermint.
9. Stop ABCI server (`Ctrl-C` two times).
10. Run ABCI server again.
11. Run Tendermint again.

**What should happen**:

The screen with ABCI server should contain the following info which looks like the following in both invocations (the address bytes will differ):

```
Votes at height 1: [{'abci.VoteInfo',{'abci.Validator',<<112,152,188,230,92,74,152,172,211,213,119,166,243,244,83,77,51,212,201,252>>,20},true}]
```

**What actually happens**:

The screen with ABCI server contains the following info at first invocation:

```
Votes at height 1: []
```

It contains the following info at second invocation (note that `true` is replaced with `false`):

```
Votes at height 1: [{'abci.VoteInfo',{'abci.Validator',<<112,152,188,230,92,74,152,172,211,213,119,166,243,244,83,77,51,212,201,252>>,20},false}]
```

(The above difference doesn’t cause a difference in app hash on replay — and panic as a result — only because currently the pseudotimestamp of last block in initial data is the same as `genesis_time` — see #2587 and [commit 916246e1 in Ercoin](https://gitlab.com/Ercoin/ercoin/commit/916246e162c7c2cc9bee9b7424199b68be73d451)).

**Have you tried the latest version**: yes

**Comment by KrzysiekJ** [comment]
Thank you, this explains this — previously `LastCommitInfo` has been treated like current commit info in Ercoin. However, despite this field is meaningless in first block, there is still a discrepancy between what it contains originally and what is sent on replay — which may potentially indicate some more serious problem.

Also sending empty votes in initial `LastCommitInfo` may aid server implementations. For example, people may want to punish validators reported as absent without the need to check block height.

**Comment by ebuchman** [comment]
>  there is still a discrepancy between what it contains originally and what is sent on replay — which may potentially indicate some more serious problem.

Can you clarify the issue here? Could it be related to https://github.com/tendermint/tendermint/pull/2893?

> Also sending empty votes in initial LastCommitInfo may aid server implementations. For example, people may want to punish validators reported as absent without the need to check block height.

Not sure what you're asking for here - we should just send the info corresponding to the validator set for this first block, even though all `signed_last_block = false` ?

**Comment by ebuchman** [comment]
Closing this - let us know if there's still something to address.
