### ISSUE TITLE
Documentation on genesis is outdated

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#2814]
Documentation on "genesis" is outdated and shows a version that would be compatible with 0.22.8 for example. https://tendermint.com/docs/tendermint-core/using-tendermint.html#initialize

It's missing the current consensus_param description as well as "address" field on validator.
Also, there are broken links like the "definition" link in section "Genesis"

**Comment by zramsay** [comment]
#2831 - i tested all the links and couldn't find broken ones in that file
