### ISSUE TITLE
Add Events To Transaction Processing Results

### ISSUE THREAD

**Issue by hleb-albau** [tendermint/tendermint#2816]
ref [cosmos #2770](https://github.com/cosmos/cosmos-sdk/issues/2770).

Let's discuss.
Main idea is to introduce tx events. They can be indexed and searched by tags similar to raw txes. 
I  just want to discuss. Is it good idea to place such logic into tendermint, or we should consider to implement it on cosmos-sdk side?

**Comment by cwgoes** [comment]
Can you explain your usecase in more detail here - is this similar to https://github.com/tendermint/tendermint/issues/1859?

**Comment by hleb-albau** [comment]
@cwgoes Yes, sorry for one more issue. It is so desirable feature :( Putting json into tags seems as ad-hoc. I think simple indexing can be done using kv.
Also, one more thing: **subscribe** rpc endpoint. We should provide a way to publish tags on cosmos sdk side than.

**Comment by ebuchman** [comment]
How is this distinct from the tags already included in tx responses?

**Comment by ebuchman** [comment]
Would changing tags to be a list-of-lists be sufficient? We should be wary for now of special privileges for Go apps.

**Comment by hleb-albau** [comment]
@ebuchman yeah, it is same as https://github.com/tendermint/tendermint/pull/1803. Will close this as duplicate.
