### ISSUE TITLE
Either `/status` or `/net_info` should report whether node is in seed mode

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2817]
Right now its not possible to tell whether a given node is operating in seed mode. 

We should make this available, probably in the `node_info.other` section

**Comment by melekes** [comment]
> probably in the node_info.other section

Shouldn't we be careful with putting too much stuff inside `node_info`?

**Comment by ebuchman** [comment]
Agreed. What would you recommend? Mostly think it would be useful for this to appear in an RPC endpoint, but we don't necessarily need to be able to know the seed status for all of a node's peers, just for the node itself, so it doesn't necessarily need to go in node_info.

Probably what we really need to do is disentangle the node_info we display in RPC from that we send in the p2p handshake...

**Comment by danil-lashin** [comment]
Maybe we should introduce new key in `/status` endpoint called, i.e., `other`? We can use it to report node configuration parameters which are not suitable for other response keys:

- `seed_mode`
- `cors.allowed_origins`, `cors.allowed_methods`, `cors.allowed_headers` - may be useful for the web applications
- `seeds` - may be useful to collect as many seed nodes as possible
- `send_rate`, `recv_rate`
- `mempool_broadcast`
- ...

**Comment by melekes** [comment]
Looks like we need an endpoint which just returns a content of config.toml. I remember that there was an issue about that, but I can't find it now.

**Comment by thanethomson** [comment]
Do we still need this?

**Comment by melekes** [comment]
I think so

**Comment by thanethomson** [comment]
Should it be one of the unsafe endpoints? Or authenticated? I'm just thinking of parameters like `private_peer_ids`.
