### ISSUE TITLE
Replace LevelDB with Inteface for Pluggable DBs

### ISSUE THREAD

**Issue by wolfposd** [tendermint/tendermint#282]
It would be a neat addition if the underlying LevelDB could be replaced with a different DB to allow read access by other clients. Ideally this would be a pluggable interface to allow implementations for all kinds of DBs (e.g. Mongo, MySQL)

Developers would need to make sure to only use Read-Access to the Tendermint-handled Tables/Documents to not corrupt data.

Two benefits I can see so far:
- no redundant data storage (currently TM-Node + NodeApp store semi-redundant data)
- easy query with SQL/NoSQL syntax (depending on used DB)

Drawbacks:
- possibly performance

**Comment by ebuchman** [comment]
This is already done! We use a db interface: https://github.com/tendermint/go-db/blob/master/db.go#L9

We have two implementations, leveldb and a memdb (just an in memory map). 

But you want to share the db across tendermint and the app? thats a little more complicated. If you want to implement another db in the `go-db` package, we'd love a PR :)

**Comment by wolfposd** [comment]
Will do when it comes to it ;-)

Some futher thoughts:
The db interface needs to be a little higher in the tier as it currently is. It can be beneficiary for other DBs if keys and values are not stored in byte[], but rather in plaintext or even have a column layout for SQL-Based DBs.

**Comment by ebuchman** [comment]
Closing for now as there doesn't seem to be an immediate actionable item here. Feel free to suggest another implementation in `tmlibs/db` (new home for go-db) or to share a design doc about your thoughts on this.

**Comment by kunaldhariwal** [comment]
@wolfposd  Hey, did you implement this? one db across tendermint and the app?
if yes, then how?

> This is already done! We use a db interface: https://github.com/tendermint/go-db/blob/master/db.go#L9
> 
> We have two implementations, leveldb and a memdb (just an in memory map).
> 
> But you want to share the db across tendermint and the app? thats a little more complicated. If you want to implement another db in the `go-db` package, we'd love a PR :)
