### ISSUE TITLE
p2p: memory leak in seed nodes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2821]
Seed nodes on gaia-9001 seem to have crashed from OOM, suggesting there is a memory leak somewhere.

Not sure yet if this leak is present in general, or only on seeds

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3397 might fix this

**Comment by melekes** [comment]
Should be fixed by https://github.com/tendermint/tendermint/pull/3478

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3478 to develop.

**Comment by ebuchman** [comment]
This probably also fixes #3306 yeh ?

**Comment by melekes** [comment]
Not according to the heap profile and goroutines dump Hendrick has posted.
