### ISSUE TITLE
rpc: too many broadcast_commit calls can lead to consensus liveness issues

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2826]
### Issue 

See #2748 

pubsub currently has no buffer (capacity: 0) by default, which helps us identify issues early. One of such issues is if it (pubsub) has too many subscribers (for example, too many `/broadcast_commit` calls waiting for txs results), we can't accept a new msg until we've broadcasted a previous one (to all subscribers). 

As an example, this https://github.com/tendermint/tendermint/blob/fb10209a9630688757d84c8dd28ec32bcb4a3e7d/consensus/state.go#L708 will block until previous msg is delivered to all subscribers. 

This can potentially lead to consensus liveness issues.

### Proposed action

We should rate limit the amount of `broadcast_commit` calls and other RPC endpoints which use pubsub (or recommend a limit for our clients to set in nginx or other software) + we need to figure out correct timeout for `/broadcast_commit` and make it configurable

https://github.com/tendermint/tendermint/blob/fb10209a9630688757d84c8dd28ec32bcb4a3e7d/rpc/core/mempool.go#L188-L189

**Comment by srmo** [comment]
Is this suggestion for synced calls? I.e. would broadcast_tx_async be unaffected?

**Comment by melekes** [comment]
> Is this suggestion for synced calls? I.e. would broadcast_tx_async be unaffected?

_sync/async are unaffected.

**Comment by mattkanwisher** [comment]
I'll add to this thread as the other, the change to 10 seconds from 2 minutes broke a ton of our software. So we have patched it temporarily on our side, and working on a PR to make these timeouts configurable https://github.com/mattkanwisher/tendermint/commit/9a8cb94fad835aeb4b8507f8ab34d59cb75f3926#diff-f0521764a882805b106091a2215d58c2R214

**Comment by melekes** [comment]
MaxSubscriptionClient and MaxSubscriptionsPerClient can be hard to figure out. Another option is to reject subscribers based on the current queue size https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-033-pubsub.md#future-problems-and-their-possible-solutions

> We should also consider a max_websocket_connections to limit the maximum number of websocket connections at a time.

We probably don't want too many variables in the config (again, because some of them are dependent on each other and the user will have to calculate their values properly). There's the `max_open_connections` param, which includes WebSocket connections.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3269 to develop. A follow-up issue with small nits / improvement suggestions https://github.com/tendermint/tendermint/issues/3410
