### ISSUE TITLE
Remove storing height a tx was received at in mempool

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2834]
# Problem

Storing the height for every received tx in the mempool causes a memory overhead of an additional 8 bytes / per tx. This isn't great given that this is a prime target for DOSing other full node's memory usage, and removal of this could lead to storing many more txs in the mempool with the same amount of memory. 

## Reason for inclusion / removal

It was included so that we don't gossip txs to peers who are too far behind to utilize them. However this in my opinion is the incorrect case to optimize for. You should assume that the majority of your peers are within one block of you at most times. In rare situations, perhaps they are 2 blocks behind. The set of txs that depend on the last two blocks of state are quite small. It is odd that we are taking this memory penalty for this use case. Instead we should just not gossip txs to peers who are more than two or three blocks behind, which can be easily checked in the broadcastTxRoutine. Recall that txs which are order dependent will get gossiped in an order dependent manner to other peers, presuming they both passed checked tx locally in your mempool. Thus the set of txs which we gossip to a peer who can't understand them will then be quite small.

**Comment by ValarDragon** [comment]
cc @milosevic, per discussion in the mempool call this morning, we probably want to remove this.

**Comment by ebuchman** [comment]
What if we want to support time based eviction of txs? 

Loom team implemented this in their fork of tendermint here: https://github.com/mattkanwisher/tendermint/pull/3

**Comment by ValarDragon** [comment]
Stuff like that is why I think the application should be able to change the mempool implementation. Its not something everyones mempool needs to do, but it is great under certain scenarios

**Comment by marbar3778** [comment]
If the application becomes aware of the txs in the mempool we could look at introducing an extra abci call to evict a list of txs, can be called at the end of each block (`EndBlockResponse` or `DeliverBlockResponse`) and it would not should not cause any sort of locking.

**Comment by alexanderbez** [comment]
Let's keep this in mind for the mempool refactor.
