### ISSUE TITLE
Mempool remove counter from mempool tx

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2835]
Within every single tx in the mempool, we store a 64 bit counter, as an index for when it was inserted into the mempool. This counter doesn't really serve any purpose. It was likely added for debugging at one point, but I am skeptical of the utility of it within debugging, as the order of txs in the mempool already gives you the insertion order. I believe we should remove the counter to reclaim that space, which enables greater mempool sizes / or mitigates memory usage at the same mempool size.

**Comment by melekes** [comment]
PR with a fix/feature was merged to develop. Will be shipped with 0.26.4 or 0.27.0 release (check the changelog).
