### ISSUE TITLE
consensus: tombstone validators that ever double signed

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2839]
Initial idea proposed here: https://github.com/cosmos/cosmos-sdk/issues/2363

Would subsume both https://github.com/tendermint/tendermint/issues/2561 and https://github.com/tendermint/tendermint/issues/2565 by making all evidence for a given validator valid once and only once.

Can also help resolve some of https://github.com/tendermint/tendermint/issues/2653

The idea is that once a validator double signs a single time, its voting power goes to 0 forever and it can never be re-added. 

This needs a proper ADR, but may radically simplify the evidence reactor logic and the application-level slashing logic.

**Comment by ebuchman** [comment]
There is a spec on the SDK side here: https://github.com/cosmos/cosmos-sdk/pull/3103

I think on the Tendermint side, this is just about spam-prevention for new evidence - ie. we only accept a piece of evidence for a given validator address *once*. Once evidence for validator X is included in a block, no new evidence for validator X will ever be accepted. 

This puts the burden on the application to decide how to handle that evidence. If, for instance, the evidence is actually too old, and refers to a validator that long ago unbonded, the application would have to ensure that the validator never rebonds, as Tendermint will not be able to provide new evidence for it.

**Comment by alexanderbez** [comment]
I recall that we are permanently tombstoning validators and keeping their key revoked in state indefinitely. But yes, other applications would have to also enforce this/handle this gracefully.

**Comment by ebuchman** [comment]
> I recall that we are permanently tombstoning validators and keeping their key revoked in state indefinitely. But yes, other applications would have to also enforce this/handle this gracefully.

Right, I'm not sure we want to make that fundamental to Tendermint though. It would mean apps can't have more nuanced control over punishment - they either have to tombstone the validator right away, not punish at all, or use some application specific transaction containing evidence instead of relying on Tendermint to broadcast it (Tendermint would still have to detect and notify clients about this evidence so they can make the txs, even if Tendermint doesn't store it and propose it in blocks ...).

**Comment by mattkanwisher** [comment]
How would this effect situations where people have Hot and Cold Validators with same private keys, if they accidentally have both run at same time, seems like a potentially very bad situation to get tombstoned?

**Comment by tessr** [comment]
I'm removing this from the 0.34 milestone. It sounds like there is further discussion needed; and there isn't urgency here for Cosmos since it enforces this on its own already.

**Comment by marbar3778** [comment]
The current way in which evidence is handled is left up to the application, yes this puts the burden on to the application to write this code but also allows the application to decide if tombstoning or other ramifications are actually needed for the economic/security model. Bringing tombstoning Tendermint would make an assumption on how applications would like to handle malicious actors. 

Currently, this logic is handled in the cosmos-sdk as there is a need for this behavior. If teams would like to see how this is done they can visit: https://docs.cosmos.network/master/modules/slashing/07_tombstone.html for more information

This proposal was discussed on the Tendermint team call (4/5/2020) and it was agreed to close this proposal in favor of the current handling of evidence.
