### ISSUE TITLE
MConnConfig doesn't take effect because transport use the default

### ISSUE THREAD

**Issue by yutianwu** [tendermint/tendermint#2842]
hi, recently, I found that the blocking time increases dramatically even in local testnet.

It cost me one whole day to track it down... It turns out that transport does not use the `MConnConfig`.

https://github.com/tendermint/tendermint/blob/6353862ac00cefe9e2710cc6763789a83d9f069a/node/node.go#L374

but we use the `MConnConfig` in Switch.

https://github.com/tendermint/tendermint/blob/6353862ac00cefe9e2710cc6763789a83d9f069a/p2p/switch.go#L105-L111

but the config in Switch does not take effect actually.

**Comment by yutianwu** [comment]
for the relatively old version, it can produce many blocks in one seconds. but now it takes 500ms to produce a block.

**Comment by ebuchman** [comment]
No doubt. Will be fixed in v0.26.3 - thanks!

**Comment by yutianwu** [comment]
I was planning to fix this this weekend, but it seems you have fixed it already :)

**Comment by ebuchman** [comment]
Heh thanks - let us know next time when you open the issue if you plan to tackle it and we'll leave it for you :)

Enjoy your weekend!
