### ISSUE TITLE
non-deterministic test fail for autofile in consensus

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2852]
https://circleci.com/gh/tendermint/tendermint/34592#tests/containers/3

```
panic: open /tmp/wal349526013: no such file or directory

goroutine 43344 [running]:
github.com/tendermint/tendermint/libs/autofile.(*Group).readGroupInfo(0xc427d920b0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/tendermint/tendermint/libs/autofile/group.go:504 +0x634
github.com/tendermint/tendermint/libs/autofile.(*Group).checkTotalSizeLimit(0xc427d920b0)
	/go/src/github.com/tendermint/tendermint/libs/autofile/group.go:247 +0x75
github.com/tendermint/tendermint/libs/autofile.(*Group).processTicks(0xc427d920b0)
	/go/src/github.com/tendermint/tendermint/libs/autofile/group.go:218 +0x64
created by github.com/tendermint/tendermint/libs/autofile.(*Group).OnStart
	/go/src/github.com/tendermint/tendermint/libs/autofile/group.go:132 +0xaf
FAIL	github.com/tendermint/tendermint/consensus	165.813s
Exited with code 1
```

**Comment by melekes** [comment]
Would be great to know which test failed exactly. I've looked at this quickly, but was not able to understand why there's no directory. In one test, we remove it using defer https://github.com/tendermint/tendermint/blob/2d525bf2b8267cbcebd5ce3899a78684ddbeeff4/consensus/wal_test.go#L29, but WAL is stopped before https://github.com/tendermint/tendermint/blob/2d525bf2b8267cbcebd5ce3899a78684ddbeeff4/consensus/wal_test.go#L41

**Comment by ebuchman** [comment]
Maybe the WAL doesn't finish shutting down fully before the remove is triggered? Some background routine in the autofile that does one more action, and encounters a missing dir ...
