### ISSUE TITLE
Switch JSON marshalling to a faster library

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2854]
iirc, amino's JSON marshaller is a bit slower than the stdlib's marshaller. We should switch to something like gojay: https://github.com/francoispqt/gojay, which provides faster / more memory efficient JSON marshalling.

_Originally posted by @ValarDragon in https://github.com/tendermint/tendermint/pull/2848/review_comment/create_

**Comment by ebuchman** [comment]
Closing this until JSON marhsaling is found to be an actual performance issue. Nice idea in spirit but also just means a new dependency for minimal gain now.
