### ISSUE TITLE
mempool: add txs from Update to cache

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2855]
We should add txs that come in from mempool.Update to the mempool's cache, so that they never hit a potentially expensive check tx. 

_Originally posted by @ValarDragon in https://github.com/tendermint/tendermint/issues/2846#issuecomment-439216656_

**Comment by melekes** [comment]
PR with a fix/feature was merged to develop. Will be shipped with 0.26.4 or 0.27.0 release (check the changelog).
