### ISSUE TITLE
Facing Error while try to run tendermint using docker

### ISSUE THREAD

**Issue by nagarajmanjunath** [tendermint/tendermint#2861]
**Tendermint version** : 0.26.2"
**Environment**:
- **OS** Windows 10:

**What happened**:
[ERROR] Could not boot kernel. error launching Tendermint server: error starting Tendermint node: open data/data/cs.wal/wal: permission denied.

I am using docker to install tendermint in my windows 10, I am facing the error called   permission denied, when i am trying to run tendermint.

 docker run -it --rm -v c:\Users\Temp\chain2:/tendermint  tendermint/tendermint

**Comment by wu-ziching** [comment]
Windows permissions don't seem to work well with https://github.com/tendermint/tendermint/pull/2286. File gets created with the wrong permissions and always panics. Looks like:

> E[16116-11-16|12:43:12.301] Failed to open WAL for consensus state       module=consensus wal=\.tendermint\data\cs.wal\wal err="file: [\\.tendermint\\data\\cs.wal\\wal]\nexpected file permissions: -rw-------, got: -rw-rw-rw-"
> E[16116-11-16|12:43:12.319] Error loading ConsensusState wal             module=consensus err="file: [\\.tendermint\\data\\cs.wal\\wal]\nexpected file permissions: -rw-------, got: -rw-rw-rw-"
> ERROR: Failed to start node: file: [\.tendermint\data\cs.wal\wal]
> expected file permissions: -rw-------, got: -rw-rw-rw-

**Comment by nagarajmanjunath** [comment]
@ebuchman  Thanks its work great !
