### ISSUE TITLE
Non-deterministic test failure in tendermint/node

### ISSUE THREAD

**Issue by joe-bowman** [tendermint/tendermint#2867]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.26.1

Repeated, but non consistently (3 or 4 times over 20 runs), failures of the following test - always the same failure:

```
--- FAIL: TestNodeDelayedStop (5.01s)
        Error Trace:    node_test.go:102
	Error:      	Not equal:
	            	expected: true
	            	actual  : false
	Test:       	TestNodeDelayedStop
```

**Comment by ebuchman** [comment]
Any details on what kind of machine and OS you're running this on and what command you're using to run the test?

**Comment by marbar3778** [comment]
This test is no longer present in the codebase, closing this issue.
