### ISSUE TITLE
log: module=main setting overrides all others

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2868]
I just noticed that the default log_level setting, `log_level = "main:info,state:info,*:error"`, actually causes all modules to log at `info` level. This seems to be because the root logger has `module=main`, so all loggers derive from this and end up with the same setting as main, in this case `info`.

The `main` module doesn't log all that much, so we could just eliminate the `main:info` piece from the default. But we should probably fix this issue anyhow so that derivative loggers can have different levels than their parents.

**Comment by melekes** [comment]
PR with a fix/feature was merged to develop. Will be shipped with 0.26.4 or 0.27.0 release (check the changelog).
