### ISSUE TITLE
Enhancements to rpc events

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#287]
As I am working with the jsonrpc interface while developing a client, I came across some enhancement wishes, which I believe would be generally useful. I am also willing to work on a pull request for them (but will need @ebuchman for review and cleanup).

First, simple enough, on the tx event, can we add the block height of the block in which it is / will be committed. It is great to receive this event, but if I want to double-check the node (a minority may be Byzantine), I will want to see the block that contains it. I think the block height is the easiest way to pass the info so I can query the block myself if needed.

Second, there is both rpc and pub-sub on the tendermint nodes. However, I only have a simple request-response interface to the tmsp app (add tx or make query). It would be super cool to also allow the client to subscribe to events in the app. Example use-case, I query for my account balance and listen to any events that change it. Only the app know this. Otherwise, I must listen to all tx and parse them locally.

I have used couchbase before, which has some nice ideas about syncing data. They use channel names for this. Every tx may define a list (array) of strings, which are channel names that the update gets pushed to. In append_tx, if the result is okay, also send txevents to all channels returned from tmsp app, prefixed by tmsp: to avoid conflicts. Like "tmsp:my_acct_id". This is generic infrastructure to support pub-sub in any tmsp app.

This second suggestion would add a field ([] string) to the tmsp result, but since the nil value has no effect, it should be backwards compatible.

Please let me know your thoughts on these changes and a thumbs up or down.

**Comment by ebuchman** [comment]
Great ideas!

For getting the height, just subscribe to the newblockheader event as well as the tx event; the block event will come first and will apply to all tx events that come subsequently until the next new block event. I suppose it would be fine if the tx events came with a block height as well though. This should be easy. We also need to do tx indexing (https://github.com/tendermint/tendermint/issues/237), so we can poll for the tx and get the height as well.

Originally there were plans to enable the app to push events, and to allow subscriptions to them through the ws. In the meantime, you could implement such a mechanism in the app, but of course thats plenty of work to get the ws up and running. We can revisit adding an event mechanism to TMSP - it might also double as a means for broadcast_tx (https://github.com/tendermint/tendermint/issues/208).

**Comment by ebuchman** [comment]
First feature has been merged. Second feature warrants more discussion and is along the lines of https://github.com/tendermint/tendermint/issues/376. Let's keep up the conversation there.
