### ISSUE TITLE
Improve Tendermint RPC docs (POST/websocket)

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#2880]
First of all, thank you for https://tendermint.com/rpc, it contains a very good source of information and defines the endpoints and return values quite well. One issue, however, is that all examples are in URI format, which works for quick curl tests, while most developers would prefer the json-rpc POST API, or better yet, the websocket endpoint that allows for subscriptions (which are a wonderful feature).

In order to make the docs more useful for people coding clients, I would suggest three improvements:

1. Alongside the `curl` examples, please show an example JSON-RPC POST body
2. Please specify if all byte fields are returned as hex or base64 (this seems more standard on hex these days, but I am unsure of eg. the broadcast_tx_commit data field, which was always base64 in the past)
3. Please provide documentation of valid subscription query types and expected response bodies. They are the hardest ones to produce example for, and very useful.

Thank you for this work, and I know the docs keep getting better, just want to push for a little more polish.

**Comment by ethanfrey** [comment]
It seems that the docs are quite out-of-date as well.

https://tendermint.com/rpc/#abciinfo shows
```
    "result": {
        "response": {
            "log": "exists",
            "height": "0",
            "proof": "010114FED0DAD959F36091AD761C922ABA3CBF1D8349990101020103011406AA2262E2F448242DF2C2607C3CDC705313EE3B0001149D16177BC71E445476174622EA559715C293740C",
            "value": "61626364",
            "key": "61626364",
            "index": "-1",
            "code": "0"
        }
    }
```

When running against a local tendermint 0.25 kvstore, I get:
`curl 'localhost:12345/abci_query?path=""&data="abcd"&prove=false'`
```
  "result": {
    "response": {
      "log": "does not exist",
      "index": "-1",
      "key": "YWJjZA=="
    }
  }
```

key is base64, while example was hex

**Comment by ethanfrey** [comment]
Move to swagger?
Then you remove all the custom rpc code with swagger autogen?

I have used swagger before for go apis and it can work, but will require a total overhaul of the rpc package. Is there an issue for that?

**Comment by srmo** [comment]
Would love this. Or even thinking about jsonschema. 
Our use case would be, that we use such an API to autogenerate json mapping classes (java) when the protocol is updated. Versioning would also allow to easily recognize updated formats.
