### ISSUE TITLE
Don't interface encode mempool messages

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2883]
Currently we interface encode mempool messages: https://github.com/tendermint/tendermint/blob/master/mempool/reactor.go#L177

This is an extra 4 bytes on every tx gossip, which is unnecessary and not really negligible. Were also not really getting anything by doing this, since there is only one message that goes to/from the mempool reactor, and in the future it will still be a small number of things. (This is also a good candidate for a protobuf oneof, the 4 byte prefix is a bit silly)

**Comment by Liamsi** [comment]
>  and in the future it will still be a small number of things. 

How will it be more than "one thing"? Can't find anything about this.

**Comment by ValarDragon** [comment]
It could potentially be more with future mempool models. Mostly meant even if that is the case, it will be a small constant, nothing on the order of `256^4` options that we are allowing to choose between.
