### ISSUE TITLE
Install cleveldb instructions need tweak

### ISSUE THREAD

**Issue by gcohler** [tendermint/tendermint#2884]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Using master branch

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):  Ubuntu 18.04 -- running on AWS EC2 instance.
- **Install tools**:
- **Others**:

**What happened**:
I attempted to use the instructions and snippets in the _Compile with CLevelDB support / Ubuntu section_ of https://github.com/tendermint/tendermint/blob/master/docs/introduction/install.md -- and they didn't quite work as stated.

**What you expected to happen**:
I expected to be able to stop and restart the tendermint app.

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
To fix the problem:  the cp commands that copy the lib and include files need to be sudo'd.  And the image built in the final step needs to be cp'd to the $GOPATH/bin folder in order to be used.

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by melekes** [comment]
PR with a fix/feature was merged to develop. Will be shipped with 0.26.4 or 0.27.0 release (check the changelog).
