### ISSUE TITLE
Blockchain reactor: disconnect from bad peers

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2896]
We currently respond to each block request message by sending (more precisely trying to send) a block. So for example, a peer can keep sending us requests for the same block and we will deliver it. This is clearly not a behaviour of a good peer. 

We need a way to measure a quality of peers and disconnect from bad peers.

**Comment by ebuchman** [comment]
We should also ensure peers only send us blocks we explicitly requested.

**Comment by ebuchman** [comment]
Will require #2897
