### ISSUE TITLE
Refactor blockchain reactor for better testability

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2897]
Tests are "hard to read, hard to modify, hard to debug" (@melekes). One idea how tests can be improved is splitting business (algorithm) logic in a function and separate it from a real message sending. This logic should capture core algorithm, i.e., for a given state, what messages we should send and how we should react upon message reception.

**Comment by ebuchman** [comment]
Might need this to help do #2896 and #2699

**Comment by marbar3778** [comment]
When https://github.com/tendermint/tendermint/pull/3561 is merged, do we consider this closed or do we keep it open for v2 of the refactor? @milosevic @ancazamfir

**Comment by marbar3778** [comment]
Closing this as v2 was recently merged, if this needs to be open please reopen it
