### ISSUE TITLE
Something seems to be wrong in reward pool calculation

### ISSUE THREAD

**Issue by dlguddus** [tendermint/tendermint#2898]
# environment
gaiad version : 0.26.1-rc1-6-gb5dafe54
genesis.json : inflation 1000 / other parameters as default
4 nodes started with equal power 100

# simulation
1. started testnet with 4 nodes
2. execute withdrawalreward from node0 -> got 16steak
3. waited for 100 blocks(about 10 minutes)
4. execute withdrawalreward from all nodes
5. final account balance : [node0,node1,node2,node3] = [27, 12, 12, 34]

# analysis
1. I checked node3 got 2 proposal rewards which is 21.6steak(400power X 2 X 10.5% X 24%)
-> 10.5% is the hourly inflation rate calculated from 1000 inflation parameter
2. rewards except proposer rewards = [27,12,12,12]
-> node0 got much more rewards than others. It should have been similar each other.
3. After node0's withdrawal, node0's pool became zero, but right after that, it grows very fast.
Meanwhile, the other 3 nodes' pool were shrinking continuously until they became about 12steak.
Total pool stays flat during the 100 blocks

# reason of suspection
1. reward except proposal reward should be fairly distributed but it was not.
2. some validator's pool is decreasing -> strange
3. some validator's pool is increasing although total pool stays flat -> strange

# conclusion
I suspect there is a mis-calculation in the pool distribution logic.

# Edited
As I rethought of this issue, I think now it is not a bug. Rewards distributed by DelAccum. By this, it is correct. But still the consequence is odd. This might be due to hourly provision distortion.

**Comment by ebuchman** [comment]
If there's still an issue here, would you mind opening it on the SDK repo? That's where the fee distribution logic is.

**Comment by dlguddus** [comment]
i will sum up some issues around reward distrubution, withdraw and pool management and post it all together with suggested solution. it will take some days. thanks!
