### ISSUE TITLE
docs: amino encoding - prefixes in table and examples are different

### ISSUE THREAD

**Issue by vicnaum** [tendermint/tendermint#2902]
In:
https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/encoding.md

Section **Public Key Cryptography** has a table of prefixes and **Examples** below.

There are discrepancies between them:
0xEB5AE987 in table for Secp256k1 pubkey, but EB5AE982 in example
0x7FC4A495 in table for Secp256k1 signature, but 16E1FEEA bytes in example

I see the table was changed during one commit (d47b4ef12dbb787298d72529828c17a21f79553e), but examples section haven't.

**Comment by Liamsi** [comment]
Thanks! Also, signature are now just encoded as bytes and there is a new key-type which was missing (the table is outdated too). I've quickly fixed the table and the example in https://github.com/tendermint/tendermint/pull/2903
