### ISSUE TITLE
False positive when searching for a prefix of a tag value

### ISSUE THREAD

**Issue by feldgendler** [tendermint/tendermint#2908]
*Tendermint version:* 0.22.8

The patch below adds a unit test that fails:

```
--- a/state/txindex/kv/kv_test.go
+++ b/state/txindex/kv/kv_test.go
@@ -89,6 +89,8 @@ func TestTxSearch(t *testing.T) {
                {"account.owner CONTAINS 'an'", 1},
                // search using CONTAINS
                {"account.owner CONTAINS 'Vlad'", 0},
+               // search using a prefix of the stored value
+               {"account.owner = 'Iv'", 0},
        }

        for _, tc := range testCases {
```

The stored value for `account.owner` is `Ivan`, but searching for just `Iv` produces a false positive.

The reason this happens is that `startKey` in `state/txindex/kv/kv.go` returns a prefix that matches too much: `account.owner/Iv` in this case. To avoid false positives, it should rather return `account.owner/Iv/`. 

There is _probably_ a similar bug where `matchRange` looks up `key` when it really should look up `key/`.

**Comment by ebuchman** [comment]
Merged to develop. To be released in v0.26.4. Thanks!

**Comment by feldgendler** [comment]
Thank you!

What about range matching? I haven't had the time to test that, but I suspect a similar bug.

**Comment by feldgendler** [comment]
I took another look at the code. `Search` passes `[]byte(r.key)` as `prefix` into `matchRange`, which calls `dbm.IteratePrefix` for it. This looks prone to the same problem: it will find any longer keys of which the one specified is a prerfix. Either `Search` or `matchRange` has to append a slash to the key.

**Comment by melekes** [comment]
Missed it. Thanks for spotting!
