### ISSUE TITLE
Search query = operator should treat numbers as numbers

### ISSUE THREAD

**Issue by feldgendler** [tendermint/tendermint#2910]
Currently, transaction search queries `key = 1` and `key = '1'` are equivalent.

I believe `key = 1` should match tags like `key=01` and `key=+1`. This would be consistent with how queries like `key < 1` treat such tags.

On the other hand, `key = '1'` should match only the exact string. This can be achieved by introducing different operator types for number equality and string equality.

**Comment by marbar3778** [comment]
In 0.35 we will support psql. If you would like a larger feature set, please use postgres instead of the native indexer.
