### ISSUE TITLE
Incorrect Block.Header.AppHash across multi node setup after multiple transaction input. (4 validator nodes)

### ISSUE THREAD

**Issue by Nicolaas0411** [tendermint/tendermint#2914]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.23.1

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
ixo - https://github.com/ixofoundation/ixo-cosmos

**Environment**:
- Amazon EC2 instances:
Brazil: 54.94.185.175:46657
California: 13.52.68.216:46657
Singapore: 13.251.214.74:46657
Sydney: 13.237.11.166:46657
(Port mapping in docker container: 26656 -> 46656)

- Docker images: 
https://hub.docker.com/r/trustlab/ixo-blockchain/

**What happened**:
After we send in some test transactions the validator nodes stops creating empty blocks because the app hash does not sync properly across the nodes.

```
California Validator 1: enterPrevote: ProposalBlock is invalid       module=consensus height=1194 round=160 err="Wrong Block.Header.AppHash.  Expected 85B2CC5B3CD02B1BAE069DC02C00373668AD961B, got C3429C88E6BDA0F10CADDFF41F2A088FBDFABF5F"
Brazil  Validator 2: enterPrevote: ProposalBlock is invalid       module=consensus height=1194 round=196 err="Wrong Block.Header.AppHash.  Expected 2156755F6006000477453CFF9626CBE09E900869, got C3429C88E6BDA0F10CADDFF41F2A088FBDFABF5F"
Singapore Validator 3: enterPrevote: ProposalBlock is invalid       module=consensus height=1194 round=195 err="Wrong Block.Header.AppHash.  Expected C3429C88E6BDA0F10CADDFF41F2A088FBDFABF5F, got 85B2CC5B3CD02B1BAE069DC02C00373668AD961B"
Sydney Validator 4: enterPrevote: ProposalBlock is invalid       module=consensus height=1194 round=160 err="Wrong Block.Header.AppHash.  Expected 0F5680EDB054977EDE13F70A49E493C2F08FC91C, got C3429C88E6BDA0F10CADDFF41F2A088FBDFABF5F"
```

**What you expected to happen**:
The app hash should sync across all the nodes and tendermint should keep creating empty blocks.

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
1. Run the docker-compose script found here on multiple instances: 
    https://github.com/ixofoundation/ixo-cosmos/blob/master/docker-compose.yml
2. Configure the genesis.json with the validator information. 
3. Start one of the nodes.
4. Configure the persistent peers prop in config.toml to point to the running node.
5. Commit some transactions. 

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

E[11-26|11:53:09.172] enterPrevote: ProposalBlock is invalid       module=consensus height=1194 round=160 err="Wrong Block.Header.AppHash.  Expected 85B2CC5B3CD02B1BAE069DC02C00373668AD961B, got C3429C88E6BDA0F10CADDFF41F2A088FBDFABF5F"

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**
```
"peers": [
      {
        "node_address": "e90d54aac15f1ae06909cfccff8fe98fd50631e1@172.18.0.3:26656",
        "peer_state": {
          "round_state": {
            "height": "1194",
            "round": "2605",
            "step": 6,
            "start_time": "2018-11-26T11:49:59.611882129Z",
            "proposal": true,
            "proposal_block_parts_header": {
              "total": "1",
              "hash": "EBC8823EBCE831E7848D16E7EB3347BB2E67FB72"
            },
            "proposal_block_parts": "x",
            "proposal_pol_round": "2604",
            "proposal_pol": "____",
            "prevotes": "xxxx",
            "precommits": "xx__",
            "last_commit_round": "0",
            "last_commit": "xxxx",
            "catchup_commit_round": "2604",
            "catchup_commit": "xxxx"
          },
          "stats": {
            "last_vote_height": "1194",
            "votes": "1194",
            "last_block_part_height": "1194",
            "block_parts": "299"
          }
        }
      },
      {
        "node_address": "b9cf19e8e7acd505a8515d14fbbbc87a616c8eed@172.18.0.3:26656",
        "peer_state": {
          "round_state": {
            "height": "1194",
            "round": "2605",
            "step": 6,
            "start_time": "2018-11-26T11:49:58.74135953Z",
            "proposal": true,
            "proposal_block_parts_header": {
              "total": "1",
              "hash": "EBC8823EBCE831E7848D16E7EB3347BB2E67FB72"
            },
            "proposal_block_parts": "x",
            "proposal_pol_round": "2604",
            "proposal_pol": "xxxx",
            "prevotes": "xxxx",
            "precommits": "xxx_",
            "last_commit_round": "0",
            "last_commit": "xxxx",
            "catchup_commit_round": "2604",
            "catchup_commit": "xxxx"
          },
          "stats": {
            "last_vote_height": "1194",
            "votes": "1194",
            "last_block_part_height": "1194",
            "block_parts": "299"
          }
        }
      },
      {
        "node_address": "5569833e0b2031e7cd1a3ec42466132f1ee416cb@172.18.0.3:26656",
        "peer_state": {
          "round_state": {
            "height": "1194",
            "round": "2605",
            "step": 6,
            "start_time": "2018-11-26T11:49:58.71497759Z",
            "proposal": true,
            "proposal_block_parts_header": {
              "total": "1",
              "hash": "EBC8823EBCE831E7848D16E7EB3347BB2E67FB72"
            },
            "proposal_block_parts": "x",
            "proposal_pol_round": "2604",
            "proposal_pol": "____",
            "prevotes": "xxxx",
            "precommits": "xx_x",
            "last_commit_round": "0",
            "last_commit": "xxxx",
            "catchup_commit_round": "2604",
            "catchup_commit": "xxxx"
          },
          "stats": {
            "last_vote_height": "1194",
            "votes": "1194",
            "last_block_part_height": "1194",
            "block_parts": "299"
          }
        }
      }
    ]
```

**Anything else we need to know**:

**Comment by ebuchman** [comment]
> 0.16.0-c8a2bdf7

This is a very old, out-dated, and unsupported version of the software. We encourage you to upgrade.

That said, is it possible there is some non-determinism in your application? All instances of the application must compute identical results for the same sequence of transactions. Do they depend on anything like the current time, random numbers, iteration over a map, or any external RPC input? Any of those things could cause consensus failure.

**Comment by ebuchman** [comment]
Ah, you just have an old version of Tendermint installed, but from your repo it looks like you're using a reasonably up-to-date version: https://github.com/ixofoundation/ixo-cosmos/blob/master/Gopkg.toml#L41

**Comment by Nicolaas0411** [comment]
Ah, I think the docker image we are using might still be using the older version of tendermint. I will investigate and revert back. Thanks for looking at this.

**Comment by Nicolaas0411** [comment]
I have confirmed that we are using version 0.23.1. All our calls are deterministic. We have no external RPC input. The block information is identical on all the nodes, but they all commit 'n different app hash value. Do you suggest maybe upgrading to the latest tendermint version?

**Comment by melekes** [comment]
note: 

in the logs, there are three distinct rounds (160, 196, 195)
in dump_consensus_state, all rounds are the same

**Comment by Nicolaas0411** [comment]
Just found the issue. We have a "createProject" call that generates an account using "server.GenerateCoinKey()". This is non-deterministic, so it was the culprit. This was an oversight on our end. Thanks so much for the help guys.
