### ISSUE TITLE
Rename accum to ProposerPriority

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2915]
`accum` is not the most helpful of names, and AFAIK isn't really a common name vs something like priority. We also always get questions about why there are negative accums / what accum is. Can we rename it to something else? I propose `ProposerPriority`. This also helps resolve ambiguity, since the fee distribution logic within the sdk also relies on something named `accum`.

**Comment by ebuchman** [comment]
Donezo!
