### ISSUE TITLE
Remove BlockTimeIota and other Consensus Params from Config

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2920]
It should be a consensus parameter, not a locally configurable option

_Originally posted by @milosevic in https://github.com/tendermint/tendermint/pull/2878_

**Comment by ebuchman** [comment]
Actually, we probably want to remove most of the consensus timeout params from the config since according to the spec now there are formal relations between them. Instead, we should only expose a couple knobs, and derive all the other values from those.

Namely, we have

```
timeoutPropose(r)>2∆+timeoutPrecommit(r−1)
timeoutPrevote(r)>2∆
timeoutPrecommit(r)> 2∆
```

where delta is the partial synchrony bound.
this delta should be increasing with each round (since the bound is actually unknown) according to some other delta. this latter delta can be part of the config.

**Comment by ebuchman** [comment]
We should be able to reduce the number of consensus timeout params in the config down to roughly the following three:

- initial proposer timeout
- round delta
- timeout commit

**Comment by ebuchman** [comment]
Bumping this back a milestone so v0.29 can ship with just the protocol breaking stuff

**Comment by ValarDragon** [comment]
I'm in favor of of removing `time_iota_ms` as a param, and hardcoding it as `1ms` in the code. (As its only role AFAIK is to ensure monotonicity of proposed block time)


I think removing the parameter would be a breaking change to the encoding of the `BlockParams`, but is removing the usage of `time_iota_ms` in the code a breaking change? (And then just leaving the parameter as deadcode?)

If making `time_iota_ms` unused, and instead hardcoded to 1 ms is fine, I'm happy to submit a PR for it.

**Comment by cmwaters** [comment]
Yeah I am for this, especially as it can cause problems if set incorrectly and doesn't really need to be there. 

I guess regardless of whether this gets fixed now or not, it will most likely be removed anyway in the next major release (especially if we implement proposer based timestamps). So I don't think it's too much of a problem if you don't submit a PR, but I see it's only going to be a couple of lines, so if you do then I'm happy to try get it in to 0.34.1

**Comment by marbar3778** [comment]
BlockTimeIota was removed recently, we need to remove the config params in favor of a more global approach (#5911)

**Comment by williambanfield** [comment]
I'd like to close this in favor of 
https://github.com/tendermint/tendermint/issues/2920 since `BlockTimeIota` was removed and this issue is therefore a bit unfocused.

**Comment by williambanfield** [comment]
Closing, in favor of the related issues for more focused discussions of each.
