### ISSUE TITLE
Change interprocess communication in ABCI from sockets to pipes

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2928]
When Tendermint is ran out of process, the communication goes over sockets. This is a costly overhead, since sockets are running the full TCP protocol. This make sense if the consensus engine and the state machine were running on different physical machines. However I don't see a genuine use case for that / a need to optimize the bulk of software for that, primarily because that further increases the latency of IPC and decreases throughput.

Instead I propose we use Unix named pipes. These are still first in first out, so messages are delivered in order as we would want. Due to the removal of the entire TCP stack, named pipes are empirically faster. See figures 1 and 2 of this study: http://pages.cs.wisc.edu/~adityav/Evaluation_of_Inter_Process_Communication_Mechanisms.pdf

From figure 1, the latency difference for IPC between sockets and pipes is substantial. It appears to me that at small message sizes (less than 1kb), the average pipe latency is 25% that of the socket latency. At the maximum TCP packet size, 64kb, the average pipe latency is 73% that of the socket latency. The former has large performance implications for IPC of small messages (our current deliver txs one by one model), and the latter indicates there are still significant performance gains even if we switched to delivering a full block at once.

Figure 2 shows that there is always a higher throughput for pipes than sockets as well. This is quite significant at small message sizes, (Appears to be a roughly 2x improvement?) and at large message sizes (512kb) the througput improvement is significant again. (roughly 2x as well)

**Comment by ebuchman** [comment]
Interesting idea. How much different would this be from using unix sockets (ie. `unix://abci.sock`), which we already support? We've done benchmarks that show using unix sockets is indeed much faster, and is probably the recommended approach when running on a single machine.

**Comment by ValarDragon** [comment]
Didn't we realize we support unix sockets! The performance of those is fairly close to named pipes as I understand, with pipes still being a bit faster. 

I've had trouble finding solid benchmarks for named pipes vs unix domain sockets, the best I've seen is: https://wiki.openlighting.org/index.php/Pipe_vs_Unix_Socket_Performance which states a 12-15% improvement for named pipes under large message sizes. However these benchmarks are unnuanced, they don't specify the improvement for small message sizes or latency vs throughput. It may be worth trying to setup pipes and benchmarking them.

**Comment by erikgrinaker** [comment]
It is not clear that pipes have any significant performance advantage over UNIX sockets ([random benchmark](https://stackoverflow.com/questions/1235958/ipc-performance-named-pipe-vs-socket/54164058#54164058) shows they're actually slower). Pipes are also unidirectional, so we would have to use a pair of them for requests and responses, complicating the implementation.

My take is that IPC overhead is likely to be a fairly small contributor to ABCI latency in any case (request processing time is likely many orders of magnitude larger), and not worth the effort unless it's demonstrated to be significant.
