### ISSUE TITLE
Write tests for Validator.ProposerPriority

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2942]
A couple recent bugs were found in proposer selection that indicate insufficient testing. See https://github.com/tendermint/tendermint/issues/2718 for more.

#2785 and #2941 fix these bugs, but they don't include sufficient testing to prove it.

We should write more complete tests for the proposer selection across validator set changes. Likely need to reside in the `state` package.

Related: https://github.com/tendermint/tendermint/issues/1555

**Comment by ebuchman** [comment]
@Liamsi do you think we can close this based on the couple PRs worth of tests you wrote and what's additionally coming in #3049  ?

**Comment by Liamsi** [comment]
Yes, I think we can close this when #3049 is merged.

**Comment by ebuchman** [comment]
Lots more tests included in https://github.com/tendermint/tendermint/pull/3049

Could always write more, but seems we can close this for now.
