### ISSUE TITLE
Responses to "subscribe" sent over WebSocket don't conform to RPC 2.0 specification

### ISSUE THREAD

**Issue by clymbon** [tendermint/tendermint#2949]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.25.0-0c9c3292

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release):

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

- **Install tools**:
- **Others**:

**What happened**:

The responses to "subscribe" over websocket are not as expected.

I believe that they are not in conformance with the RPC 2.0 spec.  (I could be wrong about that.)

When the following "subscribe" message is sent over the websocket:

{"jsonrpc":"2.0","method":"subscribe","id":"1","params":["tm.event = 'NewBlock'"]} I get this response:

I get the following response:

{
  "jsonrpc": "2.0",
  "id": "1",
  "result": {}
}

This is as expected, indicating that the message was received and processed without error.  In the above, the "id" value is 1, indicating this is the first request sent.  (I send it immediately after connecting the socket.)

Subsequently, whenever a new block is created, I get a message like this:

{"jsonrpc":"2.0","id":"1#event","result":{"query":"tm.event = 'NewBlock'","data":{"type":"tendermint/event/NewBlock","value":{"block":  ..... (block contents deleted)

I believe this is NOT in accordance with the JSON RPC 2.0 spec.  The id value is set to "1#event', which chokes the javascript RPC library I'm using.  (https://github.com/jershell/simple-jsonrpc-js)

I think I get the idea behind this - sending the events responding to the subscription request with an id value that can be correlated back to the original request.  But I don't think this is conformant.  The spec says the ID value has to be identical to the request, and that a notification should not contain an ID value.

I was able to work around this by hacking the siimple-jsonrpc-js code to look for responses with id's ending in #event, and convert them into notifications.

Maybe this is how RPC 2.0 is supposed to work?  If so, I'm not seeing that in the spec, and the library I'm using doesn't recognize it.

I do see a related bug request #1099 

**What you expected to happen**:

The events resulting from a subscription request should be sent as NOTIFICATIONs.

**Have you tried the latest version**: yes/no

No.  Latest now appears to be 0.26.4, and I see in the comments that a fix was made to accept integer IDs (I also ran into that one, so that's great.)  I will try to download latest and test against it, but I don't see anything in change log that indicates this has been fixed.

**How to reproduce it** (as minimally and precisely as possible):

Send any valid subscribe message over websocket and then dump out the responses that come back.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

See above.

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by melekes** [comment]
> I think I get the idea behind this - sending the events responding to the subscription request with an id value that can be correlated back to the original request. But I don't think this is conformant. The spec says the ID value has to be identical to the request, and that a notification should not contain an ID value.

Does it mean that subsequent messages (e.g. NewBlock) should not have the ID field at all?

Should be an easy fix.

**Comment by melekes** [comment]
> I'm not sure whether conformance with the JSON RPC 2.0 standard is more important than not breaking existing code

conformance is more important

do you wanna help us with this?

**Comment by clymbon** [comment]
I'm willing to help, but I'm not a Go programmer.  I can make design suggestions, but don't feel qualified to write Go code.  I found where the "#event" responses are sent, in core/events.go, but... It's just another language, but the code is not trivial.  At some point I may be able to invest the time to properly learn Go, set up the programming environment, etc., but right now I would be better qualified to work on the javascript client side of this interface, e.g. https://github.com/mappum/js-tendermint or on java or c or c++ code.

My suggestion would be to create another version of the "subscribe" method call, that includes a callback method name.  Whenever a matching event occurs, tendermint core would send a "request" to that JSON RPC 2.0 method on the client, containing the event data.  Should be possible to detect whether "subscribe" is being called the current way, or the new way, and respond appropriately.  That way existing code won't break, and the old version of "subscribe" can be deprecated over time.

**Comment by melekes** [comment]
See https://github.com/tendermint/tendermint/blob/44a3fbf109b69780b278d36ec62b4552d8b4d36a/rpc/lib/client/ws_client.go#L495-L510

**Comment by clymbon** [comment]
Has this been tested against clients using other JSON RPC 2.0 implementations?   For example, a javascript client using a javascript JSON RPC 2.0 implementation?

Thanks,

Duncan

**Comment by melekes** [comment]
> Has this been tested against clients using other JSON RPC 2.0 implementations?   For example, a javascript client using a javascript JSON RPC 2.0 implementation?

What do you mean by "this"?

**Comment by tessr** [comment]
@melekes what do we need to do to close this issue? I see you reopened it but I'm not sure what the outstanding work is

**Comment by melekes** [comment]
This still needs to be fixed:

> I think I get the idea behind this - sending the events responding to the subscription request with an id value that can be correlated back to the original request. But I don't think this is conformant. The spec says the ID value has to be identical to the request, and that a notification should not contain an ID value.

https://github.com/tendermint/tendermint/blob/8aa47c7da5b854a69f367f316a31c03d2fc1e942/light/rpc/client.go#L524
is not conforming to the specification.

**Comment by tessr** [comment]
Cool, thanks for the summary.

**Comment by AlexTroshkin** [comment]
@melekes, @tessr 

Ideally this should be similar to the pub sub implementation in geth

https://geth.ethereum.org/docs/rpc/pubsub

The bottom line is that the client sends a request to the server, which in turn returns the identifier of the created subscription (in our case, for example, it can be "query"). After the client has received the identifier, the server can send events to the client using notifications and by including the identifier inside the payload.

How to send the identifier and whether to send it at all are the details. For example, when subscribing, a client can indicate the name of the method on which he will wait for notifications from the server, then the subscription identifier is not needed in principle.

Interaction via server side notification instead of returning multiple responses with the same ID will fully comply with the JSON-RPC specification.

Today I wanted to start developing an explorer (like a big dipper) for a private network, but I ran into the problem that not a single JSON-RPC library in different languages ​​can correctly interact with the subscription (except for a certain client written in go inside this repository) which was very sad

**Comment by creachadair** [comment]
I'm planning to fix this as part of the implementation of [ADR 075](../blob/master/docs/architecture/adr-075-rpc-subscription.md). Updates will be tracked on #7157.
