### ISSUE TITLE
Don't start up if validator set is empty

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2951]
We allow the validator set to be empty in the genesis, because it can be set by the app in InitChain.

However, if both the genesis has empty validators and InitChain returns no validators, Tendermint still tries to startup, and then panics trying to get the proposer from an empty validator set.

Instead, if the validator set is still empty after InitChain, Tendermint should log a helpful error and exit.

**Comment by ebuchman** [comment]
Thanks @leo-xinwang !

**Comment by jjhesk** [comment]
i have started with this error
`ERROR: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain`
any help for this?

**Comment by melekes** [comment]
you have to either provide validators in genesis.json OR in your ABCI application via `InitChain`. Did you execute `tendermint init`?

**Comment by jjhesk** [comment]
i see. Let me try that again.
