### ISSUE TITLE
Cross-compile error for Android arm(32bit)

### ISSUE THREAD

**Issue by DanielTelemint** [tendermint/tendermint#2952]
**Tendermint version** : v0.26.4

**What happened**: 
error occurred while cross-compiling for android arm(32bit) with Cosmos-sdk v0.27.0

**What you expected to happen**:
Cross-compile success.

**Have you tried the latest version**: yes

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
 github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/types
../../../../vendor/github.com/tendermint/tendermint/types/validator_set.go:203:5: constant 8198552921648689607 overflows int

**Comment by Liamsi** [comment]
My bad. I didn't think about 32-bit platforms in #2785. Will fix asap!

**Comment by melekes** [comment]
You may find https://github.com/tendermint/tendermint/issues/2103 interesting

**Comment by melekes** [comment]
PR with a fix/feature was merged to develop. Will be shipped with 0.27.0 or 0.27.1 release (check the changelog).
