### ISSUE TITLE
Deadlock in addrbook

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2955]
Seeds halted on gaia-9002 testnet. Stopped responding to RPC and no new log messages. SIGABRT resulted in a large dump, with many routines blocked on accessing the AddrBook, suggesting a deadlock.

It also included this gem:

```
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: goroutine 2056 [runnable]:
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: math/rand.(*Rand).Int31(0xc422610690, 0x6ce96401)
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: /usr/local/go/src/math/rand/rand.go:96 +0x47
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: math/rand.(*Rand).Int31n(0xc422610690, 0x40, 0xc400000001)
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: /usr/local/go/src/math/rand/rand.go:128 +0xb4
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: math/rand.(*Rand).Intn(0xc422610690, 0x40, 0x1)
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: /usr/local/go/src/math/rand/rand.go:169 +0x45
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/common.(*Rand).Intn(0xc420b20370, 0x40, 0x1)
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: /home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/libs/common/random.go:276 +0x49
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/p2p/pex.(*addrBook).GetSelectionWithBias(0xc4200ca700, 0x1e, 0x0, 0x0, 0x0)
Nov 30 22:21:27 ip-10-0-0-195 gaiad[3406]: /home/greg/go/src/github.com/cosmos/cosmos-sdk/vendor/github.com/tendermint/tendermint/p2p/pex/addrbook.go:412 +0x2b9
```

Specifically `/usr/local/go/src/math/rand/rand.go:169 +0x45` is a panic! it doesn’t seem to be getting caught, but because we’re not using defer, the mtx in our libs/common/rand isn’t being released, locking up the addrbook

The core of the problem is `sdk/vendor/github.com/tendermint/tendermint/p2p/pex/addrbook.go:412 +0x2b9`, where we must be passing a 0, which is invalid for the rand methods. for some reason the `len(a.bucketsOld)` is 0 there, and we’ll need to prevent that.

**Comment by ebuchman** [comment]
I think an older version of Go was being used, so these lines don't correspond to a panic, which makes sense because afaict there's no way we're passing a 0 or negative into the rand function.

Also in other stack dumps, the Rand calls weren't present. So looks like it's something deeper.

**Comment by melekes** [comment]
[sigabrt1.txt](https://github.com/tendermint/tendermint/files/2672878/sigabrt1.txt)

some interesting bits from the goroutines dump. 3 locked mutexes: cs state, cs reactor and addrbook.

**Comment by ebuchman** [comment]
Jae points out that there's only one `runnable` routine, its the GetSelectionWithBias, and it seems to be stuck in a hot loop. The call to rand is just a coincidence, but it's a call in that hot loop, so not unlikely that the sigabrt catches it. If we never exit that loop, then we'll hold the lock for ever.

That said, here's another sigabrt that doesnt seem to have the same issue, but is similarly deadlocked:

[sigabrt3.txt](https://github.com/tendermint/tendermint/files/2683186/sigabrt3.txt)

**Comment by jaekwon** [comment]
Might be related to https://github.com/tendermint/tendermint/issues/2721#issuecomment-447635071, esp if Danil's answer is an affirmative.  Where'd you get that sigabrt3.txt?

**Comment by ebuchman** [comment]
> Where'd you get that sigabrt3.txt?

From the same seed node as the first one. Just restarted the node and waited for it to seize up again.
