### ISSUE TITLE
Remove usage of rand.Rand

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2956]
Currently all randomness happening in tendermint is going through cmn.Rand. This is done under the guise of cmn.Rand being "thread-safe randomness". cmn.Rand is just a global random instance, but with a mutex lock on every single call.

We should instead have each of these distinct threads getting its own randomness instance. This avoids the mutex lock, and more fundamentally is getting its randomness via that thread owning its randomness instance. Having each thread have its own randomness is inherently safer (any issue one thread has won't cascade into other threads), and is much faster due to avoiding contention on that mutex. 

We _don't_ need a global randomness instance to seed our per-thread PRG's. This is because as stated in the [godoc](https://golang.org/pkg/math/rand/), the default randomness instance is thread safe.

**Comment by marbar3778** [comment]
I believe this "proposal accepted"

**Comment by usamahamid** [comment]
@marbar3778, Is this still valid/open? Is there any other arguments for retaining the Mutex Lock? 
I noticed you are refactoring the whole of cmn package (to tendermint), will issue be fixed as part of that?

Just asking since I think this would be good issue to get started.

**Comment by marbar3778** [comment]
I recently removed the `common` pkg so this issue would now relate to the `rand` pkg.  This issue is still valid and available. It was not fixed in the removal of the common pkg.

**Comment by melekes** [comment]
Some work was done in https://github.com/tendermint/tendermint/pull/4252 (removing grand)

**Comment by liamsi** [comment]
Although this is only used in tests etc, this library now often called tmrand.Rand instead of cmn.Rand really should just be deleted. If I have some time during the weekends, I'll try to replace it with "math/rand" or a super lightweight wrapper around math/rand.
