### ISSUE TITLE
consensus failure while benchmarking kvstore app (gRPC, no empty blocks)

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2965]
no empty blocks, skip_timeout_commit, cleveldb, gRPC server/client
tendermint 0.27.0-d9a1aad5

E[4126-12-04|14:14:41.953] CONSENSUS FAILURE!!!                         module=consensus err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 68 [running]:\nruntime/debug.Stack(0xc0034283c0, 0xd363c0, 0x19284d0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0xa7\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine.func2(0xc000888380, 0xfab6d0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:576 +0x57\npanic(0xd363c0, 0x19284d0)\n\t/usr/local/go/src/runtime/panic.go:513 +0x1b9\ngithub.com/tendermint/tendermint/types.NewResultFromResponse(...)\n\t/root/go/src/github.com/tendermint/tendermint/types/results.go:44\ngithub.com/tendermint/tendermint/types.NewResults(0xc002da0000, 0x183a, 0x183a, 0xc003918dc0, 0xc001d6c2b8, 0xc0027dc2d0)\n\t/root/go/src/github.com/tendermint/tendermint/types/results.go:36 +0x6b\ngithub.com/tendermint/tendermint/state.(*ABCIResponses).ResultsHash(0xc004013710, 0xc0027dc5a0, 0xb602ec, 0xc0034285c8)\n\t/root/go/src/github.com/tendermint/tendermint/state/store.go:133 +0x40\ngithub.com/tendermint/tendermint/state.updateState(0x8, 0x1, 0xc00095286a, 0x6, 0xc000877640, 0x11, 0xd, 0x5a57, 0xc0026f3840, 0x20, ...)\n\t/root/go/src/github.com/tendermint/tendermint/state/execution.go:469 +0x3c6\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000954380, 0x8, 0x1, 0xc00095286a, 0x6, 0xc000877640, 0x11, 0xd, 0x5a57, 0xc0026f3840, ...)\n\t/root/go/src/github.com/tendermint/tendermint/state/execution.go:125 +0x50b\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).finalizeCommit(0xc000888380, 0xe)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1290 +0xa8c\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryFinalizeCommit(0xc000888380, 0xe)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1221 +0x451\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit.func1(0xc000888380, 0x0, 0xe)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1167 +0x90\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).enterCommit(0xc000888380, 0xe, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1198 +0x6b8\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc000888380, 0xc0022117c0, 0x0, 0x0, 0x488edd, 0xc0014e7bc0, 0xc000a64100)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1622 +0xc03\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc000888380, 0xc0022117c0, 0x0, 0x0, 0x42f272, 0xc000000008, 0xc003429b80)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:1469 +0x59\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).handleMsg(0xc000888380, 0x10673a0, 0xc001d6c0d0, 0x0, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:650 +0x696\ngithub.com/tendermint/tendermint/consensus.(*ConsensusState).receiveRoutine(0xc000888380, 0x0)\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:611 +0x555\ncreated by github.com/tendermint/tendermint/consensus.(*ConsensusState).OnStart\n\t/root/go/src/github.com/tendermint/tendermint/consensus/state.go:300 +0x132\n"

**Comment by melekes** [comment]
Here is what's happening: we create an array `[]*DeliverTxResponse` with size == num txs https://github.com/tendermint/tendermint/blob/1bb7e31d63e72e1017ac68a61a498b22a137a028/state/execution.go#L219. By the time Tendermint calls https://github.com/tendermint/tendermint/blob/1bb7e31d63e72e1017ac68a61a498b22a137a028/state/execution.go#L125 some of the DeliverTxAsync calls are still pending (or thrown an error) https://github.com/tendermint/tendermint/blob/1bb7e31d63e72e1017ac68a61a498b22a137a028/state/execution.go#L258. Not sure if this is due to the error?? in gRPC client (or server)

**Comment by ebuchman** [comment]
> some of the DeliverTxAsync calls are still pending

This shouldn't be possible because EndBlock is called synchronously, which should result in all pending ABCI requests completing. Maybe there's a bug in the GRPC client/server that makes this not true? Is this non-deterministic?

**Comment by melekes** [comment]
> Maybe there's a bug in the GRPC client/server that makes this not true?

maybe

**Comment by erikgrinaker** [comment]
> This shouldn't be possible because EndBlock is called synchronously, which should result in all pending ABCI requests completing. Maybe there's a bug in the GRPC client/server that makes this not true?

This is the case. Sync ABCI calls are not guaranteed to block until pending async calls have completed, at least this is how the gRPC client behaves. See #5548.
