### ISSUE TITLE
p2p: file descriptor leaks

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2967]
Running `lsof -i` on seed and public validator nodes from gaia-9002 shows lots of connections left in `CLOSE_WAIT` state, which suggests that connections aren't being closed properly in Tendermint in some cases.

I'm also seeing net_info report 0 peers but according to the logs there's at least 1 connected peer - this is a known issue (https://github.com/tendermint/tendermint/issues/2332) but perhaps these things are related.

Also previously reported memory leak in seed nodes: https://github.com/tendermint/tendermint/issues/2821

**Comment by bennofs** [comment]
This might at least in part be caused by https://github.com/tendermint/tendermint/issues/2046, which (despite being closed) still happens in current gaiad. The problem is that `p.Stop` in `acceptPeers` does not close the connection if the peer is rejected (for example due to the max_inbound_peers limit being reached), because the peer wasn't started yet in that case (so `Stop` is a no-op and `OnStop` is not called)

**Comment by ebuchman** [comment]
Thank you very much for finding this!

**Comment by ebuchman** [comment]
I think you mean `acceptRoutine` but it seems you're absolutely right.

Looks like the simplest way to address this is to `close(p.Quit())` instead of `_ = p.Stop()` in the `acceptRoutine`. Then the connection should be cleaned up by the go-routine started in `wrapPeer` in the `transport.go`, which receives on the Quit channel.

I'm not thrilled with the idea of closing the Quit channel from outside the base service, since technically it could lead to misuse, ie. if the service is somehow later started and then stopped it will panic due to closing a closed channel. That said, since we have a go-routine now blocking on the channel, if we never close the channel, then that go-routine will never exit. So we have no choice but to get that Quit channel closed.

Other options would be:
- Start and then immediately Stop the peer so it will be cleaned up
  - This seems a bit silly
- Modify BaseService to allow Stop to execute even if we never started
  - This would change the BaseService guarantees - would rather not modify this primitive
- Extend BaseService with eg. `Close()` which effectively runs Stop without the service needing to have been started
  - Possibly the cleanest option? Ie. if you know your BaseService might need to be cleaned up before it's even started, you use a CloseService instead which exposes `Close()`

Thoughts?

**Comment by ebuchman** [comment]
Should be fixed in #3150. See potential follow up in https://github.com/tendermint/tendermint/issues/3183
