### ISSUE TITLE
TxSearch returning duplicate transactions.

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#2970]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.23.1

**ABCI app** (name for built-in, URL for self-written if it's publicly available): not publicly available.

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu
- **Install tools**:
- **Others**:

**What happened**: My transactions have a `Timestamp` field that I use to query them within a given period of time. For instance, the blockchain has currently 250 txs and I want to query them all and return to the client, so I call `txSearch` with the query, `page = 1` and `perPage = 100` and it returns 100 txs, then I call it again to get more 100 txs with the same query, `page = 2` and `perPage = 100` and I get more 100 txs, then I do the same with `page=3` and get the 50 last txs.
However, I noticed that the first query works fine, it returns unique transactions but the second query returns a couple of transactions that were on the first query even though I changed the `page` to `2` and that's the problem I am trying to understand.

That's how I set the timestamp: 
`transaction.Timestamp = time.Now().UTC().UnixNano() / int64(time.Millisecond)`  

That's a query example: `rapidTx.UserID='<USER_ID>' AND rapidTx.Timestamp>=1541289600000 AND rapidTx.Timestamp<=1543967999999`

If I query by other field, for instance: 
`rapidTx.UserID='<USER_ID>' AND rapidTx.Manifest=123`

it works perfectly. Not sure what is happening with the timestamp query.

**What you expected to happen**: I was expeting the query with `page=2` would not return the same transactions as the `page=1`

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible): It's not publicly available, not sure how to allow you guys to test it :/ 

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: There's no error on the console.

**Config (you can paste only the changes you've made)**:
`IndexTags:    "rapidTx.ParcelID,rapidTx.ManifestID,rapidTx.UserID,rapidTx.Timestamp",`

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**: Sorry if it's not clear what I did/want to do, let me know if you guys need any further info.

If there's any other way to query transactions by date, I am happy to change the code as long as the dates are UTC.

**Comment by melekes** [comment]
It seems to me we should be able to fix this by doing https://github.com/tendermint/tendermint/issues/2906

**Comment by melekes** [comment]
Are all of the txs from the same height? Or many heights? How many txs are in a block usually?

**Comment by gianfelipe93** [comment]
@melekes I solved it by upgrading to the version `0.26.4`

I am not sure the answer to your questions, how can I check the info you asked?

**Comment by melekes** [comment]
> @melekes I solved it by upgrading to the version 0.26.4

ok, great
