### ISSUE TITLE
Feature request: support MongoDB

### ISSUE THREAD

**Issue by kunaldhariwal** [tendermint/tendermint#2973]
I have been searching everywhere the way to use mongoDB instead of LevelDB. 
I have found no documentation yet, also similar issue was raised in 2017, been 1 year and have not found any help over it.
If there's anything you can do then please let me know?

Have posted same thing on stackoverflow but nobody cares to answer

**Comment by melekes** [comment]
It should be easy to write a MongoDB adapter for Tendermint. See https://github.com/tendermint/tendermint/issues/803.

1. create a new file libs/db/mongo_db.go
2. 🙏 write amazing code 🙏 Example: https://github.com/tendermint/tendermint/blob/develop/libs/db/mem_db.go
3. add the new backend MongoDBBackendStr to db.go
4. change the local tendermint configuration to use the new backend db_backend = "mongodb"
5. send us a PR :)

You can also take a look at the BoigchainDB https://blog.bigchaindb.com/bigchaindb-2-0-is-byzantine-fault-tolerant-5ffdac96bc44. They are using MongoDB as a primary storage afaik.

---
Our chat: https://riot.im/app/#/room/#tendermint:matrix.org
Forum: https://forum.cosmos.network/c/tendermint

**Comment by srmo** [comment]
For reference some older stuff: https://github.com/tendermint/tendermint/issues/282 and from there https://github.com/bigchaindb/bigchaindb/issues/1845

**Comment by gouthamve** [comment]
Hi  @melekes, I'm helping @kunaldhariwal implement the following interface using Mongo: https://github.com/tendermint/tendermint/blob/master/libs/db/types.go#L4-L55

I see some problems with the current interface, where the operations can fail and currently there is no way to return an error. Should I make the functions return an error? I am not too knowledgeable about the codebase to answer how Tendermint should handle errors returned by `DB` operations.

**Comment by melekes** [comment]
Right now we just panic if the DB driver returns an error. I think that's because embedded DBs usually work pretty well. In case of external DBs, maybe we should retry a few times and only then panic OR retry indefinitely.

**Comment by melekes** [comment]
We've decided to limit the database options in Tendermint for the following reasons:

1) decrease the amount of code we need to support
2) focus on providing a default database, which is stable, sufficiently performant for most use-cases and covered by tests

That said, you can still use MongoDB with Tendermint by passing a different DBProvider and implementing a wrapper for MongoDB, which satisfies the DB interface.
