### ISSUE TITLE
mempool: convert added good transaction log message to debug mode

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2979]
Here: https://github.com/tendermint/tendermint/blob/master/mempool/mempool.go#L372, we make a log message for every time a tx is added to the mempool. Since this is in Info mode, it will get logged. This is a lot of IO which is causing efficiency decreases (tm-bench speed increases with logging disabled is evidence of this).

I think we should instead make it debug mode. We can perhaps make cumulative log messages, like added x txs in the last y minutes, which decreases overall IO.

**Comment by melekes** [comment]
I disagree. We should control such things via log_level (default: `main:info,state:info,*:error`). Note in 0.27 this msg won't be logged. There was an issue https://github.com/tendermint/tendermint/issues/2868 causing the logger to log all info messages, but it's fixed now.

**Comment by ValarDragon** [comment]
Totally agreed with it being in log_level, but its not clear to me why you would use this information unless you were debugging. Prometheus is for getting general metrics.

**Comment by melekes** [comment]
Yeah, I am not sure where to draw the line between info and debug messages. My current intuition is 

info - for major events (e.g. for mempool - transaction coming in, tx removed, txs reaped)
debug - minor / technical details (e.g. for mempool - cache msgs)

**Comment by ebuchman** [comment]
I think that intuition sounds right. Let's leave it as is. Folks can disable it in the config.
