### ISSUE TITLE
Remove PrivValidator.GetAddress

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#2981]
Remove `PrivValidator.GetAddress` from `PrivValidator` interface. 
Rationale: In some places we do `PrivValidator.GetPublicKey` and then `PrivValidator.GetAddress` which is just a wrapper around the former for convenience. In the remote signer / kms case this causes another (unnecessary) network request. Removing `GetAddress` makes this more obvious. 

ref: https://github.com/tendermint/tendermint/pull/2948#discussion_r239737037

**Comment by ebuchman** [comment]
Done in #2948
