### ISSUE TITLE
Can't add new validator node until hard reset data

### ISSUE THREAD

**Issue by chanwitkepha** [tendermint/tendermint#2982]
Dear All 

I'm newbie about Tendermint and try to learn about it. So I need some help.

Today I have created  4 validator node. I tried adding node 5 as new validator node 

https://tendermint.com/docs/tendermint-core/using-tendermint.html#adding-a-validator

Now the problem is that new node cannot john with another validator nodes and output some error like that.

Stop error peer {pean {MConn} {192.168.10.32:26656} 2288ddb66a24fcd90a64b99a2fac6b44fa210328 out} "err =" BlockchainReactor validation error: Invalid commit - wrong set size: 5 vs 4 "

Now I used the command. unsafe_reset_all (Yes, It's remove all the data and WAL, reset this node's validator to genesis state) on every node. 

And then execute the command "tendermint node --proxy_app = kvstore --p2p.persistent_peers ......" now all 5 node can working together as validator node.

Please advise me How can I add new validator node without unsafe_reset_all. Thank you very much.

Sorry if my English Language is not good.

**Comment by ebuchman** [comment]
Using the `kvstore`, you can't. Using the `persistent_kvstore`, you can, by sending a transaction like: `val:<hex pubkey>/<int power>`, ie. https://github.com/tendermint/tendermint/blob/master/abci/example/kvstore/persistent_kvstore.go#L132

Sorry this part isn't well documented, but adding new validators is application specific, so the app has to explicitly allow for it. `kvstore` does not allow, but `persistent_kvstore` does. Does this make sense?

**Comment by chanwitkepha** [comment]
> Using the `kvstore`, you can't. Using the `persistent_kvstore`, you can, by sending a transaction like: `val:<hex pubkey>/<int power>`, ie. https://github.com/tendermint/tendermint/blob/master/abci/example/kvstore/persistent_kvstore.go#L132
> 
> Sorry this part isn't well documented, but adding new validators is application specific, so the app has to explicitly allow for it. `kvstore` does not allow, but `persistent_kvstore` does. Does this make sense?

Thank you very much for your answer.

**Comment by chanwitkepha** [comment]
I try persistent_kvstore on both 2 node by start tendermind node like this

tendermint node --home /home/devteam/.tendermint --proxy_app=persistent_kvstore --p2p.persistent_peers 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48@192.168.10.30:26656,8e721e777b65fd19ab6a2e89c30129592fc7031b@192.168.10.31:26656

But it's still show same error.

E[8126-12-08|12:31:02.117] Error in validation                          module=blockchain err="Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:02.117] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.10.30:26656} 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48 out}" err="BlockchainReactor validation error: Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:06.301] Error in validation                          module=blockchain err="Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:06.301] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.10.30:26656} 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48 out}" err="BlockchainReactor validation error: Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:07.157] Error in validation                          module=blockchain err="Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:07.157] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.10.30:26656} 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48 out}" err="BlockchainReactor validation error: Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:10.427] Error in validation                          module=blockchain err="Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:10.427] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.10.30:26656} 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48 out}" err="BlockchainReactor validation error: Invalid commit -- wrong set size: 2 vs 1"
E[8126-12-08|12:31:10.428] MConnection flush failed                     module=p2p peer=0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48@0.0.0.0:26656 err="write tcp 192.168.10.31:35132->192.168.10.30:26656: use of closed network connection"
E[8126-12-08|12:31:10.740] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.10.30:26656} 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48 out}" err="error with peer 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48: invalid peer"
E[8126-12-08|12:31:11.046] Stopping peer for error                      module=p2p peer="Peer{MConn{192.168.10.30:26656} 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48 out}" err="error with peer 0b9072fc20b97d3f39fe72b49119e4eb8d1e9d48: invalid peer"

**Comment by ebuchman** [comment]
> wrong set size: 2 vs 1"

Are you starting both nodes from a fresh/empty state using the same identical genesis file?
