### ISSUE TITLE
Limit proposer voting power

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2985]
This is part of the proposer election problems. We currently treat accum as an int64 (not uint as it needs negatives). Due to not wanting to make accum a big Int, and there being no Int128s in golang :(, we have to ensure that accum won't overflow.

The current semantics of validator power allows a validator to have power up to `2**63 - 1` (AFAIK). This will trivially break the proposer election process (and Tendermint block validity calculations?). The issue is there is this "accum" stat, and every time you increment by `2**63 - 1` it will overflow. Even with averaging, the maximum deviation would be some factor multiplied by `2**63 - 1`. I haven't done the math to see what this maximum deviation is, mainly because I don't know if were going to change the proposer election process significantly, or just keep modifying the current one. So we don't know the maximum validator power currently allowed by proposer election, but I anticipate it being significantly lower than the maximum due to ensuring block validity.

For block validity, we at minimum require the sum of all validator powers to not overflow. I think it is best to have a uniform validator power maximum, because otherwise you could have some validators be purely unable to get more stake than another one. Thus, the maximum maximum voting power per validator is `2**63 - 1 / num_validators`. (I guess depending on the implementation which I haven't spent awhile looking at, you could get away with only requiring counting powers up to the `2/3` bound to not overflow, but I think that will cause problems elsewhere, and I think it needs to be lower anyway due to accum)

_Originally comments by @cwgoes, @ValarDragon in https://github.com/tendermint/tendermint/pull/2785#issuecomment-440357821_

/cc @cwgoes @liamsi @ebuchman @milosevic

**Comment by Liamsi** [comment]
The max allowed voting power is now limited by: https://github.com/tendermint/tendermint/blob/9c236ffd6c56add84f3c17930ae75c26c68d61ec/types/validator_set.go#L15-L22
(not `2**63 - 1`) but as you said it might happen a single validator with let's say `MaxTotalVotingPower` it wouldn't allow other validators to join. So there still might be some concerns.

**Comment by ebuchman** [comment]
We can return errors for this on Tendermint side, but really it has to be enforced on the application side too, so I question if it's worth having any limit on the Tendermint side here. We can check for overflow and return the error then (note this is an error in executing the block, which we can't recover from), and otherwise document that apps must be careful not to have the sum of their validators' voting power overflow.

If that's the case, then the only additional thing to do here is improve the documentation.

**Comment by ebuchman** [comment]
In #3157 the bound was further reduced to `math.MaxInt64 / 8`. See follow up in https://github.com/tendermint/tendermint/issues/3167
