### ISSUE TITLE
sync docs & tmint for nil/counter apps

### ISSUE THREAD

**Issue by ChatchaiCBV** [tendermint/tendermint#2986]
Hello! 

I tried to follow the instruction from [this page](https://tendermint.com/docs/tendermint-core/using-tendermint.html#run) by using other in-process apps such as 'nil' or 'counter' but it shows errors as follows

![image](https://user-images.githubusercontent.com/2574960/49683090-d3aa0f00-faf1-11e8-8cb4-60b49584b0a5.png)

Please help advice. Thank you.

**Comment by melekes** [comment]
Thanks!

It's `nilapp`, not `nil`.

https://github.com/tendermint/tendermint/blob/03e86753a2245d3ca96a7665563c3d3196b96205/proxy/client.go#L65-L77

we should either fix the docs OR add `counter` case and rename `nilapp` to `nil`.

**Comment by ChatchaiCBV** [comment]
Ok. Thank you for your support.

**Comment by zramsay** [comment]
#2988
