### ISSUE TITLE
Error while adding new validators 

### ISSUE THREAD

**Issue by altomanscott** [tendermint/tendermint#2987]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
tendermint version: 0.22.8-40d6dc2e

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
http://192.168.56.107:26657/

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.1
- **Install tools**: bigchaindb2.0.0b9
- **Others**:

**What happened**:
I would like to add a new validator, I have followed the instructions that I have to modify the **genesis.json** file and copy the file to the new machine. I have edited it and copy to new machine, and I have also modified the **config.toml** on both machines, then I start the tendermint nodes on both machine as well as bigchaindb, then I found out the the **genesis.json** seems on getting any changes. what I see on bigchaindb, it stills show the old **genesis.json** configuration on both machine. Therefore, the two nodes are not successfully connected.

**What you expected to happen**:
I would like the genesis.json file on both machine to be modified, so that new validator can be added to the network

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: here are some chunks of the log
>I[12-04|14:00:56.408] HTTPRestRPC                                  module=rpc-server method=/net_info args=[] returns="[<*core_types.ResultNetInfo Value> <error Value>]"
I[12-04|14:00:56.408] Served RPC HTTP response                     module=rpc-server method=GET url=/net_info status=200 duration=0 remoteAddr=127.0.0.1:42908
I[12-04|14:01:14.600] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[12-04|14:01:14.601] No addresses to dial nor connected peers. Falling back to seeds module=p2p 
I[12-04|14:01:44.602] Ensure peers                                 module=p2p numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[12-04|14:01:44.602] No addresses to dial nor connected peers. Falling back to seeds module=p2p 
I[12-04|14:02:12.800] Ignoring inbound connection: error while adding peer module=p2p address=192.168.56.107:42640 err="Peer is on a different network. Got test-chain-5cG0xy, expected test-chain-LXmwk7"

**Config (you can paste only the changes you've made)**:
The changes in my **genesis.json**

```
 "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "XtpEn5FrEOV99ji/yVcFmKYm/e8i6vACaX9HkvK5TIA+"
      },
      "power": "10",
      "name": ""
    }
```
and the changes in **config.toml**

```
# Comma separated list of nodes to keep persistent connections to
persistent_peers = "6ce637869221c2a1eb04f32ced3b4ee008d918c@192.168.56.107:26656"

create_empty_blocks = false
```
**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**: I have tried several things, I have tried to delete the file in _./tendermint/data_ , by doing so I managed to add peers before but it doesn't seem to work this time and I don't know why. I have also tried to run `tendermint unsafe_reset_priv_validator` and `tendermint unsafe_reset_all` multiple times on different clones of my machines to test out, but all didn't work.

**Comment by altomanscott** [comment]
@xla @davebryson @paulrd @shapeshed Please help me, many thanks to all you guys right there, I am really stuck with it for a very long time, I have read lots of related threads and posts but none has helped me, I hope you guys could find out what I have done wrong.

**Comment by ebuchman** [comment]
Note the following log line:

> I[12-04|14:02:12.800] Ignoring inbound connection: error while adding peer module=p2p address=192.168.56.107:42640 err="Peer is on a different network. Got test-chain-5cG0xy, expected test-chain-LXmwk7"

It looks like you're trying to connect peers with different chain-ids. All peers must have the same chain-id set in the genesis file.

If the chain has already been running, modifying the genesis file won't change anything. The genesis file is only relevant when the height of the chain is 0. If the chain is at a height greater than 0 and you want changes in the genesis file to take effect, you have to restart the chain by doing `unsafe_reset_all`. 

To add validators to a chain that's already live, you need to look at the specific documentation for the app you're using, in this case, BigChainDB. It's up to the app to determine how new validators are added - Tendermint just follows along. Tendermint only knows about the initial validator set in the genesis.json file. All other validator set changes are handled by the app. You'll have to review the BigChainDB documentation to see how this is done. You may need to upgrade to the latest version of BigChainDB.
