### ISSUE TITLE
Handle pre-existing data

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#299]
There should be some warning message when ~/.tendermint/data exists from some prior setup, (e.g. state was persisted and exists), it doesn't match ~/.tendermint/genesis.json . e.g.  we should  save the contents of genesis.json in the state, and print a warning if mismatched.

Likewise, `tendermint init` should do something about a preexisting data directory.

(original issue: https://github.com/tendermint/tendermint/issues/281)

**Comment by adrianbrink** [comment]
@ebuchman I think this has been implemented since we currently print this message:
```
➜  tendermint git:(feature/adrian-#469) tendermint init
NOTE[05-08|11:05:43] Already initialized                      module=main priv_validator=/Users/adrian/.tendermint/priv_validator.json
```

If I'm mistaken, please reopen the issue.
