### ISSUE TITLE
Internal error: Timed out waiting for tx to be included in a block

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#3001]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): .0.26.4

**ABCI app** (name for built-in, URL for self-written if it's publicly available): not publicly available.

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**: I had a network with 4 nodes working perfectly, then I destroyed it and started again with 5 nodes and now all transactions I send I get the same error: 
`broadcast_tx_commit: Response error: RPC error -32603 - Internal error: Timed out waiting for tx to be included in a block`

**What you expected to happen**: I expected the transaction to be sent successfully and replicate across the nodes.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):since it's not public I am not sure how to explain how to reproduce it.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: https://gist.github.com/gianfelipe93/2ad9743ff83479d6f0da7207b2b0ed0b

**Config (you can paste only the changes you've made)**:
```
        config.RPC.ListenAddress = rapidConfig.RPCListenAddress
	config.P2P.ListenAddress = rapidConfig.P2PListenAddress
	config.Consensus.CreateEmptyBlocks = rapidConfig.CreateEmptyBlocks
	config.PrivValidator = ConfigDir + "/priv_validator.json"
	config.NodeKey = ConfigDir + "/node_key.json"
	config.P2P.AddrBook = ConfigDir + "/addrbook.json"
	config.Genesis = ConfigDir + "/genesis.json"
	config.Mempool.WalPath = filepath.Join(ConfigDir+"/data", "mempool.wal")
	config.DBPath = ConfigDir + "/data"
	config.Consensus.WalPath = filepath.Join(ConfigDir+"/data", "cs.wal", "wal")
	config.Consensus.TimeoutCommit = 5000
	config.Consensus.TimeoutPrecommit = 5000
	config.Consensus.TimeoutPrecommitDelta = 5000
	config.Consensus.TimeoutPrevote = 5000
	config.Consensus.TimeoutPrevoteDelta = 5000
	config.Consensus.TimeoutPropose = 5000
	config.Consensus.TimeoutProposeDelta = 5000
```

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**
   - https://gist.github.com/gianfelipe93/e73d4de79939c4c5af18cf47db3b453d
   - https://gist.github.com/gianfelipe93/b265e46a0ce37d3f22f8ee48c7261f98
   - https://gist.github.com/gianfelipe93/92417ed7e351fb14769b1967a8f154a8

   Could not get from the other nodes because the log was too big. Hope that helps.

**Anything else we need to know**: I have tried to remove the timeouts I set and still it doesn't work. No code was changed when I included a new node, it was basically just the config that changed to connect the 5 nodes.

**Comment by gianfelipe93** [comment]
UPDATE:

I even tried to remove the fifth node and now the 4 nodes still don't connect. The addrbook appears to have the right addresses:
```
{
	"key": "2b026d244833c312270e9c0b",
	"addrs": [
		{
			"addr": {
				"id": "261b83d13ed8a7cf8864ca1c1a670eae39e32d24",
				"ip": "34.201.254.99",
				"port": 26656
			},
			"src": {
				"id": "c112115d19b967b02f1001e3b91e5182e24c6108",
				"ip": "0.0.0.0",
				"port": 26656
			},
			"attempts": 0,
			"last_attempt": "2018-12-11T05:47:16.101668877Z",
			"last_success": "0001-01-01T00:00:00Z",
			"bucket_type": 1,
			"buckets": [
				31,
				161
			]
		},
		{
			"addr": {
				"id": "4822231e591dcec9b1f2f5ecf027521f095e1a72",
				"ip": "34.192.7.220",
				"port": 26656
			},
			"src": {
				"id": "c112115d19b967b02f1001e3b91e5182e24c6108",
				"ip": "0.0.0.0",
				"port": 26656
			},
			"attempts": 1,
			"last_attempt": "2018-12-11T05:47:48.994656156Z",
			"last_success": "0001-01-01T00:00:00Z",
			"bucket_type": 1,
			"buckets": [
				151,
				51
			]
		},
		{
			"addr": {
				"id": "8a074b65edee24f6e1a020f58d08267edd4bc65d",
				"ip": "34.200.166.69",
				"port": 26656
			},
			"src": {
				"id": "c112115d19b967b02f1001e3b91e5182e24c6108",
				"ip": "0.0.0.0",
				"port": 26656
			},
			"attempts": 0,
			"last_attempt": "2018-12-11T05:47:16.10169107Z",
			"last_success": "0001-01-01T00:00:00Z",
			"bucket_type": 1,
			"buckets": [
				77,
				181
			]
		}
	]
}
```

It's really unclear why the nodes do not sync.

**Comment by melekes** [comment]
> I had a network with 4 nodes working perfectly, then I destroyed it and started again with 5 nodes and now all transactions I send I get the same error:

**There's a lot of double signing evidence in every block**. How did you destroy the first network? Did you make sure genesis files are the same across all the nodes?

**Comment by gianfelipe93** [comment]
I destroyed the virtual machine the nodes were running in. The genesis is the same across all the nodes.

What causes double signing evidence?

After trying many times, it's working now but I am not sure what the problem was so I would like to understand what was wrong possibly.

**Comment by ebuchman** [comment]
> What causes double signing evidence?

Double signing evidence refers to validators signing conflicting votes for the same height, round, and chainID. This can happen for instance if you restart a network using the same ChainID.  If at least one node connected to your network and wasnt wiped, it will broadcast evidence when the network is restarted with the same chain id. 

Can we close this?
