### ISSUE TITLE
Make dynamic changing appVersion possible

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#3007]
Currently , we set state.Version when we get ResponseInfo in handshake.
This upgrade strategy has an obvious flaw that it requires all the validator nodes stopped at the same height, and they upgrade, deploy new version tm and app, then restart.
I suggest we can add an AppVersion in the ResponseEndBlock Message.
```
message ResponseEndBlock {
  repeated ValidatorUpdate validator_updates = 1 [(gogoproto.nullable)=false];
  ConsensusParams consensus_param_updates = 2;
  repeated common.KVPair tags = 3 [(gogoproto.nullable)=false, (gogoproto.jsontag)="tags,omitempty"];
  repeated string blsKeyString = 4;
  uint64 app_version = 5;    //new added field
}
```
When we decide to upgrade to a new version, we set an upgrade height in the future. In a long time period before the upgrade height, the validator nodes can deploy the new version whenever he likes.

In the upgrade height, the app responds this field AppVersion to tell tm whether the upgrade is successful, then tm can update the version in state.

Whether the new code logic in the new version be executed or not can be based on the version, if the upgrade fails, then new logic won't be executed, the program still run the old version logic.

**Comment by ebuchman** [comment]
What do you think about https://github.com/tendermint/tendermint/issues/2671 ? Should we just add this to ConsensusParams?
