### ISSUE TITLE
docs: distributed setup guide

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3012]
Right now we have https://tendermint.com/docs/introduction/quick-start.html#cluster-of-nodes, but we're using `tendermint testnet` cmd there, which must not be used to setup a production cluster. We need to explain how to do distributed setup (using https://github.com/tendermint/alpha or Cosmos genTx) for both private and public networks.

This guide should go here https://tendermint.com/docs/networks/

**Comment by marbar3778** [comment]
This seems to mainly be an issue with the application, when run in-process. Will add something about out of process
