### ISSUE TITLE
A Tx is added to mempool so many times

### ISSUE THREAD

**Issue by kysee** [tendermint/tendermint#3035]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.27.3-0138530d

**ABCI app** (name for built-in, URL for self-written if it's publicly available): kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 17.04
- **Install tools**: all
- **Others**:

**What happened**:
'Added good transaction' is executed multiple times for same tx.
As I know, it means that one Tx is added so many times to mempool.

**What you expected to happen**:
One Tx is added to mempool only Once

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

The following is log for the Tx E9DBB1FB82...FD614756361B.
As you see, the tx is added to mempool so many times.

...
I[17126-12-17|15:24:44.453] **Added good transaction**                       module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** res="&{CheckTx:gas_wanted:1 }" height=700 total=4304
I[17126-12-17|15:24:45.744] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:45.788] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:45.801] **Added good transaction**                       module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** res="&{CheckTx:gas_wanted:1 }" height=701 total=267
I[17126-12-17|15:24:45.903] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:45.904] **Added good transaction**                       module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** res="&{CheckTx:gas_wanted:1 }" height=701 total=459
I[17126-12-17|15:24:46.008] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:46.099] **Added good transaction**                       module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** res="&{CheckTx:gas_wanted:1 }" height=701 total=802
I[17126-12-17|15:24:46.103] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:46.201] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:46.203] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:46.309] Could not check tx                           module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** err="Tx already exists in cache"
I[17126-12-17|15:24:46.311] **Added good transaction**                       module=mempool tx=**E9DBB1FB82BD0E597F6138F7305376CA4192008262D6C83BFF8EFD614756361B** res="&{CheckTx:gas_wanted:1 }" height=701 total=1223
...

**Config (you can paste only the changes you've made)**: Nothing

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:
I run 4 node and 2 validator node, in same network

**Comment by srmo** [comment]
We observe something similar, which in the end leads to mempool full, even if blocks are built. We are still in the process of writing a bug report. Our setup is 10vals + 10 nonvals and 10 clients connected to the nonvals, with 3.5tx/s each. 
Everything looks good, but as soon as we’ve seen size(cache) txs, everything goes crazy and we reach mempool full.

**Comment by srmo** [comment]
test with the current branch and the cache fix. Same problem with mempool full.
For example, CCAFA5CBDEDCBBE433C478BA68D9CACBC07E2FBFC104B3C0DC8B4362158660BB occurs 476 times in the logs for checkTx (many times for "mempool is full"). 
This transaction has been added to the network only once.

**Comment by kysee** [comment]
> Can you guys try #3036 and see if the "Added good transaction" happens less frequently?

#3036 works as expected.
``Added good transaction`` is executed only once.
But...
After mempool is full at least once, the same problem occurs.

As I analysis, 
1. RCP server recieved new tx(tx1)
2. tx1 is added to cache and mempool
3. cache is full and full...  and then tx1 is removed from cache.
4. tx1 is received from other peer.
5. tx1 is added to cache and mempool again.

I wonder why doesn't tx1 be commited until tx1 is removed from cache in step-3.
My Tx Genderator sends 3000tx/sec to RPC server. And mempool size is 5000, cache size is 10000.
Tx size is less than 200B, 2 validator node and 2 non-validator node.
As I know, tendermint's tps is over 3000 tps.

**Comment by ebuchman** [comment]
> cache is full and full... and then tx1 is removed from cache.

tx1 should only be removed from the cache after cache_size worth of txs have been received after tx1. So 10,000 txs after tx1, tx1 will be removed from the cache. If we then hear about it again from another peer, it will get re-added. This situation can't really be avoided without application-based replay protection (of course the kvstore app doesn't provide it!).

> But, I wonder why doesn't tx1 be commited until tx1 is removed from cache in step-3.

Can you clarify what you mean here?

> What should I do to get over 3000 tps by using kvstore application ?

Change `flush_throttle_timeout` to something much smaller, eg. `10ms` or less.  Also change `timeout_commit` to something much smaller, and set `skip_timeout_commit = true`. That should help

**Comment by danil-lashin** [comment]
I think that we have the same problem. 
Blocks are created with multiple identical txs: https://pastebin.com/LchvFJbs 
There must be an issue in tx cache. Will try to apply #3036 in the next testnet.

**Comment by kysee** [comment]
> > cache is full and full... and then tx1 is removed from cache.
> 
> tx1 should only be removed from the cache after cache_size worth of txs have been received after tx1. So 10,000 txs after tx1, tx1 will be removed from the cache. If we then hear about it again from another peer, it will get re-added. This situation can't really be avoided without application-based replay protection (of course the kvstore app doesn't provide it!).
> 
> > But, I wonder why doesn't tx1 be commited until tx1 is removed from cache in step-3.
> 
> Can you clarify what you mean here?

It means that the tx1 must be commited before removed from cache
when tendermint works over 3000 tps and Tx Generator generates txs below 3000 tps.

> 
> > What should I do to get over 3000 tps by using kvstore application ?
> 
> Change `flush_throttle_timeout` to something much smaller, eg. `10ms` or less. Also change `timeout_commit` to something much smaller, and set `skip_timeout_commit = true`. That should help

Thank you so much!!!
Although tx size is a very small condition, I got over 3000 tps.
Could you tell me about the material related to the configuration that affects the performance of the TenderMint?

**Comment by melekes** [comment]
> Could you tell me about the documents or references related to the configuration that affects the performance of the TenderMint?

- https://tendermint.com/docs/tendermint-core/running-in-production.html
- https://medium.com/@anton.kalyaev/tendermint-the-ultimate-guide-for-faster-consensus-cd57087dfd2e

**Comment by cdm** [comment]
I think we are also observing similar problems with our Tendermint test-net, in this net we have an average throughput of 1000-2000 tx/block with one tx added via deliver_tx_async being 'duplicated' and receiving multiple 'copies' of this tx in DeliverTx. The mempool settings are at 5000 size and 20000 cache-size. Even firing in a tx rate of 50-100/block the current versions (0.27.*) still produce the behaviour shown in danil-lashin's pastebin: https://pastebin.com/LchvFJbs

**Comment by melekes** [comment]
@cdm have you tried latest develop?

**Comment by cdm** [comment]
Hi @melekes aha not yet - I will try deploying a develop build this morning and report back.

**Comment by danil-lashin** [comment]
https://github.com/tendermint/tendermint/pull/3036 solved the issue! Thank you, @melekes!

**Comment by ebuchman** [comment]
Great, thanks all. I think we can close this. Please open new issues if you're still having problems. #3036 is released in v0.27.4
