### ISSUE TITLE
Excessive "Reached max attempts to dial" logged as error

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3037]
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
gaia 0.28.0

**What happened**:
Logs are full events (_error_ severity) of "Reached max attempts to dial" for the same peers, over and over.

**What you expected to happen**:
Logging should happen with debug or info severity and should only occur once per peer. This could be accomplished by only logging this event when attempts == max_attempts and always incrementing attempts (even when not dialing peer).

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

Below is a bit of output for a single peer:

```
Dec 17 07:42:02 i-02f6242536097e14b gaiad[1186]: E[17126-12-17|07:42:02.105] Reached max attempts to dial                 module=pex addr=9afa268c45f4b7e46a57b9f2b669daf442566f07@35.232.165.227:26656 attempts=17
Dec 17 07:48:02 i-02f6242536097e14b gaiad[1186]: E[17126-12-17|07:48:02.104] Reached max attempts to dial                 module=pex addr=9afa268c45f4b7e46a57b9f2b669daf442566f07@35.232.165.227:26656 attempts=17
Dec 17 07:53:32 i-02f6242536097e14b gaiad[1186]: E[17126-12-17|07:53:32.100] Reached max attempts to dial                 module=pex addr=9afa268c45f4b7e46a57b9f2b669daf442566f07@35.232.165.227:26656 attempts=17
Dec 17 07:57:02 i-02f6242536097e14b gaiad[1186]: E[17126-12-17|07:57:02.108] Reached max attempts to dial                 module=pex addr=9afa268c45f4b7e46a57b9f2b669daf442566f07@35.232.165.227:26656 attempts=17
Dec 17 07:58:02 i-02f6242536097e14b gaiad[1186]: E[17126-12-17|07:58:02.114] Reached max attempts to dial                 module=pex addr=9afa268c45f4b7e46a57b9f2b669daf442566f07@35.232.165.227:26656 attempts=17
```

**Comment by mdyring** [comment]
What bothers me the most is the error-level severity of the logging. Could it be changed to info to make monitoring easier? :-)

This also seems related to https://github.com/tendermint/tendermint/issues/3081.

What about doing a MarkBad() and then setting an expiry time ("marked bad until....") that is persisted in addrbook. In this case, it could be marked bad for a week or so.

Once the expiry time is hit, the entry should be removed from addrbook.. It will then only be re-added through PEX.

I think the current code leads to stale peers being dialled/gossiped, even though there is no chance of the peer every coming back online.

**Comment by melekes** [comment]
> What about doing a MarkBad() and then setting an expiry time ("marked bad until....") that is persisted in addrbook. In this case, it could be marked bad for a week or so.

Yeah, we'll need some kind of a blacklist of addresses to avoid dialling them (at least in the short term).

**Comment by melekes** [comment]
> What bothers me the most is the error-level severity of the logging. Could it be changed to info to make monitoring easier? :-)

Sure

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3144 to develop. Should land in 0.29.1 or 0.30.0.
