### ISSUE TITLE
Proposal getting out of sync with ProposalBlockPart?

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#304]
![image](https://cloud.githubusercontent.com/assets/53785/19421190/bb2f9a36-93af-11e6-9890-1487d27882a5.png)

Happened with 4 "honest" nodes.

**Comment by ebuchman** [comment]
So it goes from PrecommitWait to the next round. Then it starts receiving block parts before it sees the proposal? Is that what's going on there? Not necessarily incorrect is it? Does it recover or did you kill it?

Also, use log_level=info on latest tendermint:develop - it's more detailed but still readable

**Comment by jaekwon** [comment]
https://gist.github.com/jaekwon/000022471ecb6a4978424efac583c977

It received +2/3 precommits for round 0 while it was in round 1.

**Comment by jaekwon** [comment]
In enterCommit(height int, commitRound int), 

```golang
  // If we don't have the block being committed, set up to get it.
  if !cs.ProposalBlock.HashesTo(hash) {
    if !cs.ProposalBlockParts.HasHeader(partsHeader) {
      // We're getting the wrong block.
      // Set up ProposalBlockParts and keep waiting.
      cs.ProposalBlock = nil
      cs.ProposalBlockParts = types.NewPartSetFromHeader(partsHeader)
    } else {
      // We just need to keep waiting.
    } 
  }
```

We just trample the ProposalBlock & ProposalBlockParts, regardless of what the proposal was for that round (in this case the current round was 1, but commitRound was 0, so ProposalBlock* was getting reset to round 0's proposal).  Which is fine, but it causes an unexpected error message in the logs.

There are two "solutions" to this issue... one is, we stop trampling Proposal* upon discovery of a Commit (+2/3 precommits), but rather use a new field in RoundState... The other is to not log an error on certain conditions... Probably best to do the first solution but to do it later when we have time.

**Comment by adrianbrink** [comment]
@jaekwon Has this been tackled since?

**Comment by ebuchman** [comment]
I think this might be the same error as #1575 ! In which case it's closed - but I'll leave it opened for now just in case ...

**Comment by xla** [comment]
Until surfaced again we close this.
