### ISSUE TITLE
Make TODO log a debug message

### ISSUE THREAD

**Issue by silasdavis** [tendermint/tendermint#305]
This TODO log message creates a lot of noise in logs from log15 announcing it has normalised an odd number of arguments, which is potentially worrying for punters:

https://github.com/tendermint/tendermint/blob/master/state/execution.go#L100

This is because it is meant to hand an even length list of key/value pairs as the varargs argument to INFO. I note that the argument length part is fixed here:

https://github.com/tendermint/tendermint/blob/develop/state/execution.go#L109

But could we go further and make this a `log.Debug` message? Or even better drop it all together? Happy to make a PR in either direction.

**Comment by ebuchman** [comment]
As you notice, the arg-length bit is fixed on develop. Latest develop also has a much more manageable INFO output  - something human eyes can actually parse. I think the "changed validators" message should be INFO level, but it doesnt need to log if there were no validators changed

**Comment by ebuchman** [comment]
maybe the correct thing for now is to use `log.Warn` if validators are updated, to notify that its not implemented yet. otherwise silence. once implemented, it will be an Info msg logging the change

**Comment by silasdavis** [comment]
`log.Warn` would make sense. What is it waiting on being implemented? Is is possible to change validators at this point?

**Comment by ebuchman** [comment]
It's waiting on us having time to implement it. we just need to update tendermint core to actually make the change. we have some other priorities (handshake, bft-fix), but maybe we can try and get it included in v0.8

**Comment by ebuchman** [comment]
cleaned up on develop/valset for imminent release in v0.8
