### ISSUE TITLE
Update PubKey interface to include Name or Type

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#3050]
It will be needed in the SDK's ante handler (once x/auth params are in place) to be able to charge gas for signature verification based upon the key type. Right now these values are hard-coded for ED25519 and SECP256k1, but other applications such as Ethermint will need to provide their own key types.

The param store should thus use a `Name` or `Type` that exists on the `PubKey` interface to support such flexibility.

See discussion here: https://github.com/cosmos/cosmos-sdk/pull/2998#discussion_r239999916

**Comment by ValarDragon** [comment]
I don't think it needs to go on the pubkey interface itself, there can be a second interface for "NamedPubkey" that gets type casted to. Agreed for adding .Name() on the current pubkey implementations though.

**Comment by ebuchman** [comment]
Why can't we use a type switch? Doesn't seem like a need to expose the type on the interface itself.

```
switch pk := pubkey.(type){
  case ed25519.PubKeyEd25519:
    // ...
  case secp256k1.PubKeySecp256k1:
    //  ...
}
```

**Comment by ebuchman** [comment]
Seems we can close this.
