### ISSUE TITLE
Should we hide unroutable node infos in `node_info` method

### ISSUE THREAD

**Issue by yutianwu** [tendermint/tendermint#3055]
Hi, we use `addr_book_strict` for strict address routability rules. but it does not work on rpc method `node_info`.

For example, if I call `node_info`, I will get result like that:
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "listening": true,
    "listeners": [
      "Listener(@172.22.43.12:26656)"
    ],
    "n_peers": "1",
    "peers": [
      {
        "node_info": {
          "id": "3b62301c30805155d1e57abfc8b86c47ecd9453f",
          "listen_addr": "172.22.41.138:26656",
          "network": "chain-test",
          "version": "0.25.1",
          "channels": "40202122233038",
          "moniker": "test",
          "other": {
            "amino_version": "0.12.0",
            "p2p_version": "0.5.0",
            "consensus_version": "v1/0.2.2",
            "rpc_version": "0.7.0/3",
            "tx_index": "off",
            "rpc_address": "tcp://0.0.0.0:26657"
          }
        },
        "is_outbound": true,
        ....
  }
}
```

can we hide unroutable nodes, it may be unsafe to expose private nodes to public.

**Comment by orkunkl** [comment]
I came across this problem today when setting up a testnet. The default expectation is the IP of a private validator not exposed when ID is in `private_peers`. This could be fatal

**Comment by cmwaters** [comment]
Looking into the code, I think this is something that would be quite easy to change and in a non-breaking way. 

I feel this problem highlights the dichotomy in which Tedermint's RPC serves as both an internal input for the node operators i.e. `dump_consensus_state` for monitoring the health and status of their node and debugging the node when something goes awry but at the same time serves for external input from clients that want to use `BroadcastTx` or something similar. In the case of `NetInfo`, if it's for the external user then we should hide the private peers. However, if it is for the internal node operator then they should have access to the entire address book.
