### ISSUE TITLE
Strange timestamps in log output

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3060]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
gaia v0.29.0

**What happened**:
We're seeing strange timestamps in the log output: `[21126-12-21|15:12:31.014]`

**What you expected to happen**:
Something along the lines of `[2018-12-21|15:12:31.014]`

**Comment by ebuchman** [comment]
Fixed in #3125. Will land in v0.29.0
