### ISSUE TITLE
reactor: peers can not receive the proposal and block parts from the proposer

### ISSUE THREAD

**Issue by iceming123** [tendermint/tendermint#3068]
the proposer send proposal and blockparts by sequence, but sometime it send nil part to all peers and was marked by the proposer,then the proposer is never send block parts again when it get real blockparts in this round. it was happened a higher probability when the proposer make proposal cost a long time more than config.TimeoutPropose.

in the gossipDataRoutine of reactor.cpp, they send parts when all peers Initialized ProposalBlockPartsHeader in peerstate struct, the send part maybe nil was marked by the proposer send it，then never send it again when he get it . the last result is they can not consensus in every round.

```
if rs.ProposalBlockParts.HasHeader(prs.ProposalBlockPartsHeader) {
			if index, ok := rs.ProposalBlockParts.BitArray().Sub(prs.ProposalBlockParts.Copy()).PickRandom(); ok {
				part := rs.ProposalBlockParts.GetPart(index)   // it maybe nil
				msg := &BlockPartMessage{
					Height: rs.Height, // This tells peer that this part applies to us.
					Round:  rs.Round,  // This tells peer that this part applies to us.
					Part:   part,
				}
				logger.Debug("Sending block part", "height", prs.Height, "round", prs.Round)
				if peer.Send(DataChannel, cdc.MustMarshalBinaryBare(msg)) {
					ps.SetHasProposalBlockPart(prs.Height, prs.Round, index)
				}
				continue OUTER_LOOP
			}
		}
```

**Comment by ebuchman** [comment]
>  but sometime it send nil part to all peers and 

The proposer is sending nil block parts? Or is this a malicious proposer? 

How can we replicate what you're seeing ?

**Comment by iceming123** [comment]
yes send the nil block part(part := rs.ProposalBlockParts.GetPart(index)), it was happened when proposer make proposal(include parts) cost a long time.
because the tow operation was asynchronous that receive proposal and send block parts, when receive the proposal and initialize the ProposalBlockParts variable in state.cpp but not receive block parts data, then send the proposal info(include block parts above top). it was happen.
