### ISSUE TITLE
docs: empty code block

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3070]
Code block not showing up in https://tendermint.com/docs/spec/abci/apps.html#crash-recovery

**Comment by srmo** [comment]
Which code-block do you mean?
For me, the first block is shown but there is one section that is rendered white-on-white.
Which is probably triggered because of vuepress css
```
.content pre[class*="language-"] code, .content pre code {
    color: #fff;
    padding: 0;
    background-color: transparent;
    border-radius: 0;
```
which overrides 
```
.content code {

    color: #476582;
    padding: .25rem .5rem;
    margin: 0;
    font-size: .85em;
    background-color: rgba(27,31,35,.05);
    border-radius: 3px;
}
```

The formatting happens because of indentation. Suggested fix: unindent

**Comment by melekes** [comment]
Merged to develop.

**Comment by melekes** [comment]
Thanks @srmo!
