### ISSUE TITLE
Need Help: how can we get `State` of a given height if we want to rollback to that height

### ISSUE THREAD

**Issue by yutianwu** [tendermint/tendermint#3072]
hi, since we store `State` with a same key, so we don't have `State` of every block.

```go
// SaveState persists the State, the ValidatorsInfo, and the ConsensusParamsInfo to the database.
// This flushes the writes (e.g. calls SetSync).
func SaveState(db dbm.DB, state State) {
	saveState(db, state, stateKey)
}

func saveState(db dbm.DB, state State, key []byte) {
	nextHeight := state.LastBlockHeight + 1
	// If first block, save validators for block 1.
	if nextHeight == 1 {
		lastHeightVoteChanged := int64(1) // Due to Tendermint validator set changes being delayed 1 block.
		saveValidatorsInfo(db, nextHeight, lastHeightVoteChanged, state.Validators)
	}
	// Save next validators.
	saveValidatorsInfo(db, nextHeight+1, state.LastHeightValidatorsChanged, state.NextValidators)
	// Save next consensus params.
	saveConsensusParamsInfo(db, nextHeight, state.LastHeightConsensusParamsChanged, state.ConsensusParams)
	db.SetSync(stateKey, state.Bytes())
}
```

So if I want to rollback to a given height, I can not get the right `State` without replay all the blocks. 

The main problem is `Accum` of validators is not right, so I can not get the right Proposer.

Is there a way to get right `State` or it just does not exist

**Comment by bradyjoestar** [comment]
If you want to rollback the state, you can reconstruct it from LoadValidators(blockExec.db, block.Height)  and  LoadConsensusParams(blockExec.db, block.Height) and other information from the block.

There is no need to create a new function such as 
```
func SaveState(db dbm.DB,height int64, state State) {
	saveState(db, state, stateKey)
}
```

**Comment by bradyjoestar** [comment]
I had wrote the rollback feature for the 0.27.4 on the  [tendermint rollback](https://github.com/bradyjoestar/tendermint)
Considering that it wont use in the production env, there is no need to create a pull request.
Tested By 2 scenario(app:kvstore):
- rollback all the nodes
- rollback  1 of cluster which is made up by 4 nodes

**Comment by ebuchman** [comment]
Very good question. I think this will actually be needed to do #1029 and #3054 properly, but it looks like maybe james figured out a workaround for #3054. 

We don't persist the state in full because it's a lot of redundant information between heights. We do of course store the validator set and consensus params every time they change, so it should be possible to reconstruct the state for a given height from these. Since the ProposerPriority is part of the Validator struct, it should be part of the data that gets persisted, so you should be able to recompute the correct changes to proposer priority.

**Comment by yutianwu** [comment]
> Very good question. I think this will actually be needed to do #1029 and #3054 properly, but it looks like maybe james figured out a workaround for #3054.
> 
> We don't persist the state in full because it's a lot of redundant information between heights. We do of course store the validator set and consensus params every time they change, so it should be possible to reconstruct the state for a given height from these. Since the ProposerPriority is part of the Validator struct, it should be part of the data that gets persisted, so you should be able to recompute the correct changes to proposer priority.

yeah, but for now  we don't have such a method to recompute proposer priority easily, do you have any good suggestions

**Comment by yutianwu** [comment]
yeah, but as @ebuchman  said, it costs too much to store all validatorInfo every time. So it may need prune strategy or provide a method to recompute it from the very beginning.

**Comment by bradyjoestar** [comment]
In my scenario, my validators will change every height due to true random select strategy by bls algorithm.
I agree with you, It's a good idea to recompute it in tendermint.

**Comment by melekes** [comment]
Can we close this?
