### ISSUE TITLE
Validator ordering: unexpose or make explicit?

### ISSUE THREAD

**Issue by kevlubkcm** [tendermint/tendermint#3073]
Hi all,

Not sure if this has been discussed before, maybe over Slack?

The ordering of validators and the `index` of each validator is exposed in a few places (eg the `/consensus_state` endpoint and in `Vote` events). 

So the current implementation details of validators as an ordered list is quite important. 

For example, to maintain a valid `ValidatorSet` by following `ValidatorSetUpdates` events, we need to be aware that new validators are always added to the end of the list in the order of the `validator_updates` array and validators are deleted by shifting all validators after the deleted one down.

The name `ValidatorSet` implies that ordering is not important, but this is not true right now.

It seems to me that validator ordering is not critical to tendermint consensus. Maybe the best solution is to remove areas that expose it? Otherwise, update the docs to codify what the details are/should be (and maybe rename `ValidatorSet` to `ValidatorList`.

**Comment by ebuchman** [comment]
So this actually is documented here: https://github.com/tendermint/tendermint/blob/master/docs/spec/blockchain/state.md#validator, namely:

```
The state.Validators, state.LastValidators, and state.NextValidators, must always by sorted by validator address, so that there is a canonical order for computing the MerkleRoot.
```

As for this:

> we need to be aware that new validators are always added to the end of the list in the order of the validator_updates array and validators are deleted by shifting all validators after the deleted one down.

This should never have been true. It should always have been the case that the validators were ordered by their address. The primary reason for the ordering is for the Merkle root (Header.ValidatorsHash)

In any case, I've opened https://github.com/tendermint/tendermint/pull/3452 to better document this.

Is that sufficient to close this issue? Or would you like to see something else?

Thanks.

**Comment by kevlubkcm** [comment]
Oh great. Looking at the code now, makes sense. Think I must've read something wrong before.
Thanks!
