### ISSUE TITLE
[rpc] tx_search can take a long time

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#3076]
Hi guys,

I am running Tendermint with 7 nodes on AWS using Kubernetes. Currently, I have 36.000 transactions in the blockchain but it is taking quite a long time to query transactions (around 10 seconds to query 100 transactions).

Is there any sort of production config that I can use that will make it faster?

Thank for your help guys.

Have a great 2019!

**Comment by melekes** [comment]
What are you using to query transactions?

**Comment by gianfelipe93** [comment]
@melekes I am using `TxQuery` like below:
```
resQuery, err := rpcClient.TxSearch(query, false, page, txPerPage)
```

is it the proper way to query transactions ?

**Comment by melekes** [comment]
> is it the proper way to query transactions ?

- for individual transactions - use `/tx`
- for multiple transactions sharing a common tag - use `/tx_search`
- for complete blocks - use `/block` or /blockchain`

Could you also post a query string here? Thanks

**Comment by gianfelipe93** [comment]
@melekes thanks for you help!

can I query by a tag using `/tx` or `/block`?

I am not sure if they are suitable for my use case:
A user uploads 500 transactions per day (average) and the user is able to see its own transactions:
`tx.UserID='abc'`

the user can also query by time:
`tx.UserID='abc AND tx.Timestamp>=*<TIMESTAMP>* AND tx.Timestamp<=*<TIMESTAMP>* `

And also by other tags but the that is pretty much the query structure.

I will always query multiple transactions so I think we can discart the `/tx` route and since the transactions might be in different block probably the `/block` route doesn't suit me.

is there anything you suggest I could do to make the query faster ? 

Additionally, since we are deploying on AWS, do you think a more powerful VM would speed up the query ?

Thanks for you help!

**Comment by melekes** [comment]
Oh, I think I know how we can make it faster.

**Comment by gianfelipe93** [comment]
@melekes how ?

**Comment by melekes** [comment]
Right now we're fetching the records from the DB and perform an intersection. We should instead pass a first selection around which should shrink with a number of filters.

**Comment by gianfelipe93** [comment]
@melekes is there something I can help you with ?

**Comment by gianfelipe93** [comment]
This is becoming a real issue because it's taking more than 2 minutes to query transactions.

**Comment by melekes** [comment]
Sure! This is https://github.com/tendermint/tendermint/blob/616c3a4baeb1f52589f6afe09bc2be256b9626d2/state/txindex/kv/kv.go#L144 where you should start.

**Comment by gianfelipe93** [comment]
@melekes sorry mate, it may take a while for me to find the time to look into it but I will.

**Comment by HaoyangLiu** [comment]
@melekes 
Do we have plan to fix this issue? Suppose a blockchain has billions of tx, then if the matched tx quantity is huge, then the memory will be exhausted. This is a hack point if a node expose its rpc endpoint.

**Comment by melekes** [comment]
`/tx_search` endpoint is the most vulnerable endpoint right now. We do have a plan on how to fix this.

**Comment by HaoyangLiu** [comment]
Excellent!

**Comment by zmanian** [comment]
We might want to have a general configurable timeout on requests here to fix the Denial of Service vuln tx_search opens

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/2010
