### ISSUE TITLE
Bound mempool memory usage

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#3079]
**Summary**: As a subcomponent to: https://github.com/tendermint/tendermint/issues/1696
I think it may be near-term easy and important to bound the space usage of the mempool txs. (Note I am not proposing accounting for the LRU cache overhead, or mempoolTx struct overhead, just bounding the total amount of tx data itself) 

**Problem**: At the moment, every tx in the mempool can be of size `max(maxMsgSize, BlockDataSize)`, and the former is a constant of `1MB`. In a lot configurations, block data size may be large, which would open up the mempool to taking a lot of ram. Under default mempool size, it would be `5000 * max_block_size`. With 200KB blocks, thats 1GB of RAM, with 1MB blocks, that opens yourself up to 5GB of RAM consumed. I think both of these are too much to open up sentries under default

**Proposed solution**: Add a `max_bytes` field to the mempool config options. Before adding a tx to the mempool, check if it will cause the mempool to exceed its max_bytes limit. When removing txs in Update, subtract the corresponding amount from the `max_bytes` field. `max_txs` is a useful thing to still keep, as there are many things that depend on the number of txs as well. (Recheck time, etc.)

**Comment by ebuchman** [comment]
This makes sense. Should we just use `max_bytes` instead of having a limit in terms of number of txs? And maybe the same for the cache, or?

**Comment by ValarDragon** [comment]
I think we should keep `max_txs` until we speed up the many num_tx dependent components of the mempool. (The primary example being recheck time, since thats really a function of the number of txs, not the number of bytes)

For the cache `max_txs` feels like the better measure to me, but I'm fine with either. Cache entries are tx size independent, as we store the hash within the cache, not the actual tx. Because of that, imo its easier to reason about `max_txs` than `max_bytes`. (The opposite argument would be that the server operator may prefer to think about the resource constraint, and not the exact number of txs)

**Comment by ebuchman** [comment]
Done in #3248
