### ISSUE TITLE
Ship builds

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#308]
Because not everyone wants to deal with your source, man.

**Comment by faddat** [comment]
That's reasonable.  When you say "ship builds" you're talking about shipping builds to, for example, the github releases page?

**Comment by ebuchman** [comment]
I'm more talking about automated/deterministic build system, but yes, the end result is they should be available on the github releases page, and probably on our website too

**Comment by faddat** [comment]
Got it.  Okay, so from my perspective we have to separate our layers if
that's where we are headed.  Also, yes on that question about Jenkins. It
will be better than circle CI if we head in that direction.
