### ISSUE TITLE
Add Prometheus "chain_id" label for all metrics

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3082]
Since people are running multiple chains (game-of-stakes, genki etc.), it would be very helpful to have the chain id as a label to differentiate between metrics of unrelated chains. Ideally this should be set on all metrics.

This could be worked around by operators when registering the targets (adding the chain_id there manually or via automation), but I believe it would be generally useful to have this built in. This also makes upgrades nicer.

**Comment by ebuchman** [comment]
Added in #3123 - should be released in v0.29.0
