### ISSUE TITLE
Mempool: Rejected bad transaction should log source (nodeid or RPC)

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3091]
```
Jan  6 11:07:52 peering gaiad[10881]: I[6016-01-06|11:07:52.322] Rejected bad transaction                     module=mempool tx=5A3EEEA0890677800FB26CD31C1B1ECF7CFFB20F9E730DFD54169909DAB7ADE4 res="&{CheckTx:code:4 log:\"{\\\"codespace\\\":\\\"sdk\\\",\\\"code\\\":4,\\\"message\\\":\\\"signature verification failed\\\"}\" }" err=null
```

Log is missing important information, such as the source of the invalid TXs (p2p nodeid or RPC).

This is very useful for production to determine source of invalid TXs, especially in a "trusted" relay/peering setup.

**Comment by jamesgeorge007** [comment]
@melekes @ebuchman @mdyring I would like to take it up :+1: 
Also, it would be great if you guys could guide me as I'm not familiar with the code base.

**Comment by ebuchman** [comment]
Awesome! Take a look at the [contributing guidelines](https://github.com/tendermint/tendermint#contributing).

There was a similar PR recently to log the peerID for bad votes (https://github.com/tendermint/tendermint/pull/3086/files). So this is more or less the same but for the mempool txs!

**Comment by jamesgeorge007** [comment]
@ebuchman As I mentioned above I'm not familiar with the code base. It would be great if you could point me to the files to work with :+1:

**Comment by melekes** [comment]
```
» ag "Rejected bad transaction"
mempool/mempool.go
386:                    mem.logger.Info("Rejected bad transaction", "tx", TxID(tx), "res", r, "err", postCheckErr)
```

**Comment by jamesgeorge007** [comment]
@melekes `err` has to be replaced right? I'm not sure what should occupy it's place.

**Comment by jamesgeorge007** [comment]
@melekes `err` and `postCheckErr` has to be replaced right? I'm not sure what should occupy it's place.

**Comment by ebuchman** [comment]
Realizing this might not be the best issue to start with as it will depend on some changes to make the relevant information accessible at that point in the code. Some of those changes are already in an open PR - #2778. If you want to base your changes on top of #2778 that would work, but it won't be merged until #2778 is. 

All we want is to add to the log statement the sender of the tx.

**Comment by alexanderbez** [comment]
With #2778 merged, I don't see a direct way to get the p2p peerID from the uint16 peerID.

**Comment by jibrown** [comment]
Instead of passing the uint16 to the mempool directly, and then not being able to get the p2p.ID back, we could pass a new PeerID struct which includes the uint16 and the p2p.ID. The reactor has a map both ways so it has all the info, we just need to pass it into the mempool itself. Then in the mempool, we still mostly use the uint16 to save space, but at least we have the p2p.ID as well for when we need to log it :)

**Comment by ebuchman** [comment]
Great idea Jackie!
