### ISSUE TITLE
Show all connected nodes?

### ISSUE THREAD

**Issue by swapnil-pandey** [tendermint/tendermint#3092]
Is there any way to see all the connected nodes for the purposes of monitoring or otherwise?

**Comment by melekes** [comment]
`/net_info` endpoint (https://github.com/tendermint/tendermint/blob/1e1ca15bccedc16c2452c73745c3c2b5df91ae96/rpc/core/net.go#L12)

--
Join our chat: https://riot.im/app/#/room/#tendermint:matrix.org
