### ISSUE TITLE
Send a json rather than a key value pair?

### ISSUE THREAD

**Issue by swapnil-pandey** [tendermint/tendermint#3094]
Can we store json as the contents of the block rather than just key value pairs. I am using the kvstore app of the abci-cli.

**Comment by melekes** [comment]
Yes, you can. For Tendermint, both key and value (transaction, more broadly) are just byte arrays. So the content of a transaction could be anything.

Join our dev. chat: https://riot.im/app/#/room/#tendermint:matrix.org
P.S. you may get faster answers there
