### ISSUE TITLE
privval: add a MAC for unix sockets

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3099]
See previous issue for discussion, which should also be more permanently documented: https://github.com/tendermint/tendermint/issues/2563

IPCVal is an unencrypted local unix socket connection. Encryption+key-management is overkill for this connection. Just need to use a MAC

**Comment by marbar3778** [comment]
With the migration to gRPC for all connection types, TLS is now available for all connection types. The user will have to provide a certificate. Are we okay with this or would like to add MAC on top?

cc @hendrikhofstadt @ebuchman

**Comment by hendrikhofstadt** [comment]
TLS sounds solid but probably only acts as defense in depth measure here. I assume that the access to these services should never be exposed. As long as that's documented client certificates / auth are not necessary imo,

**Comment by marbar3778** [comment]
okay will add documentation with the refactor to gRPC, closing this issue. reopen if anyone feels the nessecity for more secruity.
