### ISSUE TITLE
privval: integration test for priv_val_server and for KMS

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3106]
This repo includes the `priv_val_server` binary under `cmd` as a simple implementation of an external validator signing process, but we don't test it anywhere. We should add tests for it.

We should also have an integration test for the external KMS process, but I'm not sure if that should live in here or in the external KMS repo - see https://github.com/tendermint/kms/issues/49

Replaces part of #2549

**Comment by ebuchman** [comment]
v0.28.0 was released without this based on manual testing. bumping this to a future milestone

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3149 to develop. Can we close this now?

**Comment by thanethomson** [comment]
> Merged #3149 to develop. Can we close this now?

I'd say so. There's always room for improvement, but we can do those in future milestones.
