### ISSUE TITLE
privval: improve heartbeat implementation

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3107]
Current implementation of heartbeat spawns an independent routine to call Ping periodically. 

It would be better if the ping timer was reset every time a message was received - that way we wouldn't call Ping more frequently than we actually need to.

We might also want to serialize calls to Ping with other calls to the SignVote and SignProposal, so that they only happen from a single routine and the underlying RemoteSignerClient need not be thread safe.

That should help clarify what needs a mutex and why. See #3064 for more. 

Also, see http://250bpm.com/blog:22 for more info on the subtleties of heartbeats.

**Comment by melekes** [comment]
> It would be better if the ping timer was reset every time a message was received - that way we wouldn't call Ping more frequently than we actually need to.

I think this can be applied to other connections we have as well (e.g. p2p).

**Comment by Liamsi** [comment]
cc @jleni this and https://github.com/tendermint/tendermint/issues/3296 (by @amrali) are the issues I was just talking about

**Comment by jleni** [comment]
I have an issue where invalid signatures leave data in the channel and affect pinging.

Very similar to what @ebuchman was saying, I would suggested to:
- split responsibilities multiplexing/demultiplexing vs command specific work
- move socket multiplexing/demultiplexing to a single go routine + channel and receives/pushes answers to other command specific channels for `ping` or `signature`, etc..
- make ping and other commands to operate on these new command specific queues/channels

We would need to have some specific header to demultiplex but talking to @Liamsi, I understand that things are already in place so the change would be small.

This will avoid thread safety issues and ordering problems in the tendermint-kms comms

**Comment by jleni** [comment]
I can prepare a PR if you agree with change and you think it has enough priority at this stage.

**Comment by jleni** [comment]
I now see that an almost identical discussion in taking place in https://github.com/tendermint/tendermint/issues/3296

**Comment by ebuchman** [comment]
See discussion in https://github.com/tendermint/tendermint/issues/3296#issuecomment-463073468. Moving it here.

**Comment by ebuchman** [comment]
Tracking https://github.com/tendermint/tendermint/issues/3486

**Comment by ebuchman** [comment]
@jleni can we close this?

**Comment by marbar3778** [comment]
This was solved in #3351. In 0.34 privval is migrating to gRPC and use keepalive functionality

**Comment by jleni** [comment]
Excellent news about gRPC!! 
A much better and simpler design? Will tmkms catch up with this?

**Comment by marbar3778** [comment]
yes once 0.34 is released then tmkms will begin work on migration
