### ISSUE TITLE
Problem while initiating Tendermint node

### ISSUE THREAD

**Issue by trinayanbhatt** [tendermint/tendermint#3108]
When I initiate Tendermint node it starts and stops frequently and that's why the application is not unable to create a proper handshake. And while using it with monit then after checking the status of monit, tendermint's process shows intializing status and after some time does not exist. 

Here is a snapshot of the whole initialisation process:

![screenshot from 2019-01-11 15-47-20](https://user-images.githubusercontent.com/25535404/51028215-e2845580-15b8-11e9-9ead-1151c069dedd.png)

**Comment by ebuchman** [comment]
What application are you using and with what abci server?

**Comment by trinayanbhatt** [comment]
I am using tendermint for bigchaindb node setup, I have already created a node server of BigchainDB but when I try to create an asset or make some transaction over this network then it throws me this error that proper handshake can't be created. The connection gets timed out after making some requests to the node server.

So, to check for the problem when I used monit to check the summary of all the processes it shows some problem with tendermint. The process of tendermint is not initializing properly as the status for it is either **initializing** or **does not exist** when i check monit summary multiple times.

**Comment by melekes** [comment]
What guide are you following? What are the Tendermint and BigchainDB versions?

**Comment by ebuchman** [comment]
Seems probably like a version mismatch. I think BigChainDB only works up to Tendermint v0.22.8: https://github.com/bigchaindb/bigchaindb/blob/c79848d66a684420b717e36bed2ec00281f57855/docs/contributing/source/dev-setup-coding-and-contribution-process/run-node-as-processes.md#installing-a-tendermint-executable

**Comment by trinayanbhatt** [comment]
@melekes this is the **tendermint** version 0.22.8-40d6dc2e and the version of **bigchaindb** is  2.0.0b9. I am following bigchaindb server docs for this installation and server setup.

http://docs.bigchaindb.com/projects/server/en/latest/simple-deployment-template/set-up-node-software.html

**Comment by trinayanbhatt** [comment]
@ebuchman I am using tendermint's version 0.22.8-40d6dc2e so it doesn't seems that its a version mismatch.

**Comment by melekes** [comment]
Closing due to no response.
