### ISSUE TITLE
pagination response and default parameter should be refined

### ISSUE THREAD

**Issue by ackratos** [tendermint/tendermint#3113]
1. response structure is requested from https://github.com/cosmos/cosmos-sdk/pull/2894#discussion_r242656989
2. limit default value 100 to 200 is requested from https://github.com/cosmos/cosmos-sdk/pull/2894#discussion_r242657896 (related with tendermint/tendermint#3065)

**Comment by melekes** [comment]
1. 👍 for the response structure
2. 👎don't think we should change the limit

**Comment by alexanderbez** [comment]
I second @melekes here, not sure of the performance implications of increasing pagination would have, perhaps minimal.
