### ISSUE TITLE
privval: test should include unix sockets

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3115]
Current tests in the `privval` pkg primarily use the tcp listener/dialer. They should be written to also test the unix listener/dialer. This is similar to how we test both URI and JSONRPC behaviour in `rpc` package.

Both tcp and unix sockets are integrations tested in the `node` pkg.

Follow up to #2923

_Originally posted by @ebuchman in https://github.com/tendermint/tendermint/pull/2923#issuecomment-453812717_

**Comment by thanethomson** [comment]
How much detail/integration is required for the socket testing? Right now we only effectively test that we can connect - do we also need to test more detailed messaging/communication over the TCP and IPC sockets?

**Comment by ebuchman** [comment]
The tests in `privval/socket_test.go` are just about connecting and sending a basic message, but we should make sure they're replicated for the unix sockets (shouldn't need to duplicate the test functions themselves, just modify to loop over the two transports).

The tests in `privval/client_test.go` test much more of the functionality, but again only use tcp sockets. We should change all those funcs to be like `testSocketXYZ(t *testing.T, sv *SocketVal, rs *RemoteSigner, xyz ...)` so that they take already setup versions of the SocketVal and RemoteSigner using whichever transport. That way the `TestSocketXYZ` funcs can just be simple loops over the two transports that call `testSocketXYZ` with the appropriate one.

**Comment by ebuchman** [comment]
Eg. the rpc tests loop over the two kinds of rpc connections: https://github.com/tendermint/tendermint/blob/develop/rpc/client/rpc_test.go#L53

**Comment by Liamsi** [comment]
`privval/socket_test.go` were updated via #3121. Should I take care of the tests in `privval/client_test.go` or is did someone already start working on this?

**Comment by thanethomson** [comment]
@Liamsi, I'm having a little trouble at the moment with getting the Unix sockets to work with the `client_test.go` tests. If it's urgent and you've got time, you're welcome to work on this now. Otherwise I'll have to take a look at it in the morning.

**Comment by Liamsi** [comment]
I do not think it is so urgent that I can't wait till tomorrow morning. Also, sounds like you've already started working on this (and I'll probably run into the issues as you). Let me know if I can help with anything though!

**Comment by thanethomson** [comment]
I'm looking into this now 👍

**Comment by ebuchman** [comment]
Thanks @thanethomson and @Liamsi !
