### ISSUE TITLE
periodically dump go routines

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3117]
Add a new config option (eg. like a WAL file name) that will allocate 1GB in an autofile for go-routine dumps taken every few minutes. When debugging deadlocks and resource leaks, this should help provide some visibility into the system's history leading up to the current state.

**Comment by melekes** [comment]
Does this mean that every few minutes the whole process will be stopped to take a snapshot (by analogy with "stop the world" garbage collectors)? For how long (1ns, 1ms, 100ms)?

What if instead we provide an easy way to get goroutines list / stack dump / smth else https://stackoverflow.com/a/19145992/820520 ?

**Comment by ebuchman** [comment]
Yes an easy alternative is to just run the pprof server and a simple external process that polls it at whatever frequency and dumps the results to a file. The benefit of that is we don't need to change Tendermint at all, but we need people to actually run that. Maybe we can provide a simple tool to poll the pprof and write to a file, and in some of our testnet instructions we can tell people to run it ?

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/3249
