### ISSUE TITLE
use a cli package

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#312]
urfave/cli or spf13/cobra ?!

I'm leaning towards cobra.

**Comment by rigelrozanski** [comment]
Just implemented cobra is passwerk (https://github.com/rigelrozanski/passwerk) works great simple easy implementation. Uses flags and commands as expected.

**Comment by ethanfrey** [comment]
We use urfave/cli in basecoin, cobra in tendermint. I don't know which path to follow...

I do think that the urfave/cli looks cleaner.  Don't know about feature difference.

Example of cobra:
https://github.com/tendermint/tendermint/blob/cli_cobra/cmd/tendermint/commands/run_node.go

Example of urfave:
https://github.com/tendermint/basecoin/blob/master/cmd/commands/start.go

**Comment by zramsay** [comment]
cobra is what we went with at monax & after migrating a handful of repos from urfave/cli to cobra I'm convinced the latter is nicer to work with.

**Comment by ethanfrey** [comment]
Okay, Cobra/Viper it is... I'll make an issue in basecoin...

**Comment by ebuchman** [comment]
https://github.com/tendermint/tendermint/pull/419
