### ISSUE TITLE
merkle: follow up to #2713

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3120]
See the review for points of follow up: https://github.com/tendermint/tendermint/pull/2713#pullrequestreview-180548151

The main concern is that `Verify` now seems to expect an object before it is hashed, so it can prepend the 0-prefix ala the rfc.

However, the leaves of our Merkle trees should always be hashed anyways, even before the 0-prefix is added. @ValarDragon see https://github.com/tendermint/tendermint/pull/2713#discussion_r238086049

Few other minor points mentioned in the review.

We're also going to need to update the SDK and possible fix some things in the `store` pkg, @jackzampolin

**Comment by jackzampolin** [comment]
@ebuchman thank you for the heads up. Are some of the required `store` changes included in or facilitated by https://github.com/cosmos/cosmos-sdk/pull/2985?

**Comment by ebuchman** [comment]
Wow that looks like it's going to be a great cleanup but I don't think it will really help here.

Consequences of this for the SDK:
- breaks the way the stores are hashed, so any hard coded merkle roots will be invalid
- changes the interface for merkle proofs by now taking in the full leaf object being proven, rather than the hash of the object

@ValarDragon did I miss anything? 

Also, @ValarDragon, can you please address https://github.com/tendermint/tendermint/pull/2713#discussion_r238085473 with a small comment to explain what's going on :) . I can handle the rest of the review comments there.

I think it should be ok to leave the new API as is - ie. the proofs take the leaf object, not the hash. If some consumer wants to pass in the hash instead, it's welcome to, like Tendermint does for txs. We just need to be clear in the documentation/spec where we pass in a hash and where we pass the whole object!

**Comment by ValarDragon** [comment]
I believe thats all the changes that need to be made SDK side. Also agreed for leaving the API as is!

I'll make a PR for that comment

**Comment by ebuchman** [comment]
Fixed in #3175
