### ISSUE TITLE
Probabilistic filtering

### ISSUE THREAD

**Issue by tomtau** [tendermint/tendermint#3127]
Currently, KVPairs tags are meant for precise indexing. That may not be always desirable, e.g. due to performance or privacy (if tags add some external data).
Say, ABCI app would add a compact filter tag at EndBlock that lite clients could read and decide whether to retrieve the full block data which may or may not contain relevant TX.
Not sure whether such logic is desirable on the Tendermint node storage indexing level -- it could possibly be in ABCI + custom implementation on top of the lite client.

**Comment by ebuchman** [comment]
I'm not sure I understand what change would be necessary to support this. Can't apps already elect to do this? Tendermint won't understand what's going on, but the tags are already arbitrary bytes.

**Comment by tomtau** [comment]
Yes, they can implement this custom logic -- tags can contain arbitrary bytes (although the docs say it should be UTF-8?).
This issue was rather whether to have something canonical such that this functionality could be provided say via https://tendermint.com/rpc/#txsearch
This change may be quite complex though -- if so, perhaps it's better to leave it on the custom app logic level, so feel free to close this issue.

**Comment by ebuchman** [comment]
Oh interesting, thanks. We can leave this open as a proposal for now. Though it probably won't see much action for some time.
