### ISSUE TITLE
Data is not catching up for a new peer

### ISSUE THREAD

**Issue by enakshipriya** [tendermint/tendermint#3128]
On adding a new validator node, its data is not catching up with the existing nodes. The application i am using is persistent kvstore. The changes in validator set is done through transaction which makes ValidatorUpdate with EndBlock response. For the new node, catching_up parameter is showing as true in status report, but its stuck:
![cap2](https://user-images.githubusercontent.com/16506408/51176074-04941580-18e2-11e9-92c9-64b060f8d399.jpg)

Following are the error logs:
[bug_report.txt](https://github.com/tendermint/tendermint/files/2759191/bug_report.txt)

**Comment by kunaldhariwal** [comment]
I think we need to look up once for the genesis file, are they identical for all the peers?

**Comment by kunaldhariwal** [comment]
`"wrong set size: 2 vs 1"`

I think we need to check if the genesis file is identical for the new node just like the other ones.

**Comment by enakshipriya** [comment]
@kunaldhariwal I made sure that the Genesis file was same across all the nodes

**Comment by kunaldhariwal** [comment]
@ebuchman Issue is solved, would be apt to close this issue.

**Comment by srmo** [comment]
Can you describe the solution please?

**Comment by kunaldhariwal** [comment]
@srmo  She had to check if the genesis files were identical.
She ran this RPC command: `curl localhost:26659/genesis`  
and it gave the output of the gensis files which were different than the one's in each nodes. She then made sure it's identical and also had issues with timestamp. Which was solved by changing the systime.
That's it, i guess?
