### ISSUE TITLE
rare edge case of signRFC6979

### ISSUE THREAD

**Issue by ackratos** [tendermint/tendermint#3130]
As there is no issue system on tendermint/btcd, open here to discuss when tendermint will pick up  https://github.com/btcsuite/btcd/pull/1347 or how about accept my back port PR: https://github.com/tendermint/btcd/pull/2

**Comment by ebuchman** [comment]
Thank you very much for bringing this to our attention! Would it be better to update to the latest commit on BTCD and just re-apply our patch on top of that, rather than taking a backport?

**Comment by ackratos** [comment]
> Thank you very much for bringing this to our attention! Would it be better to update to the latest commit on BTCD and just re-apply our patch on top of that, rather than taking a backport?

that's better, do we have ETA of updating?

**Comment by ebuchman** [comment]
We can make it happen this week.

**Comment by ebuchman** [comment]
Merged to develop. See follow up #3162 and #3163

**Comment by ackratos** [comment]
> Merged to develop. See follow up #3162 and #3163

thanks a lot!
