### ISSUE TITLE
json2wal util bug

### ISSUE THREAD

**Issue by bradyjoestar** [tendermint/tendermint#3146]
Currently we could use json2wal to convert the *.json to wal.File.

I found the the length of buffer of readline in json2wal is defalut

https://github.com/tendermint/tendermint/blob/aa40cfcbb97fac3832b47ccdcf99c6b7fb504cb2/scripts/json2wal/main.go#L48

And the length of a line in json will exceed the defaultSize(4096) and report the following erros　because the size of byte of BlockPart
```
panic: failed to unmarshal json: unexpected end of JSON input

goroutine 1 [running]:
main.main()
	/root/gelgo/src/github.com/tendermint/tendermint/scripts/json2wal/main.go:66 +0x73f

```

https://github.com/tendermint/tendermint/blob/aa40cfcbb97fac3832b47ccdcf99c6b7fb504cb2/types/params.go#L14

I will use `NewReaderSize(rd io.Reader, 70000)` to fix this bug.

**Comment by melekes** [comment]
Merged to develop. Should land in 0.29.0. Thanks 👍
