### ISSUE TITLE
tools: Make base config configurable on testnet cmd

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3160]
`tendermint testnet` generates files for a new testnet using a default config but with the option to fill in the persistent_peers (so all the nodes connect).

We should add a `--base-config` option to point to an existing config file to use as the base. 

This makes it easier to manipulate and share testnet environments

**Comment by gchaincl** [comment]
Would `tendermint testnet --home=x` work in this case?

**Comment by ebuchman** [comment]
I think the `--home` flag isn't being used by the testnet command but in theory it could look there for the config file.

**Comment by gchaincl** [comment]
I understand better now and I think `--base-config` is more explicit than `--home`

**Comment by melekes** [comment]
By `--base-config` you mean `BaseConfig` field of the config OR the whole config? In the latter case, why the `--base` prefix?

**Comment by ebuchman** [comment]
I thought to include `base` because some of the fields could still be overwritten by other flags. But it could just be `--config` too without the prefix and still have that overwritting behaviour ...

**Comment by melekes** [comment]
I think we should go with the `--config` flag since most of the developers do not know about `BaseConfig`.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3559 to develop.
