### ISSUE TITLE
Can we wrap btcd instead of forking it?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3162]
We currently have a fork of btcd so we can use a simpler encoding format for secp256k1 signatures: https://github.com/tendermint/btcd

That library continues to receive important fixes: https://github.com/btcsuite/btcd/commits/master/btcec

While we should move to using the libsecp256k1 C library and recommend it for production uses, we probably want to continue to have a native Go implementation.

We should consider if we can wrap the btcd to serialize the way we want (this may mean we have to serialize it their way, deserialize it, then reserialize it our way). That way we don't have to maintain a fork and can easily upgrade.

**Comment by Liamsi** [comment]
Should this be the same prio / milestone as #3163?

**Comment by ebuchman** [comment]
I think this is lower priority but happy to have them down together.

**Comment by ebuchman** [comment]
Uh, doesn't the library already expose what we want in https://godoc.org/github.com/btcsuite/btcd/btcec#SignCompact ? @ValarDragon

**Comment by ValarDragon** [comment]
SignCompact is of the form `recovery_byte || R || S`. We don't need the recovery byte. Also, the important part of us forking was ensuring that `r` is in the canonically smaller of the two options. So we would also have to wrap the verify and sign methods.
(Its probably on a scale thats irrelevant here, but using that sign compact method will also take longer for the signer)

**Comment by Liamsi** [comment]
> Also, the important part of us forking was ensuring that r is in the canonically smaller of the two options. So we would also have to wrap the verify method to fail for -r.

You mean `S`, right?

**Comment by Liamsi** [comment]
If you mean `s`, we have two options here: 
 1) wrap `SignCompact` and simply ditch  `recovery_byte` in the returned result (we don't make use of it), or,
 2) directly wrap and use [PrivateKey.Sign](https://github.com/btcsuite/btcd/blob/ed77733ec07dfc8a513741138419b8d9d3de9d2d/btcec/privkey.go#L61-L63) which doesn't do any additional computation (and also makes sure it takes the [smaller s](https://github.com/btcsuite/btcd/blob/ed77733ec07dfc8a513741138419b8d9d3de9d2d/btcec/signature.go#L442-L444) & provide an additional `Signature.Serialize()` method on the returned pub-key (simply append s || r, or, directly return r || s in the `Sign` method if we do not need the Signature struct

We would need to wrap the verify method anyways AFAIU (independent from if use SignCompact or not).

> Its probably on a scale thats irrelevant here, but using that sign compact method will also take longer for the signer

That's true. It does try to recover the public key. Option 2) would not do this extra computation.

Just to be sure: The only requirements here are 1) that we do not want to allow "the bigger s" on verify (to prevent malleability) and 2) that there is a way to encode the signature as `r || s` to save some bytes (and to not change the encoding again).

**Comment by ValarDragon** [comment]
You're right, that should be `s`. Those are the only requirements AFAIK

**Comment by Liamsi** [comment]
I did some benchmarks comparing the current development branch with 
 - calling ethereum's `secp256k1.Sign` and ditching the last byte `v`/recovery byte (if `cgo` enabled) and
- calling btcec's PrivateKey.Sign (if `!cgo` / cgo not enabled) and manually reject sigs in non-lower-S form

here: https://github.com/tendermint/tendermint/pull/3234

**Comment by melekes** [comment]
Done in #3234.
