### ISSUE TITLE
crypto: support using libsecp256k1

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3163]
We currently use the Go implementation of secp256k1 by btcsuite: https://github.com/btcsuite/btcd/tree/master/btcec. It is not constant time, and hasn't received nearly as much scrutiny as libsecp256k1, used by Bitcoin and Ethereum.

So while we want to continue to have a native Go version, we should also building with the libsecp256k1 C library, and recommend that for production.

Related https://github.com/tendermint/tendermint/issues/3162

**Comment by ebuchman** [comment]
Note we should be able to use the pkg from go-ethereum as it's now liberally licensed: https://github.com/ethereum/go-ethereum/tree/master/crypto/secp256k1

We should review everything going on in there. 

Note they fallback to btcd if the CGO is not available: https://github.com/ethereum/go-ethereum/blob/461291882edce0ac4a28f64c4e8725b7f57cbeae/crypto/signature_nocgo.go

**Comment by melekes** [comment]
Done in #3234.
