### ISSUE TITLE
proposer priority fixes follow up

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3166]
Follow up to #3049

- Clarify whether the maximum difference should be TotalVotingPower or 2*TotalVotingPower (https://github.com/tendermint/tendermint/pull/3049#discussion_r249140957)
- Consider whether we need to avg the priorities more frequently (https://github.com/tendermint/tendermint/pull/3049#discussion_r249139319)

**Update**: TODOs we (@ancazamfir, @cwgoes, @Liamsi) collected during a call:

 - [ ] use max int32 as a bound for voting power while keeping voting power as int64; also make sure that total voting power doesn't exceed int64 (to avoid and remove clipping) (SDK-side PR: https://github.com/cosmos/cosmos-sdk/pull/3400) (@Liamsi)
 - [ ] make sure the priority computations don't exceed int64, e.g. during scaling if we do vp * tvp/.. (@Liamsi)
 - [ ] figure out bound for difference (max - min priority) in n-validator case, ensure we respect it (we should not normalize more tightly) (@cwgoes, @Liamsi )
- [ ] formalize fairness proof and priority difference bounds in LaTeX doc (@cwgoes, @Liamsi )
- [x] treat validator set changes as a set and apply them atomically #3181 #3222 (@ancazamfir )
- [x] While addressing #3181 move priorities.go:updateValidators() to validator_set.go and write unit tests in validator_set_test.go (@ancazamfir)
- [ ] update spec/documentation (@ancazamfir)

__Update__ (Feb 8):

#3181 has been fixed. But the fix included a large refactor of the validator updating code that spawned some follow up requests in the reviews. Please see the reviews in #3222. Main items for follow up:

- [ ] Better error handling instead of panicing (https://github.com/tendermint/tendermint/pull/3222#issuecomment-461757136)
- [ ] Test cleanup if possible (https://github.com/tendermint/tendermint/pull/3222#discussion_r254254894)
- [ ] Cleanup `processChanges` function (https://github.com/tendermint/tendermint/pull/3222#discussion_r255124628)
- [ ] Update ABCI documentation to specify validation rules around what is an invalid update (https://github.com/tendermint/tendermint/pull/3222#discussion_r254957923)

**Comment by ancazamfir** [comment]
I think we should move the averaging operation before incrementProposerPriority, ideally outside IncrementProposerPriority (best in the code that does the validator set update). This way priorities are guaranteed to be normalized and scaled and centered around 0 during the (possible 'times' multiple) calls to incrementProposerPriority.  But looks like a breaking change due to precision loss during averaging.

**Comment by Liamsi** [comment]
Another idea @cwgoes and me discussed during lunch was to only average when priorities are somewhere close to "clip" (overflow). We could also combine both approaches.

**Comment by ancazamfir** [comment]
Why? Is doing it at every vset change to expensive?

**Comment by ancazamfir** [comment]
I believe having a priority range of max TVP in stable conditions and 2*TVP when we see changes is fine. Eventually the range will shrink back to TVP. So limiting to 2 * TVP seems ok. 
For newly added validators we might reduce the priority from 9/8ths to 9/16ths during normalization though  the relative prio positions remain the same. Since we leave the voting powers unchanged, a high power validator will jump quickly ahead to be elected anyway.  So TVP all the time also seems ok to me.

**Comment by Liamsi** [comment]
> Why? Is doing it at every vset change to expensive?

No, probably, not. Only if frequent changes occur and nodes need to sync all these changes in a batch. Not sure if this is a concern though. It's probably easier to reason about to average every change (update/add/remove) and not only if prios are close to clipping.

> Is there a maximum times for which we will call incrementProposerPriority

Not that I know off. if we stick to averaging inside of incrementProposerPriority, we should average more often. I find it hard to argue how often though.

**Comment by Liamsi** [comment]
> Responded to the question on difference here - #3049 (comment)

That explanation makes a lot of sense. I find it surprising that @ebuchman's tests fail if we update to `TotalVotingPower` instead of `2*TotalVotingPower`. Reverting `-9/8 * TotalPower` isn't a concern there . It's surprising that the tests fail. Only `NewValidatorSet` is called and not `updateValidators` which would set to 9/8*total.

**Comment by ancazamfir** [comment]
Is there any guarantee that updateValidators() will be called with exact same 'updates' parameter at all nodes and for replays?
[add v1, rem v2, add v3] is different than [rem v2, add v1, add v3] and, if I read the code correctly,  produces different results.
Also, while adds and updates do not modify 'currentSet', the validator removals do. So for first list, add v3 prio will work with vset-v2 while add v1 on vset. v1 will be penalized more than v3. Maybe we should order updates? (e.g. removes first, updates and adds after)

**Comment by ebuchman** [comment]
> I think we should move the averaging operation before incrementProposerPriority, ideally outside IncrementProposerPriority (best in the code that does the validator set update). This way priorities are guaranteed to be normalized and scaled and centered around 0 during the (possible 'times' multiple) calls to incrementProposerPriority. But looks like a breaking change due to precision loss during averaging.

This sounds like the right approach but I worry that so much responsibility is put on consumers of the validator set to manage the proposer selection properly. So it might make more sense to just do the averaging at the start of every call to IncrementProposerPriority.

I was thinking that doing it only when valset changes later on would not be breaking, because we're just shifting left and right. How can the averaging operation change the election order?

**Comment by ancazamfir** [comment]
I think we agree in general, by 'outside IncrementProposerPriority()' I meant inside add/ remove functions of validator_set.go. I don't think we need to do it every time we call IncrementProposerPriority(), just when there is a trigger that distorts our desired properties. 
>  How can the averaging operation change the election order?
Today, after change, we run incrementProposerPriority() and then we average. If we do average before incrementProposerPriority() I think it's a breaking change. For example if the highest 2 prios are different before the average, but same after and then the ex-smaller is elected because of the address ordering...??

**Comment by Liamsi** [comment]
Regarding:

> Clarify whether the maximum difference should be TotalVotingPower or 2*TotalVotingPower 

TotalVotingPower works just fine, too: https://github.com/tendermint/tendermint/pull/3182

**Comment by ancazamfir** [comment]
Trying to see if I need to update the spec:
Looking at the code changes (threshold is totalVotingPower):
...
	diff := computeMaxMinPriorityDiff(vals)
	ratio := diff / threshold
	if ratio > 1 {            <--- same as 'if ratio >=2 {'
               // scale here
        }
...

this means we scale as before to 2*totalVotingPower (??)  Is that the intent? 
Maybe to be more clear just explicitly do:
    if diff > threshold {
or 
    if diff > 2 * threshold {

**Comment by ebuchman** [comment]
v0.29.0 is prepared. The above, and the new bug discovered in #3181, will be bumped to v0.30.0

**Comment by Liamsi** [comment]
Thanks @ancazamfir. Yes, this should be `if diff > threshold` now. Thanks for the early review!

**Comment by ancazamfir** [comment]
I am/ was trying to formally prove that in a stable state max distance between prios is <=TVP. And I keep getting something like TVP+combo(VP(i)). I will look at it more but I think we can get close to 2*TVP. In the meantime I wrote a Python script and for [1,3,5] voting power, ran 9 times and indeed at one point the distance is 10. We end up scaling even in steady state. I think we will probably have  to go back and scale if diff > 2 * TVP

Here is the output for the example above (TVP=9):
>>> prio(v)
Init: [(1, 0), (3, 0), (5, 0)] dist: 0
-----
Run 0 : [(5, -4), (1, 1), (3, 3)] dist: 7
-----
Run 1 : [(3, -3), (5, 1), (1, 2)] dist: 5
-----
Run 2 : [(5, -3), (3, 0), (1, 3)] dist: 6
-----
Run 3 : [(1, -5), (5, 2), (3, 3)] dist: 8
-----
Run 4 : [(1, -4), (5, -2), (3, 6)] dist: 10
-----
Run 5 : [(1, -3), (3, 0), (5, 3)] dist: 6
-----
Run 6 : [(1, -2), (5, -1), (3, 3)] dist: 5
-----
Run 7 : [(3, -3), (1, -1), (5, 4)] dist: 7
-----
Run 8 : [(1, 0), (3, 0), (5, 0)] dist: 0

**Comment by Liamsi** [comment]
I also noticed that with TVP Bucky's tests rarely miss the expected frequencies:
https://github.com/tendermint/tendermint/blob/d9d4f3e6292c100e2c0a06c16d0a9cd4b6508255/state/state_test.go#L383

**Comment by cwgoes** [comment]
>  In the meantime I wrote a Python script and for [1,3,5] voting power, ran 9 times and indeed at one point the distance is 10.

Can you share your code? Those outputs don't look right to me - `power` is added *before* the proposer is selected, so the validator with the highest `power` (of `5` in your example) should be the first proposer.

**Comment by ancazamfir** [comment]
Before I didn't print the intermediate state after +=vp and the proposer sel. I added now more debugs, showing after +=vp, proposer and then -=tvp for proposer and distance. Here is the code:
```
prio(vset):
    import operator
    l = len(vset)
    vd = {v:0 for v in vset}
    svi = sorted(vd.items(), key=operator.itemgetter(1))
    print("Init:", svi, "dist:", 0)
    maxd = 0
    tvp = sum(vset)
    for k in range(tvp):
        for v in vset:
            vd[v] += v
        p = max(vd, key=vd.get)
        print("Run", k, ":\tafter += v =>", list(vd.items()), "proposer:", p)
        vd[p] -= tvp
        svl = sorted(vd.items(), key=operator.itemgetter(1))
        dist = vd[max(vd, key=vd.get)] - vd[min(vd, key=vd.get)]
        if maxd < dist:
            maxd=dist
        print("\tafter -= tvp =>", svl, "dist:", dist)
    print("Max distance", maxd)
```
and the results:
```
Init: [(1, 0), (3, 0), (5, 0)] dist: 0
Run 0 :	after += v => [(1, 1), (3, 3), (5, 5)] proposer: 5
	after -= tvp => [(5, -4), (1, 1), (3, 3)] dist: 7
Run 1 :	after += v => [(1, 2), (3, 6), (5, 1)] proposer: 3
	after -= tvp => [(3, -3), (5, 1), (1, 2)] dist: 5
Run 2 :	after += v => [(1, 3), (3, 0), (5, 6)] proposer: 5
	after -= tvp => [(5, -3), (3, 0), (1, 3)] dist: 6
Run 3 :	after += v => [(1, 4), (3, 3), (5, 2)] proposer: 1
	after -= tvp => [(1, -5), (5, 2), (3, 3)] dist: 8
Run 4 :	after += v => [(1, -4), (3, 6), (5, 7)] proposer: 5
	after -= tvp => [(1, -4), (5, -2), (3, 6)] dist: 10
Run 5 :	after += v => [(1, -3), (3, 9), (5, 3)] proposer: 3
	after -= tvp => [(1, -3), (3, 0), (5, 3)] dist: 6
Run 6 :	after += v => [(1, -2), (3, 3), (5, 8)] proposer: 5
	after -= tvp => [(1, -2), (5, -1), (3, 3)] dist: 5
Run 7 :	after += v => [(1, -1), (3, 6), (5, 4)] proposer: 3
	after -= tvp => [(3, -3), (1, -1), (5, 4)] dist: 7
Run 8 :	after += v => [(1, 0), (3, 0), (5, 9)] proposer: 5
	after -= tvp => [(1, 0), (3, 0), (5, 0)] dist: 0
Max distance 10
```

**Comment by ancazamfir** [comment]
Even 2*tvp is passed:
```
For V= [1, 20, 300, 4000, 50000, 600000] , TVP= 654321 , Maxdist= 1366513
```
It seems that with very high power proposers, the next big proposers keep doing accum(i)+=vp(i) trying to get to be elected but the big validator wins. So the max(A(i)) is pushed out significantly more and more. In the meantime, the low power validator, once elected, sets the min very low. So the window min increases very slowly while the max much faster.
Below some dumps...just watch how the distance increases just before we pass the 2 * tvp. And the accum of '4000' and '50000' getting higher and higher while '600000' is being elected
```
>>> prio_big([1, 20, 300, 4000, 50000, 600000])
For V= [1, 20, 300, 4000, 50000, 600000] , TVP= 654321 , Maxdist= 1366513
Proposer freq: {1: 1, 20: 20, 300: 300, 4000: 4000, 50000: 50000, 600000: 600000} total: 654321 
Run 135472 : proposer 1 ,svl:  [(1, -518848), (300, 73998), (20, 92176), (4000, 114212), (50000, 119008), (600000, 119454)] dist: 638302
Run 145400 : proposer 600000 ,svl:  [(1, -508920), (20, -363585), (300, -219207), (600000, -18930), (50000, 543690), (4000, 566952)] dist: 1075872
Run 145401 : proposer 50000 ,svl:  [(1, -508919), (20, -363565), (300, -218907), (50000, -60631), (4000, 570952), (600000, 581070)] dist: 1089989
Run 145402 : proposer 600000 ,svl:  [(1, -508918), (20, -363545), (300, -218607), (50000, -10631), (600000, 526749), (4000, 574952)] dist: 1083870
Run 145403 : proposer 600000 ,svl:  [(1, -508917), (20, -363525), (300, -218307), (50000, 39369), (600000, 472428), (4000, 578952)] dist: 1087869
Run 145404 : proposer 600000 ,svl:  [(1, -508916), (20, -363505), (300, -218007), (50000, 89369), (600000, 418107), (4000, 582952)] dist: 1091868
Run 145405 : proposer 600000 ,svl:  [(1, -508915), (20, -363485), (300, -217707), (50000, 139369), (600000, 363786), (4000, 586952)] dist: 1095867
Run 145406 : proposer 600000 ,svl:  [(1, -508914), (20, -363465), (300, -217407), (50000, 189369), (600000, 309465), (4000, 590952)] dist: 1099866
Run 145407 : proposer 600000 ,svl:  [(1, -508913), (20, -363445), (300, -217107), (50000, 239369), (600000, 255144), (4000, 594952)] dist: 1103865
Run 145408 : proposer 600000 ,svl:  [(1, -508912), (20, -363425), (300, -216807), (600000, 200823), (50000, 289369), (4000, 598952)] dist: 1107864
Run 145409 : proposer 600000 ,svl:  [(1, -508911), (20, -363405), (300, -216507), (600000, 146502), (50000, 339369), (4000, 602952)] dist: 1111863
Run 145410 : proposer 600000 ,svl:  [(1, -508910), (20, -363385), (300, -216207), (600000, 92181), (50000, 389369), (4000, 606952)] dist: 1115862
Run 145411 : proposer 600000 ,svl:  [(1, -508909), (20, -363365), (300, -215907), (600000, 37860), (50000, 439369), (4000, 610952)] dist: 1119861
Run 145412 : proposer 600000 ,svl:  [(1, -508908), (20, -363345), (300, -215607), (600000, -16461), (50000, 489369), (4000, 614952)] dist: 1123860
Run 145413 : proposer 4000 ,svl:  [(1, -508907), (20, -363325), (300, -215307), (4000, -35369), (50000, 539369), (600000, 583539)] dist: 1092446
Run 145414 : proposer 600000 ,svl:  [(1, -508906), (20, -363305), (300, -215007), (4000, -31369), (600000, 529218), (50000, 589369)] dist: 1098275
Run 145415 : proposer 600000 ,svl:  [(1, -508905), (20, -363285), (300, -214707), (4000, -27369), (600000, 474897), (50000, 639369)] dist: 1148274
Run 145416 : proposer 600000 ,svl:  [(1, -508904), (20, -363265), (300, -214407), (4000, -23369), (600000, 420576), (50000, 689369)] dist: 1198273
Run 145417 : proposer 600000 ,svl:  [(1, -508903), (20, -363245), (300, -214107), (4000, -19369), (600000, 366255), (50000, 739369)] dist: 1248272
Run 145418 : proposer 600000 ,svl:  [(1, -508902), (20, -363225), (300, -213807), (4000, -15369), (600000, 311934), (50000, 789369)] dist: 1298271
Run 145419 : proposer 600000 ,svl:  [(1, -508901), (20, -363205), (300, -213507), (4000, -11369), (600000, 257613), (50000, 839369)] dist: 1348270
```

**Comment by cwgoes** [comment]
Hmm, good testing, going to try to run that script in a bit - to be clear, the proof [here](https://github.com/cwgoes/tm-proposer-idris) only applies to the case of two validators, not n-validators - perhaps the bound on n-validators is `(n - 1) * TVP` or something like that instead.

**Comment by ancazamfir** [comment]
Understood. 
This was to correct my earlier statement and belief that we should scale only on validator set changes because the max-min is never > TVP. I was wrong (again!)
At this point I don't know what the bound is, how high it can get, etc.

**Comment by rigelrozanski** [comment]
Just curious why not make the input abci validator power int32 directly if it's supposed to be bound by those values. (further could convert into int64 within tendermint for calculations)

**Comment by ebuchman** [comment]
Updated opening post with more follow up from #3222
