### ISSUE TITLE
Add more tutorial plz 

### ISSUE THREAD

**Issue by bakatest-me** [tendermint/tendermint#3169]
I'm try to build DApp with Tendermint use Golang 
Can you make tutorial simple app guide step by step.
Thank you.
P.S. I read your but i can't 
I'm find a lots in google , youtube, ..... not found step by step like when i learn programing ... Thank you again

**Comment by ebuchman** [comment]
> For Cosmos-sdk look good but when i write program wanna run program step by step not wanna build all of code and run in final. T^T

I wrote a step-by-step guide for the SDK some time ago. It seems it's not being maintained but you might find it helpful. See the `appX` files, in order, each is a self contained tutorial that builds on that last:

https://github.com/cosmos/cosmos-sdk/tree/develop/docs/_attic/sdk/core

**Comment by jackzampolin** [comment]
There is also an SDK application tutorial that might have some good content for you: https://github.com/cosmos/sdk-application-tutorial (not tendermint related!)

**Comment by bakatest-me** [comment]
I read through. it's look good. will try again
@ebuchman Thank Bro so much. >///<

**Comment by melekes** [comment]
There's also https://github.com/6thc/tendermint-cas-demo

**Comment by gauthamzz** [comment]
It would be nice, if you guys could improve the documentation a bit or if someone who knows very well make a course(eth has a lot of content). Its very difficult to understand.

**Comment by jackzampolin** [comment]
@gauthamzz We are working very hard to improve documentation, and there are a number of resources linked here. If you have any specific pieces of documentation you would like to see please open an issue, or comment here. We also accept PRs for any and all of the repositories! 😉

**Comment by bakatest-me** [comment]
@jackzampolin keep fighting bro.
I think for now i can start with Tendermint a little bit 
If i complete my project i will write tutorial at Medium
wish it help another too

**Comment by jackzampolin** [comment]
Looking forward to it @bakatest-me !!

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/issues/3808
