### ISSUE TITLE
lite: move concurrency logic from DynamicVerifier into a new ConcurrentDynamicVerifier

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3170]
The `DynamicVerifier` allows requests to be made asynchronously so we can process many at once.

This is useful, but it clouds the logic of the dynamic verification. In the spirit of separating concerns, it should be moved into a new ConcurrentDynamicVerifier which embeds a DynamicVerifier and handles the concurrency. This would make the DynamicVerifier unsafe for use from go-routines - users would be expected to use the ConcurrentDynamicVerifier.

**Comment by jaekwon** [comment]
There's no need to expose a separate non-concurrent dynamic verifier, that just makes usage more confusing, so DynamicVerifier should just be concurrent, regardless of what it's decomposed into.

Currently there's a single concurrency lock on DynamicVerifier.Verify() in 15 lines of code, which is conceptually pretty simple.  To improve this system further, we'd need more than just a Concurrent* wrapper struct.  Closing to revisit after some more updates.
