### ISSUE TITLE
lite: consolidate behaviour in BaseVerifier and DynamicVerifier

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3172]
We have the method:

`func (v * XxxVerifier) Verify (signedHeader  types.SignedHeader) error {`

In the BaseVerifier, if `signedHeader.Height < v.height`, we return an error (ie. we won't verify an old commit).

But in DynamicVerifier, we don't have such a check, so it looks like we will verify older commits.

Is there some reason for this divergence in behaviour? 

If not, we should eliminate it. Probably both should be able to verify old commits. We should write tests and docs about this as well.

**Comment by ebuchman** [comment]
Actually this is already documented, but it's not clear to me why it's the case. @ethanfrey do you know if there's some reason? Why can't BaseVerifier verify SignedHeaders from the past? 

```
// BaseVerifier lets us check the validity of SignedHeaders at height or
// later, requiring sufficient votes (> 2/3) from the given valset.
```

**Comment by ethanfrey** [comment]
The current rules to jump forward (h to h+n) and the requirements of signatures I have validated as correct mathematically. For the backwards jump, someone must go through and verify it is correct mathematically, or if we need a new function

There is also the issue of the unbonding period... moving backwards before the unbonding period is unsafe.

There is well-defined safe rule for moving backwards, but only by one header at a time, which is ensuring the header hash of `h-1` is equal to the "last header" field from `h`. This is probably the most secure rule of all. But jumping back with partial sigs and worrying about unbonding period? Maybe get @cwgoes to analyze it with you can implement what you determine to be correct.

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/pull/3989. I am still unsure if somebody will need to verify already trusted headers. However, I am still planning to add a separate `VerifyTrusted` / `Recheck` function as a part of the cross checking with the alternative header providers.
