### ISSUE TITLE
lite: cleanup and write more tests

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3173]
A bug in the DynamicVerifier is indicative of insufficient tests: #2862

A test was written and the bug fixed in #3171. 

However, we should write much more extensive tests for the lite client functionality. Ideally, the tests will have a structure that makes it easy to specify new cases. The existing tests could also use some cleanup. We should test all error paths as well.

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/pull/3989.
