### ISSUE TITLE
lite: clarify behaviour in DynamicVerifier

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3174]
The DynamicVerifier verifies a SignedHeader by first updating to a `FullCommit` for `SignedHeader.Height - 1`. Then it should have `FullCommit.NextValidatorSet.Hash() == SignedHeader.ValidatorsHash` and can verify the signatures.

It verifies this using a BaseVerifier once it has all the data.

Then, to update to a `FullCommit` for height `SignedHeader.Height`, it needs the validator set for `SignedHeader.Height + 1`.

The current behaviour is as follow:
- if it can't get this validator set, return no error
- if it can get this validator set, check that it matches the `SignedHeader.NextValidatorsHash`, and if not, return an error
- if it can get this val set, it matches, and it verifies, then save the new full commit and return no error

First, why do we ignore the error if we can't get the validator set? If it's because Tendermint doesn't expose the next validator set for the latest block over `/validators`, then maybe we can fix that.

Second, it seems we're doing a full verification of the commit twice: once with the BaseVerifier, and once with the FullCommit:

https://github.com/tendermint/tendermint/blob/07263298bd76f1ea7ad82f8e06234a450150d76c/lite/dynamic_verifier.go#L139-L141

and 

https://github.com/tendermint/tendermint/blob/07263298bd76f1ea7ad82f8e06234a450150d76c/lite/dynamic_verifier.go#L155-L163

It seems the latter verification is mostly redundant. The only part that's needed from it is checking the NextValidatorSet matches up.

We should investigate and clean this up if it's indeed true. 

Related: #3173

**Comment by Liamsi** [comment]
I can confirm that `nfc.ValidateFull` does mostly redundant work:

Even `BaseVerifier.Verify`  by itself does a few things twice: `SignedHeader.ValidateBasic` calls `sh.Commit.ValidateBasic()` which again is called inside of `bv.valset.VerifyCommit` (with the same commit).

Additional redundant  checks repeated in `FullCommit.ValidateFull`:

 - `SignedHeader.ValidateBasic` is called again (on the same signed header)
 - `ValidatorSet.VerifyCommit` is called again (on the same validator set)
   - note that both call `Commit.ValidateBasic` again (4 times in total)
- signedHeader.ValidatorsHash == ValidatorSet.Hash() is checked again

As explained in the original comment there are some checks that are done in `FullCommit.ValidateFull` which are not done before though. Namely checking that the retrieved next validator set (via `dv.source.ValidatorSet(dv.chainID, shdr.Height+1)`) matches the `NextValidatorsHash` in the signed header:
https://github.com/tendermint/tendermint/blob/e0f8936455029a40287a69d5b0e7baa4d5864da1/lite/commit.go#L49-L60

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/pull/3989.
