### ISSUE TITLE
Better support for experimenting with reactors

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3176]
A number of issues have called for experimentation with reactors:
- #476 - a message passing reactor
- #2187, #2147 - alternative mempool designs

There's also issues to allow users to specify certain reactors/functionality not to run
- #2233 - run without mempool (like setting size to 0)
- #1686 - run without the app
- #2237 - tendermint modes
- #1148 - check peer channels 

And of course we're still looking to add a state-syncing reactor: #828

Taken together they suggest the need for better interfaces to composing the set of reactors and substructures that constitute the node. 

As suggested in https://github.com/tendermint/tendermint/issues/476#issuecomment-454462464, we should consider refactors to the `node` package that simplify extending tendermint nodes with custom functionality without forking the repo or copying all of `node/node.go`. 

Copying `node.go` isn't the worst as is, but we can probably do much better to minimize what needs to be copied.

**Comment by ebuchman** [comment]
Noting we could also use this to facilitate refactors like https://github.com/tendermint/tendermint/issues/2897, especially if they will require large overhauls of existing code that are difficult to do incrementally

**Comment by ebuchman** [comment]
Looks like Loom has implemented injecting custom reactors into their fork of Tendermint: https://github.com/mattkanwisher/tendermint/pull/1/files.

It would be super easy to upstream this change, but I think it only allows the addition of completely independent reactors (ie. these reactors can't interact with other ones or with the application). Ideally we'd have some interface for enabling them to interact in well defined ways. For instance see the way the consensus reactor calls the `Update` method on the evidence and mempool reactors by passing data from a new block.

**Comment by ebuchman** [comment]
Some initial work towards improving structure in the node package: https://github.com/tendermint/tendermint/pull/3456 cc @thanethomson

**Comment by ebuchman** [comment]
Just a note that some reactors may require their own explicit interface or designation, especially since they need to connect to one another. 

For instance, we have the following coupling between reactors:

- blockchain <-> consensus (ie. SwitchToConsensus)
- mempool <-> consensus (ie. Update and Reap)
- evidence <-> consensus (ie. Update)

Did I miss anything?

Perhaps we start by using the default reactor set and allowing folks to pass in arbitrary other reactors, so they can at least pass in independent reactors that don't connect explicitly to the others.

Then we can start surfacing existing reactors one at a time, say starting with the Mempool.

Perhaps the best way to do it is to pass in closure constructors, or use something like the options pattern and pass in the Node object? We need some way for these injected reactors to get access to the things they need, like the underlying ABCI connection. 

I would make as an initial goal to be able to inject Mempool and StateSync reactors.

**Comment by marbar3778** [comment]
This had been done and released recently (0.32.2), but this is the first step, now we have to organize on the decoupling of reactors

> Just a note that some reactors may require their own explicit interface or designation, especially since they need to connect to one another.

For instance, we have the following coupling between reactors:

blockchain <-> consensus (ie. SwitchToConsensus)
mempool <-> consensus (ie. Update and Reap)
evidence <-> consensus (ie. Update)

**Comment by shumy-tools** [comment]
I think #476 was closed to soon. There are very good use cases for this: threshold cryptography, integrated onion routing, distributed message brokers, etc. I was expecting such a feature to be present because the required framework is already being used.
