### ISSUE TITLE
Treat the validator updates from the application as an unordered set

### ISSUE THREAD

**Issue by ancazamfir** [tendermint/tendermint#3181]
When the application updates the validator set it calls updateValidators() with an 'updates' parameter, a list of changes that is then parsed in order, one entry at a time, making updates for the corresponding validator. i.e. the list is treated as a transaction list.
For example [add v1, rem v2, add v3] is different than [rem v2, add v1, add v3] and the call with one will produce different results than with the other.
This is an issue for gaia that requires these updates to be instead interpreted as a set.

**Comment by kevlubkcm** [comment]
sounds related to #3073

**Comment by cwgoes** [comment]
Proposal:

- First apply all updates to the validator set, without setting priorities. Track a list of addresses of newly added validators.
- Calculate the total voting power of the new validator set.
- Set the priorities of all newly added validators to `-C * total voting power` (presently `C = 1.125`).
- Normalize priorities if necessary & subtract the average.

**Comment by ancazamfir** [comment]
> Proposal for atomic application:
First apply all updates to the validator set, without setting priorities. Track a list of addresses of newly added validators.

all updates except the validator removals
> Calculate the total voting power of the new validator set.
Set the priorities of all newly added validators to -C * total voting power (presently C = 1.125).

do validator removals here
>Normalize priorities if necessary & subtract the average.
Also we should consider if we need C = 1.125 after this change.

**Comment by ebuchman** [comment]
Merged! Thanks @ancazamfir !
