### ISSUE TITLE
p2p: remove Cleanup from Transport interface

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3183]
In #3150 we fixed a resource leak where connections weren't being closed properly if the peer was never started (due to too many inbound peers).

The solution in that PR adds a `Cleanup` method to the `Transport` interface which must be called before calling `peer.Stop`. This was done to avoid having the peer magically clean things up in the transport, and to keep the Peer and Transport decoupled. 

The need for this `Cleanup` comes from the fact that the transport implementation tracks the IP addresses of peers we're connected to, so as to not connect to a duplicate IP. So when the peer stops, it's address needs to be removed.

While decoupling of components is in general a virtue, it seems in this case the Peer and Transport are genuinely coupled. The property that the peer doesn't know about the transport sounds nice in spirit, but in practice, as far as I understand here, the implementations of Peer and Transport are already tightly wound - a particular implementation of Transport returns a particular implementation of Peer, and a particular implementation of Peer is expected to come from a particular implementation of Transport. So Peer in general doesn't need to know about Transport, but if the Transport that created it necessitates some cleanup, then it surely will.

By pushing this implicit coupling into an extra responsibility for callers to call `transport.Cleanup` before calling `peer.Stop`, we're just asking them to forget about it. If we have transports that don't require this cleanup, then we're just cluttering the Transport interface unnecessarily. 

We don't need to give the peer a direct reference to the transport. It could have some cleanup closure or a channel the Transport listens for. But the current separation seems prone to misuse.

**Comment by melekes** [comment]
I think if the caller is responsible for allocating resources, he should be the one responsible for cleaning them up. See https://github.com/tendermint/tendermint/pull/3150/#discussion_r249664692

**Comment by ebuchman** [comment]
That's a fair argument. But it's already the caller's responsibility to call `peer.Stop()`. If the caller has a responsibility for cleanup, it should ideally be a single call. So either it calls peer.Stop, which should cleanup the resources on the transport, or it should call transport.Cleanup(peer), which should stop the peer and cleanup the additional resources. Requiring it to call both is just asking for trouble.

I guess the problem is we can't just call `Stop`, because then we're back to the original problem, where the peer was never started!

So probably we should change Cleanup to call peer.Stop. Then the consumer only has to make the one call - `transport.Cleanup(peer)`

Thoughts?

**Comment by melekes** [comment]
> t's already the caller's responsibility to call peer.Stop(). If the caller has a responsibility for cleanup, it should ideally be a single call.

caller's desire to stop everything in a single call does not mean it should be done that way.

This probably deserves more thought. In the meantime, I think we can create a function

```
func (sw *Switch) stopPeer() {
	sw.transport.Cleanup(peer)
        if peer.IsRunning() {
	    peer.Stop()
        } 
}
```

or use existing `stopAndRemovePeer` function everywhere (we'd have to check that RemovePeer does not panic if the peer does not exist)

```
func (sw *Switch) stopAndRemovePeer(peer Peer, reason interface{}) {
	if sw.peers.Remove(peer) {
		sw.metrics.Peers.Add(float64(-1))
	}
	sw.transport.Cleanup(peer)
	peer.Stop()
	for _, reactor := range sw.reactors {
		reactor.RemovePeer(peer, reason)
	}
}
```

**Comment by tychoish** [comment]
This issue is longer relevant in the new P2P stack.
