### ISSUE TITLE
tools: support abci containers on localnet 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3192]
Would be great if the make-localnet tooling could also start abci containers, if requested. I'm not sure if docker-compose supports conditionals, or if this will need an additional docker-compose.yml. Not sure at what point we're asking too much of the Makefile, and whether this deserves a Go tool.

In any case, in the meantime, we should document for users how to do this.

Related: 
- user request: https://github.com/tendermint/tendermint/issues/3178
- config mgmt in localnet: https://github.com/tendermint/tendermint/issues/3160

**Comment by melekes** [comment]
> I'm not sure if docker-compose supports conditionals

Let's not make this too complicated. localnet was developed to debug Tendermint, and now we're trying to transform it to help app devs to debug their applications? Let's create a separate repo for this, not try to support everything through one file.

**Comment by melekes** [comment]
Merged docs update made by @gauthamzz to develop.

**Comment by ebuchman** [comment]
>  not try to support everything through one file.

Agree we should try to keep it simple. But I think we should offer some simple way within the repo to make it easy to run external ABCI apps.
