### ISSUE TITLE
abci: RequestDeliverTx and RequestCheckTx

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3193]
The ABCI protobuf uses `RequestXxx` types for all methods.

The ABCI interface we use in Go uses `RequestXxx` for all methods *except* `CheckTx` and `DeliverTx` because they were always just `tx []byte`.

However, issues like https://github.com/tendermint/tendermint/issues/2127 suggest we may need to provide more than just `tx []byte`. So we should start using `RequestXxx` for CheckTx and DeliverTx in the Go interface. 

This is non-breaking on ABCI itself, just on the Go API. Any code that imports the `abci` package would be affected.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3735 to develop.
