### ISSUE TITLE
Fail if theres no genesis time

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#320]
since otherwise it's a source of non-determinism (https://github.com/tendermint/tendermint/blob/master/state/state.go#L98)

**Comment by ebuchman** [comment]
also deal with https://github.com/tendermint/tendermint/blob/master/types/block.go#L35

**Comment by adrianbrink** [comment]
@ebuchman 
Shouldn't it fail in the unmarshalling process?
https://github.com/tendermint/tendermint/blob/master/types/genesis.go#L26

**Comment by odeke-em** [comment]
@adrianbrink, currently with GenesisDocFromJSON if the time is zero, we use the current time.

https://github.com/tendermint/tendermint/blob/7682ad9a60162dd17fd6f61aeed7049a8635ac78/types/genesis.go#L79-L81

And this sample
```go
package main

import (
	"log"

	"github.com/tendermint/tendermint/types"
)

func main() {
	doc, err := types.GenesisDocFromJSON([]byte(`{"chain_id": "foo", "validators": [{"power": 10}]}`))
	if err != nil {
		log.Fatalf("unmarshal Genesis: %v", err)
	}
	log.Printf("parsedGenesis: %v", doc)
}
```

```shell
$ go run main.go 
2017/09/28 19:17:22 parsedGenesis: &{2017-09-28 19:17:22.481431023 -0600 MDT m=+0.034307829 foo 0xc420026510 [{{<nil>} 10 }] }
```

**Comment by ebuchman** [comment]
replacing with https://github.com/tendermint/tendermint/issues/1146
