### ISSUE TITLE
Bring back PrivValidator.GetAddress

### ISSUE THREAD

**Issue by rickyyangz** [tendermint/tendermint#3200]
In issue #2981 , the PrivValidator interface removed GetAddress() method because it says people may  call GetAddress() after GetPubKey() again which results in twice remote calls. 

What my concern is that the PubKey.Address() method is not such cheap. Actually, we need to cache the address in the higher level. In most cases, we use FilePV which does not need remote calls. 

So how about we memorize the address in each kind of PrivValidators so that we can still expose the GetAddress() method in the interface and avoid another remote call.

**Comment by Liamsi** [comment]
Thanks for the suggestion @rickyyangz! 

> because it says people may call GetAddress() after GetPubKey() again which results in twice remote calls.

This would not have been a concern anymore as we memoize the pub-key and `GetAddress()` would not need to trigger a remote request anymore (even in the non-FilePV cases). So that would not be a major concern anymore. 
`PubKey.Address()` is a call to sha256 plus slicing an array. I do not think that is particularly expensive but you are right that we could memoize the address and further improve this!

**Comment by rickyyangz** [comment]
Thanks for your reply!  
Our app is very performance-sensitive,  so I hope we can improve this.  
I have created a PR https://github.com/tendermint/tendermint/pull/3202

**Comment by ebuchman** [comment]
> Our app is very performance-sensitive, so I hope we can improve this.

Can you provide some clarity on where/how/why your app is using the PrivValidator? I don't think anyone expected this structure to be used by an app, since it's meant for the Tendermint validator.

**Comment by rickyyangz** [comment]
> Can you provide some clarity on where/how/why your app is using the PrivValidator? I don't think anyone expected this structure to be used by an app, since it's meant for the Tendermint validator.

Sorry, I didn't meant that our app directly uses the PrivValidator, but it needs very high performance and **short block interval.**  
IMHO, `GetAddress()` is called much more frequently than `GetPubKey()`, so I think exposing `GetAddress` is valuable.
Thanks!

**Comment by ebuchman** [comment]
Think we should close this for now.
