### ISSUE TITLE
Tendermint smart contract

### ISSUE THREAD

**Issue by gunvant** [tendermint/tendermint#321]
I am looking for a documentation or help from where i can get a help regarding how to write, deploy, invoke smart contract which is written in either java, .NET language.

Can anyone help me into this?

**Comment by ebuchman** [comment]
Hello,

The best I can do is direct you to the fine work of the jTMSP group, who have written a tmsp server in java and some apps: https://github.com/jtmsp/

There is an example chat app here: https://github.com/wolfposd/tmchat

Please join our slack if you have more hands-on/support style questions! http://forum.tendermint.com:3000/
