### ISSUE TITLE
Batch requests in JSON-RPC

### ISSUE THREAD

**Issue by tomtau** [tendermint/tendermint#3213]
JSON-RPC 2.0 specs allow sending multiple requests at a time: https://www.jsonrpc.org/specification#batch

Currently, Tendermint RPC will return a parser error if it receives an array of requests.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3534 to develop. Check out https://godoc.org/github.com/tendermint/tendermint/rpc/client once v0.31.5 is out.
