### ISSUE TITLE
log issue in resCbRecheck

### ISSUE THREAD

**Issue by rickyyangz** [tendermint/tendermint#3214]
https://github.com/tendermint/tendermint/blob/4d7b29cd8f8ef998cf8f7141f3a100b0a4fa718d/mempool/mempool.go#L406-L419

The log 
> `fmt.Sprintf( 
 					"Unexpected tx response from proxy during recheck\nExpected %X, got %X", 
 					r.CheckTx.Data, 
 					memTx.tx, 
 				)` 

is not correct, the expected is the `Response` while the got is `Request` which makes the comparison confusing.

I think it can be changed to 
> `fmt.Sprintf(
					"Unexpected tx response from proxy during recheck\nExpected %X, got %X",
					req.GetCheckTx().Tx,
					memTx.tx,
				)`

**Comment by melekes** [comment]
Yeah, I think `r.CheckTx.Data` and `memTx.tx` need to be swapped:

```go
				fmt.Sprintf(
					"Unexpected tx response from proxy during recheck\nExpected %X, got %X",
					memTx.tx,
					r.CheckTx.Data,
				),
```

Want to send a PR? 😄

**Comment by rickyyangz** [comment]
Created a PR, @melekes please help review😄

**Comment by melekes** [comment]
Awesome, thanks!

**Comment by melekes** [comment]
Merged to develop. Should land in 0.29.2 🚀
