### ISSUE TITLE
replay_console might be broken

### ISSUE THREAD

**Issue by kunaldhariwal** [tendermint/tendermint#3215]
Hi, When i run `tendermint replay_console` it does not display any output.
I think this might be broken.

**Comment by melekes** [comment]
Want to help us fix it? There's also an issue https://github.com/tendermint/tendermint/issues/349 about tests & docs.

**Comment by kunaldhariwal** [comment]
Yeah, According to the issue linked in the comment above, it says that this feature is disabled and we need to write and run the tests for it.

**Comment by ebuchman** [comment]
Yeh it's not currently maintained. If you want to update it to make it work that'd be amazing.

Let's close this for #349 though :)
