### ISSUE TITLE
validator update_time is valid but incorrect for first validator in local testnet

### ISSUE THREAD

**Issue by jbibla** [tendermint/tendermint#3226]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Cosmos SDK v0.30.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
MacOS

**What happened**:
when you start a local network with one validator the commission `update_time` will default to a date that is technically Jan. 1, year 1. this is a valid but incorrect date.

**What you expected to happen**:
i would have expected this field to be either the "datetime" when the validator joined the network and establishes the expected commission data for the first time, or null.

**How to reproduce it** (as minimally and precisely as possible):
follow steps here: https://cosmos.network/docs/gaia/deploy-testnet.html#single-node-local-manual-testnet
`gaiacli query staking validator <address> --trust-node`
returns `commission.updateTime: 0001-01-01 00:00:00`

**Thank you all!**

_Originally opened here https://github.com/cosmos/cosmos-sdk/issues/3411_

**Comment by melekes** [comment]
What is updateTime? What are you using as a source? block#header#time?

**Comment by melekes** [comment]
Have you tried to reproduce with just Tendermint? `make localnet-start`?

**Comment by jbibla** [comment]
updateTime is the last time the validator commission changed.

no i haven't tried reproducing with a tendermint localnet.

did you see this comment from chris? https://github.com/cosmos/cosmos-sdk/issues/3411#issuecomment-458344359

**Comment by alexanderbez** [comment]
I think this can be closed @melekes -- this is an SDK issue all along. Sorry for the back n forth @jbibla :)
