### ISSUE TITLE
privval: non-deterministic test failure on TestSocketPVVoteKeepalive

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#3237]
Attempting to run `make test_cover` from `develop` at present sometimes results in the following test failure emanating from `privval/client_test.go`:

```
--- FAIL: TestSocketPVVoteKeepalive (3.45s)
        Error Trace:    client_test.go:182
                        client_test.go:184
        Error:          Received unexpected error:
                        unmarshal to privval.RemoteSignerMsg failed after 4 bytes (unrecognized prefix bytes 48A6160A): 48A6160A5208022A0C088CB7CBE20510A0A0CBD0024240B72B728C333414BD783F5127DCAA67D4561F3C4E76FA55E272207418167F673B68483A8281243C65B5123536715EE4BC2CF6B2E3FF666BEDE4134DFE57E6600904
        Test:           TestSocketPVVoteKeepalive
```

This first occurred on CircleCI [here](https://circleci.com/gh/tendermint/tendermint/43647?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) and was replicated locally by running:

```bash
make test_cover
```

This test, however, does *not* fail when running:

```bash
GOCACHE=off go test -cover -race ./privval
ok  	github.com/tendermint/tendermint/privval	2.766s
```

**Comment by ebuchman** [comment]
So I'm able to replicate this problem locally on a different test:

```
--- FAIL: TestSocketPVVoteResetDeadline (3.24s)
        Error Trace:    client_test.go:151
                        client_test.go:160
        Error:          Received unexpected error:
                        unmarshal to privval.RemoteSignerMsg failed after 4 bytes (unrecognized prefix bytes A6160A52): A6160A5208022A0C08BC8AE8E20510B89999AC0142401247FD2842C677B57CB2664AC12B50FDA3418AD259D6D02DA6FA607E578E4D928F75CFEDBD0639D0CB71F028BFC99D5C75B7997A1795E7197D95821E87D4100E04A2
        Test:           TestSocketPVVoteResetDeadline
FAIL
coverage: 44.2% of statements
exit status 1
FAIL    github.com/tendermint/tendermint/privval        3.299s
```

It seems that the first 2 bytes of the prefix bytes are being read first. Ie. the SignVoteResponse prefix bytes look like `0xB248A616` but here we have a message that starts with the second two of those bytes, `A616`.

Similarly, in the result you posted, the message starts with `48A616`, which suggests the first byte got caught off!

I think this might be due to a race condition with Pings happening at the same time as SignVote request sine we're only using an RMutex, not a full mutex!

**Comment by ebuchman** [comment]
Seems like using a full lock makes me unable to reproduce this again. Seems this bug would exist outside the tests then as well!

**Comment by ebuchman** [comment]
Oh duh, I wrote about this potential issue here: https://github.com/tendermint/tendermint/issues/3107

**Comment by joe-bowman** [comment]
> Seems like using a full lock makes me unable to reproduce this again. Seems this bug would exist outside the tests then as well!

To confirm, we have replicated this twice in Cosmos mainnet.

**Comment by ebuchman** [comment]
@joe-bowman Can you please open a new issue describing versions you're using and what you're seeing - thanks!
