### ISSUE TITLE
How to configure validator node into different machine without docker?

### ISSUE THREAD

**Issue by gunvant** [tendermint/tendermint#324]
Hi, 

I  have 4 different machines and I want to configure Tendermint validator node into these 4 machine manually (without docker) and it should be connected with each other to run consensus algorithm

Like in Ethereum, We have to provide networkid, host and port to start the node. By using these arguments, Ethereum Node has been connected with each other and create a  blockchain network. 

I do not know how Tendermint validators node can connect with each other? Is there any networkid concept like Ethereum? I am not able to find any configruation file in tendermint where i can provide machine details (like ip, networkid, port) or Does tendermint has different concept?

Can someone help me into this? kindly share documents.

**Comment by ebuchman** [comment]
if you have the `ip:port` of the nodes, you can pass it on the command line using the `--seeds` flag.  Eg. `tendermint node --seeds 1.2.3.4:46656,5.4.3.2:46656`. You can also specify seeds in the `~/.tendermint/config.toml`.

We definitely need to document this properly - thanks. 

The network id (chain_id) is set in the genesis.json.

**Comment by gunvant** [comment]
I tried using --seeds but it throws below error

goroutine 1 [running]:
panic(0xba59a0, 0xc082008020)
        C:/Go/src/runtime/panic.go:481 +0x3f4
github.com/tendermint/tendermint/types.(*VoteSet).addByIndex(0xc082158840, 0x2, 0xc082052fc0, 0x43010b, 0xc082cd0c28, 0xc082158840, 0xc0821588f0, 0x0, 0x0)
        C:/Go/work/src/github.com/tendermint/tendermint/types/vote_set.go:119 +0x1e7
github.com/tendermint/tendermint/types.(*VoteSet).AddByIndex(0xc082158840, 0x2, 0xc082052fc0, 0xc082158800, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Go/work/src/github.com/tendermint/tendermint/types/vote_set.go:97 +0x109
github.com/tendermint/tendermint/consensus.(*HeightVoteSet).AddByIndex(0xc082118840, 0x2, 0xc082052fc0, 0xc08333e000, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Go/work/src/github.com/tendermint/tendermint/consensus/height_vote_set.go:120 +0x243
github.com/tendermint/tendermint/consensus.(*ConsensusState).addVote(0xc0820ca180, 0x2, 0xc082052fc0, 0xc08333e000, 0x40, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Go/work/src/github.com/tendermint/tendermint/consensus/state.go:1441 +0x766
github.com/tendermint/tendermint/consensus.(*ConsensusState).tryAddVote(0xc0820ca180, 0x2, 0xc082052fc0, 0xc08333e000, 0x40, 0x0, 0x0)

Here I have attached configuration file of machine[1-3] and non validating node

3 Validating peer
[mac[1-3].zip](https://github.com/tendermint/tendermint/files/638486/mac.1-3.zip)

Non validating peer
[non-validating peer.zip](https://github.com/tendermint/tendermint/files/638490/non-
validating.peer.zip)

Application is dummy.

Please note : All the nodes and application are running into one machine. I have changed port number into config.toml file to avoid the "port already bind" error.

Please suggest

**Comment by jibrown** [comment]
Can I see the rest of the log dump? You are using a different TMROOT for each one right? And which version are you using? Latest master (0.7.3)? Or something from develop?

**Comment by gunvant** [comment]
Yes I am using different TMROOT and Latest master (0.7.3). will provide you log of another node soon.

**Comment by gunvant** [comment]
PFA Log file
[log.zip](https://github.com/tendermint/tendermint/files/638590/log.zip)

Please suggest soln. appreciate if you can share document.

**Comment by ebuchman** [comment]
Hm. I'm afraid I need more info. It looks like the panic you pasted above is missing the first few lines about what actually caused the panic? Also can I see the exact command you are using to run it?

**Comment by gunvant** [comment]
Thanks for your reply, Ethan. 

Issue has been resolved after copy genesis.json file into non-validator node.

But now i am working on to auto discovery of validating peer node. Can you please guide me into this.

**Comment by ebuchman** [comment]
Auto-discovery? You have to specify seed nodes. If you are using the latest (just now's) release (v0.7.4), you can enable the "peer exchange" with the `--pex` flag. I added some more details on finding peers in the new [Using Tendermint Guide](https://tendermint.com/docs/guides/using-tendermint)

**Comment by adrianbrink** [comment]
I am closing this as we are currently at 0.10. If this issue is still relevant, please tag me and I'll reopen it.
