### ISSUE TITLE
 unmarshal to p2p.DefaultNodeInfo failed

### ISSUE THREAD

**Issue by swapnil-pandey** [tendermint/tendermint#3240]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.29.1-4d7b29cd

**ABCI app** (name for built-in, URL for self-written if it's publicly available): kvstore

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **Install tools**:
- **Others**:

**What happened**: I am trying to set up a network of 5 nodes. I have created a testnet using tendermint create testnet and copied the config folder to the respective nodes. now when I run, `tendermint node --consensus.create_empty_blocks=false` on all the 5 nodes, 3 of them work fine but on two of them an error similar to this appears:

`E[2019-02-01|15:01:17.585] Dialing failed                               module=pex addr=5d58eca80e0f0ca17fc3d3fc1be1c4d7b4acf8f6@192.168.0.83:26656 err="auth failure: handshake failed: unmarshal to p2p.DefaultNodeInfo failed after 3 bytes (insufficient bytes decoding []byte of length 49): 0A283231323032306563646330333633363935343264663030653461623866656138386332316338346412137463703A2F2F302E302E302E303A32363635361A0C636861696E2D427861624338220F302E32352E302D30633963333239322A0840202122233038003218696E666F626A656374732D5468696E6B5061642D4C3437303A3B0A06302E31322E301205302E352E301A0876312F302E322E322207302E372E302F332A026F6E32137463703A2F2F302E302E302E303A3236363537" attempts=0
E[2019-02-01|15:01:18.583] Dialing failed                               module=pex addr=dbf5beb204e4f54ac24bf61324abef96bd0d12af@192.168.0.194:26656 err="dial tcp 192.168.0.194:26656: i/o timeout" attempts=0
E[2019-02-01|15:01:19.904] Error dialing peer                           module=p2p err="auth failure: handshake failed: unmarshal to p2p.DefaultNodeInfo failed after 3 bytes (insufficient bytes decoding []byte of length 49): 0A283231323032306563646330333633363935343264663030653461623866656138386332316338346412137463703A2F2F302E302E302E303A32363635361A0C636861696E2D427861624338220F302E32352E302D30633963333239322A0840202122233038003218696E666F626A656374732D5468696E6B5061642D4C3437303A3B0A06302E31322E301205302E352E301A0876312F302E322E322207302E372E302F332A026F6E32137463703A2F2F302E302E302E303A3236363537"
E[2019-02-01|15:01:47.586] Dialing failed                               module=pex addr=5d58eca80e0f0ca17fc3d3fc1be1c4d7b4acf8f6@192.168.0.83:26656 err="auth failure: handshake failed: unmarshal to p2p.DefaultNodeInfo failed after 3 bytes (insufficient bytes decoding []byte of length 49): 0A283231323032306563646330333633363935343264663030653461623866656138386332316338346412137463703A2F2F302E302E302E303A32363635361A0C636861696E2D427861624338220F302E32352E302D30633963333239322A0840202122233038003218696E666F626A656374732D5468696E6B5061642D4C3437303A3B0A06302E31322E301205302E352E301A0876312F302E322E322207302E372E302F332A026F6E32137463703A2F2F302E302E302E303A3236363537" attempts=1`

On the three nodes which are working correctly, there was already an instance of tendermint running before. The two nodes with error are fresh nodes.
I have also opened the ports 26656 and 26657 on al the machines.

**What you expected to happen**: I expected all the 5 nodes to work perfectly normally.

**Have you tried the latest version**: yes

**Comment by ebuchman** [comment]
Sounds like the nodes are not all running the same version. Can you include `/status` rpc output from each node? That should show the difference

**Comment by melekes** [comment]
> On the three nodes which are working correctly, there was already an instance of tendermint running before.

If these three nodes were running 0.28 and two new - 0.29, then it explains the error you're seeing. 0.29 and 0.28 are not compatible. Read more at https://github.com/tendermint/tendermint/blob/master/UPGRADING.md#v0290

**Comment by swapnil-pandey** [comment]
Ok so as suggested, I installed the latest version of tendermint on all the nodes. Now after running the systems, I get this error:

```
E[2019-02-05|12:21:03.834] enterPrevote: ProposalBlock is invalid       module=consensus height=1 round=2 err="Wrong Block.Header.Version. Expected {9 0}, got {9 1}"
E[2019-02-05|12:21:25.613] enterPrevote: ProposalBlock is invalid       module=consensus height=1 round=5 err="Wrong Block.Header.Version. Expected {9 0}, got {9 1}"
```

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/issues/3260
