### ISSUE TITLE
go-deadlock: use build flags instead of sed

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3242]
We added support for running Tendermint with a deadlock detector in https://github.com/tendermint/tendermint/pull/3218

That PR adds a makefile command that rewrites import statements for the `sync` package to use the deadlock detecting one.

It would be amazing if this could instead be done using build flags instead.

**Comment by marbar3778** [comment]
I would propose we do a wrapper around deadlock.(RW)Mutex and sync.(RW)Mutex and then have a build flag to switch between the two. 

If this is accepted I can work on this as it will not be a large change
