### ISSUE TITLE
rpc: Error using NetInfo in RPC client for Cosmos-SDK v0.30.0

### ISSUE THREAD

**Issue by fkbenjamin** [tendermint/tendermint#3251]
**Tendermint version** :
1809efa3500e215e531dfd78dd6fe180ef3ef4b1

**ABCI app**:
Cosmos-SDK v0.30.0

**What happened**:
Using the rpc websocket in Go:
```
import (
 "fmt"
 "github.com/tendermint/tendermint/rpc/client"
)

cosmosClient := client.NewHTTP(config.GaiaUrl, "/websocket")
netInfo, err := cosmosClient.NetInfo()
		if err != nil {
			fmt.Println(err)
		}
```
Results in printing the following error:
```NetInfo: Error unmarshalling rpc response result: invalid IP address: AAAAAAAAAAAAAP//rB8ktw==```

Seems like this was broken by changing the plain text IP addresses field for this command to amino encoded IP address field in Cosmos. Hope this still belongs here.

**Comment by jacohend** [comment]
This is also affecting me on a plain tendermint network (no cosmos).

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3309 to develop. Should land in v0.30.1

**Comment by jacohend** [comment]
@melekes That PR does not seem to have fixed the issue here. The net_info endpoint is still returning the same bad encoding. Can you please reopen?

**Comment by jacohend** [comment]
It does look like the rpc endpoint call is succeeding, though, so I guess maybe this issue is fixed, even if the encoding is still odd?

**Comment by melekes** [comment]
What version of Tendermint are you using?

**Comment by jacohend** [comment]
I'm using both the master and the develop branches as of yesterday afternoon, and using the client rpc library as of https://github.com/tendermint/tendermint/commit/e0f8936455029a40287a69d5b0e7baa4d5864da1

**Comment by melekes** [comment]
https://gist.github.com/melekes/00b1cdb76b3994b135b0eef39b05ebea
this is what I am getting when I execute `curl localhost:26657/net_info`

**Comment by ebuchman** [comment]
How come this issue isn't/wasn't being caught by the TestNetInfo? https://github.com/tendermint/tendermint/blob/v0.30.0/rpc/client/rpc_test.go#L74

**Comment by melekes** [comment]
Because we do not create any peers `assert.Equal(t, 0, len(netinfo.Peers))`.

**Comment by melekes** [comment]
@jacohend can you post the output of `/net_info` here?

**Comment by melekes** [comment]
I don't know what can be done here except https://github.com/tendermint/tendermint/pull/3309. This is the response I'm getting - https://gist.github.com/melekes/00b1cdb76b3994b135b0eef39b05ebea. remote_ip is a string here (`"remote_ip": "192.167.10.4"`).

> so I guess maybe this issue is fixed, even if the encoding is still odd?

Have you tried vanilla Tendermint Core (not Cosmos SDK)? Maybe SDK adds some overlay upon Tendermint RPC...

**Comment by melekes** [comment]
Checked our `HTTP` client https://godoc.org/github.com/tendermint/tendermint/rpc/client response - all good 👍

**Comment by melekes** [comment]
@jacohend if you're still experiencing this issue, please get in touch either by dropping a msg here or on Riot. Thanks!
