### ISSUE TITLE
allow Tendermint to return app level data

### ISSUE THREAD

**Issue by jbibla** [tendermint/tendermint#3253]
as a client developer building on top of Tendermint and the Cosmos SDK there are times when it is convenient to query Tendermint directly as opposed to building new endpoints on the SDK's REST API. 

an example: when we query for blocks, Tendermint returns the `proposer_address` in an un-opinionated hex format. the Gaia and the SDK use bech32 for validator addresses. it would be great if Tendermint could return these bech32 addresses as an option.

there are likely other use cases and examples of where mapping app level data to Tendermint responses may be useful.

thank you kindly.

**Comment by melekes** [comment]
We might want to look into https://graphql.org/

**Comment by jbibla** [comment]
thanks for the tip @melekes!

@greg-szabo another strong indicator that we should be investigating graphQL.

**Comment by marbar3778** [comment]
Don't believe this is something that we would like to support, but with the work with protobuf this can be done client-side. Since this won't is in the scope of Tendermint then will close it, please reopen if you disagree.
