### ISSUE TITLE
lite: verify all headers

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3259]
We currently use bisection to sync a lite client so we don't have to verify all headers. But this unsafe. It looks like doing bisection safely may require application specific components: https://github.com/tendermint/tendermint/issues/3244.

As an immediate remediation, we should verify all headers in order.

**Comment by jaekwon** [comment]
See https://github.com/tendermint/tendermint/issues/3244#issuecomment-475921646 on why we need to implement counterfactual signing anyways.

If +2/3 are signing something bad, we've got bigger problems... this solution isn't necessary.

**Comment by Liamsi** [comment]
Should we close this then?

**Comment by marbar3778** [comment]
with the work of #3906, #3847, #3911 this issue can be closed.
