### ISSUE TITLE
Bandwidth configuration between trusted peers

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#3265]
## Summary
User story: between my sentry node and my validator node I would like to use a higher bandwidth than what is the default setting for the network.

```
# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024
```

## Problem Definition
The problem is that it is a network-wide setting and using Bucky's words "it breaks everything" if you change it on your node.

## Proposal
Implement a handshake in p2p to tell the other node your maximum packet size? - Needs discussion.

**Comment by melekes** [comment]
Per-peer configuration? This will make things so complex. Maybe it can be forced externally somehow?
