### ISSUE TITLE
Stop building block 

### ISSUE THREAD

**Issue by b00f** [tendermint/tendermint#3266]
**Tendermint version**  0.28.0
**OS** Linux

**What happened**:
When a new node join to the blockchain, it will stop building blocks after a while.

**What you expected to happen**:
It should continue building blocks until reaching the head

**Have you tried the latest version**: yes/no
yea

**Note**:
Disabling `FastSync` will resolve the issue. I think by enabling `FastSync` other nodes will stop sending data to the new node. Why?

This is the new node in our TestNet: http://68.183.183.16:50053/LatestBlock
Other Nodes are listed here:
https://github.com/gallactic/testnets/tree/master/Biruni-02

**Comment by melekes** [comment]
> I think by enabling `FastSync` other nodes will stop sending data to the new node. Why?

We do not start consensus until the node is fully synced.

> it will stop building blocks after a while.

Could you please describe what's happening in greater details? Or better provide logs from that node?
Does it finish syncing? and after that never switches to regular consensus?

**Comment by melekes** [comment]
Could you also provide config.toml? Are you using no-empty-blocks?

**Comment by b00f** [comment]
All the settings in config are set to default unless information about validator. A copy of config file is [here](https://github.com/gallactic/testnets/blob/master/Biruni-02/157.230.32.23/config.toml)

The log doesn't show anything useful unless it says (after a while) that there is no peer. It looks peers stop sending data. By disabling `FastSync` I can't see this problem.

**Comment by melekes** [comment]
> The log doesn't show anything useful unless it says (after a while) that there is no peer.

Have you tried changing the log level `--log_level="*:debug"?

> It looks peers stop sending data.

There might be a deadlock there. Can you post an output of `kill -6 <PID>` here?

**Comment by b00f** [comment]
I am not able to generate it again. but I am very sure about this issue. 
By the way, when I tried to reproduce it locally using my [tendermint_testnet](https://github.com/b00f/tm-testnet), I saw this error: any idea?
`filtered CONN<127.0.0.1:5001>: duplicate CONN<127.0.0.1:5001>`


Randomly I ca see this panic as well when I am trying to close application:
```
panic: Panicked on a Crisis: leveldb: closed

goroutine 30 [running]:
github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/libs/common.PanicCrisis(0x1796720, 0xc0000b3f40)
	/home/mostafa/go/src/github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/libs/common/errors.go:232 +0xb8
github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/libs/db.(*GoLevelDB).Set(0xc00020a228, 0xc004631098, 0x6, 0x8, 0xc004c7c680, 0x186, 0x186)
	/home/mostafa/go/src/github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/libs/db/go_level_db.go:70 +0xb1
github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/blockchain.(*BlockStore).SaveBlock(0xc00024b500, 0xc0043b2780, 0xc000fc05a0, 0xc00491a700)
	/home/mostafa/go/src/github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/blockchain/store.go:160 +0x120
github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).poolRoutine(0xc000cf04e0)
	/home/mostafa/go/src/github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:333 +0x9bb
created by github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/blockchain.(*BlockchainReactor).OnStart
	/home/mostafa/go/src/github.com/gallactic/gallactic/vendor/github.com/tendermint/tendermint/blockchain/reactor.go:118 +0x89
```

**Comment by melekes** [comment]
> By the way, when I tried to reproduce it locally using my [tendermint_testnet](https://github.com/b00f/tm-testnet), I saw this error: any idea?
`filtered CONN<127.0.0.1:5001>: duplicate CONN<127.0.0.1:5001>`

connections from the same IP are disabled by default. See allow_duplicate_ips in the config.toml

```
# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false
```

**Comment by melekes** [comment]
> when I am trying to close application:

How are closing it?

**Comment by b00f** [comment]
> How are you closing it?

By sending interupt signal (SIGINT) : ctrl + C.
You can close this issue. In case you see this error locally you might reopen it again.

**Comment by melekes** [comment]
This error might happen if you don't call `tmNode.Stop()` (graceful shutdown) upon SIGINT.

**Comment by melekes** [comment]
Closing due to not enough info.
