### ISSUE TITLE
Installation error in mempool undefined: AutoFile

### ISSUE THREAD

**Issue by niksmac** [tendermint/tendermint#327]
Commands 

```
› go get -u github.com/tendermint/tendermint/cmd/tendermint
# github.com/tendermint/tendermint/mempool
Code/go/src/github.com/tendermint/tendermint/mempool/mempool.go:65: undefined: AutoFile
```

I am getting `mempool.go:65: undefined: AutoFile` error. 

```
› tendermint version
zsh: command not found: tendermint
```

## OS

> Linux ether 4.4.0-51-generic #72-Ubuntu SMP Thu Nov 24 18:29:54 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ebuchman** [comment]
Thanks. Please see notes about using `glide` to install tendermint here (with vendored dependencies): https://tendermint.com/intro/getting-started/install

We'll work on shipping signed binaries soon, but making sure `go get` always works is too much trouble.

**Comment by jaekwon** [comment]
Was this on a non master branch of Tendermint?

**Comment by reachrkr** [comment]
Even I am also getting same error as on today

```
$ go get -u github.com/tendermint/tendermint/cmd/tendermint
# github.com/tendermint/tendermint/mempool
go/src/github.com/tendermint/tendermint/mempool/mempool.go:65: undefined: AutoFile
```

**Comment by niksmac** [comment]
@jaekwon I think so, because I tried the `go get` command.

**Comment by arnonuem** [comment]
Can confirm this - got the same problem using Windows 7 Ultimate.

**Comment by niksmac** [comment]
No, I am getting the same error every after installing `glide`

**Comment by ebuchman** [comment]
@niksmac did you run `glide install` in the tendermint directory?

I fixed the issue. `go get -u github.com/tendermint/tendermint/cmd/tendermint` should work again.
