### ISSUE TITLE
Cgo build tags

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3273]
In `libs/db` we use `// +build gcc` for the c_level_db.

But in the recently merged `crypto/secp256k1` work we use `// +build cgo`.

Probably we want better control over these and for them to be less confusing.

Perhaps we should change them to, eg. `tm-c-leveldb` and `tm-c-secp256k1` respectively? This way folks importing tendermint can pick and choose their build flags rather than being forced to get all C libraries at once.

**Comment by ebuchman** [comment]
See minor follow up review in #3234

**Comment by ebuchman** [comment]
build tags need to be alphanumeric. So we can just have them be like `// +build cleveldb` and `// +build libsecp256k1`

**Comment by marbar3778** [comment]
seems this was closed with https://github.com/tendermint/tendermint/pull/3628 @melekes, could you close if so.
