### ISSUE TITLE
TestReactorBroadcastTxMessage non-deterministic failure

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3274]
```
panic: test timed out after 5m0s
```

[build_44989_step_105_container_0.txt](https://github.com/tendermint/tendermint/files/2842923/build_44989_step_105_container_0.txt)

**Comment by melekes** [comment]
I don't see any errors in the log file. Since we're no longer observing this, I think it's okay to close. Related PR: https://github.com/tendermint/tendermint/pull/4876
