### ISSUE TITLE
Avoid requiring entire `go-ethereum` commit in lockfile

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#3289]
See if there's a way we can just bind to an exact version of the `secp256k1` library, which is all we need.

Perhaps copy that code out into our own repository.

Ref https://github.com/cosmos/cosmos-sdk/issues/3564

**Comment by Liamsi** [comment]
> Perhaps copy that code out into our own repository.

I think that is the way to go until the related dep issue is resolved: https://github.com/golang/dep/issues/1847

**Comment by Liamsi** [comment]
Addressed in https://github.com/tendermint/tendermint/pull/3371
