### ISSUE TITLE
Link for Guide to run first TMSP Application is defective

### ISSUE THREAD

**Issue by arnonuem** [tendermint/tendermint#329]
The link to the first TMSP Application Guide in the wiki at https://github.com/tendermint/tendermint/wiki/Application-Developers seems to be broken.
Please fix the link!

Maybe this one?
https://tendermint.com/intro/getting-started/first-tmsp

The link to the blog post is broken too.

**Comment by tomtruitt** [comment]
Works for me

**Comment by arnonuem** [comment]
@tomtruitt you say that these links are working for you?

http://tendermint.com/blog/tendermint-socket-protocol/
http://tendermint.com/guide/run-your-first-tmsp-application/

first link shows me an empty blue page
second link shows me a 404

**Comment by ebuchman** [comment]
Hmm they should be re-directing. Not working for me on Chrome either. @nylira

**Comment by ebuchman** [comment]
Ok updated in the wiki. Please note we'll be deprecating the wiki and doing all docs/tuts/guides through the website! Let us know if you can think we can approve the flow there (https://github.com/tendermint/tendermint.github.io)

**Comment by tomtruitt** [comment]
Hmm maybe it was cached copies
