### ISSUE TITLE
RemoteSigner responses are corrupted during receipt and unmarshalling

### ISSUE THREAD

**Issue by amrali** [tendermint/tendermint#3296]
**Tendermint version**: 0.29.1

**ABCI app**: Cosmos Hub

**Environment**:
- **OS** (e.g. from /etc/os-release): Alpine Linux 3.8

**What happened**:

Periodically missed prevotes and precommits due to gaiad trying to parse a corrupt amino encoded response message from a remote signer (KMS).

**What you expected to happen**:

To correctly parse the amino response message.

**Have you tried the latest version**: yes/no

As of this writing, yes. I didn't use master or the develop branches.

**How to reproduce it**:

indeterministic failure, hard to reproduce consistently.

**Logs**:

```
gaia_1                  | E[2019-02-05|10:09:56.663] Error signing vote                           module=consensus height=37903 round=0 vote="Vote{40:7BAE45052D95 37903/00/2(Precommit) CDB32C6B2887 000000000000 @ 2019-02-05T10:09:56.552078692Z}" err="unmarshal to privval.RemoteSignerMsg failed after 4 bytes (unrecognized prefix bytes 48A6160A): 48A6160A760802108FA80222480A20CDB32C6B28875A183DBE447D29C42F5794D3E45C19AE54D907C7FB9E8D728F40122408011220ADBED4A5E5A6D19FEEF873ED97C41456976AA88ACC081925386807A24DE8189E2A0C08F4C1E5E20510E49AA0870232147BAE45052D9594C083949B081E17C9784F963F123828125408FE03124F5245444143544544204552524F52204D455353414745205245444143544544204552524F52204D455353414745205245444143544544204552524F52204D455353414745205245444143544544204504"
```

**Anything else we need to know**:

There are two possible causes for this problem, either Tendermint/KMS is at fault or Tendermint/Tendermint is. I've started with the part I'm most familiar with (KMS) and I couldn't spot any execution path that would lead to corrupting the amino encoded message going out of the socket.

I then put together something small in Python to reverse engineer the outputted amino/protobuff encoded response messages to make sure that code expectations meets reality from the KMS side. The result of this effort pointed at corruption on the receiving end as it is indeed a fact that KMS does consistently output properly encoded messages under different conditions or state machines (successfully signed, failed to sign, etc.). Below is an example of a reversed amino encoded message:

```
(venv) d4de::vela (master %) $ python3 revproto.py
INFO:main:Decoded amino message with prefix: B248A616
Message<n=2>:
	Field<id=1, type=lendelim>: b'\x08\x02\x10\xb8`\x18\x04"J\n 00000000000000000000000000000000\x12&\x08\xc0\x84=\x12 00000000000000000000000000000000*\x0c\x08\xa2\xd8\xff\xd3\x05\x10\xc0\xf2\xe3\xec\x022\x14BBBBBBBBBBBBBBBBBBBB8\xd5\xbb\x03'
	Field<id=2, type=lendelim>: b'\x08\xfe\x03\x12OREDACTED ERROR MESSAGE REDACTED ERROR MESSAGE REDACTED ERROR MESSAGE REDACTED E'

INFO:main:Trying to guess message structure... hints: ([1, 4, 2], [1, 5], [2])
Message<n=2>:
	Field<id=1, type=lendelim>: Message<n=7>:
	    Field<id=1, type=varint>: 2
	    Field<id=2, type=varint>: 12344
	    Field<id=3, type=varint>: 4
	    Field<id=4, type=lendelim>: Message<n=2>:
	        Field<id=1, type=lendelim>: b'00000000000000000000000000000000'
	        Field<id=2, type=lendelim>: Message<n=2>:
	            Field<id=1, type=varint>: 1000000
	            Field<id=2, type=lendelim>: b'00000000000000000000000000000000'
	    Field<id=5, type=lendelim>: Message<n=2>:
	        Field<id=1, type=varint>: 1518332962
	        Field<id=2, type=varint>: 765000000
	    Field<id=6, type=lendelim>: b'BBBBBBBBBBBBBBBBBBBB'
	    Field<id=7, type=varint>: 56789

	Field<id=2, type=lendelim>: Message<n=2>:
	    Field<id=1, type=varint>: 510
	    Field<id=2, type=lendelim>: b'REDACTED ERROR MESSAGE REDACTED ERROR MESSAGE REDACTED ERROR MESSAGE REDACTED E'

(venv) d4de::vela (master %) $
```

The only thing that stood out to me was the use of Varint encoding for all types of integers (instead of "fixed32" or "fixed64"), which is fine for all intended purposes albeit not the most efficient use of protocol buffers.

Looking at Tendermint, specifically at https://github.com/tendermint/tendermint/blob/v0.29.1/privval/client.go I noticed that we use an `RLock`, I'm not familiar with Go's runtime memory visibility semantics and how it accounts for the different CPU architectures it is supposed to run on, but I know that the misleadingly named go-routines (one would think they're implemented as coroutines, but no) are implemented as functions that the runtime schedules over an OS-thread pool, also I think `RLock` does not implement a full memory fence (to prevent the CPU from reordering your code for efficiency), meaning that `RLock` either implements only acquire semantics or release semantics, which leaves room for the CPU to reorder LOAD/STORE instructions either before or after the `RLock` line. This explains why the amino encoded message is perceived as corrupt as one thread could finish writing and immediately starts reading a message while the Ping/Pong thread was attempting to read (the two reads could be reordered here under the assumptions of only using a read-acquire fence).

One of the reasons why sockets should never be shared between threads is because it is hard to correctly synchronize I/O access to the socket under a multi-processor system. So the fix is to either institute a full memory fence before all reads and writes at which point you'd lose all benefits (are there any here?) of concurrency, or open multiple connections and dedicate one to Ping/Pong and the other to the request/reply messages. Also I don't see the benefit of application heartbeats for the remote signer when we already use reliable protocols (i.e., TCP/SecureConnection and UNIX sockets). IMHO heartbeats makes sense for the consensus protocol, but not for the remote signer.

**Comment by Liamsi** [comment]
> The only thing that stood out to me was the use of Varint encoding for all types of integers (instead of "fixed32" or "fixed64"), which is fine for all intended purposes albeit not the most efficient use of protocol buffers.

You are right. The reason for this is due to https://github.com/tendermint/tendermint/issues/1622#issuecomment-424294274

**Comment by Liamsi** [comment]
> Looking at Tendermint, specifically at https://github.com/tendermint/tendermint/blob/v0.29.1/privval/client.go I noticed that we use an `RLock`

This changed in develop recently. Compare for instance: https://github.com/tendermint/tendermint/blob/7fd51e6ade5bd3d6820acdd53ad443c509a4fc7a/privval/client.go#L86-L87

**Comment by Liamsi** [comment]
> IMHO heartbeats makes sense for the consensus protocol, but not for the remote signer.

ref: https://github.com/tendermint/tendermint/issues/3107 

The general issue you've raised should be fixed 0.29.2.

**Comment by amrali** [comment]
> > Looking at Tendermint, specifically at https://github.com/tendermint/tendermint/blob/v0.29.1/privval/client.go I noticed that we use an `RLock`
> 
> This changed in develop recently. Compare for instance:
> 
> [tendermint/privval/client.go](https://github.com/tendermint/tendermint/blob/7fd51e6ade5bd3d6820acdd53ad443c509a4fc7a/privval/client.go#L86-L87)
> 
> Lines 86 to 87 in [7fd51e6](/tendermint/tendermint/commit/7fd51e6ade5bd3d6820acdd53ad443c509a4fc7a)
> 
>  func (sc *SocketVal) GetPubKey() crypto.PubKey { 
>  	sc.mtx.Lock()

I'm not sure if Go's implementation of a mutex Lock is implemented with a full fence, I'll try against 0.29.2 (or maybe 0.30.0) and see (this was changed just 4 days ago, should pull more often). Although a better solution IMHO is to simply get rid of the heartbeat altogether, and by extension the socket sharing across threads.

**Comment by ebuchman** [comment]
> Although a better solution IMHO is to simply get rid of the heartbeat altogether, and by extension the socket sharing across threads.

Do you really mean get rid of it altogether? Or just serialize it with other requests without a separate routine, ie. #3107

**Comment by amrali** [comment]
Yes, I do.

Let's deconstruct what it means to have a heartbeat serialized with other messages and it should explain why we should get rid of application heartbeats in this particular context.

Scenario: We send a ping request followed by a signing request. Assuming synchronous I/O.

State 1: KMS replies the ping request and then sends back a signed response. Utility of the heartbeat here is zero.

State 2: KMS replies the ping request but it takes a bit longer than expected to send the signed response. Heartbeat utility here is zero. Worse, it opens a window for people to make the mistake that once a pong is received they assume that the service is alive while it is not.

State 3: KMS replies the ping request but immediately after a cargo ship's anchor cuts the submarine cable or a guy mistakingly pulls out the wrong ethernet cable plug (no TCP RST or FIN packets to signal connection termination). Tendermint/gaiad blocks for a prolonged period of time (think minutes) on the signed response. Again, heartbeat utility here is zero.

The solution is semi-synchronous I/O (i.e., send/recv with a timeout). All we have to do is allow people to configure timeouts on recv/send (more importantly recv) operations against the KMS. So that they treat it as a KMS deadline (how much time should we allocate to the KMS to sign our requests?). I think that's a conscious decision that validators need to make while considering all the particulars of their infrastructure.

The *only* scenario where we'll have utility for application heartbeats is when we need to carry certain reconciliation/cleanup action as soon as technologically practicable (ASATP). And the proper way to implement heartbeats is by having a dedicated connection for it on the same port.

**Comment by jleni** [comment]
I repost here because it is affecting KMS/Ledger integration too and I missed this issue and posted in a related one:

-------
Very similar to what @ebuchman was saying, I would suggest to:

* split responsibilities multiplexing/demultiplexing vs command specific work
* move socket multiplexing/demultiplexing to a single go routine + channel and receives/pushes answers to other command specific channels for `ping` or `signature`, etc..
* make ping and other commands to operate on these new command specific queues/channels

We would need to have some specific header to demultiplex but talking to @Liamsi, I understand that things are already in place so the change would be small.

This will avoid thread safety issues and ordering problems in the tendermint-kms comms

I can prepare a PR if you agree with the change and you think it has enough priority at this stage.

**Comment by ebuchman** [comment]
Sorry for confusion, but we should close this for #3107 given the respective issue titles and this bug was technically fixed. Agree though that we can likely just remove the ping all together and handle the reconnections when we detect errors sending sign requests.
