### ISSUE TITLE
Don't rerun CI tests if only files changed are markdown

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#331]

**Comment by akalyaev** [comment]
https://circleci.com/docs/skip-a-build/ ? or you were thinking about something more sophisticated?

**Comment by ebuchman** [comment]
Turns out `[ci skip]` doesn't work with github requiring ci tests to pass!

**Comment by melekes** [comment]
Adding `[ci skip] [circle skip]` works!
