### ISSUE TITLE
Test-vectors in vote_test do not match sign-bytes

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#3311]
The only purpose of these test-vectors is to give devs who aim to integrate HSMs some test-vectors for Vote.SignBytes: 
https://github.com/tendermint/tendermint/blob/28d75ec8016b7fb043735cbe4c4d92ec73355de7/types/vote_test.go#L81-L138

Unfortunately, the vectors are generated using amino's `MarshalBinaryBare` instead of calling `SignBytes` (which uses `MarshalBinaryLengthPrefixed` instead). This lead to the test-vectors in the ledger app being incorrect: https://github.com/cosmos/ledger-cosmos/blob/aaae52d2692a586eae171577152378c3b756593f/tests/val/vote_parser.cpp#L81-L101
and some confusion here: https://github.com/tendermint/kms/issues/171

**Comment by melekes** [comment]
Merged to develop.
