### ISSUE TITLE
show_validator creates directories

### ISSUE THREAD

**Issue by folex** [tendermint/tendermint#3314]
**Tendermint version**: 0.25.0-0c9c3292

**Environment**:
- **OS**: Darwin mac 18.2.0 Darwin Kernel Version 18.2.0; macOS 10.14.1 (18B75)
- **Install tools**: brew

**What happened**:
I run `tendermint show_validator` without running `tendermint init` previously (i.e., no tendermint directories exist on my computer).

`tendermint show_validator` creates `~/.tendermint` directory:
```
.tendermint$ tree
.
├── config
│   ├── config.toml
│   └── priv_validator.json
└── data
```
 
**What you expected to happen**:
`tendermint show_validator` should error because there's no `priv_validator.json`. That's what `show_node_id` does.

**Have you tried the latest version**: yes

**How to reproduce it**: `brew install tendermint && tendermint show_validator`

**Comment by melekes** [comment]
Merged to develop. Should land in v0.30.1
