### ISSUE TITLE
A plan for switching to Secret Connection to the Noise handshake

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#3315]
The Secret Connection handshake is broken. https://github.com/tendermint/tendermint/issues/3010

@jaekwon expressed a preference for having a fixed Secret Connection before switching to libp2p which has it's own issues. https://forum.web3.foundation/t/transport-layer-authentication-libp2ps-secio/69

Here is a plan for switching SecretConnection to the Noise Handshake.

Extract a Noise NN implementation from https://github.com/flynn/noise 
Implement GetHandshakeHash().

After the channel has been established, sign the Handshake Hash to authenticate. 

Quoting the Noise Specification

>  11.2. Channel binding
> Parties might wish to execute a Noise protocol, then perform authentication at the application layer using signatures, passwords, or something else.
> 
> To support this, Noise libraries may call GetHandshakeHash() after the handshake is complete and expose the returned value to the application as a handshake hash which uniquely identifies the Noise session.
> 
> Parties can then sign the handshake hash, or hash it along with their password, to get an authentication token which has a "channel binding" property: the token can't be used by the receiving party with a different session.

**Comment by zmanian** [comment]
I'm just sort of reluctant to move to static Diffie Hellman based PKI.

The benefits of deniability don't seem to really buy us anything and we may want nodes to be able to sign things under the P2P identity in the future.

**Comment by tarcieri** [comment]
Alternatively one of the new Noise signature-based key exchanges would prevent the need to change key algorithms:

https://github.com/noiseprotocol/noise_sig_spec/blob/master/output/noise_sig.pdf

`K1K1sig` or `XK1sig` might be applicable. Unfortunately no existing implementations exist, but it's probably the best fit for evolving what's already in-place.

Longer term I'd suggest investigating nQUIC: https://eprint.iacr.org/2019/028

**Comment by Liamsi** [comment]
The web3 / libp2p people are getting involved in https://noiseexplorer.com. Wouldn't it be good for us to help with the Rust code generation and have the implementation Tony mentioned generated in golang / Rust (we need both anyways, right?). This would also benefit the larger ecosystem.

**Comment by zmanian** [comment]
So I think `K1K1sig` would be nearly identical to NN + signature except the static signing keys are hashed into the transcript before signing which seems good.

**Comment by tarcieri** [comment]
@Liamsi I think it'd definitely be good to use existing Noise libraries. There's [snow](https://crates.io/crates/snow) in Rust, for example

**Comment by jaekwon** [comment]
What is the most similar equivalent of the implemented STS handshake in Noise?

**Comment by tarcieri** [comment]
@jaekwon I believe `K1K1sig` is the closest thing to a drop-in replacement for the existing key exchange. It's a signature-based construction which is primarily intended to be used with Ed25519 keys, so switching to it should just be an "under-the-hood" change that has no user-facing effects on how anything else presently works.

**Comment by zmanian** [comment]
Maybe `XXsig`. It has the advantage of the ed25519 keys are only sent after ephemeral encryption is established so you need active MITM to break deniability which seems important to @jaekwon

**Comment by zmanian** [comment]
Okay. I made a standalone implementation of `XXsig` based of a noise explorer generated `NN` implementation.

it would be a modest amount of work to do some more modifications to use tendermint crypto types.

But I think I could potentially have a pull request this week.

**Comment by zmanian** [comment]
The rust implementation story seems potentially a bit more complicated.

**Comment by Liamsi** [comment]
I'm happy top implement the Rust variant.

**Comment by burdges** [comment]
There are no real complexities in converting an Ed25519 public key to an X25519 public key, so the static DH should work, no?  It's messy going the other way.  Not that it's my problem.  ;)

**Comment by tarcieri** [comment]
The whole "go through all the complexity of decoding a compressed Edwards-y point, then use the birational map to Montgomery from, then do X25519 scalar mult for D-H" thing never made any sense to me. At that point just do D-H using Ed25519 scalar mult and call it a day.

Signed (EC)DH ephemeral keys are a relatively known quantity though (see TLS), and pretty close to the existing protocol.

**Comment by zmanian** [comment]
XXsig is signing the transcript of Ephemeral key exchange which gets you deniability.

**Comment by Liamsi** [comment]
Can we summarize the reasons we want to use the more recent signature extension? 

The downsides could be:
 - there are currently no implementations we could use 
 - as a result there are no test-vectors to test against if implement it ourselves

Pros:
 - more easy to use XXSig as a drop-in replacement (very close to what we already have)
 - reasons from the [spec](https://github.com/noiseprotocol/noise_sig_spec/blob/master/output/noise_sig.pdf):
> In some cases the parties might prefer to use signing key pairs for authentication,
rather than DH key pairs. For example, maybe they have an existing PKI based
on signing keys, or would like to use the signing keys to sign other pieces of data.

Am I missing anything here?

**Comment by tarcieri** [comment]
The main reason is the one you highlighted from the spec: Secret Connection uses Ed25519 keys for node identity, so using the signature extension is a natural fit for this use case (and I believe one of the main reasons why Noise wasn't further investigated as an alternative before)

**Comment by ebuchman** [comment]
Trying to understand how this might fit into a libp2p adoption strategy. 

Supposing we were to move forward with libp2p, would it be sufficient to use TLS there until we get the noise variant we want?

**Comment by dshulyak** [comment]
are you still considering switching to noise before "libp2p evaluation"? i see that original problem with secret connection was fixed, and also libp2p noise integration is pretty close to be done ([spec](https://github.com/libp2p/specs/tree/master/noise) and corresponding [repo](https://github.com/libp2p/go-libp2p-noise)).

**Comment by tarcieri** [comment]
I don't think there's any active plan to switch to Noise aside from potentially using it via libp2p

**Comment by dshulyak** [comment]
i was going to suggest that i can make necessary changes. but if this is not a priority anymore maybe this issue can be closed
