### ISSUE TITLE
Throughput Performance Question

### ISSUE THREAD

**Issue by Deegrin** [tendermint/tendermint#3319]
I've been working on a minor school project that uses Tendermint to replicate a (distributed) database. I am wayyyy behind on updates and still using Tendermint v0.24.0. I'm not prepared to use the latest version, but I hope you can still help me with a question.

I did a quick performance test on a 16-Validator Tendermint network with a mostly default configuration (except with a very large Mempool) and these are the results I got. Note the _input transactions per second_ is cumulative across the entire network. So for the 800 value, that means each Validator is being tested with 50 transactions per second.
![tendermint](https://user-images.githubusercontent.com/1267190/52907359-2b14db80-3215-11e9-8adc-b03aa04460cd.jpg)

It seems as if Tendermint is having some difficulty sifting through the Mempool and proposing Blocks within the time out at a certain point, especially with mempool gossip enabled.

Has the team made notable performance improvements to this area between 0.24.0 and the latest 0.30.0? Or will I continue to see the same throughput performance profile if I don't tune the Tendermint configuration?

**Comment by thanethomson** [comment]
Could you please share your Tendermint configuration, and the details as to how you did the load testing (e.g. are you using the `kvstore` proxy app, are you using the HTTP or WebSockets RPC endpoints to submit transactions, etc.) with us? We can try to replicate your experiment and see if your results are still relevant to the newer versions of Tendermint.

**Comment by Deegrin** [comment]
My config.toml is: [config.txt](https://github.com/tendermint/tendermint/files/2872709/config.txt)

My Digital Ocean Terraform request is:
```
resource "digitalocean_droplet" "cluster" {
  image = "centos-7-x64"
}
variable "regions" {
  description = "Regions to launch in"
  type = "list"
  default = ["SFO2"] # Create all droplets in one region.
}
variable "instance_size" {
  description = "The instance size to use"
  default = "s-2vcpu-4gb"
}
```

My tm-bench command is: `tm-bench -v -broadcast-tx-method async -output-format plain -T 20 -r {{ rate }} -c 1 localhost:26657`

I'm using the `kvstore` proxy app (`tendermint node --proxy_app=kvstore`).

Thanks for the quick response!

**Comment by Deegrin** [comment]
My config.toml is: [config.txt](https://github.com/tendermint/tendermint/files/2872711/config.txt)

My Digital Ocean Terraform request is:
```
resource "digitalocean_droplet" "cluster" {
  image = "centos-7-x64"
}
variable "regions" {
  description = "Regions to launch in"
  type = "list"
  default = ["SFO2"] # Create all droplets in one region.
}
variable "instance_size" {
  description = "The instance size to use"
  default = "s-2vcpu-4gb"
}
```

My tm-bench command is: `tm-bench -v -broadcast-tx-method async -output-format plain -T 20 -r {{ rate }} -c 1 localhost:26657`

I'm using the `kvstore` proxy app (`tendermint node --proxy_app=kvstore`).

Thanks for the quick response!

**Comment by melekes** [comment]
> Has the team made notable performance improvements to this area between 0.24.0 and the latest 0.30.0? Or will I continue to see the same throughput performance profile if I don't tune the Tendermint configuration?

Yes, a lot! We also fixed a number of bugs with `create_empty_blocks = false` configuration and a few mempool issues. See the [CHANGELOG](https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md) for details. 

Check out the guide I am currently writing https://medium.com/@anton.kalyaev/tendermint-the-ultimate-guide-for-faster-consensus-cd57087dfd2e. Also, make sure to read https://tendermint.com/docs/tendermint-core/running-in-production.html

**Comment by melekes** [comment]
> It seems as if Tendermint is having some difficulty sifting through the Mempool and proposing Blocks within the time out at a certain point, especially with mempool gossip enabled.

The rechecking txs takes a lot of time. We're planning to add Recheck func https://github.com/tendermint/tendermint/issues/2127 to speed up things there. Note we also reduced the size of the mempool & it's cache.

**Comment by melekes** [comment]
Do you have any other questions?

**Comment by Deegrin** [comment]
No, I'm satisfied with all the answers. The changelog, guides, and planned #2127 were good reads. Thanks so much for the detailed responses!
