### ISSUE TITLE
Pre-launch feature request: store priv_validator_key.json seed for future proofing

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3320]
I'd like to propose that **pre-launch** work is done to ensure the seed used to generate priv_validator_key.json is stored (or output) during generation.

@adrianbrink is working on Ledger integration into TMKMS. Ledger devices are initialized with the seed (phrase), and AFAIK there is no way to reconstruct the seed from the private key.

If memory serves there is an upgrade path for priv_validator_key.json -> TMKMS on YubiHSM devices, where the private key is copied to a slot in the YubiHSM.

It would be desirable to have a similar upgrade path from priv_validate_key.json to TMKMS using Ledger.

IMHO an attempt to should be made, also this close to launchm to ensure validators have a transition path that includes Ledger devices, as they can offer cheap double-signing protection in hardware.

I think an ideal implementation would store the seed inside priv_validator_key.json
```
  "priv_key": {
    "type": "tendermint/PrivKeyEd25519",
    "value": "..."
  },
  "seed": {
    "type": "tendermint/SeedEd25519",
    "value": "..."
  }
```

Alternatively the seed phrase could be output to console during generation.

**Comment by zmanian** [comment]
There is no "seed" value in the ed25519 key gen process. Ed25519 generation doesn't touch bip39/bip32 at all. There is no standardized process from going from a "seed phrase" to a ed25519 key. Ledger implemented one but it's not even particularly well documented.

My recommendation is that you implement a stand alone tool that generates a priv_validator.json file using Ledger's adhoc process rather than putting this in Tendermint.

**Comment by mdyring** [comment]
To clarify, I didn't mean storing the seed phrase but simply the random seed bytes used to generate the key pair. Such as

```
void ed25519_create_keypair(unsigned char *public_key, unsigned char *private_key,
                            const unsigned char *seed);
```

... this would allow generation of the seed phrase if needed, later on.

**Comment by jleni** [comment]
Hi @mdyring,
I've done most of the work for end-to-end integration of the ledger validator app, signatory, kms, etc. and as @zmanian says this is more Ledger related than a Tendermint issue.

> My recommendation is that you implement a stand alone tool that generates a priv_validator.json file using Ledger's adhoc process rather than putting this in Tendermint.

If this is necessary, I can help with this feature but I agree with @zmanian, Ledger uses a method (similar to what Cardano has been doing) to support HD wallets for Ed25519 using a bip32 path. They need to do this because the device is initialized/restored by single mnemonic/seed that is shared byt all app/wallets in the same device regardless of the signature scheme they use (secp256k1/ed25519/etc.)

**Comment by zmanian** [comment]
Yeah but that's not how the ledger works as far as I know.

I believe it uses a BIP32 path from the master seed to generate a

**Comment by mdyring** [comment]
Yeah, if the seed bytes are not compatible, then I agree that greatly reduces the immediate (Ledger) usability.

Not sure what the best way would be to future-proof this, then? I'm trying to think a bit down the line, where other HSMs solutions might appear.

Ideally the keys should be generated inside the HSM, but in a upgrade scenario (priv_validator->HSM) I guess the only two useful things would be 1) seed and 2) private key - hence the suggestion to store both. :-)

**Comment by jleni** [comment]
> Yeah but that's not how the ledger works as far as I know.
> I believe it uses a BIP32 path from the master seed to generate a

This is what I am saying..  

In Ledger Nano S, the mnemonic that is used to restore devices is the master seed for the device and all wallets. Later apps, use a derivation path. When an app is approved and released to the app store, the app is restricted to request derivations only for certain paths. For instance, all Tendermint apps can only derive from the master seed with paths that start with 44'/118'/.....

When using Ed25519, if the app wants to be able to "restore" from the master seed/mnemonic of the device, then it needs to use this process. In this case, the app will derive with 44'/118'/0'/0/0 and receive the respective Ed25519 key pairs.

**Comment by jleni** [comment]
btw, the process has been "documented" by Ledger in python. I can try to look for the code tomorrow morning. 

@mdyring 
What you are proposing, is actually possible. Basically, what you need is to use the mnemonic of your ledger and use the Ed25519 derivation process that they use with a path 44'/118'/0'/0/0, assuming that will be the path that gets approved by ledger once the app goes into the app store.

**Comment by mdyring** [comment]
Ok, yeah so that does not leave any room for Ledger upgrade path - besides creating a specific tool as suggested above... But that would require planning ahead, as opposed to upgrading.

I still think storing the seed could be useful down the line though for other cases that requires initialization with the seed bytes?

**Comment by jleni** [comment]
Another alternative, a bit more inconvenient but still possible is to extend the ledger app so you can enter a private key in the device. This key could be stored in the secure flash and used to sign. However, it would be completely unrelated to the master seed of the ledger device.
This would require a bit of UI work in the app and the key would be linked to the app so uninstalling would delete the key.

**Comment by mattharrop** [comment]
I think a tool to generate the ed25519 key pair from the Ledger mnemonic seed would accomplish the goals that @mdyring set out.  This would allow the validator to migrate from a Ledger to another HSM or to priv_validator_key.json file.  This tool could also be used to derive a key pair from a 24 word seed generated elsewhere, allowing a validator to start with a keypair that that can be migrated to a Ledger by restoring a ledger using this seed.  

@jleni Were you able to find Ledger's "documentation" regarding this?

**Comment by jleni** [comment]
@mattharrop @mdyring @zmanian 
According to Ledger, the following script should generate the same keys as the Tendermint validator app:

https://github.com/LedgerHQ/orakolo/blob/master/src/python/orakolo/HDEd25519.py

You should use derivation path as follows:

    bip32_path[0] = 0x80000000 | 44;
    bip32_path[1] = 0x80000000 | 118;
    bip32_path[2] = 0x80000000 | 0;
    bip32_path[3] = 0x00000000 | 0;
    bip32_path[4] = 0x00000000 | 0;

**Comment by jleni** [comment]
As a reference, here is the code in the app:

https://github.com/tendermint/ledger-validator-app/blob/master/src/app_main.c#L155-L176

**Comment by mdyring** [comment]
Closing as we already launched.. ;-)

**Comment by asmodat** [comment]
Based on the code provided above I made a working python script available here: https://github.com/KiraCore/KB/blob/master/Cosmos/Scripts/tmkms-softsign-recovery-from-seed.py

No need to use tmkms import, it outputs base64 .key

**Comment by asmodat** [comment]
As recommended in the previous issue #17 script was added to the PR https://github.com/tendermint/tendermint/pull/4528/files
