### ISSUE TITLE
Evil proposers can drop valid txs in Commit stage

### ISSUE THREAD

**Issue by rickyyangz** [tendermint/tendermint#3322]
In the end of commit stage, we will update mempool to remove all the txs in current block.

```go
// Update mempool.
err = blockExec.mempool.Update(
	block.Height,
	block.Txs,
	TxPreCheck(state),
	TxPostCheck(state),
)
```

Assum an account has 3 transactions in the mempool, the sequences are `100`, `101` and `102` separately, 
So an evil proposal can only package the 101 and 102 transactions into its proposal block, and leave 100 still in mempool, then the two txs will be removed from all validators' mempool when commit.  
So the account lost the two valid txs.

**Comment by melekes** [comment]
Yeah, looks like the client will have to resubmit 101 and 102 txs to get them into a block.

So we should only remove valid/really committed txs (for which app#DeliverTx returned 0 code), not all the block's txs, from the mempool?

Refs https://github.com/tendermint/tendermint/issues/2175

Note the application can punish the evil proposer for proposing txs out of order.

**Comment by rickyyangz** [comment]
> looks like the client will have to resubmit 101 and 102 txs to get them into a block.

The `Update` method will also add the txs into the cache,  so even if the client submit again, `ErrTxInCache` error will return util the cache expired.  

```golang
// Add committed transactions to cache (if missing).
	for _, tx := range txs {
		_ = mem.cache.Push(tx)
	}

	// Remove committed transactions.
	txsLeft := mem.removeTxs(txs)
```


> So we should only remove valid/really committed txs (for which app#DeliverTx returned 0 code), not all the block's txs, from the mempool?

yes, I think so. Only these txs that delivered successfully need to be removed from mempool (and add to mem cache).

> Note the application can punish the evil proposer for proposing txs out of order. 

For this scenario, I think it's not easy to find and confirm it's a evil proposer.

**Comment by melekes** [comment]
> The `Update` method will also add the txs into the cache, so even if the client submit again, `ErrTxInCache` error will return till the cache expired.

Right! Forgot about it

**Comment by ebuchman** [comment]
Nice find. This is a bit of a subtle problem. 

A couple short term solutions might be:
- only remove txs if they returned Code==0
- remove txs that returned Code!=0 from the cache so they can be resubmitted.


In the longer term we may want to do something like https://github.com/tendermint/tendermint/issues/2639 so we can validate txs before we commit the block. But even in this case we'd only want to run the equivalent of CheckTx, which means the DeliverTx could still fail even if the CheckTx passes depending on how the app handles the ABCI Code semantics. So more work will be required around the ABCI code. See also #2185

**Comment by ebuchman** [comment]
Curious - did you discover this from inspection or did it happen on a network?

**Comment by rickyyangz** [comment]
when we check another issue, it suddenly came to my mind that we may have this attack...so I inspected the code and yes it is.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3625 to develop.

**Comment by ebuchman** [comment]
Re-opening ala https://github.com/tendermint/tendermint/pull/3701

**Comment by melekes** [comment]
I can't think of anything right now except designing better clients. Added a few lines to broadcast_tx_* RPC doc here https://github.com/tendermint/tendermint/pull/3749.

**Comment by melekes** [comment]
As Ethan said, this might be unavoidable (for now). There are two proposals, which can solve this: 

1. https://github.com/tendermint/tendermint/issues/2639
2. https://github.com/tendermint/tendermint/issues/4771

_Still, the need for a smart HTTP clients remain as nodes can be malicious themselves as documented in https://github.com/tendermint/tendermint/pull/3749._

**Comment by liamsi** [comment]
> There are two proposals, which can solve this:

How does Preprocessing solve this? Doesn't this make this even more complicated? After a prepreocess step the Tx ending up in the block aren't necessarily the same that the mem-pool has seen. Hence the Update method in the [opening comment](https://github.com/tendermint/tendermint/issues/3322#issue-411293156) can't decide if it should discard Tx or not.

**Comment by melekes** [comment]
Right, it does not. I guess I was thinking about a slightly different design - https://github.com/tendermint/tendermint/issues/3759#issuecomment-524077603
