### ISSUE TITLE
consensus: Validator with power zero inside the set

### ISSUE THREAD

**Issue by b00f** [tendermint/tendermint#3325]
Tendermint removes validators with power zero. In some cases Application maybe tend to add validators with power zero, for example in system base on reputation like [Eigentrust++](https://en.wikipedia.org/wiki/EigenTrust) a validator can be initialized with the power of zero and based of the performance it gains power.

**Comment by ebuchman** [comment]
What is the purpose of having a 0-power validator? Is it just to expand the list of allowed proposers, to include the 0 power proposer? I'm not sure the current proposer selection algorithm can cope with 0-power validators. In any case, sounds like we need to address #3285 properly for this, which is worth starting to think about.

**Comment by b00f** [comment]
It looks weird but a new validator can start with power zero and by acing good gain more power. 
But brought me to thin question is not exactly this. My idea is why Tendermint don't allow the Application to have full control over validator set and proposer selection?
Please check [Adr-036](https://github.com/tendermint/tendermint/pull/3324)

**Comment by ebuchman** [comment]
How do you measure "acting good" if they have 0 power?

The app does have full control over validator set, except it can't set power to 0. Agree we need to provide control over proposer selection, but we also don't want to require it, so apps that just want to use tendermint determinstic round robin can do so.

**Comment by b00f** [comment]
Validates by being online and signing proposals can gain reputation. 

Can make an option in EndBlock which application can choose to use tendermint algorithm for proposal selection or not?
