### ISSUE TITLE
Store state in data/priv_validator_state.json when using external signer

### ISSUE THREAD

**Issue by mattharrop** [tendermint/tendermint#3328]
When using tmkms, tendermint's double sign prevention is disabled, and tmkms must track the height, round, and type of the last message signed.  As of tmkms 0.30 this is not implemented.  Double signing is catastrophic to a validator, and it is desirable that as many validators as possible use HSMs at launch.  

In order to provide double sign prevention to validators using tmkms, I propose that support for the priv_validator_state.json file be added to the remote signer.  This will put double sign prevention for validators using tmkms/hsm on even footing with those using the internal signer.   Once tmkms implements double sign logic, this support in tendermint will continue to provide defence in depth.  

I believe that this is critical to the security of the network at launch.

**Comment by 7alisman** [comment]
+1

**Comment by tarcieri** [comment]
For what it's worth, double signing defense in the KMS (https://github.com/tendermint/kms/issues/60) is the next thing I plan on working on after https://github.com/tendermint/kms/issues/174

That said, having Tendermint also implement internal checks for double signing makes sense to me as a belt-and-suspenders approach.

**Comment by marbar3778** [comment]
We will need to modify the private validator messages here. This can be done in conjunction with https://github.com/tendermint/tendermint/issues/3752.

**Comment by ewagmig** [comment]
Is there anything updated in the dual signing prevention?
