### ISSUE TITLE
rpcserver WriteTimeout configurable

### ISSUE THREAD

**Issue by tanhuiya** [tendermint/tendermint#3329]
RT

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/d2c7f8dbcf238ccc3a2469e350523c7ed28be154/rpc/lib/server/http_server.go#L38

**Comment by melekes** [comment]
Could you please explain why you want to control these? Just curious. Do you use http_server library separately from Tendermint?

**Comment by ebuchman** [comment]
As of #3443 you can increase it by setting the new `rpc.timeout_broadcast_tx_commit` value. Do you need more direct control than that?

Maybe we should just expose the read and write timeout for the global HTTP server directly through the config.

**Comment by melekes** [comment]
Fixed on master https://github.com/tendermint/tendermint/blob/940e68292cd2e710525c35df08d7e007a7c04f9d/rpc/jsonrpc/server/http_server.go#L58
