### ISSUE TITLE
rpc: add possibility of sorting /tx_search results

### ISSUE THREAD

**Issue by gianfelipe93** [tendermint/tendermint#3333]
Hi guys,

I am using the function TxSearch to query transactions from the blockchain and now I need to get the latest 5 transactions to populate a list. However, I couldn't find a way to sort the transactions so I am here to ask if there's a way to that currently.

I am running the version 0.30.0

Thanks for your help,
Gian.

**Comment by melekes** [comment]
There's no way currently to sort txs returned by /tx_search.

**Comment by gianfelipe93** [comment]
Hi Melekes,

Thank you for helping me.

Since I want to get the latest 5 transactions, sorting by `asc` should do the job.

For now I will calculate what the last page is and get the transactions using `TxSearch` .

I am closing the issue since the question has been answered.

Thanks you again Melekes,
Gian.

**Comment by melekes** [comment]
We still need to implement the sorting. I'll update the title.

**Comment by thith** [comment]
Is there a progress on this?
It is necessary feature because apps like wallet and scan need to show transactions in the latest-first order. It is not only '5 first transactions', we need paging in that order as well.
How does cosmos scan/wallet handle this?
