### ISSUE TITLE
Initializing DB failed when do duplicate query with verifier in the same process on tendermint v0.30.0

### ISSUE THREAD

**Issue by ewagmig** [tendermint/tendermint#3335]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Release/v0.30.0 at commit header 28d75ec80

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
none

**Environment**: 
- **OS** (e.g. from /etc/os-release): Windows
- **Install tools**:
- **Others**:

**What happened**:
I have built my application based on the latest cosmos SDK(i.e. v0.31.2). When performing the query account function to get all the account information of provided addresses on the same time,  error encountered with log as below:
![image](https://user-images.githubusercontent.com/37991051/53073878-3c672c00-3524-11e9-9030-886b3bc9e34b.png)

**What you expected to happen**:
I expect the return of account information of mutiple addresses. 

**Have you tried the latest version**: yes/no
Yes, it is in the exact latest version v0.30.0 right now.
**How to reproduce it** (as minimally and precisely as possible):
1. Initiate verifier on the client context
2. Query account information with multiple addresses on the same process

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
verifier under the client context is initialized
**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:
The error took place on the query account scenario, but I think the other key store queried would also trigger the same error.

**Comment by bradyjoestar** [comment]
It seems that you are re-Initializing DB and you did it previously.

**Comment by MattWangming** [comment]
Yes, there is nothing to do with query action without verifier. I think this issue was underlied in the verifier function when initializing DB in the same process consequently.  e.g. one process was used for one action (e.g. query), following the other action(e.g. another query), the error could be reproduced.

**Comment by melekes** [comment]
I believe this was fixed in cosmos-sdk by opening / closing the DB connection (`golevedb` unfortunately does not allow multiple open connections).

Also, please take a look at our new light client package: https://pkg.go.dev/github.com/tendermint/tendermint/lite2?tab=doc
