### ISSUE TITLE
Is the light client necessary to be part of Tendermint? 

### ISSUE THREAD

**Issue by b00f** [tendermint/tendermint#3336]
With helping services like Infura for Ethereum, does it necessary to put effort on having light client?

**Comment by ebuchman** [comment]
Yes absolutely it is! It's a key design goal of Tendermint to be light-client friendly. Services like Infura are nice but they are not trustless - you have to trust the service provider. The goal of the lite client is to allow light weight devices to do all the verification themselves, with only access to the RPC of a full node.

Also, lite client protocol is the foundation of IBC, which is necessary for the Cosmos value proposition and for anyone that wants to interoperate between two Tendermint chains :)

**Comment by b00f** [comment]
Maybe not related to this topic but a lite client also can be trustworthy specially in POS chains. Consider a chain acting like a Zombie, in this case even the full node is trustless.
I still have a big question mark in my mind that how two separate chains can securely communicate in the real world.
