### ISSUE TITLE
p2p: sent next PEX request too soon

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3338]
Some users are reporting seeing this error, potentially when talking to seeds. 

Properly functioning nodes should rate limit how often they send pex requests so they don't send them too frequently. It seems something about this logic is off. 

An example of this happening was reported in #3304, though it seems that issue is about a different problem.

**Comment by guagualvcha** [comment]
### Description
I get some log in data-seed:

```
E[2019-02-20|02:58:48.688] Stopping peer for error                      module=p2p peer="Peer{MConn{10.203.42.19:7369} d375415f420d7a664e52ed98a30a433842be930b in}" err="Peer (d375415f420d7a664e52ed98a30a433842be930b) sent next PEX request too soon. lastReceived: 2019-02-20 02:58:48.56335545 +0000 UTC m=+134240.541996690, now: 2019-02-20 02:58:48.688950674 +0000 UTC m=+134240.667591914, minInterval: 10s. Disconnecting"
E[2019-02-20|03:01:28.898] Stopping peer for error                      module=p2p peer="Peer{MConn{10.203.42.19:57821} d375415f420d7a664e52ed98a30a433842be930b in}" err="Peer (d375415f420d7a664e52ed98a30a433842be930b) sent next PEX request too soon. lastReceived: 2019-02-20 03:01:28.876270203 +0000 UTC m=+134400.854911440, now: 2019-02-20 03:01:28.89826068 +0000 UTC m=+134400.876901920, minInterval: 10s. Disconnecting"
```
### Rationale
When get a PexMessage, it will compare the receive time and lastreceive time. But if follow the step:
1、stopForError fo some peer
2、peer is removed from peerset, PEXReactor.RemovePeer is in the way but id is till not delete from requestsSent and lastReceivedRequests.
3、the same peer is connected, and receive a PexMessage
Then we will make a wrong decision that the peer send pexMessage too fast.

```
func (r *PEXReactor) receiveRequest(src Peer) error {
	id := string(src.ID())
	v := r.lastReceivedRequests.Get(id)
	if v == nil {
		// initialize with empty time
		lastReceived := time.Time{}
		r.lastReceivedRequests.Set(id, lastReceived)
		return nil
	}

	lastReceived := v.(time.Time)
	if lastReceived.Equal(time.Time{}) {
		// first time gets a free pass. then we start tracking the time
		lastReceived = time.Now()
		r.lastReceivedRequests.Set(id, lastReceived)
		return nil
	}

	now := time.Now()
	minInterval := r.minReceiveRequestInterval()
	if now.Sub(lastReceived) < minInterval {
		return fmt.Errorf("Peer (%v) sent next PEX request too soon. lastReceived: %v, now: %v, minInterval: %v. Disconnecting",
			src.ID(),
			lastReceived,
			now,
			minInterval,
		)
	}
	r.lastReceivedRequests.Set(id, now)
	return nil
}
```

What we dit in our fork:
Delete some resources in PexReactor of new peer in `InitAddPeer`, which will execute before starting MConnection.

```
func (r *PEXReactor) InitAddPeer(peer Peer) Peer {
	id := string(peer.ID())
	r.requestsSent.Delete(id)
	r.lastReceivedRequests.Delete(id)
	return peer
}
```
```
func (sw *Switch) startInitPeer(p Peer) error {
	for _, reactor := range sw.reactors {
		p = reactor.InitAddPeer(p)
	}

	err := p.Start() // spawn send/recv routines
	if err != nil {
		// Should never happen
		sw.Logger.Error(
			"Error starting peer",
			"err", err,
			"peer", p,
		)
		return err
	}

	for _, reactor := range sw.reactors {
		reactor.AddPeer(p)
	}

	return nil
}
```

**Comment by ebuchman** [comment]
> peer is removed from peerset, PEXReactor.RemovePeer is in the way but id is till not delete from requestsSent and lastReceivedRequests.

Can you clarify this? How are we trying to reconnect before RemovePeer finishes?

**Comment by hleb-albau** [comment]
Experience the same issue.

**Comment by guagualvcha** [comment]
> > peer is removed from peerset, PEXReactor.RemovePeer is in the way but id is till not delete from requestsSent and lastReceivedRequests.
> 
> Can you clarify this? How are we trying to reconnect before RemovePeer finishes?

`RemovePeer ` will first delete peer in peerSet and stop mconnection, then call every reactor to remove this peer, but the same peer will reconnect meanwhile, since peerSet do not contain it, so will try to add this peer, but  reactor to remove this peer is not finish yet.

**Comment by melekes** [comment]
**Current state**

there's a PR https://github.com/tendermint/tendermint/pull/3361 by @guagualvcha which adds `InitPeer` function to all reactors. We're still thinking about the best way to handle this issue.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3634 was merged to develop.

**Comment by melekes** [comment]
Apparently it was not fixed by #3634.

**Comment by KamiD** [comment]
is this bug fixed? 
I tracking code and found a logic error:
1. deploy 4 local node.
2. run it under 200 height, p2p: sent next PEX request too soon error will showed
3. now, peer can't keep consensus and generate block

I saw a logic in peer manager:
for example, I defined Peer A(PA) and Seed Peer(SP) in follows:
1. when peer start ,  PA will try to connect SP and update addrbook
2. after then, PA received addrbook data from SP
3. now, PA call ensurePeer to connect other peers
4. in ensurePeer function, NeedMoreAddrs function will return true. PA need pick a random peer and ask for more addrBook.
5. Unfortunately,  SP was picked up again, and PA try to ask addrbook from SP.
6. SP received the ask request and found out: "the last receive pex request is just happened less than 10s", so SP stop this peer connection
7. now, PA try to reconnect it and succeeded.
8. in func AddPeer, RequestAddrs will called, PA will try to get addrbook from SP again
9. the logic will run into 2

this is a bad logic loop, it will stop when PA not request addrbook from SP.
but while the p2p error, peer won't generate new block any more

I try to commented code：
Tendermint/p2p/pex/pex_reactor.go line：353
```go
// If this address came from a seed node, try to connect to it without
		// waiting.
		/*for _, seedAddr := range r.seedAddrs {
			if seedAddr.Equals(srcAddr) {
				r.ensurePeers()
			}
		}
		 */
```
the sent next PEX request too soon error not showed again

**Comment by melekes** [comment]
@KamiD could you please try https://github.com/tendermint/tendermint/pull/3762 and see if it fixes the problem?

**Comment by KamiD** [comment]
@melekes problem resolved, tks

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3762 to master. Will be a part of the v0.32.1 release (or next major).
