### ISSUE TITLE
consensus: loop stops if votes are not received

### ISSUE THREAD

**Issue by jleni** [tendermint/tendermint#3341]
This is related to https://github.com/cosmos/cosmos-sdk/issues/3190

**Tendermint version** 28d75ec8016b7fb043735cbe4c4d92ec73355de7

**What happened**:

The issue is easy to reproduce in single node networks (typically local testnets) but it is very **unlikely** in networks with multiple nodes.

At the moment, a transition from prevote to precommit only happens if/when votes are received (addVote adds the timeout trigger).

In a single node network, if signing a proposal or vote fails then further transitions never happen and the state machine is blocked, no timeout or trigger to move away from that state.

In typical cases, a node will always receive a vote from other nodes so the state machine recovers. In the case of single node networks  a single failure results in a stalling state machine.

**Steps to reproduce**:
* A ledger device connected to the KMS as a signer
* The proposal/vote arrives to the device and the Ledger app requests manual confirmation.
* The user takes **several seconds** to accept. A timeout is raised in `gaiad`.
* `gaiad` shows a signature error in the vote/proposal. 

At this point, unless a vote arrives from another node, there is no trigger for a transition to another state. Gaia stops requesting signatures from KMS. No other blocks or rounds will be created. 

Gaiad needs to be restarted.

While difficult a DDOS may result in signature errors and votes not arriving for longer than a full loop. 

I assume but I would need to confirm that the state machine will recover when it receives any vote, even if its height/round is much higher than the expected value in that state.

**Comment by Liamsi** [comment]
IIUC, we should make sure there is still an issue with at least 4 validators. If not, this isn't an actual problem.

**Comment by jleni** [comment]
Yes, I agree. I will prepare a test with a bigger testnet.

**Comment by ebuchman** [comment]
It would be nice if it worked even for a single validator though.

**Comment by jackzampolin** [comment]
I would be good if we could if this issue fixed.

**Comment by jleni** [comment]
This PR is related to this issue #3370

**Comment by ebuchman** [comment]
@jleni can we close this?

**Comment by jleni** [comment]
The issue was sometimes reproducible as part of the other issues but it is specifically related to the state machine. I am not sure if something has changed in there since the last time I had a look at it.

As I described at the time, the problem was that signing errors blocked the state machine and it did only move forward when triggered by other signed votes. In a multi-node network, it will normally unblock as signed votes will be received. However, when testing with a single node, after a single privval timeout, the node was not able to recover.

I am not sure if it makes sense we even fix this.. Although, it can confuse people that want to test things with a single node.
