### ISSUE TITLE
p2p: Seed node will disconnect from persistent peer if inbound

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3362]
refer to #3304

For a seed node that want catch up with chain, it will only connected to a persistent peer,
but even a peer is a persistent peer of seed according to it's config file, in the runtime,
the peer may be inbounded peer(which is not persistent) or address pick from addressbook(also not persistent), witch cause the seed node disconnected to its persistent peer.

**Comment by ebuchman** [comment]
So is this specifically about `persistent_peer` setting when `seed_mode=true`? Are you saying that the seed will disconnect from an inbound peer even if that peer is listed in the persistent_peers? Or is there something else here?

**Comment by guagualvcha** [comment]
` the seed will disconnect from an inbound peer even if that peer is listed in the persistent_peers` exactly.

**Comment by melekes** [comment]
250bytes txs for 120 sec. at 500 txs/sec. rate, so total 15MB

total bytes received from 1st node in 4 node localnet

before: 42793967 (43MB)
after:    30003256 (30MB)

total bytes sent to 1st node in 4 node localnet

before: 30569339 (30MB)
after: 19304964 (19MB)

AFTER -> BEFORE
![Screenshot 2019-03-25 at 20 47 56](https://user-images.githubusercontent.com/1282182/54949576-b5044280-4f3f-11e9-9100-b6b300b9475a.png)
![Screenshot 2019-03-25 at 20 48 06](https://user-images.githubusercontent.com/1282182/54949577-b5044280-4f3f-11e9-8396-787e0630f716.png)

**Comment by melekes** [comment]
Should be fixed by https://github.com/tendermint/tendermint/pull/3593.
