### ISSUE TITLE
RPC Design

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3367]
The Tendermint RPC endpoints evolved somewhat haphazardly and insufficient attention has been given to production concerns. We have strived to enable the default Tendermint RPC endpoints to be safe to expose over the public internet, though we in general don't recommend this.  Certain endpoints leak information (#3055), while others still pose DoS vulnerabilities (#3076). Other issues suggesting the need for a larger rethink of the RPC design include:
- #3210
- #608
- #529
- #193

There's also questions around how mature Tendermint's indexer should be, and at what point we should just stream events out to an external indexer like postgres (#1161).

Opening this issue to track discussion around the RPC, and to solicit feedback from users on what they'd like to see here.

**Comment by ebuchman** [comment]
Should have also mentioned the v0.31 work on the pubsub to not block on slow subscribers (#3227) and  to limit the number of subscribers and subscriptions per subscriber (#3269)

**Comment by mdyring** [comment]
We've been using nginx successfully in production to rate-limit and filter what RPC endpoints are exposed externally. I believe other validators are doing similarly, so it might not by a major issue.

Instead of reinventing this inside of Tendermint, my suggestion is to make RPC listen on localhost:26657 by default and then give some stern warnings and guidance on how to expose it publicly.

Happy to contribute a working nginx config if so desired.

**Comment by ebuchman** [comment]
@mdyring is that to say you see no way to improve the existing RPC? :P

**Comment by mdyring** [comment]
No, not at all. Just saying "please don't reinvent nginx" :-)

I think the idea of filtering private peers from net_info could potentially be useful, in case somebody would want to expose net_info.

+1 for supporting external indexer. Perhaps indexing should be off by default, so people enable it (and consider alternatives to internal indexer) if they actually need it.

**Comment by mappum** [comment]
Just wanted to point out some things that our light-clients rely on in Lotion-land. Other than the obvious data endpoints, we also require `/genesis`, and future versions will discover new RPC-providing peers via `/net_info`.

So if `/net_info` is going to become private, it would be nice to have an endpoint specifically for discovering potential peers' RPC ports (which could either come from the addressbook, or currently connected peers).

**Comment by ebuchman** [comment]
Another point that came up in https://github.com/interchainio/tendermint-rs/pull/77 and is sort of related to #608 is that in /abci_query, the request arguments are encoded in hex but the response is in base64. Would be great if we could address this and be consistent.

**Comment by melekes** [comment]
Support for authentication was requested in https://github.com/tendermint/tendermint/issues/4248.

**Comment by marbar3778** [comment]
Another question to ask in the redeisgn is if we want to continue with jsonrpc. There are a few options out there (REST, gRPC)

**Comment by marbar3778** [comment]
For those who have participated in this comment. We have an open ADR #4857 discussing different RPC technologies. There has not been a decision. It would be beneficial to have your inputs if possible

cc @mdyring @mappum @ebuchman

**Comment by webmaster128** [comment]
> a few options out there (REST, gRPC)

I don't see how you can implement things like transaction broadcasting cleanly in REST interface. It would most likely result in some _JSON over HTTP_ thing, but not REST. RPC over any transport seems to be much cleaner.

**Comment by alexanderbez** [comment]
Also REST vs RPC aren't really the same thing. gRPC is a protocol, whereas REST is more of a loosely defined architectural style.

**Comment by cmwaters** [comment]
Although their still remains RPC work as outlined in this tracking issue: https://github.com/tendermint/tendermint/issues/7157, I find this issue here is quite outdated and many of the initial sub issues have been merged and some of the recent concerns are not captured. I'm going to therefore close this.
