### ISSUE TITLE
(windows) WSClient cannot reconnect websocket

### ISSUE THREAD

**Issue by santatic** [tendermint/tendermint#3368]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.30.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10
- **Install tools**:
- **Others**:

**What happened**:
I reused WSClient to connect to a websocket server, when I shutdown server and start again, WSClient cannot reconnect to server.

Reason:
https://github.com/tendermint/tendermint/blob/853dd34d31bee6de593be94df87cbb508688249e/rpc/lib/client/ws_client.go#L449
https://github.com/tendermint/tendermint/blob/853dd34d31bee6de593be94df87cbb508688249e/rpc/lib/client/ws_client.go#L451

Because error return on Windows is `*net.OpError` code `WSAECONNRESET`. so function `websocket.IsUnexpectedCloseError` returned false.
Then `WSClient.readRoutine()` return and it cannot reconnect to server.

**What you expected to happen**:
WSClient can handle `*net.OpError` on Windows and retry to reconnect with error `WSAECONNRESET`

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

**Comment by tessr** [comment]
We don't make any guarantees around Windows support as a core team, but I've tagged this as `good first issue` since it seems like a good thing for a Windows user/community member to look into, and I've added it to our project icebox.
