### ISSUE TITLE
ABCI CheckEvidence / DeliverEvidence (optional)

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#3377]
Instead of passing a fixed Tendermint-determined set of evidence types in `BeginBlock` and validating evidence in the Tendermint state machine, pass all evidence to an ABCI `CheckEvidence` function which returns whether or not the evidence is valid, and call `DeliverEvidence` to instruct the application to handle evidence in the state machine (unless we wrap that into `DeliverBlock`).

This will enable more complex evidence types, such as evidence of signatures by unbonding/unbonded validators (ref https://github.com/tendermint/tendermint/issues/3244), to be implemented in applications which require them (although Tendermint will still need to construct evidence, so we'll need standardized evidence encoding formats).

**Comment by cwgoes** [comment]
Possibly a candidate for the [0.33 milestone](https://github.com/tendermint/tendermint/milestone/22).

**Comment by marbar3778** [comment]
Is this still something we should look at @cwgoes @ebuchman?

**Comment by cwgoes** [comment]
I do not know. I believe @alexanderbez is working on an evidence module directly in the SDK.

**Comment by alexanderbez** [comment]
With the advent of the evidence module, I don't think these new ABCI methods will be necessary (although could still be a nice to have). Correct me if I'm wrong @cwgoes.

**Comment by cwgoes** [comment]
I agree. Closing.
