### ISSUE TITLE
CLevelDB.Stats() returns nothing

### ISSUE THREAD

**Issue by alessio** [tendermint/tendermint#3378]
Offending line: https://github.com/tendermint/tendermint/blob/416d143bf72237c026cc289e5505ad943b88944b/libs/db/c_level_db.go#L132

It should just list the same properties used in the goleveldb implementation: https://github.com/tendermint/tendermint/blob/416d143bf72237c026cc289e5505ad943b88944b/libs/db/go_level_db.go#L126

This is blocking SDK team's efforts in benchmarks comparison between the two leveldb wrappers.

**Comment by melekes** [comment]
Merged to develop. Should land in v0.31.0
