### ISSUE TITLE
Updates to Blocks and ABCI

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#338]
- Add these fields to Block.Header:
  - `TotalTxs int64` - total number of txs sent up until this block (ie TotalTxs(H) = TotalTxs(H-1) + NumTxs(H-1))
  - `LastResultsHash []byte` - merkle hash of the `{code, data}` of the previous block's tx results
  - `EvidenceHash []byte` - merkle hash of the evidence included in the Block.Data. 

 - Add these fields to Block.Data:
   - `Evidence []ProofOfMalice`- list of proofs of double signing or lock violation

 - Save this structure with every block:

```
type BlockExtra struct {
  Proposal *Proposal
  TxResults Results
  ValidatorChanges []*tmsp.Validator
}

```

 - Add a new rpc call at `/block_extra?block=X`

- Modify BeginBlock to take a `VoteInfo` type so the app can punish Byzantine validators and effect consequences when commits don't contain votes from all validators:
  - `BeginBlock(hash []byte, header Header, voteInfo VoteInfo)`

```
type VoteInfo struct {
      // list of addresses of validators in the block.Evidence
     ByzantineValidators [][]byte 
     
     // bit-array of validators who do not have a vote in the LastCommit
     AbsentValidators *BitArray   
}
```

**Comment by melekes** [comment]
#237 seems related to this (https://github.com/tendermint/tendermint/issues/237#issuecomment-273849000). There Jae wrote his concerns about possible performance degradation due to saving an extra structure.

**Comment by melekes** [comment]
Ethan: "Yeh I'm cool with that. We don't need block extra. Index txs per TX.  But we need to store Val set changes. Maybe we have a linked list of {height, changes, lastheight} so we only store when there's changes and each points to the last one like Frey was saying"

**Comment by KrzysiekJ** [comment]
#302 and #251 have mentioned adding proposer to block header, but this issue seems to miss this. Is this idea going to be abandoned? Having a proposer in block header may be useful, as it allows punishing validators who include invalid transactions in a block.

**Comment by ebuchman** [comment]
This is still open for debate. Part of the issue is ambiguity around who the actual proposer is if a block is re-proposed across multiple rounds. But I also want to be able to punish a proposer for including invalid txs, so I agree we should figure this out.

We will be having a big design session in mid-May where we hammer out these and related questions. Please let us know if you think we should be including anything else!

**Comment by ethanfrey** [comment]
I think `LastResultsHash` is critical for safe light-client proofs.  Right now, I can verify 100% that your tx was in the block, but I trust whichever node I query when getting the result (succeeded or failed).  It would be great if this was easy to verify and intergrated with light-client.

**Comment by zramsay** [comment]
is this a stale issue, replaced by #569 ?

**Comment by ebuchman** [comment]
Not quite. #569 covers the evidence portion but we still should update the header with ResultsHash and possibly some other things

**Comment by ebuchman** [comment]
Usurped by https://github.com/tendermint/tendermint/issues/952
