### ISSUE TITLE
rpc/client: test that client resubscribes upon disconnect || subscription error

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3380]
See https://github.com/tendermint/tendermint/pull/3269#discussion_r262516515

https://github.com/tendermint/tendermint/blob/27e8cea9ce06f6a75f0b26e6993bce139a5a9074/rpc/client/event_test.go#L159-L163

we need to test that the RPC client tries to resubscribe upon network failure or subscription error.

**Comment by tessr** [comment]
Assigning to @melekes because I don't know what the context is here 😁

**Comment by melekes** [comment]
NOTE: this will require us to rewrite code in http.go and local.go to use mock server.
