### ISSUE TITLE
Reconnect and re-handshake when out-of-process ABCI application restarts

### ISSUE THREAD

**Issue by thith** [tendermint/tendermint#3388]
If Tendermint node restarts, it will reconnect and do handshake with ABCI application. However, if the ABCI application restarts, is there a way to re-establish connection and do handshake again with the Tendermint node?

Currently, I have to restart the Tendermint node whenever the ABCI application restarts. I use `js-abci`, tendermint version `0.30.0-28d75ec8`.

**Comment by melekes** [comment]
Hmm... Tendermint is supposed to stop when the application disconnects.

**Comment by thith** [comment]
> Hmm... Tendermint is supposed to stop when the application disconnects.

It says 'Stopping abci.socketClient ...', but does not attempt to re-connect when the application's live again. And there is no way to tell it to do so, except for manually restarting Tendermint itself.

**Comment by melekes** [comment]
Can you attach logs here?

**Comment by ebuchman** [comment]
We tried to work on this a while back but it seems to be a bit too involved given how some of the code is structured currently. So we decided that Tendermint would exit if the App stops/restarts and it would be the operators responsibility to restart Tendermint, for instance using a supervisor process.

See the previous discussion: https://github.com/tendermint/tendermint/issues/243

**Comment by thith** [comment]
@ebuchman I see, will use process supervisor to watch the app and restart Tendermint when necessary.
@melekes I post some logs, if you still need it. It is standalone with no block except genesis. When app restarts, Tendermint emit `Stopping abci.socketClient...`.
```
I[2019-03-17|16:10:57.124] Starting Node                                module=main impl=Node
I[2019-03-17|16:10:57.125] Started node                                 module=main nodeInfo="{ProtocolVe
rsion:{P2P:7 Block:10 App:0} ID_:f80808237444397c13f6d1588a49fd8712b5b9e7 ListenAddr:tcp://0.0.0.0:26656 Network:test-chain-krDGqt Version:0.30.0 Channels:4020212223303800 Moniker:This-MacBook-Pro.local Other:{
TxIndex:on RPCAddress:tcp://0.0.0.0:26657}}"
E[2019-03-17|16:10:57.125] Couldn't connect to any seeds                module=p2p 
I[2019-03-17|16:10:58.133] Executed block                               module=state height=1 validTxs=0 
invalidTxs=0
I[2019-03-17|16:10:58.134] Committed state                              module=state height=1 txs=0 appHa
sh=
E[2019-03-17|16:11:03.796] Stopping abci.socketClient for error: EOF    module=abci-client connection=con
sensus
E[2019-03-17|16:11:03.796] Stopping abci.socketClient for error: EOF    module=abci-client connection=que
ry
E[2019-03-17|16:11:03.796] Stopping abci.socketClient for error: EOF    module=abci-client connection=mem
pool
E[2019-03-17|16:11:27.127] Couldn't connect to any seeds                module=p2p 
E[2019-03-17|16:11:31.104] Failed to read request                       module=rpc-server protocol=websoc
ket remote=[::1]:59048 err="websocket: close 1001 (going away)"
E[2019-03-17|16:11:31.104] Error closing connection                     module=rpc-server protocol=websoc
ket remote=[::1]:59048 err="close tcp [::1]:26657->[::1]:59048: use of closed network connection"
E[2019-03-17|16:11:33.023] Error on broadcastTxCommit                   module=rpc err=EOF
```

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/745713330736c5c751450245d88b8037cbee3aa6/proxy/multi_app_conn.go#L29

**Comment by tessr** [comment]
Looks like this was likely fixed by https://github.com/tendermint/tendermint/pull/5078.
