### ISSUE TITLE
Update golang.org/x/crypto

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#3391]
We removed pinning golang.org/x/crypto to a specific version via #2844. The version in Gopkg.toml still points to https://github.com/golang/crypto/commit/505ab145d0a99da450461ae2c1a9f6cd10d1f447

review what happened in the meantime and update this dependency.

related lengthy discussion: #3374

Currently used in:
![image](https://user-images.githubusercontent.com/7441766/53976119-ab3cab80-4106-11e9-8d15-5dbf07e7d07c.png)

**Comment by Liamsi** [comment]
I've reviewed the all changes that happened since the commit we were pinning to. Below is a list of changes for the packages we import directly.

For the openpgp package:
 - no changes in the armor package since years
 - some ineffassigns were fixed via: https://github.com/golang/crypto/commit/b8fe1690c61389d7d2a8074a507d1d40c5d30448#diff-e7ace1eeeac9cdf4f5fe331bf53e3fb2

For ed25519:
 - no changes: https://github.com/golang/crypto/commits/master/ed25519

ripemd160:
- some typos were fixed: https://github.com/golang/crypto/commit/45a5f77698d342a8c2ef8423abdf0ba6880b008a#diff-742a86b16bfa1a2e8e684a4995aff055
 - got deprecated https://github.com/golang/crypto/commit/a57398324d7b9ce8afc47fed8168be52977536f1#diff-742a86b16bfa1a2e8e684a4995aff055

chacha20poly1305:
 - no changes: https://github.com/golang/crypto/commits/master/chacha20poly1305

curve25519:
 - compatibility with RFC 7748 by masking most significant bit if retrieving field element from bytes: https://github.com/golang/crypto/commit/193df9c0f06f8bb35fba505183eaf0acc0136505#diff-b4f5c08f4e7644d9aed48b0e2e358934

nacl/box:
 - no changes: https://github.com/golang/crypto/commits/master/nacl/box
nacl/secretbox:
 - no changes: https://github.com/golang/crypto/commits/master/nacl/secretbox

hkdf:
 - improved a test / example in: https://github.com/golang/crypto/commit/d2c3f1d8b9537a0fec2a2d4b1df405ac091cd7f3#diff-0986bf341fc395abb5845cf0c7cb096b
- added methods `Extract/Expand` (which we don't use): https://github.com/golang/crypto/commit/e84da0312774c21d64ee2317962ef669b27ffb41#diff-0986bf341fc395abb5845cf0c7cb096b

brcypt:
 - only test improvements: https://github.com/golang/crypto/commit/bc7917b19d8f099105de72dc62898400be07c984#diff-51f01b313d48b72f46376150e6e12a98

**Comment by melekes** [comment]
Merged to develop.
