### ISSUE TITLE
Close Iterator in RemoteDB

### ISSUE THREAD

**Issue by Stumble** [tendermint/tendermint#3402]
https://github.com/tendermint/tendermint/blob/e0f8936455029a40287a69d5b0e7baa4d5864da1/libs/db/remotedb/grpcdb/server.go#L139-L161

Though this part of codes does not seem to be used for now, but in case it's used in the future, do we need to close the Iterator in `handleIterator`?

**Comment by melekes** [comment]
Good catch! I think `Iterator` and `ReverseIterator` (which are using `handleIterator`) should close it.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3424 to develop.
