### ISSUE TITLE
Wrong version in install_tendermint_ubuntu.sh

### ISSUE THREAD

**Issue by mgmgwi** [tendermint/tendermint#3405]
Hi,
this might be the wrong place for the issue, if so, then please point me to the right one.

Problem: The script [install_tendermint_ubuntu.sh](https://raw.githubusercontent.com/tendermint/tendermint/develop/scripts/install/install_tendermint_ubuntu.sh)  does contain the following line:

`GO_VERSION=1.12.0`

That variable is used to build the download URL for go:

`curl -O https://storage.googleapis.com/golang/go$GO_VERSION.linux-amd64.tar.gz`

unfortunatly there is no file https://storage.googleapis.com/golang/go1.12.0.linux-amd64.tar.gz

Changing the version to:

`GO_VERSION=1.12`

fixes the problem.

Best regards,
Guido

**Comment by Liamsi** [comment]
Thanks a lot for reporting this!

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3411 to develop.
