### ISSUE TITLE
Follow-up to PR #3269

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3410]
- [x] https://github.com/tendermint/tendermint/pull/3269#discussion_r264185012
- [x] clarify: do we really need to add `ctx` everywhere although it is used rarely?
- [x] https://github.com/tendermint/tendermint/pull/3269/files#r261048439
- [x] https://github.com/tendermint/tendermint/pull/3269#discussion_r262519335

**Comment by ebuchman** [comment]
I think the first point can be moved to a separate issue: https://github.com/tendermint/tendermint/issues/3433

For the other linked points, can we please add a small description so we can more easily remember what they are without having to load the heavy PR comments?
