### ISSUE TITLE
The transaction  that failed to be included in a block should not cache in mempool.

### ISSUE THREAD

**Issue by ArvonHuang** [tendermint/tendermint#3414]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.20.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Bill

**Environment**:
- **OS** (e.g. from /etc/os-release):
Linux mach1 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- **Install tools**:
docker
- **Others**:

**What happened**:

I broadcast a transaction to tendermint , it failed whit a response of "Timed out waiting for transaction to be included in a block" . Then I try broadcast  again. It responsed "broadcastTxCommit: Tx already exists in cache"

**What you expected to happen**:
The transaction  that failed to be included in a block should not cache in mempool.

**Have you tried the latest version**: yes/no
no

**How to reproduce it** (as minimally and precisely as possible):
when the network is not steady.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

`
time="2019/03/12 11:34:11" level=debug msg=-------------------begin------------------
time="2019/03/12 11:34:11" level=debug msg="&{POST / HTTP/1.1 1 1 map[Userkey:[sdy] Pragma:[no-cache] Content-Type:[application/json-rpc] Cache-Control:[no-cache] User-Agent:[Java/1.7.0_71] Accept:[text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2] Connection:[keep-alive] Content-Length:[314]] 0xc42024a200 <nil> 314 [] false 10.16.85.110:8223 map[] map[] <nil> map[] 10.16.8.69:45582 / <nil> <nil> <nil> 0xc42024a240}"
time="2019/03/12 11:34:11" level=debug msg="handleBroadcast:{\"Value\":{\"BillTransferSign\":{\"mideaDraftId\":\"MM1088360201903060009S\"}},\"userName\":\"MED556366\",\"instructionId\":30114085938900940,\"pubkey\":\"HNugjHKihOex3X/KpsDt44xqitr7i4Kmuq8C7yvEqeQ=\",\"sign\":\"C3yxjZgwdf5Nr2T1SJzcJk6tw+JPCQ/ggC8iBMsxKUELiPYGkJaPDETRKJ2pgg4c3PKIVRISPDRY0r388c62Ag==\",\"actionId\":16,\"operatorTime\":1552361649}"
time="2019/03/12 11:36:11" level=debug msg="BroadcastTxCommitResult:{\"jsonrpc\":\"2.0\",\"id\":\"jsonrpc-client\",\"error\":{\"code\":-32603,\"message\":\"Internal error\",\"data\":\"Timed out waiting for transaction to be included in a block\"},\"result\":{\"check_tx\":{\"code\":0,\"data\":\"\",\"log\":\"\",\"fee\":{}},\"deliver_tx\":{\"code\":0,\"data\":\"\",\"log\":\"\",\"tags\":null,\"fee\":{}},\"hash\":\"\",\"height\":0}}"
time="2019/03/12 11:36:11" level=error msg="Timed out waiting for transaction to be included in a block"
time="2019/03/12 11:36:11" level=debug msg="{\"id\":\"-9056169492124529826\",\"result\":{\"code\":2010,\"message\":\"block chain: broadcast commit err, internal err ,Timed out waiting for transaction to be included in a block\",\"data\":null},\"error\":null}\n"
time="2019/03/12 11:36:11" level=debug msg=-------------------end--------------------/n

time="2019/03/12 11:36:57" level=debug msg=-------------------begin------------------
time="2019/03/12 11:36:57" level=debug msg="&{POST / HTTP/1.1 1 1 map[Cache-Control:[no-cache] User-Agent:[Java/1.7.0_71] Content-Length:[313] Userkey:[sdy] Content-Type:[application/json-rpc] Connection:[keep-alive] Pragma:[no-cache] Accept:[text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2]] 0xc4200616c0 <nil> 313 [] false 10.16.85.110:8223 map[] map[] <nil> map[] 10.16.8.69:45582 / <nil> <nil> <nil> 0xc420061700}"
time="2019/03/12 11:36:57" level=debug msg="handleBroadcast:{\"Value\":{\"BillTransferSign\":{\"mideaDraftId\":\"MM1088360201903060009S\"}},\"userName\":\"MED556366\",\"instructionId\":30114085938900940,\"pubkey\":\"HNugjHKihOex3X/KpsDt44xqitr7i4Kmuq8C7yvEqeQ=\",\"sign\":\"C3yxjZgwdf5Nr2T1SJzcJk6tw+JPCQ/ggC8iBMsxKUELiPYGkJaPDETRKJ2pgg4c3PKIVRISPDRY0r388c62Ag==\",\"actionId\":16,\"operatorTime\":1552361649}"
time="2019/03/12 11:36:57" level=debug msg="BroadcastTxCommitResult:{\"jsonrpc\":\"2.0\",\"id\":\"jsonrpc-client\",\"error\":{\"code\":-32603,\"message\":\"Internal error\",\"data\":\"Error on broadcastTxCommit: Tx already exists in cache\"},\"result\":{\"check_tx\":{\"code\":0,\"data\":\"\",\"log\":\"\",\"fee\":{}},\"deliver_tx\":{\"code\":0,\"data\":\"\",\"log\":\"\",\"tags\":null,\"fee\":{}},\"hash\":\"\",\"height\":0}}"
time="2019/03/12 11:36:57" level=error msg="Error on broadcastTxCommit: Tx already exists in cache"
time="2019/03/12 11:36:57" level=debug msg="{\"id\":\"4467883668033597450\",\"result\":{\"code\":2010,\"message\":\"block chain: broadcast commit err, internal err ,Error on broadcastTxCommit: Tx already exists in cache\",\"data\":null},\"error\":null}\n"
time="2019/03/12 11:36:57" level=debug msg=-------------------end--------------------/n`

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by ArvonHuang** [comment]
@ebuchman ， hi , sorry to bother. can you give me any suggestions.
should i add some remove chache code in 
`case <-timer.C:
		logger.Error("failed to include tx")
		return &ctypes.ResultBroadcastTxCommit{
			CheckTx:   *checkTxR,
			DeliverTx: abci.ResponseDeliverTx{},
			Hash:      tx.Hash(),
		}, fmt.Errorf("Timed out waiting for transaction to be included in a block")
	}`
of file /rpc/core/mempool ?

**Comment by melekes** [comment]
> The transaction that failed to be included in a block should not cache in mempool.

Why is this an expectation? 

The way transaction is added right now when you use `broadcast_tx_commit` is a) it first gets added to the mempool b) proposer picks it up and creates a block c) when the block containing this particular transaction is committed, we return a result in `broadcast_tx_commit`.

NOTE you shouldn't use `broadcast_tx_commit` other than for testing and development.

0.20 is outdated. Please upgrade to the latest version - 0.30.2

**Comment by ArvonHuang** [comment]
> Why is this an expectation?
>
> The way transaction is added right now when you use `broadcast_tx_commit` is a) it first gets added to the mempool b) proposer picks it up and creates a block c) when the block containing this particular transaction is committed, we return a result in `broadcast_tx_commit`.
>
what if b) proposer picks it up and fails to create a block due to timeout or other factor. I find that in `broadcast_tx_commit` we call `mempool.CheckTx(tx,...)` and in `CheckTx` we push tx to mempool and write WAL. Then we include this tx into a block, but when timed out waiting for transaction to be included in a block happends, shouldn't we rollback pushing tx in the mempool  and writing WAL?

**Comment by ArvonHuang** [comment]
> NOTE you shouldn't use `broadcast_tx_commit` other than for testing and development.
you mean we shouldn't use `broadcast_tx_commit` in production?

**Comment by ArvonHuang** [comment]
> 0.20 is outdated. Please upgrade to the latest version - 0.30.2

we have migrated tm from 0.10 to 0.20 in production and everything goes well except this situation.

**Comment by melekes** [comment]
> you mean we shouldn't use broadcast_tx_commit in production?

Yes. Use `/broadcast_tx_sync` to make sure tx makes it to the mempool and WS client OR indexer to get the result(s).

**Comment by melekes** [comment]
> but when timed out waiting for transaction to be included in a block happends, shouldn't we rollback pushing tx in the mempool and writing WAL?

Most of the clients will want their transaction to be committed (maybe at some later point).

**Comment by melekes** [comment]
If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org)
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint)
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint)

**Comment by ArvonHuang** [comment]
> Yes. Use `/broadcast_tx_sync` to make sure tx makes it to the mempool and WS client OR indexer to get the result(s).

Thx very much.

**Comment by ArvonHuang** [comment]
> If you have any further questions, please ask them here OR

Sure

**Comment by ebuchman** [comment]
> when timed out waiting for transaction to be included in a block happends, shouldn't we rollback pushing tx in the mempool and writing WAL?

Also note this isn't necessarily a real error. It just means the tx didn't get included in a block within the specified timeout (10 seconds). The tx can still be committed later. `/broadcast_tx_commit` is a tough endpoint. In the upcoming v0.31.0, you can set the `timeout_broadcast_tx_commit` config value yourself to be greater than 10s. In any case it's probably best to use `/broadcast_tx_sync` and poll to see if the tx was committed

**Comment by song-liu** [comment]
"Error on broadcastTxCommit: Tx already exists in cache" causes headaches. It should have options to cache or not cache.
For example, in your KVstore sample code, if you do below for updating a validator,
curl 'localhost:26657/broadcast_tx_commit?tx="val:address/10"'
curl 'localhost:26657/broadcast_tx_commit?tx="val:address/0"'
curl 'localhost:26657/broadcast_tx_commit?tx="val:address/10"'
You will get "Tx already exists in cache". Nonce has to added everywhere, but in many cases, it's not necessary for some key-values.
Thanks.

**Comment by ebuchman** [comment]
You can disable the behaviour by setting `mempool.cache_size = 0` in the config. Is that sufficient?
