### ISSUE TITLE
ClevelDB memory leak contd

### ISSUE THREAD

**Issue by Stumble** [tendermint/tendermint#3416]
We need to update deps after https://github.com/tendermint/iavl/pull/130 is merged and released.

btw, why not move IAVL into this repo?

**Comment by Liamsi** [comment]
> btw, why not move IAVL into this repo?

AFAIR, Tendermint does not depend on iavl. And iavl only uses very few things from tendermint. IMHO it would be more reasonable to remove the dependency on tendemint in iavl instead (related discussion: https://github.com/tendermint/iavl/issues/46)

**Comment by Stumble** [comment]
@Liamsi i see (I was wondering why I can't find it in gopkg file).
