### ISSUE TITLE
privval: priv_validator.json shouldn't be split

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#3418]
Tendermint now by default generates separate priv_validator.json and priv_validator_state.json files.  Whatever the reason for putting the "state" in the data dir, the file shouldn't be split, as it can cause accidental double-signing by getting the two out of sync (e.g. deleting the data dir but not the config dir).

**Comment by ebuchman** [comment]
Here's the original issue: https://github.com/tendermint/tendermint/issues/1181

Default priv validator isn't really designed to be a secure way to run a validator (eg. it's not encrypted).

That said we can potentially mitigate here by creating the _state.json if it doesn't exist based on the blockchain height once we're synced.

Also related: https://github.com/tendermint/tendermint/issues/809

**Comment by marbar3778** [comment]
I do believe https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-051-double-signing-risk-reduction.md would be a better approach than merging the two files.

>That said we can potentially mitigate here by creating the _state.json if it doesn't exist based on the blockchain height once we're synced.

this should be done anyways regardless of the ADR implementation

**Comment by melekes** [comment]
agree, combined approach should eliminate most of the issues.

**Comment by melekes** [comment]
> e.g. deleting the data dir but not the config dir

Tendermint won't start if there's a `priv_validator_key.json`, but no `priv_validator_state.json` file.

**Comment by melekes** [comment]
Actually, I think https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-051-double-signing-risk-reduction.md is sufficient to cover all use-cases. Please reopen if you disagree.
