### ISSUE TITLE
rpc: support TLS

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3419]
For now, a node expose rpc service based on http rather than https, it is not secure.
Two phrase to go:
1. Cli add an tls option, node stay still. We may put an ALB before node so that ALB can change tls into http.
2. node can add tls option.

**Comment by melekes** [comment]
Should not be hard to add this feature. We already have TLS server https://github.com/tendermint/tendermint/blob/4cbd36f341c8fee55a4ea386aee42a2c7fe9c67d/rpc/lib/server/http_server.go#L62. We just need to add config options and possibly `--rpc.tls` flag to node cmd.

**Comment by guagualvcha** [comment]
Good news, and thks for response. I think a bit more work of cli will add this future then.

**Comment by melekes** [comment]
We'll need to:
- add `rpc.tls_cert_file` config option
- add `rpc.tls_key_file` config option
- in node.go when creating an RPC server if tls_cert_file and tls_key_file are both present, use `StartHTTPAndTLSServer` function instead of `StartHTTPServer`

**Comment by zramsay** [comment]
closed in #3469
