### ISSUE TITLE
LOG setting in docker-compose.yml seems wrong

### ISSUE THREAD

**Issue by mgmgwi** [tendermint/tendermint#3421]
Hi,
this line in docker-compose.yml seems wrong (also the LOG lines for the other nodes):

https://github.com/tendermint/tendermint/blob/976819537d199aa43c6ad55ec4e8958323322bb0/docker-compose.yml#L11

This creates a logfile named _${LOG:-tendermint.log}_ in .build/node0 when running `make localnet-start`

Removing the first `$` fixes the problem in my environment (Ubuntu 18.04.2):

`      - LOG=${LOG:-tendermint.log}`

Best Regards,
Guido

**Comment by pixelschnitzel** [comment]
I confirm that problem. Removing the leading $ also fixes it for me.

**Comment by melekes** [comment]
Oops.. Thank you for reporting it 👍

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3423 to develop.
