### ISSUE TITLE
using zap instead go-kit in the logger?

### ISSUE THREAD

**Issue by bradyjoestar** [tendermint/tendermint#3428]
currently we used `go-kit` as a logger. Maybe it's better to instead of it?
[zap](https://github.com/uber-go/zap)  :smiley_cat:

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/358#issuecomment-286471116

**Comment by ebuchman** [comment]
Wow the zap benchmarks are pretty enticing, could be worth considering

**Comment by xla** [comment]
Is performance affected by logging throughput? What other upsides woud a replacement have?

**Comment by ebuchman** [comment]
> Is performance affected by logging throughput? 

Anecdotally, it seems to be the case at least that DEBUG logs slow things down.  Worth measuring though.

**Comment by marbar3778** [comment]
https://github.com/go-kit/kit/blob/master/log/zap/zap_sugar_logger.go, possible option since we already have go-kit as a dep

**Comment by melekes** [comment]
also https://github.com/rs/zerolog might be an even better option

**Comment by tessr** [comment]
Before swapping out the logger, we'd like to benchmark the various loggers against one another, using the Tendermint code to generate relevant results. The current candidates are:

* go-kit's [sync logger](https://github.com/go-kit/kit/blob/master/log/sync.go#L94) (the current logger)
* uber-go/zap
* rs/zerolog 

Contributions welcome!

**Comment by melekes** [comment]
@alessio proposed github.com/sirupsen/logrus (https://github.com/tendermint/tendermint/issues/5572)

**Comment by gsora** [comment]
Hello from commercio.network 😄

It would be really nice for the logger to be able to write to plain files *and* output to some other logging framework, something like systemd's journal.

Zap surely is one of the most advanced, well-maintained structured logging libraries out there: we've been using it for our internal services for quite some time now, it strikes the right balance between feature completeness, performance and usability.

Having plaintext, structured log files would greatly help when dealing with large-scale deploys!

In an enterprise setup, one could leverage stuff like this to send logs over a Datadog instance, set up metrics and alerts over there, all by just setting up a simple daemon.

On the other hand, given the situation where we (commercio) are right now, having centralised logs in systemd journal is far easier and quicker, and would allow us to have a completely managed daemon lifecycle without reinventing the wheel.

All Tendermint must do is to just provide structured logs.

Using *de facto* standard interfaces and libraries enables us - users - employ approaches and techniques known for years and which could seriously help maintaining Tendermint-based software on the long run, while keeping the developer cognitive load low (no need for new libraries, log rotation algorithms, file truncation headaches...).

In both cases, even just having structured logging could help **a lot**, and will surely contribute to the enterprise levelling-up we're all looking for 🎉

**Comment by alexanderbez** [comment]
++ to structured and configurable logging. I'm not sure why we even have a wrapper around go-kit. We should use zap or zerolog with the ability to support JSON and text (console) logging with configurable levels and outputs.

**Comment by melekes** [comment]
> I'm not sure why we even have a wrapper around go-kit.

the idea was so that one can change the underlying logger without rewriting half of the Tendermint code.

btw, what we have right now is a structured logging https://github.com/go-kit/kit/tree/master/log#package-log. And we do support JSON format with configurable levels.

**Comment by alexanderbez** [comment]
How do you get JSON output? And why the need for multiple logger types? What is it advantageous to swap out loggers?

**Comment by gsora** [comment]
Upon further inspection, Tendermint do support setting alternative [log.Logger](https://github.com/tendermint/tendermint/blob/master/libs/log/logger.go) implementations.

Maybe this change should happen in the Cosmos SDK itself?

**Comment by alexanderbez** [comment]
I think that's fine @gsora -- I didn't realize it was an interface. I would opt for zap or zerolog in the SDK. If there is agreement, can you close this and open an issue in the SDK and I'll be sure to tackle it.

**Comment by melekes** [comment]
> How do you get JSON output? And why the need for multiple logger types? What is it advantageous to swap out loggers?

To get JSON, use https://github.com/tendermint/tendermint/blob/243ff4b43dc9f0622b54d610779c59fd4baa41a9/libs/log/tm_json_logger.go#L13 `NewTMJSONLogger`. Tendermint may be used as a library, using an interface allows Tendermint users to use any logger as long as it implements the `log.Logger` interface.

**Comment by alexanderbez** [comment]
Started a PR in the SDK -> https://github.com/cosmos/cosmos-sdk/pull/8072

**Comment by melekes** [comment]
Reopening this since I still want to see the benchmarks https://github.com/tendermint/tendermint/issues/3428#issuecomment-474967255 and, potentially, replace go-kit with zap.

**Comment by alexanderbez** [comment]
Apologies @melekes!

**Comment by marbar3778** [comment]
linking https://github.com/tendermint/tendermint/issues/6502 as an example of the current longer using too much memory

**Comment by alexanderbez** [comment]
I support removing Tendermint's logger all together while keeping the interface. I would opt to have a wrapper around zerolog that implements this interface.

**Comment by odeke-em** [comment]
So with some custom logging, my team and I, 1.2 years ago produced these benchmarks https://gist.github.com/odeke-em/3aba9267803d7813ab99fa743d5b8b8d#file-results-md rs/zerolog is mos def what we want to go for /cc @cuonglm @kirbyquerby

**Comment by marbar3778** [comment]
closed via #6534
