### ISSUE TITLE
rpc: pipe should use a struct to wrap all the global objects

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3433]
rpc/core/pipe.go allows a number of high level objects to be registered for use with the rpc. 

This creates a lot of global variables in the pkg. It might be nicer if these were contained in a single RPCEnvironment (?) struct.

Mentioned recently in https://github.com/tendermint/tendermint/pull/3269#discussion_r263348542

**Comment by melekes** [comment]
Should help us fix https://github.com/tendermint/tendermint/pull/3524#discussion_r278036869
