### ISSUE TITLE
TimeoutBroadcastTxCommit should overwrite the WriteTimeout limit

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3435]
Go servers only allow you to set a global WriteTimeout on the server, where the WriteTimeout starts after the request header is read, so it sets an absolute lifetime for the request.

It would be nicer if it started instead when we started writing the response, but now it can't be changed because Go v1 compatibility (see https://github.com/golang/go/issues/24461).

Worse, you can't set the WriteTimeout on a per request basis, only globally, since there's no way to access the underlying connection. There is some discussion in https://github.com/golang/go/issues/16100 but it's unclear if/when that will land.

This means the timeout for broadcast tx commit MUST be smaller than the configured WriteTimeout. This is currently hard coded at 20s. While the TimeoutBroadcastTxCommit is exposed in the config as of #3269, the WriteTimeout is not. We also throw an error if `TimeoutBroadcastTxCommit > WriteTimeout`. Instead, for now, we should just set `WriteTimeout = TimeoutBroadcastTxCommit + delta` so users can set the TimeoutBroadcastTxCommit as high as necessary, and the rpc WriteTimeout will just be equally as high, and we'll clearly document what's happening.

It's a bit silly to increase the global WriteTimeout just because you want a higher timeout for one endpoint (broadcast tx commit), but there isn't really a better alternative for now. Once https://github.com/golang/go/issues/16100 is implemented, then timeout_broadcast_tx_commit can be independent of WriteTimeout, and as large as the user wants.

**Comment by melekes** [comment]
Are there any security implications? Should we inform the user about that?

**Comment by Liamsi** [comment]
Just to be clear: do we want to expose `WriteTimeout` as a config (and set it depending on `TimeoutBroadcastTxCommit`), or do we just want to keep the 20 sec default and only set it to `WriteTimeout = TimeoutBroadcastTxCommit + delta` only if the `TimeoutBroadcastTxCommit` exceeds 20s?

**Comment by ebuchman** [comment]
I think maybe the simplest thing for now is to just expose TimeoutBroadcastTxCommit in the config, give it a default of `10s`, and always set the `WriteTimeout = TimeoutBroadcastTxCommit + 2s`

**Comment by Liamsi** [comment]
Hmm, I've added a `func AdjustWriteTimeout(cfg config.RPCConfig) (changed bool)` method to the `rpcserver` package and call it inside of `rpccore.SetConfig(*n.config.RPC)` (which is called by `Node.ConfigureRPC`). Maybe that's too complicated 🤔 Will push shortly. Let me know what you think.

**Comment by xla** [comment]
Just to capture the concern I raised during the team meeting on 2019-03-18: If it turns out that the endpoint semantics are hard to fullfill with the protocol - and increasing the timeout astronomically (space joke) seems to hint at that - we should explicitely deprecate that endpoint and advertise the alternative.

**Comment by melekes** [comment]
Done in https://github.com/tendermint/tendermint/pull/3443.
