### ISSUE TITLE
Consider upstreaming Loom's changes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3436]
Loom's fork of Tendermint is at https://github.com/mattkanwisher/tendermint

It contains three primary changes:
- [x] support for injecting an external reactor (related to #3176) - https://github.com/mattkanwisher/tendermint/pull/1
- [ ] expire old txs in the mempool (related to #2834) - https://github.com/mattkanwisher/tendermint/pull/3
- [ ] expose tx height over the RPC - https://github.com/mattkanwisher/tendermint/pull/2

I think if we want to support the tx eviction idea, we can upstream all these changes, but instead of a new rpc endpoint, just break /unconfirmed_txs by adding the height info. At the least we can include the first change as first step in #3176

**Comment by xla** [comment]
@ebuchman Should we break this issue apart and track in three individuals so we can take one at a time?

**Comment by ebuchman** [comment]
Yes but the first two points kind of already have their own issues, so this one could just serve the third?

**Comment by xla** [comment]
> Yes but the first two points kind of already have their own issues, so this one could just serve the third?

Yessir! Want me to rework?

**Comment by jackzampolin** [comment]
Any updates here?

**Comment by marbar3778** [comment]
closing this as the implementations have diverged far enough its not worth trying to upstream things.
