### ISSUE TITLE
Allow setting tags to index at runtime 

### ISSUE THREAD

**Issue by thith** [tendermint/tendermint#3437]
I am developing an Tendermint application that supports user-uploaded smart contracts. A smart contract is allowed to emit tags, specifying some to be indexed, some not. Indexed tags would cost more gas but useful for that smart contract's clients.

Currently, AFAIK, the only way to allow this is config to index _all_ tags, which is not optimal. I would be great if Tendermint let applications specify additional tags to index on deliver_tx.

**Comment by ebuchman** [comment]
See the config file:

```
# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""
```

Is this what you're looking for?

**Comment by thith** [comment]
How can I add items into index_tags from within the ABCI application at runtime, when both the node and the application is running? That is what I am looking for.

**Comment by melekes** [comment]
There's currently no way to tell Tendermint to index tags at runtime.

But we can probably do smth like:

```
tags: [
  {key: "account.number", value: "1", index: true},
]
```

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/1859

**Comment by thith** [comment]
> ```
> tags: [
>   {key: "account.number", value: "1", index: true},
> ]
> ```

Yes, that is what I am looking for. If the ABCI app supports smart contracts, the it is smart contract author' who requests which tags to index, at runtime.

**Comment by thith** [comment]
Is there any plan about this @melekes ?
This feature is essential for applications that support smart contract to emit arbitrary events (similar to Ethereum's).

**Comment by melekes** [comment]
Do you want to contribute?

**Comment by thith** [comment]
> Do you want to contribute?

My colleague, @favadi, has made the pull request. Could you take a look?
