### ISSUE TITLE
Mempool cache

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#345]
- [ ] https://github.com/tendermint/tendermint/blob/master/mempool/mempool.go#L48 (connection handling is not a priority right now)
- [x] make the cache size configurable
- [x] handle full cache more gracefully (limit the mempool to the size of the cache as well? boot transactions on a timer rather than just when its full?)

**Comment by ebuchman** [comment]
Consider a config flag for disabling the mempool's inbuilt replay protection (eg. https://github.com/tendermint/tendermint/issues/458)

**Comment by ebuchman** [comment]
Also need to bound the mempool

**Comment by ebuchman** [comment]
See #1539 re making the cache the mempool bound and removing list from txCache and removing an extra call to Exists

**Comment by melekes** [comment]
> ebuchman opened this issue on 29 Dec 2016

an old one

**Comment by melekes** [comment]
![tx_flow_diagram_broadcast_tx_sync](https://user-images.githubusercontent.com/1282182/40166273-3491c6ba-59cf-11e8-8948-d8383337120f.png)

maybe we can include this in docs somewhere?

**Comment by melekes** [comment]
> Consider a config flag for disabling the mempool's inbuilt replay protection (eg. #458)

here you mean txCache basically, right?

**Comment by melekes** [comment]
> handle full cache more gracefully (limit the mempool to the size of the cache as well? boot transactions on a timer rather than just when its full?)

mempool is now limited https://github.com/tendermint/tendermint/commit/0f8c6524180f37bb0f23e0ec3f55b09aa628dcbe

do we want to make cache eviction more aggressive? like remove 100 elements, not just one (from the end of the list).

**Comment by melekes** [comment]
> https://github.com/tendermint/tendermint/blob/master/mempool/mempool.go#L267

no longer relevant, I guess. since ABCI only defines 0 code.

> https://github.com/tendermint/tendermint/blob/master/mempool/mempool.go#L47

speaking about "connection handling", where is this part exactly? I see that there is `Error()` method available on proxyApp. Shouldn't we deal with connection issues on the lower level (abci socket client)? and only if we can't reconnect/write after N attempts, we should bubble up the error to the mempool?

**Comment by ebuchman** [comment]
> here you mean disabling txCache, right? in that case, one can set cache_size to 0 to achieve the same thing.

yeh

> do we want to make cache eviction more aggressive? like remove 100 elements, not just one (from the end of the list).

yeh we could. though not sure it's necessary.

> no longer relevant, I guess. since ABCI only defines 0 (success) code.

Correct :)

> Shouldn't we deal with connection issues on the lower level (abci socket client)? and only if we can't reconnect/write after N attempts, we should bubble up the error to the mempool?

Possibly, but I'm not sure if it's worth it yet. This also plays into how we handle application restarts, and the answer for now is just "restart Tendermint".

**Comment by ebuchman** [comment]
@melekes should we close this?

**Comment by melekes** [comment]
yes
