### ISSUE TITLE
RPC Client interface does not include NetworkClient

### ISSUE THREAD

**Issue by jacohend** [tendermint/tendermint#3458]
**Tendermint version**: Master as of commit e0f8936455029a40287a69d5b0e7baa4d5864da1 (0.31.0)

**What happened**:

As I was making my RPC interface more generic (using client.Client), I found my rpc.NetInfo calls were not compiling. I looked at the source code and found no NetworkClient in the Client interface: https://github.com/tendermint/tendermint/blob/master/rpc/client/interface.go#L72

**What you expected to happen**:

The Client interface should include the NetworkClient, otherwise full-featured tests and any other usage that swaps out the underlying interface will fail if the user wishes to test/use NetInfo or any other NetworkClient rpc call. 

**Have you tried the latest version**: yes

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3473 to develop.
