### ISSUE TITLE
Make Tendermint HTTP RPC arguments not take JSON?

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#346]
When running https://tendermint.com/intro/getting-started/deploy-testnet , and attempting to run dummy to query for "abcd", it doesn't work.

broadcast_tx_sync?tx=\"abcd\" is actually posting the hex bytes, 0xabcd as the transaction, not the string "abcd".  We should probably fix this to be more intuitive.  We should also update the tutorial.

So, to query, you have to do:

> query 0xabcd

The return says, {"index":0,"value":"\ufffd\ufffd","exists":true}, the \ufffd is an artifact of stringifying 0xabcd in JSON.  This is also confusing.

Ideally we can call broadcast_tx_sync?tx=0xabcd, which would be consistent w/ tmsp-cli query.  I think we can make a rule in go-rpc HTTP handler.go that anything preceded by "0x" is to be interpreted as bytes, otherwise is a JSON thing.

Also, https://tendermint.com/intro/getting-started/deploy-testnet still refers to "broadcast_tx", when it should be broadcast_tx_sync.

**Comment by jaekwon** [comment]
Maybe we should also change the tx broadcast_tx_* arg type to be a string rather than []byte, so that ?tx="abcd" actually means the string "abcd".

Then if we also change tmsp-cli query to require quotes, we have parity.

```
broadcast_tx_sync?tx="abcd"
> query "abcd"

or,

broadcast_tx_sync?tx=0xabcd
> query 0xabcd
```

**Comment by mappum** [comment]
PRs to merge:
- [ ] Fix tutorial URI - https://github.com/tendermint/tendermint.github.io/issues/22
- [ ] Fix RPC string argument handling - https://github.com/tendermint/go-rpc/pull/5
- [ ] tmsp-cli arg handling - https://github.com/tendermint/tmsp/pull/43

**Comment by jaekwon** [comment]
@ebuchman The above PRs LGTM.

**Comment by ebuchman** [comment]
All merged onto develop. Thanks Matt!
