### ISSUE TITLE
replayBlocks checkAppHash should't wait the last block

### ISSUE THREAD

**Issue by Zerppen** [tendermint/tendermint#3460]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0d985ede28bd6937fa9d3613618e42cab6fc871c

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
there are some code should be enhanced

**What you expected to happen**:
I will contribute code later
**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by Zerppen** [comment]
I will enhance it and contribute code

**Comment by Liamsi** [comment]
> there are some code should be enhanced

Could you please explain a bit what you mean here?

**Comment by Zerppen** [comment]
@Liamsi  current replay logic,only the last block's apphash will be checked.
However,the first block to replay may be wrong apphash.
In my opinion each block's apphash should be checked.

**Comment by james-ray** [comment]
The replayed blocks are already checked either in consensus process or in blockchain reactor pulling blocks process, either process has checked the block.  
Replay a block is merely to sync the app data with Tendermint.
Why the last block need to be executed through ApplyBlock is not because it need to be checked but we need to modify the state of Tendermint for it shutdown between save block and state, the state hasn't been saved in last shutdown.

**Comment by xla** [comment]
This issue is not actionable at this point, looking forward to contributions if you see fit to improve things.

**Comment by xla** [comment]
@james-ray Thanks for the clarification.

**Comment by melekes** [comment]
It would detect if the app changed in a way it shouldn't have.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3579 to develop.
