### ISSUE TITLE
Help: is that possible bad vote/proposal break consensus 

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3464]
if  someone (non-validators) sends vote/proposal, either invalid or duplicated or stale, to our node, would it impact our consensus?
I would like to have a test but it is hard to achieve.  Is there already any test about this?

**Comment by melekes** [comment]
> if someone (non-validators) sends vote/proposal, either invalid or duplicated or stale, to our node, would it impact our consensus?

It should not. I mean consensus should proceed as long as there's an honest majority (2f+1). 

We have some tests in https://github.com/tendermint/tendermint/blob/master/consensus/byzantine_test.go and https://github.com/tendermint/tendermint/blob/master/consensus/state_test.go
