### ISSUE TITLE
rpc: Tx interface should return tx's checkResult and DeliverResult

### ISSUE THREAD

**Issue by Zerppen** [tendermint/tendermint#3468]
As an user,I think endback service should return whether my tx executed successfully or not.
Yes,I can search stateDB for this result.
But I want to get the results right now,even my tx just under workflow of 'checkTx'.
Actually,I had done this feature  and It is working well since one year ago.
I am thinking about contribute it.

**Comment by srmo** [comment]
I don’t understand. There are already distinct broadcast_tx endpoints for that. 
Namely broadcast tx sync, to get the checkTx result, and broadcast tx commit, which blocks until tx is in a block or times out. 
PS: the latter is under redesign iirc

**Comment by Zerppen** [comment]
@srmo
For BroadcastTxAsync I want to know if my tx check successfully.
And I will store responseDeliverTx for tx.
You mean you don't want to see my implements?

**Comment by melekes** [comment]
> For BroadcastTxAsync I want to know if my tx check successfully.

use BroadcastTxSync https://tendermint.com/rpc/#broadcasttxsync.

if you want to get the `DeliverTx` result, poll `/tx?hash=` RPC endpoint https://tendermint.com/rpc/#tx or better subscribe for it using a WebSocket https://tendermint.com/docs/app-dev/subscribing-to-events-via-websocket.html. You can also use BroadcastTxCommit, which waits for both CheckTx and DeliverTx results https://tendermint.com/rpc/#broadcasttxcommit.

**Comment by Zerppen** [comment]
@melekes  See,I wanner improve 'user experience' of tendermint.
When users transfer their currency, they want to know each operation successfully or unsuccessfully as soon as possible via their tx hash.
So I don't think subscribe is a good way do this.
There will be some consequence my method  results in?

**Comment by srmo** [comment]
Again, you want to know if checkTx was successful or not, that’s what broadcastTxSync is for. Use that. Bo need for additional stuff. At least I don’t see where this is insufficient user experience. It even gives you the metadata the abci app returns upon a fail.

**Comment by Zerppen** [comment]
You know that I am free do this.
I do this 'cause I really hope it be better.
As a client of tendermint,I invoke rpc interfaces of tendermint.
Every time invoking I want to know if successful or not,it is not just about some special interfaces,it should be all.
That is a service really should do.
@srmo  @melekes

**Comment by ebuchman** [comment]
I'm a bit confused about the request here. We expose three different `broadcast_tx` endpoints specifically to satisfy the different guarantees users might want:

- `broadcast_tx_async` - for users that don't care about any response
- `broadcast_tx_sync` - for users that just want to know the response from CheckTx (it sounds like this is what you want)
- `broadcast_tx_commit` - for users that want to know the response from DeliverTx

Can you clarify why the above is not sufficient for you and what specific change you would like to see?

Thanks!

**Comment by melekes** [comment]
@ebuchman see the associated PR https://github.com/tendermint/tendermint/pull/3467/files#diff-638e837163a1b6a2dbb5f19513153895R328

**Comment by ebuchman** [comment]
What's the story here? Still not sure what the request is and #3467 is closed.

**Comment by melekes** [comment]
I am not sure either, but looks like @Zerppen has added an in-memory cache for results, so querying them takes less time now (in opposite to querying the goleveldb). @Zerppen am I right here?

**Comment by Zerppen** [comment]
Exactly.
 I have deployed my project for one year.
The story was given by my guest,because he wants to know result right now means before making block even checkTx failed.
@melekes

**Comment by melekes** [comment]
tx_search can take a long time (especially with large number of transactions) - https://github.com/tendermint/tendermint/issues/3076

putting cache in front of it seems like a short-term fix rather than a long term solution. Besides one can use Nginx (or similar products) to cache the results https://www.nginx.com/blog/nginx-caching-guide/

Here is what I think we should do:
1. optimize tx_search implementation ([1](https://github.com/tendermint/tendermint/issues/3076), [2](https://github.com/tendermint/tendermint/issues/2492))
2. use B+ tree instead of LSM tree and possibly indexes https://github.com/tendermint/tendermint/issues/1835 (this includes options like postgresql indexer https://github.com/tendermint/tendermint/issues/1161)
3. suggest caching results with Nginx or similar tools
