### ISSUE TITLE
rpc: paginate /validators response

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3472]
Similar to /tx_search, /validators response should also be paginated.

**Comment by ebuchman** [comment]
Should we also do this for everything that contains the validators? That would be dump_consensus_state, and genesis. Anything else?

Maybe we want to do this for every rpc endpoint somehow just in case it has a lot of data? Eg. net_info could also be in there. Large blocks? Etc.

**Comment by marbar3778** [comment]
Possibly a candidate for a design dev session, the rpc in general. If we agree that we can do this as a design dev session then we should hold off on further pagination changes. @melekes @ebuchman @thanethomson @tessr ?

**Comment by melekes** [comment]
> Should we also do this for everything that contains the validators? That would be dump_consensus_state, and genesis. Anything else?

I'd rather leave endpoints that aren't supposed to be called from outside (`/dump_consensus_state`). `/genesis` - sure

> Maybe we want to do this for every rpc endpoint somehow just in case it has a lot of data?

If it may be called externally, then I'd say yes.
