### ISSUE TITLE
abci: No way to get validator signatures in beginBlock

### ISSUE THREAD

**Issue by alari** [tendermint/tendermint#3480]
**Tendermint version**: 0.30.2

**ABCI app**: https://github.com/fluencelabs/fluence

In the `beginBlock` ABCI endpoint an ABCI application is able to get `LastCommitInfo`, including `VoteInfo` for the last votes. But this info lacks signatures for the previous block, as only the boolean flag is provided whether a particular validator signed the previous block or not:

https://github.com/tendermint/tendermint/blob/master/abci/types/types.proto#L302

So if the ABCI application wants to ensure that the requests are coming from the Tendermint and not from something else, it can not obtain and check the signatures of validators at the beginning of the new block, it just assumes that everything's ok.

The proposition is to provide add all the validators signatures with the `beginBlock` request.

**Comment by ebuchman** [comment]
> So if the ABCI application wants to ensure that the requests are coming from the Tendermint and not from something else, it can not obtain and check the signatures of validators at the beginning of the new block, it just assumes that everything's ok.

Probably the right way to achieve this is to use authentication on the ABCI connection. Wouldn't you agree?

**Comment by alari** [comment]
What we actually do is a bit more complicated: we want to build a block body from ABCI requests and then, on beginBlock request, check that signatures match the block body and export the list of validators along with the signatures.

So that finally we have a Tendermint block stored independently from Tendermint cluster, but with ability to check all the hashes.

**Comment by ebuchman** [comment]
Why do you need to do this? And will the Tendermint RPC endpoints suffice? We try to avoid packing too much data into the ABCI

**Comment by alari** [comment]
We want to be sure that all the Tendermint data is accessible from the outside of the cluster. It makes it possible to have very small Tendermint clusters and bear the risk that all cluster nodes go offline.

To be sure that data is stored, we want to have some kind of proof of storage _before_ committing the block, so that this proof could participate in `appHash`.

To do so, we need to get the last commit info and all the transactions of the block that is being processed now. All data is there except the signatures.

While block `n+1` is being processed, only block `n` is accessible from RPC endpoint (which sounds reasonable).

So no, Tendermint RPC endpoints are not enough.

**Comment by ebuchman** [comment]
> While block n+1 is being processed, only block n is accessible from RPC endpoint (which sounds reasonable).

This actually shouldn't be true, you should be able to query for the block as soon as it's committed on the Tendermint side, before even the app starts processing it. So you should be able to get those signatures from the rpc by querying the `/commit` endpoint

**Comment by alari** [comment]
Thanks, you're right! I have tried to query the `/commit` endpoint and got all the signatures for the block which is currently being processed.

So it's a kind of strange inversive control flow when ABCI calls Tendermint in reaction to ABCI call from Tendermint, but it works.

**Comment by melekes** [comment]
Seems like this is solved. It may look strange, but as Ethan has said: the reason for it is that we're trying to keep ABCI small.
