### ISSUE TITLE
docs: signature spec link is broken

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3482]
On https://tendermint.com/docs/spec/blockchain/blockchain.html#signature

>>>
See the [signature spec](https://tendermint.com/docs/docs/spec/blockchain/encoding.html#key-types) for more. => 404

**Comment by ebuchman** [comment]
Ugh the URL has `docs` in it twice. Just need to remove one and it works.

**Comment by brapse** [comment]
So There is a fix for this which is good. It might be interesting to add a test for links in the docs to make sure it doesn't happen in the future, Any thoughts here? @ebuchman?

Cf. https://github.com/tcort/markdown-link-check

**Comment by ebuchman** [comment]
Wow a link tester would be incredible

**Comment by Liamsi** [comment]
We could add a custom linter to gelangci-lint that simply checks every link in .md files which only Runs if the files have changed (on circles). Should not be too difficult (even for relative links). On the rendered homepage we could write a script that scrapes it and does the same (doesn’t sound like that necessary but we could still check).

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/3488. Opened https://github.com/tendermint/tendermint/issues/3505 for link tester. Thanks everyone 👍
