### ISSUE TITLE
abci: authenticate connection

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3483]
The ABCI connection is currently done over an unauthenticated TCP or Unix socket.

This means it's not currently possible to guarantee the integrity of data nor the authenticity of the sender. 

We should add some form of authenticated encryption here. The standard would be TLS, but we don't use HTTP here, just a raw TCP connection. Presumably it shouldn't be too hard to support TLS over raw TCP. 

Ref #3480

**Comment by marbar3778** [comment]
Instead of TLS, noise may be a better option here. If we are going to use noise elsewhere (still unknown) it would be good to use similar authentication elsewhere.

**Comment by JayT106** [comment]
any further discussion on this issue?

**Comment by marbar3778** [comment]
Before spending more time on the tcp/unix socket part of abci, it would be good to understand from the users who use tendermint in an out of process manner. There is an open discussion on either dropping grpc or tcp/unix sockets. (https://github.com/tendermint/tendermint/discussions/5855)
