### ISSUE TITLE
types: test block commits with votes for the wrong blockID

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3484]
Current code allows Commit to contain votes for the wrong blockID to facilitate tracking validator liveness.

We should add tests for this, both for the case of nil-votes and of votes for the wrong blockID. Both are allowed as valid votes in a Commit, so long as the Commit contains +2/3 votes for the right block ID.

Note this was discovered in #3298 which aimed to be the last step in implementing #1648 (ie. removing redundancy from commit votes). 

Ultimately, we maybe don't want to allow votes for the wrong blockID, but just for nil.

**Comment by jscode017** [comment]
@ebuchman , do you mean that a test that testing a commit that contain +2/3 right votes?

**Comment by ebuchman** [comment]
Yes, a commit that contains +2/3 of the right votes, but also some nil votes, and/or some votes for the wrong block id

**Comment by tessr** [comment]
Closed by #3936
