### ISSUE TITLE
consensus: Do we need to allow votes in the commit for the wrong block ID?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3485]
Current code allows Commit to contain precommits for the wrong blockID to facilitate tracking validator liveness.

Opened #3484 to actually test for this.

In working towards removing redundancy in commits (#1648), it was realized that we need to track which blockID a precommit was for if they're not all for the same blockID.  For the +2/3 that are for the right blockID, this is redundant information. But for the others, it's not.

This raises the question of if we really even need to include these precommits in a commit in the first place.

I think we certainly don't need to include those that are for a different blockID. So maybe the question is more so if we need to include precommits for nil. Even in this case, I think not, especially since to do signature aggregation we need all the msgs to be the same, unless we want to aggregate two sets of votes independently - those for the blockID and those for nil. Not sure this is worth it.

@zmanian @jaekwon @milosevic @cwgoes @sunnya97 thoughts? Can we just require Commit only contains precommits for a single blockID?

**Comment by ebuchman** [comment]
See https://github.com/tendermint/tendermint/pull/3298#issuecomment-476887355 for how we'll need to change the `Commit` struct if we do need to accept these nil votes.

**Comment by sunnya97** [comment]
I agree that we shouldn't be including precommits for different blockIDs.

Regarding whether or not to include nil votes or not, imo really depends on how it affects liveness of validators.  I imagine it wouldn't have a massive effect.

How difficult would it be to get some data on the commits from the Cosmos Hub blockchain, looking at how it would affect the liveness percentages if we only count the "correct" precommits with the right blockID and not nil.  Even something as simple as what percentage of precommits in the valid commit chain are "correct".

**Comment by zmanian** [comment]
I can't think of a reason to include commits for the wrong block id.

**Comment by milosevic** [comment]
Commit is by definition the set of +2/3 Precommit votes for the particular block. Therefore, conceptually nothing else should be there (neither votes for wrong block nor nil votes). However, it seems that we were using this also for tracking validator responsiveness (calling it validator liveness is a bit misleading). So the question is what is the right way to support this feature outside Commit data structure.

**Comment by cwgoes** [comment]
Conceptually I agree with @milosevic.

I don't quite follow why we would need this to track liveness - we know the validator set SDK-side (including the Tendermint update delay, it's tracked, and if any part isn't it can be easily) - if we have a list of validators which *signed* the correct block ID, all validators in the validator set but not in the list of signers can be treated as having missed the block.

Right now we use `voteInfo.SignedLastBlock` to determine liveness, and iterate over all the votes (which includes both validators who signed and validators who didn't), but it wouldn't be hard to change.

@sunnya97 Can you clarify - do you think this would change anything from our current logic?

**Comment by ebuchman** [comment]
I think the intention was to allow count validators who precommit nil in a round where a block is committed as having voted, for the sake of uptime considerations - ie. they'd be included in `voteInfo.SignedLastBlock` even though they signed nil.

I'm wondering if we should preserve this behaviour or otherwise care to track validators that signed nil. I'm leaning towards no, and only tracking validators that signed the actual commit. Not sure how important it is to count validators that sign nil.

**Comment by cwgoes** [comment]
Ah, I see. Does `voteInfo.SignedLastBlock` count nil-votes at the moment?

Incentive-wise I think we do want to punish validators for signing nil-votes, though - otherwise they could vote nil always for proposers they don't like with no repercussions.

**Comment by milosevic** [comment]
I am wondering if there is a (relatively) simple way to provide information about all precommits to the application (outside Commit) if this is useful (for example for tracking validator responsiveness).

**Comment by jaekwon** [comment]
Since nobody should be precommitting anything but nil or the one blockID, I think allowing for nil should be OK in terms of compressing the commit, since there are only 2 choices.

There should be a "short circuit" that syncs all peers to a commit as soon as a commit is found for a height, but without the same for +2/3 prevotes, I'm more concerned about timing/selective-disclosure attacks to try to exclude certain validators.  We're creating an incentive to not precommit nil in some situations, which seems like it would complicate analysis.

**Comment by ebuchman** [comment]
> Ah, I see. Does voteInfo.SignedLastBlock count nil-votes at the moment?

Yes.

Seems Jae and Chris have conflicting concerns re nil votes though:

> I think we do want to punish validators for signing nil-votes, though - otherwise they could vote nil always for proposers they don't like with no repercussions. 

So the concern here is that a validator will configure to always precommit nil for a particular proposer. Makes sense.

> By not allowing nil precommits in the Commit, we're creating an incentive to not precommit nil in some situations, which seems like it would complicate analysis.

Is the concern here that validators would precommit the blockID even if they didn't see a +2/3 polka for it because they're worried if they vote nil they won't get included? Wouldn't that put them at risk of being slashed in the event of a fork?

>  I'm more concerned about timing/selective-disclosure attacks to try to exclude certain validators

Not sure I understand this ...

**Comment by ebuchman** [comment]
Sounds like the best thing to do for now is probably to keep separate track of the nil votes. 

Presumably the simplest way to do this is to include a slice of integers which contains the indices of the validators in the validator set that voted nil. 

I'm not sure what we will do about this though come BLS.

**Comment by ebuchman** [comment]
> Commit is by definition the set of +2/3 Precommit votes for the particular block. Therefore, conceptually nothing else should be there (neither votes for wrong block nor nil votes). However, it seems that we were using this also for tracking validator responsiveness (calling it validator liveness is a bit misleading). So the question is what is the right way to support this feature outside Commit data structure.

Changing this name would be big and breaking, so not something to take lightly, though I agree it would be nice if Commit was just +2/3 signatures for the block ID and the votes for nil were elsewhere.

I've updated the ADR in #3298 - basically add a BlockIDFlag to CommitSig to indicate if the vote is for the BlockID, for Nil, or if it's Absent.

**Comment by ebuchman** [comment]
Closing this. Updates are in the ADR and we can follow up further from the #1648 tracking issue
