### ISSUE TITLE
Replay console is broken: fix, add docs, tests, blog post

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#349]
There is functionality in `consensus/replay_file.go` for stepping through a consensus log one message at a time in a console to get a feel for what happened. You can also just playback the whole log. 

The console is really good for understanding how the consensus implementation actually works. But the code is all untested (it uses slightly different code paths than the main routines for playback). The functionality is exposed in the command line, but currently disabled. We should write tests, documentation, and a blog post about it (blog post can show how to use replay console to step through a consensus log, would probably be very illuminating). But first we need the tests.

**Comment by adrianbrink** [comment]
@ebuchman Is this still open and what does it mean?

**Comment by ebuchman** [comment]
Updated opening.

**Comment by cmwaters** [comment]
@ebuchman what's the status on this? Is it still worth pursuing something like this or should we close this issue?

**Comment by creachadair** [comment]
> @ebuchman what's the status on this? Is it still worth pursuing something like this or should we close this issue?

I think that if we decide not to pursue it, we should probably remove the code (as a resolution for this issue before closing it).
