### ISSUE TITLE
Add markdown link tester

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3505]
See https://github.com/tendermint/tendermint/issues/3482#issuecomment-477253073

**Comment by zmanian** [comment]
This is Github Action for this.
https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by marbar3778** [comment]
added one to the [sdk](https://github.com/cosmos/cosmos-sdk/blob/master/.github/workflows/linkchecker.yml), on tendermint side we are blocked on adding any github actions because of the github plan we have

**Comment by zmanian** [comment]
Yep will try and get this unblocked.

**Comment by marbar3778** [comment]
was added in #4513
