### ISSUE TITLE
sync: Prometheus metrics should update during fast_sync

### ISSUE THREAD

**Issue by joe-bowman** [tendermint/tendermint#3507]
Currently when a node is in fast_sync mode (i.e. recovering from a position behind the head of the chain) the `.result.sync_info data` on the /status RPC endpoint is kept up to date with the sync, but the prometheus metrics, specifically `tendermint_consensus_height` does not reflect the sync height. 

This would be very useful to track the state of recovering nodes.

**Comment by ebuchman** [comment]
I wonder if this should be the same metric tho. `tendermint_consensus_height` is located in the Consensus package and probably shouldn't be mutated by anything else. So we might need `tendermint_sync_height` specifically for the blockchain reactor syncing or else to have some more global height metric that we're ok to mutate from both `blockchain` and `consensus` packages.

**Comment by xla** [comment]
Referrencing #3506 for tracking purposes.
