### ISSUE TITLE
Please change GitHub config to protect vX.X branches

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#3510]
The new release management process was merged to `develop`. To enforce permissions on the release management process, all release branches need to be protected. Please create a rule in the GitHub config to protect the `v[0-9]+\.[0-9]+` branches.

* Should only merge after review, cancel stale reviews
* Possibly enable GPG signing as a requirement for commits?

Any other privileges that are set for develop or master today.

**Comment by ebuchman** [comment]
Here's the pattern matching they use: https://ruby-doc.org/core-2.5.1/File.html#method-c-fnmatch

I just used `v0.[0-9]*` for now, not sure if I can do better.
