### ISSUE TITLE
p2p: NewNetAddressStringWithOptionalID - ID is not optional

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3521]
The function `NewNetAddressStringWithOptionalID` is from a time when peer IDs were optional. They're not anymore. So this should be renamed to `NewNetAddressString` and should ensure the ID is provided.

**Comment by bradyjoestar** [comment]
NewNetAddressString existed 
https://github.com/tendermint/tendermint/blob/75ffa2bf1c7d5805460d941a75112e6a0a38c039/p2p/netaddress.go#L69-L75

NewNetAddressStringWithOptionalId is called by
https://github.com/tendermint/tendermint/blob/75ffa2bf1c7d5805460d941a75112e6a0a38c039/node/node.go#L571-L577
but it is used to verify host and shouldn't be replaced to NewNetAddressString.

It seems it have be done. 

Should we split verify host logic from `NewNetAddressStringWithOptionalId` and create a new function named `VerifyHost` and used it in `node.go`?

If necessary, I could support some help.
