### ISSUE TITLE
p2p: Session should terminate on nonce wrapping

### ISSUE THREAD

**Issue by zebambam** [tendermint/tendermint#3531]
Hi!

The nonce that peers use to communicate in secret sessions is 64 bit (rather than 96 bit) and looks like it might wrap?

``` go
func incrNonce(nonce *[aeadNonceSize]byte) {
	counter := binary.LittleEndian.Uint64(nonce[4:])
	counter++
	binary.LittleEndian.PutUint64(nonce[4:], counter)
}
```

Seems like the session should terminate before re-using a nonce.

Doesn't look like there's a terribly practical attack available but may as well belt-and-braces since it's crypto that's important.

Thanks

**Comment by Liamsi** [comment]
Thanks for reporting this. Yes, you are right it will wrap (after the 4 bytes are full). We are moving away from our implementation of the station to station protocol (secret connection). Hence, I'm not sure it is worth the effort. 
FWIW, the easiest would be to panic before we overflow (that is what we did in the Rust implementation: https://github.com/tendermint/kms/blob/752184b5bfa139cde4c9013d836e0f3cda897110/tendermint-rs/src/secret_connection/nonce.rs#L68). This would end the session and makes sure the nonce would not be re-used.

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3609 to develop.

**Comment by zebambam** [comment]
Good stuff, thanks!
