### ISSUE TITLE
p2p: Too many unsuccessful attempts

### ISSUE THREAD

**Issue by danil-lashin** [tendermint/tendermint#3532]
**Tendermint version**: 0.31.3 

**What happened**: p2p module of Tendermint trying to connect to peers from addrbook too many times.

For example, I found this record in addrbook.json in one of my nodes: 
```
{
	"addr": {
		"id": "7f880203aacfc405d926ea9a76163a9f284e8a5e",
		"ip": "37.153.1.214",
		"port": 26656
	},
	"src": {
		"id": "8c866c4cd346f55b38cafd007862b6279d2e8000",
		"ip": "136.243.33.21",
		"port": 48236
	},
	"attempts": 497,
	"last_attempt": "2019-04-08T14:51:24.699155733+03:00",
	"last_success": "0001-01-01T00:00:00Z",
	"bucket_type": 1,
	"buckets": [
		210,
		166,
		238,
		51
	]
}
```

**497 attempts** and no success one (`"last_success": "0001-01-01T00:00:00Z"`). It happens alot especially on start of new test network. Some nodes not wipe addrbook and some wipe node_key file.

**What you expected to happen**: Tendermint should remove peer from addrbook when max dial attempts ([16](https://github.com/tendermint/tendermint/blob/75ffa2bf1c7d5805460d941a75112e6a0a38c039/p2p/pex/pex_reactor.go#L49)) reached.

**Have you tried the latest version**: yes

**Comment by danil-lashin** [comment]
Additional note: this peer is not persistent and not a seed.

**Comment by xla** [comment]
Ref. #2067

**Comment by melekes** [comment]
> Additional note: this peer is not persistent and not a seed.

you mean 7f880203aacfc405d926ea9a76163a9f284e8a5e or the node with this record in addrbook.json?

**Comment by danil-lashin** [comment]
> you mean 7f880203aacfc405d926ea9a76163a9f284e8a5e or the node with this record in addrbook.json?

7f880203aacfc405d926ea9a76163a9f284e8a5e is not a persistent node in config of node with given addrbook.json

**Comment by melekes** [comment]
What about the node with the given addrbook.json? Is it a seed?

**Comment by danil-lashin** [comment]
Yes, it is.

**Comment by melekes** [comment]
That's what I thought. Thanks for a quick response 🙇

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3573 to develop.
