### ISSUE TITLE
rpc: Tx results are stored in duplicate

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3533]
Tx results are persisted as part of ABCIResponses in the state, but they are also persisted by the TxIndexer.

This means the same data is being stored twice, which could potentially add up.

An initial PR to address this is https://github.com/tendermint/tendermint/pull/2499, which basically only persists the latest ABCIResponse. 

The problem with this is it means the tx result will only be available if indexing is enabled. 

This means that without indexing enabled, you won't be able to lookup the result of a tx, which might be especially problematic as we encourage people to move away from broadcast_tx_commit.

Perhaps a solution for this is to automatically index all txs that came through the rpc endpoint? 

Needs more discussion. But also not the highest priority item since it's just disk space, this doesn't cause more bytes to go over the p2p network.

**Comment by kostko** [comment]
As noted in https://github.com/tendermint/tendermint/issues/5327#issuecomment-686703030 I would rather see that any pruning of ABCI responses would be optional as having access to historic ABCI responses without the need for indexing is a good thing.

**Comment by marbar3778** [comment]
Moving forward we will not be removing abciResults duplication. With the support of psql, we recommend users to index with postgres, and we will use the saving of txResults in order to enable reindexing. 

Closing this issue for now, please reopen if its applicable.
