### ISSUE TITLE
mempool: propagate max gas errors back to the rpc

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3546]
If a tx exceeds the block max gas, the tx will fail to be included in the mempool, but this error is not propagated back to the rpc client since it's just internal to the mempool and not reflected in the ABCI code.

See https://github.com/tendermint/tendermint/blob/v0.31.3/mempool/mempool.go#L514  - even if the ABCI code is 0, if the postCheck fails (ie. max gas exceeded), the tx isn't included in the mempool.

The only thing that gets back to the RPC client here is the ABCI response, which in this case shows no error.

We should find some way to propagate the postCheck error back up to the rpc client. Otherwise, it can be very difficult to understand why a tx is not getting included in the mempool even though it passes the ABCI!

**Comment by melekes** [comment]
we should propagate not only postCheck error, but other errors as well. see https://github.com/tendermint/tendermint/issues/5675

**Comment by melekes** [comment]
The only solution seems to be using `CheckTxSync` instead of `CheckTxAsync`, but I'm not 100% sure that we want to do this.

**Comment by alexanderbez** [comment]
We (will?) have block_gas_used in the CheckTx response. Can't we use that to determine the error?

**Comment by melekes** [comment]
> We (will?) have block_gas_used in the CheckTx response. Can't we use that to determine the error?

we can!

but what about other errors like the one where mempool is full?

**Comment by alexanderbez** [comment]
I think we need to inject the error from `postCheck` into the RPC ABCI response object somehow...maybe just append the error or wrap the existing `log`.

**Comment by jinsankim** [comment]
I think we could use `ResponseException` to propagate the error. HDYT?

**Comment by melekes** [comment]
> `postCheck`

agree. we can probably mutate `res` object in two places [1](https://github.com/tendermint/tendermint/blob/09cf0bcb012d37de33b41425d82a77bbb31ed1b5/mempool/clist_mempool.go#L421), [2](https://github.com/tendermint/tendermint/blob/09cf0bcb012d37de33b41425d82a77bbb31ed1b5/mempool/clist_mempool.go#L428)

**Comment by alexanderbez** [comment]
So we can modify `ResponseCheckTx.Log` by appending a string. What format should the string be in?

**Comment by alexanderbez** [comment]
I don't think there is a clean solution here apart from modifying `ResponseCheckTx.Log`.

cc @tessr

**Comment by alexanderbez** [comment]
Consensus was to add a new field in `ResponseCheckTx` to indicate any Tendermint internal failures.

/cc @williambanfield

**Comment by williambanfield** [comment]
👋 I'm trying to understand how modifying the `ResponseCheckTx` message will ultimately deliver news of the failure to the application. This message is delivered to the node from the application if not mistaken. How will the new error message eventually been seen by the app? @alexanderbez would you be able to give me some explanation on that?

**Comment by alexanderbez** [comment]
Correct, the application response to CheckTx with a `ResponseCheckTx`. I can see how this is confusing. When a client broadcasts a tx, in this case the mode would have to be `sync` or `commit` (not advised), Tendermint will call, in the case of `sync`, the following code: https://github.com/tendermint/tendermint/blob/master/rpc/core/mempool.go#L35. Note, it calls `CheckTx` on the mempool and waits for a response -- `*abci.Response`. On this response object, we call `res.GetCheckTx()`.

We're looking to do the following:

1. Modify `CheckTx` in the mempool to add and populate a new field (name TBD) that would add context on any failures TM-side by modifying the `checkTxRes` object.
2. Update the RPC mempool methods -- `BroadcastTxSync` and `BroadcastTxCommit` to fetch this new field (name TBD) and set a (new) field on the `ResultBroadcastTx` result.

Does this make sense?

**Comment by williambanfield** [comment]
Ahh, thanks for the info. I think I'm understanding but to clarify: This response is eventually communicated up to the _client_. So, a client sends a Tx to a TM node. The node does its Tx checks and then makes a request into the ABCI app and gets a response. TM then does additional checks using data contained in the ABCI response. The response from the ABCI app is then returned to the _client_, regardless of the success of the post-checks. I think the confusion was that this is information being communicated to the _client_ not to the ABCI application. Is that correct?

**Comment by alexanderbez** [comment]
> Ahh, thanks for the info. I think I'm understanding but to clarify: This response is eventually communicated up to the client. So, a client sends a Tx to a TM node. The node does its Tx checks and then makes a request into the ABCI app and gets a response. 

Correct!

> TM then does additional checks using data contained in the ABCI response. The response from the ABCI app is then returned to the client, regardless of the success of the post-checks.

Correct again.

>  I think the confusion was that this is information being communicated to the client not to the ABCI application. Is that correct?

Yes, the information here is being communicated back to the client, i.e. user, that broadcasted the tx, not the application.
