### ISSUE TITLE
state: Save valSet every 1000 blocks to support rollback

### ISSUE THREAD

**Issue by bradyjoestar** [tendermint/tendermint#3555]
currently we save valset every 100000 blocks to fast the replay.
Maybe we need to save valset every 1000 blocks to support rollback?

**Comment by melekes** [comment]
> Maybe we need to save valset every 1000 blocks to support rollback?

Have you done any benchmarks? I.e. how much do we gain by saving val set every 1000 blocks. Does it worth giving an additional disk space and IO?

**Comment by bradyjoestar** [comment]
ValidatorSet is smaller than block data generally. 
And if block speed is 0.25s/1 block, this means we save it every 250s.

I will test it and post the result. :ok_hand:

**Comment by bradyjoestar** [comment]
I used a 2core-8G machine in Aws, and here is the result.
## time
```
2019-04-17 08:08:54.403186514 +0000 UTC m=+11.320796396
2019-04-17 08:08:54.403223182 +0000 UTC m=+11.320833038
```
If we save ValidatorSet, It will cost 63332ns to call 
```
db.Set(calcValidatorsKey(height), valInfo.Bytes())
```

If not, it will cost 47039ns.
```
2019-04-17 08:08:55.420355217 +0000 UTC m=+12.337965158
2019-04-17 08:08:55.42038178 +0000 UTC m=+12.337991731
```

## performance
If  we save validatorSet ***every block***, here is the result of tm-bench
```
./tm-bench -T 30 -r 1000 localhost:26657
Stats          Avg       StdDev     Max      Total     
Txs/sec        967       287        1509     29000     
Blocks/sec     0.933     0.249      1        28
```
If we not, here is two result of tm-bench
```
Stats          Avg       StdDev     Max      Total     
Txs/sec        983       288        1431     29500     
Blocks/sec     0.933     0.249      1        28

Stats          Avg       StdDev     Max      Total     
Txs/sec        801       486        1451     24024     
Blocks/sec     0.767     0.423      1        23 
```
The performance is influenced by os. 

I think it worth decreasing `valSetCheckpointInterval` to 1000.The cost is far less than 1/1000.

**Comment by melekes** [comment]
> Save valSet every 1000 blocks to support rollback 

100000 is too big to support rollback? why?

**Comment by bradyjoestar** [comment]
Here is a fictitious situation:
- we have 131647 blocks now,every block contains 100 tx , and tm is running in a pre-production env.
- at a time app meet a attack tx  like `The DAO` in the 131648。
- we want to erase this tx by rollback  all node. Also we rollback the state of APP.
- compare 1000, thus we will lose 31647 x 100 txs.

Thanks to tendermint! we forked it and our public chain is designed to save valset every block , and have finished it.

It you think there is no need to change it to 1000, I will close the pr. #3554

**Comment by melekes** [comment]
Sorry, I still don't understand. How's not storing validator set prevents us from rolling back to 131647 and loading validator set from height = 100000. Yes, it will take more time to recalculate priorities.

**Comment by bradyjoestar** [comment]
@melekes 
You are right, we saved all the blocks from 0 to 131647, and we could recalculate priorities from it with validators loaded from height=100000.

Thank you!:beer:

#3554 is closed.:ok_hand:
