### ISSUE TITLE
tools: Problem with tendermint node startup

### ISSUE THREAD

**Issue by kedarrane** [tendermint/tendermint#3562]
sudo apt install -y unzip
wget https://github.com/tendermint/tendermint/releases/download/v0.22.8/tendermint_0.22.8_linux_amd64.zip
unzip tendermint_0.22.8_linux_amd64.zip
rm tendermint_0.22.8_linux_amd64.zip
sudo mv tendermint /usr/local/bin

i have install above version of tendermint 

getting an error on command tendermint node ::::
I[04-15|09:35:23.153] Starting multiAppConn                        module=proxy impl=multiAppConn
I[04-15|09:35:23.153] Starting socketClient                        module=abci-client connection=query impl=socketClient
E[04-15|09:35:23.153] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:26.154] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:29.154] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:32.155] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:35.156] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:38.156] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:41.157] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:44.158] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query
E[04-15|09:35:47.158] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query

**Comment by xla** [comment]
@kedarrane Thanks for reporting your issue, Tendermint needs two things to work properly, the node itself and an ABCI app that it talks to, plese follow the docs: https://tendermint.com/docs/introduction/quick-start.html#overview to see how to set it up alltogether. Let us know if you run into any other issue along the way.
