### ISSUE TITLE
ci: Pin the golang version

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3564]
Currently the CI just uses `circleci/golang` for the docker container.

This means we just pull the latest version of this image, so our golang version will upgrade whenever circle updates this image.

There was some concern over this as it means there are variables that can change in our build process with out our awareness, which may cause extra debugging headaches. So we probably want to pin the go version used.

**Comment by Liamsi** [comment]
Do we want to pin the exact version (currently `1.12.3`)? Or do we want to let's say pin to `1.12` and update to all the patch versions automatically (when they are made available). I'm more for the latter as their shouldn't be any big changes besides bug fixes. Thoughts? cc @xla

**Comment by xla** [comment]
Later sounds good to me @Liamsi !

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3578#issuecomment-484668755
