### ISSUE TITLE
p2p/addrbook: add blacklist

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3572]
We need to add a blacklist to the addrbook, where we'll store peers whom we've failed to connect to. This is to avoid constantly redialing them. Note in pex reactor we're using attemptsToDial in-memory structure to avoid dialing such peers right now. But since it's in-memory, if you restart your node and receive dead peer's addr, Tendermint will try to dial it another 16 times (35h).

**Comment by xla** [comment]
Ref. #2067

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/4548

**Comment by melekes** [comment]
Duplicate of https://github.com/tendermint/tendermint/issues/1614
