### ISSUE TITLE
test: TestListenerTimeoutReadWrite non-deterministic test failure

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#3576]
https://github.com/tendermint/tendermint/pull/3575#issuecomment-484149537
```
=== RUN   TestListenerTimeoutReadWrite
--- FAIL: TestListenerTimeoutReadWrite (0.01s)
    socket_listeners_test.go:110: read tcp 127.0.0.1:38914->127.0.0.1:60772: i/o timeout
```

**Comment by Liamsi** [comment]
The cause probably is that the timeout isn't sufficient in rare cases:
https://github.com/tendermint/tendermint/blob/f2aa1bf50e3eb61f9cf27ee4e867fbd1daf9069f/privval/socket_listeners_test.go#L99-L113

**Comment by Liamsi** [comment]
The reason here is, that in rare cases, the `Accept` times out faster than the dial happens. This is weird as the accept timeout is set to one full second (and the test only runs for 0.01s ...). 
https://github.com/tendermint/tendermint/blob/f2aa1bf50e3eb61f9cf27ee4e867fbd1daf9069f/privval/socket_listeners_test.go#L99-L110
Looking at the internals of the `Accept` it seems that during the accept we run into the timeoutReadWrite (which is only 1 ms):
https://github.com/tendermint/tendermint/blob/f2aa1bf50e3eb61f9cf27ee4e867fbd1daf9069f/privval/socket_listeners.go#L67-L80

**Comment by melekes** [comment]
Hopefully fixed by https://github.com/tendermint/tendermint/pull/3580.
