### ISSUE TITLE
Delete master branch and rename develop to master

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#3581]
Due to the decision that we want to maintain past releases with back-port we want to get rid of the develop/master dichotomy. This is to reduce some of the overhead necessary when the latest release is cut: merge release on release branch (e.g. `v0.31`) -> merge from release brach to develop -> merge to master -> merge back to develop (which causes a lot of noise with no real changes).

We only need *one* branch where current development is happening. In the future this one should be named `master` (this simply is the default name for default branches in GH ;-). 
To not miss any changes that happened on `develop` (but didn't propagate to `master` yet) we want to 1) delete the master branch and 2) rename `develop` to `master`.

We plan to do this change with the next breaking release (`v0.32`).

**Note**: this might impact users that simply use `go get` to get the latest release from master! We might need to note this in the readme, too.

**Comment by Liamsi** [comment]
@greg-szabo suggested to merge `develop` to `master` and delete `develop` instead. Sounds easier and has the same result.

**Comment by jackzampolin** [comment]
Learn from our mistakes!

**Comment by ebuchman** [comment]
Doesn't deleting develop cause all PRs to close?

**Comment by Liamsi** [comment]
Hmm, good point. I'll investigate if that is true. Renaming to master might make more sense then. On the other hand we could change the base branch of all open PRs (manually or via a script).

**Comment by melekes** [comment]
> Doesn't deleting develop cause all PRs to close?

Yes (https://github.community/t5/How-to-use-Git-and-GitHub/If-a-base-branch-is-deleted-does-it-close-all-active-PRs-on-that/td-p/21358)

**Comment by Liamsi** [comment]
I think @ebuchman brought that up in one of the calls. We can still merge develop to master and retarget all open PRs to master (and then delete develop instead). 
Or would this have any other downside I'm not seeing?

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/pull/3726
