### ISSUE TITLE
test: TestStartNextHeightCorrectly non-deterministi failure

### ISSUE THREAD

**Issue by liamsi** [tendermint/tendermint#3588]
https://github.com/tendermint/tendermint/pull/3524#issuecomment-485779378
https://github.com/tendermint/tendermint/pull/3310#issuecomment-464301327

**Comment by jleni** [comment]
I hit that error too here: https://circleci.com/gh/tendermint/tendermint/56796#tests/containers/3

**Comment by tessr** [comment]
We've done a bunch of work to clean up flaky and non-deterministic tests this year, so I'm going to close this issue for now. But if it recurs, I will definitely re-open!
