### ISSUE TITLE
mempool: separate mempool and it's reactor

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3589]
This is a follow-up from https://github.com/tendermint/tendermint/pull/3524

`mempool.Reactor` should be able to use other mempool implementations, not only one based on `CList`.

See https://github.com/tendermint/tendermint/pull/3524#discussion_r272143138

**Comment by marbar3778** [comment]
I am starting to be opposed to this idea. I am leaning towards coupling the reactor to its data structure. 

If a team would like to implement a different mempool design than they can write their own reactor and data structure, place a switch in the node package to decide which to use.

**Comment by marbar3778** [comment]
closing, reopen if still applicable. 

mempool v1 has its own reactor, not using the same one as v0. Coupling reactor to mempool makes sense.
