### ISSUE TITLE
mempool: remove CheckTx and force people to use CheckTxWithInfo

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3590]
This is a follow-up from https://github.com/tendermint/tendermint/pull/3524
See https://github.com/tendermint/tendermint/pull/3524#discussion_r277659000

Pros:
- smaller `Mempool` interface
- single way to add transaction

**Comment by erikgrinaker** [comment]
If we're breaking the API anyway, why not just make `CheckTx()` take `TxInfo`? Calling the single method `CheckTxWithInfo` seems a bit unnecessary to me.

**Comment by melekes** [comment]
Good idea
