### ISSUE TITLE
Memory leak in consensus

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#363]
Monitoring the memory usage while running the consensus tests suggests there might be a leak somewhere as we quickly balloon above a few GB of RAM.

This recently caused unexpected failures on Circle as the used memory climbed above 4 GB (the max there). Adding `stopConsensusNet` function to shutdown reactors seemed to roughly halve the memory usage, but it seems like we should be able to do better.

**Comment by silasdavis** [comment]
I've had a user report reaching close to 6 GB of RAM after running Burrow for ~3 days. I haven't replicated or profiled this yet, but I thought I'd ask if this was something you were still seeing your end?

**Comment by ebuchman** [comment]
Do you have an idea of what kind of transaction load they were running under?

**Comment by adrianbrink** [comment]
@ebuchman Is this still an issue that we are actively trying to solve?

**Comment by melekes** [comment]
This should probably be solved with https://github.com/tendermint/tendermint/pull/1173. There are still some small things leaking https://github.com/tendermint/tmlibs/issues/144. Let's close this and open a new issue if we see major leak again at some point (Tendermint >= 0.16).
