### ISSUE TITLE
Set Datadir

### ISSUE THREAD

**Issue by gaia** [tendermint/tendermint#3630]
I set `db_dir = /my/other/dir` in config.toml, now I have 
```
$ ll /my/other/dir
blockstore.db/
evidence.db/
state.db/
tx_index.db/
```

But `application.db` stays in `.gaiad/data`. How to configure so it goes to `/my/other/dir`?

**Comment by melekes** [comment]
I believe this is a gaia specific issue. Tendermint does not have application.db folder.

**Comment by melekes** [comment]
Moved issue to cosmos-sdk repo https://github.com/cosmos/cosmos-sdk/issues/4289
