### ISSUE TITLE
Allow the `tendermint testnet` command to take a configuration template

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#3651]
At present, the `tendermint testnet` command allows one to override a handful of default configuration options. It's become apparent in recent conversations around more general testing needs that we need to be able to override more configuration options.

Instead of adding ever-more parameters on the command line, can we can add support for a configuration file template (using standard Go template syntax) for easily generating greater varieties of test network configurations?

**Comment by ebuchman** [comment]
I think that was recently merged to develop: https://github.com/tendermint/tendermint/pull/3559 - yeh ?

**Comment by thanethomson** [comment]
Ah awesome! Didn't see that until now 😁
