### ISSUE TITLE
PeerBehaviour: follow up and integration

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3653]
ADR-039 outlined a new interface to better capture peer behaviour. Initial implementation is in #3552. The implementation is just the basic data types and does not hook up the interface to the rest of the code.

There is some follow up necessary re the extensive discussion in #3552, particularly around:
- naming
- where the errors should live (ie. consensus-domain-specific errors shouldn't be in P2P package)

Finally, we need to integrate the new interface with the rest of the code.

**Comment by tessr** [comment]
Is this really in the p2p layer, or is it part of the blockchain v2 work?

**Comment by marbar3778** [comment]
With the new p2p stack peer stopping is unified to a single location. We have opted to not use the behavior pkg for new reactors and instead rely on the p2p v2.
