### ISSUE TITLE
Update PR template to require reference to an issue

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3654]
Many PRs get opened without a relevant issue. While sometimes there is a detailed explanation of the change in the PR itself, it is often lacking, and in any case the correct location for such details is an issue opened before the PR is created.

PRs opened without reference to a relevant issue should be immediately closed.

Exceptions may be made for extremely small PRs that are self evident (ie. only a couple lines, like typo fixes).

I will make a PR for this now :)

**Comment by Liamsi** [comment]
> Exceptions may be made for extremely small PRs that are self evident (ie. only a couple lines, like typo fixes).

Just throwing this in: The parity folks have a tag for anything that does not alter *any* logic [insubstantial](https://github.com/paritytech/substrate/pulls?q=is%3Apr+label%3AA2-insubstantial+is%3Aclosed): https://github.com/paritytech/substrate/blob/master/CONTRIBUTING.adoc#merge-process

**Comment by ebuchman** [comment]
We likely need to overhaul our entire label/tag system. Parity's is exemplary.

**Comment by melekes** [comment]
Believe this is done in https://github.com/tendermint/tendermint/pull/3655
