### ISSUE TITLE
broadcast_tx_sync: Response error: RPC error -32603 - Internal error: EOF

### ISSUE THREAD

**Issue by sunriseLe** [tendermint/tendermint#3658]
I am  creating my own blockchain using tendeimint as a consensus.When I use` BroadcastTxSync` like this:
```go
_, err := c.tc.BroadcastTxSync(tx)
```
sometimes, I will receive an error but I don't know why
```go
broadcast_tx_sync: Response error: RPC error -32603 - Internal error: EOF
```
Anyone have got this error ? need for help!

**Comment by sunriseLe** [comment]
hello，can  you  help  me？ @ebuchman

**Comment by ebuchman** [comment]
Can you please provide more info? For instance the logs from Tendermint during this time. Also which client are you using, HTTP or JSONRPC or websockets?

**Comment by melekes** [comment]
@sunriseLe ^^^

**Comment by melekes** [comment]
Closing due to no response.
