### ISSUE TITLE
Tags supported for header subscriptions but not searches

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#3665]
#915 added tags to BeginBlock/EndBlock, and they are passed into the pubsub system [just like with transactions](https://github.com/tendermint/tendermint/blob/d2eab536ac1071b1b5f64283572397606326eb73/types/event_bus.go#L125-L140)

However, with transactions, we can both *subscribe* and *search* for them. The first is great for responsive apps. The second great to get a history. With a symetrical design, we would also be able to search for blocks/headers not only by height (as now), but also tags. There recently has been some work on the tagging system #3643, so I figured this would be a good time to propose finishing the work on tagging blocks.

But what is the real use case? Simple - in order to support light-client proofs (and headers for ibc), it is very useful to get a list of all blocks where the validator set changed. That is where `header.NextValidatorHash != header.ValidatorHash`. I started the design to emit a tag on EndBlock whenever the App updates the validator set, which then can be subscribed to in order to find the changes. So far, this works well. However, if a client is offline and wants to catch-up, there is no clear way to locate such blocks - either built-in or making use of the tagging system.

**Comment by ethanfrey** [comment]
@melekes Maybe you thought about this when building the tx indexer?

**Comment by melekes** [comment]
> However, if a client is offline and wants to catch-up, there is no clear way to locate such blocks

true

> Maybe you thought about this when building the tx indexer?

nope

**Comment by ethanfrey** [comment]
@jackzampolin maybe this also goes into the rpc issue... with the other pubsub stuff

**Comment by jackzampolin** [comment]
Related to https://github.com/tendermint/tendermint/issues/3367

**Comment by alexanderbez** [comment]
This is big feature ask of many clients. Having worked on the events refactor recently, I _think_ we can piggyback off of the tx-indexing system. Mind if I tackle this @melekes ?

**Comment by melekes** [comment]
No, go ahead 😄
