### ISSUE TITLE
crypto: return more info in the AddSignatureFromPubKey error

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3672]
I incorrectly assumed there was a regression in the SDK when I couldn't do a multisig tx (https://github.com/cosmos/cosmos-sdk/issues/4391). Turned out I was using the wrong key! Totally my fault for not actually believing the error, but might be nice if the error had more info. 

The error is currently: `provided key didn't exist in pubkeys`, but would be nice if it said specifically which key didn't exist, and maybe even listed the set of keys.

**Comment by alexanderbez** [comment]
Would be happy to help here ;-)

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3675 was merged to develop.
