### ISSUE TITLE
Tendermint not returning error code on the client side

### ISSUE THREAD

**Issue by himanshunagda** [tendermint/tendermint#3676]
Hi everyone,

As per tendermint documentation (https://tendermint.com/rpc/), tendermint should return "code" and "log" in the result (for async, sync and commit method). for example below (commit method response)
  "deliver_tx": {
            "log": "",
            "data": "",
            "code": "0"
        },
  "check_tx": {
            "log": "",
            "data": "",
            "code": "0"
  }

I am using broadcast_tx_commit,  tendermint is returning only "log" on the client side.
Here attached my response of all the 3 different method from tendermint.
Async and sync method are working fine but while using commit method, i am not getting code in my results.
![asyncMethod](https://user-images.githubusercontent.com/43402071/58320792-ccb35680-7e1c-11e9-9a84-8154cb8a52dd.png)
![deliverTx_Response](https://user-images.githubusercontent.com/43402071/58320828-ddfc6300-7e1c-11e9-9960-b01315e5f4ce.png)
![syncMethod](https://user-images.githubusercontent.com/43402071/58320840-e2288080-7e1c-11e9-9207-59dc4f205287.png)

**Comment by melekes** [comment]
The reason is us directly using Protobuf structs, all of which have `omitifempty` tag => response omitting empty fields (code=0, data=""). Maybe we should create intermediary structs in such cases?

**Comment by himanshunagda** [comment]
It means, will you be making some changes in rpc in future?
for example, creating intermediary structs for this kind of cases?

**Comment by melekes** [comment]
> will you be making some changes in tendermint rpc in future?

internally (i.e. they won't be visible to clients)

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/3889
