### ISSUE TITLE
Improve localnet tests

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#3689]
This is a meta-issue where we aim to collect issues that relate to the overall improvement of localnet tests (the ones that run during the `localnet` and `test_p2p` jobs on CircleCI).

Overall goals for this improvement:
1. Make the current tests more coherent and structured
2. Increase the variety of tests that we execute against localnet to ensure p2p behaviour doesn't break
3. (Longer-term) Introduce network instability into tests once the "happy path" is validated. (e.g. perhaps by using something like [Pumba](https://github.com/alexei-led/pumba))

Here is a list of related issues thus far (please update this list as needed):
* #2805

**Comment by erikgrinaker** [comment]
Subsumed by #5291.
