### ISSUE TITLE
p2p: Evaluate libp2p

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3696]
An original [issue](#988) and even [implementation](#995) were floated in December 2017, but deemed too early for such a change. There is increasing interest in revisiting libp2p from an interoperability perspective.

Work is ongoing to improve the separation of concerns in the Tendermint peer layer (#2067). This should help ease any transitions.

There are some particular details about benefits of libp2p in https://github.com/tendermint/tendermint/issues/2067#issuecomment-429196383.

It's also known that the current SecretConnection [is broken](https://github.com/tendermint/tendermint/issues/3315). Turns out it's broken in libp2p for ed25519 keys also. There's much discussion about using a Noise variant, which seems promising, but also might require additional development and integration. We could [consider using libp2p with TLS](https://github.com/tendermint/tendermint/issues/3315#issuecomment-497516911) for now instead.

It would be valuable to outline in more detail how adoption of libp2p would occur, and especially if it were possible to do iteratively without breaking too much at once so the changes are reviewable. 

It would also be really valuable to pin down some cost/benefit analysis on the change, and to make sure we understand if there's anything we'd have to give up.

**Comment by rairyx** [comment]
Sounds exciting, I'd imagine kadmelia for node discovery and routing, go-libp2p-pubsub for message broadcasting.

**Comment by abourget** [comment]
You guys should take a look at https://github.com/perlin-network/noise/tree/add-docs (especially that branch which is about to be released). Is that project what you meant by "Noise" ?

I found it to be incredibly powerful, overlaying gRPC on top of a network with peer IDs (using PKI). It's a lot simpler than libp2p, but a great building block, and makes great reuse of existing tooling.

**Comment by marbar3778** [comment]
we recently rewrote the p2p layer. The team decided to go with a custom implementation instead of libp2p. Will close this issue for now, we can come back to it in the future.

**Comment by RangerMauve** [comment]
> we recently rewrote the p2p layer. The team decided to go with a custom implementation instead of libp2p. Will close this issue for now, we can come back to it in the future.

Sorry to necro-post, but is there any documentation on the decision process for this? It'd be interesting to hear the tradeoffs that were considered by the team.

**Comment by creachadair** [comment]
[ADR 062](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-062-p2p-architecture.md) is probably a good place to start for understanding the existing state of P2P. 

Note, however, that we are planning to go ahead with a migration to libp2p after the v0.36 release. For more about the plans around libp2p, I recommend starting with [ADR 073](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-073-libp2p.md).

**Comment by RangerMauve** [comment]
> [ADR 062](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-062-p2p-architecture.md) is probably a good place to start for understanding the existing state of P2P.
> 
> Note, however, that we are planning to go ahead with a migration to libp2p after the v0.36 release. For more about the plans around libp2p, I recommend starting with [ADR 073](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-073-libp2p.md).

Thank you for the links!
