### ISSUE TITLE
error 1 - make install

### ISSUE THREAD

**Issue by debragail** [tendermint/tendermint#3702]
Debras-MacBook-Pro:tendermint 0PHE1IA$ make install
CGO_ENABLED=0 go install  -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD`" -tags 'tendermint' ./cmd/tendermint
../go-amino/amino.go:13:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/local/Cellar/go@1.10/1.10.4/libexec/src/github.com/pkg/errors (from $GOROOT)
	/Users/0PHE1IA/go/src/github.com/pkg/errors (from $GOPATH)
make: *** [install] Error 1

**Comment by melekes** [comment]
```
$ make get_tools
$ make get_vendor_deps
```
