### ISSUE TITLE
Allow `start` to replay blocks against empty or older state.

### ISSUE THREAD

**Issue by defunctzombie** [tendermint/tendermint#3713]
## Summary
Currently, starting a node without a state.db or application.db but with a blockstore.db results in a panic complaining that [state.Height != blockstore.Height](https://github.com/tendermint/tendermint/blob/master/consensus/replay.go#L347). Instead, I would expect the application to be able to replay the local blockstore and re-create the app state - then continue syncing against the network.

The gained benefit is being able to initialize new nodes against a blockstore.db which one may have gotten from one of their other nodes or shared via the community.

## Proposal
Remove the assertion check and add replay logic, which I believe may already be present, to re-create app and state.

**Comment by ebuchman** [comment]
state.db is part of the tendermint node's db, not the application's. 

> I would expect the application to be able to replay the local blockstore and re-create the app state - then continue syncing against the network.

This expectation should be fulfilled, but Tendermint expects its state.db to do this properly. Tendermint would only be able to recover without the state.db if its starting replay from height 0, so it's a bit of an edge case.

Is there a reason you need to throw away the state.db?

**Comment by tessr** [comment]
Going to close this for now. @defunctzombie let me know if this is still something you need and we can retriage.

**Comment by marbar3778** [comment]
This is part of the state-sync followup meta-issue. should we keep it till its completed?

**Comment by tessr** [comment]
Oh yes, sure.
