### ISSUE TITLE
invalid ip (0.0.0.0) when adding a peer to addessbook 

### ISSUE THREAD

**Issue by SebastianElvis** [tendermint/tendermint#3714]
**Tendermint version**: 0.31.4

**Environment**:
- **OS**: MacOS Mojave 10.14.5
- **Install tools**: `go build`
- **Others**:

**What happened**:

When I tried to set up a cluster (with seednode and pex) using docker-compose, peers cannot add each other to the address book.
The log shows that `invalid ip address 0.0.0.0`

I finally find out that, in the `AddPeer` function of `PEXReactor` (file `p2p/pex/pex_reactor.go`), `p.NodeInfo().NetAddress()` gets the peer address with ip 0.0.0.0.

I added a line `addr.IP = p.RemoteIP()` after it to force the ip to be the remote one, and the problem is gone.
I'm not sure what will happen if deploying this version in a physical machine rather than docker containers.

I highly suspect that this problem is because I use docker rather than a physical machine. This may not be a bug as we don't usually run Tendermint clusters in docker containers.

**How to reproduce it**:

Use `docker-compose` and a `macvlan` network

**Comment by melekes** [comment]
## Temporary solution

Have you tried hard coding IP address in docker-compose.yml file https://github.com/tendermint/tendermint/blob/99c9a35982f2cf5522bc8f3eb95d5d29c8ccefaf/docker-compose.yml#L16 ? It works for our localnet cluster.

## Long term solution

Generally, this should be fixed by https://github.com/tendermint/tendermint/pull/3646

**Comment by SebastianElvis** [comment]
> ## Temporary solution
> Have you tried hard coding IP address in docker-compose.yml file
> 
> https://github.com/tendermint/tendermint/blob/99c9a35982f2cf5522bc8f3eb95d5d29c8ccefaf/docker-compose.yml#L16
> 

Hardcoding IP does not support the `scale` functionality of docker-compose.

> ? It works for our localnet cluster.
> ## Long term solution
> Generally, this should be fixed by #3646

Thanks, this should be a good and clean solution.
