### ISSUE TITLE
libs/db/bolt: Batch.Delete implementation is incorrect

### ISSUE THREAD

**Issue by Yawning** [tendermint/tendermint#3717]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

`develop`

**What happened**:

Manual code review of the BoltDB backend.

**Anything else we need to know**:

> One of these things is not like the others
> One of these things just doesn't belong
> Can you tell which thing is not like the others
> By the time I finish my song?

  * https://github.com/tendermint/tendermint/blob/96e132b4b0bd234bd3405c1909cdd40f19d2d259/libs/db/boltdb.go#L183
 * https://github.com/tendermint/tendermint/blob/96e132b4b0bd234bd3405c1909cdd40f19d2d259/libs/db/c_level_db.go#L169
 * https://github.com/tendermint/tendermint/blob/96e132b4b0bd234bd3405c1909cdd40f19d2d259/libs/db/go_level_db.go#L164
 * https://github.com/tendermint/tendermint/blob/96e132b4b0bd234bd3405c1909cdd40f19d2d259/libs/db/mem_batch.go#L35

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3720 was merged to develop.

Thanks for contributing to Tendermint 👍
