### ISSUE TITLE
 libs/db/bolt: Get implementation is incorrect.

### ISSUE THREAD

**Issue by Yawning** [tendermint/tendermint#3718]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

`develop`

**What happened**:

Manual code review of the BoltDB backend.

**Anything else we need to know**:

Per the [documentation](https://godoc.org/go.etcd.io/bbolt#Bucket.Get): "The returned value is only valid for the life of the transaction.".  Failure to honor this constraint will result in crashes, as boltdb unmaps the backing pages.

https://github.com/tendermint/tendermint/blob/96e132b4b0bd234bd3405c1909cdd40f19d2d259/libs/db/boltdb.go#L69

This constraint also applies to `key`/`value` returned from the various boltdb `Cursor` calls, that are currently also returned directly from the boltdb backend's `db.Iterator` implementation.  The `db.Iterator` interface documentation only specifies that the `Key()` and `Value()` methods return read-only slices, and not that the returned slices will be invalidated the moment `Close()` is called.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3720 was merged to develop.

Thanks for contributing to Tendermint 👍
