### ISSUE TITLE
p2p: Unify peer stopping

### ISSUE THREAD

**Issue by brapse** [tendermint/tendermint#3719]
The p2p package currently exposes multiple public methods for stopping peers:

https://github.com/tendermint/tendermint/blob/master/p2p/peer.go#L190-L194
and
https://github.com/tendermint/tendermint/blob/master/p2p/peer.go#L197-L201
and
https://github.com/tendermint/tendermint/blob/master/p2p/switch.go#L295-L302
and
https://github.com/tendermint/tendermint/blob/master/p2p/switch.go#L306-L309

These public methods allow multiple non-p2p packagel components to take responsibility for managing the lifecycle of a shared resource; the peer. Decentralized lifecycle management has led to complex debugging scenarios and bugs. The goal here is to unify how peers are stopped and make other subtle stopping vectors private.

**Comment by alexanderbez** [comment]
Yeah only the router can disconnect from peers. Reactors can request for peers to be disconnected from or connected to.

**Comment by marbar3778** [comment]
closing this as the new stack solves the mentioned issue.
