### ISSUE TITLE
The sequence of gossipCatchup for votes and blockparts

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#3721]
Now, gossipVotesRoutine and gossipDataRoutine are two seperate routines and execute independently. Func gossipDataForCatchup will send the peer with historical block parts, but we should wait for gossipVotesRoutine send all the required 2/3+ precommits to it before sending the block parts, we'd better have a mechanism to control these two processes.
Otherwise what if all the peers have sent a part they assumed the recipient has received, but in fact  the recipient kept rejecting this part because it lacks the required 2/3+ precommits, but when it collected the votes, all the peers assumed it has that part and never send to it again.

**Comment by ebuchman** [comment]
Interesting. Do you have a test for this or how did you discover?

**Comment by james-ray** [comment]
Um, I just watched the code and guess.. haven't tested yet.
If I am going to test this, I will formulate lots of validators to make the sending of the 2/3+ precommits a longer time, and make an empty block, to make sending a block part quicker.
Right now, my company is testing a Tendermint network with 100 validators, maybe I can test this by the way.

**Comment by james-ray** [comment]
204565 {"log":"I[07-04|02:41:28.761] enterNewRound(122/0): Invalid args. Current step: 122/0/RoundStepPrecommit module=consensus height=122 round=0\r\n","stream":"stdout","time":"2019-07-04T02:41:28.76281       938Z"}
204566 {"log":"I[07-04|02:41:28.761] enterCommit(122/0). Current: 122/0/RoundStepPrecommit module=consensus height=122 commitRound=0\r\n","stream":"stdout","time":"2019-07-04T02:41:28.76282321Z"}
204567 {"log":"I[07-04|02:41:28.761] Commit is for a block we don't know about. Set ProposalBlock=nil module=consensus height=122 commitRound=0 proposal= commit=054237363232575CE06150B2C93D78E4B405A6251AC       EFFB2DFB1555FB8EA304C\r\n","stream":"stdout","time":"2019-07-04T02:41:28.76282676Z"}
204568 {"log":"I[07-04|02:41:28.761] Attempt to finalize failed. We don't have the commit block. module=consensus height=122 proposal-block= commit-block=054237363232575CE06150B2C93D78E4B405A6251ACEFFB2DF       B1555FB8EA304C\r\n","stream":"stdout","time":"2019-07-04T02:41:28.762830328Z"}
204569 {"log":"I[07-04|02:41:28.762] Added good transaction                       module=mempool tx=ED7C7DC29E1ADBB9C6412B07EFAFD8818A4AEDB4ED5C1900D4F82DC6F7CD2E5B res=\u0026{CheckTx:} height=121 total=4       3670\r\n","stream":"stdout","time":"2019-07-04T02:41:28.762833817Z"}
204570 {"log":"\u001b[32mINFO \u001b[0m[07-04|10:41:28] Submitted transaction                    \u001b[32mfullhash\u001b[0m=0xb6986ed430825e74aa00fd369b4e95e4e8da3c35930480012a22f8ee110c2856 \u001b[32mre       cipient\u001b[0m=0x3B16D5ab2B0aa9952d741E20922d45CfCf000001\r\n","stream":"stdout","time":"2019-07-04T02:41:28.762837516Z"}
204571 {"log":"\u001b[32mINFO \u001b[0m[07-04|10:41:28] tx hash                                  \u001b[32mhash\u001b[0m=0xb6986ed430825e74aa00fd369b4e95e4e8da3c35930480012a22f8ee110c2856\r\n","stream":"s       tdout","time":"2019-07-04T02:41:28.763003912Z"}
204572 {"log":"I[07-04|02:41:28.763] Added good transaction                       module=mempool tx=F0A9539D02A2ECC11C69BF837260CB80BD978834D013BD9EDE787D235D002C2A res=\u0026{CheckTx:} height=121 total=4       3671\r\n","stream":"stdout","time":"2019-07-04T02:41:28.76415839Z"}


222660 {"log":"I[07-04|02:41:49.104] Ensure peers                                 module=pex numOutPeers=0 numInPeers=6 numDialing=0 numToDial=10\r\n","stream":"stdout","time":"2019-07-04T02:41:49.1052633       83Z"}


It seems like I have re-produced the problem. We made 7 nodes in different areas of the world, Tokyo, Paris, Singapore, etc.. and we use tm-bench to send the test txs, and in one test scenario, we just send txs to one node, and we have enlarge the size of the mempool from 5000 to 50000. However, maybe due to the latency of the network, "mempool is full" still be triggered, and we found the node forever hang there.     Due to the uneven of the txs pressure, the height of peer0 is 122, and the height of other nodes is 245.
