### ISSUE TITLE
ABCI: RequestBeginBlock.Header.Time is sometimes far in the future

### ISSUE THREAD

**Issue by ashleyvega** [tendermint/tendermint#3723]
* Tendermint version: 0.31.5 (d2eab536)
* ABCI app: self-written, not currently publicly available
* OS: Ubuntu 16.04.5 LTS x86_64

**What happened**: The block header time starts drifting into the future. The below graph shows `now - BlockHeaderTime`, so if the value is negative, `Block.Header.Time` is ahead of real time.

![timediff](https://user-images.githubusercontent.com/48948661/59418318-bd428000-8dc0-11e9-93a0-cd445f026e96.png)

**What was expected to happen**: The block header time should match real time, to within a couple of seconds.

**Tried the latest version**: no

**How to reproduce it**: I have yet to create a minimal ABCI app that reproduces this problem.

**Logs**: At the default log levels (`main:info,state:info,*:error`) there are no useful errors. I have changed the config to `*:debug` and am waiting for the next occurrence of time drift.

**Config**: Default config, as generated by `tendermint testnet`

**node command runtime flags**: Just `tendermint node`

Our tendermint cluster consists of 3 nodes, in GB, SG and US. Transactions are submitted at a rate of under 10 per second. If under heavy load, it would be reasonable to expect the block header time to lag real time (ie drift into the past), but this issue is drift in the opposite direction.

**Comment by cdm** [comment]
Some extra info:
- The date on all nodes is confirmed as UTC and not in future. 
- The /status endpoint from tendermint returns a future date e.g. 
```
      "latest_block_height": "34114",
      "latest_block_time": "2019-06-13T09:15:31.279384Z",
```
- Our app uses bft-time stamps read from the block header

**Comment by melekes** [comment]
Note: we're planning to switch to proposer-based timestamps back https://github.com/tendermint/tendermint/issues/2840

**Comment by aleksraiden** [comment]
Yes, we have this issue too. For 1 or 2-weeks long testnet, we have up to+30 day in future

**Comment by ebuchman** [comment]
What is the value of the `time_iota_ms` param in the genesis file? How many blocks have there been and how quickly are the blocks being made?

**Comment by ashleyvega** [comment]
@ebuchman Thanks for the questions.

* `time_iota_ms`: I cannot find `time_iota_ms` (or indeed anything mentioning `iota`) in `.tendermint/config/*.json` or `.tendermint/config/config.toml` or `.tendermint/data/*.json`. Which file _should_ the value be in? Are any special arguments needed in `tendermint init` or `tendermint testnet` in order to get this value added?
* block count: anything up to 400k, after which we usually end up resetting the chain for other reasons.
* block frequency: one per second. We measure the actual block creation time, and because we're testing initially with low load, the block frequency sticks extremely closely to 1 second (never below, occasionally a few ms higher).

**Comment by ashleyvega** [comment]
@ebuchman It looks like we're missing the whole `consensus_params` section. I'll recreate the configs and  try again.

**Comment by ashleyvega** [comment]
`tendermint init` adds the `consensus_params` section while `tendermint testnet` does not:

* init: https://github.com/tendermint/tendermint/blob/master/cmd/tendermint/commands/init.go#L57
* testnet: https://github.com/tendermint/tendermint/blob/master/cmd/tendermint/commands/testnet.go#L128

**Comment by ashleyvega** [comment]
I have added `consensus_params` (as created by `tendermint init`) to `genesis.json` manually. Now re-testing...

**Comment by ashleyvega** [comment]
No luck with the added default `consensus_params` section. We have slightly different behaviour, but still future-time-drift.

![vegatimediff-devnet](https://user-images.githubusercontent.com/48948661/59664620-4edb3480-91a9-11e9-8238-a8792755ecff.png)

**Comment by ebuchman** [comment]
Thanks for the details. Any chance you can try with a smaller setting of the `time_iota_ms` param? Say 1ms instead of 1000ms ? This setting ensures that precommits are at least time_iota_ms ahead of the last block time, which could cause the time to move into the future incorrectly if the blocks are fast. 1s blocks seems like it should be slow enough that this isn't a big issue, but it could also be right on the cusp.

**Comment by ashleyvega** [comment]
@ebuchman After 20h (and counting) of running with `"time_iota_ms": "1"`, we have not seen any future block header times.

**Comment by ashleyvega** [comment]
@aleksraiden Have you tried adding `time_iota_ms=1` as @ebuchman suggests?

**Comment by aleksraiden** [comment]
> @aleksraiden Have you tried adding `time_iota_ms=1` as @ebuchman suggests?

Yes, added. After 2day of running all OK.

**Comment by aleksraiden** [comment]
But at now, params  `blocktime_iota` take not effect - blocks always produced with 1s interval (0.31.7 version)

**Comment by ebuchman** [comment]
> But at now, params blocktime_iota take not effect - blocks always produced with 1s interval (0.31.7 version)

Right, this doesn't control the block production time at all, just the timestamp in the header. 

What's the actionable here? Sounds like we need better documentation around the blocktime_iota?

**Comment by john-jam** [comment]
We have this issue too when we disable empty block creation (after a fresh init with tendermint v0.31.7):
`time_iota_ms=1` or `time_iota_ms=1000`
`create_empty_block=false`
`timeout_commit=1s`

AppHash never changes so needProofBlock return false and we send 100txs each seconds with tm-bench. It seems that every seconds, one first block is created with only 1tx (triggered by the mempool when it receives the first transaction) and a second block is directly created with the 99txs remaining without waiting for the commit timeout. Is it intended ? If yes, the double block creation every seconds produce the block time in the future.

**Comment by ashleyvega** [comment]
@ebuchman Actionable items could include:

* Sync up `tendermint init` and `tendermint testnet` wrt the addition of a `consensus_params` section.
* Add documentation for `time_iota_ms` so other people can avoid future block header timestamps.

I'm happy to do this and submit a pull request, if you think the above are items that should be done.

**Comment by ebuchman** [comment]
Yes please and thank you!

**Comment by skdjango001** [comment]
> I have added `consensus_params` (as created by `tendermint init`) to `genesis.json` manually. Now re-testing...

Hi Ashleyvega,
I am also getting same error like tendermint return future date 
How can you did the manually genesis.json file??

**Comment by ashleyvega** [comment]
@skdjango001 Have you tried setting `time_iota_ms` to `1`, as @ebuchman [suggested](https://github.com/tendermint/tendermint/issues/3723#issuecomment-503516607)?

## `genesis.json`
```json5
{
    "app_hash": "...",
    "app_state": { /* ... */ },
    "chain_id": "...",
    "consensus_params": {
      "block": {
        "time_iota_ms": "1",
        // ...
      },
      "evidence": { /* ... */ },
      "validator": { /* ... */ }
    },
    // ...
}
```
