### ISSUE TITLE
Make the RPC host localhost:26657 to prevent DDOS attacks

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#3724]

**Comment by melekes** [comment]
`0.0.0.0` -> `localhost`?

**Comment by thanethomson** [comment]
Please elaborate on this issue. This is [configurable](https://github.com/tendermint/tendermint/blob/master/config/config.go#L290).

**Comment by thanethomson** [comment]
So this refers to the **default** value for the configuration.

**Comment by marbar3778** [comment]
PR #3746 closes this issue.
