### ISSUE TITLE
tendermint localnetwork connectivity issues

### ISSUE THREAD

**Issue by Arihantjain1** [tendermint/tendermint#3725]
E[2019-06-15|18:27:04.000] Dialing failed                               module=pex addr=0b67fb8abc2f0413ae33533f5c1eb7c5601f863e@192.168.1.20:26656 err="incompatible: Peer is on a different network. Got test-chain-3hkehd, expected test-chain-FtMEKr" attempts=1

i m using same genesis on both node(count = 2) but getting error of chainid on local network 
i m using updated package to run this but getting error continue

please fix this!

**Comment by thanethomson** [comment]
Please provide both `genesis.json` files from both nodes (i.e. copy them from the nodes to your local machine and post them here).

Also, how are you generating your genesis file(s)? Are you using `tendermint testnet`?

**Comment by Arihantjain1** [comment]
No actually , both config.toml and genesis.json and remain are generating from tendermint init
Command , and whenever I m executing tendermint node p2p.peer.......
 Command it displaying me that Genesis are not same but I used same to run 
So can you tell me how to resolve

**Comment by thanethomson** [comment]
Try using the `tendermint testnet` command instead? (See `tendermint help testnet` for details).

For example, to create a 4-node test network (where all 4 nodes are validators):

```bash
tendermint testnet --v 4 \
    --hostname host1.yourdomain.com \
    --hostname host2.yourdomain.com \
    --hostname host3.yourdomain.com \
    --hostname host4.yourdomain.com \
    --o /tmp/testnet
```

Then look in the `/tmp/testnet` folder for all of the nodes' configuration. You'll see their `genesis.json` files are prepopulated with all of their details, and their Tendermint configuration files (`config.toml`) are also prepopulated with their peers' addresses.

**Comment by melekes** [comment]
> So can you tell me how to resolve

Please provide both genesis.json files from both nodes (i.e. copy them from the nodes to your local machine and post them here).

**Double check that `chain_id` parameter is the same in both genesis.json files**

**Comment by melekes** [comment]
Closing due to no response.
