### ISSUE TITLE
Doc request: what is the relationship between abci/types/Validator.Address and crypto/Address?

### ISSUE THREAD

**Issue by coriolinus** [tendermint/tendermint#3732]
[`abci/types/Validator`](https://godoc.org/github.com/tendermint/tendermint/abci/types#Validator) has an `Address` field of type `[]byte`.
[`crypto/Address`](https://godoc.org/github.com/tendermint/tendermint/crypto#Address) is a newtype which resolves to `[]byte`.

Request documentation of the relationship between them: can we simply cast between the two, or do we need to perform any kind of manual en/decoding?

**Comment by coriolinus** [comment]
Bumping in the hopes of an answer to the question, even if it is not yet formally documented. Are the two types the same, or is some conversion necessary?

**Comment by ebuchman** [comment]
Yes they should be the same and you should be able to cast between the two. In both cases they represent the raw hash of a pubkey.

**Comment by ebuchman** [comment]
Note specifically here when we populate the abci.Validator struct, we use `val.PubKey.Address()`, which returns the `crypto.Address` :)

https://github.com/tendermint/tendermint/blob/378a0e51bfbc11f8c9891a0fc18a2ff43536f51b/types/protobuf.go#L69-L74

**Comment by coriolinus** [comment]
Great, thanks!
