### ISSUE TITLE
leveldb to rocksdb

### ISSUE THREAD

**Issue by hongyuefan** [tendermint/tendermint#3736]
if replace leveldb with rocksdb , is will be better ?

**Comment by melekes** [comment]
Could you please ask your question on [our forum](https://forum.cosmos.network/c/tendermint) or [Riot chat](https://riot.im/app/#/room/#tendermint:matrix.org). Thanks!

> if replace leveldb with rocksdb

I, personally, haven't performed any benchmarks with rocksdb.
