### ISSUE TITLE
[p2p] reserved slots for peering

### ISSUE THREAD

**Issue by dlguddus** [tendermint/tendermint#3738]
Request a new configure "reserved_peers" to reserve slots for important peers in case of full capacity of peers.

**Problem example case**

1) sentry has peer of full capacity
2) validator-sentry connection accidentally ended
3) another peer kick in to the sentry making full capacity of peers
4) validator cannot connect to sentry because it is full

**Suggested Solution**

1) list validator's node id in "reserved_peers" configure of sentry
2) sentry node will save slots for reserved peers so that validator can connect to sentry regardless of full capacity of peers

**Comment by melekes** [comment]
Maybe we could use `private_peers_ids` for this? What do you think?

**Comment by dlguddus** [comment]
I would like to re-test the edge situation with private_peer_ids and comeback to you again! Thank you.

**Comment by melekes** [comment]
Duplicate of https://github.com/tendermint/tendermint/issues/2041 ?

**Comment by dlguddus** [comment]
Yes. You are right @melekes thank you.
Close the issue.
