### ISSUE TITLE
Wrong implementation of Bytes method for interfaces crypto.PubKey and crypto.PrivKey

### ISSUE THREAD

**Issue by ironman0x7b2** [tendermint/tendermint#3739]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): d2eab536ac1071b1b5f64283572397606326eb73

**ABCI app** (name for built-in, URL for self-written if it's publicly available): None

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **Install tools**:
- **Others**:

**What happened**:
- It seems like the implementation of crypto.PrivKey.Bytes and crypto.PubKey.Bytes methods in edd25519 and secp256k1 are wrong. Why because the defined types PrivKeyEd25519, PubKeyEd25519, PrivKeySecp256k1 and PubKeySecp256k1 are basically byte arrays so we can directly return the byte slice instead of amino marshalled byte slice.

- The Bytes method returning byte slices with lengths 69, 37, 37 and 38 respectively.

**What you expected to happen**:
- Bytes method should return the original byte slice instead of amino marshalled byte slice.

- The Bytes method should return byte slices with lengths 64, 32, 32 and 33 respectively.

**Have you tried the latest version**: yes/no
Yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:
Because of this issue, the Bech32 encoded public keys which are generated through Javascript are different than Golang.

https://github.com/tendermint/tendermint/blob/master/crypto/ed25519/ed25519.go#L44
https://github.com/tendermint/tendermint/blob/master/crypto/ed25519/ed25519.go#L143
https://github.com/tendermint/tendermint/blob/master/crypto/secp256k1/secp256k1.go#L46
https://github.com/tendermint/tendermint/blob/master/crypto/secp256k1/secp256k1.go#L154

**Comment by ebuchman** [comment]
One reason not to return the raw bytes is to preserve the type data, so the Bytes() representation also encodes which kind of public key it is. There's also the case of mutlisig pubkeys, which need to encode more than one pubkey and their types.

So I think we might just need to update the JS for this.

**Comment by ironman0x7b2** [comment]
I think we can have a method Type which returns the type of key or else we can have a method RawBytes which returns the raw byte slice.

I personally prefer having Type method because it will solve both issues i.e. knowing the type and getting raw bytes.

**Comment by ironman0x7b2** [comment]
@ebuchman @melekes 

Hi,
Any update on this? When can we expect the proper action on it? What do you guys think about it?

**Comment by ebuchman** [comment]
I think we want to support including the type information in the serialized form so probably best for now to go with a `RawBytes` method. But you can get the bytes already with a type switch (or assertion) and just slicing the underling bytes alias:

```
	pk := pubkey.(ed25519.PubKeyEd25519)
	rawBytes := pk[:]
```

**Comment by marbar3778** [comment]
with the switch to protobuf the bytes methods return rawbytes instead of amino encoded bytes, for this reason it may be good to add a Type() method to the pubkey and privkey interfaces.

does anyone have any objections @melekes @ebuchman

**Comment by melekes** [comment]
nope

**Comment by marbar3778** [comment]
moved this out of proposal because is it implemented in #4648
