### ISSUE TITLE
restore sanity to those looking to get in-proc control of tendermint loggers

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#375]
@silasdavis please make a recommendation here of a simple way forward with this and we will target 0.8.1. We need to do a larger overhaul of our logging system (https://github.com/tendermint/tendermint/issues/358) that will take more time, but happy to get some low-hanging fruit to you on that front asap

**Comment by silasdavis** [comment]
Thanks for this, I was planning to come to this when we have 0.8.0 integrated.

**Comment by adrianbrink** [comment]
@ebuchman Is it okay if I close this in favour of #358
