### ISSUE TITLE
Match RemoteSignerError codes with KMS

### ISSUE THREAD

**Issue by tarcieri** [tendermint/tendermint#3752]
There's a TODO in the definition of `RemoteSignerError` to create an enum of error codes /cc @Liamsi 

https://github.com/tendermint/tendermint/blob/660e72a12f977a9b52659e263d096406b181b2ba/privval/errors.go#L26

I just added some initial error codes in this PR:

https://github.com/tendermint/kms/pull/272/files#r296408346

Namely:

1. Generic error
2. Double sign error (which will occur if two validator processes are active concurrently and talking to the same KMS process)

I imagine there are a few more it could send that would be helpful for debugging, like the requested key is missing.

**Comment by marbar3778** [comment]
@tarcieri would you like to have standard errors for when there is an error unrealted to the connection? 

the connection errors should come from gRPC now

**Comment by Liamsi** [comment]
https://grpc.io/docs/guides/error/#error-status-codes

**Comment by tarcieri** [comment]
I think it makes sense to send double signing notifications back to Tendermint, although I'm not sure what if anything Tendermint could make of those except that they can be retried at a larger h/r/s.
