### ISSUE TITLE
Indexing tags and events from an ABCI app

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#376]
**Use case**: "There currently isn’t an easy/efficient way for a light client to fetch relevant transactions via Tendermint RPC (we currently have to sync through all the blocks and fetch every transaction, which is not very efficient). Ideally, we could have an interface where we can filter all the transactions to get ones relevant to our wallet." ([link](https://tendermint.slack.com/archives/basecoin/p1484864398000026)) "for basecoin, we’d probably just tag the address of each input and output"

Tags will come from `DeliverTx` responses. We will need to store a map [tag] => `[txResponse1, txResponse2, ..]` somewhere. An external indexer (Lucene, Solar)? Internal indexer (levelDB)? Jae: "not sure what simple indexer would be able to handle tags efficiently too."

Why do we need something like Lucene to store a map? Or there will be more complex queries? Or the performance of levelDB is not sufficient?

**Comment by ebuchman** [comment]
Good question. I don't know all that much about the indexing/querying space though, but I think part of the concern is about bloating Tendermint by supporting complex features. Once we start offering tags and queries, the feature requests for what we can query might get out of hand quick - it would help to offload that responsibility to something designed for it.   might be valuable to keep simple/common query use-cases in tendermint though.

**Comment by adrianbrink** [comment]
Closing this in favour of #525
