### ISSUE TITLE
How to migrate tendermint from v0.20 to v0.31 in a live network,thx.

### ISSUE THREAD

**Issue by ArvonHuang** [tendermint/tendermint#3761]
How can i  migrate tendermint from v0.20 to v0.31 in a live network? thx.

**Comment by melekes** [comment]
I am afraid there's no way other than exporting the state and starting a new chain with that state (hardfork). The reason is that there were many breaking changes between v0.20 and v0.31. See https://github.com/tendermint/tendermint/blob/master/UPGRADING.md for more details.

**Comment by melekes** [comment]
If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org) 💬
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint) 🧵
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚
