### ISSUE TITLE
try to make get_tools, but return 'cannot load bufio....'

### ISSUE THREAD

**Issue by silravend** [tendermint/tendermint#3766]
os: ubuntu 18.04

git clone and cd to tendermint, then 
make get_tools

return this:

--> Installing tools
./scripts/get_tools.sh
--> Installing gogo/protobuf (61dbc136cf5d2f08d68a011382652244990a53a9)...
~/Documents/go/src/github.com/gogo/protobuf ~/Documents/go/src/github.com
build github.com/gogo/protobuf/protoc-gen-gogo: cannot load bufio: cannot find module providing package bufio
Makefile:83: recipe for target 'get_tools' failed
make: *** [get_tools] Error 1

**Comment by melekes** [comment]
Do you have `GO111MODULE` set to `on` in your env?

**Comment by melekes** [comment]
Can't replicate

**Comment by silravend** [comment]
my enviroment is windows10, how can I set GO111MODULE?

**Comment by melekes** [comment]
Closing due to no response.
