### ISSUE TITLE
Add Prometheus observability of last signed height per validator

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3773]
We'd like to observe individual last signed height for validators  via Prometheus by requesting a tendermint_consensus_last_signed_height metric with the following labels:

* address (example: "E33032D801DA4D124FBF696DEF7832E415EA74EE")
* operator (example: "cosmosvaloper1lc4jjw8zveuuj3njhy70zl23vgmpds2xg830hn")
* chain_id (example: cosmoshub-2)

As some might object to the cardinality of this (100+ validators on cosmoshub-2), a config option to enable this could be beneficial as well. Request is related to per-validator voting power in #3083, so a common toggle for per-validator observability would be suitable.

Thanks for your consideration. :-)

**Comment by ebuchman** [comment]
Note `operator` isn't a concept native to Tendermint. Tendermint could provide the validator's consensus pubkey, but the operator is a Cosmos-SDK concept. I wonder if the SDK is a better place for per-validator metrics?

**Comment by mdyring** [comment]
Hm, seems nice to provide for any Tendermint-based chain I think it makes sense to provide it here.

Providing address, consensus pubkey and chain-id labels would be neat!

**Comment by mdyring** [comment]
On second thought, would be messy to have both Tendermint and cosmos-sdk endpoints for Prometheus. I suspect cosmos-sdk is doing all the Prometheus-related work today, so if that it the case it might make better sense to do it from there. @jackzampolin any thoughts?

**Comment by mdyring** [comment]
This metric is useful for detecting external signing errors [such as this](https://twitter.com/validator_net/status/1156386709648662528?s=20).

Currently we're using [our own tool](https://github.com/validator-network/votewatcher) for monitoring the last signed height, but would be nice to offer out of the box IMHO.
