### ISSUE TITLE
Tendermint Core Guides

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3808]
1. [x] Writing a built-in Tendermint Core application in Go (assigned to @melekes)
2. [x] Writing a Tendermint Core application in Go (assigned to @melekes)
3. [ ] Writing a Tendermint Core application in Javascript
4. [x] Writing a Tendermint Core application in Java (@climber73)
5. [ ] Writing a Tendermint Core application in Rust
6. [ ] Writing a Tendermint Core application in C++
7.  [x] Writing a Tendermint Core application in Kotlin (@climber73)

External contributions are welcome 🏆 Please leave a comment if you want to write a specific guide for X language. When ready for review, send a PR to `master` branch.

FAQ:
1) Does it have to be a specific application?
No, any application will do.
2) Do I have to follow some structure?
Yes, see the first guide in the series https://github.com/tendermint/tendermint/blob/master/docs/guides/go-built-in.md.

Refs https://github.com/tendermint/tendermint/issues/3016, https://github.com/tendermint/tendermint/issues/3169

**Comment by climber73** [comment]
I'm going to describe Java way (and if needed - Kotlin also)

**Comment by cmwaters** [comment]
With the 0.35 release approaching, the topic of docs and specifically of the Tendermint Guides (which are out of date) were brought up. We've decided to cut the scope down to just maintaining the Built-in and Out-of-process Golang Guides (at least for now) as we think they are the most helpful to users.
