### ISSUE TITLE
v0.31: PRs to backport

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3810]
- https://github.com/tendermint/tendermint/pull/3809
- https://github.com/tendermint/tendermint/pull/3762

**Comment by ruseinov** [comment]
@melekes what is the process for backporting? Does it make sense for me to backport there 2 or the one I have introduced?

**Comment by melekes** [comment]
I or someone else need to create a branch v0.31.8 with two above commits and merge it into v0.31.

**Comment by ruseinov** [comment]
Got it, looking forward to that!

**Comment by melekes** [comment]
You can do it too :)

**Comment by ruseinov** [comment]
done in https://github.com/tendermint/tendermint/pull/3837
