### ISSUE TITLE
range query for txs

### ISSUE THREAD

**Issue by fedekunze** [tendermint/tendermint#3812]
One of the main blockers for income statement reporting and accounting is the ability to perform range queries for txs. This will allow users to get a set of txs between two given block heights. 

This could be done on the SDK but @marbar3778 and I agreed that it'd be better to have it upstream in Tendermint.

Eg: `GET /txs?from=<start-height>&to=<end-height>`

cc: @ebuchman @jackzampolin

**Comment by melekes** [comment]
you can index txs by height and use `tx_search?query="tx.height > X AND tx.height < Y"`

**Comment by melekes** [comment]
@fedekunze is ^ sufficient for your use-case?

**Comment by fedekunze** [comment]
@melekes sorry, no. This is related to ABCI range queries. Moving this issue to #3683
