### ISSUE TITLE
secret_connection_test.go test failed: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4)

### ISSUE THREAD

**Issue by jxlczjp77** [tendermint/tendermint#3814]
OS: windows 10
go version go1.12.7 windows/amd64
======================================

PS E:\work\go\src\github.com\tendermint\tendermint\p2p\conn> go test
--- FAIL: TestSecretConnectionHandshake (0.00s)
    secret_connection_test.go:58: Failed to establish SecretConnection for foo: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE642027457A29448C2B5FDDC3F6D4307BD9676D9BAAE42499F30B3636C709923713AE12402804D037C4EBAC6A9267BFB822C046D35EE1E25ED86F3CC9C69FA04A683DC33A32FB554FBC828372484C0FCA4088F94D7A21392FD44FE5444226024E0C367D01
    secret_connection_test.go:87:
                Error Trace:    secret_connection_test.go:87
                                                        secret_connection_test.go:94
                Error:          Expected nil, but got: &errors.errorString{s:"unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE642027457A29448C2B5FDDC3F6D4307BD9676D9BAAE42499F30B3636C709923713AE12402804D037C4EBAC6A9267BFB822C046D35EE1E25ED86F3CC9C69FA04A683DC33A32FB554FBC828372484C0FCA4088F94D7A21392FD44FE5444226024E0C367D01"}
                Test:           TestSecretConnectionHandshake
    secret_connection_test.go:73: Failed to establish SecretConnection for bar: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE6420FF9901D9EAB9368A1AB589F2465DEE1D2D056BC438BCCF885BAFBF6B3CB653CD1240CB26EF792467DC613CD838B4B28AD5743BB4DD236B2F84FEFF0954BF5C63549D7A9F087F7E0C1EA33C06F59395C9D9AFE7AAA2D6177E1FBEB65129D17C139E05
--- FAIL: TestConcurrentWrite (0.00s)
    secret_connection_test.go:58: Failed to establish SecretConnection for foo: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE6420C4D3844E7126A802EA654711E96A268AD29212642B471E38E686D1B1CBEF091912407A4E9ECF0B583E1E6C9B8C995EDAA1AA2048FA7EA79346291883DC122F83559E9A4EB4A2CED94C5824C7EBC62AEDE0303308E35223B098A76AB5025B703BE709
    secret_connection_test.go:73: Failed to establish SecretConnection for bar: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE6420C5881B4A78502EDEE19B451401235E77E0A705B00A05B23BAB8CD6A4EE51D4BD12401DC3B2972E69025713C6DA9AFF938511CBFED46827092A4841160AC66C0E2ED2C9759782E7CDF12577671AF796EC34AF7977110A58DB72BC4532FDC4F847FB0B
    secret_connection_test.go:87:
                Error Trace:    secret_connection_test.go:87
                                                        secret_connection_test.go:147
                Error:          Expected nil, but got: &errors.errorString{s:"unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE6420C4D3844E7126A802EA654711E96A268AD29212642B471E38E686D1B1CBEF091912407A4E9ECF0B583E1E6C9B8C995EDAA1AA2048FA7EA79346291883DC122F83559E9A4EB4A2CED94C5824C7EBC62AEDE0303308E35223B098A76AB5025B703BE709"}
                Test:           TestConcurrentWrite
--- FAIL: TestConcurrentRead (0.00s)
    secret_connection_test.go:58: Failed to establish SecretConnection for foo: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE64209F75454D9C6BA7DBDEFDC9CC65A71C9755F96CC0FACC6566B8254F7DB72736091240601DC6443BDD77034CA0F13D1995E593B8FB52F27B46A9CB82DF04C55A1AF3176F98BF3329634D0BD23DE028CB63866C4A684FF11C67801243DA537038540407
    secret_connection_test.go:73: Failed to establish SecretConnection for bar: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE6420BF2881ED867290118BE5CB9C2F7428AB72C7609601332A458F48E77FBF9B8D0F124073FD1787F592DDD7836A453CB26A14AD50183056B91C5E4A3760DDF3391E615315174F5A4188DED42571AE5B417E2F78F9953F9A4A726C1DC6A5D6F6C9416D0C
    secret_connection_test.go:87:
                Error Trace:    secret_connection_test.go:87
                                                        secret_connection_test.go:169
                Error:          Expected nil, but got: &errors.errorString{s:"unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE64209F75454D9C6BA7DBDEFDC9CC65A71C9755F96CC0FACC6566B8254F7DB72736091240601DC6443BDD77034CA0F13D1995E593B8FB52F27B46A9CB82DF04C55A1AF3176F98BF3329634D0BD23DE028CB63866C4A684FF11C67801243DA537038540407"}
                Test:           TestConcurrentRead
--- FAIL: TestSecretConnectionReadWrite (0.00s)
    secret_connection_test.go:227: Failed to establish SecretConnection for node: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE642069DB35AB383924B60EA6E8411F135F753C74CE244DE81CEEBA3937C222E58CAE124020C86046FFA0A7401A7CF40864C72214EA3F08D66A74FF6079949422B9636A4EE49F923501AC66839029A0BF8508F8663F65F72CF478BA2E1D1B968A5072EC02
    secret_connection_test.go:288:
                Error Trace:    secret_connection_test.go:288
                Error:          Expected nil, but got: &errors.errorString{s:"unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE642069DB35AB383924B60EA6E8411F135F753C74CE244DE81CEEBA3937C222E58CAE124020C86046FFA0A7401A7CF40864C72214EA3F08D66A74FF6079949422B9636A4EE49F923501AC66839029A0BF8508F8663F65F72CF478BA2E1D1B968A5072EC02"}
                Test:           TestSecretConnectionReadWrite
    secret_connection_test.go:227: Failed to establish SecretConnection for node: unmarshal to conn.authSigMessage failed after 6 bytes (expected field number: 1; got: 4): 0A251624DE6420A2C717818250D5808167D858B2E8865EAC9F3EEE49C0B1140DBC2287A10A1E301240DFC8A36468C33AF06E454648B2A0AF14C0795045D03A6F94876AA75735A62F03437CF9405CDAD4478FC979407ABCF42003B0FB6BC939CCEC7BE7BE96C45D4506
FAIL
exit status 1
FAIL    github.com/tendermint/tendermint/p2p/conn       1.179s

**Comment by ebuchman** [comment]
Interesting - do other tests fail for you?

**Comment by jxlczjp77** [comment]
The reason for the test failure was that I did not use go. mod (GO111MODULE = off)
