### ISSUE TITLE
rpc: maxBodyBytes and maxHeaderBytes should be configurable

### ISSUE THREAD

**Issue by bluele** [tendermint/tendermint#3817]
Hi, there. 
We are developing a tendermint based blockchain. This blockchain has a support for wasm smart contract, and it is deployed as Tx via RPC server. Our contract size is often greater than 1MB. But currently maxBodySize for RPC server is 1MB, and it is hardcoded in source. 
In our opinion, this value should be configurable by owner of tendermint node.
Unfortunately we couldn't find any workaround, so we propose making maxBodyBytes and maxHeaderBytes configurable.

**Comment by ebuchman** [comment]
Cool! Thanks for contributing the fix here.

Is your WASM application open source? What language is it in? 

Thanks!

**Comment by bluele** [comment]
@ebuchman 
Yes. We have multiple projects, one of which is already open source. Its URL is here: https://github.com/bluele/hypermint

ABCI app is written by golang, and smart contract is mainly written by rust.

Please check this out :)
