### ISSUE TITLE
Run CI from forks

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#382]
But this is also a security risk. White list? Not sure what the right thing to do is. Maybe jenkins will deal better.

https://circleci.com/docs/fork-pr-builds/

**Comment by adrianbrink** [comment]
Are our builds dependent on secret variables that we do not want to leak?

Also, I think it might be a good idea to have a GitHub hook that checks whether a team member has given their okay and only then does CircleCI run the build.
For example, I create a PR from my private fork, and you want have to comment on that PR with [CI-build] before CircleCI actually builds it.
Without this, a potential attack could involve opening tons of PRs and overloading CircleCI.

**Comment by ebuchman** [comment]
That sounds great. We don't have secrets right now but we used to and will again soon.
