### ISSUE TITLE
p2p: Unify Connection stopping

### ISSUE THREAD

**Issue by brapse** [tendermint/tendermint#3833]
The current connection stopping logic is  stop between `OnStop` `FlushStop` and `stopServices` methods which depend on a set of channel to coordinate. This schema comes with significant complexity and bugs when it comes to cleaning up the connection related resources. 

A better solution would be to insist that all requests are flushed and adhere to the interface provided in `BaseService` and enable the proper interpretation of `service.IsRunning()`

**Comment by melekes** [comment]
Similar issue re stopping a peer https://github.com/tendermint/tendermint/issues/3719

**Comment by tessr** [comment]
I _think_ this proposal is rendered obsolete by the new P2P proposal + the way reactors will be implemented in that proposal, so I'm going to close this for now.

**Comment by tessr** [comment]
I _think_ this proposal is rendered obsolete by the new P2P proposal + the way reactors will be implemented in that proposal, so I'm going to close this for now.
