### ISSUE TITLE
Tendermint disconnects tmkms on signing error

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3844]
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
cosmos-sdk v0.36.0-rc1

**What happened**:
Testing multiple validators connecting to a single tmkms instance, see https://github.com/tendermint/kms/issues/323.

It appears Tendermint drops the connection in case of a step regression, which is undesirable when running a HA setup with multiple validators and a single tmkms instance.

**What you expected to happen**:
Tendermint behaving in the same manner as if it couldn't sign locally, essentially do nothing but perhaps log the event.

**How to reproduce it** (as minimally and precisely as possible):
Setup tmkms to connect to two validator instances. Once it is time to do a Proposal, the step regression is likely to appear on the tmkms side.
More validators means higher likelyhood to reproduce.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

Validator seeing disconnect:

```
Jul 29 18:51:32 i-054c5a397bb89993a gaiad[1765]: E[2019-07-29|18:51:32.500] enterPropose: Error signing proposal         module=consensus height=103751 round=0 err=EOF
Jul 29 18:51:32 i-054c5a397bb89993a gaiad[1765]: E[2019-07-29|18:51:32.510] Error signing vote                           module=consensus height=103751 round=0 vote="Vote{8:32363E5BAA6B 103751/00/1(Prevote) 1D838591C0CF 000000000000 @ 2019-07-29T18:51:32.510739717Z}" er
Jul 29 18:51:33 i-054c5a397bb89993a gaiad[1765]: E[2019-07-29|18:51:33.002] Error signing vote                           module=consensus height=103751 round=0 vote="Vote{8:32363E5BAA6B 103751/00/2(Precommit) 1D838591C0CF 000000000000 @ 2019-07-29T18:51:33.002257952Z}" 
Jul 29 18:51:33 i-054c5a397bb89993a gaiad[1765]: I[2019-07-29|18:51:33.280] Executed block                               module=state height=103751 validTxs=0 invalidTxs=0
Jul 29 18:51:33 i-054c5a397bb89993a gaiad[1765]: I[2019-07-29|18:51:33.306] Committed state                              module=state height=103751 txs=0 appHash=7D818B002B59538743844C84F29F32F793C6F1AEB4CF303FD6CB4538780C56AF
Jul 29 18:51:33 i-054c5a397bb89993a gaiad[1765]: E[2019-07-29|18:51:33.411] Ping                                         module=privval err="remote signer timed out"
Jul 29 18:51:33 i-054c5a397bb89993a gaiad[1765]: E[2019-07-29|18:51:33.604] Error attempting to add vote                 module=consensus err="Existing vote: Vote{8:32363E5BAA6B 103751/00/2(Precommit) 1D838591C0CF 595EB3562ECF @ 2019-07-29T18:51:33.028052018Z}; New vote
Jul 29 18:51:33 i-054c5a397bb89993a gaiad[1765]: E[2019-07-29|18:51:33.654] Error attempting to add vote                 module=consensus err="Existing vote: Vote{8:32363E5BAA6B 103751/00/2(Precommit) 1D838591C0CF 595EB3562ECF @ 2019-07-29T18:51:33.028052018Z}; New vote
```

**Comment by liangping** [comment]
I had this error on latest kava-testnet

> Tendermint disconnects tmkms

Both validator and tmhsm are alive, but don't sign blocks

**Comment by ebuchman** [comment]
Hmm I'm not seeing anything on Tendermint side that's causing this to happen either. @jleni do you have any ideas? Is it possibly solved by https://github.com/tendermint/tendermint/pull/3370 ?

**Comment by ebuchman** [comment]
See https://github.com/tendermint/kms/issues/323#issuecomment-524135380

**Comment by melekes** [comment]
@mdyring / @liangping do you still have this problem?
