### ISSUE TITLE
Open Tracing Support

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#3849]
We should add support for https://opentracing.io/ to the p2p layer! This would allow for much better identification of performance bottlenecks and other problems with the p2p layer.

**Comment by michaelfig** [comment]
Now that https://opentracing.io/ and https://opencensus.io/ are merging into https://opentelemetry.io/ we might consider aiming for that instead.  It looks like they will be supporting both OpenCensus API compatibility (for metrics and traces) as well as OpenTracing (just for traces).

Also, [tendermint ADR 011](/tendermint/tendermint/blob/master/docs/architecture/adr-011-monitoring.md) doesn't mention that go-kit contains an [opencensus integration](https://github.com/go-kit/kit/tree/master/tracing#opencensus), and that opencensus also has a [prometheus exporter](https://opencensus.io/exporters/supported-exporters/go/prometheus/).

Tendermint seems closely tied to go-kit ATM.  @jackzampolin, is the opentracing backend you're interested in supported by opencensus?  If so, but I would suggest adding new tracing/metrics backends first via opencensus and eventually opentelemetry.

This would help me, as I am not interested in being tied to Prometheus (though having that option via the opencensus exporter I mentioned above is still valuable), and I want distributed tracing.
