### ISSUE TITLE
build/packaging issue

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#385]
`mv: cannot move ‘./build/dist/windows_386.zip’ to ‘./build/dist/tendermint_0.8.0_windows_386.zip’: Permission denied`

I think because of the use of docker the `build/dist` folder ends up owned by `root` and the renames fail. Is there a better way to do this?

**Comment by melekes** [comment]
oh my.. we can build to `build/pkg` and copy instead of move
