### ISSUE TITLE
Enable Depndabot

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#3852]
- https://dependabot.com/
- By using a bot like this it will update the go.mod when version updates arise, taking the burden away from us.

**Comment by ebuchman** [comment]
We need to be so careful about dependency upgrades: https://arstechnica.com/information-technology/2019/08/the-year-long-rash-of-supply-chain-attacks-against-open-source-is-getting-worse/

It almost certainly should not be done automatically.

**Comment by melekes** [comment]
It will create a PR (half of the job). Another half would be to review the changes.

**Comment by melekes** [comment]
Yes, it will probably force us to update deps more often, BUT reviewing small changesets is much easier than reviewing v1.0 -> v2.0 which often happens right now.

**Comment by marbar3778** [comment]
it works now, closing this issue.

**Comment by melekes** [comment]
"This release fixes a potential denial-of-service (DoS) vector in gorilla/websocket, and we recommend that all users upgrade to this version (v1.4.1) or later"

One more reason ^. #security
