### ISSUE TITLE
rpc: Refactor rpc/lib

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3857]
root `rpc` package should be renamed to `jsonrpc`
`rpcclient` package should be renamed to `client`
`rpcserver` package should be renamed to `server`

new API:

```
import "github.com/tendermint/tendermint/rpc/lib/jsonrpc/client"

c := client.New()
c2 := client.NewURI()
```

**Comment by melekes** [comment]
```
	Call(method string, params map[string]interface{}, result interface{}) (interface{}, error)
```

why Call both accepts and returns result?

**Comment by melekes** [comment]
JSONRPCRequestBatch is thread-safe, whereas clients aren't. We should either make our clients thread-safe or remove mtx from JSONRPCRequestBatch.

**Comment by ebuchman** [comment]
> why Call both accepts and returns result?

I think it might have to do with making some of the reflection stuff easier but I'm not sure

**Comment by marbar3778** [comment]
as part of this refactor should we include the moving to a jsonrpc pkg, something like: https://github.com/osamingo/jsonrpc

**Comment by ebuchman** [comment]
probably we can make the very minor change anton is suggesting, but consider using a proper jsonrpc pkg as part of #3367
