### ISSUE TITLE
Remove use of `libs/common/errors.go` 

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#3862]
I believe the use of a customized error package is not the best practice, I propose we phase this out and move towards using https://github.com/pkg/errors. This has already begun in some places, now we need to just follow through

Repos that need to be changed as well:
- [x] Iavl
- [ ] Cosmos-SDK
      - We are in the process of doing this
- [x] Tendermint

**Comment by IgorPerikov** [comment]
I'd like to help a bit with that, if you don't mind

**Comment by marbar3778** [comment]
Ah already spent time on it, should have it done soon, sorry I should have assigned myself, thank you though

**Comment by IgorPerikov** [comment]
no worry, it's fine 🤗

**Comment by ebuchman** [comment]
Is this done/closable?

**Comment by marbar3778** [comment]
just waiting on the sdk to complete the transition so we can delete the `errors.go` file. If we cut a release without the file then will block the SDK from upgrading until that work is done.

**Comment by melekes** [comment]
Is this done/closable?

**Comment by marbar3778** [comment]
>just waiting on the sdk to complete the transition so we can delete the errors.go file. If we cut a release without the file then will block the SDK from upgrading until that work is done.
