### ISSUE TITLE
mempool: Getting stuck in infinite loop of submitting txs (non-deterministic)

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#3865]
**Tendermint version**: v0.32.1 (official release)

**ABCI app**: `kvstore`

**Environment**:
- **OS** (e.g. from /etc/os-release): CentOS
- **Install tools**: [tmtestnet](https://github.com/interchainio/testnets/)
- **Others**:

I set up an 8-validator network on AWS using the [tmtestnet](https://github.com/interchainio/testnets/) script, where the mempool size limit was set to 5,000.

**What happened**:
After submitting transactions at a sufficiently high rate to saturate the mempool, it appears as though one or more validators have transactions "stuck" in their mempool and they somehow manage to keep successfully submitting these transactions to the network, and the network keeps committing these transactions *ad infinitum*.

The trouble is, this problem seems to be **non-deterministic**. It does not always occur when saturating the mempool with transactions, but it has only been observed when the mempool becomes saturated (thus far, out of testing on 6 distinct 8-validator networks).

<img width="1680" alt="Screen Shot 2019-08-01 at 12 05 44 PM" src="https://user-images.githubusercontent.com/212999/62310361-5b64d500-b457-11e9-96b0-0df3a9a15d08.png">

Zooming in on the tail end of the graph:

<img width="1680" alt="Screen Shot 2019-08-01 at 12 14 32 PM" src="https://user-images.githubusercontent.com/212999/62310372-60298900-b457-11e9-93e0-bb04bdc97520.png">

**What you expected to happen**:
I would have expected all validators' mempools to be empty after such a load test, and that no further transactions be committed to the blockchain when nobody is submitting any transactions.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Use [tmtestnet](https://github.com/interchainio/testnets/) to deploy the network and then execute a load test against it:

```bash
./tmtestnet.py -c 08-validators.yaml network deploy
./tmtestnet.py -c 08-validators.yaml loadtest start 3200_txs_per_sec
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
I was unable to obtain any meaningful logs, and unable to reproduce now when attempting at greater logging verbosity.

**Config (you can paste only the changes you've made)**:
See [this gist](https://gist.github.com/thanethomson/9119d7df63055569ebd65ae49d225005)

**Comment by melekes** [comment]
I would like to remind you & those who are reading this that application should also implement replay protection.

**Comment by ebuchman** [comment]
Is it possible to replicate on an app that does have replay protection?

**Comment by marbar3778** [comment]
@alexanderbez have you observed this behaviour with v1?

**Comment by alexanderbez** [comment]
I haven't executed these types of benchmarks on v1. However, this shouldn't be happening if the application has replay protection, which should make `CheckTx` calls fail and thus have the tx(s) removed from the mempool data structures.

@marbar3778 how do I reproduce this in the repo? is there a tool or test I can run?

**Comment by marbar3778** [comment]
I reproduced it with https://github.com/informalsystems/tm-load-test and running 1-3 tendermint nodes. 

I would bombard the node with txs using kvstore and then watch grafana.
