### ISSUE TITLE
Is the order of tx in block and blockResults the same?

### ISSUE THREAD

**Issue by qiluge** [tendermint/tendermint#3866]
please help me to resolve this question https://github.com/cosmos/cosmos-sdk/issues/4828, thx!

**Comment by melekes** [comment]
`Results are for the height of the block containing the txs. Thus response.results[5] is the results of executing getBlock(h).Txs[5]`

https://tendermint.com/rpc/#blockresults

**Comment by qiluge** [comment]
OK，thank you very much!

**Comment by melekes** [comment]
If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org) 💬
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint) 🧵
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚
