### ISSUE TITLE
`Mempool.MaxMsgBytes` is in wrong position in config/toml.go

### ISSUE THREAD

**Issue by bluele** [tendermint/tendermint#3868]
Previously, I fixed a related part at #3826, but during the release process of v 0.32.2, it seems that the degradation occurred due to the wrong commit merge.

https://github.com/tendermint/tendermint/blob/4d7cd8055b4083376b788239207f72f423e6ce07/config/toml.go#L280-L306

Related commits are here: https://github.com/tendermint/tendermint/commit/4d7cd8055b4083376b788239207f72f423e6ce07#diff-092cdc48047eeb4c0bca311a2e1b8ae6

**Tendermint version**

v0.32.2

**Comment by melekes** [comment]
Oops.. thank you for spotting this.

Speaking of `MaxMsgBytes`, don't you think we should switch to `MaxTxBytes`? By specifiyng max_msg_bytes in config we are forcing a user to account for something he/she does not know (amino overhead). I believe we should calculate it ourselves and only require users to specify desired `max_tx_bytes`.

**Comment by bluele** [comment]
Sure, it might be better.
However, the size limit of the data that `mempool.Reactor` can handle is `max_tx_bytes` plus amino overhead implicitly. Don't you mind that? (https://github.com/tendermint/tendermint/blob/master/mempool/reactor.go#L266)
If there is no problem here, I think it is a good decision.

**Comment by melekes** [comment]
> Don't you mind that? (https://github.com/tendermint/tendermint/blob/master/mempool/reactor.go#L266)

Can't we add `aminoOverhead` (`MaxTxBytes + aminoOverhead`)?

**Comment by bluele** [comment]
From my understanding, I think we can :)
Would you like me to create a new PR for that fix?

**Comment by melekes** [comment]
Go ahead!
