### ISSUE TITLE
CI: add docker logs to artifacts when a test fails

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#387]
eg. fluke failure here https://github.com/tendermint/tendermint/pull/386 that we can't investigate

**Comment by ebuchman** [comment]
Also how to get outputs from `go test` failures ... https://circleci.com/gh/tendermint/tendermint/606

**Comment by melekes** [comment]
Added `/var/log/upstart/docker.log` to artifacts. But this error:

```
Error deleting container: Error response from daemon: Driver btrfs failed to remove root filesystem 50cc4e21460626294e81de10f5b38541023d128eaac2320a092fe3ded7ca017c: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for ce9458a9638f989ea73fdb4da6399c936a65598cc13013b2ff00332968c67aa2: operation not permitted
```

 is present in all builds and do not have any impact on tests. [Upgrading docker](https://github.com/docker/docker/issues/22547) seems to be the solution, but we can't do it because of the CircleCI.

Anyway, having docker logs is a good idea.

**Comment by melekes** [comment]
> Also how to get outputs from go test failures ... https://circleci.com/gh/tendermint/tendermint/606

how did you guess that it was `go test` failure?

**Comment by melekes** [comment]
Ok, I think I've addressed this issue https://github.com/tendermint/tendermint/issues/387#issuecomment-276567484 in #394

**Comment by melekes** [comment]
As for the https://github.com/tendermint/tendermint/issues/387#issue-204394209, how do you feel about printing a response from `curl ../status` commands?

**Comment by melekes** [comment]
Ahh, it won't tell us anything... we need TM logs

**Comment by ebuchman** [comment]
> how did you guess that it was go test failure?

It timed out in the middle of the consensus package test, which I've spent inordinate hours debugging in the past. Thought I was done but alas, guess not.


> Error deleting container: Error response from daemon: Driver btrfs failed to remove root filesystem 50cc4e21460626294e81de10f5b38541023d128eaac2320a092fe3ded7ca017c: Failed to destroy btrfs snapshot /var/lib/docker/btrfs/subvolumes for ce9458a9638f989ea73fdb4da6399c936a65598cc13013b2ff00332968c67aa2: operation not permitted

Yeh this is one of those annoying CircleCI things but fortunately it doesn't really effect the tests (unless we try to remove docker containers in a shell script ...)

> printing a response from curl ../status commands? Ahh, it won't tell us anything... we need TM logs

Printing responses sounds good, but we really also need the TM logs.

Will look at PR, thanks!

**Comment by melekes** [comment]
> but we really also need the TM logs

yeah, but this require rewriting almost all docker related tests. for each test case we need to gather the logs from each container, merge them and store the result somewhere (`test/logs`?) circleci then would copy all the files from that directory to ARTIFACTS.

**Comment by ebuchman** [comment]
Aren't the logs all stored in a common docker directory though? Can we not just copy that?

**Comment by melekes** [comment]
Interesting thought! Yes, you're right http://stackoverflow.com/a/33018394/820520. But in this case we need container IDs

**Comment by melekes** [comment]
How about we run 1 more container (`syslog`) and configure all other containers (`--log-driver=syslog`) to write their logs to it? then we copy all the files from the syslog container to Circle CI.

Found one more interesting project: https://github.com/gliderlabs/logspout - aka router for docker containers

**Comment by ebuchman** [comment]
Oh that's not a bad idea. Does copying the log files directly from /var/lib/docker not work?

**Comment by ethanfrey** [comment]
I banged my head getting good logs out of docker containers.  You can read those json files directly, but it's hard to stream them, and they escape anything that is json inside.  Which was a killer for us, using json structured output.

I found a nice simple syslog config to redirect it to another service (logstash) worked well. logspout is another option, but I think 0.2. or 0.3? Maybe more now. Syslog is solid

**Comment by melekes** [comment]
>Does copying the log files directly from /var/lib/docker not work?

2 problems here: 1) it will not work on Mac (https://github.com/docker/for-mac installs docker onto another path) 2) once container is gone, logs are gone

https://github.com/gliderlabs/logspout is really nice. it captures the logs of all containers running without `-t` flag, just what we need

**Comment by ethanfrey** [comment]
Here are some lines I used.  Make sure to redirect docker not just to syslog, but to a specified facility (local{0,1,2}), otherwise it goes to `daemon` and gets mixed up with lots of other data.

Top lines send all logs to a remote host for collection and processing, as well as a local log.  The bottom file does log rotation on syslog.

/etc/rsyslog.d/11-docker-files.conf:
```
#   -------------------------------------------------------
#        Log Docker to file and remote logstash
#   -------------------------------------------------------
$template Timestamped,"%HOSTNAME% production %timegenerated:::date-rfc3339% %msg%\n"

docker.warn  /var/log/docker
local0.* /var/log/apps;Timestamped
local0.* @@699cfbb8-c8cf-4d15-b17b-997e104495f5-ls.logit.io:16024;Timestamped
```


/etc/logrotate.d/docker:
```
/var/log/apps
{
  # keep last 2 weeks of logs
  daily
  rotate 14
  create 0644 root root
  # current and last logs as text, rest gziped
  compress
  delaycompress

  # and now tell syslog to use the new files
  postrotate
    /bin/kill -HUP `cat /var/run/syslogd.pid 2> /dev/null` 2> /dev/null || true
  endscript
}
```

**Comment by ethanfrey** [comment]
docker facility captures issues in the docker daemon itself.

**Comment by ethanfrey** [comment]
This was for production, not testing, to get data into logspout and an elk stack, but maybe useful.

**Comment by melekes** [comment]
@ethanfrey got it. thanks!
