### ISSUE TITLE
Bug in PeerState

### ISSUE THREAD

**Issue by tanhuiya** [tendermint/tendermint#3874]
In the current process,if `psHeight != msg.Height`，` ps.PRS.Precommits` will be set for `nil`
https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L1253

And, in next process, when the peer-heigth lagging by local-height 1, we use `ps.PRS.Precommits` again.
https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L1266

Should we reverse the sequence for 

`if psHeight != msg.Height || psRound != msg.Round {}` and `if psHeight != msg.Height {}`

or

set a temporary value for `ps.PRS.Precommits` ?

**Comment by melekes** [comment]
Do you want to try write **a test case** showing the error?

**Comment by tessr** [comment]
Closing this as part of issue clean up (and because those links are now outdated). If this comes up again, we can reopen.
