### ISSUE TITLE
Decode transaction

### ISSUE THREAD

**Issue by BigCodilo** [tendermint/tendermint#3875]
Hello
When i send GET request: 
`http://localhost:26657/tx?hash=0x43B8422E9FD4FD4A01213772E989CDA5F36103A0EA679B95932052B20C016267`
I get the JSON struct in responce:
`{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "hash": "43B8422E9FD4FD4A01213772E989CDA5F36103A0EA679B95932052B20C016267",
    "height": "18",
    "index": 0,
    "tx_result": {
      "log": "[{\"msg_index\":0,\"success\":true,\"log\":\"\"}]",
      "gasWanted": "200000",
      "gasUsed": "33513",
      "events": [
        {
          "type": "message",
          "attributes": [
            {
              "key": "YWN0aW9u",
              "value": "YnV5X25hbWU="
            }
          ]
        }
      ]
    },
    "tx": "rgEoKBapCjZS59jqCgpnb29nbGUuY29tEg4KCW5hbWV0b2tlbhIBNRoUr67sqicZ8wXbWkNLD8E6c0TGM/YSBBDAmgwaagom61rphyEC6ICqudQCIugpL8NEvi6Fblxk+ZB+51T+NUDg0WdMQCUSQG0z4HhxINONIjPcQc/GDyVOjU9CRovZaT3GxcekSvN6SBQx94xgwMkq7EqivCxSqYB/TDC0Gp5Z/6z2+Z4Km3k="
  }
}`
One part of this JSON is: `rgEoKBapCjZS59jqCgpnb29nbGUuY29tEg4KCW5hbWV0b2tlbhIBNRoUr67sqicZ8wXbWkNLD8E6c0TGM/YSBBDAmgwaagom61rphyEC6ICqudQCIugpL8NEvi6Fblxk+ZB+51T+NUDg0WdMQCUSQG0z4HhxINONIjPcQc/GDyVOjU9CRovZaT3GxcekSvN6SBQx94xgwMkq7EqivCxSqYB/TDC0Gp5Z/6z2+Z4Km3k=`
How can i decode this to string or structure?

**Comment by melekes** [comment]
This is the base64-encoding of the raw tx.

**Comment by melekes** [comment]
If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org) 💬
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint) 🧵
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚

**Comment by BigCodilo** [comment]
I tried to do so, but it turns out something like this:

> ((
> 6Rهظي
> 
> google.com
> 	nametoken5ٌ'ZCKء:sDئ3j
> &ًZى!وش"و)/أD.n\d~هT5@ـرgL@%@m3ـxq س"3Aدئ%NOBFعi=ئإا¤JzH1`ة*ٌJ,RL0Y،
> y

what am I doing wrong?

**Comment by melekes** [comment]
how are u encoding transaction when you sent it to tendermint?

**Comment by BigCodilo** [comment]
I send JSON string

**Comment by viettienbk** [comment]
@BigCodilo : Have you solved the problem?

**Comment by BigCodilo** [comment]
Yes i already solved this problem. I used .RegisterCodec in some packages, after that i created decoder and use is for solving task
