### ISSUE TITLE
Don't use `omitempty`

### ISSUE THREAD

**Issue by safareli** [tendermint/tendermint#3882]
Types which are generated from `proto` files in go have JSON annotations which contain `omitempty` for all keys, for example:
https://github.com/tendermint/tendermint/blob/62f97a69e97262b5feb57b1c2498f0c1e0e297b3/abci/types/types.proto#L137-L145

Results in this:
https://github.com/tendermint/tendermint/blob/62f97a69e97262b5feb57b1c2498f0c1e0e297b3/abci/types/types.pb.go#L1711-L1720

Which means if you just make empty `ResponseInfo{}` and serialize it to JSON you would get empty JSON object, or if you do not set some field that field will be omitted from resulting JSON.

On the other hand, types defined by hand in go don't use `omitempty` at all, all this results in inconsistency. As some fields are in json all the time and some aren't, it makes writing parsers of request/response types unnecessarily harder in other statically typed languages.

**Comment by safareli** [comment]
Quick google gave me this article which seems to solve the issue
https://medium.com/@nevio/golang-dealing-with-protocol-buffer-omitempty-and-boolean-json-responses-ae1ba5f4e9c3

But I'm not a go developer and can't pick it up myself.

**Comment by marbar3778** [comment]
>  As some fields are in json all the time and some aren't, it makes writing parsers of request/response types unnecessarily harder in other statically typed languages.
I agree with the reasoning herer, @melekes, thoughts?

**Comment by safareli** [comment]
As a note, besides types from /abci/types/types.proto, other types from:
- /crypto/merkle/merkle.proto
- /types/proto3/block.proto
- /libs/common/types.proto
are also exposed as part of RPC

**Comment by melekes** [comment]
Thanks for bringing this up @safareli. Based on what I know there are four options available:

1) create intermediate structs for RPC specifically (+) or 
2) set EmitDefaults to true when marshaling https://stackoverflow.com/a/50044963/820520 (++) or 
3) use gogo proto json.tag feature (+) or
4) post-processing script https://github.com/tendermint/tendermint/issues/3882#issuecomment-518770040

**Comment by safareli** [comment]
No problem!, happy for seeing responce so fast 🙌

While we are at it, there is one type which I noticed in go side having no json annotations reslting in fields named `LikeThis` in json probably fixing it would be good too: https://github.com/tendermint/tendermint/blob/v0.32.2/types/tx.go#L85

**Comment by blinky3713** [comment]
Can I ask what is the status of this or #3889 is? Maybe I'm wrong, but even if you remove the `omitempty` from your JSON codecs, your codebase will still work as is? We're hoping to move beyond this in our work soon, and it's a pretty big pain point for us. If we need to contribute something let us know. Thanks!

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/3889#pullrequestreview-273472120 two comments need to be resolved before we can merge. Want to try and fix those?

**Comment by blinky3713** [comment]
@melekes https://github.com/tendermint/tendermint/pull/3912/files

**Comment by melekes** [comment]
It looks like we have two slightly orthogonal issues here:

1. _(raised by @safareli)_ some on the RPC response types (defined in https://github.com/tendermint/tendermint/blob/master/rpc/core/types/responses.go) include Protobuf types, which contain `omitempty`. But most of the response types themselves do not contain `omitempty`. This results in inconsistent output where some field are present, others - don't.

2. _(raised by @blinky3713)_ Protobuf types default is to use `omitempty` to save space. Writing parsers is hard in statically typed languages (e.g. Haskell). Here @blinky3713 talks about all Proto types exposed by Tendermint (i.e. abci/types, crypto/merkle, types/block, libs/common/types). Is this right @blinky3713?

While (1) can be solved by using a custom Marshaller https://godoc.org/github.com/golang/protobuf/jsonpb#JSONPBMarshaler (setting EmitDefaults to true will just ignore the omitempty tag in struct), (2) needs to be solved by the target language itself imho

**Comment by safareli** [comment]
> It looks like we have two slightly orthogonal issues here:

@blinky3713 made the comment on the PR for clarifying his understanding of approach taken in the PR. We don't have issue with proto files itself. The main issue we have/care about is `1.` - the inconsistency issue.

> Using a custom Marshaller in (1) will result in breaking JSON-RPC spec (#3889 (comment)) 

Why would it?

As I see the custom Marshaller is used only for [marshaling Response* types](https://github.com/tendermint/tendermint/blob/44dad6d70b80860646cea4f99494159b13ebbae7/abci/types/result.go#L49-L105)

The `RPCResponse` contains `Result  json.RawMessage` and when "success" case is constructed the Result has to be already marshaled using codec of the go-amino lib:


https://github.com/tendermint/tendermint/blob/acb874eaf668a57a98cae613cc0c77b8f9c3c1af/rpc/lib/types/types.go#L181-L194

I guess the codec from amino delegates to MarshalJSON for types being encoded. If yes, then `jsonpbMarshaller` will be used for marshaling `Response*` types which as of the PR uses `EmitDefaults: true`.

It makes me think that that PR fixes the issue as is and is not breaking json-rpc spec.

In case the amino codec is not delegating to MarshalJSON, then something like `jsonpb.Marshaler{EmitDefaults: true}` should be implemented for it and used instead of
https://github.com/tendermint/tendermint/blob/acb874eaf668a57a98cae613cc0c77b8f9c3c1af/rpc/lib/types/types.go#L186

**Comment by melekes** [comment]
> As I see the custom Marshaller is used only for marshaling Response* types

right

**Comment by safareli** [comment]
If that's right, then what's left to move forward on this?

**Comment by melekes** [comment]
> It makes me think that that PR fixes the issue as is and is not breaking json-rpc spec.

Did someone verify ^?

**Comment by safareli** [comment]
We haven't

**Comment by melekes** [comment]
Done in https://github.com/tendermint/tendermint/pull/3889

**Comment by safareli** [comment]
Thanks for the effort 🎉!
