### ISSUE TITLE
Where is amino.Typ3_ByteLength?

### ISSUE THREAD

**Issue by jian-yu** [tendermint/tendermint#3884]
**Tendermint version** (0.32.2):

**What happened**:
I can't find the variable named 'Typ3_ByteLength' in the "tendermint/go-amino/amino.go" which is called in tendermint/types/tx.go:136 'amino.Typ3_ByteLength'. But I find the variable named 'Typ3ByteLength' in the tendermint/go-amino/amino.go. Is 'Typ3ByteLength' euqal to 'Typ3_ByteLength'?

**What you expected to happen**:

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
Yes this is correct, `Typ3ByteLength` is === to `Typ3_ByteLength`

**Comment by marbar3778** [comment]
will close this issue, if you run into the same problem, please comment here and I will be notified.
