### ISSUE TITLE
Add monitoring/instrumentation for remote signers (kms/etc.)

### ISSUE THREAD

**Issue by jleni** [tendermint/tendermint#3885]
At the moment, there are no metrics to help validators analyze the connection to the remote signers / KMS. 

As a first step, I would suggest adding the following metrics to the node:
- remote_signer_request_count
- remote_signer_request_failed
- remote_signer_request_roundtrip
- remote_signer_ping_count
- remote_signer_ping_failed
- remote_signer_ping_roundtrip

As a follow up of this issue (matching error codes) https://github.com/tendermint/tendermint/issues/3752 , more instrumentation could be added wrt the specific error codes, etc.

**Comment by marbar3778** [comment]
With the migration to grpc this will be covered by: https://github.com/grpc-ecosystem/go-grpc-prometheus
