### ISSUE TITLE
sig verify reuse & verify parallelly

### ISSUE THREAD

**Issue by cjqpker** [tendermint/tendermint#3886]
Motivation: Signature verifying is a heavy CPU consumption process and in TM results of verifying are not reused to accelerate block executing, especially when a block is full of txs, excuting the block will slow down the consensus process.

Feature Request: 
1、CheckTx return the sig verifying result, TM cache it
2、Add CheckBlock into ABCI, excute CheckBlock before prevote, may be can excuting async. And CheckBlock will do sig verifying parallelly using multi goroutines
3、Expose a interface from TM to ABCI app to query verifying result, may be all txs's verifying result will hit and need no verifying again.

BTW, sig verifying parallelly using multi goroutines is a very good way to improving consensus performance, bellow is a demo:
https://github.com/annchain/annchain/blob/master/chain/app/verify.go

**Comment by melekes** [comment]
Not sure I understand. We verify `Vote`(s) and `Proposal` signatures https://tendermint.com/docs/spec/blockchain/blockchain.html#vote-2. We don't require / nor we expect transactions to contain signatures.

**Comment by cjqpker** [comment]
> Not sure I understand. We verify `Vote`(s) and `Proposal` signatures https://tendermint.com/docs/spec/blockchain/blockchain.html#vote-2. We don't require / nor we expect transactions to contain signatures.

Not signatures of Votes or Proposals, I mean signatures of txs's, what will be verified in app.

**Comment by melekes** [comment]
> Not signatures of Votes or Proposals, I mean signatures of txs's, what will be verified in app.

Right right, sorry. Can't application cache the signature verification result?

> Add CheckBlock into ABCI

Are you talking about https://github.com/tendermint/tendermint/issues/2175?

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/issues/3759
