### ISSUE TITLE
make localnet-start should automatically dial to localhost ports instead of random IP:PORT

### ISSUE THREAD

**Issue by utkarsh5k** [tendermint/tendermint#3891]
My understanding is that make localnet-start should work right out of the box. However, it seems that when we run it, the nodes are spawned, but they try to dial a random IP (hence failing with connection refused error). If it is indeed supposed to work right out of the box, shouldn't the nodes dial LOCALHOST:PORT? 

In the makefile it seems that the persistent peers are populated from a random IP. Or am I missing something in process of setting up a local cluster? 

Edit: I keep running into connection refused errors when I try to change the config.toml files under build/ . What is the proper way to get the local cluster running end to end (my approach seems hacky)? Thanks. 

Edit 2: Attaching output log after simply running make localnet-start. Followed the [documentation](https://tendermint.com/docs/networks/docker-compose.html#run-a-testnet).

```
Attaching to node3, node0, node2, node1
node3    | I[2019-08-12|06:21:18.446] Version info                                 module=main software=0.32.2 block=10 p2p=7
node3    | I[2019-08-12|06:21:18.501] Starting Node                                module=main impl=Node
node3    | I[2019-08-12|06:21:18.565] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} ID_:86b294fb47d543f4111554472d80c6f79c382811 ListenAddr:tcp://0.0.0.0:26656 Network:chain-cl6FBW Version:0.32.2 Channels:4020212223303800 Moniker:7324B03BA8EC2772 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26657}}"
node3    | E[2019-08-12|06:21:19.572] dialing failed (attempts: 1): dial tcp 192.167.10.2:26656: i/o timeout module=pex addr=a4c6d3cf6da160e4fc70f42d5811b313ef035251@192.167.10.2:26656
node3    | E[2019-08-12|06:21:19.590] dialing failed (attempts: 1): dial tcp 192.167.10.4:26656: i/o timeout module=pex addr=384da46367207928d1bae07311aef2c7c5d9d957@192.167.10.4:26656
node3    | E[2019-08-12|06:21:19.591] dialing failed (attempts: 1): dial tcp 192.167.10.3:26656: i/o timeout module=pex addr=04a6f26dedc977f523feaa35c2449bc4817766ca@192.167.10.3:26656
node3    | E[2019-08-12|06:21:19.927] Error dialing peer                           module=p2p err="dial tcp 192.167.10.2:26656: connect: connection refused"
node2    | I[2019-08-12|06:21:20.017] Version info                                 module=main software=0.32.2 block=10 p2p=7
node0    | I[2019-08-12|06:21:20.044] Version info                                 module=main software=0.32.2 block=10 p2p=7
node1    | I[2019-08-12|06:21:20.067] Version info                                 module=main software=0.32.2 block=10 p2p=7
node2    | I[2019-08-12|06:21:20.073] Starting Node                                module=main impl=Node
node2    | I[2019-08-12|06:21:20.092] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} ID_:384da46367207928d1bae07311aef2c7c5d9d957 ListenAddr:tcp://0.0.0.0:26656 Network:chain-cl6FBW Version:0.32.2 Channels:4020212223303800 Moniker:417163B96CEA2E02 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26657}}"
node2    | E[2019-08-12|06:21:20.101] dialing failed (attempts: 1): dial tcp 192.167.10.3:26656: connect: connection refused module=pex addr=04a6f26dedc977f523feaa35c2449bc4817766ca@192.167.10.3:26656
node2    | E[2019-08-12|06:21:20.102] dialing failed (attempts: 1): dial tcp 192.167.10.2:26656: connect: connection refused module=pex addr=a4c6d3cf6da160e4fc70f42d5811b313ef035251@192.167.10.2:26656
node0    | I[2019-08-12|06:21:20.116] Starting Node                                module=main impl=Node
node0    | I[2019-08-12|06:21:20.129] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} ID_:a4c6d3cf6da160e4fc70f42d5811b313ef035251 ListenAddr:tcp://0.0.0.0:26656 Network:chain-cl6FBW Version:0.32.2 Channels:4020212223303800 Moniker:DAD90E3A773741CB Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26657}}"
node1    | I[2019-08-12|06:21:20.139] Starting Node                                module=main impl=Node
node1    | I[2019-08-12|06:21:20.174] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} ID_:04a6f26dedc977f523feaa35c2449bc4817766ca ListenAddr:tcp://0.0.0.0:26656 Network:chain-cl6FBW Version:0.32.2 Channels:4020212223303800 Moniker:140EC9DDBF146B64 Other:{TxIndex:on RPCAddress:tcp://0.0.0.0:26657}}"
```

**Comment by melekes** [comment]
> If it is indeed supposed to work right out of the box, shouldn't the nodes dial LOCALHOST:PORT?

no, because each Docker container has a different IP address (you can't reach another Docker container by calling localhost with the exception of directly linking them).

> In the makefile it seems that the persistent peers are populated from a random IP. Or am I missing something in process of setting up a local cluster?

See https://github.com/tendermint/tendermint/blob/master/docker-compose.yml Each container has a static IP address.

**Comment by melekes** [comment]
What's the output of `docker ps -a`? Looks like your containers can't reach each other which is weird given they belong to the same network https://github.com/tendermint/tendermint/blob/master/docker-compose.yml#L67.

**Comment by utkarsh5k** [comment]
@melekes interesting, it seems like something is wrong with the docker setup. My output is: 

```
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                    PORTS               NAMES
772b4d04c1a2        hello-world         "/hello"            41 hours ago        Exited (0) 41 hours ago                       epic_panini
```
I suppose I should be seeing something related to tendermint too, correct?

**Comment by utkarsh5k** [comment]
@melekes I cloned the repo, and then ran make localnet-start. Was there any step that I was supposed to do before that to make everything work? (except make build-linux etc that is there in the doc)

**Comment by utkarsh5k** [comment]
@melekes looks like it is a [known issue](https://docs.docker.com/docker-for-mac/networking/) in MacOS.

**Comment by melekes** [comment]
Works fine for me (2.1.0.0)

**Comment by melekes** [comment]
10.14

**Comment by sabau** [comment]
Should be normal at the very beginning of the command to have some failures, every node boot at the same time and immediately start to query his neighbours, likely they are still in the startup phase.
After a few seconds, I see everything working.

**Comment by utkarsh5k** [comment]
Thanks @sabau ! It does say started node in a few seconds for all the nodes.
