### ISSUE TITLE
Remove JSON-RPC wrapping when URI over HTTP is used?

### ISSUE THREAD

**Issue by safareli** [tendermint/tendermint#3895]
Currently, if you access tendermint RPC server using `URI over HTTP`,  [you get](https://tendermint.com/rpc/#uri-http):
```json
{
    "error": "",
    "result": {
        "hash": "2B8EC32BA2579B3B8606E42C06DE2F7AFA2556EF",
        "log": "",
        "data": "",
        "code": "0"
    },
    "id": "",
    "jsonrpc": "2.0"
}
```
i.e. even if you are using regular URI over HTTP, to access the API you get JSON-RPC related fields.

---
Main question is what's the point of having the `URI over HTTP` version?

1. It's for quick testing using `curl`

2. It's for people who prefer to use REST-like APIs

if answer is `1.`  then this extra fields are sort of justified, but if's for `2.`  then JSON-RPC fields are not adding value and making consumption of response slightly complicated for no reason.

My impression is that answer is 2, as there are some efforts made for defining [swagger.json](https://github.com/tendermint/tendermint/pull/3880), In which case I think this JSON-RPC fields should be removed.

**Comment by melekes** [comment]
> Main question is what's the point of having the URI over HTTP version?

1

**Comment by safareli** [comment]
closing then
