### ISSUE TITLE
rpc: Inconsistent encoding of integer types

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#3898]
We currently seem to be encoding integers inconsistently in responses from the RPC.

**Tendermint version**: 0.32.2-76f3db06

**ABCI app** (name for built-in, URL for self-written if it's publicly available): kvstore

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
```bash
> curl "http://localhost:26657/broadcast_tx_sync?tx=\"abcd=1234\""
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "code": 0,
    "data": "",
    "log": "",
    "hash": "F0732FA1810E26F15D3DF480ACE8B3AD5E429C563B22AEBDED33FC06273FD42B"
  }
}
```

Note how `result` -> `code` is encoded as an integer. Then:

```bash
> curl "http://localhost:26657/tx?hash=0xF0732FA1810E26F15D3DF480ACE8B3AD5E429C563B22AEBDED33FC06273FD42B"
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "hash": "F0732FA1810E26F15D3DF480ACE8B3AD5E429C563B22AEBDED33FC06273FD42B",
    "height": "3",
    "index": 0,
    "tx_result": {
      "events": [
        {
          "type": "app",
          "attributes": [
            {
              "key": "Y3JlYXRvcg==",
              "value": "Q29zbW9zaGkgTmV0b3dva28="
            },
            {
              "key": "a2V5",
              "value": "YWJjZA=="
            }
          ]
        }
      ]
    },
    "tx": "YWJjZD0xMjM0"
  }
}
```

Here, `result` -> `index` is encoded as an integer, but `result` -> `height` is encoded as a string.

Should we not prefer encoding integers consistently? Is this related to Amino? It seems as though `int64`'s get encoded as strings, but other integers get encoded as integers.

**Comment by safareli** [comment]
If you don't encode int64 as string you would have to write custom json parser in javascript clients:

https://stackoverflow.com/questions/47188449/json-max-int-number/47188576

https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigint/18755261

**Comment by blinky3713** [comment]
While we're talking about it, it would be really nice to have a uniform encoding for bytestrings in the RPC api. In this example it seems like `hash` is base-16 encoded and the key/value pairs are base64 encoded, which matches up to my experience. What do you think?

**Comment by thanethomson** [comment]
> If you don't encode int64 as string you would have to write custom json parser in javascript clients

This is what I was afraid of 😢 Oh well, we'll have to allow for the `int64` encoding inconsistency then. Should we be allowing for encoding of integers as either strings or numbers as a general convention?

> While we're talking about it, it would be really nice to have a uniform encoding for bytestrings in the RPC api.

It's a good idea to have as much consistency as possible, but I think having hashes as hex values is something of a convention. Representing other data as base64 is just more compact. @blinky3713 - if you feel strongly about this, open a separate issue and we can discuss it?

**Comment by ebuchman** [comment]
Right. Hashes are hex, everything else is base64.

Should we close this then? If we're going to enforce all integers are encoded as strings I think that's an issue for the go-amino repo, but I'm not sure we want to do that anyways. Probably fine to stick with what I believe is the convention of encoding 64-bit ints as string and anything less as int ...

**Comment by thanethomson** [comment]
Yeah, let's close this then 👍
