### ISSUE TITLE
Continuous Fuzzing Integration

### ISSUE THREAD

**Issue by yevgenypats** [tendermint/tendermint#3899]
Hi, I'm Yevgeny Founder of [Fuzzit](https://fuzzit.dev) - Continuous fuzzing as a service platform.

I saw that you implemented Fuzz targets but they are currently not running as part of the CI.

We have a free plan for OSS and I would be happy to contribute a PR if that's interesting.
The PR will include the following
- Continuous Fuzzing of master branch which will generate new corpus and look for new crashes
- Regression on every PR that will run the fuzzers through all the generated corpus and fixed crashes from previous step. This will prevent new or old bugs from crippling into master.

You can see our basic example [here](https://github.com/fuzzitdev/example-go) and you can see and example of in the wild integration [here](https://github.com/google/syzkaller).

Let me know if this is something worth working on.

Cheers,
Yevgeny

@melekes @marbar3778

**Comment by marbar3778** [comment]
Hello, Sorry for the delay in our response. Currently, we aren't in need of this service. Thank you for reaching out, if we come in need of this in the future we will reach out to see how we can work together.
