### ISSUE TITLE
Connecting nodes in a chain should be automagically easier

### ISSUE THREAD

**Issue by faddat** [tendermint/tendermint#391]
Peer reactor resolved the original issue.  Now, the issue is refining this.

**Comment by faddat** [comment]
This is well-resolved with peer reactor.  If I was to change the comment somewhat it would instead recommend that bootstrapping happen based on some well-known-good nodes that would link chains by their name automagically.

**Comment by adrianbrink** [comment]
This seems to be resolved by the peer reactor.
