### ISSUE TITLE
High availability validators via signature agregation

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3914]
Currently, validator operators that want high availability run multiple validator nodes each with the same private key and attempt to co-ordinate them signing, typically by using either a leader-election service or by using a single KMS instance. 

A possible alternative is to introduce a new multisig pubkey type that supports pubkey and signature aggregation. This would keep the size of a validator's pubkey and signature the same as now, but would allow it to be composed of some 2-of-3 aggregated signatures. Furthermore the parties generating the signatures can be considered to trust eachother, which may reduce the communication overhead of the aggregation protocol, and may be simpler compared to running an additional leader-election service. Note this is not about aggregating signatures for a commit, but aggregating the signatures at the level of a single validator to produce a single signature to be included in the commit. 

One potential concern is that we currently include timestamp in the message, which means they'd all need to co-ordinate on timestamp. It's possible to change the nodes so their timestamps are deterministic functions of the previous block's timestamp and the current round, but that's probably not good for getting an accurate time. If we remove timestamps from votes (#2840), this problem would go away. 

Also, if we eventually moved to aggregate the commit signatures as well, could the double aggregation cause an issue? 

cc @ValarDragon

**Comment by zmanian** [comment]
The need to have a signed message leader/proposer makes this infeasible IMO with coordination on time stamps.

If you remove timestamps from votes, we can leaderless systems and get this basically for free with BLS signatures.

**Comment by james-ray** [comment]
The author of this link:
https://blog.dash.org/bls-is-it-really-that-slow-4ca8c1fcd38e
states that the verification of bls signtures is much slower than ECDSA.

**Comment by james-ray** [comment]
> 
That’s 226ms for a block with 1000 signatures. It’s a significant improvement (more than 50% time saved), but it’s still not enough to compete with ECDSA.

> 
It is only halved, according to the analysis

>  Here verification costs are constant to 2 pairing operations regardless of the number of signatures being aggregated to a very large number

> 
I agree with this too, unless the 1000 group computations cost the time.

Anyway, I find it is off the topic here.
I see the problems here are about
1. whether or not signed on timestamps. If not, maybe we should adopt a proposer-based timestamp
2. could the double aggregation cause an issue?

I don't see a problem with the second issue, the two rounds votes are with different vote types in their signatures, and the message of the aggregated vote has a vote type too.
About the first one, I see there are lots of posts of issues discussing it. If we do  proposer-based timestamp mechanism,  we should let all nodes adjust the timer of the next new height if the time in this block is even after the commit time + commit timeout.

> 	if cs.CommitTime.IsZero() {
		// "Now" makes it easier to sync up dev nodes.
		// We add timeoutCommit to allow transactions
		// to be gathered for the first block.
		// And alternative solution that relies on clocks:
		//  cs.StartTime = state.LastBlockTime.Add(timeoutCommit)
		cs.StartTime = cs.config.Commit(tmtime.Now())
	} else {
		cs.StartTime = cs.config.Commit(cs.CommitTime)
	}

> 
We should judge, if cs.StartTime.Before( the time in the block)
         cs.StartTime = the time in the block

To let the nodes better coordinate their paces.

**Comment by james-ray** [comment]
How does Polka solve the time in the block? It should have the same issue, right?

**Comment by mrlp4** [comment]
We are developing documentation for our project [Cyberd](https://github.com/cybercongress/cyberd/tree/master) and i read description of The Cephalopod Equipment validator, and found that "2-of-3 multisig" is being used to operate validator. @ebuchman can you tell a little about it, mb any references to some code/doc's, cause i wasn't really able to find something useful about it.

**Comment by ebuchman** [comment]
That just refers to the cosmosvaloper key (ie. the key controlling the atoms and signing txa), not the cosmosconspub (ie. the key signing proposals and votes)

**Comment by hxrts** [comment]
not exactly what this issue calls for, but Polychain's threshold validator work is related: https://blog.polychainlabs.com/tendermint/2020/03/26/threshold-validator-for-tendermint.html

@jackzampolin didn't you also have a version of this?
