### ISSUE TITLE
D[2019-08-25|20:44:41.572] Consensus ticker  module=blockchain numPending=0 total=0 outbound=0 inbound=0

### ISSUE THREAD

**Issue by ying2025** [tendermint/tendermint#3917]
```
I[2019-08-25|20:44:39.544] Asserted all invariants                      module=invariants duration=1.094978ms height=0
I[2019-08-25|20:44:39.545] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[2019-08-25|20:44:39.545] Version info                                 module=node software=0.31.5 block=10 p2p=7
I[2019-08-25|20:44:39.545] This node is not a validator                 module=consensus addr=7D39B586084AC77E00B1EF7A6D6A4316684AEDC1 pubKey=PubKeyEd25519{28B0B2DF7F4B478C3B8A52DD477AFAAA21D91AFF8C7B9E4C1E2B90EC1314BAC8}
I[2019-08-25|20:44:39.559] P2P Node ID                                  module=p2p ID=0365626c17c2c9ec6fa747d4203cf049ad9c40f0 file=/home/zhr/.gaiad/config/node_key.json
I[2019-08-25|20:44:39.560] Starting Node                                module=node impl=Node
I[2019-08-25|20:44:39.561] Starting P2P Switch                          module=p2p impl="P2P Switch"
I[2019-08-25|20:44:39.561] Starting ConsensusReactor                    module=consensus impl=ConsensusReactor
I[2019-08-25|20:44:39.561] ConsensusReactor                             module=consensus fastSync=true
I[2019-08-25|20:44:39.561] Starting EvidenceReactor                     module=evidence impl=EvidenceReactor
I[2019-08-25|20:44:39.561] Starting PEXReactor                          module=pex impl=PEXReactor
I[2019-08-25|20:44:39.561] Starting AddrBook                            module=p2p book=/home/zhr/.gaiad/config/addrbook.json impl=AddrBook
I[2019-08-25|20:44:39.561] Starting MempoolReactor                      module=mempool impl=MempoolReactor
I[2019-08-25|20:44:39.561] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[2019-08-25|20:44:39.561] Starting BlockPool                           module=blockchain impl=BlockPool
I[2019-08-25|20:44:39.571] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2019-08-25|20:44:39.571] No addresses to dial nor connected peers. Falling back to seeds module=pex 
E[2019-08-25|20:44:39.571] Couldn't connect to any seeds                module=p2p 
I[2019-08-25|20:44:39.572] Starting RPC HTTP server on [::]:26657       module=rpc-server 
D[2019-08-25|20:44:40.572] Consensus ticker                             module=blockchain numPending=0 total=0 outbound=0 inbound=0
D[2019-08-25|20:44:40.573] Blockpool has no peers                       module=blockchain 
D[2019-08-25|20:44:41.572] Consensus ticker                             module=blockchain numPending=0 total=0 outbound=0 inbound=0
D[2019-08-25|20:44:41.572] Blockpool has no peers                       module=blockchain 
D[2019-08-25|20:44:40.572] Consensus ticker                             module=blockchain numPending=0 total=0 outbound=0 inbound=0
D[2019-08-25|20:44:40.573] Blockpool has no peers                       module=blockchain 
D[2019-08-25|20:44:41.572] Consensus ticker                             module=blockchain numPending=0 total=0 outbound=0 inbound=0
D[2019-08-25|20:44:41.572] Blockpool has no peers                       module=blockchain 
```

**Comment by melekes** [comment]
What is the issue here? Your node can't sync because there are no peers? How are you configuring the peers? Can you paste your config here?

**Comment by ying2025** [comment]
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://127.0.0.1:26658"

# A custom human readable name for this node
moniker = "bitcv"

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: leveldb | memdb | cleveldb
db_backend = "leveldb"

# Database directory
db_dir = "data"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "config/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "config/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = "localhost:6060"

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# The name of a file containing certificate that is used to create the HTTPS server.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_cert_file = ""

# The name of a file containing matching private key that is used to create the HTTPS server.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = ""

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "config/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

##### consensus configuration options #####
[consensus]

wal_file = "data/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "tendermint"

**Comment by ying2025** [comment]
`# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

##### main base config options #####

# TCP or UNIX socket address of the ABCI application,
# or the name of an ABCI application compiled in with the Tendermint binary
proxy_app = "tcp://127.0.0.1:26658"

# A custom human readable name for this node
moniker = "bitcv"

# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true

# Database backend: leveldb | memdb | cleveldb
db_backend = "leveldb"

# Database directory
db_dir = "data"

# Output level for logging, including package level options
log_level = "main:info,state:info,*:error"

# Output format: 'plain' (colored text) or 'json'
log_format = "plain"

##### additional base config options #####

# Path to the JSON file containing the initial validator set and other meta data
genesis_file = "config/genesis.json"

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "config/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "config/node_key.json"

# Mechanism to connect to the ABCI application: socket | grpc
abci = "socket"

# TCP or UNIX socket address for the profiling server to listen on
prof_laddr = "localhost:6060"

# If true, query the ABCI app on connecting to a new peer
# so the app can decide if we should keep the connection or not
filter_peers = false

##### advanced configuration options #####

##### rpc server configuration options #####
[rpc]

# TCP or UNIX socket address for the RPC server to listen on
laddr = "tcp://0.0.0.0:26657"

# A list of origins a cross-domain request can be executed from
# Default value '[]' disables cors support
# Use '["*"]' to allow any origin
cors_allowed_origins = []

# A list of methods the client is allowed to use with cross-domain requests
cors_allowed_methods = ["HEAD", "GET", "POST", ]

# A list of non simple headers the client is allowed to use with cross-domain requests
cors_allowed_headers = ["Origin", "Accept", "Content-Type", "X-Requested-With", "X-Server-Time", ]

# TCP or UNIX socket address for the gRPC server to listen on
# NOTE: This server only supports /broadcast_tx_commit
grpc_laddr = ""

# Maximum number of simultaneous connections.
# Does not include RPC (HTTP&WebSocket) connections. See max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
grpc_max_open_connections = 900

# Activate unsafe RPC commands like /dial_seeds and /unsafe_flush_mempool
unsafe = false

# Maximum number of simultaneous connections (including WebSocket).
# Does not include gRPC connections. See grpc_max_open_connections
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
# Should be < {ulimit -Sn} - {MaxNumInboundPeers} - {MaxNumOutboundPeers} - {N of wal, db and other open files}
# 1024 - 40 - 10 - 50 = 924 = ~900
max_open_connections = 900

# Maximum number of unique clientIDs that can /subscribe
# If you're using /broadcast_tx_commit, set to the estimated maximum number
# of broadcast_tx_commit calls per block.
max_subscription_clients = 100

# Maximum number of unique queries a given client can /subscribe to
# If you're using GRPC (or Local RPC client) and /broadcast_tx_commit, set to
# the estimated # maximum number of broadcast_tx_commit calls per block.
max_subscriptions_per_client = 5

# How long to wait for a tx to be committed during /broadcast_tx_commit.
# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.
# See https://github.com/tendermint/tendermint/issues/3435
timeout_broadcast_tx_commit = "10s"

# The name of a file containing certificate that is used to create the HTTPS server.
# If the certificate is signed by a certificate authority,
# the certFile should be the concatenation of the server's certificate, any intermediates,
# and the CA's certificate.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_cert_file = ""

# The name of a file containing matching private key that is used to create the HTTPS server.
# NOTE: both tls_cert_file and tls_key_file must be present for Tendermint to create HTTPS server. Otherwise, HTTP server is run.
tls_key_file = ""

##### peer to peer configuration options #####
[p2p]

# Address to listen for incoming connections
laddr = "tcp://0.0.0.0:26656"

# Address to advertise to peers for them to dial
# If empty, will use the same port as the laddr,
# and will introspect on the listener or use UPnP
# to figure out the address.
external_address = ""

# Comma separated list of seed nodes to connect to
seeds = ""

# Comma separated list of nodes to keep persistent connections to
persistent_peers = ""

# UPNP port forwarding
upnp = false

# Path to address book
addr_book_file = "config/addrbook.json"

# Set true for strict address routability rules
# Set false for private or local networks
addr_book_strict = true

# Maximum number of inbound peers
max_num_inbound_peers = 40

# Maximum number of outbound peers to connect to, excluding persistent peers
max_num_outbound_peers = 10

# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"

# Maximum size of a message packet payload, in bytes
max_packet_msg_payload_size = 1024

# Rate at which packets can be sent, in bytes/second
send_rate = 5120000

# Rate at which packets can be received, in bytes/second
recv_rate = 5120000

# Set true to enable the peer-exchange reactor
pex = true

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false

# Comma separated list of peer IDs to keep private (will not be gossiped to other peers)
private_peer_ids = ""

# Toggle to disable guard against peers connecting from the same ip.
allow_duplicate_ip = false

# Peer connection configuration.
handshake_timeout = "20s"
dial_timeout = "3s"

##### mempool configuration options #####
[mempool]

recheck = true
broadcast = true
wal_dir = ""

# Maximum number of transactions in the mempool
size = 5000

# Limit the total size of all txs in the mempool.
# This only accounts for raw transactions (e.g. given 1MB transactions and
# max_txs_bytes=5MB, mempool will only accept 5 transactions).
max_txs_bytes = 1073741824

# Size of the cache (used to filter transactions we saw earlier) in transactions
cache_size = 10000

##### consensus configuration options #####
[consensus]

wal_file = "data/cs.wal/wal"

timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"

# Make progress as soon as we have all the precommits (as if TimeoutCommit = 0)
skip_timeout_commit = false

# EmptyBlocks mode and possible interval between empty blocks
create_empty_blocks = true
create_empty_blocks_interval = "0s"

# Reactor sleep duration parameters
peer_gossip_sleep_duration = "100ms"
peer_query_maj23_sleep_duration = "2s"

##### transactions indexer configuration options #####
[tx_index]

# What indexer to use for transactions
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
indexer = "kv"

# Comma-separated list of tags to index (by default the only tag is "tx.hash")
#
# You can also index transactions by height by adding "tx.height" tag here.
#
# It's recommended to index only a subset of tags due to possible memory
# bloat. This is, of course, depends on the indexer's DB and the volume of
# transactions.
index_tags = ""

# When set to true, tells indexer to index all tags (predefined tags:
# "tx.hash", "tx.height" and all tags from DeliverTx responses).
#
# Note this may be not desirable (see the comment above). IndexTags has a
# precedence over IndexAllTags (i.e. when given both, IndexTags will be
# indexed).
index_all_tags = true

##### instrumentation configuration options #####
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = false

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = ":26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "tendermint"`

**Comment by ying2025** [comment]
`{
  "genesis_time": "2019-08-26T03:57:09.706159221Z",
  "chain_id": "bitcv",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age": "100000"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    }
  },
  "app_hash": "",
  "app_state": {
    "accounts": [
      {
        "address": "bac1kwr08f2lh365yfv082gfxq6y3g28e3g37kdr3w",
        "coins": [
          {
            "denom": "ubac",
            "amount": "100000"
          },
          {
            "denom": "ubcv",
            "amount": "1200000000000000"
          }
        ],
        "sequence_number": "0",
        "account_number": "0",
        "original_vesting": null,
        "delegated_free": null,
        "delegated_vesting": null,
        "start_time": "0",
        "end_time": "0"
      }
    ],
    "auth": {
      "coin_new_poll": {
        "total_generate": [
          {
            "denom": "ubac",
            "amount": "0"
          }
        ],
        "already_burn": [
          {
            "denom": "ubac",
            "amount": "0"
          }
        ]
      },
      "collected_fees": null,
      "params": {
        "max_memo_characters": "256",
        "tx_sig_limit": "7",
        "tx_size_cost_per_byte": "10",
        "sig_verify_cost_ed25519": "590",
        "sig_verify_cost_secp256k1": "1000"
      },
      "default_total_energy": {
        "denom": "energy",
        "amount": "100000000000000000000"
      }
    },
    "bank": {
      "send_enabled": true
    },
    "staking": {
      "pool": {
        "not_bonded_tokens": "1200000000000000",
        "bonded_tokens": "0"
      },
      "params": {
        "unbonding_time": "1814400000000000",
        "max_validators": 21,
        "max_entries": 7,
        "bond_denom": "ubcv"
      },
      "last_total_power": "0",
      "last_validator_powers": null,
      "validators": null,
      "delegations": null,
      "unbonding_delegations": null,
      "redelegations": null,
      "exported": false
    },
    "mint": {
      "minter": {
        "inflation": "0.130000000000000000",
        "annual_provisions": "0.000000000000000000"
      },
      "params": {
        "mint_denom": "ubac",
        "inflation_rate_change": "0.130000000000000000",
        "inflation_max": "0.200000000000000000",
        "inflation_min": "0.070000000000000000",
        "goal_bonded": "0.670000000000000000",
        "blocks_per_year": "4855015"
      }
    },
    "distr": {
      "fee_pool": {
        "community_pool": null
      },
      "community_tax": "0.020000000000000000",
      "base_proposer_reward": "0.010000000000000000",
      "bonus_proposer_reward": "0.040000000000000000",
      "withdraw_addr_enabled": true,
      "delegator_withdraw_infos": null,
      "previous_proposer": "",
      "outstanding_rewards": null,
      "validator_accumulated_commissions": null,
      "validator_historical_rewards": null,
      "validator_current_rewards": null,
      "delegator_starting_infos": null,
      "validator_slash_events": null
    },
    "gov": {
      "starting_proposal_id": "1",
      "deposits": null,
      "votes": null,
      "proposals": null,
      "deposit_params": {
        "min_deposit": [
          {
            "denom": "ubcv",
            "amount": "10000000"
          }
        ],
        "max_deposit_period": "172800000000000"
      },
      "voting_params": {
        "voting_period": "172800000000000"
      },
      "tally_params": {
        "quorum": "0.334000000000000000",
        "threshold": "0.500000000000000000",
        "veto": "0.334000000000000000"
      }
    },
    "crisis": {
      "constant_fee": {
        "denom": "ubcv",
        "amount": "1000"
      }
    },
    "slashing": {
      "params": {
        "max_evidence_age": "120000000000",
        "signed_blocks_window": "100",
        "min_signed_per_window": "0.500000000000000000",
        "downtime_jail_duration": "600000000000",
        "slash_fraction_double_sign": "0.050000000000000000",
        "slash_fraction_downtime": "0.010000000000000000"
      },
      "signing_infos": {},
      "missed_blocks": {}
    },
    "gentxs": [
      {
        "type": "auth/StdTx",
        "value": {
          "msg": [
            {
              "type": "cosmos-sdk/MsgCreateValidator",
              "value": {
                "description": {
                  "moniker": "bitcv",
                  "identity": "",
                  "website": "",
                  "details": ""
                },
                "commission": {
                  "rate": "0.100000000000000000",
                  "max_rate": "0.200000000000000000",
                  "max_change_rate": "0.010000000000000000"
                },
                "min_self_delegation": "1000000000000",
                "delegator_address": "bac1kwr08f2lh365yfv082gfxq6y3g28e3g37kdr3w",
                "validator_address": "bacvaloper1kwr08f2lh365yfv082gfxq6y3g28e3g3kmghr8",
                "pubkey": "bacvalconspub1zcjduepq23gs7tjr3q544tm2gne7p5m07tgc3fgj8dsh898u9frvvymxenfqpuh9ss",
                "value": {
                  "denom": "ubcv",
                  "amount": "1000000000000"
                }
              }
            }
          ],
          "fee": {
            "amount": null,
            "gas": "200000"
          },
          "signatures": [
            {
              "pub_key": {
                "type": "tendermint/PubKeySecp256k1",
                "value": "A6A+iq7rjub9lfHOCE89E/Q02sLcpAcoZgOLBGDjN+2C"
              },
              "signature": "3jOzYkhPqxOn+I2sZL8yJJs4xXtYI/vLcylL7U8EzU0b9EwgC12vZW36nY4CGweQpWsRj3xkzyMzfBJhmLdIfQ=="
            }
          ],
          "memo": "150acb66c1e8ae5baf22292c7f0169dc0d1b767c@192.168.209.142:26656"
        }
      }
    ]
  }
}
`

**Comment by melekes** [comment]
I don't see any seeds / persistent_peers. https://tendermint.com/docs/tendermint-core/using-tendermint.html#peers

**Comment by melekes** [comment]
How are you configuring the peers?

**Comment by ying2025** [comment]
No, I donnt set any peer

**Comment by ying2025** [comment]
I deploy in my owner testnet

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/63679262-89092800-c823-11e9-9fe8-cd5e84028013.png)

**Comment by ying2025** [comment]
![image](https://user-images.githubusercontent.com/28092539/63683259-7e9f5c00-c82c-11e9-998e-2db209e6d0ac.png)
I generategenesis.json by this way.

**Comment by melekes** [comment]
What guide are you following? 

This one https://cosmos.network/docs/cosmos-hub/deploy-testnet.html#deploy-your-own-gaia-testnet ?

**Comment by ying2025** [comment]
no, I generate genesis.json, and then directly start

**Comment by ying2025** [comment]
I once try this way, but it occure error when inspect invariance.

**Comment by ying2025** [comment]
I also try this way, then replace genesis.json, but it happend error

./gaiad init --chain-id=bitcv bitcv

./gaiacli keys add validator

./gaiad add-genesis-account $(./gaiacli  keys show validator -a) 1200000000000000ubcv,100000ubac

./gaiad gentx --name validator  --amount 1000000000000ubcv

./gaiad collect-gentxs 

./gaiad start


--set-min-gasPrices-- 0.0001ubac 0.000100000000000000ubac
-----NewHandler-----handleMsgWithdrawDelegatorReward---
panic: {"codespace":"sdk","code":9,"message":"account bac1kwr08f2lh365yfv082gfxq6y3g28e3g37kdr3w does not exist"}

goroutine 1 [running]:
github.com/bitcv-chain/bitcv/app.(*GaiaApp).initFromGenesisState(0xc000103400, 0x13b9320, 0xc00033d950, 0xc00007b300, 0xd, 0xc000277800, 0x13, 0x13, 0xc000303540, 0x1, ...)
	/home/zhr/gospace/src/github.com/bitcv-chain/bitcv/app/app.go:297 +0xda8
github.com/bitcv-chain/bitcv/app.(*GaiaApp).initChainer(0xc000103400, 0x13b9320, 0xc00033d950, 0xc00007b300, 0xd, 0x0, 0xed41b8270, 0x0, 0xc00003aef8, 0x5, ...)
	/home/zhr/gospace/src/github.com/bitcv-chain/bitcv/app/app.go:316 +0x18a
github.com/bitcv-chain/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000a35500, 0x0, 0xed41b8270, 0x0, 0xc00003aef8, 0x5, 0xc0000b5f80, 0x1e44ee0, 0x0, 0x0, ...)
	/home/zhr/gospace/src/github.com/bitcv-chain/cosmos-sdk/baseapp/baseapp.go:354 +0x2c1
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00007fec0, 0x0, 0xed41b8270, 0x0, 0xc00003aef8, 0x5, 0xc0000b5f80, 0x1e44ee0, 0x0, 0x0, ...)

**Comment by melekes** [comment]
Can you explain what the issue is?

**Comment by ying2025** [comment]
now it's this one
![image](https://user-images.githubusercontent.com/28092539/63695568-92a68600-c84b-11e9-98b8-f0b28d2f0e29.png)

**Comment by melekes** [comment]
If you're referring to "Couldn't connect to any seeds", then it's already fixed. Please upgrade to v0.32.2 where this error msg is only showed when there are seeds in the config.

**Comment by ying2025** [comment]
-------newPower--- 1000000 5E7321710621D9598369E5AAE6471298551A4112
----------WithdrawDelegationRewards---------- Validator
  Operator Address:           bacvaloper1kwr08f2lh365yfv082gfxq6y3g28e3g3kmghr8
  Validator Consensus Pubkey: bacvalconspub1zcjduepq23gs7tjr3q544tm2gne7p5m07tgc3fgj8dsh898u9frvvymxenfqpuh9ss
  Jailed:                     false
  Status:                     Bonded
  Tokens:                     1000000000000
  Delegator Shares:           1000000000000.000000000000000000
  Description:                {bitcv   }
  Unbonding Height:           0
  Unbonding Completion Time:  1970-01-01 00:00:00 +0000 UTC
  Minimum Self Delegation:    1000000000000
  Commission:                 rate: 0.100000000000000000, maxRate: 0.200000000000000000, maxChangeRate: 0.010000000000000000, updateTime: 2019-03-13 23:00:00 +0000 UTC
---rewards--- { 2}
---rewards.Rewards--current--  --rewards.Rw--  --val token-- 1000000000000
====historical===  2
----calculateDelegationRewardsBetween---  
=====rewards====== 
I[2019-08-26|02:58:22.334] Asserted all invariants                      module=invariants duration=2.697641ms height=0
I[2019-08-26|02:58:22.344] Completed ABCI Handshake - Tendermint and App are synced module=consensus appHeight=0 appHash=
I[2019-08-26|02:58:22.344] Version info                                 module=node software=0.31.5 block=10 p2p=7
I[2019-08-26|02:58:22.345] **This node is not a validator                 module=consensus addr=CB749489E3BFDC4E348B689E9DA279DA6C82D555 pubKey=PubKeyEd25519{5E78352EDDBC505D659452926B36C5EC742ED01B81FF01C7EE892567BFD87F9E}**
I[2019-08-26|02:58:22.477] P2P Node ID                                  module=p2p ID=842cf48d75e98de4f91018007436b991c8842e22 file=/home/zhr/.gaiad/config/node_key.json
I[2019-08-26|02:58:22.477] Starting Node                                module=node impl=Node
I[2019-08-26|02:58:22.490] Starting P2P Switch                          module=p2p impl="P2P Switch"
I[2019-08-26|02:58:22.490] Starting MempoolReactor                      module=mempool impl=MempoolReactor
I[2019-08-26|02:58:22.490] Starting BlockchainReactor                   module=blockchain impl=BlockchainReactor
I[2019-08-26|02:58:22.490] Starting BlockPool                           module=blockchain impl=BlockPool
I[2019-08-26|02:58:22.490] Starting ConsensusReactor                    module=consensus impl=ConsensusReactor
I[2019-08-26|02:58:22.490] ConsensusReactor                             module=consensus fastSync=true
I[2019-08-26|02:58:22.490] Starting EvidenceReactor                     module=evidence impl=EvidenceReactor
I[2019-08-26|02:58:22.490] Starting PEXReactor                          module=pex impl=PEXReactor
I[2019-08-26|02:58:22.490] Starting AddrBook                            module=p2p book=/home/zhr/.gaiad/config/addrbook.json impl=AddrBook
I[2019-08-26|02:58:22.491] Starting RPC HTTP server on [::]:26657       module=rpc-server 
I[2019-08-26|02:58:22.492] Ensure peers                                 module=pex numOutPeers=0 numInPeers=0 numDialing=0 numToDial=10
I[2019-08-26|02:58:22.493] No addresses to dial nor connected peers. Falling back to seeds module=pex

**Comment by ying2025** [comment]
and the public key is different
![image](https://user-images.githubusercontent.com/28092539/63736639-683de280-c8b6-11e9-9ebd-847982e1fd4d.png)

**Comment by ying2025** [comment]
I know why. The validator address is error, so it happend this problem.
