### ISSUE TITLE
Proto Compatibility Issues in C#

### ISSUE THREAD

**Issue by Felix0301** [tendermint/tendermint#3918]
I am building a decoder/encoder for tendermint in C#. It would be great to be able to reuse the existing proto files, however (having no previous experience with proto) I am running in the issue that gogo.proto is using proto2 and the other proto files use proto3 which is causing issues in compiling the files to C# classes (I found a compiler for proto2(3.0.0) and one for proto3 (3.9.1)but none that is compatible with both formats and files compiled by the different compilers are not compatible. 
The naming of "gogo.proto" seems to indicate that it should be used for go projects which I find confusing as I understood proto to be language agnostic.
Any suggestions on how I could best proceed?

Thanks in advance!

**Comment by melekes** [comment]
https://github.com/gogo/protobuf/issues/324#issuecomment-322800209

**Comment by melekes** [comment]
https://github.com/protocolbuffers/protobuf/issues/1133

**Comment by melekes** [comment]
Hey @Felix0301! We've been long discussing if we should drop `gogo.proto`. The benefit is removing boiler plate code that we'd need to write otherwise. The downside is, well you know now. Sorry for that. **The only solution seems to be removing all gogo related things from `.proto` files.**

**Comment by Felix0301** [comment]
Thank you for the Answers!
