### ISSUE TITLE
Add a checkTxLocal method in mempool interface

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#3919]
Our application is based on ethermint and Ethereum, each transaction is signed using secp256k and has three fields r,s,v, the signer of a transaction (More precisely, the signer's public key and the address) is computed from the three fields. I find the computation runs four times for each tx:
1. When the tx first arrive in Ethereum's txPool
2. When ethermint's receive tx routine call tendermint's mempool's checkTx, which will call back to ethermint's checkTx func 
3. When DeliverTx, the tx is rlp decoded, and is executed in etherem's EVM
4. When the commit of every block triggers recheckTx.   This is kind of a problem, I find 30000~40000 txs in mempool need about 8 seconds to finish the recheck.    We have extended the memPool size to 50000.

I see #3735 has added a type field in Request_CheckTx, there are two types:
CheckTx_New and CheckTx_Recheck.
So problem 4 is solved.

As for DeliverTx, the check and restore the signer is inevitable, unless the application adopt some cache mechanism, cache the txHash and the From it has already known. I think the cache mechanism is necessary because for recheck tx, the app needs to query the cache to skip the signature verification too.

As for problem 2, I think we can add a new type in  Request_CheckTx in order to let the application know this tx is triggered by itself  or ,    by receiving from peer or rpc interface called by client.
The application can just store the "From" of current handling tx. When it judges it is a checkTx from it own triggered, it can just fetch the "From", without checking the signature to restore the signer. And the "From" can be free from lock, because the receive tx routine waits for each response to start handling the next tx, there is no other routine reads or writes the "From".

**Comment by james-ray** [comment]
> func (tx *Transaction) AsMessage(s Signer) (Message, error) {
	msg := Message{
		nonce:      tx.data.AccountNonce,
		gasLimit:   tx.data.GasLimit,
		gasPrice:   new(big.Int).Set(tx.data.Price),
		to:         tx.data.Recipient,
		amount:     tx.data.Amount,
		data:       tx.data.Payload,
		checkNonce: true,
	}

	var err error
	msg.from, err = Sender(s, tx)
	return msg, err
}

func (tx *Transaction) AsMessageWithFrom(from common.Address) (Message, error) {
	msg := Message{
		nonce:      tx.data.AccountNonce,
		gasLimit:   tx.data.GasLimit,
		gasPrice:   new(big.Int).Set(tx.data.Price),
		to:         tx.data.Recipient,
		from:       from,
		amount:     tx.data.Amount,
		data:       tx.data.Payload,
		checkNonce: true,
	}

	return msg, nil
}

>

**Comment by james-ray** [comment]
I see in #3735 , it has already been concerned and refactored, thus the application does not need to open a new interface method, just judge the type in RequestCheckTx.
So this issue is irrelevant with abci interfaces now.

**Comment by melekes** [comment]
Is there a way to make this work without modifying the mempool interface? What about using `TxInfo` for this?

**Comment by melekes** [comment]
Also, see my comment here https://github.com/tendermint/tendermint/pull/3927#issuecomment-527355575

**Comment by james-ray** [comment]
> If anything, the flag should be CheckTxType_Local, so the app can skip signatures verification. Otherwise, if it's set to Remote, how would the app know if it should do so in case of the tx rechecking.

> 


In recheck, the code now has already pass the recheck type to the app, I paste the code below:

> for e := mem.txs.Front(); e != nil; e = e.Next() {
		memTx := e.Value.(*mempoolTx)
		reqRes := mem.proxyAppConn.CheckTxAsync(abci.RequestCheckTx{Tx: memTx.tx, Type: abci.CheckTxType_Recheck})
		r := reqRes.Response.GetCheckTx()
	

>

**Comment by melekes** [comment]
> And in receiving broadcasted tx, the code now pass the NEW which I modified to REMOTE type to the app:

right, you're essentially removed _New flag without actually removing it from abci/types.proto file.

**Comment by melekes** [comment]
> The TxInfo is not passed to app side, it is used for eliminate duplicate tx broadcasting, the app still doesn't know the coming tx is come from local, remote, or recheck (Now we have a way to let it know it comes from recheck)

I know what it's used for. But we can also use it to indicate the source of the tx (`app`, `rpc` or `p2p`) instead of adding `local bool` variable to CheckTx method

**Comment by james-ray** [comment]
>  you're essentially removed _New flag without actually removing it from abci/types.proto file.

> 
Maybe I forgot to commit this file

> we can also use it to indicate the source of the tx (app, rpc or p2p) instead of adding local bool variable to CheckTx method

> 
I see.   We can add a type field in the TxInfo?    The CheckTxWithInfo is a public method so the app can call it.

**Comment by ValarDragon** [comment]
I'm confused, it sounds like CheckTx in your application shouldn't be checking signatures, and mempool-level signature checks are all handled within Ethereum's tx pool. If so, why not just wrap CheckTx in your version of Ethermint and remove its signature check?

**Comment by james-ray** [comment]
There are three possibilities that a tx's first check signature in the application:
1. The tx is sent through web3j interface SendTransaction, and enters into Ethereum's tx pool, we can pass the verified "From" to ethermint, and ethermint can store it temporarily. When tendermint call the CheckTx in the app, it can fetch it as "the last From".   This is why I suggest we add a type in Request_CheckTx
2. The tx is received from other peers, in this case, its type should be REMOTE, and the application should verify the signer and store it to a cache
3. The tx is included in the block and the node has never seen the tx before. In this case, the application should verify and restore the signer, but it doesn't need to store it to cache. Because the same tx will never appear again.

When the tx comes with type RECHECK, the app should also query the cache.
The cache is a map, its key is tx's hash, the value is the "From", the signer.

**Comment by james-ray** [comment]
> and mempool-level signature checks are all handled within Ethereum's tx pool

> 
I am a little confused, does mempool check the tx's signature?  It is supposed to call the app's CheckTx to let the app do the checking, right?

**Comment by james-ray** [comment]
The thing is, the application could skip signature check, but it still needs some way to obtain a trusted signer address (E.g, we adopt the cache map that stores its own verified txhashs and signers, it definitely trusts its own results), the application will later use this signer address to do more checks, eg. whether this signer's nonce is sequential, whether its money is enough, etc...

**Comment by melekes** [comment]
Names suggested by Ethan make more sense to me (CheckTxType: Untrusted, Trusted, Recheck)

Also, not sure this case is popular enough to be included in the original repo. Have you thought about using a fork?

**Comment by ebuchman** [comment]
Is there some reason the tx needs to go through the eth txpool first? Afaik this isn't an issue in the latest version of Ethermint, and by eliminating this, it would relieve the need to make this change to CheckTx. Can you confirm? 

In general, we prefer to gather more evidence that a change is necessary supporting it. Thanks for understanding!

**Comment by james-ray** [comment]
@ebuchman  The reason is: The develops who are familiar with web3j interfaces, such as eth.sendTransaction, eth.sendRawTransaction, and the port 8545 of Ethereum RPC, are unwilling to change their developed codes to change to Tendermint abci functions.
I will check what the newest Ethermint is now, but I think they should not have blocked this way.

**Comment by ebuchman** [comment]
The new Ethermint exposes a fully web3 compatible API, so if I'm not mistaken it should solve this issue! https://github.com/chainsafe/ethermint

**Comment by james-ray** [comment]
Thanks for pointing to the road. I find the Cosmos has implemented a new Ethereum in Ethermint. 
But I am confused about the logic of not increasing nonce in CheckTx, which I have posted an issue on it.
I mean, letting the RPC implementation call CheckTx directly is OK, but it cannot implement exact the same logic about the nonce checking in Ethereum, for the CheckTx has only two results, success or fail, it cannot store the higher nonce tx temporally.

Anyway, since Tendermint has so close relationship with Cosmos and Ethermint, and Ethermint has already implemented like that, I think this issue can be closed.

But I might insist on using my old version Ethermint which uses TxPreEvent to receive the "ready to be executed" txs from Ethereum. I think this way is looser coupled with Ethereum, and the code of Ethereum can be updated along with the community.

**Comment by melekes** [comment]
> Anyway, since Tendermint has so close relationship with Cosmos and Ethermint, and Ethermint has already implemented like that, I think this issue can be closed.

Thank you for your understanding! And for your contributions to this project. Really appreciate it 🙏

**Comment by ebuchman** [comment]
> for the CheckTx has only two results, success or fail, it cannot store the higher nonce tx temporally

Not sure I understand this. It should defntly be possible to increment the nonce in CheckTx so that multiple dependent txs can be valid in the mempool. We do this in Cosmos-SDK apps like Gaia, so should be possible (if not done already) in Ethermint!

**Comment by james-ray** [comment]
I mean, we do can increment the nonce in CheckTx.
But in Ethereum, its txPool can store the higher nonce temporally, as I mentioned, suppose the current pending nonce is 5, the tx with nonce 9 can be accepted and stored, when 6,7,8,9 have come, the 9 goes to CheckTx.
Unless Ethermint implements a txPool just like this, 
But if it does implement a txPool like this, here comes the need for the Trusted Tx, we see not every tx that passed the check directly go to memPool.

**Comment by james-ray** [comment]
> not every tx that passed the check directly go to memPool.

> 

Or in another word, not every tx should directly go to CheckTx, we should see whether the nonce of the incoming tx is sequential with the pending nonce. And price is also a concern, we should promote the txs with higher price.
If these mechanisms are established, there could be some txs with higher nonce or low price that are temporally not available to go to CheckTx. So when they go to CheckTx, its signature has already been checked, and don't need to check it again, so called Trusted Txs.

**Comment by ebuchman** [comment]
Ah I see. Wouldn't that require another type of ABCI message then, like a stateless CheckTx? There's likely to be work this year on updating the mempool; input on the design would be welcome in the spec repo.
