### ISSUE TITLE
Should mempool support flow control?

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#3920]
Recently I was doing the performance test of our application based on Tendermint and ethermint, I find opening and closing the broadcast tx flag in mempool leads to significantly different results. If the broadcast tx flag is opened, the time of commit a block is much slower than the test that the flag is closed, and the mempool is easily get fully filled, though we have extended the mempool size to 50000.
I add some flow control code in the mempool reactor:

> 
  var next *clist.CElement
	flowLimitThreshold := memR.mempool.config.FlowControlThreshold
	remainingSpace := memR.mempool.config.Size - flowLimitThreshold
    for {
		// In case of both next.NextWaitChan() and peer.Quit() are variable at the same time
		if !memR.IsRunning() || !peer.IsRunning() {
			return
		}

		if memR.config.FlowControl {
			txsLen := memR.mempool.Size()
			if txsLen >= memR.mempool.config.Size {
				memR.Logger.Info("broadcastTxRoutine flowLimit due to mempool full", "sleepTime", memR.mempool.config.FlowControlMaxSleepTime)
				time.Sleep(memR.mempool.config.FlowControlMaxSleepTime)
			} else if txsLen > flowLimitThreshold {
				sleepTime := time.Duration(float64(txsLen-flowLimitThreshold) / float64(remainingSpace) * float64(memR.mempool.config.FlowControlMaxSleepTime))
				memR.Logger.Debug("broadcastTxRoutine flowLimit due to mempool exceeds threshold", "txsLen", txsLen, "threshold", flowLimitThreshold, "sleepTime", sleepTime)
				time.Sleep(sleepTime)
			}
		}

		// This happens because the CElement we were looking at got garbage
		// collected (removed). That is, .NextWait() returned nil. Go ahead and
		// start from the beginning.
		if next == nil {
			select {
			case <-memR.mempool.TxsWaitChan(): // Wait until a tx is available
				if next = memR.mempool.TxsFront(); next == nil {
					continue
				}
			case <-peer.Quit():
				return
			case <-memR.Quit():
				return
			}
		}

		memTx := next.Value.(*mempoolTx)

> 

the FlowControl flag, the FlowControlThreshold and FlowControlMaxSleepTime could be configured. 
When in flow control, the consensus messages such as NewRoundMessage, BlockPartMessage will have a higher priority to get broadcasted.

When we configure FlowControlThreshold to 10000, FlowControlMaxSleepTime to 8 seconds, the performance is almost the same with the test with broadcastTx closed.

Is this suitable for a feature in mempool reactor?

**Comment by melekes** [comment]
See https://github.com/tendermint/tendermint/issues/5796. It looks like we've made a situation worse by introducing batching in the mempool reactor.

We do have a flow control! Every reactor exposes a channel with a specified `Priority` (e.g. mempool reactor https://github.com/tendermint/tendermint/blob/6a056e050c6708fd0addbe557cd4c5cace3ea29e/mempool/reactor.go#L141), which is later used for prioritizing messages in `p2p/conn/connection.go` https://github.com/tendermint/tendermint/blob/6a056e050c6708fd0addbe557cd4c5cace3ea29e/p2p/conn/connection.go#L522.

But it looks like it does not work as expected and the consensus messages get significantly deprioritized.

So, we need to either fix it or switch to QUIC, which will get us independent streams for each `Reactor`.

**Comment by melekes** [comment]
@james-ray Sorry it took us so long to respond. We're always open to feedback 👂 If you have other thoughts on this matter, please write something in our Discord or comment in https://github.com/tendermint/tendermint/issues/5816.
