### ISSUE TITLE
Tendermint v0.32.2: Unable to access RPC endpoint

### ISSUE THREAD

**Issue by PradeepSalanki** [tendermint/tendermint#3922]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.32.2

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
Inaccessible RPC endpoint 

**What you expected to happen**:
RPC endpoint to be accessible via browser and curl.

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

Browser and curl output v0.31.7:

<img width="594" alt="browserTendermint31 7" src="https://user-images.githubusercontent.com/6400446/63690804-e2665c80-c80d-11e9-9a70-02da1e5e599a.png">

![curlTendermint31 7](https://user-images.githubusercontent.com/6400446/63690844-fe69fe00-c80d-11e9-8ac1-d4ff30e02d39.png)

Curl output v0.32.2:

![tendermintCurl32 2](https://user-images.githubusercontent.com/6400446/63690874-09bd2980-c80e-11e9-8365-3d6eb2a9e57f.png)

**Comment by PradeepSalanki** [comment]
Could it be because of the protobuf files not being updated for js-abci package (used as a dependency for ABCI App) to accommodate changes from v0.31.7 to v0.32.0?

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/master/UPGRADING.md#rpc-changes

**Comment by melekes** [comment]
Are u running tendermint inside a container / virtual machine?

**Comment by PradeepSalanki** [comment]
Yes, via docker and vagrant (again using docker container).

**Comment by melekes** [comment]
Could you paste your docker-compose.yml or Dockerfile here?

**Comment by melekes** [comment]
What's the output of `docker ps -a`?

**Comment by PradeepSalanki** [comment]
![TM32_2Docker](https://user-images.githubusercontent.com/6400446/63752901-53f7e680-c8b2-11e9-8e43-65fc33796ab7.png)

**Comment by melekes** [comment]
Could you paste your docker-compose.yml or Dockerfile here?

**Comment by PradeepSalanki** [comment]
I just use `docker run`:
docker run --detach --name=T01_tendermint --publish=26656:26656 --publish=26657:26657 --publish=26660:26660 --restart=always --volume=/path_to/tmdata:/tendermint tendermint/tendermint:v0.32.2 node --consensus.create_empty_blocks=false --proxy_app=tcp:
//ipaddress:26658

**Comment by marbar3778** [comment]
recently we switched from binding to 0.0.0.0 to localhost so it is not being exposed outside the container, you have to add --rpc.laddr tcp://0.0.0.0:26657 to change it

**Comment by PradeepSalanki** [comment]
@marbar3778 That helped. Thank you.
