### ISSUE TITLE
Subscriptions need to have IDs

### ISSUE THREAD

**Issue by mark-microtick** [tendermint/tendermint#3931]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Tendermint: 0.31.5
ABCI: 0.16.0
BlockProtocol: 10
P2PProtocol: 7

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Microtick / Cosmos SDK

**Environment**:
- **OS** (e.g. from /etc/os-release): Linux
- **Install tools**: N/A
- **Others**:

**What happened**:
Subscriptions over websocket should have IDs so they can be independently canceled, or in the case of an error, the subscriber should know which subscription got cancelled.

**What you expected to happen**:
We had to workaround this by opening up only one subscription per websocket connection, and have multiple connections when we needed independent subscriptions.

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
Error message for subscription disconnect is generic - open up a connection, subscribe to two different events, have one time out (Tendermint seems to close connections frequently if two of the same event happens in a single block because it thinks the client is not receiving messages fast enough)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
N/A

**Config (you can paste only the changes you've made)**:
N/A

**node command runtime flags**:
N/A

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by melekes** [comment]
We should add `subscription_id` field to the response upon `/subscribe`

**Comment by marbar3778** [comment]
closed via #6386
