### ISSUE TITLE
Badger throws error on Windows: require value log truncation on restart

### ISSUE THREAD

**Issue by Shivani912** [tendermint/tendermint#3954]
**Tendermint version** : 0.32.3

**ABCI app** : KVStore

**Environment**:
- **OS** : Windows 10
- **Install tools**: git

**What happened**: When restarting the app, it throws an error saying that it requires truncation of badger value log because it is corrupted. This seems to be an issue with badger DB and it is reported [here](https://github.com/dgraph-io/badger/issues/744). It solves the problem when you set the truncate value to true, but this obviously results in loss of data. I am not sure if this is a concern or not. However, it'd great if this could be documented for Windows users!

**Comment by melekes** [comment]
Thank you for reporting this! Do you want to add ^ to the docs?

**Comment by Shivani912** [comment]
Sure. I have created a [PR](https://github.com/tendermint/tendermint/pull/3974) for this. Thanks.
