### ISSUE TITLE
[Help] how to upgrade tendermint(v0.32.0) without stopping the world

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3955]
https://github.com/tendermint/tendermint/pull/3643
This pr cause a hard fork, which is very difficult for us to handle it:
1. How to do deal with the existed index data in DB? 
2. How to coordinate the app layer and the tendermint layer to use different deliver interfaces in different height?

@melekes @ebuchman  It will be helpfull, If you can share some experience or suggestions.

**Comment by melekes** [comment]
I thought https://github.com/tendermint/tendermint/pull/3643 was non-breaking for existing applications. Did you actually test it or just curious?

**Comment by melekes** [comment]
If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org) 💬
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint) 🧵
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚

**Comment by marbar3778** [comment]
I believe this was breaking, @alexanderbez can you confirm and can you think of any way this may possible?

One **possible** solution would be that at a certain height you change the tendermint version. kind of how the eth clients handle all the previous hardforks.

**Comment by guagualvcha** [comment]
we hope the community can give an upgrade solution

**Comment by guagualvcha** [comment]
you are right, It is not breaking.
