### ISSUE TITLE
[Bug/Security] query fails when calls are parallelized.

### ISSUE THREAD

**Issue by asmodat** [tendermint/tendermint#3962]
## Summary of Bug

Paralelizing of gaiacli queries result in following errors:

```
'panic: Error initializing DB: resource temporarily unavailable'.
```

calls sometimes fail and sometimes succeed. This is a bug in tendermint here I suppose: 

https://github.com/tendermint/tendermint/blob/master/libs/db/db.go#L51

Because it is trying to open new DB for reading always, it will fail regardless if something is being written or not. Even if you stop sync on the node and disconnect it, so nothing is being written, this will always fail.

IMO If cosmos full nodes that have exposed RPC then they can be effectively DOS'ed this way, to it should prop be fixed somehow.

## Version

`0.34.7`

## Steps to Reproduce

first

```
apt install python-pip
pip install joblib
#or
python3 -m pip install joblib
```
then save to `bug.py` and run following script with command `python3 ./bug.py`
```
import subprocess
import sys
from joblib import Parallel, delayed
from subprocess import Popen, PIPE
import json
import multiprocessing

def call(s, showErrors):
    try:
        p = Popen(s, shell=True, stdout=PIPE, stderr=PIPE, universal_newlines=True)
        o = p.stdout.readline().strip()
        err = p.stderr.readline().strip()
        j = json.loads(o)
        return j
    except Exception as e:
        pass
        if showErrors:
            if err is not None:
                print("Call failed with error: '" + str(err) + "'.")
            else:
                print("Call failed during output parsing: '" + str(e) + "'.")
        return None

chainId="cosmoshub-2"

jOperators = call("gaiacli query staking validators -o json --chain-id=" + chainId,True)

def query_spam(operator):
    address=operator["operator_address"]
    jDelegators = call("gaiacli query staking delegations-to " + address + " -o json --chain-id=" + chainId,True)
    print(jDelegators)

#https://joblib.readthedocs.io/en/latest/parallel.html
Parallel(n_jobs=2)(delayed(query_spam)(operator) for operator in jOperators)
```

You will get following error output:

```
...
None
Call failed with error: 'panic: Error initializing DB: resource temporarily unavailable'.
None
Call failed with error: 'panic: Error initializing DB: resource temporarily unavailable'.
None
[{'delegator_address': 'cosmos1qdxmyqkvt8jsxpn5pp45a38ngs36mn262pv46k', 'validator_address': 'cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9', 'shares': '1000000.000000000000000000'}, {'delegator_address': 'cosmos1pk7vf4ghkx38u8es22pqz7p7yfdh2xt3vpg5vd', 'validator_address': 'cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9', 'shares': '16000000.000000000000000000'}, {'delegator_address': 'cosmos1tcc6n0h8g7cnvttuzpu7q7hlg6qr3r0veqtep8', 'validator_address': 'cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9', 'shares': '100000.000000000000000000'}, {'delegator_address': 'cosmos1ec4xsrcwsumgzzmrrq0hjjy4r6xj9nvxlaznr5', 'validator_address': 'cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9', 'shares': '10000000.000000000000000000'}, {'delegator_address': 'cosmos16sv5dd4l4vcfeqt7rr43ql8542lylw22xkvtjm', 'validator_address': 'cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9', 'shares': '500000000.000000000000000000'}, {'delegator_address': 'cosmos1asf65e9qqafyd692d0sz5xq72ucrrrg92k3mdu', 'validator_address': 'cosmosvaloper1qdxmyqkvt8jsxpn5pp45a38ngs36mn2604cqk9', 'shares': '735960000.000000000000000000'}]
Call failed with error: 'panic: Error initializing DB: resource temporarily unavailable'.
None
Call failed with error: 'panic: Error initializing DB: resource temporarily unavailable'.
None
Call failed with error: 'panic: Error initializing DB: resource temporarily unavailable'.
None
Call failed with error: 'panic: Error initializing DB: resource temporarily unavailable'.
None
...
```
if you change `(n_jobs=2)` to `(n_jobs=1)` script above will work just fine.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by asmodat** [comment]
Note: I reported issues here in the past: https://github.com/cosmos/cosmos-sdk/issues/4532 but was told to move it to TM.

**Comment by alexanderbez** [comment]
Is the issue in Tendermint @asmodat? Has there been any progress made?

**Comment by melekes** [comment]
> Because it is trying to open new DB for reading always

whom are you referring to here? Tendermint maintains open connection to its databases.

**Comment by asmodat** [comment]
Well error was occurring here: https://github.com/tendermint/tendermint/blob/release/v0.31.4/libs/db/db.go#L51
no idea where this code was moved now, but the issue still persists.

You can easily reproduce by running the script provided.

**Comment by melekes** [comment]
Okay, so based on my findings, `goleveldb` does not support multiple connections to the same database. When you open a `goleveldb`, it creates a file lock https://godoc.org/github.com/syndtr/goleveldb/leveldb/storage#OpenFile and removes it only after you call `db.Close()`.

I don't know where is the code for `gaiacli query staking delegations-to` located exactly. If somebody (@alexanderbez, @fedekunze) could point me to it, that would be great. But I suspect there we try to open a database to query it, but I may be wrong.

**Comment by alexanderbez** [comment]
We only open the DB once AFAIK and that's when we execute `start`. You can find that [here](https://github.com/cosmos/cosmos-sdk/blob/master/server/start.go#L137). Also, it doesn't even seem that we close it during cleanup :-/

**Comment by melekes** [comment]
@asmodat I know it's been a while, but maybe you still have a larger stack trace from the above error?

**Comment by alessio** [comment]
We used to have the same problem with the old keybase implementation in the SDK. We came up with a keybase lazy load implementation as a mitigation to this, i.e. a connection would be opened when an op needed to be executed, then closed after.

**Comment by asmodat** [comment]
@melekes I can no longer reproduce the bug on latest gaia-13007, could be that this issue was patched somewhere along the road

cli version 2.0.0-rc1

**Comment by melekes** [comment]
Yeah, as per @alessio comment (https://github.com/tendermint/tendermint/issues/3962#issuecomment-579278799) it's been fixed in gaia.
