### ISSUE TITLE
[help] Is that validateId panic can be attacked by hackers?

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3965]
https://github.com/guagualvcha/tendermint/pull/1/commits/f05c2a95586cdad1940e3ee2869b213a4bdd3bde

Because it will panic if validateId return error, is that possible that other evil peers send me an invalid ID?

**Comment by melekes** [comment]
> Because it will panic if validateId return error, is that possible that other evil peers send me an invalid ID?

We only call `NewNetAddress()` if we're sure there will be no errors.

```
 rg -g "\!*/*_test.go" -B5 "NewNetAddress\("
p2p/transport.go
280-                    if err == nil {
281-                            secretConn, nodeInfo, err = mt.upgrade(c, nil)
282-                            if err == nil {
283-                                    addr := c.RemoteAddr()
284-                                    id := PubKeyToID(secretConn.RemotePubKey())
285:                                    netAddr = NewNetAddress(id, addr)
--
422-    }
423-
424-    // Reject self.
425-    if mt.nodeInfo.ID() == nodeInfo.ID() {
426-            return nil, nil, ErrRejected{
427:                    addr:   *NewNetAddress(nodeInfo.ID(), c.RemoteAddr()),
```

These are the only two cases where we call `NewNetAddress()`. 

(1) we get ID from pubKey, which we've validated before. we get addr from connection info, not from peer
(2) we get ID from already validated nodeInfo (`nodeInfo.Validate()` earlier call). we get addr from connection info, not from peer

**Comment by melekes** [comment]
If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org) 💬
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint) 🧵
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚
