### ISSUE TITLE
cli: commands for managing pubkeys and genesis files

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#397]
So we can simplify setting up a testnet: eg. https://github.com/tendermint/mintnet-kubernetes/blob/master/examples/counter/app.yaml#L132

**Comment by ebuchman** [comment]
maybe it helps with seeds too

**Comment by melekes** [comment]
how about a single command: `tendermint add_validator_to_genesis "[1, XXXXXXXXXXXX]" 10 mach0`?

**Comment by adrianbrink** [comment]
@melekes Is this still active?

**Comment by melekes** [comment]
I think so, yes.

**Comment by ebuchman** [comment]
Meh. I added `tendermint testnet` command. We can revisit if we want more specific things.
