### ISSUE TITLE
Can't find implementation of validRound/lockedRound (ensuring termination)

### ISSUE THREAD

**Issue by xixisese** [tendermint/tendermint#3971]
The termination mechanism is clarified in <The latest gossip on BFT consensus> paper. The consensus use validRound & lockedRound to solve it. When some process p already has a lockedRound information, the new proposal block will be only accepted iff the proposal validRound>=lockedRound. The algorithm is as follows:

```
upon ⟨PROPOSAL, h_p, round_p, v, vr⟩ from proposer(h_p, round_p) AND 2f + 1 ⟨PREVOTE, h_p, vr, id(v)⟩ while stepp = propose ∧ (vr ≥ 0 ∧ vr < round_p) do  
    if valid(v) ∧ (lockedRound_p ≤ vr ∨ lockedValuep = v) then 
        broadcast ⟨PREVOTE, h_p, round_p, id(v)⟩
    else
        broadcast ⟨PREVOTE, h_p, round_p, nil⟩
    stepp ← prevote
```

however, I didn't find any implementation of this part in the tendermint code.  shouldn't it be added?

**Comment by milosevic** [comment]
See https://github.com/tendermint/tendermint/blob/04d13d9945b904a11885a400506bcadc725eae0b/consensus/state.go#L900,  https://github.com/tendermint/tendermint/blob/04d13d9945b904a11885a400506bcadc725eae0b/consensus/state.go#L1477 and https://github.com/tendermint/tendermint/blob/04d13d9945b904a11885a400506bcadc725eae0b/consensus/state.go#L1615. In general you can search for use of validBlock to see how it's implemented. The protocol is not exactly the same as in spec (as aligning it would be costly with the current architecture) but the termination mechanism is the same.

**Comment by melekes** [comment]
If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://riot.im/app/#/room/#tendermint:matrix.org) 💬
- [create a topic on our forum](https://forum.cosmos.network/c/tendermint) 🧵
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚

**Comment by xixisese** [comment]
Thanks for the explain. 

I checked the code. The process only vote for lockedBlock if it's there.  And it clear the lockedBlock information when newer round of 2f+1 prevote information is collected, making it possible to vote for the latest validBlock from proposer.  so the termination is guaranteed

But the mechanism might cost more rounds comparing to the spec
In case the process didn't remove the lockedBlock information in time,  such as message delay etc.

**Comment by melekes** [comment]
@milosevic are there any actionable items here?
