### ISSUE TITLE
how to generate address and sign transaction?

### ISSUE THREAD

**Issue by simpleshark** [tendermint/tendermint#3977]
https://tendermint.com/rpc/
There is no interface for address generating,and transaction.
I want to make my own wallet.
Can you help me?

**Comment by ebuchman** [comment]
Tendermint is agnostic to applications and transaction formats. There is no notion of "account" or "wallet" in Tendermint itself. All of that is handled at the application layer. If you're interested in building cryptocurrency style application's in Go on Tendermint, see the [Cosmos-SDK](https://github.com/cosmos/cosmos-sdk)
