### ISSUE TITLE
Application should be able to set needProofBlock to control block generation

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#3979]
**Background:**
We've got on-demand block generation working now for the e-money ledger, but are jumping through hoops to not change the apphash, when state changes are made that we do not need to reach consensus on _immediately_. For now, we keep those state changes outside of the IAVL, but it increases the complexity unnecessarily for crash recovery etc.

One way to work around this would be to cache and return the same AppHash in the Cosmos-SDK ABCI EndBlock, but this seems kludgey and requires forking the SDK.

**Proposal:**
_Tendermint side:_
Drawing inspiration from PR https://github.com/tendermint/tendermint/pull/3118 it seems the most surgical way to approach this would be allowing the ABCI EndBlock to return a "needProofBlock". This would replace the existing the needProofBlock logic in Tendermint.

_Cosmos-SDK side:_
The needProofBlock bool could on the SDK side be carried around in the context. It would be initialized to false but set to true in modules that so desire.

**Comment by mdyring** [comment]
Yep, missed that one. It is a duplicate, but perhaps needProofBlock is a better name than "pause" mentioned in #1909. 

Is there any plans to implement this in the near future? It seems more and more chains are based on cosmos-sdk and I imagine the added flexibility with regards to block generation would be a welcomed addition.

**Comment by marbar3778** [comment]
#1909 was in the 0.33 milestone. Since it was closed, I will add this one to replace it.

**Comment by ebuchman** [comment]
Let's close this for #1909 ?

**Comment by mdyring** [comment]
Yep, added comment in #1909 about naming and some wishful thinking about when this might become available. :-)
