### ISSUE TITLE
Query block by hash

### ISSUE THREAD

**Issue by austinabell** [tendermint/tendermint#3985]
Query option or endpoint to allow querying block by hash? 

Feature would have a benefit for the project I'm working on, but not sure if this feature would be beneficial and desired for you guys as I can't think of many usable cases for this.

Let me know if this is intentionally left out or unwanted and I can just close this issue and do a workaround to achieve what I need.

**Comment by melekes** [comment]
Done in https://github.com/tendermint/tendermint/pull/4257
