### ISSUE TITLE
Conflicts on protobuf types

### ISSUE THREAD

**Issue by antho1404** [tendermint/tendermint#3986]
When including Tendermint in a code source that already uses proto and has similar types, some types are not registered because Tendermint already registers them.

More details here https://github.com/mesg-foundation/engine/issues/1236

To fix that all the proto definitions could be prefixed with a specific namespace, eg: `tendermint.types` instead of `types` to avoiding any conflicts.

**Comment by melekes** [comment]
Can't you put generated code in `tendermint_abci` package? I don't understand where about conflict comes from. Like if you combine all .proto files together (which contain duplicate types), then yes, it will rightfully fail. But if you generate Tendermint .proto files independently from XYZ .proto files, then there should be no conflict.

**Comment by antho1404** [comment]
I'm not doing anything with the proto, I'm using directly the go package (and cosmos sdk) so I don't build these proto.

My application already has its own types in gogoproto. We define these types on a type package and have one called `Event`. 
Because of that, gogoproto will register `types.Event` from ABCI [here](https://github.com/tendermint/tendermint/blob/7e0b64e8b0842d2f13c2b24feed13ec187be10f5/abci/types/types.pb.go#L3417) and `types.Event` from my application [here](https://github.com/mesg-foundation/engine/blob/3f4b289bad1482e7c298aa61ba949a75992dde56/event/event.pb.go#L66).

One of these proto messages cannot be registered as there is already one with the same name.

**Comment by melekes** [comment]
Makes sense now, thanks! Does this mean we should prefix all our types?

**Comment by antho1404** [comment]
That's the solution that we adopted to fix this issue here https://github.com/mesg-foundation/engine/pull/1337. 
I think that would be something really nice to have at the tendermint level too.

This might have some impacts on some libraries that generate some code based on the proto files so it might be a breaking change.

If that's fine, I can work on a pull request for that.

**Comment by melekes** [comment]
> If that's fine, I can work on a pull request for that.

Please do 🙇
