### ISSUE TITLE
panic: Unknown db_backend leveldb, expected either fsdb or goleveldb or memdb

### ISSUE THREAD

**Issue by shumy-tools** [tendermint/tendermint#4003]
**Tendermint version** 
$ tendermint version
0.32.3-22000c6a

**ABCI app**:
Not relevant.

**Environment**:
- **OS** Ubuntu 18

**What happened**:
$ tendermint node
panic: Unknown db_backend leveldb, expected either fsdb or goleveldb or memdb

$ cat ~/.tendermint/config.toml
```
# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

proxy_app = "tcp://127.0.0.1:46658"
moniker = "anonymous"
node_laddr = "tcp://0.0.0.0:46656"
seeds = ""
fast_sync = true
db_backend = "leveldb"
log_level = "error"
rpc_laddr = "tcp://0.0.0.0:46657"
```
$ cat ~/.tendermint/config/config.toml | grep db_backend
```
db_backend = "leveldb"
```

**What you expected to happen**:
To just run.

**Have you tried the latest version**: yes/no
no

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
goroutine 1 [running]:
github.com/tendermint/tm-db.NewDB(0xf11851, 0xa, 0xc000039960, 0x7, 0xc000344620, 0x1d, 0x400, 0x400)
	/home/micael/go/pkg/mod/github.com/tendermint/tm-db@v0.1.1/db.go:62 +0x3a1
github.com/tendermint/tendermint/node.DefaultDBProvider(0xc0008e8040, 0xc0008e8040, 0x18, 0xe45f40, 0x40da77)
	/home/micael/go/src/github.com/tendermint/tendermint/node/node.go:66 +0xcc
github.com/tendermint/tendermint/node.initDBs(0xc0000f7cc0, 0x1079c90, 0xc00013f068, 0x4139ef, 0xe45f40, 0xc000085cb0, 0xc0008e8020)
	/home/micael/go/src/github.com/tendermint/tendermint/node/node.go:207 +0x6c
github.com/tendermint/tendermint/node.NewNode(0xc0000f7cc0, 0x11a7340, 0xc0008e6140, 0xc0008dc100, 0x1191d60, 0xc000451bf0, 0xc0008dc370, 0x1079c90, 0xc0008dc380, 0x11ac040, ...)
	/home/micael/go/src/github.com/tendermint/tendermint/node/node.go:548 +0x50
github.com/tendermint/tendermint/node.DefaultNewNode(0xc0000f7cc0, 0x11ac040, 0xc00044fba0, 0xc00011a700, 0xc00013fc90, 0x18)
	/home/micael/go/src/github.com/tendermint/tendermint/node/node.go:112 +0x45f
github.com/tendermint/tendermint/cmd/tendermint/commands.NewRunNodeCmd.func1(0xc0000ced80, 0x1928a10, 0x0, 0x0, 0x0, 0x0)
	/home/micael/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:53 +0x5b
github.com/spf13/cobra.(*Command).execute(0xc0000ced80, 0x1928a10, 0x0, 0x0, 0xc0000ced80, 0x1928a10)
	/home/micael/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:698 +0x431
github.com/spf13/cobra.(*Command).ExecuteC(0x18ff100, 0x2, 0xc00044e140, 0xf2d7a1)
	/home/micael/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:783 +0x29f
github.com/spf13/cobra.(*Command).Execute(...)
	/home/micael/go/pkg/mod/github.com/spf13/cobra@v0.0.1/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x18ff100, 0x107a978, 0x2, 0xc00044de80)
	/home/micael/go/src/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
	/home/micael/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x24a

**Comment by melekes** [comment]
change `db_backend = "leveldb"` to `db_backend = "goleveldb"`

**Comment by shumy-tools** [comment]
That works.

**Comment by MDRezaulHasan** [comment]
Hi I have an error "**ERROR: error in config file: unknown mode: node**" when I am trying to run **tendermint init validator**. Can anyone help me for solving this issue?

**Comment by tessr** [comment]
@MDRezaulHasan can you open a new issue and fill out the issue template, please?

**Comment by marbar3778** [comment]
> Hi I have an error "**ERROR: error in config file: unknown mode: node**" when I am trying to run **tendermint init validator**. Can anyone help me for solving this issue?

you must be using master or a branch that doesnt default this. try tendermint init --mode validator

**Comment by MDRezaulHasan** [comment]
@tessr sure, I will open a new issue.

**Comment by MDRezaulHasan** [comment]
@marbar3778 , It is not working

**Comment by MDRezaulHasan** [comment]
> > Hi I have an error "**ERROR: error in config file: unknown mode: node**" when I am trying to run **tendermint init validator**. Can anyone help me for solving this issue?
> 
> Can you specify the version of tendermint, it also should automatically default to validator
tendermint version: unreleased-master-76c6c677341a2d1634c570e7d4ac14046f26bcdc
