### ISSUE TITLE
dynamic validators does not match address on restart

### ISSUE THREAD

**Issue by waeljammal** [tendermint/tendermint#4006]
**Tendermint version** 
0.32.3-45ddd67b

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
osx

**What happened**:

following the example form the persistent kv store example I start up 2 nodes as an example they register the validators fine and everything is in sync when I execute new transactions they get replicated between both nodes.

If I take down node 3 (dynamic one) and then commit another transaction to node 1 then restart node 3 I get the following error:

```
vote.ValidatorAddress (C2E1BCB4D584FEFFB9AB7873E4B9FCCB9B7D3320) does not match address (1DD1A25664456736B4DD3B087459F74F6D4D326A) for vote.ValidatorIndex (0)\nEnsure the genesis file is correct across all validators.: Invalid validator address"
```

I have the same issue with 3 and 4 nodes, if I take any of them down commit a new transaction and bring the node back up I experience this issue.

Is the genesis file the only way to keep the indexes in order for the Votes? I've been going through the code but have yet to find a way for me to keep the indexes in sync across the nodes without setting them all in genesis? I need to dynamically create/tear down nodes as it's a multi tenant system and need to automate scaling for each tenants cluster without taking it down.

Another thing I have noticed is that once the genesis file is loaded with the initial validator for that node it's never refreshed if I change it manually the validators just get loaded from the DB, is there a way to force a refresh of the genesis? If there is I can take advantage of that for force a refresh of all validators making sure they are sorted correctly.

**What you expected to happen**:

After transactions for adding a validator are committed I would expect a restarted node to catch up and not end up in the above state.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

Duplicate genesis file across 2 nodes with just initial 2 validators in each, start a third node that makes a request using the client to register the new node as a validator and dial the peer using UnsafeDialPeers to join the cluster. (This all works fine for me, no errors and data is kept in sync initially)

Shutdown the third node

Commit some transactions to one of the other 2 nodes

Start the third node back up and the issue occurs.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
D[2019-09-19|19:30:15.820] Receive                                      module=consensus src="Peer{MConn{127.0.0.1:6204} 74a890922084425431480cd756a755cd0c810a85 out}" chId=32 msg="[VSM23 7/00/2 F48D144F02AAB55A768807BFE7F8658EF3F07782DB091BFAE2C77CF0E6CA4499:1:EA27B80DACD3]"
D[2019-09-19|19:30:15.902] Receive                                      module=consensus src="Peer{MConn{127.0.0.1:6204} 74a890922084425431480cd756a755cd0c810a85 out}" chId=34 msg="[Vote Vote{0:C2E1BCB4D584 7/00/2(Precommit) F48D144F02AA 8C32F08E4462 @ 2019-09-19T18:11:56.233718Z}]"
D[2019-09-19|19:30:15.902] setHasVote                                   module=consensus peerH/R=9/0 H/R=7/0 type=2 index=0
D[2019-09-19|19:30:15.902] addVote                                      module=consensus voteHeight=7 voteType=2 valIndex=0 csHeight=7
I[2019-09-19|19:30:15.902] Error attempting to add vote                 module=consensus err="vote.ValidatorAddress (C2E1BCB4D584FEFFB9AB7873E4B9FCCB9B7D3320) does not match address (1DD1A25664456736B4DD3B087459F74F6D4D326A) for vote.ValidatorIndex (0)\nEnsure the genesis file is correct across all validators.: Invalid validator address"
```

**Anything else we need to know**:

The ValidatorIndex is always 0 never 1/2 does not matter which node I stop and start back up it's reported as not matching 0.

If I don't commit any new transactions and just start the third node back up and then do a transaction it works fine. It only breaks if the node is offline then you perform a transaction and bring it back up then it has this issue.

Would be handy is there was some better examples around dynamically joining/leaving a cluster, maybe even discovery and registration using a blank genesis file with just the initial validator for that node so it can start up, useful for external orchestration services to spin up and scale up/down a cluster.

Maybe some info on how to replace the genesis state in the DB, the db and its api are private as far as I can tell. It creates the DB loads the file inside New.

**Comment by melekes** [comment]
> is there a way to force a refresh of the genesis?

no, but you can add & remove validators by passing `ValidatorUpdates` in `EndBlock` response https://docs.tendermint.com/master/spec/abci/abci.html#endblock

**Comment by melekes** [comment]
> start a third node that makes a request using the client to register the new node as a validator and dial the peer using UnsafeDialPeers to join the cluster.

Does the third node has the same genesis file nodes (1) and (2) have?

**Comment by melekes** [comment]
Closing due to no response.

**Comment by melekes** [comment]
Can't replicate 😥 

> Would be handy is there was some better examples around dynamically joining/leaving a cluster, maybe even discovery and registration using a blank genesis file with just the initial validator for that node so it can start up, useful for external orchestration services to spin up and scale up/down a cluster.

Agree! Maybe we can write a post covering our `persistent_kvstore` example application and how it handles validator updates. Or explain how it happens in Cosmos-SDK.

I thought what we have right now is enough to understand the basics, but more docs is always good.

- https://docs.tendermint.com/master/app-dev/app-development.html#endblock
- https://docs.tendermint.com/master/spec/abci/abci.html#endblock

**Comment by melekes** [comment]
I'm going to close this. Please drop a comment here if it's still an issue or anybody else reading this having a similar problem.

And sorry it took us so long to reply. Stay safe 🙏
