### ISSUE TITLE
`block_results` method missing in `tendermint lite`

### ISSUE THREAD

**Issue by tomtau** [tendermint/tendermint#4008]
`tendermint lite` proxy command exposes most JSON-RPC methods, but doesn't expose `block_results`

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.32.3-0ad70fb6

**Comment by tomtau** [comment]
It may be a cause of https://github.com/tendermint/tendermint/issues/3916 ?

**Comment by melekes** [comment]
`block_results` is implemented in new `lite2` package.

Old `lite` client and package should not be used. It's insecure and contains multiple bugs.
