### ISSUE TITLE
windows: config generates invalid paths

### ISSUE THREAD

**Issue by srinathLN7** [tendermint/tendermint#4011]
When running a simple `tendermint node --proxy_app=kvstore` on Windows 10 machine, I get the following error: 

![Capture](https://user-images.githubusercontent.com/45759699/65441039-fc558800-de29-11e9-98df-b170b8e9d1dd.PNG)

Can someone please tell me how to resolve this? Looks like some insufficient permission.

**Comment by melekes** [comment]
Filepaths do not seem to account for Windows. Should be something like `C:\Users\username\.tendermint\data\...`

**Comment by melekes** [comment]
What's the values of `priv_validator_key_file` and `priv_validator_state_file` in `config.toml`?

**Comment by lnandakumar** [comment]
In `config.toml`, I find these
`priv_validator_key_file = "config\\priv_validator_key.json"`
`priv_validator_state_file = "data\\priv_validator_state.json"`

**Comment by melekes** [comment]
Try setting them to 

```
priv_validator_key_file = "C:\Users\{YOUR_USERNAME}\.tendermint\config\priv_validator_key.json"
priv_validator_state_file = "C:\Users\{YOUR_USERNAME}\.tendermint\data\priv_validator_state.json"
```

**Comment by lnandakumar** [comment]
Thank you for your response. However, it throws the following error:

`ERROR: While parsing config: (44, 17): unfinished unicode escape`

**Comment by melekes** [comment]
Can you paste exact values you've provided here?

**Comment by lnandakumar** [comment]
This is the value I provided:
`priv_validator_key_file = "C:\Users\lakshminarayanan.nan\.tendermint\config\\priv_validator_key.json"`
`priv_validator_state_file = "C:\Users\lakshminarayanan.nan\.tendermint\data\\priv_validator_state.json"`
`genesis_file = "C:\Users\lakshminarayanan.nan\.tendermint\config\\genesis.json"`
`node_key_file = "C:\Users\lakshminarayanan.nan\.tendermint\config\\node_key.json"`

I even tried replacing double quotes `"` with `'` as per TOML `literal strings` data structure but that is returning consenus failure again.

**Comment by tessr** [comment]
This would be a great issue for a contributor working with Windows, so I've added the "good first issue" tag. (The core team doesn't work with Windows, and though we're happy to try to help, we can't make any Windows support guarantees.)
