### ISSUE TITLE
block query with 0 height fails through RPC client interface

### ISSUE THREAD

**Issue by austinabell** [tendermint/tendermint#4014]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): v0.32.2 but exists on master as well

**What happened**: Querying for block with height 0 returned error through RPC client interface

**What you expected to happen**: Should return current block height as indicated by docs and through manual tendermint queries.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): query block height through rpc client with a value 0

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: "Block: response error: RPC error -32603 - Internal error: Height must be greater than 0"

Sorry I didn't fill out all of the fields, I just see the issue in code [here](https://github.com/tendermint/tendermint/blob/v0.32/rpc/core/blocks.go#L409) and it should only reject less than 0, and latest query does work when passing nil for the pointer into the block query.

**Comment by melekes** [comment]
Can't replicate.

```
$ curl http://localhst:26657/block_results
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "height": "85",
    "results": {
      "deliver_tx": null,
      "end_block": {
        "validator_updates": null
      },
      "begin_block": {}
    }
  }
}
```

```
$ curl http://localhst:26657/block_results?height=0
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Height must be greater than 0"
  }
}
```

**Comment by austinabell** [comment]
My apologies, I just retested and the manual queries does return this as well. Is this intended to stay this way? The documentation [here](https://tendermint.com/rpc/#/Info/block) states that querying with 0 queries latest block.

**Comment by melekes** [comment]
Thanks for pointing this out! I don't have a strong opinion on this, but we should either a) update the docs OR b) update the code

**Comment by ebuchman** [comment]
Probably a docs fix on this one.
