### ISSUE TITLE
Should we punish the Byzantine voters when the chain does fork?

### ISSUE THREAD

**Issue by james-ray** [tendermint/tendermint#4015]
Currently, we only punish the voter if it sends different votes in a same round. We don't punish the node's prevote that does not match its previous precommit for a block. Though this saves extra cost verifying each prevote, if the chain does fork, which means if there really are two
different n-f precommits for two different blocks in two chains, there are no punishment for the Byzantine voters that violate their commitment to fork the chain.
A more responsible punishment mechanism can be done as follows:
1. When we find the chain forks, we should interrogate each voter in the intersection of the two precommit sets why it does so.
2. If we can find or it can provide a PoLC that is for the committed block of higher height, we turn to interrogate the voters in the intersection of this set and the lower precommit set.
3. If the voters in this set fail to provide a PoLC of which the height is greater than the lower committed height and less than its vote height for the higher committed block in some configured heights (e.g, 100 blocks), they are going to be punished.
Note that they should be punished in both chain forks.

No matter you committed which block, you should not change your decision, the chain has already forked, and we don't rollback, otherwize Byzantine nodes will send out previous precommts to arbitrarily rollback the chain. We just need to punish the voters which send the malicious prevotes that cause the fork.

As for the implementation, I think the interrogation and response can be done in the block, once you have received 2/3+ precommits for another block on a different chain, you include this set and your local set in the block, the intersection of the two precommit sets is as an "interrogated set", then we select subsequent block proposers from this set to give each of them a chance to provide PoLC of a lower round, the intersection of the PoLC set and the lower precommit set is  a new "interrogated set".  If the round of the included "interrogated set" is the lower commited round + 1,  and it is a prevote set, the voters in the intersection of this set and the lower precommit set are definitely guilty, and we can punish them immediately.

**Comment by ebuchman** [comment]
Thanks @james-ray - I believe these concerns are covered by some other issues, namely #3244, #1466, and #200, though you've done a nice job of outlining things here. Do you think we could consolidate these issues better? 

Also, have you seen the spec: https://github.com/tendermint/tendermint/blob/master/docs/spec/consensus/fork-accountability.md

**Comment by ebuchman** [comment]
Also https://github.com/tendermint/spec/pull/55

**Comment by melekes** [comment]
Closing in favor of https://github.com/tendermint/tendermint/issues/4189.
