### ISSUE TITLE
A consensus state test case may be wrong(?)

### ISSUE THREAD

**Issue by sangche** [tendermint/tendermint#4020]
Run consensus state test case [TestStateLockPOLRelock](https://github.com/tendermint/tendermint/blob/134fe2896275bb926b49743c1e25493f6b24cc31/consensus/state_test.go#L494) with a modification, changing line [571](https://github.com/tendermint/tendermint/blob/134fe2896275bb926b49743c1e25493f6b24cc31/consensus/state_test.go#L571) to:

`signAddVotes(cs1, types.PrevoteType, propBlockHash, propBlockParts.Header(), vs3, vs4)`

Test result: Pass OK

Expected: Test fail because the modified code does not compose majority voting

This indicates that either consensus state code or test code has bug(?)

For more description, please see [here](https://as2.netlify.com/190901-tendermint-test-relock)

**Comment by melekes** [comment]
So the solution here seems to be renaming `TestStateLockPOLRelock` to `TestStateLockPOLRelockSameBlock` and writing additional `TestStateLockPOLRelockDifferentBlock` test, correct? @sangche want to contribute?

**Comment by sangche** [comment]
I'd love to contribute. 
IMHO, the suggested name `TestStateLockPOLRelockDifferentBlock` does not seem to be suitable,
because `relock` does not happen to different block.

**Comment by melekes** [comment]
You can pick a different name 😉

**Comment by sangche** [comment]
My point is that, the test implementations in `consensus/state_test.go` fail to conform to the test senario(described in the comment area of the source code), because [func decideProposal(...)](https://github.com/tendermint/tendermint/blob/e0248053546bcc29df459defa416aa5387c46637/consensus/common_test.go#L151)
in `consensus/common_test.go` returns always the same block at any round of a given height.

This is root of the problem and affects all test cases in this test suite.

For example,

Replacing [line 575](https://github.com/tendermint/tendermint/blob/e0248053546bcc29df459defa416aa5387c46637/consensus/state_test.go#L575) in `consensus/state_test.go` with:
```
validatePrecommit(t, cs1, round, round, vss[0], theBlockHash, theBlockHash)
```
and run result: pass. Expected: fail


Replacing [line 836](https://github.com/tendermint/tendermint/blob/e0248053546bcc29df459defa416aa5387c46637/consensus/state_test.go#L836) 
```
validatePrevote(t, cs1, round, vss[0], propBlockHash0)
```
and run result: pass. Expected: fail
