### ISSUE TITLE
Change the statically defined data path to changeable value from $home/data to $home/$data 

### ISSUE THREAD

**Issue by jeehonglee** [tendermint/tendermint#4026]
Change the statically defined data path to changeable value from $home/data to $home/$data.
When you considering running blockchain system on K8S(Orchestration), it should be configurable value)
## Summary
Change the statically defined data path to changeable value from $home/data to $home/$data.
When you considering running blockchain system on K8S(Orchestration), it should be configurable value)

## Problem Definition
Currently, the `data` path belongs to `home path` but I think it is not good approach when we considering orchestrating Tendermint on K8S.
Because of the  `data` path is hard-coded based on $home path, It is challenging to make as the stateful application on K8S or any other orchestration engine
If we can make a `data` path like other `home` variable(from the environment and configurable), we can orchestrate Tendermint based blockchain system more easily and I think there is no disadvantage.

## Proposal
<img width="599" alt="Screen Shot 2019-10-01 at 12 07 23 PM" src="https://user-images.githubusercontent.com/54184935/65931433-8b732900-e444-11e9-9447-66eb8ee973a6.png">
e.g) , TO-BE
<img width="776" alt="Screen Shot 2019-09-26 at 4 03 50 PM" src="https://user-images.githubusercontent.com/54184935/65665761-42ebf200-e077-11e9-9caf-6d70b6101949.png">

**Comment by melekes** [comment]
I think if you provide full path (`/var/yourproject/data`), TM will use it.

**Comment by jeehonglee** [comment]
> I think if you provide full path (/var/yourproject/data), TM will use it.

Thanks for the answer .. :) @melekes
But I haven't found any code to replace `dataDir` with any other value. Can you ask me how to set the value of the environment variable to `dataDir`, and the relevant code or explanation?

**Comment by melekes** [comment]
https://tendermint.com/docs/tendermint-core/configuration.html

```
db_dir = "/var/yourproject/data"
```

**Comment by melekes** [comment]
We probably need to clarify ^ in the docs https://tendermint.com/docs/tendermint-core/configuration.html#options

```
# Database directory
db_dir = "data"
```

**Comment by jeehonglee** [comment]
Thank so much! @melekes 
I will try it!
