### ISSUE TITLE
/dial_seeds should return evidence that it's working

### ISSUE THREAD

**Issue by pdobacz** [tendermint/tendermint#403]
One can crash the node instance using the `dial_seeds` endpoint.

Using tendermint `v0.8.0`. Run node with `--proxy_app dummy`

Then doing `curl --data-urlencode "seeds=[\"127.0.0:46656\"]" http://localhost:46657/dial_seeds` (note typo in IP) gives output:
```
{"jsonrpc":"2.0","id":"","result":[34,{}],"error":""}
```
and
```
panic: Paniced on a Sanity Check: lookup 127.0.0: invalid domain name
```
crash of a node.

Other thing is that the response from the RPC is exactly the same on both successful dials and unsuccessful dials that do not crash (for instanc dialing self), which is a bit confusing.

**Comment by ebuchman** [comment]
Thanks for this! This endpoint is marked internally as Unsafe but for other reasons (ie. it could force you to dial bad seeds). Obviously we need to be sanitizing those addresses - is this something you'd be willing to take a shot at?

I hear you on the error thing - the trouble is that we spawn go-routines to do the dialing, so if we want the errors, we'd have to hang around and wait for the dialing to finish ... maybe we can have a `dial_seeds_async` and `dial_seeds_sync` for the cases where you don't want to wait and where you do?

**Comment by pdobacz** [comment]
>  is this something you'd be willing to take a shot at?
eh, I am afraid it's not on the top of the list, right now. The unfortunate reason is that it actually works, if one doesn't typo :). Nevertheless, I hope the issue is useful for future reference.

> maybe we can have a dial_seeds_async and dial_seeds_sync
This could eventually prove useful. But for the sake of this issue I'd say just return a "Success: dialing xyz in progress..."-kind-of response in cases when failure is not immediately evident (typos/self-dial etc). That is, a response that one has successfully started the dialing process

**Comment by ebuchman** [comment]
DialSeeds no longer panics but neglected to improve the response. Marked for 0.9.1
