### ISSUE TITLE
docs: `/dial_peers` is missing from `rpc/swagger.yaml`

### ISSUE THREAD

**Issue by folex** [tendermint/tendermint#4047]
I can't find doc on `/dial_peers` endpoint in https://tendermint.com/rpc/

**Comment by marbar3778** [comment]
A switch to something along the lines of https://github.com/swaggo/swag would help in avoiding these things.

**Comment by melekes** [comment]
Can't find them in https://tendermint.com/rpc/

**Comment by marbar3778** [comment]
it is in the swagger file but not reflected online, pinged the docs team, but we can close this issue for now
