### ISSUE TITLE
Tendermint installation: `make tools` returns permission denied 

### ISSUE THREAD

**Issue by lnandakumar** [tendermint/tendermint#4048]
I am running Xubuntu on a Windows 10 VM. When I run the command
`make tools`  I get the following error

![image](https://user-images.githubusercontent.com/45759699/66489058-4b005480-eaaf-11e9-9cd0-307ef38df228.png)

Any suggestions on how to resolve this would be immensely appreciated?

**Comment by melekes** [comment]
https://support.microsoft.com/en-us/help/2623670/access-denied-or-other-errors-when-you-access-or-work-with-files-and-f
