### ISSUE TITLE
`rpcclient` resolve https protocol to http

### ISSUE THREAD

**Issue by xiaoxiaff** [tendermint/tendermint#4051]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
github.com/tendermint/tendermint v0.32.5

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
When we set up a rpc client, we set node url to "https://fullnode.lino.network:443" then call NewHTTP function:
```
import (
	rpcclient "github.com/tendermint/tendermint/rpc/client"
)

rpc := rpcclient.NewHTTP("https://fullnode.lino.network:443", "/websocket")
```

In tendermint rpc lib it will be parsed to `http://fullnode.lino.network:443` which will fail the rpc call with error `ABCIQuery: error unmarshalling rpc response: invalid character '<' looking for beginning of value`

**What you expected to happen**:
Protocol should be parsed to https.

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:
Code causes the issue: https://github.com/tendermint/tendermint/blob/v0.32.6/rpc/lib/client/http_client.go#L87

**Comment by melekes** [comment]
We should add `rpcclient.NewHTTPS` and return an error if HTTPS is passed [here](https://github.com/tendermint/tendermint/blob/v0.32.6/rpc/lib/client/http_client.go#L87)

@xiaoxiaff thanks for pointing this out!

**Comment by githubsands** [comment]
Hey guys can you assign me to this issue?

Thanks

**Comment by melekes** [comment]
We can only assign people from Tendermint org, but you can help us fix ^ nevertheless.

**Comment by githubsands** [comment]
Sounds good

**Comment by pasDamola** [comment]
hi @melekes, could you point me to where the **NewHTTP** function is?

**Comment by pasDamola** [comment]
hi @xiaoxiaff @melekes please could you point me to where the **NewHTTP** function is?

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/98c595312af02037843b8fe74f0ee0625665448e/rpc/client/httpclient.go#L89

please use one the available code searching tools (e.g. https://github.com/ggreer/the_silver_searcher) or use Github search https://help.github.com/en/github/searching-for-information-on-github/searching-code next time. Spare our time

**Comment by pasDamola** [comment]
hi guys, so how do i test my solution to check if it works

**Comment by pasDamola** [comment]
hi @melekes i need further explanation on how to reproduce the error, its not really clear and how also would i test my solution also

**Comment by pasDamola** [comment]
ooh thanks @melekes @xiaoxiaff , i've been trying to reproduce this issue, haven't found how to do that yet. The explanation given above is not clear enough for me. Thank you

**Comment by yenkhoon** [comment]
@meleks may i know why is the line 87(https://github.com/tendermint/tendermint/blob/v0.32.6/rpc/lib/client/http_client.go#L87) overwrite http and https to tcp?

**Comment by melekes** [comment]
because net.Dial requires it https://github.com/tendermint/tendermint/blob/c4ba93a1e6d62b480adb178bb0f9c8d5c6f67717/rpc/lib/client/http_client.go#L107
