### ISSUE TITLE
Send ChainID in all requests to ABCI Host

### ISSUE THREAD

**Issue by KrishnaPG** [tendermint/tendermint#4058]
Currently, `ChainID` is sent only for `BeginBlock` method. Other methods either presume the ID or operate under the assumption of single Tendermint Node per single ABCI host (one-to-one mapping between ABCI Host and Tendermint node).

Sending the `ChainID` in all requests allows the ABCI host to enable `multi-tenancy`, wherein 

- multiple Tendermint Nodes can share the same ABCI host. This makes it possible to run "light weight" tendermint nodes, where the costly app calculations can be shared/abstracted out as SaaS model cluster **where needed** (currently every node has to repeat the app calculations, whether they like it or not). For example, multiple tendermint nodes running on individual laptops, each pointing to the same ABCI proxy app running on, say AWS or Azure.
- Removes the duplication of app state storage for nodes, when they chose to use the same ABCI proxy app. This allows, for example, ABCI Host to provide the app state as a, say backed by a clustered DB, that is shared by the nodes, if they want to. 
- ABCI host app (calculations and the storage) can scale independent of the tendermint node
- In private or hybrid chain models, forcing the ABCI proxy code to be centralized, enforces the security (eliminating the possibility of corrupt ABCI app code usage by individuals), while still allowing distributed tendermint state validations and nodes. Reduced attack surface.

Those that want to run one ABCI app per Tendermint node, can still run in one-to-one mode as happens today. But, if someone wants to design a multi-tenant app (such as sidechains), where tendermint Nodes that belong to different blockchains talking to the same proxy app, they can do so easily by tracking the `ChainID` (currently, it is not possible), making it truly stateless.

**Comment by melekes** [comment]
I wonder if this is the only change needed to support one-ABCI-to-many-TM case.

**Comment by KrishnaPG** [comment]
Looks like the separation between ABCI-App and TM seems to be cleanly abstracted out into the ABCI message interfaces, which appear to be stateless. 

From the current ABCI-Spec, it looks like the exact identity of TM-node is irrelevant for the functionality of ABCI-App or TM-node.

Unless there are some implicit assumptions that are currently unknown, sending the ChainID seems to be enough to let the ABCI-App know for which Chain (and the respective state) it should perform the requested state transformation operations. The exact identity of TM-node, once again is irrelevant, as is the current case.

However, one concern here, which is not a new concern but gets carried on from the existing specs, is:

- how do you prevent malicious actors that are pretending to be valid TM-nodes, connecting to the ABCI-App and sending bad data into it that may affect the app-state?

This brings up the question of authenticating the TM-nodes, which may have to be carried out, externally, at the infra-level, such as certificates that share the same common root or allow only nodes that belong to the same subnet, etc., which are easy to achieve through existing infrastructure mgmt tools

This kind of authentication also makes it possible to achieve another of our requirements: 
- the converse:  many-ABCI-to-one-TM

This is particularly useful for some of our customers where the individual state is kept private, but the shared state is offered as SaaS. For example,

- individuals running their own ABCI-App each on their own laptops, which manages their private app state on their laptops (possibly with their own local backups)
- all laptops connected to same TM-node (/ cluster) on AWS/Azure, sharing the public state, without exposing the private app-state data

The way TM-node currently initiates the connection to ABCI-App, this _many-ABCI-to-one-TM_ may not be that straightforward to achieve - but with a proxy between the multiple ABIC-Apps and the one TM-Node this may be worked out. However, it needs _one_ single TM-Node to be capable of handling proposals for _multiple chains_ from the users and passing the respective ChainID to the correct ABCI-app on the correct laptop (routed by the middle proxy that is sitting between the ABCI-Apps and TM-Node). 

Overall, enabling the ChainIDs in all communications seems to be a good starting point, given that the current ABCI-Spec has cleanly made the TM-node identity irrelevant for the app functionality.
