### ISSUE TITLE
Proposal for light-client validator set syncing

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#406]
This is a write-up of a concrete proposal from Jae, this is me just copying his words.  I will respond with my own words in a comments.

The question is how a light-client can reliably and securely catch up on any validator set changes after going offline for a few days.  There have been two proposals related to this as well, and all three should be looked at together (and only one implemented).  The related issues are #338 and #377.

**Jae (3:45 PST 15. Feb on #hey-team):**

We should, I think, store snapshots of validators every e.g. 1000 blocks, and allow for fast forwarding.  The interface to this "API" is that for any height it can give you the validators.

It has a `GetValidators(height)` function and a `AppendDiff(height, diffs)` function (the second height is for sanity).  Underneath it figures out how to store things efficiently.

This is sufficient for a light client to sync without downloading all the diffs.  It isn't the best situation, so just writing for the fun of it.  The way it would work is, the client would ask for the latest validator set and commit signatures for` H`.  The client is at `H-x`.  If there is sufficient signatures (e.g. more than 1/3 of H-x validators signed H) then client is convinced that at least the validator set at `H` is correct. (Though the block may not have been committed).  Then, it downloads the validator set at H, saves it as "trusted", and then checks the commit for +2/3.

If instead there aren't enough validators in common in `H` (e.g. less than 1/3 validators in common, or more importantly less than 1/3 from H-x that signed), then the client tries again for `H-(x/2)`.  So this is a binary search that starts at the end.

You can imagine all kinds of algorithms similar to this to find a convincing commit.

I think we can start with this, if it isn't too complex, then optimize by creating a new function for the API.  In addition to `GetValidators` and `AppendDiffs`, a third function `GetNextCheckpoint(height)` which returns H where height < H <= LastHeight, where H is the last block that a light client can get convinced of assuming the light client only knows up to height.  And a fourth function `AppendCommit(height, commit)` so the API knows who signed.

I guess this could even be an ABCI app?!

**Comment by ethanfrey** [comment]
Ethan's comments:

I think the idea is good, but I am confused by "api", are your referring to external API (tendermint rpc) or internal API (called by tendermint nodes)? I would think it was an external API, but how should a light-client call `AppendDiff`? But let me run with the general idea.

Currently, all block headers maintain the validator hash in the block header, which is also signed. Thus, if I have a hash for the validator set I trust, when I query, I can quickly detect an unchanged validator set.  This is with the current API.

Change 1: store all validators at given checkpoints  (eg. every 1000 blocks), as per Jae

**This allows us to efficiently catch up when < 1/3 validators change between checkpoints**

The tendermint nodes need to store extra data.  A validator is an address (20-bytes) + public key (64 bytes) + voting power (8 bytes) + padding? maybe 96 bytes... assuming we have 200 validators (which I feel is a lot), that would be 20K of data.  Kind of an upper limit there. If this was only written every 1000 blocks, it would be amortized 20 bytes of extra data per block (plus that 8 bytes for "last block with changes, which should be acceptable.

We add a method to tendermint RPC `GetValidators(height)`, this returns info from the last checkpoint. Enabling the binary search above... assuming that we never have more than 1/3 of the validators changing within a checkpoint.  Example response:

```
{
  Meta *BlockMeta
  Validators []*Validator
  Commit *Commit
}
```

Since all this will need to be verified, we can return the header (which includes the height and validator set hash) along with the validator set.  We can also return the precommit votes to validate this (which came from the next block and were signed by the listed validator set). This data is here to avoid two more rpc calls which would always follow (header H and block H+1).

If the commit includes >2/3 of our trusted validators from previous knowledge (and within the debonding period), then we can trust this and move on. (Note that if only 80% of our known validators are in the new set, and only 80% of those sign, we have 80% signage, but only 64% signatures of our previously trusted validators and cannot be sure it is correct.... Or am I making some mistake here, Jae?

**Comment by mappum** [comment]
>If the commit includes >2/3 of our trusted validators from previous knowledge (and within the debonding period), then we can trust this and move on. (Note that if only 80% of our known validators are in the new set, and only 80% of those sign, we have 80% signage, but only 64% signatures of our previously trusted validators and cannot be sure it is correct....

I believe the assumption is that having 1/3+ of the signatures (50% of the known validators in the new set) means you can assume the blocks are valid, since if there were less than 2/3 the consensus would have stalled and no new blocks would have been produced.

**Comment by ethanfrey** [comment]
But that let's 1/3+ malicious fork the light client.  They can stall consensus on the main branch and have a lying fork that tricks all light clients.  To make sure you are only tricked when the main consensus is taken over, you need the 2/3 check.

Better safe than sorry....

**Comment by ebuchman** [comment]
Closing in favour of https://github.com/tendermint/tendermint/issues/481
