### ISSUE TITLE
Don't panic when block is not found in store

### ISSUE THREAD

**Issue by hendrikhofstadt** [tendermint/tendermint#4069]
Tendermint currently crashes when the consensus reactor wants to help a peer catch up and send block parts which it does not hold in the store.

At Certus One we wipe the blockstore of some of our nodes to create small backups and allow quicker redeployments which is important to quickly react to events like DDoS or major outages. 

If a block is not found, the consensus reactor should not crash since this does not affect the ability to participate in consensus. Instead it should wait for the gossipSleepDuration and continue.

https://github.com/tendermint/tendermint/blob/288f1a0bc66499b71d688c80768a9e91173e0853/consensus/reactor.go#L503-L506

**Comment by gregzaitsev** [comment]
Working on this issue, here is the preliminary PR:
https://github.com/tendermint/tendermint/pull/4163

Not really sure if this can be unit-tested. Should I try to mock PeerState?
