### ISSUE TITLE
docker hub is not being updated with new releases in v0.32 line

### ISSUE THREAD

**Issue by coriolinus** [tendermint/tendermint#4073]
In the [v0.32 series](https://hub.docker.com/r/tendermint/tendermint/tags?page=1&name=v0.32), the most recent docker hub version is v0.32.3,  from two months ago. In the [v0.31 series](https://hub.docker.com/r/tendermint/tendermint/tags?page=1&name=v0.31), the releases are current up to v0.31.10. 

**What happened**:

Most recent v0.32 release on docker hub is v0.32.3.

**What you expected to happen**:

Most recent v0.32 release on docker hub is v0.32.6, and continues updating with new releases. 

**How to reproduce it** (as minimally and precisely as possible):

See docker hub: https://hub.docker.com/r/tendermint/tendermint/tags?page=1&name=v0.32

**Comment by blinky3713** [comment]
any news on this one?

**Comment by marbar3778** [comment]
Our SRE is working on getting this done, we hope to have it fixed this week, I apologize for this issue

**Comment by marbar3778** [comment]
0.32.8 was recently released and pushed to docker hub, let us know if you need previous versions as well.
