### ISSUE TITLE
Broken "Edit this page on Github" at https://tendermint.com/docs/app-dev/app-architecture.html

### ISSUE THREAD

**Issue by PerMildner** [tendermint/tendermint#4088]
The page https://tendermint.com/docs/app-dev/app-architecture.html has a link "Edit this page on Github" that goes to the non-existing page https://github.com/tendermint/tendermint/edit/develop/docs/app-dev/app-architecture.md

**Comment by marbar3778** [comment]
New docs are here: https://docs.tendermint.com/ the edit functionality is now gone, it asks to create issues in place. Thank you for flagging this

<a href="https://gitme.me/image?url=https%3A%2F%2Fmedia3.giphy.com%2Fmedia%2FJlpjgShzDsrMIyFu5U%2Fgiphy.gif&token=thankyou" data-gitmeme-token="thankyou"><img src="https://media3.giphy.com/media/JlpjgShzDsrMIyFu5U/giphy.gif" title="Created by gitme.me with /thankyou"/></a>

**Comment by PerMildner** [comment]
I do not see where "it asks to create issues in place.". At the bottom of the pages there is a "Found an Issue?" button but if I press it I get to a page that asks me to fork and suggest edits. Suggesting an edit is not the same as reporting an issue. (This may all be intentional, but making suggesting a _fix_ for an issue a prerequisite for _reporting_ an issue does not encourage bug-reporting)

**Comment by marbar3778** [comment]
yup I agree with you, will make the change in our docs.
