### ISSUE TITLE
Clarify app-architecture.md

### ISSUE THREAD

**Issue by PerMildner** [tendermint/tendermint#4089]
The overview https://github.com/tendermint/tendermint/blob/master/docs/app-dev/app-architecture.md (revision aaa060f) is unclear.

It uses "The end-user application", "the application", "the app" etc but it is not at all clear what these are referring to in the different paragraphs (or even within each paragraph). There is a huge number of different "apps" in the accompanying graphic so it would be clearer if they were referred to in some unambiguous way.

**Comment by ebuchman** [comment]
Thanks for raising this! Is this better? https://github.com/tendermint/tendermint/pull/4259
