### ISSUE TITLE
Broken link in docs/app-dev/app-architecture.md 

### ISSUE THREAD

**Issue by PerMildner** [tendermint/tendermint#4090]
https://github.com/tendermint/tendermint/blob/master/docs/app-dev/app-architecture.md (revision aaa060f) has a link "ABCI spec" that points at the nonexisting https://github.com/tendermint/tendermint/blob/master/docs/app-dev/abci-spec.md

Compare with the published page https://tendermint.com/docs/app-dev/app-architecture.html where "ABCI spec" points at https://tendermint.com/docs/app-dev/abci-spec.html which in turn says that that document is "DEPRECATED: Moved [here](https://tendermint.com/docs/spec/abci/abci.html)"

**Comment by marbar3778** [comment]
thank you for notifying us, this will be handled
