### ISSUE TITLE
Broken link in https://tendermint.com/docs/spec/blockchain/encoding.html

### ISSUE THREAD

**Issue by PerMildner** [tendermint/tendermint#4091]
https://tendermint.com/docs/spec/blockchain/encoding.html#merkle-trees has a link "Cosmos SDK" pointing at the non-existing https://github.com/cosmos/cosmos-sdk/blob/master/docs/clients/lite/specification.md

**Comment by marbar3778** [comment]
thank you, the cosmos-sdk docs got updated recently
