### ISSUE TITLE
undefined: amino.Typ3_ByteLength

### ISSUE THREAD

**Issue by dncohen** [tendermint/tendermint#4096]
Attempting to compile code that imports tendermint (via binance-chain/go-sdk), I'm running into

```
../../../../github.com/tendermint/tendermint/types/tx.go:136:42: undefined: amino.Typ3_ByteLength
```

I noticed #3884 , but that's closed and I'm running to problem with recent `go get`.

Is the issue on my end?  Any help appreciated!

**Comment by marbar3778** [comment]
Can you please post your version of go-amino? please make sure you are using a release and not master

**Comment by dncohen** [comment]
Using master.  Should I be using `v0.32.7`?

**Comment by marbar3778** [comment]
it seems they have their own version of tendermint then, this is change is master and master is not recommended to be used, I would use tendermint/go-amino if you are using this version of tendermint

**Comment by dncohen** [comment]
Okay, I appreciate your help.  I don't think the problem is here.  It might be binance-chain, or it might be me.  I installed with `GO111MODULE="off"` and maybe got different versions because of that.
