### ISSUE TITLE
Tendermint not working post using unsafe_reset_all

### ISSUE THREAD

**Issue by Blezz74** [tendermint/tendermint#4105]
I want to reset tendermint node. I tried command 

`tendermint unsafe_reset_all`

I am not able to restart the service again. I run my app but when I checked running processes tendermint process is not there which supposed to come automatically which I used to ran the app. Can you please help if there is some process to be followed post using `tendermint unsafe_reset_all`  to get the tendermint service on again.

When I do `tendermint node`

 It gives me error saying
`panic: Tendermint state.AppHash does not match AppHash after replay. Got 56E81F171BCC55A6FF8345E692C0F86E5B48E01B996CADC001622FB5E363B421, expected 731C6D062E4C3BBAE068548F7454DE9760F9574B486A12C515178D8AB7C64F9E`

**Comment by srinathLN7** [comment]
Could you check if the `.tendermint` directory is deleted once you do the reset?
`Replay` error signifies that tendermint and your application are having trouble syncing to common height and hash. Also, I suggest you to check the `Info()` if you happen to have, and see what it is returning.

**Comment by srinathLN7** [comment]
I jusr recreated the error. Its probably because inside your `Commit()` you changed the `ResponseCommit{Data: []byte("")}` and re-run with the same build. Try rebuilding the binary again and it should work.

**Comment by Blezz74** [comment]
@srinathLN7 it works after I delete . tendermint folder. But post that I also need to run tendermint init which eventually generates new node, privvalidator and genesis.json. is there any solution without deleting the . tendermint folder. I didn't got your second solution though. In which file will I get ResponseCommit{} so that I can change it?

**Comment by melekes** [comment]
Are you on Windows? `unsafe_reset_all` should've removed `$HOME/.tendermint` folder.

> is there any solution without deleting the . tendermint folder

No because that's what reset means and does. It would be helpful if you say what are you trying to archive in the end.

**Comment by melekes** [comment]
What Tendermint version are you using?

**Comment by srinathLN7** [comment]
> @srinathLN7 it works after I delete . tendermint folder. But post that I also need to run tendermint init which eventually generates new node id, privvalidator and genesis.json. is there any solution without deleting the . tendermint folder. I didn't got your second solution though. In which file will I get ResponseCommit{} so that I can change it?

That is in your `Commit()` function inside you abci application.

**Comment by Blezz74** [comment]
I somehow managed to get it run on one node.
When I am running command on first node 

"Tendermintnt node --consensus.create_empty_blocks=false --proxy_app=tcp://localhost:26658" 
is working in 1 node.

When I am using the same command on other node having same genesis.json file it is throwing error saying  "err=dial tcp #ip_addressofnode1:26656: I/o timeout" , "err=dial tcp #ip_addressofnode1:26656: I/o timeout" and goes forever. Why this is happening.

**Comment by ebuchman** [comment]
Can you give us more information on the system setup please. What OS are you using and how are the nodes networked? If they're on a LAN you may need to set `addr_book_strict = false` in the config. Also ensure they have different IPs and node ids

**Comment by melekes** [comment]
Closing due to no response.
