### ISSUE TITLE
Broken link in https://tendermint.com/docs/app-dev/ecosystem.html#ecosystem

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4110]
We thank the community for their contributions and welcome the addition of new projects. A pull request can be submitted to this file to include your project.

https://github.com/tendermint/tendermint/blob/master/docs/app-dev/ecosystem.json

file does not exist

**Comment by marbar3778** [comment]
Should we instead have a duplicate of the list in the awesome repo as json and then when people add there projects they have to also add it to json?

**Comment by melekes** [comment]
Better to have one location imho

**Comment by marbar3778** [comment]
yes the one location would be in the awesome repo

**Comment by melekes** [comment]
no, I mean one document. I think the whole ecosystem page can migrate to awesome#README, but we should probably still link to it from the docs. Or have an ecosystem page in the docs.
