### ISSUE TITLE
README.md has broken link to Original Whitepaper

### ISSUE THREAD

**Issue by PerMildner** [tendermint/tendermint#4111]
README.md 274447e has a link "Original Whitepaper" to https://tendermint.com/static/docs/tendermint.pdf but that link is dead.

**Comment by kunadawa** [comment]
I am working on a PR for this. I found a whitepaper here - https://cosmos.network/resources/whitepaper. Can this link be used instead?

**Comment by ebuchman** [comment]
That's the Cosmos whitepaper. This is about the Tendermint whitepaper. @nylira do you know where that is hosted now?

**Comment by fadeev** [comment]
@PerMildner Hi! Thanks for spotting a broken link. I've created a PR and the Tendermint whitepaper will become available again on the same URL in a couple of hours.

**Comment by marbar3778** [comment]
The most recent paper has been added back to the tendermint site, at https://tendermint.com/static/docs/tendermint.pdf, I think the old living in the spec repo is sufficient

**Comment by ebuchman** [comment]
Oh this seems to still be wrong. The readme now says:

```
- [Original Whitepaper](https://github.com/tendermint/spec)
  - You can find the link at the bottom of the readme
```

But not sure what it's referring to re the bottom of the readme and the link is still wrong. The original whitepaper is this one: https://cdn.relayto.com/media/files/LPgoWO18TCeMIggJVakt_tendermint.pdf

We should change the readme to have

```
- [Original Whitepaper: "Tendermint: Consensus Without Mining"](https://cdn.relayto.com/media/files/LPgoWO18TCeMIggJVakt_tendermint.pdf)
```

And possibly that https://tendermint.com/static/docs/tendermint.pdf link could be improved ...
