### ISSUE TITLE
genesis.json hash check before making consensus for the genesis block

### ISSUE THREAD

**Issue by dlguddus** [tendermint/tendermint#4113]
1. observation
  - we observed that the genesis block can reach consensus even if no majority with +2/3 power has same genesis
  - it is very easy to mistakenly having wrong genesis file, so the situation can happen with quite high probability

2. case example
  - 3 validators(20% power) having genesis file A, others(55% power) having genesis file B
  - the genesis block has reached consensus and block height 1 is produced
  - the chain stucked at height 2, complaining app hash mismatch

3. suggestion
  - it is safer for the validators to have identical genesis file on genesis to prevent trouble launch
  - kava launch experience shows that no-check of genesis file hash leads to chaos launch
    (https://link.medium.com/Vo6es9XPn1)
  - the state machine should gather hash of each validator's genesis file and get a consensus hash before proceeding to create a genesis block

**Comment by alexanderbez** [comment]
Great idea! We can probably do this in `InitChain` by updating `abci.RequestInitChain` to include each validator's genesis hash.

**Comment by melekes** [comment]
Good observation 👍 We could probably add optional `--genesis_hash` flag to `tendermint node` (+ a config variable), which will ensure `genesis.json` hash matches the given hash.

**Comment by alexanderbez** [comment]
That sounds' easier imho

**Comment by dlguddus** [comment]
@melekes It would be nice if `--genesis_hash` is a necessary flag so that all validators must provide the hash in config. Great idea!

**Comment by melekes** [comment]
> It would be nice if --genesis_hash is a necessary flag so that all validators must provide the hash in config

not until we introduce modes https://github.com/tendermint/tendermint/issues/2237 (right now I'd hate to provide a hash every time I want to test something)
