### ISSUE TITLE
Uninitialized Fields

### ISSUE THREAD

**Issue by IvantheTricourne** [tendermint/tendermint#4117]
Related to #3882 

The above mentioned issue should allow all fields to be present even if uninitialized. However, the responses from `/abci_info` leave out a few fields:

1. `"last_block_app_hash"`
2. `"last_block_height"`

Example:

```json
{
    "result": {
        "response": {
            "data": "{\"size\":87}",
            "app_version": "1",
            "version": "0.16.1"
        }
    },
    "jsonrpc": "2.0",
    "id": 1839091916768535552
}
```

Additionally, responses from `/block` leave their `"evidence"` struct with a single field `"evidence"` uninitialized (i.e., instead of `null`, use `[]`).

```json
"evidence": {
                "evidence": null
            }
```

**Comment by blinky3713** [comment]
it's worth noting that this response comes from running the kv-store application that ships with tendermint
