### ISSUE TITLE
catching up shows wrong information

### ISSUE THREAD

**Issue by dlguddus** [tendermint/tendermint#4124]
**software**
version : terrad 0.2.6

I raised this issue on tendermint repo because terrad shares same codebase from tendermint

**symptom**

node A connected to 7 peers including B
node B connected to 7 peers including A

node A has "latest_block_height":"2104855" and "catching_up":false
node B has "latest_block_height":"2104870" and "catching_up":false

node B's height keeps increasing but node A's height is stucked forever.
no unusual error found from node A.

I restarted node A, and then the sync normalized.

**Comment by melekes** [comment]
Could you send us a goroutine dump from node A when that happens again? You can obtain it by killing the process with (`kill -6 PID`). The go will dump all running goroutines to STDOUT.

**Comment by dlguddus** [comment]
> Could you send us a goroutine dump from node A when that happens again? You can obtain it by killing the process with (`kill -6 PID`). The go will dump all running goroutines to STDOUT.

https://drive.google.com/file/d/1O37LkddTopDMmjr_6frO1mTbQNm4rK8Y/view?usp=sharing

**Comment by melekes** [comment]
> usual wal corruption

does it happen often? do you have any insights on why it's happening?

**Comment by dlguddus** [comment]
This server has most unstable status among our servers. Still cannot find particular reason yet. Very frequently the node becomes out of sync. I will share it here when I find any suspicious condition. Thanks for asking!

**Comment by dlguddus** [comment]
I expect it is caused by ungraceful service restart. 
when I do "sudo service terrad restart", it happens with very high probability.
when I do stop and wait 5 sec, and start, it happens much less.

**Comment by melekes** [comment]
@dlguddus do you still experience this?

**Comment by dlguddus** [comment]
I never tried "restart" of the daemon after I experienced this, so no more experience on this. I will try to regenerate this again and let you know!

**Comment by melekes** [comment]
Okay. I'm going to close this for now.

Refs https://github.com/tendermint/tendermint/issues/4578
