### ISSUE TITLE
Fix issues reported by LGTM

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4128]
https://lgtm.com/projects/g/tendermint/tendermint/?mode=list

**Comment by tessr** [comment]
I'm not sure how many of these we need to actually worry about. It looks like the majority of alerts are on the python scripts for ops-y things. 

And I'm not sure the Go linter is that accurate. For example, LGTM complains: 

<img width="1236" alt="Screen Shot 2019-11-12 at 11 31 37 AM" src="https://user-images.githubusercontent.com/773524/68664197-3e549d80-0540-11ea-8ff0-52c38d48b13b.png">

but it looks like these assignments are being used to configure things on cobra. So it's probably a false alert from LGTM.

**Comment by melekes** [comment]
I'd like to see the following alerts fixed:

- `libs/pubsub/query/query.peg.go`
- `tools/tm-monitor/mock/eventmeter.go`
- and maybe `abci/example/python/abci/server.py`

**Comment by melekes** [comment]
- python(3) abci is out of date
- query.peg.go is false positive
- tm-monitor was removed
