### ISSUE TITLE
question about consensus algo

### ISSUE THREAD

**Issue by xkwang1228** [tendermint/tendermint#4130]
According to the paper "Correctness and Fairness of Tendermint-core Blockchains", tendermint will suffer a livenss problem if node1 is locked on value v1, node3 is locked on value v2 and node4 is a byzantine node.
Based on the algorithm described in your paper "The latest gossip on BFT consensus", I think the problem still exists. 
Have your guys fixed the problem? Or do you think the attack is to rare to appear?

**Comment by milosevic** [comment]
The paper "Correctness and Fairness of Tendermint-core Blockchains" is based on the old version of the spec. We have fixed this problem in the paper "The latest gossip on BFT consensus".

**Comment by xkwang1228** [comment]
Dear Mr.&nbsp;Milosevic,


I think in the paper "The latest gossip on BFT consensus", line 49 is incorrect because it prevents us from committing nil proposal if we propose certain value in the PROPOSAL.
Also, I do not see the difference between locked round, locked value and valid round, valid value. I would feel very grateful if you could share some thoughts on how they are supposed to used.
In addition, I am quite curious about the use of timeout_commit and start a new consensus instance when we receive ALL instead of 2f+1 precommit messages. It seems to me it has nothing to do with the correctness of the consensus algorithm but it affects the "responsiveness" of the algorithm which is criticized by some researchers.


Regards,
Xiaoke
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by melekes** [comment]
@xkwang1228 check out https://github.com/tendermint/tendermint/issues/4308. I believe it's about the same thing you're talking about here. Feel free to leave a comment if you have any further questions.

**Comment by Alex-duzhichao** [comment]
> 

I am also curious about the use of timeout_commit.  Does timeout_commit affect responsiveness? Or it has no relation with Agreement and Liveness?
