### ISSUE TITLE
Tendermint install script not working

### ISSUE THREAD

**Issue by Tendermeat** [tendermint/tendermint#4136]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Last version (i think)

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**: Ubuntu 18.04
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
run tendermint script https://github.com/tendermint/tendermint/blob/master/scripts/install/install_tendermint_ubuntu.sh

and this happened

go/test/zerodivide.go
package github.com/tendermint/tendermint: no Go files in /home/erg/go/src/github.com/tendermint/tendermint
Already on 'master'
Your branch is up to date with 'origin/master'.
Get Certstrap
go get: warning: modules disabled by GO111MODULE=auto in GOPATH/src;
	ignoring go.mod;
	see 'go help modules'
go: cannot use path@version syntax in GOPATH mode
tools.mk:61: recipe for target '/home/erg/go/bin/certstrap' failed
make: *** [/home/erg/go/bin/certstrap] Error 1
CGO_ENABLED=0 go install -mod=readonly -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD` -s -w" -tags 'tendermint' ./cmd/tendermint
build flag -mod=readonly only valid when using modules
Makefile:34: recipe for target 'install' failed
make: *** [install] Error 1

**What you expected to happen**:
Installation succeed

**Have you tried the latest version**: yes/no
i think yes

**How to reproduce it** (as minimally and precisely as possible): 

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by Tendermeat** [comment]
up

**Comment by marbar3778** [comment]
can you try `go get ./...`. It is working, so not sure where the go.mod is wrong that is causing you to do the `go get` command

**Comment by Tendermeat** [comment]
hey thx for the response, the go get command is working

**Comment by melekes** [comment]
If you have `GO111MODULE=auto`, you need Go >= `1.13`. What Go version do you have?

**Comment by Tendermeat** [comment]
I deleted everything and rerun the script with and modified go version to GO_VERSION=1.13
and the script work which is nice but:
`erg@Gantz:~/go/src/github.com/tendermint/tendermint$ sudo make tools
tools.mk:15: *** could not find go. Is it in PATH? .  Stop.
erg@Gantz:~/go/src/github.com/tendermint/tendermint$ env | grep go
GOPATH=/home/erg/go
PWD=/home/erg/go/src/github.com/tendermint/tendermint
PATH=/home/erg/.nvm/versions/node/v12.12.0/bin:/home/erg/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/intel/sgxsdk/include:/usr/local/go/bin:/home/erg/go/bin
`

**Comment by melekes** [comment]
You need to add go binary to your path - `export PATH=$PATH:/usr/local/go/bin`

https://golang.org/doc/install#tarball

**Comment by melekes** [comment]
Plus, why are you using `sudo`?

**Comment by Tendermeat** [comment]
I add the path, and this happened :
make tools
Get Protobuf
## protobuf v1.3.0
go: finding github.com 0ca988a254f991240804bf9821f3450d87ccbb1b
go: finding github.com/gogo/protobuf 0ca988a254f991240804bf9821f3450d87ccbb1b
go: finding github.com/gogo 0ca988a254f991240804bf9821f3450d87ccbb1b
go: finding github.com/gogo/protobuf/protoc-gen-gogo 0ca988a254f991240804bf9821f3450d87ccbb1b
go: writing stat cache: open /home/erg/go/pkg/mod/cache/download/github.com/gogo/protobuf/@v/v1.3.0.info538507886.tmp: permission denied
go get github.com/gogo/protobuf/protoc-gen-gogo@0ca988a254f991240804bf9821f3450d87ccbb1b: module github.com/gogo/protobuf@0ca988a254f991240804bf9821f3450d87ccbb1b (v1.3.0) found, but does not contain package github.com/gogo/protobuf/protoc-gen-gogo
tools.mk:66: recipe for target '/home/erg/go/bin/protoc' failed
make: *** [/home/erg/go/bin/protoc] Error 1

when i use sudo i have the same error as my last message.

by the way thank you for your help, my english is bad and i'm new

**Comment by melekes** [comment]
I think I've encountered the same error when I was setting up new Vagrant instance. The reason may be the fact that we have gogo/proto BOTH in tools and as dependency (see go.sum).

**Comment by Tendermeat** [comment]
So what can i do to resolve this ?
