### ISSUE TITLE
swagger: upgrade to OpenAPI 3 standard

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4144]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md
https://swagger.io/docs/specification/basic-structure/

**Comment by jackzampolin** [comment]
We have been working with some swagger generation tooling over in the SDK that may help with this. You annotate your handlers with comments and the `swagger.yaml` is generated.

**Comment by melekes** [comment]
https://github.com/swaggo/swag? yeah, seems cool!

**Comment by marbar3778** [comment]
will look into it, I have been doing this for the SDK so can take a look here as well.

**Comment by marbar3778** [comment]
swaggo/swag doesnt support openAPI 3.0, we can update but we will have to continue manually updating. @melekes you good with that?

**Comment by melekes** [comment]
We need to carefully weight the benefits of using swag. So far my thinking:

- ✅ good locality - swag comments are close to method body
- 🔴 no difference between editing comments vs editing swagger.yaml. that's because we don't use any framework supported by swag
- 🔴 bad overview of the whole API
- 🔴 yet another dependency

correct me if I am wrong, but swag makes more sense when you're using one of the supported frameworks. my recommendation: delay until we have a new API
