### ISSUE TITLE
refactor `libs/common` package 

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#4147]
Ideally, in idiomatic Go, we wouldn't have a `common` package. Instead, we'd have packages that more closely map to our domain model. [Dave Cheney has written more on this.](https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common)

It's possible that our current package structure can't be immediately reorganized to achieve this. And that's OK--but we should keep this in mind as a goal as we refactor the various reactors and other components of Tendermint. If we can get to a place where our packages are labeled by what they _provide_, that's likely an indicator that we've done a good job with our refactoring.

**Comment by jackzampolin** [comment]
I like adopting Dave Cheney's views on project structure. Incorporating more "idiomatic go" practices :ok_hand: :man_dancing:

**Comment by marbar3778** [comment]
We have quite a few issues related to the common package, maybe we should use this issue as a meta-issue and track where we are with that stuff

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/2191

**Comment by marbar3778** [comment]
For pkgs that could share a similar name to the std lib, should we name the pkg tm<pkg>, @melekes @tessr thoughts?

**Comment by melekes** [comment]
I'd say yes mainly to avoid the confusion. Like if I say to you imagine apple, and then give you a banana. You will be surprised.
