### ISSUE TITLE
Add height to broadcast_tx result

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#415]
When I successfully broadcast a message over tendermint rpc, I am trusting that node to be honest.  If I want security, I need to double check the block and signatures that it really was included.

But to do that easily, I want to start with the supposed tx height.  Can we add this information to the return value?  At least for the `_commit` variant? Something like:

```Go
type ResultBroadcastTxCommit struct {
	Height    int                     `json:"height"`
	CheckTx   *abci.ResponseCheckTx   `json:"check_tx"`
	DeliverTx *abci.ResponseDeliverTx `json:"deliver_tx"`
}
```

@ebuchman @melekes any thoughts on this?

**Comment by ebuchman** [comment]
Yes, or replace the ResponseDeliverTx with TxResult from https://github.com/tendermint/tendermint/pull/412/files#diff-0dcce51bde6e4cd5ca82d4d76d94e696R10

We will also need another command for querying a tx state, which would return the TxResult with the height.

**Comment by ebuchman** [comment]
or - should I just add Height and Index into this struct for 0.9 ?

**Comment by melekes** [comment]
Yes from me. Don't mind just adding height and index, but using TxResult may save us some time in the future when adding/removing some fields.

```
			event := types.EventDataTx{
				Tx:    tx,
				Data:  txResult.Data,
				Code:  txResult.Code,
				Log:   txResult.Log,
				Error: txError,
			}
```

could be changed to

```
			event := types.EventDataTx{
				TxResult: txResult,
			}

```
P.S why do we need `Tx` and `Error` there? haven't seen us using them in the code

**Comment by ethanfrey** [comment]
It looks good to unify them.  Rather than doing and redoing, let's just go with the `TxResult` approach and base this on the tx indexing work.  Before or after 0.9, that's up to you guys.  But in any case release those two parts together. The work hand-in-hand giving more tx transparence.
