### ISSUE TITLE
unable to connect to peers

### ISSUE THREAD

**Issue by Blezz74** [tendermint/tendermint#4152]
I am using GCP for running tendermint. I used 4 vms to run 4 nodes to be connected in network. I used below commands:

on node0 I ran below commands
```
       tendermint testnet
       cd mytestnet
```
Then on node0

 ```
     cp  -r node0/* ~/.tendermint/
     scp -r node1/* node1user@<node1-ip-address>:/home/node1user/.tendermint/
     scp -r node2/* node2user@<node2-ip-address>:/home/node2user/.tendermint/
     scp -r node3/* node3user@<node3-ip-address>:/home/node3user/.tendermint/ 
```
 
All nodes are sharing same genesis file. I have updated config.toml file to add peristant peers values as `<nodeid>@<nodeip>:26656` for all 4 nodes.

Then I Ran below command on all nodes 
`tendermint node --consensus.create_empty_blocks=false --proxy_app=tcp://0.0.0.0:26658`

I am getting below error on any of the 4 nodes:
![Screenshot from 2019-11-16 14-00-33](https://user-images.githubusercontent.com/51206240/68990876-6c0e4f00-087e-11ea-88e1-64b9924dec65.png)

**Comment by melekes** [comment]
Not sure if we'll be able to help you with connectivity issues. Are other nodes reachable? What's the output of `ping 35.200.139.27` for example?

**Comment by melekes** [comment]
Closing due to no response.
