### ISSUE TITLE
p2p/secret_connection: handshake indifferent to abort flag

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4154]
See https://github.com/tendermint/tendermint/pull/4153#discussion_r347089523

**Comment by cuonglm** [comment]
@melekes isn't this fixed in https://github.com/tendermint/tendermint/pull/4153/commits/4d957ebb8b11172582883bffb4e41ce43f6b84df?

**Comment by melekes** [comment]
we should test that if abort flag is true, TM drops the connection

**Comment by melekes** [comment]
test was written [here](https://github.com/tendermint/tendermint/pull/4829). however, we should try to rewrite it using mockery to improve readability and maintainability.

**Comment by melekes** [comment]
actually the current test looks good enough. not sure if we would benefit from using mockery.
