### ISSUE TITLE
state: remove unused BlockStoreRPC service

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4159]
https://github.com/tendermint/tendermint/blob/8a878c1cad3433ce266962bd5833906d8fc32d6b/state/services.go#L12-L31

**Comment by melekes** [comment]
The alternative is to use it in the RPC, which was done in https://github.com/tendermint/tendermint/pull/4510.

**Comment by erikgrinaker** [comment]
I think I'd be in favor of removing this outright, or renaming it to `BlockStoreReader` or something a bit more general.
