### ISSUE TITLE
Better client interface (and mockable)

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#416]
Based on the `rpc/tests/client_test.go`, I extracted a nice interface to make all this rpc calling much easier and type safe for the clients.  I am using this in the light-client repo, but as @ebuchman mentioned, it really belongs in tendermint.

I will extract this code, clean it up a bit, and prepare a mock version for testing as well. If it is merged in develop, I will remove the duplicate code from light-client (which originally came from my personal repo tenderize...)

@ebuchman let me know if this is something that can make it in 0.9?

**Comment by ebuchman** [comment]
Potentially, but no need to rush. Definitely for 0.9.1

**Comment by ethanfrey** [comment]
Okay, I was gonna do it, so I could pull out the code for light-client and make it more accessible.  After talking with piotr today, I realized this really could be useful for developers.

But cool, no rush, it doesn't change any APIs, and 0.9.1 is fine with me.

**Comment by ebuchman** [comment]
Ok - you're right. Do it. It'll be good for 0.9 to encourage more testing.
