### ISSUE TITLE
Better document philosophy around breaking changes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#4167]
Breaking changes are still happening for the foreseeable future but we should gain clarity on our philosophy around them by documenting it better in the repo. Eg. see https://github.com/tendermint/tendermint/pull/3783/files#r348138856

We should also include examples and guidelines on documenting the changes.

**Comment by melekes** [comment]
@erikgrinaker has done some initial work in https://github.com/tendermint/tendermint/pull/5341

**Comment by marbar3778** [comment]
We made a majority of the API internal now. This drastically reduces the API. Reopen if necessary.
