### ISSUE TITLE
Checkpointing

### ISSUE THREAD

**Issue by njmurarka** [tendermint/tendermint#4168]
I am working on a project that is being designed around Tendermint and Cosmos. The product, similar to BigChainDB, uses the blockchain to propagate requests that ultimately get recorded into a database like MongoDB. 

So at any given block height, the local MongoDB DB instance on every node in the zone has a complete copy of the entire DB, which is the key thing of value to the users. The importance of being able to look at past transactions on the blockchain is negligible. 

To be clear, we do want and need the blockchain ecosystem here to ensure that any given time, new transactions are properly accepted or rejected consistently on every node. 

So the question then is -- is there a way to have every node, at some interval (let's say every 1000th block) "reset" itself back to block height zero? Why? So we can keep a cap on the size of the blockchain's database. No need to keep all that history -- the MongoDB is enough.

**Comment by marbar3778** [comment]
In the comsos-sdk you do have the option to set pruning for everything: https://github.com/cosmos/cosmos-sdk/blob/master/server/config/toml.go#L39

In tendermints case, this will be able to be done with state-sync, we are working towards implementing this.

**Comment by melekes** [comment]
See https://github.com/tendermint/tendermint/issues/828 for state-sync progress. It's almost done! 🚀
