### ISSUE TITLE
docker-compose: Running user-defined abci-application like kvstore - returns abci.socketClient failed to connect: missing port in address.

### ISSUE THREAD

**Issue by srinathLN7** [tendermint/tendermint#4173]
The command `make localnet-start` as we know starts 4 node docker containers and runs an in-built `kvstore` app. Similarly, I wanted to run my own abci-app inside these docker containers. So, what I did was I first integrated my own abci app `sampleapp` into the abci-cli by editing the `client.go` inside the proxy directory so that the command `tendermint node --proxy_app=sampleapp` is executed successfully. And this works absolutely fine. 

Then, I navigated to `.../tendermint/tendermint/networks/local/localnode` and open the `Dockerfile` and edit the line 
from
```
CMD ["node", "proxy_app", "kvstore"].  
``` 
```
CMD ["node", "proxy_app", "sampleapp"].  
``` 
What I expected to see was my app running succesfully inside those docker containers. However, I get the following error
```
node3    | E[2019-11-20|12:37:34.450] abci.socketClient failed to connect to sampleapp.  Retrying... module=abci-client connection=query err="dial tcp: address sampleapp: missing port in address"
node2    | E[2019-11-20|12:37:35.542] abci.socketClient failed to connect to sampleapp.  Retrying... module=abci-client connection=query err="dial tcp: address sampleapp: missing port in address"
node1    | E[2019-11-20|12:37:35.747] abci.socketClient failed to connect to sampleapp.  Retrying... module=abci-client connection=query err="dial tcp: address sampleapp: missing port in address"
node0    | E[2019-11-20|12:37:35.750] abci.socketClient failed to connect to sampleapp.  Retrying... module=abci-client connection=query err="dial tcp: address sampleapp: missing port in address"
```

Any idea what port address am I missing in the docker file? Can someone please help me out here? 
The complete Dockerfile for your reference is shown below:

```
FROM alpine:3.7
MAINTAINER Greg Szabo <greg@tendermint.com>
RUN apk update && \
    apk upgrade && \
    apk --no-cache add curl jq file
VOLUME [ /tendermint ]
WORKDIR /tendermint
EXPOSE 26656 26657 
EXPOSE 26658/tcp
ENTRYPOINT ["/usr/bin/wrapper.sh"]
CMD ["node", "--proxy_app", "sampleapp"]
STOPSIGNAL SIGTERM
COPY wrapper.sh /usr/bin/wrapper.sh
COPY config-template.toml /etc/tendermint/config-template.toml
```

**Comment by ebuchman** [comment]
The problem is probably that your custom tendermint binary is not being found inside the docker container? So need to ensure that it gets in there.

**Comment by srinathLN7** [comment]
@ebuchman Thank you for your response. Yes, I later understood that could be the reason. So, I tried rebuilding the linux binary in the `build` directory through `make build-linux` and tried re-mounting it to the container.  Is this the correct way to re-build the tendermint binary? If not, can you please tell me how to rebuild everything from scratch? Also, am curious to how is that the `tendermint node --proxy_app=sampleapp` works perfectly fine within the local host environment without re-building.

**Comment by srinathLN7** [comment]
@ebuchman  I am trying this alternative route because I couldn't solve this issue. https://github.com/tendermint/tendermint/issues/4074 

Would be immensely grateful if you could take a look at this too. I followed the prescribed method in the tendermint documetation and found that the the abci containers and node containers are running successfully. The docker log shows running process and abci-server says its ready to accept connections. And the node client  keeps on redialing failing to conenct. Still for some reason the two containers cannot communicate between each other. Any idea whats going wrong?

**Comment by melekes** [comment]
>  Is this the correct way to re-build the tendermint binary?

yes

You are missing the port!

```
CMD ["node", "--proxy_app", "tcp://sampleapp:26658"]
```

OR

```
CMD ["node", "--proxy_app", "tcp://192.167.10.6:26658"]
```

If you have any further questions, please ask them on [Riot](https://riot.im/app/#/room/#tendermint:matrix.org)
