### ISSUE TITLE
v0.32.9: PRs to backport

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4177]
- https://github.com/tendermint/tendermint/pull/4163 (PR: #4287 merged)
- https://github.com/tendermint/tendermint/issues/4051 (PR: #4284 merged)
- https://github.com/tendermint/tendermint/issues/4248 (PR: #4285 merged)
- https://github.com/tendermint/tendermint/pull/4263 (PR: #4294 merged)
- https://github.com/tendermint/tendermint/pull/4283 (Not included: @marbar3778: in 0.32 series commit is vote so it doesnt have commitAbsent and commit nil. So to my understanding if vote is nil then it would be a miss)

**Comment by marbar3778** [comment]
it was asked to do this one as well: https://github.com/tendermint/tendermint/pull/4263

**Comment by greg-szabo** [comment]
I've created the branch release/v0.32.9 to track the changes we want to release. I've also submitted a fix for #4051 and updated the comment with the PR.

**Comment by greg-szabo** [comment]
@marbar3778 implementing #4263 would require a bit more involvement. Cherry-picking revealed conflicts between the current code and the PR that was accepted for `master`. Someone with an understanding of the change should look at it and do a proper backport for the release. Would you be up for it?

**Comment by leoluk** [comment]
#4283 should also be backported for the metrics to be useful for validator monitoring.

**Comment by greg-szabo** [comment]
Hah, maybe that's why I had conflicts during cherry-picking?

**Comment by leoluk** [comment]
Unlikely, the first PR is independent of the second (but the latter improves the missed block detection).

**Comment by marbar3778** [comment]
I do believe we are ready for 0.32.9 unless there are others that would like to say to back port other things

**Comment by greg-szabo** [comment]
@leoluk #4283 doesn't seem to apply here, please raise them, if you have any concerns.

If no concerns, the team will move forward with the release.

**Comment by greg-szabo** [comment]
> unless there are others that would like to say to back port other things

I would move those requests to a new backport release, if any.

**Comment by leoluk** [comment]
No concerns, #4294 already checks for nil vote

**Comment by greg-szabo** [comment]
Yay https://github.com/tendermint/tendermint/releases/tag/v0.32.9
