### ISSUE TITLE
Introduce InvalidHeaderEvidence to punish "Lunatic" Validators

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#4182]
A previous discussion (#3244) surfaced an attack on light clients that can be conducted by a cabal of validators that once controlled +1/3 of the validator set (call them VC, no pun intended ;) ) but are no longer part of the validator set. Since the attacking validators are no longer part of the validator set, this was called "counterfactual". The attack works against the "skipping" verification method (aka "bisection"), where VC gives a light client a future header that is incorrect (ie. not a result of the state transition function on committed blocks) but that the light client trusts because it is signed by VC (+1/3 of a validator set it trusts). In this new header, the full validator set is VC, so they can now do whatever they want. The unique thing about the attack is that at no point do the validators in VC commit an equivocation or a violation of the Tendermint consensus rules (just application-level invalid state transitions). 

It was [also discovered](https://github.com/tendermint/tendermint/issues/3244#issuecomment-518379429) that the attack works even if the VC are still an active part of the validator set, but are now less than +1/3. Thus the attack is more general than the counterfactual case. Since the attack always involves signing an invalid header, we call it instead the "lunatic" attack, since the participating validators are clearly nuts :).

Note if VC were still +1/3 of the validator set, the attack would necessarily involve some form of violating the consensus rules (ie. equivocation or amnesia, according to [parlance](https://github.com/tendermint/spec/blob/master/spec/consensus/fork-accountability.md#attack-scenarios)), and would also allow them to censor any evidence. Since the attack only works if they become less than +1/3 of the validator set, it's possible to avoid censorship and submit evidence and punish them within the unbonding period. One caveat: after conducting the attack, if VC can recover +1/3 of the active validator set, they can censor evidence. Presumably, they cannot guarantee this for themselves, and thus it is worth trying to punish them on chain for this.

To punish this attack, we need support for a new Evidence type, call it `InvalidHeaderEvidence`. This type includes a vote and a header. The header must contain fields that are invalid with respect to the previous block, and a vote for that header by a validator that was in a validator set within the unbonding period. While the attack is only possible if +1/3 of some validator set colludes, the evidence should be verifiable independently for each individual validator. This means the total evidence can be split into one piece of evidence per attacking validator and gossipped to nodes to be verified one piece at a time, reducing the DoS attack surface at the peer layer.

Note it is not sufficient to simply compare this header with that committed for the corresponding height, as an honest node may vote for a header that is not ultimately committed. Certain fields may also be variable, for instance the LastCommitHash and the Time may depend on which votes the proposer includes. Thus, the header must be explicitly checked for invalid data.

For the attack to succeed, VC must sign a header that changes the validator set to consist of something they control. Without doing this, they can not otherwise attack the light client, since the client verifies commits according to validator sets. Thus, it should be sufficient to check only that ValidatorsHash and NextValidatorsHash are correct with respect to the header that was committed at the corresponding height.

That said, if the attack is conducted by +2/3 of the validator set, they don't need to make an invalid change to the validator set, since they already control it. Instead they would make invalid changes to the AppHash, or possibly other fields. In order to punish them, then, we would have to check all header fields.

Note some header fields require the block itself to verify, which the light client, by definition, does not possess, so it may not be possible to check these fields. For now, then, I propose that InvalidHeaderEvidence be checked against all header fields which are a function of the application at previous blocks. This includes ValidatorsHash, NextValidatorsHash, ConsensusHash, AppHash, and LastResultsHash. These should all match what's in the header for the block that was actually committed at the corresponding height, and should thus be easy to check.

Of course, we should port this write up to an ADR-047 (as per https://github.com/tendermint/tendermint/issues/2313) and flesh out the details a bit further there.

**Comment by melekes** [comment]
> are now less than +1/3

but if VC is no longer a part of the validator set, there's nothing we can do, right?

> as an honest node may vote for a header that is not ultimately committed

can you give an example? Like if a malicious proposer from less than 1/3 cabal group creates a proposal block which changes the validator set, others won't vote for it.

> That said, if the attack is conducted by +2/3 of the validator set, they don't need to make an invalid change to the validator set, since they already control it. Instead they would make invalid changes to the AppHash, or possibly other fields.

Why would they choose to change AppHash? If +2/3 of malicious nodes control the network, they can do pretty much anything (slashing, voting to spend community pool, etc.), no?

**Comment by ebuchman** [comment]
> but if VC is no longer a part of the validator set, there's nothing we can do, right?

So long as they're still within the unbonding period we can still slash them.

> can you give an example?

Like if consensus takes multiple rounds at some height, at each round there might be different proposers with different blocks, and some honest node might precommit something from an earlier round that ultimately doesn't get committed. The block has to be valid (ie. correctly derived from the previous block) but there are many possibilities for the block itself (different txs, different proposer address, different LastCommit, etc.)

> Why would they choose to change AppHash? If +2/3 of malicious nodes control the network, they can do pretty much anything (slashing, voting to spend community pool, etc.), no?

All those things are examples of arbitrarily changing the app state, which would result in a change to the app hash :)

**Comment by melekes** [comment]
> This means the total evidence can be split into one piece of evidence per attacking validator and gossipped to nodes to be verified one piece at a time, reducing the DoS attack surface at the peer layer.

Is it really worth breaking up evidence given we know validator set size. Say there are 125 validators, 1/3+ ~= 45 voted for invalid header. 45 signatures (CommitSig) each 105 bytes ~= 5KB. Does not seem like a big attack vector to me.
