### ISSUE TITLE
consensus replay_file.go fails with "undefined db.DBBackendType"

### ISSUE THREAD

**Issue by davebryson** [tendermint/tendermint#4184]
**Tendermint version** :  0.32.8

**Environment**:
- **OS**:  OSX Mohave 10.14.6

**What happened**:
Stating a simple ABCI fails with the following error:
`pkg/mod/github.com/tendermint/tendermint@v0.32.8/consensus/replay_file.go:278:12: undefined: db.DBBackendType`

=> [Here's the line causing the problem](https://github.com/tendermint/tendermint/blob/master/consensus/replay_file.go#L278)

**Comment by melekes** [comment]
Check that you're using the v0.2.0 version of `tm-db`, not the latest v0.3.0

**Comment by marbar3778** [comment]
Since 0.3.0 is breaking the fix is in the master branch of tendermint. v0.2.0 will be compatible with 0.32.8

**Comment by davebryson** [comment]
I was using v0.3.0.   I'll try with v0.2.0.  Thanks
