### ISSUE TITLE
Transactions get stuck in the mempool

### ISSUE THREAD

**Issue by askolesov** [tendermint/tendermint#4188]
**Tendermint version**: 0.32.7-1604047c

**ABCI app**: kvstore

**Environment**:
- **OS**: Ubuntu 18.04.3 LTS
- **Install tools**: interchainio/tm-load-test (master)

**What happened**: After the continuous high load, some transactions get stuck in the mempool and are infinitely committed every several blocks.

**What you expected to happen**: Nothing gets stuck in the mempool.

**Have you tried the latest version**: yes

**How to reproduce it**:
- Run local network with the default configuration
- Run `tm-load-test --endpoints ws://localhost:26657/websocket,ws://localhost:26660/websocket,ws://localhost:26662/websocket,ws://localhost:26664/websocket -r 3000 -T 15`

**Logs**: https://pastebin.com/CCQ4tFHi
- Pay attention to the repeating number of new transactions at the end of the log: 0, 1089, 1707, 82, 0, 1089 and so on.

**Config**: Default for the localnet

**node command runtime flags**: Default for the localnet

**Comment by melekes** [comment]
https://docs.tendermint.com/master/app-dev/app-development.html#replay-protection

**Comment by askolesov** [comment]
That helped a lot. Thanks!
