### ISSUE TITLE
Tendermint throws 'rpc error: code = Unimplemented desc = Method not found: types.ABCIApplication/Echo' on example code

### ISSUE THREAD

**Issue by tmntthrowaway** [tendermint/tendermint#4191]
**Tendermint version**: 0.32.8-14e04f76

**ABCI app** : KVStore

**Environment**:
- **OS** (e.g. from /etc/os-release): RHEL 8
- **Others**: OpenJdk11, grpc 1.22.1, protoc 3.7.1

**What happened**: When running the example code defined [here](https://docs.tendermint.com/master/guides/java.html), the final step of running the tendermint node and pointing it to the grpc server results in the tendermint node complaining about no echo method found. 

Note the the code in the guide does not define an echo function. I added one to my code, which is simply 

```java
    @Override
    public void echo(RequestEcho request, StreamObserver<ResponseEcho> responseObserver) {
        var response = ResponseEcho.newBuilder().setMessage(request.getMessage()).build();
        responseObserver.onNext(response);
        responseObserver.onCompleted();
    }
```

Rebuilding and redeploying the code with this change keeps the same error.

**What you expected to happen**: No errors to be in logs

**Have you tried the latest version**: yes

**How to reproduce it** : Follow the guide to generate java files from protobufs. Use [this](https://gist.github.com/tmntthrowaway/d49ff0a68842aeeb7bf4551acca1a433) code as application code (its the same thing the guide says to write, plus the echo method). Start grpc server. Start tendermint pointing to grpc server. Observer error message.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
E[2019-11-23|04:47:25.357] Echo failed                                  module=abci-client connection=query err="rpc error: code = Unimplemented desc = Method not found: types.ABCIApplication/Echo
```

**Config**: default settings

**Anything else we need to know**: If you spin up a vanilla grpc stub, connect to the grpc server and call the echo method it works perfectly fine.

**Comment by melekes** [comment]
We have updated the package names of our proto files on master to prevent future conflicts (see https://github.com/tendermint/tendermint/pull/3986).

Please install the latest version of Tendermint (NOT MASTER)

```sh
cd $GOPATH/src/github.com/tendermint/tendermint
git checkout v0.32.8
```

then regenerate protobuf files

**Comment by tmntthrowaway** [comment]
Thanks, that did fix the error.
