### ISSUE TITLE
How do you implement the query API?

### ISSUE THREAD

**Issue by tmntthrowaway** [tendermint/tendermint#4195]
I'm a bit unclear on how a query function implementation is supposed to be designed. Is it meant to read data from the application layer persistent store, or is it meant to read straight from the blockchain layer via Tendermint API calls?

If its meant to read from Tendermint, what is the API for this? Can I say 'tendermint give me the raw block at height n'?

If its meant to be read from persistent application stores, does that mean that when a new instance of the app is added to the network it has to rebuild to store from scratch (through some replay of all previous txs)?

The example KVStoreApp seems to imply the latter, but its unclear if this is an overly-simplistic example.

If there is an existing query implantation I can look at for reference that would be great. The [documentation on query](https://docs.tendermint.com/master/spec/abci/abci.html) is a bit sparse on how to actually implement it.

**Comment by melekes** [comment]
So the idea behind `abci_query` is to free application developers from a need to spin another API server (in addition to Tendermint Core RPC). When `abci_query` is called, it's proxied by Tendermint to the app, which should use the `key` (e.g. `/store/accounts/adam`) to retrieve a piece of application data and send it back to Tendermint (which in turn will send it in response to `abci_query`).

Check out the example [here](https://docs.tendermint.com/master/guides/go.html) `1.3.3 Query`

**Comment by tmntthrowaway** [comment]
Thanks.

Does this mean that state is expected to be replicated and synchronized between the app layer and the tendermint layer? e.g. in the KVstore example you linked to the state is held at app layer, but since the tendermint layer has every raw block the state is also held there (in a less readable format). 

If so, does that imply that the app layer needs to also implement a way to recreate state at a given time (in other words, how do you deal with the `block_height` param to query)? Perhaps the piece of the puzzle I'm missing is how can the app ask Tendermint for a raw block at height `n`?

In a similar fashion, does the app layer need to replicate storage of proofs?

**Comment by melekes** [comment]
> Does this mean that state is expected to be replicated and synchronized between the app layer and the tendermint layer?

application should only store the latest state

> Perhaps the piece of the puzzle I'm missing is how can the app ask Tendermint for a raw block at height n?

https://docs.tendermint.com/master/rpc/#/Info/block

> In a similar fashion, does the app layer need to replicate storage of proofs?

if you want to give your clients ability to verify data - yes!
