### ISSUE TITLE
Question: can I use multiple ABCI apps with single Tendermint node?

### ISSUE THREAD

**Issue by damirka** [tendermint/tendermint#4196]
Hello, I haven't found the answer in Tendermint documentation (maybe I should double check, if so tell me).

I need to run multiple different ABCIs (like js-abci or rust-abci) with single Tendermint node. Can I do it? If yes how? If no why? 

There's only one CLI option and it's `--proxy_app`. Can there be more than one proxy app? Is there any recommended design solution for managing multiple 'proxies' or ABCIs?

**Comment by melekes** [comment]
See 

- https://github.com/tendermint/tendermint/issues/452
- https://github.com/tendermint/tendermint/issues/990

> I need to run multiple different ABCIs (like js-abci or rust-abci) with single Tendermint node. Can I do it? If yes how? If no why?

See https://github.com/tendermint/tendermint/issues/990#issuecomment-504478678. Currently a) there's no sufficient justification which will outweigh increased complexity & decreased throughput b) insufficient human resources

**Comment by damirka** [comment]
That pretty much answers my question for now. Thanks for quick response!
