### ISSUE TITLE
RPC reference guide leads to 404

### ISSUE THREAD

**Issue by tmntthrowaway** [tendermint/tendermint#4199]
**What happened**: The [docs](https://docs.tendermint.com/master/tendermint-core/rpc.html) currently link to a [Page Not Found](https://tendermint.com/rpc/) for the RPC reference guide

**What you expected to happen**: Working reference guide. 

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): go to https://tendermint.com/rpc/

**Comment by marbar3778** [comment]
https://docs.tendermint.com/master/rpc/ is the correct link. Will remove the link that is listed there.
