### ISSUE TITLE
Provide a strongly type config struct and defaults

### ISSUE THREAD

**Issue by silasdavis** [tendermint/tendermint#420]
Currently you can get an idea of default config that tenderminit requires by looking at: https://github.com/tendermint/tendermint/blob/master/config/tendermint/config.go#L37

However that requires you to read a config from disk and doesn't make it explicit what is mandatory and what can be derived from other values.

A more explicit way to model your config dependencies would be to provide a struct (`TendermintConfig`) with all the values there included as fields that could be passed to `NewNode`. You could unmarshal a TOML config into this struct for standalone use: https://github.com/BurntSushi/toml/blob/master/decode.go#L24

But you could also provide a utility function `CreateTendermintConfig(rootDir, <other mandatory fields...>) *TendermintConfig` which would give you access to the base config (note it would not try to read config from the filesystem itself), on top of which the caller can set/override values. This would make upgrading Tendermint in applications that own their own config easier because you can start with a working base-config up front. Currently you just end up with late and less obvious failures if you don't supply required config.

**Comment by ethanfrey** [comment]
If we go fully with cobra-viper for cli, we can use viper for the config file (with overrides from env variables and command line).

Also, 420, dude! 🎉  🇯🇲

**Comment by adrianbrink** [comment]
I think this has been tackled in #484 and hence I'll close this one.
