### ISSUE TITLE
Programmatic control of Tendermint node

### ISSUE THREAD

**Issue by KrishnaPG** [tendermint/tendermint#4204]
This issue tries to elaborate a little bit more on the brief goal discussed in https://github.com/tendermint/tendermint/issues/4065 regarding the programmatic control of TM node.

Since Tendermint is consensus-engine built for programmers, being able to programmatically control it offers wider range of possibilities, some of which are on the lines of:

- Config initialization, discovery and Updates,
- Lifetime control of the TM node itself
- Status and Stats Queries

The ProxyApp and TM node currently use ABCI protocol to communicate, control and sync their **data** flow. I am requesting to slightly expand that communication interface to include few more API calls that allow the ProxyApp to control and sync with the TM node in the **behavior** flow too.

### Config initialization 
Not sure if the `tendermint init` command currently supports specifiying config parameters on the command line, but the expecation is as below:

- `tendermint init`  should accept command line parameters, and create the config file with the supplied values (overriding the defaults). Any params that are not specified on the CLI, will assume their default values.
    - **Goal**: Allow the ProxyApp to init a new TM node with custom configuration values

    The custom config values are specified as additional params for the `init` command while _spawning_ the TM node programatically. Something like below:
````
tendermint init --rpc.laddr=tcp://0.0.0.0:26657 --consensus.create_empty_blocks_interval=30s
````
These values get converted to whatever config syntax the TM needs (e.g. `toml`) and stored in the `home` path of the node as the default config. With the custom config being set as the default, no need to further specify any customizations next time when the TM node is launched.

### Config overrides

starting a tendermint node should take the configuration values in this order:
 - from config file 
 - from the environment (overrides the config-file values)
 - from the commandline param (overrides the env and config-file values)

### Config discovery and updates
Values (that support dynamic changes, such as `create_empty_blocks` etc.) should be able to dynamically set / adjusted through some API.
 - Currently the config values cannot possibly be changed once the TM node is started. 
 - **Goal** is to be able to dynamically set / adjust the current config values in the running TM node instance through some API that the ProxyApp can invoke
 - Not all values can be changed, but the ones that make sense to control and tune at runtime, such as `create_empty_blocks_interval` can be expected to be adjusted by the ProxyApp through the API.
 
Preferably there should be additional API to tell which config values can be changed (i.e. discovery). 
 - For example `GET /dynamicConfigValues` should return the list of key-value pairs of all run-time adjustable config name and their values. Then `POST /dynamicConfigValues` with specific key-value pairs for some config values should update those specific config values inside the running TM node.
 - **Goal**: The ProxyApp should be able to build a UI that lists the config keys and their current values. The UI may possibly have some UI controls, such as Slider, UpDown control etc. that allows these config values to be changed and submitted back to the TM node for updation. Such updations should take effect immediately in the running TM node process.

### Lifetime control
The ProxyApp can launch the TM node programmatically (using OS process spawn API etc.). The ProxyApp should also be able to request the TM node to exit gracefully.
 - **Goal** is to avoid killing the TM node process externally, and rather use some API to request the TM node to gracefully exit.

   Something like `POST /shutdown` with some shutdown message in the body that gets logged into the TM node logs and results in the TM node process to exit gracefully.

### Status and stats query
Not sure if TM node currently supports health status query, but the ProxyApp should be able to know the statistics about the runtime of the TM node.
   - The statistics may include things such as:
         - how many blocks were processed till now, how many got rejected in the CheckTx stage etc.
         - performance metrics about the block creation. For example, mean block creation time, longest and shortest block creation time, average waiting time for a block commit etc.
         - optionally, the TM node process stats (such as the process start time, cpu, memory utilization etc.), 
             - the peer list, which blocks came from which peer etc.

The **goal** is for the ProxyApp to be able to build a dashboard kind of UI that administrators can monitor to know the health status of the TM node as well as the operational statistics around the blocks. 

For example, monitoring a metric like `average block creation time` (e.g. a line chart drawn over a period of time) can tell the administrators if anything is going wrong with the block creation performance.

While these block-level statistics could be easily be derived in the ProxyApp also, it would be good to have it inside the TM node as common feature, instead of every ProxyApp creator writing it from themselves.

**Comment by ebuchman** [comment]
This is a really great summary thanks for writing this. Probably some of this can be broken out into smaller issues that might be easier for external contributors to help with.

**Comment by marbar3778** [comment]
Some values that could be on `init` are on `node`. Would we want to move them all over to `init`?

I have found myself going into the `config.toml` fairly often when trying to test things, while it being a small issue it adds up. 

This issue will need to be broken up into multiple PRs and/or issues
