### ISSUE TITLE
Formalise definition, detection and processing of individual evidence

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#4213]
https://github.com/tendermint/tendermint/issues/4189 introduces two kind of evidences: individual and global. We need to formalise the notion of individual evidence and explain how it is being detected and created from a fork (detected by the lite client). Furthermore, the specification of required data structures and individual evidence processing on chain should be done.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/issues/4182 InvalidHeaderEvidence to punish "Lunatic" Validators
