### ISSUE TITLE
Formalise definition, detection and processing of global evidence

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#4214]
#4189 introduces two kind of evidences: individual and global. We need to formalise the notion of global evidence and explain how it is being detected and created from a fork (detected by the lite client). Furthermore, the specification of required data structures and global evidence processing on chain should be done.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-056-proving-amnesia-attacks.md
