### ISSUE TITLE
Write a specification of the lite client failure detection module 

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#4215]
In parallel with the core lite client module (specification is https://github.com/tendermint/spec/blob/master/spec/consensus/light-client.md), the lite client should implement the failure detection module. The role of the failure detection module is to detect forks, create an evidence of misbehaviour and submit it to the correct full node. Input to the failure detection module is a list of verified headers that are managed (and stored) by the core lite client module. Forks are detected by cross-checking those headers with headers for the same height that are downloaded from the randomly selected (other) full nodes.

We need to write formal specification of the lite client failure detection module so that requirements and operations of this module are clear.

**Comment by melekes** [comment]
Moved to https://github.com/tendermint/spec/issues/103
