### ISSUE TITLE
Write TLA+ specification of the fork accountability problem

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#4216]
https://github.com/tendermint/spec/blob/master/spec/consensus/fork-accountability.md defines several potential attacks that can be executed on lite client in case Tendermint security model is broken. However, we don't have any guarantee that this list is exhaustive. 

Write a formal model of the fork accountability problem in TLA+, and try to prove with the help of TLC that either this list is exhaustive or identify new attacks.

**Comment by melekes** [comment]
Moved to https://github.com/tendermint/spec/issues/102

**Comment by josef-widder** [comment]
That was actually done in https://github.com/tendermint/spec/pull/232, so we can close the issue.

**Comment by cmwaters** [comment]
Ah perfect. Thanks @josef-widder
