### ISSUE TITLE
Write specification of on chain fork detection protocol

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#4217]
We need to write precise specification of execution of fork detection protocol on chain. This includes interaction with a lite client (once lite client detects a fork), evidence creation, gossiping of evidence, committing evidence as part of block, and then evidence processing as part of block execution. The specification should define precisely various terms (fork, slashable fork, evidence, height vote set as part of challenge response, etc) and also contain diagram of interactions between various parties.

**Comment by melekes** [comment]
Moved to https://github.com/tendermint/spec/issues/104
