### ISSUE TITLE
tendermint data corruption: leveldb: manifest corrupted

### ISSUE THREAD

**Issue by vikstrous** [tendermint/tendermint#4220]
I got the following panic from cosmos:
```
panic: Error initializing DB: leveldb: manifest corrupted (field 'comparer'): missing [file=MANIFEST-000057]
goroutine 1 [running]:
github.com/tendermint/tm-db.NewDB(0x11aea6a, 0x8, 0xc00018b6e0, 0x9, 0xc00762d3e0, 0x12, 0x7f634d25e420, 0x1587c40)
	/go/pkg/mod/github.com/tendermint/tm-db@v0.1.1/db.go:67 +0x274
github.com/tendermint/tendermint/node.DefaultDBProvider(0xc00b8f4900, 0xc00b8f4900, 0x13bb1d, 0x515e8, 0xc0075dfaa0)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/node/node.go:66 +0xcc
github.com/tendermint/tendermint/node.createEvidenceReactor(0xc000163180, 0x13a5080, 0x1598280, 0xc01dc5a2c8, 0x15853c0, 0xc013f17240, 0x6, 0xc005bc1520, 0xa, 0x13bb1d)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/node/node.go:340 +0x83
github.com/tendermint/tendermint/node.NewNode(0xc000163180, 0x157f200, 0xc01383a6e0, 0xc013f16fd0, 0x1566200, 0xc00b6db040, 0xc013f17210, 0x13a5080, 0xc013f17220, 0x15853c0, ...)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/node/node.go:615 +0x613
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0001576a0, 0x13a5920, 0x1d, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/server/start.go:129 +0x4df
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000522f00, 0xc00016aea0, 0x1, 0x9, 0x0, 0x0)
	/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.37.0/server/start.go:43 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc000522f00, 0xc00016ae10, 0x9, 0x9, 0xc000522f00, 0xc00016ae10)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0xc000164000, 0x11d02bf, 0xc0008ffed8, 0x587c64)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000164000, 0x13a5d30, 0x11b5f46, 0x10)
	/go/pkg/mod/github.com/tendermint/tendermint@v0.32.2/libs/cli/setup.go:89 +0x3c
main.main()
	/go/src/github.com/cosmos/gaia/cmd/gaiad/main.go:68 +0x876
```
Every restart after that I got the same error.

The following logs are from right before the data corruption:
![Screenshot 2019-12-05 at 8 45 32 PM](https://user-images.githubusercontent.com/482425/70263666-f2e08880-17a7-11ea-9a60-4f03fd34e7cd.png)

The node was killed by a deployment. I think kubernetes tries to send a graceful shutdown signal, but I'm not sure what timeout it has or if cosmos responds to shutdown signals.

Sorry, I'm not sure exactly what version of cosmos this was, but we were using the official gaia images and this happened on Nov 13, 2019.

**Comment by marbar3778** [comment]
This issue may be better suited in the tm-db repo.  But this also seems like a leveldb issue. We will look into it.

**Comment by melekes** [comment]
LevelDB is known for its corruption issues ([1])(https://github.com/google/leveldb/issues?q=is%3Aopen%20is%3Aissue%20label%3Abug, [2](https://github.com/syndtr/goleveldb/issues?q=is%3Aissue+is%3Aopen+corruption)).

Have you tried opening an issue in github.com/syndtr/goleveldb? I am afraid there's not much we can do except this and maybe considering switching to another database ([1](https://github.com/tendermint/tendermint/issues/1835)).

**Comment by melekes** [comment]
#4630 should help too

I'm going to close this. Please open an issue in https://github.com/syndtr/goleveldb/issues. Thank you!
