### ISSUE TITLE
Enable contract tests 

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4229]
Openapi 3.0 is not fully supported by Dredd.

You find the status of dredd support  of openapi 3.0 here: https://github.com/apiaryio/api-elements.js/blob/master/packages/fury-adapter-oas3-parser/STATUS.md

**Comment by melekes** [comment]
https://github.com/apiaryio/api-elements.js/blob/master/packages/openapi3-parser/STATUS.md

**Comment by marbar3778** [comment]
still doesn't work https://github.com/tendermint/tendermint/pull/4830. here are the logs for the tests..

**Comment by tessr** [comment]
@marbar3778 what's the status of this issue?

**Comment by marbar3778** [comment]
dredd still doesn't support open api 3.0. We can close this since contract tests were removed entirely from ci.
