### ISSUE TITLE
Better encoding for empty hashes?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#4241]
Hashes in Tendermint are currently just slices, not fixed length arrays, so empty hashes (which occur at least in the first block) are encoded differently from others. While it's not hard to handle this currently in Go, it makes for a lot of work in Rust: https://github.com/interchainio/tendermint-rs/pull/66. 

Should we consider using fixed-length arrays for hashes and let the "empty hash" be instead the un-initialized array, ie. all 0s?

**Comment by ebuchman** [comment]
All 0's is probably a bad idea. What if instead of empty hashes we used the hash of empty values? https://github.com/interchainio/tendermint-rs/issues/101#issuecomment-569978629

**Comment by yihuang** [comment]
> All 0's is probably a bad idea. What if instead of empty hashes we used the hash of empty values? [interchainio/tendermint-rs#101 (comment)](https://github.com/interchainio/tendermint-rs/issues/101#issuecomment-569978629)

Isn't hash of empty value is as bad as all 0's ;D

**Comment by erikgrinaker** [comment]
I think fixed-length arrays are kind of annoying do deal with - most functions expect byte slices, so we'll have to do a lot of casting back and forth. Also, conceptually, the absense of a hash is not `Some(zerohash)`, it's a `None` (or `nil`, if you prefer).

I think the suggestions in the rs issue of using either an `Option` or an enum variant for the first block is more appropriate here, and would get you compile-time type checking for this as well.

**Comment by erikgrinaker** [comment]
I'm going to close this, let's reopen if anyone disagrees.
