### ISSUE TITLE
[consensus bug]LastCommit.PreCommit must be equal to all validators

### ISSUE THREAD

**Issue by BananaLF** [tendermint/tendermint#4246]
**Tendermint version** :v0.32.8

**What happened**:
The following code requires precommits size meet the full validator size. But the consensus only requires +2/3/ validators weight is enough. It should be a bug here
https://github.com/tendermint/tendermint/blob/83f1801625c4e02176d990b6f4894866430e3e2e/state/validation.go#L96

**Comment by melekes** [comment]
Tendermint includes absent votes & votes for nil block along with votes for proposal block (https://github.com/tendermint/tendermint/blob/7d7b47a39a91e565278135d8c76f9706c8a6c65b/types/block.go#L443-L452).

**Comment by BananaLF** [comment]
ok, Thanks
