### ISSUE TITLE
Enhance RPCClient Dialer with basic authentication / HTTP headers

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#4248]
User story:
I'm using a CLI to connect to a Tendermint-based blockchain RPC. I would like to lock down the RPC connection with HTTP Basic Authentication. This requires the JSONRPCClient.Call to add headers to the connection request.

**Comment by greg-szabo** [comment]
What happens in PR 4285:

Changes in http_client.go:
1. Extended JSONRPCClient struct with username and password fields.
2. Modified the JSONRPCClient.Call function to add the username and password headers if they are not empty in the struct.
3. Modified the JSONRPCClient.sendBatch function to add the username and password headers if they are not empty in the struct.
4. Removed the parseRemoteAddr, toClientAddress, toClientAddrAndParse functions and replaced their functionality with a natively parsed "parsedURL" struct and associated functions. This allows the username and password to be extracted from the URL string during parsing and be placed in the struct. The previous method of returning strings was not flexible enough for this.

Changes in ws_client.go:
1. Modified NewWSClient to use the new parsedURL struct and functions.

Test functions were modified so "//" is prefixed when a testing HTTP server address is handed over. The net/url package adheres to some rfc which defines valid address as `//192.168.0.1:443` or such, instead of `192.168.0.1:443`. (not a problem with domain names)

Additional testing was done by building a GaiaCLI with the modified tendermint vendor package and running it on a live network with an nginx server providing the server-side of TLS encryption and user authentication. Worked fine.

**Comment by greg-szabo** [comment]
I've opened the change against master. It's the same functionality that was implemented for the backported version.

**Comment by greg-szabo** [comment]
Anton requested to make the default protocol HTTP, instead of TCP in `JSONRPClient`, when a protocol is not defined. This is a breaking change in some obscure cases.

In the current test implementations, addresses seem to be written with the `tcp://` prefix (or no prefix which defaults to tcp) and the underlying code changes it to `http://` where it is necessary. All test code rely on this assumption.

I'm expecting other developers and other chains to rely on this assumption too. If we change the default to HTTP, we might break other developers' work for not much benefit.

The benefit of defaulting to HTTP would be at the end-user, who wouldn't need to type out `http://` but currently, it is mandatory to add a protocol in the URL at a higher level of the code - so end-users will not benefit from this change. (Also, end-users should use TLS and the `https://` prefix.)

I can implement this change in an additional commit in this same PR but currently, I'm leaning toward opposing this change.

@melekes Please add your thoughts.

**Comment by greg-szabo** [comment]
I think I can formalize the breaking change a bit better now, after some testing.

Original behaviour:
If an address starts with `tcp://`, it will automatically be converted to `http://` where necessary. (For example when opening the RPC connection.)

New behaviour:
If an address starts with `tcp://`, it will not be converted. This leads to errors. Easiest example is the `rpc/lib/rpc_test.go` tests, specifically the `TestServersAndClientsBasic` test. The address is hard-wired as `tcp://0.0.0.0:47768` which makes the test fail with the new behaviour.

In the PR, I've changed the constant to `http://0.0.0.0:47768` which should make it pass (still testing). Developers will need to understand that from now on adding `tcp://` will not work for JSONRPC. Which seems counterintuitive.

**Comment by melekes** [comment]
So looks like there are downsides, but no upsides except maybe less complicated code. It seems that we shouldn't do it then. Thank you for laying it out Greg and for your work 👍

**Comment by greg-szabo** [comment]
Thanks. I'll remove that commit then.

I went down the rabbit hole last night trying to fix all tests and somewhere in lite/proxy there's a call that's breaking because of the new default. (Some info here: https://circleci.com/gh/tendermint/tendermint/86670?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
Then, I fell asleep. I'm glad I don't have to go back to that rabbit hole.
