### ISSUE TITLE
Gaiad Requires Local PK while key is available via HSM

### ISSUE THREAD

**Issue by gaia** [tendermint/tendermint#4249]
**ABCI app** (name for built-in, URL for self-written if it's publicly available):

gaiad

**Environment**:
- **OS**
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**What happened**:

Gaiad Requires Local PK although it is using tmkms

## Summary of Bug

I have

`#priv_validator_key_file = "config/priv_validator_key.json"`
along with
`priv_validator_laddr = "tcp://x.x.x.x:yyyyy"`
in place.

A gaiad restart creates another priv_validator_key.json, which caused problems until I just left the actual key in there. The HSM is signing fine.

There is no reason to leave the key in the node when you have in HSM. I must be doing something wrong. How do I tell gaiad that the PK is nowhere local?!

## Version

```
name: gaia
server_name: gaiad
client_name: gaiacli
version: 2.0.3
commit: 2f6783e298f25ff4e12cb84549777053ab88749a
build_tags: netgo,ledger
go: go version go1.13.1 linux/amd64
```
**What you expected to happen**:

Gaiad to not create priv_validator_key.json when using an HSM for signing.

**Have you tried the latest version**: yes

PS: I was told [tendermint is the place for this issue](https://github.com/cosmos/gaia/issues/231).

**Comment by zmanian** [comment]
I believe a stubkey file is still required but that keyfile can just have random bytes in it. 

The validator address etc will be computed from the values from the tmkms.

You can submit a PR to not autogenerate this file if the tmkms is configured.

**Comment by gaia** [comment]
So it is ok to let the file be autogenerated with a random key! I will look into a PR. Thank you.

**Comment by gaia** [comment]
Solved. It is supposed to create a random PK. In the future it might not. See https://github.com/tendermint/tendermint/issues/4249#event-2890583603
