### ISSUE TITLE
Improve rpc client subscribe capacity

### ISSUE THREAD

**Issue by NicolasMahe** [tendermint/tendermint#4256]
I had some issue with the implementation of the event subscriber of tendermint: not all events are received when many transaction are executed in the same block. Actually, something like 2 to 5 events are received instead of 10.

The rpc client function subscriber offers a `outCapacity` option with a default of 1.
Unfortunately, the `Local.Subscribe` implementation doesn't pass `outCapacity` to `EventBus.Subscribe` that is using `pubsub.Subscribe` and thus is still using the its own default value (also 1):
https://github.com/tendermint/tendermint/blob/7b67ee408bb198574863f6acec6f3c791a4c0385/rpc/client/localclient.go#L164-L183
https://github.com/tendermint/tendermint/blob/7b67ee408bb198574863f6acec6f3c791a4c0385/libs/pubsub/pubsub.go#L141-L159

The problem with a capacity of only 1 is, it's impossible to process the events fast enough, even by delegating the event to a new go routine. Even worst, the events are discarded when the chan reach its max capacity:
https://github.com/tendermint/tendermint/blob/7b67ee408bb198574863f6acec6f3c791a4c0385/libs/pubsub/pubsub.go#L400-L419

I think the `outCapacity` from `Local.Subscribe` should be also passed to `EventBus.Subscribe` to force both the event bus and the returned chan to have the same capacity. Eg:
```go
 func (c *Local) Subscribe(ctx context.Context, subscriber, query string, outCapacity ...int) (out <-chan ctypes.ResultEvent, err error) { 
 	q, err := tmquery.New(query) 
 	if err != nil { 
 		return nil, errors.Wrap(err, "failed to parse query") 
 	} 
 	sub, err := c.EventBus.Subscribe(ctx, subscriber, q, outCapacity...)
```
Will you accept this modification? Or is there any reason not to do it?

---

In my project we start Tendermint in the same process, and we prefer to use an unbuffered chan.
`Local.Subscribe` doesn't offer the option to use an unbuffered chan, the underlying function `pubsub.Subscribe` returns an error if capacity is zero and say to use the function [`EventBus.SubscribeUnbuffered`](https://github.com/tendermint/tendermint/blob/72785a2e86256b2e514436f6d67a545bd1572454/types/event_bus.go#L77-L81).

So we got ride of `Local.Subscribe` to directly use [`EventBus.SubscribeUnbuffered`](https://github.com/mesg-foundation/engine/blob/71e536d74389f09d5012d0be8b484948d788a54b/cosmos/client.go#L134) in PR https://github.com/mesg-foundation/engine/pull/1556 but we had to implement the same logic as `Local.Subscribe`.

I think it will be nice to have a `Local.SubscribeUnbuffered` function in the client, or change `Local.Subscribe` implementation to manage capacity of zero properly. What do you think?

---

Related to similar issues:
- https://github.com/tendermint/tendermint/issues/4156
- https://github.com/tendermint/tendermint/issues/3935
- https://github.com/mesg-foundation/engine/issues/1538

**Comment by melekes** [comment]
> I think the outCapacity from Local.Subscribe should be also passed to EventBus.Subscribe to force both the event bus and the returned chan to have the same capacity. Eg:

Agree

> Will you accept this modification? Or is there any reason not to do it?

Yes, we will.

So it looks like we should

a) pass `outCapacity` to Subscribe in `Local#Subscribe`
b) if `outCapacity` is 0, use `SubscribeUnbuffered` in `Local#Subscribe`
