### ISSUE TITLE
LCD: validatorsets/latests hangs until a new block is created

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#4280]
This problem has surfaced in our own zone (e-money), which features on-demand block generation with 60 second heartbeat blocks.

See https://github.com/e-money/em-ledger/issues/2 for prior discussion.

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.32.6

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
any

**What happened**:
Running "gaiacli rest-server" and querying "validatorsets/latest" results in a hang until a new block is generated.

This is seems due to https://github.com/tendermint/tendermint/blob/c4ba93a1e6d62b480adb178bb0f9c8d5c6f67717/rpc/core/consensus.go#L53 and passing in nil heightPtr.

**What you expected to happen**:
The validator set for the current (latest) block height should be immediately returned instead of waiting for the next block. 

**How to reproduce it** (as minimally and precisely as possible):
Run a local "gaiacli rest-server" and curl localhost:3317/validatorsets/latest.

This will hang until a new block is created, so up to 5-6 seconds depending on your timing. For our em-ledger zone, this is up to 1 minute.

**Comment by melekes** [comment]
Is it possible to replicate this with raw Tendermint?

**Comment by mdyring** [comment]
Can you clarify what you mean by "raw Tendermint"?

AFAICS the culprit is in the Tendermint codebase:
https://github.com/tendermint/tendermint/blob/c4ba93a1e6d62b480adb178bb0f9c8d5c6f67717/rpc/core/consensus.go#L56

**Comment by melekes** [comment]
I meant this repo. okay, thanks for pointing to the concrete line

**Comment by melekes** [comment]
will be solved by https://github.com/tendermint/tendermint/issues/3161

**Comment by melekes** [comment]
Closing in favor of #3161
