### ISSUE TITLE
Crash on startup: error decoding 'consensus.create_empty_blocks_interval': time: invalid duration 

### ISSUE THREAD

**Issue by Ekliptor** [tendermint/tendermint#4286]
tendermint version0.32.8-7d7b47a3 compiled from github source

**ABCI app**:
Using the go Sample from here: https://docs.tendermint.com/master/guides/go.html

**Environment**:
Mac OS 10.15.2 (19C57)
go version go1.13.5 darwin/amd64
abci-cli version 0.16.1
go.mod:
```
module github.com/tendermint/tendermint

go 1.13

require (
	github.com/ChainSafe/go-schnorrkel v0.0.0-20191204112926-74e22bf42a85
	github.com/VividCortex/gohistogram v1.0.0 // indirect
	github.com/Workiva/go-datastructures v1.0.50
	github.com/btcsuite/btcd v0.0.0-20190115013929-ed77733ec07d
	github.com/btcsuite/btcutil v0.0.0-20180706230648-ab6388e0c60a
	github.com/fortytw2/leaktest v1.3.0
	github.com/go-kit/kit v0.9.0
	github.com/go-logfmt/logfmt v0.4.0
	github.com/gogo/protobuf v1.3.1
	github.com/golang/protobuf v1.3.2
	github.com/google/gofuzz v1.0.0 // indirect
	github.com/gorilla/websocket v1.4.1
	github.com/gtank/merlin v0.1.1-0.20191105220539-8318aed1a79f
	github.com/inconshreveable/mousetrap v1.0.0 // indirect
	github.com/libp2p/go-buffer-pool v0.0.2
	github.com/magiconair/properties v1.8.1
	github.com/mitchellh/gox v1.0.1 // indirect
	github.com/pkg/errors v0.8.1
	github.com/prometheus/client_golang v0.9.3
	github.com/rcrowley/go-metrics v0.0.0-20180503174638-e2704e165165
	github.com/rs/cors v1.7.0
	github.com/snikch/goodman v0.0.0-20171125024755-10e37e294daa
	github.com/spf13/cobra v0.0.1
	github.com/spf13/viper v1.6.1
	github.com/square/certstrap v1.2.0 // indirect
	github.com/stretchr/testify v1.4.0
	github.com/stumble/gorocksdb v0.0.3 // indirect
	github.com/tendermint/go-amino v0.14.1
	github.com/tendermint/tm-db v0.3.0
	golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
	golang.org/x/net v0.0.0-20190628185345-da137c7871d7
	golang.org/x/sys v0.0.0-20190813064441-fde4db37ae7a // indirect
	google.golang.org/genproto v0.0.0-20191230161307-f3c370f40bfb // indirect
	google.golang.org/grpc v1.26.0
)
```

**What happened**:
The app crashes during startup with the following log:
```
TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" tendermint node --proxy_app=unix:///Users/daniel/go/src/github.com/kvstore/example.sock

ERROR: 1 error(s) decoding:

* error decoding 'consensus.create_empty_blocks_interval': time: invalid duration 
```

The kvstore sample ABCI application has no errors in the log:
```
I[2020-01-07|13:13:46.703] Starting ABCIServer                          impl=ABCIServer
I[2020-01-07|13:13:46.704] Waiting for new connection...   
```

**Comment by melekes** [comment]
Could you please paste the content of `config.toml` file?

**Comment by Ekliptor** [comment]
I don't have a `config.toml` in `TMHOME="/Users/daniel/go/src/github.com/tendermint/thome"` because the app crashes before it creates the `thome` folder. Only the `tendermint` dir above exists. So it's likely using default settings.

**Comment by Ekliptor** [comment]
Any idea?
Or if you can provide me with a link to a more recent example app than the `kvstore` I assume this will also fix the issue.

**Comment by melekes** [comment]
Can't replicate.

My go.mod file:

```
root@46eacc317864:/go/src/github.com/me/kvstore# cat go.mod
module github.com/me/example

go 1.13

require (
        github.com/dgraph-io/badger v1.6.0
        github.com/tendermint/tendermint v0.32.9
)
```

**Comment by melekes** [comment]
> I don't have a config.toml in TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" because the app crashes before it creates the thome folder. Only the tendermint dir above exists. So it's likely using default settings.

Have you executed `tendermint init`?

```
To create a default configuration, nodeKey and private validator files, let's execute tendermint init. But before we do that, we will need to install Tendermint Core.

$ rm -rf /tmp/example
$ TMHOME="/tmp/example" tendermint init
```

**Comment by Ekliptor** [comment]
After running tendermint init I get exaclty my previous error again, so seems this was not fixed: https://github.com/tendermint/tendermint/issues/4277

kvstore log:
`error="error reading message: proto: wrong wireType = 2 for field NumTxs"`

tendermint log:
```
TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" tendermint node --proxy_app=unix:///Users/daniel/go/src/github.com/kvstore/example.sock
I[2020-01-13|21:30:24.397] Version info                                 module=main software=0.32.8 block=10 p2p=7
I[2020-01-13|21:30:24.419] Starting Node                                module=main impl=Node
I[2020-01-13|21:30:24.428] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:0} DefaultNodeID:c9858cf0db2254fae29dcb56fff123971c7ffa30 ListenAddr:tcp://0.0.0.0:26656 Network:test-chain-6KbZMU Version:0.32.8 Channels:4020212223303800 Moniker:MacBook-Pro.local Other:{TxIndex:on RPCAddress:tcp://127.0.0.1:26657}}"
E[2020-01-13|21:30:25.492] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
E[2020-01-13|21:30:25.492] Error in proxyAppConn.BeginBlock             module=state err=EOF
E[2020-01-13|21:30:25.492] Error on ApplyBlock. Did the application crash? Please restart tendermint module=consensus err=EOF
I[2020-01-13|21:30:25.492] captured terminated, exiting...              module=main 
I[2020-01-13|21:30:25.492] Stopping Node                                module=main impl=Node
I[2020-01-13|21:30:25.492] Stopping Node                                module=main 
E[2020-01-13|21:30:25.492] Not stopping BlockPool -- have not been started yet module=blockchain impl=BlockPool
E[2020-01-13|21:30:25.493] Stopped accept routine, as transport is closed module=p2p numPeers=0
I[2020-01-13|21:30:25.492] Closing rpc listener                         module=main listener="&{Listener:0xc00000de00 sem:0xc0007cdb00 closeOnce:{done:0 m:{state:0 sema:0}} done:0xc0007cdb60}"
```

The requested `config.toml` file: https://pastebin.com/hwNeErQZ

**Comment by melekes** [comment]
I'd recommend to do `tendermint unsafe_reset_all` (resets all the data and validator) and use go.mod file from https://github.com/tendermint/tendermint/issues/4286#issuecomment-573630461.

**Comment by Ekliptor** [comment]
Still the same error.
I removed my tendermint src and made a fresh dir with `git clone`.

Also I ran the suggested `tendermint unsafe_reset_all` (before removing the git dir and after a fresh build before start).

These are my commands i used to build tendermint:
```
make tools
make install
make install_abci
make install protoc_abci
make build # put binary into ./build instead of $GOPATH/bin
TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" tendermint init
TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" tendermint node --proxy_app=unix:///Users/daniel/go/src/github.com/kvstore/example.sock
```

and for `kvstore`:
```
go mod init kvstore # complained that go.mod already existed because i used the one you linked
go build
./kvstore
```

Any ideas?

**Comment by melekes** [comment]
> The kvstore example on github to clone might help.

noted

> Also I ran the suggested tendermint unsafe_reset_all (before removing the git dir and after a fresh build before start).

```
TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" tendermint unsafe_reset_all
```

just to be sure you ran ^ (with TMHOME)?

**Comment by Ekliptor** [comment]
thx for all your quick help.

The above command doesn't help, same error. When I deleted my tendermint repo it also deleted thome which is a subdirectory of it.

**Comment by melekes** [comment]
We removed `NumTxs` field a while ago.

**Comment by Ekliptor** [comment]
Just saw it too in the changelog. So why is my sample app from here trying to read it?
https://docs.tendermint.com/master/guides/go.html

I don't see `NumTxs` in my `kvstore` app code: https://pastebin.com/MRsdyWRq

**Comment by melekes** [comment]
for me, it looks like your application is using outdated Tendermint verstion (e.g. v0.32.8) while Tendermint you're running is latest (master)

**Comment by Ekliptor** [comment]
True .I am running the latest github master branch. And according to this line it is v0.32.8: https://github.com/tendermint/tendermint/blob/master/version/version.go#L23

That's also what I get from:
```
./build/tendermint version
0.32.8-a3a09285
```
However the Changelog.md file says `v0.32.9`

Should I use another version than the above linked master branch?

**Comment by melekes** [comment]
> Should I use another version than the above linked master branch?

make sure you're using 0.32.9 in your app and have 0.32.9 installed on your machine.

**Comment by Ekliptor** [comment]
That second line was the solution 👯‍♂ 

```
git clone https://github.com/tendermint/tendermint
git checkout v0.32.9
```

```
I[2020-01-14|19:52:34.558] Committed state                              module=state height=6 txs=0 appHash=
I[2020-01-14|19:52:35.600] Executed block                               module=state height=7 validTxs=0 invalidTxs=0
```

I was compiling the mater branch which didn't have `NumTxs` anymore as you said.
