### ISSUE TITLE
proto: Use linting,  breakage checking & gogoslick or gogofaster

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4288]
1. Use [buf](https://github.com/bufbuild/buf) https://buf.build/ to add linting and breaking change detection in ci.
   - ref #4078 
   - this would further deprecate GOPATH as we would use go mod vendor instead

2. move from `gogo` to `gogoslick` or `gogofaster` in the proto stub generation
   - protoc-gen-gogofaster (same as gogofast, without XXX_unrecognized, less pointer fields)
   - protoc-gen-gogoslick (same as gogofaster, but with generated string, gostring and equal methods)
the second proposal is aimed at starting to create types in proto. 

If we get rid of the XXX fields then they should be amino compatible and would not be breaking changes. 

@ebuchman @melekes thoughts on this?

**Comment by melekes** [comment]
Strongly in favor 👍 However we may be relaying on some features of `gogo`, which might prevent us from switching to `gogoslick` / `gogofaster`.

**Comment by marbar3778** [comment]
#4304 is ready to merge and I have a different branch with breaking changes. I was thinking of using one branch to merge all the breaking proto work into. @melekes thoughts?

**Comment by melekes** [comment]
fine by me

**Comment by marbar3778** [comment]
part 1 of this issue is completed, part 2 is ongoing

**Comment by marbar3778** [comment]
In the last tendermint dev call we decided to move away from gogoproto and use vanilla go protobuf. This issue can be closed. Will open a new one to track the move to vanilla
