### ISSUE TITLE
Node ID in show-node-id vs RPC/status

### ISSUE THREAD

**Issue by gaia** [tendermint/tendermint#4290]
**ABCI app** Terra 0.3.1

**Environment**:
- **OS**: Ubuntu 18.04.3 LTS
- **Install tools**: static binary

**What happened**:

`terrad tendermint show-node-id`: aaaaa
`curl -s -H "Connection: close" "http://127.0.0.1:27657/status" | jq '.result[].id'`: bbbb

**What you expected to happen**:
The ID to be the same

**Have you tried the latest version**: yes

**Comment by melekes** [comment]
How can we replicate?

**Comment by gaia** [comment]
I've decommissioned the machine where this was happening. would you like access to it?

**Comment by melekes** [comment]
Yes please

**Comment by gaia** [comment]
@melekes sent you login info via keybase. node had been stopped around 346000, it is now catching up.

**Comment by gaia** [comment]
reminder. this box will be shut off in a couple of days.

**Comment by melekes** [comment]
Can't replicate locally. Probably a bug in configuration.
