### ISSUE TITLE
Peer connection should have failure detector

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#430]
@srm found a situation where the connections somehow all died silently, and the consensus reactor is silent, and a mempool tx keeps looping in broadcastTxRoutine() every 10 seconds (or defaultSendTimeoutSeconds seconds).

(a) This node should have detected peer connection failure (e.g. pong didn't come back in time).
(b) Then, it should have restarted failed peer connections.

(b) needs to be implemented, but why didn't (a) happen?

**Comment by ebuchman** [comment]
(b) is fixed by https://github.com/tendermint/go-p2p/pull/18

Not sure about (a). Can we close this and re-open if we find the issue again? Or did that somehow get fixed in the mix of implementing (b)?

**Comment by adrianbrink** [comment]
Closed based in Bucky's comment.
