### ISSUE TITLE
tendermint node: show useful error when tendermint has not been initialised

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4303]
https://github.com/tendermint/tendermint/issues/4286

```
TMHOME="/Users/daniel/go/src/github.com/tendermint/thome" tendermint node --proxy_app=unix:///Users/daniel/go/src/github.com/kvstore/example.sock

ERROR: 1 error(s) decoding:

* error decoding 'consensus.create_empty_blocks_interval': time: invalid duration 
```

We should output more useful error instead of ^ for better usability.

**Comment by SomeMoosery** [comment]
This would be my first issue but I can take a look into this and see if I can come up with a PR shortly!

**Comment by SomeMoosery** [comment]
[https://github.com/tendermint/tendermint/pull/4312](PR here)!

**Comment by melekes** [comment]
Question: should we initialize Tendermint instead of showing an error?

pros:
- users don't have to call `tendermint init`

cons:
- potential errors due to misconfiguration (e.g. configuration exists in DIR1, but TM_HOME=DIR2 was used in command line => new configuration created)

**Comment by erikgrinaker** [comment]
I think we should throw a hard error. Explicit is better than implicit, and this is something that would be done rarely.
