### ISSUE TITLE
How to decode string value in ABCI query using Go 

### ISSUE THREAD

**Issue by dstreppa** [tendermint/tendermint#4309]
Hi to all,
as explained here https://tendermint.readthedocs.io/en/v0.11.0/getting-started.html, when I do a ABCI query in a kvstore application I receive in the JSON response the encoded string value.
How can I decode the string in Go? In the doc there is only Python2 example: `"61626364".decode('hex'). `

For completeness, in Python3 I decoded everything with the following command: `codecs.decode(resp['result']['response']['value'].encode(), 'base64').decode('ascii')`

Thank you for the help.

**Comment by marbar3778** [comment]
https://docs.tendermint.com/ here are the updated docs, the version you are looking at is heavily outdated

**Comment by melekes** [comment]
Removed https://tendermint.readthedocs.io/.

As for your question, it's base64 encoded, so the way to do it in Go:

```go
decoded, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		fmt.Println("decode error:", err)
		return
	}
```

**Comment by dstreppa** [comment]
Yes, thank you very much. It works :+1:
