### ISSUE TITLE
Explicit --data flag instead of `~/.tendermint`

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#431]
jae:
```
really ~/.tendermint is just a bad idea
it used to make sense when we wanted tendermint to be a blockchain.
now it doesn’t.
```

**Comment by ebuchman** [comment]
TMROOT -> TMHOME

**Comment by melekes** [comment]
[patch.zip](https://github.com/tendermint/tendermint/files/872537/patch.zip)

Patch for #419 which adds `data` flag

**Comment by ethanfrey** [comment]
@ebuchman I don't know the decision. Is this fixed on develop with the - - root and - - home and TMROOT and TMHOME variables? 

Or is this one to make them required?

**Comment by adrianbrink** [comment]
We now have `--home`.
