### ISSUE TITLE
config: `RPCConfig.GRPCMaxOpenConnections` does absolutely nothing

### ISSUE THREAD

**Issue by Yawning** [tendermint/tendermint#4311]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

Anything and everything starting at 1e3469789dce5a034a21b6e48288f1809a102595 .

**What happened**:

I looked at how the number of connections can be limited.

**What you expected to happen**:

`RPCConfig.GRPCMaxOpenConnections` to actually be used when instantiating the gRPC server.

**How to reproduce it** (as minimally and precisely as possible):

```
arnhem :: Documents/Development/tendermint ‹master› % ag GRPCMaxOpenConnections
config/toml.go
174:grpc_max_open_connections = {{ .RPC.GRPCMaxOpenConnections }}

config/config.go
335:	GRPCMaxOpenConnections int `mapstructure:"grpc_max_open_connections"`
398:		GRPCMaxOpenConnections: 900,
427:	if cfg.GRPCMaxOpenConnections < 0 {

config/config_test.go
71:		"GRPCMaxOpenConnections",
arnhem :: Documents/Development/tendermint ‹master› %
```                   

Alternatively look at the offending commit.
```
-               listener, err := rpcserver.Listen(
-                       grpcListenAddr, rpcserver.Config{MaxOpenConnections: n.config.RPC.GRPCMaxOpenConnections})
+               config := rpcserver.DefaultConfig()
+               config.MaxOpenConnections = n.config.RPC.MaxOpenConnections
+               listener, err := rpcserver.Listen(grpcListenAddr, config)
```

**Comment by melekes** [comment]
Do you want to help us fix this?

**Comment by Yawning** [comment]
> Do you want to help us fix this?

It's a one line (4 character) fix.
