### ISSUE TITLE
add continuous profiling

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4314]
Add a library like: https://github.com/profefe/profefe to be used as continuous profiling on nodes.

This can be a config bool similar to Prometheus in the config in which when true it exposes a port to listen for continuous profiling.

**Comment by melekes** [comment]
We're already exposing pprof server, so it's possible to download profiling data at any point. 

`tendermint debug` tool can be used to continuously collect data. We just haven't written any documentation/tutorials for it.

**Comment by marbar3778** [comment]
ah okay, didnt know this, I will make an issue for crating docs on this
