### ISSUE TITLE
Update js-abci || remove it from the docs

### ISSUE THREAD

**Issue by alex-ppg** [tendermint/tendermint#4333]
I am using the latest Tendermint version as downloaded from the pre-built binaries, however it fails to auto-mine any blocks at all. I followed the single node tutorial and used an ABCI app I had developed in the past that used to work but no blocks are auto-mined whatsoever, even after an `unsafe_reset_all` execution. I would appreciate any help with this. All types of RPC calls also fail due to this issue as transactions are never mined. My operating system is Ubuntu 16.04 on Windows Subsystem for Linux.

**Comment by marbar3778** [comment]
I am not able to recreate this issue locally. Have you tried removing the .tendermint dir as there are new things and the config most also be regenerated? 

my attempt to recreate:
```
rm -rf ~/.tendermint
make install // 0.33
tendermint init
tendermint node --proxy_app=counter
```

**Comment by alex-ppg** [comment]
It appears that downgrading to version 0.26.0 fixed the issue, is the `js-abci` library incompatible with the latest version? It hasn't received an update in a year from what I see on the repository.

**Comment by marbar3778** [comment]
ah yes, that would be correct the js-abci is not actively maintained.

**Comment by alex-ppg** [comment]
If that's the case, it should be removed from [the app-dev documentation](https://github.com/tendermint/tendermint/blob/master/docs/app-dev/getting-started.md).

**Comment by marbar3778** [comment]
I just pinged our js devs to see if they want to take a stab at updating the repo or if they know any other js-abci libs. I will update you when i get a response

**Comment by marbar3778** [comment]
js-abci has recently been updated to the new proto files, you should be able to use it now 😄 let me know if any issues arise
