### ISSUE TITLE
lite2: swap primary with alternative when the former is unavailable

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4338]
In cases where primary provider crashed (i.e. not responding for some period of time), we should swap it with one of the alternative providers.

**Comment by melekes** [comment]
More info on desired implementation:

after the light client is started, every time we try to access the primary, we should 

a) retry say 5 times (exponential retry with jitter)
b) if it fails, we swap the primary with one of the witnesses (alternative providers) and retry again

**Comment by cmwaters** [comment]
Q: If we swap out the primary, should we append it to the end of the alternatives slice or just remove it completely?

**Comment by melekes** [comment]
Remove because it's not responding imho.

**Comment by cmwaters** [comment]
Yes, okay, I would agree.
