### ISSUE TITLE
proposal: remove "cli" Suffix from Executables

### ISSUE THREAD

**Issue by ghost** [tendermint/tendermint#4339]
this "cli" suffix is everywhere, e.g. `agci-cli`.

The team should possibly decide to strip the "cli" suffixes everywhere (standard-naming), before the system becomes more mainstream.

related: cosmos/gaia#26).

**Comment by melekes** [comment]
I am in favor.

**Comment by tessr** [comment]
I think the only instance of `-cli` in the tendermint/tendermint repo is `abci-cli`, and I'm ambivalent about renaming it. While it does seem redundant to have `cli` in the name, it's nice to be able differentiate the command line tool from ABCI itself.
