### ISSUE TITLE
lite2: check witnesses are on the same chain as primary upon startup

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4350]
If not, the light client should return an error.

**Comment by cmwaters** [comment]
Q: At the moment the function to compare the new header with a random witness is optional, do we want to enforce this by requiring at least one responsive additional witness else the lite client throws an error. Is cross comparison of headers an essential part of the `VerifyHeader` algorithm?
Perhaps this should be a different issue

**Comment by melekes** [comment]
> Perhaps this should be a different issue

It is
