### ISSUE TITLE
BFT time can move backwards

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#4351]
Checked against master branch:

There is no logic to ensure the the current block header timestamp (returned by MedianTime) is not before the previous one: blocks could potentially go _Back To The Future_.

https://github.com/tendermint/tendermint/blob/6f93cfa54850144199b17475857e7fc66c20378e/state/state.go#L147

Under the "right" circumstances MedianTime can return a timestamp that is before the previous block:

* Shifts in voting power can move the VP-weighted median time backwards 
* Coordination among +1/3 of VP

This is important as ABCI applications might use the block time as a reliable time source for any number of calculation, such as Cosmos SDK:
* Staking module
* Bank module (delegations and vesting accounts)
* Governance (deadlines)
* Vesting Accounts 
 
Having this property is also desirable for IBC clock based timeouts: https://github.com/cosmos/ics/issues/353 

I'll open a PR shortly that addresses this with a simple fix.

**Comment by melekes** [comment]
> There is no logic to ensure the the current block header timestamp (returned by MedianTime) is not before the previous one: blocks could potentially go Back To The Future.

https://github.com/tendermint/tendermint/blob/c5ecd802a22f82b0a4787c68d749fbc1da682306/state/validation.go#L100

**Comment by mdyring** [comment]
Ooops. Thanks @melekes, happy to be proven wrong :-)

Closing.
