### ISSUE TITLE
RPC Endpoint to emit TrustOptions

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#4357]
Ideally there should be an endpoint where tendermint serves block headers needed for lite client initialization. The format could be as follows:
```json
[
  {
    "hash": "{{header}}",
    "trust-period": "2w",
    "height": 1200923,
  }
]
```

**Comment by melekes** [comment]
what should be the source of `trust-period`? 

Maybe it should come from whomever calls Tendermint (and uses light client). Then Tendermint only will need to return `hash` and `height`? If so, these two are already available in https://docs.tendermint.com/master/rpc/#/Info/commit endpoint.

**Comment by melekes** [comment]
Duplicate of https://github.com/tendermint/tendermint/issues/4393
