### ISSUE TITLE
Candidates for Refactoring

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#4360]
This is a tracking issue for the components which are considered refactoring candidates, per the 2020 Roadmap (to be published shortly). 

Note that these are _candidates_, and many of them need to be "evaluated" before any refactoring is planned--if any at all. 

### Consensus Reactor: 
- See https://github.com/tendermint/tendermint/issues/3366
- Assessment complete 
- Spec and ADR complete: https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-030-consensus-refactor.md 
- Implementation Phases: TODO 
    - Phase 1: Isolation of the consensus algorithm into a pure function & a finite state machine.
    - Phase 2:  Replace calls in Consensus.State with calls to the new Function
    - Phase 3:  Propose a design for improved separation and information flow between the state machine and the reactor

### P2P Module: 
- See https://github.com/tendermint/tendermint/issues/2067
- Assessment, spec, ADR, implementation TODO 
- Assessment will also include evaluating available libraries against our current requirements

### RPC Module: 
- See https://github.com/tendermint/tendermint/issues/3367
- Assessment, spec, ADR, implementation TODO

### Evidence Module: 
- See https://github.com/tendermint/tendermint/issues?q=is%3Aissue+is%3Aopen+label%3Aevidence
- Needs to be assessed for refactoring; may happen as part of the new evidence handling work (explained in further detail on the roadmap).

**Comment by lazaridiscom** [comment]
You don't talk Refactoring for 2 years. You just do it, in tiny steps.

**Comment by lazaridiscom** [comment]
curious: does this folks here; https://informal.systems plan to re-implement tendermint in rust?

**Comment by lazaridiscom** [comment]
@tessr , some more comments here: https://medium.com/p/b4709134cff1/responses/show

**Comment by cmwaters** [comment]
I'm closing this as being an outdated issue that doesn't accurately reflect the current landscape. For the refactor on the P2P service please see: https://github.com/tendermint/tendermint/issues/5670
