### ISSUE TITLE
p2p: Secret Connection Peer Identity Filtering Support

### ISSUE THREAD

**Issue by iramiller** [tendermint/tendermint#4363]
Within the peer to peer network transport there is currently support for filtering connections based on network level data prior to establishing a secure connection.  This proposal is for providing a similar extension point for filtering connections based on the public key provided during the secure connection upgrade process.

**Connection Filter**
```golang
type ConnFilterFunc func(ConnSet, net.Conn, []net.IP) error
```

**Filter Invocation Point For Inbound Connections**
```golang
err := mt.filterConn(c)
if err == nil {
    secretConn, nodeInfo, err = mt.upgrade(c, nil)
    if err == nil {
        addr := c.RemoteAddr()
        id := PubKeyToID(secretConn.RemotePubKey())
        netAddr = NewNetAddress(id, addr)
    }
}
```
https://github.com/tendermint/tendermint/blob/ca03e43d931bf64e455b182164b302234dbd030a/p2p/transport.go#L298

**Filter Invocation Point for Outbound Connections**
```
// TODO(xla): Evaluate if we should apply filters if we explicitly dial.
if err := mt.filterConn(c); err != nil {
	return nil, err
}
```
https://github.com/tendermint/tendermint/blob/ca03e43d931bf64e455b182164b302234dbd030a/p2p/transport.go#L213

### MultiplexTransportIdentityFilters(filters...IdentityFilterFunc)
The public key filter support can be provided through the same style of interface as the current connection filter extensions.  This would provide a consistent style of integration that would be familiar to developers working in the code base.

### Rational
The primary reason to add support for filtering based on identity is to provide support for network restriction and security.  As an example the Hyperledger Burrow project currently implements a restricted node lists to filter responses within the ABCI application but can not extend these filters to the peer network connectivity itself.

Another example use case of this feature would be to limit inter peer connectivity to a small set of known identities either to exclude these identities for bad behavior or to exclusively connect to these peers as part of a private security network.  While network level controls could certainly be applied for whitelist/blacklist filtering the use of the actual node public key is far more flexible and useful in cloud environments where the network configuration is dynamic.

**Additional Notes**
The use of an extension point shifts the design burden for implementation onto the application using Tendermint limiting the impact to the Tendermint codebase itself.  The limited amount of code changes would be straight forward to cover in unit tests.  A simple identity function that allows all public keys presented could be provided as a straight forward example of using this extension point.

### Suggested Changes

1. Extend MultiplexTransport struct to include identity filters support

```golang
type MultiplexTransport struct {
	netAddr  NetAddress
	listener net.Listener

	[...]

	// Lookup table for duplicate ip and id checks.
	conns       ConnSet
	connFilters []ConnFilterFunc
	// Filter set to restrict secure connections based on identity
	identityFilters []IdentityFilterFunc

	[...]
}
```

2. Add an idnetity filter hook signature

```golang
type IdentityFilterFunc func(remoteNetAddr, remotePubKey) error
```

3. Apply the connection identity filter when establishing connections to remote peers both on inbound and outbound connections

4. Provide examples for use of identity filter, test coverage, and related documentation.

**Comment by iramiller** [comment]
Here is the specific peer filtering example from the Burrow project referenced above https://github.com/hyperledger/burrow/commit/27e6a6ff5d7e7cdb172f51f14220757c26d7b113

**Comment by ebuchman** [comment]
Isn't this already supported via the `/p2p/filter/id/<ID>` query endpoint ? Ie see https://docs.tendermint.com/master/spec/abci/apps.html#peer-filtering . Only difference is its the node id (hash of the pubkey) rather than the pubkey ...

**Comment by iramiller** [comment]
That ABCI interface does seem to be roughly what I am after.  I need to review what code exists between the connection establishment and these calls though to be sure. My intent is to limit exposure so I want to review with that in mind. I should be able to follow up later today or tomorrow morning.

**Comment by iramiller** [comment]
This filter approach looks good.  Not sure how I missed it before but happy to see it.
