### ISSUE TITLE
Ordering of transactions in a multi-node network

### ISSUE THREAD

**Issue by PradeepSalanki** [tendermint/tendermint#4367]
Clarification regarding ordering of transactions

With regards to the following issues:
https://github.com/tendermint/tendermint/issues/1064
https://github.com/tendermint/tendermint/issues/1072

Also after going through, https://docs.tendermint.com/master/tendermint-core/mempool.html

Is it correct that the transactions in a block can arrive in any order during CheckTx/ DeliverTx? (if sent over multiple nodes)

What is the correct state of transaction ordering implementation and are there any changes planned(like setting priority to transactions etc)?

How do we implement usecases where tx order matters?

**Comment by melekes** [comment]
CheckTx(Tx) is called a) before Tx enters the mempool b) after Block is committed (recheck), if Tx was not committed, it will be rechecked (https://docs.tendermint.com/master/spec/abci/abci.html#checktx CheckTx_Recheck). 

Transactions in a block are guaranteed to be delivered in order (DeliverTx). Responses from the ABCI app may come out of order.

We're planning to add transaction sorting to mempool and, possibly, give ABCI apps a way to supply their own version of mempool. But I am not sure how long it's going to take.
