### ISSUE TITLE
define/document recommended development setup

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#4368]
We're currently using a mix of modules and GOPATH, and some of our tooling assumes that this repo lives inside the GOPATH. (My understanding is that this is [no longer a best practice](https://blog.golang.org/using-go-modules) with modules.) 

We should figure out a cohesive setup w.r.t. GOPATH, the Tendermint home directory, and dependencies; we should then document it and have our tooling conform to it.

(This issue sponsored by many failed attempts at running protoc.)

**Comment by tessr** [comment]
It seems that protoc and go modules have some compatibility issues, with a solution TBD: 
* https://github.com/golang/protobuf/issues/925 
* https://github.com/golang/protobuf/issues/748

In the meantime, can a few folks who have successfully been generating code from proto files share their "workspace" configuration? (@melekes? @jackzampolin?) We can then update the recommended setup once protoc knows how to work with modules.

**Comment by marbar3778** [comment]
we will begin to use https://github.com/tendermint/tendermint/blob/proto-breakage/buf.yaml for the proto things and this takes awa y the assumption of gopath. And then with this script https://github.com/tendermint/tendermint/blob/proto-breakage/scripts/protocgen.sh we will be free of gopath for protoc cases

**Comment by melekes** [comment]
> In the meantime, can a few folks who have successfully been generating code from proto files share their "workspace" configuration? (@melekes? @jackzampolin?)

I just have Tendermint within my `$GOPATH` (albeit inside a VirtualBox machine).

**Comment by marbar3778** [comment]
Now there is a better story in regard to GOPATH. We support non-GOPATH and GOPATH repo locations. On top of this, for protoc, we provide a docker image to generate the proto stubs. This should elevate the issues that lead to the opening of this issue. 

Would we want to document in more detail or is the contributing document information enough?

**Comment by erikgrinaker** [comment]
I haven't had any Tendermint tooling woes due to `GOPATH` (I don't use `GOPATH` and actively hate it) nor Protobuf compilation for a long time now, so I think can close this. Great work! 🚀
