### ISSUE TITLE
Re-index the tx indexer

### ISSUE THREAD

**Issue by antho1404** [tendermint/tendermint#4371]
Currently, if the configuration for the tx indexer change (eg: `IndexTag = "tx.hash"` to `IndexAllTag = true`)  there is no way to reindex the previous transactions and the indexation will start only when this setting is changed.

It would be nice to at least have a function that re-index all the transactions in the DB. This could be done by iterating on the ones already present (indexed by hash which is the default configuration) and call the `Index` function for each result.

**Comment by melekes** [comment]
The most simple thing to do is probably to add `tendermint tx_index --reindex` subcommand+flag, which would load the config and reindex the database.

**Comment by JayT106** [comment]
I guess this issue can be closed due to the Transaction Indexing specs changes in v0.34.0?

**Comment by antho1404** [comment]
I didn't follow the development closely, but I guess the problem would still occur if the application decides to change from not indexing to indexing. All the previous transactions would not be in the index.

Anyway, feel free to close it if this is something acceptable.

**Comment by JayT106** [comment]
@antho1404 Ah, okay. I am working on a similar issue I think can also fix this case.

**Comment by marbar3778** [comment]
this is solved with #6535. A node operator needs to tell the node to reindex all ABCIResults, if they have them.
