### ISSUE TITLE
discussion: make cmds for terraform and ansible

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4379]
Currently, in the makefile there are commands to help with setup of a sentry architecture.  They are not being maintained and are led to believe that they are not functional. 

https://github.com/tendermint/tendermint/blob/master/Makefile#L180-L198

Going forward would we like to maintain such commands or deprecate and not support such commands?

**Comment by tessr** [comment]
Let's axe 'em. Especially if they don't work.
