### ISSUE TITLE
Broken spec links

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#4381]
Lots of previous documentation made reference to the specs in this repo. Since they've been moved to the spec repo and deleted here, all those links are now broken. They can be found with `ack "docs/spec"`

We should either fix all those links to point to the spec repo and/or add back the old spec directory structure with place holder files telling folks to redirect. Note there's probably other documentation out there that makes reference to those old spec links, so doing both for now might not be a bad idea.

**Comment by marbar3778** [comment]
@erikgrinaker fixed many of them last week in https://github.com/tendermint/tendermint/pull/4376 I just picked up two outstanding in upgrading.md in #4384. we can close this after that is merged
