### ISSUE TITLE
lite2: benchmark bisection & sequential verifications

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4392]
It might be useful to benchmark verification speeds of bisection & sequential algorithms.

Also, we should think if there should be a hybrid mode in the current implementation, which alternates between bisection & sequential verification depending on how far the light client is behind the latest header.

**Comment by cmwaters** [comment]
The problem I see with comparing the speeds is that it's hard to judge how many times the bisection will need to split. If we have a thousand blocks and the validator set is the same all the way through then the bisection algorithm won't split at all and jump immediately to the latest one. Is it possible perhaps to gather how much validator sets change from block to block - could we perhaps use real data from gaia?

**Comment by cmwaters** [comment]
Is there any value in comparing speeds of recursive and non recursive bisection methods

**Comment by melekes** [comment]
> Is there any value in comparing speeds of recursive and non recursive bisection methods

no, but it would be good to benchmark both

**Comment by melekes** [comment]
as a part of this, we should create a new mock provider, which introduces configurable changes into validator set with every block. E.g. vsChangeMock(10) - validator set changes by 10% every block.
