### ISSUE TITLE
rpc: add `/block_hash?height=X` endpoint

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4393]
Right now, in the light client, we're using `/commit` endpoint to get a header X from the full node. But, when cross-checking X with witnesses (read other full nodes), we don't necessary need the whole signed header (unless they diverge which only happens in case of an attack), only block hash to compare it with X#Hash().

Also, we need a similar endpoint in cosmos/relayer to get a "trusted" hash and height from a full node in order to seed a light client instance.

Usage:

```
/block_hash?height=10
{
  "hash": "F8C810CB203F53C567955D8200B347FBF66D13344179A530F83766AE1A205C51",
  "height": 10
}

0 (or no height) gets you the latest block hash

/block_hash?height=0
{
  "hash": "37E9A6DD3FA25E83B22C18835401E8E56088D0D7ABC6FD99FCDC920DD76C1C57",
  "height": 21
}
```

**Comment by erikgrinaker** [comment]
Instead of adding separate RPC endpoints for different data projections, how about adding a `fields` parameter that takes a list of fields to include in the output? E.g.:

```
/commit?height=10&fields=signed_header.header.height,signed_header.header.last_block_id.hash

{
  "jsonrpc": "2.0",
  "id": 0,
  "result": {
    "signed_header": {
      "header": {
        "height": 10,
        "last_block_id": {
          "hash": "F8C810CB203F53C567955D8200B347FBF66D13344179A530F83766AE1A205C51"
        }
      }
    }
  }
}
```

**Comment by melekes** [comment]
I like it! I think we should consider https://graphql.org/ when redesigning our RPC (rpc 2.0). But not sure it's worth trying to implement right now (too much work, no?). What do others think?

**Comment by erikgrinaker** [comment]
GraphQL has a few annoying limitations, like the lack of first-class support for filter predicates, but it may be a good fit for our needs. Not sure if it's worth doing now though.

But what exactly are we optimizing for here? The `/commit` endpoint seems to return responses on the order of kilobytes (?), so the memory overhead is negligible, and the latency will be dominated by the roundtrip time. Is there a problem with simply picking out the fields that we need on the client and ignoring the rest?

**Comment by melekes** [comment]
> But what exactly are we optimizing for here?

mostly amount of information we're requesting & sending.

> Is there a problem with simply picking out the fields that we need on the client and ignoring the rest?

nope

**Comment by melekes** [comment]
I guess the question is: "Is it worth adding & supporting a new endpoint?"

**Comment by erikgrinaker** [comment]
I don't really see any upside here, since we already have an endpoint that's sufficient.

**Comment by melekes** [comment]
Declined.

**Comment by melekes** [comment]
"last_block_id": {
          "hash": "F8C810CB203F53C567955D8200B347FBF66D13344179A530F83766AE1A205C51"
        }

is not what we want! we want a hash from `commit#block_id#hash`, which is the hash of the header/block that it proves. so, how do we expect our users to pick correct hash if we can't do it ourselves.

**Comment by erikgrinaker** [comment]
Documentation? :) I just picked a hash more or less at random, as an example.

**Comment by melekes** [comment]
No, it has to be intuitive...

**Comment by melekes** [comment]
> The /commit endpoint seems to return responses on the order of kilobytes

14KB

"Practically, we send packets sized as the lowest MTU (Maximum Transmission Unit) on the path, which is typically 1500 bytes(for Ethernet) of data including TCP (20 bytes) and IP headers(20 bytes) (*when they don't have options)
The frame header is added too so it's get up to 1518 bytes (with 801.Q it's 1522)."
https://www.quora.com/What-is-a-the-maximum-packet-size-of-a-TCP-packet?share=1

**Comment by erikgrinaker** [comment]
>Practically, we send packets sized as the lowest MTU (Maximum Transmission Unit) on the path, which is typically 1500 bytes

Sure, but latency is dominated by roundtrip times, not packet transmission, and I believe OSes typically have initial sliding window sizes of more than 14 KB such that the entire request/response is processed in one roundtrip (post-handshake).

Anyway, I don't really have a strong opinion here - I just like to keep API surfaces small, to reduce maintenance cost and make them easier to navigate.

**Comment by melekes** [comment]
Okay. Let's punt on it for now.
