### ISSUE TITLE
p2p: notify peers of channel changes

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4394]
With the upcoming state sync feature (#4352) we will need to start a p2p stack with a limited set of reactors (e.g. only state sync and pex), and then enable the full set of reactors once the node is ready. While running a state sync, other peers will think that we are a "normal" peer, and attempt to use services that aren't available.

It would be nice if the node could announce which channels and service are available, so that peers can avoid sending messages to nodes that can't process them. This should probably have some sort of versioning scheme as well, to allow for reactor protocol changes.

**Comment by ebuchman** [comment]
Note we already do announce which channels we run in the handshake, so we can already do things like have a node that only runs PEX for instance, but there's no capability to change channels live. For instance when doing fast sync the consensus reactor is technically still able to process messages but it doesn't really do anything until we call SwitchToConsensus from the blockchain reactor when fast sync is done. So we could do something similar with state sync.

A more thorough approach would probably require significant refactoring to enable us to start a reactor at any arbitrary point ...

**Comment by erikgrinaker** [comment]
I see. I was hoping we could decouple the initial sync logic (both state sync and fast sync) from the other reactors, and as a temporary solution tear down the initial p2p stack once synced and restart a full stack with all reactors. But I'll give the current approach a go, for the initial prototype at least.

**Comment by erikgrinaker** [comment]
Related to #1148.
