### ISSUE TITLE
lite2: forbid to have both auto-update and concurrent calls to VerifyX

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4396]
this will lead to unexpected races. we should probably return an error in VerifyX funcs if auto update is running (i.e. update_period > 0 && Start was called).

The alternative is to make VerifyX functions concurrently safe.

**Comment by cmwaters** [comment]
Shouldn't a manual operation such as VerifyX cause an automatic operation like auto update to block and not the other way around?

**Comment by melekes** [comment]
> Shouldn't a manual operation such as VerifyX cause an automatic operation like auto update to block

"The alternative is to make VerifyX functions concurrently safe." as I said ^, this is an option, yes.

**Comment by melekes** [comment]
I'm just hesitant to add yet another mutex.

**Comment by cmwaters** [comment]
I'm going to add a mutex, unless you have a better suggestion for resolving this

**Comment by cmwaters** [comment]
It should be safe to run sequence/bisection (i.e. Autoupdate) alongside backwards verification (verifying a header that is before the latestTrustedHeader) right? In that case I should just put the mutex on the forward verification functions

**Comment by melekes** [comment]
> It should be safe to run sequence/bisection (i.e. Autoupdate) alongside backwards verification (verifying a header that is before the latestTrustedHeader) right?

Correct

**Comment by melekes** [comment]
Removed auto-update here: https://github.com/tendermint/tendermint/pull/4535

As for Update / VerifyX funcs,

Let's delay making Update / VerifyX funcs concurrency safe until there's a real need. Sorry about that 🙏

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/4518 left the branch as we might reconsider in the future.
