### ISSUE TITLE
lite2: divide verify functions proposal

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4398]
The current `Verify` function in `lite2/verifier.go` uses two methods of differing security to verify a new header against an old header. The first checks, in the case that the headers are adjacent, that the nextValidatorHash of the trustedHeader (@ h) is equal to the validatorHash of the untrustedHeader (@ h + 1). The second method, in the case that the blocks are not adjacent, uses `VerifyCommitTrusting` to check that the validator set that signed the trustedHeader has at least a 1/3 overlap with the validator set that signed the untrusted Header. As these two methods corresponds to two distinct methods that the lite client uses: sequence and bisection, respectively, it might make sense to spit them into two distinct functions to avoid overhead and increase clarity.

**Comment by melekes** [comment]
I am in favor 👍  (`Verify` function might be misused (called with non-adjacent headers in
  incorrectly implemented sequential verification) https://github.com/tendermint/tendermint/pull/4397/files)

But we need to a) consult with the spec b) more importantly, check in with existing API users (mainly, IBC @cwgoes and relayer @jackzampolin)

**Comment by cwgoes** [comment]
I am strongly in favour of this proposal, as long as clear API separation is in place that allows the usage of either simple sequential verification or verification with bisection and avoids duplicate code in Tendermint.

**Comment by melekes** [comment]
> verification with bisection

here we only talk about Verify, which either performs sequential verification (h1.NexValidatorHash == h2.ValidatorSetHash) or skipping verification (1/3+ of trusted validator set is present in new header)

**Comment by melekes** [comment]
Accepted.
