### ISSUE TITLE
lite2: inconsistent header / validator set pairing

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4399]
When using the lite client there are two types of pairings that functions use. The header at height h and the validator set at height h _(seen in green)_ and the header at height h and the validator set at height h + 1 _(seen in red)_

![header-validator-dilemma](https://user-images.githubusercontent.com/27455974/74439314-505e1900-4e6c-11ea-978d-40ccf2292233.png)

This can be confusing as for example, saving or deleting a header and validator set to the lite clients database using the pairing in red, whilst retrieving a header and validator set (`fetchHeaderAndValsAtHeight`) uses the green pairing. The `bisection` method requires the red pairing for the trusted header but requires the green pairing for the untrusted header. Is it possible to have a more consistent pairing between the validator set and the header?

**Comment by melekes** [comment]
props for drawing 💛 

> Is it possible to have a more consistent pairing between the validator set and the header?

I don't know, but, if there is, we should consider simplifying this!

**Comment by cmwaters** [comment]
I would think it is possible to do just the header and nextVals (red) pair.

**Comment by melekes** [comment]
Didn't we fix this?

**Comment by cmwaters** [comment]
not really. I'm not sure if there is a clean way to fix this because the code at the moment requires both types of pairings for different operations. I can have a look at it later but I think it's something we can address in the future.
