### ISSUE TITLE
Save prevote/precommit votes, POL, and precommitted blocks.

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#44]
By the time a node precommits, it should have the justification (POL) prevotes, the block itself, etc saved to disk so that should it restart, it can recall its lock state and prevote accordingly.  Without this, validators can accidentally unlock upon restart right after a precommit, perhaps causing the blockchain to halt.

This isn't a problem unless a large number of valdiators go offline simultaneously.  It could be a problem in the early stages of a blockchain when less than 4 validators are online, assuming equal voting powers.

**Comment by jaekwon** [comment]
Currently we get a cryptic error message when this happens: https://gist.github.com/jaekwon/f7e2a25102f198fa8d20

**Comment by ebuchman** [comment]
This should be addressed by https://github.com/tendermint/tendermint/pull/172 but I will write more CatchupReplay tests to address locking specifically

**Comment by adrianbrink** [comment]
@ebuchman Should this issue be closed, since it has been dealt with in #172?
