### ISSUE TITLE
Parse iso8601 time in genesis doc

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#440]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.9.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available): dummy

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
```
{
  "app_hash": "",
  "chain_id": "mychain",
  "genesis_time": "2017-03-31T16:45:15Z",
  "validators": [
    {
      "pub_key": [1, "3A4B5F5C34B19E5DBD2DC68E7D6FF7F46859A0657EDCA3274235A7EB127A0706"],
      "amount": 10,
      "name": "1"
    }
  ]
}
```

Error reading GenesisDoc: parsing time "2017-03-31T16:45:15Z" as "2006-01-02T15:04:05.000Z": cannot parse "Z" as ".000"

```
{
  "app_hash": "",
  "chain_id": "mychain",
  "genesis_time": "2017-03-31T16:51:12.972167Z",
  "validators": [
    {
      "pub_key": [1, "3A4B5F5C34B19E5DBD2DC68E7D6FF7F46859A0657EDCA3274235A7EB127A0706"],
      "amount": 10,
      "name": "1"
    }
  ]
}
```

Error reading GenesisDoc: parsing time "2017-03-31T16:51:12.972167Z" as "2006-01-02T15:04:05.000Z": cannot parse "167Z" as "Z"

**What you expected to happen**:
Tm correctly parses time.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by ethanfrey** [comment]
I'm taking a look, writing a test cases and trying to localize the bug.

**Comment by ethanfrey** [comment]
Traced it down to parsing of time in go-wire: reflect.go:754

**Comment by ethanfrey** [comment]
It only parses correctly with EXACTLY 3 digits behind the point. Try "2017-03-31T16:51:12.972Z".

I'll fix go-wire to accept seconds, milliseconds, or microseconds...

**Comment by ethanfrey** [comment]
@melekes @jaekwon please take a look at my PR in go-wire to resolve this problem.  Output time is still strictly in milliseconds, as before. Input time is flexible as to how many decimal places there are after the seconds.

**Comment by ebuchman** [comment]
Should be fixed in https://github.com/tendermint/go-wire/pull/13
