### ISSUE TITLE
Issues with breaking changes from v0.33: UPGRADING.md needs more details and version number needs to be bumped

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#4411]
The UPGRADING.md is supposed to serve as a primary point of reference for users to determine how to upgrade their software to a new version of tendermint. Ie when a user asks "what do I need to change to upgrade to the new version", a link to the section of the UPGRADING.md should be a one stop shop for all their needs.

Tendermint v0.33 included major breaking changes to block structures that will effect all software that depends on the block structure, most notably light clients. 

In relation to this, the UPGRADING.md has a single sentence: `This release is not compatible with previous blockchains due to commit becoming signatures only and fields in the header have been removed.`. However this is not sufficient for a user to determine exactly how to proceed as it does not provide detail on exactly what changed. Given the magnitude of the change here, there should be an additional section on Block Protocol Changes that describes what changed and links to the new documentation of the structures so users can clearly and easily find how to upgrade. It can also link to associated ADRs to provide background context, but the critical thing is that there's enough information there for a user to know what to do next.

Further, it looks like the Block Protocol version in the version.go file was not bumped. This must be bumped every time there is a Block Protocol breaking change. Similarly, since blocks go over the wire, this is also considered a P2P Protocol breaking change and should have bumped that version as well. Notably, we have not had such a breaking change in 12 months now!

We may need to improve documentation/checklists around releases to ensure these protocol versions get bumped correctly.

**Comment by melekes** [comment]
> it does not provide detail on exactly what changed

and it shouldn't. changelog already does that
