### ISSUE TITLE
types: VerifyCommitX should return as soon as threashold is reached

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4417]
an optimization which should increase the verification speed.

before:
verifying all the signatures

after:
verifying only 2/3+ (or in case of VerifyCommitTrusting - 1/3+) signatures

**Comment by marbar3778** [comment]
it may also help if we did batch verification of the ed25519 sigs: https://github.com/oasislabs/ed25519/blob/master/batch_verify.go
