### ISSUE TITLE
lite2: verify-earlier-headers

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4419]
NB: This is different to #4413

Given a trusted header hash and height, the lite client should be able to use the `backwards` function to verify a header at height that is less than the header at the trusted height. This should be synced with the `VerifyHeaderAtHeight`function so that users can verify both future and prior headers.

**Comment by melekes** [comment]
How is this different?

**Comment by cmwaters** [comment]
The two issues I see is using VerifyHeaderAtHeight on a header that has already been verified and in this case it shouldn't return an error but the header and just log the error. The second issues is that VerifyHeaderAtHeight isn't able to verify a header that is less in height that the trustedHeader height of the lite client.

**Comment by melekes** [comment]
> it shouldn't return an error but the header and just log the error.

so it's not an error, but we log an error (which suggests that it's actually an error). maybe it's worth to add debug statement, but not error 😄 

> The second issues is that VerifyHeaderAtHeight isn't able to verify a header that is less in height that the trustedHeader height of the lite client.

agree. we should allow backwards verification 👍

**Comment by melekes** [comment]
Done in https://github.com/tendermint/tendermint/pull/4428
