### ISSUE TITLE
lite2: question: should we replace primary if it gives us invalid headers

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4420]
for example malformed header, a header that is not signed with +2/3 of voting power, or in the case there are two consecutive headers h1 and h2 that are not consistent (for example h2.V != h1.NextV, i.e., the current voting set of h2 is not equal to the next voting set field of h1)

NOTE: we do replace primary if it's unavailable for a long period of time.

**Comment by melekes** [comment]
@cmwaters what do you think? I remember we've talked about this, but forgot why we have decided to leave the burden of removing primary (by resetting the light client) to the caller.

**Comment by cmwaters** [comment]
I think we decided to replace the primary. However we don't give the lite client the opportunity to add witnesses. Once all witnesses are exhausted, the lite clients returns an error and closes down and it is up to the caller to reset the lite client with a new (or potentially the same) list of providers

**Comment by cmwaters** [comment]
Are we still looking to implement this?

**Comment by melekes** [comment]
I think so
