### ISSUE TITLE
lite2: make saving intermediate headers optional

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4426]
Do we want to make saving intermediate headers optional? The intermediate headers just act as cache but if the user of the lite client doesn't query headers often then perhaps it's better to not save intermediate headers as this will decrease the execution speed.

**Comment by melekes** [comment]
You mean headers we save during bisection? Yeah, we don't need to store them. If primary suddenly becomes unavailable, we'll just replace it with one of the witnesses.

**Comment by cmwaters** [comment]
Yeah at the moment we automatically store all intermediate headers.

**Comment by cmwaters** [comment]
> You mean headers we save during bisection? Yeah, we don't need to store them. If primary suddenly becomes unavailable, we'll just replace it with one of the witnesses.

But this also applies to sequence and backwards. Between the untrusted header and the trusted header we store all intermediate headers

**Comment by melekes** [comment]
What is the size of each header? What are we optimizing here?

**Comment by melekes** [comment]
The only reason we might need to store intermediate headers is accountability (if the chain forked and light client followed one branch, the exact headers may come in handy). Logging interim headers somehow makes this less of a problem.

For now, I think we can opt-out of saving headers.

**Comment by cmwaters** [comment]
I'm not sure exactly. It uses amino to encode the headers and validator set, so it is hard for me to tell but I would be more focused on the speed by decreasing the amount of writes you have to do to the database for each verification process and also decreasing the read time by having a smaller database.
