### ISSUE TITLE
Rolling of WAL files fails on Windows 10 OS

### ISSUE THREAD

**Issue by mamsen** [tendermint/tendermint#444]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.9.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10
- **Install tools**:
- **Others**:

**What happened**:
When Tendermint tries to roll it's wal files, in many cases it fails (sometimes it works). Tendermint stops and error message says, that the process cannot access the file because it is used by another process.
With running Antivirus software, in 100 percent the rolling fails, with deactivated Antivirus software only each 3rd rolling operation fails.

Error message is:
```
panic: rename D:\dev\MOBAXT~1\home/.tendermint/data/cs.wal/wal D:\dev\MOBAXT~1\home/.tendermint/data/cs.wal/wal.000
Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird
```

**What you expected to happen**:
Rolling wal files (on Unix systems it works)

**How to reproduce it** (as minimally and precisely as possible):
Run Tendermint installed on Windows 10 OS and connect it to an ABCI app that produces empty blocks. Wait until wal files are rolled. To reproduce it faster, connect an ABCI app reproducing many tx.

**Anything else do we need to know**:

**Comment by melekes** [comment]
Thanks for finding our Windows bugs! Would you be willing to try `bugfix/rotating-fails-on-windows` branch on your Windows machine? 

```
go get github.com/tendermint/tendermint/cmd/tendermint
cd $GOPATH/src/github.com/tendermint/tendermint
git checkout bugfix/rotating-fails-on-windows
make get_vendor_deps
go install ./cmd/tendermint
```

**Comment by adrianbrink** [comment]
@mamsen

**Comment by melekes** [comment]
Fixed in https://github.com/tendermint/tmlibs/releases/tag/v0.2.0 (https://github.com/tendermint/tmlibs/commit/74a7f8c92b66abe75fc04c7b0a17ba52e101caef)

Please reopen if the bug shows up again.
