### ISSUE TITLE
BlockStore cache

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4444]
`BlockStore` should possibly cache blocks for faster access, using an LRU cache or similar - see https://github.com/tendermint/tendermint/pull/4437#discussion_r381377147. The cache size should be user-configurable.

**Comment by melekes** [comment]
1) does goleveldb (or other in-process DBs) have a memory cache?
2) if so, then this fact + https://github.com/tendermint/tendermint/issues/4630 should cancel the need for this issue.

**Comment by erikgrinaker** [comment]
I agree, let's close. The OS has a filesystem cache, which I think is sufficient for this. Blocks are large, and possibly not requested too often, so we probably don't want to waste precious memory on actual block contents - and if they are, the OS cache will handle it. Metadata is a different story, but we should profile and benchmark before making any optimizations here.
