### ISSUE TITLE
Place internal APIs under internal package

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4451]
It is currently difficult to know which parts of the Tendermint Go API is meant for external consumption, and which parts are considered internal. In principle, all exported items should be considered part of the public API and thus be subject to backwards compatibility guarantees, but in practice we often make breaking changes to code that is considered internal.

We should enforce a cleaner separation between our public external API and internal APIs by placing internal code under an [`internal` package](https://golang.org/cmd/go/#hdr-Internal_Directories). This will not be possible to import in external projects, thus allowing us to make breaking changes here at will.

**Comment by alexanderbez** [comment]
I support such a proposal and I believe one of the biggest advantages with such a mechanism is a clean and flexible evolution of APIs. Internally, APIs can change at will, but via the publicly exposed API mechanism, they can remain intact and provide less breaking (if any at all) changes over time.

In the Cosmos SDK, we attempted this in conjunction with an `alias.go` file at the root to provide the Go API entry point. This worked very well for us except that we also had our types defined under `internal/`. These types are now Protobuf messages and thus the proto definitions need to be public (the actual `*.proto` file(s)). Granted, we could've kept types outside of `internal/`, but idk if this is worth it. So just keep things like this in mind if you make this transition.

**Comment by melekes** [comment]
are there any concrete steps here?

**Comment by erikgrinaker** [comment]
Decide which APIs are internal and which are external. Move the internal ones to packages under `internal/`.

**Comment by marbar3778** [comment]
There have been conversations of moving reactors and other pkgs to internal. I don't think this is possible as some reactors are used as libraries. An application/user could import p2p/pex and blockchain in order to build a node that only syncs block. Allowing applications/users to build such nodes means we need to do less work to provide more configurations of a Tendermint node.

**Comment by cmwaters** [comment]
A lot of the packages have been moved to internal already. Is there any more internalization work outstanding? (I would probably exclude the node refactoring that's going on / in the pipeline)

**Comment by creachadair** [comment]
This is likely to be an ongoing conversation, but I think we've done this for enough of the essential packages that we may consider this issue satisfied. If there are any specific cases it would be fine to file another issue.
