### ISSUE TITLE
lite2: p2p transport

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4456]
For [state sync](https://github.com/tendermint/tendermint/issues/828), it would be nice if the light client could communicate with P2P peers instead of RPC servers, so that users won't have to supply RPC endpoints in addition to P2P seeds when bootstrapping a node via state sync.

**Comment by erikgrinaker** [comment]
@melekes We need to obtain commit and validator set data via p2p. There are a few approaches we can take here:

1) Overload the blockchain and consensus reactors with new messages. We can possibly use the `Block` data provided by the blockchain reactor for the commit data, but must add new messages to the consensus reactor for the validator set.

2) Add a separate reactor for basic information retrieval.

3) Implement a complete RPC server/client using a P2P transport.

I think I prefer 2. Do you have any thoughts?

**Comment by melekes** [comment]
4. Overload the state sync reactor

**Comment by erikgrinaker** [comment]
>4. Overload the state sync reactor

That would couple the lite client p2p transport pretty tightly to state sync though, so e.g. nodes which do not serve snapshots (do not run the state sync reactor) cannot be used by p2p lite clients. I would think the p2p lite client might be useful for non-state sync use-cases as well?

**Comment by melekes** [comment]
> I would think the p2p lite client might be useful for non-state sync use-cases as well?

how exactly?

**Comment by erikgrinaker** [comment]
Fast sync will also use it, as one example (#4457). Non-full nodes may also have a need for it, although I don't have a specific use-case - in general anything that needs to obtain verifiable chain data without participating in consensus.

**Comment by erikgrinaker** [comment]
Summary from Slack: over the weekend I sort of convinced myself that we should implement an RPC reactor instead. My thinking is basically:

• P2P nodes sometimes need to query each other about chain data
• We already have an HTTP RPC query interface that exposes this data
• Allowing P2P nodes to submit RPC queries via P2P is symmetric, cheap, and user-friendly
• Since RPC is a general service, it should be a separate reactor
• The RPC reactor should be optional, since not all operators may want to expose it
• P2P nodes that need RPC services can discover peers that run the RPC reactor via channel discovery

**Comment by melekes** [comment]
![rpc_reactor](https://user-images.githubusercontent.com/1282182/75168163-b9744500-5726-11ea-9c83-42f0248b5b05.png)

**Comment by erikgrinaker** [comment]
Not really. This would add P2P as an RPC transport, so the RPC reactor would run on the remote server:

State sync → Light client → RPC client → P2P → RPC reactor

cf. State sync → Light client → RPC client → HTTP → RPC server

**Comment by brapse** [comment]
From what I understand, the light client needs headers and commits for verification and we are trying to decide how to expose this. Tendermint stores this data in the block store database which is currently shared by the consensus and blockchain reactors. We are proposing a new reactor called RPC which would have another reference to this database which would specifically service the light client.

On the surface I would challenge the naming here of an `RPC` reactor as the `RPC` naming reflects a specific paradigm of the request/response which the reactors do not share.  If the light client uses request/response it should probably use RPC. 

On the other hand, If the light clients wants to gossip headers, commits or any other domain object it owns then it should probably do so as a reactor. Is the idea to create a header/commit gossip protocol? I thought the idea here is for light clients to be pretty selfish and not participate in gossip. 

If we are indeed creating selfish light clients which are only concerned with getting their commits and headers for verification in a request/response style operations then we should probably use RPC endpoints. The additional complexity in configuration might be a reasonable tradeoff here.

**Comment by erikgrinaker** [comment]
> We are proposing a new reactor called RPC which would have another reference to this database which would specifically service the light client.

If we go for an "RPC reactor", this reactor would service P2P RPC clients in general. The lite client is one user of RPC clients, but it could be useful in other cases as well.

> On the surface I would challenge the naming here of an RPC reactor as the RPC naming reflects a specific paradigm of the request/response which the reactors do not share.

I agree. But RPC client and RPC server is the current Tendermint nomenclature for this subsystem, so it was called RPC reactor by symmetry - it will wrap the functionality in `rpc/core`. It would be straightforward to add request/response semantics for this reactor by placing request IDs in the messages.

> If we are indeed creating selfish light clients which are only concerned with getting their commits and headers for verification in a request/response style operations then we should probably use RPC endpoints. The additional complexity in configuration might be a reasonable tradeoff here.

I disagree. We already ask users to obtain seed nodes to discover peers and establish communication channels. These peers have the data we need and the channels to exchange it. Asking users to obtain a secondary set of nodes with a secondary communication channel is entirely unnecessary.

If the least controversial solution is for the state sync reactor to implement its own light client transport on top of state sync-specific P2P messages for exchanging block headers and commits (in the same way that it exchanges data about snapshots) then I suggest we do that.

**Comment by brapse** [comment]
> I agree. But RPC client and RPC server is the current Tendermint nomenclature for this subsystem, so it was called RPC reactor by symmetry - it will wrap the functionality in `rpc/core`. It would be straightforward to add request/response semantics for this reactor by placing request IDs in the messages.

While I can understand the desire to simplify configuration for our users I'm not sure that wrapping the functionality of `rpc/core` and implementing a state machine to provide request/response semantics is a worthwhile tradeoff. The specific downside that I'm concerned with is that RPC is a very broad aggregator of state produced by other reactors, the blockstore, the stateDB, evidence pool, and others. I don't think it's a good idea to wrap this aggregation as it obscures the responsibility of making data available in a coherent way.

If we specifically need header/validate set gossip it might be a good idea to give it it's own reactor. Since this is the data accumulation portion of the light client protocol why not make a light client reactor?

**Comment by erikgrinaker** [comment]
> RPC is a very broad aggregator of state produced by other reactors, the blockstore, the stateDB, evidence pool, and others. I don't think it's a good idea to wrap this aggregation as it obscures the responsibility of making data available in a coherent way.

Yes, I think you're right. It probably makes more sense for reactors to have small and well-defined responsibilities.

> If we specifically need header/validate set gossip it might be a good idea to give it it's own reactor. Since this is the data accumulation portion of the light client protocol why not make a light client reactor?

That seems like a reasonable solution. 👍 What do you think @melekes?

**Comment by melekes** [comment]
> That seems like a reasonable solution. 👍 What do you think @melekes?

I like this much more than wrapping the entire RPC.

**Comment by brapse** [comment]
One oversight that is worth mentioning here is that the the motivation for using RPC over p2p is that not all tendermint implantation have p2p yet. Specifically Tendermint in rust is not scheduled to have a functional p2p layer until next year or later. From an engineering perspective it might be easier to implement  RPC  than it is p2p. And from a product/ecosystem perspective it might be better to have multiple implementation of the light client sooner rather than later. If a client is indeed light, is it reasonable to require implementation of  it our p2p stack? Interested in hearing your thoughts @melekes , @erikgrinaker

**Comment by erikgrinaker** [comment]
The light client supports multiple transports. The currently implemented transport is RPC, but the plan here is to implement an additional P2P transport that state sync and fast sync can use instead. The Rust implementation is free to choose which transport to use.

**Comment by erikgrinaker** [comment]
Rejected in today's Tendermint call, we'll use RPC nodes for the first iteration.
