### ISSUE TITLE
Light client verification for fast sync

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4457]
Fast sync should use the light client for block verification.

**Comment by cmwaters** [comment]
Hey @erikgrinaker, can you please elaborate on the issue - specifically what is the current verification process that is used for fast sync and what part of the lite client verification could be used instead and what benefits would this bring?  As I understand it at the moment, the verification process that is used by `blockchain/v2` is albeit a bit messy sufficient enough and I'm not sure where the lite client would fit in to help.

**Comment by erikgrinaker** [comment]
Afraid I'm not familiar with the details here either, @brapse and @milosevic would know more. But the verification bit happens here, I guess: https://github.com/tendermint/tendermint/blob/ee993ba8ff9893ab4c46b269987a3138ead223ff/blockchain/v2/processor.go#L135

As I understand, it currently just compares two sequential blocks, which @milosevic said was insufficient. Also, I'm not sure where it gets the root of trust from, I guess it just pulls an initial block from "somewhere" and implicitly trusts it.

**Comment by milosevic** [comment]
The current fast sync protocol (to the best of my knowledge) starts from genesis block and then download, verify and execute blocks until some conditions are met (for example, no peer in the node peerset has higher blocks, or peer set is empty, there are no new blocks in the blockchain and some timeout expires). However, we don't have any guarantee that the blocks executed and the final state indeed corresponds to the right (correct chain). In addition, when we verify blocks, we basically take two consecutive blocks b and b+1, and verify if last commit from b+1 "confirms" block b, and that last commit and blocks are valid on its own. In case verification fails (last commit and block don't match) we were not able to say which one is wrong, so we have been removing both blocks and disconnecting from both peers (blaming them as faulty). This has a negative consequence that correct peers were falsely blamed and removed from peerset; preventing node to sync fully from correct peers. 

The solution for both problems lies in using light client security model for fast sync. This basically means that light client is initialised with trusted header and that fast synch should start from the corresponding height and state (most probably obtained using state sync). This gives us correct starting point. Furthermore, we can use light client to fetch (and verify) most recent header, which gives us fast sync target. More precisely if we verify (using light client) header at height h we can safely fast sync up to h and then check if the corresponding state (obtained executing blocks up to height h) corresponds to the one from the header at height h. 

In addition, verifying blocks as part of fast sync can be more correct. Note that in light client security model, having trust in some header h and the corresponding validator set vs, guarantee that 2/3+ of the voting power will stay correct within trusted period , i.e., until 'h.Time + trusted_period'. If we operate fast sync in the same model and we have executed block at height k, we know what validator set will execute block k+1. Therefore, we can verify last commit for block k+1 (that is part of block k+2) checking that 2/3+ of the trusted validator set has signed it. In this case, block at height k+1 is correct only if lastCommit signed it. Note that lastCommit signs BlockId, so essentially valid lastCommit gives us valid BlockId for the previous block. Therefore, either last commit is invalid, so we remove corresponding block, or if lastCommit is valid, block is valid or not. So we never falsely blame correct process, so faulty processes cannot prevent correct peers in fast sync of providing blocks they know. Note that this is only true while we are within light client security model; in case we have forks, faulty processes can lead fast sync in wrong direction, but this is covered by fork accountability and detection mechanisms.

**Comment by cmwaters** [comment]
Thanks @milosevic. Just for further clarification, I would like to extract what you said into each of the features that need to be implemented, followed by any questions I might have regarding each aspect:

**Features**

- Fast sync is vulnerable during initiation and so should use the same aspect of the light client to start from a trusted header as opposed to starting from a height.
    - Is there any concern with initiating a trusted header outside the trusted period (which will most likely be the case)?
- Fast sync should use light client to obtain the most recent header and therefore the target header
    - Why is this important? -Is this to compare the app hashes of state and latest header?
    - Why is this better than writing until no peer in the node peerset has higher blocks?
    - Won't this have to be repeated as whilst we are processing prior blocks more and more blocks are being appended to the chain?
- Fast sync should use the `VerifyAdjacent` function for better correctness which will remove the prior problem of not being able to know which block to drop when verification fails and therefore which peer to ignore

**Stand-alone Questions**

The light client continuously checks headers with witnesses (other peers). Do we want to implement this as well perhaps to verify the target header, or alternatively if we are verifying outside the trustPeriod then we could iteratively (i.e every 1000 blocks) compare with witnesses to detect any forks?

Smaller question, but why is the package called blockchain? It's a widely used term and could indicate a variety of different purposes that it performs. Wouldn't something like blocksync or fastsync be better?

Is there anything important that I am missing?

**Comment by melekes** [comment]
> Smaller question, but why is the package called blockchain? It's a widely used term and could indicate a variety of different purposes that it performs. Wouldn't something like blocksync or fastsync be better?

I also find it confusing. 👍  to `fastsync` 

> Is there any concern with initiating a trusted header outside the trusted period (which will most likely be the case)?

not if you're using state sync. but if you aren't, then yes it's a concern ⚠️  

> Won't this have to be repeated as whilst we are processing prior blocks more and more blocks are being appended to the chain?

most likely, but fastsync is still faster than regular consensus

**Comment by josef-widder** [comment]
>   * Is there any concern with initiating a trusted header outside the trusted period (which will most likely be the case)?

If the trusted header is outside the trusted period, we cannot synchronize safely.  
Why is this the likely case?

> * Fast sync should use light client to obtain the most recent header and therefore the target header
>   
>   * Why is this important? -Is this to compare the app hashes of state and latest header?
>   * Why is this better than writing until no peer in the node peerset has higher blocks?
>   * Won't this have to be repeated as whilst we are processing prior blocks more and more blocks are being appended to the chain?

The termination condition of fastsync turned out to be super subtle. If you download only from peers that send you blocks slower than they are produced by the blockchain, and the timeout does not stop that, fastsync may never terminate. The question is what is an acceptable termination condition, e.g., what is sufficient to be able to switch to consensus. 

> * Fast sync should use the `VerifyAdjacent` function for better correctness which will remove the prior problem of not being able to know which block to drop when verification fails and therefore which peer to ignore

The problem was there even with `VerifyAdjacent`. In the old implementation you could try to check block 5 against 4 (adjacent) without having block 3 before. As a result, one cannot know whether 4 or 5 is faulty, and so both were dropped (including the peers that provided them; it is bad to drop a correct peer just because one is not sure what happened).


> The light client continuously checks headers with witnesses (other peers). Do we want to implement this as well perhaps to verify the target header, or alternatively if we are verifying outside the trustPeriod then we could iteratively (i.e every 1000 blocks) compare with witnesses to detect any forks?

I guess we would need that. Otherwise there are no incentives for peers not to try to attack a fastsyncing node.

**Comment by cmwaters** [comment]
> If the trusted header is outside the trusted period, we cannot synchronize safely.
Why is this the likely case?

For fast sync, where we start our trusted state at genesis, isn't it likely that genesis time will be outside of the trusted period

> The problem was there even with VerifyAdjacent.

But if we are using `VerifyAdjacent` as part of the light client where we have this concept of a last trusted block then are we not just verifying blocks one at a time and not two at once? This would then mean that if one is incorrect we just drop the peer that provided that block and not both of them.

**Comment by melekes** [comment]
> Why not for state sync?

state sync relies on the same model, true. I was just saying state after state-syncing will likely be within the trusting period.

**Comment by josef-widder** [comment]
> For fast sync, where we start our trusted state at genesis, isn't it likely that genesis time will be outside of the trusted period

Then we shouldn't do that. If the genesis is 4 weeks old, all validators might have unbonded in the meantime, and if they don't have anything at stake, we cannot trust them

> But if we are using `VerifyAdjacent` as part of the light client where we have this concept of a last trusted block then are we not just verifying blocks one at a time and not two at once? This would then mean that if one is incorrect we just drop the peer that provided that block and not both of them.

Exactly. This is why the approach based in the light client verification logic is better, and old implementations had a problem.

**Comment by jmalicevic** [comment]
@cmwaters  @milosevic  Just to clarify my understanding of the proposed solution. To reuse the verification model of the light client, we would need to assign a trusted initial state to the block sync reactor. Once we have that we can use VerifyAdjacent, or even optimize with  accepting blocks with the same validator sets who are within a trusted period w/o fully validating them. 

So a question is what would this initial trusted state be? I see a couple of scenarios:
1. If a node just joins it has to be genesis state 
2. If it has previous state and it is within the trusting period then we can just execute the regular fast sync.
3. If the nodes' last state (or genesis) is within the trusting period of the light clients current height (H), we can have an optimized protocol for syncing up to H.
4. Previous state exists but it is outside a trusting period.

For 1. and 4.  can it happen that we start fetching subsequent blocks from peers but those peers are malicious and we don't notice it until we have already synced? In that case block sync could also have a set of witnesses to decide on a correct block to start with? Or we look for blocks for a particular height within the store of the light client (assuming the light client has not stored something that has not already been verified by witnesses) and bootstrap from there.

**Comment by josef-widder** [comment]
Regarding point 1. is there a way to ask a node for a trusted state? Once the chain is running for more than 3 weeks, we cannot use the genesis state anymore, as the lightclient logic will consider that outdated.

Otherwise, all for points are still based on subjective initialization. They are safe under the assumption that the initial state is correct. The lightclient logic does ensure that even if we talk to a faulty peer. It rejects faulty blocks as the verification will fail.

**Comment by jmalicevic** [comment]
The way I understood it now (after the original question I posed), block sync could occur outside the trusted period as it has to replay all the blocks to get to a correct state. So we should not really use the light client nor anything it generated within the verification in block sync. Rather we just take the logic from there and apply it in block sync. But block sync could periodically do what the light client does and ask other peers for blocks for the same height to see whether there has been divergence. If these blocks are outside the trusting period of the light client then we don't submit evidence, but rather halt as we detected a fork?

**Comment by jmalicevic** [comment]
https://github.com/tendermint/tendermint/issues/2622 Is probably related to this issue as well.

**Comment by cmwaters** [comment]
Looping back to this I think we should first focus on swapping out the verification functions for the standard light client ones. Then further to that we can assess:
- Adding the light client detector for intermittent cross-header verification
- More "concurrent" verification strategies
