### ISSUE TITLE
Don't panic!

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4465]
We currently use panics for a lot of error handling. We should return errors instead.

This should rely on the [new error handling system in Go 1.13](https://blog.golang.org/go1.13-errors), i.e. wrap errors with the `%w` verb of `fmt.Errorf()`.

**Comment by melekes** [comment]
NOTE: panics are fine for exceptional cases where it's not possible to continue operation.

**Comment by erikgrinaker** [comment]
There have been questions about when panic is and isn't appropriate. My recommendation would be that panic is appropriate when an internal invariant of a system is broken, while all other cases (in particular, incorrect or invalid usage) should return errors. Consider the following code, modelling a bank where account balances should never go below 0:

```golang
type Bank struct {
  accounts map[int]int
}

func (b *Bank) Transfer(from int, to int, amount int) error {
  if amount < 0 {
    return fmt.Errorf("amount cannot be negative, got %v", amount)
  }
  if balance := b.accounts[from]; balance < amount {
    return fmt.Errorf("unable to transfer %v, balance is %v", amount, balance)
  }
  b.accounts[from] -= amount
  b.accounts[to] += amount
  return nil
}

func (b *Bank) Balance(account int) int {
  balance := b.accounts[account]
  if balance < 0 {
    panic("found balance less than 0")
  }
  return balance
}
```

`Transfer()` should return an error when transferring more money than the account has: this is an error condition triggered by an external call, and it is up to the caller to handle it.

However, `Balance()` should panic if it ever finds a balance less than 0. This is an invariant that our system should enforce through the checks in `Transfer()`, thus it can only happen if the code inside the system is faulty. Panicing instead of returning an error here saves our callers from handling this error, which should really never happen in the first place.
