### ISSUE TITLE
GitHub bot for auto-update/merge of PRs

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4468]
We should consider setting up a GitHub bot like [Bulldozer](https://github.com/palantir/bulldozer) that can automatically update and/or merge pull requests once all required conditions are met - typically including labels like `auto-update` and `auto-merge`. It gets pretty tedious to manually wait for tests, update from master, wait again, and merge.

We'll need to get an admin to hook this up.

**Comment by marbar3778** [comment]
I think we can move this out of proposal since we discussed it on our team call. I do believe anton and tess have those rights

**Comment by erikgrinaker** [comment]
Looks like Bulldozer is self-hosted. Let's maybe try Mergify, it's free for open source:

https://mergify.io
https://github.com/marketplace/mergify
