### ISSUE TITLE
lite2: pruning headers and vals

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4469]
Previously, the light client removed headers based on whether they resided outside the trustPeriod, however it is still possible to use verified headers outside of the trustPeriod, hence we need to modify the function to prune headers.

The pruning will need to occur whenever a new item is added to the database. We will check to see if the size of headers in the database has reached a prescribed height and if so delete the oldest headers and validator sets

**Comment by melekes** [comment]
NOTE: we could still remove headers based on a timer (rename it to PrunePeriod). It's just number of headers will give the users more control over memory usage.

**Comment by cmwaters** [comment]
> NOTE: we could still remove headers based on a timer (rename it to PrunePeriod). It's just number of headers will give the users more control over memory usage.

Would you like to have both in place then. So prune headers based on size and a time period

**Comment by cmwaters** [comment]
When we are pruning headers do we want to add something to the logger i.e. to keep track of the headers deleted. There might be people who don't read the entire spec of the lite client and don't know that they could be automatically pruning away headers that they wanted to keep. Alternatively we could default with not pruning

**Comment by melekes** [comment]
> Alternatively we could default with not pruning

and let the memory grow infinitely? safety by default is a good principle. If I start a light client on mobile wallet, I would be surprised when it crashes after a week because it took all available memory.
