### ISSUE TITLE
lite2: consider storing current valset

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4470]
"We need the current ValidatorSet of the header so that the connecting chain can verify the header was committed by the current ValidatorSet. The lite.Verify function takes in the current ValidatorSet which gets used in the IBC update function. The relayer needs some way to pull the current validator set from the liteclient db and then pass it to the connecting chain
https://github.com/cosmos/cosmos-sdk/blob/bb7e803cb9291ff408a2d8ceab29a6292537012b/x/ibc/07-tendermint/update.go#L87"

before: {Header} + {NextValset}
after: {Header} + {Valset} + {NextValset}

**Comment by jackzampolin** [comment]
This is a much needed change ++ thank you for opening the issue @melekes

**Comment by cmwaters** [comment]
Linked with #4399

**Comment by melekes** [comment]
Accepted.

After speaking with @cmwaters, we've decided to store {Header} + {Valset}. Note this means {Valset} will be used to check if we can jump from H1 to H3 in bisection, not {NextValSet}. The underlying assumption is most blockchains won't be changing their validator set often, so it's less important whenever we're using {ValSet} or {NextValSet} when deciding if we can jump to it.
