### ISSUE TITLE
LCD SSL not working?

### ISSUE THREAD

**Issue by dbriggsie** [tendermint/tendermint#4474]
Hi there,

I am running a fullnode for a cosmos subchain.

I have added in my SSL .crt & .key and even put them in the /config/ DIR.

However it seems when there is a value in the cert & key options in the config I get no response from the https... and on http side i get this error.

http error:
**{"error":"Status: error unmarshalling: invalid character 'C' looking for beginning of value"}**

you can see on these two links it being reproduced.
https://172.105.11.162/node_info
http://172.105.11.162/node_info

Any info on this would be good. The reason i need SSL working is for swagger to connect over https. As its giving errors because it doesnt want to go from https -> http (lcd)

**Comment by melekes** [comment]
Do you still have this issue? Both endpoints seem to respond correctly now.

**Comment by melekes** [comment]
@dbriggsie I am going to close this. Please drop a comment here in case you're still experiencing ^ or have any other issues. Thanks!
