### ISSUE TITLE
Prometheus with Tendermint

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [tendermint/tendermint#4475]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.32.8-759ccebe

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
I am trying to use Prometheus with tendermint network. I use the command 
`make localnet-start`
to start the network. Modified the config.toml with
`Prometheus =true`
 and Prometheus.yml with 
`- job_name: 'tendermint'
    # Override the global default and scrape targets from this job every 1 second.
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:26660']`

 I started Prometheus and it was up and running. I was expecting to get the result at
localhost:26660/metrics. But  localhost:26660 does not have an attribute metric. Also I checked localhost:9090/graph, it too does not show any attributes of tendermint.
please help.

Thanks,
Anjana

**What you expected to happen**:
localhost:26660/metrics to have a valid page
**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
The endpoint 9090 is not provided by tendermint. You will have to provide a prometheus server to ingest the data. 

for localhost:26660 I'm not sure what the issue is, if you try to spin up a node locally(no docker) with it enabled does it work?

Did you try the ip of the subnet of the docker containers? if you enable a prometheus server and pass in those endpoints it should work

**Comment by Anjana-Prabhakar** [comment]
@marbar3778  I created a prometheus.service file and had prometheus up and running for a single tendermint node without a docker. The issue exists.
Earlier for docker setting I had made change to config.toml. However I could not find such a file for non docker setting. And in prometheus.yml, i used `targets: ['localhost:9090']`.

**Comment by erikgrinaker** [comment]
@Anjana-Prabhakar This works for me. Please make sure your configuration and network settings are correct. For example, with `localnet-start` I had to change `networks/local/localnode/Dockerfile` to expose port 26660, and change `docker-compose.yml` to port-forward port 26660 to node0 and remove port forwarding for other nodes (which also claim 26660 for a different service).

Here is a diff of my changes:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index ccc80204..8aba994d 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,6 +6,7 @@ services:
     image: "tendermint/localnode"
     ports:
       - "26656-26657:26656-26657"
+      - "26660:26660"
     environment:
       - ID=0
       - LOG=${LOG:-tendermint.log}
@@ -18,8 +19,6 @@ services:
   node1:
     container_name: node1
     image: "tendermint/localnode"
-    ports:
-      - "26659-26660:26656-26657"
     environment:
       - ID=1
       - LOG=${LOG:-tendermint.log}
@@ -35,8 +34,6 @@ services:
     environment:
       - ID=2
       - LOG=${LOG:-tendermint.log}
-    ports:
-      - "26661-26662:26656-26657"
     volumes:
       - ./build:/tendermint:Z
     networks:
@@ -49,8 +46,6 @@ services:
     environment:
       - ID=3
       - LOG=${LOG:-tendermint.log}
-    ports:
-      - "26663-26664:26656-26657"
     volumes:
       - ./build:/tendermint:Z
     networks:
diff --git a/networks/local/localnode/Dockerfile b/networks/local/localnode/Dockerfile
index 03af5aa3..c3a8adc0 100644
--- a/networks/local/localnode/Dockerfile
+++ b/networks/local/localnode/Dockerfile
@@ -7,7 +7,7 @@ RUN apk update && \
 
 VOLUME [ /tendermint ]
 WORKDIR /tendermint
-EXPOSE 26656 26657
+EXPOSE 26656 26657 26660
 ENTRYPOINT ["/usr/bin/wrapper.sh"]
 CMD ["node", "--proxy_app", "kvstore"]
 STOPSIGNAL SIGTERM
diff --git a/networks/local/localnode/config-template.toml b/networks/local/localnode/config-template.toml
index a90eb7bd..bdeb5a04 100644
--- a/networks/local/localnode/config-template.toml
+++ b/networks/local/localnode/config-template.toml
@@ -1,2 +1,5 @@
 [rpc]
 laddr = "tcp://0.0.0.0:26657"
+
+[instrumentation]
+prometheus = true
```

Deleting the old configuration and restarting the Docker network then gives access to Prometheus:

```sh
$ make build-linux && rm -rf build/node* && make localnet-start
$ curl localhost:26660/metrics
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 1.6808e-05
go_gc_duration_seconds{quantile="0.25"} 4.1249e-05
go_gc_duration_seconds{quantile="0.5"} 0.00010529
go_gc_duration_seconds{quantile="0.75"} 0.000153384
go_gc_duration_seconds{quantile="1"} 0.000963147
go_gc_duration_seconds_sum 0.001279878
go_gc_duration_seconds_count 5
[...]
```

**Comment by Anjana-Prabhakar** [comment]
The changes mentioned gives a dialup error for nodes other than node0 and also the transactions dont get added to the block via abci-cli.

**Comment by erikgrinaker** [comment]
Yes, you will not be able to connect to other nodes since they no longer have port forwarding. You will have to configure the networking to suit your needs.

**Comment by Anjana-Prabhakar** [comment]
Thank you for confirming. Could you please elaborate a little more as to how to use prometheus with a 4 node network.

**Comment by erikgrinaker** [comment]
It will depend on the network topology, I can't really say without more details. In general, each Tendermint node will have Prometheus metrics available on port `26660` - you will have to configure your networking in such a way that Prometheus is able to reach this port, and configure Prometheus to gather metrics from all four nodes.

If you have a simple network topology where each Tendermint node is running on its own IP address, then simply set up a static Prometheus target configuration like so:

```yml
- job_name: tendermint
    static_configs:
    - targets:
      - 192.168.1.101:26600
      - 192.168.1.102:26600
      - 192.168.1.103:26600
      - 192.168.1.104:26600
```

**Comment by Anjana-Prabhakar** [comment]
I changed the target to [localhost:26660]. When i used the command `./prometheus  --config.file=prometheus.yml` i got an error `bind: address in use 9090`. But when i check for pids of process running in 9090, it gives me null. So I tried the command `./prometheus --web.listen.address =:26660 &` for which i get a message `bind: address in use 26660.` However for the command `./prometheus --web.listen.address =:9010 &` i get to see the metrics at `localhost/9010` as well as `localhost/9000.`

**Comment by Anjana-Prabhakar** [comment]
I undid the changes made to docker-compose.yml and retained the changes in docker file and config-template.toml.  I changed the target in prometheus.yml to [IPaddress:26660] instead of [localhost:26660]. And now it works. Thank you all.
