### ISSUE TITLE
No response with tendermint node command

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [tendermint/tendermint#4495]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.32.8-759ccebe

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore
**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**: Prometheus
- **Others**:

**What happened**:
I run the` kvstore` app via `abci-cli` and then I run tendermint using `tendermint node` command. The abci-cli terminal says `waiting for new connection` but no blocks are generated in tendermint terminal. Earlier I was getting `handshake error` and i upgraded the abci-cli to version 0.16.1. Please note that blocks are generated if i use the command `tendermint node proxy_app=kvstore`.

**What you expected to happen**:

The blocks to be generated.
**Have you tried the latest version**: yes/no
yes
**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
prometheus=true
**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by erikgrinaker** [comment]
This also works for me, please make sure your Tendermint configuration is correct. Using revision `759ccebe`:

```sh
$ make build_abci
$ ./abci-cli version
0.16.1
$ ./abci-cli kvstore
I[2020-02-28|10:13:33.918] Starting ABCIServer                          module=abci-server impl=ABCIServer
I[2020-02-28|10:13:33.919] Waiting for new connection...                module=abci-server 
```

In a different terminal:

```sh
$ make build
CGO_ENABLED=0 go build -mod=readonly -ldflags "-X github.com/tendermint/tendermint/version.GitCommit=`git rev-parse --short=8 HEAD` -s -w" -tags 'tendermint' -o build/tendermint ./cmd/tendermint/


$ rm -rf ~/.tendermint/
$ mkdir ~/.tendermint
$ ./build/tendermint version
0.32.8-759ccebe

$ ./build/tendermint init
I[2020-02-28|10:14:45.118] Generated private validator                  module=main keyFile=/Users/erik/.tendermint/config/priv_validator_key.json stateFile=/Users/erik/.tendermint/data/priv_validator_state.json
I[2020-02-28|10:14:45.119] Generated node key                           module=main path=/Users/erik/.tendermint/config/node_key.json
I[2020-02-28|10:14:45.119] Generated genesis file                       module=main path=/Users/erik/.tendermint/config/genesis.json

$ ./build/tendermint node
I[2020-02-28|10:15:03.578] Version info                                 module=main software=0.32.8 block=10 p2p=7
I[2020-02-28|10:15:03.598] Starting Node                                module=main impl=Node
I[2020-02-28|10:15:03.607] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} ID_:850d8db49529f62487fe24a161c85c381fd6f34b ListenAddr:tcp://0.0.0.0:26656 Network:test-chain-eyk0Jx Version:0.32.8 Channels:4020212223303800 Moniker:gMac.local Other:{TxIndex:on RPCAddress:tcp://127.0.0.1:26657}}"
I[2020-02-28|10:15:04.654] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[2020-02-28|10:15:04.659] Committed state                              module=state height=1 txs=0 appHash=0000000000000000

```

**Comment by Anjana-Prabhakar** [comment]
I made the changes mentioned above. But now the transactions don't reflect in the tendermint network. The transactions that I commit using abci-cli console or batch is shown as commit with height =0 in query but not present in tendermint blocks.

**Comment by erikgrinaker** [comment]
The `height=0` is probably because the `kvstore` example application does not store height metadata for its state. We should add support for this, I opened #4507 for it.

As for the Tendermint network, the commands above only start a single standalone Tendermint node on the local OS. If you need a cluster, you will need to set one up either in Docker or with multiple processes.

When I write a transaction to the application, it is stored in the appropriate block:

```
$ curl -s 'localhost:26657/broadcast_tx_commit?tx="key=value"'

I[2020-02-28|18:09:45.185] Executed block                               module=state height=60 validTxs=1 invalidTxs=0
I[2020-02-28|18:09:45.191] Committed state                              module=state height=60 txs=1 appHash=0200000000000000
```
