### ISSUE TITLE
privval: add ChainIDRequest

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4503]
## Summary

Add chainid request to privval server so that the ksm or other hsms may request the ChainID

this can be useful is the ksm is supporting multiple nodes and networks

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
and why do they need `chainID`? aren't they configured with a particular `chainID`?

**Comment by marbar3778** [comment]
it was based off this todo: https://github.com/tendermint/tendermint/blob/master/privval/messages.go#L26

@jleni do you have context on the todo?

**Comment by jleni** [comment]
I think I originally received this request because the same KMS wanted to accept requests from multiple nodes and network and decide based on that which key to use.
This is more a KMS feature request I believe.

**Comment by marbar3778** [comment]
@jleni thank you, will amend the description and touch base with the kms team

**Comment by marbar3778** [comment]
this is simple enough to group in with #4698 

talked with the kms team and agreed that adding the chainID in requests is the best way to go about this
