### ISSUE TITLE
lite2: non-recursive bisection may be slower than recursive version

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4504]
@ancazamfir:

while this is true for the example you show in Fig.1, not sure this is always the case. For example, in another case you can have something like this:

    start with th=1, ih=256
    the +1/3rd check fails a few times and interim headers are retrieved and checked, let's say: [1], 8, 16, 32, 64, 128, [256]
    8 verifies against 1 so now we have th=8, ih=256
    again the +1/3rd check fails and other headers are retrieved: [8], 16, 24, 40, 72, 136, [256]
    16 verifies against 8 and at this point th=16, ih=256
    -...

The downloaded headers are not kept around (so we save on memory) but more headers and vals need to be retrieved.

See https://github.com/tendermint/tendermint/pull/4496#discussion_r385630359 for the whole discussion.

**Comment by cmwaters** [comment]
Based from the benchmarking tests #4514, and the intuition around it, the recursive bisection is better suited for uniform changes in the validator set, and performs better when the frequency of validator set changes increased. However non-recursive performs better for infrequent and irregular changes in the validator set which we believe to be more likely the case. The other issue to consider is the amount of headers to be requested by the witness in which recursive bisection generally requires less, however it is possible to introducing a caching system in non-recursive bisection to reduce the amount of network overhead in place of more memory usage. 

In light of all this we have decided to remain with the current non-recursive bisection implementation

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/4514#issuecomment-593524947
