### ISSUE TITLE
Enable multiple ABCI apps behind the same tendermint core network

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#452]
**FEATURE REQUEST**

It might be interesting to enable the functionality that multiple ABCI apps can run behind the same tendermint core consensus network. 

For example, we have the dummy and the counter app and both are verified by the same validator set.

**Comment by ethanfrey** [comment]
This behavior is relatively easy to implement as a multiplexing abci app. The only trick is amending the proofs that come from the sub apps to be valid. Please open this as an enhancement on the abci repo. I could implement it in the next month (depending on how the refactoring goes)
