### ISSUE TITLE
Any plan to improve the performance of memory db

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#4520]
As we know tendermint is fast blocking consensus protocol, the height of blockchain grows quickly. 

Some users would like to replay the blocks from genesis, and the speed is around 20 blocks/ per second, which is slow, and the bottleneck is storage according to our analysis.

Here is our solution:
1. Let users download all the data(including history blocks).
2. Delete application.db
3. The application db use mem db, and the rest use leveldb, then start the tendermint client.

However, the performance does not improve, and the speed is still around 20 blocks per second. We profile the CPU usage:
![image](https://user-images.githubusercontent.com/7310198/75773569-23c16100-5d89-11ea-8bdc-b35757abe2df.png)

Each time `commit` a block wil save `SaveOrphans`:
```
func (ndb *nodeDB) SaveOrphans(version int64, orphans map[string]int64) {
	....
	toVersion := ndb.getPreviousVersion(version)
        ....
```
```
func (ndb *nodeDB) getPreviousVersion(version int64) int64 {
	itr := ndb.db.ReverseIterator(
		rootKeyFormat.Key(1),
		rootKeyFormat.Key(version),
	)
	...

	return 0
}
```
```
func (db *MemDB) ReverseIterator(start, end []byte) Iterator {
         ....
	keys := db.getSortedKeys(start, end, true)
	return newMemDBIterator(db, keys, start, end)
}
```
```
func (db *MemDB) getSortedKeys(start, end []byte, reverse bool) []string {
	keys := []string{}
	for key := range db.db {
                 inDomain := IsKeyInDomain([]byte(key), start, end)
		....
	}
	sort.Strings(keys)
         ...
        reurn keys
}
```
And let's see what is  memdb's structure:
```
type MemDB struct {
	mtx sync.Mutex
	db  map[string][]byte
}
``` 

It means it will iterate all the keys in db when doing `SaveOrphans`, obviously `IsKeyInDomain` and `sort.Strings(keys)` functions are CPU intensive.

So do you guys have any plan to improve the performance of Memdb? Or any idea to solve the problem that needs a long time to replay from genesis? (There is state sync mode can skip history blocks and sync the state snapshot, but that is not what we want. )

**Comment by erikgrinaker** [comment]
Hi @guagualvcha, thanks for the analysis! Just off the top of my head, it sounds like this might be improved quite significantly simply by storing keys in an in-memory B-tree or a similar sorted data structure. That should be pretty straightforward, I'll give it a try shortly.

**Comment by erikgrinaker** [comment]
@guagualvcha I have a B-tree-based drop-in replacement at https://github.com/tendermint/tm-db/pull/53, are you able to give it a quick try?

**Comment by erikgrinaker** [comment]
This was fixed in https://github.com/tendermint/tm-db/commit/a2b9135d6f1238be6fee4869d3d5af6c6207436e. We're preparing to release tm-db 0.5 with this fix, which will then have to be incorporated into a future Cosmos SDK release.
