### ISSUE TITLE
Error while querying some transactions

### ISSUE THREAD

**Issue by RiccardoM** [tendermint/tendermint#4524]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.33.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/desmos-labs/desmos

**Environment**:
- **OS** (e.g. from /etc/os-release): 
  ```
  NAME="Ubuntu"
  VERSION="19.10 (Eoan Ermine)"
  ID=ubuntu
  ID_LIKE=debian
  PRETTY_NAME="Ubuntu 19.10"
  VERSION_ID="19.10"
  HOME_URL="https://www.ubuntu.com/"
  SUPPORT_URL="https://help.ubuntu.com/"
  BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
  PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
  VERSION_CODENAME=eoan
  UBUNTU_CODENAME=eoan
  ```

- **Install tools**:
- **Others**:

**What happened**:
Sometimes when executing the `desmoscli query tx <hash> command`, the following error is returned: 

```
ERROR: header has vhash <vhash> but valset hash is <valsethash>

# Example
# ERROR: header has vhash 08D4CBC9952546DF2138BE7A85E11AD2E1D54F65246D37A45C4E680E0D22C9D5 but valset hash is 3A0D7667091181B36407E2D36B16F7CEA322483575F55432B09BC72A7491C28F
```

This is particularly strange because the transaction is included into the block properly, but once it's done it cannot be queried later. An example of failing transactions is:

`C090BF6DEEBF14A5A8C3F2D9D9473A55ADFFFDA2306DE22AC2358855429E219A` 

This can be viewed inside our example at this link: [Explorer - Tx](https://morpheus.desmos.network/transactions/C090BF6DEEBF14A5A8C3F2D9D9473A55ADFFFDA2306DE22AC2358855429E219A). You can also see the REST response [here](http://lcd.morpheus.desmos.network:1317/txs/C090BF6DEEBF14A5A8C3F2D9D9473A55ADFFFDA2306DE22AC2358855429E219A).

**What you expected to happen**:
The transaction details should be returned properly as they can be fetched from the REST APIs without many problems. 

**Have you tried the latest version**: yes/no
No

**How to reproduce it** (as minimally and precisely as possible):
```
git clone https://github.com/desmos-labs/desmos.git
cd desmos
make install
desmoscli config node http://34.74.131.47:26657
desmoscli config chain-id morpheus-3000
desmoscli query tx 4A199F10FE89A986EB34FDA4382535A7230A1736855FE5B13967CF60E374D689
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
N.A.

**node command runtime flags**:
N.A.

**`/dump_consensus_state` output for consensus bugs**
N.A.

**Anything else we need to know**:
N.A.

**Comment by RiccardoM** [comment]
Seems that forcing the `--trust-node` flag makes it work again for some reason.

**Comment by marbar3778** [comment]
this seems like a cosmos-sdk issue. did you try using the rpc and querying it directly from Tendermint?

**Comment by RiccardoM** [comment]
@marbar3778 Yeah, looks like it works: [RPC link](http://rpc.morpheus.desmos.network:26657/tx?hash=0x4A199F10FE89A986EB34FDA4382535A7230A1736855FE5B13967CF60E374D689).

I've reported this into the Cosmos SDK. I'll close it
