### ISSUE TITLE
Use bisection for parts of backwards verification

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4537]
## Summary

Given bisections speed, it would be faster when verifying a header that is not greater in height than the latest stored header, to find the trusted header in the store directly **before** the untrusted header and use `bisection` instead of `backwards` to verify the untrusted header.

## Problem Definition

Bisection is faster then backwards verification

## Proposal

Change the store interface by replacing `SignedHeaderAfter(height int) (*types.SignedHeader, error) `with `SignedHeaderBefore(height int) (*types.SignedHeader, error)`

When verifying a header prior to the latest block, check if the header is less in height than the `firstTrustedHeaderHeight`. If so, perform backwards verification like beforehand but use the header at the first trusted height as the initial trusted header. If not, then use the trusted header from `SignedHeaderBefore` and then use bisection to verify the untrusted header.  

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by milosevic** [comment]
This is fine. We just need to take care that with bisection trusted header need to be within trusted period.
