### ISSUE TITLE
[blockchain v0] Make numPending in BlockPool atomic maybe redundant

### ISSUE THREAD

**Issue by helldealer** [tendermint/tendermint#4539]
All read&write on BlockPool.numPending has been protected by BlockPool.mtx, the atomic operate maybe redundant.

**Comment by melekes** [comment]
Not true. https://github.com/tendermint/tendermint/blob/ec1c657d5ab87086790760173dbd45b619faa3ee/blockchain/v0/pool.go#L572 

Anyhow, `v0` is outdated. Please use `v2` blockchain.
