### ISSUE TITLE
[INFO] addrbook.json

### ISSUE THREAD

**Issue by dbriggsie** [tendermint/tendermint#4540]
Hi I am just looking for some information because i cant find it anywhere.

If a validator node in an addressbook that others have cant be connected or becomes unreachable for a certain amount of time... Does this validator node get removed from the addrbook across the network?
If so, how long does it need to be unreachable for it to be automatically removed from addrbooks

**Comment by cmwaters** [comment]
Hi there, 
Currently any peer, be it a validator or full node, is given 16 attempts with exponential backoff, which in total amounts to around 35 hours, to connect. If the node remains unreachable then it is automatically removed from the address book (Note: there is an issue #1614 to create a ban list - where nodes aren't first removed completely but banned for a period of time). But for persistent peers, we indefinitely try to dial all persistent peers unless `persistent_peers_max_dial_period` is configured to zero. 

An unreachable validator node is not gossiped across the network i.e. all other nodes will each try to connect to the unreachable validator node before removing it from their address book. 

For more information have a look at https://github.com/tendermint/spec/blob/master/spec/p2p/node.md
or https://github.com/tendermint/spec/blob/master/spec/reactors/pex/pex.md#select-peers-to-dial

Hopefully that answers your question :)

**Comment by dbriggsie** [comment]
yes :) thanks please close
