### ISSUE TITLE
index_all_tags have been replaced with index_all_keys but not reflected in the CHANGLOG

### ISSUE THREAD

**Issue by kwunyeung** [tendermint/tendermint#4544]
**What happened**:
We have upgraded out testnet with SDK v0.38.1 and found that all txs were not indexed with height and the events. 

**What you expected to happen**:
`/tx_search?query="tx.height=140760"` should return results of txs in the specific height. It doesn't as we didn't know about the changed of configurations.

**Anything else we need to know**:

It works after we have changed the `index_all_tags` to `index_all_keys` in the `config.toml`. This was not reflected in the `CHANGELOG.md` in v0.33.

Both `index_keys` and `index_all_keys` are new in the config.

https://github.com/tendermint/tendermint/blob/v0.33.1/config/config.go#L923

**Comment by marbar3778** [comment]
https://github.com/tendermint/tendermint/blob/master/UPGRADING.md#config-changes

there was mention of needing to regenerate your config.toml, not only for this change but also for consensus param additions.
