### ISSUE TITLE
Use caching of headers to improve bisection performance

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4546]
## Summary

I think the title is sufficient of a summary

## Problem Definition

As raised in #4504, non-recursive bisection suffers from the problem whenever it bisects the gap, that it will need to ask for the validator set from the primary again.

For a simple example. If in order to validate 256 blocks you must

grab block 256 -> fail -> grab block 128 -> fail -> grab block 64 -> success
test block 256 -> fail -> grab block 160 -> success
test block 256 -> success

It would be better however to cache block 128 and use this instead, making it most likely quicker than retrieving block 160

## Proposal

Have a map of retrieved blocks that the light clients caches and refers to instead of asking for a full node to send the light client the blocks

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
> I think the title is sufficient of a summary

lol, you can just delete the section if you feel it's not relevant!
