### ISSUE TITLE
rpc: Implement an endpoint to simply check a transaction

### ISSUE THREAD

**Issue by blinky3713** [tendermint/tendermint#4549]
## Summary

Implement and RPC endpoint to simply check a transaction

## Problem Definition

Right now to my knowledge it is not possible to simply preview whether a transaction would succeed or not without attempting to run it. This differs from ethereum where we have different RPC methods
`eth_sendTransaction` for sending an asynchronous transaction and `eth_call` for querying state *but also* attempting to run a transaction and see the return value. It is sometimes useful to have this ability to preview transactions without running them.

## Proposal

expose `checkTx`as an rpc call that would proxy the `checkTx` abci message to the application.
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
👍 (don't see why we can't do it)

**Comment by blinky3713** [comment]
Thanks! For some background, this is for a specific UI issue that a colleague of mine was having. He wanted the user to be able to preview the result of the transaction as well as the fees before the user actually submits.
