### ISSUE TITLE
A consensus deploy issue

### ISSUE THREAD

**Issue by Xiaohong027** [tendermint/tendermint#4556]
Summary

    Protocol puzzled.

Problem Definition
    Thank you for such a wonderful project and attention for the issue. There's a little question I can't find it out.
    The requirement of our project is: only our own nodes run the BFT protocol. Should we make any changes to the Tendermint Core? How to modify / add the node's stake shares during the blockchain running?

**Comment by marbar3778** [comment]
currently, there is not a way to have some nodes participate in consensus. we would have to allow nodes to stay in fast sync or a different protocol.

**Comment by melekes** [comment]
You can have nodes, which won't be voting (aka "full node"). Your nodes can be validators, which vote on blocks. Note full nodes will still be running the whole consensus algorithm (gossiping votes and block parts, applying blocks). We can change the consensus reactor to not participate in gossiping votes/block parts and only apply blocks **in case of full nodes**, but this is not on our immediate roadmap. Thank you!

If you have any further questions or requests, please leave a comment here.

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/issues/2237
