### ISSUE TITLE
Gov param-change not working

### ISSUE THREAD

**Issue by dbriggsie** [tendermint/tendermint#4559]
Hi there I am struggling to change the MaxDepositPeriod & MaxVotingPeriod params on a testnet… What am I doing wrong here?

```
{
  "title": "Deposit/Vote Time",
  "description": "This is a testnet, lets make this quicker",
  "changes": [
    {
      "subspace": "gov",
        "key": "max_deposit_period",
      "value": 72800000000000
    }
  ],
  "deposit": [
    {
      "denom": "testtoken",
      "amount": "10000000"
    }
  ]
}
```
I have checked this link, and if I add "key": deposit params & "subkey" max_deposit_period .. it still doesnt work.
https://github.com/gavinly/CosmosParametersWiki/blob/master/Governance.md#technical-specifications

Could someone please assist in figuring this out for me.

**Comment by marbar3778** [comment]
I believe this issue would be better suited in the cosmos-sdk or gaia. Tendermint does not interact with application state.
