### ISSUE TITLE
Add Docker image default configuration

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#4569]
## Summary
Add a default configuration to the tendermint docker image. Currently, the image does not have any configuration 'baked in'.

## Problem Definition
Currently, the tendermint docker image requires the end-user to run the `init` command with a mounted volume and then in a second command, it can run `node` if that mounted volume is attached. (Details here: https://hub.docker.com/r/tendermint/tendermint under the "How to use this image" section).

In some cases the user cannot mount a volume to the image and regardless, it is cumbersome to do it. The most recent use-case where it make the image unusable is GitHub Actions. GitHub Actions has a 'Services' component that can run docker images as backend services while running CI (for example integration testing). Examples include nginx, redis and postgres. The common point in all those examples is that the service starts with one command. The Services component does allow users to mount a volume, but the service is set up before the repository gets cloned, hence it becomes a chicken-and-egg problem.
I would like to use the Tendermint docker image as a service in some GitHub Actions.

Possible disadvantage of the feature is that end-users with more complex configuration need to be aware that they need to override the default configuration (by mounting a volume). This can be clarified in the documentation mentioned above.

## Proposal
During the docker image deployment, `tendermint init` should run and create a default configuration in the home folder. This can be achieved by modifying the `Dockerfile`.

Possibly the default ABCI application should be kvstore, not a TCP socket.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tarcieri** [comment]
It'd also be nice to do this for the KMS, which has also moved over to GitHub actions:

https://github.com/iqlusioninc/tmkms/issues/15
