### ISSUE TITLE
Tendermint's http endpoint response status codes

### ISSUE THREAD

**Issue by davebryson** [tendermint/tendermint#457]
BUG REPORT
version: 0.9.0
issue with Tendermint's http rpc return status codes

Making a GET call to any undefined path returns status code 200.  For non-browser clients this makes it difficult to detect an error and determine whether or not to parse the response.  For example, calling:

GET http://localhost:46657/broadcast_tx_cc  returns status code 200 (OK)  'broadcast_tx_cc' is not actually a recognized command.  It should return a NON 200 code, perhaps a 501 code.

**Comment by ebuchman** [comment]
Great point. We currently just dump an html list of all the endpoints, which is convenient in the browser, but we should change to only do that for `/`, and to return a real error for any undefined route.

**Comment by melekes** [comment]
> We currently just dump an html list of all the endpoints, which is convenient in the browser, but we should change to only do that for /

this is exactly what we're doing right now https://github.com/tendermint/go-rpc/blob/develop/server/handlers.go#L32

> to return a real error for any undefined route.

we do return an error, but as @davebryson said, the status code in response is always 200 
https://github.com/tendermint/go-rpc/blob/develop/server/handlers.go#L120
https://github.com/tendermint/go-rpc/blob/develop/server/http_server.go#L56

**Comment by ebuchman** [comment]
How about something like https://github.com/tendermint/tendermint/pull/459

**Comment by ebuchman** [comment]
merged on develop
