### ISSUE TITLE
Halted Chain Bug

### ISSUE THREAD

**Issue by dbriggsie** [tendermint/tendermint#4571]
Hi there,

I think I have found a bug on a testnet version. Maybe Bounty worthy..

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.1.0-3-gff4c7f8

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
- **Install tools**:
- **Others**:

**What happened**:
Firstly I passed a param-change proposal
`{
  "title": "Rwd Change",
  "description": "This is tansaction to test a parameter-change for rewards.",
  "changes": [
    {
      "subspace": "distribution",
      "key": "baseproposerreward",
      "value": "0.999000000000000000"
    }
  ],
  "deposit": [
    {
      "denom": "uscrt",
      "amount": "10000000"
    }
  ]
}
`
then around 5000 blocks later.. the chain stopped working.. without nodes going offline or stopping

Errors persisted:

`Mar 16 08:36:03 li1960-49 enigmad[1409]: I[2020-03-16|08:36:03.208] starting ABCI with Tendermint                module=main
Mar 16 08:36:03 li1960-49 enigmad[1409]: panic: negative coin amount
Mar 16 08:36:03 li1960-49 enigmad[1409]: goroutine 1 [running]:
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/types.DecCoins.Sub(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/types/dec_coin.go:307
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.AllocateTokens(0x169cf60, 0xc000ad0200, 0xc000aba460, 0xc000aba460, 0x169cf60, 0xc000ad0230, 0x169cfa0, 0xc000ad0280, 0xc000ab1500, 0xc, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/x/distribution/keeper/allocation.go:66 +0x1589
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/x/distribution.BeginBlocker(0x16ad9a0, 0xc000034068, 0x16c2100, 0xc001df8880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/x/distribution/abci.go:26 +0x2e6
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/x/distribution.AppModule.BeginBlock(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/x/distribution/module.go:147
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc000abb030, 0x16ad9a0, 0xc000034068, 0x16c2100, 0xc001df8880, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/types/module/module.go:297 +0x1ca
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/enigmampc/EnigmaBlockchain.(*EnigmaChainApp).BeginBlocker(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/enigmachain/app.go:391
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc000d23e00, 0xc00202a6a0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/baseapp/abci.go:136 +0x469
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000d209c0, 0xc00202a6a0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/abci/client/local_client.go:231 +0x101
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc000e2a450, 0xc00202a6a0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/proxy/app_conn.go:69 +0x6b
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x16ae3a0, 0xc000de8580, 0x16bb520, 0xc000e2a450, 0xc001ef9500, 0x16c4080, 0xc000b9e068, 0x6, 0xc000cf5570, 0xe)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/state/execution.go:280 +0x3e1
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000e8fc00, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/state/execution.go:131 +0x17a
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc000b310b0, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:475 +0x233
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc000b310b0, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:455 +0x3f3
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000c530b0, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:386 +0xeef
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000b310b0, 0x16c4d80, 0xc000108bd0, 0x7f83d63ddd63, 0x115f208)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:269 +0x485
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/node.doHandshake(0x16c4080, 0xc000b9e068, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/node/node.go:281 +0x19a
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/node.NewNode(0xc000d232c0, 0x16a7ce0, 0xc000b546e0, 0xc000b88360, 0x168b7c0, 0xc000b9bdc0, 0xc000b88590, 0x149b570, 0xc000b885a0, 0x16ae3a0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/node/node.go:597 +0x343
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000d28460, 0x149bd98, 0x1d, 0x0, 0x0)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/server/start.go:157 +0x4c1
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000d42000, 0x1fde8a0, 0x0, 0x0, 0x0, 0x0)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/server/start.go:67 +0xb4
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/spf13/cobra.(*Command).execute(0xc000d42000, 0x1fde8a0, 0x0, 0x0, 0xc000d42000, 0x1fde8a0)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0000a4c80, 0x13366cb, 0xc00043fe90, 0x591822)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000a4c80, 0x149c1d0, 0x13198a6, 0x10)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/libs/cli/setup.go:89 +0x3c
Mar 16 08:36:03 li1960-49 enigmad[1409]: main.main()
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/enigmachain/cmd/enigmad/main.go:69 +0x7ab
Mar 16 08:36:03 li1960-49 systemd[1]: enigma-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 16 08:36:03 li1960-49 systemd[1]: enigma-node.service: Failed with result 'exit-code'.
`

**What you expected to happen**:
I just expected this to run normally..

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):
As follows above

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

`Mar 16 08:36:03 li1960-49 enigmad[1409]: I[2020-03-16|08:36:03.208] starting ABCI with Tendermint                module=main
Mar 16 08:36:03 li1960-49 enigmad[1409]: panic: negative coin amount
Mar 16 08:36:03 li1960-49 enigmad[1409]: goroutine 1 [running]:
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/types.DecCoins.Sub(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/types/dec_coin.go:307
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/x/distribution/keeper.Keeper.AllocateTokens(0x169cf60, 0xc000ad0200, 0xc000aba460, 0xc000aba460, 0x169cf60, 0xc000ad0230, 0x169cfa0, 0xc000ad0280, 0xc000ab1500, 0xc, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/x/distribution/keeper/allocation.go:66 +0x1589
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/x/distribution.BeginBlocker(0x16ad9a0, 0xc000034068, 0x16c2100, 0xc001df8880, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/x/distribution/abci.go:26 +0x2e6
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/x/distribution.AppModule.BeginBlock(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/x/distribution/module.go:147
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(0xc000abb030, 0x16ad9a0, 0xc000034068, 0x16c2100, 0xc001df8880, 0xa, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/types/module/module.go:297 +0x1ca
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/enigmampc/EnigmaBlockchain.(*EnigmaChainApp).BeginBlocker(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/enigmachain/app.go:391
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(0xc000d23e00, 0xc00202a6a0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/baseapp/abci.go:136 +0x469
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc000d209c0, 0xc00202a6a0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/abci/client/local_client.go:231 +0x101
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc000e2a450, 0xc00202a6a0, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/proxy/app_conn.go:69 +0x6b
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/state.execBlockOnProxyApp(0x16ae3a0, 0xc000de8580, 0x16bb520, 0xc000e2a450, 0xc001ef9500, 0x16c4080, 0xc000b9e068, 0x6, 0xc000cf5570, 0xe)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/state/execution.go:280 +0x3e1
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc000e8fc00, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/state/execution.go:131 +0x17a
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(0xc000b310b0, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:475 +0x233
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc000b310b0, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:455 +0x3f3
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000c530b0, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, 0x20, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:386 +0xeef
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000b310b0, 0x16c4d80, 0xc000108bd0, 0x7f83d63ddd63, 0x115f208)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/consensus/replay.go:269 +0x485
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/node.doHandshake(0x16c4080, 0xc000b9e068, 0xa, 0x0, 0xc000cf5550, 0x6, 0xc000cf5570, 0xe, 0x29c8a, 0xc000cde380, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/node/node.go:281 +0x19a
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/node.NewNode(0xc000d232c0, 0x16a7ce0, 0xc000b546e0, 0xc000b88360, 0x168b7c0, 0xc000b9bdc0, 0xc000b88590, 0x149b570, 0xc000b885a0, 0x16ae3a0, ...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/node/node.go:597 +0x343
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/server.startInProcess(0xc000d28460, 0x149bd98, 0x1d, 0x0, 0x0)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/server/start.go:157 +0x4c1
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000d42000, 0x1fde8a0, 0x0, 0x0, 0x0, 0x0)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/server/start.go:67 +0xb4
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/spf13/cobra.(*Command).execute(0xc000d42000, 0x1fde8a0, 0x0, 0x0, 0xc000d42000, 0x1fde8a0)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x460
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/spf13/cobra.(*Command).ExecuteC(0xc0000a4c80, 0x13366cb, 0xc00043fe90, 0x591822)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/spf13/cobra.(*Command).Execute(...)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
Mar 16 08:36:03 li1960-49 enigmad[1409]: github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0000a4c80, 0x149c1d0, 0x13198a6, 0x10)
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/libs/cli/setup.go:89 +0x3c
Mar 16 08:36:03 li1960-49 enigmad[1409]: main.main()
Mar 16 08:36:03 li1960-49 enigmad[1409]:         /home/assafmo/workspace/enigmachain/cmd/enigmad/main.go:69 +0x7ab
Mar 16 08:36:03 li1960-49 systemd[1]: enigma-node.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 16 08:36:03 li1960-49 systemd[1]: enigma-node.service: Failed with result 'exit-code'.
`

**Config (you can paste only the changes you've made)**:
I have no config.toml changes that relate to this issue

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
This seems like a cosmos-SDK issue. Could you open an issue in that repo?
