### ISSUE TITLE
Automatically repair the WAL file in case of corruption

### ISSUE THREAD

**Issue by ptrus** [tendermint/tendermint#4578]
## Summary

Automatically try repairing the WAL file in case of corruption.

## Problem Definition

We are doing some stress testing that includes killing nodes at random. It seems that tendermint's WAL often gets corrupted. Is there any reason why the WAL should not be automatically truncated in this case? I think automatically truncating the WAL should be safe to do, as it would just mean that not fully committed state would be rolled back? 

Example of crash logs:
```
{"caller":"replay.go:151","err":"DataCorruptionError[failed to read data: EOF (read: 25297, wanted: 33864)]","height":19682,"level":"error","module":"tendermint:consensus","msg":"data has been corrupted in last height of consensus WAL","ts":"2020-03-04T04:02:16.242757143Z"}
{"caller":"state.go:321","err":"DataCorruptionError[failed to read data: EOF (read: 25297, wanted: 33864)]","level":"error","module":"tendermint:consensus","msg":"Encountered corrupt WAL file","ts":"2020-03-04T04:02:16.242798982Z"}
{"caller":"state.go:322","level":"error","module":"tendermint:consensus","msg":"Please repair the WAL file before restarting","ts":"2020-03-04T04:02:16.242823017Z"}
```

Logs then point to "manually fixing the WAL" which involves running a couple of scripts, that could happen automatically (potentially configurable via a config flag): https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L315-L324  

Note: we are not shutting down nodes gracefully, meaning that the WAL flush shutdown hook is skipped. This is likely the reason for the relatively high rate of WAL corruptions we observe. However nodes crashing non-gracefully is a realistic scenario that should probably be better handled by tendermint.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
> I think automatically truncating the WAL should be safe to do

what about double voting? in the same round for 2 different proposals? this could happen if you truncate the WAL, although it's very rare case. => **I don't think it's safe**

and yes, we should absolutely automate running the scripts, but it's not an immediate priority right now. contributions are welcomed 😺 

> This is likely the reason for the relatively high rate of WAL corruptions we observe. However nodes crashing non-gracefully is a realistic scenario that should probably be better handled by tendermint.

Absolutely agree!
