### ISSUE TITLE
Valid transactions are rejected without invoking ABCI server if they are duplicates

### ISSUE THREAD

**Issue by KrzysiekJ** [tendermint/tendermint#458]
**BUG REPORT**

**Tendermint version**:

0.9.0

**ABCI app**:

[abci_counter](https://github.com/KrzysiekJ/abci_counter/tree/45c85c3298d9a4aeac9fa031f51412e1c993c6ef) (Erlang implementation, commit 45c85c32)

**What happened**:

Valid transaction has been rejected due to being a duplicate and it has not been passed to the ABCI server.

**What should happen**:

Valid transaction should be passed to the ABCI server (and accepted).

**How to reproduce it**:

```shell
curl 'http://localhost:46657/broadcast_tx_commit?tx=0x01'
curl 'http://localhost:46657/broadcast_tx_commit?tx=0x00'
curl 'http://localhost:46657/broadcast_tx_commit?tx=0x01'
```

**Comment by ethanfrey** [comment]
This is desired behavior. Otherwise, all apps are susceptible to old TX being replayed. 

Suggested solution is to add a nonce to the TX to make them unique. This could also have validation logic (like a per-account counter) to make sure they are executed in order. This is what Basecoin does.

**Comment by KrzysiekJ** [comment]
If Tendermint provides replay protection, then why Basecoin has its own replay protection (sequence number in accounts)? Also I guess this means all transaction from genesis need to be stored by Tendermint and no pruning will ever be possible?

Anyway, the transaction in this issue has been rejected initially; accepting it when context changed does not necessarily mean “replay”.

**Comment by KrzysiekJ** [comment]
Also if Tendermint is stopped (leaving the ABCI server running) and started, then the transaction is accepted, so this is not a real replay protection. I would suggest leaving this on the ABCI applications’ side (in particular because there are various ways to achieve this, not necessarily tailored equally for all apps).

**Comment by ethanfrey** [comment]
Seems like good arguments.  @jaekwon @ebuchman can you comment here?

**Comment by ebuchman** [comment]
Correct, it's not a real replay protection. It's a mempool heuristic. It is still the responsibility of the app to handle replay protection. The mempool does not guarantee it, but it helps a little bit. The mempool keeps a cache of the last 10k txs its seen. So if you restart, or you've sent more than 10k txs, you'll be able to replay through the mempool. It's only rejecting based on seeing an identical tx.

What's the use case for removing this from the mempool? Do we really want it to allow duplicate txs? We have had this conversation before and decided to keep it as it is, but open to suggestions.

**Comment by KrzysiekJ** [comment]
There are many possible cases where a transaction will (or may) become valid in some future state. In those cases, blocking of duplicates may cause obstacles. Some examples:

* If a transaction is only valid in a specific time window (this may be used as a part of replay protection mechanism), then submitting it too early may prevent it from being delivered at all (if a light client is not prepared to submit it to another validator or someone maliciously submits it to every validator).
* In case of an ABCI app which stores sports results, submitting a result before it actually occurs will block it from delivering.
* If a transaction with nonce too big is submitted to the counter application, then the application will be blocked at that nonce.

**Comment by melekes** [comment]
Maybe we can make the size of the cache configurable? `0` - no cache. Don't want to remove the cache cause I suspect that it will hurt the performance.

**Comment by ebuchman** [comment]
> where a transaction will (or may) become valid in some future state. 

Indeed! Transactions that fail CheckTx are removed from the cache - so it's important that CheckTx implements the replay prevention. Also, the mempool will replay all transactions in the mempool through CheckTx after every block, discarding those which are no longer valid.

**Comment by KrzysiekJ** [comment]
> Transactions that fail CheckTx are removed from the cache - so it's important that CheckTx implements the replay prevention.

If a transaction fails `CheckTx`, then it will not be included in a block, so there is no place for occurence of replay in such case — if I understand correctly.

**Comment by ebuchman** [comment]
Right - if it fails CheckTx it will be removed from the mempool (or will never make it in in the first place)

**Comment by ebuchman** [comment]
I'm gonna close this in favor of https://github.com/tendermint/tendermint/issues/345 which is amalgamating some issues with the mempool cache.
