### ISSUE TITLE
WIP/DRAFT: Events Refactor

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#4592]
* Tendermint should use events for core events - simple synchronous event system makes debugging easier too.  But this means the websocket listeners need to be a little more intelligent.
* Event details should not have to be stringified before being handled by a lib/pubsub generic library.  Better to keep them as primitive objects that only need to be serialized when a listener matches.
* Query should act on a single event, not a list of "events".  There's something convoluted IMO about the pubsub design.
* NewBlock NewBlockHeader events should be deconstructed.  Better to provide events as they happen synchronously, and if we want to provide convenience functions, we can create closures.  We may need to pass info in context(?).
* There should be an event bus per listener, and the listener should get
disconnected when writing lags beyond some amount of time.
* All events subscribed should get written, instead of using "Try".

**Comment by melekes** [comment]
> Tendermint should use events for core events - simple synchronous event system makes debugging easier too

we do use `events` package internally and I agree.

> Event details should not have to be stringified before being handled by a lib/pubsub generic library. Better to keep them as primitive objects that only need to be serialized when a listener matches.

because of performance hits?

> Query should act on a single event, not a list of "events".

The idea behind this is to eventually allow complex queries like "account.receiver=Alex OR account.submitter=Alex"

> NewBlock NewBlockHeader events should be deconstructed. Better to provide events as they happen synchronously

Better for whom? For WS subscribers? We should be careful not to put additional pressure on the system as it may slow down consensus (especially if you're talking about sync events)

> There should be an event bus per listener, and the listener should get
disconnected when writing lags beyond some amount of time.

Nice idea. Would there be a global evenBus, which will proxy events to listeners eventBuses?

**Comment by jaekwon** [comment]
> The idea behind this is to eventually allow complex queries like "account.receiver=Alex OR account.submitter=Alex".

I like it, and we can accomplish that with a single ABCI event which has a "name" string and attributes.  <name>.<attribute>=<value> can still work.

I think it's more about, how we group ABCI response events as "events", and this nesting of tx ABCI responses as "events" in NewBlock... is what is confusing and strange.  The pubsub system calls an event a "msg" and some of the attributes (the ABCI response) of a particular type of event (Tx events, but grouped into a NewBlock event) an "event".

I think it would be better to break apart this compound NewBlock event into its components, as they happen, synchronously.

For example, TendermintCore websocket can emit a "BeginBlock" event as soon as it happens.  Also, each transaction ABCI response could also emit their own ABCI event.  And "EndBlock" would happen after.

If this also happened synchronously, it would make for a simple implementation at the core which can be debugged easily.  For example, you could include a breakpoint upon any event, and you can inspect the state of the whole machine.

We can do two more things to make this maybe more acceptable to people:

* Also implement something to let the synchronous events not block when there are blocking listeners.  I think one fairness principle of Tendermint should be that each websocket listener gets one "unit" of buffer, that way many connections can't suddenly DDoS the TendermintCore daemon's memory.  In other words, the number of websocket connections becomes a lever that can be adjusted to control for limited memory.

> Better for WS subscribers? We should be careful not to put additional pressure on the system as it may slow down consensus (especially if you're talking about sync events)

for clarification, my above point would help be explicit about pressures in the system coming from websocket connections, such as how much each connection can contribute to memory usage for buffers.

* Convenience events that are composites could be created... and they could be implemented with closures such that they don't even lead to serialization unless the composite events are requested.  So no existing client API needs to change.

I'm not sure it's necessary to prevent the serialization of Tendermint event objects, good point @melekes .  ABCI response events are already in bytes form, and Tendermint protocol itself produces limited events.  I guess they can stay as bytes until someone proves something about efficiency.

**Comment by melekes** [comment]
> I think it's more about, how we group ABCI response events as "events", and this nesting of tx ABCI responses as "events" in NewBlock... is what is confusing and strange.

> I think it would be better to break apart this compound NewBlock event into its components, as they happen, synchronously.

I agree!

Will there be an event people can subscribe to receive a full block though?

>  I think one fairness principle of Tendermint should be that each websocket listener gets one "unit" of buffer, that way many connections can't suddenly DDoS the TendermintCore daemon's memory. In other words, the number of websocket connections becomes a lever that can be adjusted to control for limited memory.

We already have this. I implemented that a few weeks ago: https://github.com/tendermint/tendermint/pull/4521
