### ISSUE TITLE
Make blockchain v2 reactor the default

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4595]
## Summary

We should start a push to make the `v2` blockchain reactor the default, deprecate the `v0` and `v1` reactors, and eventually remove them.

To begin with, we need to get more real-world testing of `v2`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Liamsi** [comment]
> To begin with, we need to get more real-world testing of v2.

Is there anything outside contributors / the larger community can do to help you with that?

**Comment by erikgrinaker** [comment]
>Is there anything outside contributors / the larger community can do to help you with that?

Thanks - trying it out on a few test nets and/or individual production nodes and letting us know how it goes (even if it was all fine) would be really helpful.

> CustomReactors calls RemoveReactor and it then calls reactor.SetSwitch(nil)

Ah, that's no good. Submitted PR #4671 for this.

**Comment by melekes** [comment]
Closing in favor of https://github.com/tendermint/tendermint/issues/5681
