### ISSUE TITLE
Question: Seed nodes, and PEX connectivity issues

### ISSUE THREAD

**Issue by steevi** [tendermint/tendermint#4600]
Hi.

I haven't completely understood how the seed node connectivity should happen with the rest of the network, and how pex module works. To clarify I have `addr_book_strict = false` as I use private IP addresses.

Regarding seed node connectivity, I have a local test network of four validators, which connect to 4 sentries (1-1 mapping). If I use persistent peers connectivity between sentries, then the network starts correctly, and blocks are created. However, If I create a seed node, and point sentries to the sed node using the `seeds = ""` parameter, then the network does not start.
What should be the ideal topology of the sentry nodes? Should they connect to the network using persistent_peers?

Regarding the pex module, If I point four sentries using `persistent_peers = ""` to a new sentry node (lets name it `boostrapsentry`), network starts correctly. If I shutdown the boostrapsentry node, then the blockchain halts (I guess peer information has not been exchanged at all). On the other hand, If I use `persistent_peers` at the bootstrapsentry node to connect to the 4 sentries, then the blockchain does not halt if bootstrap sentry is stopped. Is this normal?

Thanks

**Comment by melekes** [comment]
> However, If I create a seed node, and point sentries to the sed node using the seeds = "" parameter, then the network does not start.

This is the known issue - https://github.com/tendermint/tendermint/issues/3778. Please refer to [this comment](https://github.com/tendermint/tendermint/issues/3778#issuecomment-598183394) for a short term fix.

Check out https://github.com/tendermint/tendermint/blob/9b708b959ff95fc775852e6f284ca712dc1a0cb4/docs/tendermint-core/validators.md

> Is this normal?

It should work either way. Can this be related to the above issue (#3778 )?

**Comment by steevi** [comment]
Thanks a lot @melekes 
This quick fix solves both issues!
