### ISSUE TITLE
change use of errors.Wrap to fmt.Errorf with %w verb

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4603]
## Summary

Currently, throughout the repo we use errors.Wrap. This change was made before `%w` verb was introduced in go. 

## Proposal

Change all occurrences of `errors.Wrap` to `fmt.Errorf` with the `%w` verb.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- ~~[ ] Appropriate contributors tagged~~
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
https://github.com/Djarvur/go-err113 can be added as a linter when this is completed

**Comment by jyizheng** [comment]
I am interested to do this as my first issue. But I am not very fluent at Go.
I may need more guidance on this.
I have the example below: 

panic(errors.Wrap(err, "error start app"))
Should I change it to:

var ErrStartApp = errors.New("error start app")
err := fmt.Errorf("xxx: %w", ErrStartApp)

xxx can be replaced with the name of the module.

Is this correct?

**Comment by fedekunze** [comment]
I think it should be:

```go
panic(errors.Wrap(err, "error start app"))
```

to

```go
panic(fmt.Errorf("error start app: %w", err))
```
