### ISSUE TITLE
evidence: create a cache in pool to prevent DoS attacks

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4614]
In `EvidencePool#AddEvidence`, check if we've already processed the evidence (based on `Evidence#Hash`). Most likely we'll need to create a `map[string(Evidence#Hash())] => true` (of some fixed size = 1000) and perform a lookup before processing an evidence.

**Comment by cmwaters** [comment]
Wouldn't we want to use the store instead of creating a new variable and just connect the `Has()` function of the DB interface?

**Comment by melekes** [comment]
good idea!
