### ISSUE TITLE
lite2: VerifyCommitTrusting will report double vote error

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4618]
if `ValidatorAddress` is not found in `valSet` more than once

Fix: do not check `seenVals` if validator with `ValidatorAddress` is not found (idx=-1, val=nil)

**Comment by marbar3778** [comment]
We should remove `-1` as a placeholder for nil, `GetByAddress` should return an error and then we can remove the dependence on `-1`. This is a bit of a refactor but its mainly just checking for `err`

**Comment by melekes** [comment]
> We should remove -1 as a placeholder for nil, GetByAddress should return an error and then we can remove the dependence on -1. This is a bit of a refactor but its mainly just checking for err

I disagree.
