### ISSUE TITLE
evidence: DuplicateVoteEvidence does not allow different ValidatorIndex

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4619]
`DuplicateVoteEvidence` does not allow votes to have different `ValidatorIndex` (1 and 2, for example). 

https://github.com/tendermint/tendermint/blob/6c88d2ba1f152d52728d0b5a02de12fe4872f0ba/types/evidence.go#L180-L187

While it makes sense in a regular setting where we know validator set size, if the full node is following a fork, validator set might change (on another branch of a fork), but we'd still want to punish it for double voting, no?

**Block**
Val Set: A C D
Val who double signed: C
Val Index: 1

**Alt. Block**
Val Set: A B C D
Val who double signed: C
Val Index: 2

**Comment by cmwaters** [comment]
But a double votes don't happen on a fork they are what leads to a fork. When the double vote itself happens validator sets should be the same. Unless it is a double vote on an already undetected fork.

**Comment by melekes** [comment]
Right.

> Unless it is a double vote on an already undetected fork.

I guess it's too early to even consider such cases.
