### ISSUE TITLE
Persistent & Unconditional Peers similarity 

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4622]
## Problem Definition

Currently, we have persistent peers and unconditional peers. 

Persistent peers: Peers that a node will always try to connect to unless the node has a full address book. 

Unconditional peers: Peers that a node will always be connected to no matter the inbound and outbound limit of peers.

A persistent peer has become redundant. 

## Proposal

Remove Persistent Peers and rename Unconditional Peers to Persistent Peers

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
https://github.com/b-harvest/tendermint/blob/master/docs/architecture/adr-050-improved-trusted-peering.md#decision

```
Persistent_peers is only for outbound, therefore it is not enough to cover the full utility of unconditional_peer_ids. @creamers158(https://github.com/Creamers158) suggested putting id-only items into persistent_peers to be handled as unconditional_peer_ids, but it needs very complicated struct exception for different structure of items in persistent_peers. Therefore we decided to have unconditional_peer_ids to independently cover this use-case.
```
