### ISSUE TITLE
light: node/RPC import cycle

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4626]
The HTTP-based light client can't be used in the node or its reactors because of an import cycle:

```
package github.com/tendermint/tendermint/cmd/tendermint
	imports github.com/tendermint/tendermint/cmd/tendermint/commands
	imports github.com/tendermint/tendermint/lite2
	imports github.com/tendermint/tendermint/lite2/provider/http
	imports github.com/tendermint/tendermint/rpc/client
	imports github.com/tendermint/tendermint/node
	imports github.com/tendermint/tendermint/lite2
```

The light client depends on the HTTP RPC client, but that client is in the same package as the Node-based RPC client, and that client depends on the node package, which depends on the light client, and so on.

I propose splitting the `rpc/client` package into separate packages per client, e.g. `rpc/client/http` and `rpc/client/node`, to break the cycle.

**Comment by tessr** [comment]
That seems reasonable to me.
