### ISSUE TITLE
cli: tendermint node exits w/ "Stopping abci.socketClient for error: EOF"

### ISSUE THREAD

**Issue by LuffySmile** [tendermint/tendermint#4627]
When I run tendermint node,  I get a error :

```
E[2020-04-02|07:48:10.743] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
ERROR: Failed to create node: Error during handshake: Error on replay: EOF
```

How to resolve it ?

**Comment by marbar3778** [comment]
Hey, thanks for opening up an issue. Could you give a bit more information on what happened leading up to this? 

Could you try running `tendermint unsafe-reset-all` then `tendermint node` again.

**Comment by LuffySmile** [comment]
I build a blockchain network with four nodes. Three of the nodes are normal, but the fourth node cannot start tendermint. When I run tendermint node, I get a error :
E[2020-04-02|07:48:10.743] Stopping abci.socketClient for error: EOF module=abci-client connection=consensus
ERROR: Failed to create node: Error during handshake: Error on replay: EOF
I have tried runing tendermint unsafe-reset-all then tendermint node again.but it dons`t work.
My genesis.json is as follows：
{
  "genesis_time": "2020-04-01T00:47:38.898058614Z",
  "chain_id": "test-chain-6hwKm0",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age": "100000"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    }
  },
  "validators": [
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "aKlTsl5ZP0CKE5Ca/GYrqu8yjcJjyiu8Qp2+5BF+yZA="
      },
      "power": "10",
      "name": "Ubuntu Server 21"
    },
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "7lDZyOeABHSfn32ZDPWpqjkhnqTU9s/uUQNCJJ1IVus="
      },
      "power": "10",
      "name": "Ubuntu Server 22"
    },
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "Mv0g8cCZt2QwcVnZC68LJHmap9ef5nWqoznhRKIy1T4="
      },
      "power": "10",
      "name": "Ubuntu Server 23"
    },
    {
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "P4iA1dIjTVlWjvReUa7W4w7usZzjeqiHlS36FAkuYhA="
      },
      "power": "10",
      "name": "Ubuntu Server 24"
    }
  ],
  "app_hash": "" 
}                                                                                                                                         13,5          Top

**Comment by melekes** [comment]
What ABCI app are you running? 

Looks like Tendermint can't connect to your ABCI app. Please make sure your ABCI app is up and listening for connections on port `26658` (`proxy_app = "tcp://127.0.0.1:26658"` in the config).

If you want to change the default port or run one of the built-in applications (kvstore, persistent_kvstore, etc.), use the `--proxy_app=kvstore` command-line flag. You can also change the `config.toml` file.

**Comment by LuffySmile** [comment]
I use BigchainDB.

**Comment by melekes** [comment]
Could you paste logs from BigchainDB instance TM node #4 is trying to connect to?

**Comment by LuffySmile** [comment]
I hava rebuilded the blockchain betwork,and all nodes are normal now ,so I could not get the log and paste these.

**Comment by melekes** [comment]
Okay. I assume we can close this now. Feel free to ask any other questions or join our [Discord chat](https://discord.gg/AzefAFd).
