### ISSUE TITLE
Don't store blocks in database

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4630]
The block store currently stores blocks in a database, typically LevelDB. This is suboptimal, since these databases usually aren't optimized for storage of BLOBs, operations like LSM-tree compaction becomes prohibitively expensive, and contents can't be streamed. Blocks should instead be stored in the filesystem, with metadata and a checksum in the LevelDB database.

When fixing this, we should fix #4567 as well.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by melekes** [comment]
@erikgrinaker do u remember why this wasn't accepted?

**Comment by erikgrinaker** [comment]
It's accepted, just a bit tricker than I first though. Tendermint primarily uses block parts, not whole blocks - I think it's too expensive to store block parts as separate files (e.g. due to inode usage and half-full filesystem blocks), so we'll need to maintain an index for each block's part offsets.

**Comment by marbar3778** [comment]
> I think it's too expensive to store block parts as separate files (e.g. due to inode usage and half-full filesystem blocks)

We could look into removing block parts from various parts of the codebase as it pertains to consensus primarily. According to this issue https://github.com/tendermint/spec/issues/78 it is "an unfortunate artifact". It may make sense to tackle the removal in places instead of putting a bandaid on it, although this will require a greater refactor.

**Comment by melekes** [comment]
We'll still have to store erasure-coded chunks somewhere, so I wouldn't say it's a bandaid

**Comment by erikgrinaker** [comment]
So the reason why I abandoned this last time was because if we end up needing to maintain a bunch of indexes, randomly accessing block parts, and storing temporary data and stuff, then I'm not sure if storing blocks as files makes much sense anymore. A better approach might be to use e.g. a B-tree based store (like BoltDB) which doesn't need to do compaction all the time (which _I think_ is what kills LevelDB performance for blocks).
