### ISSUE TITLE
evidence: evidence max age should match trusting period

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4631]
## Proposal

Evidence, as it is a part of fork accountability, should align it's max age with the period that evidence can be enacted in which is the trusting period. Is there need for both parameters or can we simplify it?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
> Is there need for both parameters or can we simplify it?

what do you mean by both? where's trusting period defined?

**Comment by cmwaters** [comment]
> what do you mean by both? where's trusting period defined?

Okay, so is max age actually the trusting period? 
And by trusting period, I just mean the duration with which tokens are staked. Is this defined somewhere?

**Comment by melekes** [comment]
> And by trusting period, I just mean the duration with which tokens are staked. Is this defined somewhere?

Not in Tendermint. In the light client, we have trustingPeriod, which is UnbondingPeriod - evidence propagation delay (2/3 of UnbondingPeriod).

max age should be equal to UnbondingPeriod. I guess we should make this clear in the docs

**Comment by cmwaters** [comment]
okay, yes I would have just misunderstood the terminology - thanks for clarifying - I will just close the issue and add something when I write up the docs in the evidence module

**Comment by melekes** [comment]
better to create an issue https://github.com/tendermint/tendermint/issues/4670
