### ISSUE TITLE
evidence: remove prioritization of evidence.

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4635]
## Problem Definition

At the moment, when evidence is added it is assigned a priority based on the validator's voting power. This is unnecessary as all evidence has come from 1/3+ attacks and most of them (if not all) have led to full forks hence the voting power is relatively irrelevant and should if anything be based on time. It makes more sense that we process the earliest evidence before the later as a) the earliest evidence is closest to going beyond the punishable time and b) the earliest evidence could have caused the later evidence. 

All this said, currently, the evidence reactor doesn't even use the priority for broadcasting - all evidence is broadcasted to peers from a list that loops over and over again. 

## Proposal

Strip away all the prioritisation code, by default the keys which are ordered by evidence height will make it possible to use the broadcasting list and the `PendingEvidence()` function (used in constructing the blocks) to be ordered based on age. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
In addendum, the current process stores the same evidence three times in the database one for items to be broadcasted, one for items to be committed and one for items already committed. This could be better optimized.

As a remark, I wonder if it is also necessary to have both the pool / store and db abstract layers. Is it possible that we just have the pool and db abstractions or do the same with the light client and have an interface so that users can easily change the db they wish to use. These are just ideas, not 100% sure of them.

**Comment by cmwaters** [comment]
@melekes  what do you think?

**Comment by melekes** [comment]
> This is unnecessary as all evidence has come from 1/3+ attacks

not true. duplicate vote can come from incorrect software (master master validator scheme)

**Comment by melekes** [comment]
> In addendum, the current process stores the same evidence three times in the database one for items to be broadcasted, one for items to be committed and one for items already committed. This could be better optimized.

agree 👍 

> As a remark, I wonder if it is also necessary to have both the pool / store and db abstract layers.

feel free to propose a better API / design 👍 

Not sure I understand what's wrong with priority. We want to punish large validators first since they have the most power.

**Comment by cmwaters** [comment]
Yes I guess there is a priority in the sense that equivocation that leads to a fork is probably more important than lunatic attack. But I also feel that we should try to punish offences in order which they occurred.

Can you elaborate about the incorrect software. 

> This is unnecessary as all evidence has come from 1/3+ attacks

Yeah I realised I was wrong about that, also lunatic validator or double votes that were not successful aren't as important

**Comment by cmwaters** [comment]
Probably more important, is that the prioritization described is ignored and not even implemented.

**Comment by cmwaters** [comment]
> feel free to propose a better API / design :+1: 

Similar procedure to the light client. Store becomes just an interface, db remains the same and pool does the main logic

**Comment by melekes** [comment]
> Yes I guess there is a priority in the sense that equivocation that leads to a fork is probably more important than lunatic attack. But I also feel that we should try to punish offences in order which they occurred.

These look like contradicting sentences to me.

I think we do want priority since a space for evidence in a block is LIMITED. sorting by validator power & time of the infraction make a lot of sense to me.

**Comment by cmwaters** [comment]
They are contradicting in the sense that you most likely want to balance validator power and time of infringement

**Comment by cmwaters** [comment]
>  Not sure I understand what's wrong with priority. We want to punish large validators first since they have the most power.

The concern I have with prioritizing just using validator power is that we punish individually so there's nothing stopping one malicious actor from disguising themselves as 20 smaller nodes

**Comment by cmwaters** [comment]
My list of suggested improvements to the evidence module (most likely after #4532 is merged) is:
- [ ] Create a doc.go file to better explain the process of the module
- [ ] If evidence is expired before it is committed we should remove it from the db (reactor.go:200)
- [ ] Use store as an interface, keep db operations with db and the main logic with pool.go (it is unnecessary to have all three)
- [ ] Committed evidence doesn't need to be stored completely, rather a marker pointing to the block in the block store (i.e. the height it is committed and the hash of the evidence for easy lookup)
- [ ] Don't save to all three buckets in the database, rather move evidence from one bucket to the next. There is an argument to have only two buckets: broadcasted and committed. 
- [ ] Restore evidenceList at startup if the database contains evidence marked for broadcasting. This is in case of node failure, it can recover evidence that needs to be broadcasted.
- [ ] Use prioritization algorithm when calling `PendingEvidence` so that evidence can be sent for block proposal in the order of importance. Potentially a weighted average of the voting power and the time to expiry
- [ ] Send evidence in batches. An evidence list is used but only a single piece of evidence is sent at a time. `Receive` is already coded to handle batches of evidence at a time. Fill the max message size with as much evidence is possible.
- [ ] If we don't have any evidence still wait for the `broadcastEvidenceIntervalS` before checking again

Optional:
- [ ] Either remove `MarkEvidenceAsBroadcasted` or implement a system where each node has a map of evidence it has sent to peers and if it receives the same evidence back from the peer it can stop broadcasting to that peer. (NOTE: this is a bit more complicated than just constantly broadcasting but saves i/o)
- [ ] Make `maxMsgSize` and potentially even `broadcastEvidenceIntervalS` configurable (or we could default the latter to be relative to the speed of block production)
- [ ] Set the amount of evidence per block in proportion to the amount of validators in the set not to 1/10th of the block size (#2590)

Considerations:
So far, we have assumed that all evidence received is immediately ready for block proposal, however with the introduction of amnesia evidence, the evidence module must incorporate the option of waiting a defined trial period before it considers the evidence ready to be proposed.

**Comment by melekes** [comment]
> Can you elaborate about the incorrect software.

there was a case on the Cosmos Hub where one of the validators launched a second instance of Tendermint (with the same private validator key), which resulted in the second vote for the same height & round => DuplicateVoteEvidence.

**Comment by melekes** [comment]
> My list of suggested improvements to the evidence module

Great write-up! Agree with most of the points except https://github.com/tendermint/tendermint/issues/2590. Also, prioritization algorithm should take into account that one validator A might try to occupy all the slots by say committing double vote in blocks n, n+1, n+2. Therefore, if we commit evidence in block n, n+1 should first look if there are other validators before committing evidence from A again.

**Comment by cmwaters** [comment]
Closed and replaced with #4675
