### ISSUE TITLE
Node startup phases

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4644]
The way we currently transition from e.g. fast sync to consensus is very messy (the reactors enable/disable message processing and call methods directly each other). This will become even more messy when we implement state sync (#828)  and with fallback to fast sync for lagging nodes (#129).

I suggest we instead have a concept of node phases (e.g. WAL replay, block replay, state sync, fast sync, consensus, and so on), and an overall manager which enables/disables various reactors and processes based on heuristics (e.g. switch to fast sync if consensus is lagging). This requires support for announcing changes in P2P channels (#4394).

This is somewhat related to the idea of modes (#2237).

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I would love to pair up with you and help out any way I can here 👍

**Comment by cmwaters** [comment]
I think it might also be appropriate to do #4594 at the same time

**Comment by melekes** [comment]
I think this proposal is largely accepted, but a short ADR is still needed imo.

**Comment by erikgrinaker** [comment]
There have also been suggestions to use an event-driven architecture instead, where reactors exchange events with each other. I think that can get a bit complex to reason about, but it's worth considering.

**Comment by ebuchman** [comment]
Awesome, this might also help things like https://github.com/tendermint/tendermint/issues/3388 - currently we require tendermint to restart, but this might make it easier to drop back into replay mode for the reconnect
