### ISSUE TITLE
reactors: doc.go's are missing from multiple reactors

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#4651]
## Summary

doc.go files are a common practice in the go community, we should add doc.go files where they are missing to help onboard people onto the pkg and provide better documentation. 

Reators/modules missing doc.go files

- [ ] abci
- [ ] blockchain (https://github.com/tendermint/tendermint/pull/6749)
- [ ] consensus
- [x] evidence (#4674)
- [ ] p2p
  - [ ] conn
  - [x] pex
  - [ ] trust
- [ ] rpc
  - [ ] client
  - [ ] core
- [ ] state
- [ ] store

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
This is nice to have for our own records, but less critical for users since we don't want people to use reactors as libraries. I'm going to move this to a future milestone.
