### ISSUE TITLE
Call Tendermint API directly in Go app (not via RPC)

### ISSUE THREAD

**Issue by ceeji** [tendermint/tendermint#4666]
## Summary

Now we can only call Tendermint API via RPC. But for a built-in tendermint Go app, it is necessary to interact APIs directly in Go.

## Problem Definition

It will be faster and easier to call Tendermint's API directly in Go. Normally we will use built-in Tendermint app when we want high performance, so no reason to use RPC API in this situation.

## Proposal

Add API Entrypoint for direclty calling in built-in Go apps on tendermint.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
You can call API directly using https://pkg.go.dev/github.com/tendermint/tendermint@v0.33.3/rpc/client?tab=doc#Local 

```go
client := rpcclient.NewLocal(node)
resp, err := client.Status()
if err != nil {
  // handle error
}
fmt.Println(resp)
```

If you have any other questions, feel free to leave a comment here or on [Discord](https://discord.gg/AzefAFd).
