### ISSUE TITLE
evidence: refactor package with set of minor improvements

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4675]
## Problem Definition

There has been a bunch of minor problems identified with the evidence package as we update it with handling a new set of evidence types as part of greater fork accountability.

## Proposal

- Create a doc.go file to better explain the process of the module
- If evidence is expired before it is committed we should remove it from the db (reactor.go:200)
- Use store as an interface, keep db operations with db and the main logic with pool.go (it is unnecessary to have all three)
- Committed evidence doesn't need to be stored completely, rather a marker pointing to the block in the block store (i.e. the height it is committed and the hash of the evidence for easy lookup)
- Don't save to all three buckets in the database, rather move evidence from one bucket to the next. There is an argument to have only two buckets: broadcasted and committed. 
- Restore evidenceList at startup if the database contains evidence marked for broadcasting. This is in case of node failure, it can recover evidence that needs to be broadcasted.
- Use prioritization algorithm when calling `PendingEvidence` so that evidence can be sent for block proposal in the order of importance. Potentially a weighted average of the voting power and the time to expiry
- Ensure that only one evidence per validator is stored and therefore sent to be proposed -  #2561 ( replace only by earlier evidence by the same validator) 
- Send evidence in batches. An evidence list is used but only a single piece of evidence is sent at a time. `Receive` is already coded to handle batches of evidence at a time. Fill the max message size with as much evidence is possible.
- If we don't have any evidence still wait for the `broadcastEvidenceIntervalS` before checking again
- Allow for evidence to contain multiple validators (important for `PotentialAmnseiaEvidence`) - might be done in a separate PR
____

View [here](https://github.com/tendermint/tendermint/issues/4635#issuecomment-611341616) for additional features mentioned

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
what's the state of this?

**Comment by cmwaters** [comment]
I think we can close this. The only outstanding improvements listed here are #4727 and #2561 which have their own respective issues we can use to track the progress
