### ISSUE TITLE
Can't run basic example

### ISSUE THREAD

**Issue by ddsvetlov** [tendermint/tendermint#4678]
I can't run basic example locally, but i found docker image: 
https://hub.docker.com/r/tendermint/tendermint/
This image work, but i can't create net with some nodes (e.g. 5 nodes ).
I used guide "quick start": https://docs.tendermint.com/master/introduction/quick-start.html
Is there any another guide how to create and test network with simple example like kv-store?

**Comment by marbar3778** [comment]
I recommend looking here: https://docs.tendermint.com/master/networks/docker-compose.html

you can adjust the dockercompose.yml file to run the kv-store as well

**Comment by melekes** [comment]
> you can adjust the dockercompose.yml file to run the kv-store as well

I think `localnet` runs `kvstore` ABCI application by default.

**Comment by melekes** [comment]
If you have any other questions, feel free to leave a comment here or join our [Discord](https://discord.gg/AzefAFd).
