### ISSUE TITLE
Expose private validator key file Save() like method for node key

### ISSUE THREAD

**Issue by jordipainan** [tendermint/tendermint#4681]
## Summary

Expose privVal.Save() like method for node key that identifies each node in the p2p network 

## Problem Definition

**Why do we need this feature?** 

I want to pass a miner priv key as flag in a cmd like way and I want this key to be different from the node key, so I also want to pass the node key as a cmd flag.

If `LoadOrGenNodeKey` node key cannot find a key calls internally `genNodeKey` which generates a random private key and then saves this key in the same function which is not exposed to the developer.

I want to save the created node key into a file using the private key I passed through the cmd flag.

**What problems may be addressed by introducing this feature?**

Use a non random node key if not found into file system

**What benefits does Tendermint stand to gain by including this feature?**

Flexibility?

**Are there any disadvantages of including this feature?**

Maybe its better to always generate a random key for the p2p layer, but someone like me  would like to use a persistent key anyways :).

## Proposal

I do not have a formal proposal but I coded something that works fine for my use case, maybe you can be inspired or you can wait me to have time for submitting a decent PR :)

```go
// NewNodeKey returns a tendermint node key
// if tmPrivKey not specified, uses the existing one or generates a new one
func NewNodeKey(tmPrivKey string, tconfig *cfg.Config) (*p2p.NodeKey, error) {
	nodeKey, err := p2p.LoadOrGenNodeKey(tconfig.NodeKeyFile())
	if err != nil {
		return nil, fmt.Errorf("failed to load node's key: %s", err)
	}
	if len(tmPrivKey) > 0 {
		var privKey crypto25519.PrivKeyEd25519
		keyBytes, err := hex.DecodeString(util.TrimHex(tmPrivKey))
		if err != nil {
			return nil, fmt.Errorf("cannot decode private key: (%s)", err)
		}
		if n := copy(privKey[:], keyBytes[:]); n != 64 {
			return nil, fmt.Errorf("incorrect private key lenght (got %d, need 64)", n)
		}
		nodeKey.PrivKey = privKey
	}
	return nodeKey, nil
}

// NodeKeySave save a p2p node key on disk
func NodeKeySave(filePath string, nodeKey *p2p.NodeKey) error {
	outFile := filePath
	if outFile == "" {
		panic("cannot save NodeKey key: filePath not set")
	}

	aminoPrivKey, _, err := HexKeyToAmino(fmt.Sprintf("%x", nodeKey.PrivKey))
	if err != nil {
		return err
	}
	err = tempfile.WriteFileAtomic(outFile, []byte(fmt.Sprintf(`{"priv_key":{"type":"tendermint/PrivKeyEd25519","value":"%s"}}`, aminoPrivKey)), 0600)
	if err != nil {
		return err
	}
	return nil
}
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
Accepted. It's okay to expose Save method.
