### ISSUE TITLE
Cannot start more than one validator node on one machine

### ISSUE THREAD

**Issue by javaandra** [tendermint/tendermint#4690]
**Tendermint version** 0.33.2

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 19.10
- **Install tools**: binary
- **Others**:

**What happened**:
I tried to get 4 validator nodes running on one machine. For this I have used the "tendermint testnet" command, which generated a folder called mytestnet in my home directory. 
Inside mytestnet there are 4 node directories with their own config and data folders.

When trying to start the nodes ony by one using the "tendermint node" command, only one node starts and I cannot start the other 3:
`tendermint node --proxy_app=kvstore --moniker node0 --home /home/<username>/mytestnet/node0 `

**What you expected to happen**:
I would like to know a way to start the 4 nodes. Unfortunately I couldn't find more details in the documentation on what to do after 'tendermint testnet'.
The errors make sense, since
1) at first we don't have the peers running
2) all nodes are listening on the same localhost ip and port. 

My question is how to avoid these errors with the nodes running on the same machine.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
1. Run command 
`tendermint testnet`
2. Attempt to start first node
`tendermint node --proxy_app=kvstore --moniker node0 --home /home/<username>/mytestnet/node0 `
3. Open a new terminal and try to start a second node:
`tendermint node --proxy_app=kvstore --moniker node1 --home /home/<username>/mytestnet/node1 `

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
I[2020-04-16|16:07:01.040] Version info                                 module=main software=0.33.2 block=10 p2p=7
E[2020-04-16|16:07:01.071] Error in peer's address                      module=p2p err="error looking up host (node0): lookup node0 on 8.8.8.8:53: no such host"
E[2020-04-16|16:07:01.071] Error in peer's address                      module=p2p err="error looking up host (node1): lookup node1 on 8.8.8.8:53: no such host"
E[2020-04-16|16:07:01.071] Error in peer's address                      module=p2p err="error looking up host (node2): lookup node2 on 8.8.8.8:53: no such host"
E[2020-04-16|16:07:01.071] Error in peer's address                      module=p2p err="error looking up host (node3): lookup node3 on 8.8.8.8:53: no such host"
I[2020-04-16|16:07:01.071] Starting Node                                module=main impl=Node
.....
I[2020-04-16|16:07:01.097] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 Block:10 App:1} DefaultNodeID:5f8b855d99e0abae5e49a7b2eac8975903275d4e ListenAddr:tcp://0.0.0.0:26656 Network:chain-pJxi2d Version:0.33.2 Channels:4020212223303800 Moniker:node0 Other:{TxIndex:on RPCAddress:tcp://127.0.0.1:26657}}"
```

Error when trying to start a second node:
`ERROR: failed to start node: failed to listen on 127.0.0.1:26657: listen tcp 127.0.0.1:26657: bind: address already in use`

**Comment by jordipainan** [comment]
Hi! I I am just a user trying to help, do not trust me 100% but .. This happens because the first node holds port 26657 which is the default RPC port endpoint, try to change the port in the other nodes.

Node0:
- p2p port 26656
- rpc port 26657

Node1:
- p2p port 26656
- rpc port 26657

Node2:
- p2p port 26658
- rpc port 26659

Node2:
- p2p port 26660
- rpc port 26661

You can do this via config.toml file or via code. Hope this can help you. Bests

**Comment by melekes** [comment]
Thanks @jordipainan! 

@javaandra please try changing port numbers as per @jordipainan's comment and let us know if that did not work.

The alternative is to use [docker compose](https://docs.docker.com/compose/) to run 4 docker containers. Check out https://docs.tendermint.com/master/networks/docker-compose.html for more information.

If you have any other questions, feel free to leave a comment here or join our [Discord](https://discord.gg/AzefAFd).

**Comment by javaandra** [comment]
Thank you @jordipainan !

Your solution helped eliminate one of the problems. All 4 nodes are starting now.
For the record, I modified the config.toml of all 4 nodes like this:
[rpc]
laddr - > changed port for node1, node2, node3
[p2p]
laddr - > changed port for node1, node2, node3
persistent_peers -> changed ports for all nodes.

There is unfortunately a second problem, the nodes cannot find their peers and of course transactions cannot be added in the blockchain, as there is no consensus between the nodes. They seem to be looking for peers on the DNS server 's address 127.0.0.53:53, which is configured in /etc/resolv.conf file.

```
I[2020-04-17|11:09:22.560] Starting Node                                module=main impl=Node

E[2020-04-17|11:09:22.566] Error in peer's address                      module=p2p err="error looking up host (node0): lookup node0 on 127.0.0.53:53: server misbehaving"

E[2020-04-17|11:09:22.566] Error in peer's address                      module=p2p err="error looking up host (node1): lookup node1 on 127.0.0.53:53: server misbehaving"

E[2020-04-17|11:09:22.566] Error in peer's address                      module=p2p err="error looking up host (node2): lookup node2 on 127.0.0.53:53: server misbehaving"

E[2020-04-17|11:09:22.566] Error in peer's address                      module=p2p err="error looking up host (node3): lookup node3 on 127.0.0.53:53: server misbehaving"
I[2020-04-17|11:09:22.569] Started node                                 module=main nodeInfo="{ProtocolVersion:{P2P:7 B
lock:10 App:1} DefaultNodeID:c5d0deee03fc164a508429309e050087a118e43f ListenAddr:tcp://0.0.0.0:26662 Network:chain-pJxi2d Version:0.33.2 Channels:4020212223303800 Moniker:node3 Other:{TxIndex:on RPCAddress:tcp://127.0.0.1:26663}}
```

Hi @melekes 
Thanks, we actually did try first the docker-compose option, but we ran into a similar networking problem. My colleague opened the issue #4686 for that.
I suppose these issues are related and have to do something with our sever's set-up.

Thank you both for your support!

**Comment by melekes** [comment]
Yeah, there's definitely something wrong with your DNS

https://github.com/kubernetes/kubernetes/issues/39980#issuecomment-274643548

**Comment by javaandra** [comment]
Inspired by one of the comments in the kubernetes issue referenced by @melekes above, I've managed to fix the problem, by adding the following lines to the /etc/hosts file:

127.0.0.1 node0
127.0.0.1 node1
127.0.0.1 node2
127.0.0.1 node3
