### ISSUE TITLE
state: validateBlock should check if evidence is stored

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4696]
before calling `VerifyEvidence` because stored evidence is already verified and checking the DB is much faster than verifying evidence. Note: for evidence, which is not present in the DB, we'll still have to call `VerifyEvidence`, but hopefully it will be a rare case.

Refs https://github.com/tendermint/tendermint/pull/4532#discussion_r408926586

**Comment by cmwaters** [comment]
Sorry @melekes, I didn't see that you had already made this issue. 

Closing this issue because of duplicate here: #4728
