### ISSUE TITLE
privval: refactor to use gRPC 

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4698]
## Summary

Currently, we use a raw tcp connection with a secret handshake between a HSM and a tendermint node for signing capabilities. This works but is a bit complicated for clients to implement when users would like to create a new HSM. 

## Proposal

With the migration of the Tendermint codebase to protobuf there is the possibility of simplifying the privval server by using [gRPC](https://grpc.io/). SSL/TLS [authentication](https://grpc.io/docs/guides/auth/) can be used. example: [Go](https://grpc.io/docs/guides/auth/#go)

if this is accepted then it would be good to get it in 0.34 and coordinate with the iqlusioninc around updating the kms.

ref: #2830

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
_Accepted_
