### ISSUE TITLE
[RFC] Isolate failures of individual reactors

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4708]
## Summary

Failure of one / two reactors does not need to lead to global failure.

## Problem Definition

Currently, a failure inside one of the reactors will inevitably lead to a global failure. While this makes the failure more visible (process exits with error), it also makes Tendermint less resilient. A bug in evidence reactor can crash the whole system. I would like to propose a modification to the current reactors design where failures are isolated - each reactor has a `recover` func. Upon panic, `Switch` tries to restart the reactor N times in S seconds. If that fails, process exits. Those of you familiar with Erlang will immediately see the supervisor model proposed here (reactor - worker, Switch - supervisor). For those unfamiliar, there's a great article written by [Fred T-H](https://ferd.ca/): https://learnyousomeerlang.com/supervisors. By adopting this model, Tendermint will become more resilient to failures inside individual components.

## Proposal

Add a `recover` statement for each reactor. `Switch` handles failures and tries to restart the reactor N times in S seconds. If that fails, program exits with error.

![](https://learnyousomeerlang.com/static/img/restart-one-for-one.png)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
I think this makes sense. If we were able to register service constructors (e.g. factories) with the node, it would be as simple as stopping the failed reactor and starting a new one. However, with unclean shutdown there is a risk of e.g. goroutine leaks which could have unpredictable effects.

On modern systems, Tendermint is already likely to run under a process supervisor such as Systemd, Docker, or Kubernetes which would automatically restart a crashed process with e.g. exponential backoff and operator alerting. In the case of errors severe enough to restart the reactor, perhaps it might be better (and easier) to simply restart the entire process using standard tools?

**Comment by melekes** [comment]
> with the node, it would be as simple as stopping the failed reactor and starting a new one.

Sorry, it should be `Switch` (not `Node`) since it starts / stops reactors.

> goroutine leaks which could have unpredictable effects.

This is a valid concern 👍 However, maybe this will be an opportunity to review each reactor's supervision tree (ie. what goroutines it launches), reduce the number of levels (1 max) and write goroutines in a way where they check if reactor is not running (this is already the case, I think).

> On modern systems, Tendermint is already likely to run under a process supervisor such as Systemd, Docker, or Kubernetes which would automatically restart a crashed process with e.g. exponential backoff and operator alerting. In the case of errors severe enough to restart the reactor, perhaps it might be better (and easier) to simply restart the entire process using standard tools?

I'd argue that some reactors are more important. Crash inside evidence reactor or pex reactor or mempool reactor should not crash the whole node. Let's take the recent mempool DoS bug. If we adopt ^, an attacker can only crash the mempool reactor, but NOT the whole node. I.e. consensus & other critical components continue to work. Validator waits for the patch and applies it.

**Comment by erikgrinaker** [comment]
> Crash inside evidence reactor or pex reactor or mempool reactor should not crash the whole node.

I agree, but I think we could get far with a simpler solution. If we use regular errors instead of panics for error handling we would have better control of which errors should crash the node and which shouldn't. Some components should probably also have panic handlers - for example, we never want a panic in the RPC server to crash the node, and similarly when processing messages received via P2P. I believe we typically spawn goroutines for these (?), so it is simple enough to register a panic handler for that specific goroutine.

**Comment by greg-szabo** [comment]
My first thought was exactly what Erik mentioned:
> If we use regular errors instead of panics for error handling we would have better control of which errors should crash the node and which shouldn't.
Letting things fail for unknown reason and fixing them by restarting whatever failed is a very "first-response" way of dealing with issues: you have to get the system back running so you do whatever is necessary to make that happen. (You could call it the ops approach too.) It's a patch, not a systemic fix. The reasoning in doing it is that when we have more time, we'll look at what happened and fix it for good.

On the other hand the below from @melekes is also valid:
> I'd argue that some reactors are more important. Crash inside evidence reactor or pex reactor or mempool reactor should not crash the whole node. Let's take the recent mempool DoS bug. If we adopt ^, an attacker can only crash the mempool reactor, but NOT the whole node.

So, is it possible to comb through the code and replace panics with error handling?
I would also argue, that _we don't know_ what caused the panic/error in the first place and we don't know if the problem might corrupt other parts of the execution or not. Or even make the node unusable but still running. (I bet there are validators out there that check if the process is running or was recently restarted but they don't know how to monitor the internal state of the service.)

So, trying to make Tendermint more resilient needs to be more targeted/understood so the `recover` function doesn't become a `coverup`. :)

**Comment by melekes** [comment]
Thanks for the feedback @greg-szabo and @erikgrinaker! Looks like it's not the right time for this feature. As Erik pointed out, better error handling and existing rpc/p2p recover functions are sufficient for now.
