### ISSUE TITLE
inconsistent behaviour when apci app dies

### ISSUE THREAD

**Issue by arnonuem** [tendermint/tendermint#471]
More like a defect than a feature request.

**Tendermint version**
0.9.0

**ABCI app**
any

**What happened**:
When Tendermint is started and there is not yet an opened port of an ABCI app, Tendermint tries to permanently connect to the app (which is good). Once the ABCI app is there Tendermint connects to it and everything is fine.
When i kill the ABCI app Tendermint also dies with an error which is not good.

**What you expected to happen**:
I expected the same behaviour like in the beginning. Once an ABCI app crashes (socket is closed abnormally) Tendermint should fall back into 'discovery'-mode and should do the same reconnecting thing like when it was started.

**How to reproduce it** (as minimally and precisely as possible):
Run Tendermint with a connection to an ABCI app.
Kill the ABCI app.
Watch Tendermint output.

**Comment by melekes** [comment]
It's a known defect. We are working on it https://github.com/tendermint/tendermint/issues/243
