### ISSUE TITLE
crypto: multisig deprecation 

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4715]
## Summary

Currently, Tendermint has a multsig located in the crypto directory. With the merge of https://github.com/cosmos/cosmos-sdk/pull/5997 multisigs will be moved to the sdk. This makes having multsigs in Tendermint redundant.

## Proposal

Deprecate multisigs in the next major release and move all related issues/ADR's to the Cosmos-SDK

ref #2163 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
I searched github for users for `tendermint/crypto/multisig` and it's unclear if this should be done. The multisig will not be maintained anymore after 0.34 but I am unsure if some applications that are not using the sdk but are using Go are using it.

**Comment by marbar3778** [comment]
to remove amino entirely we have to deprecate this key type or its amino encoding format which will be breaking. Do you people have a preference for what to do here?

cc @melekes @tessr @erikgrinaker

**Comment by melekes** [comment]
are we planning to somehow use multisig ourselves? if not, I'd vote for removal

**Comment by ebuchman** [comment]
It's conceivable that a validator would want to use a multisig pubkey for their validator signing. I don't know if anyone is doing that or if its even been tested (I think it would have to be explicitly enabled in the `consensus_params.validator.pub_key_types` too). Likely using an aggregate or threshold sig would be better than this kind of multisig anyways, so maybe it's ok to drop it, but just flagging. Could always be brought back using protobuf for it if there's demand.

**Comment by marbar3778** [comment]
thank you for the input. Tendermint does not use it and I agree with bucky with that this would not be the best type multisig isnt best for validators. In the future when BLS sigs come about then these types of things could easily be added
