### ISSUE TITLE
evidence: control evidence gossiping

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4727]
## Problem Definition

The current state of the evidence package is such that new evidence is continuously broadcasted until committed. This means unnecessary io between nodes and opens the window for DDoS attacks. A protocol needs to be in place such that honest nodes won't continuously send messages and therefore repeatedly sent messages from the same peer can result in the punishing of that peer. 

## Proposal

One suggestion for how to resolve this issue is to introduce an acknowledge message to the current list message (which sends a list of evidence). When a node receives a list message from another node it will add all the evidence and then send an ack message with the hashes of all the evidence back to the sending peer. 

Nodes will continue to send evidence to all other peers with exponential backoff until either an ack is returned or the max timeout is reached in which case the peer would be dropped. Each node will keep a map of the peers and pointers to the evidenceList (which contains all known pending evidence) such that the list pointing to the evidence list for each peer will always be a subset of the actual evidence list. When an ack is received the node removes the reference to that piece of evidence for that particular peer such that the node will no longer send any more evidence.

When a node receives the same evidence from a peer after it has sent the peer an ack it will punish the peer (most likely by dropping the connection)

This will add more complexity to the evidence package but will reduce the messages sent and received and will prevent DDoS attacks (when a node keeps sending evidence). 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
1. we don't need to send evidence in a loop (Is it sufficient to send it once?)
2. acknowledge messages make sense (p2p layer should handle this?)
3. ask @ebuchman why we're resending evidence.

**Comment by ebuchman** [comment]
Sorry can you clarify how its different from the mempool, I don't remember exactly now.

One note is that evidence needs to be prioritized above everything else, which may be why it uses more bandwidth - we need to ensure that if evidence is seen then its committed as soon as possible

**Comment by cmwaters** [comment]
The only difference I can gauge from my limited understanding of the mempool is that the mempool checks whether the peer has already sent us the tx else it does the same procedure of continuously gossiping transactions until the transaction is committed to a block.

IMO, I think this is unnecessarily consuming of bandwidth and could be solved with a simple acknowledging system. However, I feel this problem lies in the realm of the p2p module and not the individual reactors themselves hence I would probably close this issue and leave the current algorithm as is as this will be something that will likely be addressed (and fixed) when the p2p is refactored

**Comment by ebuchman** [comment]
> mempool checks whether the peer has already sent us the tx

This is new too right? Anton implemented this recently to reduce mempool bandwidth?

I would think the evidence should be rare enough and high priority enough that using the extra bandwidth for it shouldn't be a real problem.

Also, in my mind, possible refactor of the mempool down the road might consolidate it with the evidence reactor in which case this would all be taken care of.

> However, I feel this problem lies in the realm of the p2p module and not the individual reactors themselves

Not sure I understand this.

**Comment by cmwaters** [comment]
Checking whether the peer has already sent us the tx reduces the bandwidth but there is still an unnecessary amount of messages being sent. If I send a message to you, you won't send one back but you will continue to send messages to your peers and I will continue to send messages to you and my own peers. 

If there was an acknowledging system in place such that when I send you a message you actually send just one message in return to acknowledge that you had received the transaction then I wouldn't have to continue sending messages to you nor to any of my peers that responded. This would mean the minimum bandwidth necessary to gossip messages through the network. Why I said that this problem lies within the p2p package is that it should be the job of the p2p to implement this acknowledging system not the individual reactors

**Comment by ebuchman** [comment]
> If there was an acknowledging system in place such that when I send you a message you actually send just one message in return to acknowledge that you had received the transaction then I wouldn't have to continue sending messages to you nor to any of my peers that responded

But we're using TCP, so the code is already written to assume that if I sent you a message, you receive it (or the connection fails). Is this what you mean by taken care of by the p2p layer?

**Comment by cmwaters** [comment]
Yeah kind of. I was just thinking that if we can be somewhat sure that the node has received the evidence then should we continue to send that same evidence regardless or should we instead remove it from the gossiping list.

**Comment by tessr** [comment]
I'm guessing we should revisit this after the P2P refactor, if at all.
