### ISSUE TITLE
rpc: standardize error codes

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4740]
## Summary

The RPC server must standardize error codes. See e.g. #4739.

It also should differentiate HTTP response codes. Currently all errors are returned as 500 Internal Server Error, even though the problem may have been an invalid client request (which should be a 400 status).

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
closing due to #6019
