### ISSUE TITLE
q: Is it possible to remove 1/3 validators who are offline without hard fork?

### ISSUE THREAD

**Issue by godevlion** [tendermint/tendermint#4742]
Hello everyone!
Today im faced with one sad problem. More than 1/3+ of my validators is go offline. When i restarting my validators they had voting_power=0 and they cant to be part of consensus. 
The blockchain has stopped, I can’t add a new validator and delegate a stake to it since the transactions do not work. What to do? How can I fix the blockchain? How to increase the voting powers of validators?
As i understand consensus broken, i can't generate new blocks then i can only delete all validators and recreate blockchain from height=0.

**Comment by melekes** [comment]
> More than 1/3+ of my validators is go offline. When i restarting my validators they had voting_power=0 and they cant to be part of consensus.

why is that? because your ABCI application punishes validators for being offline?

> How to increase the voting powers of validators?

https://docs.tendermint.com/master/spec/abci/apps.html#endblock you can change validator's voting power via `EndBlock#ValidatorUpdates`

**Comment by godevlion** [comment]
> why do they all have 0 voting power? because your ABCI application punishes validators for being offline?
> 
> >
Yes, they was long time offline.


> * How many validators do you have?
4

> * Tendermint version?
0.31.6

> Tendermint should discard validators with 0 power and continue to work as long as 2/3+ of voting power is online.
Hmm, where i can read this in doc. If validator has voting_power=0 he discard from consensus?

The blockchain stopped when it became more than 1/3+ of the validators with the voting_power = 0. The round began with a proposal and did not reach the pre-vote.
As for ValidatorUpdate, this is very interesting. That is, I can change the validator with the voting_power knowing its public key.
Then I have two questions:
1) Can I register any validator with any voting_power, and throw validators with lesser voting_power out of consensus without delegating a stake to my validator?
2) How can I call the ValidatorUpdate message. Is this just an ABCI message?
In doc i see this
> Note the updates returned in block H will only take effect at block H+2.
this means that I will get changes in the current block in H+2, but what if there are no new blocks :)

**Comment by melekes** [comment]
> If validator has voting_power=0 he discard from consensus?

no, but it does not create blocks (to be a proposer you have to have some stake).

> The blockchain stopped when it became more than 1/3+ of the validators with the voting_power = 0.

weird. as long as 2/3+ of voting power is online, everything should be okay. can you paste the output of `/dump_consensus_state` RPC endpoint here as a Github gist?

> Can I register any validator with any voting_power, and throw validators with lesser voting_power out of consensus without delegating a stake to my validator?

Yes, you can.

> How can I call the ValidatorUpdate message. Is this just an ABCI message?

It's a field in response to `EndBlock ABCI function. The changes will be applied in block H+2, correct. If you don't have enough voting power online, then there's nothing you can do except a hard fork.

**Comment by godevlion** [comment]
> weird. as long as 2/3+ of voting power is online, everything should be okay. can you paste the output of `/dump_consensus_state` RPC endpoint here as a Github gist?
> 
> >
No, i restarted blockchain. Sorry.

> It's a field in response to `EndBlock ABCI function. The changes will be applied in block H+2, correct. If you don't have enough voting power online, then there's nothing you can do except a hard fork.
>>
Tell me please, if i cant processing new blocks and i doesn't want to restarted from 0 my blockchain, then i have only one way - its make hard fork. How can I do this? Whats is necessary for this? I need to copy old blockchain in new validators ?:) I know that i can make hard fork if will be accepting two blocks in one height.

**Comment by melekes** [comment]
> How can I do this? Whats is necessary for this? I must to copy old blockchain in new validators ?:) 

You will need to export the ABCI application state and create a new genesis file. Then add new & existing validators and start the blockchain again. Take a look at how Cosmos Hub does this: https://github.com/cosmos/gaia/blob/master/docs/migration/cosmoshub-2.md

**Comment by melekes** [comment]
If you have any other questions, feel free to leave a comment here or join our [Discord](https://discord.gg/AzefAFd).

For anyone else looking at this issue, the answer to original question (**Is it possible to remove 1/3 validators who are offline without hard fork?**) is **NO**. This is given they haven't committed a malicious punishable behaviour (e.g. duplicate vote), in which case https://github.com/tendermint/tendermint/issues/4593 should help Tendermint to progress forward without bad validators.
