### ISSUE TITLE
Add EXISTS condition for tx_search

### ISSUE THREAD

**Issue by thith** [tendermint/tendermint#4763]
## Summary

Add EXISTS condition for `tx_search`.

## Problem Definition

The subscription feature supports EXISTS condition as the result of #4077. But `tx_search` is left unsupported.

To reproduce, just try on RPC:
```
http://localhost:26657/tx_search?query="dummy EXISTS"
```
It panics with: "other operators should be handled already".

## Proposal

Add support for EXISTS when searching for transactions similar to that of subscription.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
Could you paste a stack trace of the panic (other operators should be handled already)?

**Comment by thith** [comment]
Stact trace:

E[2020-04-29|04:10:15.054] Panic in RPC HTTP handler                    module=rpc-server err="other operators should be handled already" stack="goroutine 48 [running]:\nruntime/debug.Stack(0xc0005b8b60, 0x19c0040, 0x1dbd0e0)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1.1(0xc0005a06e0, 0x1ded9c0, 0xc0004eda40, 0xbfa244cdc33c4710, 0xb45a356fe6, 0x24e2c20, 0xc0003da600)\n\t/Users/thi/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:161 +0x486\npanic(0x19c0040, 0x1dbd0e0)\n\t/usr/local/go/src/runtime/panic.go:969 +0x166\ngithub.com/tendermint/tendermint/state/txindex/kv.(*TxIndex).match(0xc0001a3b00, 0x1ded080, 0xc000010e40, 0xc000501631, 0x5, 0x6, 0x0, 0x0, 0xc0000795c0, 0xc, ...)\n\t/Users/thi/go/src/github.com/tendermint/tendermint/state/txindex/kv/kv.go:456 +0x90e\ngithub.com/tendermint/tendermint/state/txindex/kv.(*TxIndex).Search(0xc0001a3b00, 0x1ded080, 0xc000010e40, 0xc0005a0780, 0x0, 0xc0003d1c80, 0xc0005b9390, 0xc000181e98, 0x1)\n\t/Users/thi/go/src/github.com/tendermint/tendermint/state/txindex/kv/kv.go:244 +0xbda\ngithub.com/tendermint/tendermint/rpc/core.TxSearch(0xc0005a0720, 0xc000501590, 0xc, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/thi/go/src/github.com/tendermint/tendermint/rpc/core/tx.go:70 +0x156\nreflect.Value.call(0x1a35280, 0x1cadcf8, 0x13, 0x1b35636, 0x4, 0xc0004f8750, 0x6, 0x6, 0x6, 0x18, ...)\n\t/usr/local/go/src/reflect/value.go:460 +0x8ab\nreflect.Value.Call(0x1a35280, 0x1cadcf8, 0x13, 0xc0004f8750, 0x6, 0x6, 0x5, 0x5, 0xc0000794c4)\n\t/usr/local/go/src/reflect/value.go:321 +0xb4\ngithub.com/tendermint/tendermint/rpc/lib/server.makeHTTPHandler.func2(0x1de9240, 0xc0005a06e0, 0xc0003da600)\n\t/Users/thi/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_uri_handler.go:53 +0x311\nnet/http.HandlerFunc.ServeHTTP(0xc0000f00c0, 0x1de9240, 0xc0005a06e0, 0xc0003da600)\n\t/usr/local/go/src/net/http/server.go:2012 +0x44\nnet/http.(*ServeMux).ServeHTTP(0xc000077000, 0x1de9240, 0xc0005a06e0, 0xc0003da600)\n\t/usr/local/go/src/net/http/server.go:2387 +0x1a5\ngithub.com/tendermint/tendermint/rpc/lib/server.maxBytesHandler.ServeHTTP(0x1dd3bc0, 0xc000077000, 0xf4240, 0x1de9240, 0xc0005a06e0, 0xc0003da600)\n\t/Users/thi/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:210 +0xcf\ngithub.com/tendermint/tendermint/rpc/lib/server.RecoverAndLogHandler.func1(0x1de9940, 0xc0001a0620, 0xc0003da600)\n\t/Users/thi/go/src/github.com/tendermint/tendermint/rpc/lib/server/http_server.go:183 +0x360\nnet/http.HandlerFunc.ServeHTTP(0xc0003a8000, 0x1de9940, 0xc0001a0620, 0xc0003da600)\n\t/usr/local/go/src/net/http/server.go:2012 +0x44\nnet/http.serverHandler.ServeHTTP(0xc0001a00e0, 0x1de9940, 0xc0001a0620, 0xc0003da600)\n\t/usr/local/go/src/net/http/server.go:2807 +0xa3\nnet/http.(*conn).serve(0xc001016140, 0x1ded080, 0xc000010dc0)\n\t/usr/local/go/src/net/http/server.go:1895 +0x86c\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2933 +0x35c\n"

**Comment by thith** [comment]
By the way I could create a PR for this. I have fixed to use internally by my team.

The current EXISTS is supported by `query.go`'s `Matches`, but not `kv.go`'s `Search`. The EXISTS test cases are also available in 'query_test.go` only, not in `kv_test.go`.

**Comment by melekes** [comment]
> By the way I could create a PR for this.

Please do 🙏

**Comment by melekes** [comment]
note: I was not able to replicate the above panic.

**Comment by thith** [comment]
> note: I was not able to replicate the above panic.

Was you able to obtain correct results doing search_tx with EXISTS?

**Comment by melekes** [comment]
no, it was just returning an error
