### ISSUE TITLE
why use the mock.Mempool{} to initialize the blockExec

### ISSUE THREAD

**Issue by banishee** [tendermint/tendermint#4766]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 569981325a43c18e65beb193adf7d172a498a5bc

**What happened**:
* `consensus\replay.go  line 476` : `blockExec := sm.NewBlockExecutor(h.stateDB, h.logger, proxyApp, mock.Mempool{}, sm.MockEvidencePool{})`
* Why use the `mock.Mempool{}` to initialize the blockExec? I notice that the comment showing that  `Mempool` is used for test
* if I add some functions in the interface `Mempool`, the structure `CListMempool` is easy to achieve the additional functions, but the structure `Mempool` is a empty struct. So it is hard for me to achieve the logic code.

**What you expected to happen**:
* use the `CListMempoo`l to initialize the blockExec

**Comment by zhongqiuwood** [comment]
It weird that test code was used in production code.

**Comment by melekes** [comment]
It's simple. Because we don't need both of them (mempool and evidence pool) during replay (replaying missing blocks to application).

**Comment by melekes** [comment]
I hope https://github.com/tendermint/tendermint/pull/4785 clarifies things a bit. Thanks for bringing this to our attention!
