### ISSUE TITLE
mempool: overwriting precheck and postcheck function

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4773]
## Problem Definition

When the mempool is started, it can be initiated with a precheck and a postcheck function (via options). Both are any function that takes a transaction and returns an error where the former is used in `CheckTx` and the latter is used as part of a call back function. However, when we `Update` the mempool which is run whenever the block executor applies a block and therefore runs `Commit`, the precheck and postcheck functions are overwritten by two defined functions. The first of these ensures that the bytes of any given single transaction be less than the maxdatabytes (assuming the full amount of evidence is used). The second function ( for the postcheck ) has something to do with validating the gas. 

## Proposal

Either we remove the option at initiation if we think it is unnecessary or have an array of prechecks that can be looped through so we avoid overwriting anything. 

As an auxiliary suggestion, I don't think the precheck function passed during each Update is correct. Basically it makes sure that a transaction is not bigger then the max size of a block minus the max size of the overhead and size of the evidence. As we can assume evidence is mostly empty, it could be plausible that we only check that a transaction is smaller than the max block size minus the max overhead.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
> Either we remove the option at initiation if we think it is unnecessary or have an array of prechecks that can be looped through so we avoid overwriting anything.

It's necessary to set the precheck/postcheck functions on init (node.go). It's also necessary to update them on each block (clist_mempool.go) since consensus params can change (via ABCI `EndBlock`).

I.e. it's not a bug, it's a feature 😄 I will update the Option documentation to make that more clear.
