### ISSUE TITLE
Limited and Potentially Repeated TrustLevel Validation

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#4783]
The trust level validation in [lite2/verifier.go:ValidateTrustLevel](https://github.com/tendermint/tendermint/blob/e4427b72928e5a8066f75cdc98e3d84a038cc17b/lite2/verifier.go#L204) and [types/validator_set.go:VerifyCommitTrusting](https://github.com/tendermint/tendermint/blob/master/types/validator_set.go#L757) are very similar but subtly different (one is missing a denominator != 0 check). If these checks are validating the same thing, we should consider consolidating the logic to prevent it from diverging. 

This validation is also "limited" as it is not possible to set minimums for either the denominator or the numerator. I'm not sure if this presents a security issue, but this limitation was specifically raised in the audit.

_This came via the IBC/light client audit._

**Comment by melekes** [comment]
> This validation is also "limited" as it is not possible to set minimums for either the denominator or the numerator.

Not sure I understand this part.

**Comment by tessr** [comment]
I don't either.
