### ISSUE TITLE
Unvalidated ChainID Length and Version

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#4789]
The [Tendermint documentation](https://docs.tendermint.com/master/spec/blockchain/blockchain.html) specifies the Header data structure to contain a ChainID string and Version structure (among other items).

The ChainID string is specified to have a maximum length of 50 bytes. While this length is validated in the `ValidateBasic()` function implemented on line 47+ in tendermint/types/ block.go, this function is not always reached in the lite2 client. One example of an unvalidated path is:

1. The `NewClient()` function on line123+ of `client.go` calls the nearby `initializeWithTrustOptions() function.
2. The `initializeWithTrustOptions()` function then calls (a first) `ValidateBasic()` function implemented on line 752+ of `tendermint/types/block.go` for a signed header structure.
3. This (first) `ValidateBasic()` function does check for ChainID equality with an expected value, but does not check lengths. It then calls (a second) `ValidateBasic()` function implemented on line 674+ for a commit structure.
4. This (second) `ValidateBasic()` function validates a non-negative height and a few other items, before calling (a third) `ValidateBasic()` function implemented on line 506+ for each commit signature structure. At this point, the validation focus has moved beyond the top-level header fields.
5. The logic will then essentially `returntoNewClient()` without having validated the ChainID string length.

Note that the `TrustedHeader()` function on line 193+ of `client.go` checks for a non-negative height similar to that performed in step 4 above. This suggests there is  reasonable potential for validating ChainID length there. Another non-negative height check is present in `http.go`.

Additionally, this issue was inspected by increasing the size of the `chainID` fields found in `client_test.go` and `verifier_test.go`, and re-running the tests. When the field was increased well beyond 50 bytes, no failures were observed (beyond one irrelevant ‘expected value’ mismatch).

_verbatim via the IBC/light client audit_

**Comment by melekes** [comment]
> This (first) ValidateBasic() function does check for ChainID equality with an expected value, but does not check lengths.

length check does not make sense if you have equality check.

Anyway, the issue was fixed by #4638

**Comment by melekes** [comment]
Possible values for Version fields are restricted by the type system.
