### ISSUE TITLE
Allow query of multiple TX via hashes 

### ISSUE THREAD

**Issue by wolfposd** [tendermint/tendermint#479]
Currently `http://localhost:46657/tx?hash=HASHHERE&prove=true` only allows retrieval of a single TX.

a multi-query would be nice, which returns an array-object of all TXs. It would remove some async problems when multiple tx are related to each other, as they can all be retrieved at once

**Example**

Sending:
```
{
    "id": "0", "jsonrpc": "2.0",
    "method": "tx",
    "params": [
        "BC278E0416E162CE6406A951A3D2C9AAE3C272F4", // Hash-1
        false, // Prove-1
        "F17854A977F6FA7EEA1BD758E296710B86F72F3D", // Hash-2
        false // Prove-2
    ]
}
```

Receiving:

```
{
    "error": "", "id": "0", "jsonrpc": "2.0",
    "result": [
        {
            "height": 177,
            "index": 0,
            "tx": "00",
            "tx_result": {}
        },
        {
            "height": 188,
            "index": 0,
            "tx": "01",
            "tx_result": {}
        }
    ]
}
```

**Comment by melekes** [comment]
Thanks! Could you please describe the use-case for this?

**Comment by wolfposd** [comment]
Lets say we have an online trading platform.

- Party A puts up an Apple for sale (Offer): 
    SEND: {value:apple, price:10, owner:A, id:10021}  -> hash=0xAAAA
- Party B wants to buy this Apple (Execution):
    SEND: {buy:apple,buyer:B, id:10021} -> hash=0xBBBB
- Party A acknowledges sale (Sale-ACK):
    SEND: {id:10021, offer:0xAAAA, execution:0xBBBB} -> hash=0xCCCC

_This could be easily scaled towards a final ACK-TX which bundles multiple TXs_

In order to retrieve the full trading information, currently the calls would be:

1. query for hash 0xCCCC (Sale-ACK)
    _wait for answer_
2. query for hash 0xAAAA (Offer)
    _wait for answer_
3. query for hash 0xBBBB (Execution)
    _wait for answer_
4. do stuff with the data


when allowing multiquery:

1. query for hash 0xCCCC
    _wait for answer_
2. query for hashes [0xAAAA,0xBBBB]
    _wait for answer_
3. do stuff with data


depending on the local-storage of the app (lets say that related hashes are saved in a local db together):

1. query for hashes [0xCCCC,0xAAAA,0xBBBB]
    _wait for answer_
2. do stuff with data

**Comment by ethanfrey** [comment]
I see the case, but couldn't the client library simply make two requests in parallel? Then wait for both responses and join them.  I think most modern languages have some constructs/libs to allow these types of actions.

Right there, you have the second and third cases without any server changes.  Given, it may be slightly more efficient for the server as one request, but until there is significant load, that should not be a problem.

**Comment by adrianbrink** [comment]
I think for now we will leave everything as it is. We might revisit this later on.

**Comment by melekes** [comment]
Note that there will be a mechanism to query for a few transactions based on a filter (https://gist.github.com/melekes/131291e5144e31d34ac3ed3ab7ff2aca)
