### ISSUE TITLE
unchecked header version

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#4790]
We set the header version, but we never check it (see `block.go`). 

At the moment, this is basically OK. We only really have one version number for the header; so we can assume that all blocks use that version number. However, this won't be true once there's more than one version in use. It would be good to start checking the header version so that a node expecting header version 1 won't choke on header version 2. 

(This issue may apply to other version numbers across the codebase. Also, @erikgrinaker pointed out we may want to version more things as well. This is true, but let's start by checking the version numbers we have already!)

**Comment by marbar3778** [comment]
We do check if the node we are connecting with shares the same block protocol. For some odd reason, I may be missing it, we are not checking if the node we are connecting shares the same P2P protocol.

Opened a PR to add a check within the header.ValidateBasic() if the header matches our block protocol
