### ISSUE TITLE
Logging if node is validator/observer

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#480]
It seems like a valuable addition to log if node is participating as validator or observer, as it is not clear from just looking at the configuration (validator set might change).

I suggest logging "Node is participating as observer" or "Node is participating as validator" when there is a state change.

@melekes pointed out on slack that app should also log this when it changes the validator set via ABCI, but there was agreement that since there is the validator set is bootstrapped via config, that it makes sense to log in tendermint core as well.

**Comment by ebuchman** [comment]
This is cool. We can just check if the node's priv_validator key is in the validator set on startup and log the result.

**Comment by mdyring** [comment]
Since validator set might change over time (via ABCI), ideally it should be logged when it changes.. 
But yes on startup would be good as well, just as long as it takes into account the most recent validator set (so after replay on startup I guess).

**Comment by ebuchman** [comment]
Oh yes of course. So on startup after replay (once State has latest validators), and once removed or added to the val set.

**Comment by adrianbrink** [comment]
PR: #488

**Comment by haasted** [comment]
I'd like to suggest that this is feature is expanded to have all nodes in the network log any modifications they see in the validator set, e.g. that another node switches from observer to validator, or that a new validator is added to the P2P network. Would this be possible?

**Comment by adrianbrink** [comment]
@haasted I've added the extended logging as another issue.

**Comment by srmo** [comment]
What about a message to the abci app informing it about the current valset and votepower, and if the connected node is validator or not? Maybe like the current info handshake or as answer to an rpc call?
