### ISSUE TITLE
rpc-server module doesn't start after a container restart

### ISSUE THREAD

**Issue by vvaradhan** [tendermint/tendermint#4803]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.31.5-d2eab536
  
**ABCI app** (name for built-in, URL for self-written if it's publicly available): Bigchaindb ver: 2.0.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OS: Ubuntu 18.04.4 LTS 
- **Install tools**: docker
- **Others**: all-in-one docker build except for mongodb, which is used from outside of the container running bigchaindb and tendermint.

**What happened**:
The EC2 instance ran out of disk.  After freeing up some space, when the docker containers are restarted, bigchaindb was unable to commit any transaction.  The debug log from bigchaindb said max-retries exceed to connect to http://localhost:26657 (the default tendermint port).  I tried building a fresh container and run it, in that also it did not work.

**What you expected to happen**:
rpc-server module of tendermint to be up and running.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible): 1) let a disk-full happen, 2) stop/start the container running bigchaindb/tendermint.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
bash-5.0# tendermint node --rpc.laddr "tcp://0.0.0.0:26657" --log_level="*:debug"
I[2020-05-06|18:40:05.136] Starting multiAppConn                        module=proxy impl=multiAppConn
I[2020-05-06|18:40:05.137] Starting socketClient                        module=abci-client connection=query impl=socketClient
I[2020-05-06|18:40:05.138] Starting socketClient                        module=abci-client connection=mempool impl=socketClient
I[2020-05-06|18:40:05.139] Starting socketClient                        module=abci-client connection=consensus impl=socketClient
I[2020-05-06|18:40:05.139] Starting EventBus                            module=events impl=EventBus
I[2020-05-06|18:40:05.140] Starting PubSub                              module=pubsub impl=PubSub
I[2020-05-06|18:40:05.151] Starting IndexerService                      module=txindex impl=IndexerService
I[2020-05-06|18:40:05.231] ABCI Handshake App Info                      module=consensus height=355 hash= software-version= protocol-version=0
I[2020-05-06|18:40:05.233] ABCI Replay Blocks                           module=consensus appHeight=355 storeHeight=2760414 stateHeight=2760413
I[2020-05-06|18:40:05.233] Applying block                               module=consensus height=356
I[2020-05-06|18:40:05.315] Executed block                               module=consensus height=356 validTxs=0 invalidTxs=0
I[2020-05-06|18:40:05.395] Applying block                               module=consensus height=357
```

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**:
I see the following in tendermint log (with default log level): 
E[2020-05-06|17:18:40.274] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: conn
ect: connection refused"

I tried asking in SO : https://stackoverflow.com/questions/61580896/getting-error-while-sending-transaction-over-bigchaindb-node

**Comment by melekes** [comment]
Looks like Tendermint is replaying blocks ("ABCI Replay Blocks"). RPC server will be started after we've done replaying.

**Comment by vvaradhan** [comment]
> Looks like Tendermint is replaying blocks ("ABCI Replay Blocks"). RPC server will be started after we've done replaying.

Thanks for your reply.  Is there a way to calculate the amount of time that it would take to complete replaying?

**Comment by vvaradhan** [comment]
@melekes  A more detailed post on this can be found from https://stackoverflow.com/questions/61580896/getting-error-while-sending-transaction-over-bigchaindb-node - as mentioned in the post, does **E[2020-05-03|19:19:48.586] abci.socketClient failed to connect to tcp://127.0.0.1:26658. Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: conn ect: connection refused"** in tendermint.log points to any errors in the setup which could potentially solve rpc_server not starting issue?

**Comment by melekes** [comment]
Usually replaying is pretty quick.

Are there no log lines after 

```
I[2020-05-06|18:40:05.395] Applying block                               module=consensus height=357
```

?

**Comment by vvaradhan** [comment]
No.. the rpc_server hasn't come up yet.  Are there any other debug logs that I can enable?

**Comment by vvaradhan** [comment]
I have restarted the process again to capture any missing logs.

**Comment by vvaradhan** [comment]
I see the following when terndermint starts with debug option set: 
```
I[2020-05-11|20:47:19.876] ABCI Handshake App Info                      module=consensus height=0 hash= software-version= protocol-version=0
I[2020-05-11|20:47:19.878] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=2760414 stateHeight=2760413
```
If **2760414 height** needs to be reached before rpc_server or any other logs could be seen, in **27 mins 7411 heights** have been played back as shown below: 
```
I[2020-05-11|21:15:06.815] Executed block                               module=consensus height=7410 validTxs=0 invalidTxs=0
I[2020-05-11|21:15:06.915] Applying block                               module=consensus height=7411

```
So, it will take approx. 7 - 8 days to reach **2760414** at this rate.  Is there a way to speed up things, if this has to be completed to troubleshoot further?

**Comment by melekes** [comment]
1) Do you have `fast_sync` enabled? It should speed up things significantly if you're syncing from height=0 (genesis block)
2) Are you starting a new instance? In other words, are you sure `height` should be `0`? Maybe it wasn't persisted correctly?

**Comment by vvaradhan** [comment]
> 1. Do you have `fast_sync` enabled? It should speed up things significantly if you're syncing from height=0 (genesis block)
I will check the fast_sync option.

> 2. Are you starting a new instance? In other words, are you sure `height` should be `0`? Maybe it wasn't persisted correctly?
How do I check for whether the persistence is working or not?  It always starts from height=0; even if for some reason tendermint restarts after replaying for two days, it always starts from height=0;  how do I check for persistence?  Are there any configuration to check for persistence nature?

**Comment by vvaradhan** [comment]
fast_sync is already enabled. 
```
# If this node is many blocks behind the tip of the chain, FastSync
# allows them to catchup quickly by downloading blocks in parallel
# and verifying their commits
fast_sync = true
```
Above is from the config.toml that is used by tendermint.

**Comment by erikgrinaker** [comment]
It seems like the node already has all blocks in local storage: `storeHeight=2760414`. So fast_sync is not involved, this is pure block replay.

When Tendermint starts up, it asks the application which height it is processed last, and then starts replaying blocks from there. Why does the application report it's at height 0? Is the application not persisting its state to disk?

**Comment by vvaradhan** [comment]
Application is bigchaindb here.  Is there a way to check whether the application is persisting its state or not?  If not, how to enable that.  If we enable now, will it start again from height 0 ?

**Comment by erikgrinaker** [comment]
> Application is bigchaindb here. Is there a way to check whether the application is persisting its state or not? If not, how to enable that. If we enable now, will it start again from height 0 ?

I'm afraid this is application-specific. I suggest you open an issue with BigchainDB, and get back to us if something should indicate a bug in Tendermint.

**Comment by vvaradhan** [comment]
Sure, erikgrinaker.  Meanwhile, one of the blocks replay completed.. but, tendermint fails with the following error: 
`	/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x24a
panic: Tendermint state.AppHash does not match AppHash after replay. Got , expected 32613835356337336134653463643634343339393865313431633036616237303565616365386439396562623
234326264373634393431366438633139306162
`
Any pointers on how to get tendermint back on track?

**Comment by erikgrinaker** [comment]
> Sure, erikgrinaker. Meanwhile, one of the blocks replay completed.. but, tendermint fails with the following error:
> 
> ```
> /go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x24a
> panic: Tendermint state.AppHash does not match AppHash after replay. Got , expected 32613835356337336134653463643634343339393865313431633036616237303565616365386439396562623
> 234326264373634393431366438633139306162
> ```
> 
> Any pointers on how to get tendermint back on track?

This indicates that the application returned an empty app hash after applying the final block - it's hard to say why this happened without having a closer look at the application. You may want to have a closer look at the logs, or enable additional logging.

**Comment by vvaradhan** [comment]
For tendermint, I am already running with tendermint node --log_level=*:debug - are there more debug switches available?
I have just saw another tendermint process throwing same app hash error after replaying about 1950K blocks

**Comment by erikgrinaker** [comment]
> For tendermint, I am already running with tendermint node --log_level=*:debug - are there more debug switches available?
> I have just saw another tendermint process throwing same app hash error after replaying about 1950K blocks

Do the logs say anything about something that may have gone wrong? Perhaps the connection to the ABCI application was closed, or the application crashed or something similar? Does BigchainDB have any logs?

If you post the logs somewhere I can have a quick look at them Monday.

**Comment by vvaradhan** [comment]
I am afraid bigchaindb is running without debug logging enabled.  I see only this hash-error reported getting logged in tendermint.err.log with stacktraces.   Let me upload whatever logs that I have and share the link to it here.  TIA.

**Comment by vvaradhan** [comment]
> I am afraid bigchaindb is running without debug logging enabled. I see only this hash-error reported getting logged in tendermint.err.log with stacktraces. Let me upload whatever logs that I have and share the link to it here. TIA.

Following is from bigchaindb.log (debug logging not enabled): 
```
[2020-05-11 22:14:50] [WARNING] (bigchaindb.lib) Invalid transaction (DuplicateTransaction): transaction `09d66cbd8c85ed1b439dc48b397f2c4a956c8474a806160923132dc9f1060589` a
lready exists (MainProcess - pid: 41)
[2020-05-11 23:10:48] [WARNING] (bigchaindb.lib) Invalid transaction (DuplicateTransaction): transaction `e38dfd79ce15ffdda21fb68e26fdb610b975b1c9bf662f5f0091ba3fa42954a4` a
lready exists (MainProcess - pid: 41)
[2020-05-11 23:11:32] [WARNING] (bigchaindb.lib) Invalid transaction (DuplicateTransaction): transaction `b8f2587b2f325bcfeb580b621c5f46d3e796b17f5d4d3fdaad15606d0b1079e0` a
lready exists (MainProcess - pid: 41)
[2020-05-14 22:41:26] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:51954 ... (MainProcess - pid: 41)
[2020-05-14 22:41:26] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:51956 ... (MainProcess - pid: 41)
[2020-05-14 22:41:26] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:51958 ... (MainProcess - pid: 41)
[2020-05-14 22:41:26] [INFO] (bigchaindb.core) Tendermint version: 0.31.5-d2eab536 (MainProcess - pid: 41)
[2020-05-14 22:41:29] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:51960 ... (MainProcess - pid: 41)
[2020-05-14 22:41:29] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:51962 ... (MainProcess - pid: 41)
[2020-05-14 22:41:29] [INFO] (abci.app)  ... connection from Tendermint: 127.0.0.1:51964 ... (MainProcess - pid: 41)
[2020-05-14 22:41:29] [INFO] (bigchaindb.core) Tendermint version: 0.31.5-d2eab536 (MainProcess - pid: 41)
```

**Comment by vvaradhan** [comment]
and from tendermint err log: 
```
panic: Tendermint state.AppHash does not match AppHash after replay. Got , expected 39656633613934343264393464326431346632646435646231383466646539636633616535666137376633646236333138336437376663666662346461613337

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.checkAppHash(0xa, 0x0, 0xc003d05fa0, 0x6, 0xc002e570e0, 0x11, 0x1df84a, 0x6a, 0xc002e57100, 0x20, ...)
	/go/src/github.com/tendermint/tendermint/consensus/replay.go:461 +0x1ec
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc003dc6c00, 0xa, 0x0, 0xc003d05fa0, 0x6, 0xc002e570e0, 0x11, 0x1df84a, 0x6a, 0xc002e57100, ...)
	/go/src/github.com/tendermint/tendermint/consensus/replay.go:362 +0xa87
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc003dc6c00, 0x1168b00, 0xc002efc230, 0x2, 0x115a0a0)
	/go/src/github.com/tendermint/tendermint/consensus/replay.go:264 +0x6b8
github.com/tendermint/tendermint/node.NewNode(0xc0000f7400, 0x11537e0, 0xc000333e00, 0xc0008e5ce0, 0x113ff40, 0xc0008de810, 0xc0008e5f70, 0x102eb30, 0xc0008e5f80, 0x115a0a0, ...)
	/go/src/github.com/tendermint/tendermint/node/node.go:266 +0xb4f
github.com/tendermint/tendermint/node.DefaultNewNode(0xc0000f7400, 0x115a0a0, 0xc0008f0bc0, 0xc000457700, 0xc0008efc90, 0xb)
	/go/src/github.com/tendermint/tendermint/node/node.go:109 +0x448
github.com/tendermint/tendermint/cmd/tendermint/commands.NewRunNodeCmd.func1(0xc0000c5200, 0xc0003204c0, 0x0, 0x1, 0x0, 0x0)
	/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:53 +0x5b
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).execute(0xc0000c5200, 0xc0003204a0, 0x1, 0x1, 0xc0000c5200, 0xc0003204a0)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:698 +0x431
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x18d2ce0, 0x2, 0xc000322380, 0xee66cb)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:783 +0x2ca
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:736
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x18d2ce0, 0x1030c50, 0x2, 0xc000310f80)
	/go/src/github.com/tendermint/tendermint/libs/cli/setup.go:89 +0x3c
main.main()
	/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:45 +0x24a

```

**Comment by erikgrinaker** [comment]
My guess is that BigchainDB has gotten itself into some sort of inconsistent state due to the full disk. It seems to already have the transactions contained in the blocks being replayed, so it should report being at a higher height than it does:

```
[2020-05-11 22:14:50] [WARNING] (bigchaindb.lib) Invalid transaction (DuplicateTransaction): transaction `09d66cbd8c85ed1b439dc48b397f2c4a956c8474a806160923132dc9f1060589` a
lready exists (MainProcess - pid: 41)
```

You mentioned earlier that you were replaying multiple nodes. Are all of the nodes in the cluster experiencing the same problem? If not, I would suggest wiping the faulty nodes and syncing them from scratch. If that's not an option, maybe get in touch with the BigchainDB folks to try and repair the application.

**Comment by erikgrinaker** [comment]
Since there are no further updates, and the above indicates a problem with the application, I'll close this for now. Please get in touch if there turns out to be a problem with Tendermint itself here.

**Comment by vvaradhan** [comment]
> My guess is that BigchainDB has gotten itself into some sort of inconsistent state due to the full disk. It seems to already have the transactions contained in the blocks being replayed, so it should report being at a higher height than it does:
> 
> ```
> [2020-05-11 22:14:50] [WARNING] (bigchaindb.lib) Invalid transaction (DuplicateTransaction): transaction `09d66cbd8c85ed1b439dc48b397f2c4a956c8474a806160923132dc9f1060589` a
> lready exists (MainProcess - pid: 41)
> ```
> 
> You mentioned earlier that you were replaying multiple nodes. Are all of the nodes in the cluster experiencing the same problem? If not, I would suggest wiping the faulty nodes and syncing them from scratch. If that's not an option, maybe get in touch with the BigchainDB folks to try and repair the application.

Is there a standard procedure to sync from scratch?

**Comment by vvaradhan** [comment]
> Since there are no further updates, and the above indicates a problem with the application, I'll close this for now. Please get in touch if there turns out to be a problem with Tendermint itself here.

Sorry for the delayed response, I was away with no internet access.  The node has recovered and the rpc-server came up by itself.  I am looking to update the BigchainDB/tendermint version.  Are there any recommended version to upgrade to from current 0.31.5-d2eab536?

**Comment by erikgrinaker** [comment]
>Is there a standard procedure to sync from scratch?

It should be sufficient to delete the Tendermint data directory and any application state (e.g. database or data directory), then restart the node. It will then catch up with the rest of the peers by replaying all historical block (which can take a very long time, depending on your chain).

>I am looking to update the BigchainDB/tendermint version. Are there any recommended version to upgrade to from current 0.31.5-d2eab536?

From the Tendermint side, we generally recommend running the latest version, after doing appropriate testing for your use-case. However, it will depend on which Tendermint versions are supported by BigchainDB, as they may not have migrated to the latest version yet.
