### ISSUE TITLE
Full support for light-client validator set syncing

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#481]
Now that I have tried my best to implement light-client validator set syncing as proposed in #377, I have come up with some other missing functionality that would make life much easier.  This is all still working for "gradual changes", and actually, I think we could consider any changes of > 1/3 of the validator set in one block to be almost a pathological case.

I actually think *all* of these features are much more important than `NextValidatorSet` as they make the normal case actually work.  With three more features, I think we could get really nice light-client syncing:

1. Historical validator set queries (`GetValidators(height)` from #406)
2. Validator hash only changes when the set changes
3. Emit events when validator set changes (bonus)

### Historical queries

I think this is quite clear.  If I have an old block and the new block has a change of > 1/3 then the proper solution is to bisect the blocks to find a path with each step < 1/3 change.  Only... there is no way to query the validator set from old blocks.

### Validator hash represents set and nothing else

If a client has a hash and the set of validators, it is nice to see many blocks with the same hash and know I can simply re-use the validator set. The current implementation includes an Accum, which changes the hash each round with a static set. That means with 4 validators with equal votes, the hash with cycle through 4 values, which is annoying, but possibly usable.  With 100 validators and different powers, the cycle will be very large (or basically different hash each time).

If you combine it with lack of historic queries, this is a major problem.  For example, I query the current abci state and the header with that one and get hash X.  By the time I query the validators it has progressed one block and know the hash is Y.  Even though hash X represents the same set I know, there is no way I can ever detect this.

This is a [known problem in the code](https://github.com/tendermint/tendermint/blob/master/types/validator.go#L13-L15), but should really urgently get fixed:

### Emit events on validator changes (enhancement)

One the hash only changes on actual validator changes, it would be great to send an event saying that, which could be subscribed over websocket.  So a light-client could subscribe to those messages and stay in sync with the current validators, while downloading only every 10K headers or so... just when it needed to.

Once these three are implemented, I think we could get a very nice, secure, and stable light-client syncing of dynamic validator sets.

**Comment by ethanfrey** [comment]
@ebuchman it would be great if you could consider this for the 0.11 roadmap, especially considering at least #377 was originally planned for 0.9 and this should superseed it given experience actually trying to sync with a light client.

**Comment by ebuchman** [comment]
OK, this is great. Agree with all. This is top priority for 0.11. There's a lot of design work that needs to go into moving the Accum outside the Validator and saving old validator sets. Hopefully we can hammer all that out at the retreat and have a solid strategy for implementation to get 0.11 out

**Comment by adrianbrink** [comment]
I think this would be a great workshop for the retreat. Especially moving the Accum field out of the ValidatorSet.

**Comment by ethanfrey** [comment]
The validator hash is now stable as of 0.10.0 :)

Events is being overhauled by @melekes, maybe validator changes make their way in? 

Any plans on the historical validator queries?

**Comment by ebuchman** [comment]
See https://github.com/tendermint/tendermint/issues/406 for some older details

**Comment by melekes** [comment]
- [x] Historical validator set queries (GetValidators(height) from #406)
- [x] Validator hash only changes when the set changes
- [ ] Emit events when validator set changes (bonus)

**Comment by ebuchman** [comment]
Superseded https://github.com/tendermint/tendermint/issues/789
