### ISSUE TITLE
Support historical abci queries

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#482]
It is a nice use-case to be able to query for the abci state a few blocks ago, or at least to be able to specify the same block height for multiple queries to get a consistent snapshot even if the block progresses in the meantime. Jae also thinks this is very important for removing race conditions from ibc-like communication.

This was at one time considered part of #355 but ended up a much bigger project, and that "just" got proofs from the present block (which already was a huge improvement).  Now that historical queries should soon be [supported in go-merkle](https://github.com/tendermint/go-merkle/pull/24), I want to create this issue to remind us to expose this thoughout the whole stack - merkleeyes, abci, tendermint. So that a client can get a proof of the state from a few blocks ago.

**Comment by ethanfrey** [comment]
@ebuchman Another outstanding issue we have talked about for months... 0.11?  0.12?

**Comment by ebuchman** [comment]
So what changes do we need to make to tendermint to support this? Just add a `height` arg to `/abci_query`  ? Anything else?

**Comment by ethanfrey** [comment]
Yes. And support it in all abci apps that we offer.

**Comment by ethanfrey** [comment]
This is the center point for the various repos I guess

**Comment by ebuchman** [comment]
Ok. Let's denftly get that into tendermint for 0.10. Whether or not it's actually available with the apps  in time with the 0.10 release is a second question, but at least should be soon after

**Comment by ethanfrey** [comment]
Wait.. Is the historical query pr of Paul accepted yet? That is the base functionality we need to expose. I thought that wasn't going to make 0.11.

I think it is good to do rpc, config, logging cleanup together. And in 0.11 add the historical queries, for validators as well. Together they are more useful.

**Comment by melekes** [comment]
```
ABCIQuery(path string, data []byte) { return ABCIQueryWithOptions(path, data, abci.DefaultQueryOptions) }
ABCIQueryWithOptions(path string, data []byte, opts abci.QueryOptions) { ... }

type QueryOptions struct {
  Height uint64
}
```

**Comment by zramsay** [comment]
#734
