### ISSUE TITLE
cargo install tmkms error [E0405]

### ISSUE THREAD

**Issue by AkshayaManimaran96** [tendermint/tendermint#4823]
Hi,
   I wanted to use the tools in tendermint. And so when I try to install tmkms with cargo I get the following error.
`a@a-VirtualBox:~/home/a/src/github.com/tendermint/tendermint/tools/tm-signer-harness$ cargo install tmkms
    Updating crates.io index
  Installing tmkms v0.7.2
  Downloaded signal-hook v0.1.15
  Downloaded syn v1.0.20
   Compiling proc-macro2 v1.0.12
   Compiling unicode-xid v0.2.0
   Compiling syn v1.0.20
   Compiling libc v0.2.69
   Compiling typenum v1.12.0
   Compiling cfg-if v0.1.10
   Compiling cc v1.0.41
   Compiling byteorder v1.3.4
   Compiling subtle v2.2.2
   Compiling getrandom v0.1.14
   Compiling autocfg v1.0.0
   Compiling lazy_static v1.4.0
   Compiling fnv v1.0.6
   Compiling log v0.4.8
   Compiling memchr v2.3.3
   Compiling byte-tools v0.3.1
   Compiling serde v1.0.110
   Compiling fake-simd v0.1.2
   Compiling opaque-debug v0.2.3
   Compiling rustc-demangle v0.1.16
   Compiling bytes v0.5.4
   Compiling failure_derive v0.1.8
   Compiling futures-core v0.3.5
   Compiling rand_core v0.4.2
   Compiling itoa v0.4.5
   Compiling slab v0.4.2
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling pin-project-lite v0.1.5
   Compiling regex-syntax v0.6.17
   Compiling strsim v0.9.3
   Compiling ident_case v1.0.1
   Compiling maybe-uninit v2.0.0
   Compiling futures-task v0.3.5
   Compiling ryu v1.0.4
   Compiling subtle v1.0.0
   Compiling futures-sink v0.3.5
   Compiling httparse v1.3.4
   Compiling bitflags v1.2.1
   Compiling pin-utils v0.1.0
   Compiling nix v0.14.1
   Compiling either v1.5.3
   Compiling arc-swap v0.4.6
   Compiling stable_deref_trait v1.1.1
   Compiling try-lock v0.2.2
   Compiling remove_dir_all v0.5.2
   Compiling ansi_term v0.11.0
   Compiling tower-service v0.3.0
   Compiling semver-parser v0.7.0
   Compiling ppv-lite86 v0.2.6
   Compiling void v1.0.2
   Compiling termcolor v1.1.0
   Compiling canonical-path v2.0.2
   Compiling uuid v0.8.1
   Compiling once_cell v1.3.1
   Compiling generational-arena v0.2.7
   Compiling backtrace-sys v0.1.37
   Compiling clear_on_drop v0.2.3
   Compiling secp256k1-sys v0.1.2
   Compiling num-traits v0.2.11
   Compiling num-integer v0.1.42
   Compiling indexmap v1.3.2
   Compiling tracing-core v0.1.10
   Compiling thread_local v1.0.1
   Compiling block-padding v0.1.5
   Compiling futures-channel v0.3.5
   Compiling rand_core v0.3.1
   Compiling http v0.2.1
   Compiling itertools v0.7.11
   Compiling owning_ref v0.4.1
   Compiling http-body v0.3.1
   Compiling quote v1.0.4
   Compiling iovec v0.1.4
   Compiling time v0.1.43
   Compiling net2 v0.2.34
   Compiling atty v0.2.14
   Compiling rand v0.4.6
   Compiling signal-hook-registry v1.2.0
   Compiling wait-timeout v0.2.0
   Compiling generic-array v0.12.3
   Compiling generic-array v0.9.0
   Compiling regex-automata v0.1.9
   Compiling prost-amino v0.5.0
   Compiling tracing-log v0.1.1
   Compiling want v0.3.0
   Compiling aho-corasick v0.7.10
   Compiling quote v0.6.13
   Compiling smallvec v0.6.13
   Compiling rand_core v0.5.1
   Compiling mio v0.6.22
   Compiling tempdir v0.3.7
   Compiling signal-hook v0.1.15
   Compiling digest v0.8.1
   Compiling block-buffer v0.7.3
   Compiling crypto-mac v0.7.0
   Compiling universal-hash v0.3.0
   Compiling stream-cipher v0.3.2
   Compiling aead v0.2.0
   Compiling digest v0.7.6
   Compiling backtrace v0.3.46
   Compiling secp256k1 v0.17.2
   Compiling matchers v0.0.1
   Compiling regex v1.3.7
   Compiling syn v0.14.9
   Compiling synstructure v0.12.3
   Compiling darling_core v0.10.2
   Compiling serde_derive v1.0.110
   Compiling pin-project-internal v0.4.16
   Compiling gumdrop_derive v0.7.0
   Compiling tracing-attributes v0.1.7
   Compiling thiserror-impl v1.0.16
   Compiling rand_chacha v0.2.2
   Compiling tokio v0.2.20
   Compiling atomicwrites v0.2.5
   Compiling curve25519-dalek v1.2.3
   Compiling sha2 v0.8.1
   Compiling hmac v0.7.1
   Compiling poly1305 v0.5.2
   Compiling color-backtrace v0.3.0
   Compiling zeroize_derive v1.0.0
   Compiling signature_derive v1.0.0-pre.2
   Compiling darling_macro v0.10.2
   Compiling pin-project v0.4.16
   Compiling gumdrop v0.7.0
   Compiling tracing v0.1.13
   Compiling thiserror v1.0.16
   Compiling rand v0.7.3
   Compiling tokio-util v0.3.1
   Compiling hkdf v0.8.0
   Compiling zeroize v1.1.0
   Compiling signature v1.0.0-pre.1
   Compiling failure v0.1.8
   Compiling darling v0.10.2
   Compiling chrono v0.4.11
   Compiling toml v0.5.6
   Compiling semver v0.9.0
   Compiling serde_json v1.0.53
   Compiling futures-util v0.3.5
   Compiling elliptic-curve v0.3.0
   Compiling subtle-encoding v0.4.1
   Compiling secrecy v0.6.0
   Compiling subtle-encoding v0.5.1
   Compiling curve25519-dalek v2.0.0
   Compiling chacha20 v0.3.4
   Compiling hkd32 v0.3.1
   Compiling ed25519 v1.0.0-pre.1
   Compiling prost-amino-derive v0.5.0
   Compiling abscissa_derive v0.5.0
   Compiling tracing-subscriber v0.1.6
   Compiling tai64 v3.1.0
   Compiling h2 v0.2.5
   Compiling ed25519-dalek v1.0.0-pre.2
   Compiling p384 v0.1.0
   Compiling k256 v0.1.1
   Compiling p256 v0.1.0
   Compiling x25519-dalek v0.6.0
   Compiling chacha20poly1305 v0.3.3
   Compiling abscissa_core v0.5.2
   Compiling hyper v0.13.5
   Compiling ecdsa v0.4.0
   Compiling signatory v0.18.1
   Compiling signatory-secp256k1 v0.18.1
error[E0405]: cannot find trait `PrehashSignature` in crate `signature`
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/signatory-secp256k1-0.18.1/src/lib.rs:24:10
   |
24 | #[derive(Signer)]
   |          ^^^^^^ not found in `signature`

error[E0405]: cannot find trait `PrehashSignature` in crate `signature`
  --> /home/a/.cargo/registry/src/github.com-1ecc6299db9ec823/signatory-secp256k1-0.18.1/src/lib.rs:89:39
   |
89 | #[derive(Clone, Debug, Eq, PartialEq, Verifier)]
   |                                       ^^^^^^^^ not found in `signature`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0405`.
error: failed to compile `tmkms v0.7.2`, intermediate artifacts can be found at `/tmp/cargo-installIIpaC6`

Caused by:
  could not compile `signatory-secp256k1`.
`
All help is appreciated. Thank you.

**Comment by melekes** [comment]
Could you please open an issue in https://github.com/iqlusioninc/tmkms. Thanks!
