### ISSUE TITLE
Amino-compatible encoding/json wrapper

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4828]
This is meant as a tracking issue for some places where json encoding will change and effect the developer.

## Summary

Currently amino is used for JSON encoding. With the move to protobuf this is not possible anymore. `encoding/json` & `gogo/protobuf/jsonpb` encode things differently. We will have to rely on `jsonpb` for JSON encoding in Tendermint. The json will be encoded following the protobuf json spec https://developers.google.com/protocol-buffers/docs/proto3#json

Tracking for things that will need to change

- [x] wal2json & json2wal
- [ ] RPC
- [ ] privval (.json) files
   Options:
    - Write a script to migrate keys to oneof encoding. This will take in the `privval_key.sjon` and replace it with the encoding which is consistent with oneof
    - Keep backward compatibility 
- [ ] Genesis
   - no need for backwards compatability here as chains will have to restart for this change. Although a script to aid in genesis migration may make upgrading a bit easier
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Liamsi** [comment]
Does that mean **all** json ever produced in tendermint will follow jsonpb encoding? Aren't there places where json is used via `encoding/json` only (or was that in the SDK)?

**Comment by marbar3778** [comment]
There are a few places we do use `encoding/json` primarily in the rpc pkg and a few places elsewhere. The rpc pkg will be migrated to jsonpb and the other few places could be migrated as well. I think having the entire codebase sharing the same json encoding format could be nice.

**Comment by tessr** [comment]
It does seem like we should use `jsonpb`. From the [`jsonpb` documentation](https://godoc.org/github.com/golang/protobuf/jsonpb):

> Do not rely on the default behavior of the standard encoding/json package when called on generated message types as it does not operate correctly.

I know the other concern here is about rust, but I assume rust must have a pb-to-json library that follows the official spec..... right?

**Comment by erikgrinaker** [comment]
> I assume rust must have a pb-to-json library that follows the official spec..... right?

Even if it doesn't, I think the bigger point is that there's a well-defined spec to follow.

Note that `jsonpb` only works with `proto.Message`. This means that anything that we're ever going to encode/decode as JSON has to go via Protobuf, even if we don't use the Protobufs for anything else. This implies e.g. changing the RPC layer to use Protobufs for all requests and responses. Alternatively we write (or find) a shim that encodes Go structs to Protobuf-style JSON.

**Comment by Liamsi** [comment]
> Even if it doesn't, I think the bigger point is that there's a well-defined spec to follow.

Yes, and JSON has pretty awesome support in rust via serde. So even if it doesn't, having a clear spec to follow and writing serializers using serde would be simple enough.

> I know the other concern here is about rust, but I assume rust must have a pb-to-json library that follows the official spec..... right?

We currently use some [prost](https://github.com/danburkert/prost) fork for all things amino/protobuf in tendermint-rs. While it does not support JSON afaik there are alternatives which could be used there, e.g.: 
https://github.com/stepancheg/rust-protobuf/tree/master/protobuf/src/json

My understanding is that if there are proto files, we can use them to generate serialization code from them (for both binary and proto-json). So we can throw away all the custom handwritten serialization code ... I can investigate to confirm this.

Something else to consider about jsonpb:
> The google.golang.org/protobuf/encoding/protojson package converts protocol buffer messages to and from JSON using the canonical JSON mapping, and fixes a number of issues with the old jsonpb package that were difficult to change without causing problems for existing users.

from: https://blog.golang.org/protobuf-apiv2
See also:
https://pkg.go.dev/google.golang.org/protobuf/encoding/protojson?tab=doc

**Comment by erikgrinaker** [comment]
Yeah, I'm in favor of `protojson` - but then we would need to ditch `gogoproto` since they're incompatible.

**Comment by aaronc** [comment]
One proto json thing that's a bit weird is auto camelCasing of fields. We may want to not adopt that (it's configurable)

Also in the sdk, we're planning to use https://github.com/grpc-ecosystem/grpc-gateway to serve a REST API (proxied to gRPC) instead of manual REST routes

**Comment by marbar3778** [comment]
>Also in the sdk, we're planning to use https://github.com/grpc-ecosystem/grpc-gateway to serve a REST API (proxied to gRPC) instead of manual REST routes

we are in the middle of having this discussion as well for tendermint. We are looking around and testing how somethings work to see if we would be satisfied with the same approach.

**Comment by erikgrinaker** [comment]
Following discussion in the last Tendermint call, we'll be keeping the same JSON format as currently used by Amino, but write a wrapper around encoding/json to handle it. This is a stopgap until we can finalize the discussion around RPC (see #4857).

**Comment by ebuchman** [comment]
Do we have a summary of the divergence between the protobuf JSON and the current amino JSON? I thought they were pretty close

**Comment by erikgrinaker** [comment]
Mainly the Amino interface wrapper (object with type/value keys) vs Protobuf any (same scheme but different key names with URL types) or Protobuf oneofs (one key per variant). Apart from that they should be equivalent, barring any minor differences in e.g. null handling.

**Comment by aaronc** [comment]
There may be other differences. For instance amino does bech32 encoding of addresses. These would all by base64 in proto json

**Comment by erikgrinaker** [comment]
I think those are handled by explicit marshaling overrides on individual types - so not a general Amino thing, and the same could be done with Protobuf I believe.

**Comment by aaronc** [comment]
It can with amino but not with protobuf. Proto json defines standard mappings

**Comment by erikgrinaker** [comment]
All code migrated to new Amino-compatible JSON encoder in #4955, #4968, and #4975
