### ISSUE TITLE
32bit issue ?

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#483]
https://github.com/tendermint/ethermint/issues/35

**Comment by adrianbrink** [comment]
Do we want to support 32bit platforms?

**Comment by ramilexe** [comment]
@adrianbrink I think yes, because Edison (Intel hardware for IOT) uses Yocto which is 32bit

**Comment by adrianbrink** [comment]
@ebuchman If we decide to support 32bit as well, then we also need to setup ```make test``` and make test_integrations``` to run on 32bit platforms. 

However, generally it doesn't seem like a massive change if they only places where we have to change something is in the AtomicUInt64

**Comment by ramilexe** [comment]
I can provide tests for 33bit using docker. I already did it on another
project

6 мая 2017 г. 12:16 пользователь "Adrian Brink" <notifications@github.com>
написал:

**Comment by ramilexe** [comment]
Code from CI script:

```
#workaround for https://github.com/tendermint/ethermint/issues/35
sed -i 's/atomic.LoadInt64(&c.sendRate)/c.sendRate/' vendor/github.com/tendermint/go-p2p/connection.go
sed -i 's/atomic.LoadInt64(&c.recvRate)/c.recvRate/' vendor/github.com/tendermint/go-p2p/connection.go
```

**Comment by adrianbrink** [comment]
@ramilexe This might help you too #72

**Comment by adrianbrink** [comment]
@bucky I don't think that tendermint core should support 32-bit for now. We would have to setup another CI environment just for 32-bit, plus COSMOS validators will most likely run everything in 64-bit machines. I don't see a use-case in our current scope.
