### ISSUE TITLE
lite2: block_results RPC call doesn't correctly return the result of the latest block

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4837]
## Problem Definition

When I run a local light client and query for block_results of the latest height (at height 6 in this example), the following is returned
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "failed to update light client to 7: failed to obtain the header #7: signed header not found"
  }
}
```

It should however return the result for the header #6
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
The problem is we need `7` to prove that `6` LastResultsHash.
