### ISSUE TITLE
can not open tcp-window.png

### ISSUE THREAD

**Issue by jdyuankai** [tendermint/tendermint#4842]
In page "https://docs.tendermint.com/master/introduction/architecture.html",  image url is "https://docs.tendermint.com/master/introduction/tcp-window.png"

**Comment by erikgrinaker** [comment]
Thank you for reporting this, we'll have a look.

**Comment by tessr** [comment]
Hmm. I didn't realize that page ended up on the docs website; we'd mostly checked it into the repo for our own reference. We should probably just pull it out, tbh.

**Comment by tessr** [comment]
Will move to a new `notes` directory.
