### ISSUE TITLE
p2p: update addrbook

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4848]
Following the https://github.com/tendermint/tendermint/issues/4846, we should probably update our addrbook based on the changes / bugfixes in https://github.com/btcsuite/btcd/tree/master/addrmgr

**Comment by tessr** [comment]
I know we're redoing all of the P2P layer right now, but this is probably an easy win.

**Comment by tychoish** [comment]
The new P2P layer doesn't have an address book in the same way that this describes, or would be relevant here, so I'm going to go ahead and close this issue, because I think no longer relevant.
