### ISSUE TITLE
Make RPC layer JSON-RPC 2.0 compliant

### ISSUE THREAD

**Issue by fabcan** [tendermint/tendermint#485]
**BUG REPORT**:

**Tendermint version** : 0.8

**What happened**: the RPC layer accessible via the 46657 port is not compliant to JSON-RPC 2.0 specification, thus not working with standard libraries that check compliance. 
Specification link: http://www.jsonrpc.org/specification

The specification that are not met are at least 2:
- "Either the result member or error member MUST be included, but **both members MUST NOT be included**.", each Tendermint response has both members but it must not according to specifications;
- "When a rpc call encounters an error, the Response Object MUST contain the **error member with a value that is a Object with the following members**[...]", each Tendermint error response is always a simple string and never an object, but it must be an object according to specifications.

**Comment by davebryson** [comment]
This is actually the code in tendermint/go-rpc correct?

**Comment by ebuchman** [comment]
Yes. But in the upcoming 0.10.0 release it will be in `github.com/tendermint/tendermint/rpc`. See the `develop` branch!

**Comment by davebryson** [comment]
Ooops. so I made (local) changes to go-rpc to address this issue.  Should I push a patch back for that or work off the 0.10.0 release?

**Comment by davebryson** [comment]
See https://github.com/tendermint/go-rpc/pull/19

**Comment by melekes** [comment]
I think we will be able to port this using git patch.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/521
