### ISSUE TITLE
state: lunatic evidence validation should get the header at the height of infringement

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4866]
## Problem Definition

At the moment, when checking whether an instance of lunatic validator evidence has been committed we compare the header of the lunatic validator with the most recent header of our own.

```
if ev, ok := evidence.(types.LunaticValidatorEvidence); ok {
	if err := ev.VerifyHeader(committedHeader); err != nil {
		return err
	}
}
```

However, we should be comparing the header the node has at the same height of that of the LunaticValidator otherwise many of the fields we check could have changed by then e.g. ValidatorHash, NextValidatorHash

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/976eebe281685cd7982e03a24ce06ab3ff0561e8/evidence/pool.go#L184

committed header is the header at the height of infringement

**Comment by cmwaters** [comment]
but I don't think for validation:

```
if err := VerifyEvidence(stateDB, state, ev, &block.Header); err != nil {
	return types.NewErrEvidenceInvalid(ev, err)
}
```

**Comment by cmwaters** [comment]
https://github.com/tendermint/tendermint/blob/976eebe281685cd7982e03a24ce06ab3ff0561e8/state/validation.go#L145

**Comment by melekes** [comment]
Right. Good catch!
