### ISSUE TITLE
evidence: phantom evidence doesn't require a header

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4867]
## Problem Definition

Currently we add the header to the evidence but this is not necessary because we can derive all the necessary information e.g. height, time and chainID verification from just the vote itself

## Proposal

Remove the header segment in PhantomValidatorEvidence

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
Vote does not contain `ChainID`
