### ISSUE TITLE
light: in case of a fork (light or full), monitor the chain for evidence

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4873]
when there's a fork, light client should stop and monitor the chain for evidence (amnesia or lunatic). when a new block is produced with such evidence, light client must be able to verify it and continue on its operation.

Concrete design needs to fleshed out in ADR.

Positive:

- no need for clients to restart light client subjectively

**Comment by tessr** [comment]
I feel like this has been accounted for in other conversations/designs, so I'm going to close it for now. If I'm wrong, please re-open and we can triage it!
