### ISSUE TITLE
tx indexing: application or node operator

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4877]
## Summary

With #4466 indexing of txs was enabled at runtime. Previously the node operator would decide which txs it would like to index, but now the application can decide which it should index. This mesh of application and node operator worlds can cause confusion espeically if its not well documented.

Should the application take precedence and if so having the node operator set the txs to index becomes redundant. 

## Proposal
I am not sure the best approach to this but one approach is to have an on or off switch for the indexer that is toggled by the node operator. When off the node would ignore indexing set by the application, when on the application decides what to index. 

Before making a decision on the approach the overhead to always having to run the indexer should be considered alongside the disk size growth when indexing vs not indexing. 

cc @melekes 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I agree with @marbar3778 here. Now that the application can direct decisions on what is indexed, having a switch to index in the config should be considered. That way when an operator doesn't want to index and processes tx/block events with `index: true`, they'll be ignored.

However, I took a look at the config again and it seems there are two options for `indexer`, `null` and `kv`. If the value is set to `null`, does that effectively turn off indexing @melekes?

**Comment by aaronc** [comment]
What is the rationale for the `index` field on `EventAttribute`?

My sense is that an application should only force all nodes to index stuff that is actually needed for consensus. I can see scenarios where we would want to have things indexed that live outside the merkle tree but are still using by the state machine. But if the state machine will never read these values then I think it should be the node operators choice.

**Comment by marbar3778** [comment]
>However, I took a look at the config again and it seems there are two options for indexer, `null` and `kv`. If the value is set to null, does that effectively turn off indexing @melekes?

it seems it is merely set to a null indexer: https://github.com/tendermint/tendermint/blob/master/state/txindex/null/null.go. 

>What is the rationale for the index field on EventAttribute?

A user requested the ability to index txs at runtime. They did the work and we decided to accept the work. It still has the same logic as before (node operator configurable) and now on top of that there is application indexing. I am referring to how these things should be separated. Should the application take precedent over the node operator's settings or vice versa or should there be an extra config to allow/disallow applications to freely index? 

On master, if the node operator doesn't explicitly set indexer to `null` then the application will be able to index freely.

**Comment by melekes** [comment]
> However, I took a look at the config again and it seems there are two options for indexer, null and kv. If the value is set to null, does that effectively turn off indexing @melekes?

it does turns indexing off

**Comment by melekes** [comment]
> If we have both the node operator and app deciding which txs to index then it will cause confusion

100%

**Comment by melekes** [comment]
Moving indexing configuration to the ABCI application sounds good to me. As long as node operators have a choice to opt-out. Tags were introduced for indexing/querying capabilities. It makes sense to ABCI app to say what tags needs to be indexed. 

Now, some node operators might want to index more stuff and provide extended search. For this, they will have to write their own indexer. Should be fine too.

**Comment by erikgrinaker** [comment]
> As long as node operators have a choice to opt-out. 
>
>Now, some node operators might want to index more stuff and provide extended search. For this, they will have to write their own indexer.

This could, and I think should, be configurable in the ABCI app.

**Comment by marbar3778** [comment]
> This could, and I think should, be configurable in the ABCI app.

I do agree with this. I think this can be broken into two issues. One removes event filtering in Tendermint, moves it to the application, and one enables the application to turn on or off (opt-out) of indexing. The second part could lead to a better design in which an application could inject a custom indexer when using Tendermint as a library. We would need to define an interface for indexers. This way people that want custom indexing don't need to fork the repo.

**Comment by melekes** [comment]
> One removes event filtering in Tendermint, moves it to the application

I'm afraid by doing this we'll deprive users (who don't use cosmos-sdk) of useful functionality.
