### ISSUE TITLE
Add logging for changes in the validator set

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#490]
The original issue: #480

A node should log any changes in the validator set it sees. For example, it should log whether another node in the network switches from validator to observer or vice versa. Furthermore, it should log changes in voting power as well as new observers joining.

**Comment by ebuchman** [comment]
https://github.com/tendermint/tendermint/pull/488

**Comment by melekes** [comment]
What do we need to do to achieve that?

currently, we log changes after executing a block:
https://github.com/tendermint/tendermint/blob/develop/state/execution.go#L111
```
	if len(valDiff) > 0 {
		logger.Info("Update to validator set", "updates", abci.ValidatorsString(valDiff))
	}
```

Do we want an advanced version of this? Like 

```
if (val.accum == 0) {
  Info("%s was removed from the validator set")
} else {
...
}
```

**Comment by ebuchman** [comment]
We can just log the list of updated validators when we get it from EndBlock
