### ISSUE TITLE
What is the time Zone used by the Tendermint at the time of Creation of Block

### ISSUE THREAD

**Issue by skdjango001** [tendermint/tendermint#4902]
Hi,
 I am doing research on finding Tendermint time zone format 

"latest_block_time": "2020-05-27T09:58:15.674607954Z"
I just want to know  at the time of creation of block time will show so i want to know whether the time zone is in UTC format or IST format? @ebuchman @ @melekes

**Comment by skdjango001** [comment]
Or is there any other format

**Comment by melekes** [comment]
UTC

**Comment by skdjango001** [comment]
Hi melekes i am getting this error after some blocks created  
 E[2020-05-28|16:19:54.459] Error on broadcastTxCommit  module=rpc err="Timed out waiting for tx to be included in a block"
/home/ten1//go/src/properties.txtFile contents: ZSC_Test_0,ZSC_Test_0_OWNER,cmn_usr_pwd,My!s2qlm1,Test_Node0SHA512 op is  ORxrSC5rWhx-PtRNbojMLwfreX64_rnMXKKFAJJNZdrkM6IWXlScV2PHzAKdsqlm-byI439DQYhbT4lssDCU-A==

**Comment by skdjango001** [comment]
and one more issue i have  i am trying to figure out mempool size, 
E[2020-05-28|14:13:02.431] Error on broadcastTxCommit     module=rpc err="Mempool is full: number of txs 10000 (max: 10000), total txs bytes 4774160 (max: 1073741824)"
how can i manage this mempool size and i just want to know can we turnoff mempool ?  @melekes 
@ebuchman

**Comment by erikgrinaker** [comment]
Hi @skdjango001! We answered your mempool question in #4914, perhaps increasing the mempool size will fix the tx timeout as well? I'm closing this for now, please get back to us in #4914 if you're still experiencing issues.
