### ISSUE TITLE
lite2: use bisection (not VerifyCommitTrusting) when verifying a header from witness

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4934]
When a fork is detected (two blocks have different hashes), we need to verify the one we got from a witness. Right now, we call `VerifyCommitTrusting`, which might fail if latestTrustedVals do not have 1/3+ presence in `altH.Commit`.

To properly verify an alternative header, we need to try to bisect from `latestTrustedHeader` to `altH`.

**Comment by cmwaters** [comment]
In the event of a fork where two conflicting headers are picked up by a light client, is it critical that the light client tries to find the root of the fork i.e. the two conflicting headers who share the same header parent and have at least 1/3 overlap of voting power. I'm beginning to think it is and the light client should work back to find these two headers and submit them.

**Comment by melekes** [comment]
> In the event of a fork where two conflicting headers are picked up by a light client, is it critical that the light client tries to find the root of the fork i.e. the two conflicting headers who share the same header parent and have at least 1/3 overlap of voting power. I'm beginning to think it is and the light client should work back to find these two headers and submit them instead of the initial conflicting headers it sees.

I love this ^

**Comment by cmwaters** [comment]
In addendum to what I just said, I believe if we do this method of working back to find the common parent header (i.e. the root of the fork) that attacks such as phantom validator would not be possible (and maybe even lunatic validator). I'm not 100% sure of this though, so I would need someone to validate my thinking

**Comment by melekes** [comment]
Closing for https://github.com/tendermint/tendermint/issues/5083

**Comment by ebuchman** [comment]
Should this be closed? I thought this was orthogonal to what's in 5083 and here is about ensuring when we detect conflicting headers, we always do bisection to verify them.

**Comment by melekes** [comment]
Oh, right) Thanks
