### ISSUE TITLE
vote height mismatch errors

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4936]
The current `master` (at da924fc62d7b7d8ea83ff27efa8845593055b11f) is showing these errors in the logs:

```
node2    | E[2020-06-02|09:08:08.109] Error with msg                               module=consensus height=16 round=0 peer=f0646885dae44bfbe08ebefa61b5c878a2f72e3e err="error vote height mismatch" msg="[Vote Vote{0:2D23C0E75F34 15/00/1(Prevote) AE8F4037B3F1 191F28A2AE21 @ 2020-06-02T09:08:07.966201271Z}]"
node2    | E[2020-06-02|09:08:08.109] Error with msg                               module=consensus height=16 round=0 peer=f0646885dae44bfbe08ebefa61b5c878a2f72e3e err="error vote height mismatch" msg="[Vote Vote{1:2EDBF7C7CAAA 15/00/1(Prevote) AE8F4037B3F1 2A6B048F024E @ 2020-06-02T09:08:07.965788535Z}]"
```

Can be reproduced as follows:

```
$ rm -rf build; make build-linux && make localnet-start
```

**Comment by qyzxcswbll** [comment]
use cluster of nodes
I have the same problem

E[2020-06-03|03:52:04.904] Error with msg                               module=consensus height=1458 round=0 peer=d9f68b359315c42d089808ffba4bad63c74cade8 err="error vote height mismatch" msg="[Vote Vote{1:1966A6A2956B 1457/00/1(Prevote) E2A45D6C08B3 803B0A094FE5 @ 2020-06-03T10:52:04.679532427Z}]"
E[2020-06-03|03:52:04.904] Error with msg                               module=consensus height=1458 round=0 peer=d9f68b359315c42d089808ffba4bad63c74cade8 err="error vote height mismatch" msg="[Vote Vote{3:F16C8C6F7A18 1457/00/1(Prevote) E2A45D6C08B3 6A750E510D8C @ 2020-06-03T10:52:04.686970366Z}]"

**Comment by erikgrinaker** [comment]
>use cluster of nodes
>I have the same problem

Is this on `master`, or from a release?

**Comment by qyzxcswbll** [comment]
release v0.33.5

**Comment by erikgrinaker** [comment]
Did a `git bisect`, the error message is introduced with this: https://github.com/tendermint/tendermint/commit/287110d4256006c37c9e1948169750beb830859f

Which of course means that the actual problem may have been older. We'll investigate further.
