### ISSUE TITLE
q tendermint-validator-set --limit 100 --page 0 returns same result as page 1

### ISSUE THREAD

**Issue by njmurarka** [tendermint/tendermint#4942]
**Tendermint version**:

Tendermint Core Semantic Version: 0.33.3
P2P Protocol Version: 7
Block Protocol Version: 10
```
"node_info": {
    "protocol_version": {
      "p2p": "7",
      "block": "10",
      "app": "0"
    },
    "id": "dbc39feecf277f59b4b16ae277e8545c54ac244a",
    "listen_addr": "tcp://0.0.0.0:26656",
    "network": "bluzelle",
    "version": "0.33.3",
    "channels": "4020212223303800",
    "moniker": "daemon-sentry-3",
    "other": {
      "tx_index": "on",
      "rpc_address": "tcp://0.0.0.0:26657"
    }
```

**ABCI app**:

Cosmos SDK Version: v0.38.3
```
"application_version": {
    "name": "BluzelleService",
    "server_name": "blzd",
    "client_name": "blzcli",
    "version": "0.0.0-74-ge1ee575",
    "commit": "e1ee575051ad2ea18ef22fc6bf7a6fc904612a49",
    "build_tags": "ledger,faucet,cosmos-sdk v0.38.3",
    "go": "go version go1.14.3 linux/amd64"
  }
```

Big Dipper Explorer URL:

```
http://explorer.testnet.public.bluzelle.com:3000
```

Instructions to setup a similar node (I'd suggest just setting up a sentry):
```
https://github.com/bluzelle/curium/blob/devel/docs/public/buildvalidatorsentry.md
```

Access to genesis file for chain:
```
http://a.sentry.bluzellenet.bluzelle.com:1317/genesis.json
```

Sample command to get node info:
```
curl --location --request GET 'http://a.sentry.testnet.public.bluzelle.com:1317/node_info'
```

Discord channel invite (in case you want to live chat with me... I am Neeraj one of the admins):
```
https://discord.gg/BbBZJZJ
```

**Environment**:
- **OS** (e.g. from /etc/os-release):

```
Distributor ID: Ubuntu
Description:  Ubuntu 18.04.4 LTS
Release:  18.04
Codename: bionic
```

- **Install tools**:

Using COSMOS SDK v0.38.3. Otherwise, not sure what else to say here.

- **Others**:

We are running a testnet chain with our CRUD database as one of the application modules, in COSMOS. 

We currently (as of filing this issue) have 5 "sentries" and 3 validators. To be clear, the sentries have no voting power and are the only peers that the validators talk to (the validators can talk to each other too). Furthermore, the validators are IP firewalled to only be able to talk to the sentries and other validators. The sentries themselves keep the validator node id's private.

Sentry hostnames:

```
a.sentry.testnet.public.bluzelle.com
b.sentry.testnet.public.bluzelle.com
c.sentry.testnet.public.bluzelle.com
d.sentry.testnet.public.bluzelle.com
e.sentry.testnet.public.bluzelle.com
```

I am not listing the validator hostnames, since they are inaccessible (due to the firewall) anyways.

The validators are only listening on 26656 to validators and sentries. The sentries are listening on 26656 and 26657 and also each run the cosmos REST server, listening on 1317. 

We have opened our testnet to the public. Members of the public have setup sentries and validators of their own, and are expected to use our five sentries as their P2P peers in config.toml. 

**What happened**:

When I attempt to get the tendermint validator set with pagination, page 0 returns the same result as page 1. I am guessing that in a pagination context, page 0 should be an error and certainly not the same result set as page 1?

`blzcli q tendermint-validator-set --node tcp://testnet.public.bluzelle.com:26657 --limit 100 --page 0 | jq '.validators`

`blzcli q tendermint-validator-set --node tcp://testnet.public.bluzelle.com:26657 --limit 100 --page 1 | jq '.validators`

The above two commands generate the same result.

**What you expected to happen**:

Page 0 should be an error.

**Comment by njmurarka** [comment]
@alessio 

Here is the issue we discussed.

**Comment by melekes** [comment]
https://docs.tendermint.com/master/rpc/#/Info/validators

page number is 1-based ^

**Comment by njmurarka** [comment]
@melekes I understand. 

But because there is pagination here, my argument is there shouldn't be a page 0 then.

I have noticed in some contexts (like specifying a block height integer) that there is a 0 value allowed, despite block heights starting at 1. In this context, 0 means "last block height", which is reasonable. 

But in a pagination context, it is very misleading. For example, I initially thought page 0 had a distinctive set of results from 1, until I randomly noticed they were the same.

**Comment by melekes** [comment]
makes sense. we can change the logic to return an error if `page=0` is given
