### ISSUE TITLE
Add version string to block header

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#495]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Feature Request (by ebuchman)

For 0.10 tendermint release

Add one string to the block header with a version string, which is set when we compile the software.  This string will be equal between two nodes iff they are running the same version of the software.  This will allow us to much more easily coordinate upgrades across nodes.

This may contain two parts, like API version enabled, and API version activated

**Comment by zramsay** [comment]
@ethanfrey see #736

**Comment by ethanfrey** [comment]
Sounds good. We use the version same as `tendermint version`, right?

The concept of activated has not been discussed in many, many months?

We need to coordinate upgrades both of tendermint core as well as the application running on abci. I think the more common case is coordinating abci upgrades. After 1.0, tendermint upgrades should generally be backwards compatible.

Maybe we can rethink the needs and design it proper?

**Comment by ebuchman** [comment]
Usurped by https://github.com/tendermint/tendermint/issues/952

Let's make some room in the header for version strings for now. We can enforce/decide specific behaviour later :)
