### ISSUE TITLE
testing: evaluate and adopt Twins: White-Glove Approach for BFT Testing

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4953]
Paper: https://arxiv.org/pdf/2004.10617

Right now, we only have a single test https://github.com/tendermint/tendermint/blob/master/consensus/byzantine_test.go, which does not cover all (or even a fraction) of possible scenarios.

We should analyze Twins and see if we can write a better test suite to test byzantine failures deterministically.

**Comment by cmwaters** [comment]
I was also thinking about how we can develop a more systematic and legible approach for the testing in consensus. (The state_test.go is almost 2000 lines and can be hard to navigate). Just to throw it out there I was thinking of dividing tests into:

- Byzantine tests
- Time out or time based tests
- Mutli-round tests
- Basic tests (simple single round or single aspect tests)
- Slashing tests? I saw a large section of commented out code about this so not sure if it should be there

Obviously this list isn't exhaustive and just meant to be a starting point.
