### ISSUE TITLE
DuplicateVoteEvidence is missing JSON tags

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#4958]
The `DuplicateVoteEvidence` struct is missing JSON tags, resulting in camel case JSON output.

Discovered while adding support for this in the tendermint-rs: https://github.com/informalsystems/tendermint-rs/pull/242/files#r417475910

I wonder if there's other types that might be missing JSON tags and if there's some easy way to check for that?

Would be breaking on the RPC to fix this, but also doubles as a bug fix since JSON should only use snake_case

**Comment by marbar3778** [comment]
I believe we had some way to test the openAPI documentation against the RPC but since we upgraded to openAPI 3.0 the tool we were using before does not work anymore, they are actively working on upgrading it.
