### ISSUE TITLE
testing: Jepsen test suite

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4963]
Tendermint 0.10.2 was verified using Jepsen in Sept. 2017. No significant issues were found: "Tendermint appears to satisfy its safety guarantees". You can read the [full report](https://jepsen.io/analyses/tendermint-0-10-2) for more details.

Many things have changed since then (although consensus algo remained almost untouched).

We should resurrect https://github.com/jepsen-io/tendermint test suite and, ideally, run it for every major release. 

One other option is to try to use https://github.com/jepsen-io/elle (paper: https://github.com/jepsen-io/elle/raw/master/paper/elle.pdf). But it will probably take longer to write something for Elle than to update an existing test suite.

**Comment by erikgrinaker** [comment]
Kyle just finished up a new Docker Compose setup for Jepsen: https://github.com/jepsen-io/jepsen/tree/master/docker

**Comment by melekes** [comment]
My plan so far:

- [x] update merkleeyes app (API, drop amino)
- [ ] update Jepsen to latest version
- [ ] replace amino with proto in Jepsen tests
- [ ] configure Docker compose setup
- [ ] configure nightly CI task

**Comment by dshulyak** [comment]
just fyi there is one more alternative that can be used to test linearizability - https://github.com/anishathalye/porcupine. it is much faster, and written in golang (e.g. can be used directly in tests, without complex setup).

**Comment by melekes** [comment]
run into some UX problems while upgrading tests for tm 0.34

- https://github.com/tendermint/tendermint/issues/5770
- https://github.com/tendermint/tendermint/issues/5769
