### ISSUE TITLE
broken link on light client documentation page

### ISSUE THREAD

**Issue by hxrts** [tendermint/tendermint#4977]
first link "light package is broken on this page:

https://github.com/tendermint/tendermint/blob/master/docs/tendermint-core/light-client-protocol.md

I think you want this?

https://pkg.go.dev/github.com/tendermint/light-client?tab=doc

**Comment by melekes** [comment]
The link is correct. We just need to release a new version of Tendermint for Go doc to update.

In the meantime, please use this link https://pkg.go.dev/github.com/tendermint/tendermint@v0.33.5/lite2?tab=doc

https://github.com/tendermint/light-client was deprecated 3 years ago.
