### ISSUE TITLE
fixed64 canonoical types

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4998]
This issue is meant as a communication issue on canonical types.

Within the canonical types previously we added `binary:fixed64` tag but now with protobuf we have the option of migrating to sfixed64 or fixed64 which will always represent 8-byte's. I am not sure if ledger could use a proto library. @jleni could you let me know what is capable on a ledger device and if this change can be made?

**Comment by Liamsi** [comment]
If I'm not wrong, I think the ledger lib that @jleni wrote can read the fixed proto type without any changes to the C code (because binary:fixed64 has a proto equivalent). I think the question also is: would we want to keep the fixed size encoding here, or, is it obsolete now as you can use protobuf everywhere (even on the ledger nano s and similar environments) to de/encode variable sized?

**Comment by jleni** [comment]
Using a proto (any?) library in Ledger devices is a bit painful given the very strict memory limitations. 
Given that the Tendermint app is already working and the vote parser is relatively small, I would avoid switching to a completely new parser unless necessary.

About moving from `fixed64` to `sfixed64` it sounds like a relatively easy fixed.
I see two things to take into account:
- migrating to sfixed64/fixed64
- any kind of versioning strategy in case you need support for both or so we can detect old messages and reject.

Typically in protobuf, if you make changes on the types, I would expect this to be a new field (different idx) to allow for backwards compatibility. We can internally fill the very same value from both possible pb fields.

**Comment by marbar3778** [comment]
> Using a proto (any?) library in Ledger devices is a bit painful given the very strict memory limitations.

How will this be handled for cosmos-sdk ledger app?

> migrating to sfixed64/fixed64

just a heads up these are the same. ismail has a pr to make it non breaking so there shouldnt be a worry

**Comment by jleni** [comment]
So we have two apps at the moment:
- Cosmos SDK uses JSON
- Tendermint app uses amino/protobuf

Is Cosmos also moving away from JSON to Protobuf? What would be a much much bigger change that we need to discuss.

**Comment by jleni** [comment]
> just a heads up these are the same. ismail has a pr to make it non breaking so there shouldnt be a worry

Do you have a link to that PR?
@Liamsi is that backwards compatible strategy also applicable to HW wallet? I would be surprised. The test vectors I saw look quite different!

**Comment by marbar3778** [comment]
https://github.com/tendermint/tendermint/pull/5008 this is the PR

**Comment by marbar3778** [comment]
> Is Cosmos also moving away from JSON to Protobuf? What would be a much much bigger change that we need to discuss.

ah okay forgot about this. They are staying with json for signing last i checked

**Comment by Liamsi** [comment]
> Is Cosmos also moving away from JSON to Protobuf? What would be a much much bigger change that we need to discuss.

@jleni apparently yes, they are moving completely to protobuf, but the old JSON encoding will still be possible for a while: https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-020-protobuf-transaction-encoding.md#sign_mode_legacy_amino

**Comment by jleni** [comment]
mmm... Moving to protobuf (binary) will have some unintended consequences... 

This is not about amino vs protobuf but about self-describing fields. The move to protobuf will result in incompatibilities between cosmos based chains.. 
@marbar3778 @alessio

**Comment by alexanderbez** [comment]
cc @aaronc 👀

**Comment by aaronc** [comment]
> This is not about amino vs protobuf but about self-describing fields. The move to protobuf will result in incompatibilities between cosmos based chains..
> 
> At least with respect to things like generic hw wallet support for all projects.

@jleni How will the move to protobuf result in incompatibilities between cosmos based chains? Compatibility between chains should be more or less like it is now.

> What is the timeframe for this change?

Sometime this summer.

> @Liamsi is that backwards compatible strategy also applicable to HW wallet? I would be surprised. The test vectors I saw look quite different!

Hardware wallets will use the same amino JSON signing for now until `SIGN_MODE_TEXTUAL` is implemented: https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-020-protobuf-transaction-encoding.md#sign_mode_textual.

**Comment by jleni** [comment]
I am actually really happy about moving to protobuf. 

The only issue I see if that Ledger apps right now are generic, so they can handle any self-describing message. This means that different cosmos-based projects can use the very same app. If we move to protobuf, that means that you would need to generate code for each case and go through Ledger's review process again..

Still, this is all not relevant now that you say that you are keeping JSON for now and considering SIGN_MODE_TEXTUAL. 
In my experience, an encoding that has worked very well for many other projects is CBOR. (basically a binary JSON) with low overhead.

Encoding messages in a flat CBOR map/dictionary can be easy to parse and size efficient. If necessary, CBOR->JSON is very easy to do.

In general, I would advice:
- header fields with versioning information (to avoid incorrect parsing as the data schema evolves)
- ideally key/value pairs
- self describing and ideally with some type information
- limited nesting in the tx structure (this results in higher memory usage in small devices).
- standardized type formatting / presentation. Avoid a wide variation of number of decimals, etc. that can result in presentation issues or mistakes.

**Comment by aaronc** [comment]
> The only issue I see if that Ledger apps right now are generic, so they can handle any self-describing message. This means that different cosmos-based projects can use the very same app. If we move to protobuf, that means that you would need to generate code for each case and go through Ledger's review process again..

This was true when we were encoding interfaces with `oneof`s, but we switched to `Any` in large part to avoid problems like this.

> Still, this is all not relevant now that you say that you are keeping JSON for now and considering SIGN_MODE_TEXTUAL.
> In my experience, an encoding that has worked very well for many other projects is CBOR. (basically a binary JSON) with low overhead.
> 
> Encoding messages in a flat CBOR map/dictionary can be easy to parse and size efficient. If necessary, CBOR->JSON is very easy to do.
>
> In general, I would advice:
> 
> * header fields with versioning information (to avoid incorrect parsing as the data schema evolves)
> * ideally key/value pairs
> * self describing and ideally with some type information
> * limited nesting in the tx structure (this results in higher memory usage in small devices).
> * standardized type formatting / presentation. Avoid a wide variation of number of decimals, etc. that can result in presentation issues or mistakes.




The primary motivation behind `SIGN_MODE_TEXTUAL` as I understand it is the ledger app so whatever we choose let's make it the best choice for ledger users.
