### ISSUE TITLE
mempool.broadcast = false in config file will effect any performance in block creation 

### ISSUE THREAD

**Issue by skdjango001** [tendermint/tendermint#5001]
Hi,
I just want to know about if i change mempool.broadcast = false; is there any effect for other nodes
I am running 3 nodes, is there any impact on transactions while creating the blocks all 3 nodes will go to check_tx or not  ?? @ebuchman @erikgrinaker @ValarDragon @melekes

**Comment by melekes** [comment]
`mempool.broadcast = false` won't have any affect on block production. the node won't be gossiping transactions, true, but transaction gossiping is only a part of what the node usually sends (votes, txs, peer lists, etc.)

**Comment by skdjango001** [comment]
If I made change to mempool.broadcast = false; Is there any improvement in performance ? or else nothing change in performance ? actually i am trying to increase tendermint performance.
Is there any ways to increase the tendermint performance.,

**Comment by melekes** [comment]
> Is there any ways to increase the tendermint performance?

Yes, see https://medium.com/@anton.kalyaev/tendermint-the-ultimate-guide-for-faster-consensus-cd57087dfd2e

If you have any further questions, please ask them here OR

- [join our chat and ask us anything](https://discord.gg/AzefAFd) 💬
- [ask a question on StackOverflow](https://stackoverflow.com/questions/tagged/tendermint) 📚
