### ISSUE TITLE
Wait for ABCI commit on shutdown

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5002]
I don't believe we currently wait for in-flight ABCI commits and other state operations before shutting down following a `SIGTERM`, but simply exit the process. This can cause problems for applications with non-atomic persistence layers, e.g. Cosmos SDK (see https://github.com/cosmos/cosmos-sdk/issues/6370).

**Comment by melekes** [comment]
What about all the TrapSignal we have?

```
» rg "TrapSignal"                                                                         146 ↵

cmd/priv_val_server/main.go
61:     tmos.TrapSignal(logger, func() {

cmd/tendermint/commands/run_node.go
117:                    tmos.TrapSignal(logger, func() {

cmd/tendermint/commands/lite.go
158:    tmos.TrapSignal(logger, func() {

libs/os/os.go
16:// TrapSignal catches the SIGTERM/SIGINT and executes cb function. After that it exits
18:func TrapSignal(logger logger, cb func()) {

libs/autofile/cmd/logjack.go
44:     tmos.TrapSignal(fmtLogger{}, func() {

rpc/jsonrpc/test/main.go
33:     tmos.TrapSignal(logger, func() {})

```

**Comment by erikgrinaker** [comment]
None of those wait for ABCI commit to finish, as far as I can tell. The trap in `run_node.go` calls `Stop()` on all the reactor, but from what I can tell `Stop()` on the consensus reactor does not wait for block processing to complete, it just aborts immediately.
