### ISSUE TITLE
[docs] broken link to full resolution figure

### ISSUE THREAD

**Issue by samuela** [tendermint/tendermint#5004]
https://docs.tendermint.com/master/introduction/what-is-tendermint.html

The link "See here for high resolution version" is broken.

**Comment by melekes** [comment]
got the file. should we put it in the repo directly or smth else?

**Comment by marbar3778** [comment]
The link was removed. The photo that is currently there is good. If we would like to add the high resolution we can do so in another repo to not over inflate the size of this one. (will take longer to clone on slower internet connections)
