### ISSUE TITLE
Protobuf file structure should reflect Buf.build guidelines

### ISSUE THREAD

**Issue by clevinson** [tendermint/tendermint#5021]
## Summary

Align proto file structure (for tendermint protofiles + third party proto files) to Buf.build best practices, for easier importing of tendermint proto definitions by downstream projects (e.g. Cosmos SDK).

## Problem Definition

In Cosmos SDK, protobuf files were recently reorganized into a single `proto` folder, with third party definitions in a `third_party/proto` folder to align with Buf.build conventions around `PACKAGE_DIRECTORY_MATCH` (see [here](https://buf.build/docs/lint-checkers#file_layout)).

As a result, cosmos-sdk currently needs to `sed` over a handful of imported tendermint protobuf definitions to align with these standard conventions (see [here](https://github.com/cosmos/cosmos-sdk/pull/6413/commits/626a52ee4b17639bbca9bcb8655e33e81eddaecd)).

## Proposal

- Organize all tendermint proto files into top level `proto` folder
- Organize all third party proto files into similar `third_party/proto` folder
- Turn on `PACKAGE_DIRECTORY_MATCH` linter in Buf to ensure this is adhered to moving forward

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
>

    Organize all tendermint proto files into top level proto folder
    Organize all third party proto files into similar third_party/proto folder
    Turn on PACKAGE_DIRECTORY_MATCH linter in Buf to ensure this is adhered to moving forward


the first two are already complete. I will look into the third in the morning. I believe we had something similar to this before and moved away from it. 

This also breaks vscode and possibly other ide's as they aren't able to recognize the structure of the codebase. 

https://github.com/cosmos/cosmos-sdk/pull/6413#issuecomment-645635089
