### ISSUE TITLE
Issues with VerifyComposite

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5022]
CompositeEvidence is implemented by only one type, ConflictingHeadersEvidence, which is what's submitted by a light client when they correctly verify two conflicting headers.

However I think the current VerifyComposite returns errors in certain cases where a light client was legitimately fooled. A few concerns:

- it's possible a light client is fooled by two conflicting headers, neither or which are from the real chain! So we need a way to handle this kind of evidence where neither header matches the true header for that height
- maxNumValidators seems a bit arbitrary. Sure, it's unlikely the val set will double in size, but don't we already have a global max val set size in the codebase? Can we use that? If not, maybe we should set one ? 
- `// Header must be signed by at least 1/3+ of voting power of currently` - I'm not sure this is true or where this came from. Eg. in a proper lunatic attack, the validator is tricked into believing a header with a validator set that is <1/3 of the real validator set.

I haven't had a chance to review ADR-047 yet but I'll look into it. Seems like we need a bit more work/thought here though to get this right.

These concerns originally came up when we were discussing whether or not a light client needed to submit full bisection traces as evidence or whether the two conflicting headers were enough. At the time we thought we did need the full traces, so the full node could truly verify the light client was tricked by these headers. On thinking about it now, it might be possible to avoid this, but I think we would need to do more checks.

On a related note, having ValidatorAddress in the CommitSig makes these kinds of checks much simpler, since we don't need to additionally submit the validator set. If we're removing ValidatorAddress eventually, we'll likely need to send the ValidatorSet along with the SignedHeader. It might be worth starting to make these kinds of changes iteratively to reduce dependencies on the ValidatorAddress so when it comes time to remove it, it's easy. cc #4835

**Comment by ebuchman** [comment]
Close for #5083 ?

**Comment by melekes** [comment]
I think this can be closed now.
