### ISSUE TITLE
Tendermint Application Guide for Java and Kotlin out of date.  Location of proto files no longer valid

### ISSUE THREAD

**Issue by jonpoulter** [tendermint/tendermint#5034]
https://docs.tendermint.com/master/guides/java.html

The head of the git repo does not reflect the location of the proto files as stated in the following step

mkdir -p \
  $KVSTORE_HOME/src/main/proto/github.com/tendermint/tendermint/abci/types \
  $KVSTORE_HOME/src/main/proto/github.com/tendermint/tendermint/crypto/merkle \
  $KVSTORE_HOME/src/main/proto/github.com/tendermint/tendermint/libs/kv \
  $KVSTORE_HOME/src/main/proto/github.com/gogo/protobuf/gogoproto

cp $GOPATH/src/github.com/tendermint/tendermint/abci/types/types.proto \
   $KVSTORE_HOME/src/main/proto/github.com/tendermint/tendermint/abci/types/types.proto
cp $GOPATH/src/github.com/tendermint/tendermint/crypto/merkle/merkle.proto \
   $KVSTORE_HOME/src/main/proto/github.com/tendermint/tendermint/crypto/merkle/merkle.proto
cp $GOPATH/src/github.com/tendermint/tendermint/libs/kv/types.proto \
   $KVSTORE_HOME/src/main/proto/github.com/tendermint/tendermint/libs/kv/types.proto
cp $GOPATH/src/github.com/gogo/protobuf/gogoproto/gogo.proto \
   $KVSTORE_HOME/src/main/proto/github.com/gogo/protobuf/gogoproto/gogo.proto

**Comment by marbar3778** [comment]
thank you for creating the issue. Would you like to open a PR? otherwise I will take a look at this in the coming days.
