### ISSUE TITLE
p2p: data race in NetAddress.String() memoization

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5047]
@alexanderbez is trying to run multiple Tendermint nodes in a single process and seems to have uncovered a latent data race in Tendermint that seems to be present even for a single node: https://github.com/cosmos/cosmos-sdk/pull/6489/#issuecomment-648860843

If I understand correctly, the problem is string memoization in concurrently accessed NetAddress. We keep a list of persistent peers (NetAddress), that is shared between the Dial() and Accept() routines, as each needs to check if a new peer is persistent. However, if these routines run at the same time, they may call the NetAddress.String() concurrently, which results in a data race because of the memoization (ie. one is trying to read the `.str` field while the other is trying to write it).

It's fascinating that this never came up before. It probably would require attempting to Accept() and Dial() connections at the same time. Probably running nodes in different processes means there's enough time delays that this never happens, but by running them in the same process, suddenly the issue emerges.

It should be possible to replicate this in a single node by simultaneously trying to connect to the node and calling it's `/dial_peers` endpoint to try and get the Accept() and Dial() routines to run at the same time. It could also occur in practice if someone tries to connect to the node at the same time that the PEX triggers it to dial out, but it might be pretty rare. That said, most binaries are probably not built with `--race`, so this is unlikely to be caught in the wild. 

It would be interesting to see if someone can replicate this for a single node by simultaneously trying to connect and query the dial endpoint!

A simple solution would be to remove the memoization. It seems like a pretty trivial performance impact, since if I'm not mistaken it's just formatting fields already present in the NetAddress (eg. converting port from int to string), but doesn't involve any syscalls or anything. So I suspect the memoization is unnecessary, but maybe worth a quick benchmark check.

Other solutions would involve introducing a mutex into the NetAddress, or into the persistentPeers list, but those seem like overkill. Probably the NetAddress should be a read-only structure that's thread safe by default and doesn't really need internal mutable state for memoization ...

**Comment by alexanderbez** [comment]
Thanks for the handy investigation work and detailed issue. I think going with the removal of memoization seems like the most pragmatic approach, we're not talking ms in latency here anyway. As you've laid out, a mutex seems overkill for sure.

**Comment by ebuchman** [comment]
On a related note, the race happens immediately on startup. Just build with `-race` and run tendermint and you'll see it. 

It's a bit harder to trigger afterwards using the RPC `/dial_peers` endpoint while simultaneously dialing it since you have to give it nodes it can actually connect to, but the way the pex is written it will probably happen every time it receives a pack of addresses and tries to dial them since it check's their persistence concurrently before dialing.
