### ISSUE TITLE
Protocol Version Bumps and Changelog

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5057]
Just a note on Block Protocol and P2P Protocol versions and breaking changes.

It looks like we neglected to bump both protocol versions with v0.33.0. They were bumped to Block Protocol version 10 and P2P Protocol version 7 in the v0.30.0 release, and no breaking changes were made until v0.33.0. We should have bumped them to 11 and 8 respectively in v0.33.0. In the upcoming v0.34.0, we should probably bump them to 12 and 9 then to make up for it ... not sure if it's worth a v0.33 series release with the corrected protocol versions. 

Also, in the current CHANGELOG_PENDING, many of the items under `Block Protocol` don’t relate to the block protocol. Anything related to reactor message encodings belongs under `P2P Protocol`. Things that just change on-disk formats I think have gone under CLI/RPC/Config (maybe they deserve their own section, but that’s the best one). Things under Block Protocol should actually impact the way block-level data is encoded/verified/processed. If it effects how the block is encoded, it will likely effect how a reactor msg is encoded, and thus could/should be included additionally as a P2P Protocol breaking change. Something that does belong under Block Protocol but not P2P Protocol for instance is the change to validator set sorting, which impacts block verification but doesn't impact anything sent to peers. There’s a short note on this in https://github.com/tendermint/tendermint/blob/master/version/version.go#L31 but maybe we need to document it better in CONTRIBUTING.md

There's also a bunch of stuff listed in CLI/RPC/Config that really belong under Go API (eg. any of the Go type name changes).

**Comment by ebuchman** [comment]
Also there's mention in the changelog about breaking changes to JSON encoding but it's not really clear what (if anything?) broke?

**Comment by marbar3778** [comment]
adding in a section on light client to the upgrading.md is needed. I am updating the sdk to 0.34-dev1 and digging through the code.

**Comment by melekes** [comment]
> Also there's mention in the changelog about breaking changes to JSON encoding but it's not really clear what (if anything?) broke?

it's not breaking anything afaik

**Comment by marbar3778** [comment]
the only breakage in the json should be ints being encoded as numbers instead of strings. This is shown in the changelog and relfected in the swagger file.
