### ISSUE TITLE
Implement tracing logger

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#506]
This is open for discussion. Frey suggested we have a `--trace` flag which forces log formatter to use `%+v` instead of `%v` for errors. It will be super useful when we adopt https://github.com/pkg/errors more in our code.

Question: why not output errors using `%+v` by default?

/cc @ethanfrey

**Comment by ethanfrey** [comment]
Great. 

The stack trace is only really useful for development and is confusing for the end user. Often the message about a missing config option or bound port is good for them. Only when the error is unexpected do we need the trace. We could make the default true on develop and false on master. 

I did add support for trace in tmlibs/cli. But just for the error returned by a client command, not for logging long running processes. It would be great to have the same flag increase the detail in the logger as well. 

Note that this is orthogonal to debug log level. I could only output errors in the logger, but then with the entire stack trace.

**Comment by ethanfrey** [comment]
Oh, and please integrate this in tmlibs, so I can use the same on other long running processes, like an abci app or the light client proxy

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/pull/519
