### ISSUE TITLE
node: adding custom reactors with reference to node

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5067]
## Problem Definition

I would like to swap out the consensus reactor for my own custom one - however I need access to consensus state to initialize it which is created during the `NewNode()` constructor.  Ideally, instead of passing the reactor, I would pass a function to create the reactor that gives me access to these things. 

## Proposal

Instead of this:

```
func CustomReactors(reactors map[string]p2p.Reactor) Option {
	return func(n *Node) {
		for name, reactor := range reactors {
			if existingReactor := n.sw.Reactor(name); existingReactor != nil {
				n.sw.Logger.Info("Replacing existing reactor with a custom one",
					"name", name, "existing", existingReactor, "custom", reactor)
				n.sw.RemoveReactor(name, existingReactor)
			}
			n.sw.AddReactor(name, reactor)
		}
	}
}
```

I was thinking of implementing this

```
func CustomReactorsAsConstructors(reactors map[string]func(n *Node)p2p.Reactor) Option {
	return func(n *Node) {
		for name, customReactor := range reactors {
			if existingReactor := n.sw.Reactor(name); existingReactor != nil {
				n.sw.Logger.Info("Replacing existing reactor with a custom one",
					"name", name)
				n.sw.RemoveReactor(name, existingReactor)
			}
			n.sw.AddReactor(name, customReactor(n))
		}
	}
}
```

My only concern is that maybe we don't want to restrict the access a new reactor has, i.e. don't expose the entire node (but then again node is already exposed by the very nature of the Option -> `type Option func(*Node)`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
can't you add the reactor afterwards using smth like `node.Switch().AddReactor(name, yourCustomReactor)`?

**Comment by cmwaters** [comment]
yes that's what I'm doing at the moment - I just wasn't sure if this is just a hack or how we want to be using it

**Comment by cmwaters** [comment]
Also specifically with the consensus reactor it isn't so much the reactor but the consensus state that is hard to replace. There are so many dependencies with other structs like mempool, blockExecutor and evidencePool which are predominantly private. I could imagine why someone would just prefer to fork

**Comment by melekes** [comment]
I would love to see more sane and clean `Node` API. Maybe it makes sense to create a global issue, where we list everything which is wrong w/ the current API (e.g https://github.com/tendermint/tendermint/issues/4644)

**Comment by cmwaters** [comment]
I'm closing this as I don't think this issue is relevant given the recent context surrounding reactor support and changes made to internalize the API. For those that come across this and are interested to where talk of custom reactors headed I would defer to https://github.com/tendermint/tendermint/pull/6562
