### ISSUE TITLE
Timestamp of genesis header from the container is from the time when the container was published

### ISSUE THREAD

**Issue by OStevan** [tendermint/tendermint#5082]
@ebuchman as mentioned during the last meeting here is the issue regarding the `commit` RPC endpoint and the timestamp for genesis header being from the time the container was published.

**Tendermint version**: v0.33.5

**What you expected to happen**: I would expect that the genesis header has a timestamp from the time when the container was started. The reason why I think this would be useful to fix is that if somebody wants to write integration tests (for example, for light client) they would need to set up trusted period programmatically if they want to start from the genesis block as a trusted block.

**How to reproduce it**: 
```
docker run -p 26657:26657 tendermint/tendermint:v0.33.5
curl -X GET "http://localhost:26657/commit?height=1" -H  "accept: application/json"
```
[docker-container-commit-response.txt](https://github.com/tendermint/tendermint/files/4869855/docker-container-commit-response.txt)

**Comment by marbar3778** [comment]
I do believe this is purposeful. We can change it that the container does not call `tendermint init` and it's on the user to call tendermint init, or you could provide it a genesis as a volume.

**Comment by liamsi** [comment]
> I do believe this is purposeful. 

But what is that purpose then? IMO a sane default would be where the genesis is created when the image is run the first time instead. Can't we run `tendermint init` on `CMD` / `ENTRYPOINT` instead? As far as I remember `tendermint init` does not overwrite anything if it finds any available config.

An image where the genesis time corresponds to when the image is started for the first time makes testing a light against that image easier. Actually, I can't see any usage scenario where genesis time = image creation time makes much sense. The only scenario (I can think of) where deterministic time would make sense, are reproducible builds but we would likely use a different image for that particular purpose anyways.

If I'm not missing anything here I'm happy to "fix" this as @OStevan and others would like to test different light client implementations against a running tendermint node.

**Comment by marbar3778** [comment]
> Can't we run tendermint init on CMD / ENTRYPOINT instead?

I am for this change, I never fully understood why we needed to call `tendermint init` on creation of the image.

**Comment by greg-szabo** [comment]
The background is that before a change a few weeks ago, there was no default config in the Docker image at all. You had to mount a volume, call `init` on it and then you could start the chain.

The change we implement a few weeks ago is that there is a default configuration in the image now so people (and services) can start it without any extra commands. You can still mount a volume and do your own thing, as before.

The benefit is/was that with the default configuration you have the genesis header without any additional commands and that you can run a container with only one command. This was important for tendermint-rs integration testing, where we use GitHub Actions' Services which doesn't allow you to do preparations on the service you want to run.

I guess you could add a wrapper in the Docker image to generate the config and maybe set up an extra wallet before you start the chain (and print the private keys so they can be used). The disadvantage I see is that integration tests will run on different chains each time you run them. Reproducibility will be jeopardized.

I understand that in the light client case, that's the exact need. Maybe using it as originally intended (running init on a mounted volume) is still the best way there.

**Comment by liamsi** [comment]
Thanks for all the context.

> The disadvantage I see is that integration tests will run on different chains each time you run them. 

Hmm, good point. From a light client testing perspective it is actually nice that the node will always have the same key but it seems OK to query these via (json) RPC.

> run a container with only one command. This was important for tendermint-rs integration testing, where we use GitHub Actions' Services which doesn't allow you to do preparations on the service you want to run.

I think that should still possible by basically running the equivalent of `tendermint init && tendermint node --proxy_app=kvstore` via the dockerfile. I'll keep that in mind so that it doesn't change and still be integrated swiftly into github actions.

> Reproducibility will be jeopardized.

I think you can still share genesis file and config (keys) to reproduce the exact same environment. If I'm not wrong this already isn't really "the same chain" because actions will already depend on when the image was started (genesis time might be the same but the commits will depend on the time the docker image was started).
