### ISSUE TITLE
Timestamp of a Tendermint Transaction beyond the present timestamp 

### ISSUE THREAD

**Issue by skdjango001** [tendermint/tendermint#5085]
HI Actually i am doing performance testing with my shell script with payload size of 700 characters
 I have a question about the timestamp when the No of Tx done the timestamp crease as per the flow but it increase beyond the current time line
so i am attaching the status of my tendermint tx 
```
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "node_info": {
      "protocol_version": {
        "p2p": "7",
        "block": "10",
        "app": "1"
      },
      "id": "c43490d7d9de9d1050df38fff5d7abba2e5c2505",
      "listen_addr": "tcp://0.0.0.0:20056",
      "network": "chain-EbAbRC",
      "version": "0.31.3",
      "channels": "4020212223303800",
      "moniker": "Test_Node0",
      "other": {
        "tx_index": "on",
        "rpc_address": "tcp://0.0.0.0:20057"
      }
    },
    "sync_info": {
      "latest_block_hash": "8408047AE25B2770CB0C9A5052CF70B957895801F11F43FE20E192F758C05E44",
      "latest_app_hash": "4E6F205374617465",
      "latest_block_height": "240188",
      "latest_block_time": "2020-07-07T02:41:37.856760498Z",
      "catching_up": false
    },
    "validator_info": {
      "address": "80C3842932372B1662B5FA9D83D572E283DAE444",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "RAZ5O6gQLmVHXxIIEfASXctIFZwugrgBh3VonalMEvg="
      },
      "voting_power": "10"
    }
  }
```
Is it a bug?

**Comment by melekes** [comment]
Tendermint treats transaction as opaque bytes. So, "tendermint transaction timestamp" does not make sense. Generally, it's okay for time between two servers to diverge a little bit. It might be useful to setup NTP on your servers (https://www.digitalocean.com/community/tutorials/how-to-set-up-time-synchronization-on-ubuntu-16-04) to sync time.

---

The issue tracker is for discussing Tendermint bugs and new features, not for user support. Please join our [Discord](https://discord.gg/AzefAFd) or [forum](https://forum.cosmos.network/) and ask the community.

Feel free to open an issue if you find a _confirmed_ bug in Tendermint.
