### ISSUE TITLE
Missing double quotes in Dockerfile VOLUME statement

### ISSUE THREAD

**Issue by shuplenkov** [tendermint/tendermint#5086]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
Any of 0.32 and 0.33

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- MacOs and Ubuntu (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
During container creation using docker-compose I get this error:
```
 Cannot create container for service tendermint: invalid volume specification: '48b8fe7c5f34dd6ac1c5a36d2effdc529e4a801682f3b44f3cb33f1ba46cac33:[:rw': invalid mount config for type "volume": invalid mount path: '[' mount path must be absolute
```
We expect that missing double quotes in VOLUME statement 
```
VOLUME [ $TMHOME ]
```
leads to an issue with the volume being created with three paths: /tenderment, [, ].

**What you expected to happen**:
Container created and started

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Sometimes it works, sometimes it doesn't. You may try to create docker-compose file with tendermint as a service and try to run the whole thing. Sometimes upon container creation this error happens.
Or you can start tendermint docker container, run ```docker inspect tendermint_comtainer_name``` and see there are three volumes, instead of one: 
``` 
"Volumes": {
                "/tendermint": {},
                "[": {},
                "]": {}
            },
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:
I suggest to replace 
```
VOLUME [ $TMHOME ]
```

with 

```
VOLUME [ "$TMHOME" ]
```
This should solve the problem.

**Comment by marbar3778** [comment]
thank you for opening this we will fix this issue and push a new docker image.

**Comment by liamsi** [comment]
> leads to an issue with the volume being created with three paths: /tenderment, [, ].

Ouch. I'll look into it.

> Sometimes it works, sometimes it doesn't.

🤔 

Can you confirm that the double quotes will resolve this?

**Comment by shuplenkov** [comment]
Yeah. I've tried to build 2 docker images: one with ``` VOLUME [ $TMHOME ] ``` and another with ``` VOLUME [ "$TMHOME" ] ```

In the first case, I had thee paths ``` /tenderment, [, ] ``` and in the second one there was only ``` /tenderment ```

**Comment by jawid-h** [comment]
Hi @liamsi, thank you for a quick response! Unfortunately, we're stuck with `v0.32` for now, is it possible to fix this for that version too?

**Comment by liamsi** [comment]
> is it possible to fix this for that version too?

Not sure, @marbar3778, @tessr, @greg-szabo is it possible to push updated docker images without creating a release (e.g. manually)? It would actually be nice to have the changes of #5087 for light client integration tests (in tendermint-rs we currently target 0.33).

**Comment by marbar3778** [comment]
> is it possible to fix this for that version too?

yes we will be able to provide new docker images with these fixes for 0.32 and 0.33. The images will most likely be tagged the same.

**Comment by liamsi** [comment]
reopening. can be closed when updated docker imgs are  pushed

**Comment by marbar3778** [comment]
Here is the image of [32.12](https://hub.docker.com/layers/tendermint/tendermint/v0.32.12-1/images/sha256-2f6a2d900beec57f0336c01e1cf06be8d2194f0244f386c8576b3221c05461d1?context=explore). we appended `-1` to the image name to differentiate between the original. This image has the fix of wrapping the volume in quotes. 

I will close this issue, please comment if any issues arise.
