### ISSUE TITLE
lite2: /validators and /block_results return an error

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5089]
https://github.com/tendermint/tendermint/pull/4931#issuecomment-654535452

I met following error when I tested it.
```
curl -s "localhost:8888/block_results"
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "last results  does not match with trusted last results 4837665DFE640A370E7496C691987562D02462142C5F34F59E185911A12370EA"
  }
}
```

I wonder if this code is right.
```
// in /light/rpc/client.go: BlockResults()
results := types.NewResults(res.TxsResults)
if rH, tH := results.Hash(), trustedHeader.LastResultsHash; !bytes.Equal(rH, tH)

// LastResultsHash is defined as following
LastResultsHash = ABCIResponsesResultsHash(abciResponses) // merkle.HashFromByteSlices([][]byte{bbeBytes, results.Hash(), ebeBytes})
```

If `TxsResults` is nil, then `rH` is byte[0] but `tH` is an array having 32 bytes length.

And there's another problem, `Validators` rpc seems to have not fixed it.

```
curl -s "localhost:8888/validators"
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "failed to update light client to 1756: failed to obtain the header #1756: signed header not found"
  }
}
```

**Comment by cmwaters** [comment]
For the validator issue, is the light client trying to obtain a header at a height that is 1 more than the current chain height?

**Comment by cmwaters** [comment]
> If TxsResults is nil, then rH is byte[0] but tH is an array having 32 bytes length.

I guess if the TxResults is nil then there is nothing that the light client needs to verify and we can just skip this right?

**Comment by melekes** [comment]
@egonspace ^

**Comment by melekes** [comment]
> > If TxsResults is nil, then rH is byte[0] but tH is an array having 32 bytes length.
> 
> I guess if the TxResults is nil then there is nothing that the light client needs to verify and we can just skip this right?

headers should match in any case
