### ISSUE TITLE
Tendermint version returns error

### ISSUE THREAD

**Issue by nodar-chkuaselidze** [tendermint/tendermint#509]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): **BUG REPORT**

**Tendermint version**: 267f134d44e76efb2adef5f0c993da8a5d5bd1b8

**Environment**:
- **MacOS 10.12.4**

**What happened**:
```ERROR: Failed to parse default log level (pair *:notice, list *:notice): Expected either "info", "debug", "error" or "none" level, given notice```

**What you expected to happen**: `tendermint version` to return version of the build

**How to reproduce it**: `tendermint version`

**Comment by ebuchman** [comment]
Oh yes - we removed the `notice` log level. It used to be the default. You need to either delete your ~/.tendermint/config.toml or set the log_level to something accepted, like error, info, or debug.

**Comment by ebuchman** [comment]
Closing. Please re-open if there's actually a bug.
