### ISSUE TITLE
gasWanted and gasUsed are camelCase in ResponseDeliverTx JSON

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5111]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.33 and master

**What happened**:

/block_results:

```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {
    "height": "4",
    "txs_results": [
      {
        "code": 0,
        "data": null,
        "log": "",
        "info": "",
        "gasWanted": "0",
        "gasUsed": "0",
...
      }
    ],
    "begin_block_events": null,
    "end_block_events": null,
    "validator_updates": null,
    "consensus_param_updates": null
  }
}
```

Note the `gasWanted` and `gasUsed`. These should probably be snake_case for consistency.

Tripped up in https://github.com/informalsystems/tendermint-rs/issues/423

**What you expected to happen**:

Everything in snake_case

**Have you tried the latest version**: yes/no
yes
**How to reproduce it** (as minimally and precisely as possible):
Run the kvstore, send a tx, query the block with it

**Anything else we need to know**:

We might want some tooling to check this for us. I think it may be that proto is default outputting camelCase names? 

Like what's happening here: 

https://github.com/tendermint/tendermint/blob/8b460786ded92596920050f33c82013c60055147/abci/types/types.pb.go#L2017-2027

Why are there two conflicting json tags?

**Comment by marbar3778** [comment]
I can take this, this is mainly due to protobuf since we are using gogoproto there is a feature that handles this but this will come up again when we move off of gogoproto

**Comment by erikgrinaker** [comment]
> we may need to extend out json encoder to support the custom jsontag feature

I believe this is encoded by Protobuf, as the canonical Protobuf JSON encoding specifies lowerCamelCase for field names. This can be overridden by the `[json_name = "foo"]` option.
