### ISSUE TITLE
make events hashing optional

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5113]
On Thursday, we discussed whether we should keep or revert https://github.com/tendermint/tendermint/issues/1007 (see [the recording](https://www.youtube.com/watch?v=f6mphJKKErA) for more detail).

Including events in the results hash enables a number of features that our users have requested; on the other hand, it will also likely add friction future development. Historically events have been treated as very malleable, and in particular the SDK has a wide range of events that are likely to change in the future. Including events as part of the results hash means that any change to events is now a protocol-breaking change. 

As a middle ground approach, we're now planning on giving _each event_ a flag to mark it as included in the results hash, or not. Events will be excluded by default. In other words, events marked with this new flag will be included in the hash; other events do not need any modification and will be excluded. 

TODO:

- [x] a small ADR
- [ ] implementation
- [ ] documentation, in both the docs and in changelogs and upgrading documents

**Comment by alexanderbez** [comment]
WRT to the "middle ground approach", wouldn't all operators in the network have to align on the exact same configuration in terms of what events are included in the results hash? Otherwise, you would get application Merkle root mismatches.

**Comment by marbar3778** [comment]
> WRT to the "middle ground approach", wouldn't all operators in the network have to align on the exact same configuration in terms of what events are included in the results hash? Otherwise, you would get application Merkle root mismatches.

I believe this would rely on how the application is doing event indexing. In terms of the sdk there could be a loop to check a map of preapproved events to set `hash: bool` to true or they would be set where the module sets events. This should have no outside coordination (node operators)

**Comment by alexanderbez** [comment]
Well technically Tendermint is the framework that is actually doing the indexing -- the SDK, now, dictates what is being indexed. However, this is a _local_ configuration and decision of the operator.

So the approach you've suggested will not work from what I can see. You have to remove the event index decision making at the local level and move it to the global/consensus level, which means you need to remove the recent changes to `app.toml` and now figure out a way to have this be governed by the state-machine via on-chain parameters or something.

However, I think what you can do, and maybe this is what you're actually suggesting is, have a _Tendermint_ consensus parameter, e.g. `include_events`, where if true, events are still localized in terms of indexing but can be included in the header regardless.

**Comment by melekes** [comment]
> WRT to the "middle ground approach", wouldn't all operators in the network have to align on the exact same configuration in terms of what events are included in the results hash?

Yes, they have to agree, but it should be easy if they all run the same application. If you look at it from the angle of AppHash, it's no different. Like if all operators run the same application, they all will get the same AppHash. Similarly, if all operators run the same application, they all will get the same LastResultsHash.

**Comment by marbar3778** [comment]
> However, I think what you can do, and maybe this is what you're actually suggesting, is have a Tendermint consensus parameter, e.g. include_events, 

I meant this in the application. The application has a map of events it wants hashed into the header and before sending the events to Tendermint it marks the event field `hash:bool` (can be a different name) to true and Tendermint just checks that. 

The localization of tx indexing is orthogonal to this.

**Comment by alexanderbez** [comment]
Right, but agreeing on what to hash has to be global is what I'm saying -- currently all indexing logic is **local**. So how do you decide what to hash? All events can be hashed upon a new major version, but every time you add new events, which is very common, they will not be hashed and as a result, you lose the benefits of hashing WRT to the new events.

**Comment by alexanderbez** [comment]
> Yes, they have to agree, but it should be easy if they all run the same application.

Yes, that's exactly the crux of the problem and creates a messy UX. Because it's entirely a local operator decision.

**Comment by alexanderbez** [comment]
Proposal:

1. Add new `hash: bool` field to the `Event` type.
2. The application will contain a consensus parameter that is a list of all events that are to be hashed in the header.

This way,

1. networks can perform parameter change proposals to update this list as new events are added
2. allows networks to avoid having to do hard-forks
3. events can still be added at-will to the application w/o breaking anything

**Comment by marbar3778** [comment]
makes sense, thanks for the break down

**Comment by ebuchman** [comment]
I was originally thinking this would just be part of application logic, deciding which events are hashed, but bez's proposal to maintain an explicit list in the app's consensus params that can be updated by gov makes a lot of sense!

Whether or not events are indexed should remain orthogonal and local (ie. non-deterministic / non-global).

I would recommend a short ADR summarizing both this and the introduction of the `.index` field just so we have a record of decisions for the changes to the abci Event structure and how they impact applications.
