### ISSUE TITLE
cli: light cli should remember config for easy restart

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5118]
## Summary

Currently when initializing and running a light client we need to specify a set of parameters: chainID, primary, witness, trusted header height and hash:

```
tendermint light supernova -p tcp://233.123.0.140:26657 \ -w tcp://179.63.29.15:26657,tcp://144.165.223.135:26657 \ --height=10 --hash=37E9A6DD3FA25E83B22C18835401E8E56088D0D7ABC6FD99FCDC920DD76C1C57
```

When we stop and want to start again we need to specify a lot of these parameters again. If the light client already exists it would provide a lot more convenience to save the config and use `tendermint lite` to start up the light client again using these existing parameters

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
I think it would be appropriate to use the trusted store for this.

**Comment by cmwaters** [comment]
so the trusted store contains provider info as well?

**Comment by melekes** [comment]
yeah

**Comment by cmwaters** [comment]
If we are storing provider then we will also need to extend the provider interface as well as the store interface such that the provider can be encoded and decoded into bytes and the store will need to be able to save and retrieve providers. Are you okay with that @melekes?

**Comment by melekes** [comment]
> If we are storing provider then we will also need to extend the provider interface as well as the store interface such that the provider can be encoded and decoded into bytes and the store will need to be able to save and retrieve providers. Are you okay with that @melekes?

yep

**Comment by cmwaters** [comment]
So an attempt at implementing a feature to store the provider to the light clients db proved futile because it is an interface and even if we can convert it to bytes, we need to use a concrete type to be able to know how to decode it back to the go native type it was beforehand. It could be plausible to do this but we'd need a db implementation for each implementation of the provider (so far this is two - the mock provider and the http provider). The other path we could take is to save the ip addresses of the providers as a config file for the the light client and then parse these into http providers automatically on start up. However the functionality of storing providers is then only useful when using the http provider and the cli. doesn't scale to ibc. 

If we are to step back a little and examine it at a higher level, one thing that I have noticed (and perhaps also anton) is that the light client has two different components - the first is all the verification related code (including evidence handling and storing of headers). The second is all the rpc provider handling (how to deal with non responsive providers, or faulty providers). Currently a lot of the provider handling is built into the light client but in many cases we didn't want to get lost in the details of making a robust light client system. Because of this, it may beg the question about whether it may be suitable to extract these into two different systems, one for the core verification and the other for provider handling. Doing so would provide easier modularity if someone wanted to code their own (perhaps more complicated) system for finding and managing rpc connections or make it easier if we wanted to - in the future - add p2p support for the light client.

Perhaps this isn't really something we need to address and can find a solution for saving providers without delving into any restructuring or perhaps we feel that we want to drop this issue of saving providers entirely.

**Comment by melekes** [comment]
> we need to use a concrete type to be able to know how to decode it back to the go native type it was beforehand

I would save it along with bytes. For example: {"http.Provider", "http://cosmos-station:26657"} or {"mock.Provider", "all the bytes}, where "http.Provider" is `fmt.Sprintf("%T", p)`.

> If we are to step back a little and examine it at a higher level, one thing that I have noticed (and perhaps also anton) is that the light client has two different components - the first is all the verification related code (including evidence handling and storing of headers). The second is all the rpc provider handling (how to deal with non responsive providers, or faulty providers).

Thought about it too. Extracting the retry functionality should help us de clatter the client.go. It can be a wrapper around the provider with configurable timeout and retry numbers.

**Comment by cmwaters** [comment]
so I could save the type? (i.e. mock.Provider) then how could I use it to decode the bytes?

```
provider = &mock.Provider{}

provider.Unmarshal(providerBytes []byte)
```

**Comment by melekes** [comment]
> so I could save the type? (i.e. mock.Provider) then how could I use it to decode the bytes?
> 
> ```
> provider = &mock.Provider{}
> 
> provider.Unmarshal(providerBytes []byte)
> ```

using reflect package
