### ISSUE TITLE
abci: Clarify new Event.index field

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5125]
So #4466 introduced an abci EventAttribute type to replace the old KVPair and added a new index field to support run-time changes to what we index.

It should be clarified in the proto file that this is a non-deterministic / subjective field (eg. like .info and .log in the responses). At least that's my understanding of this field.

Also, how does it interact with the indexing configuration settings? Is it still possible to turn off all indexing, even if events are firing with index=true?

Docs also need to be updated for this change cc - https://github.com/tendermint/spec/pull/101/files#r455488807

**Comment by alexanderbez** [comment]
If I'm not mistaken, indexing is 100% controlled by the application -- the only exceptions are, Tendermint events are always indexed.

**Comment by melekes** [comment]
> Also, how does it interact with the indexing configuration settings? Is it still possible to turn off all indexing, even if events are firing with index=true?

Yes, the node's operator can turn off indexing completely by setting `tx_index` to `null`.
