### ISSUE TITLE
Removing a peer should be recorded to inform later decisions

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#513]
When the blockchain pool has to remove a peer from its pool due to the peer failing to provide a block, the corresponding peer is removed and ideally that removal should be recorded for future use. https://github.com/tendermint/tendermint/blob/develop/blockchain/pool.go#L197

**Comment by melekes** [comment]
What is the meaning of "record"? log? https://github.com/tendermint/tendermint/blob/267f134d44e76efb2adef5f0c993da8a5d5bd1b8/blockchain/reactor.go#L234

**Comment by adrianbrink** [comment]
I mean that we maybe have a time-stamped array of peers that misbehaved with exponential timeouts for each peer. 
So, the first time a peer misbehaves we don't talk to them for 5 minutes, the 2nd time we ignore them for 25 minutes and so on.

**Comment by ebuchman** [comment]
This should be covered by https://github.com/tendermint/tendermint/issues/867
