### ISSUE TITLE
Return abci.Event instead of ResultEvent for event subscription

### ISSUE THREAD

**Issue by colin-axner** [tendermint/tendermint#5133]
## Summary

When subscribing to events (say as a relayer), I'd like the events to be returned as the `abci.Event` rather than a [`ResultEvent`](https://github.com/tendermint/tendermint/blob/5223cbac276485526200caf97fe71508f346edca/rpc/core/types/responses.go#L231). This will maintain event context on order of emission resulting in easier event parsing.

## Problem Definition

From a IBC relayer perspective we want a way to deterministically map txs and their events. 

The golang relayer is [subscribing](https://github.com/tendermint/tendermint/blob/5223cbac276485526200caf97fe71508f346edca/light/rpc/client.go#L485) to the tendermint rpc client which is returning [result events](https://github.com/tendermint/tendermint/blob/5223cbac276485526200caf97fe71508f346edca/rpc/core/types/responses.go#L231). This returns the events as a map[string][]string. 

From what I can tell this is resulting in events looking like this:
`"message.action":["update_client","channel_open_confirm"].` 

To parse events in a Tx precisely you either need to know the ordering or exactly what events each tx emitted. In the SDK, a message type with an action attribute is emitted for every msg run through baseapp (marking where a msg begins and ends), but TM is combining event type/attribute keys causing the ordering to be lost. 

Ideally one would be able to split the events in a Tx by some event marker emitted by the application (in this case message.action) which would be possible if the events were returned as `abci.Events` in the order they were emitted from the connected application. 

## Proposal

Allow for subscriptions to be for abci.Events rather than the internal representation of the events. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by colin-axner** [comment]
Thinking about this some more, from the relayer perspective this issue can be worked around without too much overhead. I think it'd still be a useful feature to be supported by tendermint at some point, but it can be low priority and doesn't need to be included in any upcoming releases.

**Comment by ethanfrey** [comment]
This seems to be related to/the cause of my bug here: https://github.com/cosmos/cosmos-sdk/issues/8419

It seems this Tendermint manges the events, collapsing them into a [ResultEvent](https://github.com/tendermint/tendermint/blob/5223cbac276485526200caf97fe71508f346edca/rpc/core/types/responses.go#L231-L235):

```go
type ResultEvent struct {
	Query  string              `json:"query"`
	Data   types.TMEventData   `json:"data"`
	Events map[string][]string `json:"events"`
}
```

If we have multiple messages of the same type, all structure is lost. For example, if we move coins from A -> B and B -> C in the same transaction, we emit:

```json
[
      {
        "type": "transfer",
        "attributes": [
          {
            "key": "recipient",
            "value": "wasm178muner9x4shrdnu9xjnurlgd4qkul9t9pupcp"
          },
          {
            "key": "sender",
            "value": "wasm1eldfm7jktevnscwr6prdravd8yuq7j87q6d9vx"
          },
          {
            "key": "amount",
            "value": "4000000umayo"
          }
       ]
      },
      {
        "type": "transfer",
        "attributes": [
          {
            "key": "recipient",
            "value": "wasm1c9489dfpgpual8gwpd85xfc2tnwl6qsx8d0j80"
          },
          {
            "key": "sender",
            "value": "wasm178muner9x4shrdnu9xjnurlgd4qkul9t9pupcp"
          },
          {
            "key": "amount",
            "value": "1666666umayo"
          }
      ]
    }
]
```

but tendermint gives us:

```json
[
      {
        "type": "transfer",
        "attributes": [
          {
            "key": "recipient",
            "value": "wasm178muner9x4shrdnu9xjnurlgd4qkul9t9pupcp"
          },
          {
            "key": "sender",
            "value": "wasm1eldfm7jktevnscwr6prdravd8yuq7j87q6d9vx"
          },
          {
            "key": "amount",
            "value": "4000000umayo"
          },
          {
            "key": "recipient",
            "value": "wasm1c9489dfpgpual8gwpd85xfc2tnwl6qsx8d0j80"
          },
          {
            "key": "sender",
            "value": "wasm178muner9x4shrdnu9xjnurlgd4qkul9t9pupcp"
          },
          {
            "key": "amount",
            "value": "1666666umayo"
          }
      ]
    }
]
```

**Comment by ethanfrey** [comment]
@tessr Another point for the pending Event system refactor discussion

**Comment by tessr** [comment]
@ethanfrey thanks for tagging me in this. I'm making an events tracking issue now, so if there are other things you think I should include, please LMK.

**Comment by marbar3778** [comment]
@alexanderbez, do you still want to work on this?

**Comment by alexanderbez** [comment]
Yes, I will look into this now actually.
