### ISSUE TITLE
state: genesis state is saved multiple times

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5138]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): Master & all previous versions

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Cosmos-SDK

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac Os

**What happened**: When running `./build/.simd` height 1 & 2 get played as empty valdiator sets then played as populated validator sets.

**What you expected to happen**: On the start of Tendermint height one is run once with a populated validator set.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): add logs to the Cosmos-SDk and run the in-process tests. (Will post a better walkthrough)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: https://pastebin.com/9s2Hn1M7

**Config (you can paste only the changes you've made)**: All default configurations 

**Anything else we need to know**:

the culprit seems to be `LoadStateFromDBOrGenesisDoc` but I am unable to pinpoint it

the bandaid I added is here: https://github.com/tendermint/tendermint/compare/marko/janky, but I don't think this would be correct as it may have downstream ripples

**Comment by alexanderbez** [comment]
Specifically, I believe `SaveState` (or some similar path) is called twice, for height 1 and 2 respectively, before `InitChain`.

e.g.

```
====saveValidatorsInfo====
height: 1
lastHeightChanged: 1
valSetCheckpointInterval: 100000
valSet: ValidatorSet{
  Proposer: nil-Validator
  Validators:
}
====saveValidatorsInfo====
height: 2
lastHeightChanged: 1
valSetCheckpointInterval: 100000
valSet: ValidatorSet{
  Proposer: nil-Validator
  Validators:
}
====saveValidatorsInfo====
height: 1
lastHeightChanged: 1
valSetCheckpointInterval: 100000
valSet: ValidatorSet{
  Proposer: Validator{436ACFDB567839E3FD4B3691ED1E3D039132794F PubKeyEd25519{1A551A255E84E05C539D6B32A8BE596D8AF8296C25054D76E4E5FAE61A149A7C} VP:100 A:0}
  Validators:
    Validator{436ACFDB567839E3FD4B3691ED1E3D039132794F PubKeyEd25519{1A551A255E84E05C539D6B32A8BE596D8AF8296C25054D76E4E5FAE61A149A7C} VP:100 A:0}
}
====saveValidatorsInfo====
height: 2
lastHeightChanged: 1
valSetCheckpointInterval: 100000
valSet: ValidatorSet{
  Proposer: Validator{436ACFDB567839E3FD4B3691ED1E3D039132794F PubKeyEd25519{1A551A255E84E05C539D6B32A8BE596D8AF8296C25054D76E4E5FAE61A149A7C} VP:100 A:0}
  Validators:
    Validator{436ACFDB567839E3FD4B3691ED1E3D039132794F PubKeyEd25519{1A551A255E84E05C539D6B32A8BE596D8AF8296C25054D76E4E5FAE61A149A7C} VP:100 A:0}
}
```

**Comment by marbar3778** [comment]
found where this is being called and its in consensus: https://github.com/tendermint/tendermint/blob/7c8c356f717ddff0441264d572da5298191e7c74/consensus/replay.go#L317-L336 to fix this it may require some changes in consensus 👀

**Comment by erikgrinaker** [comment]
The first `SaveState` call is in `LoadStateFromDBOrGenesisFile`:
https://github.com/tendermint/tendermint/blob/04b8cf7879012f446e0bee344016b1af9c1a7a17/state/store.go#L52

The second call is in `ReplayBlocks`:
https://github.com/tendermint/tendermint/blob/7c8c356f717ddff0441264d572da5298191e7c74/consensus/replay.go#L335

I guess the idea here is that when we first seed the initial block's state with data from genesis, and then replace it with the state from the application via `InitChain`, if any.

@alexanderbez Can you confirm that the test failures use a genesis file with an empty validator set?

**Comment by marbar3778** [comment]
yes the ValidatorSet in the genesis is empty. This is something I found into while testing.

**Comment by erikgrinaker** [comment]
Ok, in that case we have to decide whether we should allow genesis with empty validator sets. If so, we will have to change how we bootstrap state from genesis - one approach might be to not save the initial genesis state, but instead pass it into the node and only save it after InitChain has been called.

**Comment by marbar3778** [comment]
> Are there valid use-cases with empty genesis validator sets?

If we were to make empty genesis validator prohibited then this would break the flow for users. We don't know if a user prepopulates the genesis with validators or returns validators on InitChain.

> one approach might be to not save the initial genesis state, but instead pass it into the node and only save it after InitChain has been called.

if there are validators in the genesis and new validator in Initchain then its merely appended, correct? That does seem like the best approach. Would this be removing the saveState write from the consensus module?

**Comment by erikgrinaker** [comment]
>if there are validators in the genesis and new validator in Initchain then its merely appended, correct? That does seem like the best approach. Would this be removing the saveState write from the consensus module?

I would expect the validator set from InitChain to replace the one from genesis, not append to it. But either way, yes, we would have to remove the SaveState write in LoadStateFromDBOrGenesisFile, and change all of the code between the genesis load and the InitChain call to not rely on state loaded from the database, but instead pass the state explicitly.

**Comment by marbar3778** [comment]
> I would expect the validator set from InitChain to replace the one from genesis, not append to it.

If a chain exports at height x with validator set in the exported genesis, then if before starting the chain they add a gentx, then all validators would be overwritten by this one gentx? just asking for clarification on a possible scenario.

An alternative that I am using is to check if the validatorSet is nil or empty before calling ToProto. Then we dont add it to the struct if empty of nil. This is a simple way to do it but unclear of the downstream effects.

**Comment by erikgrinaker** [comment]
>If a chain exports at height x with validator set in the exported genesis, then if before starting the chain they add a gentx, then all validators would be overwritten by this one gentx? just asking for clarification on a possible scenario.

The current code replaces the validator set with the one returned by InitChain at height 0, if any. I don't see any reason to change this behavior. It's not clear to me how gentx affects this?

>An alternative that I am using is to check if the validatorSet is nil or empty before calling ToProto. Then we dont add it to the struct if empty of nil. This is a simple way to do it but unclear of the downstream effects.

It is unclear to me why we call `ValidateBasic()` during `ToProto` at all. The way I see it, conversion between data structure formats should be mechanistic, and not care about the semantic meaning of the data unless it violates type constraints. Semantic validation should happen separately, where appropriate.

**Comment by marbar3778** [comment]
> The current code replaces the validator set with the one returned by InitChain at height 0, if any. I don't see any reason to change this behavior. It's not clear to me how gentx affects this?

Ah ignore my comment didn't realize this was the current behavior.

> It is unclear to me why we call `ValidateBasic()` during `ToProto` at all. The way I see it, conversion between data structure formats should be mechanical, and not care about the semantic meaning of the data unless it violates type constraints. Semantic validation should happen separately, where appropriate.

Not sure where this got changed but we should only check validatebasic on from proto. I made this change in my branch for sdk testing but the toproto still fails as the validator set is nil.

**Comment by alexanderbez** [comment]
Just want to confirm, that both situations can occur. Typically, on a fresh chain, you will _not_ have a validator set as it is determined at runtime via `InitChain` -- this most common situation. However, you can also start with an exported state from an existing chain which _should_ have a validator set.

**Comment by erikgrinaker** [comment]
Can we close this now?

**Comment by marbar3778** [comment]
we can close unless we want to fix the saving flow?
