### ISSUE TITLE
Handle with a response if a peer asks for blocks that we don't have

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#514]
https://github.com/tendermint/tendermint/blob/develop/blockchain/reactor.go#L148

**Comment by melekes** [comment]
Do we have to? A peer will ask another peer, right?

**Comment by adrianbrink** [comment]
Yes, we could just drop it and expect peers to handle it. However we should send a response saying that we don't have that information.

**Comment by melekes** [comment]
Send block =`nil`?

**Comment by jaekwon** [comment]
Added comments to #540.

**Comment by zramsay** [comment]
#714
