### ISSUE TITLE
light: API should take a context

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5145]
The light client and RPC client APIs should take a context, for e.g. timeouts and cancellation. This should follow best practices as described in the [documentation](https://golang.org/pkg/context/).

**Comment by cmwaters** [comment]
Do we also want to extend taking a context to the full node RPC client?

**Comment by erikgrinaker** [comment]
Don't see why not. Isn't that what the light client uses for RPC anyway, so in order to do cancellation it would have to be propagated?

**Comment by cmwaters** [comment]
yup 👍

**Comment by melekes** [comment]
I would like to see the new API before you make the actual changes (i.e. what methods are you going to change? all? `NewClient`?).

**Comment by melekes** [comment]
```
Provider
- ReportEvidence(context.Context, ev types.Evidence)
- LightBlock(ctx context.Context, height int64)
```
