### ISSUE TITLE
Update ADR-056: Proving Amnesia attacks

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#5149]
Detecting faulty validators in the case of Amnesia attack can be done by the fork accountability mechanism described in: https://docs.google.com/document/d/11ZhMsCj3y7zIZz4udO9l25xqb0kl7gmWqNpGVRzOeyY/edit?usp=sharing. However, this procedure guarantees misbehaviour detection only in case there was a fork, i.e., it requires at least +1/3 of voting power misbehaving. Therefore, triggering expensive on chain fork detection protocol should be done only if we indeed have a proof of fork. 

There is an ongoing work (https://github.com/tendermint/tendermint/issues/5083, https://github.com/informalsystems/tendermint-rs/issues/461) on formalising the concept of proof of fork (to replace the term ConflictingHeadersEvidence from https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-047-handling-evidence-from-light-client.md), defining the corresponding data structure, protocol for its submission by the light client and the proof of fork verification function executed by the full node upon reception. This verification function will define the enabling condition for triggering on chain fork detection protocol for amnesia, i.e., we shouldn't create Amnesia evidence if we are not sure that submitted proof of fork is valid. Note that this might put a requirement on Evidence reactor for Amnesia evidence logic as full node should in principle not forward Amnesia evidence before verifying it. This might also imply that we need to gossip proof of fork (or at least subset of it that allows proof of fork recovery) between full nodes as otherwise they might not able to validate if the fork is valid or not. And this potentially opens (again) can of worms regarding individual evidence creation vs batched evidence creation. In case we can't avoid gossiping of proof of fork, we can maybe do creation of individual evidences at the latter stage, maybe only at the block proposal time, or even as part of on chain evidence processing. If done on chain, it could potentially first try to see if there are double signing and lunatic misbehaviour and only in case we are not able to create such evidence of misbehaviour, we would trigger amnesia related challenge-response protocol.

**Comment by josef-widder** [comment]
I drafted fork detection and definitions for "proof of fork" in https://github.com/informalsystems/tendermint-rs/pull/479

**Comment by tessr** [comment]
Adding @cmwaters to this issue to track/follow-up on it and make sure that ADR 56 is up-to-date.

**Comment by cmwaters** [comment]
I'm redirecting all future amnesia related work to this issue here: https://github.com/tendermint/tendermint/issues/5270
