### ISSUE TITLE
Create config.toml file upon init

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#515]
When running `tendermint init` or `basecoin init`, the TMHOME or BCHOME dir don't have a config.toml file.  It's pretty annoying to have to run `init` then `start`, then quit, just to be able to edit the config file, then `start` again.  Better to have the config file upon `init`, so it can be edited, then `start` to start.

**Comment by ebuchman** [comment]
This works on latest tendermint. I'll open on basecoin
