### ISSUE TITLE
Release Tendermint binary for Linux/ARM64

### ISSUE THREAD

**Issue by odidev** [tendermint/tendermint#5157]
Hi Team,

Currently, Tendermint releases are available for Linux/amd64 and Linux/arm. I am interested in having a Linux/ARM64 Tendermint release. I have checked that the Tendermint package supports arm64. I have followed the installation process given here : <https://github.com/tendermint/tendermint/blob/master/docs/introduction/install.md>

I followed below steps for building linux/ARM64 binary :

$ echo export GOPATH=\"\$HOME/go\" >> ~/.bash_profile
$ echo export PATH=\"\$PATH:\$GOPATH/bin\" >> ~/.bash_profile
$ echo export GO111MODULE=on >> ~/.bash_profile
$ git clone https://github.com/tendermint/tendermint.git
$ cd tendermint
$ make tools
$ make install
$ make build

Here is the output of “file tendermint” : 

```
root@77387aa9d81d:/odidev/tendermint/build# file tendermint
tendermint: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, Go BuildID=2Ilhzqwm_kYAMcdpDMcL/p9QMDngfbkqmZsZZPvBN/JHWY-UVDdfy3oS0TOlec/R6JGFkvgq4OgkXhoX7YZ, stripped
```

I am able to generate a ‘tendermint’ binary inside the ".build/” folder.
I am working on adding arm64 support to BigChainDB which is dependent on Tendermint, So it will be very helpful if the Tendermint binaries are available for the Linux/ARM64 platform.
Please share your opinion on this.

**Comment by marbar3778** [comment]
thank you for opening this issue. I dont see a reason why we cant do this. It should merely be adding a one liner to CI release process. We will not be able to provide binaries for previous releases, thought.
