### ISSUE TITLE
docs: evidence(s) sent to app

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5175]
## Summary

In Tendermint we have 5+ different types of evidence. Not all are reported to the application. we should document which ones are and why. A simple example of why an application may want to handle x type of evidence would be helpful as well

**Comment by cmwaters** [comment]
I agree that giving some guidance on how applications should deal with this stuff would be helpful

Once phantom validator evidence is removed there will only be three types of evidence that can be committed onto the chain and reported to the application: duplicateVote, amnesia and lunatic. 

Where do you think this document should reside?

**Comment by marbar3778** [comment]
we can put in this dir https://github.com/tendermint/tendermint/blob/aaa060fda4e3a564a32f1ba81f05cea93f6e34ce/docs/app-dev for now. We need to do a docs overhaul the flow is weird

**Comment by cmwaters** [comment]
Does that automatically get updated to the docs website? 

> We need to do a docs overhaul the flow is weird

I tend to agree. I feel it's mostly because a lot of the stuff is in the spec

**Comment by marbar3778** [comment]
> Does that automatically get updated to the docs website?

yes
