### ISSUE TITLE
starting a Cosmos-SDK chain stops on first try

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5178]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): master/v0.34-rc2

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Cosmos-SDk

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac Os (latest
- **Install tools**:
- **Others**:

**What happened**: When starting Simapp from the Cosmos-SDK I would observe all reactors start but unable to produce blocks. When I stop and then restart the chain it begins as normal. 

**What you expected to happen**: Start from the first try

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): 

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

first try: https://pastebin.com/UY8aXUdL
second try (restart): https://pastebin.com/zV2AWP5S

**Config (you can paste only the changes you've made)**: Default

**node command runtime flags**: none

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

present on all versions of fast-sync

**Comment by melekes** [comment]
Could you provide debug level logs as well? And maybe goroutine list dump? https://medium.com/tendermint/rule-76-no-excuses-debug-like-a-champion-8ef42fc52786

**Comment by marbar3778** [comment]
debug logs are in the paste bin above, do you want more logs than that?
