### ISSUE TITLE
Hash genesis file into first block

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5183]
Currently, individual fields in the genesis file are propagated separately into the genesis block (e.g. the validator set and consensus params are hashed, and the chain ID is copied in). However, some fields are not fully handled (e.g. app hash, see #5177), and the file in its entirety is not checked.

This is problematic if we want to add additional fields that aren't hashed (see discussion in https://github.com/tendermint/spec/pull/119#pullrequestreview-457226355), and can cause user confusion (see `--genesis_hash` which was added in https://github.com/tendermint/tendermint/issues/4113).

We should somehow make sure the genesis file is identical for all nodes in a network, e.g. by including a hash of the file in the genesis block, or via some other mechanism.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
Not sure I understand this - shouldn't everything in the genesis make it's way into a hash, now that we return the AppHash in ResponseInitChain?

If this is about adding a predecessor block to the genesis, maybe that should be referenced as the LastBlock in the new first block in the chain? Or is it going to be weird for the first block in the chain to have a predecessor (it makes sense from a continuous chain perspective, so maybe worth adapting Tendermint to it).

What are some alternatives? We could stick the genesis hash in some LastXXX field in the header? Or make the genesis file or its hash the first tx in the first block?

**Comment by erikgrinaker** [comment]
Yes, I believe everything is currently hashed separately into the genesis block. The idea here was that if we wanted to add additional fields to the genesis file that aren't individually hashed (consider something trivial like a website address), or a user wants to verify that they're using the correct genesis file, then having it hashed into the genesis block might be useful. #4113 outlines some practical implications of users struggling with the wrong genesis files, and `--genesis_hash` feels a bit bolted-on.

This really hasn't been thought through to any extent though, and we probably want more concrete use-cases before doing anything about it.
