### ISSUE TITLE
light: proposal for light client modularity

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5186]
## Summary

On the whole, I am quite happy with the light client functionality as it stands. However, if I were to tweak the system, which could be a possibility down the road, for better modularity, I would encourage the following setup.

## Proposal

![lightclient](https://user-images.githubusercontent.com/27455974/89026146-7434ee80-d328-11ea-8d75-ff67f3c6cedb.png)

Probably the biggest change up this would involve would be to split out the provider handling aspects of the light client. This would mean that the provider handling would manage all networking aspects with other nodes (dropouts, discovery etc..) and all the light client would be worried about was retrieving the signed headers and validator sets for verification. The reason for having modularity here, is that someone can easily replace the module with providers that have more advanced features or use different network protocols (i.e. this would allow for easy integration of a p2p provider handler).

At the moment, we sort of tie verification and detection together. However, I have noticed that the tendermint-rs team make more of a distinction between verification (i.e. the actual bisection or sequential processes) and then detection (which is taking the signed header and comparing with other witnesses and if there are conflicting headers managing this appropriately). In this case the verification module can be use in other areas such as fast sync and the detector could be used possibly in the future as it's own reactor bootstrapped to a full node. Or another case is that you might not want to use a detector at all and feel comfortable enough with the guarantees of just the verification module.

The last module, the store, already exists with an interface, so no need to talk too much about that, but this allows for different DB's to be used. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
I am for this!! 

Previously in the lite package, there was a bit of separation and it allowed Users to use some functions for verification. This was removed in 0.34 and caused the SDK to have to remove a feature for verification.

**Comment by cmwaters** [comment]
**UPDATE:** After implementation of the detector and the transition to using light blocks, the only outstanding work with this proposal would be the development of a handler. This is probably the least important component of the light client but could lead to greater robustness. The handler would be in charge of managing dropouts and other errors, replacing providers, keeping an address book, blacklist/whitelist and perhaps even provider discovery.
