### ISSUE TITLE
Merkle tree is not compatible with rfc6962 for empty sets

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5192]
@liamsi discovered that our Merkle tree implementation which is supposed to be compatible with RFC6962 diverges for empty tress. This is true for both Go and Rust, which are also currently incompatible with eachother - https://github.com/informalsystems/tendermint-rs/issues/498

According to RFC6962, empty trees should use the hash of the empty string as their root, while in Tendermint we just use the empty string.

This means eg. blocks with no transactions have an empty value for the DataHash in the header. One possible benefit of this is that it means empty blocks have smaller headers, which is nice, but it's not clear that benefit is worth diverging from the spec.

The only hashes in the header that this would really effect are the DataHash and the EvidenceHash, which are both often empty. So this change would make Headers 64 bytes bigger for empty blocks, 32 bytes bigger for blocks with transactions, and the same size as blocks with transactions and evidence. Of course we might be able to remove the evidence hash down the road circa #2530 

We might want to consider fixing this for v0.34 ...

**Comment by erikgrinaker** [comment]
I agree, we should get this in for 0.34.

**Comment by ValarDragon** [comment]
Completely agreed re fixing this to be spec compliant. Thanks for catching this @liamsi!
The evidence hash size increase being handled by a https://github.com/tendermint/tendermint/issues/2530 esque approach is better anyway imo.

**Comment by erikgrinaker** [comment]
@alexanderbez The SDK and IAVL should possibly change its hash algos to follow this behavior as well, what do you think?

**Comment by alexanderbez** [comment]
The IAVL library for certain, yes. It is unclear to me if there will be any necessary changes needed to the Cosmos SDK.

**Comment by erikgrinaker** [comment]
>It is unclear to me if there will be any necessary changes needed to the Cosmos SDK.

I think you copied some hashing code from Tendermint into the SDK that may need to be updated: the stuff to combine the root multistore hashes into a single Merkle tree.
