### ISSUE TITLE
Unable to create a built-in application in Go

### ISSUE THREAD

**Issue by iHarishKumar** [tendermint/tendermint#5194]
I've installed Tendermint Core as discussed here: https://docs.tendermint.com/master/introduction/install.html

Created the main.go and app.go files as discussed here: https://docs.tendermint.com/master/guides/go-built-in.html
In main.go file, I've replaced the line `app := NewKVStoreApplication(db)` with `app := NewKVStoreApplication()` as it was throwing error stating `invalid number of arguments`.

Once these files are in place, following the below commands in sequence for getting the tendermint up and running.
> $ go mod init github.com/me/example
$ go build
$ rm -rf /tmp/example
$ TMHOME="/tmp/example" tendermint init
$ ./example -config "/tmp/example/config/config.toml"

When I execute the last command, it gives me the error (attached file [err.txt](https://github.com/tendermint/tendermint/files/5012238/err.txt)).
But it will still be able to continue forward.
Operating System: OSx (10.15.5)

Let me know if you need more information. Thanks for the help.

**Comment by marbar3778** [comment]
it seems you are describing the same issue in #5195. Let's close this issue and continue discussions there.

**Comment by iHarishKumar** [comment]
Hi @marbar3778,

The issue which is mentioned here is different from the issue which is mentioned in #5195 
Could you please take a look at the logs once?

Thanks,
Harish

**Comment by marbar3778** [comment]
could you post the logs in a paste bin as outlined in the bug issue template. What app are you building tendermint with & What version of tendermint?

**Comment by iHarishKumar** [comment]
You can find the logs here: https://github.com/tendermint/tendermint/files/5012238/err.txt
I'm trying to build the kvstore app as outlined in the official doc page.
The tendermint version is: **0.34.0-185cd5b8**
