### ISSUE TITLE
Tendermint fails with invalid character error while starting.

### ISSUE THREAD

**Issue by iHarishKumar** [tendermint/tendermint#5195]
I've installed Tendermint Core as discussed here: https://docs.tendermint.com/master/introduction/install.html

Created the main.go and app.go files as discussed here: https://docs.tendermint.com/master/guides/go-built-in.html
In main.go file, I've replaced the line `app := NewKVStoreApplication(db)` with `app := NewKVStoreApplication()` as it was throwing error stating invalid number of arguments.

Once these files are in place, following the below commands in sequence for getting the tendermint up and running.

>$ go mod init github.com/me/example
$ go build
$ rm -rf /tmp/example
$ TMHOME="/tmp/example" tendermint init
$ ./example -config "/tmp/example/config/config.toml"

When I execute the last command, it gives me the following error.
> badger 2020/08/02 18:41:42 INFO: All 0 tables opened in 0s
badger 2020/08/02 18:41:42 INFO: Replaying file id: 0 at offset: 0
badger 2020/08/02 18:41:42 INFO: Replay took: 12.665µs
badger 2020/08/02 18:41:42 DEBUG: Value log discard stats empty
Error reading PrivValidator state from /tmp/example/data/priv_validator_state.json: invalid character -- Amino:JSON int/int64/uint/uint64 expects quoted values for javascript numeric support, got: 0.

Operating System: OSx (10.15.5)

Let me know if you need more information. Thanks for the help.

**Comment by marbar3778** [comment]
Thank you for opening this issue! Could you let me know what version of Tendermint you are using?

**Comment by iHarishKumar** [comment]
Hi @marbar3778,

I've followed the installation instructions which were present in the official doc page which I've mentioned earlier.
So, I guess it is taking a master branch.

Thanks,
Harish

**Comment by marbar3778** [comment]
> Hi @marbar3778,
> 
> I've followed the installation instructions which were present in the official doc page which I've mentioned earlier.
> So, I guess it is taking a master branch.
> 
> Thanks,
> Harish

thank you, I was asking around the version of Tendermint you are running? It seems you are running a javascript ABCI application. Is this the js-abci?

**Comment by iHarishKumar** [comment]
Sorry about that, I'm using **0.34.0-185cd5b8** version.

**Comment by erikgrinaker** [comment]
Thank you for reporting. The `master` branch currently contains a lot of breaking changes for our upcoming 0.34 release, while most of the documentation refers to the latest stable release 0.33.8. I suggest you use this version until 0.34 is released, and we will make sure the documentation is updated before then (see #5229 for this).

**Comment by iHarishKumar** [comment]
Hi @erikgrinaker , I tried with version **0.33.8-1a8e42d4** from the github(v0.33) and still keep getting error as attached. Not sure why this is happening. 
> badger 2020/08/16 18:22:49 INFO: All 0 tables opened in 0s
E[2020-08-16|18:22:49.308] Error on catchup replay. Proceeding to start State anyway module=consensus err="wal should not contain #ENDHEIGHT 1"
E[2020-08-16|18:22:49.308] Failed to save AddrBook to file              module=p2p book=config/addrbook.json file=config/addrbook.json err="open config/write-file-atomic-08118884421143796897: no such file or directory"
E[2020-08-16|18:22:50.367] CONSENSUS FAILURE!!!                         module=consensus err="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 82 [running]:\nruntime/debug.Stack(0xc00011da40, 0x1b032e0, 0x2695c70)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc007062000, 0x1dcea48)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:617 +0x57\npanic(0x1b032e0, 0x2695c70)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/dgraph-io/badger.(*DB).newTransaction(0x0, 0x1300001, 0xc006725fc0)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/dgraph-io/badger@v1.6.1/txn.go:638 +0x26\ngithub.com/dgraph-io/badger.(*DB).NewTransaction(...)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/dgraph-io/badger@v1.6.1/txn.go:634\nmain.(*KVStoreApplication).BeginBlock(0xc0002426e0, 0xc00710e240, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/harishgunjalli/Desktop/MAXonrow/Tendermint/kvstore/app.go:117 +0x60\ngithub.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(0xc0002a6d20, 0xc00710e240, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/abci/client/local_client.go:231 +0x101\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(0xc0002c5f70, 0xc00710e240, 0x20, 0x20, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0, ...)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/proxy/app_conn.go:69 +0x6b\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp(0x1f213a0, 0xc0002929a0, 0x1f2af00, 0xc0002c5f70, 0xc006c22a80, 0x1f31de0, 0xc0002585b8, 0x6, 0xc000037080, 0x11)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/state/execution.go:284 +0x3e1\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc0000d6310, 0xa, 0x0, 0xc000039510, 0x6, 0xc000037080, 0x11, 0x0, 0x0, 0x0, ...)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/state/execution.go:135 +0x17a\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc007062000, 0x1)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:1459 +0x8f5\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc007062000, 0x1)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:1377 +0x383\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1(0xc007062000, 0x0, 0x1)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:1312 +0x90\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc007062000, 0x1, 0x0)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:1349 +0x61a\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc007062000, 0xc000178d20, 0x0, 0x0, 0xda6ffa65, 0xe150d12a91ed7aed, 0xc00011fac0)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:1891 +0xa39\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc007062000, 0xc000178d20, 0x0, 0x0, 0x8, 0xc00011fad0, 0x107e7cd)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:1707 +0x67\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc007062000, 0x1f03700, 0xc00029a390, 0x0, 0x0)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:713 +0x252\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc007062000, 0x0)\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:664 +0x579\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/Users/harishgunjalli/go/pkg/mod/github.com/tendermint/tendermint@v0.33.8/consensus/state.go:335 +0x13a\n"
E[2020-08-16|18:24:49.310] Failed to save AddrBook to file              module=p2p book=config/addrbook.json file=config/addrbook.json err="open config/write-file-atomic-0375857585354787581: no such file or directory"
E[2020-08-16|18:26:49.305] Failed to save AddrBook to file              module=p2p book=config/addrbook.json file=config/addrbook.json err="open config/write-file-atomic-5551357184234016726: no such file or directory"
E[2020-08-16|18:28:49.307] Failed to save AddrBook to file              module=p2p book=config/addrbook.json file=config/addrbook.json err="open config/write-file-atomic-0241529210802719763: no such file or directory"
E[2020-08-16|18:30:49.304] Failed to save AddrBook to file              module=p2p book=config/addrbook.json file=config/addrbook.json err="open config/write-file-atomic-5000734903687001336: no such file or directory"

**Comment by manxiaqu** [comment]
Facing same error of `E[2020-08-16|18:22:49.308] Failed to save AddrBook to file module=p2p book=config/addrbook.json file=config/addrbook.json err="open config/write-file-atomic-08118884421143796897: no such file or directory"`.

**Comment by marbar3778** [comment]
> badger 2020/08/02 18:41:42 INFO: All 0 tables opened in 0s
badger 2020/08/02 18:41:42 INFO: Replaying file id: 0 at offset: 0
badger 2020/08/02 18:41:42 INFO: Replay took: 12.665µs
badger 2020/08/02 18:41:42 DEBUG: Value log discard stats empty
Error reading PrivValidator state from /tmp/example/data/priv_validator_state.json: invalid character -- Amino:JSON int/int64/uint/uint64 expects quoted values for javascript numeric support, got: 0.

This error is because in 0.34 we changed a number in JSON from string to number (without quotes).  Your priv_validator_state.json is generated with 0.34 but the tendermint version you are running seems to still expect the old version. 

this is happening because in your go.mod you are using 0.33.x but you have 0.34 installed. If you install the same version as what is your go.mod this error will not persist.
