### ISSUE TITLE
Config for starting from latest block when Tendermint restart

### ISSUE THREAD

**Issue by romakingwolf** [tendermint/tendermint#5197]
When Tendermint restart, it will rerun InitChain and every block.

<img width="951" alt="screenshot01" src="https://user-images.githubusercontent.com/11656968/89167473-0994e480-d5ae-11ea-8033-afdc94acecea.png">

Can i config Tendermint to start from latest block when restart ?

**Comment by erikgrinaker** [comment]
The `kvstore` application is a _non-persistent_ application, meaning it loses all state on exit. Try the `persistent_kvstore` application instead, which saves its state to disk and resumes on restart.
