### ISSUE TITLE
Adding support for OR queries for WS subscriptions 

### ISSUE THREAD

**Issue by amanusk** [tendermint/tendermint#5206]
## Summary

The RPC `subscribe` end points only supports AND in queries. Listening to more than one event thus requires to open several listeners. An OR in queries would allow for more flexibility.  

## Problem Definition

As described in the [RPC doc](https://docs.tendermint.com/master/rpc/#/Websocket/subscribe), when subscribing to events, only the "AND" keyword can be used in queries. 
This requires opening additional listeners for more complex queries.

If, for example, I would like to listen for incoming transactions on 5 addresses, I must use 5 listeners.
Since the node is by default limited to 5 connections per client, I cannot listen to more than 5 addresses.

Adding an OR to the query would not use up all my 5 connection, while allowing to listen on multiple incoming transactions at once.

Example for query:
`tm.event=Tx AND transfer.recipient=<Address1> OR transfer.recipient=<Address2> ...`

## Proposal

Add and OR option to the queries, and possible some sort to parentheses, to sort precedence. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by assafmo** [comment]
I'm alao interested in this. 

Related: https://stackoverflow.com/questions/65709248/how-to-use-an-or-condition-with-the-tendermint-websocket-subscribe-method

**Comment by marbar3778** [comment]
In 0.35 we will support psql, if you would like larger feature set, please use postgres instead of the native indexer. 

reopen if we still want to add this into the internal indexer.

**Comment by Freak12Techno** [comment]
@marbar3778 are there any guides on using psql with WebSocket and /subscribe in 0.35?

**Comment by alexanderbez** [comment]
Websockets are used for subscribing to _live_ events. Sinks, e.g. `psql` and `kvstore` are used to _index_ events.

**Comment by xloem** [comment]
This issue is about websocket subscriptions. It was closed offering that the functionality could be available if the psql indexer was used. Is this incorrect? Was it closed in error?
