### ISSUE TITLE
evidence: move `VerifyEvidence` to evidence module

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5208]
## Problem Definition

Currently `VerifyEvidence` resides in the state package. What this means is that we have three different areas where verification of evidence occurs: types/evidence.go, state/verification.go and evidence/pool.go. This makes it more difficult for developers to follow/understand, makes the code a little messy and potentially increases the amount of tests we have.

## Proposal

I propose moving `VerifyEvidence` and all its corresponding code / tests to the evidence module. That way we can simplify the evidence interface in the `BlockExecutor` and the `verifyBlock` code will only need:

```
for _, ev := range block.Evidence.Evidence {
       err := evpool.VerifyEvidence(ev)
}
```
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
Totally, this should go in `evidence`, and probably be renamed as `evidence.Verify()` or something similar.

**Comment by marbar3778** [comment]
the cheery on top of this change could be the decoupling of specific types of evidence in the `verifyEvidence` function. One way to do this would be adding a verify function to the Evidence interface and pass the state and blockstore (very generlized), Verify(dbm.DB, store.BlockStore). And verify evidence just calls evidence.Verify. I think this goes into what erik was suggesting with the rename to `evidence.Verify`
