### ISSUE TITLE
state: metamorphose into a state store

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5213]
## Summary

In most other modules, db's are wrapped in either a store (i.e. blockstore or lightstore) or a pool (evidence pool or mempool), however for state we don't have a store and so instead of using methods we have functions which take a db and perhaps other arguments and performs an action. I'm not sure if there is a good reason for doing it this way but if not then for the sake of consistency and to make it easier to create interfaces of the stateDB then I would suggest extracting these functions into a store.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
I am for this change.

**Comment by erikgrinaker** [comment]
I would also argue that most components shouldn't need to touch the state store at all, but should be given a state and return an updated state. The consensus reactor and node would probably be the main components that need to read/write to the store directly.
