### ISSUE TITLE
evidence: light client can use genesis state as trusted state

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5228]
## Summary

This issue tags onto the discussion opened [here](https://github.com/tendermint/spec/issues/131)

## Problem Definition

I can see this being useful predominantly for testnets where we want to initiate light clients and full nodes from genesis

## Proposal

As suggested, the best way to implement this is likely to get the first header from the primary and validate it against the genesis validator set and then start from there as the trusted header

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
@erikgrinaker do you think state sync would benefit from this? Users could just use the genesis (therefore same sort of input as fast sync) and thus wouldn't have to find a trusted height and hash to start the light client.

If the trust level was at 2/3, I believe this would provide the same security as fast sync

**Comment by erikgrinaker** [comment]
Would be great if that was the case. But hasn't there been discussions about using light client verification for fast sync, since the current model isn't safe?

I don't know the finer points of light client security, but I believe we recommend users use a trusted height that is less than the unbonding period away from the snapshot height. Won't genesis be way outside of this window, and thus vulnerable to certain attacks?

**Comment by cmwaters** [comment]
> But hasn't there been discussions about using light client verification for fast sync, since the current model isn't safe?

Yup but I believe this is more for efficiency. Currently when a node receives a bad request it drops two peers when only one of them might have been faulty. Oh and also the cross verification part. But other than that the verification methods are already basically the same.

The trusted height being within the unbonding period / trust period is there so that light clients have a means of punishing bad behaving nodes. It changes nothing of the detection method nor how difficult/likely it is for nodes to fool light clients. 

Put a different way: If at anypoint in the chain's history there was 2/3 in control then they could also fool full nodes fast syncing to follow a fork. So in this way the level of security would be the same.

**Comment by erikgrinaker** [comment]
Cool, if we could use bisection to quickly validate from genesis to the snapshot height then that would be much more convenient than having to find the trusted height and hash. It would still require operators to obtain a valid genesis, since that'll be the root of trust, but they'll need that anyway.

**Comment by cmwaters** [comment]
> It would still require operators to obtain a valid genesis

Yeah I guess that's the problem for all nodes. But at least now different start up methods have a common root of trust.

I guess we could consider keeping the trusted height and hash as an option that some node runners could exercise (it would make it slightly quicker depending on how long the chain is). I was also thinking that if a node runner was capable of finding a trusted header and height why not find one that corresponded to a snapshot height. Then we wouldn't even need the light client.

**Comment by erikgrinaker** [comment]
Yup, I think in an ideal world the snapshot metadata would be subject to consensus and committed on-chain, controlled by a consensus parameter. Then state syncing could be more or less automatic.

**Comment by alexanderbez** [comment]
I think there a few pros/cons to having snapshot and it's corresponding metadata reside on-chain, the primary being we may not want to enforce all operators and nodes to abide by a certain snapshotting configuration.

**Comment by cmwaters** [comment]
I don't believe we've got an issue for this so I've created one here: https://github.com/tendermint/tendermint/issues/5761
