### ISSUE TITLE
docs: update for 0.34

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5229]
There's still a lot of documentation that's incompatible with `master` (see e.g. #5195), we'll need to publish updated documentation once 0.34 is released.

**Comment by marbar3778** [comment]
Putting some notes on areas to fix:

- update tutorials
- state-sync section in tendermint-core
- block pruning
- non-zero genesis height

I will add things in as I go through more of the docs

**Comment by marbar3778** [comment]
Looking through the docs everything is updated other than the spec. That is being worked in the spec repo. We can close this issue.
