### ISSUE TITLE
Adding validators to localnet

### ISSUE THREAD

**Issue by Anjana-Prabhakar** [tendermint/tendermint#5235]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.32.8-759ccebe

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore
**Environment**:
- **OS** (e.g. from /etc/os-release): NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
- **Install tools**: prometheues
- **Others**:

**What happened**:
I used the command `localnet-start: localnet-stop
	@if ! [ -f build/node0/config/genesis.json ]; then docker run --rm -v $(CURDIR)/build:/tendermint:Z tendermint/localnode testnet --v 5 --n 3 --o . --populate-persistent-peers --starting-ip-address 192.167.10.2 ; fi
	docker-compose up`
to modify the no: of validators. But it gives an error `localnet-start:: command not found`

**What you expected to happen**:
The validators would be created to the testnet.

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible): 
https://docs.tendermint.com/master/networks/docker-compose.html

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
Thanks for opening an issue. I checked out `759ccebe` and when running `make localnet-start` it starts running a network:
```
tendermint on  HEAD (759cceb) via 🐹 v1.14.7 took 3s 
❯ make localnet-start
docker-compose down
Removing network tendermint_localnet
WARNING: Network tendermint_localnet not found.
docker build --tag tendermint/localnode localnode
```

It seems you are trying to run localnet-start as a cmd instead of a make command. is this correct?

**Comment by Anjana-Prabhakar** [comment]
Yes. I gave the command `localnet-start: localnet-stop @if ! [ -f build/node0/config/genesis.json ]; then docker run --rm -v $(CURDIR)/build:/tendermint:Z tendermint/localnode testnet --v 5 --n 3 --o . --populate-persistent-peers --starting-ip-address 192.167.10.2 ; fi docker-compose up` in cmd for adding validator. However to run the testnet I was using the command `make localnet-start`. Should I give it as `make localnet-start: localnet-stop @if...` instead?

**Comment by marbar3778** [comment]
yes please give that a try.

**Comment by Anjana-Prabhakar** [comment]
I get an error `make: *** No rule to make target 'localnet-start:'. Stop.`

**Comment by erikgrinaker** [comment]
This is `make` syntax, not shell syntax, so the shell is not able to execute it.

The easiest is to modify the `Makefile` and then run:

```sh
$ rm -rf build/node*; make build-linux && make localnet-start
```

If you really want to do it manually, run something like the following:

```sh
$ rm -rf build/node*
$ make build-linux
$ (cd networks/local && make)
$ docker run --rm -v ./build:/tendermint:Z tendermint/localnode testnet --v 5 --n 3 --o . --populate-persistent-peers --starting-ip-address 192.167.10.2
$ docker-compose up
```

**Comment by marbar3778** [comment]
The command you should be changing is in the [makefile](https://github.com/tendermint/tendermint/blob/master/Makefile#L219-L222). the command will generate configs for 8 nodes but only run 4 because that is how many nodes are in the docker-compose file. you must also add more nodes to the docker compose

**Comment by Anjana-Prabhakar** [comment]
Thank you @erikgrinaker and @marbar3778 . I made changes to makefile and docker-compose.yml and successfully created new validators.
