### ISSUE TITLE
fix rpc/swagger/swagger.yml

### ISSUE THREAD

**Issue by ilgooz** [tendermint/tendermint#5251]
**Tendermint version**: v.33.7

**Environment**:
- **OS** (e.g. from /etc/os-release) :Debian GNU/Linux 10

**What happened**:
**1-**

Swagger Editor gives errors for https://raw.githubusercontent.com/tendermint/tendermint/v0.33.7/rpc/swagger/swagger.yaml

**2-**
We need these errors to be fixed in order to generate client code in Go. The tool we're using to generate code also complains because of these errors and won't generate code.

I'm using https://openapi-generator.tech/ for code generation and it also gives similar errors:
```
Errors: 
	-attribute components.schemas.SyncInfo.earliest_block_hash is unexpected
	-attribute components.schemas.SyncInfo.earliest_app_hash is unexpected
	-attribute paths.'/dial_peers'(post).parameters.[Array of peers to connect to & if they should be persistent].in is not of type `string`
	-attribute paths.'/dial_seeds'(post).parameters.[Array of peers to connect to].in is not of type `string`
	-attribute components.schemas.SyncInfo.earliest_block_time is unexpected
	-attribute components.schemas.SyncInfo.earliest_block_height is unexpected
```

**What you expected to happen**:
* No errors on Swagger Editor,
* If you can also double check Go client code generation with https://openapi-generator.tech/, it would be awesome.

**Have you tried the latest version**: yes - v0.33.8

**How to reproduce it** (as minimally and precisely as possible):
**1-**
Swagger Editor: Import the yml to online editor - https://editor.swagger.io/

**2-**
openapi-generator: follow installation instructions  https://openapi-generator.tech/ and run ` openapi-generator generate -i swagger.yml -g go -o dest`

**Comment by marbar3778** [comment]
This has been fixed on master. 

We are unable to make changes to files in previous releases. What is the reason for generating code? You could use the client we have in tendermint, https://github.com/tendermint/tendermint/tree/master/rpc/jsonrpc.

**Comment by ilgooz** [comment]
Thank you!

* Master also has a bug:
![image](https://user-images.githubusercontent.com/6023117/90250976-ad4f8180-de45-11ea-8132-f5e092111fd1.png)

* Do you have docs for `jsonrpc` client, and is there a generated Go client for it? What I need is a statically typed generated client and data types.

**Comment by marbar3778** [comment]
> Thank you!
> 
>     * Master also has a bug:
>       ![image](https://user-images.githubusercontent.com/6023117/90250976-ad4f8180-de45-11ea-8132-f5e092111fd1.png)

saw that, I will have it fixed in a PR in a few minutes, thank you for bringing it to my attention. 

>     * Do you have docs for `jsonrpc` client, and is there a generated Go client for it? What I need is a statically typed generated client and data types.

here are some rough examples through tests https://github.com/tendermint/tendermint/blob/master/rpc/client/examples_test.go, we use to have more but not sure where they are. will try to find them and get back to you
