### ISSUE TITLE
fastsync: verify +2/3 only

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5259]
## Summary

Currently, fast_sync verifies 100% of the signatures, while this is required for consensus it is not needed for catch up. 

## Problem Definition

Fast sync is slow

## Proposal

Speed up fast sync by using `VerifyCommitLight` (only verifies +2/3 of sigs). 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
It's probably sufficient to only implement this in the v2 reactor, since v0 and v1 will be deprecated.

**Comment by marbar3778** [comment]
> It's probably sufficient to only implement this in the v2 reactor, since v0 and v1 will be deprecated.

Until v2 is defaulted we should at least do it for v0 as well, no?

**Comment by erikgrinaker** [comment]
Depends on how much work it would be.

**Comment by marbar3778** [comment]
ah, it's a one line change in all versions.

**Comment by melekes** [comment]
shouldn't we use light client for verification during fast sync?
