### ISSUE TITLE
Use epochs for validator set changes

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5260]
## Summary

Defining an interval where every n blocks allows a validator set change (as opposed to every block) is something that I have seen other block chains use that can provide performance optimizations in areas such as light client verification, the state store and possibly other areas. This could be something that we could also look to implement as having the option to change validator set every height could be seen as being unnecessary.

## Proposal 

Define an epoch number n with which validator set changes can occur.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
This is basically already under the control of the app. Is there something specific to add to Tendermint here? Maybe it's something about the light client possibly being aware that the app uses some epoch system and can take advantage of that? It's cool that the existing bisection approach is just very efficient if the val set doesnt really change for a while

**Comment by erikgrinaker** [comment]
Yeah, since bisection is logarithmic it's basically "fast" for any number of blocks. Reducing the number of blocks to consider by, say, three orders of magnitude only reduces the bisection time by about half (20 → 10 for one million blocks). It would be useful with concrete, quantitative examples of any significant optimizations we would gain from this.

Also, IBC is using epochs for e.g. chain upgrades, which could cause some term confusion.

**Comment by ValarDragon** [comment]
I think this is necessary for deterministic leader election to have fairness security guarantees under stake changes (cc #2890 - We only know about security under no stake changes at the moment)

**Comment by marbar3778** [comment]
> Is there something specific to add to Tendermint here? Maybe it's something about the light client possibly being aware that the app uses some epoch system and can take advantage of that? 

Possibly adding a consensus param that informs Tendermint of how often validator sets change. The change would consist of an addition of a `uin64` to the consensus params and changes to take advantage of this.

**Comment by alexanderbez** [comment]
But why does this need to be in Tendermint? What benefits does it have? This can entirely be up the control of the application.

**Comment by marbar3778** [comment]
> But why does this need to be in Tendermint? What benefits does it have? This can entirely be up the control of the application.

Right now Tendermint and the light client assume validator set changes are in every block even if the app has epochs. This would just notify Tendermint that there are epochs. This is mainly to aid in the light client verification.

**Comment by ValarDragon** [comment]
Concretely, it should aid lite client bisection. (There the number of headers you need to verify is related to bounding the validator set diffs between two succesively verified headers. Knowledge of an epoch change should improve the base case)

**Comment by marbar3778** [comment]
closing in favor of https://github.com/tendermint/spec/issues/260. 

this is a protocol change, should be in the spec
