### ISSUE TITLE
Question on skipping block proposer

### ISSUE THREAD

**Issue by kwunyeung** [tendermint/tendermint#5262]
On `Band Protocol` testnet, which is running with `Tendermint` `v0.33.8`, we have just seen a situation which block proposer is being skipped.

`Band` has set the default `timeout_commit` to `1.5s` in the `config.toml`. 

```
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "1.5s"
```

We accidentally updated our `timeout_commit` to `5s`. 

```
timeout_propose = "3s"
timeout_propose_delta = "500ms"
timeout_prevote = "1s"
timeout_prevote_delta = "500ms"
timeout_precommit = "1s"
timeout_precommit_delta = "500ms"
timeout_commit = "5s"
```

There are 47 active validators running the network with nearly the same voting power. Our node have been skipped as block proposers for quite some time. After I changed it back to `1.5s`, it starts proposing again. In my understanding, the proposer will be skipped if it cannot propose during the `timeout_propose` and the `timeout_commit` is to control how much time delay to commit a block by a proposer. Is there any behavioural change on the timeout values? It does looks like a way to avoid validators to slow down the network but I can't find any related information.

**Comment by ebuchman** [comment]
timeout_commit is how long you wait before starting the next height (and thus proposing the next block)

timeout_propose is how long others wait to hear a proposal after starting a new height or round.

If your timeout_commit is higher than others, especially if its greater than the timeout_commit + timeout_propose of others, you will be skipped. 

There's some more info here: https://docs.tendermint.com/master/tendermint-core/configuration.html#consensus-timeouts-explained

Let us know if/how you think that explanation can be improved!

**Comment by kwunyeung** [comment]
@ebuchman I get it. Thanks! The doc explains the parameters precisely, just the readers may not be able to imagine all possibilities in an asynchronous network.
