### ISSUE TITLE
tests: replace handwritten mocks with mockery

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5274]
## Summary

Throughout the codebase there are many handwritten mocks, this is not a problem per se. To keep consistency with other parts of the codebase we should replace handwritten mocks with generated mocks using mockery.

## Proposal

Migrate from using handwritten mocks to using mockery.

____

#### For Admin Use

- [X] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by githubsands** [comment]
@marbar3778 which mockery lib are you guys using?

**Comment by marbar3778** [comment]
Hey we use https://github.com/vektra/mockery.

**Comment by githubsands** [comment]
@marbar3778 this guy, mempool, is handwritten correct?

https://github.com/tendermint/tendermint/blob/master/mempool/mock/mempool.go

**Comment by githubsands** [comment]
For reference, needing change:

- [ ]

**Comment by marbar3778** [comment]
> @marbar3778 this guy, mempool, is handwritten correct?
> 
> [https://github.com/tendermint/tendermint/blob/master/mempool/mock/mempool.go](https://github.com/tendermint/tendermint/blob/master/mempool/mock/mempool.go?rgh-link-date=2021-02-04T16%3A52%3A58Z)

correct. In some places it won't be possible because specific cases are needed.

**Comment by githubsands** [comment]
@marbar3778 sweet thanks
