### ISSUE TITLE
proto: check for unnecessary length-prefixing

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5276]
When using Amino, we arbitrarily and unnecessarily length-prefixed certain messages. We should double-check that this hasn't carried over to the Protobuf implementation.

Note that some messages, e.g. `Proposal`, keep the length-prefixing for backwards-compatibility with hardware devices, these should be documented.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Length-prefixing is done in two places, privval and p2p. The privval prefixing is done with hardware devices in mind and p2p so other clients can know how long the message is (I can't recall the detail of the reason)

**Comment by erikgrinaker** [comment]
Yeah, so P2P uses length prefixing for message framing (there needs to be some sort of framing since it's otherwise not possible to know where one message ends and the next one begins). However, individual messages shouldn't be length-prefixed (which would e.g. cause them to be length-prefixed twice over P2P).

As you say, looks like the only messages we length-prefix are the proposal and vote, for hardware compatibility. Submitted #5283 to clarify this in the code.
