### ISSUE TITLE
statesync: invalid part set proof

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5295]
Looks like something has broken with part set proofs in consensus after state sync. After state sync, the initial block failed with:

```
simdnode3    | E[2020-08-26|15:46:53.186] Error with msg                               module=consensus height=7 round=1 peer= err="error part set invalid proof" msg="[BlockPart H:7 R:1 P:Part{#0\n  Bytes: 0A92030A0208...\n  Proof: Proof{\n    Aunts: []\n  }\n}]"
```

Then every time the node tries to propose a block afterwards, it errors with:

```
simdnode3    | E[2020-08-26|15:47:14.907] Error with msg                               module=consensus height=14 round=0 peer=9aacb715472dab88136010e28217e048ca66c5db err="error invalid proposal signature" msg="[Proposal Proposal{14/0 (B1C2C28EE5411FF5B96DF4A7A48FD45EA2FA056F9E58E76C10635C70DA0A7E1E:1:2127507B38C3, -1) 3ACECA7AB354 @ 2020-08-26T15:47:14.804815481Z}]"
simdnode3    | E[2020-08-26|15:47:15.008] Error with msg                               module=consensus height=14 round=0 peer=105b3975ab438f26109ff2ac42db2fbe88819fb4 err="error invalid proposal signature" msg="[Proposal Proposal{14/0 (B1C2C28EE5411FF5B96DF4A7A48FD45EA2FA056F9E58E76C10635C70DA0A7E1E:1:2127507B38C3, -1) 3ACECA7AB354 @ 2020-08-26T15:47:14.804815481Z}]"
simdnode3    | E[2020-08-26|15:47:15.011] Error with msg                               module=consensus height=14 round=0 peer=b4b8a0940f423732942c66cc3c79423e9ccc7338 err="error invalid proposal signature" msg="[Proposal Proposal{14/0 (B1C2C28EE5411FF5B96DF4A7A48FD45EA2FA056F9E58E76C10635C70DA0A7E1E:1:2127507B38C3, -1) 3ACECA7AB354 @ 2020-08-26T15:47:14.804815481Z}]"
```

Possibly related to #5193.

**Comment by erikgrinaker** [comment]
This seems to be caused by the state synced node being on a different proposer schedule. The state synced node has this validator set at height 134:

```
ValidatorSet{
  Proposer: Validator{DD7E9ED6404B9805F116227DB40816E1BB84A941 PubKeyEd25519{F9A66B990417D96EF341D6C572B0B076A5892862E3AF0EDE939DA26E7B4F6976} VP:100 A:-100}
  Validators:
    Validator{0F18F2D94F1E6B7C54BD1CDFFF64C8AD74535757 PubKeyEd25519{F41BAF4A97A5C7393471E2ED2FE2A880CF3469F36C7AB5AC4E2C63E5B39011C0} VP:100 A:-100}
    Validator{B6BADC5D6F189C8DC518661722F819454A306143 PubKeyEd25519{516F3A20B244B5FDE5B0E033E489A8BD3F1A53475FAF430973C60827370B84C8} VP:100 A:-100}
    Validator{DD7E9ED6404B9805F116227DB40816E1BB84A941 PubKeyEd25519{F9A66B990417D96EF341D6C572B0B076A5892862E3AF0EDE939DA26E7B4F6976} VP:100 A:-100}
    Validator{E1919BEFC945030230A3051FA65F64C12E21E43B PubKeyEd25519{7D170B2851384E189F918B35E8CEF87F548D652786D97CF932250A1FAE7156CC} VP:100 A:300}
}
```

While a "normal" node has this validator set at height 134:

```
ValidatorSet{
  Proposer: Validator{0F18F2D94F1E6B7C54BD1CDFFF64C8AD74535757 PubKeyEd25519{F41BAF4A97A5C7393471E2ED2FE2A880CF3469F36C7AB5AC4E2C63E5B39011C0} VP:100 A:-300}
  Validators:
    Validator{0F18F2D94F1E6B7C54BD1CDFFF64C8AD74535757 PubKeyEd25519{F41BAF4A97A5C7393471E2ED2FE2A880CF3469F36C7AB5AC4E2C63E5B39011C0} VP:100 A:-300}
    Validator{B6BADC5D6F189C8DC518661722F819454A306143 PubKeyEd25519{516F3A20B244B5FDE5B0E033E489A8BD3F1A53475FAF430973C60827370B84C8} VP:100 A:100}
    Validator{DD7E9ED6404B9805F116227DB40816E1BB84A941 PubKeyEd25519{F9A66B990417D96EF341D6C572B0B076A5892862E3AF0EDE939DA26E7B4F6976} VP:100 A:100}
    Validator{E1919BEFC945030230A3051FA65F64C12E21E43B PubKeyEd25519{7D170B2851384E189F918B35E8CEF87F548D652786D97CF932250A1FAE7156CC} VP:100 A:100}
}
```

Notice how the priorities (`A`) are different. The validator set of the state synced node at height 134 is equal to that used by the rest of the network at height 136, so they are two blocks out of sync.

@melekes State sync simply uses the validator set given by the light client, via `TrustedValidatorSet()`. Do you think this a problem with the light client or Protobuf handling, or rather state sync having an off-by-two error somewhere? This used to work back in May, so it's caused by changes to Tendermint since then.

**Comment by erikgrinaker** [comment]
Doing another run was off by 1 height, so it doesn't seem to be an off-by-something error in state sync. It's probably caused by `TrustedValidatorSet()` not returning the correct proposer priorities for the validator set at the given height.

**Comment by melekes** [comment]
> It's probably caused by TrustedValidatorSet() not returning the correct proposer priorities for the validator set at the given height.

TrustedValidatorSet is a proxy for `/validators` RPC endpoint, which itself calls `store#LoadValidators`.

**Comment by erikgrinaker** [comment]
> > It's probably caused by TrustedValidatorSet() not returning the correct proposer priorities for the validator set at the given height.
> 
> TrustedValidatorSet is a proxy for `/validators` RPC endpoint, which itself calls `store#LoadValidators`.

That doesn't seem to be correct. I wrote a simple script which does this:

```go
func getVals(lc *light.Client, height int64) {
	_, err := lc.VerifyHeaderAtHeight(height, time.Now())
	if err != nil {
		panic(err)
	}
	vals, _, err := lc.TrustedValidatorSet(height)
	if err != nil {
		panic(err)
	}
	fmt.Printf("vals at %v: %v\n", height, vals)
}
```

Calling it for heights 100, 99, 101 (in that order) gives the following priorities:

```
100: -300 100 100 100
99:  -300 100 100 100
101:-300 100 100 100
```

RPC for these heights gives these priorities:

```
100: 0 0 0 0
99: -100 -100 -100 300
101: -300 100 100 100
```

**Comment by erikgrinaker** [comment]
Related to #5306

**Comment by erikgrinaker** [comment]
I'm seeing these errors again with a simple `kvstore`-like application. It's unclear whether it's caused by #5298 or if there are further corner cases.

**Comment by cmwaters** [comment]
Is it the same/similar error to what you were seeing before? I guess you can run it before and after the commit to find out if it was caused by #5298

**Comment by erikgrinaker** [comment]
Yeah, same error. It's a bit fiddly to test, will dig in tomorrow.

**Comment by erikgrinaker** [comment]
@cmwaters Looks like `VerifyLightBlockAtHeight` doesn't propagate the validator priorities, I'm getting the same priorities for all heights (`-300 100 100 100`).

**Comment by cmwaters** [comment]
Seems like a later commit reverted to using `NewValidatorSet`

https://github.com/tendermint/tendermint/blob/2f4c1f60c789a6d19a328b44ae9d3a6c1c394e5c/light/provider/http/http.go#L111

**Comment by cmwaters** [comment]
perhaps it was the light block one and I just missed it. In any case I will get on to fixing it now

**Comment by cmwaters** [comment]
Added back here: https://github.com/tendermint/tendermint/pull/5308

**Comment by erikgrinaker** [comment]
>Added back here: #5308

Thanks, that fixed the proposer priorities from the light client. State sync works with Cosmos SDK `master`, but interestingly not with this other `kvstore`-like app I'm testing with, which is getting proposal signature errors. Will dig deeper.

**Comment by erikgrinaker** [comment]
Superseded by #5328.
