### ISSUE TITLE
Streamline Tendermint light client API

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#5300]
At the moment, the Tendermint light client API (in Golang) takes data structures where only some fields are actually used - this is a bit awkward for consumers such as IBC who want to avoid storing any unnecessary data, and so must construct partial data structures - if Tendermint changes which fields are required, this may cause bugs.

cc @cmwaters

**Comment by cmwaters** [comment]
I'm just trying to cement my knowledge about this. So we want to minimise the data we store on the light client for the next header we verify (as only a fraction of it is used for verification. So, for verification we would still request a full `SignedHeader` and `ValidatorSet` from the primary but after it has been verified the light client would only store a `LightHeader` like this:

```
type LightHeader struct {
    Height  int64
    Time  time.Time
    NextValidatorsHash   Hexbytes
}
```

We would still need to store the validator set for future validation, right? we don't need the entire commit, perhaps just the header hash?

I'm starting to see two roles that the light client does - just verify the header or store the header itself so we can verify other stuff from within the header (I'm thinking of the rpc that is exposed through the light client which needs stuff like the app hash and consensus hash)

**Comment by cwgoes** [comment]
> We would still need to store the validator set for future validation, right? we don't need the entire commit, perhaps just the header hash?

The API can require the validator set; we'll probably just store the hash, at least in IBC.

**Comment by melekes** [comment]
@cmwaters see https://github.com/cosmos/cosmos-sdk/issues/6736#issuecomment-663754268

**Comment by melekes** [comment]
> We would still need to store the validator set for future validation, right? we don't need the entire commit, perhaps just the header hash?

That depends on what the light client is and what needs it serves. In my mind it's okay for the light client to serve headers + commits + validator sets so the user (wallet, etc.) does not need to refetch the data from the full node(s).

> At the moment, the Tendermint light client API (in Golang) takes data structures where only some fields are actually used - this is a bit awkward for consumers such as IBC who want to avoid storing any unnecessary data, and so must construct partial data structures - if Tendermint changes which fields are required, this may cause bugs.

This is a valid concern @cwgoes. As with Tendermint or even all software, functions often take some object and only use some fields. When either object or a function changes, either of them or both can break. BUT I don't think this fact justifies creating an intermediate struct for each function! It's just not optimal solution. https://www.youtube.com/watch?v=YR5WdGrpoug I like what Rich Hickey proposed back in 2018 for Clojure, but I don't think the analogue exists for Go programming language. All that said, I don't know what we can do here at this moment.
