### ISSUE TITLE
light: provider uses `NewValidatorSet` to aggregate validators which shifts proposer priority

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5306]
## Summary

Incorrect proposer priority in light client validator sets

## Problem Definition

The light client http provider collects all individual validators and aggregates them together with `NewValidatorSet`

https://github.com/tendermint/tendermint/blob/49efd44faa21c00c324825c3a0734020032b6552/light/provider/http/http.go#L122

This calls `updateWithChangeSet` which changes the proposer priority of the individual validators in the validator set. This ended up causing errors with statesync

## Proposal

Create a validator set from the individual validators that leaves the proposer priority in tact

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
oh man, good catch 🥇
