### ISSUE TITLE
light: TLA+ verification test suite

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5322]
Informal have created a TLA+ specification for parts of the light client, which generates JSON-based test cases (block traces). We should write a Go test driver for these and add them to our test suite.

There is a prototype test driver here, written by @Shivani912: https://github.com/informalsystems/conformance-tests/blob/master/tests/lite_client_test.go

Get in touch with Andrey at Informal for details. There's an overview here: https://github.com/informalsystems/tendermint-rs/blob/andrey/mbt-lightclient/light-client/tests/support/model_based/Abstract.md
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by melekes** [comment]
@erikgrinaker are you working on this? if not, do you mind if I tackle this?

**Comment by erikgrinaker** [comment]
Go for it
