### ISSUE TITLE
state: prune ABCIResponses

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5327]
## Summary

Tendermint saves ABCIResponses in case of failure of the node. But after we call save we could prune the ABCIResponses from the database. With the introduction of block pruning this is less of a concern but as the information is still duplicated, in the indexer, we should aim to undo this.

## Problem Definition

ABCIResponses are saved in case of failure between commit and `s.Save`, but they are not pruned after we call save.

## Proposal

Prune ABCIResponses for previous block after `s.Save` is called. 

ref https://github.com/tendermint/tendermint/issues/2491#issuecomment-424927721

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
What about this comment?

>// Responses are indexed by height so they can also be loaded later to produce
>// Merkle proofs.

**Comment by marbar3778** [comment]
Not sure where we load this for Merkle proofs. I can't find it being loaded for this purpose. 

We store the same information in the blocks and the events are indexed.

**Comment by kostko** [comment]
> but as the information is still duplicated, in the indexer, we should aim to undo this.

But the indexer can be disabled? IMO any such pruning should be optional as having access to historic ABCI responses without the need for indexing is a good thing.

**Comment by marbar3778** [comment]
We got an issue for everything. Looking through the issues I found: #3533. Will close this issue in favor of that one.
