### ISSUE TITLE
Application Developer docs outdated

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#533]
The developer docs in https://github.com/tendermint/tendermint/wiki/Application-Developers are outdated. For example, Handshake is still saying

> The ABCI handshake and related improvements are upcoming in v0.8.0

Are you aware of this? Is this the wrong place to look for developer docs?

**Comment by ebuchman** [comment]
Yes wrong place. We've basically deprecated the wiki but there for historical purposes. All docs are now on the website: https://tendermint.com/docs/guides/app-development

**Comment by ebuchman** [comment]
That said, they also need an update. We're working on it :)

**Comment by srmo** [comment]
Oh dear, thanks for the heads on on the link. Can be closed then I guess :)
