### ISSUE TITLE
Error when doing a TX hash query over RPC

### ISSUE THREAD

**Issue by davebryson** [tendermint/tendermint#536]
Tendermint 0.10.0

Calling  RPC `tx/hash=value` with curl only works if you remove the quotes around the hash value and include the `0x` prefix.  Making this work with an RPC client using JSON-RPC (say in Python) seems to be nearly impossible.  Quoting the hex string and including an 0x prefix returns a `400 bad request` error.  Any other permutation of the hash value doesn't seem to work either.  The errors are a bit misleading.

**Comment by melekes** [comment]
On error codes: there is a PR https://github.com/tendermint/tendermint/pull/521 which will be a part of the next release. Our RPC will comply to http://www.jsonrpc.org/specification.

**Comment by melekes** [comment]
> Quoting the hex string and including an 0x prefix returns a 400 bad request error.

@ebuchman is this supposed to work? `curl -X POST --data '{"jsonrpc":"2.0","method":"tx","params":["0x68656c6c6f20776f726c64"]}'`

If that was never implemented, I think we should do it.

**Comment by davebryson** [comment]
I'm wondering if there's a better overall fix when dealing with hex strings.  It can be very confusing from the client side when pushing hex strings to the RPC server.  Obviously the challenge on the server side is to determine whether it's just a string or hex value.   If it's prefixed with '0x' you can assume it's a hex.  But then the hex value must also be of proper length:  `len(hexvalue) % 2 == 0`  otherwise the decoding fails.   Which means: `0x1` fails, but `0x01` is ok.   I guess at a minimum this should be clearly documented for clients to prevent the confusion.

**Comment by melekes** [comment]
we can copy https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding section and adapt it for our use-case

**Comment by davebryson** [comment]
Yes... I was actually peeking at there json-rpc approach last week when I ran into this :-)

**Comment by ryansealy** [comment]
After doing some troubleshooting trying to implement a binary transaction format for my abci, and after getting an awesome, middle of the night response on the tendermint dev channel, I think this can be cleared up with some better documentation.

https://github.com/tendermint/tendermint/wiki/RPC indicates that you can just send hex for a binary transaction format, but there are a few details that would help clear this up.

Here's what I have tested.

To send a literal UTF8 transaction, you simply quote the value of the tx parameter on the GET request:
`GET http://myserver:46657/broadcast_tx_commit?tx="hello"`
This sends a 5 byte transaction "h e l l o" [68 65 6c 6c 6f]

To send as raw hex, you MUST omit the quotes, AND prefix the hex string with 0x
`GET http://myserver:46657/broadcast_tx_commit?tx=0x01020304`
This sends a 4 byte transaction [01 02 03 04]

If you prefer to POST your data as json, you have to Base64 encode your transaction byte array.
```
POST http://myserver:46657
{ 
  "method": "broadcast_tx_commit",
  "jsonrpc": "2.0",
  "params": {"tx": "AQIDBA=="},
  "id": ""
}
```
This sends the same 4 byte transaction [01 02 03 04]

Note that you CANNOT POST your transaction as hex like so:
```
{ 
  "method": "broadcast_tx_commit",
  "jsonrpc": "2.0",
  "params": {"tx": "0x01020304"},
  "id": ""
}
```
You'll get a 400 Bad Request with error: "Error converting json params to arguments: illegal base64 data at input byte 8"

**Comment by srmo** [comment]
@ryansealy Amazing! We were hitting this when moving from 0.9.2 to 0.10.1 - our previous logic stopped working with hex-encoded strings. Thanks for the write-up!

**Comment by zramsay** [comment]
i've updated the tendermint RPC wiki to link to this issue. #691 will further improve the RPC docs

**Comment by melekes** [comment]
We still need to document this.

Question from Riot:
```
hello everyone!
If I send broadcast_tx_sync json-rpc request to tendermint with hex, on abcihandler it turns to encode-broken message like ���@�}�N��}��^t�n=뾼�N����^�. with tx in url query all ok. what can be wrong?
```

**Comment by melekes** [comment]
Done in #3349.
