### ISSUE TITLE
Is there anything like fabric CA in tendermint to control node access?

### ISSUE THREAD

**Issue by BruceChen1995** [tendermint/tendermint#5368]

**Comment by marbar3778** [comment]
The way I have understood fabric CA is to be a registry of which nodes can join the network and which can not, correct?

This could be built on top of tendermint's ABCI layer. The application could have a registry of nodes that area able to join. When a new node tries to connect to a node Tendermint will notify the application via the query connection: https://docs.tendermint.com/master/spec/abci/apps.html#query-connection, if the application returns a non-OK response the node will not connect to the peer.

**Comment by BruceChen1995** [comment]
Thank you, I got you.But I think fabric CA is more like: Once you are authorized, you are authorized everywhere.

And in tendermint, what will happen if the node that a new node tries to connect is broken down? 
Should the new node find another node and ask it to update its registry, or the ABCI application implement a globally synchronized registry?

**Comment by marbar3778** [comment]
The application would have a global registry. To have a registry in the application it's state has to be replicated across all machines. So before someone tries to connect to the network they will have to submit a transaction informing the network their IP and node address.

**Comment by BruceChen1995** [comment]
Ok, I know how to submit a transaction, but I can't figure out the behavior of tendermint when a new node try to connect, like the concrete parameter of query sent to ABCI Application, should I do a test or is there any more detailed document?
(BACKGROUND: I just accomplished an ABCI Application in Rust and the "CA" is the last part, but I haven't read all the code of tendermint and written a lot of Go code, sincerely thank you for your help.)
