### ISSUE TITLE
where is the detailed introduction of tendermint gossip protocol？

### ISSUE THREAD

**Issue by ShallMate** [tendermint/tendermint#5372]
I’m very sorry to interrupt you. I mentioned "The details of the Tendermint gossip protocol will be discussed in a separate technical report." in the paper 《The latest gossip on BFT consensus》. I would like to ask where can I find the detailed introduction of this  tendermint gossip protocol？

**Comment by cmwaters** [comment]
Hey, following from the initial paper, most work has been aimed in implementation and therefore you might be able to find some of the technical information you are looking for this in the [spec repo](https://github.com/tendermint/spec/tree/master/spec). 

We unfortunately don't have a single technical report of the gossip protocol at the moment but we are looking to produce one in the future.

**Comment by milosevic** [comment]
You might want to take a look at consensus reactor spec that contains details on gossip: https://github.com/tendermint/spec/blob/master/spec/reactors/consensus/consensus-reactor.md.
