### ISSUE TITLE
rpc: events from WebSocket subscription are concatenated

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#5373]
This may or may not be intended (from [this recent commit](https://github.com/tendermint/tendermint/commit/59ec3d91e4f60e5f540feab6bbd0cd107abf8eca)), but the Tendermint WebSocket RPC server is now (non-deterministically) concatenating multiple events into each outgoing text message.

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 

`0.34.0-ed046966`

**ABCI app** (name for built-in, URL for self-written if it's publicly available): 

`kvstore`

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS
- **Install tools**:
- **Others**:

**What happened**: Running some event subscription tests in tendermint-rs showed me that events are being concatenated (separated by a newline) into a single outgoing WebSocket text message.

**What you expected to happen**: For each event to be written out as a separate WebSocket text message, or perhaps for the JSON-RPC batching standard to be followed.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

In one terminal:

```bash
docker run -it --rm -v "/tmp/tendermint:/tendermint" tendermint/tendermint init
docker run -it --rm -v "/tmp/tendermint:/tendermint" -p 26657:26657 tendermint/tendermint node --proxy_app=kvstore
```

In a separate terminal:

```bash
git clone git@github.com:informalsystems/tendermint-rs.git
cd tendermint-rs
# See https://github.com/informalsystems/tendermint-rs/pull/572
git checkout rpc/tx-event-subscription
cargo test --all-features transaction_subscription -- --nocapture --ignored
```

Should produce some output like:

```
...
running 1 test
Attempting to grab 10 transaction events
thread 'rpc::transaction_subscription' panicked at 'Timed out waiting for an event', tendermint/tests/integration.rs:245:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test rpc::transaction_subscription ... FAILED

failures:

failures:
    rpc::transaction_subscription
```

**Config (you can paste only the changes you've made)**: none (i.e. default config)

**Anything else we need to know**: This issue could be related to #5367.

**Comment by melekes** [comment]
This was done in https://github.com/tendermint/tendermint/pull/5312 mostly to reduce the number of write syscalls. I thought most clients can handle this (by reading till newline like they do in HTTP protocol when reading header and body).

**Comment by thanethomson** [comment]
> This was done in #5312 mostly to reduce the number of write syscalls. I thought most clients can handle this (by reading till newline like they do in HTTP protocol when reading header and body).

Makes sense! Does the current Go WebSocket client work with this approach?

**Comment by thanethomson** [comment]
Also, I see that the current code [marshals the messages with indentation](https://github.com/tendermint/tendermint/pull/5312/files#diff-f593a99e44d02e0f63dbf56d5c501e4fR430). Won't this interfere with such a scheme?

**Comment by ebuchman** [comment]
Seems the solution is a bit of a weird artifact. I guess ideally the library would allow you to specify distinct websocket messages without requiring you to flush them out to the connection one at a time? Just concatenating multiple messages like this seems like a bit of a hack, but maybe its a good enough solution for now. Do you know if other projects do something similar or how they'd deal with this? 

We should also document this better since it's a bit surprising and I think constitutes a breaking change in the websocket functionality.

**Comment by thanethomson** [comment]
Why don't we serialize the responses as an array? (similar to how [JSON-RPC batching](https://www.jsonrpc.org/specification#batch) works)

**Comment by melekes** [comment]
> Why don't we serialize the responses as an array? (similar to how [JSON-RPC batching](https://www.jsonrpc.org/specification#batch) works)

not sure WS clients would be able to read it correctly by default.

> But Gorilla doenst allow this?

no, not to my knowledge. there are read and write buffers (4096 bytes each), maybe we can increase those.

**Comment by thanethomson** [comment]
> not sure WS clients would be able to read it correctly by default.

From the client, couldn't we just do something like:

```go
// ...
// `data` is the incoming WebSocket message
var responses []types.RPCResponse
if err = json.Unmarshal(data, &responses); err != nil {
	var response types.RPCResponse
	if err = json.Unmarshal(data, &response); err != nil {
		c.Logger.Error("failed to parse response", "err", err, "data", string(data))
		continue
	}
	responses = []types.RPCResponse{response}
}
```

Or:

```go
var responses []types.RPCResponse
if bytes.HasPrefix(data, []byte("[")) {
	err = json.Unmarshal(data, &responses)
} else {
	var response types.RPCResponse
	err = json.Unmarshal(data, &response)
	if err != nil {
		responses = []types.RPCResponse{response}
	}
}
if err != nil {
	c.Logger.Error("failed to parse response", "err", err, "data", string(data))
	continue
}
```

Right now, in Rust code, I parse the current (non-array-based) scheme like so (there could be a better way, but I haven't found it yet):

```rust
async fn handle_text_msg(&mut self, msg: String) {
    let msgs = msg
        .split("}\n{")
        .map(|m| m.to_string())
        .collect::<Vec<String>>();
    for mut msg in msgs {
        if !msg.starts_with('{') {
            msg.insert(0, '{');
        }
        if !msg.ends_with('}') {
            msg.push('}');
        }
        match Event::from_string(&msg) {
            // ... handle event
        }
    }
}
```

And finally, I don't see any handling of this scheme in the [JSON-RPC WebSocket client code](https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/ws_client.go#L487) - is that what possibly could be causing the issue in #5367?

**Comment by webmaster128** [comment]
I just got hit by this and found this ticket after a some debugging. It is causing invalid JSON documents for all clients that expect `message.data` to be a JSON document (as it was for many versions of Tendermint).

I don't know a standardized way to concatenate multiple JSON documents. So we'd basically have to invent and specify one. This is two levels of decoding 1. Split in multiple documents and 2. Parse JSON.

Using a JSON array of responses as @thanethomson suggested seems relatively clean to me. But then it should always be an array even if there is only one element in the message.

Overall I wonder if the additional complexity for clients is worth it. We already use sockets such that every message is cheap, right?

**Comment by thanethomson** [comment]
> But then it should always be an array even if there is only one element in the message.

Seems reasonable to me.

> Overall I wonder if the additional complexity for clients is worth it. We already use sockets such that every message is cheap, right?

The challenge @melekes is trying to overcome is a performance bottleneck that Tendermint hits when attempting to write a large number of RPC responses via the WebSocket endpoint in quick succession. Under the hood, Gorilla flushes each message individually, which slows things down tremendously. Batching outgoing messages together results in significantly improved write performance.

**Comment by webmaster128** [comment]
I see, thank you.

> But then it should always be an array even if there is only one element in the message.

After thinking about this more, I guess I tried to oversimplify life. There two different types of responses:
1. Responses to requests with a 1:1 mapping via ID
2. Events from a subscription

Since 2. is a non-standard extension to JSON-RPC anyways, I think it is sufficiently clean to send them as an array in `message.data`. This functionality is probably only required by a smaller set of sophisticated clients.

But for 1. when you send a sindle request I think it is reasonable to expect a single response. Otherwise it becomes incompatible to the JSON-RPC spec, right?

**Comment by thanethomson** [comment]
> Since 2. is a non-standard extension to JSON-RPC anyways, I think it is sufficiently clean to send them as an array in message.data. This functionality is probably only required by a smaller set of sophisticated clients.

@melekes, can you tell us whether event writing was the primary cause of the write bottleneck?

If that's the case, then we could simply introduce another RPC response type that aggregates events into a single response, as per @webmaster128's suggestion, instead of changing the whole JSON-RPC/WebSocket response serialization scheme.

**Comment by ebuchman** [comment]
I think it would make sense to revert this change for now to unblock folks and propose the optimization/new API in an ADR

**Comment by melekes** [comment]
> @melekes, can you tell us whether event writing was the primary cause of the write bottleneck?

yep

Reverting the change seems like the best option for now. Later we may want to experiment with alternative websocket libraries - e.g. https://github.com/nhooyr/websocket or tweak gorilla [buffer sizes](https://pkg.go.dev/github.com/gorilla/websocket#hdr-Buffers) / use [`PreparedMessage`](https://pkg.go.dev/github.com/gorilla/websocket#PreparedMessage)

**Comment by webmaster128** [comment]
Thanks for reverting the API breaking change. Confirming it works as expected using the current `tendermint/tendermint:latest` from DockerHub
