### ISSUE TITLE
save file and share between nodes

### ISSUE THREAD

**Issue by morteza404** [tendermint/tendermint#5376]
hi
i want to share a file with all of nodes in cluster.  in other word i want to commit transaction with key=filename and value=file_content.
for example:
curl -s 'localhost:26657/broadcast_tx_commit?tx="file_name=file_content"'
how can i do it?
Does anyone have a better offer?
 thanx

**Comment by marbar3778** [comment]
This would need to be handled in the application. Tendermint does not have knowledge of what is in a tx, this is checked by the application
