### ISSUE TITLE
Clean types dependency tree

### ISSUE THREAD

**Issue by NateWilliams2** [tendermint/tendermint#5379]
## Summary

Please clean the tree of imports required by /types, /rpc/core/types, etc
## Problem Definition

Currently, importing /types imports as a dependency abci/types, which in turn imports the entirety of grpc. Similarly, rpc/core/types imports /p2p, which imports the entire tendermint p2p library. I'm building a web application which needs tendermint types but not the functionality of a whole tendermint node. This dependency tree results in a massive binary which includes many unrelated and almost entirely unused packages. 
## Proposal

- move `p2p.DefaultNodeInfo` into a separate types package, so that rpc/core/types only needs to import this shared package, rather than the entirety of tendermint/p2p.
- move the aBCIApplicationClient & ABCIApplicationServer types, which require grpc, into a separate package from the rest of abci types, so that other abci types can be accessed without requiring the grpc library. I believe this would also remove the grpc dependency from /rpc/core/types and from /types
- likely other dependency tree improvements for users of your library

These changes would be much appreciated by both me and my browser :-}

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
The dependency graph could probably be cleaned up, and it's something we'll look into for our next release. (Our next release cycle will focus on API stability, so this could fit in nicely.) 

But you have us all a little surprised - you're running Tendermint in your browser??

**Comment by NateWilliams2** [comment]
@tessr No, not running Tendermint itself... I've made a [block explorer](https://gitlab.com/vocdoni/vocexplorer/-/tree/master) for Vocdoni's [Voting Tendermint Blockchain](https://docs.vocdoni.io/#/architecture/components/vochain). I have a client in the browser which is using the Tendermint API to get info about the blockchain. It uses a custom rpc websockets client, though, hence only needing types from Tendermint.

**Comment by tessr** [comment]
Ah, got it. Thanks for the explanation!
