### ISSUE TITLE
blockchain/v2: nondeterministic panic

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5387]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): master

**ABCI app** (name for built-in, URL for self-written if it's publicly available):cosmos-sdk

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu
- **Install tools**:
- **Others**:

**What happened**: while syncing the node paniced with the below log:

```
panic: processed height 4541 but expected height 4540
goroutine 105 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handleBlockProcessed(0xc000e77dc0, 0x11bd, 0xc000044600, 0x28, 0x36, 0xb4, 0xc006814d00, 0x51a847)
	github.com/tendermint/tendermint@v0.34.0-rc3.0.20200907055413-3359e0bf2f84/blockchain/v2/scheduler.go:551 +0x257
github.com/tendermint/tendermint/blockchain/v2.(*scheduler).handle(0xc000e77dc0, 0x1e5e9c0, 0xc004134760, 0x1878560, 0x195a300, 0x10ad400, 0x1e5e9c0)
	github.com/tendermint/tendermint@v0.34.0-rc3.0.20200907055413-3359e0bf2f84/blockchain/v2/scheduler.go:706 +0xb8
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc00024e480)
	github.com/tendermint/tendermint@v0.34.0-rc3.0.20200907055413-3359e0bf2f84/blockchain/v2/routine.go:78 +0x2ed
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).startSync
	github.com/tendermint/tendermint@v0.34.0-rc3.0.20200907055413-3359e0bf2f84/blockchain/v2/reactor.go:151 +0x105
```

**What you expected to happen**: Node to sync with no issues

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): I reset the node and started a sync with v2 again, no issue was observed. On a secondary node I was also unable to reproduce it

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: see above

**Config (you can paste only the changes you've made)**:
`prometheus: true`
`external_address: ""`
`version: v2` (blockchain reactor)

**node command runtime flags**:none

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**: It would be nice to have a rollback a couple blocks feature in order to avoid a sync from genesis.

**Comment by erikgrinaker** [comment]
Was this with state sync enabled, or only fast sync?

**Comment by marbar3778** [comment]
> Was this with state sync enabled, or only fast sync?

Only fast sync. I could not find enough rpc endpoints to use state sync 🤔

**Comment by erikgrinaker** [comment]
I've been seeing a bunch of these recently too:

```
panic: duplicate block enqueued by processor

goroutine 91 [running]:
github.com/tendermint/tendermint/blockchain/v2.(*pcState).enqueue(...)
	github.com/tendermint/tendermint/blockchain/v2/processor.go:91
github.com/tendermint/tendermint/blockchain/v2.(*pcState).handle(0xc000cd11d0, 0x141fcc0, 0xc001310b60, 0x1167b60, 0x1207580, 0xf36c00, 0x141fcc0)
	github.com/tendermint/tendermint/blockchain/v2/processor.go:135 +0xd1b
github.com/tendermint/tendermint/blockchain/v2.(*Routine).start(0xc000cce900)
	github.com/tendermint/tendermint/blockchain/v2/routine.go:78 +0x2ed
created by github.com/tendermint/tendermint/blockchain/v2.(*BlockchainReactor).startSync
	github.com/tendermint/tendermint/blockchain/v2/reactor.go:152 +0x12e
```

**Comment by melekes** [comment]
@marbar3778 were there any errors in the log before the panic happened?

**Comment by marbar3778** [comment]
> were there any errors in the log before the panic happened?

nope, no indication of an upcoming error

**Comment by melekes** [comment]
Re the original issue: been staring at the code for the past hour. don't understand how this is possible. I think the very fact that we have such issue talks about fundamental issues in the design (concurrency not always good).
