### ISSUE TITLE
Consider adding a Timestamp to RPC responses

### ISSUE THREAD

**Issue by Chris-Harbo** [tendermint/tendermint#54]
Having a timestamp on all RPC responses will enable easier monitoring and debugging of nodes.
i.e. if Network Monitor is sends an RPC request for status and receives an old block height/timestamp but a more recent timestamp from the node that would indicate the node is online but not processing blocks.  There may be a number of ways to achieve this.

**Comment by ebuchman** [comment]
I think there are many other ways to achieve this without burdening every response with timestamp info.
