### ISSUE TITLE
RPC: does not handle url's without ports

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5407]
RPC does not handle URL's without ports. 

Below is a simple test

```go
func TestMakeHTTPDialerURL(t *testing.T) {
	remote := "https://foo-bar.com"

	u, err := newParsedURL(remote)
	require.NoError(t, err)
	dialFn, err := makeHTTPDialer(remote)
	require.Nil(t, err)

	addr, err := dialFn(u.Scheme, u.GetHostWithPath())
	require.NoError(t, err)
	require.NotNil(t, addr)
}
```

The error: 

```sh
dial tcp: address foo-bar.com: missing port in address
```

**Comment by JayT106** [comment]
@marbar3778 `net.Resolver` requires the port info in the URL(or address). Under this case, What do you think to add default rpc server port, i.e. `26657` after the URL?

**Comment by marbar3778** [comment]
It's hard to say what a default could be. I have ended up using :443 if no port is provided, if that doesnt work and 26657 doesn't I try to do a port scan. Im not sure the best path forward with this

**Comment by gibson042** [comment]
I think this ticket should be reopened, since cb63ab4ac0e5dd2b8ddae1b14e3cf7de403630fc apparently never landed on the `main` branch. See also parallel issue https://github.com/cometbft/cometbft/issues/1902 .
