### ISSUE TITLE
quick start, install, make get_vendor_deps

### ISSUE THREAD

**Issue by Tinrry** [tendermint/tendermint#5410]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.34.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
0.17.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
ubuntu 20.04

- **Install tools**:
- **Others**:

**What happened**:
## build
git checkout master
make get_tools
make get_vendor_deps

![image](https://user-images.githubusercontent.com/16282255/94361800-9c9f5600-00e9-11eb-89a5-59a6181460ba.png)
where is get_vendor_deps?

**What you expected to happen**:

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by marbar3778** [comment]
`get_vendor_deps` has been deprecated a while go. We have migrated to go modules now. If you are trying to install the binary you can run make install or make build. Go modules will cache the deps on your system
