### ISSUE TITLE
Enhancement: init command genesis file w/o validator filled

### ISSUE THREAD

**Issue by Greg-Szabo** [tendermint/tendermint#542]
This is a similar enhancement request as was opened for basecoin here:
https://github.com/tendermint/basecoin/issues/124

The `tendermint init` command should be able to generate genesis.json files that have the validator part filled (as it is now) or where the validator part is empty. (new enhancement)

Option #1: Keep as is and introduce switch:
tendermint init --not-a-validator (or similar, like --no-validator)

Option #2: Make no-validator the default and optionally fill it:
tendermint init (creates genesis.json with validator not filled `tendermint init --validator` (creates genesis.json with validator filled)

The second option is better for production use as more people will install tendermint for non-validator nodes than validator nodes. The first option is better for developers where a new installation is usually for a one-node testnet. (For multi-node testnets, it doesn't matter which option is chosen, as it will be overwritten.) The same option should be chosen that was chosen in the base coin request.

**Comment by ebuchman** [comment]
I don't understand. A genesis.json without validators is useless. What am I missing? Non-validator nodes still need a genesis file with the validators in it. `tendermint init` is really just for development. If the genesis file already exists, you don't need to run it. That said, maybe we still need something to produce an initial config.toml file ....

**Comment by melekes** [comment]
@Greg-Szabo any comments to ^^^ ?

**Comment by Greg-Szabo** [comment]
Not relevant anymore, closing.
