### ISSUE TITLE
docs: merge "Getting Started" and "Using ABCI-CLI" pages

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5421]
## Summary

Getting Started: https://docs.tendermint.com/master/app-dev/getting-started.html
Using ABCI-CLI: https://docs.tendermint.com/master/app-dev/abci-cli.html

Both these pages in slightly varying ways introduce the `abci-cli` and then go through two example applications the `kvstore` and `counter`. As they are right after one another and talk about practically the same thing, I propose that we merge these two pages together

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
I view getting started more as getting started with Tendermint and abci-cli introducing the tool abci-cli. They do cover some same info (kvstore and counter) but in different lights.

**Comment by cmwaters** [comment]
I see that perspective but getting started introduces Tendermint through the abci-cli. Personally I just feel that there is too much redundancy and it can all be consolidated through a single page.

> The flow of the docs needs a reorg, I was planning on doing this post 0.34 release, so we don't break the links.

Yeah I agree. Would be happy to help with this when we get around to it

**Comment by tessr** [comment]
I know that Marko has a whole docs "refactor" planned, so I'm going to close this issue for now since I think the whole flow is going to change.
