### ISSUE TITLE
consensus: check proposal block size is valid on receiving it

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5423]
## Summary

Validators should ensure that block size should not exceed `MaxBytes` defined in the consensus params

## Problem Definition

This check was originally in place but was unfortunately inadvertently removed when migrating to protobuf. There is logic on the proposer side to ensure that the block is of the correct size but if the proposer were to bypass it, it allows them to create blocks of any size where the other validators would approve of it. This only applies for 0.34.

As a side note we should also check to make sure that none of the other validation logic was affected by the protobuf migration. 

## Proposal

Reimplement the check here:

https://github.com/tendermint/tendermint/blob/99aea7b079172f4cb9abf76ac9de5b2d50ba170b/consensus/state.go#L1782-L1792

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
> As a side note we should also check to make sure that none of the other validation logic was affected by the protobuf migration.

Other than consensus/state, `UnmarshalBinaryLengthPrefixedReader` was used in p2p/connection, secret_connection and privval. All now use `protoio.DelimitedReader`, which seem to be correct.

**Comment by erikgrinaker** [comment]
Good catch Callum!

I remember working on something related. I'm not really sure why this used length-prefixing originally - this is typically only used for message framing on the wire, which is why it's still in use e.g. in p2p, secret conn, and privval. However, length-prefixing individual messages doesn't really make sense since the message is presumably already demarcated as a byte slice (or in this case, a slice of byte slices).

I haven't looked into the details here, but shouldn't this validation happen before we even accept the part, to avoid the partset growing without bound?

**Comment by cmwaters** [comment]
> I haven't looked into the details here, but shouldn't this validation happen before we even accept the part, to avoid the partset growing without bound?

Yeah you're right, we should keep a tally and check it as each part is received

**Comment by marbar3778** [comment]
> > I haven't looked into the details here, but shouldn't this validation happen before we even accept the part, to avoid the partset growing without bound?
> 
> Yeah you're right, we should keep a tally and check it as each part is received

This does seem to already be present here: https://github.com/tendermint/tendermint/blob/58b4deca8688ef3759b97d77c56d80334c315f7a/consensus/reactor.go#L32-L32

**Comment by erikgrinaker** [comment]
Won't that just limit the size of each part, not of the total part set? (haven't look at the code here at all, so I may be missing something)

**Comment by marbar3778** [comment]
> Won't that just limit the size of each part, not of the total part set? (haven't looked at the code here at all, so I may be missing something)

Correct, it would not limit the block size when decoded. So a check would be needed on the size of a block. I don't think length prefixing of the specific message is needed here, will bleed into state storage, but could be wrong.

**Comment by cmwaters** [comment]
So just to summarize things:
- We already have a check that the part size doesn't exceed the msg size.

- But we still need to check the block size (the total of all the parts) and we should do this by keeping a byte sum that we update when each part is received. At any point, if this sum exceeds the consensus param `MaxBytes` we then return an error and thus the validator prevotes and precommits nil
