### ISSUE TITLE
Remove gogoproto 

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5446]
## Summary

Currently Gogoproto is used throughout Tendermint. The primary use of it is `(gogoproto.nullable) = false`. With protoc 3.12 adding support for the optional field in proto3 (https://github.com/protocolbuffers/protobuf/releases/tag/v3.12.0) the nullable feature of gogoproto becomes redundant. For this reason we could remove gogoproto entirely from tendermint.

One blocker that may arise from this is the performance degradation that will come with using vanilla go protobuf. https://github.com/alexshtin/proto-bench

## Problem Definition

Remove a redundant dependency.

## Proposal

Remove gogoproto and replace it with vanilla [go protobuf](https://github.com/protocolbuffers/protobuf-go).

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Note to self: we should aim to do this post p2p refactor. Currently, we are marshaling twice, once in the reactor and again prior to sending over the wire. In the new system there will be only one marshal this will mitigate some performance concerns.
