### ISSUE TITLE
use commit instead of votes when calculating maximum bytes

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5448]
## Problem Definition

This is relatively minor but I saw when calculating the max data bytes we use `MaxVoteBytes` (209) multiplied by the `valsCount`when we should be probably using the `valsCount` to calculate the maximum size of the commit. I think this is left over from when votes were stored in the block instead of commit sigs 

```
func MaxDataBytes(maxBytes int64, valsCount, evidenceCount int) int64 {
	maxDataBytes := maxBytes -
		MaxOverheadForBlock -
		MaxHeaderBytes -
		int64(valsCount)*MaxVoteBytes -
		int64(evidenceCount)*MaxEvidenceBytes
```

## Proposal

Calculate the size of the maximum commit as opposed to multiplying the `valsCount` by the `MaxVoteBytes`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
CommitSig, not commit
