### ISSUE TITLE
docs: set /master by default for docs deployment

### ISSUE THREAD

**Issue by lovincyrus** [tendermint/tendermint#5472]
## Description

After merging https://github.com/tendermint/tendermint/pull/5468, we expect docs.tendermint.com to have /master, /v0.32, and /v0.33. While they do have those path prefixes, docs.tendermint.com doesn't show /master by default.

https://docs.tendermint.com/ (showing v0.32) *
https://docs.tendermint.com/master/
https://docs.tendermint.com/v0.32/
https://docs.tendermint.com/v0.33/

![image](https://user-images.githubusercontent.com/1021101/95247793-2bd3fa00-07cb-11eb-95e3-84ac5b411653.png)

### References: 
- branches and path prefixes set up: https://github.com/tendermint/tendermint/pull/5467
- docs.cosmos.network may be facing the same issue, but it's not as apparent because old versions of tendermint docs have a different UI. https://github.com/cosmos/cosmos-sdk/issues/7468

**Comment by marbar3778** [comment]
closed via #5474
