### ISSUE TITLE
circleci -> github actions migration

### ISSUE THREAD

**Issue by alessio** [tendermint/tendermint#5478]
It'd be great if we could disable CircleCI integration altogether.

CC'ing @marbar3778 @tessr @erikgrinaker @ebuchman for feedback/ideas.

Thanks for considering.

**Comment by marbar3778** [comment]
There are two things left, releases and docs. 

For releases, we could migrate to goreleaser (https://github.com/goreleaser/goreleaser). I can do this. 

For docs, we could try to deploy to github pages? We would have to change a few things for this.

**Comment by alessio** [comment]
> For releases, we could migrate to goreleaser (https://github.com/goreleaser/goreleaser). I can do this.

Happy to help!

> For docs, we could try to deploy to github pages? We would have to change a few things for this.

Yes please!

**Comment by tessr** [comment]
Reopened since we haven't been able to move the docs over yet.
