### ISSUE TITLE
tendermint v0.32.6 docker image

### ISSUE THREAD

**Issue by morteza404** [tendermint/tendermint#5484]
Hi every body,
i need to tendermint v0.32.6 docker image and i search and not found official release for that in dockerhub. 
[https://hub.docker.com/r/tendermint/tendermint/tags/](url)
can every one help me?

**Comment by marbar3778** [comment]
It seems from 0.32.3-0.32.8 were not pushed. I am not sure if there was a docker issue at this time. Can you try v0.32.13? We do recommend upgrading to the latest releases as soon they come out. They may hold security fixes that can affect your network.

**Comment by morteza404** [comment]
ok, i download tendermint v0.32.6 binary file and build image successfully. thanx
