### ISSUE TITLE
Regression: 0.34 only supports ed25519 consensus types

### ISSUE THREAD

**Issue by joe-bowman** [tendermint/tendermint#5495]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.34

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
n/a

**What happened**:
#5016 removed support for secp256k1 consensus; contrary to comments on that issue, secp256k1 _is_ supported, and is used - most notably by Band protocol!

**What you expected to happen**:
This shouldn't have been removed!

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
create a genesis file, and add secp256k1 as the value for `consensus_params.validator.pub_key_types`.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
Error: failed to unmarshal genesis state: error reading GenesisDoc at /home/joe/.union/config/genesis.json: params.Validator.PubKeyTypes[0], secp256k1, is an unknown pubkey type
```

**Comment by joe-bowman** [comment]
In fact, secp256k1 has been removed from Tendermint in it's entirety (presumably because it was removed from here, and was then deemed surplus to requirements...).

**Comment by sorawit** [comment]
We have been using `secp256k1` in production an has been vocal about it. It makes interoperability with EVM possible without blocking on [EIP-665](https://eips.ethereum.org/EIPS/eip-665). How much work would it take to bring back secp256k1?
