### ISSUE TITLE
How to start four local nodes using my own application?

### ISSUE THREAD

**Issue by BruceChen1995** [tendermint/tendermint#5497]
According to https://docs.tendermint.com/master/networks/docker-compose.html#configuring-abci-containers , I started 4 localnode containers and 4 rust application containers(every application is connected to a mongodb container),then I got:
```shell
node0       | E[2020-10-14|07:15:21.597] abci.socketClient failed to connect to tcp://abci0:26658.  Retrying... module=abci-client connection=query err="dial tcp 192.167.10.6:26658: connect: connection refused"
```
I changed `node --proxy_app=tcp://abci0:26658` to `node --rpc.laddr=tcp://abci0:26657` in `docker-compose.yml`,then I got:
```shell
node0       | E[2020-10-14|07:29:43.798] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
```
Based on rust-abci library,my application communicate with tendermint core via rpc port 26657,how can I start localnode network?

**Comment by erikgrinaker** [comment]
Which port is your application actually listening on? With rust-abci, this seems to be specified when initializing the ABCI server via `serve()`. You need to use that port number for `--proxy_app`.

**Comment by BruceChen1995** [comment]
https://docs.rs/abci/0.7.0/abci/fn.run_local.html , my application listen on default 26658 port.But `node --proxy_app=tcp://abci0:26658` didn't work as mentioned above.

**Comment by erikgrinaker** [comment]
It may be because Tendermint is started before the ABCI application. Try setting e.g. `depends_on: abci0` for the Tendermint containers, or start the containers manually in the correct order with e.g. `docker-compose up abci0` and so on.

**Comment by erikgrinaker** [comment]
Ah, no. `run_local()` only listens on `127.0.0.1:26658` so it's not accessible from other containers, only from within the `abci0` container on localhost. You have to listen on `0.0.0.0:26658`.
