### ISSUE TITLE
Enable installation through brew on macOS

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#550]
Fix the installation steps in here: https://github.com/tendermint/homebrew-tendermint

**Comment by zramsay** [comment]
close? looks like latest update in the homebrew repo are recent

**Comment by adrianbrink** [comment]
Doesn't fully work yet though.

**Comment by ebuchman** [comment]
Make Tendermint Great Again!

**Comment by melekes** [comment]
https://github.com/Homebrew/homebrew-core/pull/21331

**Comment by zramsay** [comment]
is resubmission blocking on fixing our install from source?

**Comment by melekes** [comment]
No, I just need to release ethermint (https://github.com/tendermint/ethermint/issues/357)

**Comment by melekes** [comment]
https://github.com/Homebrew/homebrew-core/pull/23251

**Comment by ebuchman** [comment]
What happened here? Let's just get the `brew install tendermint` and forget ethermint for now

**Comment by jackzampolin** [comment]
We are not planning on supporting these targets. Closing this issue.

**Comment by melekes** [comment]
let's keep this open. brew makes it easy to try something (developers often use it)

**Comment by cmwaters** [comment]
Opened a PR to get brew support for tendermint 0.34: 

https://github.com/Homebrew/homebrew-core/pull/65645

(I tried initially to use the forked repo already in tendermint but I didn't have perms so just created my own fork)
