### ISSUE TITLE
types: simplify Header hashing

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5514]
Spec: tendermint/tendermint#7915

Change header hashing scheme from (1) building a Merkle tree from fields to (2) hashing a slice of fields directly

https://github.com/informalsystems/tendermint-rs/blob/80fb191e398e32eec88d22cd2c4e807ea27a3d0b/tendermint/src/block/header.rs#L68-L102

**Comment by marbar3778** [comment]
This is a quick change but is there any benefit to doing it this way versus just proto encoding the header struct than hashing the output?

**Comment by melekes** [comment]
> This is a quick change but is there any benefit to doing it this way versus just proto encoding the header struct than hashing the output?

because you don't want to lock into protobuf?

**Comment by marbar3778** [comment]
> > This is a quick change but is there any benefit to doing it this way versus just proto encoding the header struct than hashing the output?
> 
> because you don't want to lock into protobuf?

That ship has sailed, we are locked into protobuf harder than Karl Marx into communism.

**Comment by cmwaters** [comment]
All jokes aside, if the protobuf were to change the way they encoded things, this would mean a hard fork for all networks that upgrade right?

**Comment by marbar3778** [comment]
> All jokes aside, if the protobuf were to change the way they encoded things, this would mean a hard fork for all networks that upgrade right?

yes.

**Comment by cmwaters** [comment]
Okay. I think that's probably fine
