### ISSUE TITLE
JSON and protobuf messages discrepancies

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#5522]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.34.0-6ef7b316
(latest Docker image at 2020-10-18)

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore (docker image)

**Environment**:
- **OS** (e.g. from /etc/os-release): linux (Docker image)
- **Install tools**: -
- **Others**: -

**What happened**:
curl localhost:26657/block returns the following block: (excerpt)
```
        "block_id": {
          "hash": "2A55A0D0001200C149A0DA2FA22B06FF2B484B459FDD378B13CCDB96626028C0",
          "parts": {
            "total": 1,
            "hash": "4AC10C7D55C9C9E6823D359F11216CB8A401C3E664E5845479077E5C7FA8D5ED"
          }
        },
```

**What you expected to happen**:
The same, but instead of `parts` field, I expected `part_set_header`, The reason: the protobuf definitions now define it as `part_set_header`.

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
```
docker run -p 26657:26657 tendermint/tendermint
curl localhost:26657/block
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:
(whatever is in Docker)
**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:
I feel guilty reporting this as a bug, because I understand that the inconsistency comes from before the protobuf times. And the naming convention was introduced in protobuf. I feel, the JSON structs are not derived from protobuf?

**Comment by marbar3778** [comment]
Nice find, thank you for the issue!! I'll open a quick pr to fix this
