### ISSUE TITLE
RPC keeps panic when there are RPC requests

### ISSUE THREAD

**Issue by kwunyeung** [tendermint/tendermint#5529]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.33.7

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
[Kava-4 ](https://github.com/Kava-Labs/kava/tree/v0.11.0) with Cosmos SDK `v0.39.1`.

**Environment**
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- **Install tools**: go module
- **Others**:

**What happened**:
Node continuously having
```
Panic during RPC panic recovery: write tcp 127.0.0.1:26657->127.0.0.1:52708: i/o timeout
```
And not syncing with new blocks.

**What you expected to happen**:
The node would panic during RPC panic, stop the connection and continue syncing.

**Have you tried the latest version**: yes/no
no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
https://pastebin.com/Q2ciBsaf

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:
The RPC service is behind reverse proxy.

**Comment by erikgrinaker** [comment]
Thanks for reporting! I believe the root problem here is that the RPC server uses panics for error handling instead of returning errors, which can cause side effects (e.g. not properly releasing mutexes). In this case, it may cause some RPC component to continually try to flush a write buffer. We should really return errors instead, see #4465.

**Comment by joe-bowman** [comment]
Can confirm I see the same issue in TM 0.33.9; it affects our monitoring so is quite user impacting.
