### ISSUE TITLE
blockchain/v2: consider not removing blocks from peers who disconnected or timed out

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5532]
https://github.com/tendermint/tendermint/pull/5499#discussion_r508311701

Those blocks are not necessary faulty, although they could be. We should also keep in mind p.2 from https://github.com/tendermint/tendermint/issues/5496.

**Comment by cmwaters** [comment]
I agree that we need to make the distinction between peers providing invalid blocks and those just dropping out because of networking reasons

**Comment by marbar3778** [comment]
V2 has been removed
