### ISSUE TITLE
Make tendermint commands more embeddable

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#554]
We suggest the possibility of embedding tendermint in another app, and do so with basecoin.  However, we either miss much functionality or have to rewrite it.

For example:

`tendermint node` takes a number of flags that `basecoin start` does not support, and also includes some genesis file parsing that is duplicated.

`basecoin init` and `tendermint init` do much of the same functionality but duplicated code

Clearing this up should help with devops and cli maintenance.

**Comment by rigelrozanski** [comment]
Cool! I like the idea of a plugin architecture, similarly to how a basecoin plugin will import a bunch of basecoin commands in the `main.go`.. maybe we could basecoin-core (quarks) could import commands directly from tendermint? Just a thought

**Comment by ethanfrey** [comment]
Fixed with #561
