### ISSUE TITLE
evidence: node crashes if state syncing to a height where an attack occured

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5554]
## Problem Definition

If we state sync to block 100 we don't have block 100 but the state for it thus when we go to process height 101 if there was ever evidence that required block 100 (or anything below) the evidence pool wouldn't be able to find it and thus would fail verification which would cause the node catching up on consensus to panic like so:

```
panic: failed to process committed block (1016:818004A8D10AEF29A67912C15F88073061AB547BBA2618AEEC6FDD3D67DE5669): Invalid evidence: don't have header at height #1015. Evidence: DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1015/01/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 258275714E02 @ 2020-10-22T14:06:59.431393311Z}, VoteB: Vote{4:A54399B792EC 1015/01/SIGNED_MSG_TYPE_PREVOTE(Prevote) 281D1620AAE9 5F95FBC60A4F @ 2020-10-22T14:06:59.430423203Z}}
```

You can see the full log [here](https://gist.github.com/cmwaters/d560086b66a8ae329afe7ae288696efd)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
I suspect this will happen in all cases where the block isn't available. One trivial way to reproduce this should be to set block retention to `1` and delay the evidence by two heights.

**Comment by cmwaters** [comment]
The tricky part I see about this is that with voting if the validator doesn't have the evidence because it doesn't have the block you don't want it to blindly approve so the default is to error. But if we are catching up in consensus we still want it to process the block without erroring.

**Comment by cmwaters** [comment]
I don't think there is an easy solution to this. 

If the node doesn't have a block that it needs to verify evidence because it hasn't retained it or because of state sync then I can't think of any other way then that it needs to go back get the block or at least the validator set at that height, verify that it is the correct block, then verify the evidence and then use the validator set at that height to produce the abci evidence. 

I thought we could bypass the validation of evidence during state sync and just say that as long as the quorum of votes was reached, we trust that the evidence inside there is valid but it's not just about validation, we need I believe at least the validator set in order to get the malicious validators information so that we can form abci evidence and send it to the application. 

And this is something we can't bypass because then some applications get abci evidence and others don't and then we don't have state machine replication.

**Comment by erikgrinaker** [comment]
Wait, isn't the evidence in the block self-contained? I get that during evidence verification we'll need access to external data, but once it's put into the block proposal it needs to be self-contained. Otherwise we'll run into exactly these kinds of problems when we submit it to the state machine.

**Comment by cmwaters** [comment]
nope none of the evidence is self-contained in that regard. All of them require access to state to verify and access to state to produce the evidence information that goes to the application.

**Comment by erikgrinaker** [comment]
Right, I don't think that's going to work. What'd it take to make it self-contained in blocks?

**Comment by cmwaters** [comment]
Well we need each of the evidence structs to support the abci evidence struct which consists of:
```
type Evidence struct {
	Type EvidenceType `protobuf:"varint,1,opt,name=type,proto3,enum=tendermint.abci.EvidenceType" json:"type,omitempty"`
	// The offending validator
	Validator Validator `protobuf:"bytes,2,opt,name=validator,proto3" json:"validator"`
	// The height when the offense occurred
	Height int64 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	// The corresponding time where the offense occurred
	Time time.Time `protobuf:"bytes,4,opt,name=time,proto3,stdtime" json:"time"`
	// Total voting power of the validator set in case the ABCI application does
	// not store historical validators.
	// https://github.com/tendermint/tendermint/issues/4581
	TotalVotingPower int64 `protobuf:"varint,5,opt,name=total_voting_power,json=totalVotingPower,proto3" json:"total_voting_power,omitempty"`
}
```
This means that `DuplicateVoteEvidence` would need to look something like:
```
type DuplicateVoteEvidence struct {
  voteA *Vote
  voteB *Vote
  val Validator
  time time.Time
  totalVotingPower int64
}
```
and `LightClientAttackEvidence` like:
```
type LightClientAttackEvidence struct {
  conflictingBlock *LightBlock
  commonHeight int64
  time time.Time
  byzValidators  []Validator
  totalVotingPower int64
}
```

The evidence pool does this already when it wraps evidence in the `info` struct thus making it "self-containable" or ready to be sent to the application

```
type info struct {
	Evidence         types.Evidence
	Time             time.Time
	Validators       []*types.Validator
	TotalVotingPower int64
	ByteSize         int64
}
```

**Comment by erikgrinaker** [comment]
Yeah, I think we'll have to do that - but do check with others who have been involved with the evidence work what they think.
