### ISSUE TITLE
evidence: proposer adds already committed evidence to new block

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5560]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
`v0.34.0-rc6`

**What happened**:

Ran a  E2E test with a double vote set to happen at height 1012. The evidence is detected and submitted in the following height. Then in height 1025 we get this:

```
validator03    | I[2020-10-23|08:32:10.379] Executed block                               module=state height=1024 validTxs=2 invalidTxs=0
validator03    | I[2020-10-23|08:32:10.391] Committed state                              module=state height=1024 txs=2 appHash=C86A6AEA84A4C62AEF2A65DAA62DB202C8C85CB8B142F766E48088B08DD738B4
validator03    | E[2020-10-23|08:32:11.457] Invalid evidence: evidence was already committed. Evidence: DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 378847C58918 @ 2020-10-23T08:31:52.558190037Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 46F68ABA614F 2780052F1AB1 @ 2020-10-23T08:31:52.557410639Z}} module=evidence 
validator03    | E[2020-10-23|08:32:11.457] Stopping peer for error                      module=p2p peer="Peer{MConn{10.186.73.2:53758} d3b5bfd2aeac159c79812dd9426de51a971c7a61 in}" err="Invalid evidence: evidence was already committed. Evidence: DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 378847C58918 @ 2020-10-23T08:31:52.558190037Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 46F68ABA614F 2780052F1AB1 @ 2020-10-23T08:31:52.557410639Z}}"
```

i.e. Another proposer is adding already committed evidence into a new block

**What you expected to happen**:

Proposer at height 1025 should have added evidence at height 1013 to evidence pool which should have removed it from the pending bucket so that the proposer would have not added it to the block. 

What I think is happening is that when the block is being executed we are not updating the evidence pool correctly and removing the evidence committed in the block from the pending bucket and putting it in the committed bucket.

**How to reproduce it** (as minimally and precisely as possible):

Run the E2E ci.toml test (I'm not sure how deterministic the behavior is though)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

[Full log can be found here](https://pipelines.actions.githubusercontent.com/KyLXqUW5FXEommX1jskveX9BQo621QMUbAS3HHgRXLqddPVNkV/_apis/pipelines/1/runs/13904/signedlogcontent/3?urlExpires=2020-10-23T09%3A58%3A11.4335856Z&urlSigningMethod=HMACV1&urlSignature=SBbJkqdEcIAu9juUGh3ypmF0HaTty%2FQiSoQgLzi%2BADI%3D)

**Anything else we need to know**:

This is a non-critical bug. The only problem was that the peer who proposed the block with that evidence was then dropped. It's also nice to know that you can't submit committed evidence (we hadn't really tested that before).

**Comment by erikgrinaker** [comment]
It's possible that this is more serious than first thought. I had a testnet now that halted because the validators were not able to establish a quorum, seemingly because they kept getting disconnected from each other due to evidence errors.

**Comment by cmwaters** [comment]
So it's not one particular validator that is proposing committed evidence but they all are at relatively sporadic heights?

**Comment by erikgrinaker** [comment]
I didn't look very closely, but lots of nodes were throwing evidence errors and disconnecting, and the network halted.

This was the `ci.toml` network, had to rerun it a bunch of times before it passed.

**Comment by erikgrinaker** [comment]
Here's an example: https://github.com/tendermint/tendermint/pull/5562/checks?check_run_id=1298400281

**Comment by cmwaters** [comment]
So I'm not sure if this is all the problem but I think partly it comes from nodes who are a little behind continuing to gossip just up to the point before the evidence pool processes the block and removes the evidence. So part of the solution could just be ignoring the gossiping of committed evidence if it's say one or two heights away from being committed. 

But I'm not sure if this is the entire problem

**Comment by cmwaters** [comment]
Hmm strange. So once evidence is committed on block, these validators are removing evidence from their gossiping list (`clist`) but then in a later height they are gossiping evidence (that they shouldn't have) to other nodes then these nodes are responding with the committed evidence and so are being dropped straight away. This log here sort of paints the picture:

```
validator02    | E[2020-10-23|16:49:36.583] Removing evidence from gossip list           module=evidence evidence="DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 065FE9EE05A9 @ 2020-10-23T16:49:34.410427875Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 8201B6E7FC31 3739DCB93855 @ 2020-10-23T16:49:34.401454526Z}}"
validator02    | I[2020-10-23|16:49:36.583] Executed block                               module=state height=1013 validTxs=7 invalidTxs=0
validator02    | I[2020-10-23|16:49:36.590] Committed state                              module=state height=1013 txs=7 appHash=A20A1AACE5958ED508BE503DA9C6F58F6548714C1CBBA1E06258FC8823BB39C5
validator02    | E[2020-10-23|16:49:36.975] Gossiping evidence to peer                   module=evidence evidence="DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 065FE9EE05A9 @ 2020-10-23T16:49:34.410427875Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 8201B6E7FC31 3739DCB93855 @ 2020-10-23T16:49:34.401454526Z}}" peer="Peer{MConn{10.186.73.5:44110} 539ffc12a0ac78970dab31ae8cdcfdd4285b2162 in}"
validator02    | E[2020-10-23|16:49:37.100] Invalid evidence: evidence was already committed. Evidence: DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 065FE9EE05A9 @ 2020-10-23T16:49:34.410427875Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 8201B6E7FC31 3739DCB93855 @ 2020-10-23T16:49:34.401454526Z}} module=evidence 
validator02    | E[2020-10-23|16:49:37.100] Stopping peer for error                      module=p2p peer="Peer{MConn{10.186.73.5:44110} 539ffc12a0ac78970dab31ae8cdcfdd4285b2162 in}" err="Invalid evidence: evidence was already committed. Evidence: DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 065FE9EE05A9 @ 2020-10-23T16:49:34.410427875Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 8201B6E7FC31 3739DCB93855 @ 2020-10-23T16:49:34.401454526Z}}"
validator02    | E[2020-10-23|16:49:37.101] Invalid evidence: evidence was already committed. Evidence: DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 065FE9EE05A9 @ 2020-10-23T16:49:34.410427875Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 8201B6E7FC31 3739DCB93855 @ 2020-10-23T16:49:34.401454526Z}} module=evidence 
validator02    | E[2020-10-23|16:49:37.101] Stopping peer for error                      module=p2p peer="Peer{MConn{10.186.73.5:44110} 539ffc12a0ac78970dab31ae8cdcfdd4285b2162 in}" err="Invalid evidence: evidence was already committed. Evidence: DuplicateVoteEvidence{VoteA: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 000000000000 065FE9EE05A9 @ 2020-10-23T16:49:34.410427875Z}, VoteB: Vote{4:A54399B792EC 1012/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 8201B6E7FC31 3739DCB93855 @ 2020-10-23T16:49:34.401454526Z}}"
```

I'm suspecting that the problem could lie somewhere in these concurrent lists which I am not so familiar about
