### ISSUE TITLE
Actual block size can exceed `max_bytes` of `consensus_params`

### ISSUE THREAD

**Issue by egonspace** [tendermint/tendermint#5564]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
latest (d11e5993b15515ef57fd3447467bad049fa6e491)

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
counter app

**Environment**:
- **OS** (e.g. from /etc/os-release): centOS 7.2
- **Install tools**: docker
- **Others**: used make-linux; make-docker

**What happened**:
While I am doing load test on 100 validators following error raised.
"total size of proposal block parts exceeds maximum block bytes"

So I wrote some debugging code on `CreateProposalBlock()` like following and I found that a CommitSig size is 104 bytes that is larger than expected size(`MaxCommitSigBytes + protoEncodingOverhead` = 79 bytes).
```
block, partSet := state.MakeBlock(height, txs, commit, evidence, proposerAddr)
if partSet.ByteSize() > maxBytes {
	txsSize := 0
	for _, tx := range txs {
		txsSize += len(tx)
	}
	pb, _ := block.ToProto()
	b, _ := pb.Marshal()
	h, _ := pb.Header.Marshal()
	d, _ := pb.Data.Marshal()
	e, _ := pb.Evidence.Marshal()
	c, _ := pb.LastCommit.Marshal()
	c1, _ := pb.LastCommit.Signatures[0].Marshal()
	blockExec.logger.Error("block size exceeds the max", "evSize", evSize, "maxDataBytes", maxDataBytes, "txs size", txsSize, "block", len(b), "header", len(h), "data", len(d), "evidence", len(e), "commit", len(c), "one commit", len(c1))
}
```

Please check this.

**What you expected to happen**:

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by cmwaters** [comment]
Interesting 🤔 . I will look into it. Thanks for opening the issue

**Comment by cmwaters** [comment]
I see we were allocating 32 bytes for the signature instead of 64 bytes.
MaxCommitSigBytes should be 1(block flag) + 24(timestamp) + 20(validator_address) + 64(signature) = 109
Good spot, I will create a fix.
