### ISSUE TITLE
I cannot define max_batch_bytes small.

### ISSUE THREAD

**Issue by egonspace** [tendermint/tendermint#5565]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
latest

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
counter app

**Environment**:
- **OS** (e.g. from /etc/os-release): CentOS 7.2
- **Install tools**: self building
- **Others**: using docker

**What happened**:
I set `max_batch_bytes` to be small to limit mempool from delivering bulk txs to peer. Because the tx in counter app was so small (less than 20 bytes) that too many txs are transmitted at a time, I found that the consensus messages are not being processed for a while. However, I tried to reduce the batch unit by making this value smaller, but the node failed to start due to the following error.

`ERROR: error in config file: error in [mempool] section: max_batch_bytes can't be less or equal to max_tx_bytes`

I think this policy is wrong. I think the batch size should be limited to the number of transactions not to the batch bytes.

**What you expected to happen**:

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by cmwaters** [comment]
Could you provide more of an explanation as to why you think having batch size based on the number of txs instead of a max number of bytes is a better policy?

This parameter is basically setting the mempool channel capacity so if it were in number of txs we would need to multiply it by the `max_tx_bytes` in any case. Would you propose that mempool messages are not filled to the channel capacity (in bytes) but rather capped by a set amount of txs?

**Comment by egonspace** [comment]
`max_tx_bytes` is set to 1MB by default. So I cannot define `max_batch_bytes` under 1MB. This means that mempools exchange txs message with peer in units of more than 1 megabyte. This slows down consensus message processing on busy tx requests because mempool reactor and consensus reactor use same receive thread(refer this https://github.com/tendermint/tendermint/issues/5566 for more information). 

I have to set `max_tx_bytes` to be small to set `max_batch_bytes` small. However, the size of the transaction may be large, so it cannot be set small.

**Comment by egonspace** [comment]
If you really want to limit it by the byte size, how about to create a rule that eliminates the constraint that `max_batch_bytes` should be larger than `max_tx_bytes`, and that if tx is smaller than `max_tx_bytes` and larger than `max_batch_bytes`, only one should be included in the batch?

**Comment by erikgrinaker** [comment]
I think we should add another setting `max_batch_txs`, and stop adding to the batch once we reach either `max_batch_txs` or `max_batch_bytes`. We need both, because if we only have `max_batch_txs` then we have to assume that each tx can be up to `max_tx_bytes` when we calculate internal size limits, which means we can only put a handful of txs into a batch.

**Comment by melekes** [comment]
> I found that the consensus messages are not being processed for a while

that does not sound good. maybe we should decrease MempoolReactor channel `Priority`

> ERROR: error in config file: error in [mempool] section: max_batch_bytes can't be less or equal to max_tx_bytes

have you tried lowering `max_tx_bytes`? e.g. setting it to "20 bytes" and setting max_batch_bytes to say 110 bytes (resulting in max 5 transactions)

**Comment by egonspace** [comment]
> have you tried lowering `max_tx_bytes`? e.g. setting it to "20 bytes" and setting max_batch_bytes to say 110 bytes (resulting in max 5 transactions)

Yes, I had no choice but to do so to continue testing.

**Comment by marbar3778** [comment]
`max_batch_bytes` was removed in: https://github.com/tendermint/tendermint/pull/5800 for the time being. This fix will be released in 0.34.1.
