### ISSUE TITLE
rpc/lib/rpc_test.go sets Logger in `init()`

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#557]
This is a no-no. Not sure what a better solution is.

References:
https://github.com/tendermint/tendermint/blob/master/rpc/lib/rpc_test.go#L90
https://github.com/tendermint/tmlibs/blob/master/log/testing_logger.go#L19

**Comment by ethanfrey** [comment]
What init() is being used for in this case (global setup), can be done with `TestMain` in a cleaner way.

http://cs-guy.com/blog/2015/01/test-main/

https://github.com/tendermint/tendermint/blob/master/rpc/client/main_test.go

**Comment by melekes** [comment]
> What init() is being used for in this case (global setup), can be done with TestMain in a cleaner way.

yep, let's rewrite using `TestMain` approach

**Comment by melekes** [comment]
Done at d578f7f81edde980fa2cdd15a3220f667e8f697e
