### ISSUE TITLE
Replace tendermint/libs/log with github.com/sirupsen/logrus

### ISSUE THREAD

**Issue by alessio** [tendermint/tendermint#5572]
`github.com/tendermint/tendermint/libs/log` seems outdated and a tag convoluted and should be replaced with a modern, flexible, and syslog-friendly package.

I've been studying and using `github.com/sirupsen/logrus` lately. On top of a clean and simple interface, it offers a seamless integration with syslog - [see here](https://github.com/sirupsen/logrus#hooks) for more information.

I'm happy to contribute to it.

Thanks for considering.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
Yeah, I'd be in favor of improving the logging infrastructure. We had some brief discussions on this a few months back, but haven't prioritized it. You may want to have a look at this issue as well: https://github.com/tendermint/tendermint/issues/3428#issuecomment-623554264.

**Comment by melekes** [comment]
let's consolidate in one issue. I'll close this one.
