### ISSUE TITLE
test: simplify maverick implementation for easier maintenance

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5575]
## Summary

Currently we take a copy of the entire consensus package and modify that in order to obtain the desired functionality of the maverick node. In the long run this is going to be annoying when any update to the consensus package means a second update to the maverick package.

## Problem Definition

The maverick package is difficult to maintain and should be reduced in size. The reason why I copied the entire package was a) it was fast and easy and b) it meant not touching the consensus package at all

## Proposal

In the `state` struct we have these fields:

```
// some functions can be overwritten for testing
	decideProposal func(height int64, round int32)
	doPrevote      func(height int64, round int32)
	setProposal    func(proposal *types.Proposal) error
```
It might be possible then to create just an alternate constructor method like `NewMaverickState()` which uses the same `state` struct but instead implements different functions for each of the above fields such that we can mimic the behavior.

A bonus might also be to create another field: `doPrecommit` which mimics `doPrevote` and allows for greater options for the maverick twin. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Looked into implementing this proposal but I don't think it's going to be possible, theres checks elsewhere stopping sending multiple votes and there's no option to be selective (i.e. send half the peers one vote and send the other half another vote).

I think the best option is to write a custom reactor using the new p2p framework, which is bare and just comprises of the minimum logic to send vote/proposal messages to selected peers.

**Comment by cmwaters** [comment]
To just zoom out a little, the original goal of having a maverick node was to be able to test the evidence handling lifecycle in an e2e setting. Initially I thought that we would spin up a node that would perform some misbehaviour and observe the result. This would be able to assert that detection of misbehaviour worked correctly and handling of evidence worked correctly. 

More recently, I have thought of a smaller, easier to implement solution which could at least test the handling of evidence and wouldn't require the construction of an entire separate node. This would be to form and inject ready made evidence to a random node via the RPC endpoint `/broadcast_evidence`. The testnet would then assert that evidence was eventually committed on chain.

Obviously this means that we won't be able to analyse detection but I think this is sufficiently covered by unit tests. And detection in the maverick node is already limited by our ability to come up with attacks.

What do you guys think @melekes @alexanderbez

**Comment by alexanderbez** [comment]
I like the idea! Although a bit sad we can't test the detection of evidence, but this is a great middle ground I think! 🎉

**Comment by melekes** [comment]
> To just zoom out a little, the original goal of having a maverick node was to be able to test the evidence handling lifecycle in an e2e setting. Initially I thought that we would spin up a node that would perform some misbehaviour and observe the result. This would be able to assert that detection of misbehaviour worked correctly and handling of evidence worked correctly.
> 
> More recently, I have thought of a smaller, easier to implement solution which could at least test the handling of evidence and wouldn't require the construction of an entire separate node. This would be to form and inject ready made evidence to a random node via the RPC endpoint `/broadcast_evidence`. The testnet would then assert that evidence was eventually committed on chain.
> 
> Obviously this means that we won't be able to analyse detection but I think this is sufficiently covered by unit tests. And detection in the maverick node is already limited by our ability to come up with attacks.
> 
> What do you guys think @melekes @alexanderbez

I'm in favor of this. Kinda reminds me https://github.com/tendermint/tendermint/issues/4953
