### ISSUE TITLE
Ledger Nano S support for validator signing

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#558]
Provide another implementation of the `types.Signer` interface for signing on the Ledger Nano S.

https://github.com/tendermint/tendermint/blob/master/types/priv_validator.go#L60

Note it must be stateful and satisfy the same logic as our default signer (https://github.com/tendermint/tendermint/blob/master/types/priv_validator.go#L206) to prevent double signing!

**Comment by zramsay** [comment]
https://github.com/tendermint/go-crypto/pull/37

**Comment by ebuchman** [comment]
Replaced by https://github.com/tendermint/tendermint/issues/647 and ongoing work in https://github.com/tendermint/tendermint/pull/637
