### ISSUE TITLE
signer_client: crash parsing GetPubKeyResponse

### ISSUE THREAD

**Issue by tarcieri** [tendermint/tendermint#5581]
I'm working on upgrading Tendermint KMS to use a proto-based Secret Connection.

In the course of doing so, I managed to send a malformed message that crashed Tendermint with a NPE. This is in the context of a `stargate-4` gaiad process but that's orthogonal:

```
$ gaiad start
I[2020-10-27|19:34:52.553] starting ABCI with Tendermint                module=main
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xfb5d76]

goroutine 1 [running]:
github.com/tendermint/tendermint/privval.(*SignerClient).GetPubKey(0xc00115e2e0, 0xc00067e960, 0xa, 0xc00115e2e0, 0x0)
        github.com/tendermint/tendermint@v0.34.0-rc4.0.20201005135527-d7d0ffea13c6/privval/signer_client.go:85 +0x1d6
```

That corresponds to this `nil` dereference of `resp.PubKey`:

https://github.com/tendermint/tendermint/blob/v0.34.0-rc4/privval/signer_client.go#L85

```go
pk, err := cryptoenc.PubKeyFromProto(*resp.PubKey);
```

The `resp.PubKey` field should probably be non-nullable if that's still possible post-gogoproto.

**Comment by marbar3778** [comment]
We can use non-nullable for now but post gogoproto we can migrate to optional field which was added in protoc 3.12 and made available without an experimental flag in 3.13. (https://github.com/protocolbuffers/protobuf/blob/master/docs/implementing_proto3_presence.md).
