### ISSUE TITLE
p2p/conn: problems implementing Protobuf-based secret connection 

### ISSUE THREAD

**Issue by tarcieri** [tendermint/tendermint#5584]
I'm working on integrating Tendermint KMS with the new Protobuf-framed Secret Connection protocol. WIP is here:

https://github.com/iqlusioninc/tmkms/pull/200

I've managed to implement the handshake and successfully parse an incoming `PacketPing` as a proto-framed message.

However, in attempting to send a `PacketPong` response (`[0x02, 0x12, 0x00]`) if I have it framed correctly I'm both crashing  Tendermint (#5581) which seems to be trying to interpret this response as a public key, and getting a message back from Tendermint which I can't decode as a `Packet`.

That message is:

```
[0x02, 0x3a, 0x00]
```

That seems to correspond to:

- Length prefix: 2 bytes
- Field identifier: 7
- Wire type: 2
- Field length: 0

However, the `Packet` type (for which I'm successfully able to parse a `PacketPing` the first frame) is a `oneof` which goes up to 3, so I'm not sure what a field ID of 7 is supposed to indicate:

https://github.com/tendermint/tendermint/blob/730e165/proto/tendermint/p2p/conn.proto#L19-L25

**Comment by marbar3778** [comment]
I think you are looking at this message oneof: https://github.com/tendermint/tendermint/blob/c36d5c629acb468ce6a2ece9df620b4caf416bff/proto/tendermint/privval/types.proto#L65-L76 which would be ` PingRequest            ping_request             = 7;` which seems to match that message `[]uint8([]byte{0x3a, 0x0})`

**Comment by tarcieri** [comment]
Aha, thanks! So the first message was a `PubKeyRequest`, and that's why #5581 is occurring when I send it an otherwise empty reply (as I was interpreting that as a `PingRequest).
