### ISSUE TITLE
p2p: improve detection and advertisement of own address

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5588]
The current P2P stack simply advertises the listen address to other peers. However, the default value is `0.0.0.0` (all interfaces), and this address is useless to other nodes. Similarly, nodes often have private IP addresses on their local interfaces which are NATed to public addresses (common both for public clouds and home connections), and these shouldn't be advertised since they're not usable - unless the peer is on the same private network, in which case they should be.

See https://github.com/tendermint/tendermint/pull/3516#issuecomment-587555940 and https://github.com/tendermint/tendermint/issues/3716#issuecomment-669797580.

**Comment by tychoish** [comment]
We talked about this today, in person, and I wanted to update this ticket with some details of that conversation. 

- When listening on potentially mutliple interfaces (e.g. `0.0.0.0`) it's very hard to figure out, what the correct mapping of local interfaces to publicity routable addresses, at best we could just *guess* but this would probably produce some wrong responses which might be frustrating. STUN provides a way to poke through NATs and discover the public addresses to advertise, and that might help improve how we report interfaces, but wouldn't really improve "which" addresses we would want to interface.
- This is not a regression in the new p2p stack but would be a nice feature to be able to have. 

I think there are really two solutions: 
- We write a lot of code to attempt to solve this problem, with the knowledge that there will still be some cases that slip through, or cases where we cannot guess the best endpoint to advertise. 
- We explicitly disallow listening on `0.0.0.0` and make nodes fail to start in this mode, forcing users to explicitly pass the interface that they want us to listen on and what the public. This is a breaking change, but not necessarily a bad one. 

In light of this, it definitely makes sense to push this out till at least v0.36, but I think it requires a bit more thought/decision.

**Comment by Wondertan** [comment]
According to the recent discussions regarding the transition to libp2p stack, I suggest adding that as a solution, as libp2p solves the described issue out of the box and promotes all the p2p nodes to listen on `0.0.0.0`.

**Comment by williambanfield** [comment]
Thanks for the info @Wondertan. I'm curious how they solve this problem, would you mind linking to some documentation to help give me a sense of what the libp2p project does in this case?

**Comment by Wondertan** [comment]
@williambanfield,
* There is utility [identify protocol](https://github.com/libp2p/specs/tree/master/identify) which is run between libp2p Hosts on connection establishment by default. It has [observedAddr](https://github.com/libp2p/specs/tree/master/identify#observedaddr) message field, which peers exchange with each other. E.g. NATed peer A connects to public peer B. Peer B accepts the connection and sees the real remote address and sends it back to peer A.
* There is also an optional [AutoNAT](https://github.com/libp2p/go-libp2p-autonat) helper protocol. I didn't find a spec for it, but it essentially allows client peers to request even more information regarding their NAT status, including public addresses, by attempting to dial those. For example, some seed nodes can be volunteering by running the server-side of AutoNAT, and any other node can request its NAT status and public address.
* In case of node operator knows the network conditions, it can directly specify what address the node should listen to and advertise or not. I can't think of a good doc to reference that, but as a reference, I'll show the Filecoin networking config which provides all those fields. Note that Filecoin uses libp2p and those configs fields are passed to the libp2p subsystem. 
![image](https://user-images.githubusercontent.com/22449364/129746372-94a36c63-0a62-4eb3-beba-94e09e7e0b8d.png)
Filecoin does not implement anything here itself and delegates everything to libp2p, besides config format, as libp2p does not mandate a config format for its users. 
* You might be wondering about the ports as well. Libp2p relies on TCP/UDP(for QUIC) [port reusing](https://lwn.net/Articles/542629/) option which allows nodes to listen on and dial from the same port, so effectively libp2p peer can have only one port for multiple in/outbound connections.

Therefore, in case a node listens on multiple network interfaces, it can have multiple remote addresses, which it can figure out by simply connecting to some other peers using those network interfaces or by simply knowing them in advance from the configuration.

**Comment by tychoish** [comment]
This looks super solid. I think you're right @Wondertan that libp2p offers an additional possible solution to this problem and I should have (correctly) outlined it as a thing we were considering. 

I think the general path of pushing this off to 0.36 continues to be the correct one.
