### ISSUE TITLE
p2p: include peer's node ID in handshake

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#5590]
A user reported trying to write a Tendermint proxy that would proxy P2P connections on a single IP address to multiple Tendermint nodes on the backend. To do this, the initial handshake needs to include the ID of the target peer we're trying to reach.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by tychoish** [comment]
I believe that the new p2p stack successfully disallows connections from nodes that it's already connected to (modulo bugs), which I think means that this might be close-able, if I'm reading the goal correctly. 

I'm also reasonably sure that this doesn't need to be in the v0.35 milestone, but I might be reading that wrong.

**Comment by tychoish** [comment]
I'm going to go ahead and close this issue. Reading it (and my previous response) I'm not sure that it makes sense to do that this time without a specific user requirement, as this would (probably) be a breaking change and given the roadmap for libp2p, I'm not sure if this makes particular sense right now.
