### ISSUE TITLE
Docs Improvements [Tracking Issue]

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5594]
Tracking issue for various docs improvements tracked in https://github.com/tendermint/tendermint/projects/11, just so I can include it in the 0.35 milestone. 

Highlights include:

* Versioned docs 
* [Docs "refactor"](https://docs.google.com/document/d/1lBY3hujqgQCR6t9jJgSjxswLNp6NvSA3mngHX4zDPkk/edit?usp=sharing)
* And many small fixes 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
As an update on this:
- We have added versioned docs
- We have made many of the modifications mentioned in the Doc "refactor" doc

For 0.36 we should look at completing the following:
- Reduce the amount of guides https://github.com/tendermint/tendermint/issues/3808#issuecomment-909011697
- Update the guides and docs to include the changes in ABCI++
