### ISSUE TITLE
Upgrade tooling

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5595]
## Summary / Problem definition

Marko and I have been kicking around the idea of "upgrade tooling" for about a year now. The motivation here is that it's pretty painful to upgrade Tendermint versions across any kind of block protocol-breaking change, because chains have to restart and lose all their history. With the introduction of things like starting chains at arbitrary heights, as well as the forthcoming work to version the heck out of everything, it should be possible to make this upgrading process a little smoother. 

## Proposal

This feature hasn’t been designed yet. Whoever takes it on should begin by talking to users to figure out what the requirements and the nice-to-haves are, and should probably investigate prior art in other blockchain networks. They should also consider how this plays with the Cosmos SDK upgrade module. Then a design doc can be drafted, taking into consideration feasibility and other constraints. 

Possible approaches include:

* Dump all application state/history into a database and give people tools for querying it 
* Migrate old blockchain history to a new format 
* More?? 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
I would like to surface a few ideas and comments I have about this.

So there's two roads that I see us taking and potentially we can go down both. One is to use some versioning system such that block protocol breaking changes don't require a hard reset and the start of a new chain. I am writing an RFC about it at the moment but the gist is to support "soft" upgrading of a set of data structures. This of course won't prevent the fact that there will still be major breaking tendermint releases that will require networks to hard fork (but will hopefully prolong the time between major releases). This brings me to the second road we can take which is to generally make it easier when the time comes to do a hard fork, to do it.

I would like to enumerate a few thoughts on the latter of these two roads (i.e. making hard resets easier on networks) but first it would probably help to explain the current process:

> The recommended upgrade path for block protocol-breaking upgrades is currently to hard fork the chain (see e.g. [cosmoshub-3 upgrade](https://blog.cosmos.network/cosmos-hub-3-upgrade-announcement-39c9da941aee)). This is done by halting all validators at a predetermined height, exporting the application state via application-specific tooling, and creating an entirely new chain using the exported application state.
 
This is just stolen from something Erik wrote but I didn't feel like regurgitating everything again. Anyway, we can help node runners perform this process easier by offering them a few things.

1. Make it easier for networks to schedule all nodes to halt together: (See #5645) (of course there must be consideration that this doesn't add any unnecessary vulnerabilities.

2. Add some tooling that makes it simple to swap between two binaries (in with the new tendermint out with the old). The Cosmos SDK already have something called [cosmovisor](https://github.com/cosmos/cosmos-sdk/tree/master/cosmovisor) which I believe does something similar.

3. Make it easier to export state and generate a new genesis from an existing one. This is also functionality that I think the Cosmos SDK have already implemented and it would be useful to upstream.

If I was to look at this from a another angle, say an idealists view, I would want some sort of cli setup or whatever is that validators use these days where I could download the binary, set a height (either independently or agreed upon by the network) and let tendermint do its :sparkles:  **magic** :sparkles:

**Comment by marbar3778** [comment]
> Make it easier to export state and generate a new genesis from an existing one. This is also functionality that I think the Cosmos SDK have already implemented and it would be useful to upstream.

I don't believe Tendermint cant do this. We don't know what is in the AppState field in genesis and how to change it. https://github.com/tendermint/tendermint/blob/cc247c091b85eff3c5233fab40933d9f0cd8c7ef/types/genesis.go#L46-L46. Unless you are thinking of adding some sort of hooks for applications to register migration steps?

**Comment by cmwaters** [comment]
> Make it easier to export state and generate a new genesis from an existing one. This is also functionality that I think the Cosmos SDK have already implemented and it would be useful to upstream.

This statement was definitely more on the side of vague wishful thinking than concrete action. I'm not so well versed on how this actually works. Is there are a strong reason why we merge application and tendermint stuff into a single genesis? Could it be better to separate these and perhaps just use the AppHash to confirm that nodes have the same initial state. This would definitely make it easier to generate a new genesis from the existing blockchain.

Alternatively if we wanted to leave it in there we could come up with some way of getting the information. Perhaps sneak it into Endblock which would trigger a new genesis and an upgrade.

**Comment by cmwaters** [comment]
As another remark I feel that improving the Node (go) API (#3690) to programmatically better control the node would be a good idea and may assist with these sort of upgrades. This could also be paired with internalising a lot of the other functionality.
