### ISSUE TITLE
Adopt ZIP 215

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5596]
## Summary

 Different Ed25519 implementations verify signatures in subtly different ways. This will pose a problem for future implementations of Tendermint which may use different Ed25519 libraries. ZIP 215, from the Zcash Foundation team, “settles the situation by explicitly defining the Ed25519 validity criteria and changing them to be compatible with batch validation.” 

## Proposal

We should adopt ZIP 215, for more consistent signature verification for all Tendermint implementations.

Next steps:

- [x] Merge RFC in tendermint/spec: https://github.com/tendermint/spec/pull/144 
- [ ] Migrate tendermint/tendermint to use  https://github.com/hdevalence/ed25519consensus 
- [ ] Update related documentation 

Note that this should be treated as a breaking change.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Since https://pkg.go.dev/filippo.io/edwards25519 was released, there is the potential to move https://github.com/hdevalence/ed25519consensus straight into Tendermint as the only change would be to the verify function.

**Comment by robert-zaremba** [comment]
Recently FB released the paper: [Taming the many EdDSAs](https://research.fb.com/wp-content/uploads/2020/10/Taming-the-many-EdDSAs.pdf) with the efforts to standarize ed25519 signatures:
> We give a formulation of Ed25519 signaturescheme that achieves the highest level of security, explaining how each stepof the algorithm links with the formal security properties. 

What's interesting, they claim that the ZIP-215 approach is _"incomplete" fail-fast check which only rejects signatures if any of the first 3 most significant bits are set. The latter implies that non-canonical signature values might be accepted_
IIRC this is true, though I don't when  and how practically that increases the security risks.

**Comment by hdevalence** [comment]
@robert-zaremba I don't think that's correct, ZIP215 requires that the `s` value is fully reduced.  See the ZIP215 specification for the exact language on that point.
