### ISSUE TITLE
[evidence] accept evidence from the previous epoch

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5600]
**Currently, the following situation is possible:**

chain A is going to upgrade at height 1000. A group of malicious validators perform a light client attack (or any kind of attack really) at height 999 and potentially fool the target light client (or more light clients). There's no punishment since there was no time for evidence propagation and chain A successfully upgraded at height 1000. Therefore, there's a security hole in the current design of upgrades in IBC.

**What we need to do:**

Zarko: "evidence handling still need to be in place for an extended period of time (unbonding period basically). We formally need to support evidence handling between two chains, i.e., deal with old evidence on the new chain."

The problem is Tendermint does not have a notion of epochs. From its perspective, the old chain is completely different chain, which is not related to the new one. We'll probably need to introduce such a relation between two chains, so the evidence from the old one could be processed on the new chain.

**Comment by cmwaters** [comment]
It also doesn't have to be directly before the chain upgrades. For example, if the chain is currently at height 1100 (with the upgrade happening at height 1000) and a light client wants to verify a transaction at height 999 or before, it would also then be vulnerable to a 1/3+ attack. 

I think this needs to be coordinated with the upgrade tooling work as well. For example if we were to decide that the best option for upgrading would be a soft network upgrade using the same chainID and versioning then this problem becomes rather trivial. If we decide to stay with something similar to what we have now then we would need to have some overlap period where one chain can recognise evidence from another chain.
