### ISSUE TITLE
nomenclature: rename consensus params to params

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5630]
## Summary

The current `ConsensusParams` struct looks as follows:

```
type ConsensusParams struct {
	Block     BlockParams     `protobuf:"bytes,1,opt,name=block,proto3" json:"block"`
	Evidence  EvidenceParams  `protobuf:"bytes,2,opt,name=evidence,proto3" json:"evidence"`
	Validator ValidatorParams `protobuf:"bytes,3,opt,name=validator,proto3" json:"validator"`
	Version   VersionParams   `protobuf:"bytes,4,opt,name=version,proto3" json:"version"`
}
```
Although these parameters are read by the consensus engine they are stored in `state.State`, used by the `BlockExecutor`, the `evidence.Pool` and most importantly governed by the app. 

## Proposal

I feel that these parameters are much more generalized than just within the scope of consensus and thus propose that when the timing is right we rename them to something like `Params` 

@marbar3778 mentioned that it might be good to aggregate together these nomenclature changes so we can agree on them and implement them all at once alongside a blog post to announce the changes.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
`Params` would suffice I think if it's in a pkg that provides context. What would be the package here?

**Comment by cmwaters** [comment]
Well currently it's residing in `proto/tendermint/types`. It would probably stay there until we wanted to do something about the types directory in which case it would probably be best suited in the `state` package

**Comment by alexanderbez** [comment]
So it'd be `types.Params`? I think that's probably fine as long as `Params` encapsulates everything.

**Comment by melekes** [comment]
I feel like `Params` is too abstract and does not really reflect what it this thing is.

**Comment by alexanderbez** [comment]
> I feel like `Params` is too abstract and does not really reflect what it this thing is.

Right, this is why I mentioned the package, because they package is what provides context. `types.Params` is a bit too ambiguous, but `consensus.Params` is perfectly fine.

**Comment by tessr** [comment]
> @marbar3778 mentioned that it might be good to aggregate together these nomenclature changes 

Do we have a list of proposed (or decided) nomenclature changes anywhere?
