### ISSUE TITLE
Check if both numerator and denominator are negative in ValidateTrustLevel

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#5651]
Noted during the IBC audit of our interfaces to the Tendermint light client.

**Comment by tessr** [comment]
Does this need to get in for 0.34.0?

**Comment by cwgoes** [comment]
As far as I can tell, it's not a *bug* per se, just potentially confusing - still, it'd be nice!

**Comment by tessr** [comment]
Alright, let's backport it /cc @cmwaters
