### ISSUE TITLE
Why Content-Type is text/json not application/json

### ISSUE THREAD

**Issue by enfipy** [tendermint/tendermint#5660]
**Tendermint version**: v0.34.0-rc6 (master)

**What happened**: Content-Type for RPC is not right. There's no such thing as `text/json` but there's `application/json`. More details [here](https://github.com/paritytech/jsonrpc/pull/597#issuecomment-726730895). Link for `tendermint` code: https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/http_json_client.go#L175.

**Have you tried the latest version**: yes

**Comment by tessr** [comment]
Thank you for trying RC6 and helping us with testing! We'll have a fix for this shortly.
