### ISSUE TITLE
Use linter to detect unchecked arithmetic

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5662]
## Summary

We need to protect against integer under/overflow. One possibility is to add a new checked integer type (see https://github.com/tendermint/tendermint/issues/2692), but the team has discussed this and thinks it would be a bit onerous. A more lightweight solution is to add a linter that can detect unchecked integer arithmetic and warn us before we introduce it. 
____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by williambanfield** [comment]
It looks like [marko suggested moving all ints to uints](https://github.com/tendermint/tendermint/issues/2684#issuecomment-727906508). Would we need to do both of these changes?

Also, is there an example of the overflow checking we're considering currently in the codebase? cc @marbar3778

**Comment by creachadair** [comment]
I'd like to better understand the intended scope of this issue. 

Many of the integral operations performed by a program (e.g., loop and slice indexing, allocation sizes, etc.) are already checked by the runtime. Even if we _could_ check those, there is probably not much to be gained by doing so.

Are there more specific contexts in which we're concerned about overflow conditions, e.g., during transaction validation? Relatedly: Do we have an understanding of what should happen in such cases?

It's pretty easy to locate all the program expressions involving integral values and arithmetic operations, but that is a very large data set, and I don't think we are well-served by trying to hand-audit that many locations.
