### ISSUE TITLE
Circular dependency with IAVL? 

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5694]
As we were doing the release, @marbar3778 mentioned that Tendermint now has a dependency on IAVL for testing... but IAVL already has a dependency on Tendermint 😬   We should consider trying to disentangle these two repos.

**Comment by erikgrinaker** [comment]
There are a few options here:

* Don't use IAVL for testing in Tendermint.
* Split out the `crypto` package so IAVL can depend on it rather than Tendermint.
* Migrate all proofs to `ics`.

**Comment by marbar3778** [comment]
>     * Don't use IAVL for testing in Tendermint.
> 
>     * Split out the `crypto` package so IAVL can depend on it rather than Tendermint.

The top two are the simplest with one being the least breaking. Although I do like 2 and since the pkg is rarely touched it would not need much maintenance but maintenance of the repo is unclear and would lead to breakage. 

>     * Migrate all proofs to `ics`.

It's unclear how many teams this will affect.

**Comment by melekes** [comment]
My bad 😞 I wanted to write an actual test with proofs and everything, but didn't account for the circular dependency between the repos.

> Migrate all proofs to `ics`.

extracting proofs seems like the cleanest solution to me.

**Comment by marbar3778** [comment]
Are we fine with removing the abci_query test for now?

cc @cmwaters

**Comment by cmwaters** [comment]
Yeah I guess so. I think the entire `abci_query` RPC endpoint needs to be rethought. I think it was a helpful tool a while back but now we have fully fledged SDK's to build applications on top off I don't think having this call is necessary. The SDK should and I think does support the application with querying its data

**Comment by marbar3778** [comment]
>  think the entire `abci_query` RPC endpoint needs to be rethought.

We would need to think of a way of handling light client queries, though. I think the main use case was light client queries and the sdk used it as a workaround for IAVL issues.  Do you have something in mind with this?

**Comment by cmwaters** [comment]
But the light client doesn't know how to verify the proofs - it has to be injected in and it's messy.  I think the best thing would be to provide an interface so that applications can also implement light nodes (ABCILight lol)

**Comment by marbar3778** [comment]
> But the light client doesn't know how to verify the proofs - it has to be injected in and it's messy. I think the best thing would be to provide an interface so that applications can also implement light nodes (ABCILight lol)

this is how its currently done, the application registers the proof format for verification. This is why applications should integrate the light client in their app and not use Tendermints. For example: https://github.com/cosmos/cosmos-sdk/pull/9155
