### ISSUE TITLE
ci: run goreleaser prior to release

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5695]
For 0.34.0 we ran into a issue where goreleaser attempted to build Tendermint for 32-bit arch and failed causing the overall job to fail and no builds being posted on the release page. If we had a pre build stage in the release process this could have been avoided. 

Current flow is:

pull down rcX-vX.X.x -> create tag -> push tag. at this point go release builds binaries and creates the release on the release page. 

Updated flow can/should be:

pull down rcX-vX.X.x -> create release/vX.X.x branch -> pre run goreleaser -> successful build of all binaries -> create tag -> push tag -> goreleaser build binaries and create release

A flow similar to the updated flow is longer but prevents failures from arising in the middle of creating a release.

**Comment by alexanderbez** [comment]
ACK
