### ISSUE TITLE
node: skip fast sync if validator has 1/3+ of the voting power and height is > 0

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5696]
Refs https://github.com/cosmos/cosmos-sdk/issues/7505

Right now we only skip fast & state sync if it's a 1 validator network. The proposal is to also skip fast & state sync if there are more than 1 validators, but the validator which has failed had 1/3+ of the voting power. We know for sure that no new blocks were minted since 2/3+ of the voting power is required, hence we can safely skip fast and state sync.

**Comment by njmurarka** [comment]
Do we have any info on which versions of Tendermint this affects?

**Comment by melekes** [comment]
I believe all of them.

**Comment by tessr** [comment]
> I believe all of them.

Wait, but this wasn't reproducible using SDK 0.40 (built with Tendermint 0.34 RCs).

**Comment by erikgrinaker** [comment]
We could also consider simply switching to consensus if fast sync isn't able to find any blocks for e.g. 30 seconds, as a fallback. Don't really see any downside in doing so.

**Comment by njmurarka** [comment]
My two cents is not to wait for a timeout. If there is no possible new blocks can exist, fast since should not happen. In the particular use case where the validator has 67%+ voting power, they should be be able to create blocks without delay. This is particularly important for testing environments.

**Comment by melekes** [comment]
Added a note in cosmos-sdk re why we can't skip fast sync if height is zero (or otherwise significantly less than) the actual  height of the network https://github.com/cosmos/cosmos-sdk/issues/7505#issuecomment-733699325.

**Comment by melekes** [comment]
Closing in favor of https://github.com/tendermint/tendermint/issues/5718.

**Comment by njmurarka** [comment]
Just so I understand... so we have closed this issue and this will now get resolved in 5718?

**Comment by melekes** [comment]
No, we've realized that the proposed solution does not consider a few corner cases - https://github.com/tendermint/tendermint/pull/5717#discussion_r530347672. There's no solution other than logging the progress (or absence of such, e.g., when your node does not have any peers) and make sure we switch to a consensus after a specific timeout.

**Comment by njmurarka** [comment]
So the plan then is that if the validator has sufficient power but cannot peer, after a given timeout, it starts doing consensus anyways?

I understand the case where if you lost your local blockchain data, there is a corner case that you could start and not even know you missed some blocks... so I am assuming the expectation is if you know this, you are responsible to ensure your node peers before that timeout occurs?

**Comment by melekes** [comment]
> so I am assuming the expectation is if you know this, you are responsible to ensure your node peers before that timeout occurs?

yes. the timeout is sufficiently large though
