### ISSUE TITLE
blockstore: why do we save seen commit and block commit?

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5698]
## Summary

When we save a block, either through consensus or through fast sync we call `SaveBlock()` this saves both the block commit and seen commit. I understand that persisting the latest seen commit is necessary so that validators in the next round can propose a block with that commit in it. But it seems that we're saving all seen commits and the only time they are removed is when the block is pruned. This therefore seems like we are unnecessarily storing duplicate commits

## Proposal

Persist only the latest seen commit

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
Yeah, I don't think we need to store all seen commits. We only need one for the latest height. @ebuchman is that right?

**Comment by ebuchman** [comment]
I believe that is correct yes, but I'm not sure if these SeenCommits might be helpful in case we need to prove Amnesia attacks? At least before we have a more coherent strategy for this cc @milosevic

**Comment by cmwaters** [comment]
Hmm I would think not because the light client already has both of the commits from the conflicting light blocks it got from the primary and witness. It's more a problem of not knowing about between those that voted again in the later commit, which of them incorrectly changed locks (i.e the byzantine nodes) and which correctly changed them. 

I guess it would still be nice for @milosevic to confirm that this rationale is correct. In any case, keeping the seen commits for heights within the unbonding period would still save a lot more data than keeping them for the entire history.

**Comment by milosevic** [comment]
My understanding is that for evidence handling purpose we need to have access to a blockchain (not even sure if commits at all are needed there). As Callum correctly pointed out, light client attack evidences capture sufficient information need to verify and process them. Regarding amnesia in particular, the current protocol requires access to all votes (prevote and precommit) between conflicting heights, but we would not rely on seen/block commit to get those precommit messages. I don't have a full picture re usage of seen/block commit, but if evidence handling is the only concern, in my view, that does not look like a problem.
