### ISSUE TITLE
blockchain/vX: ensure we switch to consensus after timeout

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5718]
It's been reported that in a certain case it may look as the node halted (when it tried to fast sync and was waiting for peers). We should a) check we switch to consensus after timeout b) log any errors during the fast sync c) log absence of progress (i.e. "Tried to sync, but found no peers...") to improve UX.

Refs https://github.com/cosmos/cosmos-sdk/issues/7505

**Comment by njmurarka** [comment]
May I suggest a flag that I can pass that forces the node to not wait for peers and progress with consensus. Basically, skip that timeout...

**Comment by melekes** [comment]
> May I suggest a flag that I can pass that forces the node to not wait for peers and progress with consensus. Basically, skip that timeout...

The flag already exists: `--fast_sync=false`

**Comment by melekes** [comment]
My plan is:

- [ ] define clear termination criteries in `blockchain/doc.go`
- [ ] make sure both v0 and v2 abide them
- [ ] check we're logging errors
- [ ] check we're logging absence of progress

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/bf388aca3a52375336470f5971a731c078474be3/blockchain/v2/reactor.go#L413

I think this needs to be modified so we switch to consensus anyway if the timeout (60s) expires.
