### ISSUE TITLE
Have tendermint.core report its version on handshake

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#572]
**FEATURE REQUEST**

To make sure that an ABCI app will work with a given tendermint version, it would be nice to have core report its version during handshake in info. This way, an ABCI app can decide if it is OK to run on the given tendermint version.

Sidenote: we think about encoding a version (abci or core) into the appstate hash, so an ABCI app with a different version will be excluded from the chain if it doesn fit to the other versions.

**Comment by antoineherzog** [comment]
i agree !

**Comment by adrianbrink** [comment]
It could be an idea for core to send that information along with InitChain and then InitChain has to respond with its own version number.

https://github.com/tendermint/abci#initchain

**Comment by antoineherzog** [comment]
at the end, the ABCi app should decide if it can run or not with the tendermint node version.

**Comment by srmo** [comment]
Why initChain()? Isn't that supposed to run only for fresh chains? Using this in handshake is for longer running chains, to make it easier for migration scenarios

**Comment by ebuchman** [comment]
So in the `Info` call we could add some arguments, including version.

We should probably set the chain_id in the `InitChain` so we dont have it twice between app and tendermint

**Comment by antoineherzog** [comment]
@srmo i agree with you. We should make it easy about migration scenario.

**Comment by srmo** [comment]
Additionally, thinking about the upcoming np-empty-blocks change.
Can we think about a set of configuration options that migth be worth adding here? This all might help with the scenario: "add node config/version to appstate-hash" so we make sure every ACBI app uses the same version. Why for no-empty-blocks? Because we generate a new appstate on each new height, based on previous appstate and height etc, so an app running on a no-empty-blocks node will have a different hash than an app running on a empty-blocks node.

**Comment by ebuchman** [comment]
merged into ABCI (https://github.com/tendermint/abci/blob/master/types/types.pb.go#L596), about to be merged into tendermint 0.11

**Comment by srmo** [comment]
Love you guys!
