### ISSUE TITLE
dev mode

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5721]
## Summary

There are some features of tendermint that are meant for testing (https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_commit) yet we expose it in production. 

## Proposal

A dev mode will allow us to expose functionality that should not be exposed in production. 

Put routes and other useful developer oriented items under a dev flag or dev mode.

Dev mode:

- https://docs.tendermint.com/master/rpc/#/Tx/broadcast_tx_commit
- index all txs

These are two items that I have encountered. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
I wonder if this would be a breaking change for anyone. (I sure hope not.)

**Comment by marbar3778** [comment]
> I wonder if this would be a breaking change for anyone. (I sure hope not.)

Ah, it would most likely be a breaking change. 😢

**Comment by melekes** [comment]
Yep, removing indexing and `/broadcast_commit` are both massively breaking changes. While I agree with removing `broadcast_commit`, removing indexing will degrade user experience since one won't be able to get transaction results via `/tx` and `/tx_search` anymore.

**Comment by marbar3778** [comment]
oh, I mean when in dev mode we force index everything.

**Comment by melekes** [comment]
Ah, okay then.

**Comment by marbar3778** [comment]
Putting this here as a note, an example of something meant for testing being used in prod https://github.com/cosmos/cosmos-sdk/pull/9408
