### ISSUE TITLE
error reading message: proto: wrong wireType = 2 for field Height

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5735]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 243ff4b43 latest master

**ABCI app** (name for built-in, URL for self-written if it's publicly available): merkleeyes https://github.com/melekes/jepsen/tree/main/merkleeyes

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS
- **Install tools**:
- **Others**:

**What happened**:
when I ran Tendermint and my app, connected via socket, I got `error reading message: proto: wrong wireType = 2 for field Height` error

**What you expected to happen**:
no errors

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
E[2020-12-02|23:15:56.982] Connection error                             module=abci-server err="error reading message: proto: wrong wireType = 2 for field Height"
E[2020-12-02|23:15:56.986] Connection was closed by client              module=abci-server
E[2020-12-02|23:15:56.986] Connection was closed by client              module=abci-server
E[2020-12-02|23:15:56.986] Connection was closed by client              module=abci-server
```

```
E[2020-12-03|11:04:41.953] consensus connection terminated. Did the application crash? Please restart tendermint module=proxy err="read message: EOF"
E[2020-12-03|11:04:41.953] Error in proxyAppConn.BeginBlock             module=consensus err="read message: EOF"
```

**Config (you can paste only the changes you've made)**:
no config changes

**node command runtime flags**:
no flags

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:
same issue here https://stackoverflow.com/questions/65085698/tendermint-get-error-when-start-tendermint-node-as-per-the-sample

it works when I checkout `v0.34.0` and install it, but not with the latest master

**Comment by marbar3778** [comment]
This was due to different version of Tendermint proto files being used. Master contains a breaking change with the indexes of the request and response oneofs. We should update and specify clearly what versions should be used.
