### ISSUE TITLE
statesync: how to best discover snapshots

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5742]
## Summary

Currently, State sync will wait to discover snapshots. If a nodes address book is full it will not be able to discover snapshots. In some cases the address book is not full but the node is still not able to discover snapshots, even if it is known snapshots are being taken by other nodes. 

## Problem Definition

Discovering snapshots with a full address book is not possible. 

## Proposal

1. Disconnect from some peers in hope of finding new ones

2. A mix of 1 and falling back to fast sync if it's been too long. 

Long term proposal:

- Service discovery. This is in the p2p roadmap for phase 3. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
Related to #5481.

>A mix of 1 and falling back to fast sync if it's been too long.

Do we really want to fall back to fast sync? State sync has to be enabled explicitly by the user, and presumably they would prefer to try to get state sync working rather than switching to fast sync and then either having to reset the node or wait for a couple of days.

**Comment by erikgrinaker** [comment]
Also, this may possibly be related to the P2P refactor, in that we want some way to prioritize peers and disconnect from less-important peers. For example, nodes should prefer validators. It seems like that system should probably take snapshots into account as well, via some mechanism.

**Comment by marbar3778** [comment]
> Also, this may possibly be related to the P2P refactor, in that we want some way to prioritize peers and disconnect from less-important peers. For example, nodes should prefer validators. It seems like that system should probably take snapshots into account as well, via some mechanism.

This goes into service discovery. If we were to use a dht or some other form of discovery than a service could be "snapshots". This would drastically reduce discovery times. 

Also based on what type a node is, it may have different services it would like to subscribe to.

**Comment by erikgrinaker** [comment]
Another point to note here is that we generally have a very low degree of P2P meshing due to the faulty address advertisement in the P2P stack. Nodes have to change the default configuration to use an explicit listening address (0.0.0.0 doesn't work), and if they are behind NAT they also have to set external_address, otherwise these nodes cannot be gossiped and reached by other nodes.
