### ISSUE TITLE
statesync: commit snapshot meta data on-chain

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5761]
## Summary

We may want to consider using the consensus engine to commit snapshot meta data on chain (perhaps in a similar way that we do with evidence) governed by a consensus parameter. This would mean that the application wouldn't need to store and retrieve snapshot data but just the chunks themselves. 

See https://github.com/tendermint/tendermint/issues/5228#issuecomment-730419906 for original comment

We should first look to weigh up pros and cons against the current design before we venture any further

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Does this mean operators and nodes are all required to follow the same snapshotting behavior? How does this tie into custom pruning settings and what if a node's pruning settings conflict with the canonical on-chain snapshot settings?

**Comment by cmwaters** [comment]
Yes this would forfeit individual snapshotting behavior. 

The application would decide on the consensus parameter governing snapshot frequency (just as it decides on the retain height) so the ball would be in the applications court to not create any conflicts with snapshotting and pruning. 

In any case if we decide to implement a pruning ceiling (due to the issue with evidence) then this won't be a problem as snapshotting will invariably (due to light client verification) occur inside the evidence (unbonding) period

**Comment by marbar3778** [comment]
I am a fan of not making the assumption everyone in the network does everything. If I am a validator I may not want to create snapshots or run other services. It puts an unnecessary burden on all the nodes while only a fraction actually need to do snapshotting. 

What are we trying to optimize for here?

**Comment by erikgrinaker** [comment]
>What are we trying to optimize for here?

UX and reliability.

Currently, an adversary can trivially prevent nodes from state syncing by spamming the network with fake snapshot metadata, as there is no way to determine which snapshots are real and which are fake á priori. Obtaining the necessary data for state sync is also a bit of a hassle. And state sync has a different, additional trust model than that of a non-state sync node joining the network (light client vs trusting the configured P2P IP addresses), when it would be cleaner to use a single trust model for all nodes.

**Comment by marbar3778** [comment]
> And state sync has a different, additional trust model than that of a non-state sync node joining the network (light client vs trusting the configured P2P IP addresses), when it would be cleaner to use a single trust model for all nodes.

Agree with a single trust model for all nodes. This would be solved by introducing the light client into the p2p layer, am I missing something?

> Obtaining the necessary data for state sync is also a bit of a hassle.

This is solved by a light client in the p2p layer and a way for applications providing a bootnode to be injected on init. Part of the hassle will always be present no matter the node you spin up. 

I am primarily not a fan of having all the nodes doing the same jobs if it's not necessary. I would not want to run this on my validator because it doesn't need do.

**Comment by erikgrinaker** [comment]
Everything you say is true. It really boils down to the tradeoff between making state sync automagic and resistant to DoS attacks, and placing an additional computational burden on validators. Since validators are compensated via network I personally feel like that's fine, but it's a judgement call.

**Comment by cmwaters** [comment]
So trying to clarify this further (and correct me @erikgrinaker if I'm wrong). We have a field in the block where snapshot can be filled.

```golang
type snapshot struct {
	Height   uint64
	Format   uint32
	Chunks   uint32
	Hash     []byte
	Metadata []byte

	trustedAppHash []byte // populated by light client
}
```

At every n height, where n is determined through a consensus parameter, the snapshot data of the previous height (because we use delayed execution) is proposed in the block and eventually committed.

When state syncing we verify the block using the light client verification model which means we can therefore trust the snapshot meta data. Then when we start to request chunks from peers which we can verify against the snapshot.

**Comment by erikgrinaker** [comment]
>At every n height, where n is determined through a consensus parameter, the snapshot data of the previous height (because we use delayed execution) is proposed in the block and eventually committed.

In principle. In practice, generating snapshots can be time-consuming (potentially hours), and we can't halt block processing for this long, so it must be async and only get committed once +2/3 have finished generating it.

>When state syncing we verify the block using the light client verification model which means we can therefore trust the snapshot meta data. Then when we start to request chunks from peers we can verify them against the snapshot metadata.

Yep, that's the idea. 👍

**Comment by cmwaters** [comment]
> In principle. In practice, generating snapshots can be time-consuming (potentially hours), and we can't halt block processing for this long, so it must be async and only get committed once +2/3 have finished generating it.

I see so the snapshot could be for a height that is several below the height that it get's committed in. I guess there would need to be some design thought in ensuring that proposers did actually propose snapshots and that light clients could easily find them (as the light client itself doesn't have knowledge on consensus params)
