### ISSUE TITLE
rpc: http jsonrpc don't set cache-control in response

### ISSUE THREAD

**Issue by yihuang** [tendermint/tendermint#5764]
## Summary

Some of the RPC apis can be perfectly cached since the data is immutable, like `/block` `/block_results`, etc.
If we set proper cache-control response header, and setup with some http proxy cache server like [varnish](https://varnish-cache.org/), we can easily archive great performance of http apis.

## Proposal

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by JayT106** [comment]
@tessr If I want to do a contribution to this issue, should I submit PR directly, or it needs to been discussed or make a proposal for it?

**Comment by JayT106** [comment]
Sounds good! Thanks!
