### ISSUE TITLE
p2p: communicate node's limits to peers

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5773]
If two nodes have different limits (say `MempoolConfig.MaxBatchBytes`), one of them will disconnect from another when the latter sends a message which is bigger than the allowed limit. To avoid this, we need to learn about other node's limits during the handshake and use them (if defaults are too big) when communicating w/ that node.

### Example issue:

```
It is related with the new config option "MaxBatchBytes" https://github.com/tendermint/tendermint/blob/master/config/config.go#L654

Description says "Maximum size of a batch of transactions to send to a peer" but its not accurate since it ALSO applies on the received batch transactions. As it can be seen here: https://github.com/tendermint/tendermint/blob/master/p2p/conn/connection.go#L857

So in our case it looks like the Full node (with a 150k mempool capacity) was sending a Tx Batch to its p2p neighbors (validators) that was overloading this maximum. Then the Reactor of the validator drop that p2p connection with the Full node: https://github.com/tendermint/tendermint/blob/master/p2p/conn/connection.go#L637

I am not sure what happens next, but after some time this p2p connetion is recovered, the Full node sends the batch and the connection is drooped again.... Thus the validators are never receiving the missing transactions.

So if instead of the default value (10 * 1024 * 1024 = 10MB) I set a much lower value such as the following:
Mempool.MaxBatchBytes = 500 * Mempool.MaxTxBytes // 500 max-size txs: 500 * 256KB = 128000

Then everything works fine!

I still don't know exactly why that happens, but it looks that for some reason the Full node is sending more transaction bytes than the ones defined in Mempool.MaxBatchBytes (so the connection is drop). I wonder if this comparison works actually as expected: https://github.com/tendermint/tendermint/blob/master/mempool/reactor.go#L286
```

**Comment by alexanderbez** [comment]
I guess there is no other way to handle this gracefully other than to do it when we perform the various handshake(s). Do we have the entire set of max values peers need to know about when exchanging binary data?

**Comment by p4u** [comment]
That's a complex issue to fix. I would propose to split  `MaxBatchBytes` in two config options:
+ MaxBatchSendBytes: limit for sending
+ MaxBatchRecvBytes: limit for receiving

So let the user be aware of these two different limits so it can be configured properly depending on the general configuration of the Tendermint network.

By default I would use something like: `MaxBatchRecvBytes = 2*MaxBatchSendBytes` So in case the user does not take into account the Recv limit, there will be some buffer in order to avoid possible node isolation problems.

**Comment by faddat** [comment]
Wouldn't it make more sense to set this at the blockchain level (don't allow users to set it on their nodes), so that chains have clear requirements re: network bandwidth and compute capacity?
