### ISSUE TITLE
ProposalBlock is invalid: block time 2020-12-10 12:25:47.5630378 +0000 UTC is not equal to genesis time 2020-12-10 12:25:47.7005918 +0000 UTC

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5782]
the issue occurs when you use `.000Z ` 3 digit millisecond precision versus `.481331Z`  6 digits in genesis time. No blocks are committed. Instead, Tendermint keeps trying to create a block, but fails every time (every round).

we should check the time format and throw an error (or append missing digits), so users do not experience ^.

**Comment by alexanderbez** [comment]
Can we not just enforce all usage of time in Tendermint to use a specific format? Or does this still occur if we do that?

**Comment by tessr** [comment]
I think both of you are suggesting the same thing!

**Comment by alexanderbez** [comment]
Splendid 🎉

**Comment by melekes** [comment]
cannot replicate this
