### ISSUE TITLE
6 abci apps within tendermint

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5790]
## Summary

In working on abci updates for lazy ledger and debugging tests I went through updating multiple different abci apps:

- https://github.com/tendermint/tendermint/blob/master/consensus/mempool_test.go#L209
- https://github.com/tendermint/tendermint/blob/master/state/helpers_test.go#L233
- https://github.com/tendermint/tendermint/blob/master/abci/example/counter/counter.go
- https://github.com/tendermint/tendermint/blob/master/abci/example/kvstore/kvstore.go
- https://github.com/tendermint/tendermint/blob/master/abci/example/kvstore/persistent_kvstore.go
- https://github.com/tendermint/tendermint/blob/master/test/e2e/app/app.go

## Problem Definition

Too many apps to update and debug. Also, some tests use kvstore others counter and others their own custom counter or kvstore app. 

If others don't see this as a problem, custom testing may need custom apps, feel free to close the issue.

## Proposal

Use fewer apps and be consistent with what is used in tests. 

Using Mockery could be a replacement as well. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Why not just bring in SimApp :-p (I'm kidding of course), but I do think limiting these would reduce headache and maintenance burden.

**Comment by cmwaters** [comment]
Yeah I think for some of the more specific test cases (i.e. in consensus/mempool_test.go), mockery would be a good option. It's easy and lightweight.

As for the examples, maybe we could remove one, say the kvstore. However, for me personally, I know that when I'm trying to learn a new library or framework, I'll just take a working example and then start fiddling with that along side reading the docs until I can develop a better understanding. This is in fact exactly what I did to try get my head around the cosmos-sdk. I just used the namespace tutorial and started modifying that. So I think having a few examples is helpful.

**Comment by marbar3778** [comment]
this is down to 5 now, counter was removed

**Comment by marbar3778** [comment]
talked with callum about merging kvstore and persistent kvstore. We would expose a flag that opts the operator into using memdb but by default it would us a db. This will help in reducing the amount of apps

**Comment by ebuchman** [comment]
I believe the `counter` tested certain mempool logic that the kvstore stuff didn't which is why different tests used different apps.

IIRC, kvstore doesnt have invalid txs while counter did so we could test things like CheckTx working properly and whether we can have sequential dependent txs in the mempool, all of which can be a bit tricky
