### ISSUE TITLE
Test performance against the previous release

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5815]
To be able to notice any significant performance regressions, we need to test each new release against the latest current release. What makes a good benchmark? It's reproducible and convincing. The ideal would be a script, which creates a four node cluster, sends a bunch of transactions to each node and stops after 1m. We probably shouldn't use GH actions for it(?) Deploying to a cloud (google, amazon, DigitalOcean) is also an option. After numbers for both releases are there, the script would turn them into nice graphs and notify of any significant difference.

**Comment by marbar3778** [comment]
There are two benchmarks we may want to look at. 1 being the above, the second being individual pkg performance (blockchain, state, etc..). 

An interesting approach would be PR benchmarks that post the result as a comment and pre-release benchmark on a 10-100 validator network. This would be configured by using the testnets repo. This is something I noticed Diem does.

**Comment by erikgrinaker** [comment]
I'd start with the above (whole-system benchmarks), and only optimize/benchmark individual packages when they're shown to be bottlenecks.
