### ISSUE TITLE
lock&unlock：Some doubts

### ISSUE THREAD

**Issue by jackma-cloud** [tendermint/tendermint#5834]
###  Summary
I thought of some situations, I want to know how tendermint handles them?
 > case1
 
How tendermint handles this IBFT situation： [IBFT-305](https://github.com/ConsenSys/quorum/issues/305)

 > case2
 
Four validator nodes：A、B、C、D
step1：Proposer propose block X;
step2：node A and C receives +2/3 "pre-vote X", while other honest nodes （B、D）receives < 2/3 "pre-vote X". (so A、C locks on X)
step3:  A ,C send precommit X, all nodes receives < 2/3 "pre-commit X"，so，enter next round.
step4:  D is proposer, send proposal Y，A is a Byzantine node， pre-vote Y.  so A、B、D pre-vote Y，and they  receives > 2/3 "pre-vote Y". (so B、D locks on Y)
step5: then，A is shutdown，C locked on block X，B、D locks on block Y, Will B、C、D have a normal consensus next? Will tendermint make the consensus network work properly?

 > case3

Four validator nodes：A、B、C、D
A、B locked on block X;
C、D locked on block Y;
How to deal with this situation？

and, I want to know, if a validator is locked at X, will it be unlocked when it receives +2/3 precommit nil?

**Comment by milosevic** [comment]
In Tendermint, correct process unlocks a value once it sees +2/3 prevotes for a different value from the most recent round. For example, if a correct process locks value V in round 5, after it sees +2/3 prevotes for value V' from round >5, it will unlock V. Furthermore, when Proposal is sent in Tendermint, it contains a pair, a value and a round (called valid value and valid round in Tendermint): validValue is proposed block and validRound is -1 initially and it is updated whenever process sees +2/3 prevotes for a different value from the more recent round. As part of block proposal, processes gossip the corresponding prevotes messages that corresponds to the proposed value: for example if (v',7) is proposed, then every correct process will gossip all prevote(v',7,) messages it is aware off. This will allow every correct process that has locked some value different from v' in a round smaller than 7 to unlock its value and prevote for v'. This is the way how Tendermint deals with the cases where different correct processes lock different values: eventually a correct process that has locked value in the highest round will be a proposer and other processes will unlock its values, prevotes for proposed value and decide. 

More complete treatment of Tendermint termination is covered in section III.A of Tendermint consensus paper: https://arxiv.org/pdf/1807.04938.pdf. More formal treatment is done in section IV.    

> I want to know, if a validator is locked at X, will it be unlocked when it receives +2/3 precommit nil?

Unlocking in Tendermint is based on prevotes, so it will not unlock a value when it when it receives +2/3 precommit nil. Unlocking based on prevotes is sufficient for termination (and it is part of block proposal mechanism), but there are probably cases where it would be safe to unlock when seeing +2/3 precommits; it can be more seen as an optimisation, but it is not really clear if it brings any significant benefit.

**Comment by konnov** [comment]
A follow-up on the response by @milosevic, using [this TLA+ spec](https://github.com/tendermint/spec/blob/ik/lock-unlock/rust-spec/tendermint-accountability/MC_n4_f1_case2.tla) the [Apalache model checker](https://github.com/informalsystems/apalache) produces a successful unlocking and deciding scenario for your case 2. In that spec, the protocol follows the steps you mentioned and then tries to reach a state, where `C` decides on a value.

A concrete example, as produced by the model checker, can be found [here](https://github.com/tendermint/spec/blob/ik/lock-unlock/rust-spec/tendermint-accountability/MC_n4_f1_case2_example.tla). Basically, the extension of your case 2 is as follows:

1. `C` timeouts in the `propose` state and increases its round number to 1.
2. `C` prevotes on `nil`, as it disagrees with the proposed value `v1` (recall that `C` had locked on `v0`).
3. `C` receives 3 prevotes on `v1` from `A`, `B`, and `D`. The reason for that is as follows: Although `A` crashes in your scenario after prevoting on `v1`, the gossip layer should propagate `v1` to `C`, as `B` and `D` have seen this message. Hence, `C` locks `v1` in round 1 and sends a precommit on `v1`. (We do not model gossip in the TLA+ spec, the messages are received non-deterministically. This overapproximates the behavior of gossip implementation.)
4. `C` receives 3 precommits on `v1` (from `B`, `C`, and `D`) and decides on `v1`.

I am not sure about cases 1 and 3. If you have more precise scenarios in mind, we could specify them in TLA+ too.

**Comment by guojian1234** [comment]
@konnov  at here "the gossip layer should propagate v1 to C, as B and D have seen this message. Hence, C locks v1 in round 1 and sends a precommit on v1. "
Consider an extreme situation，If C does not receive v1 due to network problems, then timeout and precommit nil。at this case,if A is shutdown，then B and D will time out in the precommit phase because only two precommit v1(from B,D) are collected. when new round ,A is fail down or locked on v0, C locked on v0, B and D locked on v1

**Comment by konnov** [comment]
In the extreme case of unbounded timeouts, consensus is not solvable, which is [old news](https://dl.acm.org/doi/10.1145/3149.214121). That is why the [Tendermint paper](https://arxiv.org/pdf/1807.04938.pdf) assumes partial synchrony. There are periods of global stabilization, where the messages are received in a timely manner. This assumption is explained in Section II.A of the paper and used in Section III.A.

**Comment by melekes** [comment]
closing this

@jackma-cloud if you have questions left, please leave a comment here. thanks all!
