### ISSUE TITLE
defaultTMHome is hard coded and non-cross platform nor portable

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#5836]
**What happened**:
Noticed while auditing, the value of defaultTMHome is this https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/tools/tm-signer-harness/main.go#L21

which will work if "~/" properly resolves, but also if that’s the user’s home.
I believe the initial code might have been written mostly for *NIX OSes, and that
we should perhaps improve this by using:
[os.UserHomeDir()](https://golang.org/pkg/os/#UserHomeDir) which returns a cross platform and portable way to get the user’s current home.

**Comment by tessr** [comment]
Good call. We might want to consider this a breaking change, since it _may_ move the TM directory out from under some users.
