### ISSUE TITLE
tools/tm-signer-harness/internal: newTestHarnessListener can leak an open file if protocol is not “unix” or “tcp”

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#5837]
**What happened**:
Noticed while auditing code that if the protocol isn’t any of “unix” or “tcp”, that the already bound net.Listener won’t be closed. Try any other protocol type and you’ll see it bound but never released
as per

https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/tools/tm-signer-harness/internal/test_harness.go#L358-L380

**What you expected to happen**:
Invoke ln.Close() on that default clause.

**Comment by erikgrinaker** [comment]
Good catch, thanks! Submitted #5850.
