### ISSUE TITLE
Same txhash can be stored on several blocks.

### ISSUE THREAD

**Issue by egonspace** [tendermint/tendermint#5838]
This is more like a question rather than a bug reporting, but when the same txhash is stored in multiple blocks, it seems that `TxIndex` only stores the last txhash. If Byzantine node maliciously proposes a successful tx in the previous block in the current block, and other nodes error this tx and update the `TxIndex`, wouldn't the previous successful tx result be eliminated from `TxIndex`?

**Comment by cmwaters** [comment]
You're right. This seems like a valid concern. It would make more sense to be able to index and query multiple txs with the same hash. I.e. indexing by hash would **append** a tx with the same hash and a different result rather than replace the previous one. Similarly querying a tx by hash would return all the `TxResults` that had the same tx hash.

**Comment by dshulyak** [comment]
It is computationally infeasible to find a second value that will hash to the same result (2nd preimage resistance property i believe). I don't think that you have to deal with potentially forged tx with the same hash, if preimage resistance doesn't stand there are more serious problems.

As for preventing duplicates, usually, blockchains are using the nonce to invalidate txs, from the same sender, that are using old nonce. In tendermint it seems to be the responsibility of the application that runs on top of consensus engine.

**Comment by alexanderbez** [comment]
> As for preventing duplicates, usually, blockchains are using the nonce to invalidate txs, from the same sender, that are using old nonce. In tendermint it seems to be the responsibility of the application that runs on top of consensus engine.

This. Applications will almost certainly have some level of replay protection built-in.

**Comment by egonspace** [comment]
This is a problem of security vulnerabilities with respect to byzantine tolerance of Tendermint. When a byzantine maliciously propose the same tx in a block(this is very easy and can be done without worrying about slashing), the successful result of prior tx disappears from all normal nodes. Can app defend this? You'll have to defend it in Tendermint.

**Comment by dshulyak** [comment]
In ethereum tx hash is a unique storage identifier as well [(ref)](https://github.com/ethereum/go-ethereum/blob/master/core/rawdb/accessors_indexes.go#L33-L71). With the ethereum hash size of 256 bits, you will need to generate 2^128 hashes to find a collision. The same is true for tendermint, I don't think that it is possible to achieve intentionally as of today. 

In bitcoin situation is a bit different, tx hash is not guaranteed to be unique, you can check what they did [here](https://github.com/bitcoin/bips/blob/master/bip-0030.mediawiki). In short - block with duplicate hashes will be rejected by the network if tx with same hash wasn't spent yet. But once it is spent new tx will overwrite old one in the index.

**Comment by egonspace** [comment]
I'm not worried about txhash collisions of different tx. This is a warning of the danger that occurs when a byzantine maliciously included a previously successful tx(exactly same) in the current block. Of course, in this case, the normal nodes will treat this tx as invalid tx. But as a result, the previous successful tx result disappears.

**Comment by alexanderbez** [comment]
@egonspace that would fail `DeliverTx`, so no, it would not make it into a block I believe.

**Comment by egonspace** [comment]
@alexanderbez During propose stage, the proposal is received if there is no problem with the block's basic format because validators do not verify the individual txs, but only verify the block headers and signatures. An error will occur in the `DeliveryTx` at a later execution and will be processed as invalid tx. However, the invalid tx is already recorded in the block and the tx index is updated during the state transition.

**Comment by alexanderbez** [comment]
In order to propose, an honest process would have to first execute `CheckTx`, which would fail. Of course a malicious process could still include this.

**Comment by egonspace** [comment]
As I was thinking about this problem, wouldn't it be better to `CheckTx` if the txs of the block are not in my mempool? Of course, I'm careful that this will cause too much change in Tendermint, but I think it would be better to `CheckTx` in advance than to put it in the block with invalid state.

**Comment by dshulyak** [comment]
are there any issues if index update for tx that already exists will be simply ignored? 
additionally, there is also a possibility of using merkle inclusion proof for a tx in a newer block as an evidence that proposer intentionally injected already processed transaction, which could lead to slashing

**Comment by alexanderbez** [comment]
> As I was thinking about this problem, wouldn't it be better to `CheckTx` if the txs of the block are not in my mempool? Of course, I'm careful that this will cause too much change in Tendermint, but I think it would be better to `CheckTx` in advance than to put it in the block with invalid state.

If you're not the proposer, what good does this do? You already implicitly run `CheckTx` when you process the block.

**Comment by tessr** [comment]
Per @alexanderbez, this is:

* something validators might do in theory but hasn't been seen in practice
* something we should keep thinking about for a pre-1.0 release but doesn't block v0.35

I'm going to move this off the 0.35 milestone and we can come back to it after we get that release out.
