### ISSUE TITLE
abci/client: indefinite mutex lock after grpcClient.StopOnError is !IsRunning() due to missing .Unlock()

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#5840]
This code leaves the grpcClient’s mutex indefinitely locked if !IsRunning() as per https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/abci/client/grpc_client.go#L135-L138 but surprisingly that code has existed for 5+ years.

We need an unlock before exiting, but even more surprising is that the composed method is expected to be under a mutex lock.

**Comment by odeke-em** [comment]
socketClient uses the lock only after the IsRunning() check per https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/abci/client/socket_client.go#L600-L613

**Comment by tessr** [comment]
Good catch. This is very funky and definitely merits further investigation.

**Comment by erikgrinaker** [comment]
Thanks @odeke-em, submitted #5849 for this.
