### ISSUE TITLE
blockchain/v2: (*BlockchainReactor).{Add, Remove}Peer misuse lock by acquiring a read lock then writes to the critical section acquired channel

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#5842]
https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/blockchain/v2/reactor.go#L549-L553

the code above is invalid because it acquires a read lock, then performs a write on code that shouldn’t have a write.

**Comment by odeke-em** [comment]
Ditto for RemovePeer https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/blockchain/v2/reactor.go#L557-L566

**Comment by dshulyak** [comment]
There is nothing wrong with acquiring a shared read-lock in the above examples.
Both methods do not modify `r.events`,  and they only **read** a reference to an already thread-safe data structure. Therefore exclusive lock is unnecessary. You would be right if `r.events` was a slice, for example.

**Comment by erikgrinaker** [comment]
@dshulyak is right. The mutex protects the `Reactor.events` field itself (which can be modified, e.g. set to `nil`), not the contained channel (which is already thread-safe). Here, we're only reading the `events` field, not modifying it, so an `RLock` is appropriate.
