### ISSUE TITLE
blockchain/v2: (*BlockchainReactor).Receive can leave code locked before exiting, and also misuses Read locks

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#5843]
This code https://github.com/tendermint/tendermint/blob/aef1ac7ba5d5f2d73cba706d2d23fafeeb73d8ef/blockchain/v2/reactor.go#L510-L526 can return before the read lock is released. This could use a defer RUnlock()

However, the code in that section performs a write with a channel send, yet it used a read lock. This code needs to be fixed up, just like #5842.

This is symptomatic of the need to just have a plain sync.Mutex and use of defers which will remove the raised problems.

**Comment by erikgrinaker** [comment]
Thanks! As in #5842, the `RLock` is appropriate here, because the mutex protects the `Reactor.events` field itself, not the structure it points to. The channel is already concurrency-safe and does not need additional guards.
