### ISSUE TITLE
ABCI returned error code are not reflected in json response

### ISSUE THREAD

**Issue by davebryson** [tendermint/tendermint#585]
Tendermint: 0.10.1
Websocket connection to tendermint rpc

Errors (and codes) are not reflected in JSON response from ABCI call.  In my test, I intentionally returned `abci.ErrBadNonce` in the `checkTx` (it was the only returned value). However the response never reflects the error. Instead it always returns code 0 - which is `OK`

Sample responce:
  `{ jsonrpc: '2.0',
      id: '0.hzg1r26lfpu',
      result: 
        { code: 0,
           data: '',
           log: '',
           hash: 'F5D86D2748211F8E7B7ED0447441CF9C425D5DC5' },
           error: '' 
       }
   }`

This makes it very difficult to detect errors on the client side.

**Comment by srmo** [comment]
@davebryson copypasta from slack:

> @dbryson did you broadcast_async? In that case, you will not get the checkTx result. You'd need to call broadcast_sync
don't let you fool by the sync call, it's websocket after all, so your call returns immediately but the result will be sent from core once the tx passed checkTx.

**Comment by davebryson** [comment]
Ahhh...  Yes that could be it... need to test it.  Probably need to document that.  I'm sure I'm not the last person to run into it!
