### ISSUE TITLE
Tx can not be stored properly when we make node stop.

### ISSUE THREAD

**Issue by carameleon** [tendermint/tendermint#5851]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

I've found this issue on the various chain using Tendermint v0.33.9 or lower version.

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 20.04, 18.04
- **Install tools**: go1.15.6 or lower
- **Others**:

**What happened**:

It can not store tx properly when we stop the node. So we can not query tx in specific block height when node down.
It does not matter what pruning mode run.

**What you expected to happen**:

query tx normaly.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):

stop the node, when the block is committed. (and the block must have txs) (please see logs below)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

This is syslog 
```
Jan  4 14:43:30  systemd[1]: Stopping Running a rest-server as a background service...
Jan  4 14:43:30  systemd[1]: rest_server_kava-4.service: Main process exited, code=exited, status=143/n/a
Jan  4 14:43:30  systemd[1]: rest_server_kava-4.service: Failed with result 'exit-code'.
Jan  4 14:43:30  systemd[1]: Stopped Running a rest-server as a background service.

Jan  4 14:43:30  systemd[1]: Stopping Running a kvd  as a background service...
Jan  4 14:43:36 ip-172-31-5-191 systemd[1]: kvd_kava-4.service: Main process exited, code=exited, status=143/n/a
Jan  4 14:43:36 ip-172-31-5-191 systemd[1]: kvd_kava-4.service: Failed with result 'exit-code'.
Jan  4 14:43:36 ip-172-31-5-191 systemd[1]: Stopped Running a kvd  as a background service.
```

This is Kava-4 chain node logs(kvd)
```
Jan  4 14:43:30 kvd_kava-4[24164]: E[2021-01-04|14:43:30.984] Stopping peer for error                      module=p2p peer="Peer{MConn{46.4.78.88:26656} 6a49457503f6c1d9eefc6ce50496c0e60db36446 out}" err="write tcp 172.31.5.191:40998->46.4.78.88:26656: use of closed network connection"
Jan  4 14:43:33 kvd_kava-4[24164]: E[2021-01-04|14:43:33.955] Won't start a peer - switch is not running   module=p2p peer="Peer{MConn{54.67.121.37:53662} e312b38635e7939ba462f8f59f8b461c18ed43bd in}"

Jan  4 14:43:35 kvd_kava-4[24164]: I[2021-01-04|14:43:35.385] Executed block                               module=state height=776195 validTxs=3 invalidTxs=0
Jan  4 14:43:35 kvd_kava-4[24164]: I[2021-01-04|14:43:35.596] Committed state                              module=state height=776195 txs=3 appHash=6B3FE99D00E20ADC3CB909BB97DA0336F3E6EFE15474BCA322ACEFEE81E5DFD6
Jan  4 14:43:35 kvd_kava-4[24164]: E[2021-01-04|14:43:35.603] Stopped accept routine, as transport is closed module=p2p numPeers=0

Jan  4 14:43:36 kvd_kava-4[24164]: I[2021-01-04|14:43:36.104] exiting...                                   module=main

Jan  4 14:45:17 kvd_kava-4[894]: I[2021-01-04|14:45:17.554] starting ABCI with Tendermint                module=main
```

I've executed the stop command(systemctl stop service) at 14:43:30(syslog), and it is actually stopped at 14:43:36(kvd log) after height=776195 

rest-server query result (this tx is in block with height = 776195)
```
{
"error": "Tx: RPC error -32603 - Internal error: tx (DB422391691BA84AECC722A1594D6E74B0C09767E99704AC4CAF489326774F89) not found"
}
```

I've found this error band-protocol chain too. 
The tendermint and cosmos-sdk version are (many chains use this version; e.g. kava, certik, band, akash... and occurred same issue.)
```
    github.com/cosmos/cosmos-sdk v0.38.5
    github.com/tendermint/tendermint v0.33.6

    github.com/cosmos/cosmos-sdk v0.39.1
    github.com/tendermint/tendermint v0.33.7

    github.com/cosmos/cosmos-sdk v0.39.1
    github.com/tendermint/tendermint v0.33.8

    github.com/cosmos/cosmos-sdk v0.39.2
    github.com/tendermint/tendermint v0.33.9
```

**Config (you can paste only the changes you've made)**: pruning = nothing or default

**node command runtime flags**: ./kvd start --home /.kvd

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by tessr** [comment]
Thanks for the logs and the details. Just to be clear: Are you saying that after you stop _and then restart_ a node, you can't query any transactions on it? Or do specific transactions, maybe from the most recent block, go missing? Or something else?

**Comment by carameleon** [comment]
Hello, @tessr 
In this case, only transactions included in block height = 776195.

This image show block height 776195, and included 3 txs.

![image](https://user-images.githubusercontent.com/45417810/103657835-bd5f2d80-4fad-11eb-9739-0bb054d9799d.png)

And the query result is "not found"
rest-server, rpc or whatever can not get the tx detail.

result of query(tx hash = DB422391691BA84AECC722A1594D6E74B0C09767E99704AC4CAF489326774F89 in block height 776195)
![image](https://user-images.githubusercontent.com/45417810/103658107-2181f180-4fae-11eb-979f-f4816cea1e74.png)

txs is not stored properly when node down right after block committed.

**Comment by carameleon** [comment]
This problem make me harder when we node maintenance(e.g. increase volume size). 

If it happens, I need to change rpc endpoint connected explorer or wallet apps for get the txs just in 1 block.

**Comment by marbar3778** [comment]
Hey, thanks for the issue! When you try to query through the cmd line is there any difference? Does this happen for every query? 

Also do you mind posting your endpoint? It would help in debugging.

**Comment by erikgrinaker** [comment]
This probably happens because we index transactions after we've committed the block, so the process can crash in between. The proper solution to this is to write all data as part of a single ACID transaction, but that's not feasible across the ABCI boundary. Barring implementing distributed transactions (which we really shouldn't attempt), the only other option I can think of is to index transactions before the block is committed, and assume that if a node crashes before commit then the same block will always be replayed (which I think is a reasonable assumption).

Also, we should make sure Tendermint shuts down gracefully, e.g. by completing in-flight block processing and transaction indexing before exiting (see #5002).

**Comment by tessr** [comment]
I'm going to consider this issue part of #5002 and triage _that_ issue for inclusion in an upcoming release.

**Comment by dshulyak** [comment]
> the only other option I can think of is to index transactions before the block is committed, and assume that if a node crashes before commit then the same block will always be replayed (which I think is a reasonable assumption)

@erikgrinaker do you mean that block will be replayed by listening on the network after restart, e.g. naturally? or there is some other replay util in place?
if the former, then the fork (e.g. at first A was received and index was updated with txs from A, after restart A' got in, that has a different set of txs) will leave index in inconsistent state, with txs from both blocks

**Comment by erikgrinaker** [comment]
>@erikgrinaker do you mean that block will be replayed by listening on the network after restart, e.g. naturally? or there is some other replay util in place?
if the former, then the fork (e.g. at first A was received and index was updated with txs from A, after restart A' got in, that has a different set of txs) will leave index in inconsistent state, with txs from both blocks

This happens via local block replay. We only execute `Commit` after the block has been subject to consensus and stored locally.
