### ISSUE TITLE
consider the binary size of importing/building tendermint

### ISSUE THREAD

**Issue by mvdan** [tendermint/tendermint#5859]
This is a bit of an umbrella issue to take a look at how some of Tendermint's packages and dependencies affect binary size. For example, when lookint at a recent build of https://github.com/vocdoni/go-dvote with Go 1.15.6 on linux/amd64 and Tendermint https://github.com/vocdoni/go-dvote, here are the top 20 packages by compiled code size as shown by https://github.com/bradfitz/shotizam:

```
sqlite> select pkg, sum(size) from bin where pkg <> '' group by 1 order by 2 desc limit 20;
net/http|831978
google.golang.org/protobuf/internal/impl|721936
runtime|721615
github.com/gogo/protobuf/proto|697546
github.com/miekg/dns|643012
github.com/francoispqt/gojay|585584
github.com/tendermint/tendermint/abci/types|507167
github.com/dgraph-io/badger/v2|504770
github.com/gogo/protobuf/types|483503
github.com/marten-seemann/qtls-go1-15|483201
github.com/ethereum/go-ethereum/les|480077
github.com/ipld/go-ipld-prime-proto|464846
crypto/tls|458227
github.com/ipfs/go-ipfs/core/commands|447648
github.com/dgraph-io/badger|436086
net|425419
github.com/ethereum/go-ethereum/core|414046
github.com/libp2p/go-libp2p-pubsub/pb|392011
github.com/tendermint/tendermint/proto/tendermint/types|378811
github.com/lucas-clemente/quic-go|371382
```

Before looking at these numbers, please realise that a package showing up as e.g. 500k probably means a larger size in the final binary due to the symbol table, debug information, alignment, and so on. These numbers are useful more as relative measurements than anything else. I think a good baseline is that badger/v2 is 500k; we can call that a "large" package, since it's what it takes to build a proper fancy key-value database.

I should also point out that the total binary size, including debug info, is 97MiB.

Two useful bits of info stand out to me:

1) gogo/protobuf is pretty heavy at 500k, so https://github.com/tendermint/tendermint/issues/5446 could potentially shave off close to a megabyte from the binary.
2) The types packages, especially abci and proto, are pretty heavy. I assume this is due to the generated code for many message types. I hope replacing gogo would help a bit here, but more careful analysis is probably deserved.

If we look at the top 21-40 packages, then:

```
reflect|367782
github.com/ipld/go-ipld-prime/node/basic|353599
github.com/syndtr/goleveldb/leveldb|351676
github.com/libp2p/go-libp2p-core/introspection/pb|351436
github.com/tendermint/tendermint/consensus|325051
github.com/libp2p/go-libp2p-pubsub|322740
gopkg.in/alecthomas/kingpin%2ev2|311242
github.com/tendermint/tendermint/types|289881
gopkg.in/yaml%2ev2|288740
github.com/cosmos/iavl/proto|288287
github.com/ethereum/go-ethereum/eth|285970
math/big|251376
google.golang.org/grpc/internal/transport|246462
github.com/gogo/protobuf/protoc-gen-gogo/descriptor|246089
github.com/ethereum/go-ethereum/core/vm|239214
google.golang.org/grpc|228904
github.com/ethereum/go-ethereum/eth/downloader|228602
github.com/libp2p/go-libp2p-kad-dht|219656
github.com/spf13/pflag|219316
github.com/klauspost/compress/zstd|216339
```

We can see a similar story, when it comes to Tendermint. More types packages like /types and iavl/proto, another gogo package, and the consensuses package. I also spot a new one:

3) db packages which are always built, but might never be used, like `github.com/syndtr/goleveldb/leveldb`. This would be fixed by https://github.com/tendermint/tm-db/issues/113, at least for Tendermint's tm-db.

Overall, I think there's some reasonably low-hanging fruit that would allow a Tendermint binary to drop by a few megabytes. I haven't actually measured what a "normal" Tendermint client binary should weigh, though, as our 97MiB include plenty of other heavy dependencies like go-ipfs.

**Comment by tessr** [comment]
Thank you for this thorough analysis! I'll definitely add this to our todo list. Can you also share more about how the binary size impacts your use case?

**Comment by mvdan** [comment]
The binary size isn't directly affecting us in any significant way, but it's the kind of "bloat creep" that will keep increasing over time unless one keeps it in check. Our main backend program, dvotenode, is already at 100MiB, which makes docker pushes and pulls quite heavy, for example.

For example, I am currently on FTTC internet, meaning good old phone lines to the building, so my maximum internet speed is about 70/7 Mbit/s. Uploading 100MiB at ~1MiB/s is quite painful :)
