### ISSUE TITLE
Version picker on docs page

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5877]
The version picker on the docs page is pretty hard-to-spot and disappears if you choose any version other than `master`. If you open v0.34, there are links to other versions in the sidebar; but if you open v0.33, there's no way to choose a different version of Tendermint. 

![Screen Shot 2021-01-07 at 12 03 46 PM](https://user-images.githubusercontent.com/773524/103885780-cf8db880-50e0-11eb-9a7d-f4c024b017b5.png)

**Comment by marbar3778** [comment]
This was a pain point of mine as well: https://github.com/cosmos/vuepress-theme-cosmos/issues/91#issuecomment-740207629. Will reopen the issue in vuepress-theme-cosmos.

**Comment by marbar3778** [comment]
The version picker is now visible on v0.32 - master. To make the version picker more visible we can open an issue in https://github.com/cosmos/vuepress-theme-cosmos
