### ISSUE TITLE
state sync: sophisticated ordering in the snapshot pool

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5880]
## Summary / Problem Definition

New nodes running state sync keep a "snapshot pool" which is used for collecting and ordering snapshots from preexisting nodes (snapshot providers). The state sync reactor pulls snapshots from the snapshot pool and sends them to the application, which can verify a given snapshot and then tell Tendermint to start pulling in the chunks for that snapshot. 

At the moment, this snapshot pool always orders the snapshots by recency, sending the newest snapshot first to the application. But we may want to include other heuristics in the ordering, such as how many peers actually have a given snapshot. For example, if only one node has the newest snapshot, we may not want to prioritize that one: It could be a bad snapshot, or it could be slow to request all chunks from just that one provider node. 

## Proposal

Update the definition of [`Best()`](https://github.com/tendermint/tendermint/blob/91bef75f62631045ead4473ec3613387f4c896ce/statesync/snapshots.go#L136) to incorporate the frequency/availability/popularity of the snapshot in addition to its recency. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I think peer count is a great heuristic. Are there any other obvious ones?

**Comment by erikgrinaker** [comment]
>I think peer count is a great heuristic. Are there any other obvious ones?

It should be combined with recency. We don't want to restore an ancient snapshot just because more nodes have it.

If we know anything about the quality of the peers (e.g. their bandwidth or latency) then that might be useful heuristics too. Or maybe we want to include some sort of configurable prioritization (e.g. only fetch snapshots from a specific list of peers).

**Comment by tessr** [comment]
> It should be combined with recency. We don't want to restore an ancient snapshot just because more nodes have it. 

Yes, definitely. _In addition_ to recency 😅

**Comment by erikgrinaker** [comment]
Looks like we already take peer count into account, but in the most naïve way possible -- i.e. first order by height, then format, then peer count. The only benefit of this is that if 40 peers claim some snapshot hash for a given height, and 3 peers claim a different hash, then we pick the snapshot that the most peers have. But if a single peer has a snapshot 1 height above then it doesn't matter if 40 peers have a lower-height snapshot.

https://github.com/tendermint/tendermint/blob/91bef75f62631045ead4473ec3613387f4c896ce/statesync/snapshots.go#L173-L175

**Comment by tessr** [comment]
I think format is probably the least important thing to handle when "ranking" snapshots, since bad formats get rejected (and blacklisted) at a different point in snapshot gathering process. I'd also guess that newer (higher) snapshots will probably have newer (later) formats.

I tried to think of some simple way to incorporate these factors. Two ideas off the top of my head:

1. Give every snapshot a "rating" (or grade) and prefer the snapshot with the highest grade. A snapshot's grade is calculated as `(height × peer count) + format number`. This is a simple way to incorporate both newness and popularity, and it means that if 40 peers claim a snapshot at height 1000, it will be preferred over a snapshot claimed by one peer at height 1001. However, it also means that a snapshot at height 10,000 held by 21 nodes would be preferred over a snapshot at height 20,000 held by 10 nodes. 
2. Rate each snapshot as either "common" or "uncommon," based on whether they are available from some minimum `n` number of peers. This number can probably be a configurable default. Then, run the current `Ranked` function over the common snapshots, followed by the uncommon snapshots. This basically would mean that we prefer the newest snapshot that's available from at least `n` peers. 

I think (2) is the better of these approaches; I'd like to keep this as simple as possible so that we can test it easily.

**Comment by erikgrinaker** [comment]
Yeah, I'd start with something simple like 2 until we get actual user reports about bad heuristics.

**Comment by alexanderbez** [comment]
Looks like we pretty easily tweak the existing business logic to accommodate something like (2).
