### ISSUE TITLE
privval: remove previous protocol

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5883]
# Summary

In preparation for 0.35 or later major release we should remove the previous/custom private validator protocol. (This is mainly deleting lines).

**Comment by marbar3778** [comment]
Moving this to the next release cycle to keep in line with 0.35 be as non-breaking as possible.

**Comment by jackzampolin** [comment]
Thank you for not killing it for this release, but I'm good with removing in 0.36
