### ISSUE TITLE
Reactors Package

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#5887]
## Summary

Currently, reactor implementations reside in their respective packages (e.g. `statesync`) under the root package of Tendermint.

## Problem Definition

It's difficult to understand or quickly find out what is a reactor without looking at the actual implementations of each package and check if it implements the `service.Service` interface or contains a `reactor.go` file.

## Proposal

Create a `reactors` package under the root and move all reactors there.

e.g.

```
tendermint/reactors/statesync
tendermint/reactors/evidence
tendermint/reactors/blockchain
...
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
I am in favor of this, although it will alter the git history and make it a little more challenging to see original authors of things (since the history for files gets truncated whenever they move). I think that's OK, though. 

Also, I think the super-package name should be `reactor` singular (see https://rakyll.org/style-packages/#:~:text=In%20go%2C%20package%20names%20are%20not%20plural.).

**Comment by tessr** [comment]
Going to hold off on any reorganizing until right before the 0.35 release so that we don't make backporting too complex.

**Comment by alexanderbez** [comment]
> Going to hold off on any reorganizing until right before the 0.35 release so that we don't make backporting too complex.

Makes sense! I think that's the best approach as it'll make backports (i.e. cherry-picking) more straightforward and less error-prone.

**Comment by erikgrinaker** [comment]
I suppose this would imply having a `stores` package with all data stores and so on? I think it makes more sense to organize code by area of responsibility (i.e. "topic") rather than design pattern, since I'm usually much more interested in "all the code related to state sync" rather than "all the code that implements reactors", and this makes the code easier to navigate. It also allows use of private code without exporting these across package boundaries. Personally I'd leave reactors in the respective packages.

I'm also guessing cross-"topic" packages like these could quickly end up with import cycles -- unless we have a sub-package per topic, which becomes unergonomic because we'd have lots of packages with conflicting names (e.g. `statesync`, `reactors/statesync`, and `stores/statesync`).

**Comment by tessr** [comment]
> I think it makes more sense to organize code by area of responsibility (i.e. "topic") rather than design pattern 

Heh, while you were away, we had an (off Github) conversation about this, and I tried to make this point, somewhat less succinctly. But since we're not going to make any of these changes until shortly before a breaking release, I think we have plenty of time to stew on it.

**Comment by erikgrinaker** [comment]
Ah, right. I feel like the reactor is simply one external interface (via P2P networking) for the package logic, with RPC being another, and command-line yet another. It seems odd to me to group all of this logic by one of the external interfaces, when it could in principle be accessed via any number of interfaces, and also provide non-reactor infrastructure that is accessed by other non-reactor packages. Just my 2¢.

**Comment by alexanderbez** [comment]
I don't quite follow @erikgrinaker? All of these are "reactors" that implement the `service` interface. Them being reactors or services or whatever else you call them, make them fall under that topic/domain. Yes, they may serve RPC needs and maybe even have logic outside of that domain, but they're still primarily a thing -- reactor/service.

E.g. in the SDK we have the `/x` pkg. This package has all the modules as sub-pkgs, yet these sub-pkgs may very well implement other interfaces and do other things, yet they're all still modules and are part of a general grouping. This has served as very well there.

It seems like folks don't think this is a good idea, so feel free to close @tessr -- I mainly wanted to point out that I think this is a UX annoyance.

**Comment by erikgrinaker** [comment]
>I don't quite follow @erikgrinaker? All of these are "reactors" that implement the service interface. Them being reactors or services or whatever else you call them, make them fall under that topic/domain. Yes, they may serve RPC needs and maybe even have logic outside of that domain, but they're still primarily a thing -- reactor/service.

Consider e.g. the `mempool` package: the core entity is the mempool data structure, which is also shared by `consensus` (to build blocks) and `state` (to execute blocks). I would argue that the mempool reactor is a secondary component of this package, and that it does not make sense to group the mempool data structure (and thus the `mempool` package) under a `reactors` package.

**Comment by alexanderbez** [comment]
But the mempool package is in and of itself a reactor. So you'd either join consensus and mempool together or leave as-is. Regardless, they're both reactors (as they are implemented today).

**Comment by erikgrinaker** [comment]
>But the mempool package is in and of itself a reactor. So you'd either join consensus and mempool together or leave as-is. Regardless, they're both reactors (as they are implemented today).

The `mempool` package _contains_ a reactor, which is one of many things that interacts with the core mempool data structure, but the primary purpose of the`mempool` package is to provide the mempool data structure. When we refer to the "mempool", in 99% of the cases we refer to the data structure not the reactor. Anyway, I'll defer to the rest of the team.

**Comment by marbar3778** [comment]
We have moved many reactors into internal and will continue either moving things to internal or pkg at the root level. Closing this issue
