### ISSUE TITLE
light: pruning not concurrently safe

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5892]
## Summary

Changes introduced in #5848 have led to the non-deterministic failure of the concurrency test in `light/store/db_test.go`. I believe this is because the pruning function is not concurrently safe and multiple calls can occasionally cause the store to lock.  

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Any particular tests that are failing? Can you post stacktraces with `--race` enabled?

**Comment by cmwaters** [comment]
Yeah it halts during `TestConcurrency` and I think it has to do with multiple iterators running in parallel. `--race` doesn't seem to pick it up though.
You can repro it by running:
```
 while true; do go test ./... -count 1 -race -timeout 10s; done
```

**Comment by alexanderbez** [comment]
Right, eventually that retry script will fail and what is the resulting stack trace? Or do you have a CI output log to pin for this issue instead?

**Comment by cmwaters** [comment]
Yup: https://pastebin.com/1bMWCqJf
