### ISSUE TITLE
run e2e test nightlies on release branches

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5895]
At the moment, we run the e2e tests as nightlies on `master`, but we should probably be running them on v0.34.x as well. (Edit: v0.33.x and v0.32.x don't have any E2E tests.)

To do: 

- [x] Backport E2E test updates to the 0.34 branch
- [ ] Add nightly runners for each of these branches 

You can request a nightly run under https://github.com/tendermint/tendermint/actions?query=workflow%3Ae2e-nightly

**Comment by marbar3778** [comment]
I wonder if its worth trying to add something like `@tendy run e2e` and it runs a large set of e2e tests. This way, on large PRs or PRs that are touching sensitive things we can get a larger set of e2e tests instead of only one.

**Comment by tessr** [comment]
We can manually request E2E nightly runs at https://github.com/tendermint/tendermint/actions?query=workflow%3Ae2e-nightly on any branch. I don't think we need to add additional Github bots.

**Comment by tessr** [comment]
Closed by #5906
