### ISSUE TITLE
pex: message ergonomics

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5899]
## Summary

There are two messages in the Peer exchange reactor, `PexRequest` and `PexAddrs`. It is not very intuitive that `PexAddrs` is the response to `PexRequest`. We should change `PexAddrs` to `PexResponse`.

It may be better to change the name of both messages, `AddrsRequest` and `AddrsResponse`. This way it is easy to understand what the messages contain.

**Comment by marbar3778** [comment]
Does anyone have a preference? Otherwise, I will change them to `AddrsRequest` and `AddrsResponse`.

**Comment by erikgrinaker** [comment]
Go for it. We may end up making further changes here when we refactor the PEX reactor, but I think this makes sense anyway.
