### ISSUE TITLE
test large tx sizes in e2e tests

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5905]
We should put larger transactions (>1 MB) through the e2e tests. This would help us catch issues like the mempool batching performance issue we introduced in 0.34.0 and reverted in 0.34.1.

**Comment by alexanderbez** [comment]
Specifically, I think we should be able to tweak/configure on a per node basis how many txs and/or the size of txs to broadcast. Thoughts?

**Comment by erikgrinaker** [comment]
>We should put larger transactions (>1 MB) through the e2e tests. This would help us catch issues like the mempool batching performance issue we introduced in 0.34.0 and reverted in 0.34.1.

Probably a good idea to have a couple of sizes (e.g. "small" and "large"), but comprehensive tests should be done via integration or unit tests.

>Specifically, I think we should be able to tweak/configure on a per node basis how many txs and/or the size of txs to broadcast. Thoughts?

This would have to be per-network, not per-node, since all nodes process all transactions.

**Comment by cmwaters** [comment]
> This would have to be per-network, not per-node, since all nodes process all transactions.

Doesn't this highlight that `MaxTxBytes` should really be a consensus param rather than an individual config. The fact that some nodes accept the tx while others don't and yet it in the end it's able to be committed on chain. I guess there was some deliberate reason behind making it a local config.

**Comment by erikgrinaker** [comment]
Yup.
