### ISSUE TITLE
rpc: debug mode

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5908]
## Summary

When a node panics because of a divergent hash the node will immediately panic and shut down. When the user tries to restart the node in order to query the RPC to try to debug it immediately panics. Having a mode that starts up with only the RPC on the data directory could help in debugging these issues. 

## Proposal

Debug mode (not sold on the name) that runs only RPC on the database in order to query data from the node that has panicked. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
How does this look like implementation-wise? Do we look for a flag and simply "hang" without starting any reactors?

**Comment by marbar3778** [comment]
yea, instantiate a new node in the node package and look for existing dbs then only run the RPC server and hang.

**Comment by alexanderbez** [comment]
Seems reasonable and trivial.

**Comment by melekes** [comment]
maybe this can be a part of "refactoring node package"?

**Comment by alexanderbez** [comment]
Yes, I think so @melekes. I'd like to tackle this work after p2p and mempool stuff is fleshed out more.

**Comment by cmwaters** [comment]
> Debug mode (not sold on the name)

I actually don't mind debug mode but this form of observing the system without enacting any control (i.e. through starting a reactor) reminds me of Tesla's "Shadow Mode" which I think could also be an apt name.

**Comment by marbar3778** [comment]
I think this doesnt have to be a debug item but also a process you can use in production. It would be similar to [rpcdaemon](https://github.com/ledgerwatch/turbo-geth/tree/master/cmd/rpcdaemon) from turbo geth. In order to solve this we may need to first have propoer shutdown in order to close the DB, if we don't do this already.

**Comment by marbar3778** [comment]
reopening this as this was a very useful feature and users are still looking for it
