### ISSUE TITLE
consensus: revise testing

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5920]
## Summary

The consensus reactor is quite an unwieldy beast. In many ways it feels like a reactor within a reactor, with state having methods like `receiveRoutine` and `handleMsg`. It has 4 channels, a WAL, and an event bus all carefully interwoven with timeouts. If understanding the evidence reactor might be the equivalent of poking at the engine of a yamaha 125, then understanding the consensus reactor is like popping the hood on a boeing 747. It's a complex piece of machinery. This invariably makes is difficult to test. The predecessors who wrote most of the consensus test suite did a pretty good job but there is still quite a bit of work that needs to be done:
 - The slashing test suite is commented out
 - Some locking tests and the catchup test suite are missing
 - Byzantine tests are scarce (and hard to write)
 - Network partition tests and clock distorting (although perhaps this is outside of consensus)

We should look at fleshing out all these tests, review if any others could be improved on and perhaps better organise the tests (`state_test.go` is already 1900 lines)

Furthermore, the testing relies on the eventbus to ensure that the internal state machine processes occur as expected (which we can't be sure has the desired behavior when looking from the outside). This also has little control over the timing of events (i.e. it's hard to test how the locking mechanism may behave with timeouts) and requires a lot of overwriting of consensus logic to squeeze out the right situation. What I think might benefit the consensus tests is a complimentary vote-centric testing framework, which wraps around, one or possibly many consensus reactors, leaving them untouched and intact and merely focusing on their endpoints. The framework would be designed to fire specific permutations of votes (proposals, prevotes and precommits) and listen to how the reactor/s react/s. This could then more easily mock various network situations and could be thus considered more high level.

Would be happy to hear others input about how we can improve testing
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Can you elaborate a bit more on the concrete proposal @cmwaters? This framework will still yield unit tests, correct? Or is it more akin to e2e tests?

**Comment by cmwaters** [comment]
Sure, this would be more at a unit testing level but approaches testing consensus at a different angle to the current testing suite.

I should preface this all by stating that I think first we'd need to investigate and beef up the current testing suite before making a decision on whether there lies enough benefit to design another. 

My line of thought however, is that whilst the current testing suite does the job of ensuring that consensus performs correct internal state transitions such as `enterProposal`, `enterPrevote`, `enterPrecommit` and so forth, a complimentary testing framework could ensure that the consensus reactor exhibits the correct external behaviors. This would be done similarly to how we might test other reactors (given the p2p refactor) which is to mock the p2p channels and essentially simulate the behavior of the rest of the network by firing a sequence of votes and asserting that the consensus reactor fires back the correct votes.

I have no idea how informal's model based testing is constructed but I could imagine that this framework might synthesize well with it. 

My proposal so far is about as concrete as that.

**Comment by Olshansk** [comment]
I saw that this was on the [Q4 2022 roadmap](https://docs.tendermint.com/v0.35/roadmap/roadmap.html#v1-0-expected-q4-2022) and just wanted to share something similar we have at Pocket Network.

We use a different consensus algorithm (modified version of hotstuff), but the approach to building a testing library like this is similar "in spirit". The tests are defined in [hotstuff_test.go](https://github.com/pokt-network/pocket/blob/main/consensus/consensus_tests/hotstuff_test.go) and the utils are in [utils_test.go](https://github.com/pokt-network/pocket/blob/main/consensus/consensus_tests/utils_test.go).

Sharing it here because it's something I'm personally excited about and proud of. If you have any feedback, or want to reference it for inspiration, or just want to bounce ideas for a similar implementation you may need, just lmk!


In short, the testing framework helps mock the P2P sends & broadcasts in the network and then verify the state of consensus for each height/step/round. E.g.:
```
	// Commit
	preCommitVotes, err := WaitForNetworkConsensusMessages(t, testChannel, consensus.PreCommit, consensus.Vote, numNodes, 1000)
	require.NoError(t, err)
	for _, vote := range preCommitVotes {
		P2PSend(t, leader, vote)
	}

	commitProposal, err := WaitForNetworkConsensusMessages(t, testChannel, consensus.Commit, consensus.Propose, 1, 1000)
	require.NoError(t, err)
	for _, pocketNode := range pocketNodes {
		nodeState := GetConsensusNodeState(pocketNode)
		require.Equal(t, uint64(1), nodeState.Height)
		require.Equal(t, uint8(consensus.Commit), nodeState.Step)
		require.Equal(t, uint8(0), nodeState.Round)
		require.Equal(t, leaderId, nodeState.LeaderId, fmt.Sprintf("%d should be the current leader", leaderId))
	}
	for _, message := range commitProposal {
		P2PBroadcast(t, pocketNodes, message)
	}
```

**Comment by cmwaters** [comment]
Hey, thanks for the reference. Yeah, just briefly looking at this, this seems somewhat similar to the tests we have whereby the consensus reactor fires certain events and so the unit test will subscribe to the events it expects to be fired to reflect certain state transitions. But I guess this is based around a small network rather than an individual node right?

**Comment by Olshansk** [comment]
> the consensus reactor fires certain events and so the unit test will subscribe to the events it expects to be fired to reflect certain state transitions

Yes, that sounds pretty similar in "spirit".

> But I guess this is based around a small network rather than an individual node right

I believe the answer is yes, but hard to say without providing details.

```go
        ...
	numNodes := 4
	configs := GenerateNodeConfigs(t, numNodes)
	...
	leaderId := typesCons.NodeId(2)
	leader := pocketNodes[leaderId]	
	...
	for _, pocketNode := range pocketNodes {
	...
```

I took out a few lines from the code, separated by ellipsis, just to show that we do mimic the broadcasts/sends amongst all the mocked nodes.

I'm curious what prompts the question so I can see in what direction your thinking?
