### ISSUE TITLE
e2e: support light clients

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5935]
## Problem Definition

We currently have not tests that integrate light clients with full nodes and validators. 

## Proposal

Add light client as a possible node type which can connect to nodes and query them for light blocks. 

A further extension would be to generate `LightClientAttackEvidence` and assert that it correctly propagates the network and
is committed on chain (although formulating such a specific scenario might be best created in a separate test suite i.e. not e2e). 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
I think this should be a priority. @melekes, I'm going to assign this to you for now since I think it fits under the umbrella of advanced testing work, but @cmwaters could also take it on as part of his evidence work. (Really, I'd like to assign it to whoever has spare cycles first.)
