### ISSUE TITLE
evidence: internal audit

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5943]
As part of our "evidence-hardening" push, we've been discussing doing some kind of audit with the Informal team, similar to [the one they did for IBC](https://twitter.com/informalinc/status/1351940252617814017). This would be a great opportunity for us to check our assumptions about how evidence works, to ensure that the evidence spec is up-to-date, and to transfer protocol knowledge from the Informal team to the Interchain team.

Given how critical evidence handling is, I'd like to do this sooner rather than later, but there are a few open questions:

* Should we try to do this before the protocol changes mentioned in https://github.com/tendermint/tendermint/issues/5688, such as amnesia handling?
* Do we need a formal report, à la https://github.com/informalsystems/audits/blob/main/IBC2020/report.pdf?

**Comment by cmwaters** [comment]
> Should we try to do this before the protocol changes mentioned in #5688, such as amnesia handling?

Yes. I think there is a lot more work needed before we reach a solid understanding of amnesia attacks and how they can be combatted. I think a slower and more structured approach is required. We should develop tools (model based testing or something akin to what I proposed in #5920) that can test the golang implementation of consensus and prove more definitively the range of attacks that are possible (with greater than or less than 1/3 voting power) as well as their consequences. Then we might be in a position where we can ask ourselves how do we prevent amnesia attacks? 

This somewhat brings me to a question of my own. Is the audit on the implementation of how evidence gets detected or on the implementation of how evidence is handled (or both)?

> Do we need a formal report, à la https://github.com/informalsystems/audits/blob/main/IBC2020/report.pdf?

I would say that one overarching issue accompanied by all the specific issues would suffice (at least as far as fixing informal's findings). I am not too sure if there are other purposes that a report might be fit for i.e. a record that's not built-in to GitHub's workflow.

**Comment by milosevic** [comment]
I think this is great idea. My feeling is that the whole evidence business is still pretty fragmented and it might be beneficial having some focused attention end-to-end (@cmwaters I would say both). We also discussed in the past about ensuring that forks are detected on the main chain and properly handled, so this could potentially be also part of the scope.

**Comment by tessr** [comment]
Assigning this to Callum and Josef to follow-up on the issues that were found in the audit :)

**Comment by cmwaters** [comment]
Lol teamwork
