### ISSUE TITLE
Error loading ConsensusState wal module=consen sus err="open \.tendermint\data\cs.wal\wal: The system cannot find the path specified."

### ISSUE THREAD

**Issue by inovatecc** [tendermint/tendermint#595]
**BUG REPORT (?)**:

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
b467515719e686e4678e6da4e102f32a491b85a0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
installed using go get -u github.com/tendermint/abci/cmd/...

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):
N/A

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 7 run inside virtualbox vm
- **Install tools**: go, nodejs, git per instruction
- **Others**:

**What happened**:
Just following along getting started guide starting with https://tendermint.com/downloads

**What you expected to happen**:
tried running first sample apps, dummy, counter, counter nodejs app
the sample apps run fine, but when running tendermint with 
tendermint init (later unsafe_reset_all)
tendermint node
get:
E[07-28|03:18:39.616] Error loading ConsensusState wal             module=consen
sus err="open \\.tendermint\\data\\cs.wal\\wal: The system cannot find the path
specified."

if run tendermint node without running the sample app then get:
E[07-28|03:21:13.788] abci.socketClient failed to connect to tcp://127.0.0.1:466
58.  Retrying... module=abci-client connection=query

**How to reproduce it** (as minimally and precisely as possible):
on windows 7 "inside virtualbox vm", just following the getting started guide.  used install tendermint from source option.  everything installed fine.  defined $GOPATH=c:\tendermint\go in user environment variable.  (installed go under tendermint)

am a starter with tendermint, with blockchain as a whole.  don't have lot of experience with go, git command line, nodejs, etc yet.

**Comment by inovatecc** [comment]
Got it working... only a workaround though... 
Following is for Windows but may apply to other OS:

After typing tendermint init and tendermint node OR tendermint unsafe_reset_all and tendermint node... ^C out and then create a file .tendermint\data\cs.wal\wal (.tendermint is located under C: drive).  Then rerun tendermint node.  Not tendermint unsafe_reset_all b/c this will delete the file again.

NOTE: "perhaps" there is an issue (?) with tendermint node in that it does not create an empty dummy file .tendermint\data\cs.wal\wal when running initially.  Or perhaps in the piece of code that accesses the .tendermint\data\cs.wal\wal file it may want to create it if it does not exist.

**Comment by inovatecc** [comment]
Other comments:
1) create .tendermint\data\cs.wal\wal as in previous comment
2) (In documentation) add %GOPATH%\bin to PATH variable (for Windows) where all of the executables are created by go, so that don't have to type the fullpath to the exe files each time
3) (In documentation) install curl from https://curl.haxx.se/download.html
4) (In documentation) for Windows anyway have to type curl commands without the single quotes: the curl command examples for "Another Example - Counter" (without the single quotes) work, but not the curl commands for "A First Example - Dummy" (with single quotes)
5) (In documentation) for Windows use %ENVVAR% not $ENVVAR

**Comment by ebuchman** [comment]
Thanks for this. I think it's a Windows only issue with not creating the wal dir properly. I'll reopen this until we figure out how to solve it - I have no experience with Windows :)

**Comment by inovatecc** [comment]
Possible code change concerning error creating "\.tendermint\data\cs.wal\wal" file on Windows.  Error may arise from dot in ".tendermint" in the path.  path.Dir(walFile) where walFile = "\.tendermint\data\cs.wal\wal" just returns ".".

Propose using "path/filepath" library instead of "path".  Former seems to work just by dropping the last part of the path.  Tested on windows and seems to work.  Did not test on other OS however.

**Comment by zramsay** [comment]
#664
