### ISSUE TITLE
test/fuzz: add missing tests

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5959]
As a follow-up to https://github.com/tendermint/tendermint/pull/5918, we should analyze what tests are missing (i.e. what inputs do we want to cover with fuzzing). A few that come to my mind immediately:

- light client (https://github.com/tendermint/tendermint/issues/4453)
- ~~X Reactor # Receive (it does not make sense to test protobuf encoding / decoding, but it does when it comes to handling individual messages)~~ property-based tests make more sense because they are able to constrain the space of generated values
- RPC `/tx_search`, `/blockchain`

**Comment by JayT106** [comment]
@melekes I would like to tackle this ticket. Is anyone doing this?

**Comment by cmwaters** [comment]
I'm pretty sure no one is doing this atm so you can definitely try tackle this. In regards to the light client, we used model based tests (provided by informal) which I believe should sufficiently cover fuzzy based testing (unless you feel there are areas that we are missing). As for the others, I'm less sure about. Perhaps it would be good, if you could give a rough plan about what parts you aim to add fuzzy tests to first

**Comment by JayT106** [comment]
Thanks for the reply, @cmwaters. I will play with the RPC part mentioned above first. And then to see any missing part I can see.
