### ISSUE TITLE
light: consider not replacing primary if it says it does not have a block X

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5964]
Sometimes during e2e tests for state sync we get:

```
2021-01-25T03:36:26.4154552Z validator06    | E[2021-01-25|03:35:38.924] failed to add snapshot                       module=statesync peer=0b529c309608172a29c49979394734260b42ac
fb height=9 format=1 err="light block not found. Tried to replace primary but: no witnesses connected. please reset light client" channel=0xfc6ac0
```

Currently, we replace a primary if it does not have a certain block (see `lightBlockFromPrimary`). This sometimes results in errors (**not critical**) during state sync ^ when a node legitimately does not have a block. 0b529c309608172a29c49979394734260b42ac is not malicious here (although it can be!).

solution 1:

verify first
Callum: "For me, this is one of those problems where the solution could be more nuanced but we just haven't got around to it. We should replace a primary because a malicious primary could pretend to not have any block the light client requests, leaving it stuck at the height it initialised at. At the same time, if the primary honestly doesn't have the block because it's at a height that it hasn't reached yet or it has pruned the block then we shouldn't necessarily disconnect. What we probably should do in cases where we know the primary hasn't been explicitly malicious, is to swap the primary (not remove) with a witness and try again. If we get through all providers with the same error then we return that back to the user"

solution 2:
trust first. 
the solution lies within trusting primary first - like if it says it does not have a block, then we say okay. but if we find out (later that other providers have that block), we remove primary

**Comment by cmwaters** [comment]
> but if we find out (later that other providers have that block), we remove primary

How would this happen exactly? If we keep trusting the primary when it said it didn't have the block, we would never get around to checking witnesses

**Comment by melekes** [comment]
> > but if we find out (later that other providers have that block), we remove primary
> 
> How would this happen exactly? If we keep trusting the primary when it said it didn't have the block, we would never get around to checking witnesses

maybe we can retry a few times with timeout? otherwise, we will need to consult with witnesses re/ what height they are on.
