### ISSUE TITLE
Set docs-staging branch as protected

### ISSUE THREAD

**Issue by lovincyrus** [tendermint/tendermint#5972]
**Request**: set `docs-staging` branch as protected.

I just wanted to make sure the branch won't be deleted after each merge. 🤝  We need `docs-staging` branch for https://staging.docs.tendermint.com (netlify) 

- [ ] add branch rule for docs-staging with no extra configurations.

Ref: https://github.com/allinbits/design/issues/366

**Comment by tessr** [comment]
I added `docs-staging` to the protected branches list, with no extra rules around merges, etc:

![Screen Shot 2021-01-26 at 10 53 57 AM](https://user-images.githubusercontent.com/773524/105829617-e4b18500-5fc4-11eb-822b-f0a0b35814b2.png)


I think this is correct but lmk if anything is amiss.
