### ISSUE TITLE
ongoing PEX work

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#598]

**Comment by ebuchman** [comment]
Useless issue. Will open more descriptive ones as necessary

**Comment by sbellem** [comment]
New to Tendermint and in the spirit of trying to help:

I just arrived to this issue from the docs: https://tendermint.readthedocs.io/en/master/using-tendermint.html#peers

> Additionally, the peer-exchange protocol can be enabled using the `--pex` flag, though this feature is [still under development](https://github.com/tendermint/tendermint/issues/598). If `--pex` is enabled, peers will gossip about known peers and form a more resilient network.

It would be helpful if the documentation was updated or if this issue would reference a relevant issue.

Thanks!

**Comment by dan-turner** [comment]
Agreed.  So does this work or not?

**Comment by zramsay** [comment]
see #862 and #867 for specific PEX related issues

**Comment by zramsay** [comment]
#940, #968
