### ISSUE TITLE
can't add non-validator on different version

### ISSUE THREAD

**Issue by hxzqlh** [tendermint/tendermint#600]
My old tendermint node version is `0.7.3`, and I want add a non-validator node on a different machine which tendermint  verison is `0.10.0`

```
$ tendermint node --p2p.seeds 120.24.83.29:46656
```
 
then, tendermint output this err:

```
E[08-02|06:51:03.986] Failed to add peer                           module=p2p address=120.24.83.29:46656 error="Peer is
on a different minor version. Got 7, expected 10"
E[08-02|06:51:03.986] Error dialing seed                           module=p2p error="Peer is on a different minor versio
n. Got 7, expected 10"
```

**Comment by srmo** [comment]
That's correct behavior I'd say. Both versions are incompatible with each other.

**Comment by ebuchman** [comment]
This is correct behaviour. That said, these nodes may be able to connect, but to avoid encouraging that behaviour while we are still making some breaking changes, we prevent the connection unless at least the minor version matches. You should be able to build the older version from source: https://github.com/tendermint/tendermint/releases/tag/v0.7.3

**Comment by hxzqlh** [comment]
So, how to upgrade the node from 0.7.3 to 0.10.0 and leave the legacy data continue available? Since my business data is all in `~/.tendermint/data` .

**Comment by hxzqlh** [comment]
So, how to upgrade the node from 0.7.3 to 0.10.0 and leave the legacy data continue available? Since my business data is all in ~/.tendermint/data .

**Comment by hxzqlh** [comment]
So, how to upgrade the node from 0.7.3 to 0.10.0 and leave the legacy data continue available? Since my business data is all in `~/.tendermint/data` .

**Comment by ebuchman** [comment]
Unfortunately that's not possible right now without custom tooling. Your best best would be to bring up new 0.7.3 nodes. If you want to engage us to build that custom tooling so you can upgrade everything to 0.10, please reach out at ethan@tendermint.com and we can figure something out.

**Comment by adrianbrink** [comment]
#603

**Comment by hxzqlh** [comment]
Another question about validator: How to remove one or more validators from current running validators? since this doc [using-tendermint](http://tendermint.readthedocs.io/en/master/using-tendermint.html) only describes how to add a Validator.

**Comment by melekes** [comment]
https://tendermint.readthedocs.io/en/master/app-development.html#endblock "To add a new validator or update an existing one, simply include them in the list returned in the EndBlock response. To remove one, include it in the list with a power equal to 0. Tendermint core will take care of updating the validator set. Note validator set changes are only available in v0.8.0 and up."

**Comment by hxzqlh** [comment]
@melekes thanks. "endblock" method need modify code. From my opinion: app need not know which validator to add or remove, since such task should be done by tendermint.

**Comment by ebuchman** [comment]
> app need not know which validator to add or remove, since such task should be done by tendermint

While Tendermint carries out the task, it has no way of knowing when it should happen, other than when the app tells it. Remember Tendermint is totally agnostic to state - transactions are meaningless blobs of bytes. If we want Tendermint to have the full generality it does, validator set change decisions need to be made by the app and relayed back to Tendermint via EndBlock. 

Does that make sense?
