### ISSUE TITLE
blockchain/v0: DATA RACE TestReactor_BadBlockStopsPeer

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#6005]
From https://github.com/tendermint/tendermint/pull/5993/checks?check_run_id=1782552717:

```
WARNING: DATA RACE
Write at 0x00c0012dd440 by goroutine 20:
  runtime.mapdelete_faststr()
      /opt/hostedtoolcache/go/1.15.7/x64/src/runtime/map_faststr.go:297 +0x0
  github.com/tendermint/tendermint/blockchain/v0.(*BlockPool).removePeer()
      /home/runner/work/tendermint/tendermint/blockchain/v0/pool.go:331 +0x324
  github.com/tendermint/tendermint/blockchain/v0.(*BlockPool).RedoRequest()
      /home/runner/work/tendermint/tendermint/blockchain/v0/pool.go:236 +0x1d6
  github.com/tendermint/tendermint/blockchain/v0.(*Reactor).poolRoutine()
      /home/runner/work/tendermint/tendermint/blockchain/v0/reactor.go:526 +0xbbc

Previous read at 0x00c0012dd440 by goroutine 358:
  github.com/tendermint/tendermint/blockchain/v0.TestReactor_BadBlockStopsPeer()
      /home/runner/work/tendermint/tendermint/blockchain/v0/reactor_test.go:403 +0xd99
  testing.tRunner()
      /opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0x202

Goroutine 20 (running) created at:
  github.com/tendermint/tendermint/blockchain/v0.(*Reactor).OnStart()
      /home/runner/work/tendermint/tendermint/blockchain/v0/reactor.go:154 +0x190
  github.com/tendermint/tendermint/libs/service.(*BaseService).Start()
      /home/runner/work/tendermint/tendermint/libs/service/service.go:140 +0x538
  github.com/tendermint/tendermint/blockchain/v0.setup()
      /home/runner/work/tendermint/tendermint/blockchain/v0/reactor_test.go:153 +0x24da
  github.com/tendermint/tendermint/blockchain/v0.TestReactor_BadBlockStopsPeer()
      /home/runner/work/tendermint/tendermint/blockchain/v0/reactor_test.go:326 +0x2e4
  testing.tRunner()
      /opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0x202

Goroutine 358 (running) created at:
  testing.(*T).Run()
      /opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1168 +0x5bb
  testing.runTests.func1()
      /opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1439 +0xa6
  testing.tRunner()
      /opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1123 +0x202
  testing.runTests()
      /opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1437 +0x612
  testing.(*M).Run()
      /opt/hostedtoolcache/go/1.15.7/x64/src/testing/testing.go:1345 +0x3b3
  main.main()
      _testmain.go:105 +0x356
==================
--- FAIL: TestReactor_BadBlockStopsPeer (11.39s)
    testing.go:1038: race detected during execution of test
```

**Comment by alexanderbez** [comment]
This existed before the reactor as well. I'm not sure how to go about fixing it w/o introducing a dedicated lock and `setStore` just for this one test.

**Comment by tessr** [comment]
Sorry for the naive question, but do we know what the root cause is here?

**Comment by alexanderbez** [comment]
[This](https://github.com/tendermint/tendermint/blob/master/blockchain/v0/reactor_test.go#L366-L370). We _intentionally_ mutate the `state` field to put it in a bad "state", but doing so modifies the object which causes a race condition. I just want to be clear -- this only happens in this one single test.

**Comment by erikgrinaker** [comment]
I'd argue that this test does the wrong thing. These kinds of scenarios should be tested by either injecting appropriate inputs directly or mocking stuff, not by setting up integration test networks and start fiddling with their internals.

**Comment by alexanderbez** [comment]
Well this test was an artifact of the original reactor test suite.

> injecting appropriate inputs directly 

Is this not what the test does?

> mocking stuff

Perhaps. But that might require moving things to interfaces, i.e. `*store.BlockStore`, which I'm not sure is worth it depending on the breadth of what we want to test.

**Comment by erikgrinaker** [comment]
>>injecting appropriate inputs directly
>Is this not what the test does?

No, this sets up a bunch of reactors and has them talk to each other. This is an integration test. I'm arguing these sorts of tests should be unit tests.

**Comment by alexanderbez** [comment]
Right, but the issue here is modifying a single reactor in-place and injecting/replacing it's `BlockStore`. Even if we just had one reactor and it was a pure unit test, we'd still have this issue AFAICT.

**Comment by erikgrinaker** [comment]
Isn't what we're testing here that a peer which provides a bad block gets disconnected? If so, the unit test approach would be to send a bad block on the input channel, and read off the error from the error channel.

**Comment by alexanderbez** [comment]
Yes, that is what it is testing. I'll see if I can modify the test to reflect that.
