### ISSUE TITLE
consensus: state deadlock?

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#6009]
**Tendermint version**:

`bez/p2p-refactor-consensus-reactor`

## Context

After wrapping up the consensus reactor refactor, I've moved onto refactoring the tests, starting with `TestReactorBasic`. What I've observed is that when using buffered channels for the p2p channels (say >= 4), the test always passes. But when using unbuffered channels, the test would timeout.

Note, using buffered vs unbuffered channels should not really change the safety or correctness of the code (I think), just maybe make it slower. After poking around I noticed it was around the use of `r.conS.RWMutex`.

I noticed some places we used a read-lock and others we used a write-lock to grab fields on `r.conS`, which didn't make sense -- I changed all of these to read-locks after verifying this with @ebuchman. However, the test still timesout after making this change.

Worried that I introduced an inconspicuous bug, I triple checked all the logic and didn't find anything alarming. Dumbfounded and w/o any more ideas, I decided to uses the deadlock detector and voila:

```
POTENTIAL DEADLOCK:
Previous place where the lock was grabbed
goroutine 3651 lock 0xc000125590
state.go:768 consensus.(*State).handleMsg { cs.mtx.Lock() } <<<<<
state.go:735 consensus.(*State).receiveRoutine { cs.handleMsg(mi) }

Have been trying to lock it again for more than 30s
goroutine 5533 lock 0xc000125590

Here is what goroutine 3651 doing now
goroutine 3651 [chan send]:
github.com/tendermint/tendermint/consensus.(*Reactor).broadcastNewValidBlockMessage(0xc0000e5b80, 0xc0001255a8)
	/Users/aleksbez/code/tendermint/tendermint/consensus/reactor.go:307 +0x370
github.com/tendermint/tendermint/consensus.(*Reactor).subscribeToBroadcastEvents.func2(0x1dad520, 0xc0001255a8)
	/Users/aleksbez/code/tendermint/tendermint/consensus/reactor.go:350 +0x5d
github.com/tendermint/tendermint/libs/events.(*eventCell).FireEvent(0xc000d62bc0, 0x1dad520, 0xc0001255a8)
	/Users/aleksbez/code/tendermint/tendermint/libs/events/events.go:198 +0x2c6
github.com/tendermint/tendermint/libs/events.(*eventSwitch).FireEvent(0xc0001d72d0, 0x1e38e1e, 0xa, 0x1dad520, 0xc0001255a8)
	/Users/aleksbez/code/tendermint/tendermint/libs/events/events.go:158 +0xe5
github.com/tendermint/tendermint/consensus.(*State).addVote(0xc000125500, 0xc0013ce820, 0xc00003a720, 0x20, 0xc001036780, 0xc000f09df8, 0xc0000ca5e8)
	/Users/aleksbez/code/tendermint/tendermint/consensus/state.go:2003 +0x1ed2
github.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000125500, 0xc0013ce820, 0xc00003a720, 0x20, 0xc0000e9210, 0x0, 0xc00000b800)
	/Users/aleksbez/code/tendermint/tendermint/consensus/state.go:1846 +0x7d
github.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000125500, 0x208a740, 0xc0001f0140, 0xc00003a720, 0x20)
	/Users/aleksbez/code/tendermint/tendermint/consensus/state.go:802 +0xd97
github.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000125500, 0x0)
	/Users/aleksbez/code/tendermint/tendermint/consensus/state.go:735 +0x9ec
created by github.com/tendermint/tendermint/consensus.(*State).OnStart
	/Users/aleksbez/code/tendermint/tendermint/consensus/state.go:378 +0xf69
Other goroutines holding locks:
goroutine 1329 lock 0xc000124e90
state.go:768 consensus.(*State).handleMsg { cs.mtx.Lock() } <<<<<
state.go:751 consensus.(*State).receiveRoutine { cs.handleMsg(mi) }

goroutine 676 lock 0xc000124b10
state.go:768 consensus.(*State).handleMsg { cs.mtx.Lock() } <<<<<
state.go:735 consensus.(*State).receiveRoutine { cs.handleMsg(mi) }

goroutine 312 lock 0xc000124790
state.go:768 consensus.(*State).handleMsg { cs.mtx.Lock() } <<<<<
state.go:751 consensus.(*State).receiveRoutine { cs.handleMsg(mi) }
```

This seems to indicate that the issue stems from `State` and not the `Reactor`. I still can't make the connection between the use of buffered vs unbuffered channels in the tests and the use of `r.conS.RWMutex` in the `Reactor` or if this is even an issue/bug, but just noting this for documentations sake.

**Comment by alexanderbez** [comment]
I imagine `state` is waiting a long time for the lock because `broadcastNewValidBlockMessage` is blocking (unbuffered)?

**Comment by ebuchman** [comment]
>  when using buffered channels for the p2p channels (say >= 4), the test always passes. But when using unbuffered channels, the test would timeout.

Can you link to which channels in which tests and how to reproduce the deadlock detection? Looks like it could be a test artifact.

**Comment by erikgrinaker** [comment]
Yeah, this is an artifact of the tests, the `simulateRouter` method is too naïve. I'd recommend using the real router with in-memory transports for these sorts of integration tests, and to prefer single-reactor unit tests where possible.

If you look at the full goroutine dump of the deadlock detector, you'll see that there are four goroutines that are blocked on `chan send` doing sends on `suitesByPeerID[...][c].in`, e.g.:

```
goroutine 364 [chan send]:
github.com/tendermint/tendermint/consensus.simulateRouter.func1(0xc0005c2420, 0xc0001d9ae0, 0xc000223be0, 0x4, 0x4, 0x100020)
	/Users/erik/Projects/tendermint/tendermint/consensus/reactor_test.go:170 +0x20b
created by github.com/tendermint/tendermint/consensus.simulateRouter
	/Users/erik/Projects/tendermint/tendermint/consensus/reactor_test.go:164 +0x468

goroutine 209 [chan send]:
github.com/tendermint/tendermint/consensus.simulateRouter.func1(0xc00028d110, 0xc0001d99a0, 0xc000223be0, 0x4, 0x4, 0xc000210020)
	/Users/erik/Projects/tendermint/tendermint/consensus/reactor_test.go:170 +0x20b
created by github.com/tendermint/tendermint/consensus.simulateRouter
	/Users/erik/Projects/tendermint/tendermint/consensus/reactor_test.go:164 +0x468
```

And so on... I suspected all four are for the same channel, and verified this by adding a select timeout and logging the sends:

```
broadcast timeout chan 35 ecdd6c96c9c59b968cb2fe0e5596dc04->a5cdd563b21e50b1aeb5fb6580df4114
broadcast timeout chan 35 a21a14e4c9583766b5d2a7b8b44871c0->a5cdd563b21e50b1aeb5fb6580df4114
broadcast timeout chan 35 a5cdd563b21e50b1aeb5fb6580df4114->ecdd6c96c9c59b968cb2fe0e5596dc04
send timeout chan 35 ab082efc0baa465e716080727b36b00d->a5cdd563b21e50b1aeb5fb6580df4114
```

Here, you'll see that `ecdd6c96c9c59b968cb2fe0e5596dc04` is blocked sending to `a5cdd563b21e50b1aeb5fb6580df4114`, but `a5cdd563b21e50b1aeb5fb6580df4114` is also blocked sending to `ecdd6c96c9c59b968cb2fe0e5596dc04`. The others are blocked sending to either of these.

Since there is only a single goroutine both sending and consuming messages, if a channel send blocks while the remote peer is sending a message to us, then there is noone on our end to receive that message, so the peer also blocks and everything stalls. Buffering mitigates this problem since we're no longer dependent on having our goroutine read the message synchronously (which it can't do, since it's busy sending).

**Comment by alexanderbez** [comment]
Thanks for summarizing that @erikgrinaker and confirms my susipicion. I'm going to use buffered channels to avoid this and eventually use an in-mem transport instead of a naive router.
