### ISSUE TITLE
"basecli keys new cool" doesn't work with bash command prompt on Windows

### ISSUE THREAD

**Issue by inovatecc** [tendermint/tendermint#601]
**BUG REPORT:

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.10.2

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Installed from go get -u github.com/tendermint/abci/cmd/...

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):
102aaf5a8ffda1846413fb22805a94def2045b9f

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 7 running on VirtualBox
- **Install tools**: installed basecoin
- **Others**:

**What happened**:
When running "basecli keys new cool" on bash window, command prompt skips "Enter a passphrase:" and give error "ERROR: The handle is invalid.".

**What you expected to happen**:
It should stop on "Enter a passphrase:" to receive keyboard inputs.  And also on "Repeat the passphrase:"

**How to reproduce it** (as minimally and precisely as possible):
Run on Windows 7, after installing basecoin, open bash window and type "basecli keys new cool".

**Anything else do we need to know**:
Workaround: use regular windows command prompt, not "bash".  Works as expected.  When using windows command prompt, need to create %HOME% env variable that is same as the $HOME variable in bash.

**Comment by odeke-em** [comment]
Thank you @inovatecc for filing the bug and welcome to Tendermint!

/cc @ethanfrey, and ideally we should file this bug at the basecoin repo where basecli is in development https://github.com/tendermint/basecoin.

**Comment by ethanfrey** [comment]
Yes we should. And we need a windows machine for testing. 

Unfortunately we don't officially support windows yet. 

We use stdout and stderr which may not be supported on windows.

**Comment by inovatecc** [comment]
This is non-issue: sorry.  I was using Git-bash which was installed with Git Windows installer.  It did not have a valid stdin tty input and was causing an error in bgentry.speakeasy vendor library.

Downloaded win-bash port and using it makes stdin available.
