### ISSUE TITLE
libs/sync: undefined deadlock.Once

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#6013]
`sync.Closer` relies on `deadlock.Once`, but `deadlock.Once` is not available in go-deadlock 0.2 (the latest release), so running `go test -tags deadlock` errors with `undefined: deadlock.Once`.

In any case, `deadlock.Once` is just an alias for `sync.Once` so there is no point in using it; I suggest we move `sync.Closer` to a separate file and use `sync.Once`.

**Comment by alexanderbez** [comment]
This was already resolved by @marbar3778 by updating the commit version of `go-deadlock`. I'm OK with either approach.

**Comment by erikgrinaker** [comment]
Right, ok -- was running it on a branch.

**Comment by alexanderbez** [comment]
I think your suggestion holds merit though @erikgrinaker. Do you still think that's beneficial?

**Comment by erikgrinaker** [comment]
Yeah, I don't really see the point in duplicating the code to make use of `deadlock.Once` (with/without `deadlock` tag) when `deadlock.Once` is just an alias for `sync.Once` anyway.
