### ISSUE TITLE
How about add a nonce in persistent_kvstore tx

### ISSUE THREAD

**Issue by kukugi** [tendermint/tendermint#6027]
## Summary

how about make a way to create a unique tx with same parameter

## Problem Definition

I'm trying to test tendermint with randomly set power, but sending tx with same power and pubkey failed. because there is a same tx

## Proposal

if i can make a unique tx, then my test will be pass. please consider it
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
You can turn off mempool cache by setting `cache_size` to 0 (https://docs.tendermint.com/master/spec/abci/apps.html#replay-protection) in `[mempool]` section of config.toml.
