### ISSUE TITLE
Define upgrade path from older version to newer versions of Tendermint

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#603]
We need to describe how to upgrade from older versions of tendermint to newer ones.

Ideally the persistence layer should still work.

**Comment by hxzqlh** [comment]
Good News for you!I have developed a tool that can migrate legacy data from tendermint 0.7.3 to tendermint 0.10.0, it will be coming soon

**Comment by ebuchman** [comment]
Wow @hxzqlh that sounds awesome - thanks! We're very excited to see that. Do you have any other open source Tendermint projects already that we can add to our [ecosystem page](https://tendermint.readthedocs.io/en/master/ecosystem.html)?

**Comment by adrianbrink** [comment]
@hxzqlh That's awesome. Could you post the link to the tool?

**Comment by hxzqlh** [comment]
@adrianbrink @ebuchman I have post this tool on my git [tm-tools](https://github.com/hxzqlh/tm-tools), you can try and test it now.

**Comment by adrianbrink** [comment]
@hxzqlh thank you very much

What project are you working on?

**Comment by zramsay** [comment]
#754
