### ISSUE TITLE
Standardize (standardise) our spelling of "misbehavio(u)r" 

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#6030]
This is kind of silly, but almost certainly going to cause a bug at some point. We mix the spelling of behavior/behaviour all over the codebase. "Behavior" is slightly more prevalent, but we do have a package called `behaviour`. 

A quick search suggests that Tendermint Core mostly uses American English spelling: We've used "offense," not "offence;" "color," not "colour;" "artifact," not "artefact;" and "center," not "centre." With this in mind, I suggest we standardi**z**e to American English. 

(I'll also admit I'm biased, of course.)

**Comment by erikgrinaker** [comment]
I'll note that the `behaviour` package will be removed in the P2P refactor, and replaced with a new peer quality/behavior API.

**Comment by erikgrinaker** [comment]
Also, we already use the `misspell` linter, but it defaults to a "neutral English" locale -- setting `-locale US` will make the linter error on `behaviour`.

**Comment by tessr** [comment]
Oh cool, nice!

**Comment by cmwaters** [comment]
You have no idea when I was writing the misbehavior stuff in Maverick how many times I had to catch myself. I was already assuming that we were following American English.
