### ISSUE TITLE
Order release branches correctly for go mod

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#6072]
We currently use release tags only on release branches, `go mod` doesn't "know" whether the commits on master come "before" or "after" the releases.

From @mvdan on Discord:

> Since there are no v0.35 pre-release tags, cmd/go has to assume that master is shortly after v0.34.0, its latest reachable tag. Which means master is considered to be an older version than v0.34.3 - meaning one can upgrade from master to v0.34.3, which is backwards :)

See also: https://github.com/golang/go/issues/38985#issuecomment-626925765 

TODO:

- [x] Apply tags on `master` to order it correctly relative to the release branches
- [ ] Update CONTRIBUTING.md and release flow to include tagging master along with release branches 

I'll also note that, in a perfect world, we'd somehow disable the ability to automatically "upgrade" to master altogether - after all, we want people to use release branches!

**Comment by mvdan** [comment]
>     * Apply tags on `master` to order it correctly relative to the release branches

FYI, you probably want to tag the master commit *right after* the release branch was forked off, so that all commits after it are considered part of v0.35.

**Comment by tessr** [comment]
Right. We only fork off when we do "major" releases (e.g., 0.34.0, 0.35.0), and minor releases come from commits individually cherry-picked off master and onto release branches. Would it be sufficient to tag master only when those major releases happen (i.e., right after the fork) or do we need to create tags on master that correspond to point release (e.g. 0.34.3) as well?

**Comment by mvdan** [comment]
Just one tag whenever you create a new release branch should be sufficient. Essentially, whenever you split development of one branch into two, e.g. v0.34.x (backports) vs v0.35.x (upcoming release), the latter needs a pre-release tag to hint to the Go tool that it is indeed a v0.35.x pre-release, and not the continuation of the last tag, v0.34.0.

**Comment by tessr** [comment]
Right, that makes sense. Thank you for calling this to our attention and also for the explanation!

**Comment by alexanderbez** [comment]
Tagging off of master right after creating a major release branch off of master proposal makes sense to me!

**Comment by tessr** [comment]
Tagged `v0.35.0-dev` at `ecd3cbc2bd1c28987dcac327072a88e290a6fc5e`, which is the first commit on master _after_ the last commit that is on both `master` and `0.34.x`. This might be slightly wonky, because we started using the `0.34.x` terminology after that point (we used `release/x` for a while), but after the next release it should be fine.
