### ISSUE TITLE
Panic in RPC HTTP handler

### ISSUE THREAD

**Issue by RiccardoM** [tendermint/tendermint#6078]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
```
tendermint: ""
abci: 0.17.0
blockprotocol: 11
p2pprotocol: 8
```

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
[Desmos `v0.15.1`](https://github.com/desmos-labs/desmos/tree/v0.15.1)

**Environment**:
- **OS** (e.g. from /etc/os-release):  
   ```
   NAME="Ubuntu"
   VERSION="20.04.1 LTS (Focal Fossa)"
   ID=ubuntu
   ID_LIKE=debian
   PRETTY_NAME="Ubuntu 20.04.1 LTS"
   VERSION_ID="20.04"
   HOME_URL="https://www.ubuntu.com/"
   SUPPORT_URL="https://help.ubuntu.com/"
   BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
   PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
   VERSION_CODENAME=focal
   UBUNTU_CODENAME=focal
   ```
- **Install tools**:
- **Others**:

**What happened**:  
Shortly after starting the node, the RPC paniced with an error. 

**What you expected to happen**:  
The node should have run without any errors.

**Have you tried the latest version**:  
No

**How to reproduce it** (as minimally and precisely as possible):
1. Start a desmos node
2. The error suddenly appeared

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:  
https://pastebin.com/smFSbWAh

**Config (you can paste only the changes you've made)**:

**Node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**  
https://pastebin.com/uDAGpb4K

**Anything else we need to know**:

**Comment by alexanderbez** [comment]
`http: superfluous response.WriteHeader call from github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1.1 (http_server.go:157)`.

I'll take a look into this.

**Comment by alexanderbez** [comment]
This is happening because there is a panic in the request path _after_ we've written to the response (i.e. we've already written the status or body?)

Is your node actually panicing and crashing from this or is it just the logs that you've noticed?

**Comment by RiccardoM** [comment]
> This is happening because there is a panic in the request path _after_ we've written to the response (i.e. we've already written the status or body?)
> 
> Is your node actually panicing and crashing from this or is it just the logs that you've noticed?

Sorry for the late reply. I saw that inside the logs, but the node **did not** crash

**Comment by alexanderbez** [comment]
Ahh, yes, that is the panic recovery logger. You can ignore that. Going to close this issue since these are just IO timeouts.
