### ISSUE TITLE
Cleanup branches and remove stale ones

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#610]
Currently there are 30 branches on this repository. Let's try and trim that down to only the ones people are still actively working on.

**Comment by zramsay** [comment]
ping @ebuchman so i dont delete anything important (all branches here live in forks already tho)

**Comment by ebuchman** [comment]
Slowly working on it ...

**Comment by zramsay** [comment]
this is happening naturally. there's a bunch of branches that go with open issues and I'll open as WIP pr's to more easily track the work that is being saved
