### ISSUE TITLE
Clean up build tooling

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#6103]
There are currently a number of unfortunate mysteries in our build tooling. Why are we manually pulling certain versions of dependencies, for example? 

Before 1.0, we _must_ audit all this tooling and understand what it does and why, ideally cleaning it up and deleting a lot of it as we go.

**Comment by githubsands** [comment]
noticed a lot of this and pulled https://github.com/tendermint/tendermint/pull/6070
