### ISSUE TITLE
0.34.x e2e timeout failures

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#6117]
We've had timeout failures on the 0.34.x nightlies for two nights in a row. Relevant logs: 

* Last night (2021-02-16): https://gist.github.com/tessr/45954b7f182b6857e77f73dc22ef929b 
* Two nights ago (2021-02-15): https://gist.github.com/tessr/5f6a2cb2a05d1964f1327ea6adbc082c and  

We should look at these timeouts and either increase the timeout tolerances in the tests or find/address a root cause. 

Incidentally, it looks like the 02-15 tests also had a truly spurious failure:

```
I[2021-02-15|02:35:20.463] Removing Docker containers and networks      
E[2021-02-15|02:35:21.796] failed to run ["bash" "-c" "docker network ls -q --filter label=e2e | xargs $(if [[ $OSTYPE == \"linux-gnu\"* ]]; then echo -n \"-r\"; fi) docker network rm"]:
Error response from daemon: error while removing network: network gen-group02-0009_gen-group02-0009 id d88f9ac036fcc12b3c1c16f72a701a631e87a7057fa249ffd99eb8b0af852afb has active endpoints
```

and I don't think we need to worry about that one.

**Comment by cmwaters** [comment]
We've had relatively consistent e2e nightlies pass on 0.34 so I'm going to close this issue
