### ISSUE TITLE
better error in client if method does not exist

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#612]
@ebuchman commented on [Thu Sep 01 2016](https://github.com/tendermint/go-rpc/issues/2)

The difficulty in debugging https://github.com/eris-ltd/eris-db/issues/253 stems from the client trying to unmarshal the main page (the list of endpoints, which is returned if the method does not exist) into a return type, which it's not

**Comment by ebuchman** [comment]
closing for https://github.com/tendermint/tendermint/issues/1531
