### ISSUE TITLE
e2e: invalid node address

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#6133]
```
validator01    | ERROR: failed to create node: failed to create peer manager: invalid peer address "4fe295e4cfad69f1247ad85975c6fd87757195db@[fd80:b10c::2]:26656": invalid node address "4fe295e4cfad69f1247ad85975c6fd87757195db@[fd80:b10c::2]:26656": parse "4fe295e4cfad69f1247ad85975c6fd87757195db@[fd80:b10c::2]:26656": first path segment in URL cannot contain colon
```

https://github.com/tendermint/tendermint/runs/1923724451

**Comment by alexanderbez** [comment]
Does this look like faulty random address generation in the e2e suite @erikgrinaker?

**Comment by erikgrinaker** [comment]
Nah, I think this is an oversight in the `ParseNodeAddress` heuristic that tries to detect unqualified (scheme-less) URLs and apply a default scheme -- it doesn't take IPv6 addresses into account.

https://github.com/tendermint/tendermint/blob/27b05d6b3939966d617605e2358e48ba83c4224e/p2p/address.go#L94-L103
