### ISSUE TITLE
P2P Issues 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#614]
- [ ] support persistent node key and x509
- [x] remove SwitchEventNewPeer and SwitchEventDonePeer (is there some reason not to ? )
- [ ] better broadcast (don't launch a go-routine for every peer for every broadcast)
- [x] consider removing AddToIPRangeCounts/CheckIPRangeCounts
- [ ] pong timeout (if pong not received within one minute of ping, kill connection)

**Comment by odeke-em** [comment]
4 was resolved by https://github.com/tendermint/tendermint/pull/655

**Comment by ebuchman** [comment]
Opened new issues for these
https://github.com/tendermint/tendermint/issues/804
https://github.com/tendermint/tendermint/issues/805
https://github.com/tendermint/tendermint/issues/806
