### ISSUE TITLE
rpc: timeout not working

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6142]
I was looking into the light client / rpc framework and wanted to investigate the error that is returned when the client times out. I set the full node to delay it's response by 10 seconds and set the timeout of the light client to 3 seconds:

```
rpchttp.NewWithTimeout(remote, "/websocket", 3 * time.Second)
```

Instead of timing out the light client waited the full 10 seconds for the full node and then responded

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I would double check the underlying client, which should most likely have a read and write timeout. It could be that we're setting the read timeout only, and not the write timeout.

**Comment by cmwaters** [comment]
This is what gets set: (`net/http#Client`)
```
// Timeout specifies a time limit for requests made by this
	// Client. The timeout includes connection time, any
	// redirects, and reading the response body. The timer remains
	// running after Get, Head, Post, or Do return and will
	// interrupt reading of the Response.Body.
	//
	// A Timeout of zero means no timeout.
	//
	// The Client cancels requests to the underlying Transport
	// as if the Request's Context ended.
	//
	// For compatibility, the Client will also use the deprecated
	// CancelRequest method on Transport if found. New
	// RoundTripper implementations should use the Request's Context
	// for cancellation instead of implementing CancelRequest.
	Timeout time.Duration
```

**Comment by alexanderbez** [comment]
Ahhh right, could it perhaps be the headers we are trying to write?

**Comment by cmwaters** [comment]
> could it perhaps be the headers we are trying to write?

Could you elaborate.

I was also wondering if by providing a context to the client we override the `Timeout`

**Comment by cmwaters** [comment]
Lol I added my favourite debugging tool to see what was happening:

```
if c.client.Timeout == 0 {
panic("hello?")
}
```

and it triggered so somewhere we are resetting it to zero. I shall investigate further

**Comment by alexanderbez** [comment]
Yup, good ole' reliable print statements, never let me down. Good catch. I'm sure you'll be able to follow the bread crumbs and see where that's happening 👍

**Comment by cmwaters** [comment]
Closing due to #6145.

Within the light client RPC server there are two requests made to full nodes:

1. For the data itself whether it be a block or consensus params
2. For the light block needed to validate that header

The second one had a timeout. The first one didn't. #6145 introduces a default 10s timer on the first request
