### ISSUE TITLE
Timestamp not included in log output in JSON log format

### ISSUE THREAD

**Issue by strophy** [tendermint/tendermint#6146]
**Tendermint version** 0.34.3

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/dashevo/js-drive

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **Install tools**:
- **Others**:

**What happened**: Enabled `log_format = "json"` in `config.toml`

**What you expected to happen**: "plain" log output includes a timestamp. I expected to also see the timestamp in the JSON log output, preferably in UNIX_MS format.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):
Enable `log_format = "json"` in `config.toml` and view logs

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
`log_format = "plain"` <-- each line starts with a timestamp
```
I[2021-02-18|20:28:27.484] Executed block                               module=state height=6177 validTxs=0 invalidTxs=0
I[2021-02-18|20:28:27.529] Committed state                              module=state height=6177 txs=0 appHash=1F1780FC6782FE7FB25F587CB9E16C16CFD08242
I[2021-02-18|20:31:28.130] Executed block                               module=state height=6178 validTxs=0 invalidTxs=0
I[2021-02-18|20:31:28.137] Committed state                              module=state height=6178 txs=0 appHash=1F1780FC6782FE7FB25F587CB9E16C16CFD08242
```
`log_format = "json"` <-- no timestamp data available
```
{"_msg":"Executed block","height":6175,"invalidTxs":0,"level":"info","module":"state","validTxs":0}
{"_msg":"Committed state","appHash":"1F1780FC6782FE7FB25F587CB9E16C16CFD08242","height":6175,"level":"info","module":"state","txs":0}
{"_msg":"Executed block","height":6176,"invalidTxs":0,"level":"info","module":"state","validTxs":0}
{"_msg":"Committed state","appHash":"1F1780FC6782FE7FB25F587CB9E16C16CFD08242","height":6176,"level":"info","module":"state","txs":0}
```

**Config (you can paste only the changes you've made)**:
`log_format = "json"`

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by alexanderbez** [comment]
What logger are you using?

**Comment by strophy** [comment]
I'm pretty sure it is the built-in one, our changes are mostly limited to validator set rotation.

A bit of background: I'm trying to ingest logs into Elasticsearch with Filebeat. These tools work natively with JSON, so I want log output in JSON. Because a timestamp is missing in the output, Filebeat applies a timestamp each time the log is read, which can differ from the event time by up to 30s.

**Comment by alexanderbez** [comment]
Yeah, it's due to go-kit and our custom logging wrapper around it.

I'd advocate for using [zap](https://github.com/uber-go/zap) or [zerolog](https://github.com/rs/zerolog) directly and removing our custom logging wrapper, however, we should still keep our logging interface for those who wish to use something else.
