### ISSUE TITLE
Start long running computation at block N and only include results at N+Y

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#615]
The idea is that I might want to build an app that requires some heavy computation such as machine learning. Currently we describe the ABCI programming model that a transaction gets executed and the results should be immediately reflected in the state.

My proposal is that we extend this to be asynchronous. Ideally, an app should be able to receive a transaction, which causes it to start a long-running computation in a thread, and then the app can include that state change at some later point in another block.

One of the issues I see is that all apps need to include that state change at the same block and hence the transaction might need to include after how many blocks to include the change. Maybe there can be a model where the results don't need to get included in the same block across all nodes, but are rather stored in a separate data structure that only enforces eventual consistency. 

This is an issue designed to talk about possible solutions.

**Comment by adrianbrink** [comment]
From @rigelrozanski:

In staking, we need to do something like this, when processing unbonding tokens, the unbonded tokens need to remain in a queue, unbonded but still slashable, and then some amount of blocks later be actually released from the queue and nolonger slashable.  So to answer your question yes, this can be a achieved right now by simply using an on-chain stack or queue and processing it with the beginblock/endblock methods

**Comment by ebuchman** [comment]
Does this require a change to Tendermint? This behaviour should be possible already!

Please clarify if this requires something new from Tendermint, otherwise I think we can close this issue.

**Comment by adrianbrink** [comment]
My question here is more whether it is possible to this without requiring to specify at which block to include the result of the transaction?

**Comment by adrianbrink** [comment]
@zramsay Could we include this somewhere in the documentation. I have been asked about this on the chat.

**Comment by zramsay** [comment]
will be handled in: https://github.com/zramsay/tendermint/issues/4
