### ISSUE TITLE
TxSearch to return results in descending order by default

### ISSUE THREAD

**Issue by hcchang0701** [tendermint/tendermint#6155]
## Summary

Return results in descending order by default when querying multiple transactions

## Problem Definition

In practice, the **newer** transactions (with higher block heights) are what users/developers are more interested in.
However, the top-level application, Gaia, doesn't allow sorting in the query of transaction history via its interface to the Tendermint core's search function, while Tendermint used to return search results ascendingly by default, which is not a good user experience.

## Proposal

![snapshot](https://user-images.githubusercontent.com/19609845/108591022-84361d80-73a1-11eb-84fd-63dbc1c408c9.png)

To completely solve the problem, I suggest to revise the `switch orderBy` statement located at _rpc/core/tx.go_, where case `""` combine with case `desc` rather than case `asc`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I think this is a fair proposal. However, I should note that the underlying application should be explicitly providing the `orderBy` value. I believe the SDK is currently hard-coded to `""`.

**Comment by hcchang0701** [comment]
May I ask when I can expect this issue to be resolved? I'm quite urgently looking for this feature~

**Comment by alexanderbez** [comment]
I believe this is a breaking change in semantic behavior. I'm not sure if this constitutes as a breaking change though. Perhaps we backport this to 0.34? Not sure...

**Comment by melekes** [comment]
> May I ask when I can expect this issue to be resolved? I'm quite urgently looking for this feature~

Done. Note we'll NOT backport this to 0.34 because it's a breaking change.

**Comment by alexanderbez** [comment]
Agree. Note, we **can** introduce this into Stargate via a non-breaking manner, but this work must be done SDK-side. The SDK will have to expose the `orderBy` parameter via it's query API and pass that value to Tendermint.

/cc @alessio

**Comment by alessio** [comment]
Will do!
