### ISSUE TITLE
Issue with peer connectivity

### ISSUE THREAD

**Issue by kanishkatn** [tendermint/tendermint#6156]
**Tendermint version**: 0.26.4

**ABCI app**: built-in

**Environment**:
- **OS** : Amazon Linux

**What happened**:
I have created a test cluster with 5 nodes on AWS. The metric `tendermint_p2p_peers` is between 1-3 for the nodes in the cluster.

This is the error I am getting 
`"Error reconnecting to peer. Trying again"  err="auth failure: secret conn failed: EOF" module=rpc-server protocol=websocket round=0 tries=1`

**What you expected to happen**:
All the nodes should be able to connect to each other. i.e the metric `tendermint_p2p_peers` should be 4

**Have you tried the latest version**: no

**Anything else we need to know**:

1. I am running the nodes behind an external NGINX proxy server which streams tcp requests
2. On NGINX I am seeing `recv() failed (104: Connection reset by peer) while proxying and reading from upstream` errors
3. The `external_address` is set on all nodes
4. After adding more logs on tendermint, I found that the error is being thrown here: https://github.com/tendermint/tendermint/blob/1f01e5d72667e8ce4507fd6a602bb617451f32ab/p2p/conn/secret_connection.go#L301

**If I run it without the NGINX proxy, `tendermint_p2p_peers` is 4 for all the nodes**

**Comment by melekes** [comment]
Hey @kanishkatn! Could you make sure that all 4 nodes are running the same version of Tendermint? `protocol=websocket` seems incorrect to me. Can you paste the content of `tendermint_p2p_peers` here? It should look more or less like `tendermint_p2p_peers="tcp://125.169.123.140:46657,tcp://19.113.0.154:46657,tcp://151.100.106.151:46657,tcp://53.89.15.147:46657"`. (NOTE: these are random IPs)

Also, v0.26.4 is outdated. Please use the latest version - https://github.com/tendermint/tendermint/releases/tag/v0.34.7

**Comment by kanishkatn** [comment]
Hey @melekes ,
Thank you for your response. 

Yes, all 5 nodes are running the same version to tendermint. 

I thought `tendermint_p2p_peers` is just the metric. Do you mean `persistent_peers` in config.toml? if not, where can I find it?

**Comment by melekes** [comment]
> Do you mean persistent_peers in config.toml?

yes, that's what I meant.

**Comment by kanishkatn** [comment]
I have configured the persistent_peers to have all the 5 nodes in the cluster. 

They are in the format: `<ID>@<IP>:26656`

**Comment by melekes** [comment]
If you're using v0.26, then the correct format is `<IP1>:46656,<IP2>:46656, ....` I believe.

**Comment by kanishkatn** [comment]
It is working with the format I'm using though. 

I mean, nodes are able to connect to peers. It's just that, it's not connecting to all of them!

**Comment by melekes** [comment]
Do you see any errors in the log of nodes who are disconnecting? Usually EOF means the remote peer closed the connection because of some error.

**Comment by kanishkatn** [comment]
with the error log level, I didn't notice anything. There were few conn rejections stating it is a duplicate. 
I will run it again tomorrow and share it with you. 

Thank you!

**Comment by kanishkatn** [comment]
Hey @melekes ,

This is the only rejection log I could find. 
`level=info msg="Inbound Peer rejected"  connection=consensus err="filtered CONN<35.72.182.73:41180>: duplicate CONN<35.72.182.73:41180>" module=rpc-server numPeers=0 protocol=websocket`

I also noticed i/o timeout along with EOF.

**Comment by melekes** [comment]
> If I run it without the NGINX proxy, tendermint_p2p_peers is 4 for all the nodes

maybe the issue is with your NGINX setup then?

**Comment by kanishkatn** [comment]
I believe so, yes! 
It would be great if I can find the exact reason for a remote peer to close the connection. 

Could you please point me to the module responsible for handling this?

**Comment by melekes** [comment]
Since this is likely the issue with Nginx, then you need to look at its logs. 

@marbar3778 do you have an example of Nginx configuration at hand?

**Comment by kanishkatn** [comment]
Hi @melekes ,

I've fixed this. 

Since all the p2p traffic was being routed through the nginx proxy server, the ips in the peer connection were the same. The proxy server was just using different sockets to connect to the tendermint node. So, the new peers were being rejected. 

I fixed it by enabling `AllowDuplicateIP` in tm p2p config. 

Thank you for your time!
