### ISSUE TITLE
Make linters pass to move towards standard linting process

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#616]
All the linters described [here](https://github.com/tendermint/ethermint/blob/develop/Makefile#L69) should pass when run against this codebase. 

This will be a massive PR and initially it is okay to just opt out using comments.

**Comment by zramsay** [comment]
started in #643

**Comment by zramsay** [comment]
https://github.com/tendermint/coding/issues/30 this is a cross-repo and always-ongoing process
