### ISSUE TITLE
Events can be dropped by http events listener

### ISSUE THREAD

**Issue by hydrogen18** [tendermint/tendermint#6161]
I've been working with the HTTP client that streams events back from a tendermint node. I was going through the code and found this

https://github.com/tendermint/tendermint/blob/master/rpc/client/http/http.go#L712

As far as I can tell what happens here is

1. If the channel is unbuffered, a blocking send to the channel is made
2. If the channel is buffered, a non-blocking send to the channel is made. If the channel is full, it drops the value

I'm not sure this makes sense at all. Generally, I use buffered channels between goroutines with small capacities. Anecdotally, this provides a decent performance increase since the two goroutines aren't synchronized any longer by the presence of an unbuffered.

Dropping values **only when a channel is buffered** makes little to no sense to me. Additionally there isn't any way for an application to know this is happening since it only visible in the logs.

What I'm trying to establish here is

1. Is there any real world use case for this logic? It seems like blocking until the send completes is the correct behavior
2. If this behavior really is desired, can this be made configurable somehow. I've been part of the Akash team for a while now and on the client side we would definitely prefer the goroutine to block.

**Comment by melekes** [comment]
I don't remember exactly why we've decided to drop events. My guess is to avoid the scenario where 1 subscription handling loop (reading from `out` channel) could block other loops (subscriptions) from receiving events when the former one is slow. But you have a good point about application not knowing about dropped events.

**Comment by melekes** [comment]
opened https://github.com/tendermint/tendermint/pull/6163

I'm still not sure whenever this is an optimal solution. Maybe instead we should run a goroutine per subscription and block there instead of the main `eventListener` loop. That way we don't loose events AND subscriptions are independent of each other.

**Comment by cmwaters** [comment]
> Maybe instead we should run a goroutine per subscription and block there instead of the main eventListener loop

I perhaps don't have the full context, but this would make sense to me

**Comment by hydrogen18** [comment]
> opened #6163
> 
> I'm still not sure whenever this is an optimal solution. Maybe instead we should run a goroutine per subscription and block there instead of the main `eventListener` loop. That way we don't loose events AND subscriptions are independent of each other. wdyt?

I'm not entirely sure this solves the problem. If you've got 5 goroutines feeding 5 subscribers, you still need to feed the 5 goroutines from a common point. Either you block trying to send to one of the feeders, or drop sending to one of the feeders. This means the problem has just moved from one location in the code to another.

The simplest solution is probably just to 
1. Drop events by default when the channel is full
2. Allow the caller to disable dropping events entirely, if they need that behavior.
