### ISSUE TITLE
node halts after restart and replaying blocks

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6169]
## Summary

This stems from the e2e tests. It seems that a node which restarted and then replays the blocks gets stuck in consensus. 

In this scenario:
- the validator restarted at 1050
- replayed block 1050
- After replaying was done, it continued to timeout, being stuck on height 1051 (it's peers are at height 1057)

## Node Configuration

```
[node.validator08]
     mode = "validator"
     persistent_peers = ["validator04", "validator06", "validator07", "validator01"]
     database = "badgerdb"
     abci_protocol = "tcp"
     privval_protocol = "grpc"
     start_at = 1005
     fast_sync = ""
     state_sync = true
     persist_interval = 1
     snapshot_interval = 3
     retain_blocks = 3
     perturb = ["disconnect", "restart"]
     log_level = ""
     [node.validator08.misbehavior
```

Full logs: https://gist.github.com/cmwaters/b235a52b0eb88ff483a8494f900b9a57

e2e test: https://github.com/tendermint/tendermint/runs/1957759252?check_suite_focus=true

I have also seen this on other occasions

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Out of curiosity, have you seen these issues before the consensus p2p refactor?

**Comment by cmwaters** [comment]
I don't recall so but I haven't honestly been tracking e2e failures too closely

**Comment by alexanderbez** [comment]
I see this from the logs:

```
2021-02-23T02:43:54.8054037Z [32;1mvalidator08    |[0m E[2021-02-23|02:43:09.187] data has been corrupted in last height of consensus WAL module=consensus err="DataCorruptionError[failed to read data: EOF (read: 25318, wanted: 26237)]" height=1051
2021-02-23T02:43:54.8056023Z [32;1mvalidator08    |[0m E[2021-02-23|02:43:09.187] the WAL file is corrupted; attempting repair module=consensus err="DataCorruptionError[failed to read data: EOF (read: 25318, wanted: 26237)]"
```
