### ISSUE TITLE
rpc/lib/server: Provide SSL for Websocket endpoint if possible

### ISSUE THREAD

**Issue by srmo** [tendermint/tendermint#617]
FEATURE REQUEST
The Websocket endpoint should support SSL (WSS) preferrably with a configurable certificate.

**Comment by melekes** [comment]
@odeke-em are you still working on this?

**Comment by odeke-em** [comment]
@melekes yes in deed, I am working on it and will be fixing it soon.

**Comment by srmo** [comment]
Will this also allow TLS on the rest endpoints or do you guys require an additional issue for that?
PS: thanks for taking care! :)

**Comment by srmo** [comment]
Additionally, can you imagine client cert authentication for this?

**Comment by melekes** [comment]
@odeke-em are you still working on this?

**Comment by melekes** [comment]
again, why not use something like nginx and terminate ssl there?

**Comment by ebuchman** [comment]
we've decided against doing this for now in favour of just using nginx to handle things like tls, auth, rate limitting, etc.

**Comment by odeke-em** [comment]
Thanks for resurrecting this @ebuchman. In fact @ebuchman if perhaps you recall from our discussions and DMs in I believe late September 2017 or October 2017, you and I came to the same conclusion that the frontend proxy should be the one to handle such :)
