### ISSUE TITLE
Avoid tmos.Exit() on privval/file.go, return error instead

### ISSUE THREAD

**Issue by jordipainan** [tendermint/tendermint#6182]
## Summary

Some operations on privval/file.go performs an os.Exit(1) if error instead of returning the error.

## Problem Definition

Some operations on privval/file.go performs an os.Exit(1) if error instead of returning the error.

I understand this is done because things like `priv_validator_state.json` are important for a running node and the node should not even been started without them.

But if Tendermint is used as a library this is bit problematic as it is impossible to catch the error and the program just terminates.

Examples:
- https://github.com/tendermint/tendermint/blob/master/privval/file.go#L202
- https://github.com/tendermint/tendermint/blob/master/privval/file.go#L220

## Proposal

I think it would be more flexible to just return the actual error.

____

Thank you !

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks for opening up an issue @jordipainan. I do agree here that we should instead rely on returning errors and enforce the caller to handle them as they wish.
