### ISSUE TITLE
docs: how to read logs

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#619]

**Comment by Greg-Szabo** [comment]
How to understand /dump_consensus_state. Ideally a walkthough of the options would be best. Less ideally a generic overview helps too.

**Comment by Greg-Szabo** [comment]
List of modules that log into the tendermint.log and a little overview what they do. This might be already available somewhere hidden in dev documentation, I'm not sure. (I'm talking about the module= p2p, consensus, mempool, etc entries) A little description on the most common entries.

**Comment by ebuchman** [comment]
@melekes do you want to try to take this on as an exercise in demonstrating your increasing mastery of Tendermint core?

**Comment by melekes** [comment]
hah) yeah, sure
