### ISSUE TITLE
version command should not check the config file

### ISSUE THREAD

**Issue by ratranqu** [tendermint/tendermint#620]
BUG REPORT:

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): `0.10.2-'b467515` and `0.10.3-'8d76408`

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS Sierra
- **Install tools**: download zip from github.com/tendermint/tendermint
- **Others**:

**What happened**:
```
> ./tendermint version
ERROR: Failed to parse default log level (pair *:notice, list *:notice): Expected either "info", "debug", "error" or "none" level, given notice
```

but 

```
 > ./tendermint --home ./.ethermint/tendermint version
0.10.2-'b467515
```
**What you expected to happen**:
IMHO, the `--home` option should not be necessary (including defaults, i.e. the version should show even if the home is not properly setup or not available where expected)

**How to reproduce it** (as minimally and precisely as possible):
see above.

**Anything else do we need to know**:

**Comment by zramsay** [comment]
i encountered this as well. Change you `~/.tendermint/config.toml` so that `log_level` _isn't_ `notice`

**Comment by ratranqu** [comment]
thanks @zramsay! I have a workaround indeed. I would vote to have this removed at some point in the future as it's intrinsically coupling a config item to returning a version (which IMHO should not be).

**Comment by zramsay** [comment]
cool, yeah. re-naming issue to reflect the real problem

**Comment by adrianbrink** [comment]
`tendermint version` should definitely work without any other flag.

**Comment by ebuchman** [comment]
Fixed on develop! https://github.com/tendermint/tendermint/pull/623
