### ISSUE TITLE
light: rpc /status call should return info about the light client

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6200]
## Summary

Currently, when `/status` is called on a light client rpc server, the light client returns
the status of the primary full node that it is connected to.

## Proposal

We may consider it more helpful to users of light clients if `/status` actually returned the status
of the light client itself. One such example could be to use `SyncInfo` for the first and last
trusted blocks in the light clients store.

Unfortunately, I don't think the other data structures: `NodeInfo` and `ValidatorInfo` map to well
to the light client. Perhaps we can find a way to tweak it. 

Information that light client operators may want to know:

- the primary that the light client is connected to
- the witnesses that the light client is connected to
- the light client version / rpc version

This is just suggestive

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I think this makes sense 👍

**Comment by tessr** [comment]
@cmwaters is this something you're thinking of tackling, or would this be a good issue for an external contributor?

**Comment by cmwaters** [comment]
Yeah, once we've sketched out what the return values are / should be then we can mark this as a good issue for an external contributor

**Comment by tessr** [comment]
@cmwaters I'm assigning this to you, to specify what should go in this endpoint, and then I'll mark it as good first issue (or you can implement it, either way).

**Comment by tessr** [comment]
@williambanfield I saw this back in your onboarding doc - did you decide to tackle it?

**Comment by williambanfield** [comment]
@tessr not currently. I've been more focused on the other work you sent, namely removing mocks and providing occasional hands in the e2e tests. Happy to switch over if this seems more pressing.

**Comment by tessr** [comment]
No problem at all - I actually was thinking of making it part of Michael's onboarding, but didn't want to get any wires crossed!
