### ISSUE TITLE
Block time skew in docker containers

### ISSUE THREAD

**Issue by ethanfrey** [tendermint/tendermint#6217]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

v0.34.7 but I have had this on all v0.34.x versions and remember a similar issue on 0.33

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

Both simapp v0.41.3 and wasmd v0.15.1

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

Host: Ubuntu 20.04 (same under 18.04 and other devs on Mac OSX)
Linux docker container

**What happened**:

I run two one-node blockchains inside docker containers for CI tests on https://github.com/confio/ts-relayer. Sometimes it dies with block time difference. (The header we submit for updating client is more than 20s in the future of the receiving chain). This sometimes happens by itself, but it is pretty easy to reproduce by closing the laptop (putting it in standby) and opening it again.

Note that I have sub-second blocktimes (commit timeout set to 250ms) to make the CI tests run quicker. Should not be an issue as tendermint counts time in nanoseconds.

**What you expected to happen**:

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

```
git clone https://github.com/confio/ts-relayer.git
cd ts-relayer

# open 2 consoles and run the following
# console one
./scripts/simapp/start.sh
# console two
./scripts/wasmd/start.sh
```

Wait a bit, or put your laptop in suspend mode and awaken it. Then try to query the block times.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

Investigating a bit, I found the clock skew only affected tendermint, not the system clock in docker

```
# this is the wasmd container
$ curl -s http://localhost:26659/block | jq .result.block.header.time
"2021-03-05T12:44:41.202275656Z"

# this is the simapp container
$ curl -s http://localhost:26658/block | jq .result.block.header.time
"2021-03-05T12:49:34.038483791Z"

$ date && docker exec wasmd date && docker exec simapp date
vie 05 mar 2021 13:33:12 CET
Fri Mar  5 12:33:13 UTC 2021
Fri Mar  5 12:33:13 UTC 2021
```

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by melekes** [comment]
I've seen at least ten issues related to Golang time and Docker (here's one for example https://github.com/golang/go/issues/27090). Not sure what the solution is. Maybe try installing NTP?

**Comment by alexanderbez** [comment]
> I seriously think you enforce some minimum block time in tendermint "BFT blocktime". If that is 1s and I have 250ms block time, then we will get such a skew.

The minimum time between blocks is 1ms: https://github.com/tendermint/tendermint/blob/8c539f7c2be332afbf5fd6db5b46cd7f2f3d4a97/consensus/state.go#L2198

**Comment by ethanfrey** [comment]
That seems like a very reasonable minimum.

To end up several minutes (possibly hours) off is worrying. Please play around a bit with my setup above.

I just had a pair open to run CI scripts. I ran the following command counting 2-3 second between each run.
Note that the nanoseconds are identical, and blocks are running 3-4 times faster than reality

```
$ TZ="UTC" date -Ins && curl -s http://localhost:26658/block | jq .result.block.header.time
2021-03-09T23:55:57,130822013+00:00
"2021-03-10T01:24:06.187521015Z"

$ TZ="UTC" date -Ins && curl -s http://localhost:26658/block | jq .result.block.header.time
2021-03-09T23:55:59,395079678+00:00
"2021-03-10T01:24:15.187521015Z"

$ TZ="UTC" date -Ins && curl -s http://localhost:26658/block | jq .result.block.header.time
2021-03-09T23:56:01,860751374+00:00
"2021-03-10T01:24:24.187521015Z"

$ TZ="UTC" date -Ins && curl -s http://localhost:26658/block | jq .result.block.header.time
2021-03-09T23:56:04,346044810+00:00
"2021-03-10T01:24:34.187521015Z"
```

**Comment by ethanfrey** [comment]
More data. Note the perfect 1 second block times, 3.5 hours in the future

```
$ TZ="UTC" date -Ins
2021-03-10T12:24:01,887101906+00:00

$ curl -s http://localhost:26658/block?height=22531 | jq .result.block.header.time
"2021-03-10T15:58:20.588721675Z"
$ curl -s http://localhost:26658/block?height=22530 | jq .result.block.header.time
"2021-03-10T15:58:19.588721675Z"
$ curl -s http://localhost:26658/block?height=22529 | jq .result.block.header.time
"2021-03-10T15:58:18.588721675Z"
$ curl -s http://localhost:26658/block?height=22528 | jq .result.block.header.time
"2021-03-10T15:58:17.588721675Z"
```

**Comment by ethanfrey** [comment]
Ah, this was in `genesis.json`:

```json
{
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
  }
}
```

I will regenerate and see if it works better

**Comment by cmwaters** [comment]
Right sorry thought it was in config.toml but actually it's a consensus param

**Comment by ethanfrey** [comment]
No need to apologize. I found it and fixed it and it is looking better. Great help!

~250ms between headers (and varying nanoseconds): 

```
$ curl -s http://localhost:26658/block?height=132 | jq .result.block.header.time
"2021-03-10T15:36:39.283303952Z"
$ curl -s http://localhost:26658/block?height=133 | jq .result.block.header.time
"2021-03-10T15:36:39.534920774Z"
$ curl -s http://localhost:26658/block?height=134 | jq .result.block.header.time
"2021-03-10T15:36:39.780787819Z"
$ curl -s http://localhost:26658/block?height=135 | jq .result.block.header.time
"2021-03-10T15:36:40.031159885Z"
```

And it stays close to the real time:

```
$  TZ="UTC" date -Ins && curl -s http://localhost:26658/block | jq .result.block.header.time
2021-03-10T15:38:12,531100233+00:00
"2021-03-10T15:38:12.093738597Z"
```

**Comment by ethanfrey** [comment]
My issue is resolved. It seems like this is fixed in master.

Feel free to close this issue if you wish, or maybe just add some docs (somewhere?) Maybe this github issue is the best docs, when someone searches

**Comment by cmwaters** [comment]
Glad to hear. Yeah I will close the issue and fingers crossed people land here if they get any more docker timing troubles
