### ISSUE TITLE
the same transaction appears in two different blocks

### ISSUE THREAD

**Issue by xiangjianmeng** [tendermint/tendermint#6219]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): v0.33.9

**ABCI app** (name for built-in, URL for self-written if it's publicly available): cosmos v0.39.2，[okexchain v0.16.6](https://github.com/okex/okexchain/tree/v0.16.8)

**Environment**:
- **OS** (e.g. from /etc/os-release): mac os 11.2.1
- **Install tools**: make
- **Others**:

**What happened**:

1. the same transaction appears in two different blocks

**What you expected to happen**:

2. the same transaction should not appears in two different blocks, that is to say that one txhash should only appear once on the whole block chain.

**Have you tried the latest version**: yes/no
no

**How to reproduce it** (as minimally and precisely as possible):
1. change the code in https://github.com/tendermint/tendermint/blob/1baf670c60c1c97c42523f2c14c6c0768812856c/abci/client/client.go#L102 as follow to simulate a scenario in concurrency to accelerate scene reproduction:
```
var b bool = true

// Sets the callback for this ReqRes atomically.
// If reqRes is already done, calls cb immediately.
// NOTE: reqRes.cb should not change if reqRes.done.
// NOTE: only one callback is supported.
func (reqRes *ReqRes) SetCallback(cb func(res *types.Response)) {
	reqRes.mtx.Lock()

	if reqRes.done {
		reqRes.mtx.Unlock()
		if b {
			b = false
			time.Sleep(time.Second*10)
		}
		cb(reqRes.Response)
		return
	}

	reqRes.cb = cb
	reqRes.mtx.Unlock()
}
```
2. send two txs by a account with sync mode, tx1 with sequence 1, tx2 with sequence 2. The sequence of the account on chain is 1.

3. all txs are added into mempool, the tx2 will be added into mempool befor tx1. Then tx2 is proposed into block ahead of tx1, so the tx2's sequence is not equal to  the sequence on chain when executing antehandler in deliverTx.

4. the tx1's sequence is satisfied. And the tx2 will not be removed when call recheckTx, because the tx2's sequence is satisfied after the tx1 handled, so tx2 is proposed into the next block.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by alexanderbez** [comment]
So the steps you've laid out all seem reasonable to me. Two different txs sent from the same account with correct nonce handling. Yet, I fail to see where the same hash is generated based on the information you provided.

AFAIK, it is the application that determines the hash of the tx based on it's encoded value.

**Comment by xiangjianmeng** [comment]
> So the steps you've laid out all seem reasonable to me. Two different txs sent from the same account with correct nonce handling. Yet, I fail to see where the same hash is generated based on the information you provided.
> 
> AFAIK, it is the application that determines the hash of the tx based on it's encoded value.

the same hash is the hash of tx2. That is to say tx2 will be packaged into two different blocks.

**Comment by xiangjianmeng** [comment]
comment of `updateMtx ` https://github.com/tendermint/tendermint/blob/1c314c830e56da52b4b744ed849c6b5dd7aef94b/mempool/clist_mempool.go#L50 denote that its purpose is to prevent concurrent execution of `CheckTx` or `ReapMaxBytesMaxGas(ReapMaxTxs) ` methods, but all `CheckTx` or `ReapMaxBytesMaxGas` use RLock().

**Comment by melekes** [comment]
> > So the steps you've laid out all seem reasonable to me. Two different txs sent from the same account with correct nonce handling. Yet, I fail to see where the same hash is generated based on the information you provided.
> > AFAIK, it is the application that determines the hash of the tx based on it's encoded value.
> 
> the same hash is the hash of tx2. That is to say tx2 will be packaged into two different blocks.
> 
> 1. tx1 and tx2 are packaged into the first block. tx2 is executed failed in the first block, because its sequence is not equal to 1, and the sequence on chain is updated to 2 after tx1 is executed on deliverTx.
> 2. then tx2 is packaged into second block, and is executed succeedly because its sequence is equal to 2.
> 3. so the same tx2 appears two different blocks

Do we claim somewhere in the docs that this situation is not possible?

**Comment by xiangjianmeng** [comment]
> > > So the steps you've laid out all seem reasonable to me. Two different txs sent from the same account with correct nonce handling. Yet, I fail to see where the same hash is generated based on the information you provided.
> > > AFAIK, it is the application that determines the hash of the tx based on it's encoded value.
> > 
> > 
> > the same hash is the hash of tx2. That is to say tx2 will be packaged into two different blocks.
> > 
> > 1. tx1 and tx2 are packaged into the first block. tx2 is executed failed in the first block, because its sequence is not equal to 1, and the sequence on chain is updated to 2 after tx1 is executed on deliverTx.
> > 2. then tx2 is packaged into second block, and is executed succeedly because its sequence is equal to 2.
> > 3. so the same tx2 appears two different blocks
> 
> Do we claim somewhere in the docs that this situation is not possible?

I haven't seen the claim in the docs. You mean that it Is normal and this scenario is allowed?

**Comment by alexanderbez** [comment]
> > So the steps you've laid out all seem reasonable to me. Two different txs sent from the same account with correct nonce handling. Yet, I fail to see where the same hash is generated based on the information you provided.
> > AFAIK, it is the application that determines the hash of the tx based on it's encoded value.
> 
> the same hash is the hash of tx2. That is to say tx2 will be packaged into two different blocks.
> 
> 1. tx1 and tx2 are packaged into the first block. tx2 is executed failed in the first block, because its sequence is not equal to 1, and the sequence on chain is updated to 2 after tx1 is executed on deliverTx.
> 2. then tx2 is packaged into second block, and is executed succeedly because its sequence is equal to 2.
> 3. so the same tx2 appears two different blocks

This doesn't make sense to me. How can tx1 and tx2 be in block, say H, and then tx2 again is included in block, say H+1?

`CheckTx` should fail for tx2 and thus never even enter block H. Thus, block H should _only_ have tx1, unless you validators are faulty.

**Comment by xiangjianmeng** [comment]
> > > So the steps you've laid out all seem reasonable to me. Two different txs sent from the same account with correct nonce handling. Yet, I fail to see where the same hash is generated based on the information you provided.
> > > AFAIK, it is the application that determines the hash of the tx based on it's encoded value.
> > 
> > 
> > the same hash is the hash of tx2. That is to say tx2 will be packaged into two different blocks.
> > 
> > 1. tx1 and tx2 are packaged into the first block. tx2 is executed failed in the first block, because its sequence is not equal to 1, and the sequence on chain is updated to 2 after tx1 is executed on deliverTx.
> > 2. then tx2 is packaged into second block, and is executed succeedly because its sequence is equal to 2.
> > 3. so the same tx2 appears two different blocks
> 
> This doesn't make sense to me. How can tx1 and tx2 be in the _same_ block, say H, and then tx2 again is included in block, say H+1?
> 
> `CheckTx` should fail for tx2 and thus never even enter block H. Thus, block H should _only_ have tx1, unless you validators are faulty.

tx1 pass CheckTx first, then tx2 pass CheckTx. But tx2 enter mempool before tx1. Because the code can not promise firrst pass CheckTx first enter mempool.

**Comment by alexanderbez** [comment]
1. What gives these txs the same hash? They should be different if not for the very reason they have different nonces, right?
2. Why is that the order of `CheckTx` (tx1 -> tx2) is not the same as the order of execution/inclusion in a block from the mempool? I.e. why is `CheckTx` tx1 -> tx2, but `DeliverTx` tx2 -> tx1? @melekes

**Comment by xiangjianmeng** [comment]
> 1. What gives these txs the same hash? They should be different if not for the very reason they have different nonces, right?
> 2. Why is that the order of `CheckTx` (tx1 -> tx2) is not the same as the order of execution/inclusion in a block from the mempool? I.e. why is `CheckTx` tx1 -> tx2, but `DeliverTx` tx2 -> tx1? @melekes

The `CheckTx` of mempool will be executed concurrently. There is no lock to promise that  `mem.proxyAppConn.CheckTxAsync` and tx entering mempool are atomic.

please refer:
https://github.com/tendermint/tendermint/blob/884d4d525299e4d43ab881ac19062501c1e09ddf/mempool/clist_mempool.go#L298

**Comment by melekes** [comment]
> 2. Why is that the order of `CheckTx` (tx1 -> tx2) is not the same as the order of execution/inclusion in a block from the mempool? I.e. why is `CheckTx` tx1 -> tx2, but `DeliverTx` tx2 -> tx1? @melekes

that should not be the case. if it is, then I would say it's a regression because it was the case before.

**Comment by melekes** [comment]
> the same transaction should not appears in two different blocks, that is to say that one txhash should only appear once on the whole block chain.

Tendermint does not guarantee that. Of course, it's possible to solve this by allowing Tendermint to introspect transactions. Please add your suggestion in https://github.com/tendermint/spec/pull/154.

**Comment by melekes** [comment]
> Why is that the order of CheckTx (tx1 -> tx2) is not the same as the order of execution/inclusion in a block from the mempool? I.e. why is CheckTx tx1 -> tx2, but DeliverTx tx2 -> tx1?

@xiangjianmeng is ^ the case? did the ABCI app first see `CheckTx(tx1)`, then `CheckTx(tx2)`, then `DeliverTx(tx2)`, then `DeliverTx(tx1)`?

**Comment by xiangjianmeng** [comment]
> > Why is that the order of CheckTx (tx1 -> tx2) is not the same as the order of execution/inclusion in a block from the mempool? I.e. why is CheckTx tx1 -> tx2, but DeliverTx tx2 -> tx1?
> 
> @xiangjianmeng is ^ the case? did the ABCI app first see `CheckTx(tx1)`, then `CheckTx(tx2)`, then `DeliverTx(tx2)`, then `DeliverTx(tx1)`?

Yes, it is.

**Comment by xiangjianmeng** [comment]
What I encounter that a account send tx1, tx2 ...... tx50 with strictly increasing sequence. And all 50 txs enter the mempool,  the order of all txs in block is tx2, tx1, tx3, tx4, tx5 ...... tx50, only tx1 is executed succeed, all others failed.

**Comment by melekes** [comment]
> > > Why is that the order of CheckTx (tx1 -> tx2) is not the same as the order of execution/inclusion in a block from the mempool? I.e. why is CheckTx tx1 -> tx2, but DeliverTx tx2 -> tx1?
> > 
> > 
> > @xiangjianmeng is ^ the case? did the ABCI app first see `CheckTx(tx1)`, then `CheckTx(tx2)`, then `DeliverTx(tx2)`, then `DeliverTx(tx1)`?
> 
> Yes, it is.

Do you have a log from your ABCI app?

**Comment by xiangjianmeng** [comment]
> > > > Why is that the order of CheckTx (tx1 -> tx2) is not the same as the order of execution/inclusion in a block from the mempool? I.e. why is CheckTx tx1 -> tx2, but DeliverTx tx2 -> tx1?
> > > 
> > > 
> > > @xiangjianmeng is ^ the case? did the ABCI app first see `CheckTx(tx1)`, then `CheckTx(tx2)`, then `DeliverTx(tx2)`, then `DeliverTx(tx1)`?
> > 
> > 
> > Yes, it is.
> 
> Do you have a log from your ABCI app?

No, but you can add sleep like above I have issued to reproduct this case.

**Comment by alexanderbez** [comment]
> What I encounter that a account sends tx1, tx2 ...... tx50 with strictly increasing sequence. And all 50 txs enter the mempool, the order of all txs in block is tx2, tx1, tx3, tx4, tx5 ...... tx50, only tx1 is executed succeed, all others failed.
> Then tx2, tx3, tx4......tx50 are proposed into next block again.

Ahh yes, that's fine and expected I think. Why do tx2...tx50 fail if they all have monotonically increasing nonces?

**Comment by xiangjianmeng** [comment]
> > What I encounter that a account sends tx1, tx2 ...... tx50 with strictly increasing sequence. And all 50 txs enter the mempool, the order of all txs in block is tx2, tx1, tx3, tx4, tx5 ...... tx50, only tx1 is executed succeed, all others failed.
> > Then tx2, tx3, tx4......tx50 are proposed into next block again.
> 
> Ahh yes, that's fine and expected I think. Why do tx2...tx50 fail if they all have monotonically increasing nonces?

tx2,... tx50 in first block fail, but second block succeed.

**Comment by alexanderbez** [comment]
Right, but if they all have monotonically increasing nonces, why do they fail? Is it because they're executed out of order?
