### ISSUE TITLE
Too large genesis file committed to panic with `out of memory`

### ISSUE THREAD

**Issue by KamiD** [tendermint/tendermint#6222]
**Tendermint version** : Tendermint 33.9

**ABCI app** : OKExChain, here is the block explorer for test-net : https://www.oklink.com/okexchain-test

**Environment**:
- **OS** (e.g. from /etc/os-release):  ubuntu 18.04
- **Install tools**:
- **Others**:16G memory, 4 cores CPU

We have activate the evm function on OKExChain which based on ethermint、 cosmos-sdk 39.2 and tendermint 33.9
it works well on our test net and will launch to main net soon
during test, there was lots of evm call transactions run at okexchain-testnet (over 12 millions), and we have done lots of optimization, when we trying to export state data to a genesis file and import it as new states, the panic happened with `out of memory`, its not friendly if chain has been running while a long time and huge state data need export/import

This issue may getting some help : https://github.com/cosmos/iavl/issues/373

**What happened**:
when we trying to export state data to a genesis file and import it as new states, the panic happened with `out of memory`

**What you expected to happen**:
every thing works well

**Have you tried the latest version**: yes/no
no

**How to reproduce it** (as minimally and precisely as possible):
import a large genesis file （over 5GB）

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by alexanderbez** [comment]
Thanks @KamiD, but this issue belongs to the Cosmos SDK. Regardless, there already exists an issue to improve the genesis state UX.
