### ISSUE TITLE
Issues with pruning everything. Can't restart a node

### ISSUE THREAD

**Issue by anilCSE** [tendermint/tendermint#6228]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.34.8

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): 
- **Install tools**:
- **Others**:

**What happened**:
We have recently upgraded Akash Network mainnet to stargate version. There are couple of node operators who are using `pruning everything` setting. It worked fine initially but when they had to restart they started getting 
Detailed logs are here: https://pastebin.com/38271y9M

**What you expected to happen**:
It should restart the node smoothly even for `pruning everything`

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
- Start a chain
- Start a node with `--pruning everything` option
- Stop and try to restart it (it will start throwing errors here)

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
https://pastebin.com/38271y9M

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:
``--pruning everything`
**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

cc @boz

**Comment by AC-Validator** [comment]
Some details collected:

**AWS Server:** Ubuntu 16.04.6 LTS (Xenial Xerus)

**Kernel:** 4.4.0-1109-aws (buildd@lgw01-amd64-017) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #120-Ubuntu SMP Fri Jun 5 01:26:57 UTC 2020

**Compiler:** go version go1.16 linux/amd64

**Processor:**
      product: Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
       vendor: Intel Corp.
       physical id: 1
       bus info: cpu@0
       width: 64 bits
       capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp x86-64 constant_tsc rep_good nopl xtopology nonstop_tsc tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single kaiser fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f rdseed adx smap clflushopt clwb avx512cd xsaveopt xsavec xgetbv1 ida arat pku

**Comment by alexanderbez** [comment]
> app initialization:failed to load latest version: failed to load store: wanted to load target 509 but only found up to 0

This is a Cosmos SDK issue.

**Comment by anilCSE** [comment]
> > app initialization:failed to load latest version: failed to load store: wanted to load target 509 but only found up to 0
> 
> This is a Cosmos SDK issue.

@alexanderbez Is there a way to move this issue onto sdk repo directly?

**Comment by alexanderbez** [comment]
I do not think so, you may just have to close and re-create?

**Comment by marbar3778** [comment]
closing this issue as it should be reopened in the SDK
