### ISSUE TITLE
Comparison of ErrVoteNonDeterministicSignature is ineffective

### ISSUE THREAD

**Issue by hydrogen18** [tendermint/tendermint#6235]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.34.8

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu linux
- **Install tools**:
- **Others**:

**What happened**:

we keep seeing on the AKT network this log message

```
Mar 10 21:09:13 ns500267 akash[4622]: 9:09PM INF failed attempting to add vote err="existing vote: Vote{11:58B9F2517DBF 30460/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 34463C7C581B 622FBE41B8D8 @ 2021-03-10T21:09:12.806234568Z}; new vote: Vote{11:58B9F2517DBF 30460/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 34463C7C581B 622FBE41B8D8 @ 2021-03-10T21:09:12.803861408Z}: non-deterministic signature" module=consensus
```

**What you expected to happen**:

This error did not happen before our upgrade, so we think this is something that got introduced in the upgrade

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):

Start a validator on the akash mainnnet

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
Mar 11 13:06:48 ns500267 akash[4622]: 1:06PM ERR failed to process message err="error adding vote" height=39752 module=consensus msg={"Vote":{"block_id":{"hash":"9796B22DDC7371CB875A7D3E4E3CA532AF521CA441CEE13F68769FA2560601D5","parts":{"hash":"7D9C8962695A7ECE5ABDABDA21F841A89B58973AF0A2F9DEDA0FDC3F28640536","total":1}},"height":39751,"round":0,"signature":"VcmP6qFN6ctUYpUwlg99plKqVeNIzGt7rcgRUNz2iCfe0lJPo7nam/zxBUHws+J2k9faxYzbJFi2BSKfzBBsCw==","timestamp":"2021-03-11T13:06:47.825380216Z","type":2,"validator_address":"58B9F2517DBF8C55573FCFA9853FFF27066D86ED","validator_index":11}} peer=47c9acc0e7d9b244a6404458e76d50b6284bfbbb round=0
Mar 11 13:06:48 ns500267 akash[4622]: 1:06PM INF failed attempting to add vote err="existing vote: Vote{11:58B9F2517DBF 39751/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 9796B22DDC73 55C98FEAA14D @ 2021-03-11T13:06:47.812144039Z}; new vote: Vote{11:58B9F2517DBF 39751/00/SIGNED_MSG_TYPE_PRECOMMIT(Precommit) 9796B22DDC73 55C98FEAA14D @ 2021-03-11T13:06:47.825380216Z}: non-deterministic signature" module=consensus

```

**Anything else we need to know**:

This is logging a wrapped golang Error about the non deterministic signature. It appears the intent is for this else if  to catch this and simply ingore it https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1969 . However, because this is using == operator instead of errors.Is ( or another comparison tool) it is not matching on this wrapped error. Instead, it winds  up on this and gets treated as an error https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1978 . Then the error gets logged in our application.

I think this on line 1969 is a bug, do you agree ?

**Comment by cmwaters** [comment]
Yeah that seems correct to me, thanks. I will make the change. 

Let me know if there's any other logging anomalies you also think might need tweaking.

**Comment by alexanderbez** [comment]
Thanks for reporting this issue! Wish we had a linter for this :-/

**Comment by ValarDragon** [comment]
Glad this got fixed, was about to file an issue for it as well haha
