### ISSUE TITLE
augment scripts/dist_build.sh to allow only building specific arch/os

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#624]
Right now we always build all of them. Sometimes I just want to build for linux for dev purposes

**Comment by zramsay** [comment]
which 2-3 combinations from https://github.com/tendermint/tendermint/blob/master/scripts/dist_build.sh#L18-L19 are most prefered?

**Comment by melekes** [comment]
`go build ./cmd/tendermint`?

**Comment by zramsay** [comment]
i mean, which os/arch combination should be supported by this issue. Presumably a default linux and a default darwin?

**Comment by melekes** [comment]
I don't understand the purpose of this ticket at all

**Comment by ebuchman** [comment]
This came from needing to push custom builds for Jepsen. Only linux was needed. Maybe this is silly and we can just close it, but I was thinking it'd be nice to be able to specify that i only wanted a linux x86 build when calling this script, instead of building for all platforms

**Comment by melekes** [comment]
Ah, I see. No, it should be easy to implement. Just read `GOOS` and `GOARCH` env vars and if they are defined, use them

**Comment by melekes** [comment]
Looks like it's already implemented. You just need to provide `XC_ARCH` and `XC_OS`

```
XC_ARCH=amd64 XC_OS=linux bash scripts/dist_build.sh
```

**Comment by ebuchman** [comment]
Duh! Thansk Anton.
