### ISSUE TITLE
Bigchaindb tendermint initializing issue

### ISSUE THREAD

**Issue by rupam150** [tendermint/tendermint#6242]
Hi  i have created 4 node setup using bigchaindb and out of them 2 of them are running well and showing all the set of 4 validator , but of the rest two when i tried to start it always show TENDERMINT INITIALIZING in monit summary
I checked the tendermint out log of the not working nodes and it shows something like this
![tendermint out log of peer 4](https://user-images.githubusercontent.com/76766096/111304888-4cf31d80-867c-11eb-8614-d1df346b5cea.PNG)

And the rest which i think are working shows

![tendermint output log of peer 1](https://user-images.githubusercontent.com/76766096/111305020-7613ae00-867c-11eb-919a-88894e5ba346.PNG)

Any kind of help from your side will be highly aprreciated .
Thanx  in advance

**Comment by marbar3778** [comment]
What version of Tendermint are you using? 

You can try setting the nodes external address in config.toml to help with connecting

**Comment by rupam150** [comment]
@marbar3778  i have followed the steps of Simple deployment template given in Bigchaindb doc 
 
My Tendermint version  is - 0.31.5-d2eab536

and here is the snap of my persistent peers i added in config.toml 
![config toml](https://user-images.githubusercontent.com/76766096/111306820-b411d180-867e-11eb-8d91-90651133d05d.PNG)

**Comment by rupam150** [comment]
And here is my monit summary 
![monit summary](https://user-images.githubusercontent.com/76766096/111307339-4ca85180-867f-11eb-8398-fbed9cf23f45.PNG)

**Comment by marbar3778** [comment]
> My Tendermint version is - 0.31.5-d2eab536

This is an outdated version of Tendermint. I would recommend upgrading the version and trying again. 

It seems to be a configuration issue. Either your nodes are not exposed to the public internet or they are sedning incorrect dialing data. Try setting external addresses in your config.toml's to help with this.

**Comment by rupam150** [comment]
Hi @marbar3778  yes the one is outdated version of tendermint but i am using it for bigchaindb and only the given versions supports for bigchaindb 

![bigchaindb tendermint version](https://user-images.githubusercontent.com/76766096/111425815-b4ab7600-8719-11eb-815e-586481dc62dc.PNG)

Morever the i have set up the nodes in aws and i have reverse proxy the NGINX server so i think aws ports should have worked properly .

**Comment by marbar3778** [comment]
It could be the reverse proxy. When you try without the proxy does it work? This could be an issue in BigChainDb as well.

**Comment by tessr** [comment]
I'd recommend opening an issue with BigchainDB. That version of Tendermint is two years out of date.

**Comment by rupam150** [comment]
Hi @marbar3778 i tried without reverse proxy it's still the same .
but though it is initializing it showing all validators and server is also working well . 
May be some issue with monit as i am running tendermint using monit and it always monitors the status every n sec ( 1 sec in my case)

**Comment by rupam150** [comment]
Hi @tessr  What's the latest version of tendermint and does it configure with Bigchaindb2.2.2?

**Comment by marbar3778** [comment]
> Hi What's the latest version of tendermint and does it configure with Bigchaindb2.2.2?

We are unaware if newer versions of Tendermint work with bigchaindb, you could ask the maintainers. 

> i  have followed the steps of Simple deployment template given in Bigchaindb doc

If bigchainDB has a communication channel you could try asking there. We are not sure if the instructions are incorrect or your setup. In the pictures above according to monit Tendermint has started yet?

I will close this issue but feel free to comment on it, we will try to help out further.
