### ISSUE TITLE
User defined mempool support

### ISSUE THREAD

**Issue by gchaincl** [tendermint/tendermint#6243]
## Summary

Allow Tendermint's developer to inject a custom mempool implementation.

## Problem Definition

The current mempool is implemented as a FIFO queue and it does not support different sortings (like prioritization). Also the mempool is Tx agnostic, which means that if someone want's to sort the Txs based on a specific Tx field, they will need a user-defined implementation.

Tendermint supports injecting (and replacing) the Reactors vis [CustomReactors](https://github.com/tendermint/tendermint/blob/master/node/doc.go#L34) option parameter, but replacing the reactor won't effectively replace the mempool implementation (https://github.com/tendermint/tendermint/blob/master/node/node.go#L935)

## Proposal
The naive approach I can foresee, is to create a `NewNodeWithMempool(...)` that receives a [Mempool](https://github.com/tendermint/tendermint/blob/master/mempool/mempool.go#L16) implementation or a `NodeMempool` factory that creates a mempool reactor and implementation 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Thanks for opening this issue. I agree for the time being we should allow users to replace mempools until the refactor lands, but we want to avoid exposing too much to the developer. This can lead to many user errors and reduces the guarantees we can make on behalf of the software.


> Tendermint supports injecting (and replacing) the Reactors vis [CustomReactors](https://github.com/tendermint/tendermint/blob/master/node/doc.go#L34) option parameter, but replacing the reactor won't effectively replace the mempool implementation (https://github.com/tendermint/tendermint/blob/master/node/node.go#L935)

Have you tested replacing the mempool reactor which imports a different mempool? Would be good to first get a demo to see what is possible with the current offering before we investigate workarounds.

**Comment by gchaincl** [comment]
I'll be exploring that to see how can be useful for my use case and report the results and observations back.

**Comment by gchaincl** [comment]
@marbar3778 here's a small example that tries to exemplify the problem I'm describing: https://gist.github.com/gchaincl/c3c957c871685d08eda1a3b28af9a7d0

The code creates reactor that uses a new mempool instance, you'll see that since Tendermint's `NewNode` is creating its own Mempool instance, the one I create never gets called.

**Comment by marbar3778** [comment]
Hmm, okay. I think I know how we should change things, but there is another way you can define your own mempool. You could copy node.go and replace the mempool with your own. I will look into creating a short demo of my theory on how to change things.

**Comment by marbar3778** [comment]
This is what I quickly mocked up https://github.com/tendermint/tendermint/pull/6291/files. I need to test if it solves your issue and discuss with the team if this is worth doing. I think the best case for now is to replace `NewNode` with your own implementation of it that uses your mempool

**Comment by gchaincl** [comment]
Thanks for reviewing and taking the time to write a fix to my request. I'll follow your advice and go with a custom `NewNode` implementation that uses my Mempool for now!

**Comment by gchaincl** [comment]
@marbar3778 I was able to use a custom mempool by replacing the NewNode by my own implementation.
Closing this, thanks!

**Comment by marbar3778** [comment]
![](https://media1.giphy.com/media/5GoVLqeAOo6PK/giphy.gif)
