### ISSUE TITLE
light/rpc: adaptive provider in RPC client

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6249]
## Summary

Track light client primary changes in the RPC client

## Problem Definition

When we start a light client alongside a corresponding RPC client, the light client's primary is dynamic and can change over time while the provider that the RPC is connected with remains static. Imagine a case where the light client drops a primary because it no longer responds, the light client still works but now the RPC remains connected with a node that isn't responding.

## Proposal

A nice feature would be that the RPC client is also able to be dynamic with the provider that it is connected to.

A simple proposal would be that upon each RPC call the client checks if it needs to source information from a provider. If it does it calls `lightClient.Primary()`. It then checks the endpoint with the current one that it has. If it is different then it sets up a new connection with this new provider, replacing the existing one. If it's the same then it continues with the call.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tessr** [comment]
This seems like a good idea to me 👍🏼
