### ISSUE TITLE
config: revision to accommodate node modes

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6255]
## Summary

In light of making clearer and more consistent definitions of nodes and their roles in a network, I would like to propose
a series of changes to the config system.

Reference Comment: https://github.com/tendermint/tendermint/pull/6241#issuecomment-801098665

## Problem Definition

At a glance, the current config system involves sharing a single config file across all types of tendermint nodes whether running a validator node or a seed node. This means a large config file where many parameters are entirely redundant to the end user. I think this a sign or poor UX and we should aim to keep the complexity of parsing different configs on the Tendermint side and providing a clean and understandable config file with reasonable defaults on the users side.

## Proposal

I will try break down the proposal into a series of smaller enumerable steps that in most cases can be individually evaluated on:

1. Have a `BaseConfig` that is common to all node types. This already partly exists but could be adjusted to remove some node specific items such as the `PrivValidator....` params. The essential component to this is the `mode` parameter which indicates whether the config should be parsed as a `Full`, `Validator`, `Seed`, or `Light` node. When the TOML file is parsed we use the mode parameter to indicate how the rest of the config should be read.
2. Introduce a `LightConfig`. Currently none exists although there are several adjustable parameters which are usually set via flags. This can be cumbersome when you need to continually type them out. It also aligns itself with the convention of the other nodes which have a config file. A conceivable example of `LightConfig` would be as follows:
```go
type LightConfig struct {
     Primary string
     Witnesses []string
     VerificationMode string // "skipping" | "sequential"
     TrustedHeight int
     TrustedHash string
     TrustedPeriod string
     MaxClockDrift int
     PruningSize int
     TrustLevel string // parsed into a fraction
}
```

As the light node runs an RPC, serving and verifying requests, we would expect a `LightNode` to require a `BaseConfig`, `LightConfig` and `RPCConfig`

3. Nodes are linked with the configs based on the services they provide as follows:
- Validator -> `BaseConfig`, `ValidatorConfig` (see 4), `RPCConfig`, `P2PConfig`, `MempoolConfig`,  `FastSyncConfig`, `StateSyncConfig`, `ConsensusConfig`, `TxIndexConfig`, `InstrumentationConfig`
- Full -> `BaseConfig`, `RPCConfig`, `P2PConfig`, `MempoolConfig`, `FastSyncConfig`,  `StateSyncConfig`, `ConsensusConfig`, `TxIndexConfig`, `InstrumentationConfig`
- Seed -> `BaseConfig`, `P2PConfig`

4. Introduce a config specific to validators: 
```go
type ValidatorConfig struct { // could also be called PrivValidatorConfig
	PrivValidatorKey string `mapstructure:"priv-validator-key-file"`
	PrivValidatorState string `mapstructure:"priv-validator-state-file"`
	PrivValidatorListenAddr string `mapstructure:"priv-validator-laddr"`
	PrivValidatorClientCertificate string `mapstructure:"priv-validator-client-certificate-file"`
	PrivValidatorClientKey string `mapstructure:"priv-validator-client-key-file"`
	PrivValidatorRootCA string `mapstructure:"priv-validator-root-ca-file"`
}
```
5. Update `ConsensusConfig` by removing redundant parameters. See https://github.com/tendermint/tendermint/issues/2920#issuecomment-454062585
6. Move `FastSyncMode` out from `BaseConfig` and into `FastSyncConfig` by just having an `enable` bool parameter. This aligns with the convention used with `StateSync`

I would love to hear other people's suggestion to how we can make the config file more intuitive and user friendly. Not all the ideas I've suggested here may be the best ones going forward.

As a closing note, I would like to add that as much as I like clean and concise configs I also don't want to cause any strain for node operators upgrading, thus if we want to make breaking changes to the config, then I would like to keep the legacy config in place throughout 0.35 and add a few lines of code that will automatically migrate old configs to the new format. 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
It seems these concerns are certainly warranted. I would like to see feedback from the user surveys with regards to existing configuration before deciding on a concrete proposal.

I also think the proposal would be a bit easier to grok and understand if a clear structure was laid out.

e.g.
```go
type Config struct {
  BaseConfig
  FullNodeConfig
  SeedNodeConfig
  ValidatorNodeConfig
  LightClientNodeConfig
  // ...
}
```

**Comment by cmwaters** [comment]
> I would like to see feedback from the user surveys with regards to existing configuration before deciding on a concrete proposal

Yup this makes sense.

I wasn't thinking of amassing everything into a single config rather four configs like so:
```go 
type FullNodeConfig struct {
    BaseConfig
    RPCConfig
    P2PConfig
    MempoolConfig
    FastSyncConfig
    StateSyncConfig
    ConsensusConfig
    TxIndexConfig
    InstrumentationConfig
}

type ValidatorNode struct {
    BaseConfig
    ValidatorConfig
    RPCConfig
    P2PConfig
    MempoolConfig
    FastSyncConfig
    StateSyncConfig
    ConsensusConfig
    TxIndexConfig
    InstrumentationConfig
}

type SeedNodeConfig struct {
    BaseConfig
    P2PConfig 
}

type LightNodeConfig struct {
    BaseConfig
    LightConfig
    RPCConfig
}
```

**Comment by alexanderbez** [comment]
Yes, but there is still a single configuration file, right?

**Comment by cmwaters** [comment]
We can, but I don't see why we need one. We just need a function that can parse the toml file and run the correct node

**Comment by cmwaters** [comment]
Can you explain why you think it would be a regression. I'm not opposed to having it altogether as a single struct, I just don't think that the toml file should contain anything that isn't relevant to the node that is being run i.e. there shouldn't be any consensus parameters for a seed node config file. When it comes to running a node in process, I think you should also specify which node you are running and provide the config that applies just to that node.

**Comment by alexanderbez** [comment]
I can tell you as an operator, the less files I have to worry about the better. I don't want to constantly be asking, "what mode am I in?" in conjunction with "what config files exist?" and "what config files should exist"? I think it'll be a UX nightmare. I could be wrong. Ask operators and validators what they think. Personally, I think having a single config file makes sense. They can always omit any configurations that are not relevant to their mode.

**Comment by cmwaters** [comment]
But on the operator side there will just be a single config file. If you are running a full node there will be just one `config.toml` that gets parsed into a `FullNodeConfig` and then will be run as a full node. If you are running a validator there will just be one `config.toml` file which will have a few other parameters and upon start up will run as a validator.

**Comment by alexanderbez** [comment]
Yes, that what is what I was suggesting and hence my question here https://github.com/tendermint/tendermint/issues/6255#issuecomment-804046856. I was confused when you stated, `We can, but I don't see why we need one.`.

**Comment by cmwaters** [comment]
Right, sorry for the confusion, yes operators will have a single `config.toml`.

**Comment by alexanderbez** [comment]
Sweet! Then yeah, this has an ACK from me, great idea 👍

**Comment by marbar3778** [comment]
Love the approach, the issue that may arise from this is node operators needing to regenerate their configs in order to switch the full node to a validator node. This would be something to consider when doing the implementation but generally for the change.

**Comment by cmwaters** [comment]
Yeah I also had that concern although I think we can easily tackle it in the implementation with some sort of upgrade function that can be triggered when someone runs a config with `mode: full` but with the flag `--mode validator` or something to that affect

**Comment by alexanderbez** [comment]
I can't speak for everyone, but as an operator, this is what I would do. I'd have `config.toml` copies of all the modes i'm interested in with a main `config.toml` that acts as my current configuration. If I ever want to switch modes, and thus configuration values, instead of manually tweaking the file, I just replace them.

i.e.
```
-- config.toml (current; full-node)
-- config.val.toml
-- config.seed.toml
```

If I want to go from full-node to validation mode, I just do `cp config.toml config.full.toml; cp config.val.toml config.toml`.

**Comment by tessr** [comment]
Should we try to get this in for 0.35?

**Comment by cmwaters** [comment]
I would love to. I think the only thing looming over doing this now is if we wanted to wait until we got some feedback from the user survey

**Comment by tychoish** [comment]
It's my sense that the main difference is that we want to:

- generate default configuration files that are appropriate to the mode and don't contain extraneous configuration options.
- validate the configuration conditionally based on the mode value. 

I'm not sure, on an internal basis, that we to have many re-compositions of the same config sub sections might actually be more difficult to maintain (particularly given impending API stability, but maybe it doesn't matter.
