### ISSUE TITLE
jsonrpc: parsedURL parses the port and path incorrectly for path routed domains

### ISSUE THREAD

**Issue by fdymylja** [tendermint/tendermint#6260]
**Tendermint version**: master

**What happened**: while using the jsonrpc client on load balancers which route to endpoints via path (ex: host.com:443/tmrpc) the address of the client is parsed in a not valid format.

**How to reproduce it**:

```golang
func TestEndpoint(t *testing.T) {
	x, err := rpchttp.New("https://example.com:443/rpc", "")
	if err != nil {
		t.Fatal(err)
	}
	_, err = x.Status(context.TODO())
	if err != nil {
		t.Fatal(err)
	}
}
```

This happens because the address is set [here](https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/http_json_client.go#L139) using the [GetTrimmedHostWithPath](https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/http_json_client.go#L69
) function which ends up creating an URI with an invalid port (ex: `:443.rpc`).

I could provide a fast fix, but I'm not sure why the '/' to '.' replacement is done.

**Comment by alexanderbez** [comment]
Thanks for creating the issue @fdymylja! What API does this internally call and what is the proposed fix?

**Comment by fdymylja** [comment]
@alexanderbez the struct `parsedURL` has a method `GetTrimmedHostWithPath` https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/http_json_client.go#L69

This method replaces any `/` with a `.`. This leads to URL having a path to be malformed. Ex: `example.com/path` would end up being `example.com.path` which leads to an invalid URL. 

A solution could be to ignore the first slash, but it wouldn't be a good fix, because you could a proxy which routes requests to TM specific endpoints in this way `example.com/tendermint/rpc`, `example.com/tendermint/p2p` etc. So it wouldn't be a proper fix for this issue.

On a secondary note, I'm not sure why in tendermint we replace slashes with periods.

**Comment by alexanderbez** [comment]
> On a secondary note, I'm not sure why in tendermint we replace slashes with periods.

Yeah, this makes zero sense to me atm. I have no idea why we do this. We just need to ensure the supplied value is a valid URL, i.e. `url.Parse(...)`. I think using that should be ok 👍

**Comment by cmwaters** [comment]
Nope and I can't find anything in the code that may hint as to why we do this change

**Comment by fdymylja** [comment]
Based on the usage lookup, I'm not seeing any scenario in which if the replacement happens the endpoint will be valid.

If you give me the OK, I will open a PR with the fix

**Comment by alexanderbez** [comment]
Yes please :)

**Comment by fdymylja** [comment]
Ok, so after some testing, I realized the root of the issue. The reality is that there's an incompatibility between unix sockets and how URL formats them. TBH I'm not sure there's even a clear approach on how to parse unix socket domains via URL. 

For example if my unix socket 'endpoint' is /tmp/socket, the URL library has no way of recognizing what is the actual endpoint and what is the actual path for the request. Also which is the dial function? We could make assumptions and say that if the remote address is unix://something, then what is after `unix://` is the actual domain. 

But this would exclude the possibility in which a unix socket can proxy to other endpoints via path.

It's difficult to offer a generalized approach, as the one we have now (which does not work with path routed domains), taking into consideration that we might deal with unix sockets.

**Comment by alexanderbez** [comment]
I'm not very familiar with unix sockets and their formats tbh. I would say if we see `unix://`, then everything after is the endpoint? Otherwise, use the `url` package to parse it.
