### ISSUE TITLE
not caught up yet  

### ISSUE THREAD

**Issue by ws160920096** [tendermint/tendermint#6267]
![图片](https://user-images.githubusercontent.com/32269053/112285709-915a6b00-8cc5-11eb-8737-b44f9751154f.png)

I set it to generate empty blocks by default, but it doesn't
And use broadcast_ tx_ Commit error:Internal error: Timed out waiting for tx to be included in a block

**Comment by marbar3778** [comment]
If you are using master, you need to define a mode. In this case `--mode validator` for your node. Also, please don't use master but a release. We do not make guarantees master will not break the next time you try to use it.

**Comment by ws160920096** [comment]
thank you
