### ISSUE TITLE
Shorten the add-precommit message

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#6269]
## Summary

Currently tendermint consensus (very helpfully) logs whenever it receives a precommit. However the precommit messages at the moment are way too verbose imo, and logs would benefit significantly if these were made more concise.
Here is a message taken from our validator: (I've inserted newlines so it be seen more easily)
```
<Time> INF added vote to precommit module=consensus precommits="VoteSet{H:225794 R:0 
T:SIGNED_MSG_TYPE_PRECOMMIT 
+2/3:A53377E66BF3781B5E029DAEF6B3452A9DF38B482BB97D4A8414A49B48B53EB6:1:B43AC002F7F6(0.7551514243122066) 
BA{64:xxxxxxxxxxxxxxxxxxxx__xxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_x_x_xx} map[]}" 
vote={"block_id":{"hash":"A53377E66BF3781B5E029DAEF6B3452A9DF38B482BB97D4A8414A49B48B53EB6",
"parts":{"hash":"B43AC002F7F64D2CCB107A282ED483EFE1610BCCA22A57FC0CDA339EB552BFAA","total":1}},
"height":225794,"round":0,
"signature":"BdSx1ADuNMBFcPdR5Ga4uLXIb6x5Qg/0j17TGWw7Fj/Ye3Jm+RfSaSxliDXXRIOH5Gx5GKcceI0aGXJM558/Ag==",
"timestamp":"2021-03-24T19:33:48.189145073Z",
"type":2,"validator_address":"B1852D17FA66B5382A8F770725CC5B228B357750","validator_index":1}
```

I suggest we change this something along the following, instead of printing out a struct directly:

```
<Time> INF added vote to precommit module=consensus vote data="H:225794, R:0, block_id= 
"A53377E66BF3781B5E029DAEF6B3452A9DF38B482BB97D4A8414A49B48B53EB6" 
validator="B1852D17FA66B5382A8F770725CC5B228B357750" vote_timestamp="{UTC timestamp}"", overall_stats=" 
fraction voted = (0.7551514243122066)}" BA{64:xxxxxxxxxxxxxxxxxxxx__xxx_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx_x_x_xx}"
```

This would save log space and generally improve readability. I'm also not even sure that keeping the block_id in the log is that helpful, since there should be a log entry containing the block ID for the proposal. I think displaying the block ID is only helpful for a received precommit on a block you didn't vote for. 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@tychoish wanna take a crack at this?
