### ISSUE TITLE
config improvements

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#628]
- [x] we should return an error if a config element is unknown (rather than ignore it)
- [x] add some new elements to the p2p config (#636):
  - max_msg_packet_payload_size
  - send_rate
  - recv_rate
- [ ] we should add some function, eg. `config.Parse()` to check the validity of all arguments. Ie that ints are positive, that strings are from the allowed set, etc.
- [x] separate config files and data by creating 2 subfolders (config, data) (#556, #709)
- [x] config docs (#705, #733)

**Comment by odeke-em** [comment]
Some questions:
a) By `we should return an error if a config element is unknown (rather than ignore it)` do you mean while unmarshaling/parsing config? While doing the `mapstructure` --> CLI args parsing? Or do you mean if a field is set and we can't find it?
b) 
```
 add some new elements to the p2p config:
```

- max_msg_packet_payload_size: int?
- send_rate: float?
- recv_rate: float?

**Comment by ebuchman** [comment]
a) dont care too much, as long as we catch it before tendermint starts and provide a useful error to the user

b)

send_rate: https://github.com/tendermint/tendermint/blob/master/p2p/connection.go#L31
recv_rate: https://github.com/tendermint/tendermint/blob/master/p2p/connection.go#L34
payload_size: https://github.com/tendermint/tendermint/blob/master/p2p/connection.go#L678

**Comment by odeke-em** [comment]
For the sake of clarity, I might be repeating myself but today on the Thursday company call, a new member had trouble using
```shell
tendermint --home ~/.tendermint node
```
where `~/.tendermint` was non-existent and their tendermint had never been initialized. We should have thrown an error and told them that `~/.tendermint` doesn't exist.

**Comment by odeke-em** [comment]
Another requirement raised offline by @ebuchman. Let's make sure that:
- priv_validator.json
- genesis.json
files are all valid
after we've added the `--verify` flag

**Comment by ebuchman** [comment]
punt to next release for more code review

**Comment by ebuchman** [comment]
Closing this since most PRs are merged, and only one is left open that might need some cleanup
