### ISSUE TITLE
Custom Reactors can't communicate due to unknown Channels

### ISSUE THREAD

**Issue by gchaincl** [tendermint/tendermint#6289]
**Tendermint version**: d988cd61018a7ae3884762d4e5188df1c67833c1

**What happened**:
When setting a custom reactor on `NewNode` using `CustomReactors` options with a custom name (not `MEMPOOL` ... `STATESYNC`), they are not able to communicate due to a missing channel error:

```
D[2021-03-29|11:51:09.606] Unknown channel for peer                     channel=128 channels=40202122233038606100
```

**What you expected to happen**:
I'd expect the reactor to be able to send and receive messages between peers.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Here's my reactor code:
```go
const (
	Channel = byte(0x80)
)

type Reactor struct {
	p2p.BaseReactor
}

func NewReactor() *Reactor {
	r := &Reactor{}
	r.BaseReactor = *p2p.NewBaseReactor("MyReactor", r)
	return r
}

func (r *Reactor) GetChannels() []*conn.ChannelDescriptor {
	return []*conn.ChannelDescriptor{
		{ID: Channel, Priority: 2},
	}
}

func (r *Reactor) InitPeer(peer p2p.Peer) p2p.Peer {
	peer.SetLogger(
		log.NewTMLogger(os.Stdout),
	)
	return peer
}

func (r *Reactor) AddPeer(peer p2p.Peer) {
	peer.Send(Channel, []byte("hello"))
}

func (r *Reactor) Receive(chID byte, peer p2p.Peer, msgBytes []byte) {
	fmt.Printf("msgBytes = %+v\n", msgBytes)
}
```

**Comment by gchaincl** [comment]
My understanding is that the switch's nodeInfo does not get updated after the invocation of `CustomReactors`. And since the channels are defined in the nodeInfo, the peers won't be created with an updated version of the channels.

**Comment by cmwaters** [comment]
I think we can close this now (ref: https://github.com/tendermint/tendermint/pull/6339)
