### ISSUE TITLE
rpc: auto generate the slate docs

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#629]
Would be amazing to have a script that tested each function and populated the doc.

**Comment by zramsay** [comment]
@melekes can you host them on heroku like mentioned and we can update the link here on RTD

**Comment by melekes** [comment]
https://glacial-waters-46750.herokuapp.com/#block

**Comment by melekes** [comment]
now I am thinking maybe we should move API docs to RTD also. What do you think?

**Comment by zramsay** [comment]
yes. although maybe the `.rst` format is problematic

**Comment by melekes** [comment]
Closing in favor of #691 ?
