### ISSUE TITLE
tendermint node error 

### ISSUE THREAD

**Issue by rupam150** [tendermint/tendermint#6301]
Hi i have created a 4 node setup in bigchaindb using tendermint 
But when i tried to execute tendermint node command in the 4 nodes it is showing some error and blocks are not generated .

Specifications - 
Operating sysytem - UBUNTU 
Bigchaindb version - 2.2.2
Tendermint versio n - 0.31.5-d2eab536 ( its a earlier version but in bigchiandb doc it is the supported one ) 

Here i am attaching the snippet of the four nodes ----

1. While running tendermint node in node 1 
![tendermint node error node 1](https://user-images.githubusercontent.com/76766096/113104967-b8152600-921e-11eb-817c-16ef812a6e89.png)

2. While running tendermint node in node 2 
![tendermint node error node 2](https://user-images.githubusercontent.com/76766096/113105073-d11dd700-921e-11eb-817c-c2a08e29a3e7.PNG)

3. While running tendermint node in node 3 
![tendermint node eroor node 3](https://user-images.githubusercontent.com/76766096/113105115-dbd86c00-921e-11eb-8008-c03abeea6981.PNG)

4. While running tendermint node in node 4 
![tendermint node error](https://user-images.githubusercontent.com/76766096/113105376-24902500-921f-11eb-896a-317bd8b4bb35.PNG)

please help stuck from weeks , 
Thank you !

**Comment by marbar3778** [comment]
Hey, thanks for opening an issue. The issue you are seeing is due to nondeterminism in the application. Unfortunately we are not aware how bigchaindb works. I would recommend asking the bigchaindb team for more info.
