### ISSUE TITLE
indexer: only provide streaming of events

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#6303]
## Summary

A tendermint node is tasked with many things that are consensus critical, storing indexed events is not a consensus critical item, yet we still store them. Our indexing service is used in conjunction with a **custom** query engine. This query engine is not feature rich and leads users to write simple queries in an attempt to describe a complex relationship between events. 

## Problem Definition

Tendermint handles consensus critical processes, we should not rely on it to store indexed events and provide a service to users in which they can query this data. 

## Proposal

This proposal is to remove the kv indexer, provide a streaming interface similar to [ADR-38 from the SDK](https://github.com/cosmos/cosmos-sdk/blob/master/docs/architecture/adr-038-state-listening.md). We would provide a tool that listens on the other side in order to write data to Postgres or the file system, similar to what is outlined in the ADR. 

Things to keep in mind.

- Should we provide guarantee that events will be stored for a couple blocks in the case of the listener stopping? 

Reference:

- https://github.com/tendermint/tendermint/issues/1161
- https://github.com/tendermint/tendermint/issues/5963
- https://github.com/tendermint/tendermint/issues/5206
- https://github.com/tendermint/tendermint/issues/5978

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I am totally onboard with this. The SDK ADR-038 is a good basis for how this could (and should?) be done in Tendermint, arguably less complex and with less LOC too! Implementing this should be pretty straightforward while also providing a much larger degree of flexibility and reliability in the event system.

In addition, I think we should provide a few `WriteListener` implementations out of the box. Namely, we should provide a `KV` and `SQL` implementations of `WriteListener`, and maybe a `Kafka` one if we're feelin' frisky. The `KV` `WriteListener` should be the default one so we maintain UX parity with current event system usage.

We also get the added benefit of having a completely flexible query system that is offloaded to the underlying event source, e.g. postgres.

**Comment by cmwaters** [comment]
Thumbs up from me as well on this 👍. Would be great to leverage what many good minds have already worked hard on getting right.

**Comment by tomtau** [comment]
related issue: https://github.com/tendermint/tendermint/issues/1161

**Comment by marbar3778** [comment]
> The `KV` `WriteListener` should be the default one so we maintain UX parity with current event system usage.

Do you see this using the same underlying query engine?

**Comment by ethanfrey** [comment]
Yes, I think a generic write service (a la ADR-038) and then a few pluggable backends make sense. I second @tomtau and would love a dump-to-postgres option out of the box. (I would prefer to go for real, scalable services if we make this pluggable, not just swap leveldb for sqlite).

This would be responsible for putting the data into these backends, right? Are the indexers expected to return the same data to tx_search as currently done (this would be a difference to ADR-038 which is just about feeding data to an external store, with no expectations of what it would provide).

I would be very interested in an external indexer that not only implements the `tx_search` interface more efficiently, but also allows us to build more advances APIs on it (like GraphQL). I know you had some experience building out https://github.com/fissionlabsio/juno and it would be awesome if that just plugged in here with the same interface.

**Comment by ethanfrey** [comment]
>  The KV WriteListener should be the default one so we maintain UX parity with current event system usage.

This provides a nice backwards-compatibility wrapper.
Is there the idea of allowing multiple data sinks? (even if only one is used by `tx_search`)

**Comment by marbar3778** [comment]
> would love a dump-to-postgres option out of the box. (I would prefer to go for real, scalable services if we make this pluggable, not just swap leveldb for sqlite).

100% this is the goal. We don't want to bloat tendermint with sqllite and do some magic when this can be done by postgres. 

> This would be responsible for putting the data into these backends, right? Are the indexers expected to return the same data to tx_search as currently done (this would be a difference to ADR-038 which is just about feeding data to an external store, with no expectations of what it would provide).

I'm not sure if this would be ideal. In my eyes the current kv indexer stays the same and supports tx_search, if a different backend is used like postgres, we return tx_search with "this is not supported on this node due to a different backend." As for doing graphql, this would be out of scope, but can easily be accomplished by using hasura on top of postgres. I can write a docker compose file for this as well, when the time comes.

**Comment by ethanfrey** [comment]
> I'm not sure if this would be ideal. In my eyes the current kv indexer stays the same and supports tx_search, if a different backend is used like postgres, we return tx_search with "this is not supported on this node due to a different backend" or something similar.

That sounds reasonable. Can a node support multiple indexers? eg. kv to handle tx_search and postgres for a more powerful API?

I would also love to see a standardized API coalesce around the postgres listener. Maybe like Juno++. But that is another issue and the next step.

**Comment by iramiller** [comment]
> maybe a Kafka one if we're feelin' frisky.

We use Kafka extensively within our environments.  This is something we would be interested in contributing towards if you are looking for assistance.  

------

The event system and data indexing overall is something we have struggled to work around since pretty much the inception of our work on the Cosmos SDK platform.  I find it pretty telling that when we introduce our application development teams to our blockchain internally the first complaint they all have after establishing connectivity are the issues surrounding data access and indexing.

1. Event [data] delivery -- an easy to integrate connection point that will push data as it becomes available to registered endpoints.  Ideally as an API that allows independent implementation specific transport layers to be integrated on top easily (think Kafka, WSS, direct database connections)
2. Data structure and relationships.  Module developers will have their own ideas for how the state and msg/query traffic for their modules interplay and what types of information should be linked.  Similarly the core SDK can go a long way towards helping external indexes form high quality relational structures if it also makes these relations available.
3. Persistence, scale, availability, and retention of indexed data.

In my mind the right balance for an SDK solution should be heavy on the first point, a minimum viable 'best practice' solution for the second that covers core modules, and a small reference implementation for the third.  I would hate to see the SDK stray too far from 'a core set of tools' towards 'a middleware platform'.  Drawing a small tight circle around the state machine application which contains the smaller circle of tendermint consensus should be a guiding philosophy here.

**Comment by alexanderbez** [comment]
> We use Kafka extensively within our environments. This is something we would be interested in contributing towards if you are looking for assistance.

Yes, absolutely! Just implement a sink that fulfills the interface defined in [ADR-065](https://github.com/tendermint/tendermint/pull/6307).

> The event system and data indexing overall is something we have struggled to work around since pretty much the inception of our work on the Cosmos SDK platform. I find it pretty telling that when we introduce our application development teams to our blockchain internally the first complaint they all have after establishing connectivity are the issues surrounding data access and indexing.

Well what specifically are the core or most common issues at a high-level and does [ADR-065](https://github.com/tendermint/tendermint/pull/6307) address them?

**Comment by iramiller** [comment]
Generally the issues are, ‘what are the things I can search on’, ‘why do some queries that seem simple hang forever’ (typically blockheight/data volume related), and the last major area being query formatting and invocation. 

The expectations are usually level set based on experience using RDBMS and as that isn’t what the query system is based on there is bound to be some disappointment.  

A simple collection of the various block event fields being indexed would be a huge win... both for those using the system and the devops crew doing the configuration of which fields should be indexed.

**Comment by alexanderbez** [comment]
Thanks for outlining that @iramiller, very helpful :)

> what are the things I can search on

Up until recently, it was just transactions. The RPC call `tx_search?query=_&prove=_&page=_&per_page=_&order_by=_` should make that pretty evident, no?

Or are you referring to _what_ you can search by? If so, that is entirely an _application-specific_ question and not related to Tendermint. The Cosmos SDK has per-module docs on all the events that are emitted for all message types.

> why do some queries that seem simple hang forever

Great question and somewhat of a loaded one too. As far as I understand it, it's mainly a culprit of two things:

1. The fundamental design of Tendermint's RPC & ABCI single-threaded inner workings and relationship.
2. The application's data storage and structures, i.e. the IAVL stores.

From what I've gathered, it's really (2) that is the true bottleneck, so somewhat outside the scope of Tendermint again.

> The expectations are usually level set based on experience using RDBMS and as that isn’t what the query system is based on there is bound to be some disappointment.

Totally makes sense! Tendermint has supported tx event indexing and now more recently block event indexing too, however, via a proprietary mechanism. ADR-065 will address this concern I hope.

> A simple collection of the various block event fields being indexed would be a huge win... both for those using the system and the devops crew doing the configuration of which fields should be indexed.

Totally, but you won't ever find these in Tendermint. Again, they're application-specific and are also outlined in the Cosmos SDK if that's what you're using :)

e.g. of events emitted during blocks and transactions => https://github.com/cosmos/cosmos-sdk/blob/master/x/gov/spec/04_events.md

**Comment by iramiller** [comment]
The documentation of a module isn't as helpful if the instance you are connecting to has a custom filter on which events it has indexed.

**Comment by alexanderbez** [comment]
Correct, and that is currently not exposed. However, if you control the instances/nodes, then you should know.

**Comment by marbar3778** [comment]
Going to close this, @iramiller would you like to open an issue for kafka?
