### ISSUE TITLE
docs: ABCI sections are out of order

### ISSUE THREAD

**Issue by hdevalence** [tendermint/tendermint#6318]
This is a really small issue somewhere in the rendering pipeline for https://docs.tendermint.com/master/spec/abci/

<img width="655" alt="Screen Shot 2021-04-05 at 9 23 23 AM" src="https://user-images.githubusercontent.com/44879/113597556-bc5f8b80-95f0-11eb-9ed6-e208fa316cce.png">

The section headers in the table of contents are out of order with the intended reading order.

**Comment by marbar3778** [comment]
Was fixed here https://github.com/tendermint/spec/pull/282.
