### ISSUE TITLE
Fetch transaction by hash from the blockstore

### ISSUE THREAD

**Issue by p4u** [tendermint/tendermint#6325]
## Summary

Export a method for fetching a specific transaction from the blockstore. 

We could use `BlockStore().LoadBlock(height)` and then iterate until the specific transaction is found but that's ugly and slow.

## Problem Definition

Instead of duplicating the transaction information in the application layer state, use the information already stored by Tendermint.

So in our use-case we are storing votes. Currently votes are saved into our IAVL database. But at the same time they are also saved by Tendermint on the blockstore and/or tx_index database. We only need to fetch a vote payload in the moment of the tally or when a user request it through our REST API. If we were able to fetch the vote payload from Tendermint, we would only need to save a reference to the vote `hash(payload)` in our state database which would reduce drastically the amount of information stored on the local storage of the node.

## Proposal

`txIndexer` on node.go might be exported

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by p4u** [comment]
@NateWilliams2 please feel free to add more information to this issue

**Comment by marbar3778** [comment]
I think this makes sense. Its a small change and solves the use case. Does anyone have any objections? 

cc @cmwaters @alexanderbez

**Comment by p4u** [comment]
You could send the PR if you agree on that solution.

**Comment by cmwaters** [comment]
Would this conflict at all with our notion of internalising a lot of the API's? If not, then I'm happy with making such a change.

@p4u, how do you generally find using TM nodes programatically? Are there any other pain points you would like us to look at :)

**Comment by NateWilliams2** [comment]
We may not end up using the txIndexer at all, but in any case here's a PR that goes along with this request.
https://github.com/tendermint/tendermint/pull/6327

**Comment by p4u** [comment]
I regret of the tx_indexer proposed solution as @NateWilliams2 states. After talking with Marko, I think in our case it makes more sense to disable the tx_indexer (we don't need it). In any case the PR from Nate would make sense (we won't use it but that's something someone else might use it).

Our best shot would be to extend the tendermint blockStore in order to be able to do something like `BlockStore.LoadTxFromStore(txHash)`

That would require to save on the tendermint blockstore a relation between txHash => (blockHeight, txIndex). So the transaction can be easily recovered by doing something like `Block[height].Tx[txIndex]`.

We might send a PR extending the current blockStore implementation to support that. Of course that could be a feature disabled by default because only those working at low level (as we do) would use it.

Do this make sense to you?

**Comment by p4u** [comment]
> Would this conflict at all with our notion of internalising a lot of the API's? If not, then I'm happy with making such a change.
> 
> @p4u, how do you generally find using TM nodes programatically? Are there any other pain points you would like us to look at :)

In one word: Mempool

I find the current implementation quite messy. I know a refactor is pending and I'm pretty sure Tendermint devs will do a great job. I just have a few things I'd love to have on the new implementation:

1. Do not use recheck by default, that's safe but it drops the performance
2. Allow async mempool (tx could be checked by the mempool in parallel)
3. Bring the p2p information to the Application layer (so we can play with it, i.e creating a cluster of trusted p2p nodes in order to perform a soft-check of a transaction)
4. Use libp2p (I know that's probably too much)

**Comment by p4u** [comment]
Another solution for us which is probably less harmful for Tendermint (if you don't want to add this extra index database on the blockstore) is to add the TX index (integer position of the transaction inside the `Txs[]` array) on the `abcitypes.RequestDeliverTx` data structure that is passed to `BaseApplication.DeliverTx()`. This way we can keep the relation in the application side and access directly to the transaction by calling `BlockStore().LoadTransactionByHeight(height).Txs[position]`

**Comment by cmwaters** [comment]
> add the TX index (integer position of the transaction inside the Txs[] array) on the abcitypes.RequestDeliverTx data structure

Couldn't you deduce this by keeping track of how many `RequestDeliverTx`'s there has been since the `RequestBeginBlock`. I believe adding such a field to an ABCI request would constitute a breaking change, which is something we may want to avoid in the upcoming release and thus may not be possible until 1.0.

**Comment by cmwaters** [comment]
> In one word: Mempool

I might have been able to guess that 😄. Yes we are looking to refactor it in the near future (primarily to enable prioritisation).

> 1. Do not use recheck by default, that's safe but it drops the performance

I think it's okay to be safety first and performant second, especially as disabling the recheck is just a small config change.

> 2. Allow async mempool (tx could be checked by the mempool in parallel)

For tx's that are mutually independent or not dependent on current state, I think this makes sense. Definitely would be good to explore this option

> 3. Bring the p2p information to the Application layer (so we can play with it, i.e creating a cluster of trusted p2p nodes in order to perform a soft-check of a transaction)

Can you explain this a little more? 

> Use libp2p (I know that's probably too much)

We're currently just in phase one of a p2p refactor but I believe in phase 3 we will look to consider adopting libp2p 
(see this [ADR](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-061-p2p-refactor-scope.md) for more context)

**Comment by p4u** [comment]
If the order of transactions is always serial and deterministic, we can do that, yes. So I understand that is the best and quick solution for now. Shall we discard Nate's PR then?

For future breaking changes I'd propose to send as many information as possible to the Application callbacks, such as the txIndex and the p2p information. Adding pointers to abciTypes.Request... is cheap and brings flexibility to the application layer.

8 d’abr. 2021 ha escrit:
>> add the TX index (integer position of the transaction inside the
>Txs[] array) on the abcitypes.RequestDeliverTx data structure
>
>Couldn't you deduce this by keeping track of how many
>`RequestDeliverTx`'s there has been since the `RequestBeginBlock`. I
>believe adding such a field to an ABCI request would constitute a
>breaking change, which is something we may want to avoid in the
>upcoming release and thus may not be possible until 1.0. 

-- 
S’ha enviat des del meu telèfon Android amb <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a>. Si us plau, excusa la meva brevetat.

**Comment by cmwaters** [comment]
>  Shall we discard Nate's PR then?

I think so. I just had a look over it now. My feeling is that the use case for searching for tx's either via a query string or directly via the hash should be sufficiently covered by the tx indexer. We are even in the process of adding greater customizability on that front (see https://github.com/tendermint/tendermint/pull/6307). If a user wants to use the blockstore as the source of retrieving txs then I would recommend they set up their own secondary index which they can use to store the height and the index.

**Comment by cmwaters** [comment]
I'm closing this issue now because I believe it has been resolved. If there's something left outstanding that I've missed then let me know and we can open this issue up again.
