### ISSUE TITLE
tendermint testnet 

### ISSUE THREAD

**Issue by rupam150** [tendermint/tendermint#6349]
Hi i have setup 4 nodes using tendermint testnet command for my blockchain project  , and nodes are running well with it , but if i want to setup  5 or more  nodes using tendemint testnet command what should i do ??

**Comment by cmwaters** [comment]
Hey @rupam150,

For simply initialising multiple nodes you can run:

```
tendermint testnet --v 5 --o ./output --populate-persistent-peers --starting-ip-address 192.168.10.2
```
where the 5 here indicates to create 5 validators.

If you want better ease of use with setting up and running them, I would suggest using docker instances. You can find documentation for this [here](https://docs.tendermint.com/master/networks/docker-compose.html)

**Comment by rupam150** [comment]
Hey @cmwaters  thank you for your reply , just have one query if can i change the starting-ip-adress 192.168.10.2 with my own local ip adresses if i have already setup 5 nodes in my local system.

**Comment by cmwaters** [comment]
If you've already set the nodes up then I would just change the `config.toml` files for each of them by replacing the `ListenAddrs` in the P2P and RPC section with your IP address/es. (If it's all on the same address then just increment the ports)

**Comment by rupam150** [comment]
okkay thanx @cmwaters
