### ISSUE TITLE
Consider option to keep txs which failed DeliverTx in the mempool

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#635]
Eg. in ethermint txs could be invalid in DeliverTx because block gas limit already hit. 

We either need to improve mempool.Reap to account for this some how (some possible solutions coming in 0.11.) or else keep invalid DeliverTx txs around

**Comment by adrianbrink** [comment]
This would be a fix for https://github.com/tendermint/ethermint/issues/300

**Comment by melekes** [comment]
> keep invalid DeliverTx txs around

If we left txs in the mempool, won't this lead to mempool bloat?

**Comment by ebuchman** [comment]
We would need some kind of intelligent policy. It's a non-trivial feature. Probably best to just write better clients actually. I think @cloudhead might have some thoughts on this as he recently emailed me some questions about mempool semantics and invalid txs

**Comment by cloudhead** [comment]
Am definitely for "dumbing-down" the mempool and moving some of the intelligence to the clients. It's a lot easier to manage that way. So I'd say let them retry.

**Comment by ebuchman** [comment]
Yep lets close this.
