### ISSUE TITLE
rpc: read-your-writes consistency

### ISSUE THREAD

**Issue by tarcieri** [tendermint/tendermint#6359]
I was a bit uncertain whether to file this as a bug report or a feature request. I started as a bug, and looking at the feature request template I felt a bug report style might be a bit more appropriate, though the likely resolution for this is probably a new feature.

**Tendermint version**

0.34.0

**ABCI app**

```
~ # gaiad version
stargate-1a-35-gabbf6b9
~ # gaiad tendermint version
tendermint: 0.34.0
abci: 0.17.0
blockprotocol: 11
p2pprotocol: 8
```

**Environment**:

@jackzampolin's gaia test container: https://hub.docker.com/r/jackzampolin/gaiatest

**What happened**:

After submitting a valid `MsgSend` transaction via the JSON RPC API using the `/broadcast_tx_commit` endpoint and receiving successful response for both `CheckTx` and `DeliverTx`, I attempted to look up the commit hash in the response using `/tx_search`.

I observed there is a small window, ostensibly between when the transaction is accepted and when it is indexed, where `/tx_search` will return no results.

**What you expected to happen**:

When performing `/tx_search`,  I was expecting 1 result on the first try instead of 0.

In the context of an integration test I was writing, I was hoping for [read-your-writes (RYW) consistency](http://www.dbms2.com/2010/05/01/ryw-read-your-writes-consistency/), namely I want to delay performing `/tx_search` until I'm guaranteed that a transaction with successful `DeliverTx` has been indexed.

I ended up "solving" the problem by [repeatedly querying the `/tx_search` endpoint for the same transaction hash](https://github.com/cosmos/cosmos-rust/blob/f409277/cosmos-sdk-rs/src/dev.rs#L101-L113) until I received 1 transaction result in the response instead of 0.

**Have you tried the latest version**

No

**How to reproduce it**

If you would like a repro, I can modify a [`cosmos-sdk-rs` integration test](https://github.com/cosmos/cosmos-rust/blob/f409277/cosmos-sdk-rs/tests/integration.rs#L86-L98) to reproduce this reliably.

**Anything else we need to know**:

Concretely what I'd like is an RPC API with RYW consistency which allows broadcasting a transaction in such a way that searching for that same transaction is always guaranteed to return a result.

I think having a straightforward solution to this problem is important for helping people write correct applications. If there's a way to make `/broadcast_tx_commit` "just work" this way, I think that'd be great, but I can see why there might be reasons not to.

Otherwise, I can imagine any number of ways of achieving this. I'm presently using the JSON RPC API, but if there's a gRPC API for this I'd be happy to switch.

In the context of a JSON RPC API I can imagine either adding an additional parameter to `/broadcast_tx_commit` (e.g. `wait_for_indexed=true` or so), or adding an additional `/broadcast_*` endpoint which provides RYW guarantees.

For all I know perhaps this exists today and I'm simply unaware. Happy to acommodate whatever solution works.

**Comment by cmwaters** [comment]
Hey @tarcieri, you're spot on with your analysis. 

A `/broadcast_commit` call subscribes to the `EventBus` the same way that the Tx Indexer does. This means that when a block get's committed and the events are fired, the broadcast commit returns the result at around the same time that the Tx Indexer receives the Tx to index. Thus the delay arises from the time the Tx Indexer takes to store the Tx.  

The Tx Indexer is viewed as a secondary source of data. In fact we are in the process of externalising it from Tendermint even further by implementing just an event sink (see https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-065-custom-event-indexing.md) so I don't think you can expect this read-your-writes guarantee. The primary source of data would be the block store (which doesn't have the best API). You could technically call `node.BlockStore().Block(height)` and the Tx would be somewhere in that block.

**Comment by alexanderbez** [comment]
Totally get the concern @tarcieri, but we make zero guarantees about the tx and block indexer, especially not RYW and I'm not sure we ever can or ever will being that it's async and event driven, as well as many things could fail on the indexing side.

I suppose you could view the indexer as eventually consistent. However, for your specific use case can you not just use the `/tx?hash=` endpoint?

**Comment by tarcieri** [comment]
> However, for your specific use case can you not just use the `/tx?hash=` endpoint?

That sounds like it might do the trick. I guess it isn't wrapped in the Rust RPC client though:

https://docs.rs/tendermint-rpc/0.19.0/tendermint_rpc/trait.Client.html

I can take a look at getting it added.

**Comment by cmwaters** [comment]
I'm going to close this issue now because I believe it has been addressed. If I'm wrong, then let me know and I will reopen the issue

**Comment by tarcieri** [comment]
I attempted to switch from polling the `/tx_search` endpoint to using the `/tx` endpoint in this PR to `cosmrs`:

https://github.com/cosmos/cosmos-rust/pull/116/files

However, the tests sporadically fail with:

https://github.com/cosmos/cosmos-rust/pull/116/checks?check_run_id=3724891908

```
Caused by:
    Internal error: tx (FFE0D601EF72615F73F9C3F99F583A1D1DBB2C9A010EB910185E88D2048E1E7C) not found (code: -32603)
```

**Comment by tarcieri** [comment]
I was able to "fix" this by adding back polling, except against the `/tx` endpoint:

https://github.com/cosmos/cosmos-rust/pull/116/commits/b95b14e2274bc8fafd9b47914dac6eb700ccdf79

**Comment by tarcieri** [comment]
@cmwaters can this issue be reopen given the above?

**Comment by tarcieri** [comment]
Filed a new issue for this since I couldn't get this issue reopened: #7196
