### ISSUE TITLE
check_tx failed: code=111222, codespace=undefined after genesis but before first block

### ISSUE THREAD

**Issue by tarcieri** [tendermint/tendermint#6360]
**Tendermint version**

0.34.0

**ABCI app**

```
~ # gaiad version
stargate-1a-35-gabbf6b9
~ # gaiad tendermint version
tendermint: 0.34.0
abci: 0.17.0
blockprotocol: 11
p2pprotocol: 8
```

**Environment**:

@jackzampolin's gaia test container: https://hub.docker.com/r/jackzampolin/gaiatest

**What happened**:

The `single-node.sh` entrypoint script in the `jackzampolin/gaiatest` creates a genesis account:

```
$ gaiad add-genesis-account $GENACCT $coins
```

After booting a new node and waiting for a successful `/genesis` response containing `$GENACCT` and the `$coins` distribution above, but before the first block was generated, I tried to use the RPC API `/broadcast_tx_commit` a transaction sent from `$GENACCT`.

I got the following response:

```
check_tx failed: TxResult { code: Err(111222), data: None, log: Log("panic"), info: Info(""), gas_wanted: Gas(0), gas_used: Gas(0), events: [], codespace: Codespace("undefined") }
```

**What you expected to happen**:

I realize that trying to broadcast a transaction before the first block is produced is probably a fraught endeavor, so I'm not sure I have a reasonable "expectation" here.

However, I hear codespace: undefined is... bad.

**Have you tried the latest version**

No

**How to reproduce it**

Use the `/broadcast_tx_commit` endpoint to broadcast a valid transaction before the first block is produced.

I can put together a repro if you'd like.

**Logs**:

NOTHING! Not even with `log_level="debug"`. Seems like an internal crash which is getting swallowed somewhere and never logged.

**Comment by alexanderbez** [comment]
I think this issue belongs in the SDK tbh. The error you received was due to a result in a recovered panic in the SDK.

**Comment by marbar3778** [comment]
closing this as it belongs in the sdk.
