### ISSUE TITLE
config: reuse `Seeds` p2p config parameter as initial peers to connect with

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6363]
## Summary

Since seed nodes aren't treated any differently in a system, the `P2PConfig.Seeds` parameter is unused. 

## Proposal

Nodes need to be able to bootstrap to a few peers on start up such that they can run the PEX reactor with and get addresses of the nodes in the network. Currently, we use `P2PConfig.PersistentPeers` to add nodes. However persistent peers have a special use, nodes that we persistently want a connection with. I propose that we use `P2PConfig.Seeds` to be a list of peers that we add to the peer store on startup. There are no guarantees that the node will remain connected with these initial peers.

I personally think prior users can still think of `P2PConfig.Seeds` in a same way and that there won't be much confusion. If others think differently then perhaps we can make this as a new config parameter: `P2PConfig.InitialPeers` or `P2PConfig.BootstrapPeers`.  

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Actually I change my mind. I think we should probably rename it else users will think that only seed nodes go there

**Comment by alexanderbez** [comment]
Rename what exactly @cmwaters?

**Comment by cmwaters** [comment]
`P2PConfig.Seeds` to `P2PConfig.InitialPeers`. Well we'd probably leave the seeds parameter there so it's more of making a new p2p config param rather than renaming one

**Comment by alexanderbez** [comment]
Why can't we just use `P2PConfig.Seeds`?

**Comment by cmwaters** [comment]
I don't mind directly using `P2PConfig.Seeds`. There could be enough overlap. My understanding of the difference:
- `P2PConfig.Seeds`: Previously used to refer to seed nodes only and indicated to the node that these nodes would behave differently whereas now seed nodes behave in the same manner but they have only the PEX reactor running. When a node was running low on peers it would fall back to asking the seed nodes else it wouldn't use them much. 
- `P2PConfig.InitialPeers`: Can be a seed node or a full node. It is just the peers we initially add and join with but we could disconnect from them or remove them from the peer store at a later stage.

**Comment by alexanderbez** [comment]
IMHO, if we add `P2PConfig.InitialPeers`, I can see this really confusing operators. Best to introduce less configuration if we can. If it's an absolute must, I suppose we can but we need to be very explicit with documentation.

**Comment by alexanderbez** [comment]
Also keep in mind, the legacy p2p stack will be removed at some point.

**Comment by cmwaters** [comment]
Yeah so you definitely have more experience than me when it comes to operating so I would defer final judgement to you.

What I know is that we definitely need some way that we can bootstrap the PEX reactor with some initial peers to get it going. At the moment this can only be done with `PersistentPeers`. However, I imagine not all nodes want to have persistent peers. We should offer an alternative way to add initial peers without the characteristic of them being persistent. 

My two options for doing this as I mentioned above is either to use the existing `Seeds` config parameter which would mean a slight tweak in its definition **or** to add a new `InitialPeers` parameter for this purpose and when we remove the legacy stack we also remove the `Seeds` parameter.

I have a slight preference for the latter.

What do you think?

**Comment by alexanderbez** [comment]
> to add a new InitialPeers parameter for this purpose and when we remove the legacy stack we also remove the Seeds parameter.

I have a preference for this. Let's add a new configuration and eventually remove seeds. I'm ok with just `Peer` or `BootstrapPeers` or something similar 👍
