### ISSUE TITLE
mempool: transaction drop mechanism

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#6369]
## Summary

To implement a timeout mechanism in the mempool to drop the transactions when the pool update.

## Problem Definition

The mempool doesn't have a timeout mechanism to drop the transactions automatically. So if some transactions stuck in the mempool and occupy some mempool space, the pool might not be able to accept new transactions.
ref: https://github.com/tendermint/tendermint/discussions/6295

## Proposal

In the mempool refactor discussion, we can add `max_mempool_duration` in the mempool config settings and implement a map to keep the transaction incoming height, therefore, we can do the height check in`Update` call

https://github.com/tendermint/tendermint/discussions/6295#discussioncomment-621807
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks @JayT106 for creating the issue. This should be a fairly low-lift and easy thing to add with high value.

@tessr can we add this to the 0.35 milestone?
