### ISSUE TITLE
cmd: integrate e2e test commands

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6373]
## Summary

This was a proposed feature of the original e2e test RFC (now an ADR) that was never implemented.

## Proposal

I think the command set in the e2e tests provides a lot of great features when playing around with testnets that we should export to end users.

This is a relatively simple change, however one piece of work that we might want to add is to allow users to connect the e2e tests with their own applications

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Add the e2e commands to the `tendermint` cli in replace of `tendermint testnet`. We will also need to make slight modifications to the e2e framework to configure other apps to be able to use it instead of the default test app

**Comment by marbar3778** [comment]
> Add the e2e commands to the `tendermint` cli in replace of `tendermint testnet`.

Is this only the generator or also the spinning up of network? Testnet command is used to also quickly setup distributed testnets through various devops tools. We should try to keep the same functionality.

**Comment by cmwaters** [comment]
> Testnet command is used to also quickly setup distributed testnets through various devops tools.
Can you elaborate? AFAICS, `testnet` is just good for initialising multiple nodes with different ip's in some file directory

I was thinking of being able to spin up the network (as well as load it, perturb it, benchmark it and so forth)
