### ISSUE TITLE
evidence: revise hashing method

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6388]
## Summary

A problem with seeing inconsistent evidence hashes (particularly LightClientAttackEvidence) was noted in #6326

A non breaking fix was made to the problem here: https://github.com/tendermint/tendermint/pull/6375 which revised how we encoded and decoded validator sets to be consistent (with respect to the unexported field: TotalVotingPower)

Given the opportunity to make a block protocol breaking change, we should consider changing from using bytes to hashes:
```go
    evidenceBzs[i] = evl[i].Bytes()
```
```go
   evidenceBzs[i] = evl[i].Hash()
```

Furthermore we should look to change the hash / validation to prevent the opportunity for nodes to spam the network with `LightClientAttackEvidence`. Right now nodes are capable of mutating existing `LightClientAttackEvidence` such that it has a different hash (is seen as new evidence) and is still valid. 

## Proposal

See https://github.com/tendermint/tendermint/pull/6342 for an earlier implementation

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
ACK 👍

**Comment by tessr** [comment]
When you say "breaking change," you mean a _block protocol breaking change_ (hard fork), right?

**Comment by alexanderbez** [comment]
> When you say "breaking change," you mean a _block protocol breaking change_ (hard fork), right?

Great question!

**Comment by cmwaters** [comment]
Yes this would be a block protocol breaking change (hard fork)

**Comment by josef-widder** [comment]
I am putting my notes from a call with @cmwaters earlier today:

- duplicate vote evidence just consists of two votes by the same validator. As a result one cannot create slight variations of the evidence that hash to different values
- light client attack (LCA) evidence, is a richer data structure with `common-height` and a conflicting `LightBlock` which itself is a richer data structure that contains a `commit` that contains many votes (up to the cardinality of the validator set). As a result, from one LCA evidence, e.g., by omitting one of the votes, we could get a LCA evidence which is "in essence" the same, but hashes to a different value. Right now hashes are used as "admission control" to check whether evidence should be (i) gossiped (ii) voted for (iii) executed. This use of hashes opens the possibility to flood the network with basically the same evidence.

A central problem is to define a validation mechanism that is more precise, and doesn't allow variants of already committed evidence to enter the system again.

During the discussions two ideas were discussed
1. in addition to the hash, for a LCA, store the `common-height` and the `Lightblock.Height`, and only allow at most one evidence per `( common-height, Lightblock.Height)`. This might lead to situations where some misbehavior goes unpunished. But still we guarantee that per attack at least `1/3` of the voting power is punished.
2. store evidence per validator. (I didn't think this one through. Will do so in the coming days, perhaps storing the heights also would be useful in this case). 

Perhaps a combination of 1 and 2 would be even better...
