### ISSUE TITLE
cmd: operationalize key migration script for 0.34

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6392]
The following migration script is complete, but isn't connected to an upgrade workflow or command line interface, so we need to do this before the release. The migration code is here: 

https://github.com/tendermint/tendermint/blob/master/scripts/keymigrate/migrate.go#L335-L347

**Comment by marbar3778** [comment]
we could test this now to get a rough estimate of the duration.

**Comment by marbar3778** [comment]
@tychoish closed?

**Comment by cmwaters** [comment]
Yes I think we can close this (cc @tychoish)
