### ISSUE TITLE
docker-compose log file save

### ISSUE THREAD

**Issue by puffanddmx** [tendermint/tendermint#6393]
When running daemon using docker-compose, I want to save the daemon log in the container. Since the Tender Mint node itself does not have a log storage function, it is saved using nohup, but it is difficult to save it using the nohup function in the docker container. If there is a way, please let me know.

**Comment by tychoish** [comment]
Thanks for this report! I'm a little confused by your setup, please forgive me if these questions are too simple.

I might be reading this wrong, but it seems more like the problem at hand is with the behavior of docker/docker compose/nohup, and less with tendermint itself. This is cool, and I think points to some of the ways tendermint can be better at logging, but I have the following questions: 

- What docker container are you running? How are you building this container and running that container? 
- What is the docker compose configuration that you're running?
- What process are you sending the HUP signal to? 
- Which process is run with nohup?
- What makes it difficult to save the log with the nohup command today? Is there a specific command that you're running that has different behavior than you expect? 

Would making the logging target file configurable be a desirable solution in the longer term? 

Thanks for your patience!

**Comment by puffanddmx** [comment]
thanks!!
