### ISSUE TITLE
lightclient: unable to sync

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#6394]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.34.x and 0.34.10

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Cosmos-SDK and Tendermint

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac
- **Install tools**: Make
- **Others**:

**What happened**: When using the light client to sync with the cosmos hub, it errors on a websocket handshake error

```
I[2021-04-22|18:51:10.744] Creating client...                           chainID=cosmoshub-4
I[2021-04-22|18:51:10.839] Downloading trusted light block using options
I[2021-04-22|18:51:43.463] Starting proxy...                            laddr=tcp://localhost:8888
E[2021-04-22|18:51:43.563] proxy ListenAndServe                         err="can't start client: websocket: bad handshake"
```

**What you expected to happen**: sync the light client with the cosmos hub

**Have you tried the latest version**: yes

Master contains a breaking change outlined here https://github.com/tendermint/tendermint/issues/6389

**How to reproduce it** (as minimally and precisely as possible):
Here is a command I used

```
tendermint light cosmoshub-4 -p http://34.91.93.201:26657/ -w http://159.203.104.207:26657/,http://52.15.82.69:26657/ --height 5940895 --hash 8663FBD3FB9DCE3D8E461EA521C38256F6EAF85D4FA492BAE26D5863F53CA150
```

**Config (you can paste only the changes you've made)**: Default configuration

**Anything else we need to know**:

**Comment by cmwaters** [comment]
This issue is also mentioned in #6389

**Comment by marbar3778** [comment]
> This issue is also mentioned in #6389

oh whoops, thought that was focused on master syncing. Will close this
