### ISSUE TITLE
consensus: remove the WAL after database project

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6397]
## Summary

As part of #6032, we want to replace the data persistence layer (presently tm-db) that will provide a data layer that more durable and safe, and will make it possible to eliminate the use of a separate write-ahead-log (WAL) and rely on the storage engine itself for this level of functionality.

## Problem Definition

The separate WAL code in the consensus package is something of a maintenance burden, and is responsible for data persistence and state machine management. By taking advantage of a new database layer, the WAL can be removed, simplifying maintenance, and facilitating a simplifying refactor of the existing code. 

## Proposal

I believe that once the new database layer is complete it should be a much smaller undertaking to replace the current WAL component in the consensus state manager with appropriate calls to the new database layer. While we may eventually change some of the interfaces in the consensus package, at least initially it should be possible to rehome the existing functionality on top of new persistence fundamentals, to take advantage of the existing tests. This refactor should be safe to do as a forward compatible upgrade, once the new database service exists.

**Comment by alexanderbez** [comment]
I support this endeavor! The current WAL is pretty buggy as well. I do recall @ebuchman stating there was an additional purpose to the WAl. Would love for him to chime in here.

**Comment by tychoish** [comment]
The WAL code seems partially responsible for managing state machine within the consensus package, and I'm not proposing changing this aspect, but rather just removing the writing files to disk part.
