### ISSUE TITLE
0.33.x - commit does not validates anymore when the validator set contains more than 30 entries

### ISSUE THREAD

**Issue by daeMOn63** [tendermint/tendermint#6406]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.33.9

**What happened**:

At a certain height of my chain, CLI client queries started to fail with errors like:
```
ERROR: header has next vhash CB3FF4F1739E941F3A22E8F9F4D537B419DA2DFAC6C668D20A59477F51379B43 but next valset hash is 549142B6599C5646AA29CB95861A18418E9556D5A372C53EDB9874110E6BB592
```

It started to fail when a new validator joined, making the total number of validators equal to 31.

Tracing this, it starts from the commit validation: 
- https://github.com/tendermint/tendermint/blob/v0.33.9/lite/commit.go#L56

Which was created from the dynamic_verifier, which compute the wrong hash because it gets a partial validator set here: 
- https://github.com/tendermint/tendermint/blob/v0.33.9/lite/dynamic_verifier.go#L163

The client requests the validators from the API with a `page=0` and `perPage=0` arguments here:
- https://github.com/tendermint/tendermint/blob/v0.33.9/lite/client/provider.go#L114

The `perPage` is replaced by the `defaultPerPage` value when it's less than 1 in the validation:
- https://github.com/tendermint/tendermint/blob/v0.33.9/rpc/core/env.go#L116

Which default to 30:
- https://github.com/tendermint/tendermint/blob/v0.33.9/rpc/core/env.go#L23

So when having more than 30 validators, the verifier will only get the first 30 and is then unable to compute the validator set / next validator set hashes matching the ones in the header.

The quick fix was to query with the `--trust-node` flag, bypassing the whole verification.
I also validated that the issue is solved by swapping the `perPage=0` parameter to some value greater than the size of my validators set in https://github.com/tendermint/tendermint/blob/v0.33.9/lite/client/provider.go#L114

Now I'm unsure what's the best way to fix this:
- make the client read all pages ?
- make the client request the validator set with `perPage = staking.Params.MaxValidators` ?
- make the pagination validation treat 0 as "all" ?

**What you expected to happen**:

Being able to query the chain without having to provide the `--trust-node` flag.

**How to reproduce it** (as minimally and precisely as possible):

- Have a chain with 30 validators
- Query for the latest block and see it's working, displaying the block information
- Make a 31st validator join the party
- Query for the latest block and see the error `ERROR: header has next vhash ABC but next valset hash is DEF`

**Comment by cmwaters** [comment]
Thanks for reporting the issue @daeMOn63. We are aware of this and have made changes to master and v0.34 as you will see here:
https://github.com/tendermint/tendermint/blob/20610be98cef42c663169e3aae7f3a65ac5336bc/light/provider/http/http.go#L162
where we iterate through each page and then build the validator set afterwards. This fix doesn't seem to have been backported to v0.33 but I can look into getting that done.

**Comment by whiter4v3n** [comment]
To me, the real question how this procedure to increase the trust from client perspective?

**Comment by cmwaters** [comment]
> how this procedure/computation increases the trust from client perspective?

Are you still referring to the pagination of the validator set? The pagination is purely a REST/RPC trait to break down large chunks of data.

If you're referring to the more high level question about trust, the light client only ever trusts the initial header hash/height combination that the operator gives it on start up. It never trusts anything that the nodes it is connected to gives it but verifies it instead.

**Comment by cmwaters** [comment]
Hey, closing this issue as we're no longer supporting v0.33.x. I would recommend updating to v0.35 (or v0.34)
