### ISSUE TITLE
p2p: create migration script to transfer addresses from addressbook to peerstore

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6412]
Just jotting this down before I forget.

Should be done in a similar fashion to the key migration script / cli. Should be relatively trivial to read in the JSON file, parse the addresses and persist them to the peer store. I don't think we should delete the address book on completion.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
@cmwaters do we absolutely _need_ this? If we don't do this, most peers will just automatically be rediscovered. What we can do is add a hook that exists only in 0.35 such that if it sees an address file exists, it auto-migrates it.
