### ISSUE TITLE
rpc: remove global state in variables. 

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6424]
There are a couple of places in the RPC package that depend on global variables which ought to be removed and replaced with more explicitly managed states. 

- the [node](https://github.com/tendermint/tendermint/blob/master/rpc/client/main_test.go#L13)in the client test package should be replaced in individual tests with the appropriate fixtures. 
- in the core service package [env](https://github.com/tendermint/tendermint/blob/master/rpc/core/env.go#L30-L39) should be constructable, and all of the dependencies should become methods. This means that [the routes](https://github.com/tendermint/tendermint/blob/master/rpc/core/routes.go#L10) will also have to have a dependency on the environment.

This is in support, though somewhat tangentially, of preparing the public API for general consumption.

**Comment by alexanderbez** [comment]
Yes, please! This the main (only?) reason why we have to have a hacky lock in the in-process Tendermint test network used in the SDK.
