### ISSUE TITLE
libs/os: CopyFile when given a directory as the source can be made to truncate destination file

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#6427]
While auditing the code in here I noticed this pattern
https://github.com/tendermint/tendermint/blob/0b0914b3df50b06e6ca59fc76ccedb71d0bce8c1/libs/os/os.go#L52-L73

### Problem
If we look closely, we firstly stat the origin file https://github.com/tendermint/tendermint/blob/0b0914b3df50b06e6ca59fc76ccedb71d0bce8c1/libs/os/os.go#L53-L56

and then invoke os.Open on it ONLY if it exists, invoking os.Open on a directory is allowed, just reading from it for I/O will fail.

then we proceed to truncate the destination file :-( https://github.com/tendermint/tendermint/blob/0b0914b3df50b06e6ca59fc76ccedb71d0bce8c1/libs/os/os.go#L65-L69

and then ONLY fail at the end if reading from the origin fails ouch.
### Exhibit and test case
```go
func TestTrickedTruncation(t *testing.T) {
        tmpDir, err := ioutil.TempDir(os.TempDir(), "pwn_truncate")
        if err != nil {
                t.Fatal(err)
        }
        defer os.Remove(tmpDir)

        originalWALPath := filepath.Join(tmpDir, "wal")
        originalWALContent := []byte("I AM BECOME DEATH, DESTROYER OF ALL WORLDS!")
        if err := ioutil.WriteFile(originalWALPath, originalWALContent, 0755); err != nil {
                t.Fatal(err)
        }

        // 1. Sanity check.
        readWAL, err := ioutil.ReadFile(originalWALPath)
        if err != nil {
                t.Fatal(err)
        }
        if !bytes.Equal(readWAL, originalWALContent) {
                t.Fatalf("Cannot proceed as the content does not match\nGot:  %q\nWant: %q", readWAL, originalWALContent)
        }

        // 2. Now cause the truncation of the original file.
        // It is absolutely legal to invoke os.Open on a directory.
        if err := tmos.CopyFile(tmpDir, originalWALPath); err == nil {
                t.Fatal("Expected an error")
        }

        // 3. Check the WAL's content
        reReadWAL, err := ioutil.ReadFile(originalWALPath)
        if err != nil {
                t.Fatal(err)
        }
        if !bytes.Equal(reReadWAL, originalWALContent) {
                t.Fatalf("Oops, the WAL's content was changed :(\nGot:  %q\nWant: %q", reReadWAL, originalWALContent)
        }
}
```

### Impact
The usages of CopyFile can basically be intentionally changed to pass in directories and then truncate critical state such as the prior write ahead log

### Fix
Please make use of the os.Stat result at the very very beginning and use its .IsDir() method to ensure ONLY non-directories are used.

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
All Tendermint versions until 0b0914b3df50b06e6ca59fc76ccedb71d0bce8c1 or before this issue is fixed

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Irrelevant but every tendermint use

Backports might be necessary.

Kindly /cc-ing @cuonglm @ebuchman

**Comment by cuonglm** [comment]
There's one dangerous usage of this:

https://github.com/tendermint/tendermint/blob/0b0914b3df50b06e6ca59fc76ccedb71d0bce8c1/consensus/state.go#L339

If the WAL file setting is wrongly set, then the recovering process will silently failed.

**Comment by odeke-em** [comment]
Indeed! Exactly that's what I referenced as well and referenced in my repro above. An easy way to self pwn and clear out the WAL silently.
