### ISSUE TITLE
Coding for maintenance

### ISSUE THREAD

**Issue by josef-widder** [tendermint/tendermint#6432]
Surfaced from [Informal Systems](https://informal.systems/) Evidence end-to-end audit of https://github.com/tendermint/tendermint/commit/5a39f72aa8288696d7284e56e3f630ab721a9f9a.

Here we list some implementation details that look correct right now, but contain the risk of breaking properties in maintenance due to programming style or lack in documentation.

1. right now it is safe to [check](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/light/detector.go#L164) equality by hash of a lightblock and hash of a header. This might become problematic in future changes of data structures.

2. Computing the [intersection of two commits](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/types/evidence.go#L258) assumes that signatures in both commits are ordered identically. In the light client specifications, commits are considered as sets. It is unclear whether  conflicting blocks may have different order? I propose to update the data structure spec to mention the order requirement within the commits.

3. It is unclear why the check uses [>=0](https://github.com/tendermint/tendermint/blob/5a39f72aa8288696d7284e56e3f630ab721a9f9a/types/evidence.go#L136)?  Wouldn't that allow equal strings? So validate basic would allow evidence with two identical votes.  If the order is expected/enforced it should be documented [here](https://github.com/tendermint/spec/blob/master/spec/core/data_structures.md#duplicatevoteevidence).

**Comment by cmwaters** [comment]
> It is unclear why the check uses >=0? Wouldn't that allow equal strings? So validate basic would allow evidence with two identical votes. If the order is expected/enforced it should be documented here.

I looked over this code again and it is correct. If the `strings.Compare()` function returns a 0 or 1 it is seen as invalid hence using `>= 0` makes sense.
