### ISSUE TITLE
lint: logger should be lint free

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#645]
running `gometalinter --vendor --deadline=600s --disable-all --enable=errcheck ./...` throws many errors for the logger. I don't think it makes sense to check all them but rather have the logger not throw an error.

**Comment by odeke-em** [comment]
@zramsay I've retitled the issue, please feel free to revert it if I was off.

However, I can't reproduce this issue on the latest on `develop` 54c63726b03cbba067d10fa6b69b885c85678d17
<img width="754" alt="screen shot 2017-09-06 at 4 30 48 pm" src="https://user-images.githubusercontent.com/4898263/30137485-c48bddd0-9320-11e7-8799-b5a5bd4ba68d.png">

**Comment by odeke-em** [comment]
Also, which logger? I can't find a repository called `logger` or a variant of that in tendermint, might we be talking about `tmlibs/logger` instead?

**Comment by ebuchman** [comment]
@melekes :P

**Comment by melekes** [comment]
Yeah, let's change the interface and implementation to not return an error.

**Comment by zramsay** [comment]
Issue moved to [tendermint/tmlibs #50](https://github.com/tendermint/tmlibs/issues/50) via [**ZenHub**](https://www.zenhub.com/)
