### ISSUE TITLE
libs/clist: unnecessary usage of sync.WaitGroup

### ISSUE THREAD

**Issue by cuonglm** [tendermint/tendermint#6450]
## Summary

We can avoid using `sync.WaitGroup` and use channel instead.

## Problem Definition

Looking through `libs/clist` code, the documentation state why we use `sync.WaitGroup`:

https://github.com/tendermint/tendermint/blob/fdd506a12666e8b86b1cadda6151a1945bf07c3e/libs/clist/clist.go#L33

Though, that same job can be archived by using corresponding channels. That said:

 - `wg.Wait()` can be replaced by a receive operation on channel
 - `wg.Done()` can be replaced by closing channel operation

## Proposal

Removing all sync.WaitGroup fields, and use only channel primitives for synchronization. That should cleanup the code, make it more readable, easier to maintain and slightly more efficient.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Thanks for bringing this up @cuonglm. I'm curious as to why made you bring this up? Is the current implementation really that poor in performance compared to your changeset? I see there's a bit of improvement in the memory allocation, but I'm wonder if those changes are really worth it?

I just do not have enough context here to confidently give an ACK or not on the PR. Specifically, that code is already kinda messy and more complicated than it needs to be.

@tychoish thoughts?

**Comment by cuonglm** [comment]
@alexanderbez My main point is making the code simpler, not a boost in performance.

The usage of sync.WaitGroup is duplicated with what the wait channel does, so it's really confused.

@tychoish Yes, and I think we should add a better benchmark, as the current one is a bit of noisy.

**Comment by alexanderbez** [comment]
I do not have confidence in approving or disapproving this PR. Being that the current code works as-is and the added memory performance improvement isn't that drastic, I'd rather not touch it.
