### ISSUE TITLE
all reactors: unexport DecodeMessage and defend against empty input

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#646]
While working on https://github.com/orijtech/tendermint/commit/8c13a65bdd0396888a3dba7db8cf7d1396fbc098, which is a fix for https://github.com/tendermint/tendermint/issues/514, and at develop https://github.com/tendermint/tendermint/commit/54c63726b03cbba067d10fa6b69b885c85678d17, I have to write a test for the new change. However, I noticed that inside `blockchain/reactor.go` there is an exported function `DecodeMessage` https://github.com/tendermint/tendermint/blob/54c63726b03cbba067d10fa6b69b885c85678d17/blockchain/reactor.go#L291-L302.

That function is untested but also doesn't seem to be used anywhere in the other repos.
Grep-ing for `\.DecodeMessage` outside of this repo, gives 686 spurious hits that can be examined at https://gist.github.com/odeke-em/657adf5c63e0b4866f67c9508e25eb40, which you'll notice are spurious hits because the return signatures don't match up

I suggest that we unexport this function, to avoid API bloat as it isn't used anywhere elese but in the same file, and moreover isn't unit tested.

**Comment by ebuchman** [comment]
Note all reactors have a function like this for their particular message types. I don't think any of them are used outside their respective packages, as they are effectively just convenience functions. 

It may be wise to export them, but I'm hesitant to do so just yet.

**Comment by ebuchman** [comment]
let's unexport all of them and ensure their inputs aren't empty (even though reactors should guarantee the input is not empty)

**Comment by melekes** [comment]
Merged to develop. Will be shipped with 0.22.1 release.
