### ISSUE TITLE
privvalidator interface and easier HSM signing

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#647]

**Comment by silasdavis** [comment]
ha I came here to say this. Actually I was going to say "leave the filesystem alone". Or at least it should be the very outer layers than touch it. Currently writing back state to `PrivValidator` is problematic. As this issue implies forcing writing private key matter to disk so it can be reingested is also a bad idea. Everything Tendermint needs to do shoiuld be possible to be facilitated by delegated access to a signing daemon.

Can we make all interaction to PrivValidator via a signing interface?

It would be nice also if from `NewNode` down Tendermint doesn't touch the filesystem (for genesis doc, state database etc) so we could inject our own dependencies for those things that may be dynamically sourced in a cloud orchestration platform like kubernetes, or from a secret store like vault or an elf in box with many pigeons.

**Comment by ebuchman** [comment]
A presumably deleted comment that I think is valuable:

```
ha I came here to say this. Actually I was going to say "leave the filesystem alone". Or at least it should be the very outer layers than touch it. Currently writing back state to PrivValidator is problematic. As this issue implies forcing writing private key matter to disk so it can be reingested is also a bad idea. Everything Tendermint needs to do shoiuld be possible to be facilitated by delegated access to a signing daemon.

Can we make all interaction to PrivValidator via a signing interface?

It would be nice also if from NewNode down Tendermint doesn't touch the filesystem (for genesis doc, state database etc) so we could inject our own dependencies for those things that may be dynamically sourced in a cloud orchestration platform like kubernetes, or from a secret store like vault or an elf in box with many pigeons.

```

**Comment by silasdavis** [comment]
That was from me, I thought I'd come back with something more substantive, but I'd be interested in working on this

**Comment by ebuchman** [comment]
@silasdavis see https://github.com/tendermint/tendermint/pull/637 for the PrivValidator interface. Interested in your thoughts on the interface and default implementation: https://github.com/tendermint/tendermint/blob/feature/hsm/types/priv_validator.go#L37

Also, what do you think of https://github.com/tendermint/tendermint/blob/feature/hsm/cmd/tendermint/commands/run_node.go#L44 ? Specifically how its used in NewRunNodeCmd. It enabled other projects to have a simple main.go, like https://github.com/tendermint/tendermint/blob/feature/hsm/cmd/tendermint/main.go, where all they have to do is pick a function to pass to NewRunNodeCmd.

As for the other comment, about NewNode not touching the disk again ... should this hold try for the DB as well? You think we should provide interfaces for building the DB and fetching the genesis file here too ? I can look into that tomorrow.

**Comment by silasdavis** [comment]
Regarding the `NewRunNodeCmd` I like the general idea but I'd say it's an odd place to hook. If I am running Tendermint in-process I'm likely to want to be more in control, and you add relatively little value by coupling the node creation with a specific library (cobra) and a specific command. I'd also expect to have control of the config so not sure we want that passed through. I think the `NewNode` function is the correct place to inject dependencies. Tendermint-the-binary can provide its own dependencies (DB, genesis, filesystem), but Tendermint-the-library can start there.

For the `PrivValidator` inteface, what you have there looks like it might work internally as a shim, but it's always been a code smell that Tendermint (and eris-db!) embeds its signature's inside the structure being signed, like:

```go
type Proposal struct {
	Height           int              `json:"height"`
	Round            int              `json:"round"`
	BlockPartsHeader PartSetHeader    `json:"block_parts_header"`
	POLRound         int              `json:"pol_round"`    // -1 if null.
	POLBlockID       BlockID          `json:"pol_block_id"` // zero if null.
	Signature        crypto.Signature `json:"signature"` // Smell
}
```

It would be better if we just provide an opaque signing inteface to `NewNode` it should not need to know about your types and should be fed a plain digest. I note that you have an interface like this that your `PrivValidator` implementations use:

```go
type Signer interface {
	Sign(msg []byte) (crypto.Signature, error)
}
```

It's down to Tendermint core how the digest (btw this is a better name than `SignBytes`) is generated - callers shouldn't need to know how to sign a `Heartbeat`. Even better than using your own `Signer` interface is to use Go's crypto stdlib one and be compatible with everything else that uses it: https://golang.org/pkg/crypto/#Signer.

So I would propose that you change the `NewNode` function to have a signature like the following (not necessarily suggesting you need a `Tendermint` interface, but add it as a dummy to give a compileable example):

```go
package tendermint

import (
	"crypto"

	"github.com/Masterminds/glide/cfg"
	"github.com/tendermint/tendermint/node"
	"github.com/tendermint/tendermint/proxy"
	"github.com/tendermint/tendermint/types"
	dbm "github.com/tendermint/tmlibs/db"
	"io"
)

type TendermintDBContext struct {
	id string
	// Open for extension
}

type Tendermint interface {
	NewNode(config cfg.Config, validatorSigner crypto.Signer, genesisDoc types.GenesisDoc,
		dbProvider func(dbContext *TendermintDBContext) dbm.DB, clientCreator proxy.ClientCreator) *node.Node
}

// Go Crypto Signer interface for reference:

// Signer is an interface for an opaque private key that can be used for
// signing operations. For example, an RSA key kept in a hardware module.
type Signer interface {
	// Public returns the public key corresponding to the opaque,
	// private key.
	Public() PublicKey

	// Sign signs digest with the private key, possibly using entropy from
	// rand. For an RSA key, the resulting signature should be either a
	// PKCS#1 v1.5 or PSS signature (as indicated by opts). For an (EC)DSA
	// key, it should be a DER-serialised, ASN.1 signature structure.
	//
	// Hash implements the SignerOpts interface and, in most cases, one can
	// simply pass in the hash function used as opts. Sign may also attempt
	// to type assert opts to other types in order to obtain algorithm
	// specific values. See the documentation in each package for details.
	//
	// Note that when a signature of a hash of a larger message is needed,
	// the caller is responsible for hashing the larger message and passing
	// the hash (as digest) and the hash function (as opts) to Sign.
	Sign(rand io.Reader, digest []byte, opts SignerOpts) (signature []byte, err error)
}
```

**Comment by silasdavis** [comment]
We could go further than this with making `NewNode` even more 'side-effect free` and providinig it with abstract networking objects rather than it dialing over TCP itself, but this is probably a bridge too far because it is deeply integrated into Tendermint (and Go), but if you had a reliable transport abstraction then why not run the Tendermint protocol across threads running on different processor cores, or devices using a non-TCP transport...

**Comment by ebuchman** [comment]
Wow, thanks Silas! This is super helpful!

**Comment by ebuchman** [comment]
Also see Duncan's comment: https://github.com/tendermint/tendermint/pull/637#issuecomment-330628114

I think what you propose can still work, if the PrivValidator itself satisfies crypto.Signer, we can use that, but then the hardware needs to be able to deserialize the msg and check conditions

**Comment by silasdavis** [comment]
I've responded in other ticket, but I think you can just provide a function to decorate a `crypto.Signer` into a `PrivValidator`.

**Comment by ethanfrey** [comment]
Wait... where is `crypto.Signer` defined?
It's not in go-crypto... https://godoc.org/github.com/tendermint/go-crypto

You mean `types.Signer`?
https://github.com/tendermint/tendermint/blob/master/types/priv_validator.go#L56-L64

**Comment by ebuchman** [comment]
He's referring to Golang's built in Signer interface: https://golang.org/pkg/crypto/#Signer

**Comment by ebuchman** [comment]
merged https://github.com/tendermint/tendermint/pull/637
