### ISSUE TITLE
No way to send from VM

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#65]
Unless I'm missing something, there is no way to send funds from a contract to an account. Presumably this would be done with the CALL opcode, but that simply calls `vm.Call(...)` which panics if there is no code passed in. Instead, we should remove the panic, do the transfer, and then return if there's no code. This is more or less what happens in go-eth. Also CALL expects the destination account to exist, and returns an error if it doesn't, so we might have to remove that check so the contract can send funds to a new account. Happy to fix it once you acknowledge.

**Comment by jaekwon** [comment]
+1  Also wrote on the comments for the PR
