### ISSUE TITLE
docs: update docs to accurately reflect changes in 0.35

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6512]
## Summary

The current [docs](https://docs.tendermint.com/master/) has a few sections that are outdated in light of the changes made for 0.35. Specifically, this is information regarding to how the P2P system works and the mempool. There may even be a few other outdated sections with respect to the light client / RPC / statesync etc... 

I would suggest, before cutting 0.35, that we do a pass over all the documentation and try lift the bar a little so that it's consistent and relevant with respect to the current state of Tendermint. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by abom** [comment]
Also I want to mention this built-in app tutorial is outdated and doesn't work or compile:

https://docs.tendermint.com/master/tutorials/go-built-in.html

For instance, the code has internal imports while it instructs the reader to do all in an external package.

```
 "github.com/tendermint/tendermint/internal/p2p"
```

Also, many imports are outdated and definitions are not there anymore.

**Comment by cmwaters** [comment]
Thanks for pointing that out. We've changed up the repo structure a lot in this release so there's definitely a lot updating that will need to be done to the documentation

**Comment by abom** [comment]
Thank you for your reply. Is it possible that this tutorial works on a certain version (not master)? or the tutorial itself has to be fixed?

**Comment by abom** [comment]
Code samples of this tutorials are working against [0.34.11](https://github.com/tendermint/tendermint/blob/c2908ef785bb5ca6e015910368e4b7a32821b9ff/docs/tutorials/go-built-in.md).

**Comment by oliverasistemas** [comment]
Hello, is this issue been worked by someone? Can I help?
