### ISSUE TITLE
Always set limit when using `wire.ReadBinary`

### ISSUE THREAD

**Issue by mveytsman** [tendermint/tendermint#652]
go-wire can allocate slices with arbitrary length in memory when using `DecodeBinary`

`DecodeBinary` has a limit parameter which limits how many bytes are to be read off the reader which will correlate with how many bytes we're allocating. When the limit is set to 0 it will read forever, and this can lead to memory exhaustion.

We should always be calling `DecodeBinary` with a non-zero limit parameter.

Tendermint core uses a limit of 0 in the following places:

- [ ] https://github.com/tendermint/tendermint/blob/267f134d44e76efb2adef5f0c993da8a5d5bd1b8/blockchain/store.go#L67

- [ ] https://github.com/tendermint/tendermint/blob/267f134d44e76efb2adef5f0c993da8a5d5bd1b8/state/txindex/kv/kv.go#L39

- [ ] https://github.com/tendermint/tendermint/blob/267f134d44e76efb2adef5f0c993da8a5d5bd1b8/types/validator.go#L98

- [ ] https://github.com/tendermint/tendermint/blob/7f3c697b6e4c624aa0f8d29ff97e9bfe20deb8f9/types/validator_set.go#L303

- [ ] https://github.com/tendermint/tendermint/blob/267f134d44e76efb2adef5f0c993da8a5d5bd1b8/state/txindex/kv/kv.go#L39

- [ ] https://github.com/tendermint/iavl/blob/bd904fb161c757ce2b04889c62e1c5f4b88165a8/iavl_proof_key.go#L46

We should use a maxlength based on the object being read for all of them.

Furthermore, we may want to consider erroring out in `go-wire` when we read with a 0 limit, or choose some (sane) limit when we encounter 0.

**Comment by odeke-em** [comment]
Thanks for reporting this @mveytsman, I was eager to file an issue on `go-wire` but while writing a repro that would then become a test case after fixing it but unfortunately I can't reproduce it.
Please see
```go
package main

import (
	"bytes"
	"fmt"
	"time"

	"github.com/tendermint/go-wire"
	"github.com/tendermint/tendermint/types"
)

type result struct {
	n    int
	err  error
	meta *types.BlockMeta
}

func readThatBinary(limit int) chan *result {
	resChan := make(chan *result, 1)
	go func() {
		defer close(resChan)
		r := bytes.NewReader([]byte(`{
		      "block_id":{
			  "hash":"68617368","parts":{"hash":"70617274735F68617368","total":1000000}
		      },"height":12345,"round":23456,"type":2}}`))
		res := new(result)
		res.meta = wire.ReadBinary(new(types.BlockMeta), r, limit, &res.n, &res.err).(*types.BlockMeta)
		resChan <- res
	}()

	return resChan
}

func main() {
	tests := [...]int{
		0: 1000,
		1: 0,
	}

	timeoutPeriod := 2 * time.Second
	for i, limit := range tests {
		bChan := readThatBinary(limit)
		startTime := time.Now()
		select {
		case <-time.After(2 * time.Second):
			fmt.Printf("#%d: \033[31mlimit: %d, failed to read output in %s\033[00m\n", i, limit, timeoutPeriod)
		case res := <-bChan:
			fmt.Printf("#%d: \033[32mlimit: %d, successfully read out: %#v\033[00m in %s\n", i, limit, res, time.Now().Sub(startTime))
		}
	}
}
```

Result:
---
```shell
#0: limit: 1000, successfully read out: &main.result{n:1, err:(*errors.errorString)(0xc4201bc6a0), meta:(*types.BlockMeta)(0xc42006e100)} in 103.897µs
#1: limit: 0, successfully read out: &main.result{n:1, err:(*errors.errorString)(0xc4201bc6d0), meta:(*types.BlockMeta)(0xc42006e180)} in 13.481µs
```
all the tests pass with limit `0`.

Perhaps am writing the wrong repro?

**Comment by odeke-em** [comment]
Oops nvm, am passing in JSON input instead of wire.Binary input ahah, let me fix this up and reproduce. I am so JSON minded :(

**Comment by melekes** [comment]
what's up with this issue?

**Comment by melekes** [comment]
I believe it's not relevant anymore with new go-wire.
