### ISSUE TITLE
RPC: split into internal and external endpoints

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6520]
## Summary

The RPC currently serves a dual purpose. It both provides a set of endpoints that external clients can use to query the state of the blockchain and to submit transactions and yet it also provides a set of endpoints to help the operator to query the health and status of the node that they are running. More effort should be made to draw this distinction

## Problem Definition

A good example of this is private peers on `/net_info`. The operator may want this endpoint to debug what peers they are connected to and thus display private peers but this information should not be displayed when an external client wants to query information regarding the network. The same could be said with `/dump_consensus_state`. We may even want to support other endpoints such as live config changes which is definitely operator specific.

## Proposal

I think we would need to brainstorm what may be the best way to do this and if we feel like making this distinction is strictly necessary. An idea would be to separate these endpoints across two different ports

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
I like your proposal, but this is what tools like nginx are for. I would prefer recommending using tools already known in the devops ecosystem rather than creating it internally

**Comment by cmwaters** [comment]
Ok. I might have figured that this functionality was possible I'm just rather naive when it comes to the operator side of software. I think more than just building something internally, I'm curious as to whether people share my view on the RPC being dual purpose and whether we should be making some more cosmetic changes to highlight this distinction

**Comment by alexanderbez** [comment]
I like the idea. As @marbar3778 pointed out, this can already be solved externally and probably suggests that we shouldn't even bother fiddling with this complexity in the RPC layer. So you can either really do:

1. Use reverse proxies, i.e. nginx, to do this easily.
2. Require Tendermint to use OAuth or some other form of authentication for specific routes.

Option (1) requires no effort on our part :-)

**Comment by marbar3778** [comment]
Are we fine with recommending people use proxies, @cmwaters ?

**Comment by cmwaters** [comment]
Sure, I guess so. Do we want to add any documentation/guides to instruct operators what's a good way to set up their RPC server?

**Comment by marbar3778** [comment]
got an issue for it https://github.com/tendermint/tendermint/issues/5704
