### ISSUE TITLE
mempool: disconnect from faulty peers

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#6523]
## Summary

We should consider explicitly disconnecting, via a peer update, from peers that consistently send us transactions that fail `CheckTx`. We may have to type check against the errors for added granularity, i.e. `ErrTxTooLarge`. And we should also have a threshold per peer, i.e. not disconnect at first sight of an error.

ref: https://github.com/tendermint/tendermint/pull/6468#discussion_r642878668

/cc @cmwaters 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by JayT106** [comment]
The current router channel seems like it will evict the peer when all the error happen in the mempool (except for the types.ErrTxInCache)

https://github.com/tendermint/tendermint/blob/93c4e00e8e3138f71982be61c6c29ebe965ebfbf/internal/mempool/reactor.go#L211
https://github.com/tendermint/tendermint/blob/93c4e00e8e3138f71982be61c6c29ebe965ebfbf/internal/p2p/router.go#L417
