### ISSUE TITLE
p2p: ensure NodeID and NetAddress remain exported/public

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6548]
After #6547, or similar changes, which would move the p2p package into an `internal` package, there are a few types/functions which need to remain exported for use automating some very common operational tasks. These are, mostly [NetAddress](https://github.com/tendermint/tendermint/blob/master/p2p/netaddress.go#L22-L28) and its dependent type [NodeID](https://github.com/tendermint/tendermint/blob/master/p2p/address.go#L37-L40). 

These should, probably for the current moment move into the `types` package, though it might make sense to move it into the config package. 

There are a couple of related functions/method and constructors which are, as a matter of practice of the `pex` package and should move into pex.

**Comment by marbar3778** [comment]
Update here? NodeID was merged but its unknown. 

Please use labels and try to add it to a milestone or project board. We aren't the best at this as a team but we should work towards this.

**Comment by cmwaters** [comment]
@tychoish Is this issue still relevant?

**Comment by tychoish** [comment]
This work is complete
