### ISSUE TITLE
Add block gas used to `ResultBlockResults` response 

### ISSUE THREAD

**Issue by fedekunze** [tendermint/tendermint#6551]
## Summary

Add the total gas used in the block to the `coretypes.ResultBlockResults`

## Problem Definition

As a user, I would like to retrieve the total gas used in a block without needing to iterate over all the `ResponseDeliverTx` items, so that I can populate the total gas used on the ethereum transaction receipt

## Proposal

Sum the txs gas used and add a new `TotalGasUsed` in the block to the `coretypes.ResultBlockResults` fields

@cmwaters 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
This could be done. Thanks for opening the issue.

For whoever picks this up, please update the spec as well 
(https://docs.tendermint.com/master/spec/rpc/#blockresults)

**Comment by crypto-facs** [comment]
Hey @marbar3778! I think I could help with this issue

**Comment by marbar3778** [comment]
> Hey @marbar3778 ! I think I could help with this issue

AMAZING!! let me know if you need any help!

**Comment by crypto-facs** [comment]
For sure! Thanks for the offer 💪 .. Can you please add me as a contributor so I can assign myself?

**Comment by fedekunze** [comment]
awesome @crypto-facs, ping me in the PR if you need an extra review

**Comment by crypto-facs** [comment]
Hey @marbar3778 I am about to raise a small PR to tackle this. Can you please point me to where I can update the specs?
