### ISSUE TITLE
rpc: move `p2p.NodeInfo`, `p2p.ConnectionStatus` to types 

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6553]
Based on @cmwaters comment on #6547, these times need to remain exported to for users of the RPC layer.

**Comment by marbar3778** [comment]
@tychoish nodeInfo has been moved, does ConnectionStatus still need to be moved?

**Comment by tychoish** [comment]
I believe so! Particularly if it's used in the RPC layer.
