### ISSUE TITLE
rpc: make changes to accommodate new p2p layer

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6555]
There are a number of aspects of the RPC layer that depend on aspects of the legacy p2p stack, which (likely) don't work when using the router rather than the switch (and would probably cause panics.) Before cutting a release we should fix these methods. This issue affects several methods: 

- `DumpConsensusState`
- `NetInfo`
- `UnsafeDialSeeds`
- `UnsafeDialPeers`

I guess the questions are:

- Do we want to take the opportunity to change any of these interfaces, or should we (insofar as it's possible) preserve compatibility with the legacy methods and types?
- Do these methods, particularly the Unsafe methods, even make sense given the differences between the peer management layers?
- Does it make sense to deprecate or remove the unsafe methods?

**Comment by alexanderbez** [comment]
So we definitely need to keep `DumpConsensusState` and `NetInfo`, which I think should be very straightforward with the new p2p stack.

I'm a bit skeptical on the `UnsafeDialSeeds` and `UnsafeDialPeers` methods though. Perhaps we remove those.

**Comment by tychoish** [comment]
I think removing the Unsafe methods make a lot of sense, and should be relatively non-contraversal.

The `NetInfo` method exports the `p2p.ConnectionStatus` (a property of the connection so probably fine,) and the `p2p.NodeInfo` which isn't a structure that we cache in the new peer manager (and perhaps don't want to?)

**Comment by tychoish** [comment]
I'd like to hear more about how these methods are used. it seems to me, that the legacy system wasn't great at staying connected to new peers or to connecting very frequently? The thought, as I understand it, is that the new p2p layer wouldn't need this kind of manual intervention/handcranking. Does the system not work without these methods, or do they just make a class of operations work faster?

Which is also to say that these describe operations that don't entirely have good analogues with the new p2p layer. We could leave them and make them not panic, to be removed when we remove the switch, or we could try and make analogues, but I'm not convinced that that would be useful.

**Comment by marbar3778** [comment]
How I have used it and other validators, I know, use it is when spinning up a new node instead of modifying the config or vis cmd line this endpoint would be used to give it peers but also the nodes that are already running to add this new node as a persistent peer. This avoids needing to stop and restart your node.

**Comment by tychoish** [comment]
I guess I'm confused as to the resistance to restarting a node to update the config vs using one of these unsafe methods. If the node doesn't have peers it's not meaningfully "up" (or making progress), so restarting it wouldn't hurt (or am I missing something?) It also seems, well, unsafe, to be able to effectively change the configuration via the RPC interface. 

I think the way we'd end up implementing this is just to add the new peers directly to the peer manager (via its `Add` method), potentially with a boost to it's score, and then let the existing peer management machinery do its work? Though it might make sense to have this be implemented as a new method and deprecate the existing methods?

**Comment by alexanderbez** [comment]
Well it could have peers, but maybe it wants more. Also, restarting nodes isn't as simple as you'd think for some validators. Many run theirs through VaaS providers, others have very strict SLAs/uptime requirements and restarting for just a config change may not be worth the trouble or risk.

**Comment by tychoish** [comment]
Surely VaaS companies provide some mechanism to support restarts to accommodate config changes and/or upgrades? 

We did some discussing about this earlier, and at least on the hub the uptime requirement is pretty flexible (to get slashed you have to miss 95% of 10k blocks, which means being offline for 16 hours, and  therefore can have recoverable production outages of basically anything less than that) which means simple restarts for cases like this are probably fine.

Calling an off-label "unsafe" method seems far less risky (and less likely to be well tested) than just restarting a process.

**Comment by alexanderbez** [comment]
> Surely VaaS companies provide some mechanism to support restarts to accommodate config changes and/or upgrades?

No, not directly (I've worked on one).

> We did some discussing about this earlier, and at least on the hub the uptime requirement is pretty flexible (to get slashed you have to miss 95% of 10k blocks, which means being offline for 16 hours, and therefore can have recoverable production outages of basically anything less than that) which means simple restarts for cases like this are probably fine.

This is the direct uptime requirements of the protocol. Customers and clients running infra have different SLAs and requirements, often more strict.

**Comment by tessr** [comment]
> I'd like to hear more about how these methods are used.

I think this question (from @tychoish) is reasonable, and @marbar3778's suggestion to ask in the validators channel is also a good one. We don't have to make a whole thing, but just dropping in and asking how people use these methods should give us a better idea of how it would impact folks to remove them. Sam, do you want to take that one since your face is on the ticket?

**Comment by greg-szabo** [comment]
Quick validator opinion:
* "unsafe" methods must be unsafe for a reason so I expect them to change/break/burn at any moment. (More like "dev" or "beta".) They are disabled in production environments and if they need to be enabled, they are considered a workaround until the feature gets into a stable state. I understand, that's not the original purpose of the tag, but at one point you have to let the operator's hand go. (`gaiad tx bank send` is not very safe for different reasons, but we don't tag it as unsafe.)
* `NetInfo` and `DumpConsensusState` are used in monitoring and alerting:
  * `NetInfo` is a good indicator of a node's network health, (node ID, IP, port, total number of connected peers, maybe moniker and incoming/outgoing flags are useful) but there's no point in listing the protocol version of the nodes or the RPC endpoints one-by-one: in practice, they are going to be the same. If the format breaks and only the essential information is provided, that's still ok.
  * `DumpConsensusState`: I've seen this used during network launches. If the format changes (gets more compact, even :) ), that should be fine, as long as the necessary information can still be derived.
  *
