### ISSUE TITLE
fuzz: adding entrypoint package for fuzzing

### ISSUE THREAD

**Issue by cuonglm** [tendermint/tendermint#6557]
## Summary

We need to add fuzzing to improve code quality.

## Problem Definition

Currently, there's no fuzzing in the code base. It's problem for critical code path, like `p2p`, `crypto`, ... which require high quality/performance/security.

## Proposal

Adding `fuzz` package for fuzzing al necessary code path, roughly the same as https://github.com/cosmos/cosmos-sdk/tree/fuzz-packages/fuzz

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cuonglm** [comment]
cc @odeke-em @tessr @marbar3778

**Comment by alexanderbez** [comment]
@melekes did a lot of work on introducing fuzzing into Tendermint. I'd highly recommend going off of what he's already established in this repo.

**Comment by odeke-em** [comment]
Aleksandr, adding this repo to oss-fuzz is setting up indeed so that prior
fuzzing functions can be used continuously. We are indeed building off
prior fuzzed code but taking it to the next level :-)

**Comment by odeke-em** [comment]
@cuonglm there are some fuzz functions as @alexanderbez mentioned that @melekes had done, please see https://github.com/tendermint/tendermint/search?q=fuzz

**Comment by marbar3778** [comment]
@cuonglm can this be closed?

**Comment by cuonglm** [comment]
> @cuonglm can this be closed? 

Ah yes.
