### ISSUE TITLE
Echo method not found

### ISSUE THREAD

**Issue by RodrigoASilvaSimoes** [tendermint/tendermint#6561]
**Tendermint version**:
unreleased-master-d6b4bc267bf333124438ed6b32a61660aa3e8fa1

**ABCI app**:
https://github.com/climber73/tendermint-abci-grpc-java

**Environment**:
- **OS**: Ubuntu 20.04.02 64-bit
- **Java version**: 12.0.2

**What happened**:
Using your latest version with your source code from a tutorial found on this page: https://docs.tendermint.com/master/tutorials/java.html. 
I simply cloned the project from the repository and as stated in the tutorial I ran the following command: `./gradlew run` and it showed me the following message:
`SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".`
`SLF4J: Defaulting to no-operation (NOP) logger implementation`
`SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.`
`gRPC server started, listening on 26658`

Then when I tryied to start the application with the command `TMHOME="/tmp/example" tendermint node --abci grpc --proxy-app tcp://127.0.0.1:26658` it shows the following error continually:
`ERR Echo failed connection=query err="rpc error: code = Unimplemented desc = Method not found: tendermint.abci.ABCIApplication/Echo" module=abci-client`

**Comment by marbar3778** [comment]
Hey, thanks for the opening this issue. What version of tendermint are you using? This seems to be a version mismatch.

**Comment by RodrigoASilvaSimoes** [comment]
When I execute "tendermint version" the output is:
unreleased-master-d6b4bc267bf333124438ed6b32a61660aa3e8fa1

**Comment by RodrigoASilvaSimoes** [comment]
I went to tested on branch release/v0.32.5 and it showed me the first warning message but tendermint behave as expected, no errors.
Then I tested on branch release/v0.34.0 and the error remains.

Unfortunately I do need version 0.34.0 for my project.

**Comment by marbar3778** [comment]
> I went to test on branch release/v0.32.5 and it showed me the first warning message but tendermint behave as expected, no errors.
> Then I tested on branch release/v0.34.0 and the error remains.
> 
> Unfortunately I do need version 0.34.0 for my project.

do you have a link to the code you are writing?

**Comment by RodrigoASilvaSimoes** [comment]
Solved it. The java example was broken for version 0.34.0 and up because ABCI changed. I created a fork with the version fixed for 0.34.x.

Here it is: https://github.com/RodrigoASilvaSimoes/tendermint-abci-grpc-java
