### ISSUE TITLE
statesync: increase chunk request timeout and decrease chunkFetchers

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#6564]
## Summary

Increase the chunk request timeout and decrease chunkFetchers. It can be hardcoded or make into a config setting.

## Problem Definition

Currently, the default chunk request timeout is 10 secs and not able to modify it. We can see our seed node server receive a chunk request from peers but not able to send the chuck in time. Therefore, the peer statesync will fail because not able to retrieve a full snapshot from our seed nodes. 

Some numbers I can see from debugging logs.
The current size of snapshot might around  200~MB. The chunk size limit is 10MB and the snapshot has 23 chunks.

I tried to extend the timeout to 1 min, the request can get some chunks back but still not able to finish.
extend the timeout also made  `chunkFetchers` from 4 down to 1, I am able to receive all chunks from the seed node.

The other issue we can see is the snapshot creation performance is bad, currently to create a new snapshot spend 30 mins to finish. Therefore, the node is not able to create a snapshot every 100 blocks.

## Proposal

modify the chunk request timeout longer, decrease the chunkFetchers
or make it configurable.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
> The other issue we can see is the snapshot creation performance is bad, currently to create a new snapshot spend 30 mins to finish. Therefore, the node is not able to create a snapshot every 100 blocks.

I'm not sure there is anything we can do about this due to IAVL's nature and that issue should be raised in the SDK.

To the other points, we can make that configurable.

**Comment by JayT106** [comment]
Yap. the snapshot part is related to the IAVL issue. I believe it's a known issue and the team is working on it.

@alexanderbez do you want me to add these chunk constants to the config?

**Comment by alexanderbez** [comment]
I've already started a PR but thanks @JayT106.

**Comment by cmwaters** [comment]
I still don't quite understand how changing `chunkRequestTimeout` is going to change anything. It doesn't stop peers from sending chunks after that time has passed; it instead signals when to send a second request for the chunk. I think it might even be a misnomer calling it a timeout. The same goes with decreasing the chunkFetchers - I'm struggling to reason how it makes a difference.

**Comment by JayT106** [comment]
@cmwaters from the behavior I've seen was: you are correct, the `chunkRequestTimeout` cannot stop the connecting peers sending the chunks. But it increases the p2p overhead between the connecting peers (our seed nodes) and my local node. Especially under the network bandwidth limitation (each chunk size has 10MB if I'm correct), Therefore, my local node is not able to receive the chunks within whole chunks request timeout, so I am not able to apply the full chunks. 

To decrease chunkFetchers is also trying to ease the p2p transmission pressure. I can receive the snapshot chunks from our seed nodes easily by lower the chunkFetchers to 1.

**Comment by cmwaters** [comment]
I get your point about the bandwidth but if 10 seconds is too short for 10MB then can't we just increase it to 20 or 30 seconds. Like I understand that the time we've chosen could be incorrect but I don't think we should make the value something configurable. All networks deal with the same problem (send 10MB of chunk data in 10 seconds) hence why would they need to tweak it. My view is if we can avoid an extra config variable we should. I would be much happier if we could agree on a better time and just set it to that.

**Comment by alexanderbez** [comment]
> All networks deal with the same problem (send 10MB of chunk data in 10 seconds) hence why would they need to tweak it. My view is if we can avoid an extra config variable we should. I would be much happier if we could agree on a better time and just set it to that.

@cmwaters I don't think you can reasonably expect that. You can't assume that all network topologies behave in the same way. Different nodes/networks sit behind various network providers, switches, firewalls, etc..., all competing for bandwidth with other processes.

The fact that the current values didn't provide a successful state sync for @JayT106 and their infra, but does provide successful state sync for other nodes/networks strongly suggests we can't just "bump it by X seconds" and expect it to work for everyone. This clearly demonstrates that values need to be tweaked for different topologies.

----

Re Tendermint's configuration, a thought crossed my mind recently. Tendermint is a beast of software -- it's pretty complicated and does many things and is ran in various ways in various operating systems and setups. We surely don't expect SpaceX's Falcon 9 to only have a few knobs and switches in it's control panel, so I think it would also be unreasonable to expect operators to run Tendermint with only a handful of configurations given everything it does.

**Comment by cmwaters** [comment]
> @cmwaters I don't think you can reasonably expect that. You can't assume that all network topologies behave in the same way. Different nodes/networks sit behind various network providers, switches, firewalls, etc..., all competing for bandwidth with other processes.

Sure I was making a rough generalisation about network typologies but the point was that they're not magnitudes different. Also I don't think this is a factor we need to get exactly right. It's fine to err on the safe side and bump it up a little higher if we know that it's causing too much network traffic.

> The fact that the current values didn't provide a successful state sync for @JayT106 and their infra, but does provide successful state sync for other nodes/networks strongly suggests we can't just "bump it by X seconds" and expect it to work for everyone. This clearly demonstrates that values need to be tweaked for different topologies.

I don't really think there's enough data points to draw that conclusion. What I hear (admittedly its second hand from Marko or Billy) is that there's many teams that occasionally struggle with state sync and that's fine. State sync is still in its teething stage and were slowly working to make it become more reliable. With any of these configuration problems, I think we need to first try to find a solution to it ourselves and only if we can't, do we throw it over the fence for the application developers to deal with it.

---

Your second point is more a high level stance towards configuration which is something I haven't really developed the intuition to have a strong opinion about. I think just as we can compare Tendermint to SpaceX's Falcon 9, so to could we look at things like TCP which do a great deal to solve a difficult problem but also abstract over it in a way that users don't need to worry too much about how it works. That's initially how I thought Tendermint wanted to position itself. You as the application developer don't need to know the ins and outs; it solves a difficult problem and it just works. You don't have to be crypto.com and hire a full-time engineer to work on Tendermint to understand how to run it, just like you don't need to be NASA and have astronaughts go through a two year program just to understand how Falcon 9 works.

**Comment by alexanderbez** [comment]
>  It's fine to err on the safe side and bump it up a little higher if we know that it's causing too much network traffic.

Ok so what value do you bump it to and why? And what if users still see issues and we come full circle? What value(s) to we bump it to then?

> I don't really think there's enough data points to draw that conclusion. What I hear (admittedly its second hand from Marko or Billy) is that there's many teams that occasionally struggle with state sync and that's fine. State sync is still in its teething stage and were slowly working to make it become more reliable. With any of these configuration problems, I think we need to first try to find a solution to it ourselves and only if we can't, do we throw it over the fence for the application developers to deal with it.

What are the solutions here? You either (1) keep the values the same, (2) tweak them arbitrarily (we'll never have enough context or data to reasonably set these), or (3) make them configurable with sane defaults.

**Comment by JayT106** [comment]
I think we can keep the current configuration as it is. So it doesn't create troubles for the other projects using the tendermint core 
Just made it configurable.

**Comment by cmwaters** [comment]
> Ok so what value do you bump it to and why? And what if users still see issues and we come full circle? What value(s) to we bump it to then?

Well what are we trying to solve here: My understanding is that when we request a second chunk of the same index in quick succession (i.e. after 10 seconds), we are potentially incurring unnecessary bandwidth (10MB worth) because the first request had taken longer to respond. So we want to mitigate the amount of times we request a second chunk when the first is on its way.  Network speeds are usually faster than 10MB/s so it's not like it's impossible to send a chunk within 10 seconds. Without changing the timeout we could also solve this problem by 1) increase the amount of nodes providing state sync services or 2) decrease the amount of connected peers so nodes are sharing bandwidth over lesser peers. 

Another way to look at it is that we may have 20+ chunks that need delivering - we're probably not going to notice the extra time even if we increase the timeout to about a minute. Statesync still usually takes a couple of hours on the cosmos hub

I would estimate without doing any work that a time between 30s - 1min is reasonable. We could experiment with these times and keep a counter of how many times we ask a chunk to be resent to track how effective the times are. It would be cool to try them on the cosmos hub or crypto.com.

**Comment by cmwaters** [comment]
Ah really? Here are my points against making this configurable just to be clear:
- At a high level, I feel that we should only make something configurable as a last resort - I feel that already a lot of the current `config` file could be simplified. We still need configuration but having too much configuration can be overwhelming; it requires users to have a good understanding of the mechanics of Tendermint and I feel that ideally we should endeavour to cover up as much as possible so users don't have to worry "which of the hundred knobs should I tweak to make something work". Therefore, if we can provide a solid solution that can cover 3 standard deviations of use cases we should. I think this is an example where it's insignificant enough to not warrant being a config. Tendermint has dozens of similarly styled timeouts and thresholds that are quite lazily picked but with a bit of tuning can easily cover 3 standard deviations of use cases. 
- I understand this is a problem with bandwidth. I think there are already knobs that users can already tweak in the p2p config (i.e. max_connected_peers) to make sure that they're able to send a chunk within 10 seconds. As I mentioned before you can also increase the amount of seed nodes offering snapshots (and if it's centralized, coordinate the heights at which snapshots are offered).
- I don't think we've properly diagnosed the problem and I think we're jumping too quickly to make something configurable as an easy way of dealing with the problem. I would like to gather more empirical evidence. I would try state sync a node 10 times and keep a counter of how often we need to ask for a chunk again and that the first chunk arrives.
- The nature of this case has very small downsides if we just increase it.
- Even if we do make this configurable, we still need to set a reasonable default so we still need to put the work in to find a reasonable timeout, why not just cement it at that.

There are advantages with a make-everything-configurable approach. It's less work on us for example. I'm just not sure if it's the right approach.

All in all, I didn't really want to labour on about this, I merely wanted to justify my thinking. As there's just the two of us and I'm blocking this and I do think that it might in fact help fix some problems, I'm not going to put my foot down on this.
