### ISSUE TITLE
p2p/conn: secret connection broken [P2P Audit]

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#6569]
The `dhSecret` is computed using `X25519`, then it is used to generate secret for receiving, sending and challenge without hashing.

The problem is that [with X25519, multiple publics key can lead to the same shared secret](https://crypto.stackexchange.com/q/73138/33178), aka `dhSecret` in this case. So if the attacker can control the `dhSecret`, he owns the secret connection. Further more, without hashing, [it increase the chance that part of the key might be guessable from public DH value](https://crypto.stackexchange.com/a/10661/33178).

Here's another [link](https://crypto.stackexchange.com/a/68238/33178) to prove that the security contract requires hashing the shared secret.

To fix this, we think the spec must be updated to require hashing the shared secret. This is also what [Noise does](https://noiseprotocol.org/noise.html#terminology) (emphasize ours):

> A Noise protocol begins with two parties exchanging handshake messages. During this handshake phase the parties exchange DH public keys and perform a sequence of DH operations, **hashing the DH results into a shared secret key**

We can also refer to what [age does](https://github.com/FiloSottile/age/blob/fb293ef526a2c09d5c7fc32d38a269558e77039c/agessh/agessh.go#L219).

**Comment by marbar3778** [comment]
My proposal here would be to drop the current secret handshake in the post 0.35 world and adopt noise.
