### ISSUE TITLE
p2p: PeerRatio Lock [P2P Audit]

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#6573]
`PeerManager#PeerRatio` should hold the lock right before checking if m.options.MaxPeers == 0.

`PeerManager#DialFailed` invokes a goroutine after m.retryDelay that calls m.dialWaker.Wake() after a timeout, but immediately after the goroutine is created, unconditionally invokes m.dialWaker.Wake().

**Comment by tychoish** [comment]
These appear to be seperate issues, is that correct?

**Comment by alexanderbez** [comment]
No, not based on the audit report. @odeke-em want to chime in?
