### ISSUE TITLE
tx indexer: add apache kafka event sink

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6584]
## Summary

[ADR 065](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-065-custom-event-indexing.md) introduced custom TX indexing via event sinks. We also added postgres support which offers a rich query engine for clients (block providers / wallets) that want to make funky transaction queries. The other use case that clients may want transactional data is via event streaming. 

## Proposal

[Apache Kafka](https://kafka.apache.org/) is a commonly used tool that allows clients to subscribe to events. We should allow operators to hook up kakfa servers (producers) to a node via the `EventSink`. I'm not sure if we have to set up the topics or wether the operator has to but I imagine they just correlate to the `Event.Type`. 
 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by laniehei** [comment]
A few questions came up for me while thinking about this issue

- There are several prominent opensourced kafka go packages available, namely [kafka-go](https://github.com/segmentio/kafka-go), [confluent's kafka implementation](https://github.com/confluentinc/confluent-kafka-go), and [sarama](https://github.com/Shopify/sarama). Is it dealer's choice which one to choose?
- Why are several of the methods no-op in the postgres implementation? I couldn't find this in the docs

I have a skeleton implementation, but these questions stopped me up a bit from going further ! tia

**Comment by alexanderbez** [comment]
> Why are several of the methods no-op in the postgres implementation? I couldn't find this in the docs

The no-op methods are the searching methods. The reason they are no-op is because the underlying sink, e.g. postgres, already provides this functionality as that is the entire point of the sink. e.g. you wouldn't provide a SQL query directly to the RPC method, you'd use Postgres directly. The same would apply for Kafka or any other sink.

**Comment by JayT106** [comment]
The implementation is quite simple, but I am running into this issue when writing the integrating test.
https://github.com/segmentio/kafka-go/issues/684
