### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by juntao** [tendermint/tendermint#659]
BUG REPORT

**Tendermint version**

0.10.3-'8d76408

**ABCI app**

N/A. I do have the "dummy" app running and listening for connections on the same machine.

**Merkleeyes version**

N/A

**Environment**:
- **OS** (e.g. from /etc/os-release): CentOS 5
- **Install tools**: Downloaded and unzipped from pre-compiled binaries
- **Others**: GO is NOT installed. Just the Tendermint, ABCI, and Basecoin binaries

**What happened**:

Running "tendermint node" throws the following error: "panic: Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable"

**What you expected to happen**:

I expect a single node with local validator should start.

**How to reproduce it** (as minimally and precisely as possible):

rm -rf $HOME/.tendermint
tendermint init
tendermint node

**Anything else do we need to know**:

The full stack trace is below. I suspect the binary install on a fresh Linux box is missing some dependencies. Perhaps we need to install GO?

Loaded PrivValidator                         module=node file=/home/azureuser/.tendermint/priv_validator.json privValidator="PrivValidator{24477F216FDA82599EE83B8DAB2C5D07C897D2F3 LH:30, LR:0, LS:3}"
panic: Panicked on a Sanity Check: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common.PanicSanity(0xaaebe0, 0xc420155480)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/common/errors.go:26 +0xdd
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/db.NewDB(0xbb9707, 0xa, 0xc4201434b0, 0x7, 0xc42015c600, 0x20, 0xbc07fe, 0x13)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/db/db.go:57 +0x18d
github.com/tendermint/tendermint/node.NewNode(0xc42006ac30, 0xc420140640, 0x1051740, 0xc42014d620, 0x105b880, 0xc42014d230, 0x1051740)
	/go/src/github.com/tendermint/tendermint/node/node.go:70 +0x127
github.com/tendermint/tendermint/node.NewNodeDefault(0xc42006ac30, 0x105b880, 0xc42014d230, 0x2)
	/go/src/github.com/tendermint/tendermint/node/node.go:65 +0x181
github.com/tendermint/tendermint/cmd/tendermint/commands.runNode(0x109db40, 0xc42013ab80, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/tendermint/tendermint/cmd/tendermint/commands/run_node.go:78 +0x375
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).execute(0x109db40, 0xc42013ab40, 0x2, 0x2, 0x109db40, 0xc42013ab40)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:647 +0x3f8
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x109d920, 0x4100a8, 0x20, 0xb0d100)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/tendermint/tendermint/vendor/github.com/spf13/cobra.(*Command).Execute(0x109d920, 0x9f0621, 0xb0d100)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli.Executor.Execute(0x109d920, 0xd054d8, 0x2, 0xc42013a940)
	/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/tmlibs/cli/setup.go:97 +0x4e
main.main()
	/go/src/github.com/tendermint/tendermint/cmd/tendermint/main.go:12 +0x8b

**Comment by mappum** [comment]
I believe that error message happens when another process is already using the LevelDB store. Are you sure you don't have another tendermint process running?

**Comment by juntao** [comment]
Arrrgh, you are right. So sorry. Killing all stray processes fixed this problem. Thanks.

**Comment by mappum** [comment]
No worries, really this just shows that we could have a more helpful error message since you likely won't be the last person to run into this 😊
