### ISSUE TITLE
docs: minor typo on transaction flow diagram

### ISSUE THREAD

**Issue by thephez** [tendermint/tendermint#6592]
**Tendermint version**: N/A

**ABCI app**: N/A

**Environment**: N/A

**What happened**:

There's a typo in the lower right side of the [transaction flow diagram](https://github.com/tendermint/tendermint/blob/master/docs/imgs/tm-transaction-flow.png). Where the "Mempool Connection", "Consensus Connection", and "Query Connection" are listed, "Consensus" is improperly spelled as "Cosensus".

**Comment by marbar3778** [comment]
Nice find!! This has gone under the radar for a couple of years. I will see if we can dig up the diagram, otherwise we may need to live with it.

**Comment by thephez** [comment]
Sounds good. Sometimes I just can't unsee typos so I thought I'd mention it :smile:

**Comment by marbar3778** [comment]
We weren't able to find the diagram, but the design team has added a todo to update and make the diagram cooler. Will close this issue for now. 

Thank you for opening this issue 😄
