### ISSUE TITLE
p2p: don't route messages to peer queues where the peer doesn't have the channel

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6593]
## Summary

Upon receiving a message from a peer to a channel that the router isn't aware of, the router will drop the message however if the sender is aware of the channels that the receiver has, they could stop the message from reaching their own queue as well as travelling across the network to the receiver in the first place.

## Proposal

Router tracks the connected peers channels (we could also do this in the peer manager?) and runs a check somewhere around here to prevent adding the message to the peer queue:

https://github.com/tendermint/tendermint/blob/d228afc5483ef2f2143e9d0ce4b3e5dcba70f8bb/internal/p2p/router.go#L442-L464
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
I see these as two orthogonal issues -- smarter peer update management and more efficient gossiping. Where I think the latter is more important IMHO.

**Comment by cmwaters** [comment]
I wouldn't call them completely orthogonal but they can be considered two different issues and I do agree that the latter is more important

**Comment by alexanderbez** [comment]
IMHO they are orthogonal in their solution and context. I would create two separate issues.

**Comment by cmwaters** [comment]
Ok I will pull it out into a different issue
