### ISSUE TITLE
Node stopped with error

### ISSUE THREAD

**Issue by RiccardoM** [tendermint/tendermint#6607]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.34.10

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
[Desmos](https://github.com/desmos-labs/desmos)

**Environment**:
**OS** (e.g. from /etc/os-release)
```
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
D_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**What happened**:
The node stoppped 

**Have you tried the latest version**  
No

**How to reproduce it** (as minimally and precisely as possible)  
No idea. The node has been running for months without any error. Then it crashed. 

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**  
https://pastebin.com/JEfR4Gk7

**Logs**
Here is the zip file produced from the `tendermint debug kill` command: [desmos.zip](https://github.com/tendermint/tendermint/files/6682326/desmos.zip)

**Comment by alexanderbez** [comment]
I don't understand @RiccardoM. The logs don't indicate anything with regards to the node stopping or anything that went wrong. What I do notice is that the process is managed by `cosmovisor`. Are you sure that `cosmovisor` didn't stop the binary?

**Comment by RiccardoM** [comment]
@alexanderbez Is there any way I can check if it was Cosmovisor causing this? The node just plain stopped without any error. The logs stopped rolling and the process froze. Is there a way I can search for additional logs?

**Comment by marbar3778** [comment]
@RiccardoM Could you ask in the cosmos discord or in the comsos-sdk repo. We dont have the best knowledge on cosmosvisor.
