### ISSUE TITLE
p2p: when connecting to a peer error is not descriptive

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#6611]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 0.34.10

**ABCI app** (name for built-in, URL for self-written if it's publicly available): cosmos-sdk

**What happened**:
When connecting to a node, if their address book is full the observed error will be i/o timeout, which could mean anything, but we keep trying to dial them

**What you expected to happen**:
Better error handling:

First, when I connect to another node, and if their addressbook is full, the peer should let me know this instead of denying the connection and my node observing i/o timeout. 

Second, if the peers addrbook is full, instead of rejecting the connection, it should reject it **and** provide some more peers for the node to dial. When spinning up a node with no seed node and only persistent peers, I repeatedly dial only the provided peers even if there is an error. Instead getting a response of, "Hey I'm full, but try these guys" would allow me to bootstrap a lot easier. 

**Have you tried the latest version**: no

I have not tried this with the new vesrion of the P2P layer.

**How to reproduce it** (as minimally and precisely as possible):

Connect to any network with only persistent peers

**Comment by alexanderbez** [comment]
If I'm not mistaken, this happens in the PEX reactor, which is now different in the new stack, as in we don't have an address book really. Do you think there's anything to be carried over to the new stack in this context?

**Comment by cmwaters** [comment]
> Do you think there's anything to be carried over to the new stack in this context?
Yeah I think peers should let one another know when they are rejecting a peer because all the connection slots are taken up

Currently we advertise peers to other peers based on score alone but if we could keep track of how many connections a node has then we can better inform peers which peers are better to connect to.
