### ISSUE TITLE
Move all `types` types package into `pkg` subpackages

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6616]
This is just a coordinating issue to move types around in preparation for the public API work. The goal of this issue is eliminate the `types` package entirely, and replace it with sub-packages within a new `pkg` hierarchy to hold types specific to their use/function. Additional goals, making the dependencies between legacy `types` types more explicit, permitting an "import what you need" model. 

The risk, of course, is that the `pkg` hierarchy will unintentionally leak details about the internals of various packages within `internal`, and that for the current use case, `types` is actually pretty good at avoiding being the location for (most) of the implementations. 

If we're onboard with doing this, I'd like to do this as one big push to reduce the CI cycle time and to be able to streamline the work, and hopefully soon enough that we can make any adjustments or re-categorizations as needed before 0.35.

**Comment by marbar3778** [comment]
> The risk, of course, is that the pkg hierarchy will unintentionally leak details about the internals of various packages within internal, 

How does this differ from types? 

I think the hardest point will be figuring out cyclical imports, but it can be done. Could we get an overview of potential cyclical imports to have a better understanding of what's possible.

**Comment by tychoish** [comment]
> How does this differ from types?

I think `types`, as a result of being _singular_ is easier to review and spot check, but I think in both cases it's up to reviewers to police the boundary, so I think you're right that it's not mechanically different. I think that putting big implementations into packages named `types` raises red flags in a way that putting a big implementation into a package named `pkg/mempool` wouldn't, and so `types` communicates intent a bit better. 

> I think the hardest point will be figuring out cyclical imports, but it can be done. Could we get an overview of potential cyclical imports to have a better understanding of what's possible.

There isn't extant tooling that I'm aware of that does this kind of dependency analysis between types within a package, so getting a list of this before making a decision on how to prioritize/schedule this work, may be roughly equivalent to doing it. 

The only real risk is that we might end up with *more* packages in `pkg` than there are in `internal` as a way of breaking the cycle, but I kind of doubt it. This seems annoying, and may lead to the discoverability and UX of `types` being better, but that's just a risk. 

--- 

I think we should consider the implications of doing this relative to #6616, and see where it makes sense to put this work relative to the 0.35 milestone.

**Comment by alexanderbez** [comment]
Fully support the `pkg/<domain>` model, however, I do not support doing it in one fell swoop -- I'd rather implement and review PRs package-by-package.

**Comment by tychoish** [comment]
> Fully support the pkg/<domain> model, however, I do not support doing it in one fell swoop -- I'd rather implement and review PRs package-by-package.

I could really go either way on this, there's pros and cons to both approaches, though I feel pretty strongly that we shouldn't do half of the packages in one release and half of the packages in the next release. I think the main open question is: _Should this go in to 0.35?_ 

As a practical matter, given the reliability of the CI and its turn around time, makes doing this package-by-package 5x as expensive from the perspective of engineering effort/time (and reviewer fatigue is definitely an issue/risk as well.) 

If we can do it in 1-2 PRs it could be done in a week or less and could easily make 0.35, I think package-by-package it could easily take 3+ weeks.

**Comment by alexanderbez** [comment]
I think there is no need to rush this and get this into 0.35 -- AFAIK this was never the plan. Ofc, we'd get it all in one release however. And doing it pkg by pkg won't really cost us anything.

**Comment by tychoish** [comment]
The increase in cycle time and reviewer fatigue is not free.

If we're ok with this happening in 0.36, then it means that some additional types will need to move into the `types` package for 0.35. Which I think is ok...

**Comment by alexanderbez** [comment]
I respectfully disagree. Reviewers are _benefited_ by the smaller scoped PRs. In addition, there is no rush to do this in a day or even a week, so the cycle time argument is moot.

**Comment by marbar3778** [comment]
Moving the types that weren't in `types` prior to 0.35 into `pkg` makes sense, to me, and then for 0.36 we migrate `types` into `pkg`.

**Comment by tychoish** [comment]
> Moving the types that weren't in `types` prior to 0.35 into `pkg` makes sense, to me, and then for 0.36 we migrate `types` into `pkg`.

While this makes a certain amount of sense, abstractly, I think given dependencies this will be difficult in practice. Additionally the UX for this is poor, as people who weren’t users during 0.34 won’t be able to understand why some types are in one location and other types are in another.
