### ISSUE TITLE
move generated proto files to `internal` 

### ISSUE THREAD

**Issue by tychoish** [tendermint/tendermint#6617]
This will make it so that other libraries cannot use our copies of the generated protobuf code, and will have to generate their own copies (which will help us upgrade libraries as needed.)

As a result a a number of the functions in the `types` package will need to become private, so this is worth thinking about in connection with #6616.

**Comment by marbar3778** [comment]
This will effect the sdk. CC'ing people for visibility 


cc @amaurym @ryanchristo @aaronc

**Comment by aaronc** [comment]
Can you provide more rationale pleas?

**Comment by tychoish** [comment]
I think this is sort of related to the #6166: right now we have a collection of types (in the `types` package, but this may move,) and we have a lot of boilerplate functions that convert these types to/from protobufs, and it would be nice if we could reduce the public surface area of the `types` folder, by moving the generated protobuf code out of the public API, we can also move the converting code, which I think would be a good for being able to upgrade/change the generator regularly, and make the public API of the project more ergonomic. 

The big benefit from this would be, I think, that the SDK and Tendermint wouldn't need to rely/coordinate on the implementation of the protobuf generated code. The proto files themselves are really an interchange format, and both projects really ought to be generating code themselves, and the fact that they're not is a bit thorny at the moment.

It's not required, of course, and we can talk more about the details or timeline of this, but I think it would be a good move.

**Comment by aaronc** [comment]
I would prefer if this doesn't go in 0.35 so that the SDK's work on mempool prioritization doesn't get delayed.

**Comment by tychoish** [comment]
Waiting on this till after 0.35 might make a lot of sense! I think we should also consider doing this more or less at the same time as #6616 because they impact a very related set of types.
