### ISSUE TITLE
blockchain: BlockchainReactor.AddPeer doesn't add peer to its pool

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#666]
I just hopped on to work on finishing PR https://github.com/tendermint/tendermint/pull/648 and while reading through the code I noticed that the code for AddPeer
https://github.com/tendermint/tendermint/blob/7f8240dfde4c7acca445e8dbceddb0b2e9a42e7a/blockchain/reactor.go#L114-L118

Just tries to send the peer our state, doesn't add the peer to the pool.

However, the code in RemovePeer pops the peer from the pool
https://github.com/tendermint/tendermint/blob/7f8240dfde4c7acca445e8dbceddb0b2e9a42e7a/blockchain/reactor.go#L121-L123

Am I mistaken that we aren't properly adding a peer to the pool or is there some reasoning for this? Also I don't see any tests for AddPeer nor for RemovePeer.

**Comment by melekes** [comment]
We add peer to the pool upon receiving bcStatusResponseMessage https://github.com/tendermint/tendermint/blob/develop/blockchain/reactor.go#L159

**Comment by ebuchman** [comment]
We should update the comments to more clearly reflect what's going on - the peer doesnt get added to the pool until we've received a bc msg.

So this isn't really an issue as is, but we should clarify the comments and add tests
