### ISSUE TITLE
psql: too many connections when syncing

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#6661]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): master

**ABCI app** (name for built-in, URL for self-written if it's publicly available): cosmos-sdk

**What happened**:
I am using a postgres instance from digital ocean. When i begin syncing a node in order to index all events, its quickly opens 50 connections and is unable to write new events to the db. 

**What you expected to happen**:

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
```
git clone gaia then checkout marko/master

git clone cosmos-sdk checkout marko/master

git clone tendermint
modify the config.toml to use psql

then get genesis and start the node
https://github.com/cosmos/mainnet

```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
3:27PM ERR failed to index block err="pq: remaining connection slots are reserved for non-replication superuser connections" height=5250002 module=txindex
3:27PM ERR failed to index block txs err="pq: remaining connection slots are reserved for non-replication superuser connections" height=5250002 module=txindex
```

The below photo illustrates the difference between using digital oceans connection pool vs not doing so. When I turn off the connection pool, it immediately spikes close 50 connections and the above logs begin showing in the terminal of tendermint. 
<img width="1063" alt="Screenshot 2021-07-06 at 17 28 02" src="https://user-images.githubusercontent.com/24299864/124627595-36f9aa80-de6f-11eb-877e-36bf2033fdcd.png">

**Comment by JayT106** [comment]
guess the issue relate to 
https://github.com/JayT106/tendermint/commit/1a7df529f3fdf9f47c8245edba8898bbd2497bb4

Will set up an env to reproduce/verify it.
