### ISSUE TITLE
params: MaxTxBytes should be a global consensus param

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6667]
## Summary

`MaxTxBytes` is currently a local config subjective to individual nodes. It strikes me as inconsistent that a Tx that is too big for one node could be fine for another node and make it into a block. There may be other fields that are also better suited as a global consensus variable rather than a local one (such as some consensus timeouts)

Ref: https://github.com/tendermint/tendermint/issues/5905#issuecomment-763690176

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by williambanfield** [comment]
I believe we discussed this, but `MaxTxBytes` checked before admission to the mempool, is that correct?

If it is checked before a Tx is admitted to the mempool then what is it generally meant to do? Make sure a single transaction does not overwhelm the mempool?

**Comment by marbar3778** [comment]
> I believe we discussed this, but `MaxTxBytes` checked before admission to the mempool, is that correct?

correct 

> If it is checked before a Tx is admitted to the mempool then what is it generally meant to do? Make sure a single transaction does not overwhelm the mempool?

Correct. Since we do not make assumptions on how node operators operate, a high level of configuration was provided. 

I tend to agree with this reasoning. I think there isn't a large use case for having this on a per-node basis.

**Comment by marbar3778** [comment]
Was briefly thinking about this and is this parameter actually something we need? Its meant as more of a ddos prevention mechanism, but can we rely on the application to not allow large txs through checktx?

**Comment by alexanderbez** [comment]
I understand the intuition @cmwaters and my suspicion is that 99.9% of operators do not touch this configuration. Note, we already have `MaxBytes` in the consensus params, which caps the block size.

Note, @marbar3778 we check the config's `MaxTxBytes` _before_ we execute the application's `CheckTx`, having the application check it in `CheckTx` would add just a bit of overhead and don't address the UX issue I think.

I can't think of any good reasons really atm for keeping this configuration. However, there could be some cases where operators don't want to waste bandwidth on large txs?

**Comment by williambanfield** [comment]
I would be in favor of removing this parameter and choosing a fine default. In general, I think the [no knobs])https://github.com/mongodb/specifications#no-knobs) approach is a good one for cases like this. It's unlikely a user will know how to pick a good value and it makes running the software more confusing than it likely needs to be?

**Comment by cmwaters** [comment]
After thinking about it some more, I've sort of walked back on what was initially proposed. I guess I was coming from a position where having every individual node set their own max Tx bytes seemed inconsistent and generally unhelpful. The idea of making this a consensus param was thought of as more of a way to signal one consistent value across the network. But in order for this to be of any use we'd need to verify every tx in every proposed block which seems a bit over the top. 

I guess I'm fine with either leaving it as is or removing it completely and using `MaxBytes` as the ceiling on tx size

**Comment by alexanderbez** [comment]
I would either opt for removing it entirely or just keeping it as-is. @tessr or @marbar3778 are you familiar with any projects that rely on this?

**Comment by ValarDragon** [comment]
I prefer the approach that already exists. From Ethereum, I think its pretty clear that everyones life is harder if you artificially limit in consensus the number of bytes that can go into a tx, distinct from block size limits. We see many requests to increase it, and its held back zkrollups for instance.

In Osmosis, what we've done for gas already, is make a per-node configuration for limiting the gas wanted per tx. At the moment its in the source code(but not consensus), however we plan to make this in the app.config for the nodes as well. I think this is a good parameter to maintain until the mempool logic ships more needed improvements.
