### ISSUE TITLE
e2e: light client app query error

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6671]
## Problem Definition

There is a non deterministic failure in the **v0.34.x** branch where the light client returns an error when the `Block` RPC call is made. I'm unsure how this occurs as there doesn't seem to be any other errors in the logs.

Error message in e2e tests: 
```
--- FAIL: TestApp_Hash (0.00s)
    --- FAIL: TestApp_Hash/light01 (30.02s)
        app_test.go:53: 
            	Error Trace:	app_test.go:53
            	            				e2e_test.go:56
            	Error:      	Received unexpected error:
            	            	post failed: Post "http://127.0.0.1:5701": EOF
            	Test:       	TestApp_Hash/light01
FAIL
FAIL	github.com/tendermint/tendermint/test/e2e/tests	37.340s
FAIL
E[2021-07-06|02:32:03.495] exit status 1 
```

This was observed in `gen-group00-0011.toml`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
I also see this on **master**

**Comment by williambanfield** [comment]
Which test net did you observer this in?

**Comment by cmwaters** [comment]
This occurred in the nighties on `new/gen-group01-0023.toml`

**Comment by alexanderbez** [comment]
I would recommend logging the response headers and setting `Close = true` on the request.
