### ISSUE TITLE
Make the ABCI application aware of validator health/participation

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#668]
Feature request for consideration, from the Rocket Chat.

Short version:
It seems useful to let the ABCI app know the health of the validator set. For instance, a nice metric to have would be number of blocks "missed" (validator in validator set, but didn't vote), so that dead validators could be expired by the app.

There are some security implications by this, so would need careful consideration by the application.

Chat log:
srm 8:19 AM 
@pepesza good questions. Re: throughput limiting factors - yes, it is limit by the number of transitions/transactions (a transition is a new block though) and is correlated with the number of nodes due to quadratic growth of messages to transfer because of the gossip.
How can an abci app be notified about a dropped validator?

mdyring 10:39 AM
@srm yeah i don't think that is possible at the moment, but actually it would be an interesting metric for the app to have.. for instance, how many of the last blocks that a validator "missed" it could be passed in the the commit/endblock invocation
 srm 8:20 AM
How can an abci app be notified about a dropped validator?
then it could be left for the app to decide that after X missed blocks, a validator is dropped

srm 10:54 AM
Exactly. Especially seeing that an offline validator increases each nth round.

mdyring 11:01 AM
@adrian @bucky does the above make sense to you - i.e. should i open a GH issue?

adrian Admin Owner Cosmos 11:16 AM
@mdyring What do you mean by missed?
Also, if in doubt, always open a github issue, so that we can share the conversation with more people
🙂

mdyring 11:19 AM
@adrian "missed": validator is in validator set, but didn't participate (vote) on last X blocks
that leaves it up to the app to decide if some validators should be retired/expire after some threshold it decides

**Comment by srmo** [comment]
As I’ve said, I think this is important to have a consistent blocktime, otherwise dead validators will slow down the overall network.

**Comment by melekes** [comment]
Interesting proposal for the dead validators problem. I think we could send a validator set for the last block with the corresponding heights they are on, so an app can take some measures if some validator is too far behind. The other question is do we want to burden the app with such task or we can implement it on the TM side?

**Comment by srmo** [comment]
I would consider it a burden to the core and a treat for the app. You usually want to have control over the validator set in your app, in my understanding at least. Moving this to core seems to provoke all kinds of wishes on how to configure that behavior. In the end, the app has to decide on the validator set either way, doesn't it?

**Comment by mdyring** [comment]
I have a preference for @melekes more generic approach of providing the current height of each validator.. Then the number of missed blocks can be trivially calculated.

Even with a large number of validators (as envisioned for Cosmos), providing this information per block shouldn't be too expensive.

**Comment by srmo** [comment]
Agreed. Seems like clean, easy approach.

**Comment by ebuchman** [comment]
The plan is to add new fields to begin block
- bit array of validators that signed the last commit
- list of validator addresses for which byzantine behaviour was detected

Is that sufficient? 

See https://github.com/tendermint/tendermint/issues/338 and https://github.com/tendermint/tendermint/issues/569

**Comment by srmo** [comment]
This sounds like a good start. Did you leave out the „report height of validator“ on purpose?

**Comment by mdyring** [comment]
Whaaaaaaa... I'm 99.5% certain I left a comment earlier today, but now it's gone. Anyway:

Bit array is fine with me, if there is an easy way to map the Nth bit to a validator and thus track the heights inside the app instead. Personally, I'd prefer a list of <validator, height>. I guess you guys have already considered this and decided against the higher overhead, but IMHO it seems cleaner and more in line with the below.

List of validators with byzantine bahaviour: Sounds good, but should probably include some details on what kind of behaviour was observed, before it is useful for the app to take automated action on.

**Comment by ebuchman** [comment]
>  Did you leave out the „report height of validator“ on purpose?

What height?

> I'd prefer a list of <validator, height>.

Can you clarify what these heights are? We're suggesting every block includes a bit array for the validators that signed the last block (ie. in the LastCommit in the current block). The height for the current block is available in the BeginBlock header

>  Sounds good, but should probably include some details on what kind of behaviour was observed, before it is useful for the app to take automated action on

Yeh we thought about this too. I think for now it will just be about double signing until we want to build out more advanced byzantine detection.

**Comment by melekes** [comment]
so with bitarray application should be able to detect what validators are behind or dead. but how the application can detect how far behind a particular validator is (in order to make a decision to remove it, for example)? p.s. we have this info in blockchain/pool.

**Comment by mdyring** [comment]
@ebuchman for the list of <validator, height>, height is the last block that the validator signed.

The app would be able to derive this information itself using the bit array and some method of mapping Nth bit to a certain validator, but providing it upfront relieves the app of doing this.

Either way is fine by me, it should just be documented how to do the bit position -> validator mapping. ;-)

**Comment by srmo** [comment]
Yeah, would work too. 

>>    Did you leave out the „report height of validator“ on purpose?
> What height?

The thing mdyring mentioned, reporting the height of each validator. I was wondering if you considered it and found reasons to not do it.

**Comment by ebuchman** [comment]
Oh I see.  Well if the app has been getting the bitarray of validators for every block , it should keep track of "last block it signed". the reason to do that is its probably much less overhead for abci then sending a full list of the last heights for every validator every time - right ? 

As for order - good point. Validators have a canonical order but we need to make it clear how it works and easy for apps to follow! I'll work on that soon.

**Comment by srmo** [comment]
> much less overhead
sounds reasonable. But it will get a bit messy when you start considering rotating validator sets across the run-/lifetime of the chain.

**Comment by mdyring** [comment]
Mmm. There is also the case of static/hard-coded in configuration validator sets.

Maybe providing canonical info is more general purpose.. But then again if it is static the app won't care anyway and probably ignore the bit array. :-)

Either option looks good, I am not too worried about abci overhead since it would be roughly 32 bytes + varint for height + change per validator.

**Comment by srmo** [comment]
Yeah, well let's start with the easy bits and see where it takes us :)

**Comment by ebuchman** [comment]
This is now supported in ABCI: https://github.com/tendermint/abci/blob/master/types/types.proto#L69

Just needs to be included from Tendermint side
