### ISSUE TITLE
Core doesnt recover when ABCI app restarts

### ISSUE THREAD

**Issue by trusch** [tendermint/tendermint#669]
BUG Report

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.10.4

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Should be with every abci app

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): debian stretch
- **Install tools**: go get
- **Others**:

**What happened**:
When I stop the ABCI app tendermint core shows this error and hang until (manual) restart:
```
E[09-21|13:11:03.262] Stopping abci.socketClient for error: EOF    module=abci-client connection=consensus
E[09-21|13:11:03.262] Stopping abci.socketClient for error: EOF    module=abci-client connection=query
E[09-21|13:11:03.262] Stopping abci.socketClient for error: EOF    module=abci-client connection=mempool
```

**What you expected to happen**:
Tendermint Core should die gracefully so that systemd or something can handle the restart

**How to reproduce it** (as minimally and precisely as possible):
start core, start abci app, Ctrl-C the abci app.

**Anything else do we need to know**:
I think this should be enough :)

**Comment by zramsay** [comment]
thanks for the bug report @trusch; this is known behaviour and is tracked in this issue: #243
see also #257 and #259 - the work was started to fix this issue.

**Comment by trusch** [comment]
Thank you @zramsay! I did not find this. From my point of view a simple os.Exit(1) at the right place would be enough, but OK, I understand the problems of doing this right are much more complicated :)
