### ISSUE TITLE
statesync: late messages after reverse sync causes peer errors

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6691]
## Summary

In the e2e testnets, I've noticed the following error:
```
validator04    | 2021-07-09T12:09:06Z INFO successfully completed backfill process endHeight=4 module=statesync
...
validator04    | 2021-07-09T12:09:07Z ERROR error processing light block response err="unsolicited light block response" module=statesync
```

It looks like responses for request sent before reverse sync was finished are coming in after reverse sync is finished causing the node to error the peer. This is causing the node to drop a peer which didn't really do no wrong

## Proposal

I'm still not sure how this is happening because the case for late messages has been programmed into the algorithm so ideally we find out where exactly this is happening and prevent that error from occurring in the first place or we just change the code so that that particular error doesn't cause the peer connection to be dropped

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Note that this has been partially resolved here: https://github.com/tendermint/tendermint/pull/6687 where unsolicited light block responses will not be punished

**Comment by alexanderbez** [comment]
Looks like we still need to find the root cause, right @cmwaters?

**Comment by cmwaters** [comment]
Yup
