### ISSUE TITLE
statesync: statesync metrics in SyncInfo 

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#6693]
## Summary

add some metrics for statesync in `SyncInfo` RPC call

## Problem Definition

https://github.com/tendermint/tendermint/pull/6620#pullrequestreview-696100403

## Proposal

Which metrics we would like to see?
- the `TotalStateSyncTime`
- the `RemainingStateSyncTime` or the `StateSync stage(or status)` ?
   there are 2 major parts in the state-sync: 1. sync snapshot 2. backfill

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
> there are 2 major parts in the state-sync: 1. sync snapshot 2. backfill

You could also argue that there be three parts:
1. Discovering Snapshots
2. Fetching and Loading Chunks
3. Backfilling blocks

Possible candidates for metrics for me would therefore be:
- `amount of snapshots discovered`
- `chunk progress i.e. 5/20 chunks` 
- `backfill progress i.e. 40/100 light blocks` (NOTE: that the denominator here would be an estimate)

I'm not sure what granularity of information we would want to provide. I also think trying to calculate `RemainingStateSyncTime` might be quite difficult

**Comment by JayT106** [comment]
@alexanderbez would it be okay to assign this issue to me? In case I forgot to implement it. Thanks!

**Comment by alexanderbez** [comment]
Yes, please and thank you @JayT106 :)
