### ISSUE TITLE
fix markdown link check non-429 errors

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#6695]
This list was generated from the [check markdown link action](https://github.com/tendermint/tendermint/actions/runs/1021230798). I downloaded the results and filtered out the github 429s.

```
grep -v 'github.com.*Status: 429' link_audit 2>&1 | grep -E 'Status: ' 2>&1
[✖] ./indexing-transactions.md → Status: 400
[✖] ../app-dev/app-development.md → Status: 400
[✖] https://wiki.parity.io/Warp-Sync-Snapshot-Format.html → Status: 404
[✖] https://github.com/tendermint/spec/blob/master/rfc/004-abci%2B%2B.md → Status: 404
[✖] https://docs.tendermint.com/master/spec/consensus/fork-accountability.html → Status: 404
[✖] (https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/accountability.md) → Status: 400
[✖] ./adr-056-light-client-amnesia-attacks → Status: 400
[✖] https://docs.tendermint.com/master/spec/consensus/light-client.html → Status: 404
[✖] ../nodes/logging#list-of-modules → Status: 400
[✖] ../tools/debugging.md → Status: 400
[✖] https://cosmos.network/intro/hub → Status: 404
[✖] ../app-dev/app-development.md → Status: 400
[✖] ./rpc.md → Status: 400
[✖] https://github.com/tendermint/tendermint/blob/master/p2p/README.md → Status: 404
```

**Comment by marbar3778** [comment]
Some of the above links work but show up as 400 or 404, like: 
https://github.com/tendermint/spec/blob/master/rfc/004-abci%2B%2B.md
https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/accountability.md

**Comment by williambanfield** [comment]
@marbar3778 the light client accountability seems to be 404'ing because the markdown link contains the paired parenthesis. 
https://github.com/tendermint/tendermint/blame/822893615564cb20b002dd5cf3b42b8d364cb7d9/docs/architecture/adr-047-handling-evidence-from-light-client.md#L182

**Comment by marbar3778** [comment]
fixed, thanks for the pointer
