### ISSUE TITLE
Tracking issue for upstreaming improvements from the LINE fork

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#6697]
The LINE devs are trying to be innovative in their branch. 

They seems to have some improvements that are worth upstreaming.

### Worth Upstreaming

https://github.com/line/ostracon/pull/264

https://github.com/line/ostracon/pull/273

### Consider Upstreaming

https://github.com/line/ostracon/pull/200

### Concurrency changes

They have made changes to the concurrency behavior that have semantic implications.

1. Concurrent checktx/recheck tx would require a hard requirement that CheckTx be stateless or implement locking behavior instead of the current recommendation for statelessness. 

2. Concurrent DeliverTx is unsafe without access lists.

**Comment by alexanderbez** [comment]
@tychoish you've made changes that are in context re https://github.com/line/ostracon/pull/264.

The WAL PR looks harmless. I'll port that.

**Comment by tychoish** [comment]
I think https://github.com/line/ostracon/pull/264 starts from before my change to this function, and I think my version has more linear scaling properties (e.g. my approach to this calls `Data.Size()` n times, with a single transaction in the `Data` object and their patch, adds all transactions to a single `Data` instance and calls `Size` on the one instance n times, which means that you have to evaluate size n squared times, so I think I'd stay with our version.
