### ISSUE TITLE
light: add new providers without needing to re-instantiate

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6702]
## Summary

There's an incongruence between the light client model and state sync model. The light clients "peers" are static. It never adds any more once it is instantiated, however the statesync continues to add peers throughout it's lifespan.

## Problem Definition

The problem is that when a node starts, it instantiates the state provider with all the peers it has which is usually a low number because it's just started this increases the reliance on a few providers. If they fail or are slow then statesync fails.

## Proposal

Light clients should be able to add new peers without having to reinstantiate the instance. This can then be used by state sync to continually add peers if needed

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
Didn't we have discussions to avoid using the light client altogether and rely solely on p2p?

**Comment by cmwaters** [comment]
Using p2p will still use the light client. The light client should be seen as more the verification method whereas p2p and rpc are the means with which the necessary information to verify is acquired

**Comment by cmwaters** [comment]
Closing because of: https://github.com/tendermint/tendermint/pull/6733
