### ISSUE TITLE
Large genesis makes node crash

### ISSUE THREAD

**Issue by RiccardoM** [tendermint/tendermint#6706]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
`v0.34.11`

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Cosmos SDK `v0.42.7`

**What happened**:
Querying a large genesis file (~ 60 MB) makes the node crash with the following error: 
```
failed to read response body: http: unexpected EOF reading trailer
```

**What you expected to happen**:
The genesis is returned properly. 

**Anything else we need to know**:
The node outputs 
```
ERR failed to write responses err="write tcp 65.21.152.138:26657->185.23.87.234:42626: i/o timeout" module=rpc-server res=[
```
Then it prints the whole genesis file and halts.

**Comment by cmwaters** [comment]
Thanks for writing up the issue. @marbar3778 also reported a similar issue (#6354) when trying to query a large genesis. We decided to resolve this by introducing a new rpc endpoint which chunks the genesis (#6445). This will be introduced in v0.35.

**Comment by RiccardoM** [comment]
@cmwaters Thanks. Is it possible to backport this to the `v0.34.x` series?

**Comment by cmwaters** [comment]
Yup we can try look into doing that
