### ISSUE TITLE
Get a list of peers a node is connected to

### ISSUE THREAD

**Issue by shravanshetty1** [tendermint/tendermint#6716]
## Summary

Would like someway to get a list of a peers a node is connected to - address book

## Problem Definition

Currently abci application clients have no way of discovering new nodes automatically. They usually just connect to one node hardcoded in the application. Would like to have a way in which clients can get a list of peers from a node, this way client can connect to multiple nodes and easily switch between nodes once its part of the network.

Current workaround could be to use the peer filter functions to get a list of peers, and making an endpoint in the abci application level. However there is no way to know if a peer has been dropped, it only shows peers that are being added to the address book.

## Proposal

A tendermint rpc endpoint would be sufficient which just returns the contents of address book along with metadata.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Hey, tendermint nodes do connect to more peers than which are in the config.tom. This is part of the PEX (peer exchange). As for a rpc endpoint, you can use net info https://docs.tendermint.com/master/rpc/#/Info/net_info. The provides you with address book information.

**Comment by shravanshetty1** [comment]
@marbar3778 Thank you, this works for my usecase. None of the https://rpc.cosmos.network/net_info peers accept http requests since they are private. I could add a peer filter func in my application to filter nodes that dont accept ping requests proving they are private.
