### ISSUE TITLE
grpc: deprecate grpc in the rpc layer

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#6718]
## Summary

Tendermint supports both grpc and jsonRPC at the rpc layer. The gRPC part is less known and only supports tx submission. Should we mark it as deprecated in 0.35 and remove it in 0.36 in order to converge on a single supported RPC standard?

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
ACK
