### ISSUE TITLE
Tendermint emits events over WebSocket faster than any clients can pull them if tx includes many events

### ISSUE THREAD

**Issue by romac** [tendermint/tendermint#6729]
**Tendermint version**: 0.34.9 (Gaia v4.2.1)

**ABCI app**: N/A

**Environment**:
- **OS**: macOS 11.4 x86-64 (first noticed on a Linux machine)
- **Install tools**:
  - http://rustup.rs
  - https://github.com/websockets/wscat
- **Others**:

**What happened**:

When a tx includes more than 100 events, Tendermint will emit these events faster than any WebSocket client can pull them, and will end up closing the WebSocket connection.

The culprit seems to be the combination of
a) the outgoing channel having a fixed capacity ([100 as of now](https://github.com/tendermint/tendermint/blob/4f885209aae4428923eff7922a41e0f98dbcff8b/rpc/core/events.go#L16))
b) events being sent through the outgoing channel in a tight loop (I didn't check but would assume that's what happens)

Together this means that when there is a burst of more than 100 events being emitted at once,
there's little chance for the WebSocket client to pull them fast enough, which fills the outgoing
channel and ends up closing the subscription.

On my machine, Hermes/wscat/Firefox typically manage to pull ~15-30 events before the subscription is closed.

**What you expected to happen**:

Tendermint emits events at a reasonable rate which lets WebSocket clients pull all the events emitted by a tx in time.

I can think of a few potential solutions:
a) increase the size of the event buffer, but that's not be very reliable as the problem would persist if a tx emits more events at once than the buffer can hold
b) rate-limit the emission of events (perhaps in batches) to give a chance to the client to pull them in time, the downside is that this might introduce too much latency, and it's not clear what the proper rate-limiting factor should be
c) use an unbounded/large buffer and wait until the next block is committed before checking if there are any leftovers events and only then close the subscription

**Have you tried the latest version**: No, but the issue is likely still be present, as the buffer size has stayed the same (100).

**How to reproduce it** (as minimally and precisely as possible):

(Sorry I don't know a better or standalone way of getting Tendermint to emit 100+ events at once)

1. Setup the Rust toolchain: https://rustup.rs
2. Download the `ft_transfer_config.toml` configuration file for Hermes: https://gist.github.com/romac/3d82e5df9ea0031ceded2f9ee1a22abd
3. Clone the ibc-rs repository

    ```
    $ git clone https://github.com/informalsystems/ibc-rs
    $ cd ibc-rs
    ```

3. Check out the `anca/dex_rpc_event` branch, which includes a script to spawn two Gaia chains with `timeout_commit` and `timeout_propose` set to 10 seconds in order to allow for 100+ txs to be included in a single block (this is required to exhibit the problem):

    ```
    $ git checkout anca/dex_rpc_event
    ```

4. Build Hermes

    ```
    $ cargo build
    ```

5. Spawn two Gaia chains and import the keys into Hermes:

    ```
    $ ./scripts/dev-env /path/to/ft_transfer_config.toml ibc-0 ibc-1
    ```

5. Create a channel (and associated connection and clients) between the two chains

    ```
    $ cargo run -- -c path/to/ft_transfer_config.toml create channel ibc-0 ibc-1 --port-a transfer --port-b transfer
    ```

6. Install `wscat`: (alternatively, use the JavaScript WebSocket client from a browser, see below)

    ```
    $ npm install -g wscat
    ```

7. Subscribe to `Tx` events from `ibc-0` over WebSocket

    ```
    $ wscat -c ws://127.0.0.1:26657/websocket
    Connected (press CTRL+C to quit)
    > { "jsonrpc": "2.0", "method": "subscribe", "id": 0, "params": { "query": "tm.event='Tx'" } }
    < {
      "jsonrpc": "2.0",
      "id": 0,
      "result": {}
    }
    ```

8. In another terminal, from the `ibc-rs` folder, send 150 packets from `ibc-1` to `ibc-0`:

    ```
    $ cargo run -- -c path/to/ft_transfer_config.toml tx raw ft-transfer ibc-1 ibc-0 transfer channel-0 9999 -o 1000 -n 150 -k user2
    ```

9. Check the output of the `wscat` process, notice it likely printed a few events and ended up with:

  ```json
  < {
    "jsonrpc": "2.0",
    "id": 0,
    "error": {
      "code": -32000,
      "message": "Server error",
      "data": "subscription was cancelled (reason: client is not pulling messages fast enough)"
    }
  }
  ```

> ***Subscribe to the WS events with a web browser instead of `wscat`***:
> Open the Chrome/Firefox/Safari dev tools, go the the Console and type the following:
> ```javascript
> var ws = new WebSocket('ws://127.0.0.1:26657/websocket');
> ws.onmessage = function(event) { console.log(event); };
> ws.send('{ "jsonrpc": "2.0", "method": "subscribe", "id": 0, "params": { "query": "tm.event=\'Tx\'" } }')
> ```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**: N/A

**Node command runtime flags**: N/A

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**: N/A

**Anything else we need to know**: N/A

**Comment by alexanderbez** [comment]
Thanks for posting this issue @romac. Perhaps we simply increase the buffer for now. If you consider the case where every tx has multiple messages and both BeginBlock and EndBlock emit a relatively significant amount of events, you'd still be looking at only a few hundred at most, right? We could also consider not having a buffered channel at all.

**Comment by thanethomson** [comment]
Would it not perhaps make sense to make this parameter configurable? It seems like a tuning parameter to me.

**Comment by alexanderbez** [comment]
Yes, good idea @thanethomson. Perhaps via the API of creating a websocket subscription?

**Comment by thanethomson** [comment]
> Yes, good idea @thanethomson. Perhaps via the API of creating a websocket subscription?

Not sure where the best place is to configure it in the server API, but I'd imagine we'd want a configuration parameter in the `[rpc]` section of the Tendermint `config.toml` file that we can configure.
