### ISSUE TITLE
Postgresql as backing store

### ISSUE THREAD

**Issue by sandys** [tendermint/tendermint#674]
we've been reading the Merkle data stores proposal (https://github.com/tendermint/tendermint/blob/9af837c24d2223bc98c2859dcebcb2398a2c35c2/docs/architecture/merkle-frey.md) and are very interested in the possibility of using postgresql. 

The note basically admits that postgresql has all the features that tendermint needs , but that it may be "overkill". That is a flawed viewing of real life production environments, especially when it comes to blockchain.

basically, the key advantage of postgresql being commercially supported through AWS/Google/Azure is a critical differentiator. LevelDB, while good, does not come with that kind of devops support today.

It basically enables the setup of a robust blockchain infrastructure from day 1 through to infinity. Given that postgresql is super seamless on osx (https://postgresapp.com/) , windows and obviously *nix - it has the full compatibility needed to run it on any node.

In addition, Postgresql is well on its way to handle even larger workloads (big data scale) with its Postgres 10 release - https://wiki.postgresql.org/wiki/New_in_postgres_10#Big_Data . In addition, the data audit mechanisms enable for deep forensics if something goes wrong (as has been the case with blockchains in the past) - https://blog.2ndquadrant.com/traceable-commit-postgresql-10/.

One last thing that the proposal also missed out - postgresql has a native type called JSONB which works as a key value datastore. It means that the amount of code that tendermint has to rewrite for dual support (leveldb and postgresql) will be minimal.

Is this something that tendermint team will be interested in implementing ?

**Comment by AFDudley** [comment]
Do you have a use-case in mind?

**Comment by sandys** [comment]
@AFDudley im kind of talking about the backing store for the data. The case, I'm trying to make is that postgresql allows me to use highly resilient, commercially available and managed databases to run my blockchain. 
Leveldb is nice - but for commercial applications, it will be a huge pain to run devops to manage leveldb. OTOH postgresql can scale nearly infinitely and be supported on infrastructure like AWS Relational Database Service or Google Cloud SQL.

The proposal already qualifies Postgresql to be good enough for tendermint (even without using jsonb... which will make this even better). So I'm looking forward to Tendermint being able to run on Postgresql and bring in resilience and low maintainence for free.

**Comment by AFDudley** [comment]
@ecmendenhall, you might find this interesting.

**Comment by sandys** [comment]
based on rocket.chat discussion, just one clarification - when we talk about scale in context of postgresql for the purpose of tendermint, I am NOT talking about distributed scale. I'm referring to postgres' ability to scale up beautifully on a single node.

AWS has commercially available db.r3.8xlarge 244GB single node postgresql machines on RDS. In addition, their x1.32xlarge machines support postgresql upto 3.9 TB of RAM and 128vcpu.

This allows for each blockchain node able to scale up seamlessly without fighting over managing leveldb

**Comment by melekes** [comment]
> LevelDB, while good, does not come with that kind of devops support today.

hm.. I am a fan of Postgresql, but the trick with LevelDB is that it is **embeddable** KV store, so in the best case you **don't need a devops for it** (assuming it stays within some size X).

**Comment by sandys** [comment]
Hi Anton,
That is unfortunately something that really doesn't happen.

See Bitcoin moved from BDB to Leveldb, because it was becoming unmanageable
- Coinbase Toshi bitcoin node is postgresql.

I think all blockchain projects start off with a genuine desire to keep
things simple. Yet, we are in a world where the Monero size is 25gb+ and
Bitcoin has a political split over computing resources.

While building blockchains, you now have to worry about how you will deal
with 30-40 GB of data pretty soon. And then it will be too late to fix.

Secondly, it's not going to be hard supporting both Leveldb and postgres
(esp given postgresql JSONB type). In one shot you have created something
that has built in capability to scale.

**Comment by ethanfrey** [comment]
I like postgresql very much. And personally  it is the only alternative data store I would port our Merkle tree too.

One issue is latency. Postgres has amazing throughput for concurrent queries. When all TX must be executed sequentially, and we target 1-2 ms processing time for the TX, including signature verification, in order to get a blockchain throughput of 300-500 tx/sec.

I think the overhead of a query or insert on postgres is often around 1ms, which is very fast, but too slow for this use case.

It would be interesting to support it for projects with more complex query needs but lower throughput requirements

**Comment by ethanfrey** [comment]
But maybe we should just support multiple stores and allow each developer to pick the store the fits their chains use case best... I will bring this up with others working on storage layer.

BTW, thank you for reading that doc. It is rather old now, and I would change some details, but I hadn't had much feedback before

**Comment by sandys** [comment]
@ethanfrey - here we are in the territory of mongodb vs postgresql. The key difference in the slight amount of latency is because of ACID. the reason that monero chose [LMDB](https://monero.stackexchange.com/questions/702/why-did-monero-choose-lmdb-over-alternative-database-types/704) over leveldb was because they valued ACID over latency.

Which is why im requesting for the dual support model. There would be some usecases for which ACID is not important. After looking at some of the failures of blockchains over the past few years, I'm of the opinion that ACID matters a lot in other usecases.  Dual support of postgresql and leveldb will make everyone happy at a small incremental cost of maintenance.

here's a comment by achow101 of Bitcoin Core - https://bitcointalk.org/index.php?topic=1394020.msg14159449#msg14159449

> LevelDB being stupid is one of the major reasons that people have to reindex on Bitcoin Core crashes. There have been proposals to replace it but so far there are no plans on doing so. However people are working on using different databases in Bitcoin Core and those are being implemented and tested.

**Comment by sandys** [comment]
in addition, there are these recent discussions of "breaking Bitcoin" which are focused towards breaking leveldb . I'm not an expert, but from what I have read, this is the basis of "UTXO spam attack bug"

https://www.reddit.com/r/Bitcoin/comments/6z776p/breaking_bitcoin_day_2_livestream/dmwxrm6/

> What doesn't help this is LevelDB's transaction format: when you update the utxo set, you want to do this atomically (otherwise you may end up with a corrupted state). To do so, you start a DB transaction (do not confuse this with Bitcoin tx, this is just how you build a change set before pushing it to disk), update the change set then commit the tx. With LevelDB, as long as the transaction is live, the entire changeset will remain in RAM (usually a DB engine writes the changes on disk as you provide them, then updates internal pointers at commit time to apply the change), basically double dipping on the RAM hogging and I/O inefficiency.

**Comment by AFDudley** [comment]
> I think the overhead of a query or insert on postgres is often around 1ms, which is very fast, but too slow for this use case.

I think postgres insert times can be optimized, it goes without saying that query times and be optimized with indexes, etc etc.

**Comment by sandys** [comment]
I was trying to make a point that even at 1ms, it is not slow for
tendermint's usecase. Because we are now in "Mongodb is much faster than
postgresql" territory. It's a trade-off between ACID guarantees which are a
much bigger architectural need than a few milliseconds of performance.

Postgresql is about 100x slower than leveldb. Today the ecosystem of the
tools around any blockchain is already on postgresql. There are tons of
tools where people pull data from leveldb,etc into postgresql and actually
so analyses there.

I'm merely suggesting to have first class support for both. Given that
postgresql has a key value data store in jsonb, I do not estimate it will
be a substantial difference.

Regards
Sandeep

On 21-Nov-2017 23:17, "A. F. Dudley" <notifications@github.com> wrote:

I think the overhead of a query or insert on postgres is often around 1ms,
which is very fast, but too slow for this use case.

I think postgres insert times can be optimized, it goes without saying that
query times and be optimized with indexes, etc etc.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tendermint/tendermint/issues/674#issuecomment-346105781>,
or mute the thread

**Comment by AFDudley** [comment]
Yeah, I agree with all of that. Postgres hackers are hard-to-find/expensive but it seems like we should get significantly better performance with this:
https://github.com/greenplum-db/gpdb/blob/master/src/backend/access/appendonly/README

**Comment by sandys** [comment]
Postgresql has managed solutions like Amazon RDS, Google cloud SQL , azure
postgresql and heroku that makes this unnecessary.

The high performance hosted version of postgresql is Citus Cloud. These are
all production ready and already used by millions of users and some of the
biggest companies in the world.

Leveldb is fully manage-your-own. While for a certain set of users, it's
worth the trade-off...I would argue for a truly democratic setup, you
should reduce the effort it takes to scale up gradually.

For those who need extremely high performance , Citus or a postgresql
fronted by a Kafka queue is the accepted solution  - also in production
everywhere.

**Comment by ebuchman** [comment]
Thanks for good discussion. Let's refocus it in: https://github.com/tendermint/tendermint/issues/1161
