### ISSUE TITLE
statesync/indexer: be able to query the historical transaction/block events

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#6758]
## Summary

Allows the client to query the historical transaction/block events even the blockchain node starts with the statesync

## Problem Definition

The statesync provides a good solution for starting the blockchain service without sync whole network data from scratch. In the production networks, it could take few hours even days to catch the current network height and to start the transaction processing or to join the blockchain consensus. However, due to missing the full block sync, the indexer won't have the events of the historical txs/blocks before the statesync block height(inclusive). So we are not able to query the historical events from the indexer.

To support this feature, it might let the current sync mechanism more complicated.

ref: https://github.com/tharsis/ethermint/issues/211

## Proposal

There are some options to achieve this:

1. similar to the current Reverse-Sync implementation https://github.com/tendermint/spec/blob/master/rfc/005-reverse-sync.md, to be able to grab the `block.txs` `state.ABCIResponses` from the trust peers and run an indexer to index the events.
2. the reverse-sync needs to be able to back grab data to a designated block height. 
3. the process will be started once the consensus reactor has called `SwitchToConsensus` and will be stopped after synced to the designated block height. 

Note: is there any way we can verify the correctness of the ABCIResponses? So we can grab data from the other peers.

2. A new p2p protocol to support send the query to the trusted peers, and then return the result from the peer. This option might have some issues that need to be conquered :
- the peer connection resource constraint or attack prevention
- the current query schema constraint
- know the trusted peer has the indexer service support from which block height (the peer might also start with the statesync at some point).

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
To be honest, and what I always tell people, is if you want to index the entire chain then you should run your application from genesis. Yes, I know this would take days or even weeks, but generally it's just the cleanest approach. If you want all the data indexed, then don't use or rely on state-sync.

Yes, of course we could even further expand the state-sync protocol, but I wonder if the additional complexity will be worth it. Thoughts @cmwaters?

**Comment by cmwaters** [comment]
When writing up the initial RFC for reverse sync, it was planned to be able to fetch all block data right back to genesis. But the scope was gradually cut down to retrieving the necessary data for evidence handling. A large reason for that was that nodes could just start a full node from genesis if they really wanted to become an archive node.

I wonder however if there becomes a point where the chain is so large that it makes it worth it to be able to simply fetch the last 6 months worth of data then having to fetch all 5 years of it. I think at the moment we are probably still far from it. If we wanted to do that, I think an alternative and perhaps simpler approach than to extend the reverse sync protocol, would be to fetch a snapshot from 6 months ago and then sync from there. 

> is there any way we can verify the correctness of the ABCIResponses? 

Yup this can be done so long as you have the header at the next height verified. Then it's just a matter of comparing the hash of `ABCIResponses` with `LastResultsHash`

**Comment by alexanderbez** [comment]
> If we wanted to do that, I think an alternative and perhaps simpler approach than to extend the reverse sync protocol, would be to fetch a snapshot from 6 months ago and then sync from there.

ACK. If it doesn't add much complexity, I would say this is currently a "nice-to-have".

**Comment by JayT106** [comment]
> I wonder however if there becomes a point where the chain is so large that it makes it worth it to be able to simply fetch the last 6 months worth of data then having to fetch all 5 years of it. I think at the moment we are probably still far from it. If we wanted to do that, I think an alternative and perhaps simpler approach than to extend the reverse sync protocol, would be to fetch a snapshot from 6 months ago and then sync from there.

@yihuang, What do you think?

**Comment by yihuang** [comment]
> > I wonder however if there becomes a point where the chain is so large that it makes it worth it to be able to simply fetch the last 6 months worth of data then having to fetch all 5 years of it. I think at the moment we are probably still far from it. If we wanted to do that, I think an alternative and perhaps simpler approach than to extend the reverse sync protocol, would be to fetch a snapshot from 6 months ago and then sync from there.
> 
> @yihuang, What do you think?

Yeah, I think it's a "nice-to-have" too, not a blocker for us right now, it's just as the chain grows bigger and bigger, it'll be nicer and nicer to have ;D
The main UX difference with this feature is syncing in the background, one can setup a node and provide chain state very quickly, while gradually recover the ability to query historical transaction states. Definitely very useful, especially when chain grows larger.

**Comment by JayT106** [comment]
Right, so my proposal is a faster consensus switch, and the backend process the historical data later. It needs another reactor to deal with it (but can be shut down when finishing the data sync).

@cmwaters 's option is doing a snapshot at a certain point, then sync block here, and then start the consensus later(it might still take a while to start the consensus). And it's easier to implement it due to extend the currently existing sync reactor.

**Comment by cmwaters** [comment]
I agree that this becomes nicer to have as chains grow bigger and bigger which will certainly be the case with soft upgrades. I would still hold out on doing any major work for at least another year as there's definitely a few workarounds that people can do to get more historical data.

When it comes to the actual implementation, from my assessment, we would want to house this backend process within the blocksync (formerly known as blockchain) reactor as this already is used for gossiping blocks and does the exact process but going forwards rather than backwards. It also makes sense to use the existing `RetainHeight` within the `EndBlock` to communicate how far back to do this process. `RetainHeight` is also used for pruning so this will avoid contention between fetching historical data and pruning it. The only message we might need to add is the gossiping of ABCI responses (which contains the events from each block) unless we wanted to execute the historical blocks against the application (which I'd be hesitant on doing).
