### ISSUE TITLE
TestByzantinePrevoteEquivocation timeout

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#6769]
Logs linked [here](https://gist.github.com/williambanfield/6f89bccf3538ee4c177b30dcceaa10f8).

**Comment by thanethomson** [comment]
@williambanfield any hints on how to reproduce this locally? I just ran it 1000 times in a loop and not a single failure.

**Comment by creachadair** [comment]
I'm not aware that we have ever figured out a reliable repro for this. Anecdotally, it seems to fail aperiodically in CI, which makes me suspect side-effects of slow scheduling. Maybe bump up the `-cpu` a bunch? I'm not really sure.
