### ISSUE TITLE
statesync: syncing a second time

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6774]
## Summary

If a node has state sync enabled and crashes (or the operator just wants to restart the node), the node will try to state sync again. If there's only been hundred blocks in the interim, it would be far better just to block sync. Worse than that, the block/state store will have this gap in blocks (i.e. it will have blocks 100 - 200 and form 300 onwards) which could lead to some undesirable consequences. I have a feeling that re state-syncing is underspecified at the moment. I propose that until we can think of more nuanced designs, that state sync can only happen once. Therefore if there is already an existing state that is not the initial state we should not run the state sync process (this is currently not the case). 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by alexanderbez** [comment]
> Therefore if there is already an existing state that is not the initial state we should not run the state sync process (this is currently not the case).

How would the implementation look like? Would the `Node` check if existing state exists, and if so not run state sync? How do we know it's the "initial" state and what does that mean?

**Comment by cmwaters** [comment]
> Would the Node check if existing state exists

Exactly. The node would load state from the stateStore. If it doesn't exist (because this is the first time running the node), it would run state sync. If it did exist it would perform a handshake with the application and then start block sync / consensus from there.

**Comment by alexanderbez** [comment]
Yeah I think this is a reasonable thing to do for now 👍
