### ISSUE TITLE
Missing docker image on dockerhub for v0.11.0

### ISSUE THREAD

**Issue by trusch** [tendermint/tendermint#678]
FEATURE REQUEST

please build and push a v0.11.0 tag to dockerhub, so that it is possible to use the lastet tendermint version without complications. 

I'm currently developing an ABCI app and would like to provide a docker based setup to my users. Using the "official" tendermint/tendermint container image would be great.

**Comment by melekes** [comment]
https://store.docker.com/community/images/tendermint/tendermint

**Comment by melekes** [comment]
Sorry, we sometimes forgot to do that. Need to write a script for the whole release process, so such things never happen.
