### ISSUE TITLE
Possibility to punish proposer for invalid app state hash

### ISSUE THREAD

**Issue by pdobacz** [tendermint/tendermint#679]
**FEATURE REQUEST**

Following [discussion on rocket](https://cosmos.rocket.chat/channel/tendermint_core?msg=AYhgGDaLwbqaQzGKY):

Suppose the app state hash in a proposed block is different from the app state hash returned from the call to `ABCI.Commit`. The former is provided by the proposer, while latter is calculated locally by every validator. 

The proposer is deemed byzantine and that block will be rejected due to validation error. See [here](https://github.com/tendermint/tendermint/blob/develop/types/block.go#L80). As a result, it will cause the validator to [prevote nil](https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1035).

This prevents such block from being commited, assuming 2/3 honest validators, however it doesn't allow to punish the proposer within the ABCI app.

The idea is to somehow allow for such proposer to be punished.

**Comment by adrianbrink** [comment]
We are currently working on a slashing module in the [cosmos-sdk](https://github.com/cosmos/cosmos-sdk). Once that's implemented byzantine behaviour will be slashable.

**Comment by ebuchman** [comment]
Note the app hash from abci.Commit is included in the next block - so we should be able to check as soon as the proposal block is received if it is valid, and if not, just ignore it (ie. prevote nil). Do we really need to punish the proposer?

There are a number of byzantine cases that don't necessarily need to be punished since they can just be handled/ignored and can't lead to escalations (ie. safety or liveness violations). How do we decide which to punish? Should we seek to punish all detectable byzantine behaviour ?

**Comment by pdobacz** [comment]
Ah, I see your point.

> How do we decide which to punish?

Maybe this decision here should be based on whether byzantine behavior can be made profitable "opportunistically".

By "opportunistically" I mean that I act byzantine 100 times, and 99/100 there's no escalation nor benefit, but 1/100 there is, and since there's no penalty, this benefit becomes "free lunch". In such situations, one should punish every attempt.

Hmm... but in this particular case, to have benefit, the byzantine block must be voted for by 2/3+, so this cannot be done opportunistically (can it?).

**Comment by ebuchman** [comment]
Only if "delaying progress" can be considered opportunistic. In some cases, it probably can, but one can just as easily broadcast a valid but massive block that will likely timeout before being propagated ...

**Comment by pdobacz** [comment]
Gotcha,

I need to ponder this a while longer, but I think I'm convinced: it's not necessary. Feel free to close, if you think there's nothing left to cover, I'll reopen in case I come up with a concrete scenario, where it's required.

Thanks!

**Comment by ebuchman** [comment]
Ok!
