### ISSUE TITLE
`panic: unable to delete version X with Y active readers`

### ISSUE THREAD

**Issue by Freak12Techno** [tendermint/tendermint#6804]
I have the Osmosis node I use for monitoring and sometimes it crashes with the message like this:

```
panic: unable to delete version 171000 with 1 active readers
goroutine 160 [running]:
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).pruneStores(0xc00050cfa0)
    github.com/cosmos/cosmos-sdk@v0.42.9/store/rootmulti/store.go:388 +0x26e
github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).Commit(0xc00050cfa0, 0x29c34, 0x0, 0xc00d78e840, 0x1b0a197700121d0a)
    github.com/cosmos/cosmos-sdk@v0.42.9/store/rootmulti/store.go:362 +0x1c6
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Commit(0xc0000941a0, 0x0, 0x0, 0x0, 0x0)
    github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:305 +0x27c
github.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc000fb53e0, 0x0, 0x0, 0x0)
    github.com/tendermint/tendermint@v0.34.11/abci/client/local_client.go:258 +0xab
github.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0xc000503190, 0x0, 0x0, 0x10a346f)
    github.com/tendermint/tendermint@v0.34.11/proxy/app_conn.go:93 +0x33
github.com/tendermint/tendermint/state.(*BlockExecutor).Commit(0xc00e8a5ea0, 0xb, 0x1, 0xc00e989630, 0x7, 0xc00e989637, 0x9, 0x1, 0x29c34, 0xc013688580, ...)
    github.com/tendermint/tendermint@v0.34.11/state/execution.go:228 +0x244
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(0xc00e8a5ea0, 0xb, 0x1, 0xc00e989630, 0x7, 0xc00e989637, 0x9, 0x1, 0x29c34, 0xc013688580, ...)
    github.com/tendermint/tendermint@v0.34.11/state/execution.go:180 +0x725
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc00e996380, 0x0)
    github.com/tendermint/tendermint@v0.34.11/blockchain/v0/reactor.go:398 +0x1033
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
    github.com/tendermint/tendermint@v0.34.11/blockchain/v0/reactor.go:110 +0x8c
```

I assume it has something to do with my pruning, so here they are:
```
pruning-keep-recent = "50"
pruning-keep-every = "0"
pruning-interval = "10"
...
min-retain-blocks = 100
```

My concern here is that IMO even if the node is misconfigured (I think that may be my case) the node shouldn't crash if the blocks could not be pruned.

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
From the `osmosisd version --long` output:
```
- github.com/tendermint/tendermint@v0.34.11
- github.com/tendermint/tm-db@v0.6.4
```

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04.2
- **Install tools**:
- **Others**:

**What happened**: Node crashed, see the logs above
**What you expected to happen**: A warn message that block could not be pruned (probably error), not a panic and a node crash

**Have you tried the latest version**: no
**How to reproduce it** (as minimally and precisely as possible):

Set these pruning configs, then start the app. I also think that this may happen because I have a lot of scripts doing gRPC queries to the node.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: Posted them above
**Config (you can paste only the changes you've made)**: Posted them above
**node command runtime flags**: None
**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs** -
**Anything else we need to know**: -

**Comment by marbar3778** [comment]
@alexanderbez & likhita-809  this has overlap with https://github.com/cosmos/cosmos-sdk/issues/9570. 

The issue you mention is a cosmos-sdk issue. The reader is, most likely, state sync and you are pruning versions before you can take a snapshot. You would need to change the pruning settings to be a multiple of snapshot_interval.

**Comment by Freak12Techno** [comment]
@marbar3778  I agree, but should the node panic and crash in that case? For me it seems like this shouldn't cause the node crash, I've seen a ticket on tendermint on "don't panic" policy, that's why I've reported this.

**Comment by marbar3778** [comment]
agree, this panic should be caught by the application or just error out. If the application panics there is no way for tendermint to avoid panicking.

**Comment by Freak12Techno** [comment]
@marbar3778 can you clarify it it's tendermint or cosmos which panics?
If it's tendermint, imo instead it should log an error or something and just continue working, and therefore it should be fixed on tendermint side, if it's cosmos then it should be fixed there and we should either open another issue on that on cosmos-sdk or add this to the existing one.
I've seen tendermint in stacktrace, that's why I've reported here and not in cosmos-sdk.

**Comment by marbar3778** [comment]
the sdk is the one crashing here. The stack trace shows the entire path, but usually where it starts is the culprit. I had an issue here https://github.com/cosmos/cosmos-sdk/issues/9570 but then couldnt reproduce.

**Comment by serge1peshcoff** [comment]
okay, got it. let me know if I can be of any help on reproducing this.
My idea is that I have a bunch of scripts that do some heavy requests (such as all validators request) to both grpc and tendermint rpc node, maybe they are readers here?

**Comment by Freak12Techno** [comment]
okay, got it. let me know if I can be of any help on reproducing this.
My idea is that I have a bunch of scripts that do some heavy requests (such as all validators request) to both grpc and tendermint rpc node, maybe they are readers here?
