### ISSUE TITLE
Data synchronization function proposal

### ISSUE THREAD

**Issue by summerpro** [tendermint/tendermint#6805]
Hello, tendermint team, we are the development team from exchain, and we have implanted evm based on cosmos-sdk.
## Problem Definition
We hope to have such a node between the light node and the validator node, called the rpc node, which can provide a lot of query work and can have a lower hardware configuration.

We now have some full nodes with relatively low machine configuration, but often because they can’t keep up with the validator block generation speed, they can’t support query services normally.

## Proposal
It is possible to develop a dedicated synchronization mode, which only uses fast synchronization to interact with all nodes to synchronize the latest state changes to the local, without the need to execute blocks to generate states. Now although tendermint has a fast synchronization function, it only starts to execute when the block is too far behind. We hope that for the rpc node, the state synchronization mode can be turned on all the time.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Hey @summerpro. Thanks for reaching out!

Incidentally, a big chunk of our work at the moment is looking into improving the node initialization, structure and composability. We already have in mind an "archive" node (name pending) which entails something similar to what you describe. You can find the issue here https://github.com/tendermint/tendermint/issues/5615

**Comment by summerpro** [comment]
> Hey @summerpro. Thanks for reaching out!
> 
> Incidentally, a big chunk of our work at the moment is looking into improving the node initialization, structure and composability. We already have in mind an "archive" node (name pending) which entails something similar to what you describe. You can find the issue here #5615

thank you for your reply

**Comment by marbar3778** [comment]
Closing this in favor of #5615. If you, @summerpro have further comments, can you comment there?

**Comment by summerpro** [comment]
> Closing this in favor of #5615. If you, @summerpro have further comments, can you comment there?

ok

**Comment by chengzhinei** [comment]
@marbar3778

>There will be no application (ABCI) so verification of incoming data will have to be through the light client.

I have a question, how can we get the application state while having no ABCI? My understanding is that we get the state through DeliverTx.
Or, the BlockStore only store the block without the state？

> Closing this in favor of #5615. If you, @summerpro have further comments, can you comment there?

**Comment by marbar3778** [comment]
> I have a question, how can we get the application state while having no ABCI? My understanding is that we get the state through DeliverTx.
> Or, the BlockStore only store the block without the state？

you cant at the moment, in the other issue the design is still not final, including the application is also possible.
