### ISSUE TITLE
degradation in throughput over time

### ISSUE THREAD

**Issue by mrihn** [tendermint/tendermint#6808]
**Tendermint version** 
0.34.11

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
kvstore

**Environment**:
Ubuntu 20.04

**What happened**:
The throughput of a Tendermint node (or cluster of nodes) degrades significantly as more transactions are sent.
The maximum achievable transaction rate declines by 50% or more after a few hundred thousand transactions have been processed, and the degradation appears to continue even beyond that.

With the kvstore app running on a single Tendermint node, and a constant stream of broadcast_tx_commit transactions being sent to it for a period of several minutes, a certain transaction rate is achieved. The first couple of tests show similar transaction rates, but after many tests have been run, and a few hundred thousand transactions have processed, the transaction rate achieved is less than half of what was achieved with the initial tests. The performance continues to degrade with each successive test.

A similar degradation occurs with transactions being sent to a cluster of nodes, and the degradation occurred at a faster rate when the max-connections/max-subscription-clients were increased to allow for more transactions to be sent concurrently. This occurred on both amd64 and s390x platforms.

**What you expected to happen**:
Did not expect to see such a significant degradation in performance over a relatively short period of time. Is there a known issue that may be causing this drop in performance? Can anything be done to mitigate it?

**How to reproduce it** (as minimally and precisely as possible):

Start up Tendermint node with kvstore app:

tendermint init validator
tendermint start --proxy-app=kvstore --consensus.create-empty-blocks=false

In another terminal, use a script to generate as many broadcast_tx_commit with unique keys as the node can handle
ex:
curl -s 'localhost:26657/broadcast_tx_commit?tx="abcd"'

**Config (you can paste only the changes you've made)**:

(for some of the tests)
max-connections=128 (changed from 64)
max-subscription-clients = 200 (changed from 100)

**Comment by marbar3778** [comment]
Thanks for opening this issue. Do you happen to have data from your findings you can share?

Was the mempool full? 
Were blocks being filled?

**Comment by mrihn** [comment]
The blocks were still being filled. The mempool did not seem to be full. I was not seeing any messages about the mempool size when I was running with the default log-level. I tried running with log-level set to debug, and then I was seeing the mempool messages indicating that the num_txs was in the hundreds. I originally had the max number of transactions in the mempool set to the default of 5000, but increased it to 55000 to be safe. The transactions that I am sending are small (<100 bytes), and max-txs-bytes for the mempool is set to the default of 1 GB.

Is there a simpler way to check the mempool size, that doesn't involve setting the log-level to debug? The logs were way too large when I used this setting.

**Comment by tychoish** [comment]
In addition to profiling, I'd be interested in seeing (if you have collected it) a thread dump/stack trace of a running process that's acting slow. I believe there's a pprof endpoint that provides this but you can also send SIGABRT to a go process to get it to dump this dump.

**Comment by mrihn** [comment]
I have not done any profiling before, but I will take a look at the pprof tool and collect that additional data

**Comment by mrihn** [comment]
I did not figure out how to collect a stack trace with the pprof tool, but I did collect one with the perf command:

[perf.report.txt](https://github.com/tendermint/tendermint/files/6973037/perf.report.txt)

**Comment by mrihn** [comment]
I ran a pprof trace with a large workload running against a single node and saw a lot of leveldb compaction

![profile001](https://user-images.githubusercontent.com/88684821/130638584-77cc46d4-9db6-4aae-9487-a28b62d610d1.gif)

**Comment by tychoish** [comment]
The `/debug/pprof/trace` endpoint can probably give you some insight into the stacktrace, which may still be useful. 

The profile that you see isn't particularly surprising given the workload you describe. The more data you add to the system, the more data that leveldb has to compact, so this is (perhaps) expected and wouldn't necessarily slow down the rest of the system. The boxes that are the biggest (i.e. using the most CPU time) are also the kinds of operations that are necessarily more CPU intensive (e.g. compression and serialization,) so I'd expect to see those boxes large. We could try running similar  tests against a different database engine (i'd be curious to see how badger and boltdb worked for you, but this is mostly idle curiosity.) 

This kind of profile might obscure if we were spending a lot of time waiting on a channel or a mutex, or something similar, and there are a couple of resource leaks that I can imagine that might also explain the performance degradation, but I don't feel confident in any of those cases based on what I can see here. If you have a trivial reproduction that we could run that might be helpful in expediting things.

I'd be curious to see if: 
- you can send requests less frequently and get the performance to stabilize at, and if so what that transaction rate is?
- does this problem resolve (for a while?) once you restart either the client or the server? (e.g. does it appear after the data reaches a certain size, after a certain amount of total transaction nodes.
- is the slow down constant or does it continue to increase the more transaction/blocks are added to the node?

Thanks so much for your time and patience on this.

**Comment by mrihn** [comment]
The problem is not resolved by restarting the client, but it is resolved when I reset the node and remove the data (unsafe-reset-all).
The slow down appears to be relatively constant, at first, but the rate of degradation seems to tail off after a while, i.e. the transaction rate drops by smaller amounts with successive measurements.
If I submit transactions at a lower rate, it will take longer to get to the point where the performance starts to drop, but it will eventually happen. It seems to start after somewhere between 100k and 200k transactions have been submitted.

It should be fairly trivial to reproduce. As I mentioned in my initial comments, I start up a Tendermint node with the kvstore app, and use a single client to submit broadcast_tx_commit transactions continuously until a couple hundred thousand transactions have been submitted. At that point, the transaction rate starts to drop with successive measurements.
