### ISSUE TITLE
Tendermint- ABCI

### ISSUE THREAD

**Issue by devanshi318** [tendermint/tendermint#6815]
Hello, How can I configure ABCI in tendermint and what write in command in![Screenshot 2021-08-11 at 4 40 19 PM](https://user-images.githubusercontent.com/49709121/129019229-3a485db6-4786-4560-ae88-b92955929585.png) code!

abci0:
    container_name: abci0
    image: "abci-image"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: <insert command to run your abci application>
    networks:
      localnet:
        ipv4_address: 192.167.10.6

  abci1:
    container_name: abci1
    image: "abci-image"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: <insert command to run your abci application>
    networks:
      localnet:
        ipv4_address: 192.167.10.7

  abci2:
    container_name: abci2
    image: "abci-image"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: <insert command to run your abci application>
    networks:
      localnet:
        ipv4_address: 192.167.10.8

  abci3:
    container_name: abci3
    image: "abci-image"
    build:
      context: .
      dockerfile: abci.Dockerfile
    command: <insert command to run your abci application>
    networks:
      localnet:
        ipv4_address: 192.167.10.9

**Comment by marbar3778** [comment]
Hey, thanks for opening an issue. What sort of configuration are you talking about?

In the photo you show docker, this should work out of the box. Does it now?

**Comment by devanshi318** [comment]
I need to configure abci in tendermint. Just run four nodes using tendermint and now I want to add abci in the application. So I just followed the steps which were defined in the link (https://docs.tendermint.com/master/networks/docker-compose.html#configuring-abci-containers). But I don't know what to write "<insert command to run your abci application>" instead of this in abci0, abci1, abci2, abci3 command and also don't found about "abci.Dockerfile" file where kept. Please provide a solution as soon as possible

**Comment by devanshi318** [comment]
@marbar3778  Waiting for your answer!

**Comment by marbar3778** [comment]
do you have a link to some code? I cant see any issues, from the docs

**Comment by devanshi318** [comment]
The issue is solved but now getting new problem. I just start 4 nodes abci using tendermint and docker. Now I want to the transaction between 2 nodes.

-> "make localnet-start" command
response:

node1  | 2021-08-12T12:11:53Z INFO Dialing peer address={"id":"4174b7b75ef104a447ac016f48066a7f3e26a859","ip":"192.167.10.5","port":26656} module=p2p
node1  | 2021-08-12T12:11:53Z INFO starting service impl=MConn{192.167.10.5:26656} module=p2p peer={"Hostname":"192.167.10.5","NodeID":"4174b7b75ef104a447ac016f48066a7f3e26a859","Path":"","Port":26656,"Protocol":"mconn"} service=MConnection
node1  | 2021-08-12T12:11:53Z INFO starting service impl="Peer{mconn://192.167.10.5:26656 4174b7b75ef104a447ac016f48066a7f3e26a859 out}" module=p2p peer={"id":"4174b7b75ef104a447ac016f48066a7f3e26a859","ip":"192.167.10.5","port":26656} service=Peer
node1  | 2021-08-12T12:11:53Z INFO Added peer module=p2p peer={"Data":{},"Logger":{}}
node3  | 2021-08-12T12:11:53Z INFO starting service impl=MConn{192.167.10.3:45166} module=p2p peer={"Hostname":"192.167.10.3","NodeID":"85423d35bfbd046c12ddb4c3c30ca77c6765926e","Path":"","Port":45166,"Protocol":"mconn"} service=MConnection
node3  | 2021-08-12T12:11:53Z INFO starting service impl="Peer{mconn://192.167.10.3:45166 85423d35bfbd046c12ddb4c3c30ca77c6765926e in}" module=p2p peer={"id":"85423d35bfbd046c12ddb4c3c30ca77c6765926e","ip":"192.167.10.3","port":45166} service=Peer
node3  | 2021-08-12T12:11:53Z INFO Added peer module=p2p peer={"Data":{},"Logger":{}}
node0  | 2021-08-12T12:11:54Z INFO starting service impl=multiAppConn module=proxy service=multiAppConn
node0  | 2021-08-12T12:11:54Z INFO starting service connection=query impl=socketClient module=abci-client service=socketClient
node1  | 2021-08-12T12:11:54Z ERROR Error dialing peer err="dial tcp 192.167.10.2:26656: connect: connection refused" module=p2p
node1  | 2021-08-12T12:11:54Z INFO Reconnecting to peer addr={"id":"0b45b5e79760d742f6242bf7f23dca5f7dcd7d5a","ip":"192.167.10.2","port":26656} module=p2p
abci0  | 2021-08-12T12:11:54Z INFO Accepted a new connection module=abci-server
abci0  | 2021-08-12T12:11:54Z INFO Waiting for new connection... module=abci-server
node1  | 2021-08-12T12:11:54Z INFO Dialing peer address={"id":"0b45b5e79760d742f6242bf7f23dca5f7dcd7d5a","ip":"192.167.10.2","port":26656} module=p2p
....

Are all nodes connect to each other or not?

**Comment by cmwaters** [comment]
Did this get resolved? I'm going to close the issue as being stale but if you still need something answered then feel free to reopen it
