### ISSUE TITLE
abci.socketClient connect failed

### ISSUE THREAD

**Issue by lukema95** [tendermint/tendermint#6818]
When I execute the following command, the program reports an error
```
tendermint start proxy_app="kvstore"                                  
I[2021-08-12|16:57:23.695] Starting multiAppConn service                module=proxy impl=multiAppConn
I[2021-08-12|16:57:23.695] Starting socketClient service                module=abci-client connection=query impl=socketClient
E[2021-08-12|16:57:23.696] abci.socketClient failed to connect to tcp://127.0.0.1:26658.  Retrying after 3s... module=abci-client connection=query err="dial tcp 127.0.0.1:26658: connect: connection refused"
```
I try to delete the ~/.tendermint and try it again , but it does not work.

**Comment by marbar3778** [comment]
What command was run? the above exerpt does not show.

**Comment by devanshi318** [comment]
When I execute "make localnet-start" command, the program reports an error:

node0  | 2021-08-12T10:15:59Z INFO starting service impl=multiAppConn module=proxy service=multiAppConn
node0  | 2021-08-12T10:15:59Z INFO starting service connection=query impl=socketClient module=abci-client service=socketClient
abci0 exited with code 0
node0  | 2021-08-12T10:16:02Z ERROR abci.socketClient failed to connect to tcp://abci0:26658.  Retrying after 3s... connection=query err="dial tcp 192.167.10.6:26658: connect: no route to host" module=abci-client
node0  | 2021-08-12T10:16:05Z ERROR abci.socketClient failed to connect to tcp://abci0:26658.  Retrying after 3s... connection=query err="dial tcp: lookup abci0 on 127.0.0.11:53: no such host" module=abci-client

**Comment by lukema95** [comment]
> What command was run? the above excerpt does not show.

I execute ' tendermint start proxy_app=kvstore '

**Comment by lukema95** [comment]
> What command was run? the above excerpt does not show.

And I found that after installing tendermint, there was no problem when I started it for the first time, and then I would have this error when I exited and restarted

**Comment by lukema95** [comment]
cant not repeat the error

**Comment by puneet166** [comment]
Same problem i am facing
