### ISSUE TITLE
p2p/conn: peer connection dropped due to long message receiving blocks the pong message.

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#6824]
the original discussion is from this thread
https://github.com/cosmos/cosmos-sdk/issues/9686#issuecomment-897275507

In short, the p2p MConnection.recvRoutine, if a message or many messages blocks (might be due to the slow connection situation) the receiving process, the recvRoutine cannot receive the pong message in time (within 45 secs after the ping message was sent). the program will break the receiving loop and then mark the peer status down.  

The 45 secs pong timeout limited the capability of the message receiving. Especially in the large message transmission. ping/pong should be used to guarantee the liveness of the connection. If a message is sending/receiving, maybe should find a way to skip the ping/pong checking.

**Comment by ValarDragon** [comment]
As a quick fix, can we try to increase this pong timeout to be say, 30 minutes, get it on some osmosis nodes, and see if #7186 is fixed?
