### ISSUE TITLE
Postgres event indexer improvements

### ISSUE THREAD

**Issue by aaronc** [tendermint/tendermint#6843]
I just chatted with @alexanderbez and @tessr about this and they asked me to open this issue documenting things we discussed. From the Cosmos SDK's perspective we want cleanly to support typed events (https://github.com/cosmos/cosmos-sdk/issues/7563) and improving Tendermint's event indexing - specifically the Postgres indexer - will help.

To begin with, here are a few issues I notice with the current Postgres events schema (https://github.com/tendermint/tendermint/blob/master/state/indexer/sink/psql/schema.sql):
- there is no way to retrieve block events as an atomic event because they all get flattened. The same is true for tx events, but at least the tx result has them and is indexed
- the `block_events` `UNIQUE(key, height)` key is too restrictive - an event key can occur multiple times in a block
- ditto for `tx_events` `UNIQUE (hash, key)`
- `hash` should probably be part of `tx_results` not `tx_events`
- I find it awkward to simply query events by their type. In the trivial case where an event consists of just a type with no attributes, it will be impossible to retreive that event using this data model. That trivial case may seem unlikely and even useless, but I'm not sure why we should reject it - imagine something like that was used to signal epochs - an important event which may have no other data attached other than the event type

For our internal use cases, I made a simple postgres event indexer using python. The schema is here in case that provides any inspiration: https://gist.github.com/aaronc/148036659cb033c82da7ce6d4fd012a5. It doesn't support block events, but I will try to tweak it a bit so it does. Also, it breaks down events by message which can't be done generically for tendermint.

This schema is designed to support indexing multiple chains in the same database which is likely useful for multi-chain apps. In this schema, composite primary keys do become quite long in `msg_event_attr`, but this is so they to be used as foreign keys in a way that still allows querying to be simple. I experimented with surrogate auto-increment keys, but in the end reverted to composite natural keys because that made queries more elegant.

**Comment by creachadair** [comment]
I would be especially interested in feedback from @aaronc and @jackzampolin on #6868, since you were the folks interested in this and the dependent #6828.

**Comment by creachadair** [comment]
Just an update on this issue, #6868 is merged and has been back-ported into the v0.34.x branch (#6906). I plan to cut a new v0.34 release soon, including that change.

**Comment by creachadair** [comment]
These changes are now in both [v0.34.13](https://github.com/tendermint/tendermint/releases/tag/v0.34.13) and the [first v0.35 release candidate](https://github.com/tendermint/tendermint/releases/tag/v0.35.0-rc1). I'm closing this issue on that basis, but if you have further questions or run into any problems, please feel free to re-open or file new issues.
