### ISSUE TITLE
Should not unlock locked block when seeing +2/3 prevote for nil

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#6849]
There is a subtle divergence from the consensus mechanism as outlined in the [tendermint paper](https://arxiv.org/pdf/1807.04938.pdf) and the mechanism as implemented in this codebase that was discovered in discussion with @milosevic @josef-widder and @cmwaters .

In the paper, once a correct process has 'locked a block' that process will never clear the `lockedBlock` field during a run of consensus for a height. It may replace the `lockedBlock` when +2/3 prevotes are seen for a _different_ block, but it will never end up with a `nil` `lockedBlock`. The only place that the `lockedBlock` is updated within run of consensus for a given height is on line [38 of the algorithm](https://github.com/tendermint/spec/blob/master/spec/consensus/consensus-paper/consensus.tex#L104). 

The go implementation modifies this `lockedBlock` value in an additional place. The go implementation[ nils out the `lockedBlock`](https://github.com/tendermint/tendermint/blob/a374f74f7c914a3c7640694ae80c33bf74e05688/internal/consensus/state.go#L1418) if the process saw +2/3 prevotes for nil in `state.go`. 

This logic of nil-ing out the locked block should be removed to bring the code in line with the spec. To do this, we should ensure there is a test for the current behavior of setting `lockedBlock` to `nil` when +2/3 are seen. We should then remove the logic, ensure that the test fails, and then invert the test to check that the block does not become unlocked.

**Comment by williambanfield** [comment]
This is a prerequisite for #6799

**Comment by josef-widder** [comment]
I think that @cezarad can help with the tests.
