### ISSUE TITLE
Makefile issue

### ISSUE THREAD

**Issue by jerryleooo** [tendermint/tendermint#6859]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
41a361ed8d9755b62972140fc3ddb7a9826e3529

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- **Install tools**: I followed docs [here](https://docs.tendermint.com/master/introduction/quick-start.html#cluster-of-nodes)
- **Others**:

**What happened**:
The script failed, after checking I think https://git.io/fFfOR (which is listed in the docs site) is outdated. And I also tried to run `make all`, it fails too.

**What you expected to happen**:
- Update the docs site
- Fix Makefile

**Have you tried the latest version**: yes/no
Yes

**How to reproduce it** (as minimally and precisely as possible):
Simply follow https://docs.tendermint.com/master/introduction/quick-start.html#cluster-of-nodes

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
make: *** No rule to make target 'get_tools'.  Stop.
make: *** No rule to make target 'get_vendor_deps'.  Stop.
CGO_ENABLED=0 go install -mod=readonly -ldflags "-X github.com/tendermint/tendermint/version.TMVersion=unreleased-master-41a361ed8d9755b62972140fc3ddb7a9826e3529 -s -w " -trimpath -tags tendermint ./cmd/tendermint
flag provided but not defined: -mod
usage: install [-i] [build flags] [packages]
Run 'go help install' for details.
Makefile:72: recipe for target 'install' failed
make: *** [install] Error 2
```

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:
Same issue here: https://github.com/tendermint/tendermint/issues/6416#issuecomment-857358990

**Comment by shengwubin** [comment]
I reinstall the latest version of go and the problem is solved.
