### ISSUE TITLE
Outdated code sections in main.go for the built-in app in Tendermint Core guide

### ISSUE THREAD

**Issue by Bidon15** [tendermint/tendermint#6864]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
tendermint version
unreleased-master-41a361ed8d9755b62972140fc3ddb7a9826e3529

git HEAD: 41a361ed8d9755b62972140fc3ddb7a9826e3529
**ABCI app** (name for built-in, URL for self-written if it's publicly available):
built-in kvstore code section in the guideline
https://github.com/tendermint/tendermint/blob/master/docs/tutorials/go-built-in.md

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS Catalina 10.15.7
- **Install tools**: 
- **Others**:

**What happened**:
After copy-pasting the code sections for main.go in the tutorial, go is displaying errors regarding missing packages/modules
The list to be more precise: 
- package libs/cli/flags is missing
- log package: NewTMLogger, NewSyncWriter are not declared in the package
- read private validator: the config data in the signature of LoadFilePV should be updated(afaiu there is 1 more inner level)
- internal p2p package: LoadNodeKey method is not declared
- node package: NewNode, DefaultGenesisDocProviderFunc, DefaultDBProvider, DefaultMetricsProvider are not declared

**What you expected to happen**:
Run the code snippets with no errors to not lose the context of the tutorial

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):
Follow and reproduce the steps in this guideline: 
https://github.com/tendermint/tendermint/blob/master/docs/tutorials/go-built-in.md

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:
The initiative was first done here: https://github.com/tendermint/tendermint/issues/3808
From the log history, it seems to be left behind since 2019 (except for some small changes e.g. go version updates)

**Comment by marbar3778** [comment]
`unreleased-master-41a361ed8d9755b62972140fc3ddb7a9826e3529`

ill add a note to the tutorial that another assumption is you are using a released version of tendermint. As master is in flux until the release, we do not recommend using it

**Comment by marbar3778** [comment]
I will keep this issue open till after the first rc in order to use it as a reminder to update the tutorial
