### ISSUE TITLE
Improvements in built-in app tutorial for Tendermint Core guide

### ISSUE THREAD

**Issue by Bidon15** [tendermint/tendermint#6865]
The guide itself attracts from the start due to the easy-to-read and follow style. Still, there is a proposal to make it more neat.
https://github.com/tendermint/tendermint/blob/master/docs/tutorials/go-built-in.md#creating-a-built-in-application-in-go

Open questions:
There is gap between 1.1 Installing Go and 1.2 Creating a Go project. Being more exact:
1. Should we clone the repo(tendermint) as a pre-req, too?
2. Does having a kvstore app created inside the repo itself makes it more easy to follow the narrative? 

Proposal on points where to improve: 
1. include the simple sentence like "git fork/clone tendermint" to be as precise as in 1.1 and 1.2 sections 
2. create a kvstore dir/app inside the main repo

If there are better ideas, please let me know as me as newbie would fancy to help others who are(or going to be) on the same page as me 🥳 
Cheers

**Comment by cmwaters** [comment]
> Should the reader create the kvstore dir inside the freshly cloned tendermint repo or outside as the separate one?

Outside I believe and then just import it. I guess we were assuming it was already cloned but makes sense to add a comment to `go get tendermint`

**Comment by marbar3778** [comment]
there isn't a need to clone the repo. The walkthrough seems correct to me. 

1.1 install go
1.2 create a new go project

I will leave a few sentences that mention there is no need to clone tendermint

**Comment by devanshi-supraoracles** [comment]
Any tutorial for rust-based kvstore application on tendermint?
