### ISSUE TITLE
seems to collect wrong metrics

### ISSUE THREAD

**Issue by carameleon** [tendermint/tendermint#6871]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

github.com/cosmos/cosmos-sdk v0.43.0
github.com/tendermint/tendermint v0.34.11

----

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

https://github.com/crypto-org-chain/cronos/tree/v0.5.2

----

**Environment**:
- **OS** (e.g. from /etc/os-release): 20.04
- **Install tools**:
- **Others**:

----

**What happened**:

Below 2 results show different information of missed blocks.

Result of prometheus metrics `tendermint_consensus_validator_missed_blocks`
It presents the number of missed blocks keeps on increasing continuously.

![image](https://user-images.githubusercontent.com/45417810/131249056-5adba8d6-f0a2-46fd-981e-c3b917cbc261.png)

- Result of querying signing info 

It presents nothing missed blocks
```
address: ethvalcons12w6pdg0keyvdt0uq4u20zgpylv54anfklq206w
index_offset: "33739"
jailed_until: "1970-01-01T00:00:00Z"
missed_blocks_counter: "0"
start_height: "6771"
tombstoned: false
```

I actually checked missed block are exists or not.

There were no missed blocks.

----

**What you expected to happen**:

----

**Have you tried the latest version**: no

----

**How to reproduce it** (as minimally and precisely as possible):

You can see once you set prometheus = true in [instrumentation] section and collect metrics.

And then you can compare with prometheus metrics and the result of query when missed blocks is increased.

----

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by cmwaters** [comment]
Hi @carameleon, thanks for opening an issue. 

So I'm not the most familiar with the Cosmos SDK but I believe these are slightly different values. The `missed_blocks_counter` in the ComosSDK counts missing signatures in a block _across a sliding window_ i.e. how many blocks missed in the last 1000 blocks. Whereas, the Tendermint Prometheus metric is since the node started.  

However, if you think you're getting different values across the same timespan then let me know. Looking at the code now, this shouldn't be happening.

**Comment by carameleon** [comment]
Hello @cmwaters,

> However, if you think you're getting different values across the same timespan then let me know. Looking at the code now, this shouldn't be happening.

I think we're getting different values across the same period. 

I've never stopped or restarted a node since I first started a node on 26th Aug

Below is tendermint metrics 

- `tendermint_consensus_validator_missed_blocks` from 26th Aug to 30th Aug

![image](https://user-images.githubusercontent.com/45417810/131319033-769b6026-8a21-4807-b485-66eaa8e139b8.png)

- signing info 
Aug 26 02:22:16 ~ Aug 30 09:36:02 UTC 2021
```
address: ethvalcons12w6pdg0keyvdt0uq4u20zgpylv54anfklq206w
index_offset: "43253"
jailed_until: "1970-01-01T00:00:00Z"
missed_blocks_counter: "0"
start_height: "6771"
tombstoned: false
```

**Comment by marbar3778** [comment]
> missed_blocks_counter: "0"

Points to missed blocks in a row, while the tendermint value is associated to the total amount of missed blocks. The reason tendermint doesn't reset it is that we don't know how the app handles downtime and if we were to make assumption it would limit the app. 

These numbers in 99% of cases will not be the same. 

Closing this for now, feel free to comment and we will do our best to respond.

**Comment by carameleon** [comment]
@marbar3778 
> These numbers in 99% of cases will not be the same.

If `tendermint_consensus_validator_missed_blocks` is increased, `missed_blocks_counter` must be increased in the current block window. Is it right?
If yes,
I wonder why `missed_blocks_counter` always zero, regardless `tendermint_consensus_validator_missed_blocks` is increased continuously?

**Comment by marbar3778** [comment]
> If tendermint_consensus_validator_missed_blocks is increased, missed_blocks_counter must be increased in the current block window. Is it right?

Correct, if its not then the issue may be in the SDK. We don't have power over this value. 

> I wonder why missed_blocks_counter always zero, regardless tendermint_consensus_validator_missed_blocks is increased continuously?

If you stop your validator, then look at both endpoints they should be increasing, but once you start your validator back up and sign one block, missed_blocks_counter will be reset to 0
