### ISSUE TITLE
Bifurcation

### ISSUE THREAD

**Issue by ItsFunny** [tendermint/tendermint#6872]
## Summary
Bifurcation

## Problem Definition
A,B,C,D four validators
1. What If A commit the block and B,C,D enterPrecommit but failed to writeBlock (server shutdown just at the same time and same code line)
2. A server shutdown and it wont restart again ,And  B,C,D restart  , Can it be possible  that ,B,C,D accept new transactions
    and  commit a different Block ? 
3. Thanks a lot 

## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Hey 👋 , 
Tendermint consensus uses a write ahead log to record messages sent and received between peers such that in the event of their machine crashing, upon restart, they should be able to replay the messages (which includes the 2/3+ precommit votes) and recover the committed block. Does this answer your question?

**Comment by cmwaters** [comment]
I'm going to close this issue now. Feel free to ask any follow up questions that you might have. Actually, the best place to ask them would be on Discord
