### ISSUE TITLE
ABCI: speed up tx delivery using bidirectional streaming with gRPC

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#688]
Feature request:

Change ABCI over gRPC to "CheckTxs" and "DeliverTxs", i.e. provide all TXs in a single RPC call and use bidirectional gRPC streaming.

A bit of .proto says a thousand words:

```
service ABCIApplication {
...
	rpc DeliverTxs(stream RequestDeliverTx) returns (stream ResponseDeliverTx);
	rpc CheckTxs(stream RequestCheckTx) returns (stream ResponseCheckTx);
...
}
```

See "bidirectional streaming" on https://grpc.io/docs/guides/concepts.html.

This should significantly reduce the performance gap of gRPC ABCI and socket ABCI by avoiding the roundtrip for each Check/DeliverTx invocation.

**Comment by odeke-em** [comment]
Thank you @mdyring for filing this issue and welcome back to tendermint!

I've updated the issue title a little but I believe you meant to open this issue in this repo https://github.com/tendermint/abci targeting the code in these declarations here 
https://github.com/tendermint/abci/blob/191c4b6d176169ffc7f9972d490fa362a3b7d940/types/types.proto#L230-L242
unless am mistaken.

The rest of the team will evaluate and get back on the issue, thanks again.

**Comment by mdyring** [comment]
@odeke-em, thanks for the improved title.

You are correct, changes to the .proto needs to be done in the abci repo but I imagine some changes in the tendermint core will be needed as well, to implement the changes.

Where you guys want to track the issue I'll leave with you - let me know if you want to opened in abci repo instead.

**Comment by odeke-em** [comment]
Roger that. Yes you are correct, perhaps we might need to make the major changes in core here, first -- we'll coordinate the issue in both repos.

**Comment by adrianbrink** [comment]
This shouldn't require changes in Tendermint core, since the ABCIApplication is only used by the underlying GRPC library if you are running with `--socket grpc`.

**Comment by mdyring** [comment]
Sounds good, want me to re-create issue in abci repo?

**Comment by adrianbrink** [comment]
Yes please

**Comment by mdyring** [comment]
Moved here: https://github.com/tendermint/abci/issues/112

**Comment by marbar3778** [comment]
With ABCI++ we are migrating to finalizeBlock, this will deliver transactions as a single batch. Not sure if we need to worry about bidirectional streaming in this case. 

closing this, reopen if we want to add streaming for checktx.
