### ISSUE TITLE
External Application run error

### ISSUE THREAD

**Issue by devanshi-supraoracles** [tendermint/tendermint#6888]
Hello

I run rust based kvstore application on tendermint. But When I tried to start tendermint node I got error like "ERROR: failed to create node: error during handshake: error calling Info: read message: EOF" .

My tendermint version: unreleased-master-511bd3eb7f037855a793a27ff4c53c12f085b570 

Is there any issue for tendermint version or any other issue?

**Comment by cmwaters** [comment]
Hey, could you link us to the rust-based kvstore application? At a glance, it looks like it's something to do with the ABCI connection

**Comment by marbar3778** [comment]
> Is there any issue for tendermint version or any other issue?

it may be so, we recommend using a release at all times instead of master. We can not make guarantees for master
