### ISSUE TITLE
Add RPC documentation

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#691]
Let's add RPC documentation in this style.
https://h.readthedocs.io/en/latest/api/#operation/root

It looks super sexy and is easily usable. The sources for it can be found [here](https://github.com/hypothesis/h/tree/master/docs/_extra/api).

**Comment by adrianbrink** [comment]
@zramsay I wasn't sure if I had mentioned this to you already. What do you think about this?

**Comment by zramsay** [comment]
#526, sort of

**Comment by ebuchman** [comment]
We have the slate docs

**Comment by melekes** [comment]
> We have the slate docs

where?

**Comment by ebuchman** [comment]
In the code. But you're right we need to serve them ...

**Comment by zramsay** [comment]
OK so I've basically figured out what we need to do. The procedure is as follows:

1) check for changes in `rpc/core`, if none, @tenderbot is off the hook (CI does nothing further)
2) if changes, clone: https://github.com/tendermint/slate and checkout the `gh-pages` branch, run `bundle install`
3) have CI run https://github.com/tendermint/tendermint/blob/zach/slate/slate.sh
4) commit the changes to the `tendermint/slate` repo (`gh-pages`) branch and push
5) from the `tendermint/slate` repo, run `./deploy.sh`
6) now, https://tendermint.github.io/slate should be hosting the RPC docs

**Comment by ebuchman** [comment]
Cool. Let's make sure this is clearly documented. Is there a simple way to preview the docs on develop too ? Looping in @greg-szabo

**Comment by zramsay** [comment]
right now it builds from develop directly. The `scripts/slate.sh` is well-documented WRT to what and why

**Comment by zramsay** [comment]
switched to build from master. one day Slate will have verisoning.
