### ISSUE TITLE
Mempool: Re-CheckTx leads to panic

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#6919]
While @tychoish was making alterations to the `e2e` test suite, a novel bug surfaced in the mempool code.

The events that lead to this panic are as follows.

A series of `CheckTx` requests fail to execute because the queue is full.
```
validator06    | 2021-09-09T17:19:24Z ERROR failed to execute CheckTx during rechecking err="can't queue req: buffer is full" module=mempool version=v1
validator06    | 2021-09-09T17:19:24Z ERROR failed to execute CheckTx during rechecking err="can't queue req: buffer is full" module=mempool version=v1
validator06    | 2021-09-09T17:19:24Z ERROR failed to execute CheckTx during rechecking err="can't queue req: buffer is full" module=mempool version=v1
```

Soon after, the following panic is observed:

```
validator06    | panic: re-CheckTx transaction mismatch; got: 1565A5B7FACF14A50DC359762EE9478A6754E9CDB326BAB5CB6B4E893DD6D316, expected: 32A01DDFCD821C0D8A2170957036352B515E1861EB42A4020C4B874F068D20E1
validator06    | 
validator06    | goroutine 105 [running]:
validator06    | github.com/tendermint/tendermint/internal/mempool/v1.(*TxMempool).defaultTxCallback(0xc000272480, 0xc003183520, 0xc003092c80)
validator06    | 	github.com/tendermint/tendermint/internal/mempool/v1/mempool.go:632 +0x99f
validator06    | github.com/tendermint/tendermint/abci/client.(*socketClient).didRecvResponse(0xc0001f6e70, 0xc003092c80, 0x0, 0x0)
validator06    | 	github.com/tendermint/tendermint/abci/client/socket_client.go:222 +0x202
validator06    | github.com/tendermint/tendermint/abci/client.(*socketClient).recvResponseRoutine(0xc0001f6e70, 0x16d1100, 0xc000010358)
validator06    | 	github.com/tendermint/tendermint/abci/client/socket_client.go:185 +0x107
validator06    | created by github.com/tendermint/tendermint/abci/client.(*socketClient).OnStart
validator06    | 	github.com/tendermint/tendermint/abci/client/socket_client.go:93 +0x2bc
```

It would appear that the message queue drops `CheckTx` messages on the floor when the queue is full. 
See https://github.com/tendermint/tendermint/blob/816e9b0b49efb7d008dd19e16f0cb513891eb202/abci/client/socket_client.go#L491

The comments on the mempool `defaultTxCallback` indicate that the callback should be called in the same order as the Tx are rechecked. 
https://github.com/tendermint/tendermint/blob/816e9b0b49efb7d008dd19e16f0cb513891eb202/internal/mempool/v1/mempool.go#L617

It seems possible that if a recheck fails the callback may still erroneously fire and wind up with the wrong data. This is still a hypothesis and needs further investigation.

**Comment by creachadair** [comment]
Possibly related to #5439 as well? The symptoms aren't identical, but the conditions are similar (busy mempool, CheckTx panic).

**Comment by tychoish** [comment]
Because callbacks synchronous as of 0.36 (in consensus), and the socket client has a significantly simplified execution model (without asynchronous methods) don't think this can happen anymore, and I certainly haven't seen in a while. (Also all of the code at the heart of this stack trace doesn't exist in master). I think it's fair to close this issue for now, and we can reopen (or open a new issue) if we see this or a related issue again in the future.
