### ISSUE TITLE
Ensure all funcs in types pkg are well guarded

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#693]
Eg. https://github.com/tendermint/tendermint/blob/master/types/vote_set.go#L137 is highly unsafe

**Comment by ebuchman** [comment]
@odeke-em I was somewhat unnerved to discover this. Want to help level up this package? We need to make sure all functions are well guarded against bad input, or if not, have clear comments that it's the callers responsibility to pass in valid arguments, and if not a panic could result.

I'm mostly worried about aberrant votes/msgs coming in on the consensus reactor and hitting this data structures. For instance here if we received a vote from a different chain that had more validators than us we'd panic - obviously very bad behaviour. This particular one is fixed here: https://github.com/tendermint/tendermint/commit/cd8dff0c96ca3ea1ec44d637f93c10c418edac1a#diff-bd488e139d955daba658159f507010f7R105. But I'm now worried there's more lurking - we could probably do with much improved test suite to try and hunt for all these cases and fuzz these datastructures! 

Interested?

**Comment by odeke-em** [comment]
Great stuff discovering and reporting this @ebuchman. Yes in deed, I am interested in working on this.

**Comment by ebuchman** [comment]
As an indicator, we should probably be shooting for 80% coverage on all of these: https://codecov.io/gh/tendermint/tendermint/tree/master/types

**Comment by xla** [comment]
@melekes After your recent improvements should we still keep this open?

**Comment by melekes** [comment]
Yes. I think there may be still some bugs lurking.

**Comment by jackzampolin** [comment]
Going to go ahead and close this issue.
