### ISSUE TITLE
Single command to get full tendermint peer address

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#6959]
## Summary

Currently you get your Tendermint peer address by:
`osmosisd tendermint show-node-id` to get the `6364e63227345d7d4be951c8b771303dc2dfc27a` component, and then you manually copy paste the `@{your IP}:{your port}`.

It'd be great if there could be a command for building the whole string, reading `{your IP}` from the external address if in the config, and if not obtain it from however Tendermint typically guesses at a node's external address.

## Problem Definition

This will save lots of time / annoyance for node operators.

## Proposal

add a CLI command for `tendermint show-p2p-address` that displays the full string `6364e63227345d7d4be951c8b771303dc2dfc27a@143.244.147.126:26656`

from a conversation with @UnitylChaos 
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by williambanfield** [comment]
related to: #5588

In general, Tendermint's story for discovering its external address is not great. It's a difficult thing to do correctly given the network topologies where Tendermint may be run, i.e. behind a NAT and we're planning to make that better as improve Tendermint's P2P system.

@ValarDragon @UnitylChaos Could you give a common task that node operators may be trying to accomplish when they would invoke this endpoint?

**Comment by ValarDragon** [comment]
The main use cases trying to be done is share your peer address to other nodes in starting up a network (so before the status endpoint is available), or when you've synced to the network, and giving people your peer to add to their configs or seed.toml's. (The latter could be accomplished via status, I didn't know that it was provided their before!)

**Comment by julienrbrt** [comment]
Hi I would like to look at this issue as it's labelled as a "good first issue". Reading `ExternalAddress` from the P2P config is straightforward, however is:
> and if not obtain it from however Tendermint typically guesses at a node's external address.

a dependency of  #5588 given @williambanfield  comment?
