### ISSUE TITLE
Link to bug bounty in changelog is dead

### ISSUE THREAD

**Issue by haasted** [tendermint/tendermint#6962]
It seem appears that the link to the bug bounty program, which is included in the changelog for most major releases, is no longer pointing to anything meaningful.

For reference, the link is currently: https://hackerone.com/tendermint

Update: Did some googling, and the correct link is probably https://hackerone.com/cosmos

**Comment by creachadair** [comment]
Thanks for pointing that out! I'll make sure that gets updated appropriately for the next release.

**Comment by creachadair** [comment]
I updated the link in #7011, so the fix is visible at tip and will land in the upcoming v0.35. Thanks again for letting us know.
