### ISSUE TITLE
p2p: logs are flooding the terminal

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#6987]
## Summary

Tendermint p2p logs flood the terminal, this takes attention away from other core information. 

As you can see here https://pastebin.com/7JBa1VRm, in between two blocks there are 10s of lines of p2p errors.

This is a nice to have, but i know many users would appreciate it. 

## Problem Definition

P2P logs too many errors. 

## Proposal

If possible, a way to group multiple error logs from p2p in info mode, if debug mode is set they would be expanded back to how they are currently outputted 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jackzampolin** [comment]
Yes please! Make tendermint logs readable again!

**Comment by JayT106** [comment]
https://github.com/rs/zerolog#log-sampling
maybe can use advanced sampling for the `p2p` error message when the logger level setup is `Info`?
