### ISSUE TITLE
tendermint node 

### ISSUE THREAD

**Issue by rupam150** [tendermint/tendermint#7002]
Can anyone tell me the difference between the commands 

**tendermint node**  VS  **tendermint node --consensus.create_empty_block=false --proxy_app=tcp://0.0.0.0:26658**

**Comment by cmwaters** [comment]
Hey @rupam150, `tendermint node` is being deprecated in favor of `tendermint start` as the command to start the node. In regards to the flags:
- `consensus.create_empty_block=false` means that tendermint won't propose empty blocks. By default, if a proposer has no transactions in their mempool, they will still propose a block with no transactions (which can be quite consuming of data). Setting this to false means that validators will wait until a transaction comes through before proposing anything.
- `proxy_app=tcp://0.0.0.0:26658` informs the node how it should communicate with the application. In tendermint, you can run a node with the application built-in to it or you can run them as different processes that communicate to each other. In this example, you are telling Tendermint that to communicate to the application via TCP over this specific port.
