### ISSUE TITLE
cli: initialize node with genesis flag

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7005]
## Summary

Just something I thought might be a neat little UX improvement whilst I was mucking around with the testnets. It would be a little easier if you could initialize a node like so:
```
tendermint init validator -genesis http://45.118.37.9:26657
```
where the endpoint points to another node in the network and the command fetches and sets up the genesis file for you (as opposed to creating a default one).

We could even add a checksum field as well if someone wanted that little extra layer of security

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tychoish** [comment]
+1 to having a checksum. 

It might also be good to use the chunked_genesis endpoint (potentially with a list of providers so we could pull a bunch from different services to make things really speedy.

**Comment by marbar3778** [comment]
This would be awesome!! This would make the UX way way better. 

A small ux improvement on top of this would be to introduce a genesis message in the p2p layer. This way, you don't have to scavenge for an exposed rpc endpoint. But this is the cherry on top, its not needed for now.

**Comment by cmwaters** [comment]
> It might also be good to use the chunked_genesis endpoint (potentially with a list of providers so we could pull a bunch from different services to make things really speedy.

Yuppp depending on the size of the genesis
