### ISSUE TITLE
add dev docs in Java

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#701]

**Comment by srmo** [comment]
Seeing Java makes my ears ring. What is this about? jTendermint? Is there something we can do to help?

**Comment by zramsay** [comment]
e.g. https://github.com/tendermint/tendermint/blob/develop/docs/app-development.rst gives only a description in go. It should be expanded/re-organized for other languages. Could even have its own section on the landing page (sort of tied to the apps in Ecosystem)

**Comment by srmo** [comment]
Ah, ok. Let me see if I can provide some snippets from the jTendermint repo. Not today but I'll try to find the time in the coming days. Does the general approach of branching from develop and then PRing into devlop hold here?

**Comment by zramsay** [comment]
sounds good :) branching from and PRing to develop is correct!

check out docs/README.md for instructions on building locally to view your edits.

**Comment by srmo** [comment]
Damn it. I wanted to go to bed but started to work on RST in IDEA and just added a collapsable code snippet logic to the theme. Looking forward to send a PR tomorrow/friday :)

**Comment by melekes** [comment]
@srmo ![you rock](https://media.giphy.com/media/PRs0raLvOiYzC/giphy.gif)

**Comment by srmo** [comment]
Trust me, I’m working on it.

**Comment by srmo** [comment]
@zramsay have a look at https://github.com/srmo/tendermint/tree/701-add-dev-docs-in-java
There's the first java code block for deliverTx containing the example for collabsable code blocks.
looking for first feedback

**Comment by zramsay** [comment]
thanks! closed in #746
