### ISSUE TITLE
ERROR: unknown flag: --proxy-app

### ISSUE THREAD

**Issue by fedproject** [tendermint/tendermint#7012]
**tendermint version: 0.34.13**

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):	macOS 11.5.1
- **Install tools**: brew
- **Others**:

**What happened**:
When I follow the instruction in [Local-Node section in Quick-Start](https://github.com/tendermint/tendermint/blob/master/docs/introduction/quick-start.md#local-node)
to type `tendermint start --proxy-app=kvstore`, it props up error 
`ERROR: unknown flag: --proxy-app`
<img width="522" alt="image" src="https://user-images.githubusercontent.com/90293674/135065076-21d687f0-650f-4011-bfd7-8c1f3fe8b48a.png">

**What you expected to happen**:
```
I[01-06|01:45:15.592] Executed block                               module=state height=1 validTxs=0 invalidTxs=0
I[01-06|01:45:15.624] Committed state                              module=state height=1 txs=0 appHash=
```

**Have you tried the latest version**: yes/no
yes

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by fedproject** [comment]
Submitted Proposed Fixed in #7013

**Comment by marbar3778** [comment]
In 0.35, the upcoming release, the flag is `proxy-app`. if youd like to use 0.34, there are docs for this version here https://docs.tendermint.com/v0.34/

**Comment by creachadair** [comment]
I filed #7017 to see if we can make this situation less likely to trip folks up.
