### ISSUE TITLE
Default docs.tendermint.com should show the latest release, not tip

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7017]
## Summary

Make https://docs.tendermint.com/ default to showing the documentation for the latest release rather than tip.

## Problem Definition

Per #7012, it ie confusing for users to install a release version of Tendermint, while docs.tendermint.com shows newer content that applies to a future release. The [installation instructions](https://docs.tendermint.com/master/introduction/install.html) guide folks to either download a binary release or Homebrew, both of which lead to tagged releases. Only users who clone and build from source will have a binary at tip, and that's probably not ideal for other reasons, unless they specifically want to test unreleased features.

## Proposal

If possible, our default docs site should redirect to the latest release tag rather than to master. Having the docs for master accessible is still valuable, but it should be a choice users make rather than the default.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
This makes sense to me as well
