### ISSUE TITLE
Postgres Driver not available, cannot use postgres sink.

### ISSUE THREAD

**Issue by brennhill** [tendermint/tendermint#7043]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.34.13

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Any

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX
- **Install tools**:
- **Others**:

**What happened**:
When configuring config.toml to use postgres driver, this will fail to function properly, even if postgres is available and the connection string is valid.  This is because there is no postgres driver available.

**What you expected to happen**:
I would expect tendermint to connect to postgres without further configuration OR very clear instructions that we need to import a postgres driver in our app, e.g.
`import (_ "github.com/lib/pq")`

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
Try using the postgres sink without importing a postgres driver in your app.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by creachadair** [comment]
The fix is merged and will go out with v0.34.14. It is also already addressed in the forthcoming v0.35 release.

**Comment by brennhill** [comment]
Great,thank you so much @creachadair
