### ISSUE TITLE
Tendermint checks explicitly for KV indexer rather than indexer capabilities

### ISSUE THREAD

**Issue by brennhill** [tendermint/tendermint#7044]
## Summary

In the tendermint code, there are three potential indexers: null, KV, and postgres.  However, only the KV indexer is feature complete.  I believe this is why the code checks explicitly if the indexer is the KV indexer, rather than checking for certain indexer features.  This inhibits the ability to create new indexers in the future, as even if the new indexer were to provide all the features of the KV indexer, it still would not be used by tendermint.  

I suggest adding feature flags to the Indexer interface and using those to activate certain APIs/behaviors rather than checking for the identity of a specific indexer.

## Problem Definition

See summary

## Proposal

See Summary

If others agree this is something I can look at working on.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
I agree that checking for that specific indexer is not really ideal. That check is mainly a workaround because custom indexing is a recent addition, and the sole other indexer implementation right now (psql) isn't fully feature-compatible with the KV one.

I intend to  work on the indexing interface during the 0.36 cycle, and I would like to get rid of that limitation. I'd rather not remove the special case just yet, though. Do you already have a custom indexer that is already blocked by this workaround?

**Comment by brennhill** [comment]
Not *immediately* blocked but we want to use postgres. We were surprised to see it wasn't feature complete AND even if we did add those features, it still wouldn't enable the APIs because of the hardcoded KV indexer check.

Happy to provide a patch just need agreement on what it looks like.

**Comment by brennhill** [comment]
My thought is there are two ways to do this, the first is a set of hasFeature() methods attached to the indexer API.  While this would work and also work with IDE code discovery, it's not effortlessly extensible by future indexers.  

Another approach would be a `features` map, which can come with a set of explictly known/exposed keys.  If a key is missing or false, the indexer does not have that feature.  My background is more nodejs and that's a pretty typical approach, but I'm not sure if that's the idiomatic go way.  The downside is that this is less obvious to code completion tools and a little harder to discover, but more extensible.

I could handle creating a patch for either option, or I'm happy to consider other suggestions if they are more idiomatic or just plain better.  

Please let me know your thoughts here.

**Comment by marbar3778** [comment]
Hey, thanks for opening this issue. The psql indexer is feature complete. Kv Indexer is meant to be marked as deprecated and all indexing to be done externally. Tendermint is tasked with providing consensus and networking. Providing a way to query information should be done via an external service. 

If youd like to use postgres, you can hook directly into the db or expose it through something like graphql.

**Comment by creachadair** [comment]
> Hey, thanks for opening this issue. The psql indexer is feature complete.

To expand on this point slightly: It was indeed by choice that the psql indexer doesn't implement the query components of the indexing interface. So it doesn't implement all the same features as the KV indexer, but that was intended.

That said, we're still thinking about the way forward for indexing. Right now as @marbar3778 says, using the Postgres indexer should allow more expressive queries via SQL, and if you can use that I'd recommend it. However, we haven't fully decided what other changes the indexing interface needs.

My thoughts so far are that we should _remove_ the query parts of the indexing interface, so that every implementation can fully satisfy it with no need for type switches or feature selection. But it sounds like you have some other ideas in mind.

Can you say more about how you are currently using the rest of the interface? If, hypothetically, we replaced the KV indexer with something else that allowed offline queries (like Postrgres) would that meet your needs? (To be clear: I'm not saying we will do that necessarily, but that's one option).

**Comment by brennhill** [comment]
@creachadair I actually like the idea of removing the queries from the indexer entirely and just have it be a method of writing data to an external system that can be used for those queries.  Then expose a seperate/matching module that can be used/extended by applications.  

I think the indexer in tendermint may also need an extension mechanism, in case one wants to index the results of certain application behavior.  I'm considering use cases like Axie in which there may be game world consensus or other items that the application may want to be able to index and/or query.  I'm not clear on the best/most modular way of handling this yet.  But I do want to create a way for a robust and extensible indexing/querying system.

**Comment by creachadair** [comment]
> I think the indexer in tendermint may also need an extension mechanism, in case one wants to index the results of certain application behavior.

Can you say more about some of the uses you have in mind? My intuition is that the consensus node probably doesn't want to be a general-purpose logging facility for arbitrary application state. The events the node logs now are just the ones that relate to state replication (e.g., blocks and transactions and some descriptive metadata for those). Arguably the metadata are sort of open-ended, but they're really just decorations on the state-replication events.

It seems to me that application-specific details should probably be logged/indexed by the application itself. If the node operator is already running a database to store Tendermint logs, the application could also write data there to suit the queries it needs—that could be a convenient operational efficiency. I don't see any real advantage to having the consensus node act as a logging proxy, except for the events where consensus is the source of truth.

That said, if you have some use cases in mind that I'm not considering, I'd be interested to read more.

**Comment by faddat** [comment]
Maybe this should be on the cosmos sdk?

The user story is basically:

`As a user, I'd like to be able to query anything stored in a cosmos-sdk chain rapidly` and I guess that Brenn (he works with Notional) is likely referring to things that are kept in the SDK's multistore, too.

**Comment by brennhill** [comment]
Consider a chain that has NFT like capabilities but without building that into a special smart contract layer. Basically, the chain manages the NFTs, which may have lots of metadata.  

Ownership of that NFT, and the metadata (some of which could potentially be mutable somehow - mechanism ignored for now in this imaginary example), must go on the consensus layer, as must the mutation.  

Now, if I want to build a UI against this, I need to support a lot of functions:

1. Who owns NFT X?
2. What is the history of ownership of NFT X?
3. When was NFT X mutated?
4. What is the history of that mutation?
5. How many times has ownership been changed?

What if we wanted to fractionalize that NFT?  

I think you can see where I'm going with this.  All these state mutations must have consensus and most apps will want to query... basically everything.

**Comment by brennhill** [comment]
It's possible my mental model is not 100% there yet with all the pieces of Tendermint/Cosmos so maybe I'm looking in the right place, but either way just making the indexer a "pluggable" part of the system seems a low-downside lots of possible upside road to go down.

**Comment by brennhill** [comment]
Another use case is analytics/hot backup.  By dumping to an external sink, that sink could log to a secondary computer where if the first node fell down the secondary node would be getting these updates in a streaming fashion and could act.  Sort of like CDC style monitoring in traditional systems.  This would allow node providers to have more robust infrastructure, I think. Again, still getting up to speed.
