### ISSUE TITLE
Tendermint (ABCI app) vs smart contract app

### ISSUE THREAD

**Issue by epsstan** [tendermint/tendermint#706]
This is not a bug/feature request.  I'm looking for some docs/clarification. I couldn't find them at tendermint/readthedocs or in the examples.

When building an ABCI app, what are idioms for the following :
1) Code distribution - How do you ensure all participants are using the same version of the app. Is this logic that needs to be built into the app ? ( With (ethereum) smart contracts, everyone just uses a contract deployed to a particular address.

2) Identity/Entitlements - Is there any notion of identity other than the pub/priv keys of the tendermint nodes themselves ? For example, in ethererum, the identity/address of a function caller is injected via the msg.sender and tx.origin globals.  In tendermint, this has to be explicitly modeled as part of the tx payload ?

3) Mutliplexing multiple apps on the same tendermint cluster -  A tendermint node accepts a single proxy-app parameter. Does this mean that if I want to build/run N distinct apps with the same set of participants, I need to run N tendermint clusters (1 per app) ?

I have some more questions.  Should I ask them here or somewhere else  ? Thanks.

**Comment by zramsay** [comment]
For 1., see #495, which will make building that logic into the app possible. I'll let others chime in on 2/3; these are good points which we should address in the docs, thanks. The community chat is a great place to start: https://cosmos.rocket.chat

**Comment by srmo** [comment]
@zramsay @epsstan you can also relay on https://github.com/tendermint/tendermint/issues/572 from now on. One of the ideas is to add the version string to your appstate hash. This way only nodes on the same version will be able to work on the chain. 
Distributing code is another story :)

3) seems to be possible with your app ignoring transactions not related to it's logic. It gets tricky when you consider that you still need to produce the same apphash as all other nodes

**Comment by epsstan** [comment]
@zramsay Ignoring transactions not specific to the app can be very inefficient, especially if app1 has much more transactions than app2.  

What are your thoughts around tendermint being a library applications are coded against instead of a process they connect to. The tendermint state (genesis etc) can be part of the application's state.

**Comment by srmo** [comment]
> can be very inefficient
This looks like premature optimisation - if this is true, than the underlying assumption that you can run multiple applications on the same chain is inefficient by itself. 
Maybe we can think of the distinction between validators, which have to see all transactions and (light) clients, that only subscribe for transactions with certaing tags?

**Comment by zramsay** [comment]
@epsstan hope the discussion here helped. Our chat is actually riot: https://riot.im/app/#/room/#cosmos:matrix.org for follow up discussion.
