### ISSUE TITLE
state: Use a single source of versioning

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7072]
## Problem Definition

Currently, the `State` struct has two sources where the version is held:
1. In `State.Version.Consensus.App`
2. In `State.ConsensusParams.Version.AppVersion`

Keeping these two in sync across updates to consensus params, upon startup, statesync and replay (when we use the `Info` ABCI call) is vulnerable to introducing bugs/inconsistencies.

## Proposal

The Soft Upgrades work will most likely introduce `BlockVersion` to the `ConsensusParams`. I would therefore propose removing `State.Version` as being redundant. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by laniehei** [comment]
Hi Callum! Just doing a gut check -- you expect that the spec repo will also have to be changed with this proposal, right? Looks like ConsensusParamsFromProto() requires the protobuf definition to be updated with this change

**Comment by cmwaters** [comment]
Hey, yup we'll need to update the spec by adding `Block` to `ConsensusParams.Version`. We might also want to rename `AppVersion` to `App` because it stutters a bit.

**Comment by spaceCh1mp** [comment]
Hi, I'd like to pick up this issue if no one's currently working on it and it's still a priority

**Comment by spaceCh1mp** [comment]
Just wanted to be clear on if the plan is to cut `version.Version` from the state struct
cause that'd mean changing the structure of the Header type and pretty much every part of the code that's dependent on it

**Comment by musinit** [comment]
@spaceCh1mp are you working on this issue?
