### ISSUE TITLE
abci: remove global mutex around local client

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7073]
## Problem Definition

This was brought up in a similar [issue](https://github.com/tendermint/tendermint/issues/6899). Currently, Tendermint uses a mutex around ABCI calls so that they are serialized. This was done out of safety and simplicity. However, this restricts the ability for apps to implement any form of concurrency between the applications. It should thus really be the responsibility of application to handle mutexes.

## Proposal

Remove the mutex here:
https://github.com/tendermint/tendermint/blob/e53f92ba9cfceb49c1588775f6a9c700c22d4c0a/abci/client/local_client.go#L18

We should make sure that the change in responsibility is well documented

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
So my thinking was that by already forcing a set of changes with the ABCI++ work it might be okay to force app developers to handle concurrency. I also don't mind making this lighter by having two implementations and then deprecating one so some users can still use the synchronized local client but in all honesty the SDK will be making the change for the app and I don't think there's too much work in just adding a mutex for the non SDK users

**Comment by thanethomson** [comment]
> @thanethomson is the motivation for dropping it again still the same as outlined in this issue? Based on #9288 it seemed like the global mutex is being kept in Tendermint and now it's being dropped again. Is this now a final decision to remove it or could this end up being added back again?

The motivation's still the same. The original problem still stands, but the changes were reverted due to #9155.

**Comment by thanethomson** [comment]
After today's community call, we decided that we can roll this out in an additive, non-breaking way by providing a non-blocking local client (i.e. without the mutex) _in addition to_ the existing local client.

We should roll this out to v0.34 onwards. If users prefer the non-blocking client, we can deprecate the blocking one in v0.38 and remove it in v0.39 or later.

**Comment by thanethomson** [comment]
Speaking to @tac0turtle about this today, it's not clear whether the SDK will be able to make use of the unsynchronized local client in #9660 if we backport it to v0.34 due to concerns around the impact on the concurrency model. For now we'll roll out the new unsync local client in Tendermint v0.38, unless someone brings up a need for it in an older version of Tendermint.

We will probably mark the regular (synchronized) client as deprecated in v0.38 and schedule it for removal in a later version, unless there's a good reason to keep it around.
