### ISSUE TITLE
block commitment latency of tendermint

### ISSUE THREAD

**Issue by Grivn** [tendermint/tendermint#7087]
## Summary

Improve the metrics of Tendermint consensus.

## Problem Definition

To demonstrate the performance of Tendermint better, we perfer some measurement of the latency of each block commitment.

**Latency of block commitment**, which means the time interval from the creation of a block to the commitment of it.

Besides, we could measure the latency of transaction commitment which means the time interval from when one node has received a transaction to the commitment of it.

## Proposal

Create an instance `CurLatency` in consensus metrics `internal/consensus/metrics.go`. Then, we could collect the block commitment latency while a block has been committed.

As for the transactions, we could find the **wrapped latency** which means the time interval from a transaction received to the transaction wrapped into a block. The sum of **wrapped latency** and **block commitment latency** could be regarded as **transaction commitment latency**. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Hey @Grivn, thanks for opening this issue. Currently we just have `consensus_block_interval_seconds` (the time between blocks) which I think is quite a basic metric and could definitely be further elaborated on. Off the top of my head it would be interesting to measure:
- time to reach consensus. That is specifically the time between receiving the proposal block to reaching 2/3+ precommits
- block propagation time. The time between the start of a round and receiving all the block parts to reconstruct the proposed block.

I know @williambanfield has been interesting in gathering more metrics (specifically on latencies from the application) so would be interested in his thoughts. AFAIK, **average wrapped latency** might be a bit more difficult but I believe we track the time we receive each transaction so perhaps it would be easy to measure the time between entering the mempool and when `Update` is called by consensus which flushes out all the committed transactions.
