### ISSUE TITLE
upnp: use syscall to get actual IP

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#712]
from https://github.com/tendermint/tendermint/blob/7682ad9a60162dd17fd6f61aeed7049a8635ac78/p2p/upnp/upnp.go#L8

and https://github.com/tendermint/tendermint/blob/09aed7ee89b88f56719aec88d7966beb510e6f06/p2p/listener.go#L199

see:
http://pastebin.com/9exZG4rh

**Comment by mdyring** [comment]
I'd prefer to see https://github.com/tendermint/tendermint/issues/758 (public ipv4 passed on cmdline) implemented before further UPnP improvements.

At least to bootstrap the network, validators will be needed and most of those won't run in a home (UPnP) environment.

**Comment by jackzampolin** [comment]
Closing this issue as resolved.
