### ISSUE TITLE
Osmosis outputs Tendermint logs "commit is for a block we do not know about"

### ISSUE THREAD

**Issue by thednaz** [tendermint/tendermint#7131]
Tendermint v0.34.12 / [Osmosis V4.0.0](https://github.com/osmosis-labs/osmosis/tree/v4.0.0)
OS: Alpine Linux v3.12.7

**What happened**:
I had a node running on Osmosis Mainnet, and after stopping the Osmosis process, I proceeded to back up the data directory. Subsequently I copied the data directory to a fresh node and launched the Osmosis binary; i.e. restoring from backup.

The node seemed to be fine, but for the first few minutes I saw a number of messages that said: `commit is for a block we do not know about`. After a few minutes these messages stop being printed. I've observed this behavior on both the sentry nodes and the validator nodes.

I'm working on a repro, but wanted to open the issue early and ask: is this a cause for concern? I assume not, as I see in the source that this just means information for a block has been received earlier than expected, and it makes a request to get that info. However, I'm not sure what's causing it, and I haven't seen this when doing similar backup/restore processes with other Tendermint protocols. 

[Logs](https://gist.github.com/thednaz/3174db8b28cd43318125481dce42f352)

**Comment by ValarDragon** [comment]
Can we make this a debug message?
