### ISSUE TITLE
Tracking: Pluggable custom event indexing

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7135]
☂️ This issue tracks requested improvements to the Tendermint event indexing interface.  Following on from the original implementation of [custom event indexing (ADR 065)][adr065], users have requested several further improvements. To satisfy these requests, we will need to do some further work on the custom indexing interfaces.

The requested improvements so far include the following (please update this list if you discover others):

- ✅ Preserve event structure and support more expressive queries (cf. #6843, addressed by #6868; also #3210).
- ⚪ Remove special cases and support plugging in additional indexer implementations (cf. #7044, #6584).
- ⚪ Make it easier to wire up custom indexers in the node configuration (cf. #7125).
- ⚪ Allow more detailed events to be indexed (cf. #3210, #7059).

To support these requests, there are several improvements we should pursue, including: Separating indexing (recording events) from querying, and decoupling internal service and lifecycle details from the indexing interface.

More detailed plans will be discussed and documented as a revision of ADR 065. More generally, the indexing subsystem interlocks tightly with both pubsub and the RPC service, addressing the need for clients to gain visibility into the status of state replication, so there are several important use cases to keep in mind for this design.

## References

- [RFC 012: Event Indexing Revisited](https://github.com/tendermint/tendermint/blob/master/docs/rfc/rfc-012-custom-indexing.md)

## Historical context

- #6032 Discusses more general concerns about data storage in Tendermint, including index storage.
- #3210 Discusses some of the motivations behind the current architecture.

[adr065]: https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-065-custom-event-indexing.md

**Comment by brennhill** [comment]
I think indexers themselves need a set of feature flags, so that teams can build custom indexers used to power APIs.

**Comment by creachadair** [comment]
My current thinking about how to handle custom indexers is to shift indexing entirely out of the process. Once we’ve made the event subscription RPC reliable enough to survive bursts and not lose messages, there will no longer be a need to privilege the block and tx event indexer to stall consensus inline.

By shifting the indexer out of process, we’d remove all the existing constraints on what events can be indexed, how they’re stored, how they’re queried, and even what language the indexer needs to be written in. The interface will no longer require compiling a modified consensus node nor any additional config settings.

All this still needs to be laid out in an RFC or ADR, which I plan to get back to once the more immediate work on pubsub and the RPC subsystem are further along. I’ll make sure to ping back once that’s available.

**Comment by brennhill** [comment]
Since I did a lot of investigation already on using postgres indexer, perhaps I could write something up for an RFC and you could comment?  Can you give me an ultra-high-level version of what it would need to discuss?

**Comment by brennhill** [comment]
In my mind, the tendermint process could either:
A. send events async to an in-process default indexer or 
B. send events async to an in-process pub/sub mechanism that in turn sends to an external process somehow, but the question in my mind is what should that method be?

Ideas:
Have a http serve indexing transmitter that sends events as POST using a JSON serialization of the data (not protobuf). This would allow any data structure that can be serialized to JSON to be sent and read by any language.  But I wonder if this would just be an overwhelming amount of traffic? But if sending full blocks it should be OK.
2. ???

Do you have any high-level thoughts about how we send all the data out of process in a way that's truly universal?

**Comment by creachadair** [comment]
For anyone interested in this topic, I wrote a draft [RFC 011: Event Subscription Revisited](https://github.com/tendermint/tendermint/pull/7784) that is intended to pull together some of the discussions on this topic, which are currently spread out across several issues.  Your feedback will be welcome.

The RFC discusses some of the high-level thoughts I've had about what we could do, but is not a definitive prescription.

**Comment by 0xF0D0** [comment]
Will this feature be ready in v0.36.x?

**Comment by 0xF0D0** [comment]
😢 Too bad. Looking forward to this feature.
Could you tell me when this would be implemented?

**Comment by marbar3778** [comment]
Provenance left an interesting comment that carries over to this. I think a better approach than having a pluggable design, but a proto service that streams out if enabled. Then users can write a process to listen on the other end. Basically like abci out of process apps.
