### ISSUE TITLE
Comments for functions that never error

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#715]
If a  function *never* returns an error, we should be able to avoid checking it. 

In such cases, we should add the following lines to the functions comment doc:

```
CONTRACT: Never returns an error
```

Sometimes functions need to have error return values to satisfy an interface, even though they never return them, like the hash functions, and like this one.

In these cases, either we use `// nolint`, or we use `_ := `. I'm not sure which is better. 

Is it possible to specify the `// nolint` on the function itself with respect to it's use ? like a special `// nolint-when-called` so the linter is off whenever the function is called. That'd be amazing.

Whatever we decide here, we should make it a coding standard, and use it while addressing the metalinter

**Comment by melekes** [comment]
I'd vote for `// nolint`. `_ :=` is ugly.

**Comment by ebuchman** [comment]
I tend to agree. Probably easier to `ack` for as well

**Comment by cloudhead** [comment]
This is odd to me - surely the types should be the contract?

**Comment by ebuchman** [comment]
Yes, but in some cases an interface method requires an error even though the implementation never errs, for instance the hash functions. 

Would you say we should just always check these errors, even if they never exist? It's surely more future proof, but lots of useless error checking in the meantime ...

**Comment by cloudhead** [comment]
Yeah I mean the problem is indeed that since the function can return an error without breaking compilation, we can be in a situation in the future where the function does return an error that is ignored and we end up in a nonsensical state that is hard to debug. Maybe something like this could work?

```go
val, err := shouldNeverReturnErrors()
cmn.PanicOnError(err)

// For side-effecting functions
cmn.PanicOnError(shouldNeverReturnError2())
```
It's not perfect but maybe better than ignoring the error.

**Comment by ebuchman** [comment]
Sounds like the right approach. @zramsay let's use cmn.PanicOnError(err) for functions that should never error. When upstream changes happen and errors are suddenly returned, our tests should panic. We will also need an effort to make sure every PanicOnError is test-covered!

**Comment by ebuchman** [comment]
moving to coding repo
