### ISSUE TITLE
Tracking: Tendermint RPC improvements

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7157]
☂️ This issue tracks some improvements to the Tendermint RPC interface targeting the v0.36 release. These are motivated by [RFC 002: Interprocess Communication in Tendermint](../blob/master/docs/rfc/rfc-002-ipc-ecosystem.md), but focused mainly on incremental changes that can be done to improve performance and reliability within the existing design.

## Planned Changes

- ✅ [Remove the deprecated gRPC interface to the RPC service](../pull/7121).
- ✅ [Strip down the base RPC client interface](../pull/6971).
- ✅ Decouple transport-specific plumbing from the client and server interfaces (#7725).
- ✅ Rationalize how parameters are encoded/decoded
    - ✅ [Remove the custom JSON encoding library](../pull/7673).
    - ✅ [Unify RPC method signatures and parameter decoding](../pull/8397).
- 🟡 Make the JSON-RPC implementation spec compliant (cf. #2949).

  Once the websocket interface is removed in Tendermint v0.37, the remaining service will be almost entirely spec-compliant, with the exception of a few corner cases that we can iron out as we go along.

- ✅ Rework subscription playback to be transactional (see #7801 and [ADR 075][adr075]).
    - ✅ https://github.com/tendermint/tendermint/pull/7825
    - ✅ https://github.com/tendermint/tendermint/pull/7930
    - ✅ https://github.com/tendermint/tendermint/pull/7965
    - ✅ https://github.com/tendermint/tendermint/pull/7974
    - ✅ https://github.com/tendermint/tendermint/pull/7981
    - ✅ https://github.com/tendermint/tendermint/pull/7982
    - ✅ https://github.com/tendermint/tendermint/pull/7986
    - ✅ https://github.com/tendermint/tendermint/pull/7987
    - ✅ https://github.com/tendermint/tendermint/pull/7993

- ❌ ~Deprecate and remove the HTTP GET (URI) interface~ (Abandoned: Too much depends on the GET interface, including many tutorials, to make this worthwhile. Instead clean up the implementation).

- ✅ Split the RPC endpoint to export event subscription separately from the rest of the service (see also #7156 and [ADR 075][adr075]).

  This is effectively done as of Tendermint v0.36. The existing websocket event subscription API remains in-place until Tendermint v0.37, but it can be selectively disabled by node operators (opt-in via `[rpc] experimental-disable-websocket = true`) and the ADR 075 interface can be protected separately by a proxy in the standard way.

- ⚪ Partition the RPC endpoints to give operators more control over which subsets of the service are exported, and possibly allow different addresses (requires discussion).

- ⚪ Make RPC method handlers responsive to deadlines per-endpoint rather than globally. Roughly, this means ensuring the request context is correctly plumbed through on both the clients and the server so that client-side cancellations can be detected (see also #8465).
    - ✅ #8570

[adr075]: https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-075-rpc-subscription.md

**Comment by Jmunb** [comment]
Do I understand correctly that the websocket interface will soon be removed? If so, what does this have to do with it?
