### ISSUE TITLE
API call /genesis include app_options

### ISSUE THREAD

**Issue by Greg-Szabo** [tendermint/tendermint#717]
Feature request.
I would like the /genesis API call to return the app_options portion of the initial genesis.json.

This is required for cosmos-ui to be able to automatically download the merged genesis.json file from the testnet.

Tendermint 0.11 (develop branch)
basecoin 0.7.0 (develop branch)

**Comment by melekes** [comment]
Thanks! Will do today.

**Comment by melekes** [comment]
Duplicate of #564
