### ISSUE TITLE
Attempting to replay a transaction can cause broadcast_tx_sync to hang

### ISSUE THREAD

**Issue by firelizzard18** [tendermint/tendermint#7185]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

v0.35.0-rc1, and the source in question has not changed up to v0.36.0-dev

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/AccumulateNetwork/accumulated

**Environment**:
- **OS** (e.g. from /etc/os-release): Gentoo Linux

**What happened**:

An application sends a transaction to `broadcast_tx_sync`. An application sends an identical transaction to `broadcast_tx_sync`. The call hangs.

**What you expected to happen**:

The call should not hang.

**Have you tried the latest version**:

I have verified that the relevant source has not changed up to v0.36.0-dev.

**Debugging:**

The error occurs whether I'm using the HTTP RPC client, or the local client. By using the local client and debugging, I have tracked down how this is occurring.

[`internal/rpc/core.Environment.BroadcastTxSync`](https://github.com/tendermint/tendermint/blob/v0.36.0-dev/internal/rpc/core/mempool.go#L35) is called:

```go
	resCh := make(chan *abci.Response, 1)
	err := env.Mempool.CheckTx(
		ctx.Context(),
		tx,
		func(res *abci.Response) { resCh <- res },
		mempool.TxInfo{},
	)
	if err != nil {
		return nil, err
	}

	res := <-resCh // <== this blocks forever if CheckTx returns nil but doesn't call the callback
```

This calls [`internal/mempool/v1.TxMempool.CheckTx`](https://github.com/tendermint/tendermint/blob/v0.36.0-dev/internal/mempool/v1/mempool.go#L229). **CheckTx returns `nil` on [line 273](https://github.com/tendermint/tendermint/blob/v0.36.0-dev/internal/mempool/v1/mempool.go#L273) without ever calling the callback**. Because CheckTx returns nil and does not call the callback, BroadcastTxSync hangs forever on the [channel read](https://github.com/tendermint/tendermint/blob/v0.36.0-dev/internal/rpc/core/mempool.go#L47).

**Comment by firelizzard18** [comment]
Until this is fixed, I'm going to use a fork that replaces `return nil` with `return types.ErrTxInCache`. That may not be the correct fix, but it is sufficient for our purposes. And it does fix the problem. https://github.com/AccumulateNetwork/tendermint/commit/9db021eaebd8fe5a3d457ad33ff1ab1128f2a5f7

**Comment by cmwaters** [comment]
Thanks for opening and debugging this issue @firelizzard18. Question: Is it just the second call that hangs or the first one as well? 

I'll have a look at this in more depth next week.

**Comment by firelizzard18** [comment]
By first and second do you mean the first time I broadcast the TX vs the second? Only the second call hangs. More precisely, if `internal/rpc/core.Environment.BroadcastTxSync` is called with a transaction that exactly matches a previous transaction, it hangs.

I'm not clear when/why `GetOrSetPeerByTxHash` would return a value (and thus `CheckTx` would return an error), but in my tests it always blocks.

**Comment by JayT106** [comment]
@cmwaters any update?

**Comment by creachadair** [comment]
I would expect #7714 (backported to v0.35.x in #7718) to have helped with this issue. If you haven't already, can you please try the latest v0.35.2 tag?
