### ISSUE TITLE
ValidatorSet: overflowing lengths cause runtime crashes in go-wire

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#722]
Found with go-fuzz, the inputs [1] below when fed into `*ValidatorSet.FromBytes` cause a runtime panic [2]

where the running code is
```go
package main

import "github.com/tendermint/tendermint/types"

func main() {
	vs := new(types.ValidatorSet)
	vs.FromBytes([]byte{0x01, 0x01, 0x30, 0x01, 0x06, 0x30, 0x30, 0x30, 0x30, 0x30,0x30})
}
```

[1] Inputs
```input
        inputs := [][]byte{
                {
                        0x01, 0x00, 0x00, 0x30,
                },
                {
                        0x01, 0x01, 0x30, 0x01, 0x06, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30,
                },
                {
                        0x01, 0x01, 0x02, 0x01, 0x01, 0x14, 0x5e, 0xbe, 0x09, 0x30, 0x40, 0xbe, 0x46, 0x15, 0x96, 0x0a,
                },
                {
                        0x01, 0x01, 0x03, 0x01, 0x01, 0x14, 0x89, 0xca, 0x3e, 0xfb, 0x67, 0x05, 0x07, 0xa7, 0x9d, 0xaf,
                        0xd0, 0x24, 0xdd, 0x8d, 0x11, 0xd0, 0x56, 0x16, 0xb3, 0x28, 0x01, 0xd3, 0xab, 0x48, 0xc9, 0x9a,
                        0xbc, 0x8f, 0x23, 0x93, 0xe8, 0xd3, 0x4c, 0x5c, 0x14, 0x41, 0x53, 0xaa, 0x46, 0x4e, 0x92, 0xf9,
                        0x81, 0xb7, 0xf0, 0x72, 0x8c, 0xaf, 0xae, 0xb5, 0x66, 0xe1, 0x25, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x00, 0x00, 0x64, 0xf2, 0x25, 0x07, 0x5d, 0x00, 0x00, 0x00, 0x64, 0x01, 0x01, 0x14, 0xe1, 0x56,
                        0x43, 0x9c, 0x68, 0x5a, 0x37, 0xf1, 0x75, 0x91, 0xa4, 0xac, 0xc4, 0x2a, 0xb3, 0xbd, 0x4a, 0x0a,
                        0xeb, 0xce, 0x01, 0x69, 0xf7, 0x30, 0xbb, 0xe1, 0x4e, 0x49, 0x71, 0xa0, 0xfd, 0x14, 0x7a, 0x0f,
                        0xeb, 0x1a, 0xa7, 0xd9, 0x4d, 0xae, 0x8b, 0x1a, 0x08, 0x20, 0x71, 0xab, 0x7f, 0x11, 0x16, 0x77,
                        0x24, 0xbb, 0xb7, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x00, 0x00, 0x64, 0x01, 0x01, 0x14, 0xf2, 0x55, 0x75, 0x8f, 0xc2, 0x91, 0xb1, 0xaf, 0x74, 0x5c,
                        0x45, 0x78, 0x00, 0x03, 0x54, 0x65, 0xb1, 0x23, 0x22, 0x6a, 0x01, 0x88, 0xa6, 0xae, 0xf2, 0x25,
                        0x07, 0x5d, 0x1b, 0x7f, 0x9f, 0x2c, 0x77, 0x30, 0x2a, 0xf7, 0x8f, 0x50, 0x3b, 0x60, 0xc4, 0x41,
                        0xd3, 0x11, 0x32, 0x65, 0x8a, 0xa9, 0x13, 0xd7, 0xe1, 0x0b, 0xc3, 0x00, 0x00, 0x00, 0x00, 0x00,
                        0x00, 0x01, 0xf4, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x38, 0x01, 0x05, 0x14, 0xf2, 0x55,
                        0x75, 0x8f, 0xc2, 0x91, 0xb1, 0xaf, 0x74, 0x5c, 0x45, 0x78, 0x00, 0x03, 0x54, 0x65, 0xb1, 0x23,
                        0x22, 0x6a, 0x01, 0x88, 0xa6, 0xae, 0xf2, 0x25, 0x07, 0x5d, 0x1b, 0x7f, 0x9f, 0x2c, 0x77, 0x30,
                        0x2a, 0xf7, 0x8f, 0x50, 0x3b, 0x60, 0xc4, 0x41, 0xd3, 0x11, 0x32, 0x65, 0x8a, 0xa9, 0x13, 0xd7,
                        0xe1, 0x0b, 0xc3, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xf4, 0xff, 0xff, 0xff, 0xff, 0xff,
                        0xff, 0xff, 0x38,
                },
        }
```

- Panic [2]
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.ReadByteSlice(0x1668ba0, 0xc4205488a0, 0x0, 0xc42018fee0, 0xc42018fef0, 0x86, 0xc420056601, 0x1432820)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/byteslice.go:30 +0x227
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.readReflectBinary(0x1471ce0, 0xc42055e080, 0x197, 0x1672200, 0x1471ce0, 0x1402dcf, 0x7, 0x0, 0x1471ce0, 0xc42000c160, ...)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/reflect.go:277 +0x1169
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.readReflectBinary(0x14a4060, 0xc42055e080, 0x199, 0x1672200, 0x14a4060, 0x1407c55, 0xa, 0x0, 0x1426580, 0xc42000c020, ...)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/reflect.go:317 +0xa96
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.readReflectBinary(0x1426580, 0xc420548870, 0x197, 0x1672200, 0x1426580, 0x1407c55, 0xa, 0x0, 0x1426580, 0xc42000c020, ...)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/reflect.go:292 +0xf53
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.readReflectBinary(0x1492be0, 0xc420548870, 0x199, 0x1672200, 0x1492be0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/reflect.go:317 +0xa96
github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire.ReadBinary(0x14d23c0, 0xc420548870, 0x1668ba0, 0xc4205488a0, 0x0, 0xc42018fee0, 0xc42018fef0, 0xc42018ff00, 0x1012e38)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/vendor/github.com/tendermint/go-wire/wire.go:31 +0x32e
github.com/tendermint/tendermint/types.(*ValidatorSet).FromBytes(0xc420548870, 0xc420564000, 0xb, 0x20b)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/types/validator_set.go:308 +0xd0
main.main()
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/fuzz/types/validatorSet/repro/main.go:22 +0x142
exit status 2
where:

length value is: 52983525027888
lmt: 0

We should fix go-wire to and add Fuzz anti-regression tests with a diff like this
```diff
diff --git a/byteslice.go b/byteslice.go
index f46db44..378bb7e 100644
--- a/byteslice.go
+++ b/byteslice.go
@@ -2,6 +2,7 @@ package wire
 
 import (
 	"io"
+	"math"
 
 	cmn "github.com/tendermint/tmlibs/common"
 )
@@ -20,6 +21,10 @@ func ReadByteSlice(r io.Reader, lmt int, n *int, err *error) []byte {
 		*err = ErrBinaryReadInvalidLength
 		return nil
 	}
+	if length >= math.MaxInt32 {
+		*err = ErrBinaryReadOverflow
+		return nil
+	}
 	if lmt != 0 && lmt < cmn.MaxInt(length, *n+length) {
 		*err = ErrBinaryReadOverflow
 		return nil
```

**Comment by odeke-em** [comment]
I've filed it here to coordinate with go-wire's https://github.com/tendermint/go-wire/issues/37 so that we update both.

**Comment by ebuchman** [comment]
Where is this even used? Can we just delete the function?

**Comment by odeke-em** [comment]
You have great judgement @ebuchman! In deed, we don't seem to be using it anywhere. Sure, let's delete that code. When we do so, I'll then close https://github.com/tendermint/tendermint/pull/742.

**Comment by ebuchman** [comment]
https://github.com/tendermint/tendermint/commit/e76ef2a8a134b282af038a572e829ff4e4bb4eea
