### ISSUE TITLE
Normalize slashing penalties by total supply

### ISSUE THREAD

**Issue by tmckenzie51** [tendermint/tendermint#7240]
## Proposal and Problem Description

@cwgoes @alexanderbez  brought this up a while ago. A brief description from the original post is copied here:

"I think we might want to normalize slashing amounts by the total supply. Currently, the spec calculates slashing amounts in proportion to validator shares, which are just bonded tokens.

In between when an equivocation is made and when it is discovered, the total token supply will change due to inflation. This would have the strange property that later discovery of evidence means a (slightly) lesser penalty, since the tokens which would have been burned if the evidence was discovered earlier can be inflated as usual until the evidence is actually discovered.

With our current unbonding period and inflation parameters, the difference is minimal, but we (or governance) might want to change those parameters in the future.

If we change the calculation to slashedTokens = slashFraction * totalBondedTokensNow * (validatorBondedTokensAtEquivocation / totalBondedTokensAtEquivocation), it changes the semantics to "slashed as if the validator double-signed now with the power they had at the time of equivocation", and means that slashing penalties are just as severe if evidence is discovered when the unbonding period is almost over as if it were discovered immediately."

See more details and a thread [ here](https://github.com/cosmos/gaia/issues/30#issue-450954894)
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Interesting idea. I think this issue is better suited to the Cosmos SDK. Tendermint has no concept of slashing it just sends evidence of misbehaviour over to the application to handle. I will see if I can transfer it over.

**Comment by cmwaters** [comment]
Turns out I can't transfer it across organizations (which kinda makes sense) so I'm going to close it here and you can open it over on the [Cosmos SDK](https://github.com/cosmos/cosmos-sdk/issues/new/choose)

**Comment by tmckenzie51** [comment]
@cmwaters I realized that I didn't understand the issue well enough. I think that what we need in order to make this proposal possible on our end is to have a `total_voting_power field ` added in order to obtain evidence that can be used modify the SDK's slashing logic. Should I open up a new issue for this specific request?

**Comment by cmwaters** [comment]
Would this be returned via ABCI? It's not feasible to track total validator power in the SDK already?
