### ISSUE TITLE
Immediate block creation

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#728]
Feature request:

In contrast to the fixed interval block creation, I'd like to suggest a configuration option that will initiates consensus -> block creation as soon as a TX is waiting in the mempool.

Even though there will be some traffic/storage overhead related to this, I think this is a useful for zones where there is a desire for lower latency. One such example would be the DEX.

**Comment by melekes** [comment]
m? that was implemented in 0.10.3 - https://github.com/tendermint/tendermint/blob/master/CHANGELOG.md#0103-august-10-2017

```
new flag, --consensus.create_empty_blocks; when set to false, blocks are only created when there are txs or when the AppHash changes.
```

or you are talking about something else?

**Comment by zramsay** [comment]
it's documented a bit better here: https://github.com/tendermint/tendermint/blob/develop/docs/using-tendermint.rst#no-empty-blocks

**Comment by mdyring** [comment]
Sorry, maybe I wasn't clear. This is not related to if a block can be empty or not.

What I am is that once the proposer sees a TX that could be included in a block, it immediate starts prevote instead of waiting for X seconds.

Not sure what name best describes the option, but I guess "low latency block interval" is not wildly inaccurate. Or maybe "immediate block creation".

The idea is that in zones where there is an active market (and thus it is desirable to to lower the latency to narrow the spread), it might be a meaningful tradeoff to try to create a block immediately instead of waiting X seconds.

It would also make sense in payment systems where you want finality as soon as possible, and not at a fixed time interval.

**Comment by melekes** [comment]
> The idea is that once the proposer sees a TX that could be included in a block (passes CheckTx)

that is exactly how it works right now with `--consensus.create_empty_blocks` turned on

**Comment by mdyring** [comment]
Ah! Somehow I missed the "empty" in create_**empty**_blocks_interval.

Was this always the case, that the interval was is ignored if there are TXs available? Somehow I remember it differently, so that TXs were queued until the next block interval.

Anyway, intuitively, this should also be the same behavior with create_empty_blocks=false? Is that the case?

**Comment by mdyring** [comment]
Answer my own question and closing. Reminder to self: RTFM.

"
To configure tendermint to not produce empty blocks unless there are txs or the app hash changes, run tendermint with this additional flag:

tendermint node --consensus.create_empty_blocks=false
"
