### ISSUE TITLE
light: update model-based tests

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7280]
It seems from conversations held in #6915 that the model based tests are out of date and new tooling is being used. We should update the light client model-based tests and make sure that any future changes to structs like the header or commit can also be incorporated.

https://github.com/tendermint/tendermint/issues/6915#issuecomment-952880137_

cc @andrey-kuprianov

**Comment by andrey-kuprianov** [comment]
Thank you for opening an issue! We are finishing MBT plugin for Go this quarter, so next quarter we'll take care of updating LightClient model-based tests to the new tooling. 

For now please just disable the tests.
