### ISSUE TITLE
Use of unconditional_peers_ids to guarantee connection

### ISSUE THREAD

**Issue by jennyhys** [tendermint/tendermint#7295]
We are trying to form a connection between two nodes by including each node id, IP in each other's `persistent_peers` and `unconditional_peers_ids` list in the `config.toml` , yet they are still not connecting(by running `curl -s localhost:26657/net_info | jq .result.peers`) after this configuration has been used. Did we configure anything wrong? Or is there any extra configuration needed to gurantee their connection(assumed both servers are online and tendermint is running). 

Please advise, thank you!

**Comment by williambanfield** [comment]
Hey @jennyhys, are you able to confirm that both ends of the connection are able to reach each other at the hostname/port specified using something like `telnet`? Beyond that, your logs should help further determine what may be the issue, can you include a snippet or your p2p logs that may indicate the error?

**Comment by jennyhys** [comment]
Hey @williambanfield yes they are able to reach each other and connect to each other eventually, but it usually takes a long time(Osmosis halted their chain daily and once the chain start progressing again some node takes a while to begin catching up as they couldn't connect to any peer), it kept getting this error `Ensure peers module=pex numDialing=10 numInPeers=0 numOutPeers=0 numToDial=0` even we have added their peer id to the `unconditional_peers_ids`, and updated the `persistent_peers_max_dial_period` to 1s to disable exponential backoff

**Comment by williambanfield** [comment]
`unconditional_peer_ids` are peers that you will always try to connect to no matter what, but if the peer is not responsive within a time, then you will not get a connection, regardless of which field you put the peer into. If you see indication in the logs that Tendermint is dialing the peer ID you specified and then see failures for that peer ID, you may need to debug the network connection.
