### ISSUE TITLE
rollback leads to an invalid state

### ISSUE THREAD

**Issue by tzemanovic** [tendermint/tendermint#7304]
Related issue: #7123

**Tendermint version**: master and `0.34.14`

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/anoma/anoma

**What happened**: I'm trying to use the new `tendermint rollback` version with the Anoma app. However, it seems that the command leads to an invalid state in Tendermint in the replay of the block:

```
Error: error during handshake: error on replay: block time 2021-11-22 14:22:01.19637851 +0000 UTC not greater than last block time 2021-11-22 14:22:01.19637851+0000 UTC
```

Note that we are also rolling back the apps state, however the error is coming Tendermint's side with Tendermint's node state.

The `LastBlockTime` in the `State` seems to be using the value as the current block (i.e. it's not being rolled back to the predecessor block).

**What you expected to happen**: The Tendermint state should roll back to a consistent predecessor block from which it's possible to restart the node and replay the last block.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible): Run rollback and restart the node

**Comment by cmwaters** [comment]
> The LastBlockTime in the State seems to be using the value as the current block (i.e. it's not being rolled back to the predecessor block).

Ah nice catch! 

We've unfortunately not really properly tested this feature because we've wanted to coordinate with the SDK as the application also needs to be able to rollback (well depending on when the crash happened it might not need to rollback).

**Comment by cmwaters** [comment]
I'm going to close this issue as being solved by https://github.com/tendermint/tendermint/pull/7315. Let me know @tzemanovic if you experience any other related issues.
