### ISSUE TITLE
Use `uint64` for block height everywhere

### ISSUE THREAD

**Issue by silasdavis** [tendermint/tendermint#731]
ABCI uses a `uint64` height on `EndBlock`: https://github.com/tendermint/abci/blob/master/types/application.go#L22 as does https://github.com/tendermint/tendermint/blob/master/types/tx.go#L119. However `Block` and `BlockStore` use `int` heights: https://github.com/tendermint/tendermint/blob/master/types/block.go#L161.

Assuming a one second block time this means on a 32-bit architecture a Tendermint chain can only live 68 years, which is _just_ under the worldwide mean life expectancy for a male. Surely a Tendermint chain should live longer!

I am taking heights to be `uint64` in Burrow and it would be nice to make things consistent across Tendermint, and avoid the casting, and use `uint64` everywhere there is a height...

**Comment by adrianbrink** [comment]
@ebuchman Should we update all `uint` to `uint64`?

**Comment by silasdavis** [comment]
@adrianbrink note it is currently `int` and not `uint`

**Comment by zramsay** [comment]
relevant blogpost: https://medium.com/@anton.kalyaev/choosing-a-type-for-blockchain-height-beware-of-unsigned-integers-714804dddf1d
