### ISSUE TITLE
tx indexer miss block when restart

### ISSUE THREAD

**Issue by yihuang** [tendermint/tendermint#7312]
**Tendermint v0.34.14**

**ABCI app**

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

We found that our node miss some tx indexes for certain blocks.
When investigating the code, we found a case that when you stop the node while the tx indexer is indexing a block, that block won't be picked up again after the restart, and it won't be indexed ever.

**What you expected to happen**:

tx indexer should index all the blocks.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):

1. Patch `v0.34.14` like this for easier reproduction.

```diff
--- a/state/txindex/indexer_service.go
+++ b/state/txindex/indexer_service.go
@@ -2,6 +2,7 @@ package txindex

 import (
        "context"
+       "time"

        "github.com/tendermint/tendermint/libs/service"
        "github.com/tendermint/tendermint/state/indexer"
@@ -61,6 +62,7 @@ func (is *IndexerService) OnStart() error {
                        eventDataHeader := msg.Data().(types.EventDataNewBlockHeader)
                        height := eventDataHeader.Header.Height
                        batch := NewBatch(eventDataHeader.NumTxs)
+                       is.Logger.Error("[debug] start index block", "height", height)

                        for i := int64(0); i < eventDataHeader.NumTxs; i++ {
                                msg2 := <-txsSub.Out()
@@ -82,11 +84,14 @@ func (is *IndexerService) OnStart() error {
                                is.Logger.Info("indexed block", "height", height)
                        }

+                       time.Sleep(time.Second)
                        if err = is.txIdxr.AddBatch(batch); err != nil {
                                is.Logger.Error("failed to index block txs", "height", height, "err", err)
                        } else {
                                is.Logger.Debug("indexed block txs", "height", height, "num_txs", eventDataHeader.NumTxs)
                        }
+
+                       is.Logger.Error("[debug] finish index block", "height", height)
                }
        }()
        return nil
```

2. Start devnet, and randomly restart the node.
3. You can observe logs similar to this:
```
...
2:16PM ERR [debug] start index block height=62 module=txindex server=node
2:16PM ERR [debug] start index block height=63 module=txindex server=node
2:16PM ERR [debug] finish index block height=63 module=txindex server=node
...
```

It means block 62 is not indexed.

**Comment by JayT106** [comment]
I think https://github.com/tendermint/tendermint/pull/7231 solves it. If we shut down the node when it is indexing tx/block. It will reindex the missing block when the node is doing ABCI Handshake
@creachadair would it be possible to backport it into v0.34/v0.35?

**Comment by creachadair** [comment]
> I think #7231 solved this issue. Once the node has been rebooting. It will reindex the missing block during the ABCI Handshake.
> 
> @creachadair would it be possible to backport it into v0.34/v0.35?

It might be possible to backport into v0.35, but I'll have to check API compatibility. It is not practical for v0.34.

**Comment by JayT106** [comment]
> > I think #7231 solved this issue. Once the node has been rebooting. It will reindex the missing block during the ABCI Handshake.
> > @creachadair would it be possible to backport it into v0.34/v0.35?
> 
> It might be possible to backport into v0.35, but I'll have to check API compatibility. It is not practical for v0.34.

Sounds good! thanks!

**Comment by yzang2019** [comment]
This issue still not fixed, the missing tx issue after restart still exists even after applying the patch mentioned in https://github.com/tendermint/tendermint/pull/7231
