### ISSUE TITLE
Unable to fetch snapshots from rpc server list

### ISSUE THREAD

**Issue by sunnyk56** [tendermint/tendermint#7313]
I have set up two full nodes with Enabling State Sync Snapshots by setting configuration in app.toml

pruning-keep-recent = "100"
pruning-keep-every = "500"
pruning-interval = "10"

[state-sync]

snapshot-interval = 500

snapshot-keep-recent = 4

and I am able to see snapshots  in  $TMHOME/data/snapshots like
**18500  19000  19500  20000  metadata.db**

Then trying to set up State Syncing a Node using these snapshots and set configuration in config.toml

enable = true
rpc_servers = "188.166.98.209:26657,188.166.62.34:26657"
trust_height = 19738
trust_hash = "59C41D429F96FC6B11C0BBB5BE8EE91FE0B4BE53A70CAF58A8CF453EC9976FA7"
trust_period = "336h"
discovery_time = "20s"

and getting logs as  trying  Discovering snapshots for 20s again and again

1:34PM INF starting ABCI with Tendermint
1:34PM INF Starting multiAppConn service impl=multiAppConn module=proxy
1:34PM INF Starting localClient service connection=query impl=localClient module=abci-client
1:34PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
1:34PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
1:34PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
1:34PM INF Starting EventBus service impl=EventBus module=events
1:34PM INF Starting PubSub service impl=PubSub module=pubsub
1:34PM INF Starting IndexerService service impl=IndexerService module=txindex
1:34PM INF Version info block=11 p2p=8 software=
1:34PM INF This node is not a validator addr=DE3C62FFA185ADFA83B3589DD3A41358E6617D32 module=consensus pubKey=LsLerLwAswXBsuP9v9immSOt8MZojqRc3oVXnAF2sYk=
1:34PM INF P2P Node ID ID=dae70f91d6f01ccbd56bf0d6bd730047de0eaae4 file=/root/.onomy/config/node_key.json module=p2p
1:34PM INF Adding persistent peers addrs=[] module=p2p
1:34PM INF Adding unconditional peer ids ids=[] module=p2p
1:34PM INF Add our address to book addr={"id":"dae70f91d6f01ccbd56bf0d6bd730047de0eaae4","ip":"0.0.0.0","port":26656} book=/root/.onomy/config/addrbook.json module=p2p
1:34PM INF Add our address to book addr={"id":"dae70f91d6f01ccbd56bf0d6bd730047de0eaae4","ip":"0.0.0.0","port":26656} book=/root/.onomy/config/addrbook.json module=p2p
1:34PM INF Starting Node service impl=Node
1:34PM INF Starting pprof server laddr=localhost:6060
1:34PM INF Starting P2P Switch service impl="P2P Switch" module=p2p
1:34PM INF Starting PEX service impl=PEX module=pex
1:34PM INF Starting AddrBook service book=/root/.onomy/config/addrbook.json impl=AddrBook module=p2p
1:34PM INF Starting RPC HTTP server on [::]:26657 module=rpc-server
1:34PM INF Starting Mempool service impl=Mempool module=mempool
1:34PM INF Starting BlockchainReactor service impl=BlockchainReactor module=blockchain
1:34PM INF Starting Consensus service impl=ConsensusReactor module=consensus
1:34PM INF Reactor  module=consensus waitSync=true
1:34PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=0 numToDial=10
1:34PM INF No addresses to dial. Falling back to seeds module=pex
1:34PM INF Starting Evidence service impl=Evidence module=evidence
1:34PM INF Starting StateSync service impl=StateSync module=statesync
1:34PM INF Dialing peer address={"id":"94dbdea539bdc450962c2e94f2bd0f45a6381485","ip":"144.126.222.34","port":26656} module=p2p
1:34PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:34PM INF Starting state sync module=statesync
1:34PM INF Downloading trusted light block using options module=light
1:34PM INF Starting Peer service impl="Peer{MConn{144.126.222.34:26656} 94dbdea539bdc450962c2e94f2bd0f45a6381485 out}" module=p2p peer={"id":"94dbdea539bdc450962c2e94f2bd0f45a6381485","ip":"144.126.222.34","port":26656}
1:34PM INF Starting MConnection service impl=MConn{144.126.222.34:26656} module=p2p peer={"id":"94dbdea539bdc450962c2e94f2bd0f45a6381485","ip":"144.126.222.34","port":26656}
1:34PM INF Added peer module=p2p peer={"Data":{},"Logger":{}}
1:34PM INF Discovering snapshots for 20s module=statesync
1:34PM INF starting API server... module=api-server
1:34PM INF Starting RPC HTTP server on [::]:1317 module=api-server
1:34PM INF Discovering snapshots for 20s module=statesync
1:34PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:34PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:34PM INF No addresses to dial. Falling back to seeds module=pex
1:34PM INF Discovering snapshots for 20s module=statesync
1:35PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:35PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:35PM INF No addresses to dial. Falling back to seeds module=pex
1:35PM INF Discovering snapshots for 20s module=statesync
1:35PM INF Discovering snapshots for 20s module=statesync
1:35PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:35PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:35PM INF No addresses to dial. Falling back to seeds module=pex
1:35PM INF Discovering snapshots for 20s module=statesync
1:36PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:36PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:36PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:36PM INF No addresses to dial. Falling back to seeds module=pex
1:36PM INF Discovering snapshots for 20s module=statesync
1:36PM INF Discovering snapshots for 20s module=statesync
1:36PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:36PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:36PM INF No addresses to dial. Falling back to seeds module=pex
1:36PM INF Discovering snapshots for 20s module=statesync
1:37PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:37PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:37PM INF No addresses to dial. Falling back to seeds module=pex
1:37PM INF Discovering snapshots for 20s module=statesync
1:37PM INF Discovering snapshots for 20s module=statesync
1:37PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:37PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:37PM INF No addresses to dial. Falling back to seeds module=pex
1:37PM INF Discovering snapshots for 20s module=statesync
1:38PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:38PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:38PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:38PM INF No addresses to dial. Falling back to seeds module=pex
1:38PM INF Discovering snapshots for 20s module=statesync
1:38PM INF Discovering snapshots for 20s module=statesync
1:38PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:38PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:38PM INF No addresses to dial. Falling back to seeds module=pex
1:38PM INF Discovering snapshots for 20s module=statesync
1:39PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:39PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:39PM INF No addresses to dial. Falling back to seeds module=pex
1:39PM INF Discovering snapshots for 20s module=statesync
1:39PM INF Discovering snapshots for 20s module=statesync
1:39PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:39PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:39PM INF No addresses to dial. Falling back to seeds module=pex
1:39PM INF Discovering snapshots for 20s module=statesync
1:40PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:40PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:40PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:40PM INF No addresses to dial. Falling back to seeds module=pex
1:40PM INF Discovering snapshots for 20s module=statesync
1:40PM INF Discovering snapshots for 20s module=statesync
1:40PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:40PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:40PM INF No addresses to dial. Falling back to seeds module=pex
1:40PM INF Discovering snapshots for 20s module=statesync
1:41PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:41PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:41PM INF No addresses to dial. Falling back to seeds module=pex
1:41PM INF Discovering snapshots for 20s module=statesync
1:41PM INF Discovering snapshots for 20s module=statesync
1:41PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:41PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:41PM INF No addresses to dial. Falling back to seeds module=pex
1:41PM INF Discovering snapshots for 20s module=statesync
1:42PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:42PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:42PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:42PM INF No addresses to dial. Falling back to seeds module=pex
1:42PM INF Discovering snapshots for 20s module=statesync
1:42PM INF Discovering snapshots for 20s module=statesync
1:42PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:42PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:42PM INF No addresses to dial. Falling back to seeds module=pex
1:42PM INF Discovering snapshots for 20s module=statesync
1:43PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:43PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:43PM INF No addresses to dial. Falling back to seeds module=pex
1:43PM INF Discovering snapshots for 20s module=statesync
1:43PM INF Discovering snapshots for 20s module=statesync
1:43PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:43PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:43PM INF No addresses to dial. Falling back to seeds module=pex
1:43PM INF Discovering snapshots for 20s module=statesync
1:44PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:44PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:44PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:44PM INF No addresses to dial. Falling back to seeds module=pex
1:44PM INF Discovering snapshots for 20s module=statesync
1:44PM INF Discovering snapshots for 20s module=statesync
1:44PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:44PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:44PM INF No addresses to dial. Falling back to seeds module=pex
1:44PM INF Discovering snapshots for 20s module=statesync
1:45PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:45PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:45PM INF No addresses to dial. Falling back to seeds module=pex
1:45PM INF Discovering snapshots for 20s module=statesync
1:45PM INF Discovering snapshots for 20s module=statesync
1:45PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:45PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:45PM INF No addresses to dial. Falling back to seeds module=pex
1:45PM INF Discovering snapshots for 20s module=statesync
1:46PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:46PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:46PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:46PM INF No addresses to dial. Falling back to seeds module=pex
1:46PM INF Discovering snapshots for 20s module=statesync
1:46PM INF Discovering snapshots for 20s module=statesync
1:46PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:46PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:46PM INF No addresses to dial. Falling back to seeds module=pex
1:46PM INF Discovering snapshots for 20s module=statesync
1:47PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:47PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:47PM INF No addresses to dial. Falling back to seeds module=pex
1:47PM INF Discovering snapshots for 20s module=statesync
1:47PM INF Discovering snapshots for 20s module=statesync
1:47PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:47PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:47PM INF No addresses to dial. Falling back to seeds module=pex
1:47PM INF Discovering snapshots for 20s module=statesync
1:48PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:48PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:48PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:48PM INF No addresses to dial. Falling back to seeds module=pex
1:48PM INF Discovering snapshots for 20s module=statesync
1:48PM INF Discovering snapshots for 20s module=statesync
1:48PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:48PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:48PM INF No addresses to dial. Falling back to seeds module=pex
1:48PM INF Discovering snapshots for 20s module=statesync
1:49PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:49PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:49PM INF No addresses to dial. Falling back to seeds module=pex
1:49PM INF Discovering snapshots for 20s module=statesync
1:49PM INF Discovering snapshots for 20s module=statesync
1:49PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:49PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:49PM INF No addresses to dial. Falling back to seeds module=pex
1:49PM INF Discovering snapshots for 20s module=statesync
1:50PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:50PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:50PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:50PM INF No addresses to dial. Falling back to seeds module=pex
1:50PM INF Discovering snapshots for 20s module=statesync
1:50PM INF Discovering snapshots for 20s module=statesync
1:50PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:50PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:50PM INF No addresses to dial. Falling back to seeds module=pex
1:50PM INF Discovering snapshots for 20s module=statesync
1:51PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:51PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:51PM INF No addresses to dial. Falling back to seeds module=pex
1:51PM INF Discovering snapshots for 20s module=statesync
1:51PM INF Discovering snapshots for 20s module=statesync
1:51PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:51PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:51PM INF No addresses to dial. Falling back to seeds module=pex
1:51PM INF Discovering snapshots for 20s module=statesync
1:52PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:52PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:52PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:52PM INF No addresses to dial. Falling back to seeds module=pex
1:52PM INF Discovering snapshots for 20s module=statesync
1:52PM INF Discovering snapshots for 20s module=statesync
1:52PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:52PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:52PM INF No addresses to dial. Falling back to seeds module=pex
1:52PM INF Discovering snapshots for 20s module=statesync
1:53PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:53PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:53PM INF No addresses to dial. Falling back to seeds module=pex
1:53PM INF Discovering snapshots for 20s module=statesync
1:53PM INF Discovering snapshots for 20s module=statesync
1:53PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:53PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:53PM INF No addresses to dial. Falling back to seeds module=pex
1:53PM INF Discovering snapshots for 20s module=statesync
1:54PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:54PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:54PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:54PM INF No addresses to dial. Falling back to seeds module=pex
1:54PM INF Discovering snapshots for 20s module=statesync
1:54PM INF Discovering snapshots for 20s module=statesync
1:54PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:54PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:54PM INF No addresses to dial. Falling back to seeds module=pex
1:54PM INF Discovering snapshots for 20s module=statesync
1:55PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:55PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:55PM INF No addresses to dial. Falling back to seeds module=pex
1:55PM INF Discovering snapshots for 20s module=statesync
1:55PM INF Discovering snapshots for 20s module=statesync
1:55PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:55PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:55PM INF No addresses to dial. Falling back to seeds module=pex
1:55PM INF Discovering snapshots for 20s module=statesync
1:56PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:56PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:56PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:56PM INF No addresses to dial. Falling back to seeds module=pex
1:56PM INF Discovering snapshots for 20s module=statesync
1:56PM INF Discovering snapshots for 20s module=statesync
1:56PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:56PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:56PM INF No addresses to dial. Falling back to seeds module=pex
1:56PM INF Discovering snapshots for 20s module=statesync
1:57PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:57PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:57PM INF No addresses to dial. Falling back to seeds module=pex
1:57PM INF Discovering snapshots for 20s module=statesync
1:57PM INF Discovering snapshots for 20s module=statesync
1:57PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:57PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:57PM INF No addresses to dial. Falling back to seeds module=pex
1:57PM INF Discovering snapshots for 20s module=statesync
1:58PM INF Saving AddrBook to file book=/root/.onomy/config/addrbook.json module=p2p size=0
1:58PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:58PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:58PM INF No addresses to dial. Falling back to seeds module=pex
1:58PM INF Discovering snapshots for 20s module=statesync
1:58PM INF Discovering snapshots for 20s module=statesync
1:58PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:58PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:58PM INF No addresses to dial. Falling back to seeds module=pex
1:58PM INF Discovering snapshots for 20s module=statesync
1:59PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:59PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:59PM INF No addresses to dial. Falling back to seeds module=pex
1:59PM INF Discovering snapshots for 20s module=statesync
1:59PM INF Discovering snapshots for 20s module=statesync
1:59PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=1 numToDial=9
1:59PM INF We need more addresses. Sending pexRequest to random peer module=pex peer={"Data":{},"Logger":{}}
1:59PM INF No addresses to dial. Falling back to seeds module=pex

@antho1404 @davebryson  could you guys help us

**Comment by cmwaters** [comment]
Hey @sunnyk56, do you have those same nodes that are saving snapshots as persistent peers for the node that you're trying to bootstrap?

**Comment by sunnyk56** [comment]
Thanks, @cmwaters for your response. Yes, these are the same nodes that are saving snapshots. Now this has been solved I was using Tendermint v0.34.8 but when I tried with v0.34.14 then it's working fine

**Comment by PhuongDo0712** [comment]
I'm currently using v0.34.14 and I still have this problem

**Comment by joshcaskiefoundry** [comment]
I'm using `github.com/tendermint/tendermint@v0.34.19` and have this problem
