### ISSUE TITLE
Genesis Block / config/genesis.json

### ISSUE THREAD

**Issue by puneetsingh166** [tendermint/tendermint#7364]
HI ,
I am defining my concern in few steps-

1- I have a genesis file in this location ```$BINARY/config/genesis.json```.
2- Started the chain with ```$BINARY/config/genesis.json``` file.
3- When I hit rpc url ```http://ip:26657/genesis?```. I was getting the same genesis file data which was in ```$BINARY/config/genesis.json```.
4 - Then I stop the chain, make some changes to ```$BINARY/config/genesis.json``` and start the chain again.
5 - When I hit rpc url again ```http://ip:26657/genesis?```. that time the updated genesis file was not found. I found the old genesis, which was when the chain first time started.

The question is - when I am hitting rpc tendermint url - ```http://ip:26657/genesis?```.where is this genesis data coming from?

Please help regarding it.

**Comment by marbar3778** [comment]
Hey, was the chain that you ran previously reset?

**Comment by puneetsingh166** [comment]
> Hey, was the chain that you ran previously reset?

HI @marbar3778 no ,
I just want to update genesis  without reset chain. Or want to know cache location where is this genesis data coming from? When hitting rpc url.

The exact location where all blockheight, genesis data is saved after the chain starts.

**Comment by marbar3778** [comment]
Once a chain starts the genesis file is saved, to change it you will need to start a fresh chain.

**Comment by puneetsingh166** [comment]
> this is where its cached https://github.com/tendermint/tendermint/blob/master/internal/rpc/core/env.go#L88
The genesis file is saved in the cache at all times while the chain is running?? 
 
Or  saved in ```$HOME/.tendermint/data ``` directory??

**Comment by puneetsingh166** [comment]
@marbar3778 Pease help.

**Comment by marbar3778** [comment]
Hey, modifying the genesis file after the chain has started should not be done unless restarted. This is not what a blockchain does. Unfortunatly after starting the chain, the genesis is saved and won't be modifiable, unless you go into the data directory but it won't change anything on chain.

**Comment by puneetsingh166** [comment]
@marbar3778 Thank you so much

**Comment by marbar3778** [comment]
Happy to help with any further questions in discord 😄 You can tag marbar in your question

**Comment by lhtvineettiwari** [comment]
@marbar3778 even after restarting the network (Stopped the chain and then start it again), Still having the same genesis file data. Could you help me out here ?
