### ISSUE TITLE
blockstore: propagate errors instead of panicking

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7366]
## Summary

The blockstore panics whenever it comes across an error in saving, loading or marshalling data. We should handle these panics by propagating the error back up to the caller to handle as they wish. For comparison, we currently do this with the statestore.

## Proposal

Replace panics with errors

Ref: https://github.com/tendermint/tendermint/issues/4465

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by championshuttler** [comment]
Can i work on it @cmwaters if you can mentor me and tell me where to do it?? Thanks

**Comment by cmwaters** [comment]
Sure @championshuttler, you can try open a draft PR and I can review it. You should have a look at the state store as a reference. There are still going to be times were we want to panic (i.e. when unmarshalling a struct fails). And we may also want to halt a node when consensus fails to save a block.

**Comment by thanethomson** [comment]
@championshuttler are you still going to work on this? Otherwise I can take over if you don't have capacity.

**Comment by binjamil** [comment]
Can I take on this if this issue is still open? This will be my first open source contribution so really looking forward to it

**Comment by mehrankamal** [comment]
Hi @cmwaters can you have a look into the PR and let me know if I am going correct direction. Current test state is broken, I'll fix it once you let me know if I am directed to correct direction. Thanks!

**Comment by cmwaters** [comment]
Hey @mehrankamal, thanks for opening the PR - I'll try look over it this evening.
