### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#738]
Feature request.

IPv6 support for the P2P layer.

I believe this should be a high priority to get implemented before launch (and ideally sooner for the sake of test nets) due to IPv4 address space exhaustion. For people who will be co-locating validator nodes, IPv4 may no longer be a viable option.

Discussed briefly with @adrianbrink, he believe this affects mainly command-line and config file parser as well as P2P layer (go-wire).

As a nice-to-have the RPC and ABCI stuff could be IPv6 enabled (if it isn't already), but this seems less urgent as it can be worked around (IPv4 localhost for ABCI or HTTP proxy for the RPC stuff).

**Comment by mdyring** [comment]
I think this should be a priority to get working on Gaia **before** launch, in case it turns out to be a breaking change to the PEX.

**Comment by mdyring** [comment]
Is this no longer a priority before Cosmos launch?

I really think it should be, in case it requires breaking changes to the wire protocol.

**Comment by aertoria** [comment]
Is this till a priority? Today I've been trying tendermint v0.20, is ipv6 been supported there?

**Comment by mdyring** [comment]
@xla would be good to clarify if any changes to the wire protocol (specifically peer exchange) will be required to support this?

Would suck if this introduced breaking changes after launch.

**Comment by ebuchman** [comment]
Let's reconsider this after some of the p2p refactors ongoing in https://github.com/tendermint/tendermint/pull/1710

We plan to have a versioning scheme that will allow us to roll this out in a backwards compatible way - ie. peers using IPv6 wont send IPv6 addresses to peers that cant understand them

**Comment by melekes** [comment]
Basic support was implemented in https://github.com/tendermint/tendermint/pull/1818.

**Comment by mdyring** [comment]
Closing as we have IPv6 network up and running for gaia-8001.

Seems to be well supported these days, only improvement I'd like to see is https://github.com/tendermint/tendermint/issues/2317.
