### ISSUE TITLE
The link "Local cluster using docker-compose" in README response 404 status

### ISSUE THREAD

**Issue by Frederic-Zhou** [tendermint/tendermint#7412]
The links  "Local cluster using docker-compose" and "Remote cluster using Terraform and Ansible"  in README response 404 status

Please modify it to the correct new url

**Comment by creachadair** [comment]
Thank you for pointing this out! This should now be fixed.

**Comment by Frederic-Zhou** [comment]
“Remote cluster using Terraform and Ansible” this link is OK
But "Local cluster using docker-compose"  this link is still response status 404

**Comment by creachadair** [comment]
> “Remote cluster using Terraform and Ansible” this link is OK But "Local cluster using docker-compose" this link is still response status 404

Thanks again! #7439 will fix it.
