### ISSUE TITLE
RPC: add application version to NodeInfo

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7459]
## Proposal

Currently, `NodeInfo` (from the `/status` RPC request) looks as follows:
```
"node_info": {
      "protocol_version": {
        "p2p": "8",
        "block": "11",
        "app": "1"
      },
      "id": "19c81c98a297111107f51b463ee824dc750b1213",
      "listen_addr": "tcp://0.0.0.0:26656",
      "network": "osmosis-1",
      "version": "0.34.12",
      "channels": "40202122233038606100",
      "moniker": "node",
      "other": {
        "tx_index": "off",
        "rpc_address": "tcp://127.0.0.1:26657"
      }
    },
```

Version, in this struct, refers to the Tendermint version, but applications may also want to know what version a network is running (so that they can find out if they are running the same version). We get the application version in the `Info` ABCI call which we perform on startup. I propose that we also add this to `NodeInfo` and better distinguish between tendermint and application versions. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by spaceCh1mp** [comment]
Possible solutions for this could be to either make the call in the `Status` method and include that as a field `AppInfo` in the `ResultStatus` or make the `InfoSync` call in `makeNode` and pass the response to `makeNodeInfo`. To better distinguish between Tendermint and application versions can we include two new fields in `NodeInfo`?  e.g `AppVersion` and `TendermintVersion`

**Comment by jonasbostoen** [comment]
@cmwaters this can be closed
