### ISSUE TITLE
tendermint node connection refused issue 

### ISSUE THREAD

**Issue by rupam150** [tendermint/tendermint#7478]
i have a four node setup in tendermint ( 0.31.5-d2eab536) , i have configured the config.toml file accordingly with the node id and node host adress but when i run the tendermint node command in the node it is showing connection refused and something called self id during p2p connection , i was expecting blocks generation after the tendermint node command execution , Please help as i am new to the tendermint !!!!
<img width="960" alt="tendermint node issue" src="https://user-images.githubusercontent.com/76766096/146713670-fcc2b1cc-dd8e-4090-948d-7f577c80fefd.PNG">

Here's my config.toml file with the persistent peers .
<img width="960" alt="config tmol" src="https://user-images.githubusercontent.com/76766096/146713805-c1cab755-9f58-4984-95fa-0c459f3ae5f6.PNG">

**Comment by creachadair** [comment]
Hi @rupam150. The "connection refused" messages are not specific to Tendermint, that message means there is either nothing listening at the given address, or that the connection is blocked in some way (e.g., by a firewall, VPN, proxy, etc.).

Separately, I should note that v0.31 is quite an old version of Tendermint. If you're new and trying to get started, I'd recommend you look at a more recent version. The latest release is v0.35.0, and the latest supported by the Cosmos SDK is v0.34.

**Comment by creachadair** [comment]
I believe there are no further actions for this issue, so I’m marking it closed. However, please feel free to reopen it if you have further questions on this topic.
