### ISSUE TITLE
IPv6 addr

### ISSUE THREAD

**Issue by mgialong215** [tendermint/tendermint#7479]
Hello, I experienced the error saying "too many colons in address" when putting an IPv6 address as seeds or peers in the config.toml or environment variable. Is there a way that we can config to use IPv6 address? Since we really want it.
Thank you.

**Comment by creachadair** [comment]
An IPv6 address should work, but you may need to use the `[host]:port` notation (note square brackets) to satisfy the address parser, e.g., `[2001:db8::1]:80`.

**Comment by mgialong215** [comment]
got it, thank you so much.
