### ISSUE TITLE
There are several errors in the Document 

### ISSUE THREAD

**Issue by Frederic-Zhou** [tendermint/tendermint#7482]
referr : [tutorials  -> go built in](https://docs.tendermint.com/master/tutorials/go-built-in.html) 

### 1.  line 16
`tmflags "github.com/tendermint/tendermint/libs/cli/flags"` 
the `flags` package   is not exist in  libs/cli/

### 2.  line 73
```
	// create logger
	logger := log.NewTMLogger(log.NewSyncWriter(os.Stdout))
```

`NewTMLogger`, `NewSyncWriter` : not declared by package log

### 3.  line 81~84

```
	// read private validator
	pv := privval.LoadFilePV(
		config.PrivValidatorKeyFile(),
		config.PrivValidatorStateFile(),
	)

```
`pv := privval.LoadFilePV(...)`: cannot initialize 1 variables with 2 values

`PrivValidatorKeyFile`,`PrivValidatorStateFile` : undefined

### 4.  line 93~100
```
	// create node
	node, err := nm.NewNode(
		config,
		pv,
		nodeKey,
		abcicli.NewLocalClientCreator(app),
		nm.DefaultGenesisDocProviderFunc(config),
		nm.DefaultDBProvider,
		nm.DefaultMetricsProvider(config.Instrumentation),
		logger)
	if err != nil {
		return nil, fmt.Errorf("failed to create new Tendermint node: %w", err)
	}
```

`NewNode`, `DefaultGenesisDocProviderFunc`, `DefaultDBProvider`,`DefaultMetricsProvider` not declared by package node

`abcicli.NewLocalClientCreator(app),` :  **undeclared name: abcicli**

As a newbie, I tried to learn Tendermint step by step according to the official documentation but I did not know how to adjust the code to implement the first Demo App. 👍

**Comment by Frederic-Zhou** [comment]
```
package main

import (
	"flag"
	"fmt"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"

	"github.com/dgraph-io/badger"
	"github.com/spf13/viper"

	abci "github.com/tendermint/tendermint/abci/types"
	cfg "github.com/tendermint/tendermint/config"
	"github.com/tendermint/tendermint/libs/log"
	"github.com/tendermint/tendermint/libs/service"
	nm "github.com/tendermint/tendermint/node"
)

var configFile string

func init() {
	flag.StringVar(&configFile, "config", "$HOME/.tendermint/config/config.toml", "Path to config.toml")
}

func main() {
	db, err := badger.Open(badger.DefaultOptions("/tmp/badger"))
	if err != nil {
		fmt.Fprintf(os.Stderr, "failed to open badger db: %v", err)
		os.Exit(1)
	}
	defer db.Close()
	app := NewKVStoreApplication(db)

	flag.Parse()

	node, err := newTendermint(app, configFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v", err)
		os.Exit(2)
	}

	node.Start()
	defer func() {
		node.Stop()
		node.Wait()
	}()

	c := make(chan os.Signal, 1)
	signal.Notify(c, os.Interrupt, syscall.SIGTERM)
	<-c
}

func newTendermint(app abci.Application, configFile string) (service.Service, error) {
	// read config
	config := cfg.DefaultValidatorConfig()
	config.RootDir = filepath.Dir(filepath.Dir(configFile))
	viper.SetConfigFile(configFile)
	if err := viper.ReadInConfig(); err != nil {
		return nil, fmt.Errorf("viper failed to read config file: %w", err)
	}
	if err := viper.Unmarshal(config); err != nil {
		return nil, fmt.Errorf("viper failed to unmarshal config: %w", err)
	}
	if err := config.ValidateBasic(); err != nil {
		return nil, fmt.Errorf("config is invalid: %w", err)
	}

	// create logger
	// logger := log.NewTMLogger(log.NewSyncWriter(os.Stdout))
	logger := log.MustNewDefaultLogger(log.LogFormatPlain, log.LogLevelInfo, false)
	var err error
	// logger, err = tmflags.ParseLogLevel(config.LogLevel, logger, cfg.DefaultLogLevel)
	// if err != nil {
	// 	return nil, fmt.Errorf("failed to parse log level: %w", err)
	// }

	// read private validator
	// pv := privval.LoadFilePV(
	// 	config.PrivValidatorKeyFile(),
	// 	config.PrivValidatorStateFile(),
	// )

	// read node key
	// nodeKey, err := p2p.LoadNodeKey(config.NodeKeyFile())
	// if err != nil {
	// 	return nil, fmt.Errorf("failed to load node's key: %w", err)
	// }

	// create node
	// node, err := nm.NewNode(
	// 	config,
	// 	pv,
	// 	nodeKey,
	// 	abcicli.NewLocalClientCreator(app),
	// 	nm.DefaultGenesisDocProviderFunc(config),
	// 	nm.DefaultDBProvider,
	// 	nm.DefaultMetricsProvider(config.Instrumentation),
	// 	logger)

	node, err := nm.NewDefault(config, logger)

	if err != nil {
		return nil, fmt.Errorf("failed to create new Tendermint node: %w", err)
	}

	return node, nil
}
```

I modify the `main.go` file like this, right?

**Comment by williambanfield** [comment]
Hey @Frederic-Zhou, thanks for pointing out some of the shortcomings in our docs. I would recommend not looking at the master docs, since `master` is generally not considered stable and things are subject to change.

The `abcicli` package was renamed to `abciclient` and we removed some fields in node initialization to make creating a node easier and simpler. 

The main change I would suggest you make to the code you supplied for `main.go` is the `New(...)` constructor for a node so that you can pass through an abci application. As of now, your `newTendermint` function passes through an `app` but doesn't actually use it in the node you construct. With the basics of the node in place with a simple abci application, you should then be able to continue experimenting by changing the abci application how you wish. 

Using the `New(...)` constructor will require that you pass through a genesis file. This can be constructed using the `GenesisDocFromFile()` package function. As an example: https://github.com/tendermint/tendermint/blob/d3abe15aae1933c672af03c257c12acb01e7d98d/node/node.go#L1052

**Comment by williambanfield** [comment]
Hey @Frederic-Zhou, I've created some fixups in the #7488 branch. I'll try to merge those in soon, but if you want to try them out in the mean time and give some feedback it'd be much appreciated.

**Comment by Frederic-Zhou** [comment]
Thanks a lot @williambanfield .
I found the right way to do it from "tendermint/cmd/tendermint/commands/run_node.go".
Yes, And I found that the code in `tendermint/abci/cmd/...` and `tendermint/cmd/...` is good for learning.
