### ISSUE TITLE
Can Client, App, Core inside the same process?

### ISSUE THREAD

**Issue by Frederic-Zhou** [tendermint/tendermint#7489]
Hello!
I  create **localCreator** instance via `localCreator :=abciclient.NewLocalCreator(mnapp.NewPersistentKVStoreApplication("./db"))` 
and use the localCreator  to new a tmNode instance and call Start() it in a goroutine, 
then create a client via `client, err := localCreator()`

Finally, I use **client's** functions to execute deliver_tx, etc.

Is this feasible?
Or only should request HTTP API  like this `localhost:26657/broadcast_tx_commit?tx="name=satoshi"` ?

**Comment by creachadair** [comment]
Hi @Frederic-Zhou. It is certainly possible to run an application and consensus in the same node, that's actually quite typical for applications written in Go. 

However, note that there is a difference between an ABCI client (talking to the application) and an RPC client (talking to the node). I'm guessing you probably mean RPC, although your code example shows setup for an ABCI client. Those are separate protocols.

There is a [local RPC client](https://github.com/tendermint/tendermint/tree/master/rpc/client/local) that can be used to call the RPC service in-process, so you can indeed make RPC calls within the binary without an HTTP request.

Does that address your question?

**Comment by Frederic-Zhou** [comment]
Thanks a lot @creachadair !
Yes, your reply made me understand that I was wrong to confuse the RPC client and ABCI client. 
Now I know how to write RPC client code. Thank you so much
