### ISSUE TITLE
questions about the 'timeout_commit'

### ISSUE THREAD

**Issue by zzyalbert** [tendermint/tendermint#7491]
I am new to tendermint, and curious about `timeout_commit` that you have to wait before next block proposal. Some papers said it is necessary for liveness and tendermint doesn't have `Responsiveness` due to this. Is that true? Can I have a scenario?

**Comment by cmwaters** [comment]
`timeout_commit` isn't necessary for liveness. I would refer to the discussions that happened in this issue https://github.com/tendermint/spec/issues/359#issuecomment-966351401 for more context on `timeout_commit`

**Comment by zzyalbert** [comment]
Thanks for you reply. I just read this in the HotStuff paper (https://arxiv.org/pdf/1803.05069.pdf)

![image](https://user-images.githubusercontent.com/8242525/148007873-8cc22cdf-759e-4c0a-9d6f-2f6b11a38fa9.png)

Does Tendermint have to wait `the maximal network delay` to begin the next block consensus? Is `the maximal network delay` the same thing as 'timeout_commit'?

**Comment by zzyalbert** [comment]
> `timeout_commit` isn't necessary for liveness. I would refer to the discussions that happened in this issue [tendermint/spec#359 (comment)](https://github.com/tendermint/spec/issues/359#issuecomment-966351401) for more context on `timeout_commit`

Thanks for the reference, quit useful for me
