### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by and00999** [tendermint/tendermint#7492]
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned
[alchemy_notify-master.zip](https://github.com/tendermint/tendermint/files/7775952/alchemy_notify-master.zip)

**Comment by creachadair** [comment]
I'm closing this empty issue. If you have a question or an issue to report, feel free to reopen it with more detail.
