### ISSUE TITLE
Use godoc properly on exported types

### ISSUE THREAD

**Issue by p4u** [tendermint/tendermint#7495]
It took me a while to realize the P2PConfig.Seeds field is now deprecated since godoc was not able to find the comment here https://github.com/tendermint/tendermint/blob/master/config/config.go#L572

I'm not sure why some fields do not have properly set the godoc tag, but just adding the name of the field in the begining of the comment description would make life easier for developers. Probably it's worth it :)

```
	// Seeds is a comma separated list of seed nodes to connect to
	// We only use these if we can’t connect to peers in the addrbook
	// NOTE: not used by the new PEX reactor. Please use BootstrapPeers instead.
	// TODO: Remove once p2p refactor is complete
	// ref: https://github.com/tendermint/tendermint/issues/5670
	Seeds string `mapstructure:"seeds"`
```

**Comment by creachadair** [comment]
Hi @p4u.  The field documentation should work fine even without adding the name. See, for example, the [godoc for the `P2PConfig.Seeds` field](https://pkg.go.dev/github.com/tendermint/tendermint/config#P2PConfig.Seeds) which does correctly document the fields of this type.

But what we definitely _should_ do there is to add a proper ["Deprecated" annotation](https://rakyll.org/deprecated) to the fields. That would make the deprecation visible to lint tools and pkg.go.dev.

The convention of starting with the name is mainly relevant for top-level declarations, which appear in the function summaries. I don't think we'd gain much additional value by mechanically adding names on the fields of the struct type, though it wouldn't hurt anything.

**Comment by p4u** [comment]
> Hi @p4u. The field documentation should work fine even without adding the name. See, for example, the godoc for the P2PConfig.Seeds field which does correctly document the fields of this type.

Umm, that's right. But for some reason my vscode IDE does not show the comments, seems the name of the field might be required. 

Also the official Code Reviews comments state `Comments should begin with the name of the thing being described and end in a period`, see https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences

Golint and most linters would also complain about it.

So I think it's worth to do it even if godoc would accept it :)
