### ISSUE TITLE
How to join peers in a  network at runtime

### ISSUE THREAD

**Issue by Frederic-Zhou** [tendermint/tendermint#7498]
Hi!

I created **testnet** as described in the documentation and it works fine.

For the example, testnet generates a configuration file of 4 nodes and then provides all peers IDs, IPs, Ports as parameters to flag --p2p.persistent-peers when starting each one as "validator".

In addition to Testnet's networking approach, **is it possible to start several nodes individually and then join them together to the same network at runtime?**

for example, I start 4 validator nodes 
```
tendermint init validator
// modify  genesis.json , set chainID to the same 
tendermint start --proxy-app=persistent_kvstore
```
then, how to make them join each other...

In addition, I found that the function `DeliverTx`  in `persistent_kvstore` app can update the validator set, how to use it ?
```
func (app *PersistentKVStoreApplication) DeliverTx(req types.RequestDeliverTx) types.ResponseDeliverTx {
	// if it starts with "val:", update the validator set
	// format is "val:pubkey!power"
...
}
```

As a beginner, my description may not be very clear, and I look forward to your reply!

**Comment by cmwaters** [comment]
> is it possible to start several nodes individually and then join them together to the same network at runtime?

The short answer is yes. You can create a genesis with a single validator and begin the network with just that validator then add more nodes. If the genesis contains only a single validator then any other nodes that you start will not be validators initially. To add and remove validators dynamically, the application that you built needs to send `[]ValidatorUpdate` in `EndBlock`. The `persistent_kvstore` shows how a transaction received in `DeliverTx` can be parsed and processed to produce a `ValidatorUpdate` in the `EndBlock`.

**Comment by Frederic-Zhou** [comment]
Thank you very much for your answer.
