### ISSUE TITLE
Update 'skip_timeout_commit' name

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7519]
The name makes this values sound like it disables the 'timeout-commit' mechanism. However, it does not do that. Instead, a changes the timeout-commit logic to proceed directly to the next height _if the validator has observed 100% of the voting power on the network_.

I propose renaming this configuration parameter to 'timeout-commit-bypass-enabled' and documenting clearly what 'bypass' means in this case.

**Comment by cmwaters** [comment]
@williambanfield can we close this?

**Comment by faddat** [comment]
I think it is okay to close, or we could call it "wait for all signatures"
