### ISSUE TITLE
Is the implementation of abci's async interface planned and in progress?

### ISSUE THREAD

**Issue by malefooo** [tendermint/tendermint#7520]
## Summary

I found that the server used the async interface in the interaction with local_client, but the client still used the sync interface in the call to abci, so in fact the whole call is still sync, I would like to ask about the client and abci when the async function is implemented

## Problem Definition

We are currently experiencing low performance in our project and need to rely on the concurrency of deliver_tx to improve performance

## Proposal

async mode for client and abci

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by williambanfield** [comment]
Hey @malefooo, thanks for the question.  The `Async` code is an asynchronous client, meaning that the client will go and do other work while waiting for the response to its request. It still sends requests and awaits responses in serial, not concurrently. We don't have plans to expand this at the moment and switching to a concurrent client may not be safe for many applications that expect the current mechanism to execute transactions deterministically.
