### ISSUE TITLE
notified txs available but mempool empty

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#753]
`E[10-18|00:24:00.478] CONSENSUS FAILURE!!!                         module=consensus err="notified txs available but mempool is empty!`

This happened after sending a tx to a node via `_commit` in fast sync. The tx timed out before it finished syncing. Then once it synced up this error occured.

**Comment by melekes** [comment]
I have not yet reproduced it, but my first guess would be that we're calling 

https://github.com/tendermint/tendermint/blob/develop/mempool/mempool.go#L272

after rechecking txs, while here https://github.com/tendermint/tendermint/blob/develop/mempool/mempool.go#L256 we may be removed the single tx, which left in the mempool => that will lead to `size==0`
