### ISSUE TITLE
Make first block time >= genesis time.

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7546]
Currently, the [timestamp specified in the genesis file](https://github.com/tendermint/tendermint/blob/90cf742065944d6e8260dc4cacb79580b00e4397/types/genesis.go#L38) is used as the timestamp for the first block. The consensus code checks to [ensure that the first block time matches this genesis time](https://github.com/tendermint/tendermint/blob/90cf742065944d6e8260dc4cacb79580b00e4397/internal/state/validation.go#L126) and rejects the first block if they do not match. 

With the creation of the proposer-based timestamps algorithm, this is no longer needed. It was important when using BFT time that the block's timestamp match the genesis time because _there was no other possible timestamp that could be used in the first block_. BFT time relied on using values form the previous height to generate the next height's timestamp, but no previous height exists during the first height. PBTS no longer relies on values from the previous height, so it should be safe to relax the validation to ensure that the first block's timestamp is >= the genesis time.

**Comment by marbar3778** [comment]
Question: in network launch cases the genesis time is used to say at which time the network should start. Would this change this behaviour?

**Comment by williambanfield** [comment]
@marbar3778 Good question. No, we would still start consensus at the `genesis_time`. This just relaxes the constraint so that the timestamp in the first block no longer has to exactly equal the `genesis_time`. The timestamp will be validated to be >= the timestamp in the genesis doc. 

As far as I can tell, the genesis time was historically serving two roles: 

1. Determining what time the network should start consensus.
2. Determining what value should be placed into the first block for the timestamp.

We still want to preserve (1) because that's a very valuable way to coordinate network starts, but (2) is no longer required. BFT Time required it but PBTS does not require it.

**Comment by milosevic** [comment]
I agree with William's comment above and do confirm that with PBTS we can relax constraint as suggested and rely on PBTS algorithm to define timestamp for the initial block.
