### ISSUE TITLE
Potential Error in Docs > Specification > Validators

### ISSUE THREAD

**Issue by ttmc** [tendermint/tendermint#756]
The current docs page at https://tendermint.readthedocs.io/en/master/specification/validators.html says:

> Validators are responsible for committing new blocks in the blockchain. These validators participate in the consensus protocol by broadcasting votes which contain cryptographic signatures signed by each validator’s public key.

I suspect the signatures are computed using the validator's private key, not the public key. But what do I know?

**Comment by melekes** [comment]
@ttmc good eye! thank you
