### ISSUE TITLE
Ability to specify public IPv4 address for P2P

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#758]
Feature request, seems high priority for launch.

It should be possible to specific the public address that should be shared with peers. 

Amazon EC2 instances does not support UPNP, so a user should have the ability to obtain it (using `ec2metadata --public-ipv4` or similar) and provide it on the command-line.

**Comment by mdyring** [comment]
Discussed briefly with Adrian.

Being able to provide a random IP on the cmdline could potentially be used for some kind of attack.

A reasonable workaround (for less configuration work) would be if a node, once it sees a new connection, checks if the remote IPv4 address is in any of the private ranges: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16.

If it is private, the IP should be not be sent to other nodes at the PEX layer. If public, it can be shared (with a restriction, explained below).

Additionally, it would be very nice to be able to hide a validator behind some public nodes (to keep its IP anonymous and mitigate DoS).

So a configuration option should be available ("hide_my_ass=true" ?), which instructs a remote node to share the peer IP or not..

**Comment by ebuchman** [comment]
Is it sufficient to use the address from the connection itself and the self reported port to avoid letting peers specify the listening address they report?  I'm not sure what the attack scenario is, but peers can already set their `p2p.laddr` to anything, and that is what gets self reported - if they're dishonest about it, they just won't be able to accept connections.

> If it is private, the IP should be not be sent to other nodes at the PEX layer. If public, it can be shared (with a restriction, explained below).

We already check if the address is routable (https://github.com/tendermint/tendermint/blob/master/p2p/addrbook.go#L537). There is a config option, `p2p.addr_book_strict` that can be set to false to allow connecting to these non-routable addresses, including private addresses.


> Additionally, it would be very nice to be able to hide a validator behind some public nodes (to keep its IP anonymous and mitigate DoS).

See new issue https://github.com/tendermint/tendermint/issues/865

**Comment by mdyring** [comment]
I am not aware of the PEX implementation details, but since the node accepting an inbound connection will know the remote IP/port, perhaps it could report this back to the initiator node during the handshake phase (if such a thing exists), allowing it to discover it's public endpoint.

It would then be up to the initiator to decide via config options if wants to publish its address to the wider network (or, add itself to address book if that is the terminology here?).

I'd prefer this to providing the IP on the cmdline.

**Comment by ebuchman** [comment]
>  inbound connection will know the remote IP/port,

They will know the remote IP, but the remote peer needs to self report the listening port!

I don't think we need use the network as a self-IP-discovery service yet, though that could be cool. But we can have peers use the IP from the connection and the remote's self-reported port to figure out the expected listening address, and use that in the PEX. 

New issue here: https://github.com/tendermint/tendermint/issues/873
