### ISSUE TITLE
Generate user documentation from Tendermint protobuf files

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7584]
During the TM dev call on 13-Jan-2022, we agreed it would be useful to generate pretty documentation from the Tendermint protobuf files. The [buf](https://buf.build) tools appear to support this.

To do:

- [ ] Investigate whether we can generate documentation separately from code.
- [ ] Set up some basic automation to generate documentation suitable for linking on the web.

**Comment by mfridman** [comment]
Hey @creachadair, this sounds awesome. Although I now work for Buf, I think it'd be neat to have "pretty" docs for the protos. I always found it a subpar experience to browser protos in GitHub repos. 

If you have any questions, I'd be happy to help and answer any.

**Comment by brennhill** [comment]
Is this something I could help with?

**Comment by creachadair** [comment]
> Is this something I could help with?

Thank you for the offer! There isn't really a separable task yet, I need to do some investigation first. But I will update this issue once that happens, and would be grateful for your feedback.

**Comment by brennhill** [comment]
Have you looked at this tool: https://github.com/pseudomuto/protoc-gen-doc

The downside of buf is it appears to be a paid item.

**Comment by mfridman** [comment]
Great suggestion, the [protoc-gen-doc](https://github.com/pseudomuto/protoc-gen-doc) plugin is the most widely used (I've used it in a few projects myself).

> The downside of buf is it appears to be a paid item.

Many projects, commercial and open source, that have public Protobuf definitions push to the [Buf Schema Registry](https://buf.build/blog/announcing-bsr) at no charge. A few examples are [envoyproxy/envoy](https://buf.build/envoyproxy/envoy), [authzed/api](https://buf.build/authzed/api) and [cosmos/cosmos-sdk](https://buf.build/cosmos/cosmos-sdk). Not only are consumers able to browse Protobuf documentation, but more interestingly, the Buf ecosystem allows for dependancy management. This allows the community to consume and rely on definitions pushed to the Registry without having to copy/paste and vendor them.

Apologies for trying to push "buf" here, but I really do think it's a great solution for the given use case. I'm obviously a bit conflicted here, but I've been following the Tendermint project well before joining Buf and think there is a great opportunity to make the project more accessible.

**Comment by brennhill** [comment]
awesome, as long as it's available for open source, I'm happy to take a stab at this. I'm just unclear what the ideal outcome is (given that I haven't used buf before. Perhaps it's obvious to someone more used to that tool)

**Comment by brennhill** [comment]
Are we looking for the equivalent for tendermint as cosmos-sdk?

**Comment by marbar3778** [comment]
> Are we looking for the equivalent for tendermint as cosmos-sdk?

yes, but I believe it would be safer to do this post spec and tendermint merge. Here is a file that can be copied to close this https://github.com/cosmos/cosmos-sdk/blob/master/.github/workflows/proto-registry.yml
