### ISSUE TITLE
Light Client: Absence proof verification doesn't work

### ISSUE THREAD

**Issue by ashcherbakov** [tendermint/tendermint#7640]
**Tendermint version:** v0.34.14 and master(`233f40963f5e26ea34a8d546d83714dc96600d7f`)
**ABCI app:** Cosmos-sdk and https://github.com/zigbee-alliance/distributed-compliance-ledger

**What happened**:
- LightClient proxy is started
- An ABCI query request is sent via light client proxy where there is no value for the given key in the store
- Absence proof verification fails with the error: `verify absence proof: key path string must start with a forward slash '/'`

**What you expected to happen**:
- No error. Absence proof is successfully verified.

**Have you tried the latest version**: yes

I believe the reason is that not a full path (without a store prefix) is passed to `VerifyAbsence` function in https://github.com/tendermint/tendermint/blob/master/light/rpc/client.go.

**Comment by ashcherbakov** [comment]
Fix: https://github.com/tendermint/tendermint/pull/7639

**Comment by brennhill** [comment]
Is this still open?
