### ISSUE TITLE
Blockchain Reactor Improvements

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#766]
Blockchain reactor and blockpool parameters need some better tuning:

- maxPendingRequestsPerPeer should be set based on how many blocks we could be sending to a peer at any one time. Eg. for a 128kB/s connection with 1kB blocks and 10 peers, we can push 12.8 blocks/sec per per. 
- requests and blocks share the same reactor channel - this should be split in two
- we use TrySend everywhere, meaning if our reactor channel is full, we'll drop the msg and likely timeout

In general the pool is a bit complicated with its use of maps/mutexes and could use some cleanup or at least make it clearer whats happening where and why

**Comment by ebuchman** [comment]
Some work: https://github.com/tendermint/tendermint/pull/765

**Comment by milosevic** [comment]
Related issue: #1734.

**Comment by xla** [comment]
Closed in favour of #2026
