### ISSUE TITLE
ABCI++: Decide what to do with `TxRecord`

### ISSUE THREAD

**Issue by sergio-mena** [tendermint/tendermint#7663]
## Summary

The structure `TransactionRecord` is a late addition to the ABCI++ spec. It allows the App to modify the transaction in a flexible way (see https://github.com/tendermint/spec/pull/366).

This needs to be dealt with at both the spec and implementation level.

## Problem Definition

One of the features of the API using `TransactionRecord` is that the App can provide traceability information when it transforms one or more TXs into other TXs.
However, as this is done when handling `PrepareProposal`, currently, we don't have a means of making the traceability info available to other nodes. We need to decide how to deal with this.

* Discuss which part should be responsible for transaction traceability (Tendermint or the App?).
    * If the answer is "Tendermint, come up with a method to spread this info via p2p, or include it as an extension of a TX in the block format.
    * If the answer is "the App", then remove filed `new_hashes`; and explain in the spec that this is up to the App to encode it inside its TXs

Once decided, open PRs (spec and/or implementation) and implement/document the decision.

## Dependencies

#7654 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
I've been thinking about this issue for a while. Specifically I've been trying to work out if we need verifiability and if so how to achieve that.

**Verifiability:** if a proposer and takes Tx 1 & 2 and modifies it to make Tx 3 in the block yet indicates that the hashes of Tx 4 & 5 as being the original transactions that led to 3, then all other nodes should detect that and consider the block invalid.

If verifiability is not important and we want to use the original hashes:
- Clients listening to a non-proposer could potentially think their transaction has made it into a block when it hasn't (NOTE: there's nothing stopping nodes atm from saying that a transaction went through even although it didn't. Clients have to submit the tx query with proof  
- Non-proposer nodes could potentially remove a transaction from their mempool which wasn't actually involved in the production of a block.

Alternatively we could ignore the original hashes and:
- Clients would not be able to track modified txs on nodes that weren't the proposer
- The original transactions would stay in the mempool unless removed by `reCheckTx` or a `TTL`

The only foreseeable way of being able to verify modified transactions is to assert that any modifications are replicable/deterministic. That way we could provide the original transactions (if the node has them) as well as the modified transactions in `ProcessProposal` and get the app of the other nodes to validate them. What do you think?

**Comment by cmwaters** [comment]
Another idea would be to force the application to provide a deterministic id that Tendermint can use for tracing and garbage collection. This would have to be done by storing it in the transaction itself. The Cosmos SDK already does this by having the address of the sender and a nonce in every transaction (to prevent the sender from submitting the same tx twice). In fact we explicitly state that all applications must implement some form of replay protection.

This would be done by returning an ID in `CheckTx` which would go back to the original sender and be the TxId in the mempool. Upon committing a block, `FinalizeBlock` should return the list of ids corresponding to committed txs. Tendermint can use them to flush out txs from the mempool and potentially use them in a secondary index so users can find their tx and corresponding merkleproof.

As discussed in a conversation with @sergio-mena, the other path is to try dissuade modifying txs by removing the `new_hashes` field from `TransactionRecord`

**Comment by sergio-mena** [comment]
@angbrav is working on this

**Comment by sergio-mena** [comment]
Addressed via #8002
