### ISSUE TITLE
docker-compose error report

### ISSUE THREAD

**Issue by THEBESTSZ** [tendermint/tendermint#7676]
how to resolve?

$ docker-compose up

Creating network "tendermint-master_localnet" with driver "bridge"
Pulling node0 (tendermint/localnode:)...
latest: Pulling from tendermint/localnode
c67f3896b22c: Pull complete
db2c3d46205d: Pull complete
4faab18e7d68: Pull complete
65b282177e18: Pull complete
Digest: sha256:2c37eed3cff902fdd6330fb20d49945ca654e1c99564929d5eb18db09ebb8c3e
Status: Downloaded newer image for tendermint/localnode:latest
Creating node2 ...
Creating node3 ...
Creating node1 ... error
Creating node2 ... error

ERROR: for node1  Cannot start service node1: OCI runtime create failed: invalid mount {Destination:] Type:bind Source:/var/lib/docker/volumes/cf77cfeca062283edcb1883a06dac9531d34bf95ea44915bb155afbaa6d68b47/_data Options:[rbind]}: mount destination ] not absolute: unknown
Creating node3 ... error
ERROR: for node2  Cannot start service node2: OCI runtime create failed: invalid mount {Destination:] Type:bind Source:/var/lib/docker/volumes/f2c2482bcbeb2da061d363823c45ee1c1e773f80bb2f7f32b74e92c38719bd0c/_data Options:[rbind]}: mount destination ] not absolute: unknown

ERROR: for node3  Cannot start service node3: OCI runtime create failed: invalid mount {Destination:] Type:bind Source:/var/lib/docker/volumes/bfc73da5d09f5cde34e1fe36cad2f63cda4678a25955031f71d0b504169f2113/_data Options:[rbind]}: mountCreating node0 ... error

ERROR: for node0  Cannot start service node0: OCI runtime create failed: invalid mount {Destination:[ Type:bind Source:/var/lib/docker/volumes/8dd2f610a722c97f0a9a9eb4f0d5ad5943626230513ed6f6b5529a9a6f2a3628/_data Options:[rbind]}: mount destination [ not absolute: unknown

ERROR: for node1  Cannot start service node1: OCI runtime create failed: invalid mount {Destination:] Type:bind Source:/var/lib/docker/volumes/cf77cfeca062283edcb1883a06dac9531d34bf95ea44915bb155afbaa6d68b47/_data Options:[rbind]}: mount destination ] not absolute: unknown

ERROR: for node2  Cannot start service node2: OCI runtime create failed: invalid mount {Destination:] Type:bind Source:/var/lib/docker/volumes/f2c2482bcbeb2da061d363823c45ee1c1e773f80bb2f7f32b74e92c38719bd0c/_data Options:[rbind]}: mount destination ] not absolute: unknown

ERROR: for node3  Cannot start service node3: OCI runtime create failed: invalid mount {Destination:] Type:bind Source:/var/lib/docker/volumes/bfc73da5d09f5cde34e1fe36cad2f63cda4678a25955031f71d0b504169f2113/_data Options:[rbind]}: mount destination ] not absolute: unknown

ERROR: for node0  Cannot start service node0: OCI runtime create failed: invalid mount {Destination:[ Type:bind Source:/var/lib/docker/volumes/8dd2f610a722c97f0a9a9eb4f0d5ad5943626230513ed6f6b5529a9a6f2a3628/_data Options:[rbind]}: mount destination [ not absolute: unknown
ERROR: Encountered errors while bringing up the project.

**Comment by creachadair** [comment]
Hi, @THEBESTSZ. I'm not able to reproduce the errors described above. Can you say a bit more about the environment you're running in (e.g., operating system, version), and what version of Tendermint you're building against?

From the error messages it looks as if maybe Docker is misconfigured, or not running in the right directory, but it's hard to be more specific. In general you may have better luck using `make localnet-start` than trying to build things manually.
