### ISSUE TITLE
Remove xsalsa20symmetric xchacha20poly1305 package in crypto folder

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#7689]
## Summary

Seems like no other package depends on it. Perhaps can remove it if there is no future implementation on top of it.

## Proposal

Remove packages.

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
It looks like we could probably get rid of salsa20symmetric too. The Cosmos SDK has a dependency on it, but there's no obvious reason it needs to live in the TM core repository.

**Comment by JayT106** [comment]
Yes, it might be better to move it to the Cosmos SDK.

**Comment by creachadair** [comment]
> Yes, it might be better to move it to the Cosmos SDK.

Agreed. I sent https://github.com/cosmos/cosmos-sdk/pull/11027 to start that.
