### ISSUE TITLE
Error msg while succesful syncing on private testnet

### ISSUE THREAD

**Issue by robertdavid010** [tendermint/tendermint#769]
**Tendermint version**
0.10.3-'8d76408

**ABCI app**
Ethermint

**Environment**:
Mac 10.12.6
- **Install method**:
Binary install

**What happened**:
Manual testnet setup resulted in syncing of two nodes:

First node is in VirtualBox VM running Ubuntu LTS. This works 100% as validator node
Second node, is on host MacOS. This node connects (as seed) and syncs with VM validator node.

Everything works as normal except that the console output for seed Tendermint node (run in own instance on Mac OS) returns an error between every block...

```
Attempt to finalize failed. We don't have the commit block. module=consensus height=### proposal-block= commit-block=<hash>
```

However is seems to keep syncing as normal. Could just be logging level? Set to default.

**What you expected to happen**:
Normal syncing of nodes on private testnet.

**How to reproduce it** (as minimally and precisely as possible):
Basic install for binaries as documented. Ran several tests on each node.
Then reset both nodes, and instantiated with common `genesis.json`

**Anything else do we need to know**:
p2p.peers is set only on seed node, with the validator node being the registered peer.
Using `admin.peers` from `geth attach` returns an empty array.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/blob/develop/consensus/state.go#L1130-L1132

**Comment by adrianbrink** [comment]
@zramsay about the errors guide.

**Comment by adrianbrink** [comment]
I've seen this error repeatedly when using Gaia.

**Comment by zramsay** [comment]
#778 for the errors guide
@robertdavid010 perhaps upgrading to 0.11.1 would help

**Comment by ebuchman** [comment]
This isn't a real error. Maybe we should change the log to Info instead of Error? It's just reporting that we saw the commit votes before we actually received the full block, which can happen, especially when we're a full node and not a validator.

**Comment by melekes** [comment]
> Maybe we should change the log to Info instead of Error

yeah, let's do that

**Comment by robertdavid010** [comment]
Sounds great, still getting into the usage of tendermint, hoping I can help when I can.
