### ISSUE TITLE
Enable validator punishment for broadcasting transactions with failing stateless checks durirng CheckTx

### ISSUE THREAD

**Issue by robert-zaremba** [tendermint/tendermint#7698]
## Summary

By default, validator will not broadcast a tx if it failed during `CheckTx`. Those transactions are junk and cause unwanted network spam.
If we require validator to sign such a tx before broadcasting then we can construct a slashing evidence for misbehave. 

Ref: https://github.com/cosmos/cosmos-sdk/issues/10984#issuecomment-1018007252
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
validators don't generally broadcast txs but any node in the network. based off the comment Aaron seems to be talking about proposer slashing for including signature failing txs. The issue described here is different.

**Comment by aaronc** [comment]
This would be done via x/slashing in the SDK I think not Tendermint

**Comment by marbar3778** [comment]
going to close this issue in tendermint for now
