### ISSUE TITLE
RPC: expose mempool size

### ISSUE THREAD

**Issue by p4u** [tendermint/tendermint#7722]
## Summary

Export a method to fetch the current mempool size (in bytes and/or number of transactions).

## Problem Definition

This information was available on previous Tendermint version.

## Proposal

Export a method to fetch mempool information on the local RPC node.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
Mechanically this does not seem particularly difficult to do, but what is the use case for such a method? Details like the size of the mempool are an implementation detail of the consensus node. 

For us to understand the tradeoffs, it would be helpful to have more detail about what problems might be solved by this, and what other options were considered.

**Comment by p4u** [comment]
We currently use it for printing log based stats.

I can see a potential use case of increasing the Mempool size dinamically. So the application layer can decide, depending on the mempool occupation and some other parameters (such as block period or CPU/Memory usage) to increase/decrease the size of the mempool.
