### ISSUE TITLE
Mempool: do not store tx in cache if mempool full

### ISSUE THREAD

**Issue by p4u** [tendermint/tendermint#7723]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.35

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

https://github.com/vocdoni/vocdoni-node

**What happened**:

After executing some benchmarks on our tendermint based application using the last 0.35 release, I observed a weird behavior on the mempool. When sending a huge number of transactions to the network distributing them through multiple nodes (some validators and some just full nodes) at the end only 60-70% of them become included in some block while the rest got lost.

The miners have a mempool of 5000 transactions while the full-nodes (receiving the transactions) have a mempool 10 times bigger. We use `KeppInvalidTxsInCache=true` since in our logic a transaction cannot be valid after being invalid once. Our Cache size is 100k transactions.

In the miner logs I can see the following message appearing many times:
```
2022-01-28T18:07:08Z ERROR rejected incoming good transaction; mempool full err="mempool is full: number of txs 5000 (max: 5000), total txs bytes 3512534 (max: 512000000)" module=mempool tx=749FC7E3ED60924BD60B109ED30B161EC921D34246C06D1CD47886D936C41E44 version=v1 
```

So my guess is that eventually the mempool of the miners becomes full (5000 txs) and the rest of transactions (sent by other nodes in the network) are considered invalid (they are rejected). Since we use `KeppInvalidTxsInCache=true`, the transactions are not removed from Cache, thus they will not be accepted anymore. On the origin node (holding the transaction) the TTL is reached (15 minutes) and the transaction are finally removed.

**What you expected to happen**:

A mempool TX should only be considered invalid (and stay in cache if KeppInvalidTxsInCache=true) if-and-only-if CheckTx() returns non zero. But if the TX is rejected because of mempool full, it should not be stored in the cache and should be accepted afterwars, even if `KeppInvalidTxsInCache=true`

**Comment by p4u** [comment]
Related to this, I have observed huge block time delays with a network of different mempool sizes.

As before, block size at 5MiB, validators with mempool of 5k, fullnodes with mempool from 50k to 200k. Then I flood the fullnodes network with 65k valid transactions. This time I set KeppInvalidTxsInCache=false in order to avoid the previous problem.

First weird thing, fullnodes mempool does not reach 65k (even if it could), it stays around 30-40k

Then the block time goes from the target (10s) to 60-80-100s. 
5 MiB blocks should be easy build by validators (I have run this benchmark many times on previous tendermint versions). So I don't think it is a CPU problem.

My feeling is that fullnodes are constantly trying to send transactions to validators (even if they rejected them because of mempool size) creating a kind of network DDOS. So validators are not able to exchange consensus rounds thus no new blocks are created at time.

Another potential reason is that the mempool runs some kind of blocking or very expensive operation, even if rejecting transactions because of size. That blocks the execution so no new blocks are created.

I know validators should run behind sentinel nodes blablah... But sentinel nodes should exist to avoid malicious behaviors, not honest ones. So I'd expect a more advanced behavior here at protocol level, something such as once some TX is rejected by node B, node A would wait for a signal from node B in order to unblock the transaction sharing to him.

I have not checked the new mempool code so I could be wrong on my assumptions, let me know please.

**Comment by cmwaters** [comment]
> But if the TX is rejected because of mempool full, it should not be stored in the cache and should be accepted afterwars, even if KeppInvalidTxsInCache=true

This makes sense, we shouldn't be adding these txs to the cache but I don't think it's worth running CheckTx on them if they're not going to make it to the mempool, rather run CheckTx when they are eventually submitted again and the mempool has space for them.

Based on what you've written up, it sounds that being able to communicate to your peers when your mempool is full and you're not capable to receive any more txs might reduce unnecessary network traffic. There was some discussion beforehand about having dynamic p2p channels essentially signalling to peers when a node is able to send and receive data across a channel which sounds relevant in the case you describe. 

When you flood the system with transactions and experience large block delays, are the blocks that are being produced full?

**Comment by p4u** [comment]
> When you flood the system with transactions and experience large block delays, are the blocks that are being produced full?

To be honest, I don't know. But my feeling is that yes, they are full or close to be full. 

There has been some changes on the Prometheus values and I have not yet find a way to print the block size on our Grafana.

Is there some documentation on what the Prometheus values are? 

I'm doing this, but the numbers I see do not make much sense: `tendermint_consensus_block_size_bytes{instance="foo.bar"}/(1024*2)`

**Comment by p4u** [comment]
> This makes sense, we shouldn't be adding these txs to the cache but I don't think it's worth running CheckTx on them if they're not going to make it to the mempool, rather run CheckTx when they are eventually submitted again and the mempool has space for them.

Totaly agree, CheckTx should not be executed if the mempool is full.

**Comment by cmwaters** [comment]
> Is there some documentation on what the Prometheus values are?

This is the list we have: https://docs.tendermint.com/master/nodes/metrics.html

`tendermint_consensus_block_size_bytes{instance="foo.bar"}/(1024*2)` this looks okay. Is `1024*2` to the power of 2 or the multiple of 2?

**Comment by p4u** [comment]
> > Is there some documentation on what the Prometheus values are?
> 
> This is the list we have: https://docs.tendermint.com/master/nodes/metrics.html
> 
> `tendermint_consensus_block_size_bytes{instance="foo.bar"}/(1024*2)` this looks okay. Is `1024*2` to the power of 2 or the multiple of 2?

Typo, my bad, I meant (1024*1024)

**Comment by p4u** [comment]
So I managed to chart the block size using the following query: 
`delta(tendermint_consensus_block_size_bytes_sum{instance="foo.bar"}[2m])/delta(tendermint_consensus_latest_block_height{instance="foo.bar"}[2m])/(1024)`

And I confirm blocks are full (5 MiB).

**Comment by JayT106** [comment]
If I understand correctly, the Tx be rejected due to the mempool full will remove the Tx from the cache.
https://github.com/tendermint/tendermint/blob/eed617c2d9da5e6ba1d742b5f59940dec6682f99/internal/mempool/mempool.go#L552
and
https://github.com/tendermint/tendermint/blob/eed617c2d9da5e6ba1d742b5f59940dec6682f99/internal/mempool/mempool.go#L568

**Comment by p4u** [comment]
Right. However (I'm not sure about the logic behind it) the Tx is only removed by cache `if len(evictTxs) == 0 {`
https://github.com/tendermint/tendermint/blob/eed617c2d9da5e6ba1d742b5f59940dec6682f99/internal/mempool/mempool.go#L549

**Comment by JayT106** [comment]
> Right. However (I'm not sure about the logic behind it) the Tx is only removed from cache if:
> 
> https://github.com/tendermint/tendermint/blob/eed617c2d9da5e6ba1d742b5f59940dec6682f99/internal/mempool/mempool.go#L549

I think this check is saying the new transaction doesn't have a higher priority compared with all txs in the current mempool. 

Say if your tooling always uses the same tx priority, so when the mempool is full, the new tx cannot get in and it will not stay in the cache too.

However, the GetEvictableTxs might have a performance issue because it will copy a tx array from the mempool and then sort it. So when mempool is full. this function will always be called.

**Comment by cmwaters** [comment]
> would it be possible for the acbi client put the tx priority as an argument when calling CheckTx?

I don't understand why Tendermint would do that. Can you explain further

**Comment by ancazamfir** [comment]
iiuc, `proxyAppConn.CheckTxAsync` returns the `priority` in the result. When we store a Tx in the mempool we also keep a heap (`priorityIndex`) with highest priority at the top. This is useful for the `ReapMax...` cases but not for `GetEvictableTxs` when we want the lowest priority item. Having another heap (with lowest prio at top) or a different datastructure would help with performance here.

**Comment by JayT106** [comment]
> iiuc, `proxyAppConn.CheckTxAsync` returns the `priority` in the result. When we store a Tx in the mempool we also keep a heap (`priorityIndex`) with highest priority at the top. This is useful for the `ReapMax...` cases but not for `GetEvictableTxs` when we want the lowest priority item. Having another heap (with lowest prio at top) or a different datastructure would help with performance here.

Yes, I was thinking DEPQ( [Double Ended Priority Queue](https://en.wikipedia.org/wiki/Double-ended_priority_queue) ) might work for this case, but not sure is it worth to do

**Comment by cmwaters** [comment]
So my estimation here is that the priority mempool becomes quite inefficient when full and constantly needing to reshuffle (add and evict) transactions based on priority. @p4u did you have the opportunity to run the same testnets using v0.35 but the v0 mempool instead (i.e. fifo)?

**Comment by p4u** [comment]
I can do that, can you provide instructions no how to use Mempool v0? here is how we create the tendermint node https://github.com/vocdoni/vocdoni-node/blob/master/vochain/start.go#L251

**Comment by cmwaters** [comment]
You'd just need to set `tconfig.Mempool.Version` to `"v0"`
