### ISSUE TITLE
Pre-upgrade/key migration is not working

### ISSUE THREAD

**Issue by yaruwangway** [tendermint/tendermint#7737]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.35

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
I am testing the key-migration in tendermint 0.35. I added  [`MakeKeyMigrateCommand()` ](https://github.com/tendermint/tendermint/blob/v0.35.0/cmd/tendermint/commands/key_migrate.go) to simapp
 (cosmos-sdk main branch which uses tendermint 0.35). I tried to upgrade simapp, when upgrade height is reached, I run 
`MakeKeyMigrateCommand()` to migrate the key. logs:
```
 running app args=["pre-upgrade"] module=cosmovisor path=/Users/sb/.simapp/cosmovisor/upgrades/testpreupgrade/bin/simd
2022-01-31T18:29:24+01:00 INFO beginning a key migration dbctx=blockstore num=1 total=6
2022-01-31T18:29:24+01:00 INFO beginning a key migration dbctx=state num=2 total=6
2022-01-31T18:29:24+01:00 INFO beginning a key migration dbctx=peerstore num=3 total=6
2022-01-31T18:29:24+01:00 INFO beginning a key migration dbctx=tx_index num=4 total=6
2022-01-31T18:29:24+01:00 INFO beginning a key migration dbctx=evidence num=5 total=6
2022-01-31T18:29:24+01:00 INFO beginning a key migration dbctx=light num=6 total=6
2022-01-31T18:29:24+01:00 INFO completed database migration successfully
```

the log shows the migration is sucessful but when i restart the chain i get
```
6:29PM INF ABCI Handshake App Info hash="l�\x11\x04e����Y\x15���I�')]���m���H����H" height=39 module=consensus protocol-version=0 software-version=0.43.0-beta1-696-gab160b24e
6:29PM INF ABCI Replay Blocks appHeight=39 module=consensus stateHeight=0 storeHeight=0
panic: state.AppHash does not match AppHash after replay. Got
6CAC110465C5E0BDDF5915C6D2D749C227295DC4F1826D9682D8489694B58648, expected .

State: {{{11 0} 0.35.0-unreleased} test 1 0 :0:000000000000 2022-01-25 16:12:43.288805 +0000 UTC ValidatorSet{
  Proposer: nil-Validator
  Validators:

} ValidatorSet{
  Proposer: nil-Validator
  Validators:

} ValidatorSet{
  Proposer: nil-Validator
  Validators:

} 1 {{22020096 -1} {100000 48h0m0s 1048576} {[ed25519]} {0}} 1 [] []}

Did you reset Tendermint without resetting your application's data?
```

**What you expected to happen**:
Key migrated, and able to start the new chain

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
When i do `tendermint inspect --home ~/.simapp`,  and `curl localhost:26657/commit`
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": null
}
```
 `curl http://localhost:26657/block\?height\=_`
```
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32602,
    "message": "Invalid params",
    "data": "error converting http params to arguments: invalid 64-bit integer encoding \"_\", expected string"
  }
}%
```
**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:
I used `preupgrade` in cosmovisor to run the `MakeKeyMigrateCommand()` , here is how to do it
https://github.com/cosmos/cosmos-sdk/blob/v0.44.5/docs/migrations/pre-upgrade.md
I execute `MakeKeyMigrateCommand()`in `HandlePreUpgrade()`

**Comment by creachadair** [comment]
One thing that jumps out is this line:

```
curl http://localhost:26657/block?height=_
```

The error is complaining (correctly) about `_` not being a valid height. This looks like maybe an example from the OpenAPI docs? If so, you will probably need to replace `_` with the desired target height.

**Comment by yaruwangway** [comment]
ha, right, thank you! @creachadair 
so i tried upgrade height 40, so at height 39, i got the err `Did you reset Tendermint without resetting your application's data?` as showed above.
then I curl height 39,
```
curl http://localhost:26657/block\?height\=39
{
  "jsonrpc": "2.0",
  "id": -1,
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "height must be less than or equal to the head of the node's blockchain (requested height: 39, blockchain height: 0)"
  }
}%
```

So tendermint thinks the height is 0 while the app thinks it is 39 ?

**Comment by creachadair** [comment]
>     "data": "height must be less than or equal to the head of the node's blockchain (requested height: 39, blockchain height: 0)"
> 
> So tendermint thinks the height is 0 while the app thinks it is 39 ?

It looks that way. There are a couple of suggestions for things to check:

- Can you get logs from the run of the key migration script? It should be safe to (re)run the script if necessary, and that might help see whether there was a problem in the migration itself.
- Does _either_ version of the node (either before or after the upgrade) work on the key-migrated data? This would rule out whether (say) migration failed or missed some keys.

**Comment by creachadair** [comment]
Another thing you might try, is to run `tendermint inspect` on the database you migrated. This starts up a node-shaped RPC service, but without any of the consensus bits, which you can then make RPCs into to check the state of the data.  That could give you a way to check whether the issue is that the app itself is confused, or if the data weren't properly migrated.
