### ISSUE TITLE
ABCI++: application to control how many txs it receives in PrepareProposal

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7750]
## Context

As is currently planned in ABCI++, Tendermint sends the application up to `ConsensusParams.Block.MaxBytes - CommitBytes - HeaderBytes - EvidenceBytes` of txs. It also sends this number so that applications know the maximum amount of transactions they can return (if they want to add txs or modify them). If applications tend to merge or squash a lot of txs, or they need to filter through and either delay or remove txs, having this limit means they will tend to have undersized blocks. 

## Proposal

I would instead propose that the application returns the amount of txs (in bytes) it would want in `ResponseFinalizeBlock` for the following height. This is somewhat similar (mechanically) to how we do pruning using `RetainHeight`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by williambanfield** [comment]
I think that what this proposal is getting at is that the initial list of Tx that are sent to the application in `PrepareProposal` may not be the correct list: The application may want more Tx or it may want to delete Tx from the mempool or replace some. The application likely wants to fill the block during PrepareProposal, so passing the application a big list of Tx is a decent way to ensure that we pass the application enough to fill the block.

I wonder if an iteration-based approach might be slightly cleaner. This iteration-based approach would entail adding new ABCI methods, `MoreProposalTxs()`, and `EndPrepareProposal()` that Tendermint would be able to repeatedly call on the application. The `PrepareProposal` phase would look a bit more like the old `ABCI` `BeginBlock`->`DeliverTx`->`EndBlock` flow. 

The flow would be as follows: `PrepepareProposal` -> `MoreProposalTxs` -> `EndPrepareProposal`. After each `MoreProposalTxs`, the application could indicate in its response that it was not done filling the block through some response code and TM would continue to dutifully hand Tx from the mempool to the application until the application indicated it was done or until the mempool reached the end.

**Comment by cmwaters** [comment]
With an iteration-based approach you have the advantage of requesting only the txs that you need but the application must continually cache the txs and you have to deal with the IPC costs (which could be negligible but worth mentioning). I don't think the cost of say requesting double the size of the block and sifting through it so that only half makes it in is actually that computationally expensive but maybe I stand corrected

**Comment by williambanfield** [comment]
> I don't think the cost of say requesting double the size of the block and sifting through it so that only half makes it in is actually that computationally expensive but maybe I stand corrected

No, I don't really think that's much of an issue. The advantage conferred, as far as I can tell, by the iteration-based approach is that you're able to get exactly the amount of Tx you want. I.e. you iterate over the potential Tx until you have exactly enough. 

If the application wants to implement more sophisticated strategies for ordering Tx, it may be a bit out of luck if it doesn't see many Tx matching its criteria in the first batch. I.e., Say an application wanted to implement a mechanism to allow a Tx to specify an 'execute after height' mechanism: The mempool may hand the application a lot of txs that all request execution a few heights in the future and the application would have no way to grab any more Tx. It would just be stuck rejecting the Tx it was handed. That's somewhat of a contrived example, but you could imagine apps that wanted to delay execution of certain types of Tx but right now they would be at the mercy of order that the `PrepareProposal` method delivers them.

**Comment by creachadair** [comment]
> The advantage conferred, as far as I can tell, by the iteration-based approach is that you're able to get exactly the amount of Tx you want. I.e. you iterate over the potential Tx until you have exactly enough.

I think that advantage only really applies, however, if the application either doesn't care about the order (say, it just grabs the first n txn regardless) or the order of transactions is already what the application wanted. The latter seems to be the crux of the problem: The order is more or less arbitrary (e.g., when stuff arrived via gossip or was posted via RPC). If we don't want to own it, the app will have to look at ALL the txn (in the general case) to know which ones are "best".

> Yeah, this is definitely worth considering, especially since, for in-process ABCI applications, this means keeping identical data in two places. Although, it would be capped by `MaxBytes`, which defaults to `1Mb`, so perhaps not an enormous amount of data.

I don't think the design should privilege in-process applications in terms of responsibility. If the app wants to keep copies of transactions, and associate them with other metadata, the fact that we have similar data elsewhere in the process is not (IMO) a good candidate for deduplication.

**Comment by cmwaters** [comment]
> The order is more or less arbitrary (e.g., when stuff arrived via gossip or was posted via RPC).

The app can set the priority of transactions which is some relatively crude means of dictating the order with which it will receive transactions in `PrepareProposal`.

If, in the extreme case, an application wants complete control then they can take the entire mempool and pick accordingly. This isn't ideal in terms of duplication but it works and I don't think it should be too much of a problem with either method we go for.

On a slightly adjacent note, I don't think that having unfilled blocks is a disaster. 99% of blocks currently don't reach maximum capacity anyway that's why I don't think the case of the application saying: "Give me n transactions for this next block, oh shit I misestimated the amount I removed or squashed give me some more" is that much of a problem that we should bend over backwards for by providing an elegant request and response mechanism.

**Comment by williambanfield** [comment]
I would propose that there are currently two alternatives for how to implement this.

# One-shot approach
In the 'one-shot' approach, the node reaps a set of transactions from the mempool and hands them to the application. The size of the set of transactions handed to the application will be dictated by a new `ConsensusParam` that the application can update on each `FinalizeBlock` call.

ConsensusParams would take the following form:

```proto
message ConsensusParams {
...
    ABCIParams abci = 7;
...
}

message ABCIParams {
  // prepare_proposal_max_bytes configures the size of the 
  // set of transactions in bytes passed to the application during
  // PrepareProposal.
  // Set this value to -1 to retrieve the entire contents of the mempool
  // during PrepareProposal.
  // If this value is set to 0, then PrepareProposal passes at most
  // ConsensusParams.Block.MaxBytes worth of transactions to the application.
  int64 prepare_proposal_max_bytes = 1;
}
```

## Advantages 
* Simple to implement and understand
* Gives application flexibility to retrieve the entire mempool

## Drawbacks
### No way to fetch additional transactions
Once the initial set of transactions has been handed to the applications, it can only sift through them. If the set of transactions it receives does not contain enough of the transactions it's looking for, then it cannot keep searching. It must propose using just that set. 
This drawback can be overcome by receiving the entire mempool. Receiving the entire mempool, however, would be costly for out-of-process applications which would need to receive potentially gigabytes of data in the `PrepareProposal` call. In-process applications would not pay this cost, and would instead receiver pointers to the original transactions as they do now.

# Iterative approach
In the iterative approach, the application would continually receive a candidate set of transactions until it built its full proposal. Once it built the full proposal, the application would respond to the application with the full set of transactions. 

This would take the form of adding a new field to the `RequestPrepareProposal` and the `ResponsePrepareProposal`.

```proto
message RequestPrepareProposal {
...
  //  remaining_tx_bytes is the sum of the bytes of the transactions
  // that have not yet been passed to the application during the 
  // current PrepareProposal invocation.
  // If this value is 0, the application must respond with
  // the set of transactions to include in the next block.
  // It is an error to set get_more_status to GET_MORE_TX 
  // if reamining_tx_bytes is 0.
  int64 remaining_tx_bytes = 7;
...
}
message ResponsePrepareProposal {
...
  // proposal_complete_status is used to communicate to the node
  // if the application has completed the proposal.
  // If the application sets proposal_complete_status to GET_MORE_TX,
  // Tendermint will send an additional list of transactions to the application
  // for it to potentially include in the proposal. The application should
  // should not return the list of TxRecords if it sets GET_MORE_TX.
  // 
  // If the application sets proposal_complete_status to COMPLETE
  // it must also include the list of complete TxRecords to be included
  // in the proposal.
  ProposalCompleteStatus proposal_complete_status = 7;
  enum ProposalCompleteStatus {
    UNKNOWN = 0;
    GET_MORE_TX = 1;
    COMPLETE = 2;
  }
...
}
```

## Advantages
* Applications can more closely retrieve only the Tx needed, ceiling'd by the size of the `RequestPrepareProposal`.

## Drawbacks
### IPC overhead
Fetching each additional list of transactions will require the application to incur a new request/response overhead. For in-process applications, this is less onerous. Both in-process and out-of-process applications will have to access the mempool an additional time per request/response, which means potentially hitting the mempool lock each time.

**Comment by ValarDragon** [comment]
I think the one shot approach suffices for now, and we can transition to a request/response approach in the future if its needed. I don't really see a huge need for it though, since the application could also buffer everything it sees over CheckTx.

One thing that'd be nice in the one shot approach is if this could be a per-node config parameter (similar to the timeouts), rather than a consensus parameter in the state machine. Then this gives applications and validators more flexibility to play around with prepare proposal in prod. (Which I think is going to be extremely valuable)

**Comment by sergio-mena** [comment]
To add to @williambanfield's summary of yesterday's meeting, the solution based on an extra `config.toml` parameter won't break the ABCI++ interface when implemented, as long as the spec (and other docs) emphasizes that the App may be _obliged_ to shrink the set of transactions it receives on `RequestPrepareProposal`.
I will open a PR to clarify this on the spec.
