### ISSUE TITLE
key migration: correctly migrate the seen commit key

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7755]
## Summary

There seems to be a problem where we are not migrating the `SeenCommit` correctly. 

## Problem Definition

If perform an upgrade as follows: 

1. Run v0.34.x
```
tendermint init validator && tendermint start --proxy_app persistent_kvstore
```
2. stop it after it produces a few blocks. Then update the config and change to the v0.35.x binary.
3. Run `tendermint key-migrate`
4. Run `tendermint start --proxy-app persistent_kvstore`

I get:
```
2022-02-02T16:55:12+01:00 INFO starting service impl=multiAppConn module=proxy service=multiAppConn
2022-02-02T16:55:12+01:00 INFO starting service connection=query impl=localClient module=abci-client service=localClient
2022-02-02T16:55:12+01:00 INFO starting service connection=snapshot impl=localClient module=abci-client service=localClient
2022-02-02T16:55:12+01:00 INFO starting service connection=mempool impl=localClient module=abci-client service=localClient
2022-02-02T16:55:12+01:00 INFO starting service connection=consensus impl=localClient module=abci-client service=localClient
2022-02-02T16:55:12+01:00 INFO starting service impl=EventBus module=events service=EventBus
2022-02-02T16:55:12+01:00 INFO starting service impl=PubSub module=pubsub service=PubSub
2022-02-02T16:55:13+01:00 INFO starting service impl=IndexerService module=txindex service=IndexerService
2022-02-02T16:55:13+01:00 INFO ABCI Handshake App Info hash="\x00\x00\x00\x00\x00\x00\x00\x00" height=17 module=consensus protocol-version=1 software-version=0.17.0
2022-02-02T16:55:13+01:00 INFO ABCI Replay Blocks appHeight=17 module=consensus stateHeight=17 storeHeight=17
2022-02-02T16:55:13+01:00 INFO Completed ABCI Handshake - Tendermint and App are synced appHash="\x00\x00\x00\x00\x00\x00\x00\x00" appHeight=17 module=consensus
2022-02-02T16:55:13+01:00 INFO Version info block=11 mode=full module=main p2p=8 tmVersion=v0.35.0
2022-02-02T16:55:13+01:00 INFO This node is a fullnode module=consensus
panic: failed to reconstruct last commit; commit for height 17 not found
```

I believe this is because we straight swap the keys at each height. However, in v0.35 we also made another change to the `SeenCommit` which instead of storing the `SeenCommit` at every height we store only the last one as it is only the last one that gets used for consensus.  

## Proposal

Modify the migration script so we find the last seen commie, migrate that key and remove all the other seen commits.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tychoish** [comment]
I think I see the logic of the fix, though there are a couple of questions concerns:
- the migration script moves each item in the database from the old format to the new format. The "old values" were in the database before and weren't causing problems. 
- the migration script doesn't introspect the values it migrates and assumes that each key value pair is (for its purposes) fully orthogonal, so adding this new migration logic isn't super straight forward.

Is it viable to walk about the `SeenCommit` change in 0.35 or make it backwards compatible without the migration?

**Comment by cmwaters** [comment]
> Is it viable to walk about the SeenCommit change in 0.35 or make it backwards compatible without the migration?

walk about meaning to revert that change?

We could write a separate migration script just for the seen commit that should happen either before or after the key migration one.

**Comment by cmwaters** [comment]
Yeah keeping it simple for users makes sense.

There was another concern with migrating in that the v0.34 config becomes invalid in v0.35 because of the renaming from `fastsync` to `blocksync`. Do you think it would make sense to also provide support there?

**Comment by tychoish** [comment]
I think the config changes are easier for people to do manually, though clearly it wouldn't be terrible to make the migration/upgrade path easier, by changing something in the code. Having said that, I think the config issue is entirely orthogonal.

I also don't know that I fully understand what should happen with the `SC` items in the database or if we should:
- do an extra migration, which might make the upgrade process take longer
- revert the change in 0.35
- add some kind of compatibility code so that the old data doesn't confuse the new implementation.

**Comment by tychoish** [comment]
are this issue and #7737 duplicates?

**Comment by cmwaters** [comment]
> are this issue and https://github.com/tendermint/tendermint/issues/7737 duplicates?

This issue came about from talking with Yaru and trying to debug the issue it opened. It might solve it but I have a feeling there were other things that might have caused the migration to fail.

> I think the config changes are easier for people to do manually

Sure its just a quick find and replace although I believe the value proposition Cosmovisor is trying to achieve is that the upgrade process is automatic. We don't have to do it but I assume if we don't that the Cosmos SDK will. I brought it up simply because I experienced it when trying to migrate and we're talking about migrations.

> do an extra migration, which might make the upgrade process take longer

I think it will but I don't think it will have a considerable impact. I'm averse to reverting the change because it will break chains that started on v0.35.0 and v0.35.1. There probably aren't any of importance but principally I don't like the idea.

**Comment by creachadair** [comment]
I think it makes sense to keep `key-migrate` scoped to just the database migration. That said—if we think the key format change was worth keeping at all, it's probably worth making it stick for v0.35 rather than rolling it forward.

**Comment by cmwaters** [comment]
> I think it makes sense to keep key-migrate scoped to just the database migration. 

Yeah definitely.
