### ISSUE TITLE
Proposer-Based Timestamps: Diagnostic 'runbook'

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7756]
# Summary
Proposer-based timestamps adds a new criteria for considering a block 'valid'. Therefore, validators may begin to prevote nil in cases that they would not previously have done so. It may not be immediately clear to operators and chains why a validator is prevoting nil. We should generate a runbook to help operators diagnose this condition. This runbook should rely on the newly added metric for determining timely-ness that was added as part of the implementation steps. See: #7709 for the relevant metric. It should consist of fine-grained and actionable steps that an operator may take to determine if the reason that they are not producing blocks is related to issues with synchronization and similarly actionable steps that they can take to correct the issue.

## Open Questions

Is it reasonable to assume that operators are monitoring their nodes with prometheus? Prometheus is a very common tool used to capture metrics for production software. If we can assume it is being used, the runbook can rely on standard monitoring and alerting that users of prometheus are likely to have in place.

**Comment by brennhill** [comment]
I don't think it's reasonable to make that assumption unless we provide an effortless connector and instructions.

**Comment by williambanfield** [comment]
Thanks for the response @brennhill. Out of curiosity, do you run validator nodes? 
We do publish many metrics that can be scraped directly from prometheus, so what would a 'connector' be in this case?
