### ISSUE TITLE
Proposer-Based Timestamps: Synchronize the ADR with the spec

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7758]
# Summary

ADR-71 describes the implementation steps for proposer-based timestamps. New spec development occurred between its initial inception and the implementation of PBTS. We should aim to synchronize these two documents to clarify what was built.

**Comment by cason** [comment]
Hi, William, this link is broken: https://docs.cosmos.network/v0.43/ibc/overview.html#acknowledgements (Alternative Approaches section, IBC item).
