### ISSUE TITLE
Metrics: Replace 'peer_id' with 'Moniker'

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7766]
A set of the p2p metrics [are annotated with the ID](https://github.com/tendermint/tendermint/blob/ce61abc038c794c3b22f210f2fa9e2a50697df92/internal/p2p/metrics.go#L79) of the peer a node is connected to. This produces metrics of the following form:

```
tendermint_p2p_peer_send_bytes_total{chID="0x20",chain_id="cosmoshub-4",peer_id="ee68cdd7ead64ec50a6161faee4a21d651403475"} 1.74380314e+08
```
However, this ID is not particularly meaningful to node operators. Operators report that they would prefer to have these instrumented with the 'moniker' of the peer instead.

**Comment by peterbourgon** [comment]
IDs are unique, but monikers unfortunately are not. Duplicate monikers would make corresponding metrics unsound.

**Comment by JayT106** [comment]
perhaps we can add a `Moniker` label prior to the peer_id
