### ISSUE TITLE
Metrics: Operators report that missing blocks is calculated incorrectly

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7770]
Tendermint publishes a metric for the number of blocks that the validator has 'missed'. The metric takes the following form:

```
# HELP tendermint_consensus_validator_missed_blocks Total missed blocks for a validator
# TYPE tendermint_consensus_validator_missed_blocks gauge
tendermint_consensus_validator_missed_blocks{chain_id="cheqd-mainnet-1",validator_address="3C35D7CF08EE16F509A8C2D3805FC1937D4BC5F3"} 3
```
Operators report that this metric is not calculated correctly. They will miss many blocks in a row and only see the metric increment up a few times, not correctly capturing all of the blocks the validator missed.

**Comment by RicoToothless** [comment]
We are facing a similar issue as well.

Our validator is up but it keeps missing blocks after we created a new validator. The strange thing is, it is fine on the scanner website and API (We use [cosmos-exporter](https://github.com/solarlabsteam/cosmos-exporter) to do the API query)

It happened on Cosmos Hub and IRIS testnet.

![image](https://user-images.githubusercontent.com/39393540/177985734-476127cf-64e5-4c4b-b015-0461fd467267.png)

The workaround solution: Create a new validator. Maybe there is another better way to do this.
