### ISSUE TITLE
Barak and Debora issues

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#78]
- [ ] fix debora stop
- [ ] take hosts from cli
- [ ] --bg labelname
- [ ] some way to unite the logs across boxes so we can easily grep through them all (since they might deploy at different seconds and so have different names)
- [ ] `debora status` should return which jobs are running too
- [X] barak should close and release log files.
- [ ] debora open/close should take "0.0.0.0:port" and ":port" as well.  (currently must be "[::]:port")
- [ ] move debora public key out of group config?

**Comment by jaekwon** [comment]
There's `debora list`, is that sufficient for the last item?

**Comment by ebuchman** [comment]
debora list is probably fine but has lots more info. would be nice if status also just listed the names of running processes? (i love one liners)

**Comment by jaekwon** [comment]
Yeah that sounds great.
