### ISSUE TITLE
Test flake in CI on TestReactorValidatorSetChanges

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7824]
## Repro

I have not yet had success reproducing this locally, but this is the command to run the test that flakes in CI.

```sh
go test -run TestReactorValidatorSetChanges ./internal/consensus
```

If you are running this test repeatedly on macOS, you will probably want to do this first, as the KV store is profligate with descriptors. 🦝

```sh
ulimit -n unlimited
```

## Observe

```
--- FAIL: TestReactorValidatorSetChanges (36.80s)
    reactor_test.go:201: 
        	Error Trace:	reactor_test.go:201
        	            				reactor_test.go:210
        	            				asm_amd64.s:1581
        	Error:      	Received unexpected error:
        	            	tx already exists in cache
        	Test:       	TestReactorValidatorSetChanges
FAIL
```

**Comment by tychoish** [comment]
I've seen this fail a lot recently. 

Relatedly, this test no longer runs with the persistent app ( after https://github.com/tendermint/tendermint/commit/61a81279bd6ebfded58979783629b2916195fca3) which should obviate the need to mess with ulimits. 

I think though we could imagine that if a tx is in the mempool we could just not error, I'd 100% believe that timing effects + the change to the caching policy of the mempool would definitely cause us to hit this error in a way that we hadn't before.

**Comment by tychoish** [comment]
Having said that, I've seen this test fail both in the way you link above and also in a more generic timeout (in CI only still), and I don't think that my test would address the timeout case, though maybe the change to not write files made the timeout case less likely to happen.
