### ISSUE TITLE
e2e: extension of the framework

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#7832]
## Summary

[RFC 004](https://github.com/tendermint/tendermint/blob/master/docs/rfc/rfc-004-e2e-framework.rst) discussed the value of the e2e framework and highlighted a few ways with which it could be improved. I would like to propose that some of these suggestions be transformed into more concrete designs that we should prioritise this as part of our objective to gain greater confidence in our release. 

Specifically, I think there should be a separation of desired outcome in our end to end testing, namely:
- Correctness: does Tendermint perform state machine replication correctly even given arbitrary failures of less than 1/3 of the network.
- Performance: is Tendermint robust enough to handle a variety of stress conditions (not just transaction load but other variables like size of the network). 

Our existing test suite currently does a good job at detecting failures in correctness. I would like to leverage the existing tooling (i.e. node orchestration) to be able to support the testing of performance in what would be similar to a staging environment or canary testnet. This would be deployed not after every commit to master but after large projects are merged and before the cutting of releases. 

This performance orientated testnet should have the following characteristics
- Large and geographically disperse set of participating nodes. We currently don't run networks greater than 7 nodes whilst production grade networks have a couple hundred. We also run all nodes on the same machine which doesn't account for networking latency when passing messages.
- Flexible workload generation. In the same way that the current e2e test systematically generates every permutation over a range of possible configurations, we should apply the same to workload generation. Systematically injecting transactions across several dimensions: number of transactions, size of transactions, duration of load, frequency of load (i.e. over bursts), distribution of load (do we submit all transactions to a single node or across multiple).
- Metrics gathering. Use existing tools like prometheus and grafana to monitor for trends and record statistics for comparison across versions / commits / network configurations. 

Rather than producing a full product we should focus first on getting a minimal design that can provide some insight and value.     
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
I'm generally in agreement that we should have these things. That said, at some point we cross over from an end-to-end test into a "live test network". Ideally an end-to-end test should continue to work as a CI-type job, where it can be set up and torn down entire. 

Exercising larger networks is not something that easily combines with setup-to-teardown automation: We might want to start and _maintain_ a network over, say, a handful of node instances in different metros—but spinning that up and tearing it down daily seems prone to a lot of noise. Perhaps we should consider these two separate (though related) concerns.

**Comment by tychoish** [comment]
I think I still like the thing that I wrote in the e2e RFC, and I think I agree with Michael's points about serverabiliy of concerns and goals. 

Having said that, I think at core our E2E framework (despite our frustrations with the actual tests) is a good thing, and I think we can get pretty far out of iterating on it. 

Practically speaking, the things I'd be excited about doing:
- make the load generation (which currently exists) more configurable, while keeping the current implementation as a base/default (for our current type of tests,) but allow manifests to specify (network wide/per-network) things like
  - duration of test
  - variable transaction sizes 
  - frequency of test creation 
  the workload should also be optional and it should be possible to disable it entirely (for just "run a test deployment case.) 
- improve the abstraction for orchestration. As much as I don't _like_ this solution, I think it makes sense to replace docker compose with [kind](https://kind.sigs.k8s.io) to enable running test deployments on more distributed environments (EKS/GKS/akash?). Regardless of the solution, the current orchestration stuff should definitely be revisited. 
- Operational improvements
  - improved reporting for the benchmark case, but also structured reports to facilitate inter-run comparsion/etc.
  - bring `run-multiple.sh` inside the tool.

I think all of these improvements would help e2e tests even if we don't expand the scope/use of the tool very much, but also make it possible to avoid writing _another_ orchestration harness, which seems worth avoiding. 

These could be good onboarding projects for the right new team member.

**Comment by cmwaters** [comment]
> Perhaps we should consider these two separate (though related) concerns.

To be clear, my idea was that they serve different purposes (albeit both at an integration level) and I'd expect the more large scale, performance-based smoke test to not be done every commit but just before releases and after large projects are merged. I was wondering whether some of the existing e2e infrastructure can be tweaked so that it can also serve to start up and tear down these larger networks but perhaps I'm wrong and we need to build a different orchestrator

**Comment by thanethomson** [comment]
I'm relatively confident that we can expand on our E2E testing framework to be able to switch between a Docker- and Ansible/Terraform-based infrastructure API, such that we can run our E2E tests with real networks and expand on our E2E testing for larger/more complex test cases.
