### ISSUE TITLE
The golang code in document `Creating an application in Go`

### ISSUE THREAD

**Issue by kth-tw** [tendermint/tendermint#7852]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:
In [this Chapter](https://docs.tendermint.com/master/tutorials/go.html#_1-4-starting-an-application-and-a-tendermint-core-instances), you provide a golang example code.
```
package main

import (
 "flag"
 "fmt"
 "os"
 "os/signal"
 "syscall"

 "github.com/dgraph-io/badger"

 abciserver "github.com/tendermint/tendermint/abci/server"
 "github.com/tendermint/tendermint/libs/log"
)

var socketAddr string

func init() {
 flag.StringVar(&socketAddr, "socket-addr", "unix://example.sock", "Unix domain socket address")
}

func main() {
 db, err := badger.Open(badger.DefaultOptions("/tmp/badger"))
 if err != nil {
  fmt.Fprintf(os.Stderr, "failed to open badger db: %v", err)
  os.Exit(1)
 }
 defer db.Close()
 app := NewKVStoreApplication(db)

 flag.Parse()

 logger, err := log.NewDefaultLogger(log.LogFormatPlain, log.LogLevelInfo, false)
 if err != nil {
  fmt.Fprintf(os.Stderr, "failed to configure logger: %v", err)
  os.Exit(1)
 }

 server := abciserver.NewSocketServer(socketAddr, app)
 server.SetLogger(logger)
 if err := server.Start(); err != nil {
  fmt.Fprintf(os.Stderr, "error starting socket server: %v", err)
  os.Exit(1)
 }
 defer server.Stop()

 c := make(chan os.Signal, 1)
 signal.Notify(c, os.Interrupt, syscall.SIGTERM)
 <-c
 os.Exit(0)
}
```
In this code, you exit the process by `os.Exit`, it doesn't trigger `defer` function which close socket and db.
Ref: [https://pkg.go.dev/os#Exit](https://pkg.go.dev/os#Exit)
```
Exit causes the current program to exit with the given status code. Conventionally, code zero indicates success, non-zero an error. The program terminates immediately; deferred functions are not run.
```

This results that the file `example.sock` is still in the directory.

**What you expected to happen**:
Use `return` exit the function. It will run `server.Stop()` and `db.Close()` after ^C.

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by creachadair** [comment]
Closing a Unix-domain socket doesn't unlink the socket file, that's something you'd have to do explicitly (even if the defers do run).

In this case, the `os.Exit` call is redundant anyway (it returns zero, which is what also happens when falling off the end of `main`), so we might as well remove it.
