### ISSUE TITLE
Remove RFC and ADR documents from backport branches

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#7865]
I propose to remove the `docs/architecture` and `docs/rfc` directories from backport branches, and have these documents live only on master.

Rationale:
1. The copies on the backport branches are incomplete. They have only the docs that were present at the time we cut the branch.
2. The files on the backport branches get outdated. They don't have any revisions to the files they do contain since the time we cut the branch.

We would need to include a step in the release notes, as part of creating the backport branch, to remove those directories after the branch is cut. However, I think that would be worth a little extra work on those (rare) occasions to keep things simpler for ongoing maintenance.

- [x] Remove from v0.35.x (#7866)
- [x] Remove from v0.34.x (#7867)
- [x] Remove from v0.33.x (#7879)
- [x] Update release instructions (#7846)

**Comment by cmwaters** [comment]
I'm guessing this can be closed now
