### ISSUE TITLE
Avoid `time.Sleep` in tests

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#790]
We should try to use channels and tickers whenever possible so we can set higher timeouts without impeding the tests.

Sometimes circle fails since these aren't heigh enough.

Eg. https://circleci.com/gh/tendermint/tendermint/1836#artifacts/containers/0 is due to https://github.com/tendermint/tendermint/blob/master/p2p/pex_reactor_test.go#L101

**Comment by zramsay** [comment]
#820
