### ISSUE TITLE
Enumerate Light Client verification trajectories

### ISSUE THREAD

**Issue by brapse** [tendermint/tendermint#7901]
The Light Client is responsible for getting the latest trusted state by verifying a sequence of headers. The validity of those headers must be substantiated by multiple witnesses in the execution of the fork detection protocol before they can be truly trusted. 

There have been extensive conversations about the different scenarios in in which verification can happen and what the expected outcome could be. For instance from https://github.com/informalsystems/tendermint-rs/pull/371#issuecomment-653642253

> If verification with the primary fails for any reason, we replace the faulty primary and perform verification again
> Otherwise, if the fork detector suspects
> a) a faulty witness, we replace the faulty witness and perform verification again
> b) that a witness timed out, we replace the faulty witness and perform verification again
> c) an actual fork, we report the fork, raise an error and abort

Or From https://github.com/tendermint/tendermint/issues/4694#issuecomment-639897804
> If a light client encounters two valid bisection traces, should it do full sequential verification to determine which trace is valid?

Both instances are mixed in lengthy conversation across multiple issues which make extracting the correct behaviour difficult for any potential implementer. It would be better if the spec included clear guidelines enumerating the different types of trajectories, across headers and witnesses, sequential/bisections to set expected behaviour for implementation.

What we are looking for here is to add a flow chart to the spec which can provide clarity to the different intermediate and terminal states.

Ref https://github.com/tendermint/tendermint/issues/5022
Ref. https://github.com/tendermint/tendermint/issues/5083

**Comment by cmwaters** [comment]
I tend to agree with this. The light clients detection mechanism has become quite a complicated protocol and it would be great to be able to support it with some sort of schematic that explains the decision making process when comparing headers
