### ISSUE TITLE
doc page is 404

### ISSUE THREAD

**Issue by Mrfogg** [tendermint/tendermint#7935]
this doc page is response 404 

https://docs.tendermint.com/master/

**Comment by creachadair** [comment]
We removed the docs for the master branch, as we found a lot of folks being confused by the unreleased changes. If you visit https://docs.tendermint.com you should be able to find the latest docs. But can you say where you saw a link to master? It looks like we might have missed updating that to point to the default.

**Comment by creachadair** [comment]
Hmm. It appears a lot of the search results on Google point directly to master for whatever reason.

I think we ought to probably set up a redirect from master to the latest release (v0.35) on the generated site, so that those links at least go somewhere relevant instead of 404.

**Comment by Mrfogg** [comment]
> We removed the docs for the master branch from the generated site, as we found a lot of folks being confused by the unreleased changes.
> 
> If you visit https://docs.tendermint.com you should be able to find the latest docs. But can you say where you saw a link to master? It looks like we might have missed updating that to point to the default.

![image](https://user-images.githubusercontent.com/7734816/155086426-6007a33a-f530-402d-85ec-a45e099bda6e.png)


this page

**Comment by creachadair** [comment]
Ok, these should all be working again now. My apologies for the disruption, and thanks for reporting the problem.
