### ISSUE TITLE
PBTS: evidence

### ISSUE THREAD

**Issue by josef-widder** [tendermint/tendermint#7943]
With proposer-based time, the consensus messages will change. In particular, there will be possible misbehavior w.r.t. the time value that is part of the messages. We need to capture in the specification the new evidence validation rules.

This might also be a good opportunity to add "double proposal evidence", that is, if the proposer equivocates.

**Comment by cason** [comment]
We can prove two "atemporal" misbehaviors for PBTS:
1. Proposing a value (`BlockID`) with a timestamp that does not match the block's timestamp (mentioned above);
2. Proposing at height `h` a timestamp smaller than or equals to the timestamp of the block committed at height `h-1`, thus violating monotonicity.

To prove other misbehaviors, we would need a way to produce "certificated" timestamps, which is more complex.
