### ISSUE TITLE
/dump_consensus_state: fix peer_round_state bit array marshalling

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#795]
got:

```
          "bits": 4,
          "elems": [
            0
          ]
```

want:

```
_ _ _ _
```

or 

```
X X X X
```

**Comment by melekes** [comment]
This can be done by overriding `MarshalJSON` / `UnmarshalJSON` functions, right?

**Comment by ebuchman** [comment]
believe so. think we just need to define those functions for the BitArray type

**Comment by jaekwon** [comment]
I don't think we should do this with MarshalJSON.
For developers, the existing struct's natural Amino:JSON format is fine.
Turning it into a custom formatted string makes it more difficult to create a compatible BitArray implementation in other languages.

**Comment by melekes** [comment]
> Turning it into a custom formatted string makes it more difficult to create a compatible BitArray implementation in other languages.

maybe it makes it more easier because now you're as a developer not limited to bits: int, elems: [uint64]. in Java for example, there is no uint64.

**Comment by jaekwon** [comment]
How about just a simple string of "-" or "x" with no BA{?:} wrapper?

**Comment by jaekwon** [comment]
Or I guess BA{-----} works too.  I just don't like the prefix as much :)

**Comment by melekes** [comment]
> I just don't like the prefix as much

Me neither

**Comment by melekes** [comment]
btw, if we only use MarshalJSON/UnmarshalJSON while viewing `/dump_consensus_state`, what's wrong with it?

**Comment by jaekwon** [comment]
it's OK I guess, esp since javascript doesn't support uint64.  If it were uint32, maybe I would argue that a list of uint32s are a more compact representation, and also sufficiently easy for developers to grok, that there's little point making the JSON pretty... but I don't mind as long as it's easy to parse.

I think of BA{...} more as debug output than a proper encoding, but I could just change that perspective.

**Comment by melekes** [comment]
tmlibs 0.8.3 (https://github.com/tendermint/tmlibs/commit/d94e312673e16a11ea55d742cefb3e331228f898)
