### ISSUE TITLE
/Health endpoint broken in swagger

### ISSUE THREAD

**Issue by justyntemme** [tendermint/tendermint#7977]
Using the swagger located here https://docs.tendermint.com/master/rpc/#/Info/health 

The health endpoint fails to return a status code, instead returning an error. We are hopeful to use this piece of tech in our app, but noticed the docs were not working successfully.

**Comment by creachadair** [comment]
Hi, @justyntemme. I'm not sure what you're reporting here: Are you saying the documentation is incorrect, or that the `/health` endpoint itself is not working?

**Comment by justyntemme** [comment]
👋 Hello! When i try to use the swagger to execute the curl request it fails, if you scroll down to the health endpoint and click execute, it will fail to return data.

**Comment by creachadair** [comment]
Ah, I see, thanks. It looks like the request actually does work if you execute it directly:

```
% curl -X GET "https://rpc.cosmos.network/health" -H "accept: application/json"
{
  "jsonrpc": "2.0",
  "id": -1,
  "result": {}
}
```

so I am guessing this may be some kind of configuration problem on the OpenAPI doc.

**Comment by justyntemme** [comment]
The id of negative one is suppose to mean an error right? id should be 0?

**Comment by creachadair** [comment]
> The id of negative one is suppose to mean an error right? id should be 0?

No, that's just a normal JSON-RPC request ID (it's the ones the GET handler uses by default).

Looking at the browser logs in Chrome, it appears the error may be CORS related:

```
/master/rpc/#/Info/health:1 Access to fetch at 'https://rpc.cosmos.network/health' from origin 'https://docs.tendermint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
rpc.cosmos.network/health:1          Failed to load resource: net::ERR_FAILED
actions.js:440 TypeError: Failed to fetch
    at index.js:581:80
    at c (runtime.js:45:40)
    at Generator._invoke (runtime.js:271:22)
    at Generator.e.<computed> [as next] (runtime.js:97:21)
    at o (asyncToGenerator.js:5:20)
    at s (asyncToGenerator.js:27:9)
(anonymous) @ actions.js:440
```

That suggests maybe we need to tweak the configs to set the mode as described.

**Comment by justyntemme** [comment]
Okay then looks like our health endpoint should be working just fine. thanks for your help!

**Comment by creachadair** [comment]
I created #8020 for the underlying issue, and will close this one in favour of that. Thanks for reporting the problem.
