### ISSUE TITLE
node_info missing from available endpoints endpoint?

### ISSUE THREAD

**Issue by okwme** [tendermint/tendermint#7979]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

"github.com/tendermint/tendermint@v0.34.14",

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

      "github.com/cosmos/cosmos-sdk@v0.44.3 => github.com/cosmos/cosmos-sdk@v0.44.2",

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

n/a

**What happened**:

when you go to tendermint's RPC endpoint (ie https://rpc.cosmos.network) you see a list of available endpoints. it seems that `node_info` is missing? I saw it in the swagger at https://v1.cosmos.network/rpc/v0.44.5 and tried visiting it directly at https://rpc.cosmos.network/node_info and it worked but for some reason wasn't listed in the available endpoints, is that on purpose?

**What you expected to happen**:

https://rpc.cosmos.network/node_info to be included in the response of https://rpc.cosmos.network

**Have you tried the latest version**: yes/no

no

**How to reproduce it** (as minimally and precisely as possible):

see above

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

not sure how these nodes are configured

**node command runtime flags**:

not sure how these nodes are configured

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by creachadair** [comment]
Hi @okwme. It looks to me like maybe that version doesn't have this endpoint:

```
% curl -i https://rpc.cosmos.network/node_info
HTTP/2 404 
content-type: text/plain; charset=utf-8
date: Wed, 23 Feb 2022 17:47:19 GMT
x-content-type-options: nosniff
x-server-time: 1645638439
content-length: 19

404 page not found
```

That's consistent with it being absent from the list. That said: The relationship between the swagger docs and the actual implementation is tenuous at best, so I'm guessing maybe the doc versions might be out of sync with the build perhaps.

**Comment by okwme** [comment]
ahh i realize now that this is part of the REST API, not the RPC. That makes sense now, i wrote the address incorrectly on the first comment, it's actually: https://api.cosmos.network/node_info

this makes sense now, it's not missing just rather part of REST instead : )

thanks for checking as well and will close the issue!
