### ISSUE TITLE
Enable pluggable consensus

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#800]
Add support for multiple consensus engines that offer finality, such as HoneyBadger (use case behind TOR) or Hashgraph (high throughput for financial application).

**Comment by ebuchman** [comment]
This might be too general/vague to be a useful issue at this time. Besides, if implementations of other consensus protocols use ABCI, don't we already kind of have pluggable consensus ?

**Comment by ebuchman** [comment]
Closing in absence of more specific details
