### ISSUE TITLE
proto: use a breaking change checker in CI workflow of release branches

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#8003]
## Summary

All release branches i.e. `v0.34.x` should never contain any proto-breaking changes. To avoid a situation where this accidentally happens we should use a proto-breaking change checker (like the one provided by buf) in the CI of these release branches  

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by thanethomson** [comment]
Just to add to this from https://github.com/tendermint/tendermint/pull/8029#discussion_r826509151:

> FWIW, I think it's fine if we run the check on all branches, as long as we don't mark it as required for submission on master.

**Comment by creachadair** [comment]
> All release branches[…]

Probably: All **supported** release branches. My proxy for this has been "anything we agree to build for the static docs site", which currently includes v0.33.x, v0.34.x, v0.35.x, and tip.
