### ISSUE TITLE
Median clock

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#801]
Feature request:

During consensus, every validator could submit their view of UTC time. The median value of these views could be reported to the ABCI app in BeginBlock.

For instance, this would be useful for financial applications that needs to know about todays date.

**Comment by mdyring** [comment]
Perhaps something similar is already in the block header (time below)? Would be great with some details on this.

message Header {
	string chain_id = 1;
	uint64 height = 2;
	**uint64 time = 3;**
	uint64 num_txs = 4;
	BlockID last_block_id = 5;
	bytes last_commit_hash = 6;
	bytes data_hash = 7;
	bytes validators_hash = 8;
	bytes app_hash = 9;
}

**Comment by melekes** [comment]
> The median value of these views could be reported to the ABCI app in BeginBlock.

but the median value does not really tell you anything. if some node significantly lags behind, median can't still be OK given say 100 validators.

maybe we should add this to our RPC - `/status`?

**Comment by mdyring** [comment]
The idea is to have a "consensus" time for the application, so that it is deterministic and will be persisted in the blockchain (and hence is available for replay or nodes joining later).

It is not important if it is accurate as each node could use NTP or better time source for that. 

One use-case could be todays date for financial transactions (you could roll the date forward once the 
median time from the block tells you to), for expiring items from a cache, etc.

Can you elaborate how the current time value from the header is set? Perhaps it is "good enough", if the time is the same across all nodes and is persisted.

**Comment by melekes** [comment]
> Can you elaborate how the current time value from the header is set?

it's set by block proposer (https://github.com/tendermint/tendermint/blob/develop/types/block.go#L32).

**Comment by mdyring** [comment]
Does the validators look at this time when considering the validity of the proposal? (say, it if is +/- 1 minute from its own time)

I think the concept of a mutually agreed upon "estimate" of current time is useful to have recorded in each block.

**Comment by melekes** [comment]
So far as I know there is a TODO https://github.com/tendermint/tendermint/blob/develop/types/block.go#L56. But I agreed that we should set some borders

**Comment by mdyring** [comment]
The suggested logic in the TODO is dangerous, theoretically an invalid time could set too far ahead in the future thus halting progress until then. Even proposer with a clock off by a minute could lead to a "stutter" behaviour.

Not sure what the best approach would be, but the median time does not seem like such a bad idea to me.. Since we assume 2/3 must be honest anyway, the median value should never be "way off" and probably a better estimate of time than taking a single sample from the proposer.

The app can then ensure that time only moves forward in the rare case that the median value moves backwards compared to the previous block (which should be a very rare occurrence even with block times in the second range).

**Comment by melekes** [comment]
> I think the concept of a mutually agreed upon "estimate" of current time is useful to have recorded in each block.

I will need @ebuchman vote on this one.

**Comment by ebuchman** [comment]
The plan is to do this. Details are still being sorted

**Comment by adrianbrink** [comment]
Implemented here: https://github.com/tendermint/tendermint/blob/master/types/block.go#L155

**Comment by srmo** [comment]
@adrianbrink is this field and it's usage/semantic already documented somewhere? 
PS: thanks for implementing this! We had many discussion what "time" means in an totally async network!

**Comment by adrianbrink** [comment]
@zramsay Is the time in header documented yet?
