### ISSUE TITLE
Resolve upgrade of tm-db to v0.6.7

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#8014]
The [recent automated upgrade](https://github.com/tendermint/tendermint/pull/7939) of Tendermint's import of tm-db to v0.6.7 failed.  Although the API for the Go library is compatible, v0.6.7 depends on a fork (I think?) of the underlying C library code for RocksDB, and that breaks the build automation Tendermint Core currently uses.

The breakage only occurs when the `rocksdb` build tag is enabled in `TENDERMINT_BUILD_OPTIONS`, but that currently affects our end-to-end tests, which build with all supported tags.

**Action item:** Decide how to deal with this conflict.

### Discussion

There are several choices for how we could resolve this, including:

1. Skip v0.6.7 and remain pinned at v0.6.6.
2. Update the build automation to fetch and compile the patched C library.
3. Remove RocksDB support from Tendermint Core.

Option (1) is the least work, and in light of our intentions documented in [RFC 001][rfc001], this may be the simplest practical solution for now. One drawback is that if we need to patch tm-db to fix a bug or security issue, we'd then have to confront this again. Given, however, that the rate of updates to tm-db has been very low, this may be a reasonable gamble.

Option (2) is the most work, and provides dubious return on investment. While RocksDB is favoured by some operators for application storage, it does not provide any clear advantages for use by the consensus engine's internal storage. On the other hand, if we are _not_ going to upgrade to the latest tm-db version, leaving the old dependency in place may expose users to weird link-time issues, where the C libraries export different symbols. The latter is the main reason to consider (2) over (1).

Option (3) requires a few changes, and is a breaking change for existing use. For `master` this is not a concern, but will also need to address this issue for all supported release branches as well. Doing this would resolve the C link-time risk, and would still permit applications to build their own custom RocksDB integration. What would break is any node that might have been using RocksDB as its _consensus_ storage. We have some reason to believe such usage is rare (if any), but it's a question that deserves a clear answer.

### Recommendation

I believe (3) is our best option, and (1) is a reasonable alternative. I do not think we should implement (2). Note that neither (1) nor (3) prevents _applications_ from continuing to use the RocksDB backend in tm-db, this is only about what the consensus engine uses.

[rfc001]: https://github.com/tendermint/tendermint/blob/master/docs/rfc/rfc-001-storage-engine.rst

**Comment by JayT106** [comment]
In Feb, the Cronos network (crypto.com) just switched to using the rocksdb as the backend storage to solve the network sync delay issue (observed the node has overloaded disk I/O with the leveldb), maybe there are other teams also using the rocksdb as the total storage.

**Comment by JayT106** [comment]
But it might be okay if the consensus storage does not support the rocksdb due to the main bottleneck is being on the SDK side.

**Comment by cmwaters** [comment]
What would happen for a node that was previously using rocksdb as the storage engine? i.e. what is the migration path across

**Comment by creachadair** [comment]
> What would happen for a node that was previously using rocksdb as the storage engine? i.e. what is the migration path across

We'd need to provide a migration tool. That would be relatively easy to write (there is no way to migrate in place, so it's a matter of cloning all the data from one to another). It'd require stopping the node, updating the data, changing the config file to select the new backend, and starting back up. 

Given we are about to start doing more substantial changes to the database we will need this anyway, though it may not be worthwhile to support migration to another tm-db backend at this point. (It is possible, though).

**Comment by cmwaters** [comment]
Yeah I can imagine that this would have been similar to the eventual database migration.

My interest in v0.6.7 stems from the pain point in validator operators at the moment (actually for some time now). Pruning with GoLevelDB doesn't really free up any disk space and so node operators are constantly having to restart their nodes (usually via statesync) to avoid bloating their servers. There is a tool here https://github.com/binaryholdings/cosmprund which some use to periodically compact GoLevelDB. It uses tm-db v0.6.7 as Marko wrote up a method called `ForceCompact` for this purpose. I would like Tendermint to adopt some form of this in the CLI to assist validators. Now, there are other ways of doing this without updating the tm-db dependency but at first glance this seems to be the simplest.

**Comment by iramiller** [comment]
We have a dbmigrate tool written already that does this. We use it for testing and porting between various backends

https://github.com/provenance-io/provenance/tree/main/cmd/dbmigrate

**Comment by creachadair** [comment]
> There is a tool here https://github.com/binaryholdings/cosmprund which some use to periodically compact GoLevelDB. It uses tm-db v0.6.7 as Marko wrote up a method called `ForceCompact` for this purpose. I would like Tendermint to adopt some form of this in the CLI to assist validators.

When I wrote this issue, there wasn't any obvious pressing concern. (Though it sounds like maybe this problem already existed, just not very clearly documented). This is a reasonable case to revise my original recommendations. As far as I know, RocksDB compatibility is the only hitch to doing this upgrade—the main sticky part is that we are somewhat pinned against an unfortunate dependency choice by the SDK. We can work around it if we need to.

That said: However we work around (whether patching the TM build, eliminating Rocks, or some other tactic) we will have to backported at least as far as v0.35 or it won't help any existing networks. Realistically even then it will be a while before it does. I'd argue any case for going back into v0.34 should come with a clear argument for the impact to justify spending the time on it.

**Comment by faddat** [comment]
@iramiller 🙏 

https://github.com/tendermint/tm-db/issues/260
