### ISSUE TITLE
proto: Upload protos to Buf schema registry from CI

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#8017]
Follows from #7975 and conversations with @marbar3778.

It would be very useful to consumers of our `.proto` files if they were uploaded to the [Buf schema registry](https://buf.build/). We should add a CI workflow that does this automatically.

Question: should we do this only for releases, or for each versioned branch (i.e. `master`, `v0.34.x`, `v0.35.x`, etc.)?

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
I think we may need to do it per release, since releases may contain changes to the protobuf files. Even if we eliminate wire-breaking changes, the types still need to be kept in sync.
