### ISSUE TITLE
About the timeout of RoundStepPrevote/RoundStepPrecommit

### ISSUE THREAD

**Issue by zhiqiangxu** [tendermint/tendermint#8025]
This is actually not a bug report rather a discussion ..

In tendermint, `RoundStepPrevote/RoundStepPrecommit` will never timeout until `2/3` of any votes are received, this is quite different from normal pbft protocols, which schedules a timeout for the next step no matter whether `2/3` votes are received for current step.

Is there any theoretical analysis for this change?

**Comment by cason** [comment]
I think this is a valid discussion. Do you mind reopening it at the https://github.com/cometbft/cometbft/ repository?
