### ISSUE TITLE
Enable pluggable DBs?

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#803]
A guy from BigchainDB said it would be cool if one does not need to fork Tendermint in order to run it with some other DB than levelDB.

**Comment by ebuchman** [comment]
This should already be doable. If one wants to inherit the entire tendermint CLI, one can use https://github.com/tendermint/tendermint/blob/master/cmd/tendermint/main.go#L34 and just pass in a NodeFunc that uses a DB of choice.

Or, if using Tendermint as a library, just pass in a db Provider of choice when calling NewNode: https://github.com/tendermint/tendermint/blob/master/node/node.go#L118

That said, we will probably look to improve the default db to something more performant than leveldb.

**Comment by vrde** [comment]
I took a look to the links you shared, and I found this nice set of [database interfaces](https://github.com/tendermint/tmlibs/blob/d9525c0fb671204450b160807480e1263053fb20/db/db.go). Specifically, the 
[github.com/tendermint/tmlibs/db/mem_db](https://github.com/tendermint/tmlibs/blob/d9525c0fb671204450b160807480e1263053fb20/db/mem_db.go) implementation seems easy to understand—I'm _quite_ new to Go, I started yesterday :dancer:

Would it make sense to do the following:
 1. fork this repo and fork `tmlibs`
 2. create a new file `tmlibs/db/mongo_db.go`
 3. :pray: write amazing code :pray:
 4. add the new backend `MongoDBBackendStr` to [db.go](https://github.com/tendermint/tmlibs/blob/d9525c0fb671204450b160807480e1263053fb20/db/db.go#L39) 
 5. change the local tendermint configuration to use the new backend `db_backend = "mongodb"`

**Comment by melekes** [comment]
6. send a PR :)

Cool! Welcome to the community

![](https://gophercon.com/assets/public/img/gophercon_logo_main.png)

**Comment by kunaldhariwal** [comment]
> This should already be doable. If one wants to inherit the entire tendermint CLI, one can use https://github.com/tendermint/tendermint/blob/master/cmd/tendermint/main.go#L34 and just pass in a NodeFunc that uses a DB of choice.
> 
> Or, if using Tendermint as a library, just pass in a db Provider of choice when calling NewNode: https://github.com/tendermint/tendermint/blob/master/node/node.go#L118
> 
> That said, we will probably look to improve the default db to something more performant than leveldb.

Can you please shed some light on first lines of your comment?

**Comment by ebuchman** [comment]
This is where we set up the root command of the entire tendermint CLI: https://github.com/tendermint/tendermint/blob/v0.27.0/cmd/tendermint/main.go#L42

The only argument is a `type NodeProvider func(*cfg.Config, log.Logger) (*Node, error) `. We use the DefaultNewNode (https://github.com/tendermint/tendermint/blob/v0.27.0/node/node.go#L83). But by passing in your own `NodeProvider` you can have a Node that uses any DB you like.
