### ISSUE TITLE
proto: Managing schema divergence in relation to specifications

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#8038]
At the time of logging this issue we find ourselves in a position where the generated Go code currently in the repo (i.e. all of the `*.pb.go` files) cannot be generated from Protobuf schemas at any point in the repository history. The reason for this divergence is that we've been using the protos as **data structure specifications**, and so the `.proto` files currently in the repo are effectively the goal state of where we want to get to.

In order to generate Go code from them, however, that doesn't break our builds, we now need to manually patch these files locally and generate that Go code using the dirty `.proto` files.

This probably arises because we have two conflicting needs:

1. We want to be able to define and experiment with breaking Protobuf schemas that may not yet be able to be implemented (e.g. during the specification process).
2. We want to have continual confidence in our `.proto` files that they definitely represent a single source of truth as to our actual data schema.

There are several possible approaches for when current and desired Protobuf schemas diverge:
1. @sergio-mena mentioned in recent discussions that we could add differently named copies of each file that diverges and then work on the copy. For example, if `proto/tendermint/abci/types.proto` needs to be updated, but we're not ready yet to implement the changes in the Tendermint code, we could copy that file to `proto/tendermint/abci/types.proto.next` and make changes in that file. We can then easily merge the files and delete the `.next` file when we're ready.
2. We could make a copy of the entire `proto` tree in the `spec` directory, and use this similarly to (1), copying files back when we're ready to implement them.
3. @williambanfield recommended an approach that keeps these diverged protos on branches related to the feature work currently underway (e.g. ABCI++-related changes would occur on a feature branch related to ABCI++).
4. Protobuf files could be treated exclusively as code and not as specifications, and specifications should only concern themselves with higher-level details. For example, if we absolutely had to include such detail, instead of giving a Protobuf schema, we could define a field as "an unsigned integer value". Protobuf files should be considered as part of the **implementation** of a specification.

Once we've decided on an approach to managing Protobuf schema divergence, we need to implement it practically in the code.

Personally I predict that option (4) will result in the least overhead overall and am generally in favor of options with less overhead :slightly_smiling_face: Options (3) and (4) also seem like they can easily coexist.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by williambanfield** [comment]
> @williambanfield recommended an approach that keeps these diverged protos on branches related to the feature work currently underway (e.g. ABCI++-related changes would occur on a feature branch related to ABCI++).

To elaborate on this: I don't see much of a usecase for maintaining an elaborate structure for storing the desired state of our protocol buffers in the main branch. If we are going to make a change to the protos, it will either be breaking or non-breaking. 

If the change is non-breaking, then there's no need to keep the desired protos anywhere at all. They should be compiled and checked into the repo, being tracked just in the main branch. I think that this will likely cover most of our usecases. We don't make breaking proto changes all that often. I think that ABCI++ is an exception that we shouldn't really bias too heavily towards, especially as we move towards 1.0 where we don't want to break our APIs almost at all. 

Insofar as changes cannot be modeled as non-breaking, they can and should live outside the main branch. These changes will need to accompany an ADR that will describe the changes to the proto files and should likely also include a branch with a prototype of the new protos anyway. Making the breaking change will take the form of integrating the prototype/demo branch into the repo in a series of pull requests.

**Comment by thanethomson** [comment]
Since we now generate our Go types from the protos, it seems like we can close this issue.

Some of the concern raised by this issue could possibly be addressed by #9197.
