### ISSUE TITLE
p2p: Better Broadcast

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#805]
Consider not launching a go-routine for each peer on every call to Broadcast.

Note that using go-routines means the current version doesn't guarantee multiple broadcasts are ordered with respect to each other.

**Comment by melekes** [comment]
So if we limit number of go-routines, does this means we can drop messages if peer can't handle so much load (N msgs in M sec.)?

**Comment by melekes** [comment]
Cause we can do 

```
		go func(peer Peer) {
			defer wg.Done()
			success := false
			if peer.CanSend(chID) {
				success = peer.Send(chID, msg)
			}
			successChan <- success
		}(peer)
```

then

**Comment by melekes** [comment]
The problem with just using something like https://github.com/Jeffail/tunny is bad peer can hold all the workers. So it should be N goroutines per peer. Note [above modification](https://github.com/tendermint/tendermint/issues/805#issuecomment-357110973) essentially means 1 goroutine per peer.

**Comment by jaekwon** [comment]
``peer.CanSend(chID)` doesn't work because it's not atomic.  Send can still fail.  So we probably shouldn't ever implement CanSend.

Yes, it should be N goroutines per peer.

The above violates the desired property of ordered broadcast messages:  If I broadcast X, then Y, then a peer should never receive X after Y.  (though messages can get dropped, for now).

It's also potentially blocking on `successChan <- success`, so depending, it's not N goroutines per peer.  We probably want to create N broadcastRoutine services per peer, that also ensures that successChan isn't too blocked...

**Comment by melekes** [comment]
## Option 1

Ok, what if we create 1 broadcast queue (say size=100) per peer. Upon receiving Broadcast call, we copy msg to each queue and for each peer there will be a go-routine reading from that queue and sending msg to peer.

Q: should queue be persistent?

## Option 2

Or we can create common persistent queue for all peers. each peer will store `marker` (position of the last broadcasted msg processed). for each peer there will be a go-routine reading from common queue and sending msg to peer plus updating `marker`

**Comment by ebuchman** [comment]
Oh I like Option 2. It would basically be like a `clist`, right ? Seems basically exactly how the mempool works.

Queues shouldn't need to be persisted - it's ok if we lose those messages. AddPeer method should make sure everything works out (eg. PeerState is reset when a connection drops and is re-added). In this context it's also ok to send a message twice (across a reconnection. we shouldn't be sending a msg twice for a given connection).

**Comment by melekes** [comment]
> It would basically be like a clist, right ?

right, but garbage collected (more like kafka's topic designed)

**Comment by xla** [comment]
Out of curiosity what properties make Option 2 more desirable than Option 1 where we get ordering and isolation from using one channel per peer?

**Comment by melekes** [comment]
Less memory, I think

**Comment by ebuchman** [comment]
Less memory , and only one queue for the Broadcast() to block on rather than 3

**Comment by milosevic** [comment]
In terms of synchronisation, do we need to prevent concurrent access in option 2?Can you explain why option 2 is more memory efficient? We can bound size of queues in both cases?

**Comment by melekes** [comment]
1) we'll have many concurrent readers, 1 writer 
2) 1 queue, not 3
3) we can and we will

Do you have other ideas?

**Comment by milosevic** [comment]
In option 1, 1 reader, 1 writer. For me option 1 seems like simpler and potentially more performant as sender coroutine will not need to fight for access to the shared resource. 
But I am not fully familiar with Go concurrency so I am maybe misunderstanding something. At least in Java, lock contention was something which we were normally trying to avoid whenever possible. Especially as we don't talk about 3 peers but potentially 50 or more.
How much memory efficient is 1 queue of size K compared to 3 queues of size K/3?

**Comment by xla** [comment]
> How much memory efficient is 1 queue of size K compared to 3 queues of size K/3?

The size would be K in both cases as option 2 proposes a single queue without message duplication and the readers manage the position in the queue (Kafka style consumers if I understood @melekes reference correctly).

**Comment by milosevic** [comment]
Then apart from the fact that we already have code for option 2, I don't see strong arguments in favour of option 2.

**Comment by ebuchman** [comment]
Right, option 1 is K*N memory where N is the number of peers. Option 2 is just K.

Let's talk about it more at tendermint core meeting monday

**Comment by melekes** [comment]
Will wait for a few days before implementing. Maybe @jaekwon will comment in the meantime.

**Comment by jackzampolin** [comment]
@melekes did you end up doing this?

**Comment by melekes** [comment]
No 😄
