### ISSUE TITLE
DOCS: URLs referring to master get 404

### ISSUE THREAD

**Issue by nooomski** [tendermint/tendermint#8052]
URLs pointing to master return a 404, which makes most google links unusable right now. Examples:

- https://docs.tendermint.com/master/nodes/
- https://docs.tendermint.com/master/nodes/state-sync.html
- https://docs.tendermint.com/master/introduction/what-is-tendermint.html

**Comment by creachadair** [comment]
(I'm closing this on the belief that it's fixed, but if I missed something feel free to reopen)

**Comment by nooomski** [comment]
Thanks for the quick response. Looks like everything is working again!

**Comment by nooomski** [comment]
@creachadair looks like it's happening again. Examples:

- https://docs.tendermint.com/master/nodes/
- https://docs.tendermint.com/master/nodes/validators.html
- https://docs.tendermint.com/master/tendermint-core/state-sync

**Comment by creachadair** [comment]
I think I see the problem, we landed a Markdown file with invalid front matter on master. The other branches are still building OK, which is why the rest still works. #8086 should clear it up. I'll rebuild the site once that merges.

I have to think about ways to catch such things sooner.

**Comment by nooomski** [comment]
@creachadair  We're using a [link checker](https://github.com/cosmos/gaia/blob/main/.github/workflows/linkchecker.yml) on Gaia, that's how we found out about it. Maybe that's something y'all wanna use? But maybe that won't work if all links are relative.
