### ISSUE TITLE
add peers via cli

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#8072]
## Summary

all node operators to add peers to a running node

## Problem Definition

currently to add peers to a running node we must stop the node and restart it. 

## Proposal

Add a way to add peers via cli to a running node. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
Is the idea here to only add peers dynamically, or would this also need to handle updating the config for persistent peers?

**Comment by marbar3778** [comment]
it would be nice to write it to the config, but don't think its necessary for the first implementation.

**Comment by JayT106** [comment]
The unsafe APIs used to have`/dial_seeds` and `/dial_peers`. However, the Tendermint RPC doc still keeps it. https://docs.tendermint.com/master/rpc/#/Unsafe/dial_peers
