### ISSUE TITLE
internal/consensus/state.go receiveRoutine can't panic

### ISSUE THREAD

**Issue by altergui** [tendermint/tendermint#8077]
In vocdoni we came across a node that OOM'd
https://github.com/vocdoni/vocdoni-node/issues/315

investigating the root cause, i believe it's due to the fact that this `panic()` 
https://github.com/tendermint/tendermint/blob/8df7b6103f6f48f0ca3c9a319937e4fae10e5668/internal/consensus/state.go#L910-L917
didn't manage to effectively panic (which i believe is the intention, given the message "check your file system and restart the node"), because of this `recover()` 
https://github.com/tendermint/tendermint/blob/8df7b6103f6f48f0ca3c9a319937e4fae10e5668/internal/consensus/state.go#L873-L886

i guess that recover function should add a check on the cause of the panic? 

or, altogether, don't try to recover at all? i mean, at least in this case, the node continued running without receiveRoutine(), and just died some time after OOM due to goroutine leak.

**Comment by creachadair** [comment]
This analysis seems pretty reasonable. I'm not sure what the intent was in handling the panic in this particular way—the comment suggests it's to avoid continuing, but it very much does continue. That handler has been around in the code for long enough that I'd be reluctant to remove it blind—it's not at all clear what else might be parked above it on the stack. 

We might think about doing a hard exit, or re-throwing the panic. That should at least let the binary exit without dumping us somewhere else random.

**Comment by altergui** [comment]
thanks for the feedback! very reassuring.

yeah, i had the feeling the safest change would be to check whether `r` is "failed to write %v msg to consensus WAL..." and in that case, re-throw the `panic(r)`

afaiu this would leave other panics unaltered (i.e. recovered) but would let that particular panic do the thing it's willing to do.

...but i'm not involved in this codebase nor do i have an overview, so i'll limit my contribution to this issue report and go back to my playfield, but i wanted to take the opportunity to thank you for all the hard work you put into this!! :heart:

**Comment by creachadair** [comment]
> yeah, i had the feeling the safest change would be to check whether `r` is "failed to write %v msg to consensus WAL..." and in that case, re-throw the `panic(r)`
> 

I think probably we shouldn't attempt to distinguish specific errors in this context. I think once we've had a panic out of the consensus machinery, we should likely _always_ terminate the binary. Having the handler there to provide a log seems reasonable, though.
