### ISSUE TITLE
p2p: code for MakeConnectedSwitches might be invalid every switch connecting to itself

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#808]
I was just reading through the MakeConnectedSwitches code and noticed that the 2 nested loops
https://github.com/tendermint/tendermint/blob/ec87c740a7cdc8591e97188f9e5ebfb4ded9d020/p2p/switch.go#L512-L516

pass in i == j thereby connecting every switch to itself. Is this intended? Doesn't seem so at least according to the comment https://github.com/tendermint/tendermint/blob/ec87c740a7cdc8591e97188f9e5ebfb4ded9d020/p2p/switch.go#L523-L525.

This code seems to only be used in tests
```shell
$ grep -Rn 'MakeConnectedSwitches' *
consensus/byzantine_test.go:87:	p2p.MakeConnectedSwitches(config.P2P, N, func(i int, s *p2p.Switch) *p2p.Switch {
consensus/reactor_test.go:47:	p2p.MakeConnectedSwitches(config.P2P, N, func(i int, s *p2p.Switch) *p2p.Switch {
mempool/reactor_test.go:48:	p2p.MakeConnectedSwitches(config.P2P, N, func(i int, s *p2p.Switch) *p2p.Switch {
p2p/CHANGELOG.md:53:- Fixes for MakeConnectedSwitches and Connect2Switches
p2p/switch.go:497:// MakeConnectedSwitches returns n switches, connected according to the connect func.
p2p/switch.go:501:func MakeConnectedSwitches(cfg *cfg.P2PConfig, n int, initSwitch func(int, *Switch) *Switch, connect func([]*Switch, int, int)) []*Switch {
p2p/switch_test.go:96:	switches := MakeConnectedSwitches(config, 2, initSwitch, Connect2Switches)
```
 but nonetheless it is exported code from p2p that's used in consensus tests.

Simple repro at 
https://play.golang.org/p/R5zbM3UqhN
```go
package main

import "fmt"

func connectThem(i, j int) {
	if i == j {
		fmt.Printf("i=%d == j\n", i)
	}
}

func main() {
	n := 10
	for i := 0; i < n; i++ {
		for j := i; j < n; j++ {
			connectThem(i, j)
		}
	}
}
```
which gives 
```shell
i=0 == j
i=1 == j
i=2 == j
i=3 == j
i=4 == j
i=5 == j
i=6 == j
i=7 == j
i=8 == j
i=9 == j
```

**Comment by melekes** [comment]
```
rg "MakeConnectedSwitches" | grep -v "tendermint"
go-p2p/CHANGELOG.md:- Fixes for MakeConnectedSwitches and Connect2Switches
go-p2p/switch.go:func MakeConnectedSwitches(n int, initSwitch func(int, *Switch) *Switch, connect func([]*Switch, int, int)) []*Switch {
go-p2p/switch_test.go:  switches := MakeConnectedSwitches(2, initSwitch, Connect2Switches)
```

**Comment by melekes** [comment]
Yeah, the code is strange, to say the least.

I think it should look more like:

```
for i := 1; i < n; i++ { 
  connect(switches, 0, i) 
}
```

**Comment by odeke-em** [comment]
@melekes or did we mean to say
```go
for i := 0; i < n; i++ {
   for j := i+1; j < n; j++ {
      connect(switches, i, j)
   }
}
```
for unidirectional connections:
n = 5
* i = 0 ==> (0, 1), (0, 2), (0, 3), (0, 4)
* i = 1 ==> (1, 2), (1, 3), (1, 4)
* i = 2 ==> (2, 3), (2, 4)
* i = 3 ==> (3, 4)
* i = 4 ==> ()


but then for a bidirectional connection:
```go
for i := 0; i < n; i++ {
    for j := 0; j < n; j++ {
        if i != j {
           connect(switches, i, j)
        }
    }
}
```

n = 5
* i = 0 ==> (0, 1), (0, 2), (0, 3), (0, 4)
* i = 1 ==> (1, 0),  (1, 2), (1, 3),  (1, 4)
* i = 2 ==> (2, 0), (2, 1), (2, 3), (2, 4)
* i = 3 ==> (3, 0), (3,1),  (3, 2), (3, 4)
* i = 4 ==> (4, 0), (4, 1), (4, 2), (4,3)
