### ISSUE TITLE
validators: On change from full-node to validating-node never vote until the next block

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#809]
Add a feature to tendermint core that ensures that when switching from full to validating node the new node doesn't vote until the next block. This will prevent double signing in the case of node failure.

@zmanian

**Comment by ebuchman** [comment]
I don't understand this. Is there a bug in the PrivValidator logic that admits double signing?

**Comment by zmanian** [comment]
As a validator I will likely implement fail over in the following manner.

1. My back up validator monitors a heart beat on my main server.

2. If the heart beat is unresponsive, my backup server will switch keys to my validator keys and to using a backup HSM.

3. Assume that zero state is synced to my backup, my backup doesn't know that last consensus signed before fail over. This is the point of maximum risk of incorrectly signing two messages at the same height.

4. If we always wait for a round to complete before voting on startup this risk is mitigated.

**Comment by ebuchman** [comment]
I see this is about validator fail over. Is this not something that can be handled in the validator itself? Ie. only allow it to start signing at height H?

**Comment by zmanian** [comment]
Then I need a specific piece of software running on the backup server that constantly tracks the height of the chain and use that as an argument for the fail over procedure.

This would be fine. Just need to put in the validator requirements documents

**Comment by jackzampolin** [comment]
Closing this issue as approaches to validator HA have evolved significantly since this discussion
