### ISSUE TITLE
replay error after running rollback with built-in kvstore

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#8095]
trying to check a rollback issue `panic: StoreBlockHeight (6) > StateBlockHeight + 1 (5)` related to  #7837, found another issue when testing the rollback against the built-in kvstore App. the node can produce blocks even the Client AppVersion is not matched with the genesis AppVer.

TM ver: 7c03e7dbfb25fea4c980b490c6572bd3ec48a9e4

Reproduce steps:
1. ./tendermint start --proxy-app kvstore, and wait few blocks generated.
2. ./tendermint rollback, got
```
Rolled back state to height 6 and hash 0000000000000000%
```
3. re-run  the node, got
```
ERROR: failed to create node: error="error on replay: wrong Block.Header.Version. Expected {11 0}, got {11 1}" closerError=""
panic: failed to create node: error="error on replay: wrong Block.Header.Version. Expected {11 0}, got {11 1}" closerError=""
```

**Comment by JayT106** [comment]
@creachadair do you think adding the genesis init height check will be reasonable? 
So check 1. the state height of the node is empty 2. the state height of the node is one block below the genesis initial height (for the genesis upgrade case)
https://github.com/tendermint/tendermint/pull/8068#discussion_r822092634

**Comment by firelizzard18** [comment]
@JayT106 Is there a workaround for this? I tried the one listed in cosmos/cosmos-sdk#10791 but I still got the same erorr.

**Comment by ewagmig** [comment]
For the built-in kvstore app, the app version is hard coded as `0x1` in file `abci/example/kvstore/kvstore.go`
https://github.com/tendermint/tendermint/blob/3324f49fb7e7b40189726746493e83b82a61b558/abci/example/kvstore/kvstore.go#L20
If it is set to `0x0` to keep consistent with that of default version in consensus params. 
Compile the code again, and it could work OK for the node from scratch.
However, this is not suitable for the existing chains with all data running.
