### ISSUE TITLE
Snapshot error - operation in progress conflict error

### ISSUE THREAD

**Issue by effofxprime** [tendermint/tendermint#8097]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
```
tendermint: 0.34.12
abci: 0.17.0
blockprotocol: 11
p2pprotocol: 8
```

**Environment**:
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

**What happened**:
Sometimes my RPC server that is setup for state sync will have issues creating snapshots.
```
Mar 09 00:08:59 rpc vidulumd[33544]: 12:08AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2007400
Mar 09 00:28:33 rpc vidulumd[33544]: 12:28AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2007600
Mar 09 00:47:59 rpc vidulumd[33544]: 12:47AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2007800
Mar 09 01:07:33 rpc vidulumd[33544]: 1:07AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2008000
Mar 09 01:27:11 rpc vidulumd[33544]: 1:27AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2008200
Mar 09 01:46:43 rpc vidulumd[33544]: 1:46AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2008400
Mar 09 02:06:13 rpc vidulumd[33544]: 2:06AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2008600
Mar 09 02:25:54 rpc vidulumd[33544]: 2:25AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2008800
Mar 09 02:45:32 rpc vidulumd[33544]: 2:45AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2009000
Mar 09 03:05:10 rpc vidulumd[33544]: 3:05AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2009200
Mar 09 03:24:53 rpc vidulumd[33544]: 3:24AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2009400
Mar 09 03:44:32 rpc vidulumd[33544]: 3:44AM ERR failed to create state snapshot err="a snapshot operation is in progress: conflict" height=2009600
```

Whats interesting is it's making snapshots, but on 'odd' numbered counts.  I have snapshots taken every 100 blocks.  Odd numbered, ie: 100, 300, 500...etc, snapshots exist, even numbers like from the error above, do not exist.

```
drwxr-xr-x   3 vidulum vidulum 4.0K Mar  9 02:26 2008700
drwxr-xr-x   3 vidulum vidulum 4.0K Mar  9 02:50 2008900
drwxr-xr-x   3 vidulum vidulum 4.0K Mar  9 03:08 2009100
drwxr-xr-x   3 vidulum vidulum 4.0K Mar  9 03:26 2009300
drwxr-xr-x   3 vidulum vidulum 4.0K Mar  9 03:48 2009500
drwxr-xr-x   2 vidulum vidulum 4.0K Mar  8 08:52 metadata.db
```

**What you expected to happen**:
No errors when creating snapshots and all snapshots are made.

**Have you tried the latest version**: yes/no
no

**How to reproduce it** (as minimally and precisely as possible):
I don't know.  It just begins to happen on it's own.  I have only had this happen to me once before, and I believe my resolution was to full restart the server/wipe the snapshots folder.  I wanted to check in first this time and see whats up?

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
See logs above.

**Config (you can paste only the changes you've made)**:
```
# State sync snapshots allow other nodes to rapidly join the network without replaying historical
# blocks, instead downloading and applying a snapshot of the application state at a given height.
[state-sync]

# snapshot-interval specifies the block interval at which local state sync snapshots are
# taken (0 to disable). Must be a multiple of pruning-keep-every.
snapshot-interval = 100

# snapshot-keep-recent specifies the number of recent snapshots to keep and serve (0 to keep all).
snapshot-keep-recent = 100
```
and
`pruning = nothing`
(I was just thinking state sync relevant settings, if you need/want all let me know)

**node command runtime flags**:
`vidulumd start`

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**
https://trpc.rpc.erialos.me/dump_consensus_state?
rpc.erialos.me for restapi.  

**Anything else we need to know**:
Restarting the daemon alone does not resolve the issue.

**Comment by creachadair** [comment]
This particular error ("failed to create state snapshot") appears to come from the Cosmos SDK base app ([current location](https://github.com/cosmos/cosmos-sdk/blob/5356a868255b7ad27ca418eb846ccb89a98d8bfd/baseapp/abci.go#L384)). The underlying error would seem to imply that a previous snapshot operation is hanging around incomplete, though I would expect restarting to have resolved that (perhaps it recurs).

@marbar3778 do you have any insights here? Given that this is Tendermint v0.34.12, it could be an issue previously fixed—possibly related to https://github.com/cosmos/cosmos-sdk/issues/9686?

**Comment by effofxprime** [comment]
Oh shoot, I feel dumb.  Im sorry for filing this in the wrong place. I appreciate you linking this over in cosmos for me.
