### ISSUE TITLE
consensus: trailing nodes can get stuck 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#810]
We detected a halted trailing node in the venus testnet (v0.10.0). It is receiving messages from up-to-date peers but not progressing. I believe the problem is as follows.

In gossipDataForCatchup, where we send block parts the peer needs, we take the `.Not()` of the peers BitArray of block parts (https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L502). But if the BitArray is nil, then `.Not()` also returns nil (https://github.com/tendermint/tmlibs/blob/master/common/bit_array.go#L135), which means we won't send any block parts at all! So the peer never ends up making progress.

I think we need to ensure the peer has the proposal first, so it initialized the ProposalBlockParts bit array to the right size, so that we'll send it peers. Alternatively, since we know how many block parts are in an old block, we can initialize the bitarray properly for them so we wont get `nil` on `.Not()`.

**Comment by ebuchman** [comment]
We could also solve this by switching back to fast sync if we're trailing by a lot (https://github.com/tendermint/tendermint/issues/129), but it does mean there's a flaw in our catchup/gossip logic in the consensus reactor.

**Comment by ebuchman** [comment]
Relevant for @milosevic and @cloudhead work on specing this. @melekes should also take a look

**Comment by melekes** [comment]
That's why I don't like the following code:

```
	if bA == nil {
		return 0, false
	}
```

> https://github.com/tendermint/tendermint/issues/810#issuecomment-342334513

this is more like a hack :)

> I think we need to ensure the peer has the proposal first, so it initialized the ProposalBlockParts bit array to the right size, so that we'll send it peers.

I would vote for that.

**Comment by ebuchman** [comment]
We don't actually need the proposals if we're catching up. So one decent fix is to check if the bitarray is nil and initialize it.

Currently, for a trailing peer, the bit array is initialized in `ApplyCommitStepMessage`. 

The bug can be replicated by commenting out the CommitStepMessage broadcast in https://github.com/tendermint/tendermint/blob/master/consensus/reactor.go#L359. Then just run one validator node and one peer node (without fast sync) and the peer will never catchup.
