### ISSUE TITLE
Querying large TX through RPC returns "unexpected EOF reading trailer"

### ISSUE THREAD

**Issue by V-Staykov** [tendermint/tendermint#8133]
**Tendermint version**: v0.34.14

**Environment**:
- **OS** Ubuntu 21.10
- **Install tools**:
- **Others**:

**What happened**:
We've created a large tx with 4000 messages (i.e. /cosmos.bank.v1beta1.MsgSend). When trying to query this tx in some cases we get  

`Error: failed to read response body: http: unexpected EOF reading trailer`

This **doesn't happen** when querying it from a local node, but happens if we run the CLI command with --node flag.
Also this works fine:
`curl http://<node_ip>:26657/tx?hash=<tx_hash>`

This seems to have something in common with this issue #6706

**What you expected to happen**:
I expect no errors.

**Have you tried the latest version**: no

**How to reproduce it**:
1. Create a large TX, in our case with 4000 messages.
2. Try to query the tx through RPC with:
`noded q tx <tx_hash> --node tcp://<node_ip>:26657 --chain-id <chanin_id>`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
`Error: failed to read response body: http: unexpected EOF reading trailer`

**Comment by creachadair** [comment]
We'd probably need to see the server logs to be sure, but that error message suggests the message was truncated. The RPC server doesn't have a built-in response size limit, and the fact that the `curl` request works suggests any truncation is happening in the code that handles the higher-level request in the SDK itself, rather than in the node.

**Comment by creachadair** [comment]
> The node prints this log, when queried for that tx: `ERR failed to write responses err="write tcp ip:port->ip:port: i/o timeout" module=rpc-server res=[{"id":0,"jsonrpc":"2.0","result":{"hash":"F...`

Thanks for the additional detail. That error probably originates from the `net` package, suggesting the response probably was not consumed within the write timeout. The node does set the [`http.Server.WriteTimeout`](https://godoc.org/net/http#Server.WriteTimeout) field, and a client that doesn't fully consume the response quickly enough may exceed it.

If the response is sufficiently large, whether the whole response gets consumed in time may well depend on how loaded the node is and how much network bandwidth it has available. That could account for the differences between nodes.
