### ISSUE TITLE
Investigate Lock Contention as Cause of Gossip Problem during Osmosis 'Epoch' Blocks.

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#8157]
Users report that during the Osmosis Epoch block, nodes will fully execute the block before gossiping it. This has implications for operators running a 'sentry' pattern. If a validator is running behind a sentry or set of sentries, then the sentries will execute the block before gossiping it to the validator. The validator will therefore _miss_ the block being gossiped and not vote on it.

We should attempt to alleviate issues related to gossiping blocks and ensure that blocks are gossiped while they are being executed.

**Comment by williambanfield** [comment]
https://github.com/tendermint/tendermint/pull/8139 #8138 and #7992 + #7994 attempt to alleviate the lock contention issue. These pull requests do two things: 
1. Yield the lock in the consensus reactor when a block proposal is completed. This ensures that other routines, such as the gossip routine, that wait on the consensus lock to gossip, will be able to access the `RoundState` as soon as the block is complete instead of waiting for the state machine to fully execute the transition that results from the complete block.
2. Allow the consensus reactor gossip routines to operate on a copy of the consensus state. Previously, the gossip routines would block waiting to acquire the consensus lock each time the routine ran. Now, the consensus reactor periodically reads the consensus state and updates the gossip routines operate on this copy.

**Comment by 08d2** [comment]
[I commented here](https://github.com/tendermint/tendermint/pull/8139#discussion_r833666451) but I'll repeat in this issue for visibility: these PRs read values under one lock, release the lock, and then evaluate them separately. Consequently there is no guarantee that the values are still valid. Even if the current implementation happens to avoid data races, the code is unsound.

**Comment by creachadair** [comment]
> [I commented here](https://github.com/tendermint/tendermint/pull/8139#discussion_r833666451) but I'll repeat in this issue for visibility: these PRs read values under one lock, release the lock, and then evaluate them separately. Consequently there is no guarantee that the values are still valid. Even if the current implementation happens to avoid data races, this has gotta be unsound, right? 😬

Can you say more about what would be unsound in this context? The state that's captured is a coherent snapshot of the state at a definite point in time during the execution of the operation, so it does not affect linearizability. I don't think we depend on the state not to change _after_ the point at which it's inspected—as long as it doesn't change during. Is there some other case I'm overlooking?

**Comment by 08d2** [comment]
> I don't think we depend on the state not to change after the point at which it's inspected—as long as it doesn't change during. Is there some other case I'm overlooking?

I guess my point is that, by reading the value at one synchronization point, and then acting on that value at a _subsequent_ execution point, it's possible that the value has in fact changed during the control flow.

**Comment by creachadair** [comment]
> I guess my point is that, by reading the value at one synchronization point, and then acting on that value at a _subsequent_ execution point, it's possible that the value has in fact changed during the control flow.

The changes @williambanfield mentioned do not allow additional currency _within_ the consensus reactor, they only allow messages to be handled by the other reactors. So while in principle the consensus reactor could interfere with itself, that shouldn't be an issue here.

**Comment by 08d2** [comment]
> The changes @williambanfield mentioned do not allow additional [concurrency] within the consensus reactor, they only allow messages to be handled by the other reactors

I'm not exactly sure how to parse this. "Concurrency" isn't really the issue I'm trying to point out — I'm saying the read can become stale before it's evaluated. Whether or not the calling code happens to trigger this condition is incidental — the bug exists if it _can_ happen, not if it _does_. I think? Right?

Concretely: if `added` is evaluated as true [on line 968](https://github.com/tendermint/tendermint/blob/e4ae922c333f89629e1a4e31bf408aa67008b223/internal/consensus/state.go#L968) but becomes false [between lines 981-983](https://github.com/tendermint/tendermint/blob/e4ae922c333f89629e1a4e31bf408aa67008b223/internal/consensus/state.go#L981-L983) — or vice versa — does this not represent a problem for the logic [on lines 987-1003](https://github.com/tendermint/tendermint/blob/e4ae922c333f89629e1a4e31bf408aa67008b223/internal/consensus/state.go#L987-L1003)?

If not, then I don't see why `handleMsg` takes the lock at the start of the method. It doesn't need synchronization until execution enters one of the switch cases, and apparently even then it may not need synchronization of execution at all, but rather of read values. Should the lock perhaps exist in the methods called by this method, i.e. `addProposalBlockPart`, `handleCompleteProposal`, and `tryAddVote`? The state protected by the mutex only seems to be directly accessed there, anyway? Am I missing something?

Furthermore...

```
// We unlock here to yield to any routines that need to read the the RoundState.
```

Unlocking and then immediately locking again provide no guarantee that other routines that may be waiting on the lock will be able to take it. All it does is introduce the possibility that the values read under the first lock will be changed by the time the second lock is taken.

**Comment by creachadair** [comment]
> I'm not exactly sure how to parse this. "Concurrency" isn't really the issue I'm trying to point out — I'm saying the read can become stale before it's evaluated. Whether or not the calling code happens to trigger this condition is incidental — the bug exists if it _can_ happen, not if it _does_. I think? Right?

It doesn't matter that the read is stale—the reader is only using the state to determine what messages to send out, and those messages should be valid at that state moment even if the state subsequently changes before the messages happen to be sent. 

The PRs linked above are not the ideal solution here, they're a workaround for an unfortunate control-flow design that we need to continue to clean up. There shouldn't be any safety or correctness issue, though.

**Comment by williambanfield** [comment]
Thanks for adding the clarifying comments @creachadair.

These PRs definitely do not represent a perfect end state of the consensus reactor. They're an attempted improvement over the current design to allow for block propagation to proceed under a specific, somewhat unfortunate condition. As far as I can tell, these don't represent any correctness issue since `added` and `err` are not being modified from within multiple threads. Happy to be corrected here about a possible issue but at the moment I don't see one.

**Comment by 08d2** [comment]
[tendermint/state.go](https://github.com/tendermint/tendermint/blob/e4ae922c333f89629e1a4e31bf408aa67008b223/internal/consensus/state.go#L968)

```go
func (cs *State) handleMsg(ctx context.Context, mi msgInfo) {
	cs.mtx.Lock()
	defer cs.mtx.Unlock()
	var (
		added bool
		err   error
	)

	msg, peerID := mi.Msg, mi.PeerID

	switch msg := msg.(type) {
	case *ProposalMessage:
```

`cs.mtx.Lock()` is taken at the start of the method, but for no reason, as far as I can see! 😅 Nothing up to and including this line of code requires it. It's only once the code enters the various case blocks that it becomes relevant.

The linked PR deals with BlockPartMessage, so,

```go
	case *BlockPartMessage:
		added, err = cs.addProposalBlockPart(ctx, msg, peerID)
```

addProposalBlockPart doesn't appear to require the mutex lock to be held, as it only interacts with public methods on `cs`, or fields which must be synchronized, like metrics.

```go
		cs.mtx.Unlock()
		cs.mtx.Lock()
```

So this seems unnecessary? I could be totally misunderstanding! What does `cs.mtx` actually protect?

**Comment by williambanfield** [comment]
> What does cs.mtx actually protect?

Ah, yeah the `mtx` protects the fields of `RoundState`, primarily so that readers from outside of this code don't read inconsistent/intermediate values. the `Lock` -> `defer Unlock` is just done for simplicity. There are certainly multiple ways of writing this code. The `added` and `err` vars are not what's protected by the lock.

> addProposalBlockPart doesn't appear to require the mutex lock to be held, as it only interacts with public methods on cs, or fields which must be synchronized, like metrics.

`addProposalBlockPart` needs the lock for reading and writing the fields on `RoundState`, e.g: https://github.com/tendermint/tendermint/blob/06e86206215a5689fd428860f2b5e9a48fe2a332/consensus/state.go#L1904. 

All fields of RoundState are public so that they can be interacted with by serializers and deserializers.

**Comment by 08d2** [comment]
> addProposalBlockPart needs the lock for reading and writing the fields on RoundState, e.g:

> All fields of RoundState are public so that they can be interacted with by serializers and deserializers.

If a value needs a lock in order to be safely read-from or written-to, then it should not be public, right? That synchronization should be safely encapsulated by methods?

**Comment by creachadair** [comment]
> If a value needs a lock in order to be safely read-from or written-to, then it should not be public, right? That synchronization should be safely encapsulated by methods?

As you've observed, there are various places where the organization of data, concurrency, and synchronization could be improved here. We would have done many things differently if we were starting over.  Longer-term, we are discussing how to more comprehensively refactor these reactors, to support model-based testing and improve the maintenance & unit-testing story.  In the meantime, though, I don't think there's too much to be gained from low-impact minor API changes that would churn local structure without addressing higher-level design issues.

**Comment by 08d2** [comment]
I understand and appreciate the balance of pragmatism and idealism. The problem with concurrency issues like these is that what may appear to be a pragmatic engineering choice is actually unsound, and what may appear to be an idealistic or perfectionist alternative is actually mandatory. To bring it back to this comment:

> We unlock here to yield to any routines that need to read the the RoundState.

Unlocking _allows_ but does not _guarantee_ that a waiting goroutine will be able to get the lock. If that's not a problem, good! But then there's no reason to unlock in the first place. If it is a problem, then this code may ameliorate but does not actually solve the problem, and the lock belongs somewhere else.

I've said what I can say at this point, so I'll bow out.
