### ISSUE TITLE
p2p: PEXReactor.Receive should not ignore peer's NewNetAddressString errors lest we crash

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#816]
If a peer's NodeInfo is intentionally malicious with an invalid port range ie >= `1<<16`, they can cause a PEXReactor to crash in the Receive routine by sending in bytes representing a binary encoded`*pexAddrsMessage` for example

```go
package main

import (
	"github.com/tendermint/go-crypto"
	"github.com/tendermint/tendermint/p2p"
	"github.com/tendermint/tmlibs/log"
)

func main() {
	addrB := new(p2p.AddrBook)
	prec := p2p.NewPEXReactor(addrB)
	if prec == nil {
		panic("nil Reactor")
	}
	peer1 := newFuzzPeer()
	prec.AddPeer(peer1)
	prec.Receive(0x01, peer1, []byte{0x02, 0x01, 0x01, 0x01, 0x01, 0x00, 0x30, 0x30})
}

type fuzzPeer struct {
	m map[string]interface{}
}

var _ p2p.Peer = (*fuzzPeer)(nil)

func newFuzzPeer() *fuzzPeer {
	return &fuzzPeer{m: make(map[string]interface{})}
}

func (fp *fuzzPeer) Key() string {
	return "fuzz-peer"
}

func (fp *fuzzPeer) Send(ch byte, data interface{}) bool {
	return true
}

func (fp *fuzzPeer) TrySend(ch byte, data interface{}) bool {
	return true
}

func (fp *fuzzPeer) Set(key string, value interface{}) {
	fp.m[key] = value
}

func (fp *fuzzPeer) Get(key string) interface{} {
	return fp.m[key]
}

var ed25519Key = crypto.GenPrivKeyEd25519()
var defaultNodeInfo = &p2p.NodeInfo{
	PubKey:     ed25519Key.PubKey().Unwrap().(crypto.PubKeyEd25519),
	Moniker:    "foo1",
	Version:    "tender-fuzz",
	RemoteAddr: "0.0.0.0:98991",
	ListenAddr: "0.0.0.0:98992",
}

func (fp *fuzzPeer) IsOutbound() bool             { return false }
func (fp *fuzzPeer) IsPersistent() bool           { return false }
func (fp *fuzzPeer) IsRunning() bool              { return false }
func (fp *fuzzPeer) NodeInfo() *p2p.NodeInfo      { return defaultNodeInfo }
func (fp *fuzzPeer) OnReset() error               { return nil }
func (fp *fuzzPeer) OnStart() error               { return nil }
func (fp *fuzzPeer) OnStop()                      {}
func (fp *fuzzPeer) Reset() (bool, error)         { return true, nil }
func (fp *fuzzPeer) Start() (bool, error)         { return true, nil }
func (fp *fuzzPeer) Stop() bool                   { return true }
func (fp *fuzzPeer) String() string               { return fp.Key() }
func (fp *fuzzPeer) Status() p2p.ConnectionStatus { var cs p2p.ConnectionStatus; return cs }
func (fp *fuzzPeer) SetLogger(l log.Logger)       {}
```

And we'll get back crash
```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x12626cc]

goroutine 1 [running]:
github.com/tendermint/tendermint/p2p.(*AddrBook).AddAddress(0xc4204300e0, 0xc4204352f0, 0x0)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/p2p/addrbook.go:165 +0x12c
github.com/tendermint/tendermint/p2p.(*PEXReactor).Receive(0xc4200afb90, 0xc42001ca01, 0x147ca80, 0xc42000e048, 0xc42001caa0, 0x8, 0x8)
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/p2p/pex_reactor.go:153 +0x355
main.main()
	/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/fuzz/p2p/pex-reactor/main.go:17 +0x10e
exit status 2
```

### Remedy
We can fix that by straight up capturing the error on parsing the peer's address that is
```diff
diff --git a/p2p/pex_reactor.go b/p2p/pex_reactor.go
index 54c2d06..0df37d2 100644
--- a/p2p/pex_reactor.go
+++ b/p2p/pex_reactor.go
@@ -120,7 +120,11 @@ func (r *PEXReactor) RemovePeer(p Peer, reason interface{}) {
 // Receive implements Reactor by handling incoming PEX messages.
 func (r *PEXReactor) Receive(chID byte, src Peer, msgBytes []byte) {
 	srcAddrStr := src.NodeInfo().RemoteAddr
-	srcAddr, _ := NewNetAddressString(srcAddrStr)
+	srcAddr, err := NewNetAddressString(srcAddrStr)
+	if err != nil {
+		r.Logger.Error("Invalid srcAddr", srcAddrStr, "err", err)
+		return
+	}
 
 	r.IncrementMsgCountForPeer(srcAddrStr)
 	if r.ReachedMaxMsgCountForPeer(srcAddrStr) {
```
Please note the bytes required to trigger this bug are from a binary encoded `*pexAddrsMessage`.

Found by fuzzing to generate the code path and then intentionally maliciously by hand with the invalid port.

**Comment by melekes** [comment]
Nice find!

**Comment by ebuchman** [comment]
Interesting. But I'm a bit confused about what has actually been discovered.

1) I don't think the patch is relevant here. It's checking the error on the source peer, whose address is initialized during the original connection handshake, and is independent on the msgBytes being passed in. That said, for defensive purposes, we should keep the patch, but it should basically never error, since we read RemoteAddr of our peers direct from the connection in https://github.com/tendermint/tendermint/blob/master/p2p/peer.go#L195

2) The panic seems to be coming from the fact that the addrbook.Logger is nil.

3) The addrbook is not initialized properly.

If I change the defaultNodeInfo to have proper ports, and initialize the addrbook properly (ie. `addrB := p2p.NewAddrBook("ok", false) `), this `msgBytes` does not cause a panic. 

Can we please clarify if there's an actual issue here or if it's just improperly setup tests?

**Comment by odeke-em** [comment]
@ebuchman:
1. the bytes passed in just trigged a path to where we had to invoke AddAddress which trips out since we have an invalid IP
https://github.com/tendermint/tendermint/blob/c931279960eaebd3992970c7db79dd4707f83324/p2p/pex_reactor.go#L149
2. Not really, it comes from code on branch `develop` not `master` and my apologies(please read point 3) --> https://github.com/tendermint/tendermint/blob/7f3c697b6e4c624aa0f8d29ff97e9bfe20deb8f9/p2p/addrbook.go#L688
3. My apologies, I was trying to make a minimal test but the actual code that triggered it is
https://github.com/tendermint/tendermint/blob/b122670a58627c170f99ba5a05923309157d3250/fuzz/p2p/pex-reactor/main.go which has a properly setup address book

If we re-run with a properly setup test but invalid addresses(out of range ports) for a peer, the IP will be nil but the port will eraneously be set to the value > 1<<16 and the panic occurs at https://github.com/tendermint/tendermint/blob/7f3c697b6e4c624aa0f8d29ff97e9bfe20deb8f9/p2p/addrbook.go#L688.

**Comment by ebuchman** [comment]
Right ok thanks for the details. Fixed on develop.

**Comment by odeke-em** [comment]
Awesome, thanks for the prompt fixes!
