### ISSUE TITLE
Flag `--key` for `init` subcommand is ignored in docker container

### ISSUE THREAD

**Issue by svkirillov** [tendermint/tendermint#8162]
**Tendermint version**: [master](https://github.com/tendermint/tendermint/tree/485c96b0d386d5461d397fef76ae75df0d56c885), [v0.35.2](https://github.com/tendermint/tendermint/tree/v0.35.2) - docker images

**What happened**: `tendermint init validator --key secp256k1` in docker container generates an ed25519 private validator key.

**What you expected to happen**: `tendermint init validator --key secp256k1` in docker container should generate a secp256k1 private validator key.

**Have you tried the latest version**: yes

**How to reproduce it**:
1. Build docker image from local repository or pull it from docker hub:

```sh
make build-docker # or: docker pull tendermint/tendermint:latest
```

2. Make sure that `/tmp/config` and `/tmp/data` doesn't exists.

```sh
rm -rf /tmp/config /tmp/data
```

3. Run tendermint docker container with `init validator --key secp256k1` subcommand:

```sh
docker run --rm -v /tmp:/tendermint:Z tendermint/tendermint init validator --key=secp256k1
```

4. Make sure that `/tmp/config/priv_validator_key.json` contains ed25519 private validator key instead of the secp256k1 key.

**Comment by williambanfield** [comment]
It's definitely true that running `init` with the `docker-entrypoint.sh` script does result in using the `ed25519` key. The `docker-entrypoint.sh` currently provides some reasonable defaults in the `config.toml` that are not part of the standard `config.toml` that is created when running ` tendermint init validator`. That entrypoint serves as a baseline for running a basic version of Tendermint. If you need specific parameters configured for your usecase, I think importing the Tendermint image and overriding the parameters as needed in a separate `entrypoint.sh` would be a good option. Is there anything that would make doing so a major hindrance to you?

**Comment by svkirillov** [comment]
For me, as a regular user, this behavior requires a little research to understand why `init --key=secp256k1` generates ed25519 the private key of the validator. Of course, I can set entrypoint directly to `/usr/bin/tendermint`, but wouldn't it be better if the script respects the specified options on the first `init` call?

**Comment by svkirillov** [comment]
This behavior is very similar to the problem that I fixed in the recent past: #7782 But if in that case there was an error in the tendermint source code, now the problem is in `docker-entrypoint.sh`. This issue only occurs if the config folder is missing. Otherwise, everything works as it should.

**Comment by williambanfield** [comment]
>  but wouldn't it be better if the script respects the specified options on the first init call?

This `entrypoint` is intended to provide a basic and easy to use initial version of Tendermint that gets up and running without really any fiddling. I can definitely see why some users will need more specific uses and different configurations, but this basic entrypoint is not really for them. I'd recommend importing the `Dockerfile` into your project or modifying a copy for your specific needs but I'm not inclined to include more nuanced and configurable behavior into this basic file.

**Comment by williambanfield** [comment]
I see that we document running the `init` command, with a mapped volume which I find a bit odd:
https://github.com/tendermint/tendermint/blob/64e7b5efea147a99df3d8462514e3c0087f03ae7/DOCKER/README.md#start-one-instance-of-the-tendermint-core-with-the-kvstore-app

That seems to lose a lot of the value of running a container: getting an overlay filesystem that lasts for the lifecycle of the container. Depending on the OS docker also creates these with _root_ so you often can't manage them manually that easily.

**Comment by creachadair** [comment]
> I see that we document running the `init` command from docker with a mapped volume which I find a bit odd: https://github.com/tendermint/tendermint/blob/64e7b5efea147a99df3d8462514e3c0087f03ae7/DOCKER/README.md#start-one-instance-of-the-tendermint-core-with-the-kvstore-app
> 
> That seems to lose a lot of the value of running a container: getting an overlay filesystem that lasts for the lifecycle of the container. Depending on the OS docker also creates these with _root_ so you often can't manage them manually that easily.

Mapping a volume seems right to me: The config directory contains, among other things, keys and blockchain data. If you don't map those to a volume, they have to be part of the image itself. As a rule of thumb you don't want to keep keys in images.

Docker does automatically capture changes to the running container from the base image in a volume, but I don't think that is a great operational choice. Such volumes have to be explicitly captured to persist beyond the cache.

**Comment by svkirillov** [comment]
Well, if there is no any plans to change the behavior of docker-entrypoint.sh, I think this issue and corresponding PR can be closed.
