### ISSUE TITLE
 Compile with CLevelDB support  fail

### ISSUE THREAD

**Issue by msak222** [tendermint/tendermint#8190]
I followed the tutorial to install levelDB first,
then run CGO_LDFLAGS="-lsnappy" make install TENDERMINT_BUILD_OPTIONS=cleveldb, 
then prompt me  package cleveldb is not in GOROOT (/usr/local/go/src/cleveldb)
     I have two questions about this operation;
    1. How are the two names leveldb and cleveldb related?
    2. How did cleveldb go to the $GOROOT/src directory

![middle_img_v2_07db93ec-3187-4820-9f32-f39613c5480g](https://user-images.githubusercontent.com/19371846/159878840-fd143fdb-1046-4f72-8240-d579c4b20613.png)

**basis of operation**:
           link: [https://docs.tendermint.com/master/introduction/install.html#compile-with-cleveldb-support](url)
![image](https://user-images.githubusercontent.com/19371846/159878989-3d0902b3-f3d1-4571-96fe-bcf3cb47d7fe.png)

**Comment by creachadair** [comment]
Hi, @msak222. To your question (1):

The tag `cleveldb` in the Makefile indicates the C implementation of LevelDB (which uses CGo), as opposed to the native Go implementation (tagged `goleveldb` in the Makefile).

For your question (2), I'm not sure what's going on. I tried the instructions linked above on my Mac, and they worked with two minor alterations (I have `leveldb` installed via Homebrew):

```
brew install leveldb
brew install snappy

CGO_CFLAGS="-I/opt/homebrew/include" CGO_LDFLAGS="-L/opt/homebrew/lib -lsnappy" make build TENDERMINT_BUILD_OPTIONS=cleveldb
```

The changes here are the addition of the `-I` and `-L` options to target the Homebrew paths.

I also tried this in Alpine:

```
apk add build-base gcc git go leveldb-dev snappy-dev
CGO_LDFLAGS="-lsnappy" make build TENDERMINT_BUILD_OPTIONS=cleveldb
```

and it seems to work fine.

Can you say a bit more about what commands you ran to get the error message you show here?

**Comment by msak222** [comment]
> 
I just followed the instructions of the connection step by step on the centos system, but when I installed levelDB and then executed the install command, I was prompted with this error
![image](https://user-images.githubusercontent.com/19371846/160040253-f6086ec4-900a-4ea2-9392-4e3367d9d800.png)

**Comment by creachadair** [comment]
> I just followed the instructions of the connection step by step on the centos 7 system, but when I installed levelDB and then executed the install command, I was prompted with this error

What commands did you run to install leveldb on CentOS? I don't know from CentOS, but following what I found searching, I tried running `yum update; yum install leveldb-devel`, but that package appears not to be in the registry. I'd like to try to reproduce what you're seeing locally.

**Comment by msak222** [comment]
> yum



> > 我只是在centos 7系统上按照说明一步一步连接的，但是当我安装完levelDB，然后执行install命令的时候，提示这个错误
> 
> 你在 CentOS 上运行了哪些命令来安装 leveldb？我从 CentOS 不知道，但按照我发现的搜索，我尝试运行`yum update; yum install leveldb-devel`，但该软件包似乎不在注册表中。我想尝试重现您在本地看到的内容。



> > I just followed the instructions of the connection step by step on the centos 7 system, but when I installed levelDB and then executed the install command, I was prompted with this error
> 
> What commands did you run to install leveldb on CentOS? I don't know from CentOS, but following what I found searching, I tried running `yum update; yum install leveldb-devel`, but that package appears not to be in the registry. I'd like to try to reproduce what you're seeing locally.

wget https://github.com/google/leveldb/archive/v1.20.tar.gz

tar -zxvf v1.20.tar.gz
cd leveldb-1.20
make -j4

cp -r include/leveldb /usr/include/
cp out-shared/libleveldb.so.1.20 /usr/lib/
ln -s /usr/lib/libleveldb.so.1.20 /usr/lib/libleveldb.so.1
ln -s /usr/lib/libleveldb.so.1.20 /usr/lib/libleveldb.so

ldconfig

**Comment by creachadair** [comment]
Ok, I can see a couple things that may help move you along here:

1. Your system appears to be missing some tools that the build requires, notably `buf`, `clang-format`, and the `protoc-gen-gogofaster` plugin. That's not the only error, but you'll definitely need those tools to get a build working.
2. The fact that you're getting these messages makes me suspect you are trying to build at head of `master` rather than at a release tag. I suggest checking out at, say, `v0.35.2`, which is the latest release as I write this.

I tried to get a working repro of your setup in a CentOS 7 container, but the versions of toolchain packages available for that version are quite old. You may need to update some of the other tools as well, if you haven't already.

**Comment by creachadair** [comment]
Another thing to check here is which version of Go you have installed: If your system has a sufficiently old Go version, it may not be capable of building this module. Tendermint currently requires Go 1.17, but if the Go version on your system is old enough, it might not know how to read the toolchain version to give a proper diagonstic.
