### ISSUE TITLE
Data access mode when spin up a node with a problematic data set

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#8213]
## Summary

Provides a way to load the block and state data without spin-up the consensus when starting a node with a problem data set.

## Problem Definition

The TM core will execute the handshake when we start a node. If the data set has an issue (like app hash mismatch) we would like to go into more detail. The node will panic and shut down immediately. 

It would be great if the TM core can spin up a node without the handshake but load the block and state. Then we can use the Tendermint RPC to check the status of the problem data (especially the data set is not easy to reproduce, meaning an indeterministic bug on the application side).

## Proposal

start a node with a dedicated mode for probing the state and the block data, skip handshake, disable the consensus reactor maybe the peer connection, but keep the rpc server alive.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
If you are using Tendermint ≥ v0.35, I think `tendermint inspect` should give you the ability to do this. It does more or less as you suggest, though it does not implement the entire RPC service (since it can't, without consensus).

**Comment by JayT106** [comment]
Ah, thanks, the Cosmos SDK v0.44 doesn't support `inspect`yet.

**Comment by creachadair** [comment]
> Ah, thanks, the Cosmos SDK v0.44 doesn't support `inspect` yet.

This is not a feature we are likely to add to any earlier version of Tendermint. Fortunately, it looks like v0.46 is now in beta, so hopefully access to v0.35.x will not be too far off.

**Comment by JayT106** [comment]
Hmm, just checked the main branch of the SDK, cannot find the `inspect` cmd, but also under the `Tendermint` subcommand.

**Comment by creachadair** [comment]
> Hmm, just checked the main branch of the SDK, cannot find the `inspect` cmd, but also under the `Tendermint` subcommand.

The `tendermint` CLI does have it, but possibly the SDK wrappers would need to add support explicitly?

**Comment by JayT106** [comment]
> > Hmm, just checked the main branch of the SDK, cannot find the `inspect` cmd, but also under the `Tendermint` subcommand.
> 
> The `tendermint` CLI does have it, but possibly the SDK wrappers would need to add support explicitly?

I think so. I am not familiar with the latest spec in the SDK, should I submit an issue to it?

**Comment by creachadair** [comment]
> > The `tendermint` CLI does have it, but possibly the SDK wrappers would need to add support explicitly?
> 
> I think so. I am not familiar with the latest spec in the SDK, should I submit an issue to it?

That seems worthwhile. Given that the next release is in beta now, the timing seems good.
