### ISSUE TITLE
spec: define syncing protocols

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#8219]
## Summary

Our current spec has no mention for the syncing protocols that Tendermint uses: block sync and state sync. It would be good to write one up these so people can use it to quickly understand how each of them work. 

- [ ] Block sync specification (@jmalicevic)
- [ ] State sync specification (@cmwaters)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by sergio-mena** [comment]
When addressing state sync, think of migrating the section in ABCI++ spec. See [this comment](https://github.com/tendermint/tendermint/pull/8506/files#r871114473)
