### ISSUE TITLE
consensus: add hash of polka to precommit

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#823]
In order to do accountability properly we need precommits to commit to their polka.

breaking change

**Comment by xla** [comment]
@jaekwon Should this be considered as improvement for conensus?

**Comment by melekes** [comment]
one downside: +32 bytes to each `CommitSig`

**Comment by tessr** [comment]
Per the [Fork Accountability spec](https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/accountability.md) (and conversation with @milosevic and @ebuchman), this is no longer needed.
