### ISSUE TITLE
Implement _same-block execution_ mode

### ISSUE THREAD

**Issue by sergio-mena** [tendermint/tendermint#8233]
## Summary

ABCI++, as of v0.36 does not support _same-block execution_ mode.

## Problem Definition

The ABCI++ spec living in `master` contains the full specification of this mode, also with the additional fields needed in `ResponsePrepareProposal`.

## Proposal

We need to:
* add (back) the extra fields in `ResponsePrepareProposal`'s protobuf
* Add a parameter (a boolean)`same-block-mode` in the Genesis block, or `config.toml`
* implement the dual logic: depending on the boolean, we
  * read the relevant values from `ResponseFinalizeBlock` or from `ResponsePrepareProposal`
  * set those values (a) in the block after the one just decided, or (n) in the block about to be proposed
  * Adapt light client, block sync, and any other mechanism that navigates the blockchain data

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Linking https://github.com/tendermint/tendermint/issues/7898 to this
