### ISSUE TITLE
mempool: tx gossip cause CheckTx error during the statesync stage

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#8243]
**Tendermint version**
v0.34.14

Cosmos SDK v0.45.2

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
cronos v0.6.5
https://github.com/crypto-org-chain/cronos/releases/tag/v0.6.5

**Environment**:
linux/amd64

**What happened**:
Tendermint will gossip transactions with connecting peers during the statesync stage. it causes the ante handler panic when calling `CheckTx`. The ante handler will recover itself so I think the panic in the app side should be fine.

**What you expected to happen**:
Tendermint should ignore the tx gossip processing during the statesync stage.

**Have you tried the latest version**: 
no

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
see https://github.com/crypto-org-chain/cronos/issues/317

**Comment by cmwaters** [comment]
> Tendermint should ignore the tx gossip processing during the statesync stage.

Yes we don't do this and we should but I think the real culprit is that the node should start up in phases (See https://github.com/tendermint/tendermint/issues/4644)
