### ISSUE TITLE
mempool: rechecktx should be an application controlled variable

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#8244]
## Summary

Currently, the ability to run check tx on all remaining transactions in a nodes mempool after a block has been committed is a locally defined variable (in the config.toml file). This is commonly used as a means of garbage collection via the application. It seems to me more intuitive if rechecktx were a global-application defined variable i.e. either returned in `ResponseFinalizeBlock` or set by the `ConsensusParams`.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
This seems like a very reasonable thing to me. Summarizing our separate discussion: this could be a good candidate for a consensus parameter. As you mentioned, it shouldn't change often, and we're already adding a bunch of consensus params during the ABCI++ rollout anyway.
