### ISSUE TITLE
Add LastBlockTime to abci_info RPC endpoint

### ISSUE THREAD

**Issue by ancazamfir** [tendermint/tendermint#8248]
## Summary
The IBC relayer needs to know the time of the latest header known by the application. This may not be the same as the latest chain header.

## Problem Definition
To handle this in the relayer the following is required:
- get the application info (use RPC `abci_info`)
- get the chain status (use RPC `status`)
- if at same height use the `status.sync_info.latest_block_time`
- otherwise get the header at `abci_status.last_block_height` (use RPC `commit`)

(see [wip here](https://github.com/informalsystems/ibc-rs/blob/0294c6307886d0701a6d0cbb3c18f226d07b0ffb/relayer/src/chain/cosmos.rs#L1235))

This operation happens on every IBC send packet event and requires up to 3 RPC calls.

## Proposal
Add `LastBlockTime` to `abci_info` RPC endpoint.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Would it be possible to make application recorded height and tendermint recorded height atomic so application height and tendermint height never differed (obviously we need to decide whether tendermint height comes from the block store or state store)

**Comment by tychoish** [comment]
I'm also curious as to the situation where the application's last chain header is not the same as the time that would be reported by tendermint's status. I'm also interested in understanding a bit more about what having this piece of data helps you confirm or avoids in the current design of the interaction between the relayer and the consensus engine.
