### ISSUE TITLE
nil bit-array in ApplyVoteSetBitsMessage

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#825]
https://github.com/tendermint/tendermint/pull/824

**Comment by melekes** [comment]
Did we solve this?

**Comment by ebuchman** [comment]
We solved it, but it's still not apparent why the issue arose.

**Comment by ebuchman** [comment]
This is fixed, but leaving open as a reminder to look more closely at nil pointers in the reactors

**Comment by xla** [comment]
Closed until surfacing again.
