### ISSUE TITLE
Unconfirmed transactions not being gossiped to persistent peers

### ISSUE THREAD

**Issue by theblockbois** [tendermint/tendermint#8277]
Hello,

I have approximately 5 nodes distributed around the globe running tendermint. Each node was initialized with the other 4 nodes specified as persistent peers, and I can verify that the peers are all connected to each other via the net_info RPC query. 

On each node, I am running the same code where I am monitoring the local mempool via the unconfirmed_txs RPC query to find a transaction from a specific account. However, I notice that I can detect the target transaction on only 1 of the peers - the other peers never detect it in their local mempools, even after the transaction has been mined.

Given that the nodes are all connected to each other as persistent peers, I expected that if one node receives a transaction in its mempool, it would then broadcast the transaction to the connected persistent peers via TCP gossip, and thus all of the other nodes would eventually detect the transaction in their mempools. This doesn't seem to happen however - for some reason, only 1 particular node is able to detect the transaction I'm looking for, and it isn't being gossiped to the others.

Does anyone know why this might be and how I might fix it?

**Comment by greg-szabo** [comment]
Is it possible that the transaction gets into a block before it has the chance to be gossiped?

How long is the turnaround time for transactions in your network?

Try to create a setup where the unconfirmed transaction has a hard time to get into a block: for example set a minimum fee on the validators, except for one that stays zero fee and enter a zero fee transaction from a full node. If the transaction is to be entered into a block it has to reach the validator with the zero fee transactions through mempool gossip.

This way you have the chance to measure how long it takes to gossip a transaction without new blocks getting in the way.

**Comment by theblockbois** [comment]
@greg-szabo Good question, this is on the Terra blockchain where blocks are confirmed every ~7 seconds. I would assume that's generally more than enough time for the transaction to be gossiped before confirmation. I'll run your experiment to verify.

What's weird is that I was running this exact same code to monitor transactions from a different account and had no problem detecting it on every node - this new account however is somehow harder for the nodes to discover. Could the location of peer that originates the transaction also be part of this?

**Comment by creachadair** [comment]
One important question here is whether it matters that these transactions do not show up in the mempools of other nodes. If transactions are successfully added to the chain, it should not matter whether an observer finds them in the mempool or not.

On a small network with good connectivity, I could believe that transactions are propagated, delivered, committed, and removed from the mempool before a casual observer notices. That doesn't seem like a problem in itself. Likewise, if the node where the tx was submitted rejects it in CheckTx, that seems OK.

The case I'd worry about is if txn are neither rejected nor committed nor gossiped. It sounds like the network is still making progress in this case, is that right?

**Comment by theblockbois** [comment]
I see what you mean. To an extent it is pure luck (or lack thereof) that the transaction would enter and exit the mempool before the client is able to query for it. I would expect this to be the exception rather than the rule for a sufficiently decentralized network like Terra. Based on what I can observe, however, this seems to be the rule for a subset of the nodes.

Today I deployed a new node in the same location as one of the 4 nodes consistently missing the target transaction (literally across the world from the node that can spot the transaction!), and surprisingly the fresh node was able to consistently spot the target transaction in its mempool. The original nodes have been running for several weeks up to this point, so I wonder if maybe the node network connectivity has degraded or gone stale over time. I restarted the original nodes and redialed their peers several times but it didn't help - only starting from a completely clean slate with a fresh node did the transaction begin to be detected...

**Comment by aofengli** [comment]
> I see what you mean. To an extent it is pure luck (or lack thereof) that the transaction would enter and exit the mempool before the client is able to query for it. I would expect this to be the exception rather than the rule for a sufficiently decentralized network like Terra. Based on what I can observe, however, this seems to be the rule for a subset of the nodes.
> 
> Today I deployed a new node in the same location as one of the 4 nodes consistently missing the target transaction (literally across the world from the node that can spot the transaction!), and surprisingly the fresh node was able to consistently spot the target transaction in its mempool. The original nodes have been running for several weeks up to this point, so I wonder if maybe the node network connectivity has degraded or gone stale over time. I restarted the original nodes and redialed their peers several times but it didn't help - only starting from a completely clean slate with a fresh node did the transaction begin to be detected...

We also encountered a similar problem, do you have any conclusions here?@theblockbois
