### ISSUE TITLE
`ERROR: unknown flag: --proxy-app` when following documentation

### ISSUE THREAD

**Issue by am-work** [tendermint/tendermint#8311]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

```
$ ./build/tendermint version
v0.34.19
$ git rev-parse --verify HEAD
2f231ceb952a2426cf3c0abaf0b455aadd11e5b2
```

**ABCI app** (name for built-in, URL for self-written if it's publicly available): N/A

**Environment**:
- **OS** (e.g. from /etc/os-release):  RHEL8
- **Install tools**: Go 1.18
- **Others**:

**What happened**:

I'm following the instructions to install from source here: https://docs.tendermint.com/master/introduction/install.html

I was able to compile the executable using `make build`, but when I follow the commands in the "Run" section, I get:

```
$ tendermint init validator
$ ./build/tendermint init validator
I[2022-04-11|13:02:09.589] Found private validator                      module=main keyFile=/home/am/.tendermint/config/priv_validator_key.json stateFile=/home/am/.tendermint/data/priv_validator_state.json
I[2022-04-11|13:02:09.589] Found node key                               module=main path=/home/am/.tendermint/config/node_key.json
I[2022-04-11|13:02:09.589] Found genesis file                           module=main path=/home/am/.tendermint/config/genesis.json

$ ./build/tendermint start --proxy-app=kvstore
ERROR: unknown flag: --proxy-app
```

**What you expected to happen**:

I expected ` ./build/tendermint start --proxy-app=kvstore` to start a one-node blockchain with a simple in-process application (instead of failing).

I suspect it's the documentation that's out-of-date; would be nice to update it for total Tendermint beginners like me.

**Have you tried the latest version**: yes; tried master, same thing.

**How to reproduce it** (as minimally and precisely as possible): See commands above.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**: See commands above.

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by creachadair** [comment]
For version v0.34, please try https://docs.tendermint.com/v0.34/introduction/install.html instead of `master`.
