### ISSUE TITLE
In some conditions transaction passing checkTx but never added to mempool

### ISSUE THREAD

**Issue by ze97286** [tendermint/tendermint#8320]
Tendermint version 0.34.15 (though seems to also be relevant to 0.34.x and 0.35.x)

**ABCI app** 
Socket client. 

**What happened**:
When calling BroadcastTx_Async, under some conditions the transactions is not added to the mempool and is never included in a block. 

**What you expected to happen**:
If a transaction is passing checkTx, it should be added to the mempool (unless the mempool is full or there is some other error). 

**Have you tried the latest version**: yes/no
N/A

**More information**
The problem is that CListMempool::CheckTx does the following:

```
reqRes := mem.proxyAppConn.CheckTxAsync(abci.RequestCheckTx{Tx: tx})
reqRes.SetCallback(mem.reqResCb(tx, txInfo.SenderID, txInfo.SenderP2PID, cb))
```

i.e. it first calls CheckTxAsync then sets the callback.
Client::SetCallback has this logic for handling the situation where the result for checkTxAsync has already returned when called for setting the callback

```
if r.done {
	r.mtx.Unlock()
	cb(r.Response)
	return
}

```

However, socketclient (unlike the other clients grpc and local), never calls setDone(), so would only work if checkTxAsync completed after the callback has been set. So a transaction that has completed checkTxAsync before setting the callback will never call the callback (if socket client is used) and hence never be added to the mempool and be lost.
From a quick look this issue seems to still exist on all 0.34.x x>=15 and possibly on the 0.35.x.
I fixed it locally in my branch by adding a call to reqres.SetDone() before the call to reqres.Done() in socket_client.go.

**Comment by creachadair** [comment]
Thanks for the report! The fixes for this issue from #8331 will be included in the next point release of v0.34, and are also included in v0.35.4.
