### ISSUE TITLE
Identify potential non-nil nil-valued interface values

### ISSUE THREAD

**Issue by firelizzard18** [tendermint/tendermint#8322]
Given

- `type Foo struct { ... }`; which implements
- `type Bar interface{ ... }`
- `func NewFoo() (*Foo, error) { ... }`
- `func NewBar() (Bar, error) { return NewFoo() }`

If `NewFoo` returns nil for the first return value, `NewBar` will create a non-nil interface value of type `*Foo` containing a nil value. Specifically, `fmt.Printf("(%[1]T, %[1]v)", v)` will print `(*pkg.Foo, <nil>)` and `v != nil` will pass.

If an error is returned along with this value, it should not be an issue because callers should not use the interface value. However if `NewFoo` returns `nil, nil` then `NewBar` will return `(*pkg.Foo, <nil>), nil` and callers will see a non-nil value and may attempt to use it, which will likely lead to a nil pointer exception.

Therefore, due to the easy potential for nil-pointer-exception inducing bugs, functions like `NewBar` should be detected with `go vet`/`staticcheck`/etc and refactored to not allow the situation to occur.

`internal/eventbus.EventBus.SubscribeWithArgs` is a concrete example (in Tendermint) of a function like `NewBar`. The function it called used to have a case that returned `nil, nil`, which lead to unexpected nil pointer exceptions. I created a test [here](https://github.com/AccumulateNetwork/tendermint/blob/5aeb3f2cf63505dfee87ddad9aa19bf59aec8222/internal/eventbus/event_bus_wb_test.go) that demonstrates the non-nil nil-valued interface value. When `nil` is returned for the first return value, `SubscribeWithArgs` effectively does the following:

```go
var sub eventbus.Subscription = (*pubsub.Subscription)(nil)
```

This creates a non-nil `eventbus.Subscription` interface value represented by the tuple `(typeof(*pubsub.Subscription), nil)`. The following code will panic:

```go
var sub eventbus.Subscription = (*pubsub.Subscription)(nil)
if sub != nil {
	sub.ID()
}
```

This is because the interface value is not nil, so `sub.ID()` calls `(*pubsub.Subscription).ID` with a nil pointer, which panics. In practice this issue arises when `pubsub.Subscription.SubscribeWithArgs` returns `nil, err`.

**Comment by creachadair** [comment]
Code that calls `SubscribeWithArgs` (or any other function that can return an error) should check that `err == nil` before attempting to use the other values.

Conventionally in Go, one cannot assume anything about the non-error values of a function when there is an error, unless the function documents otherwise.

**Comment by firelizzard18** [comment]
This is an excerpt from `libs/pubsub.Server.subscribe` in `v0.35.0-rc1`

```go
select {
case s.cmds <- cmd{op: sub, clientID: clientID, query: query, subscription: subscription}:
	// ...
	return subscription, nil
case <-ctx.Done():
	return nil, ctx.Err()
case <-s.Quit():
	return nil, nil
}
```

In the last case, `Server.Subscribe(...) (*Subscription, error)` returns `nil, nil`. Then in `types.EventBus.Subscribe` that is converted into a non-nil but nil-containing interface value and a nil error. That is where the real bug was. The caller was left with a nil error and a garbage value that passed `v != nil` but would cause a panic if any of its methods were called.

If `Subscribe` returned an error, I respect that. In this case it did _not_ return an error. Even though the `return nil, nil` case has been removed, IMO this should still be changed.

**Comment by creachadair** [comment]
> This is an excerpt from `libs/pubsub.Server.subscribe` in `v0.35.0-rc1`

The opening comment of this issue is reporting a problem with the `master` branch. 
 
> In the last case, `Server.Subscribe(...) (*Subscription, error)` returns `nil, nil`. 

That case has since been fixed on the v0.35 branch since #7310. As a general note, if you're looking for the current state of one of the release branches, it's better to look at the "x" backport branch, e.g., `v0.35.x`, rather than older tags.

**Comment by firelizzard18** [comment]
I closed the MR. Maybe this issue should be rewritten as "Identify places where non-nil nil-valued interface values may be returned and replace them with concrete types or explicitly return nil"?

**Comment by creachadair** [comment]
> I closed the MR. Maybe this issue should be rewritten as "Identify places where non-nil nil-valued interface values may be returned and replace them with concrete types or explicitly return nil"?

That's probably a good idea.

> IIRC `go vet` is pluggable. Someone might have already written a rule to detect this.

The `staticcheck` tool has the plumbing to write a check like this, but as far as I was able to tell it doesn't currently have one for this case. (I looked into that previously for exactly the reasons you mentioned above).
