### ISSUE TITLE
ResetStateCmd and ResetAllCmd not using --home flag default value

### ISSUE THREAD

**Issue by V-Staykov** [tendermint/tendermint#8327]
**Tendermint version**: v0.34.19

**Environment**:
golang:buster docker image

**What happened**:
When running unsafe-reset-all cmd without setting --home flag, the default value of the flag is not used. When i set some value for --home, it gets used and tendermint tries to delete the given directory. This works similarly for reset-state as well.

Not sure what happens, but I did debug with `fmt.Println(cmd.Flags().GetString(tmcli.HomeFlag))` in `resetAllCmd` and it does have the value I expect set. `resetAll` function uses `config.DBDir` though and I haven't gotten much into how this works.

P.S. Also the text for the `--home` flag default alue show the correct default value.
P.S.2 This was working fine with tendermint v0.34.14. Probably because cosmos sdk implemented this command on root level and was setting the config like this:
```
serverCtx := GetServerContextFromCmd(cmd)
cfg := serverCtx.Config

```
**What you expected to happen**:
I expect tendermint commands to use the default values of the flags like all other commands

**Have you tried the latest version**: yes

**How to reproduce it**:
Compile any cosmos-sdk v0.45.0 app up with set `DefaultNodeHome` in app.go to something custom. Then try `noded tendermint unsafe-reset-all` and check if it tries to delete the correct dir.

**Logs**:
```
cudos-noded tendermint unsafe-reset-all -h
...
Global Flags:
      --home string         directory for config and data (default "/usr/cudos/cudos-data")
...
```
```
cudos-noded tendermint unsafe-reset-all 
I[2022-04-13|12:46:04.200] Removed all blockchain history               dir=/home/<user>/data
I[2022-04-13|12:46:04.208] Reset private validator file to genesis state keyFile=/home/<user>/config/priv_validator_key.json stateFile=/home/<user>/data/priv_validator_state.json
```

**Comment by williambanfield** [comment]
Thanks for the report @V-Staykov.
Running with Tendermint v0.34.19, it appears that this is working as expected when not setting the `--home` flag in the Tendermint codebase. My guess is that the interaction is related to this change:
https://github.com/osmosis-labs/cosmos-sdk/pull/175/files#diff-3f2f34f0293c51450e9bc26d1cb0ebd4ee306ac529a0999c77acb657082c7c89L124-L131

```
[william@sidewinder] tendermint[tags/v0.34.19]:. ◆ ./build/tendermint unsafe-reset-all
I[2022-04-13|16:08:42.841] Removed existing address book                module=main file=/home/william/.tendermint/config/addrbook.json
I[2022-04-13|16:08:42.842] Removed all blockchain history               module=main dir=/home/william/.tendermint/data
I[2022-04-13|16:08:42.848] Reset private validator file to genesis state module=main keyFile=/home/william/.tendermint/config/priv_validator_key.json stateFile=/home/william/.tendermint/data/priv_validator_state.json
```

**Comment by RaulBernal** [comment]
Same for Tendermint v.0.34.20

```
bcnad tendermint unsafe-reset-all
I[2022-08-01|14:02:37.300] Removed all blockchain history               dir=/Users/raul/data
I[2022-08-01|14:02:37.306] Reset private validator file to genesis state keyFile=/Users/raul/config/priv_validator_key.json stateFile=/Users/raul/data/priv_validator_state.json
```
Should be:
`dir=/Users/raul/.bcna/data`

**Comment by cmwaters** [comment]
We do have a fix for that here: https://github.com/tendermint/tendermint/pull/9113
