### ISSUE TITLE
Restart the node, some transaction data will be lost

### ISSUE THREAD

**Issue by vae520283995** [tendermint/tendermint#8355]
Same problem in both terra network and cosmos network
https://github.com/terra-money/core/issues/725

**Comment by creachadair** [comment]
Can you give us some more context about what you're seeing? The linked issue doesn't give much detail.

Is the transaction you're trying to query one that has already been committed into a block, or is it one that was pending in the mempool of the running node?  Also, it would be helpful to know what version of Tendermint is involved. Also, since the RPC query shown in that issue appears to be targeting the SDK rather than Tendermint directly, it would be good to know what version of the SDK is in use (if that's correct).

**Comment by vae520283995** [comment]
> Can you give us some more context about what you're seeing? The linked issue doesn't give much detail.
> 
> Is the transaction you're trying to query one that has already been committed into a block, or is it one that was pending in the mempool of the running node? Also, it would be helpful to know what version of Tendermint is involved. Also, since the RPC query shown in that issue appears to be targeting the SDK rather than Tendermint directly, it would be good to know what version of the SDK is in use (if that's correct).

Thank you for your answer, because of security, I can't tell the domain name of my node directly, I gave a request link for a public node
https://lcd.terra.dev/cosmos/tx/v1beta1/txs/623CEC5F918EE872B62CC240FBAF58ECCAEDDCDAF3D0FDD7938FA0140BF21971

The transaction is already in the block, cosmos_sdk_version: "v0.44.5"

**Comment by creachadair** [comment]
Unfortunately I think we're left with only guesswork given the evidence so far. It looks like the transaction is accepted by the network, which suggests maybe this node has some kind of synchronization issue. 

What role is the node that was restarted? Is it a full node, or a validator? Is the node set up to prune blocks at all?

**Comment by vae520283995** [comment]
> What role is the node that was restarted? Is it a full node, or a validator? Is the node set up to prune blocks at all?

It's full node
app.toml
set pruning = "nothing"

**Comment by creachadair** [comment]
A few other things to look for:

- Before the node was restarted, was it able to return this transaction?
- Can the node successfully find other committed transactions before and/or after this one?
- Does this node run an indexer?
- Is there anything in the node logs around the time of the failed query, that might give us more clues?

**Comment by vae520283995** [comment]
> A few other things to look for:
> 
> * Before the node was restarted, was it able to return this transaction?

Because I need to scan all blocks and transactions, if I don't restart the node, everything goes well, but if I restart it will be blocked because a transaction cannot be obtained

> * Can the node successfully find other committed transactions before and/or after this one?

Just now I double-checked, if I restart, I can get the block, but I can't get the transaction details in the block
https://lcd.terra.dev/cosmos/base/tendermint/v1beta1/blocks/7244890

> * Does this node run an indexer?

What is an indexer, there should be none

> * Is there anything in the node logs around the time of the failed query, that might give us more clues?

I'm sorry, the log only prints the normal info information, and did not find any abnormality

**Comment by creachadair** [comment]
> What is an indexer, there should be none

Ordinarily the indexer is what keeps track of the mapping between query terms (e.g., hash, height, application metadata) and the transactions that match them.  It's possible for the application to do its own indexing, or Tendermint has one built-in (if it's enabled).

If the application did not successfully index all the transactions (e.g., because the node was stopped), that could explain why those queries are not turning up results for the specific transaction, even though the block is apparently present.

**Comment by vae520283995** [comment]
> If the application did not successfully index all the transactions (e.g., because the node was stopped), that could explain why those queries are not turning up results for the specific transaction, even though the block is apparently present.

How to enable the indexer?

**Comment by creachadair** [comment]
> > If the application did not successfully index all the transactions (e.g., because the node was stopped), that could explain why those queries are not turning up results for the specific transaction, even though the block is apparently present.
> 
> How to enable the indexer?

It's a good question. Based on the fact that you were able to look up transactions from _other_ blocks, I am guessing that either your application has its own index, or that it's using the Tendermint indexer. As far as the Tendermint indexer, it's configured by the `[tx-index]` section of the `config.toml`.

But if, as you said above, that isn't enabled, then there must be some app-specific setting, and I don't know what that would be.

**Comment by vae520283995** [comment]
```
#######################################################
###   Transaction Indexer Configuration Options     ###
#######################################################
[tx_index]

# What indexer to use for transactions
#
# The application will set which txs to index. In some cases a node operator will be able
# to decide which txs to index based on configuration set in the application.
#
# Options:
#   1) "null"
#   2) "kv" (default) - the simplest possible indexer, backed by key-value storage (defaults to levelDB; see DBBackend).
# 		- When "kv" is chosen "tx.height" and "tx.hash" will always be indexed.
indexer = "kv"
```
It is enabled by default, I think this should be caused by other reasons

**Comment by creachadair** [comment]
From the symptoms it looks like the target block may not have been fully indexed. I think this is possible in v0.34 if the node shuts down during delivery of a block. In principle it should re-execute the block after restart, but it's conceivable that didn't happen for some reason.

If that hypothesis is correct, it may be a little tricky to fix. TM v0.35 has a `reindex-event` command that could be used to rerun the block in question to re-generate the events, but v0.34 does not. You might try spinning up a fresh (separate) copy of the node with an empty store, and see if it correctly indexes the block during resynchronization.

**Comment by vae520283995** [comment]
> If that hypothesis is correct, it may be a little tricky to fix. TM v0.35 has a `reindex-event` command that could be used to rerun the block in question to re-generate the events, but v0.34 does not. You might try spinning up a fresh (separate) copy of the node with an empty store, and see if it correctly indexes the block during resynchronization.

Thanks a lot for your help, I hope this will be fixed in some future release

**Comment by vae520283995** [comment]
> If a newly-synchronized node is able to find the transaction that was missing on the original, that would support an indexing issue. If not, though (i.e., if the same thing recurs), it could also be some kind of application bug.

I can't re-run a new node to observe due to time and money, thanks again for your help
