### ISSUE TITLE
feat: Decouple the p2p system from mempool and node

### ISSUE THREAD

**Issue by l0k18** [tendermint/tendermint#8367]
## Summary

Currently the p2p transaction and block propagation system is very tightly coupled to the mempool and node. I am proposing to loosen the coupling so that potentially alternative methods of distributing transactions and blocks could be easily swapped in.

## Problem Definition

As [ADR 073](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-073-libp2p.md) elaborates, the p2p subsystem is very tightly coupled with the node and mempool and other `internal` elements of the tendermint architecture. In part this issue resolves some of `ADR 073` but this is not the purpose, rather, it is to open the path to experimenting with creating substantially different alternatives, *as well as* making one of the key steps towards changing to libp2p in this ADR.

## Proposal

As a starting point, the existing p2p subsystem is wrapped in an exported package to produce a basic API, the Node is then redirected to link to this, and then based on this API it becomes possible to define an interface to alternative p2p implementations.

The proposer's purpose for this is an idea to enable implementing other p2p broadcast strategies for other purposes. There is a kademlia DHT based p2p anti-partition routing protocol that was developed by dusk.network, called Kadcast, for example, which could be plugged into a tendermint node. Indeed any kind of multiplexed network adapter whether multiplexed or for testing purposes.

The proposer's main interest, however, is in creating a dynamic sharding protocol for managing sessions for realtime interactive shared applications, ideally trying to hit the 100ms latency target to provide sufficient speed for realtime (eg, FPS, RPG) games and shared document editing applications.

The pluggability can be provided either by replace directives or potentially a registry could be added to allow multiple configurable implementations to coexist or even operate simultaneously, with a multiplexer fanning the message streams to two or more parallel p2p systems, and funneling them back in.

There is also a discussion [https://github.com/tendermint/tendermint/discussions/8361](https://github.com/tendermint/tendermint/discussions/8361) and details like whether to create a source plugin registry and adding this to configuration items would be done or whether to make it a little more quick and dirty with `replace` directives, or other alternatives.

## Volunteering

I add that as proposer of the feature I would like to also do the work of implementing it. I am already working on it on this fork [https://github.com/cybriq/ergodicity](https://github.com/cybriq/ergodicity). After some time reading back and forth in the code and trying things out I am focusing on a short path to exposing the p2p system as an interface, which will be the part relevant to ADR 73, and then focusing on creating the low latency A/P consensus starting with the latency topology map.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by tychoish** [comment]
Thanks for this comment and this idea!

From a high level this is very consistent with the kind of direction that we're headed: we're definitely going to migrate to using libp2p, with work to begin on that project very soon: while the API hasn't been decided, I imagine that applications may (optionally) have access to the P2P network and be able to use that to build "backchannel" (from tendermint's perspective) protocols between nodes that would be the applications responsibility. 

Additionally, we've been discussing (at a high level), what the future of the "mempool" and rest of the node architecture will end up being, and we don't have a clear answer to that at this time. The [node architecture RFC](https://github.com/tendermint/tendermint/pull/8317) is the beginning of this conversation, but there's more to come. Having said this, I want to be clear, we definitely want to separate the projects of "figuring out what the interface and function should be" (for a component like the mempool or the peer stack) from the "making components pluggable." In our experience, it is very clear that even subtle changes to components like the mempool can have far reaching impacts in the rest of the service. I believe it's prudent to do this work as part of separate projects and potentially a bit more slowly.

In the near future we hope to have some follow up documentation for the libp2p project, and can begin to iterate from there.
