### ISSUE TITLE
block height keeps increasing without any in nodes

### ISSUE THREAD

**Issue by dunidaho75** [tendermint/tendermint#8425]
Hello,

My node is currently processing blocks, and is keeping up with the network. However, when I look at the logs, I see the following:

```
Apr 27 18:56:37 6:56PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=85 numToDial=15
Apr 27 18:56:07 6:56PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=85 numToDial=15
Apr 27 18:55:37 6:55PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=86 numToDial=14
Apr 27 18:55:07 6:55PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=86 numToDial=14
Apr 27 18:54:37 6:54PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=86 numToDial=14
Apr 27 18:54:07 6:54PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=86 numToDial=14
Apr 27 18:53:37 6:53PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=86 numToDial=14
Apr 27 18:53:07 6:53PM INF Ensure peers module=pex numDialing=0 numInPeers=0 numOutPeers=86 numToDial=14
```

numInPeers is consistently 0 throughout the logs. 

If the number of InPeers is 0, how is that my node is getting any blocks? 🤔

**Comment by dunidaho75** [comment]
> > The rest of our peers are only distinguished by being either inbound (they dialed our public address) or outbound (we dialed them).

From the documentation. 

I think my understanding for inPeers and outPeers was wrong. It seems connections are always bidirectional, and inound and outbound are just to distinguish who initiated the connection. 

Is that correct?

**Comment by creachadair** [comment]
I believe that is correct. If the network is agreeing on blocks and this isn't the only validator, it's safe to assume they're communicating.

**Comment by dunidaho75** [comment]
Thanks @creachadair !
