### ISSUE TITLE
Store custom events from modules EndBlocker

### ISSUE THREAD

**Issue by avalkov** [tendermint/tendermint#8464]
## Summary

Custom events returned from EndBlocker module call are lost.

## Problem Definition

Events fired from cosmos gravity bridge module are not stored, because they are fired from EndBlocker function.

https://github.com/Gravity-Bridge/Gravity-Bridge/blob/main/module/x/gravity/keeper/attestation.go#L152

## Proposal

Support interface in the event bus to emit custom events so later clients can query them.

https://github.com/tendermint/tendermint/blob/master/internal/state/execution.go#L554
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
Hi @avalkov. I'd like to understand better what the request is here. Is the concern about propagating custom events to subscribers, or indexing them for queries?

- You mentioned the event bus: Tendermint's event bus already supports publishing arbitrary event items during consensus (though I don't know whether the module you pointed to is forwarding these events to the bus). Subscribers should already be able to filter for these (including custom types).

- However, you also mentioned client queries. The indexer (which is what allows client queries to be answered) records only ABCI event metadata generated by the application (the type-key-value tuples captured during `BeginBlock` and `EndBlock` for example). Other event metadata are not indexed (this is true for all consensus events, not just custom ones).

**Comment by avalkov** [comment]
@creachadair Hi, what I want is to be able to store the events so I can query them later on like audit what happened. I cannot find how to publish custom events to the eventBus from EndBlock, can you point this to me?
I followed the entire logic from EndBlocker of the module to tendermint fireEvents and it looks like just that these events are skipped, because they are not part of transaction.

**Comment by avalkov** [comment]
@creachadair Thanks I understand

**Comment by creachadair** [comment]
> What method you would suggest for persisting some events-like data in EndBlocker that I can later query? Since your out of transaction in EndBlocker I am not sure how I can achieve. My end goal is for example gravity module calls directly into the bank module and makes transfer and I wanna be able later to query all such gravity module transfers.

My general advice would be for an app to keep its own database to store data that it wants to persist. That gives the application control over what to store, how long to keep it around, and what queries to support. I believe applications built on top of the SDK already have access to a managed key-value database that might be sufficient.
