### ISSUE TITLE
[pubsub] Prioritise internal subscribers (e.g. reactor) over external (e.g. RPC)

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#847]
Right now when we get the msg, we iterate over map (of queries -> subscribers). If there are 1000 subscribers, consensus reactor could receive his msg last.

Ways to solve this:
1) return back old events system for internal events and proxy events to the new pubsub
2) add some priority/sorting to the new pubsub
3) add special kind of subscribers (VIP) to the new pubsub

**Comment by ebuchman** [comment]
Decision:

- use the old `events` for consensus internal stuff
- use new `pubsub` for RPC
