### ISSUE TITLE
light/provider/http: (*http).signedHeader should just check if err == nil instead of checking on the type of the err is it is nil

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#8471]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
e80dfa1ef51997a341b1a384eee0686aee925eaa

**Have you tried the latest version**: yes

If you look at the code in https://github.com/tendermint/tendermint/blob/8682489551b69d6b31947c9253c8c2f86fe4f2c7/light/provider/http/http.go#L238-L241

which relies on the underlying client's .Commit method to return a nil and untyped error. However this can be fallacious if at all a typed error would be returned yet the results was nil, we just need to check if the err == nil
```go
commit, err := p.client.Commit(ctx, height) 
if err == nil { // success!!
 	return &commit.SignedHeader, nil 
}
  
switch e := err.(type) { 
```

and this is an exhibit that can trivially show how things can fail https://go.dev/play/p/e9iAD00bhZB or inlined below
```go
package main

import (
	"fmt"
)

type myErr struct{ reason string }

func (me *myErr) Error() string { return me.reason }

func do() ([]byte, error) {
	var err *myErr
	return nil, err
}

func main() {
	_, err := do()
	fmt.Printf("%T\n", err)
}
```

which prints out NOT nil but instead
```shell
*main.myErr
```

**Comment by jmalicevic** [comment]
@odeke-em  We implemented this change in the corresponding PR, but even if we check for err == nil, in your example, err == nil would still not be true (https://go.dev/play/p/bG7KxttRtq0) . The only way to really signal that there was no error is to explicitly send nil as error so technically the two variations of the code return the same thing. Do you see anything we are missing here?
