### ISSUE TITLE
Decide: Should `VerifyVoteExtension` be called on `nil` precommits?

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#8487]
Validators currently call `VerifyVoteExtension` on all precommits that they receive for the current height. However, we currently do not use the vote extension data when reconstructing the lastCommit and passing the extended data to the application during `PrepareProposal`. This suggests that we can forgo calling the application with this data that is inevitably not going to be used. We should also consider dropping this from the `ExtendedCommit` that is stored in the block store.

**Comment by sergio-mena** [comment]
We decided back in December (in several ABCI++ meetings) that `nil` precommits wouldn't be extended. Several external people were in those meetings (notably @ValarDragon who was in agreement).
The spec was written following that principle. Has anything changed at this point to reopen this discussion?

**Comment by williambanfield** [comment]
We don't extend `nil` precommits, which is documented in the spec, so it seems natural to not call `VerifyVoteExtensions` as a result.

**Comment by thanethomson** [comment]
What happens if we do see vote extensions on a nil precommit? Should we actively strip it out or let vote validation fail? My sense is it should be considered a malformed vote if we see an extension on a nil precommit.

**Comment by sergio-mena** [comment]
> Either way, the code currently does make the call to `VerifyVoteExtension` if the precommit is nil at the moment and I'm assuming we don't want to do that.

If that's the case, that was an oversight on my side when reviewing the code. You're right: we shouldn't call `VerifyVoteExtension` if the precommit is `nil`.

**Comment by sergio-mena** [comment]
> What happens if we do see vote extensions on a nil precommit? Should we actively strip it out or let vote validation fail? My sense is it should be considered a malformed vote if we see an extension on a nil precommit.

I agree with you. At the very least, we should ignore the extension and log an error. Further, we could (in the future) even consider this as evidence of misbehavior.
