### ISSUE TITLE
scripts: Documentation

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#8507]
Reviewing #8501 got me poking around the `scripts` directory and I noticed we don't really have any documentation describing what's in there. Would it be worthwhile to have some kind of overview/README in that directory that describes the various tools/scripts and their purpose? Maybe their usage?

**Comment by creachadair** [comment]
Seems like a good idea to me. I think there are probably some things in there that could do with a bit of code love, as well as documentation.
