### ISSUE TITLE
chain cannot produce blocks

### ISSUE THREAD

**Issue by yaruwangway** [tendermint/tendermint#8516]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.35.2

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:
simd build from cosmos-sdk 0.46 with tendermint 0.35.2 cannot produce blocks.

```
 starting service impl=BlockSync module=blockchain service=BlockSync
3:29PM INF starting service impl=ConsensusReactor module=consensus service=Consensus
3:29PM INF starting service impl=StateSync module=statesync service=StateSync
3:29PM INF starting service impl=Mempool module=mempool service=Mempool version=v1
3:29PM INF starting service impl=Evidence module=evidence service=Evidence
3:29PM INF starting service impl=PEX service=PEX
3:29PM INF not caught up yet height=1 max_peer_height=0 module=blockchain timeout_in=58997.807458
3:29PM INF not caught up yet height=1 max_peer_height=0 module=blockchain timeout_in=57997.783208
3:29PM INF not caught up yet height=1 max_peer_height=0 module=blockchain timeout_in=56997.787667
3:29PM INF not caught up yet height=1 max_peer_height=0 module=blockchain timeout_in=55997.805458
3:29PM INF not caught up yet height=1 max_peer_height=0 module=blockchain timeout_in=54997.706708
3:29PM INF not caught up yet height=1 max_peer_height=0 module=blockchain timeout_in=53997.791292
3:29PM INF not caught up yet height=1 max_peer_height=0 module=blockchain timeout_in=52997.788125
```

**Have you tried the latest version**: yes/no

**How to reproduce it** (as minimally and precisely as possible):
```
cd cosmos-sdk
git checkout v0.46.0
make install
```
then [init a fresh chain](https://github.com/cosmos/cosmos-sdk/tree/main/simapp) and run it

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by yaruwangway** [comment]
the same thing happened when bumping gaia to use sdk 0.46 and tendermint 0.35, [here is the branch](https://github.com/cosmos/gaia/tree/rho)

**Comment by yaruwangway** [comment]
Marko told to to add `--mode validator` when start, works!

**Comment by yaruwangway** [comment]
sry for the drama 😂

**Comment by creachadair** [comment]
You can also put this into `config.toml` (in the global section at the top):

```toml
mode = "validator"
```
