### ISSUE TITLE
ABCI: strip down `CheckTxResponse` to necessary fields

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#8543]
## Summary

The `CheckTx` response has become quite bloated over the years with many of the fields unused or unnecessary (partly because of a desire to be in sync with `DeliverTx` response). We should review the usage of these fields and provide better documentation for the fields we think make sense.

## Proposal

Remove `MempoolError`, `Info`, `Events` & `Logs` from `CheckTxResponse`. 

We currently have both `GasWanted` and `GasUsed`, however only `GasWanted` is really used by the mempool to tally the total gas in a block. We should thus also consider removing `GasUsed` as well.

cc: @marbar3778 @aaronc

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jmalicevic** [comment]
A couple of comments. The fields not used anywhere meaningfully are: 
- Log
- Info 
They are however used in messages printed out to the user. Perhaps that can be relevant?

- GasUsed - is this however not useful information for the application to have for profiling? 
- Events

Regarding `MempoolError`, there is an explicit note in the code that it is not the application that should set this. There is a comment in RFC 11 https://github.com/tendermint/tendermint/blob/master/docs/rfc/rfc-011-delete-gas.md on it as well. 

 So if it is not the application that sets it but it still returns useful application, maybe it does ot have to be part  of the `ResponseCheckTx` but we should have it somewhere.

**Comment by jmalicevic** [comment]
From what I saw in the code, the only place `mempoolError` is set is by Tendermint **after** CheckTx returns. The application should not be setting it. As William already explained in the RFC linked above, we should provide this information to the operator. An option would be to separate this variable into a new message time so an operator can know that the transaction was kicked out of the mempool (even though it passed `CheckTx`) but I am not sure it adds value. I will add a comment to clarify its usage better though.

**Comment by creachadair** [comment]
> A couple of comments. The fields not used anywhere meaningfully are: […]

We should be careful about inferring usage from only the Tendermint repository—applications can call back into the node via the `ABCIQuery` RPC endpoint, and I believe the SDK may rely on that to service some of its gRPC endpoints. (I don't know of a specific case where _these_ fields are used, this is only to mention that we should check for usage outside the core alone).

**Comment by marbar3778** [comment]
> We currently have both GasWanted and GasUsed, however only GasWanted is really used by the mempool to tally the total gas in a block. We should thus also consider removing GasUsed as well.

I would check if this is used by users in order to help in debugging issues before removing. I think this is useful for users to find out more if the tx fails in the checked phase. Its a bit easier than parsing the raw_log in the response.  

> Remove MempoolError, Info, Events & Logs from CheckTxResponse.

MempoolError was added recently (https://github.com/tendermint/tendermint/commit/84c15857e41f036e99399c5f9167f1d72cf45a03) & (https://github.com/tendermint/tendermint/issues/3546). I think it is useful for clients, does it need to be removed. 


Info, Events & logs I am for removing.

**Comment by cmwaters** [comment]
`MempoolError` is for tendermint-side errors. We will still pass the error back to clients, we just won't add it to the ABCI response itself. It's a bit of a leaky abstraction to include the field there

**Comment by cmwaters** [comment]
>  I think this is useful for users to find out more if the tx fails in the checked phase

I don't think we pass `GasUsed` information to the client (nor `GasWanted`)
