### ISSUE TITLE
Document "various" mempool parameters

### ISSUE THREAD

**Issue by sbellem** [tendermint/tendermint#855]
Regarding the `mempool` parameters, the [documentation for the configuration](https://tendermint.readthedocs.io/en/master/specification/configuration.html) states:

> * `mempool.*`: Various mempool parameters

It would be helpful if these "various" parameters would be documented or if relevant documentation or even code was pointed/hyperlinked to.

**Comment by melekes** [comment]
Will be fixed by #792 most probably.

**Comment by zramsay** [comment]
yeah #792 fixes this
