### ISSUE TITLE
Disconnect from peer if it sends vote extension data when disabled

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#8565]
## Background
During the v0.36 development cycle, we implemented the ABCI++ `VoteExtension` feature. This feature could optionally be enabled by chains by selecting a height to require extensions. Before the selected height, vote extensions are not expected to be created or broadcast.

## Proposal

A peer sending a vote extension before the configured height should be disconnected from. The peer is either running faulty and possibly malicious software.

**Comment by tychoish** [comment]
I believe it's the case if the message handling function returns an error that the effect will be to disconnect the peer.
