### ISSUE TITLE
RFC 007 specifies unneeded sorting of repeated fields

### ISSUE THREAD

**Issue by aaronc** [tendermint/tendermint#8582]
Came across this when discussing protobuf serialization with @cmwaters.

It RFC 007 it says:

> 3. Reordered the contents of all repeated fields to be in lexicographically sorted order.
> repeated fields will appear in a message as having the same tag but will contain different contents. Therefore, lexicographical sorting will produce a stable ordering of fields with the same tag.

In the [proto encoding spec](https://developers.google.com/protocol-buffers/docs/encoding#optional), it says:
> The order of the elements with respect to each other is preserved when parsing, though the ordering with respect to other fields is lost. In proto3, repeated fields use [packed encoding](https://developers.google.com/protocol-buffers/docs/encoding#packed), which you can read about below.

Also in the [proto3 spec](https://developers.google.com/protocol-buffers/docs/proto3#specifying_field_rules)
> repeated: this field can be repeated any number of times (including zero) in a well-formed message. The order of the repeated values will be preserved.

So ordering matters. Sorting them doesn't make the encoding more deterministic it just breaks the spec and causes ordering information to be lost. This has the side effect that there could be collision of distinct messages with different field orderings.

**Comment by aaronc** [comment]
Also, our cosmos-proto code generator mostly implements ADR 027 deterministic marshaling with one pending issue to address: https://github.com/cosmos/cosmos-proto/issues/34

**Comment by creachadair** [comment]
> The order of the elements with respect to each other is preserved when parsing

That's exactly the concern:  For some messages, the order is significant, for others it is not. Protobuf parsing (and usually encoding) preserves order regardless. When it isn't significant, hashing whatever arbitrary order happened to be in the host value can give spurious differences. For an application where order counts, you wouldn't want to sort.

**Comment by aaronc** [comment]
> > The order of the elements with respect to each other is preserved when parsing
> 
> That's exactly the concern: For some messages, the order is significant, for others it is not.

The order of fields in encoding is never significant and those can be sorted to create a deterministic hash. The order of values in repeated fields should always be assumed to be significant. Trying to assume otherwise just breaks the spec

**Comment by creachadair** [comment]
> > That's exactly the concern: For some messages, the order is significant, for others it is not.
> 
> The order of fields in encoding is never significant 

That's true for order of _distinct_ field tags, but whether it is true for multiple values of the _same_ field tag depends on the application. That's the crux of the concern here: Whether the order of a repeated field matters to the application is not encoded in the wire format.

> The order of values in repeated fields should always be assumed to be significant. Trying to assume otherwise just breaks the spec

That only matters if you need to decode the result (which isn't a concern in this context). The procedure described is a workaround for producing a consistent hash, not a transformation to an equivalent encoding.

If you're building something that needs to decode the canonicalized bits, then as you say you can't use that trick.

**Comment by aaronc** [comment]
But how can you know for a given field whether the order matters for the application at the encoder level? What's proposed in RFC 007 and wirepb just indiscriminately sorts the repeated values. In rare cases it can introduce collisions.

**Comment by creachadair** [comment]
> But how can you know for a given field whether the order matters for the application at the encoder level? What's proposed in RFC 007 and wirepb just indiscriminately sorts the repeated values. In rare cases it can introduce collisions.

You can't. RFC 007 doesn't propose a general-purpose solution for all protobuf messages, it's only about the messages within Tendermint where we know (and mostly control) what the message types are.

**Comment by aaronc** [comment]
So _every_ repeated field in every message in Tendermint has unordered set semantics?

**Comment by creachadair** [comment]
> So _every_ repeated field in every message in Tendermint has unordered set semantics?

I think so, at least for the messages that need to be hashed. For those that don't participate in hashing, it doesn't matter. (And of course, if that's wrong, we'll just revise the plan).

**Comment by aaronc** [comment]
Why not just take a generic approach that is spec compliant? And that will actually be faster than an approach which sorts fields. That's what we're trying to do in https://github.com/cosmos/cosmos-proto which aims to provide high speed codegen-based deterministic serialization. And it could be a common tool for the SDK and Tendermint

**Comment by williambanfield** [comment]
I think that we should take that under advisement, but we don't really have much use for spec compliance. We won't roundtrip the bytes out of the canonical format, we only need deterministic serialization for hashing. I also think that our usecase is a bit simpler: we don't have arbitrary messages. We have a very narrow set of messages that require some canonical format for hashing and signing. 

Regarding the library, does it support multiple languages, or is it Go specific?

**Comment by creachadair** [comment]
> That's what we're trying to do in https://github.com/cosmos/cosmos-proto which aims to provide high speed codegen-based deterministic serialization. And it could be a common tool for the SDK and Tendermint

Part of the motivation for the proposal is to avoid having to depend on custom code generation machinery, which would have to be kept up-to-date against protobuf changes _and_ maintained for every language that wants to consume Tendermint proto messages. 

We (by which I mean not only Tendermint but the wider ecosystem) have had a poor history with maintaining custom code generation schemes. I'm cautious about embracing a new one until it has proven itself.

The trick we proposed in RFC 007 is not an ideal solution, it's true, but it's an inexpensive workaround for a relatively narrow problem.

**Comment by aaronc** [comment]
> Regarding the library, does it support multiple languages, or is it Go specific?

cosmos-proto is go-lang specific. It's compliant with the new google.golang.org/protobuf API but has performance similar to gogo proto

If you want a cross language solution that's more robust you can just have RFC 007 without doing the sorting of repeated values, which is effectively ADR 027. I'm not very comfortable relying on a non spec compliant approach which could go wrong if a repeated field actually does have ordered semantics. Also not sure why that would ever be needed unless you have nodes doing other non-deterministic things to generate non-deterministic array ordering, but that sounds like another problem
