### ISSUE TITLE
proof flag in rpc

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#86]
rpcs should take an optional proof flag, and corresponding responses should supply merkle proof of the response data

**Comment by akalyaev** [comment]
-> #355

**Comment by adrianbrink** [comment]
This can be closed, since it is implemented in #355

**Comment by ethanfrey** [comment]
Well, we still don't provide merkle hashes for the txs... but that would be another endpoint, and another issue.

**Comment by ebuchman** [comment]
Cool, this is covered by `abci_query?prove` and `tx?prove`
