### ISSUE TITLE
docs (block structure): hyperlinks lead to 404

### ISSUE THREAD

**Issue by sbellem** [tendermint/tendermint#860]
2 broken links:

- [ ] [that is a different chainID...](https://github.com/tendermint/basecoin/issues/32)
- [ ] [Simple Tree hash](http://tendermint.readthedocs.io/projects/tools/en/master/specification/Merkle-Trees#simple-tree-with-dictionaries)

### 1
In the [Commit](http://tendermint.readthedocs.io/projects/tools/en/master/specification/block-structure.html#commit) section of the [Block Structure](http://tendermint.readthedocs.io/projects/tools/en/master/specification/block-structure.html) documentation, second paragraph, last sentence:

> Also note that this `chainID` is in the `genesis.json` from Tendermint, not the `genesis.json` from the basecoin app ([that is a different chainID...](https://github.com/tendermint/basecoin/issues/32)).

the above hyperlink (https://github.com/tendermint/basecoin/issues/32) leads to a 404

### 2
In the [Block Hash](http://tendermint.readthedocs.io/projects/tools/en/master/specification/block-structure.html#block-hash) section of the [Block Structure](http://tendermint.readthedocs.io/projects/tools/en/master/specification/block-structure.html) documentation:

> The block hash is the [Simple Tree hash](http://tendermint.readthedocs.io/projects/tools/en/master/specification/Merkle-Trees#simple-tree-with-dictionaries) of the fields of the block Header encoded as a list of KVPairs

**Comment by zramsay** [comment]
fixed in #871, thanks for finding!
