### ISSUE TITLE
mempool: what is sender?(v0.35.4)

### ISSUE THREAD

**Issue by aofengli** [tendermint/tendermint#8623]
what is sender? Is it peer or user account address?

**Comment by creachadair** [comment]
Hi @aofengli. Do you mean the Sender field of the CheckTx response?

If so, that field is populated by the application, so the application decides what it represents. I believe the sender is typically filled with account information (if not left empty). This gives the application a way of limiting how many transactions to include in each block from a given account. Beyond that, the details depend on how the application is set up.

**Comment by aofengli** [comment]
thx so I can't post my future transactions? I mean: can I still maintain the sequence of my account offline?

**Comment by aofengli** [comment]
> Hi @aofengli. Do you mean the Sender field of the CheckTx response?
> 
> If so, that field is populated by the application, so the application decides what it represents. I believe the sender is typically filled with account information (if not left empty). This gives the application a way of limiting how many transactions to include in each block from a given account. Beyond that, the details depend on how the application is set up.

thank you for your reply;
So, if my sender field is the address of my account, can I still make concurrent transactions? Because I see this logic:

**Comment by aofengli** [comment]
In addition, we have also encountered this problem. We don't know if the priority queue can solve this problem. [#6219](https://github.com/tendermint/tendermint/issues/6219)
We also have two transactions with the same hash, in different blocks.
The result in the first block is wrong, but the resubmission in the second block is correct.
So, I see adr067 is the introduction of priority queue, so can he solve the problem of ordering transactions according to sequence?

**Comment by creachadair** [comment]
> So, if my sender field is the address of my account, can I still make concurrent transactions?

No, for the exact reason you pointed out: The node currently allows only one transaction per sender value. The node doesn't interpret the value, except to compare it for equality (as seen in the snippet you quoted).

If you want to allow multiple transactions for a given user of your application, you'd have to ensure the app issues different "sender" strings for them (e.g., by including a nonce of some kind in the value).

**Comment by creachadair** [comment]
> In addition, we have also encountered this problem. We don't know if the priority queue can solve this problem. [#6219](https://github.com/tendermint/tendermint/issues/6219) We also have two transactions with the same hash, in different blocks. The result in the first block is wrong, but the resubmission in the second block is correct. So, I see adr067 is the introduction of priority queue, so can he solve the problem of ordering transactions according to sequence?

It's not clear to me how priority would address this concern. In general, the consensus node is fine with the same transaction hash across _different_ blocks. Applications that want to avoid this would need to make rules about transaction validity to avoid this (for example, including nonces, sequence numbers, signatures, etc.). I believe the Cosmos SDK already includes some logic for tracking account sequence numbers for this exact concern.

But it's important to note that it's the _application_ that decides validity. As long as a transaction is not duplicated within the same height, the consensus node will generally not prevent this from occurring.

**Comment by aofengli** [comment]
> 



> > In addition, we have also encountered this problem. We don't know if the priority queue can solve this problem. [#6219](https://github.com/tendermint/tendermint/issues/6219) We also have two transactions with the same hash, in different blocks. The result in the first block is wrong, but the resubmission in the second block is correct. So, I see adr067 is the introduction of priority queue, so can he solve the problem of ordering transactions according to sequence?
> 
> It's not clear to me how priority would address this concern. In general, the consensus node is fine with the same transaction hash across _different_ blocks. Applications that want to avoid this would need to make rules about transaction validity to avoid it (for example, including nonces, sequence numbers, signatures, etc.). I believe the Cosmos SDK already includes some logic for tracking account sequence numbers for this exact concern.
> 
> But it's important to note that it's the _application_ that decides validity. As long as a transaction is not duplicated within the same height, the consensus node will generally not prevent this from occurring.

Thanks again for your reply.
The phenomenon is: our transaction is sent to the full node. Both transactions with sequence = 9 and sequence = 10 have passed the full node verification and entered the mempool. However, when broadcasting to the consensus node, the consensus node returns an error: seqence expects 9, got 10!
My guess is that the transaction with sequence = 10 is gossip first. I wonder if there is a way to avoid this problem on the tendermint side?

Because I saw what was introduced in adr067, the priority queue of tendermint refers to the dim memory pool, so...

**Comment by creachadair** [comment]
> Thanks again for your reply. The phenomenon is: our transaction is sent to the full node. Both transactions with sequence = 9 and sequence = 10 have passed the full node verification and entered the mempool. However, when broadcasting to the consensus node, the consensus node returns an error: seqence expects 9, got 10! My guess is that the transaction with sequence = 10 is gossip first. I wonder if there is a way to avoid this problem on the tendermint side?
> 
> Because I saw what was introduced in adr067, the priority queue of tendermint refers to the dim memory pool, so... @creachadair

I see what you mean. It's possible priorities could help with this, but it would need to be implemented carefully: For example, if the application simply sets the priority to the sequence number, and user X has sequence number 7000 while user Y has sequence number 50, user Y's transactions would probably never get selected.

The challenge here is that priorities are "shared" across all transactions (i.e., it's not just priority among a given user's transactions). I'm not saying it couldn't be done, but I don't see an obvious easy answer off the top of my head.

**Comment by aofengli** [comment]
> 
@creachadair 
I agree that it would be unfair for user Y if the priority ordering rule is by sequence, but it might be fair if it is sorted by other order (i.e: gas fee)

But this may not solve our current problem:
Scenario reproduction:
**Role: X User**
1. User X sends two transactions to the full node, the sequence of the transaction is sequence = 9 and sequence = 10
2. The checkTx for both transactions is successful,
3. Transactions gossip
4. The transaction of X user sequence = 10 first reaches the consensus node from the full node
5. The transaction order of the consensus node's mempool for these two X users is [10, 9]

Results of the:
1. The transaction with sequence = 9 of user X is executed failed.
2. The transaction with sequence = 9 of user X is executed successfully.
3. The transaction with sequence = 10 of user X is executed successfully in the next block.

Maybe the priority queue has not solved the problem that a single user's transaction gossip is out of order in the consensus node's mempool (maybe the tendermint team thinks this should be solved by the app) 😄

**Comment by creachadair** [comment]
> Maybe the priority queue has not solved the problem that a single user's transaction gossip is out of order in the consensus node's mempool (maybe the tendermint team thinks this should be solved by the app) 😄

Yes, I think your diagnosis here is essentially correct: Priority cannot solve ordering issues among transactions for the same user unless the application can consistently assign priorities that do not depend upon the order of arrival of those transactions.

But in this case I think the outcome isn't so bad: The sequence order of transactions is still preserved, modulo the block boundary in between.

**Comment by aofengli** [comment]
> > Maybe the priority queue has not solved the problem that a single user's transaction gossip is out of order in the consensus node's mempool (maybe the tendermint team thinks this should be solved by the app) 😄
> 
> Yes, I think your diagnosis here is essentially correct: Priority cannot solve ordering issues among transactions for the same user unless the application can consistently assign priorities that do not depend upon the order of arrival of those transactions.
> 
> But in this case I think the outcome isn't so bad: The sequence order of transactions is still preserved, modulo the block boundary in between.

thank you very much! I think I can close this issue.
