### ISSUE TITLE
rpc: net_info should return connection status

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#8636]
## Summary

In the v0.34 series, the `/net_info` call would return the connection status of the peers in its address book. The p2p refactor in v0.35 removed this so `/net_info` only returned the id and url of each peer. 

## Proposal

Consider reintroducing this information so operators are aware of which peers they are connected to.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by p0mvn** [comment]
Hi @cmwaters . Can I pick this up?
