### ISSUE TITLE
Distinguish between seeds and manual peers

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#864]
- [x] try to connect through addrbook before requesting peers from seeds
- [x] distinguish between seeds and manual peers in the config/flags
    - we only use seeds if we can’t connect to peers in the addrbook.
    - we always connect to nodes given in config/flags

related to https://github.com/tendermint/tendermint/issues/862

**Comment by melekes** [comment]
> try to connect through addrbook before requesting peers from seeds

https://github.com/tendermint/tendermint/blob/master/p2p/pex_reactor.go#L248-L292
we're already doing that, no?

**Comment by melekes** [comment]
> distinguish between seeds and manual peers in the config/flags

so we should add another config option & flag like `--manual_seeds`?

**Comment by zramsay** [comment]
:+1: for config option
:-1: for flag

I guess it depends on how often a dev/user will use this feature but in general i'm against adding new flags unless necessary

**Comment by ebuchman** [comment]
> we're already doing that, no?

Yes but that's after we've done DialSeeds.

We should specifically not dial the seeds if theres addrs we can dial, and only fall back on them if we cant connect to anyone.

> so we should add another config option & flag like --manual_peers

Yes. `--p2p.manual_peers`. This should ultimately replace the current use of `--p2p.seeds`, as seeds will become something else (just where you get your addresses from, not persistent peers).

**Comment by melekes** [comment]
> echo "Test connecting via /dial_seeds"
> bash test/p2p/pex/test_dial_seeds.sh $DOCKER_IMAGE $NETWORK_NAME $N $PROXY_APP

do we still want /dial_seeds to be around?

**Comment by ebuchman** [comment]
Handled in https://github.com/tendermint/tendermint/pull/1030
