### ISSUE TITLE
abci-cli: implement command for `PrepareProposal`

### ISSUE THREAD

**Issue by jmalicevic** [tendermint/tendermint#8643]
## Summary

We want to be able to call `PrepareProposal` via cli. The main use case at the moment is mbt testing of ABCI. 

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Can you provide a bit more clarification on this. Why do you want to use the cli for `PrepareProposal`?

**Comment by jmalicevic** [comment]
There was a request for this for MBT testing so that the test can call into the application.

**Comment by cmwaters** [comment]
I'm just a bit confused about how this works. You have tendermint calling `PrepareProposal` all the time. How would the CLI work

**Comment by jmalicevic** [comment]
I think this is just done for testing, unless I am mistaken, it should enable someone to run PrepareProposal against a running app and check the behaviour of just this function. I may be missing context around the cli, but right now this is being called only for abci testing.
