### ISSUE TITLE
Consensus: WAL replay takes very long if there are many rounds to be replayed

### ISSUE THREAD

**Issue by lklimek** [tendermint/tendermint#8679]
Dash Platform testnet network had failure after that the network advanced to round > 1000.
After restart a node, processing 1000 rounds took a lot of time (~ 14h, the node got to round 477).

We have fixed this in https://github.com/dashevo/tenderdash/pull/331 and would like to ask to include this solution in Tendermint.
We'll submit PR with the solution.

**Tendermint version**: Tenderdash 0.7.0, which is a fork of Tendermint 0.35 

**ABCI app**: Dash Platform Drive, https://github.com/dashevo/platform

**Environment**: [Docker image](https://github.com/dashevo/tenderdash/blob/c0411500126dfe7ea25bce44e9507e122714cf4b/DOCKER/Dockerfile)

**What happened**: 

Our network failed due to some issue with quorum. Validators were not able to reach consensus, and were increasing the round to a very huge number.

Once we fixed the issue and restarted Tenderdash/Tendermint node, it started replaying WAL, processing all rounds one by one. This took very long time (many hours). We decided to wipe WALs to make it faster, but this solution won't be easy to deploy on production network.

**What you expected to happen**:

Just replay last round from the WAL, and then sync with the network to get up-to-date.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):

Make the validators prevote NIL again and again at some height, and leave them running like that for a few days ;).

**Comment by cason** [comment]
> Just replay last round from the WAL, and then sync with the network to get up-to-date.

Why you consider this to be the expected behavior?

**Comment by cason** [comment]
So, first of all, is the height under discussion committed? Meaning, the node committed the decision of the height before crashing/being restarted?

If no, meaning, if the node did not know, at the time it interrupted its operation, the decision value, it had a given local state which is crucial for processing future messages in that height. Being very specific here, the locked and valid values are updated upon receiving `2/3+` Prevotes on any given round. Being locked into a value at a given round of consensus prevents a node from (pre)voting for any other value, exception made if the `Proposal` is accompanied by a valid round that is larger than the locked round. The valid round, and the `Proposal` broadcast by a node is, on its turn, determined by the node's local valid value and round. So, by skipping messages "from all rounds but the last" would prevent nodes from having valid and locked values and rounds properly set. This would produce what we call amnesia attack, as nodes that "promised" not voting for anything else than the value they locked may end up doing so.

So, while I agree that replying all the messages from the WAL is not optimal, any solution for avoiding this behavior must take into consideration any possible local state transition (e.g., setting lock and valid values and rounds) that will not be replayed using this approach, potentially making, in very simple works, correct nodes to equivocate.
