### ISSUE TITLE
Replace or refine use of github.com/btcsuite/btcd

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#8698]
We use this module as part of the implementation of the github.com/tendermint/tendermint/crypto/secp256k1 package. Recent changes to the upstream have introduced build breakage, and generally the history of that package reveals a number of sketchy dependency management choices.

We should either find a better-maintained implementation of this functionality, or fork out the piece we care about so we can have a cleaner dependency.

**Comment by wcsiu** [comment]
I have submitted a PR for it and it should fix the problem you mentioned.
https://github.com/tendermint/tendermint/pull/9250
