### ISSUE TITLE
allow nodes to start from only a state

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#8699]
## Summary

I would like to be able to start a node from a single state instead of needing both the latest block and state. I believe this is already possible because of how state sync works. If so, this functionality could be under a feature flag in the start command
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
We basically do this already it's just really messy and needs to be cleaned up. I think all "state-advancing mechanisms" i.e. statesync, blocksync, and consensus should work by taking in one state and through some means be able to progress to another more advanced state. Going between these protocols should be a matter of pausing one and passing the final state as the initial state of the new one
