### ISSUE TITLE
Active/active validator setup

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#870]
For high availability, it would be nice to setup multiple validators that sign using the same key. So basically an active/active setup instead of relying on failing over in case of a failure.

This would protect against downtime in the case of a failure of the primary, but it is unclear what happens (if anything) during consensus when identical signatures appear?

@adrianbrink hinted that @zmanian would be able to provide some input on this.

**Comment by zmanian** [comment]
Having two nodes with the same key puts you at risk for slashing.

The nodes will likely propose two different blocks when their proposer turn comes around.

An adversary could selectively target the nodes to trigger a double sign.

It could be interesting to have setting where a node is instructed to never sign anything but stays synched.

**Comment by mdyring** [comment]
Agreed, makes sense when proposing.

It then seems some mechanism to do a fast fail-over is missing as a piece of this puzzle, if slashing happens when a validator is down?

**Comment by ebuchman** [comment]
No slashing for now when a validator is down - just lower rewards, and eventually the validator gets unbonded. 

We're working on signing code - see https://github.com/tendermint/tendermint/pull/1044,  https://github.com/tendermint/tendermint/pull/1060, and https://github.com/tendermint/signatory.

Will close this in favour of those
