### ISSUE TITLE
two long lived v0.34 branches exist

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#8702]
there are two long lived 0.34 branches on this repo. One is getting back ports from dependant and other is getting back ports from the developers. Which one is the correct one?

**Comment by creachadair** [comment]
The [v0.34.x](https://github.com/tendermint/tendermint/tree/v0.34.x) branch is the correct (maintained) backport branch for v0.34. 

Are you looking at the `v0.34/x` branch as the other candidate? If so I strongly suspect that may have been a typo, and we should probably just delete it.

**Comment by marbar3778** [comment]
figured it out.
