### ISSUE TITLE
a peer may panic when switch from fastSync to stateSync

### ISSUE THREAD

**Issue by chengzhinei** [tendermint/tendermint#8703]
when switchToConsensus, cs.LastCommit is nil.
and if it receives the vote of last height at this moment, it will panic because of LastCommit.AddVote()

![image](https://user-images.githubusercontent.com/7297559/172151981-b53042ca-e98c-4bfd-87d3-9b80cb3d461b.png)
![image](https://user-images.githubusercontent.com/7297559/172152042-db53ff27-03f7-4f3b-b557-9fbf765030d8.png)

**Comment by cmwaters** [comment]
Thanks for raising this issue. What version do you see this in?

**Comment by chengzhinei** [comment]
We use an early version, but have no change here.
And it still has this problem in the latest version, but is it occasional.

> Thanks for raising this issue. What version do you see this in?
