### ISSUE TITLE
all: use SHA256 with SIMD for higher speeds and throughput

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#8707]
In this repository, we heavily use the Go standard library's crypto/sha256. However there exists a Single Instruction Multiple Data (SIMD) package from our friends at Minio per https://github.com/minio/sha256-simd and it promises 8X speed ups when using AVX instructions. We should explore this.

Let's explore if performance radically improves and then plumb it in.

Kindly cc-ing my colleague @elias-orijtech

**Comment by ValarDragon** [comment]
cref https://github.com/tendermint/tendermint/issues/2186

**Comment by odeke-em** [comment]
> cref https://github.com/tendermint/tendermint/issues/2186 , recommends the same repo :)

Good foresight @ValarDragon! Thanks for the reference and we shall get this in.

**Comment by cmwaters** [comment]
I'm happy to encourage experimenting with this. I don't know exactly what the acceptance criteria for this should be but other than showing some tendermint-specific benchmarks, I'd like to know that this library has been externally audited and is trusted and used by many other systems.

Obvious question, but this wouldn't change the hashing algorithm itself right?

**Comment by webmaster128** [comment]
> Obvious question, but this wouldn't change the hashing algorithm itself right?

Right. It's a different implementation that executes the same algorithm differently. This is possible by using CPU specific instructions that not every CPU has available.
