### ISSUE TITLE
p2p: consider changes to facilitate future upgrades

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#872]
!

**Comment by melekes** [comment]
do we have to do anything concrete, or it's just something we should keep in mind?

**Comment by ebuchman** [comment]
Something to keep in mind. Amino might help here.

But we should walk through a scenario of what would happen if we upgrade things - probably the handshake should start with exchange of some kind of versionable object otherwise it will always be breaking.

I think maybe if NodeInfo is Amino encoded it will be ok

**Comment by xla** [comment]
*2018-06-13* Discussion between @ebuchman @jaekwon @xla 

We want to communicate the following versions:

* tendermint binary version (currently in [version.go](https://github.com/tendermint/tendermint/blob/master/version/version.go))
* tendermint protocol version, yet to be specified
* app binary version
* app protocol version

Protocol versions assumed to be monotically incrementing integers which guarantee backwards and forwards compatibility of at least one (max two versions).

**Comment by xla** [comment]
Relevant #1627

**Comment by ebuchman** [comment]
Closing for [ADR-016](https://github.com/tendermint/tendermint/blob/develop/docs/architecture/adr-016-protocol-versions.md)
