### ISSUE TITLE
Question: how to run node as seednode, fullnode and validator on 0.34.x version?

### ISSUE THREAD

**Issue by zeroFruit** [tendermint/tendermint#8726]
Hello. I'm trying to run node as seednode, fullnode and validator with Tendermint v0.34.14.
I've noticed that on v0.34.14, there's no `mode` field which is quite intuitive to use, so I'm curious about how to run the node for each type.
So far, I've checked out [v.0.34.14 commit and read the docs](https://github.com/tendermint/tendermint/blob/85870def7b/docs/DOCS_README.md). However, there are still some questions.

1. If we want to run the node as a full node, then `priv_validator_key_file`, `priv_validator_state_file` field should be empty? Or doesn't it matter, if `genesis.json` does not contain the pubkey of the node?
2. If we want to run the node as a seed node, then `seed_mode` should be true? And if that field is true, `priv_validator_key_file`, `priv_validator_state_file` fields are doesn't matter whether empty or not?
3. How should we set the config if we want to run the node as a persistence node with non-validator (full node)?

The followings are some parts of the config and genesis file to help to understand the question easily.

*config.toml*
```
#######################################################################
###                   Main Base Config Options                      ###
#######################################################################

# Path to the JSON file containing the private key to use as a validator in the consensus protocol
priv_validator_key_file = "config/priv_validator_key.json"

# Path to the JSON file containing the last sign state of a validator
priv_validator_state_file = "data/priv_validator_state.json"

# TCP or UNIX socket address for Tendermint to listen on for
# connections from an external PrivValidator process
priv_validator_laddr = ""

# Path to the JSON file containing the private key to use for node authentication in the p2p protocol
node_key_file = "config/node_key.json"

#######################################################
###           P2P Configuration Options             ###
#######################################################
[p2p]

# Seed mode, in which node constantly crawls the network and looks for
# peers. If another node asks it for addresses, it responds and disconnects.
#
# Does not work if the peer-exchange reactor is disabled.
seed_mode = false
```

*genesis.json*
```
"genutil": {
      "gen_txs": [
        {
          "body": {
            "messages": [
              {
                "@type": "/cosmos.staking.v1beta1.MsgCreateValidator",
                "description": {
                  "moniker": "mynode",
                  "identity": "",
                  "website": "",
                  "security_contact": "",
                  "details": ""
                },
                ...
                "min_self_delegation": "1",
                "delegator_address": "...",
                "validator_address": "...",
                "pubkey": {
                  "@type": "/cosmos.crypto.ed25519.PubKey",
                  "key": "G71WmUkKIR4afrXrvZomdvGDUAlJJOdyJC8J87nGJNk="
                },
              }
            ],
            "memo": "8aebef39fd93e06a5fba32016847970dfc013444@10.10.10.206:26656",
          },
          "auth_info": {
            "signer_infos": [
              {
                "public_key": {
                  "@type": "/ethermint.crypto.v1.ethsecp256k1.PubKey",
                  "key": "AiWYRXo2KBF6zVR86jD8MheUrc1jbAGTW09bVriCGOme"
                },
                "mode_info": {
                  "single": {
                    "mode": "SIGN_MODE_DIRECT"
                  }
                },
                "sequence": "0"
              }
            ],
          },
        }
      ]
    },
```

**Comment by zeroFruit** [comment]
After some tests, I realized that a full node can be a persistence node, sentry node, seed node, or both.
Below Venn-diagram is what I understand about node type.

A seed node is also a full node that syncs the state with the validator, plus it crawls the peer address and sends addresses to the connected peer at the same time.

Could someone double-check if this is right?

![image](https://user-images.githubusercontent.com/18715362/172768230-85dadb78-83be-41cc-9938-c56df4c6d576.png)

**Comment by cmwaters** [comment]
In v0.34.x, all full nodes are validators in the sense they also generate validator keys for signing votes and proposals. However, they will only sign these things if they are in the `ValidatorSet`. As you pointed out, to run as a seed node, you simply set it in the p2p section of the `config.toml`. Sentry nodes are also just regular nodes but they have they have persistent peer connections with the validator. Hope that clarifies things, but let me know if you have any further questions

**Comment by zeroFruit** [comment]
Thank you I understand completly!

**Comment by zeroFruit** [comment]
@cmwaters Thank you for the answer. Now I did bootstrap my network successfully with proper connections 👍

**Comment by cmwaters** [comment]
No worries. Going to close this issue but feel free to open up more if you come across anything else
