### ISSUE TITLE
p2p: more accurate ListenAddr for inbound peers

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#873]
Inbound peers may not know their public IP.
We should override the IP (but not the port) in the nodeInfo.ListenAddr with the IP from the connection itself.

**Comment by ebuchman** [comment]
There was discussion re what to do about this, namely nothing. It would mean that peers that can't figure out their own IP never get dialed. We could easily change the behaviour later if it's a problem.

It still seems a bit weird to me that the address we dial could be different than the address the peer self reports. It means later, for instance when we consider the peer as a source for reactor messages, the source address would be the self-reported ListenAddr, and not necessarily the actual address we dialled.

**Comment by ValarDragon** [comment]
I presume by this being in the launch milestone. Would this change belong in PexReactor.Addpeer, or the peer transport.

**Comment by ebuchman** [comment]
I think we can close this. It's a concern mostly replaced by using ExternalAddress correctly.
