### ISSUE TITLE
Is it necessary to write every msg into wal?

### ISSUE THREAD

**Issue by chengzhinei** [tendermint/tendermint#8734]
when a peer receive msg and before handleMsg, this msg will write into wal no matter it is added.
![image](https://user-images.githubusercontent.com/7297559/172988419-f8cc365c-75ef-4162-a1bf-e1a638c1bc67.png)

maybe it should write the msg only when this msg is used and added.

**Comment by cmwaters** [comment]
Yeah this has been discussed in the past and we are aware that the consensus WAL could be improved a lot - we just currently don't have the bandwidth to make it a high priority. We do have this high level tracking issue on future database related work: https://github.com/tendermint/tendermint/issues/6032

**Comment by cason** [comment]
This is a good point, worth some improvement, but I agree that is not top priority by now.

Notice, however, that this `Write` call is not persistent, and the cost of writing the WAL to disk is only paid when the node produces a message (`WriteSync` call in the `case` statement below the depicted one).

**Comment by chengzhinei** [comment]
When block has too many txs, the block-size becomes bigger, and we will get more block parts.
Every block part will write wal, and we have tested it costs about 40ms each part, and when the number of block parts is too many, it cost much time to complete the ProposalBlock.

So, how about only keep writing the vote msg, and ignore other msg types when handleMsg?

**Comment by chengzhinei** [comment]
> Yeah this has been discussed in the past and we are aware that the consensus WAL could be improved a lot - we just currently don't have the bandwidth to make it a high priority. We do have this high level tracking issue on future database related work: #6032

When block has too many txs, the block-size becomes bigger, and we will get more block parts.
Every block part will write wal, and we have tested it costs about 40ms each part, and when the number of block parts is too many, it cost much time to complete the ProposalBlock.

So, how about only keep writing the vote msg, and ignore other msg types when handleMsg?

**Comment by cason** [comment]
> So, how about only keep writing the vote msg, and ignore other msg types when handleMsg?

In this case, how can we know, when recovering, which proposal we voted for?

I see some improvements on how we manage the WAL, we might avoid writing a (full) block multiple times and so. But persisting a value/block _before_ voting for it is crucial for supporting nodes that fail and can later recover...

**Comment by cason** [comment]
Regarding blocks shipped through multiple block part messages, I agree some improvement can be achieve here.

While we still need to persist the proposed block, we might postpone this until we get a valid full block. The cost of writing the full block, however, should not be much lower than persisting it part by part. 

One solution we might consider here is to increase the buffer size of the writer. I assume it is a buffered writer, that only actually persist data to disk when the buffer is full, or when instructed to do so (`WriteSync` calls).
