### ISSUE TITLE
Redis-like subscriptions

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#874]
The issue of `tmlibs/pubsub/query` being too complex was raised by @ethanfrey https://github.com/tendermint/abci/pull/130#issuecomment-345223461. 

Notably, the query 
1) allows you to do cool stuff like query by date ("block.time > TIME(2017-01-01 14:30:00.000)" and range ("tx.height > 5")
2) the same interface can be used for streaming and batch parts

Downsides are speed (see query#Matches https://github.com/tendermint/tmlibs/blob/master/pubsub/query/query.go#L66) and complexity.

### Proposal

Redis-like subscriptions https://redis.io/topics/pubsub

```go
eventHub.Subscribe(ctx, "test", ["first", "second"], out)
eventHub.Publish(msg, "first")
```

```
If we actually used redis as a backing store for pub sub (just as an example, we don't need to), sorted sets would satisfy the requirements of exactly one, predefined integer sort:

https://redis.io/topics/data-types#sorted-sets
https://redis.io/commands/zrangebyscore

This technique is explained in detail here (just skip the java code in the middle):

https://www.infoworld.com/article/3212768/database/how-to-use-redis-for-real-time-stream-processing.html?page=2
```

Pros:
- faster

Cons:
- does not allow complex stuff

Q: do we need pattern-matching? Like `eventHub.PSubscribe(ctx, "test", ["account.number.*"])`

### Indexing

```
btw, my approach for handling this directly on leveldb, which supports iteration, would be to define keys as (channel string, block uint64, index uint32) tuples, using uncompressed bigendian for the uints so their binary representation has the same lexographical order as an integer comparison. And prefixing string with the length to avoid overlap in searches between strings like "foo" and "foobar" (or another approach that acheives the same).

You could then calculate byte representations for (channel, min block, 0) and (channel, max block, MAX_UINT32) and run a level db iterator over that space. Super easy and efficient (edited)

The purpose of adding tx index as a third parameter is to avoid collisions if there are multiple tx in the same block that match a channel
```

```
# index by channel
(channel, block, index) => []byte()
# index tx by block and index
(block, index) => (result TxResult)
```

Q: do we need to index tx by hash? hash is long (20 bytes) comparing to 12 bytes (block + index).

**Comment by melekes** [comment]
```
BEFORE:
BenchmarkEventBus/10Clients1Query1Event-2                 500000              3797 ns/op           384 B/op          5 allocs/op
BenchmarkEventBus/100Clients-2                             50000             26690 ns/op           384 B/op          5 allocs/op
BenchmarkEventBus/1000Clients-2                             5000            234626 ns/op           384 B/op          5 allocs/op
BenchmarkEventBus/10ClientsRandQueries1Event-2           1000000              2196 ns/op           464 B/op         10 allocs/op
BenchmarkEventBus/100Clients#01-2                         200000              5256 ns/op           640 B/op         21 allocs/op
BenchmarkEventBus/1000Clients#01-2                        100000             19213 ns/op           640 B/op         21 allocs/op
BenchmarkEventBus/10ClientsRandQueriesRandEvents-2               1000000              2032 ns/op           496 B/op         12 allocs/op
BenchmarkEventBus/100Clients#02-2                                 300000              4655 ns/op           640 B/op         21 allocs/op
BenchmarkEventBus/1000Clients#02-2                                100000             19568 ns/op           640 B/op         21 allocs/op
BenchmarkEventBus/10Clients1QueryRandEvents-2                    1000000              1192 ns/op           384 B/op          5 allocs/op
BenchmarkEventBus/100Clients#03-2                                1000000              2603 ns/op           384 B/op          5 allocs/op
BenchmarkEventBus/1000Clients#03-2                                100000             14766 ns/op           384 B/op          5 allocs/op
```

**Comment by ethanfrey** [comment]
What are the four cases? 

The first is much slower. The other three are quite similar...

**Comment by melekes** [comment]
```
Jae Kwon [26 minutes ago] 
I think experimenting with a simple > < conditional is OK for now.  It's just a message bus, so comparisons etc are done in memory so it really shouldn't be a performance bottleneck.
The > < conditions will be useful in the future for sharding indexers...
```

**Comment by LeeBlues** [comment]
Why don't you guys look at nchan pub/sub solution?
It's open source. https://github.com/slact/nchan

**Comment by LeeBlues** [comment]
May shim pubsub server helpful? nchan can serve millions of live subscribers. 
https://github.com/slact/nchan

**Comment by LeeBlues** [comment]
what about nchan pubsub server?
current parser seems cool though..

https://youtu.be/TVgQSmqWm60?t=13m19s

https://github.com/slact/nchan

**Comment by melekes** [comment]
nchan looks great! but it is written in C and I don't think we want any C deps.

**Comment by jackzampolin** [comment]
I like this idea a lot. Is it also tied into the RPC improvements issue?

**Comment by jackzampolin** [comment]
I like this idea a lot. Is it also tied into the RPC improvements issue? #3367

**Comment by ethanfrey** [comment]
Wow, back to the living.

I think part of RPC improvements.
If there is real momentum, and you are willing to rebuild rpc from scratch, I have plenty of ideas...

**Comment by melekes** [comment]
> Wow, back to the living.

😭

**Comment by marbar3778** [comment]
> If there is real momentum, and you are willing to rebuild rpc from scratch, I have plenty of ideas...

I would love to facilitate this conversation, @ethanfrey would you like to post some ideas here #3367 and we can spur discussion and decide how to move forward

**Comment by tessr** [comment]
[Note: This is distinct from indexing; this is subscribing to live events as they happen.]

**Comment by marbar3778** [comment]
TODO:
- Who would benefit from this change?
- What are the options from moving away from our custom pubsub model.

**Comment by alexanderbez** [comment]
I believe the less proprietary code we have to maintain, the better. I don't know if Redis is the right approach, but if we can find a well supported go-native approach that would allow us to remove the custom querying and match code, I think that would be worth it. We should explore the landscape of pubsub frameworks out there that persist data to replace our own.

**Comment by creachadair** [comment]
This should be mostly subsumed by [ADR 075](../blob/master/docs/architecture/adr-075-rpc-subscription.md). The design retains the existing query language (whose performance was improved in #7319 et seq.), but we could always consider extending or replacing that later.
