### ISSUE TITLE
Version string empty in Docker images tendermint/tendermint

### ISSUE THREAD

**Issue by webmaster128** [tendermint/tendermint#8743]
In #6488 and #6494 it was discussed that Tendermint exposing its version would be very valuable for clients. This now becomes important again as people start to connect to Cosmos SDK 0.46 networks which need a Tendermint 0.35 client. In order to be able to provide a convenient experience for app builders, higher level client library code should be able to detect the Tendermint version and use the best client for it (currently 0.34 or 0.35).

In https://github.com/cosmos/cosmjs/pull/1173 I'm trying to test the Tendermint version returned from Tendermint in the Docker images `tendermint/tendermint:v0.34.19` and `tendermint/tendermint:v0.35.6`. Unfortunately they are always empty.

```
$ curl -sS http://localhost:11135/status | jq .result.node_info
{
  "protocol_version": {
    "p2p": "8",
    "block": "11",
    "app": "1"
  },
  "id": "647ec3620ba85fb056c8c94faa4ef023dadc6f9b",
  "listen_addr": "tcp://0.0.0.0:26656",
  "network": "dockerchain",
  "version": "",
  "channels": "402021222330386061626300",
  "moniker": "dockernode",
  "other": {
    "tx_index": "on",
    "rpc_address": "tcp://0.0.0.0:26657"
  }
}
```

and

```
$ curl -sS http://localhost:11135/status | jq .result.node_info
{
  "protocol_version": {
    "p2p": "8",
    "block": "11",
    "app": "1"
  },
  "id": "647ec3620ba85fb056c8c94faa4ef023dadc6f9b",
  "listen_addr": "tcp://0.0.0.0:26656",
  "network": "dockerchain",
  "version": "",
  "channels": "402021222330386061626300",
  "moniker": "dockernode",
  "other": {
    "tx_index": "on",
    "rpc_address": "tcp://0.0.0.0:26657"
  }
}
```

**Comment by cmwaters** [comment]
Hey, yup we can look into this. As a follow up question, do you think it may be helpful to distinguish between app version and tendermint version? Also is there any value in using the protocol version to reflect breaking changes?

**Comment by webmaster128** [comment]
Thank you!

So far I only needed Tendermint versions. This is for the Tendermint RPC API only. Breaking changes in the p2p layer are not a problem for the client.

I have

```
  "protocol_version": {
    "p2p": "8",
    "block": "11",
    "app": "1"
  },
```

available but never used those for anything.
