### ISSUE TITLE
Genesis export doesn't set `LastBlockHeight` correctly

### ISSUE THREAD

**Issue by robert-zaremba** [tendermint/tendermint#8773]
Moved from https://github.com/cosmos/gaia/issues/1533

**Tendermint version** 
0.34.x, probably other versions as well

**What happened**:

When importing an exported genesis (eg from a running chain to a different environment), we don't set `LastBlockTime` correctly. Instead of taking a time from the last block, it takes time from the original genesis time.

**What you expected to happen**:

I expect to see a time from the last processed block when the export was done.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):

See https://github.com/cosmos/gaia/issues/1533

**Comment by williambanfield** [comment]
I think I'm a bit confused by this issue. Looking at the original gaia issue, the user appears to have cleared the blockstore. If there is nothing in the blockstore, Tendermint will use the time listed in the genesis file as the last block time in consensus. Perhaps I'm misreading the original issue, as this seems like the expected behavior.

**Comment by RafilxTenfen** [comment]
@williambanfield right now if we use the genesis file as the last block time when restarting a chain from an exported genesis, the next new block would have the same block time as the genesis time

wouldn't be better if the last block time was saved in the genesis file? this way we would never have any new block with the block time == genesis time

**Comment by robert-zaremba** [comment]
> Tendermint will use the time listed in the genesis file as the last block time in consensus

I think he export doesn't work correctly. 
IMO, the `LastBlockTime` should be the time of the last finalized block when doing the export, rather than the original genesis time.

**Comment by williambanfield** [comment]
> I think the export doesn't work correctly.

Got it, I think this issue should be filed against the sdk [where the `export` command is maintained](https://github.com/cosmos/cosmos-sdk/blob/8fa2faba47068a21ce7865a6114c0357130fb096/server/export.go#L27) unless there's another command in the Tendermint code that I'm not recalling. I've pasted the Tendermint subcommands below to clarify.


```
BFT state machine replication for applications in any programming languages

Usage:
  tendermint [command]

Available Commands:
  debug                       A utility to kill or watch a Tendermint process while aggregating debugging data
  gen-node-key                Generate a node key for this node and print its ID
  gen-validator               Generate new validator keypair
  help                        Help about any command
  init                        Initialize Tendermint
  light                       Run a light client proxy server, verifying Tendermint rpc
  probe-upnp                  Test UPnP functionality
  replay                      Replay messages from WAL
  replay-console              Replay messages from WAL in a console
  reset-state                 Remove all the data and WAL
  rollback                    rollback tendermint state by one height
  show-node-id                Show this node's ID
  show-validator              Show this node's validator info
  start                       Run the tendermint node
  testnet                     Initialize files for a Tendermint testnet
  unsafe-reset-all            (unsafe) Remove all the data and WAL, reset this node's validator to genesis state
  unsafe-reset-priv-validator (unsafe) Reset this node's validator to genesis state
  version                     Show version info

Flags:
  -h, --help               help for tendermint
      --home string        directory for config and data (default "/home/william/.tendermint")
      --log_level string   log level (default "info")
      --trace              print out full stack trace on errors

Use "tendermint [command] --help" for more information about a command.
```

**Comment by robert-zaremba** [comment]
`LastBlockTime` is set in Tendermint, not SDK.

**Comment by williambanfield** [comment]
> wouldn't be better if the last block time was saved in the genesis file?

@RafilxTenfen could you explain a bit more about what is wanted by this? I'm a bit unclear.

**Comment by RafilxTenfen** [comment]
> @RafilxTenfen could you explain a bit more about what is wanted by this? I'm a bit unclear.

I can try ^^
running gaia on v702 
![image](https://user-images.githubusercontent.com/17556614/173385388-514dbf2b-d3cd-46a3-8ddb-07c677561056.png)

Block Height: 4 was the last block before stopping the node
After stopping the node, running `export` to generate the `genesis.json`, delete the *.db, and restarting the chain with the exported genesis
The next block generated of height 5, is going to have the same block time as the genesis block (block height 0) 

IMHO this is bad because it should never be a block time lower than the previous block time
Also is breaking the modules which compute the time between blocks to calculate interest like [543](https://github.com/umee-network/umee/issues/543)

**Comment by williambanfield** [comment]
Got it, @RafilxTenfen, this would require a change to the `export` command to output a genesis file with a timestamp corresponding to the timestamp of block height 4.

**Comment by williambanfield** [comment]
Since the `export` code is not a part of Tendermint and instead lives in the Cosmos-SDK, this issue should be moved over there @RafilxTenfen.

**Comment by RafilxTenfen** [comment]
> Since the `export` code is not a part of Tendermint and instead lives in the Cosmos-SDK, this issue should be moved over there @RafilxTenfen.

@robert-zaremba do you want to do that ?
