### ISSUE TITLE
Sync Tendermint 0.34.x and 0.35.x

### ISSUE THREAD

**Issue by 9M6** [tendermint/tendermint#8776]
Hello, I'm trying to sync a chain node built on top of Tendermint 0.35.4 with another node that still uses 0.34.x, blocks are not coming in, is it something related to tendermint itself, or am I doing something wrong my side in the business logic?

**Comment by creachadair** [comment]
Hi, @9M6. Can you say more about what versions of Tendermint the various nodes in your network are using, and what the symptoms are? 

For example: Is the network not making any progress at all (as a whole), or is it only some of the nodes that are not receiving blocks? And are the nodes successfully exchanging traffic, or are there errors/failures in the logs?

More broadly: We can't generally promise that networks using multiple Tendermint releases will necessarily work together. I do not know of any _specific_ reasons why v0.34 and v0.35 shouldn't be able to consense together, but this is not a pattern we'd recommend, and it's not a case we have deliberate testing for. 

With more details, it's possible we could find configuration changes that could make it work, but it's definitely not a use case we can guarantee will work.
