### ISSUE TITLE
Replaced tendermint's kv tx_index with postgresql, but data cannot be written

### ISSUE THREAD

**Issue by aofengli** [tendermint/tendermint#8807]
**Tendermint Vserion**:  v0.34.14.
**Postgreql Version**: v14
**character set**: utf-8
**Error Msg**: ERR failed to index block err="end-block events: pq: invalid byte sequence for encoding \"UTF8\": 0x00"

![image](https://user-images.githubusercontent.com/22781840/174745840-c3725fb8-246f-4049-ad7b-7f55c9496461.png)

**Comment by marbar3778** [comment]
which application are you using?

**Comment by jacobhjkim** [comment]
@aofengli Were you able to fix this? I am having the same issue.
