### ISSUE TITLE
all: re-arrange some structs for optimal RAM savings

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#8846]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
cfd13825e2c4ea5b6099ae05f73524a97a1eba82

**What happened**:
Ran, an open sourced Orijtech static analyzer [structslop](https://medium.com/orijtech-developers/efficient-struct-packing-guided-pass-for-go-92255872ec72) on tendermint and it showed that some of the structs could be optimally arranged for RAM savings

```shell
/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/types/part_set.go:156:14: struct has size 88 (size class 96), could be 80 (size class 80), you'll save 16.67% if you rearrange it to:
struct {
	hash          []byte
	parts         []*Part
	partsBitArray *bits.BitArray
	byteSize      int64
	mtx           sync.Mutex
	total         uint32
	count         uint32
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/config/config.go:411:16: struct has size 232 (size class 240), could be 224 (size class 224), you'll save 6.67% if you rearrange it to:
struct {
	CORSAllowedOrigins           []string
	CORSAllowedMethods           []string
	CORSAllowedHeaders           []string
	RootDir                      string
	ListenAddress                string
	PprofListenAddress           string
	TLSKeyFile                   string
	TLSCertFile                  string
	MaxSubscriptionsPerClient    int
	EventLogWindowSize           time.Duration
	EventLogMaxItems             int
	TimeoutBroadcastTxCommit     time.Duration
	MaxBodyBytes                 int64
	MaxHeaderBytes               int
	MaxSubscriptionClients       int
	MaxOpenConnections           int
	ExperimentalDisableWebsocket bool
	Unsafe                       bool
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/config/config.go:606:16: struct has size 184 (size class 192), could be 176 (size class 176), you'll save 8.33% if you rearrange it to:
struct {
	RootDir                       string
	ListenAddress                 string
	ExternalAddress               string
	BootstrapPeers                string
	PersistentPeers               string
	QueueType                     string
	PrivatePeerIDs                string
	MaxIncomingConnectionAttempts uint
	FlushThrottleTimeout          time.Duration
	MaxPacketMsgPayloadSize       int
	SendRate                      int64
	RecvRate                      int64
	HandshakeTimeout              time.Duration
	DialTimeout                   time.Duration
	MaxOutgoingConnections        uint16
	MaxConnections                uint16
	PexReactor                    bool
	UPNP                          bool
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/config/config.go:725:20: struct has size 88 (size class 96), could be 80 (size class 80), you'll save 16.67% if you rearrange it to:
struct {
	RootDir               string
	Size                  int
	MaxTxsBytes           int64
	CacheSize             int
	MaxTxBytes            int
	MaxBatchBytes         int
	TTLDuration           time.Duration
	TTLNumBlocks          int64
	Broadcast             bool
	KeepInvalidTxsInCache bool
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/config/config.go:824:22: struct has size 104 (size class 112), could be 96 (size class 96), you'll save 14.29% if you rearrange it to:
struct {
	RPCServers          []string
	TrustHash           string
	TempDir             string
	TrustHeight         int64
	TrustPeriod         time.Duration
	DiscoveryTime       time.Duration
	ChunkRequestTimeout time.Duration
	Fetchers            int32
	Enable              bool
	UseP2P              bool
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/internal/consensus/types/peer_round_state.go:15:21: struct has size 152 (size class 160), could be 136 (size class 144), you'll save 10.00% if you rearrange it to:
struct {
	ProposalBlockPartSetHeader types.PartSetHeader
	StartTime                  time.Time
	ProposalBlockParts         *bits.BitArray
	Height                     int64
	ProposalPOL                *bits.BitArray
	Prevotes                   *bits.BitArray
	Precommits                 *bits.BitArray
	LastCommit                 *bits.BitArray
	CatchupCommit              *bits.BitArray
	Round                      int32
	ProposalPOLRound           int32
	LastCommitRound            int32
	CatchupCommitRound         int32
	Step                       RoundStepType
	Proposal                   bool
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/internal/consensus/types/round_state.go:67:17: struct has size 208 (size class 208), could be 192 (size class 192), you'll save 7.69% if you rearrange it to:
struct {
	StartTime                 time.Time
	ProposalReceiveTime       time.Time
	CommitTime                time.Time
	ValidBlockParts           *types.PartSet
	LockedBlockParts          *types.PartSet
	Validators                *types.ValidatorSet
	Proposal                  *types.Proposal
	LastValidators            *types.ValidatorSet
	ProposalBlock             *types.Block
	ProposalBlockParts        *types.PartSet
	LastCommit                *types.VoteSet
	LockedBlock               *types.Block
	Votes                     *HeightVoteSet
	Height                    int64
	ValidBlock                *types.Block
	ValidRound                int32
	CommitRound               int32
	LockedRound               int32
	Round                     int32
	Step                      RoundStepType
	TriggeredTimeoutPrecommit bool
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/internal/p2p/peermanager.go:1421:15: struct has size 88 (size class 96), could be 72 (size class 80), you'll save 16.67% if you rearrange it to:
struct {
	LastConnected time.Time
	ID            types.NodeID
	AddressInfo   map[NodeAddress]*peerAddressInfo
	Height        int64
	MutableScore  int64
	FixedScore    PeerScore
	Persistent    bool
	Inactive      bool
}

/Users/emmanuelodeke/go/src/github.com/tendermint/tendermint/light/provider/http/http.go:52:14: struct has size 24 (size class 24), could be 16 (size class 16), you'll save 33.33% if you rearrange it to:
struct {
	Timeout             time.Duration
	MaxRetryAttempts    uint16
	NoBlockThreshold    uint16
	NoResponseThreshold uint16
}
```

**What you expected to happen**:
No complaints

**Have you tried the latest version**: Yes

**How to reproduce it** (as minimally and precisely as possible):
Please install it per https://github.com/orijtech/structslop#installation

Kindly cc-ing my team @elias-orijtech @kirbyquerby @willpoint

**Comment by creachadair** [comment]
This is an interesting analysis, but I'm not convinced changing these types could save us much.

Many of the types mentioned here (for example, configs, options, and client or server wrappers) are instantiated only once per process, or a small single-digit number of times, so the memory footprint of their layout simply does not matter. It'd be harmless to change them, but would not have much practical benefit.

Some other cases from the list:

- `peerInfo` is more numerous, though probably not numerous enough to worry about: A node typically caps peers at ~100 so the total available memory savings is probably less than 1 KiB.

- It might be worth investigating whether `PartSet` is common enough to have an impact. Generally part sets are stored on disk and only held in memory during block commit and sync. I'd be surprised if we ever get more than a few hundred of those in-memory at a time, but these at least have some potential to save more space. That said: Given that these are all encoded as protocol buffers, the overhead of marshaling and unmarshaling is likely to dwarf any gain or loss to be had from the layout. We'd also need to take extra care here to avoid perturbing any hash computations, as such changes would be protocol breaking.

- It might also be worth investigating whether `RoundState` is common enough to have an impact. My intuition is probably not, I think it's somewhat uncommon for consensus rounds to exceed even 10.

If we're observing specific memory pressure problems, I suspect we'd probably get more return for an investment of our effort on cleaning up allocation patterns in specific hotspots in the implementation. That said, I've generally found that works better starting from profile traces rather than static analysis, as much of Tendermint's memory use depends a lot on workload.

**Comment by ValarDragon** [comment]
I generally think struct field re-arrangement isn't good a use of time/energy for code non-systems code, and shouldn't be something considered when ordering elements. (All focus wrt order should be on code readability)

None of the above realistically is going to have impact, we'd have to consider pathalogical scenarios to get 1MB of RAM savings, whereas RAM overheads are in the gigabytes for consumers of Tendermint.

**Comment by odeke-em** [comment]
Thanks everyone for the discourse @creachadair and @ValarDragon! Great thoughts and arguments presented. Indeed, this is low hanging fruit. 

>None of the above realistically is going to have impact

@ValarDragon am not sure about this conclusion, without having done tests on objects in RAM! It's also low hanging fruit but much later on if we really want to tune and save RAM, these will come into consideration.

>If we're observing specific memory pressure problems, I suspect we'd probably get more return for an investment of our effort on cleaning up allocation patterns in specific hotspots in the implementation. That said, I've generally found that works better starting from profile traces rather than static analysis, as much of Tendermint's memory use depends a lot on workload.

@creachadair yup yup, indeed this is what we've always done for performance improvements in which we do profiling guided improvements. This issue was filed because of a static analyzer we wrote which can help indiscriminately reduce the size of your structs so that you don't have to spend 10s to 100s of hours and focus just to jump back to the conclusion that some structs are big, also this is a kind of thing and calculation that 99.99% of people never do as it requires going over every single struct field and finding optimal arrangements, most people gloss over it.


@ebuchman presented a very important thought which is that changing struct arrangement directly affects consensus and might be tricky to change structs. As also @ValarDragon mentioned, we can spend more time on objects in RAM.
Anyways I opened this issue and now y'all aware about structslop, if later on with fresh projects y'all want to ensure structs are optimal and you can by default conserve your RAM, then turn it on. I shall close this isssue and thanks again everyone!
