### ISSUE TITLE
Take EventSwitch as argument to NewNode to allow caller access to event firehose

### ISSUE THREAD

**Issue by silasdavis** [tendermint/tendermint#886]
Another inversion of control request from me :)

I'd like to be able to create an event firehose from Tendermint. Currently I can get the `EventSwitch` used by `Node`, but to get all events I would have to subscribe to every event. My use case is for a firehose of events where I don't necessarily know what is interesting until later on (e.g. analytics). It would be useful if I was able to pass in an `EventSwitch` implementation so that I can capture events in an arbitrary way. This would also allow for different implementations of `EventSwitch` to be provided by the caller such as a persistent event switch or one that maintains a buffer. I note that allowing us to set the `EventSwitich` after `Node` would not provide the same functionality since we would need to have access to the switch being passed here:

https://github.com/tendermint/tendermint/blob/master/node/node.go#L285 

Now I realise this would also allow you to break Tendermint, but I think that if we are calling `NewNode` we are already interacting with Tendermint in a more tightly couple was so probably okay to add it as an argument their in analogy to the `privValidator`, `genesisDocProvider` arguments already there. However if you prefer to add it to a `NewCustomNode` or similar that would work for me and I can see the rationale. There is a question of where this ends, personally I think that it would be A Good Thing to be able to pass in implementations for any interfaces otherwise instantiated in `NewNode`. We are pretty close to that as it is, and very fine it is too...

**Comment by melekes** [comment]
Have you seen the new pubsub? It's on develop. You can subscribe to all events by calling `err := eventHub.Subscribe(ctx, "analytics", "", out)`.

**Comment by silasdavis** [comment]
Looks good, I like the command architecture rather than all the locks big improvement! And the peg grammar for queries. I think it would be better if you provided a suitable interface that `EventBus` implements (like `EventSwitch` had been made an interface) so that an alternative could be provided to blockchain and consensus reactors. I appreciate it is an internal class but still, better to be open to extension on inputs.

Also just to be clear I don't see a `Subscribe` with the signature above, do you mean:

```go
err := eventBus.Subscribe(ctx, "analytics", query.New(""), out)
```

That would give me a catch all subscription?

**Comment by melekes** [comment]
> I think it would be better if you provided a suitable interface that EventBus implements (like EventSwitch had been made an interface) so that an alternative could be provided to blockchain and consensus reactors. I appreciate it is an internal class but still, better to be open to extension on inputs.

this can be done, yes. good thing to do probably.

> That would give me a catch all subscription?

yes
