### ISSUE TITLE
Define standards for spec files

### ISSUE THREAD

**Issue by cason** [tendermint/tendermint#8879]
As we have more people involved in writing and updating Tendermint specs, I would suggest the definition of some standards for them.

Now, we have [Contibuting](https://github.com/tendermint/tendermint/tree/master/spec#contibuting) section (with a typo) on the `spec/` directory of the repository, that is very minimal, and points to the need of opening a RFC for spec changes.

I would suggest creating a `CONTRIBUTING.MD` file or something similar to the [`docs/DOCS_README.md`](https://github.com/tendermint/tendermint/blob/master/docs/DOCS_README.md) file.

In terms of content, the intent of opening this issue is to collect suggestions and agree in some standards.

**Comment by cason** [comment]
To kick it off, I would suggest establishing a maximum length for lines in MD files as, in @sergio-mena words, "long lines that hinder diffs".

**Comment by sergio-mena** [comment]
Thanks @cason for the initiative. I've been using 100 characters, as a good compromise. But I understand it's a somewhat arbitrary figure, so I'm open to other possibilities.

**Comment by mark-rushakoff** [comment]
I've been following the [semantic line feeds](https://rhodesmill.org/brandon/2012/one-sentence-per-line/) pattern for years and it has worked out very well in regards to understandable diffs and readable text.

There is a somewhat newer [Semantic Line Breaks specification](https://sembr.org/) that suggests a maximum line length of 80 characters. I find 80 characters to be restrictively short; 100 or 110 gives more leeway around not orphaning a single word on a line just to fit in an arbitrary, short line length.

**Comment by cason** [comment]
I agree. As a Vim user, I tend to break lines on 80 chars, but I'm flexible when editing/changing up to 100 and something. This allows changes within a line to be better tracked than always breaking lines at 80.

**Comment by sergio-mena** [comment]
I've been working on a 100 limit for years. To us it was the best tradeoff between line length, possibility of side-by-side diff even in a laptop screen, and readability of diffs
