### ISSUE TITLE
in rpc/http/client when unsubscribing, close the channel before deleting the wsSubscription

### ISSUE THREAD

**Issue by lightyear15** [tendermint/tendermint#8887]
https://github.com/tendermint/tendermint/blob/27ff2f46b8b5d54c986228a84edd053b2809c7aa/rpc/client/http/ws.go#L114

I am testing with tendermint version 0.35.7, but I don't see big differences with current master version.
I think the expected behaviour of the client when dealing with websocket and even subscription is that ``client.Unsubscribe`` and ``client.UnsubscribeAll`` should close all the currently open channels before destroying any reference to them by calling ``delete`` on the map structure stored in ``wsEvents``.

here is an example code that shows that the application never exits gracefully

```go
package main
import (
	"context"
	"fmt"
	"sync"
	"time"
	rpchttp "github.com/tendermint/tendermint/rpc/client/http"
	"github.com/tendermint/tendermint/rpc/coretypes"
)
const subscriber = "test-subscriber"
func main() {
	client, err := rpchttp.New("tcp://<ip-address>:26657")
	if err != nil {
		fmt.Println("error in rpchttp.New", err)
		return
	}
	err = client.Start()
	if err != nil {
		fmt.Println("error in client.Start", err)
		return
	}
    ctx := context.Background()
	_, err = client.Health(ctx)
	if err != nil {
		fmt.Println("error in client.Health", err)
		return
	}
    status, err := client.Status(ctx)
	if err != nil {
		fmt.Println("error in client.Status", err)
		return
	}
	query := "tm.event = 'NewBlock'"
	txs, err := client.Subscribe(ctx, subscriber, query)
	if err != nil {
		fmt.Println("error in client.Subscribe", err)
		return
	}
    isRunning := client.IsRunning()
    fmt.Println("client.IsRunning", isRunning)
    wg := new(sync.WaitGroup)
    wg.Add(1)
	go printOut(txs, wg)
	time.Sleep(5 * time.Second)
	fmt.Println("stopping the client")
    err = client.UnsubscribeAll(ctx, subscriber)
    if err != nil {
        fmt.Println("error in client.UnsubscribeAll", err)
    }
	err = client.Stop()
    if err != nil {
        fmt.Println("error in client.Stop", err)
    }
	err = client.Stop()
	wg.Wait()
}
func printOut(out <-chan coretypes.ResultEvent, wg *sync.WaitGroup) {
    defer wg.Done()
    fmt.Println("starting printOut")
	for event := range out {
		fmt.Println(event)
	}
    fmt.Println("exiting printOut")
}
```

**Comment by creachadair** [comment]
Unfortunately, the subscriber implementation depends on the assumption that the channel for a subscriber is never closed. The design is unfortunate, but is pretty deeply baked into both the  subscriber plumbing and the RPC handlers for subscription. The caller should not assume a subscriber will close, even if Unsubscribe has succeeded: After unsubscribing, the caller should "give up" on waiting for more results. One way to manage that is by plumbing in a context. Using your example, for instance:

```go
func printOut(ctx context.Context, out <-chan coretypes.ResultEvent, wg *sync.WaitGroup) {
   select {
   case <-ctx.Done():
      return
   case evt := <-out:
      fmt.Println(evt)
   }
}

// ...
txs, err := client.Subscribe(ctx, subscriber, query)
// ...
stop, cancel := context.WithCancel(ctx)
defer cancel()

wg.Add(1)
go printOut(stop, txs, wg)
```

or words to that effect.

Starting with Tendermint v0.36, we're adding a new and easier-to-program events API based on [ADR 075](https://tinyurl.com/adr075), that will replace the websocket subscription API entirely in later versions. For now, I recommend working around this limitation in the existing API. Changing this basic an assumption of the API is possible, but would expose a _large_ volume of existing use to risk of breakage.

**Comment by lightyear15** [comment]
thanks for your answer.
In the proposal for the new event API, I don't see an example of a client connecting to the service and waiting for receiving events.
I agree that is really unfortunate that the initial design overlooked this important step of closing the channel when client requests to unsubscribe from an event, or simply stops the service.

Closing the issue

**Comment by creachadair** [comment]
> In the proposal for the new event API, I don't see an example of a client connecting to the service and waiting for receiving events.

The ADR 075 API is based on long polling instead of a blocking stream. In the v0.36.x branch (as well as in master), there's a [client library](https://github.com/tendermint/tendermint/blob/v0.36.x/rpc/client/eventstream/eventstream.go) that adapts the basic /events interface to a callback-style interface.
