### ISSUE TITLE
Error when building the tm-bench code

### ISSUE THREAD

**Issue by Ajita24** [tendermint/tendermint#889]
I wanted to make some changes in tm-bench code. The change simply involved changing the transaction size from 250 to 350 in file
https://github.com/tendermint/tools/blob/master/tm-bench/transacter.go#L30

After making just this small change I tried to build the tm-bench with command make build. But encountered error as shown in screenshot- https://www.screencast.com/t/XN4664FaPN
			
When I went through the commits it seems that now "ResultsCh" has been replaced by "ResponsesCh" mentioned in commit-			
https://github.com/tendermint/tendermint/commit/f6adddb4a8e611c2c7d1f8ca64266bda6674e330#diff-a969276db2d519208a2bf7aa9447acf6L321

But the tm-bench code still doesn't seems to be updated.
Please provide some insight as to how to fix this problem.
Please guide.

**Comment by zramsay** [comment]
it should work if you run `make get_vendor_deps` before `make build`. if it doesn't, we'll need to update the pinned tendermint version here: https://github.com/tendermint/tools/blob/master/tm-bench/glide.yaml#L10 ... which we should do anyway

**Comment by melekes** [comment]
`make get_vendor_deps` should solve this. Feel free to reopen this issue or better create an issue in https://github.com/tendermint/tools if that's not the case.

**Comment by yassersheikh** [comment]
I have tried with _make get_vendor_deps_ but getting the same error on building the command.

**Comment by melekes** [comment]
Try cleaning up deps you've checked out before:

```
rm -rf $GOPATH/src/github.com/tendermint/tools/tm-monitor
...
```

They might conflict with glide dependencies (glide downloads all the deps to /vendor dir)
