### ISSUE TITLE
blocksync not enabled can block peer updates

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#8899]
Version: v0.35.x

At the moment, the node setup code calls the Subscribe() method on the peerUpdates type for each reactor it creates. This call registers a subscriber that is serviced by the `PeerManager`.
https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/node/setup.go#L358

The `PeerManager` always expects to be able to write to the subscription and does so in a blocking fashion under a mutex. This can cause an issue when the reactor is constructed but not started. If the reactor is not started then the subscription does not get read and can back up the p2p manager. If blocksync is not enabled, this channel not be read. 

A fix was implemented for this in v0.36. The fix passes through a function callback that is used when the type is started. A similar approach should be taken with v0.35.x
The fix was implemented in v0.36 here: 9d1e8eaad46e78d6c9d1caf912ab181c11a780c6

**Comment by tychoish** [comment]
I believe in 0.36, (and possibly also in 0.35, though clearly ) it's not possible to run a Tendermint node without blocksync enabled. The referenced change is a huge, mostly orthogonal plumbing change, and I think it would be reasonable to: 
- disable the construction of the blocksync reactor (and therefore the subscription) unless its enabled,
- disallow allowing tendermint nodes to start without blocksync enabled.

Frankly I thought the second option was the case even in 0.35, but would be curious to see if that's not the case.

**Comment by williambanfield** [comment]
@tychoish Tried with the change applied and it can still block peer acquisition.

**Comment by tychoish** [comment]
https://github.com/tendermint/tendermint/pull/8912/files#diff-375d57e386f20eaa5f09f02bb9d28bfc48ac3dca18d0325f59492208219e5618L225 should do it in 0.35 but I'm not sure why the e2e test is failing. 

Will continue to dig in, but putting this a bit lower on the stack, as it's a sharp corner for UX.
