### ISSUE TITLE
mempool: Mempool should have a CloseWAL method

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#890]
I have been trying to fuzz `mempool` but all my crashers were just false positives because of resource exhaustion e.g `too many open files`, `timed out` etc.

I noticed that underlying we have a WAL whose type is `tmlibs/autofile.AutoFile` https://github.com/tendermint/tendermint/blob/128e2a1d9e88eeb0aa7645973940b23eb7a14803/mempool/mempool.go#L120-L124
which however, just listens for SIGHUP
https://github.com/tendermint/tmlibs/blob/master/autofile/sighup_watcher.go#L22-L29

which won't invoke a closeAll for all other exits except when you destroy the terminal itself.
I raised the signal listening offline in one of the engineering channels, but that's another discussion.

It would be nice for programs that use the WAL to close it after use. This way normal usage won't leave files open.

**Comment by melekes** [comment]
```
// consensus/state.go#267
func (cs *ConsensusState) OnStop() {
...
	// Make BaseService.Wait() wait until cs.wal.Wait()
	if cs.IsRunning() {
		cs.wal.Wait()
	}
```

`Close` or `Start/Stop` by analogy with other services using autofile (e.g. consensus/state)

**Comment by odeke-em** [comment]
Nice, thanks for the suggestion to instead use `Stop`, consistent with our other APIs. I'll update the title to reflect this.

**Comment by melekes** [comment]
Re signals: I think we should add 

```
signal.Notify(c, syscall.SIGTERM)
signal.Notify(c, syscall.SIGINT)
```

**Comment by odeke-em** [comment]
@melekes 100% agree, syscall.SIGQUIT too :), but could we also mention this in the engineering channel for consensus or actually a Github issue on `tmlibs`?

**Comment by melekes** [comment]
```
The SIGQUIT signal is sent when the user at the controlling terminal presses the quit character, which by default is ^\ (Control-Backslash)
```
https://golang.org/pkg/os/signal/

this is not a standard practice to include SIGQUIT. I think it's better without it. Besides who stops programs like this when we have Ctrl-C
