### ISSUE TITLE
MConn close causes longer consensus

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#8903]
Version: v0.35.x with non-legacy p2p stack

### Problem Statement

It was observed by @evan-forbes that firing the event when adding a vote in consensus can take a very long time to complete.
https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/consensus/state.go#L2076

This event type is only listened for in one place, the consensus reactor. The event switch is a synchronous bus that immediately invokes all registered callbacks.
https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/consensus/reactor.go#L426

The consensus reactor callback quickly puts the vote onto the p2p channel and returns. However, this p2p send can block if a single peer is slow or disconnecting. The channel that is sent on is serviced by a routine in the router. In this routine, the router listens on the channel. For each broadcast message [the router gathers all of the outgoing peer queues](https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/p2p/router.go#L440) and attempts, in serial, to [write to each of them](https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/p2p/router.go#L488). 

The peer queues read from the channel and attempt to write to the `MConn` via a call to [sendBytes](https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/p2p/conn/connection.go#L803). This function is a simple select statement between a write to an unbuffered channel and a timeout channel. If the `MConn` is shutting down or blocking, the call waits the entirity of the 10 second timeout before returning to the peer queues and eventually percolating back up to the router which is then free to continuing writing to the next queue.

### How did legacy p2p solve this problem?

Legacy p2p created a new go routine per message per peer. I.e. every time a new message was being sent, it looped over all of the peers and created a new go routine for each. It solved our queuing problem by effectively using an unbounded queue.
https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/p2p/switch.go#L313

### Options and solutions

As a first change, we should update the `sendBytes` call to also select across the mconn state; if it is closed then we should fail the send call as soon as we discover that it is closed.

As far as I can tell there are a few options for dealing with the remaining issue of what to do when the mconn is slow but not shutdown. We still need to prevent some amount of head-of-line blocking so that consensus can continue.

#### Option 1:
 Drop Messages when p2p channel buffer is full. While the `MConn` timeout is being reached, the consensus reactor will continue to try to put messages onto the peer queues. Once a peer queue is full, we can either drop messages to that peer or stall all of consensus until they are able to be sent.

#### Option 2: 
Increase the buffer size. The legacy p2p system created an unbounded queue. The new p2p attempts to not have an unbounded amount of resource use, but a very large value should be fine. The large value would need to buffer messages while the mconn timeout is being reached.

#### Option 3:
Decrease the `MConn` timeout. The timeout is 10 seconds. Perhaps this value is too large and should be considered for diminution.

#### Option 4:
Create a channel send worker pool. Currently, the router writes to all of the peer queues, one by one, in serial:
https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/p2p/router.go#L484
It is usually the case that one or two peers max are being disconnected at any one moment. Creating a worker pool to handle the queue sends would avoid any head-of-line-blocking. Only one or two of the workers would be tied up at any moment while the others would be able to be sent to. The disconnecting queue would simply take a worker away instead of stalling all sends.

### How was this determined

The MConn timeout was determined to be the issue by adding timing metrics to the validator running on the celestia testnet. A metric was added for how much time it took to put messages into the peer channel. This metric spiked to many seconds from time to time.

A metric was then added to time the operation of the only reader of this channel in [router.go](https://github.com/tendermint/tendermint/blob/978f754ad3f928d5e067bf13037759affa911e3c/internal/p2p/router.go#L958). This new metric revealed that sending to the MConn could occasionally take multiple seconds, usually ten or more in the degenerate case.
The following images show the time for the channel to enqueue a message in the first image and the time to write the message into the mconnection in the second image. A fix was applied to drop messages when the queue is full which explains why the mconn sends register as slow slow after the peer queue sends cease taking upwards of 10 seconds.
![image](https://user-images.githubusercontent.com/4561443/176550627-1d7c057d-dcff-477d-a543-336c63c1eaec.png)
![image](https://user-images.githubusercontent.com/4561443/176551360-240b17e0-de09-45e1-baf0-6eeb87304bcf.png)

**Comment by tychoish** [comment]
This is perhaps a different problem, and maybe kind of an absurd suggestion, but could we eliminate the event and/or send the event outside of the critical section?

**Comment by williambanfield** [comment]
> This is perhaps a different problem, and maybe kind of an absurd suggestion, but could we eliminate the event and/or send the event outside of the critical section?

This wouldn't really solve the problem. The issue is that nodes are unable to send their votes at all because the send routine gets blocked on a single slow/broken connection. We could get the send out of the critical section and have a separate routine read off what to send. This may unblock consensus but it doesn't solve the issue of votes not being sent. The slow or stuck connection will still head-of-line block when the votes eventually do get sent.

**Comment by williambanfield** [comment]
As of now, the proposed solution is to do the following:

1. Increase the internal queue sizes. These queues were unbounded in v0.34.x. A very large value should be safe and no worse than the previous implementation's functionality.
2. Never block writers in the load-shedding queue. Currently, the `pqueue` has one routine to service the read end and the write end of the queue, alternating between the two.[ If the write end becomes blocked waiting on the mconn](https://github.com/tendermint/tendermint/blob/6d8079559baaf7428e16e504134ceb4e1e9d37db/internal/p2p/pqueue.go#L261), the read end will stall and writers will not be able to add work items to the queue. We should not do this. We should instead properly shed load in the case that the queue is unable to write messages onto the wire.

These two changes will ensure that we don't block writers to the queue but that we instead drop messages and it will ensure that when we drop very few messages due to the upgraded size of the queues.

**Comment by cason** [comment]
Just to recall that votes are not sent by this procedure, but a node broadcast a `HasVoteMessage` to all peers. This "gossip-level" message is not required for correctness, its only point is to prevent peers to send me a vote that I already have (i.e., reduce duplication).

For the above mentioned reasons, (i) we can drop this message when buffers are full or sending is slow, and (ii) we need to find another method (not synchronous) for triggering the sending of such control messages.

**Comment by williambanfield** [comment]
#8929 aims to fix this issue. The change fixes the issue by adding a queue that more effectively drops load when disconnecting a peer.
