### ISSUE TITLE
couldn't connect to seed nodes

### ISSUE THREAD

**Issue by Sandeep-Narahari** [tendermint/tendermint#8938]
(Local network)
node1===>>>Validator node or main node ,duplicate ip=true

node2===>>>(getting this is not a validator )seed node, seed mode=true, persistent peer="node1id@127.0.0.1:26656",duplicate ip=true

node3===>>new node adding through seed node [,,,seed="node2id@127.0.0.1:26656",]([url](![Screenshot from 2022-07-05 16-22-57](https://user-images.githubusercontent.com/46187761/177313010-e5126108-548f-4574-be4e-7f59ec55e3bd.png))) duplicate ip=true

why it is unable 3rd node is unable to connect to node 2 seed node?

**Comment by cmwaters** [comment]
Hey @Sandeep-Narahari, at a glance, this looks like you've used an incorrect node ID for the seed node in the config.toml file which is causing the error in the handshake when the node tried to dial the seed node

**Comment by Sandeep-Narahari** [comment]
Nope I have used the seed node I'd
