### ISSUE TITLE
vagrant setup and tendermint compilation

### ISSUE THREAD

**Issue by wighawag** [tendermint/tendermint#894]
BUG REPORT

**Tendermint version** ae67408d138a95f82ffd55b6209475f4c51634dd

**Environment**:
- **OS** Windows 10 , vagrant

**What happened**:

Upon executing vagrant up followed by vagrant ssh

I executed
 ```
cd /vagrant/
make
```

I got the following error :
```
cmd/tendermint/main.go:6:2: cannot find package "github.com/tendermint/tmlibs/cli" in any of:
        /usr/local/go/src/github.com/tendermint/tmlibs/cli (from $GOROOT)
        /home/vagrant/go/src/github.com/tendermint/tmlibs/cli (from $GOPATH)
make: *** [install] Error 1
```

I then executed :
```
go get github.com/tendermint/tmlibs/cli
make
```

This It got  the following error :

```
go install: no install location for directory /vagrant/cmd/tendermint outside GOPATH
        For more details see: 'go help gopath'
make: *** [install] Error 1
```

**What you expected to happen**:
I expected vagrant to be setup to start compiling tendermint.
should we execute ```make``` ?

**How to reproduce it** (as minimally and precisely as possible):
```
vagrant up
vagrant ssh
cd /vagrant
make
```

the second error can be seen after executing the following

```
go get github.com/tendermint/tmlibs/cli
make
```

**Comment by melekes** [comment]
mm, you need to `cd ~/go/src/github.com/tendermint/tendermint`

**Comment by wighawag** [comment]
cool, thanks
