### ISSUE TITLE
statesync: p2p state provider is overwritten

### ISSUE THREAD

**Issue by jmalicevic** [tendermint/tendermint#8940]
**Tendermint version** 
v0.36 and master

**What happened**:
When the state provider for statesync is configured to be p2p, it is overwritten in the `[OnStart](https://informalsystems.slack.com/archives/CU7FB7KEZ/p1657026466238459?thread_ts=1656359019.919879&cid=CU7FB7KEZ)` function of the reactor.

**Comment by cmwaters** [comment]
Overwritten by the RPC state provider?

**Comment by jmalicevic** [comment]
It is not, I missed the return statement if the provider is p2p.
