### ISSUE TITLE
Optimize ABCI Response Information stored as part of state.db to validate latest height

### ISSUE THREAD

**Issue by moniya12** [tendermint/tendermint#8946]
## Summary

Currently COSMOS-SDK store ABCI Information in state.db ( on disk) at every commit. Purpose of storing ABCI information is to compare when new commit comes and validate new commit is at least one height above existing ABCI Response information. 

While to compare, we just need ABCI Information for one previous block, cosmos-sdk continues to store all blocks and never deletes them. As a result state.db is bloated, turning state.db in 100s of GB (95% of data is ABCI Information) and also increasing latency. 

Store ABCI Response information in optimized manner and delete everything above 100 or 1000 blocks. Currently state.db ABCI Response information pruning is handled with same configuration for blockstore.db and application.db. High volume chains (Osmosis as an example) produce 10s of transactions per block, and so state.db bloat exponentially. 

We need mechanism where older ABCI information is deleted from state.db every time new block is committed. Basically we store ABCI Information in separate DB and delete ABCI Information of block H1 when H1+100 is committed. 

Code: 

1) Tendermint saves ABCI Response Information to State.db - Tendermint saves ABCI Response before commit - https://github.com/tendermint/tendermint/blob/0cceadf4d4c5acf9d390f22616b80070fece52d4/internal/state/execution.go#L233  

It is not deleted until pruning configuration deletes it. Pruning configuration honors bonding period, so state.db is not deleted until for bonding period (2-4 weeks). At that point LevelDB is bloated, with multiple levels, and disk space is never reclaimed. (Info on LevelDB Deletion: https://twitter.com/valnodes/status/1435465250803945472) 

2) Merkle Tree Verification never goes beyond 100 aunts: https://github.com/tendermint/tendermint/blob/3d448e1ef83685857b12c6ca94162097916c3402/crypto/merkle/proof.go#L16

## Problem Definition

I do not see any, but would like to discuss use-case where one want to get merkle proof at height 1. 
## Proposal

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
This overlaps with https://github.com/tendermint/tendermint/issues/8028.

We've discussed this problem in a few calls but thanks for bringing it up again. It's important in determining how much of a priority this should be. As of now, we're pretty confident that we can have a clean solution in v0.36 (which would change the crash semantics). We may also be able to add something to the config that validators can opt into which would only store the last ABCI response for v0.34 and v0.35

**Comment by moniya12** [comment]
@cmwaters Thanks! 

LMK if you would like to discuss over here or in #8028. 

If we can push change where we just store last block ABCI Response we would have tremendous progress. Key thing over here would be where to store that value, we can't store last height and delete earlier one as LevelDB will not make it easy to reclaim space. If we store with same key "LastHeight" or something like that, it would over writing (it still creates new entry for each update but cleans them during updates with right configuration). 

Obviously, one has to think through how do we handle merkle proof if one wants to do it.

**Comment by cmwaters** [comment]
Yeah we will backport it v0.34 when we make the patch

**Comment by williambanfield** [comment]
closing with the completion of #9090
