### ISSUE TITLE
docs: Architecture as-is

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#8975]
This is something we've previously spoken about synchronously in the team, but I thought I'd capture it here as a TODO item.

While the RFC and ADR processes are useful in terms of capturing significant deliberations and decisions over time, we don't have any documentation for the current system architecture as it is right now. Even reading through all of the ADRs over time doesn't give one this picture, and it's actually more difficult to establish a clear as-is picture by doing so than just reading the code itself.

This is very important to newcomers to the codebase. Just recently we've had several conversations with people who are currently onboarding who ask for a clear entrypoint into the codebase (beyond the user-facing documentation) and we can't really give them one.

### Definition of done
A single-page, high-level architecture doc with bullet points describing the main components that make up a Tendermint node, ideally linking to specific code, would be sufficient for now. This document would need to be updated over time as major system components evolve.

A stretch goal here would be to start to capture some sense of the system concurrency model.

**Comment by cmwaters** [comment]
I think this would be very useful. Just to clarify further, would this be in a separate section to the spec?

**Comment by thanethomson** [comment]
> would this be in a separate section to the spec?

Yes. I'd recommend something easily accessible from the root of the [`docs` folder](https://github.com/tendermint/tendermint/tree/master/docs), but I'm not personally too fussy about where or how.
