### ISSUE TITLE
Fetch TX metadata for all TXs in a block

### ISSUE THREAD

**Issue by pdobacz** [tendermint/tendermint#905]
**FEATURE REQUEST**

- Describe *in detail* the feature/behavior/change you'd like to see.

Currently, a call to Tendermint RPC `block` returns a field `"data"` and `"txs"` therein. There is a list of transactions there - i.e. each transaction in its entirety (the tx bytes). OTOH, there's no easy access to transactions metadata

Alternatives to consider:
  - returning just hashes of the txs (to let the user use the `tx` endpoint for details) or
  - adding some metadata to this field, so that after a call to `block` we can get all info we need about a all transactions in a block. Metadata that comes to my mind is `tx_hash`, `code`, `log`, `data`, as persisted in Tendermints tx storage.

Possibly, getting this behavior could be achieved by splitting the `block(height)` endpoint into `block(height)` and `block_transactions(height)`, with distinct purposes. Not sure here.

Other point to have in mind is (by @adrianbrink):
> (...) a call to block might return 1000 transactions, a large amount of data

**Tendermint version**
`0.10.3`

**Comment by ebuchman** [comment]
@ethanfrey what are your thoughts here ?

**Comment by adrianbrink** [comment]
@melekes Does indexing solve this use case?

**Comment by ethanfrey** [comment]
If by TX Metadata, you mean the TX hash, code, and data, then that is considered the TX result. If a TX is included in block h, that data is available in block h+1 (as of 0.14 or 0.15)

There should be a results endpoint that returns this info, which can be verified by checking against the results hash in the header. 

I am not sure (must check code) if the TX hash is included, but I think not, we just use indexes, such that results[5] on h+1 corresponds to data[5] on h.

If someone reviews current state, it should not be hard to make a concrete proposal of a minor adjustment that should support this. 

Is it acceptable to query data and results?

**Comment by melekes** [comment]
`/block_results?height=X`

> I am not sure (must check code) if the TX hash is included

no

**Comment by pdobacz** [comment]
Thanks everyone for your feedback and apologies for me going silent for a moment.

I'm still mulling this over, in terms of requirements, meanwhile, two helper questions:

First helper question:

> `/block_results?height=X`
is that implemented, planned or are you just suggesting a solution in the RPC, it's not entirely clear to me. E.g. it's not in here https://tendermint.readthedocs.io/en/master/specification/rpc.html#endpoints

Second helper question is this - with the current implemented RPC, what would be the easiest way to iterate through all transactions for a given `height`, getting all the results that are available through the `tx` endpoint.

@melekes ?

**Comment by melekes** [comment]
Yeah, we might have forgotten to add it to routes. It is implemented: https://github.com/tendermint/tendermint/blob/master/rpc/core/blocks.go#L299

No, if you want all results you should use `/block_results` as it fetches block from blockstore only once. Plus `/tx` endpoint requires indexer to be enabled.
