### ISSUE TITLE
Short-term data storage improvements

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9054]
Tracking issue for 2022 Q3 work on storage optimization.

- [x] #8946 
  - [x] Validate the extent to which this reduces node storage needs, while still ensuring correctness
  - [x] #9274 
  - [x] Port https://github.com/tendermint/tendermint/pull/9090 to `main`

**Comment by marbar3778** [comment]
Is this a tracking issue for abci responses or storage improvements in general? I think there are a few more things people could add in for storage improvements

**Comment by thanethomson** [comment]
It's purely all work related to the Council's Q3 priorities. The issue's still a WIP.

**Comment by cmwaters** [comment]
We ran two osmosis nodes. One with a modified binary that used the v0.34.x branch (which discards ABCI responses and only stores the last for crash recovery purposes) and the other that used v0.34.19. After about 18 hours of usage from a quick sync snapshot here is the disk usage:

**Regular Node**
```
1.9G	./data/state.db
1.1G	./data/blockstore.db
```
**Modified Node**
```
176M	./data/state.db
1.1G	./data/blockstore.db
```
cc: @ValarDragon

**Comment by ValarDragon** [comment]
Amazing!! Thanks for making this happen!

**Comment by thanethomson** [comment]
Seems like we can mark this as done now.
