### ISSUE TITLE
unable to get nodes (two machines) to pair up

### ISSUE THREAD

**Issue by sparkspeedy** [tendermint/tendermint#906]
I have got the following genesis file in two machines on the same  network:
`
{"genesis_time":"0001-01-01T00:00:00Z","chain_id":"test-chain-1zvnTr","validators":[{"pub_key":{"type":"ed25519","data":"58AB4B36BAB4B67E99F127EB21F0F1A5816A9B62EBCE1D6A4261613CDF4D64CE"},"power":10,"name":""},{"pub_key":{"type":"ed25519","data":"C0A80EA91ACAB36CB25F8174A6847CF33A7B70F94D53D23599DCD5889D96A04A"},"power":10,"name":""}],"app_hash":""}`

I run tendermint using the following command on both the machines to pair them up:

`tendermint node --p2p.seeds "192.168.1.100:46656,192.168.1.105:46656"`

All I see is both the nodes connecting to the abci-cli:

```
Retrying... module=abci-client connection=query
E[11-29|16:52:49.153] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
E[11-29|16:52:52.153] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
E[11-29|16:52:55.154] abci.socketClient failed to connect to tcp://127.0.0.1:46658.  Retrying... module=abci-client connection=query
```

How do I get the nodes to pair up? Is it necessary for an application run on abcli to do that?

**Comment by melekes** [comment]
The ABCI application must be running and listening for TCP connections on port` 46658`.

**Comment by ebuchman** [comment]
You either need to run an abci app separately on each machine or use `--proxy_app=dummy` in the `tendermint` command to just use the in-process dummy app
