### ISSUE TITLE
Indexing txs (bonus parts)

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#907]
Refs #835 

- [x] rewrite indexing service to index a batch of transactions (it could subscribe to block headers to find out when blocks start and how many txs they have, then wait for those txs and batch the writes.
TODO: add a note One day we can have this IndexerService run many go-routines to do the indexing in parallel.)
- [ ] benchmark kvIndexer#Search
- ~~DO WE NEED THIS? `if i wanted to index txs the hit my account I might do account=deadbeef but if I want to index for all accounts, would I just do account ? we can add pattern-matching like "account.*". I just wanted to get smth simple done. If I am not mistaken, the func we have is enough for UI team.`~~

**Comment by ebuchman** [comment]
- [ ] make `intersect` function in `kv.go` more efficient (https://github.com/tendermint/tendermint/pull/835#discussion_r154272570)

**Comment by melekes** [comment]
The biggest issue right now with indexing is goleveldb perfomance decline https://github.com/tendermint/tendermint/issues/1835

**Comment by jackzampolin** [comment]
cc @ultraeric
