### ISSUE TITLE
Short-term monitoring/logging improvements

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9076]
It must be easy to profile/understand “what is my node currently doing?”, and "where my bandwidth is going?"

- [x] #8752
  - This is "trivially" done as the filtering was removed in v0.35.x
- [ ] #2600. Solution not clear (see discussion)
  - [ ] Agree on the best tradeoff [Estimation 2 days]
  - [ ] Implementation [Estimation 5 days]
- [ ] Ask node operators/validators what information and/or tools are currently missing in terms of logging/monitoring.
  - Rework this item once we have their answers (list of issues)
- [ ] Audit logging across all packages and determine whether the logs are useful/necessary and whether they're at the correct level (info, debug, error).
  - [ ] Starting point: Reduce P2P logging spam [130 logs, estimation 5 days]
  - Other packages [Estimations proportional to the number of logs]
    - [ ] Consensus, 253 logs
    - [ ] rpc, 90 logs
    - [ ] cmd, 60 logs
    - [ ] light, 51 logs
    - [ ] libs, 49 logs
    - [ ] node, 47 logs
    - [ ] statesync, 46 logs
    - [ ] tools, 36 logs
    - [x] #9920
    - [ ] abci, 33 logs
    - [ ] evidence, 32 logs
    - [ ] mempool, 29 logs
    - [ ] state, 23 logs
    - [ ] other (privval, types,proxy), 33 logs
- [x] Improve Metrics Collection
   - https://github.com/tendermint/tendermint/pull/8488
   - https://github.com/tendermint/tendermint/pull/8479
- [ ] How transactions spread using Mempool and Block parts?
   - Log hash of transactions received at mempool and as block parts to determine the duplication of transaction data. Will be useful in determining gains of in solving #7932
- [x] #9756 
- [ ] #9885

**Comment by sergio-mena** [comment]
```
% git lg -n1
* 20ffe9e10 - (HEAD -> main, origin/main) build(deps): Bump actions/stale from 5 to 6 (#9493) (2022-09-27 15:51:22 +0000) <dependabot[bot]>
%
% for i in $(grep -ri 'logger\.' | cut -d / -f2 | grep -vE '^(\.git|CHANGELOG)' | sort | uniq); do echo -n $i; grep -ri 'logger\.' ./$i | wc -l ; done
abci      33
blocksync      33
cmd      60
consensus     253
docs       7
evidence      32
libs      49
light      51
mempool      29
node      47
p2p     130
privval      19
proxy       7
rpc      90
spec       3
state      23
statesync      46
test      35
tools      36
types       7
```

**Comment by cmwaters** [comment]
I think it might be more helpful  to know how many of those are DEBUG, INFO or ERROR

**Comment by sergio-mena** [comment]
@cmwaters I'm using that output to get a grasp of how much work there is on each top-level dir in order to audit the logging (see the reworked description).
This will (hopefully) allow us to decide which part fits in Q4 (in the case the decision is to keep prioritising this effort in Q4)
