### ISSUE TITLE
Prioritized mempool follow-ups

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9077]
- [x] #9310
      - [Link](https://github.com/tendermint/tendermint/blob/main/docs/architecture/adr-067-mempool-refactor.md) to existing ADR when prioritized mempool was introduced.
- [x] Performance and stability are at least as good as the mempool in v0.34 (no regression).
   - [x] (https://github.com/tendermint/tendermint/pull/8962 ) Backported fixes from 0.35 to 0.34 (v0.34.20). 
   - [x] Benchmark the heap consumption with the backports. 
- [x] Prioritized mempool implemented and tested according to the specification.
    - [x] Ability to provide priority to transactions in CheckTx responses, which deliver transactions to the application in priority-based order.
- [x] Transactions are still gossiped in FIFO order.
- [x] We have a clear answer to the question as to whether we need the prioritized mempool when ABCI++ lands
    - [x] If not we need to remove the `Priority` field from `CheckTx`. This impacts the release of [ABCI++](https://github.com/tendermint/tendermint/issues/9053).

**Comment by williambanfield** [comment]
If Cosmos-SDK  [ADR-60](https://github.com/cosmos/cosmos-sdk/pull/12838) is accepted, it seems quite likely that the prioritized mempool will no longer be needed by the SDK with the advent of ABCI++. We may wish to keep the prioritized mempool so that other users may take advantage of it, but, at the moment, our largest consumer does not appear to need it.

**Comment by williambanfield** [comment]
Profiling was performed and documented [here](https://github.com/tendermint/tendermint/pull/8962#issuecomment-1183309987), is there more profiling we need to do as part of this issue? It's fairly clear that the prioritized mempool, with the backported fixes, does not display the unbounded heap growth present in the original implementation.

**Comment by jmalicevic** [comment]
"Performance and stability are at least as good as the mempool in v0.34 (no regression)." I don't know whether we have other metrics identified that could contribute to this particular section (Transaction throughput for example )? If not, then maybe for now this is sufficient.

**Comment by jmalicevic** [comment]
https://github.com/tendermint/tendermint/issues/9388 is set to deprace the priority mempool.

**Comment by jmalicevic** [comment]
The priority mempool was depracated. Therefore closing this issue.
