### ISSUE TITLE
Release process improvements

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9078]
We should be able to quickly get new Tendermint releases with quality of life wins onto many major Cosmos chains.

- How do our processes need to change to accommodate a more regular release cadence?
- How do we ensure that new Tendermint releases can get absorbed quickly by the Cosmos SDK?

**Comment by marbar3778** [comment]
> How do we ensure that new Tendermint releases can get absorbed quickly by the Cosmos SDK?

Is this for getting it out to users or testing?

**Comment by mark-rushakoff** [comment]
I have https://github.com/tendermint/tendermint/issues/9173 in progress, which is part of this general priority.

**Comment by thanethomson** [comment]
> How do our processes need to change to accommodate a more regular release cadence?

The only type of _regular_ releases we could possibly look into accommodating would be "minor" releases (e.g. v0.34.21 to v0.34.22). Along these lines, we would need to:

1. Change our `CHANGELOG_PENDING` process to accommodate this. Right now this is a very manual process that also involves making changes to `main`, since we try to keep the changelog on `main` up-to-date as the primary source of truth for users.
2. Automate the cutting of releases, if there are any changes on release branches. Here we'd need to decide on a cadence. Weekly or biweekly minor/patch updates shouldn't be too much of a problem.

"Major"/breaking releases suffer from a supply chain problem in that people are hesitant to take them up. It also takes quite a bit of manual work to create a new major release. Our team only has capacity to maintain 3, maybe 4 major/breaking releases, and if people don't upgrade to new versions of Tendermint Core these releases may end up piling up.

> How do we ensure that new Tendermint releases can get absorbed quickly by the Cosmos SDK?

This question actually applies to all Tendermint users, and the answer primarily involves social coordination. Fleshing out our roadmap and keeping it up-to-date will go a long way toward helping sync people's expectations.

**Comment by thanethomson** [comment]
I'll be closing this particular issue for now. Will open follow-up ones with more concrete deliverables as needed.
