### ISSUE TITLE
Bug: per_page limit on the unconfirmed_txs rpc endpoint is returning limit + 1 transactions

### ISSUE THREAD

**Issue by ctrl-Felix** [tendermint/tendermint#9092]
The ``/unconfirmed_txs`` endpoint has a flag ``per_page`` which should return the ``Number of entries per page (max: 100)``: Now the ``per_flag`` param seems to be called ``limit``now.

Now it does return the entered limit + 1. So if I want 100 per page it will return me 101 transactions. The same behaviour applies when using the default and not passing a limit. 31 transactions will be returned. This behaviour appears on the current cosmos and osmosis rpc. 

Example:

https://rpc.cosmos.interbloc.org/unconfirmed_txs
https://rpc.osmosis.interbloc.org/unconfirmed_txs

Return value:
```  
"result": {
    "n_txs": "31",
    "total": "251",
    "total_bytes": "123766"
```

I would assume the problem is that it starts counting at zero and then stops when the limit is reached. The right behaviour would be to stop at limit - 1.

**Comment by cmwaters** [comment]
Thanks for opening the issue @ctrl-Felix. We'll look into this as soon as we can

**Comment by cmwaters** [comment]
The `limit` / `per_page` issue looks to be resolved on master

**Comment by ctrl-Felix** [comment]
> The `limit` / `per_page` issue looks to be resolved on master

So on master limit = 30 means, I get 30 transactions?
And what about the missing page?

**Comment by cmwaters** [comment]
I need to dig a little deeper
