### ISSUE TITLE
Migrate `master` to `main`

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9096]
This is a checklist of all the things we need to do to ensure `main` is up-to-date with `master` in terms of its config, documentation, etc. We should update it as we discover additional tasks.

- [x] #9095 
- [x] Ensure Docker build has been migrated
   - [x] #9170 
- [x] Import documentation and update links from `master` -> `main`
   - [x] #9130 
   - [x] #9115 
      - [x] #9398
      - [x] Ensure that https://docs.tendermint.com/ is generated correctly
      - [x] #9181 (see also [this](https://gist.github.com/williambanfield/3fdd5e2f5e34e0d29bbca7551cf0411f))
   - [x] #9180
   - [x] Ensure spec is up-to-date
   - [x] Update links from `master` to `main`

**Comment by thanethomson** [comment]
> Can we be more specific about what documentation needs to be ported across.

Feel free to edit the issue :slightly_smiling_face:

**Comment by mark-rushakoff** [comment]
There are currently 47 matches reported by git grep -E 'tendermint/(blob|tree)/master'. A plain search-and-replace to switch those to referencing main might be sufficient, but without looking closely, I'm not sure if any of them need to remain referencing master.

**Comment by williambanfield** [comment]
@mark-rushakoff Would you mind throwing a list of matches into a gist so we can track together?

**Comment by mark-rushakoff** [comment]
@williambanfield sure, https://gist.github.com/mark-rushakoff/6093bc92c0e3237b387815ae96e7e157

**Comment by williambanfield** [comment]
Broken markdown links: https://gist.github.com/williambanfield/3fdd5e2f5e34e0d29bbca7551cf0411f
