### ISSUE TITLE
Very small error in docs

### ISSUE THREAD

**Issue by davebryson** [tendermint/tendermint#910]
In `docs/ecosystem.rst` 'py-tendermint' is listed as an ABCI Server. This is incorrect. The actual Python ABCI Server is 'py-abci':  https://github.com/davebryson/py-abci which is also available via pypi.

'py-tendermint' is an ABCI application (framework) that builds on 'py-abci'

**Comment by zramsay** [comment]
see fix in #912

**Comment by davebryson** [comment]
@zramsay  Thanks!
