### ISSUE TITLE
Port #7338 (Performance improvements for the event query API) to main

### ISSUE THREAD

**Issue by mark-rushakoff** [tendermint/tendermint#9111]
Per https://github.com/tendermint/tendermint/pull/9099#issuecomment-1197260981, #7338 has some performance and maintainability improvements over the existing pubsub query API, but due to the event structure change which is not (yet) present on the `main` branch, it is not likely a simple cherry pick.

**Comment by creachadair** [comment]
Saving some context:

The specific API change is that in the v0.34.x line, ABCI event metadata were represented as a map from fully-composed tags to attribute values (in Go, `map[string][]string`). In v0.35.x and later this was changed to a slice of ABCI `Event` protobuf messages, where each item decomposes the tags into a `type` prefix (e.g., "tm") and a slice of key/value `EventAttribute` messages (e.g., "event":"NewBlockHeader").

To manage the port, the matching API would need to be patched to handle the composed format. This isn't a huge change but does affect the query package in ways a simple patch won't mitigate. Notably the test cases will need updating in various ways.

Alternatively the event metadata format changes could instead be backported, but v0.34 is very brittle to minor changes and that will likely be a more risky approach.
