### ISSUE TITLE
Add tags to Begin/Endblock and support subscriptions to them

### ISSUE THREAD

**Issue by t-bast** [tendermint/tendermint#915]
FEATURE REQUEST

Hey guys,

First of all, thanks for all the good work you've done with Tendermint, it's a really great project!
I have a question / feature request about pub-sub events, and I wasn't able to find a good answer in the code.
I currently have my client app subscribed to TMCore's new block events and this is really handy.
But I haven't found a way to fire an event from my ABCI app to the client app (unless I open a dedicated connection between the two).
I'd like to re-use TMCore's pub-sub system and be able to fire such events from my ABCI app and have TMCore forward the event to connected clients. Maybe I have missed something, but it looks like I can't do that right now.
Would it be reasonable to add such a feature? Or do you think it's a bad design and I should have a dedicated connection between my client and my ABCI app? Or do you see another solution?

Note: in my case I'm compiling Tendermint with my ABCI, so they are part of the same process. I can understand that in the general case where Tendermint and the ABCI app are separate processes, this feature might be a bit heavy so I would understand if you just tell me that this is a bad idea :)

Thanks!

**Comment by t-bast** [comment]
Looks like I was in fact not looking at the right place...
This feature is already present and works like a charm, in case others are looking for this here is how it can be done:
  * In your ABCI app, create a client to the Tendermint Core node (either via client.NewLocal or client.NewHTTP)
  * That client object will directly have a FireEvent method
  * You simply need to create a struct implementing events.EventData and you're good to go

Sorry for the noise, hopefully this will be helpful for others!

**Comment by pdobacz** [comment]
@t-bast I'm curious about your use case. Are your events fired per transaction? then you could employ [this](https://github.com/tendermint/tendermint/blob/7682ad9a60162dd17fd6f61aeed7049a8635ac78/state/execution.go#L80), which I assume is an event fired on every delivered Tx. Or are your events fired during some other (i.e. other than `DeliverTx`) call to `ABCI`?

**Comment by t-bast** [comment]
In my case I'd like to fire some events during BeginBlock and Commit, to let the client know about some data that I'm able to compute at that time but won't store in Tendermint itself.

**Comment by t-bast** [comment]
In fact unfortunately the code I shared that uses the FireEvent doesn't work...
It works when I start Tendermint via rpctest.StartTendermint, but it doesn't when I start it normally.

Here is the detail of the issue:
  * My ABCI app is compiled with Tendermint and creates a local client to it via client.NewLocal
  * My ABCI app sends a custom event via FireEvent on this client, with an object of my choosing
  * In rpctest this works fine and TMCore forwards that event to listeners (my UI app for example)
  * With a real Tendermint node, the web socket issues an error because my object doesn't have a registered serializer/deserializer (in types/events.go, it looks like I'm forced to send one of the types of the tmEventDataMapper which I don't have access to)

So my question is:
  * Was it the intention of Tendermint to expose client.FireEvent and allow ABCI apps to fire arbitrary events?
  * If that was the case, is it a bug that only tendermint-registered object types are allowed through that websocket?
  * Or is there a different way of doing what I want to do?

Of course my other option is to directly open another web socket between my app and my ABCI app, but if Tendermint allowed me to re-use the connection that's already there I thought it would be better.

**Comment by pdobacz** [comment]
Maybe an alternative to firing the events using a `client` would be to allow for some collection of events to be fired to be returned from calls to the `ABCI` app, i.e. `Commit`/`EndBlock`/`BeginBlock` etc.?

So e.g. [`EndBlock`](https://github.com/tendermint/abci#endblock) returns `Diffs` and `EventsToFire`

**Comment by ethanfrey** [comment]
There is now (as of 0.13.0 I believe) support for tags on DeliverTx result. This is intended to allow clients outside of tendermint to subscribe to certain transactions (eg. `all token transfers involving account XYZ`). It also optionally supports search with the indexer.

You can add any tag in DeliverTx and it can be read by any rpc client. If you are forking tendermint core (which I do not advise unless really needed), you can read them and call fire event. I would suggest using tags to index them so you can filter, and returning the data you want to be read, which is not in abci storage or in the tx itself, in the data field of the DeliverTxResult.

Maybe @melekes can explain this better or offer a cleaner approach.

**Comment by t-bast** [comment]
Thanks Ethan.
I'm not entirely sure this would solve my problem though, because I'm creating some events in BeginBlock and Commit and would like to notify connected clients at that point (not in DeliverTx).
The best solution is probably to manage my own web socket from my client to my ABCI right?
I was mislead by the presence of the FireEvent method but it looks like it's not meant to be used by my ABCI app the way I tried, is it?

**Comment by ethanfrey** [comment]
FireEvent is internal to tendermint core. Should not be used by abci app.
I recommend against any direct connection to the abci app, but not sure how to solve your issue otherwise.

**Comment by t-bast** [comment]
Ok thanks, I'll remove my code that attempts to use FireEvent.
Can you detail why you recommend against direct connection from my client to my abci app?

Another option if I didn't want a direct websocket between my client and my abci app is that my abci app can store the data it needs to sends to the client, the client can register to the new block event from TM core and at each new block do a custom abci_query for which my abci app would serve the data it wanted to send to the client. It's not an ideal design, but it works...

**Comment by ethanfrey** [comment]
I think for security. If you can trigger the abci app to modify state at all though a connection that doesn't come from tendermint core, you can break consensus. The tendermint rpc interface should be hardened against attacks and offer cryptographic proofs and be the only entry point to the system. You just have to squeeze everything else into the abci interface.

If this is totally impossible, sure make a direct connection, but it is a big flag for me that we need to add more capabilities to tendermint.

**Comment by t-bast** [comment]
Thanks, that makes sense.
I'll discuss it with my team, but I think I'll use the abci_query route for now (the design is not ideal but at least it doesn't require managing another websocket).
I think it could be a good feature if Tendermint allowed the ABCI app to somehow use the built-in FireEvent capabilities.
It could either be as @pdobacz suggested (enriching the ABCI response to BeginBlock, DeliverTx, EndBlock and Commit with a list of events to fire or data to include in Tendermint's current events for those steps) or by allowing the ABCI app to use a subset of FireEvent at certain times / with some restrictions...or something else entirely :)

**Comment by ethanfrey** [comment]
I agree with the idea of event sourcing and not just polling, but this is a bit much of an architecture change right now. We look to get a stable 1.0 to audit for the cosmos launch very soon.

**Comment by t-bast** [comment]
That sounds perfectly reasonable, don't worry my usecase isn't a priority at all (especially since I have a workaround).
Keep up the good work to get that 1.0 out ;)

**Comment by ebuchman** [comment]
This is a great issue - thanks Bastien.

Maybe we need to add tags to BeginBlock and EndBlock? I think there's reasonable justification for that, and that should solve your problem.

I wouldn't add them to Commit though - Commit really shouldnt be doing anything except committing the state, so I would imagine that anything you want to fire from commit could be fired from EndBlock.

Can you confirm your use case would be satisfied if we included tags in BeginBlock and EndBlock ?

**Comment by ebuchman** [comment]
@melekes @ethanfrey @jaekwon let's add tags to Begin/EndBlock ?

**Comment by t-bast** [comment]
It would be perfect in BeginBlock and EndBlock, thanks Ethan!

**Comment by ebuchman** [comment]
Closing this for #180

**Comment by ebuchman** [comment]
Nevermind thats a different repo

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/1571
