### ISSUE TITLE
docs: Ensure all Markdown links work

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9181]
At present there are a number of broken links across our Markdown files ([example](https://github.com/tendermint/tendermint/actions/runs/2809329995)).

We should aim to have this check passing.

**Comment by cason** [comment]
The approach here is centralized, someone tries to fix them all, or are we splitting the task among  us, each one handling a path?

**Comment by cason** [comment]
Issue #8340 can be related, as we are using a fork of the markdown-link-checker, and not the official release.
