### ISSUE TITLE
upstream 0.35 crypto improvements 

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#9186]
## Summary

Before I worked on batch verification for ed25519 and there were other performance improvements for ed25519. Ideally we can get those into 0.37 since they are low lift and isolated. 

## Problem Definition

While not large in the below snapshot on chains that have less activity signature verification stands out a bit more. 

(Yes, most of the issue is in the sdk)

![Screenshot 2022-08-07 at 20 29 25](https://user-images.githubusercontent.com/24299864/183305716-f52abe92-5729-451c-8479-f16e23522bcc.png)

## Proposal

Upstream performance improvements of ed25519 to main:

- https://github.com/tendermint/tendermint/pull/6526
- https://github.com/tendermint/tendermint/pull/6120

cc @Yawning

> Happy to do the work if needed

**Comment by Yawning** [comment]
I am in favor of this for the following reasons:
 * I am going to have to do the work anyway when Oasis moves beyond tendermint 0.34.x
 * We (Oasis) has been using this library in production for quite a while.
 * It has had third party external review, though there have been additions past that point.
 * It is a massive boost when syncing a node the hard way.
 * The library has a few other "nice-to-haves" such as h2c and Ed25519 ECVRF.

Like I said, I would be happy to do the work again just let me know.

**Comment by Yawning** [comment]
As a reminder (mostly for myself), #6414 also needs to be integrated.

If I were to do the work I would probably add support for batch verification (without concrete implementations in any signature scheme, ie: #6120 + #6414 minus the `crypto/ed25519` and `crypto/sr25519` changes), then in a separate commit wire in the batch verification implementations as part of switching to using voi.

**Comment by Yawning** [comment]
With the merge of #9255 this is probably complete?
