### ISSUE TITLE
Can not reconnect remote signer unless restart whole process.

### ISSUE THREAD

**Issue by RicoToothless** [tendermint/tendermint#9194]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.34.20

**Environment**:
- **OS** (e.g. from /etc/os-release): Debian 5.10.127-2 x86_64 GNU/Linux
- **Install tools**:
- **Others**:

**What happened**:
Tendermint can not reconnect to the remote signer unless restarting the whole process. Most of the time is running smoothly, it happens about once a month. By the way, we are not sure what caused the disconnect.

**What you expected to happen**:

Tendermint can reconnect automatically.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
INF SignerListener: Blocking for connection module=privval
INF SignerListener: Listening for new connection module=privval
ERR SignerListener: Ping timeout module=privval
```

**Anything else we need to know**:

Note: It happened in most Cosmos chains. For example Cosmos Hub, Osmosis, Juno, Umee...etc.

**Comment by williambanfield** [comment]
Hey @RicoToothless, I don't see anything jumping out to me that would cause this behavior; either the disconnect or the failure to reconnect. Looking at the privval code, it looks like the signer should be trying to dial the Tendermint process if it's connection goes down :thinking: 
https://github.com/tendermint/tendermint/blob/69845bb44e4f99886cb5042fbf03b1f418b3367f/privval/signer_dialer_endpoint.go#L72

Would you be able to run the signer server in debug mode to capture debug output from the _signer_ when this happens? That would definitely help triangulate where this issue may be coming from.

**Comment by RicoToothless** [comment]
> Would you be able to run the signer server in debug mode to capture debug output from the _signer_ when this happens? That would definitely help triangulate where this issue may be coming from.

`tmkms` keeps showing these errors:
```
2022-08-15T11:23:00.638916Z DEBUG tmkms::session: [come-chain-id@tcp://ooss.ooss:1234] connecting to validator...
2022-08-15T11:23:00.639064Z  INFO tmkms::connection::tcp: KMS node ID: ooxxooxx
2022-08-15T11:23:10.911281Z ERROR tmkms::client: [come-chain-id@tcp://ooss.ooss:1234] protocol error:
   0: io error
   1: Resource temporarily unavailable (os error 11)
Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```
