### ISSUE TITLE
document use of the lite package

### ISSUE THREAD

**Issue by t-bast** [tendermint/tendermint#921]
FEATURE REQUEST

I was wondering why the Vote object only includes the validator's address and index, and not its public key?
This makes it harder to verify the vote's signature because it means we need to find the voter's public key (via genesis block or /validators RPC).
Is there a security reason why the public key was not included with the signature for verification?

More generally, what is your recommendation for proving that a commit header (and thus an AppHash) was correctly signed by validators?
It looks like I need to query the /commit RPC, then look at each Precommit vote to get Signature + ValidatorAddress, then get the validator public key from its address, and with that public key and the signature verify that this correctly signs the header's bytes (and how should I get those bytes? just from the go object? from a canonical json representation? something else?).
Is that the correct way of doing it?

Thanks!

**Comment by ebuchman** [comment]
Anyone verifying the signature is expected to have the list of validators and their pubkeys because they have to check their voting power to know when +2/3 is reached. Address+index is cheaper than sending PubKey around, and we typically index by address rather than pubkey as well.

What are you writing this in? Have you seen the `lite` package in here? It used to be called `certifiers`. But it's an implementation of exactly what you're asking for. We need to find a clear place to put the spec for it as well in the docs @ethanfrey @zramsay

**Comment by t-bast** [comment]
Thanks, I had not seen the lite package (we're currently on Tendermint 0.12).
It looks like it does exactly what I want, I need to dive into the code and start using it (our code is in Go, so it's perfect).

In our system we interact with multiple blockchains (currently BTC, Tendermint, Hyperledger Fabric) and want to be able to provide our users with an evidence object that gives them all the data they need to verify existence of some data in one of these blockchains. So ideally I'd like to get them the data that is in the lite.FullComit object. I'll dig more into what's in the lite package and upgrade our code to the latest Tendermin version.

Thanks for the pointers!

**Comment by ethanfrey** [comment]
Hi t-bast, yeah, the lite client was my work some months ago and finally more visible (not in it's own lonely repo). The godocs should be half decent, and you can look at an example using it for queries here: 
https://github.com/cosmos/cosmos-sdk/blob/master/client/query.go
https://github.com/cosmos/cosmos-sdk/blob/master/client/common.go

And set up of the certifier:
https://github.com/cosmos/cosmos-sdk/blob/master/client/commands/init.go#L278-L323

**Comment by t-bast** [comment]
Awesome thanks Ethan, I'll dig into it and will let you know if I'm having troubles with it.

**Comment by ebuchman** [comment]
I think this can be closed. https://godoc.org/github.com/tendermint/tendermint/lite is reasonably comprehensive.

**Comment by ethanfrey** [comment]
I just took a look at the godoc output and it is pretty poor, with markup notation everywhere. (Probably my doing many, many months ago). If you link this from any docs, maybe someone can go through and format the godoc nicer.
