### ISSUE TITLE
Tendermint not starting to produce blocks with custom `--home` flag

### ISSUE THREAD

**Issue by faustbrian** [tendermint/tendermint#9228]
**Tendermint version** 0.34.20

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 12.5 (21G72)
- **Install tools**: n/a
- **Others**: n/a

**What happened**:

I'm running into an odd issue with the `--home` flag and I don't really know where to start looking to resolve it. I'm attempting to run tendermint with a custom home directory like `tendermint start --home="/usr/.myapp/genesis_0"` and Tendermint does launch but only until it logs `Started node` and then never progresses.

Now the part where I'm a bit stumped is that setting `export TMHOME="/usr/.myapp/genesis_0"` in my `~/.zshrc` instead of using `--home="/usr/.myapp/genesis_0"` works just fine and the node will be fully operation while the `--home` flag seems to leave the node in some odd state where it just never starts producing blocks.

**Please note that this isn't an issue with the configuration. Copying the same `config` and `data` directories from `/usr/.myapp` to `~/.tendermint` works just fine.**

**What you expected to happen**:

App launches the same way like when the **exact same configuration** is in the `~/.tendermint` directory.

**Have you tried the latest version**:

yes

**How to reproduce it** (as minimally and precisely as possible):

I'm using the stock files from `tendermint init` on `0.34.20` so it should be sufficient to run that and then runny any ABCI app. I'm saying any because I don't even see any attempt from Tendermint to talk to my ABCI app beyond getting to the `Started node` log.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

n/a

**Config (you can paste only the changes you've made)**:

Using stock `config.toml` from `tendermint init`

**node command runtime flags**:

n/a

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

Not relevant.

**Anything else we need to know**:

n/a

**Comment by williambanfield** [comment]
I am unable to reproduce this. Running Tendermint with both `--home` and `TMHOME` set work. 

Can you include a log snippet? Are you running an in-process ABCI app or an out of process ABCI app?
