### ISSUE TITLE
Consensus failure due to missing blockstore.db after several days of running

### ISSUE THREAD

**Issue by faustbrian** [tendermint/tendermint#9231]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.34.20

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

n/a

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 20.04
- **Install tools**: n/a
- **Others**: n/a

**What happened**:

After several days of having a network running on 0.34.20 I had 2 out of 12 nodes crash with a `CONSENSUS FAILURE!!!` error with the following message `"open /home/username/.tendermint/data/blockstore.db/000002.log: no such file or directory"` which looks like an issue with LevelDB?

**What you expected to happen**:

The nodes should keep running without data in `~/.tendermint/data` disappearing and corrupting the node.

**Have you tried the latest version**:

yes

**How to reproduce it** (as minimally and precisely as possible):

Not sure how to reproduce it because the nodes just kept running and only 2 out of 12 nodes ran into this issue.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
E[2022-08-12|05:24:22.610] CONSENSUS FAILURE!!!                         module=consensus err="open /home/username/.tendermint/data/blockstore.db/000002.log: no such file or directory" stack="goroutine 148 [running]:\nruntime/debug.Stack()\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:727 +0x4c\npanic({0xefa060, 0xc003523e60})\n\t/opt/hostedtoolcache/go/1.18.3/x64/src/runtime/panic.go:838 +0x207\ngithub.com/tendermint/tendermint/store.(*BlockStore).SaveBlock(0xc00010e640, 0xc000262d20, 0xc003ea7c80, 0xc00350dde0?)\n\t/home/runner/work/tendermint/tendermint/store/store.go:366 +0x577\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc000254e00, 0x685)\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:1614 +0x822\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc000254e00, 0x685)\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:1564 +0x2ff\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:1499 +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc000254e00, 0x685, 0x0)\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:1537 +0xcb7\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc000254e00, 0xc0035285a0, {0xc000038b40, 0x28})\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:2151 +0xb7c\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc000254e00, 0xc0035285a0, {0xc000038b40?, 0xc003444b00?})\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:1949 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc000254e00, {{0x12cc440?, 0xc00344a688?}, {0xc000038b40?, 0x0?}})\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:856 +0x44b\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc000254e00, 0x0)\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:763 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/home/runner/work/tendermint/tendermint/consensus/state.go:379 +0x12d\n"
```

**Config (you can paste only the changes you've made)**:

Stock `config.toml` other than `moniker` and `persistent_peers` on the various nodes.

**node command runtime flags**:

`tendermint start` without any flags

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

n/a

**Anything else we need to know**:

Note that both nodes were validator nodes, none of the sentries had this happen to them. There are 6 validator nodes and 6 sentries and 2 out of the 6 validators had this issue. This also bricked the node for good and I had to delete all application and tendermint data, syncing from 0 to get it back on track.

**Comment by williambanfield** [comment]
Is this related to issue #9228 ? It looks like the home directory mentioned here is different from the home directory mentioned in that issue.

**Comment by williambanfield** [comment]
Thanks @faustbrian, what does the disk usage look like on those nodes? Are they near full?
