### ISSUE TITLE
Update github.com/btcsuite/btcd versions

### ISSUE THREAD

**Issue by wcsiu** [tendermint/tendermint#9249]
## Summary

Currently, `tendermint/tendermint` is using `github.com/btcsuite/btcd v0.22.1`  which is a relatively old version of `btcsuite/btcd` and when it is used with some other modules with a more updated version of `btcsuite/btcd` like `v0.23.1`, the `btcsuite/btcd` being used for the whole project will be upgraded `v0.23.1` and it will cause some dependency conflicts due to the vast differences between `v0.23.1` and `v0.22.1`.

## Problem Definition

Currently, `tendermint/tendermint` can't be used with projects using newer version of `btcsuite/btcd` and of cause, `tendermint/tendermint` can't use newer version `btcsuite/btcd` either due to the dependency of old version(v0.22.1) of `btcsuite/btcd` in `crypto/scep256k1`. With this update, `tendermint/tendermint` could be more freely imported with other projects and `tendermint/tendermint` will also be able to use the latest version of `btcsuite/btcd`. There is basically no disadvantage to the tendermint.

## Proposal

Instead of using `github.com/btcsuite/btcd v0.22.1` and `github.com/btcsuite/btcutil v1.0.3-0.20201208143702-a53e38424cce`, we use `github.com/btcsuite/btcd/btcec/v2 v2.2.1` and `github.com/btcsuite/btcd/btcutil v1.1.2` which are the only two modules from `btcsuite` `tendermint` uses. It should eliminates all potential dependency conflicts with modules using the most updated `github.com/btcsuite/btcd`.

Some logic in `github.com/tendermint/tendermint/crypto/secp256k1` will have to be updated for the corresponding updates in dependencies.

**Comment by wcsiu** [comment]
I have submitted a PR for this issue. You may have a look. Let me know if there is anything I can do to make the merge easier.
https://github.com/tendermint/tendermint/pull/9250

**Comment by williambanfield** [comment]
> tendermint/tendermint can't be used with projects using newer version of btcsuite/btcd and of cause, tendermint/tendermint can't use newer version btcsuite/btcd either due to the dependency of old version(v0.22.1) of btcsuite/btcd in crypto/scep256k1

I'm not sure I understand why this is the case, could you provide some explanation?

**Comment by wcsiu** [comment]
> > tendermint/tendermint can't be used with projects using newer version of btcsuite/btcd and of cause, tendermint/tendermint can't use newer version btcsuite/btcd either due to the dependency of old version(v0.22.1) of btcsuite/btcd in crypto/scep256k1

> I'm not sure I understand why this is the case, could you provide some explanation?
It is about the minimum version selection in go. For package using btcsuite/btcd v0.22.1 and package using btcsuite/btcd v0.23.1, Go module will pick v0.23.1 when they are put together.
For more detailed explanation, this article gives a better answer(https://research.swtch.com/vgo-mvs).
I have prepared an example for you, https://github.com/wcsiu/tendermint-demo.
If you try to run `go mod tidy`, it will return
```
go mod tidy    
go: finding module for package github.com/ava-labs/avalanchego/wallet/chain/x
go: found github.com/ava-labs/avalanchego/wallet/chain/x in github.com/ava-labs/avalanchego v1.7.18
go: finding module for package github.com/btcsuite/btcd/btcec
demo imports
        github.com/tendermint/tendermint/crypto/secp256k1 imports
        github.com/btcsuite/btcd/btcec: module github.com/btcsuite/btcd@latest found (v0.23.1), but does not contain package github.com/btcsuite/btcd/btcec
```
