### ISSUE TITLE
Validator node blocking the network by not creating empty blocks

### ISSUE THREAD

**Issue by bijlar** [tendermint/tendermint#925]
**BUG REPORT**:

**Tendermint version**:
0.10.3

**Environment**:
Windows

**What happened**:
Set up 2 validator nodes, both set to not create empty blocks using the `--consensus.create_empty_blocks=false` flag. One of these nodes is receiving input constantly, while the other does not. This results in nothing happening in the network, except the CheckTX function being broadcasted to the other node. 

**What you expected to happen**:
I expected the input to be broadcasted to the other node, after which a block would be formed.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Anything else do we need to know**:
I'm not entirely sure if this is even a bug, it could just be expected behavior that I will need to deal with. Once I set the node that's not receiving any input to just create empty blocks the system works fine, however I'd like to be able to avoid that if possible.

**Comment by bijlar** [comment]
No, not yet. I'll try to do that in the near future. Do you have any specific reason to think that the result might be different for that version? Or just in general?

**Comment by melekes** [comment]
just in general

**Comment by ebuchman** [comment]
Would it be possible to provide a short shell script that replicates this ?

**Comment by adrianbrink** [comment]
@bijlar Could you provide more information on this? I'm closing this issue for now. Please just leave a comment and we can reopen it. :-)
