### ISSUE TITLE
question about Unlock-on-Polka

### ISSUE THREAD

**Issue by SlackBuffer** [tendermint/tendermint#9251]
### Discussed in https://github.com/tendermint/tendermint/discussions/9246

<div type='discussions-op-text'>

<sup>Originally posted by **SlackBuffer** August 14, 2022</sup>
Hi, guys, I got a liveness question. I'll just quote the scenario described in ["Tendermint: Byzantine Fault Tolerance in the Age of Blockchains"](https://knowen-production.s3.amazonaws.com/uploads/attachment/file/1814/Buchman_Ethan_201606_Msater%2Bthesis.pdf):

_"Consider a round where A and B precommitted blockX while C and D pre-committed nil - a split vote. They all move to the next round, and blockY is proposed, which C and D prevote for. Suppose A is Byzantine, and prevotes for blockY as well (despite being locked on blockX), resulting in a polka. Suppose B does not see the polka and pre-commits nil, while A goes offline and C and D pre-commit blockY . They move to the next round, but B is still locked on blockX, while C and D are now locked on blockY , and since A is offline, they can never get a polka. Hence, we've compromised liveness with less than a third (here, only one) Byzantine validators."_

In such situation, B, locked on blockX, can only prevotes for blockX in the upcoming rounds, C and D can only prevote for blockY., meaning blockX, blockY, or any other new block can never get a polka. 

Let's say A, being Byzantine, stays offline forever. So how does the Unlock-on-Polka mechanism work since there's no way the now 3-node Tendermint cluster will get a polka in a higher round? As I see it, liveness is still compromised with only one Byzantine node.

Very confused here...</div>

**Comment by thanethomson** [comment]
Discussions are the right place to open this kind of question, as you have done :slightly_smiling_face: (No need for a discussion _and_ an issue, unless you find a specific bug in the specification/protocol)
