### ISSUE TITLE
abci++: Port E2E tests from `v0.36.x` to ABCI++ feature branch

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9271]
- Goal: Backport all non-ABCI++ related improvements to e2e tests up to v0.36.x
- Size: around 3 KLOC
- can be done in parallel with all other tasks above
- [ ] apply patch (diff btw v0.34.x and v0.36.x on e2e dir) [Estimation : 0 days]
- [ ] remove vote extension & `FinalizeBlock` related code from e2e App [Estimation : 3 days]
- [ ] No errors in make build, make test (just in case) [Estimation : 1 day]
- [ ] e2e builds, runs, but some tests fail [Estimation : 2 days]
- [ ] e2e tests pass [Estimation : 3 days]

**Comment by cmwaters** [comment]
I believe we can close this issue. The main things that were ported across was evidence generation and the addition of abci delays. 

Changes that haven't been ported across were the timeout changes and transaction broadcasting tweaks which were done mostly in reaction to the v0.35 p2p layer and don't seem to be problematic here. The other series of changes I see are code hygiene ones such as the addition of contexts which we will likely add in future releases.

So far the e2e tests in v0.37 and main have been passing quite consistently.

Feel free to reopen this if you think something is missing but I consider this issue done.
