### ISSUE TITLE
config: Migrate `discard_abci_responses` from `[rpc]` to new `[storage]` section

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9274]
As discussed in https://github.com/tendermint/tendermint/pull/9267#discussion_r946753672 and on Slack, we should migrate [this configuration option](https://github.com/tendermint/tendermint/blob/1f0cf7762bc414bf95b93afa773160f8467902e1/config/config.go#L412) to its own new section, as it seems a little misplaced to have a state store configuration option under the `[rpc]` section.

So far the best option seems to be a new `[storage]` section.

**Comment by cmwaters** [comment]
@thanethomson strange that this didn't automatically close. Going to close it now
