### ISSUE TITLE
forcing wrong Header and dialer protocol, in websocket client.

### ISSUE THREAD

**Issue by ranlavanet** [tendermint/tendermint#9278]
**Tendermint version** latest

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu
- **Install tools**:
- **Others**:

**What happened**:
Websocket client dialer, and start cant support user credentials and ws:// headers 

**What you expected to happen**:
1. Dailer should not overwrite proto with the current protocol as proto will be "tcp" and protocol might be ws://, therefore using makeHTTPDialer in that case doesn't fit. 

i would suggest:
`func createDailer(remoteAddr string) (func(string, string) (net.Conn, error), error) {
	u, err := url.Parse(remoteAddr)
	if err != nil {
		return nil, err
	}
	if u.Scheme == "" {
		u.Scheme = "tcp"
	}
	dialFn := func(proto, addr string) (net.Conn, error) {
		var timeout = 10 * time.Second
		return net.DialTimeout(proto, u.Host+u.EscapedPath(), timeout)
	}
	return dialFn, nil
}`

2. dial() function creates an empty http.Header which means username and password protected addresses couldn't be reached. 
my suggestion to rewrite dial to:
`func (c *WSClient) dial() error {
	dialer := &websocket.Dialer{
		NetDial: c.Dialer,
		Proxy:   http.ProxyFromEnvironment,
	}
	endpointURL, err := url.Parse(c.protocol + "://" + c.Address + c.Endpoint)
	if err != nil {
		return err
	}
	rHeader := make(http.Header)
	if endpointURL.User != nil {
		b64auth := base64.StdEncoding.EncodeToString([]byte(endpointURL.User.String()))
		rHeader.Add("authorization", "Basic "+b64auth)
		endpointURL.User = nil
	}
	conn, _, err := dialer.Dial(endpointURL.String(), rHeader) // nolint:bodyclose
	if err != nil {
		return err
	}
	c.conn = conn
	return nil
}
`

**Have you tried the latest version**: yes/no
yes 

**How to reproduce it** (as minimally and precisely as possible):

Create a websocket server in port 9999 or anything that works. 
`
addr := "ws://localhost:9999"
c,_ := client.NewWS(addr, "")
err := c.Start()
defer c.Stop()
if err != nil {
   fmt.Printf("err; %s", err)
}
`

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
websocket: bad handshake

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by williambanfield** [comment]
What tendermint version is this for? 

> Websocket client dialer, and start cant support user credentials and ws:// headers

I'm not sure I understand what the issue is exactly?

**Comment by mishaelran** [comment]
I am talking about the latest version as well as previous ones as no changes been made to the dialer as far as i could see in the past few versions. 

The issue is when trying to send a websocket request with username and password credentials the Header is created as an empty Http.header that you could see the diff in the dial function as i suggested. Also creating a client with a protocol ws:// will fail for sure as you override the proto with protocol in the Dialer callback also as i added

**Comment by williambanfield** [comment]
> I am talking about the latest version as well as previous ones
Are you referring to v0.34.21?

**Comment by mishaelran** [comment]
V0.35.9

**Comment by yoongbok-lee** [comment]
idk if this is relevant but the following code snippet will result in an error
```
package main

import (
	tmclient "github.com/tendermint/tendermint/rpc/client/http"
)

func main() {
	c, err := tmclient.New("https://tendermint.bd.evmos.dev:26657", "/websocket")
	if err != nil {
		panic(err)
	}

	err = c.Start()
	if err != nil {
		panic(err)
	}
}
```
with error `websocket: bad handshake`.

changing to wss or ws doesn't work either since it can't even recognize `wss` or `ws` protocol.

This is from v0.34.20

**Comment by mishaelran** [comment]
Yoongbok did you mean NewWs instead of New? 
In your example you wrote New. 

Non the less currently tendermint client doesnt allow addressess that doesnt start with tcp as they hard code the protocol in the dialer callback 

( see the Dailer setup inside Websocket client) 

Hopefully this can be fixed.

**Comment by yoongbok-lee** [comment]
It should be `New` from `rpc/client/http` instead of `rpc/jsonrpc/client` since I want to subscribe and decode the output directly. This is also about the same since it force converts `http` and `https` to `tcp` in the dialer as well.
