### ISSUE TITLE
specify directory with `--config-dir` and `--data-dir`

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#928]
after discussion with Greg, this would be sysadmin friendly

**Comment by zramsay** [comment]
related to #556

**Comment by odeke-em** [comment]
@zramsay am assuming you already implemented this in tmlibs https://github.com/tendermint/tmlibs/commit/39df69728ce14eafd720f4fda06bb136e3328750 right? What are the next steps?

**Comment by zramsay** [comment]
that commit started the process but was really meant for splitting the data & config dirs (pre-requisite for this issue). i tinkered on this issue but after discussion with @ebuchman is was determined to not be a priority

**Comment by ebuchman** [comment]
I'm going to close this.
