### ISSUE TITLE
consensus: add time fields to signed messages (proposals and votes)

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#929]
In preparation for using a BFT time in the header

**Comment by ethanfrey** [comment]
This is just adding the info and not doing anything with it?

Should this be backwards compatible with older versions? Probably not, it is not persisted and all nodes must upgrade tendermint at the same point, right?

**Comment by ebuchman** [comment]
That's right. Once it's in, we can use it to later make BFT timestamps in the block header without a breaking change. So let's just get them in there.

**Comment by ethanfrey** [comment]
Addressed in #953 which was merged. Closing issue.
