### ISSUE TITLE
v0.35.x retraction doesn't work

### ISSUE THREAD

**Issue by faddat** [tendermint/tendermint#9307]
Still getting v0.35.x imports when working with the SDK

```bash
    1  git pull
    2  git clone https://github.com/cosmos/cosmos-sdk --branch release/v0.46.x
    3  cp -r cosmos-sdk/simapp .
    4  rm -rf cosmos-sdk
    5  cd simapp
    6  mv * ../
    7  cd ..
    8  git restore README.md
    9  rm -rf simapp
   10  mv simd eve
   11  go mod init
   12  go mod init github.com/notional-labs/eve
   13  go mod tidy
   14  go get github.com/tendermint/tendermint@v0.34.21
   15  go mod tidy
   16  go mod tidy
   17  history
```

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

sdk 46

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

Cosmos SDK

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

Got v0.35.9 imports

**What you expected to happen**:

They'd be retracted

**Have you tried the latest version**: yes/no

The idea is not to do that

**How to reproduce it** (as minimally and precisely as possible):

The exact commands are above

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

Maybe the comma is wrong?  I'm not sure, but it would be really nice to get rid of v0.35.x

**Comment by creachadair** [comment]
It is likely that the module proxy is still targeting `master`, since that branch still exists. To work around this, it will probably be necessary to publish the retractions in the `go.mod` file on the `master` branch. (As far as I know, the module proxy does not have knowledge of which branch is the "default" in a repository)

Alternatively, renaming or deleting `master` might (I think) convince the proxy to retarget against `main`, but I'm not positive.

**Comment by cmwaters** [comment]
I think we'll keep `master` around at least a little longer for posterity so it probably makes the most sense to update `master` as well.

**Comment by faddat** [comment]
Thanks to both of you!

I'll let you know if this shows up again
