### ISSUE TITLE
spec: priority mempool specification

### ISSUE THREAD

**Issue by jmalicevic** [tendermint/tendermint#9310]
We need to specify the priority mempool: its behaviour, transaction ordering, interaction with other Tendermint components etc. 

Currently available documentation:
- Link to [ADR067](https://github.com/tendermint/tendermint/blob/main/docs/architecture/adr-067-mempool-refactor.md) that introduced the priority mempool.

**Comment by thanethomson** [comment]
Since we're probably going to deprecate the priority mempool (#9388), we probably don't need the specification work on this front. I'll close this for now, and if somehow we decide to continue to support the priority mempool we can reopen this issue.
