### ISSUE TITLE
Port #6408 (refractor EventAttribute) to main

### ISSUE THREAD

**Issue by Jiuhk** [tendermint/tendermint#9314]
Per [#6403 ](https://github.com/tendermint/tendermint/issues/6403), [#6408](https://github.com/tendermint/tendermint/pull/6408) solved corrupted event attributes which lead to failing query API, especially for events with non utf8 values. It is currently the major obstacle in my application that must use unicode characters.

**Comment by thanethomson** [comment]
Thanks for the reminder! I've reopened #6403.

**Comment by Jiuhk** [comment]
Is it not guaranteed to include the fix in v0.37, but rather depends on you guys' progress?
