### ISSUE TITLE
Wrong type for `max_age_duration`?

### ISSUE THREAD

**Issue by faustbrian** [tendermint/tendermint#9324]
> Tendermint v0.34.21 as you can see at the linked proto file.

The type of `consensus_params.evidence.max_age_duration` is specified as  **google.protobuf.Duration** in https://github.com/tendermint/tendermint/blob/v0.34.21/proto/tendermint/types/params.proto#L48-L49 but the `genesis.json` has a different structure if you attempt to use **nanos** and **seconds** as specified by **google.protobuf.Duration** then Tendermint will blow up because the structure is wrong.

**Genesis file from `tendermint init`**
```json
{
  "genesis_time": "2022-08-29T11:53:21.107854Z",
  "chain_id": "test-chain-6XBJhY",
  "initial_height": "0",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
      "max_age_num_blocks": "100000",
      "max_age_duration": "172800000000000",
      "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "ed25519"
      ]
    },
    "version": {}
  },
  "validators": [
    {
      "address": "5C65D7EDED882E4581FC35C0522989B51ADA29C8",
      "pub_key": {
        "type": "tendermint/PubKeyEd25519",
        "value": "eyDZObkdlW1gHuu7RvuMTGBcogeT3HuyJAp9hO1WbKk="
      },
      "power": "10",
      "name": ""
    }
  ],
  "app_hash": ""
}
```

Now why this is a problem is that if you try to use the proto files with any tool that generates code from it you'll get code that is wrong. `nanos` for example is specified as `int32` but max value in that case would be `2147483647` unless I'm missing something, which `172800000000000` obviously exceeds. My use-case specifically is for TypeScript and the generated code from the proto files blows up because `172800000000000` exceeds the `int32` limit.

What's correct? The proto file or the `genesis.json` or neither? What value should be used for `nanos` since it has to be `int32` and `172800000000000` would only fit into `int64` which is defined as `seconds` as you can see here https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/duration.proto#L103-L116.

**Comment by williambanfield** [comment]
Hey @faustbrian, I just did some spelunking. 
We use the[ `stdduration = true` annotation on our protos](https://github.com/tendermint/tendermint/blob/v0.34.21/proto/tendermint/types/params.proto#L48-L49), which produces a generated struct with a Golang `time.Duration`, instead of the typical proto duration you describe. This means that the `json` field is being parsed into a `time.Duration` using Go's json package. `time.Duration` is an alias to `int64` representing a nano second. While Go does implement a standard library function [time.ParseDuration](https://pkg.go.dev/time#ParseDuration) to decode simpler Go duration strings, the golang `json` package does not use this to parse. See  https://github.com/golang/go/issues/10275. As a result, the field `max_age_duration` is parsed as a plain `int64` and used as nano seconds.

**Comment by williambanfield** [comment]
> which I would say isn't ideal since out of process applications aren't guaranteed to be written in golang.

I would agree this is not ideal. Changing this is a breaking change of historical genesis files and is subtle and risky. Genesis files are stored in the Tendermint DB after startup so this would require a migration and / or maintaining multiple versions of the file at once within a version of Tendermint to read old and new duration fields.

For the time being, I would recommend writing an int64 as the value of that field, perhaps as a post-processing step on your generated JSON bytes when trying to encode into a Tendermint genesis file.

**Comment by williambanfield** [comment]
To clarify, my suggestion here is to use a special proto only for interacting with the JSON for the tool(s) it sounds like you're building, _not_ for trying to use as part of Tendermint itself. That value is still going to encode and decode as a wire format proto `duration` when written as proto, meaning as a `message` containing an `int64` and an `int32`.

**Comment by williambanfield** [comment]
If you're not interacting with the genesis file as JSON but instead interacting with the socket, then you can still use a regular proto `duration`, i.e. the original `.proto` definition. The genesis file is the place this shows up as a result of the use of a `Go` flag. For example, [tendermint-rs generates a proto duration](https://github.com/informalsystems/tendermint-rs/blob/main/proto/src/prost/tendermint.types.rs#L419) and is compatible with Tendermint via the socket. Are you seeing errors when interacting with Tendermint when sending a proto `duration` for the `max_age_duration` field?

**Comment by williambanfield** [comment]
Ah, got it. Use `seconds: 172800`. The value in the genesis file is nanoseconds, but the integer width is 64 bits in that encoding instead of 32.

**Comment by williambanfield** [comment]
> Is nanos irrelevant for consensus_param_updates in EndBlock and can basically stay at a hardcoded value or what is the idea behind that?

It is not completely irrelevant there if you would like to have a value in the range of a few nano seconds (although I'm not sure why you would). When working with native proto in code that is _not go_, use the normal `proto` duration fields (`nanos` and `seconds`). The difference is in what type the value is represented as in _go code_ and in the `genesis.json`. All other places it is a regular `proto` duration.
