### ISSUE TITLE
node fails to parse seed addresses when prefixed with protocol `tcp://`

### ISSUE THREAD

**Issue by spacejam** [tendermint/tendermint#934]
BUG REPORT

node fails to parse seed addresses when prefixed with protocol, such as: `tcp://1.2.3.4:46656`

**Tendermint version** 
v0.13.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
abci counter demo

**What happened**:
tendermint crashed with log message: `
ERROR: Failed to start node: Error in address tcp://1.2.3.4:46656: address tcp://1.2.3.4:46656: too many colons in address
`

**What you expected to happen**:
parse `tcp://1.2.3.4:46656` the same as `1.2.3.4:46656`

**How to reproduce it** (as minimally and precisely as possible):
specify seeds in `config.toml` with protocol
```
[p2p]
laddr = "tcp://1.2.3.4:3000"
seeds = "tcp://1.2.3.4:3000,tcp://1.2.3.5:3001,tcp://1.2.3.6:3002,tcp://1.2.3.7:3003"
```

**Anything else do we need to know**:
works:
```
[p2p]
laddr = "tcp://1.2.3.4:3000"
seeds = "1.2.3.4:3000,1.2.3.5:3001,1.2.3.6:3002,1.2.3.7:3003"
```

**Comment by zramsay** [comment]
#979
