### ISSUE TITLE
remove usage of private global in cmds

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#9340]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): All

Some tendermint commands make use of a private global that in the sdk we need to wrap the tm cmd in an extra layer to make work correctly. It would be nice to be able to reuse these commands without wrapping. 

https://github.com/cosmos/cosmos-sdk/pull/13084#discussion_r958826140

can we get this for 0.34 and 0.37 as its annoying to duplicate logic to fix this

**Comment by cmwaters** [comment]
Sam K actually did this in v0.35/v0.36 so at least we have a reference point. Totally agree we should be cleaning this up when we get the chance

**Comment by JayT106** [comment]
> Sam K actually did this in v0.35/v0.36 so at least we have a reference point. Totally agree we should be cleaning this up when we get the chance

is PR #7719? I can help re-porting it.
