### ISSUE TITLE
separate abciresponse to a different DB

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#9347]
## Summary

Right now if a operator wants to save abciResponses they are saved in the state.db. Recently there was work to make this optional, I believe a next step would be to separate state storage from abciResponses in general. 

## Proposal

Create a new abciResponse.db that stores all abciresponses if the option to save them is enabled. This is a nice to have but the separation creates a cleaner separation of concerns

**Comment by cmwaters** [comment]
What's the advantage of this? That you can simple delete the db directly if you want (instead of relying on pruning which is somewhat inefficient)?
