### ISSUE TITLE
v0.35.9 lives (dependabot)

### ISSUE THREAD

**Issue by faddat** [tendermint/tendermint#9355]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

* https://github.com/BitCannaGlobal/bcna/pull/46

**What happened**:

Dependabot is insisting that v0.35.9 is a good idea.

**What you expected to happen**:

v0.34.21

**Have you tried the latest version**: yes/no

yep

**How to reproduce it** (as minimally and precisely as possible):

install dependabot

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

* https://github.com/BitCannaGlobal/bcna/pull/46

**Config (you can paste only the changes you've made)**:

https://github.com/BitCannaGlobal/bcna/blob/main/.github/dependabot.yml

**Comment by thanethomson** [comment]
I've been trying to find how exactly to convince the proxy to consider the `main` branch as our default branch, and it doesn't seem like there's a clear way to do this. It seems there may be an open issue relating to pkgsite in this regard: https://github.com/golang/go/issues/41312

We've tried retracting the version on [`main`](https://github.com/tendermint/tendermint/blob/6bdc970377be29e9473a69ad9af77c7f235e660e/go.mod#L274) and on [`master`](https://github.com/tendermint/tendermint/blob/85a584dd2ee3437b117d9f5e894eac70bf09aeef/go.mod#L250), and it seems as though these instructions are just totally ignored.

**Comment by thanethomson** [comment]
Ah, never mind:

> To retract a version, a module author should add a retract directive to go.mod, then publish a new version containing that directive. The new version must be higher than other release or pre-release versions; that is, the `@latest [version query]`(https://go.dev/ref/mod#version-queries) should resolve to the new version before retractions are considered. The go command loads and applies retractions from the version shown by go list -m -retracted $modpath@latest (where $modpath is the module path).

This will only take effect once we publish v0.37.0.
