### ISSUE TITLE
Allow ConsensusParams to be updated by EndBlock

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#937]
Similar to Ethereum style sliding block limit.

**Comment by ebuchman** [comment]
Tendermint is agnostic to how this is done. Only needs to know that the block limit changed. Otherwise its app side logic

**Comment by ebuchman** [comment]
EndBlock should include `ChangeConsensusParams` which is a diff of how the ConsensusParams change. If its all zeros (default) then there's no change.

In other words, it should work alot like the validator set changes. Though we need better terminology ala https://github.com/tendermint/tendermint/issues/924

**Comment by melekes** [comment]
Wait for https://github.com/tendermint/abci/pull/163

**Comment by melekes** [comment]
See https://github.com/tendermint/tendermint/pull/972
