### ISSUE TITLE
p2p: peer went down but didn't StopPeerForError

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#938]
Sometime we lose a peer but don't notice.

Can be seen in `net_info` as a massive and growing `Idle` and a zero `InstRate` and `CurRate`.

Not sure how to deterministically reproduce yet

**Comment by ebuchman** [comment]
This should be fixed by solving the mempool memory leak: https://github.com/tendermint/tendermint/pull/1173

We'll keep testing though and open a new if it repeats

**Comment by odeke-em** [comment]
@ebuchman could we add a test please?

**Comment by ebuchman** [comment]
See https://github.com/tendermint/tendermint/pull/1202/files

**Comment by ebuchman** [comment]
Also opened a new issue: https://github.com/tendermint/tendermint/issues/1222
