### ISSUE TITLE
Query `tm.event='Tx'` returns only as batch per block

### ISSUE THREAD

**Issue by unlimittt** [tendermint/tendermint#9395]
**What happened**:
Subscribing to transaction events tendermint returns only as batch per block

**What you expected to happen**:
Return every tx from mempool where they must be stored FIFO, not in block.

**Anything else we need to know**:
Any workarounds? How to get transactions appear one by one? I've noticed you've got events/types.go:181 but no actual implementation.
```
type TxEventPublisher interface {
	PublishEventTx(EventDataTx) error
}

```
And there is no message with `mempool` reactor channel_id. How to start receiving pending transactions?

**Comment by creachadair** [comment]
The consensus node does not publish events for unconfirmed transactions added to the mempool. `Tx` events are generated after delivery, when a block is committed.

There is a separate call to query for unconfirmed transactions but it does not support query filters.

**Comment by unlimittt** [comment]
> The consensus node does not publish events for unconfirmed transactions added to the mempool. `Tx` events are generated after delivery, when a block is committed.
> 
> There is a separate call to query for unconfirmed transactions but it does not support query filters.

What's the query, can't find.

**Comment by creachadair** [comment]
> What's the query, can't find.

https://docs.tendermint.com/v0.34/rpc/#/Info/unconfirmed_txs

**Comment by unlimittt** [comment]
Okaaaaay, I did it. Block events fire when block minted, transaction events fire when transaction submitted.
Still think this is bug despite transaction finality on submit.

**Comment by cmwaters** [comment]
> Block events fire when block minted, transaction events fire when transaction submitted.

Transaction events only fire when the block is minted. This is because the events are often dependent on the current state of the application. You don't know what events may be emitted from a transaction without knowing the state it was applied against. Does that make sense?
