### ISSUE TITLE
Support extra isLatest param in event query API in ADR 075

### ISSUE THREAD

**Issue by mmsqe** [tendermint/tendermint#9424]
## Summary

Allow client query from latest on init call like [kafka](https://kafka.apache.org/documentation/#consumerconfigs_auto.offset.reset).

## Problem Definition

Currently [master](https://github.com/tendermint/tendermint/blob/85a584dd2ee3437b117d9f5e894eac70bf09aeef/internal/eventlog/eventlog.go#L105) return without wait if given cursor not head.

## Proposal

A [param](https://github.com/mmsqe/tendermint/pull/76/files) to [avoid](https://github.com/evmos/ethermint/pull/1321/commits/52c85d9fd16017a2d0099c43f41d5468dcb679b6) extra 1st call with Before now in client side.

**Comment by creachadair** [comment]
Can you say a bit more about the problem this proposal is intended to solve? Generally a client will only set the `before` cursor if there are multiple pages of results matching a query at the head of the log. In that context the only events that _could_ match are already in the past, so this isn't something you'd do as an initialization step. 

A client _will_ often set an `after` cursor, as a way of picking up after a restart for example. But that doesn't trigger the pagination behaviour so it should not need additional parameters. 

Have I missed some aspect of your concern here?

**Comment by mmsqe** [comment]
On initial step, when client has no cursor and tries to call with empty `after`, triggers [WaitScan](https://github.com/tendermint/tendermint/blob/85a584dd2ee3437b117d9f5e894eac70bf09aeef/internal/rpc/core/events.go#L214) with this empty `after`, results in [scanState](https://github.com/tendermint/tendermint/blob/85a584dd2ee3437b117d9f5e894eac70bf09aeef/internal/eventlog/eventlog.go#L105), since wait need equal cursor in [waitStateChange](https://github.com/tendermint/tendermint/blob/85a584dd2ee3437b117d9f5e894eac70bf09aeef/internal/eventlog/eventlog.go#L98). A workaround for client is [quick](https://github.com/tendermint/tendermint/blob/85a584dd2ee3437b117d9f5e894eac70bf09aeef/internal/rpc/core/events.go#L226) poll with non-empty `before` to get head cursor as `after` to call in next long poll call.

**Comment by creachadair** [comment]
That should be the desired result: when the client first calls, there are two possible outcomes: 

1. There are matching items for the query. In this case the query returns them (or as many as it can up to the requested limit) without waiting.

2. There are no marching items for the query. In this case the request waits up to the requested interval for more to arrive.

In both cases the client knows what the available range is at that moment. It's not clear to me what problem the client hopes to solve by knowing the range in advance. If the client doesn't already have a cursor saved from a previous call, there's nothing meaningful it can do with that information that wouldn't also accompany a normal query.

**Comment by mmsqe** [comment]
Got it thanks, we can keep 1st call as this reference then.

**Comment by creachadair** [comment]
Yes, I think making the call normally is the right solution. If for some reason the client doesn't care about pre-existing events it can simply ignore the results from the first reply. (That seems like a weird thing to want to do; events are not strongly globally time ordered anyway. But in that case the client can easily get what it wants without asking the server for a special case)
