### ISSUE TITLE
abci: port across finalize block from v0.36

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#9427]
Manually port #7798

Also requires https://github.com/tendermint/tendermint/pull/7607 and https://github.com/tendermint/tendermint/pull/8401

**Comment by sergio-mena** [comment]
Is this a sub-issue of #9396?

**Comment by cmwaters** [comment]
> Is this a sub-issue of https://github.com/tendermint/tendermint/issues/9396?

yes you should see it there

**Comment by sergio-mena** [comment]
OK, thanks for confirming, and for taking it up :-)

I also see that the feature branch (`feature/abci++vef`) has been created. Thanks for that as well!

**Comment by mbreithecker** [comment]
Hey,
I might be a little late to the party but just saw the changelog:

> [rpc] Removed begin_block_events and end_block_events from BlockResultsResponse. The events are merged into one field called finalize_block_events. (https://github.com/tendermint/tendermint/issues/9427)

How does one distinguish BeginBlockEvents from EndBlockEvents if they are merged in one field?
How can I reconstruct the order of the events taking the tx_results into accounts?
Usually I just go: begin_block -> tx_results[] -> endblock
How can I retrieve the order with the new structure with having finalize_block?
