### ISSUE TITLE
When using postgres indexer, TxResults for blocks where any transaction has an error code are not stored

### ISSUE THREAD

**Issue by pscott31** [tendermint/tendermint#9460]
**Tendermint version** 0.34.20

**ABCI app** [vega](https://github.com/vegaprotocol/vega)

**Environment**:
- **OS** ubuntu 20.04

**What happened**:
We're testing out switching to using the postgres indexer to facilitate building a block explorer. I noticed a bunch entries missing in the tx_results table, and in the log I see messages like

```txindex/indexer_service.go:88   deduplicate batch       {"height": 412}```

Digging into it a little it seems that this is because `txIdxr.Get(hash)` is not implemented by the `BackportTxIndexer` that is used when the postgres indexer is enabled. I think it would not be too tricky to implement, and I'm happy to have a stab at that, but thought I had better check here first because I don't fully understand the purpose of `DeduplicateBatch`.

Also we've noticed that when enabling the postgres indexer tendermint cannot keep up with its peers and keeps going out of sync so I'm a bit loathe to add in more PG queries; I figure this sort of thing could possibly be solved with an `ON CONFLICT DO xxx` clause but I'm not sure if I could make that fit in nicely with the backend-agnostic framework you have.

**What you expected to happen**:

No errors in the log, all my TxResults in my postgres DB :)

**Have you tried the latest version**: yes/no

I haven't tried in 0.35.xx as we have had a bunch of issues with that and have had to revert back to 0.34 for now

**Comment by cmwaters** [comment]
`DeduplicateBatch` if I'm not mistaken is more a case of the kv indexer as it indexes on tx hashes (which there could be multiple duplicates committed with different results and in which the latest result overwrites the previous ones). 

I think it's used also for postgres for consistency reasons but I'm not sure if that really makes sense

**Comment by cmwaters** [comment]
>  I see messages like
> txindex/indexer_service.go:88 deduplicate batch {"height": 412}

Just realised that the actual error isn't being logged. Will push a small patch for that

**Comment by cmwaters** [comment]
Ok, after digging around it seems that we need to move the deduplication logic into the kvIndexer only because as it's currently implemented any transaction that is committed but not successfully executed will cause the postgresql to error and batch nothing

**Comment by pscott31** [comment]
Brilliant work thank you - I am glad I didn't try and implement `txIdxr.Get(hash)` on the postgres sink and then have to suffer getting my patch rejected :)
