### ISSUE TITLE
`--p2p.external-address` flag is the only "start" flag that uses dash-case

### ISSUE THREAD

**Issue by mark-rushakoff** [tendermint/tendermint#9480]
Using v0.37.0-alpha.2, every other flag to `tendermint start` uses `snake_case` (e.g. `--db_backend`, `--consensus.create_empty_blocks_interval`, `--p2p.private_peer_ids`).

But `--p2p.external-address` uses `dash-case`, and if you type `--p2p.external_address`, the flag is not recognized.

With pflag, [it is possible to set a normalization function](https://pkg.go.dev/github.com/spf13/pflag#readme-mutating-or-normalizing-flag-names) such that we make `--p2p.external_address` the canonical flag for consistency with all other flags, but we continue to accept `--p2p.external-address` for backwards compatibility.

**Comment by cmwaters** [comment]
Good catch. I believe it was added in later. See https://github.com/tendermint/tendermint/issues/9035
