### ISSUE TITLE
`gen-node-key` does not respect `--home` flag

### ISSUE THREAD

**Issue by mark-rushakoff** [tendermint/tendermint#9481]
Using v0.37.0-alpha.2, generating a node key does not respect the --home flag, even though it is listed in the global flags for `tendermint gen-node-key --help`.

Setting environment variable `TMHOME` is a suitable workaround until the flag is connected correctly.

```console
$ tendermint gen-node-key  # Expected to already exist
ERROR: node key at /tendermint/config/node_key.json already exists
$ tendermint gen-node-key  --home /tmp/1 # --home should be respected (but isn't)
ERROR: node key at /tendermint/config/node_key.json already exists
$ TMHOME=/tmp/1 tendermint gen-node-key # Environment variable is respected
1ce6a03db8411f0705beb0bc0012a5adad34d3b4
```

**Comment by JayT106** [comment]
tested with 12f0c4a624ea1da0ab1c30ec025ff981425d657a, doesn't have this issue. But something that can be improved is it created the `config` and `data` folder when generating the node key, we should just create the `node_key.json` to the `home` path directly if not the default home
