### ISSUE TITLE
consensus: Proposal should not include block ID

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#9504]
## Summary

The proposal sent by the proposer not only includes the signature and height and round but also the `block_id`. This allows validators to short cut consensus by signing the vote without needing to receive the block. Validators could theoretically run a simple stateless process that listens on proposals and continuously signs the block ID. This could compromise data availability guarantees. Tendermint should force validators to only sign a vote once they have received the full block. To do this, the proposal should not include the block ID but just the part set header. The signature should still remain over the BlockID but now validators must compute the hash of the block to reconstruct the BlockID. Given that the proposal still have the unique height, round fields, it should be possible to derive who the expected proposer is and if they have signed the received block.

Ref: https://github.com/tendermint/tendermint/issues/7922

**Comment by cason** [comment]
Legit.

In fact, in the code the `Hash` portion of `Proposal.BlockID` is never used, only the `PartSetHeader`.
