### ISSUE TITLE
Forward port some v0.35/v0.36 bug fix/improvement PRs to main

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#9508]
## Summary

Since v0.35/v0.36 release has been deprecated. Some PRs might be still worth bringing into `main` and won't cause trouble. 

## Proposal

forward port PRs to `main`

### IMPROVEMENTS PR
#6018 store: update store/store.go StoreBlock to use batches
#6067 state: save in batches within the state store
#5876 privval: Query validator key
#7108 refactor: assignment copies lock value in BitArray.UnmarshalJSON()
#6969 consensus: remove panics from test helper functions
#7325 internal/libs/protoio: optimize MarshalDelimited by plain byteslice allocations+sync.Pool
#7612 rpc: paginate mempool /unconfirmed_txs endpoint

### Bug fixes PR
#7642 light: Fix query against the latest state in light client
#7639 light: Fix absence proof verification by light client

**Comment by sergio-mena** [comment]
@thanethomson, do you think we could get this prioritized as part of "tech debt" in Q4?
Since users are asking for it, and it seems purely backporting, I think we could tackle it.
However some time should be planned for understanding some of those, as they are very old.

**Comment by JayT106** [comment]
@sergio-mena we could help to port these PRs, the same as porting ADR-075. But it requires core devs to have time to review it.

**Comment by sergio-mena** [comment]
Hi @JayT106, sorry for delay coming back on this.
We're doing our best to find time for reviewing PRs related to ADR-075, so TBH I don't think we have bandwidth for these PRs at present (unless they are critical, in which case, please come to our community bi-weekly, message us via Slack to add one agenda item prior to the meeting, and we can discuss synchronously).

We can reevaluate after having the first alpha/RC for v0.38.x out (end of December, or beginning of January).
