### ISSUE TITLE
add genesis_hash to genesis_chunked

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#9523]
## Summary

add the genesis hash to the genesis chunked api in order to avoid getting the entire genesis then hashing. In some cases the genesis file could be many 100 mb and potentially gigabytes big. this would avoid needing to duplicate the work that the node already has

**Comment by williambanfield** [comment]
@tac0turtle Can you provide a little more insight into the motivation behind this issue? I'm having a little bit of trouble understanding how this is intended to be used and what value it brings.

The `genesis_hash` that you're referring to, do you mean the sha256 of the genesis file?

**Comment by tac0turtle** [comment]
yea so when the endpoint is chunked you have to loop through the chunks then hash. Its an ergonomic thing

**Comment by williambanfield** [comment]
What is the hash being used for in the envisioned usecase?

**Comment by tac0turtle** [comment]
for the rosetta api, instead of asking users to provide it.

**Comment by williambanfield** [comment]
Can you link me to some documentation on this? The only current use of the hash of the genesis file is to independently verify the genesis file to ensure the file you were given matches the one you expect, so combining them seems very suspicious.

**Comment by tac0turtle** [comment]
the use case is better ux, instead of them having to find it on the web and add it to the config its automatically there. 

not sure where its in the spec (https://www.rosetta-api.org/docs/Reference.html), @rllola was needing it for rosetta

**Comment by williambanfield** [comment]
If you're going to implicitly trust the file provider is giving you the correct data, then it's better to just disable the hash check
