### ISSUE TITLE
rpc: use encoding/json rather than tmjson

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#9531]
We should try use standardised libraries when possible. This code hygiene change was initially done in v0.36

Ref: https://github.com/tendermint/tendermint/pull/7670

**Comment by peterbourgon** [comment]
> this is a quite large breaking change for clients. We opted to tmjson to avoid the breaking. Agree we should migrate away but it will be painful.

What would break, specifically?

**Comment by tac0turtle** [comment]
some json encoding is different. I think int64 is string in the current one as well. they would be small hidden changes
