### ISSUE TITLE
Let Tendermint RPC report a block's gas_wanted and gas_used

### ISSUE THREAD

**Issue by webmaster128** [tendermint/tendermint#9555]
## Summary

Chains configure a block gas limit via `consensus_params.block.max_gas`. However, I currently see no way to monitor the gas usage using Tendermint RPC.

## Problem Definition

As a user I would like to get an overview of the gas wanted and gas used values over the chain's blocks. This is important to evaluate if `consensus_params.block.max_gas` was set to a sane value and how gas usage and block times correlate. Unfortunately there seems to be no straight forward way to read those values on a per-block basis from Tendermint RPC.

Mintscan also wants to show those values here: https://www.mintscan.io/cosmos/blocks/12471351

If I had to calculate the value client-side now, I had to do the following, right?
1. Get /block_results and look into `results`
2. Sum up `gas_used` and `gas_wanted`

This seems a bit cumbersome as those values should be available at block level anyways (at least when the `max_gas` limit is checked). Also I am unsure if there is gas usage outside of transactions (like begin/end block execution).

## Proposal

Making `gas_used` and `gas_wanted` available in /block or /blockchain RPC endpoints would be much appreciated from a client library dev.

-----------

Of course, if I misunderstood something here, let me know. I'm not horribly familiar with Tendermint details. Thanks!

**Comment by aramakam3505** [comment]
Even we suggest the same.
Is there any way to get gasUsed for the block?

**Comment by webmaster128** [comment]
I copied this over to CometBFT: https://github.com/cometbft/cometbft/issues/1024
