### ISSUE TITLE
p2p: Tendermint disconnects peers running unknown reactors/channels

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#957]
Ie. if one peer runs the PEX and another doesnt, the latter will disconnect the former when it receives a PEX message: https://github.com/tendermint/tendermint/blob/master/p2p/connection.go#L468

Not sure this is something we want. What accommodations should we make for unknown reactors/channels?

**Comment by melekes** [comment]
> What accommodations should we make for unknown reactors/channels?

drop these messages?

**Comment by ebuchman** [comment]
Yeh, we just need to be careful about spam/DoS

**Comment by melekes** [comment]
Maybe we need to check if peer has pex enabled before sending plus punish peer that is trying to send us pex msg given he knows that pex disabled.

**Comment by ebuchman** [comment]
Lets add `[]Channels` to the NodeInfo struct.

Then we can make peer.Send/TrySend drop msgs for channels the peer the doesnt know about.

Then if a peer sends us a msg for a channel we don't know about, we can mark them as bad and disconnect :)

**Comment by ebuchman** [comment]
closing for PR: https://github.com/tendermint/tendermint/pull/1049
