### ISSUE TITLE
p2p/trust: in intervalToHistoryOffset use math/bits.Len(interval)-1 instead of int(math.Floor(math.Log2(float64(interval))))

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#9604]
I highly recommend using `math/bits.Len(interval)-1` instead of `int(math.Floor(math.Log2(float64(interval))))` as the former is much faster, easier to understand, less operations and sure this code isn't affected by it, but I am issuing this advisory having inspected a bunch of code that uses math.Log2(X) where X wasn't checked and 0 was passed in; very good that this repo firstly checks that interval == 0 then returns elsewhere.

**Comment by sergio-mena** [comment]
Thanks @odeke-em, the idea looks good to us.
I'll be taking a look at your PR next week.

**Comment by thanethomson** [comment]
Closing, since the (unused) p2p/trust package was removed in #9625.
