### ISSUE TITLE
active view change, to solve the problem of proposer falling behind

### ISSUE THREAD

**Issue by chengzhinei** [tendermint/tendermint#9606]
### Problem Definition

- In the  logic of consensus of Tendermint, at every height there is a validator to be the proposer and make the block. Other validators are waiting and receiving the block in the step of StepPropose, then sign the block as a valid vote. When valid votes have been collected for more than 2/3, this block is marked as a valid block.
- There is a  timeout mechanism at the step of StepPropose, it means that, if validator doesn't receive the block from proposer within the required time, it will sign a nil block as an invalid vote . As a result, it can't collect more than 2/3 valid votes, and this will lead to the ViewChange.
- If the proposer of a height falls behind or for other reasons, it may not have finished the last height, so it can't make the block of this height. As a result, other validators can't receive the block and it will lead to the ViewChange.
- ViewChange will increase the block time and reduce the tps.

### Solution
Two new consensus messages  are added:
- ProposeRequestMessage：for requesting to be the proposer of current height. Include "Height, original proposer address, new proposer address"
- ViewChangeMessage：for telling all the validators that the proposer of current height has been changed. Include "Height, original proposer address, new proposer address"

1. Every validator sends the ProposeRequestMessage(prMsg) to the original proposer after it has finished the ApplyBlock and updateToState, requests to be the proposer of current height.
2. The original proposer receives the prMsg, and it handles this prMsg depends on its current state. If the proposer already enters this height of prMsg, it ignores the prMsg and make block itself; If the proposer falls behind, it accepts the sender of the first prMsg to be the new proposer and ignores other prMsgs of this height, then broadcasts the ViewChangeMessage(vcMsg) to tell all the validators that the proposer of current height has been changed.
3. The other validators receive the vcMsg, and it updates its validator set depending on the new proposer in the vcMsg, then receives the proposal and block of the new proposer.
![image](https://user-images.githubusercontent.com/7297559/197129021-3ddf7cd6-5ef9-43a9-9019-75ec0ab00f22.png)

### Effect
we have developed this feature, and it is working well.
The results shows that when the proposer falls behind a new proposer can take its place and produce the proposal and block, as a result, no view change happened then. 
And the elapsed time of consensus improves about 37.43%.

![image](https://user-images.githubusercontent.com/7297559/199190826-1e3e5126-e744-44dc-bb83-f54226a7d5e5.png)
https://github.com/okex

**Comment by cmwaters** [comment]
Hey @chengzhinei, thanks for opening the issue. So as I understand it, this is basically an optimisation for when the proposer is behind yet still running whereby we can prevent the validators in the network from having to trigger the timeouts necessary for the view change.

To make this even simpler, the proposer could just broadcast something like `ForfeitProposalMessage` which would cause the recipients to move into the next round whereby a new proposer would be automatically elected.

I guess a question I have is how does the proposer know they are behind. Nodes will ignore votes in heights that are ahead of them. Could a malicious node potentially fool a proposer into thinking they're behind?

**Comment by chengzhinei** [comment]
> Hey @chengzhinei, thanks for opening the issue. So as I understand it, this is basically an optimisation for when the proposer is behind yet still running whereby we can prevent the validators in the network from having to trigger the timeouts necessary for the view change.
> 
> To make this even simpler, the proposer could just broadcast something like `ForfeitProposalMessage` which would cause the recipients to move into the next round whereby a new proposer would be automatically elected.
> 
> I guess a question I have is how does the proposer know they are behind. Nodes will ignore votes in heights that are ahead of them. Could a malicious node potentially fool a proposer into thinking they're behind?
Hey @cmwaters 
yes, it is an optimisation for proposer falling behind.

Q:how does the proposer know they are behind?
A:other validators will send the prMsg(include height) every height, and the proposer only handle the prMsg with the height higher than its consensus height. eg: most validator is at the height 100, and they will send the prMsg with height(100), and if the proposer is just at the height 90, it can know it is falling behind now.

Q:how to prevent  a malicious node？
A:all the validators have its pubkey for consensus, and the prMsg should be signed by the prikey. When the proposer receive the prMsg, it will verify the signature first.

![image](https://user-images.githubusercontent.com/7297559/197759633-544cb6b0-994e-405d-819f-9dd9fe1f8bf7.png)

**Comment by cmwaters** [comment]
> A:other validators will send the prMsg(include height) every height, and the proposer only handle the prMsg with the height higher than its consensus height. eg: most validator is at the height 100, and they will send the prMsg with height(100), and if the proposer is just at the height 90, it can know it is falling behind now.

Just to be more accurate about this, the proposer would need to receive at least 1/3+ `pMsg`s in voting power of a future height (to have the same fault tolerant guarantees). Given this requirement:
- Is it important that the potential proposer know that it would have been the proposer at that height? Being behind means that the potential proposer doesn't actually know what the validator set at the height he/she is supposed to propose is. How would the potential proposer calculate 1/3+?
- When do the other validators send this `ProposeRequestMessage`? Do they also wait a certain time after a round is finished? Perhaps they could go off whether they've seen a vote from the potential proposer in the previous round

**Comment by chengzhinei** [comment]
> > A:other validators will send the prMsg(include height) every height, and the proposer only handle the prMsg with the height higher than its consensus height. eg: most validator is at the height 100, and they will send the prMsg with height(100), and if the proposer is just at the height 90, it can know it is falling behind now.
> 
> Just to be more accurate about this, the proposer would need to receive at least 1/3+ `pMsg`s in voting power of a future height (to have the same fault tolerant guarantees). Given this requirement:
> 
> * Is it important that the potential proposer know that it would have been the proposer at that height? Being behind means that the potential proposer doesn't actually know what the validator set at the height he/she is supposed to propose is. How would the potential proposer calculate 1/3+?
> * When do the other validators send this `ProposeRequestMessage`? Do they also wait a certain time after a round is finished? Perhaps they could go off whether they've seen a vote from the potential proposer in the previous round

no need to receive 1/3+ prMsgs. 

Every validators include the potential proposer send the prMsg every height, and the original proposer will handle the first prMsg it received at one height, and who sent this prMsg should be the new proposer. And then the original proposer will broadcast the ViewChangeMessage(vcMsg), every other validators include the potential proposer can know who is the new proposer by vcMsg.

Validators send the prMsg(height 100) when it has finished the ApplyBlock of height 99 and after it update its state from height 99 to height 100(UpdateToState). 
The Active-View-Change only work at round 0, and other rounds keep the original view-change logic.
