### ISSUE TITLE
node: simplify construction and usage patterns

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#9627]
## Summary

Node is a messy glob of a data structure where everything in Tendermint is thrown into. As the entry point to the code base it's incredibly difficult to read and is where the most tech debt is visible as the codebase has gradually changed over time.

## Proposal

I propose a few goals around this package:
- Make the constructor lightweight and do not perform any IPC (i.e. currently we do a handshake with the application which may also involve replaying hundreds of blocks)
- Improve in-line documentation around what's happening at each stage
- Add start up phases i.e. Handshake, BlockSync, StateSync and Consensus 
- Provide the option to create a node a) by simply pointing to a filesystem, b) from a config and c) using go native data structures

**Comment by jmalicevic** [comment]
Is this related to the issues mentioned in [RFC-016](https://github.com/tendermint/tendermint/blob/main/docs/rfc/rfc-016-node-architecture.md)?

**Comment by cmwaters** [comment]
> Is this related to the issues mentioned in [RFC-016](https://github.com/tendermint/tendermint/blob/main/docs/rfc/rfc-016-node-architecture.md)?

Yes there's some overlap
