### ISSUE TITLE
pre-run block, to make the block-execution parallel with consensus

### ISSUE THREAD

**Issue by chengzhinei** [tendermint/tendermint#9636]
### BackGround
In the  logic of consensus of Tendermint, the block is assembled at the step of Propose, but it is executed after the step Prevote and step Precommit. 
The block is executed in ApplyBlock through the ABCI by the interface execBlockOnProxyApp.

### Optimization solution
Start a new goroutine(preRun routine), it is specifically used for executing the block.
At every height, when the block parts are collected and completed for a block, this block is put into the preRun routine, and after the block is finished execution, result of execution(abciResponse) will be put into a channel(taskResultChan).
In ApplyBlock, it will wait for the execution result of the preRun routine, and get the result from the channel(taskResultChan), then it continues to perform subsequent operations.
![image](https://user-images.githubusercontent.com/7297559/198230548-909ffa02-0d52-4d56-a261-4c3bcd71d33c.png)

### Special case
If the view-change happens at a height, when the block of a new round is completed, it will send a signal of stopPrerun to stop the task of this height last round in preRun routine, and the new block of new round will be put into the preRun routine
### Benefit
we have developed this feature, and it is working well.
The time of step Prevote and step Precommit can be used for executing the block, and it will reduce the block time and increase the tps.

![image](https://user-images.githubusercontent.com/7297559/199190826-1e3e5126-e744-44dc-bb83-f54226a7d5e5.png)
https://github.com/okex

**Comment by cmwaters** [comment]
Hey, this is essentially optimistic execution right? as in we're executing the block before consensus is made.

In v0.37, we've introduced `ProcessProposal` and `PrepareProposal`. With these methods, the application is able to begin to execute the block in the prevote stage (i.e. the moment the full block is received) and can provide the results of the execution upon `EndBlock` (or `FinalizeBlock` in v0.38). Would this meet your use case?

**Comment by chengzhinei** [comment]
> Hey, this is essentially optimistic execution right? as in we're executing the block before consensus is made.
> 
> In v0.37, we've introduced `ProcessProposal` and `PrepareProposal`. With these methods, the application is able to begin to execute the block in the prevote stage (i.e. the moment the full block is received) and can provide the results of the execution upon `EndBlock` (or `FinalizeBlock` in v0.38). Would this meet your use case?

Thank you for your reply!

I've seen these methods, but do not figure out how it works. 
I saw that `ProcessProposal` just responds the status of "ResponseProcessProposal_ACCEPT", but the actually executions(DeliverTx) is still in the method "ApplyBlock". Or it depends on the project `cosmos-sdk`?

Maybe you have the `issue`, `pull requests` or some documents of `ProcessProposal` and `PrepareProposal` to help me to understand it?


In `pre-run` function, just put the interfaces `execBlockOnProxyApp`(include `BeginBlock`, `DeliverTx`, `EndBlock`) into another routine to parallel with consensus, as you see in the [#9648](https://github.com/tendermint/tendermint/pull/9648), it just change the place of `execBlockOnProxyApp`.


Thanks again for your patience!

**Comment by chengzhinei** [comment]
> Hey, this is essentially optimistic execution right? as in we're executing the block before consensus is made.
> 
> In v0.37, we've introduced `ProcessProposal` and `PrepareProposal`. With these methods, the application is able to begin to execute the block in the prevote stage (i.e. the moment the full block is received) and can provide the results of the execution upon `EndBlock` (or `FinalizeBlock` in v0.38). Would this meet your use case?

hey @cmwaters ,thanks for your patience! 
I have reviewed the code and introduction of `ProcessProposal` and `PrepareProposal` yesterday.
So to my understanding, these methods are just ABCI interfaces without actually executions. If someone wants to execute the block in the prevote stage, he must develop these interfaces himself.

In short, `ProcessProposal` and `PrepareProposal` depends on the users' own development, but `pre-run` is completely an optimisation of Tendermint consensus logic and it is transparent to users.

The `pre-run` only changes little of the code, and it is not conflicting with the `ProcessProposal` and `PrepareProposal`.
Besides it has been running on OKC(https://www.oklink.com/en/okc) for a while, and is proved to be viable. 
So, i sincerely hope that you can consider this optimisation, and I will provide all what I can do.

**Comment by sergio-mena** [comment]
@chengzhinei indeed, it will be up to the application to decide _when_ it want to execute the block. `PrepareProposal` and `ProcessProposal` make the proposed block available to the application early on. If the application wants to execute it early, it can to do so, but it is not forced to do it.

The part I don't clearly see in your approach is that you assume that the application will always be interested in executing blocks as soon as they are proposed. I'm not convinced that will always be the case (it's a tradeoff between performance and complexity at the application level). Moreover, what happens in your approach when several rounds take place in a consensus height? How many blocks will the application end up executing? How will the application know which of those executions to roll back (to ensure correct state-machine replication)?

**Comment by chengzhinei** [comment]
hey, @sergio-mena  thanks for your reply.

The application should only care the service logic and Tendermint should decides when to execute ABCI(It is Tendermint decides BeginBlock/DeliverTx/EndBlock before). For application, they do not care the logic of consensus, so as soon as possible to execute block is just about performance and it should has no matter with the Applicaition.

In fact, in most cases, the probability of veiw-change happening is very low. And if the veiw-change happened, only the last round block is valid,  when the preRun-routine receive a new block of new round at the same height, it will stop the task of this height last round in preRun routine, and the new block of new round will be put into the preRun routine as a new task. A task is just to invoke the interface `execBlockOnProxyApp`, and it include BeginBlock, DeleverTx, EndBlock, and in `BeginBlock`, the deliverState is reinitialized, and only the last round of block(the valid block) changes the deliverState sothat ensure the correct state-machine replication. And the application no need to roll back, it is transparent to application.

As all I said, the `pre-run` has been running on OKC for a long time, and it performs very well. And it can improves the TPS about 50%+.
The code changes are very small, and the performance optimization effect is very obvious.
Any other concerns may I solve for you? And Thank you again~
![image](https://user-images.githubusercontent.com/7297559/199670366-6b96d25f-460c-4365-bed5-6ea298e8e1c4.png)

**Comment by tac0turtle** [comment]
Interesting issue. I don't see how tendermint can force this on the application. Prepare and process are steps into this direction as tendermint making an assumption about application execution should not happen. In the sdk we pln on incorporating optimistic execution but this doesn't require any changes to tendermint so I'm not sure what exactly is being proposed here? Is it something different than optimistic execution? 

 Applications can run begin block after the last block committed today without the new abci interface methods.

**Comment by chengzhinei** [comment]
> Interesting issue. I don't see how tendermint can force this on the application. Prepare and process are steps into this direction as tendermint making an assumption about application execution should not happen. In the sdk we pln on incorporating optimistic execution but this doesn't require any changes to tendermint so I'm not sure what exactly is being proposed here? Is it something different than optimistic execution?
> 
> Applications can run begin block after the last block committed today without the new abci interface methods.

I'm curious about how you can incorporate optimistic execution in the sdk? This sdk you mean `cosmos-sdk`? But I don't see the possible to achieve it without the Application's development.

To my understanding, the Application has to develop the `PrepareProposal` and `ProcessProposal` themself. And these two interface are new ABCI interface.

`pre-run` has two different points: 
1. less changes: all the code changes you can see in the [#9648](https://github.com/tendermint/tendermint/pull/9648), and it doesn't require any changes to any other place include the sdk or the Application.
2. better performance: because it leaves out performance cost of invoking the ABCI, all the consensus logic is guaranteed in Tendermint.

**Comment by sergio-mena** [comment]
@chengzhinei I think the positions are clear by now in this discussion. If you would like to further discuss this point, you are welcome to attend our bi-weekly community call. That'll probably be more efficient.

**Comment by tac0turtle** [comment]
> `pre-run` has two different points:
> 
> 1. less changes: all the code changes you can see in the [#9648](https://github.com/tendermint/tendermint/pull/9648), and it doesn't require any changes to any other place include the sdk or the Application.
> 2. better performance: because it leaves out performance cost of invoking the ABCI, all the consensus logic is guaranteed in Tendermint.

Ah I see what you are doing now. This is basically the same optimistic execution just in a simpler way. This makes sense to me and is a valid proposal. Wonder why it never came up before. 

 I think with the new abci path allows the application the option of either, while in this way it would need to be a consensus param.

**Comment by chengzhinei** [comment]
> @chengzhinei I think the positions are clear by now in this discussion. If you would like to further discuss this point, you are welcome to attend our bi-weekly community call. That'll probably be more efficient.

Thanks for the advice, and it is so nice and honor if I have this chance to communicate with you.
And may I ask how to attend our bi-weekly community call? Thank you so much!

**Comment by chengzhinei** [comment]
> > `pre-run` has two different points:
> > 
> > 1. less changes: all the code changes you can see in the [#9648](https://github.com/tendermint/tendermint/pull/9648), and it doesn't require any changes to any other place include the sdk or the Application.
> > 2. better performance: because it leaves out performance cost of invoking the ABCI, all the consensus logic is guaranteed in Tendermint.
> 
> Ah I see what you are doing now. This is basically the same optimistic execution just in a simpler way. This makes sense to me and is a valid proposal. Wonder why it never came up before.

Thanks for your affirmation!
After we finish this optimistic, we keep it running on our OKC for a while to guarantee this change is available and effective.
And now it has been proved valid, so we want to make a contribution to Tendermint.

> 
> I think with the new abci path allows the application the option of either, while in this way it would need to be a consensus param.

Yes, this is a very clear understanding

**Comment by sergio-mena** [comment]
> it is so nice and honor if I have this chance to communicate with you.

The honor is ours :-)

> And may I ask how to attend our bi-weekly community call? Thank you so much!

If you give us an email, we can include you in the calendar invite. Alternatively,
* [This](https://www.google.com/url?q=https://us02web.zoom.us/j/83266817964?pwd%3DREg0eENGYmNwY1daV1JYVjdKdHIwZz09&sa=D&source=calendar&ust=1668371749104791&usg=AOvVaw2Jt2Z032pbhG03DE4eVAfU) is the Zoom link
* It takes place tomorrow (Thu 2022-11-10) at 16:00 GMT, then every two weeks

**Comment by chengzhinei** [comment]
> 
> If you give us an email, we can include you in the calendar invite.

Thank you so much!
And this is my email: chengxue5yuan@163.com

Besides, a few colleagues can have better communication than me and they may attend the community call together.

**Comment by cmwaters** [comment]
Hey again, I took some time this morning to go through your implementation. There are a few edge cases to be wary of e.g. what if we reach consensus on a block but are still in the process of executing a block from an earlier around or the other way, what if we agree with an earlier block that is different to the latest one that was executed (specifically when it comes to saving ABCI responses) but on the whole the rationale seems sound.

My chief concern with this change is that it modifies the _grammar_ of the tendermint consensus protocol, specifically it is understood that applications should only ever receive `FinalizeBlock` (or `BeginBlock`, `DeliverTx`, `EndBlock`) once per height. Applications would have to be reconfigured to be able to execute multiple states off from a common root and then once `Commit` is called, persist the state aligning with the block that was actually committed. This is all to say that we can make that semantic change if we want to but it does seem as though `PrepareProposal` and `ProcessProposal` can allow for the application to do the same (albeit with a little more code on the application side), so the question is more of a product perspective: how many execution patterns does Tendermint want to support and how many ways do we allow that?

**Comment by sergio-mena** [comment]
We reached the following conclusions during today's synchronous discussion:
* We agree that the mechanism proposed here works, and improves the performance of the application, but requires the application to be ready to roll back its state, when the local Tendermint requires a multi-round height.
* Forcing applications to handle several `BeginBlock`-`DeliverTx`-`EndBlock` cycles for a single height:
  * Breaks the current ABCI specification (see [here](https://github.com/tendermint/tendermint/blob/6371f02/spec/abci/abci%2B%2B_tmint_expected_behavior.md#valid-method-call-sequences))
  * Would probably cause some friction on simpler applications that don't necessarily use the SDK. This could nevertheless be addressed with a newly introduced consensus param having the right default value.
* ABCI 1.0, which is part of v0.37.0, is offering a similar mechanism via `PrepareProposal` and `ProcessProposal` where the application has the choice of leveraging this or not, thus causing less friction in the app's logic.

Following this, we will close this issue.

Finally, we would like to thank the creators of this issue for the idea proposed (if we hadn't introduced ABCI++, we would probably have taken it). Keep up the good work!
