### ISSUE TITLE
rpc: should not cache check-tx result

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#9689]
#9650 enable the rpc caching support. However, just found the `check-tx` call should rely on the current chain state (thanks @yihuang ). So it should not be cached in the cache server.

**Comment by thanethomson** [comment]
Thanks @JayT106. Looking at the remaining endpoints for which cache control is enabled, are all the others correctly configured?

**Comment by JayT106** [comment]
Yes, the remaining endpoints can be cached whatever the chain state.
