### ISSUE TITLE
`tendermint lite init` and fix the proxy

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#970]
Running the lite proxy requires an init step that's currently insecurely skipped.

Also some code is commented out to make it (insecurely) work without init

**Comment by zramsay** [comment]
running `tendermint lite` i get `WARNING (tendermint/rpc/lib): Please use fully formed listening addresses, including the tcp:// or unix:// prefix module=main `

**Comment by odeke-em** [comment]
>Running the lite proxy requires an init step that's currently insecurely skipped.
>Also some code is commented out to make it (insecurely) work without init

Could you please elaborate on what this means? That would be nice for easy pickup of the work by anyone such as me as well as new Tendermint coders i.e. that isn't always looking at the code, thank you!

**Comment by odeke-em** [comment]
Okay I found some context for this issue:
a) Lite proxy requires an init step that's currently insecurely skipped
https://github.com/tendermint/tendermint/blob/3d5c05e4e642d236a718ccf3aa228d7d72c8d90b/lite/proxy/certifier.go#L17-L27

which was added in https://github.com/tendermint/tendermint/commit/11761d17698151166af94219d2b53f40b1be546c

**Comment by odeke-em** [comment]
@zramsay your concern in https://github.com/tendermint/tendermint/issues/970#issuecomment-358785802
>running tendermint lite i get WARNING (tendermint/rpc/lib): Please use fully formed listening addresses, including the tcp:// or unix:// prefix module=main

has been addressed in https://github.com/tendermint/tendermint/pull/1297

**Comment by jackzampolin** [comment]
Closing this issue as addressed. Please reopen if I'm wrong.
