### ISSUE TITLE
Rollback doesn't work when validators don't synchronize

### ISSUE THREAD

**Issue by robert-zaremba** [tendermint/tendermint#9715]
**Tendermint version**  `0.34.21`

**ABCI app** Umee

**Environment**: 
- **OS**  Ubuntu

**What happened**:

* We had an tendermint state hash mismatch problem (gas consumption), and had to rollback the chain
* validators didn't collaborate, for a moment we had enough validators to produce one block, but the other validators who joined couldn't verify it, getting the following error

```
Sep 28 18:37:09 umee-validator-taxi umeed[26504]: 6:37PM INF Timed out dur=2000 height=3216274 module=consensus round=2 step=7
Sep 28 18:37:09 umee-validator-taxi umeed[26504]: 6:37PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"3D271B242FE424FA481E37F20C7C3C2B0D9ABF2714D79A509F9247EF456B8992","parts":{"hash":"C1FB6796A6B0DBAE193304ACEFF5EDFFA7A77961069A2D6C52D63F8B403DCCDC","total":4}},"height":3216274,"pol_round":-1,"round":3,"signature":"M+Vy==","timestamp":"2022-09-28T18:37:08.712034856Z"}
Sep 28 18:37:10 umee-validator-taxi umeed[26504]: 6:37PM INF received complete proposal block hash=3D271B242FE424FA481E37F20C7C3C2B0D9ABF2714D79A509F9247EF456B8992 height=3216274 module=consensus
Sep 28 18:37:11 umee-validator-taxi umeed[26504]: 6:37PM INF finalizing commit of block hash={} height=3216274 module=consensus num_txs=534 root=6698494A87E3922C323A302FC5F664A977789B308C225F3FC8B40F8A3F9F1923

Sep 28 18:37:11 umee-validator-taxi umeed[26504]: 6:37PM ERR CONSENSUS FAILURE!!! err="couldn't find validators at height 3216272 (height 3216273 was originally requested): %!w(<nil>)" 
```

My interpretation:
1. We were able to produce block *73 (3216273)
2. Some validators joined later and were still syncing after the rollback
3. They received block *73 and now they want to validate it
4. Since they made rollback for block ...72, they wiped out the state at block  72
5. Tendermint, when trying to validate block ...73 tries to load the state at current block (...73) or the previous one ...72.  Now, since the tendermint state `*72` was wiped out by rollback, and they didn't participate at the consensus for 73, they don't have state .

Sounds like we can request those validators to fully resync using the fast sync.
1. Only use healthy nodes to resync
2. To resync you need to wipe your data directory, by you need to KEEP your private val json file. (copy val file and use `umeed tendermint unsafe-reset-all`)

More context: (Umee validator discord channel): https://discord.com/channels/815699313581490196/940283450089435216/1024760992980271185

**What you expected to happen**:

All validators are able to handle rollback, even if they join late.

**Have you tried the latest version**: yes

**How to reproduce it** 
1. Halt the chain with tendermint state missmatch
2. Rollback
3. be able to produce one block with 67% of the network
4. remove one validator (causing less than 66% support)
5. ask other validators to join

**Anything else we need to know**:

We have been already discussing this issue in Cosmos SDK. Seams like that we need to consider redesign of `rollback`.

Related:
* https://github.com/tendermint/tendermint/issues/9174

**Comment by cmwaters** [comment]
Hey Robert, thanks for posting the issue. I'm a little confused still so do you mind clarifying some things:
1. Did the network commit the block with the non-deterministic hash or were validators unable to reach consensus and so just incremented through the rounds?
2. With the CONSENSUS FAILURE you're showing, can you provide the entire stack trace?
3. Rollback doesn't actually delete the validator set from the db (which perhaps it should because these could be invalid when the application reapplies the same block) so I don't know how those validators ended up missing the validator set at that height


As a helpful note, v0.37.1 onwards will include a `--hard` flag which rollbacks both state and block (however this shouldn't be performed network wide, only for individual validators. It's dangerous to delete blocks). See https://github.com/tendermint/tendermint/pull/9261.

If you think it would help, you're welcome to discuss this at our community call. Just let me know you're email if you're not yet invited and we can add you.

**Comment by robert-zaremba** [comment]
Sorry for later response.

1. Somehow 1 block was produced and then it sucked with the non-deterministic hash error
2. no, we don't have it nay more
3. since a new block was produced, validators who didn't participate in consensus during that time, and rolled back to the previous verision, couldn't get the active val set and validate the new block (n+2, where n=block number after rollback). So basically, n=block after rollback. n+1 = repeated block (from rollback), n+2 = new block which was created.

**Comment by robert-zaremba** [comment]
Here is a longer copy of the log I had in my notes:
```
Sep 28 18:37:09 umee-validator-taxi umeed[26504]: 6:37PM INF Timed out dur=2000 height=3216274 module=consensus round=2 step=7
Sep 28 18:37:09 umee-validator-taxi umeed[26504]: 6:37PM INF received proposal module=consensus proposal={"Type":32,"block_id":{"hash":"3D271B242FE424FA481E37F20C7C3C2B0D9ABF2714D79A509F9247EF456B8992","parts":{"hash":"C1FB6796A6B0DBAE193304ACEFF5EDFFA7A77961069A2D6C52D63F8B403DCCDC","total":4}},"height":3216274,"pol_round":-1,"round":3,"signature":"M+Vy==","timestamp":"2022-09-28T18:37:08.712034856Z"}
Sep 28 18:37:10 umee-validator-taxi umeed[26504]: 6:37PM INF received complete proposal block hash=3D271B242FE424FA481E37F20C7C3C2B0D9ABF2714D79A509F9247EF456B8992 height=3216274 module=consensus
Sep 28 18:37:11 umee-validator-taxi umeed[26504]: 6:37PM INF finalizing commit of block hash={} height=3216274 module=consensus num_txs=534 root=6698494A87E3922C323A302FC5F664A977789B308C225F3FC8B40F8A3F9F1923

Sep 28 18:37:11 umee-validator-taxi umeed[26504]: 6:37PM ERR CONSENSUS FAILURE!!! err="couldn't find validators at height 3216272 (height 3216273 was originally requested): %!w(<nil>)" 
```
And my interpretation:
1. We were able to produce block *73
2. Some validators joined later and were still syncing after the rollback
3. They received block *73 and now they want to validate it
4. Since they made rollback for block ...72, they wiped out the state at block  72
5. Tendermint, when trying to validate block ...73 tries to load the state at current block (...73) or the previous one ...72.  Now, since the tendermint state `*72` was wiped out by rollback, and they didn't participate at the consensus for 73, they don't have state .
