### ISSUE TITLE
github.com/cosmos/cosmos-sdk/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.6), but does not contain package github.com/cosmos/cosmos-sdk/client/rest

### ISSUE THREAD

**Issue by myfirst-crypto** [tendermint/tendermint#9721]
there are many similar errors like:
github.com/cosmos/cosmos-sdk/client/rest: module github.com/cosmos/cosmos-sdk@latest found (v0.46.6), but does not contain package github.com/cosmos/cosmos-sdk/client/rest
github.com/tendermint/tendermint/state: module github.com/tendermint/tendermint@latest found (v0.35.9), but does not contain package github.com/tendermint/tendermint/state
google.golang.org/grpc/credentials/insecure: module google.golang.org/grpc@latest found (v1.51.0, replaced by google.golang.org/grpc@v1.33.2), but does not contain package google.golang.org/grpc/credentials/insecure
...
when I try to import tendermint in my project, anyone could help me? thanks you so much

**Comment by thanethomson** [comment]
I suspect you need to specify a specific version of Tendermint that you want to import. It seems as though you're trying to import Tendermint v0.35, which was deprecated as per #9155.

**Comment by tac0turtle** [comment]
this feels like a duplicate of https://github.com/tendermint/tendermint/issues/9355

to fix the issue you are having, run

`go get github.com/tendermint/tendermint@v0.34.22` this will solve the immediate issue
