### ISSUE TITLE
Support fgprof for profiling

### ISSUE THREAD

**Issue by v-homsi** [tendermint/tendermint#9722]
## Summary

Add support for fgprof as it enables on and off cpu profiling. The builtin profiler only show on-cpu time which is misleading. 

https://github.com/felixge/fgprof 

## Problem Definition

The builtin profiler that tendermint uses is misleading as cpu time spent waiting on I/O is not accounted for.

The problem is best explained in [here](https://github.com/felixge/fgprof#the-problem)

## Proposal

Add the handler 
```
http.DefaultServeMux.Handle("/debug/fgprof", fgprof.Handler())
```
https://github.com/tendermint/tendermint/blob/main/node/node.go#L685

**Comment by peterbourgon** [comment]
> The builtin profiler that tendermint uses is misleading as cpu time spent waiting on I/O is not accounted for.

Do you have `fgprof` profiles which demonstrate this is the case?
