### ISSUE TITLE
security: audit all our vendors for usage of rand.Seed to see if their changes can potentially revert to known seeds

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#973]
I had initially filed this internally. I stumbled onto this a few hours ago while auditing (*tmlibs.BitArray).PickRandom https://godoc.org/github.com/tendermint/tmlibs/common#BitArray.PickRandom.

### Problem Statement
Currently for crypto/rand seeded PRNG, we use tmlibs'
[1] https://github.com/tendermint/tmlibs/blob/bfcc0217f120d3bee6730ba0789d2eb72fc2e889/common/random.go#L13-L21
<img width="408" alt="screen shot 2017-12-13 at 10 59 17 am" src="https://user-images.githubusercontent.com/4898263/33954184-b49eea7c-dff4-11e7-9492-d93563262e19.png">

and from then on in our application there are usages of math/rand.R*. However, some of our dependencies reset the seed such as
```shell
$ grep -nR 'func init' * | cut -d":" -f1 | while read F;do grep -Rn 'Seed(' "$F";done
vendor/github.com/btcsuite/btcd/database/internal/treap/common.go:135:    rand.Seed(time.Now().UnixNano())
vendor/github.com/btcsuite/btcd/database/internal/treap/common_test.go:120:    rand.Seed(0)
vendor/github.com/btcsuite/btcd/peer/peer.go:2171:    rand.Seed(time.Now().UnixNano())
vendor/github.com/btcsuite/btcd/rpcserver.go:4253:    rand.Seed(time.Now().UnixNano())
vendor/github.com/jmhodges/levigo/leveldb_test.go:14:    rand.Seed(int64(time.Now().Nanosecond()))
vendor/github.com/tendermint/go-crypto/hd/hd_test.go:63:        seed := bip39.NewSeed(d.Mnemonic, "")
vendor/github.com/tendermint/go-crypto/hd/hd_test.go:123:    _, priv, ch, _ := ComputeMastersFromSeed(string(seed))
vendor/github.com/tendermint/go-crypto/random.go:37:// This uses the OS and the Seed(s).
vendor/github.com/tendermint/tmlibs/common/random.go:20:    rand.Seed(int64(seed))
```

narrowed down to
```shell
vendor/github.com/btcsuite/btcd/database/internal/treap/common.go:135:    rand.Seed(time.Now().UnixNano())
vendor/github.com/btcsuite/btcd/database/internal/treap/common_test.go:120:    rand.Seed(0)
vendor/github.com/btcsuite/btcd/peer/peer.go:2171:    rand.Seed(time.Now().UnixNano())
vendor/github.com/btcsuite/btcd/rpcserver.go:4253:    rand.Seed(time.Now().UnixNano())
vendor/github.com/jmhodges/levigo/leveldb_test.go:14:    rand.Seed(int64(time.Now().Nanosecond()))
```

### Implications
Later on, if someone wants to inject the original behavior `rand.Seed(1)` https://golang.org/pkg/math/rand/#Seed as the default predictable PRNG back,
inside their imports, bury a dependency with a messed up and lexicographically weird name that imports the last and in there do something like this
```go
func init() {
     rand.Seed(1)
}
```

and we are back to the PRNG that is predictable and susceptible to attacks and in the entire binary
the current benefit with the code in our init in is that the random generator is safe for concurrent usage but the downside is a nefarious person modifying our deps or even just patching the binary to change that symbol to `1` then we are caput, which is averse the entire way. This is why signing binaries is quite important. While it seems far fetched, a man-in-the-middle proxy can look for and change such symbols to revert to the PRNG behavior such as by applying such a diff https://gist.github.com/odeke-em/e1270bcaab2f1d113f904199e05a6732 which in that demo produces a file of the same size but obviously different checksums.

It reminds me of a post that I read https://googleprojectzero.blogspot.ca/2017/10/using-binary-diffing-to-discover.html in which they used a binary diffing tool to figure out vulnerabilities that Microsoft had patched in supported versions but hadn't backported to older versions that originated from the somewhat same codebase.

### Proposed fix
I was thinking perhaps for the start of a lighter fix which is:
* audit usages of rand.R\*
* replace that with our own rand.Rand instance and protect it with a mutex for concurent usage, giving the same guarantees as the one from the stdlib
* figure out how expensive those fixes in each vendor will be, and then fork and fix those repos

**Comment by petabytestorage** [comment]
rather than trying to "fix" other deps (which seems impossible) i think we need to move away from `rand.Rand` if we want a safer rng. that safer RNG needs to have a non-exported seeding mechanism that is also unavoidable by virtue of being in the constructor that is constrained to be singleton i would presume.

**Comment by odeke-em** [comment]
Exactly @petabytestorage, that's the eventual goal and I had that as a thought which I mention that in tmlibs https://github.com/tendermint/tmlibs/issues/99. My initial proposed fix would be to gradually roll this out, but for sure, us implementing our own Source would be the best way.

**Comment by jaekwon** [comment]
https://github.com/tendermint/tmlibs/pull/121

Rand* are not for uses related to security.  It's useful for testing.

We should be able to seed it.  This PR adds support for *Rand objects to create new sources that can be optionally seeded.

The tests don't seem to do what it proposes to do.  I will fix the tests as well.
