### ISSUE TITLE
Simplify Tendermint database engine support

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9749]
Supersedes #6032, breaking that issue down into more concrete, clearly separated deliverables/sub-tasks.

It's ultimately expensive and painful for the team to have to cater to many different use cases that require different underlying storage engines, and we would rather converge on a single database that meets our core requirements well. We do, however, want to simultaneously provide ways for integrators to access and transform core data into whatever storage system suits their use case.

## Problems

1. Through [tm-db](https://github.com/tendermint/tm-db), Tendermint currently supports multiple database backends. As such:
   1. Tendermint does not make extensive use of database-specific optimizations.
   2. Storage behavior is not consistent across different databases, potentially resulting in more troubleshooting and bug fixing work for the team (e.g. #8416).
2. While we could just decide to only support GoLevelDB (as per #9741), one of the most commonly used underlying databases for Tendermint, it seems to struggle with pruning (see #9743). It's also not clear, given our typical storage workloads for the most common use cases, whether the underlying data structure that LevelDB provides is even suitable for Tendermint. Current problems experienced by operators seem to suggest otherwise.
3. It's also not clear whether it makes sense for Tendermint to support event indexing - another source of storage space consumption, and something that is actually more of an application-level concern. #9437 is work towards designing one possible solution that will allow us to offload that responsibility to an external process in a consistent way across Tendermint-based networks.
4. We currently do not have a very clear set of requirements for an underlying database for Tendermint.
5. Tendermint currently maintains its own [WAL](https://github.com/tendermint/tendermint/blob/101bf50e715d6a10c8135392166c35bdae94972e/consensus/wal.go) - is this even necessary, given that the underlying database should actually be taking care of this? It is another source of complexity and potential point of failure in the system that the team has to maintain.

[RFC-001](https://github.com/tendermint/tendermint/blob/main/docs/rfc/rfc-001-storage-engine.rst) provides some more detail around the problem space.

## Work Breakdown

In order to achieve our overall goal of storage simplification, we need to complete the following work.

- [ ] #9750
- [x] #9944
- [ ] Provide a mechanism to offload event indexing
- [ ] Refactor Tendermint to use a single underlying database

**Comment by yihuang** [comment]
Just saying, [rocksdb FIFO compaction style](https://github.com/facebook/rocksdb/wiki/FIFO-compaction-style) is a better fit for the pattern of block store and block result store.

**Comment by JayT106** [comment]
> For the pattern of block store and block results, [rocksdb FIFO compaction style](https://github.com/facebook/rocksdb/wiki/FIFO-compaction-style) is a better fit to have minimal compaction overhead. Or simply store in plain files.

The concern for adapting Rocksdb as tendermint DB engine is that it's not a pure-go implementation I guess. So it's more complicated when building projects on top of tendermint across different platforms?

> relational database backend will be convenient for some query service providers.

The current psql indexer provided most use cases for query block & tx events and data. But it requires implementing the SQL query from the psqlDB directly instead of query data from the indexer, it's designed on purpose.
However, if we need more query data related to the block details, e.g. parts of the block_result or the block data, we will require to call RPC to get the whole picture in the current codebase. Maybe when doing ADR-082, is able to stream block_result or whole block data to offload the queries directly to the tendermint backend DB.

**Comment by JayT106** [comment]
#8014 also has some context to discuss the database engine support concerns.
