### ISSUE TITLE
bump github.com/btcsuite/btcd to 0.23.2 or latest version in v0.37

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#9783]
When porting a feature into the Cosmos SDK `main` branch, it depends on tendermint v0.37.0-rc1, which uses `github.com/btcsuite/btcd v0.22.3`. The version has been reported as a [critical vulnerability](https://github.com/advisories/GHSA-2chg-86hq-7w38). Therefore, there are few Cosmos PRs failed the CI module dependency check. 

ref: https://github.com/cosmos/cosmos-sdk/actions/runs/3562031520/jobs/5983425243#step:4:8
  
## Proposal
the current tendermint `main` merged #9250 and bumped `btcd` to the latest version. Not sure if is it okay to backport it to v0.37.x

**Comment by julienrbrt** [comment]
+1, this is blocking and counting:
- https://github.com/cosmos/cosmos-sdk/pull/13701
- https://github.com/cosmos/cosmos-sdk/pull/13724
- https://github.com/cosmos/cosmos-sdk/pull/14059

**Comment by tac0turtle** [comment]
+1

**Comment by sergio-mena** [comment]
Closed by #9784 and #9787
