### ISSUE TITLE
Retry timeout requests for Statesync

### ISSUE THREAD

**Issue by chillyvee** [tendermint/tendermint#9798]
## Summary

During statesync, RPC requests timeout (context deadline exceeded) even though a manual curl/GET will respond immediately

## Problem Definition

Polkachu has a path to minimally reproduce the problem on the evmos network
A common is a lack of response (even if context deadline is increased to 100seconds):

```
failed to fetch and verify app hash err="failed to obtain the header at height #7879461: post failed: Post \"https://evmos-rpc.polkachu.com:443\": context deadline exceeded" module=statesync server=nodeShow context
```

Instructions:
https://polkachu.com/state_sync/evmos

The RPC to use is:
https://evmos-rpc.polkachu.com:443

This RPC also has similar problems:
https://rpc-evmos-ia.cosmosia.notional.ventures:443

The Peer to use is:
425b9969981dd38bbc53c0f3f01593fdca631667@65.108.131.174:13456

Let's see if we can get Polkachu to give any additional details such as nginx configuration.

## Proposal

Determine if a retry should be performed.

Determine whether the problem is requester, network, or busy rpc server in nature

**Comment by thanethomson** [comment]
How often does this happen? And does this entirely prevent state sync from working at all, or is this an intermittent problem?

**Comment by PolkachuIntern** [comment]
@chillyvee The rate limit of our RPC/API endpoints is typically 30 requests per minute on a rolling basis. 

It seems that this rate-limiting setting works for most chains as we state-sync our nodes periodically without issues. The problem probably occurs to chains with many chunks to download (like Evmos). 

A potential solution is to handle the 429 more gracefully by falling back to the secondary state-sync RPC node (assuming the user uses two different state-sync RPC nodes in the config.toml file.

**Comment by PolkachuIntern** [comment]
Yeah, Evmos state-sync is not working for me as of yesterday. The error message is as posted by @chillyvee. I remember that there is another chain facing the same issue, although I cannot recall which one at this moment. When the error happens, I have not found a good way to overcome it. 

I am not knowledgable enough to know why this is the case. Chilly's explanation about "rpc/witness failure" makes sense to me.

**Comment by thanethomson** [comment]
It's not clear to me yet whether this is an issue with Tendermint or your operational setup.

Are the requests timing out at your Nginx instance, or are they timing out between Nginx and the node?

**Comment by chillyvee** [comment]
The context timeout is technically at Tendermint's light client, but the root cause can be almost anywhere.

Have you been able to see the problem yourself using the statesync info above?

**Comment by thanethomson** [comment]
I don't have access to your Nginx setup (nor do I want that), so there's no way for me to triage it. We also don't have capacity to triage people's operational setups - we're a small team with limited capacity.

We rely on users to triage the issues to the point that issues are reproducible with a Tendermint node only. So unless you can provide such information, there isn't much more we can do to help you.

**Comment by chillyvee** [comment]
It should be possible to recreate the problem without the chain.

Any tips on starting statesync with tendermint only without the chain app code?  

Happy to try :)

**Comment by thanethomson** [comment]
A start would be to try to sync from the node directly (with app chain code), without any reverse proxy in between, and see if the same issue occurs. Is that possible?

**Comment by chillyvee** [comment]
Will ask Polka to try since he might be the one with the closest config.

**Comment by PolkachuIntern** [comment]
Just state-synced an evmos mainnet node with the naked RPC port from the state-sync node. So the `context deadline exceeded` issue was related to the Nginx reverse proxy.

**Comment by chillyvee** [comment]
Good to know!  So we're narrowing down the source of the problem.

**Comment by yihuang** [comment]
I seems usually due to rate limiting setting in reverse proxy.
