### ISSUE TITLE
p2p: peer.Key() uses pubkey but pex_reactor does lookups via address

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#982]
Key() is pubkey: https://github.com/tendermint/tendermint/blob/master/p2p/peer.go#L212

but pex reactor uses IP: https://github.com/tendermint/tendermint/blob/master/p2p/pex_reactor.go#L267

This causes the pex to try dialing all the peers we're already connected to.

Either we change the Key() to be the address, or we store the PubKey in the address book too

**Comment by odeke-em** [comment]
@ebuchman how did you find this? Auditing with eyeballing?

**Comment by ebuchman** [comment]
I noticed that peers were dialing eachother in the pex reactor test when they were already connected, and then read the code and found it!

**Comment by odeke-em** [comment]
Oh crap, is there something that we can do to perhaps detect such or perhaps make an integration test later on?

**Comment by paralin** [comment]
Is there a fix?

**Comment by melekes** [comment]
Just looked up how libp2p does this. It seems like they take hash from pubkey for peer identity (there are other methods): https://github.com/libp2p/go-libp2p-peer/blob/master/peer.go#L194

```

In P2P networks which distribute resources of dubious legality, the issue of lack of anonymity becomes apparent. For example, the BitTorrent file sharing system directly exposes the IP address of peers to each other in a swarm. This would allow peers in the swarm to know the identity of other peers who are downloading certain resources, for example. Once the peer's identity is compromised, further attacks, whether physical or legal, can continue to be directed at that specific target.
```
http://www.cse.wustl.edu/~jain/cse571-07/ftp/p2p/#privacy

They use https://github.com/multiformats/go-multiaddr in their addrbook.

**Comment by melekes** [comment]
Also good reading: A Sybilproof Distributed Identity Management for P2P Networks http://ieeexplore.ieee.org/document/4625694/

**Comment by ebuchman** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/1048
