### ISSUE TITLE
panic: WaitGroup is reused before previous Wait has returned in MemPool reactor

### ISSUE THREAD

**Issue by paralin** [tendermint/tendermint#985]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

v0.14.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

Source unavailable

**Environment**:
- **OS** (e.g. from /etc/os-release):

Gentoo

**What happened**:

Panic observed inside the MemPool reactor, appears to be some mishandling of a `WaitGroup`

**How to reproduce it** (as minimally and precisely as possible):

Normal operations of an app.

**Stack trace**

```
panic: sync: WaitGroup is reused before previous Wait has returned

goroutine 1885 [running]:
sync.(*WaitGroup).Wait(0xc42586d060)
	/usr/lib64/go/src/sync/waitgroup.go:133 +0xbb
project/vendor/github.com/tendermint/tmlibs/clist.(*CList).FrontWait(0xc423b0fa70, 0xc42cf139f0)
	/project/_output/local/go/src/project/vendor/github.com/tendermint/tmlibs/clist/clist.go:173 +0x2d
project/vendor/github.com/tendermint/tendermint/mempool.(*Mempool).TxsFrontWait(0xc423fac580, 0x1)
	/project/_output/local/go/src/project/vendor/github.com/tendermint/tendermint/mempool/mempool.go:180 +0x2f
project/vendor/github.com/tendermint/tendermint/mempool.(*MempoolReactor).broadcastTxRoutine(0xc426e213e0, 0x7ff13a1e2bd0, 0xc42984b830)
	/project/_output/local/go/src/project/vendor/github.com/tendermint/tendermint/mempool/reactor.go:127 +0x25d
created by project/vendor/github.com/tendermint/tendermint/mempool.(*MempoolReactor).AddPeer
	/project/_output/local/go/src/project/vendor/github.com/tendermint/tendermint/mempool/reactor.go:63 +0x63

```

**Comment by ebuchman** [comment]
Wow. Can you clarify how to reproduce this? We have not seen such a thing. Granted I don't think any of us have run on Gentoo.

**Comment by melekes** [comment]
```
Calling Add again while the Wait is still in the process of resolving is what triggers the error, but more importantly, it probably just plain isn't what you want.
```

https://stackoverflow.com/questions/39800700/waitgroup-is-reused-before-previous-wait-has-returned

**Comment by ebuchman** [comment]
@paralin can you let us know if you can replicate this on 0.13.0? Theres some new code in 0.14 that might explain this, but needs some investigation. Knowing it worked on 0.13 would help tremendously.

Thanks.

**Comment by odeke-em** [comment]
@ebuchman I've started a Dockerfile with
```
FROM gentoo/stage3-amd64
ADD ./tendermint .
CMD ["./tendermint", "--home", ".tendermint", "unsafe_reset_all"]
CMD ["./tendermint", "--home", ".tendermint", "node"]
```

```shell
$ docker build -t tgc .
$ docker run -p 46658:46658 tgc
ERROR: Failed to create node: Couldn't read GenesisDoc file: open .tendermint/genesis.json: no such file or directory
```

but I am still blocked on https://github.com/tendermint/tendermint/issues/989 before we can stand up some Docker images to reproduce such issues.

**Comment by paralin** [comment]
@odeke-em You can't have two CMD lines in a Dockerfile.

@ebuchman I can try to reproduce on v0.13. It's a bit hard to reliably reproduce it in any case, it's a random error.

To be honest I would just rewrite that bit of code, use something else or some other pattern, but in any case the WaitGroup mechanism in use is pretty buggy. Replacing it completely would ensure the problem is fixed :)

**Comment by odeke-em** [comment]
Oops sorry about that, was freestyle typing out the commands, thanks @paralin :) We've found and fixed the issue so I'll perhaps put up a Dockerfile later tonight when I circle back to this issue.

**Comment by odeke-em** [comment]
@paralin how many CPU cores does your machine have? More than 4?

**Comment by paralin** [comment]
@odeke-em MacBook Pro Retina 13inch late 2015

Running Gentoo

**Comment by odeke-em** [comment]
@paralin could you please run this command to find out the number of processors?
```shell
$ system_profiler | grep Processor
```

**Comment by odeke-em** [comment]
And I've also filed https://github.com/tendermint/tmlibs/issues/112

**Comment by odeke-em** [comment]
@paralin here is a test from the Go tree that can help give hints for us to repro that test; like I suspected, it requires a bunch of concurrency to reproduce this as we've got to make *sync.WaitGroup.Wait or *sync.WaitGroup.Add before a previous *sync.WaitGroup.Wait returned
```go
package test

import (
	"runtime"
	"sync"
	"sync/atomic"
	"testing"
)

// Ripped directly from the Go tree
func TestWaitGroupMisuse2(t *testing.T) {
	if runtime.NumCPU() <= 4 {
		t.Skip("NumCPU<=4, skipping: this test requires parallelism")
	}
	defer func() {
		err := recover()
		if err != "sync: negative WaitGroup counter" &&
			err != "sync: WaitGroup misuse: Add called concurrently with Wait" &&
			err != "sync: WaitGroup is reused before previous Wait has returned" {
			t.Fatalf("Unexpected panic: %#v", err)
		}
	}()
	defer runtime.GOMAXPROCS(runtime.GOMAXPROCS(4))
	done := make(chan interface{}, 2)
	// The detection is opportunistic, so we want it to panic
	// at least in one run out of a million.
	for i := 0; i < 1e6; i++ {
		var wg sync.WaitGroup
		var here uint32
		wg.Add(1)
		go func() {
			defer func() {
				done <- recover()
			}()
			atomic.AddUint32(&here, 1)
			for atomic.LoadUint32(&here) != 3 {
				// spin
			}
			wg.Wait()
		}()
		go func() {
			defer func() {
				done <- recover()
			}()
			atomic.AddUint32(&here, 1)
			for atomic.LoadUint32(&here) != 3 {
				// spin
			}
			wg.Add(1) // This is the bad guy.
			wg.Done()
		}()
		atomic.AddUint32(&here, 1)
		for atomic.LoadUint32(&here) != 3 {
			// spin
		}
		wg.Done()
		for j := 0; j < 2; j++ {
			if err := <-done; err != nil {
				panic(err)
			}
		}
	}
	t.Fatal("Should panic")
}
```

**Comment by paralin** [comment]
Instead of using a wait group why not just come up with something using channels and maybe a context cancellation?

**Comment by melekes** [comment]
See https://github.com/tendermint/tmlibs/issues/112#issuecomment-353920065

**Comment by paralin** [comment]
> @paralin could you please run this command to find out the number of processors?
> ```shell
> $ system_profiler | grep Processor

I'm on Gentoo and don't have system_profiler. Here is my lscpu:

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               69
Model name:          Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
Stepping:            1
CPU MHz:             1151.660
CPU max MHz:         2900.0000
CPU min MHz:         800.0000
BogoMIPS:            4800.33
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            256K
L3 cache:            3072K
NUMA node0 CPU(s):   0-3
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts a
cpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_goo
d nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg f
ma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf
_lm abm cpuid_fault epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms
 invpcid xsaveopt dtherm ida arat pln pts                                                                
```

**Comment by odeke-em** [comment]
Awesome, thank you @paralin, it is as I had suspected, more CPUs more parallelism. @jaekwon has a PR to start working on this, please feel free to chime in at https://github.com/tendermint/tmlibs/pull/113.

**Comment by ebuchman** [comment]
@odeke-em @paralin @jaekwon is this fixed by the updates to `clist` to use mutexes (https://github.com/tendermint/tmlibs/pull/113) ?

**Comment by greg-szabo** [comment]
No update, bug is fixed. Please reopen if issue still occurs.
