### ISSUE TITLE
Loaded BlockCommit for catch-up printed every 100ms to output

### ISSUE THREAD

**Issue by paralin** [tendermint/tendermint#987]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report

**Tendermint version**:

v0.14.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

Source unavailable

**Environment**:
- **OS** (e.g. from /etc/os-release): Gentoo

**What happened**:

This message is printed to the output every 100ms:

```
I[12-18|20:55:20.010] Loaded BlockCommit for catch-up              module=consensus peer="Peer{MConn{172.1
7.0.2:60178} E00D0E52FB24 in}" height=97 commit="&{BlockID:3mdv1rEKRFwBgEAFeuYusPZ4P2mD:1:0E495A1C2216 Pre
commits:[Vote{0:D3C9DCEFDB66 97/00/2(Precommit) C6CC5B02E44E {/9C5295890F70.../}}] firstPrecommit:<nil> ha
sh:[] bitArray:<nil>}"                                                                                   
I[12-18|20:55:20.110] Loaded BlockCommit for catch-up              module=consensus peer="Peer{MConn{172.1
7.0.2:60178} E00D0E52FB24 in}" height=97 commit="&{BlockID:3mdv1rEKRFwBgEAFeuYusPZ4P2mD:1:0E495A1C2216 Pre
commits:[Vote{0:D3C9DCEFDB66 97/00/2(Precommit) C6CC5B02E44E {/9C5295890F70.../}}] firstPrecommit:<nil> ha
sh:[] bitArray:<nil>}"                                                                                   
I[12-18|20:55:20.210] Loaded BlockCommit for catch-up              module=consensus peer="Peer{MConn{172.1
7.0.2:60178} E00D0E52FB24 in}" height=97 commit="&{BlockID:3mdv1rEKRFwBgEAFeuYusPZ4P2mD:1:0E495A1C2216 Pre
commits:[Vote{0:D3C9DCEFDB66 97/00/2(Precommit) C6CC5B02E44E {/9C5295890F70.../}}] firstPrecommit:<nil> ha
sh:[] bitArray:<nil>}"                                                                                   
```

Blocks continue to be made correctly but this message is spammed.

**What you expected to happen**:

Not to have this spammed to the output when a peer is not reachable for whatever reason. I'd hate to imagine what this would look like with more than one peer.

**How to reproduce it** (as minimally and precisely as possible):

Run Tendermint normally with two nodes:

 - A: power 10, validator
 - B: power 0, not a validator, not in validator set

1. Start up Tendermint, the two peers sync.
2. Kill A after a few seconds
3. Restart A after a few seconds
4. A prints the above message every 100ms forever

**Comment by ebuchman** [comment]
Whoops thanks for this. Will clean up for next release.

**Comment by paralin** [comment]
@melekes I think it may have been more than just an issue of changing what level the message logs at. It was logging every 100Ms, the same message, for the same peer, for the same block, for minutes straight. Even at a debug level that seems wrong.

**Comment by ebuchman** [comment]
fixed on develop. thanks. 

let us know if there's any other logs you find particularly annoying/unhelpful, or if theres any logs that aren't there that you'd like to see.

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/issues/987#issuecomment-353156188

I think @paralin said there could be a bug or this is a normal behaviour given the test case above?

**Comment by ebuchman** [comment]
@paralin were either/both of the nodes failing to commit blocks?   

Otherwise, it's possible the non-validator node is always a couple blocks behind, in which case this would be expected, but it wasn't useful to have a log statement there. We do have a routine for each peer that checks if there are votes to send, and sleeps for 100ms. There are a few cases, depending on the height of the peer compared to our own, and in this case it seems like the peer is always "catching up" (ie. more than 1 behind). 

If the peer isn't committing new blocks though (eg it's stuck for a long time on height=97" there's another problem at foot.
