### ISSUE TITLE
installation instructions need updating

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#989]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.14.0-88f5f21

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:
```shell
$ uname -a
Darwin Emmanuels-MacBook-Pro-2.local 15.6.0 Darwin Kernel Version 15.6.0: Sun Jun  4 21:43:07 PDT 2017; root:xnu-3248.70.3~1/RELEASE_X86_64 x86_64```

**What happened**:
I built tendermint from scratch, starting with erasing my previous ~/.tendermint directory.
I looked at the instructions at http://tendermint.readthedocs.io/projects/tools/en/master/getting-started.html

```shell
$ tendermint init
$ tendermint node --proxy_app=dummy
ERROR: Failed to create node: Couldn't read GenesisDoc file: open /Users/emmanuelodeke/.tendermint/genesis.json: no such file or directory
```
I then pinged the internal engineering team but in vain
```shell
$ tendermint unsafe_reset_all
$ tendermint node --proxy_app=dummy
ERROR: Failed to create node: Couldn't read GenesisDoc file: open /Users/emmanuelodeke/.tendermint/genesis.json: no such file or directory
```
and then with other permutations of the suggestions
```shell
$ tendermint init
$ tendermint node --proxy_app=dummy
ERROR: Failed to create node: Couldn't read GenesisDoc file: open /Users/emmanuelodeke/.tendermint/genesis.json: no such file or directory
```

**What you expected to happen**:
I expected initialization to work

**How to reproduce it** (as minimally and precisely as possible):
Delete your ~/.tendermint directory and try to start afresh with the instructions at http://tendermint.readthedocs.io/projects/tools/en/master/getting-started.html

**Comment by ebuchman** [comment]
Lol ok. We could clearly improve this. The correct sequence of events is:

```
tendermint unsafe_reset_all
tendermint init
tendermint node --proxy_app=dummy
```

If you run `tendermint node`, it will create the ~/.tendermint dir with a config and priv val. If you then try to run `tendermint init`, it will not create the genesis. Of course it fails silently. Let's fix this.

**Comment by odeke-em** [comment]
@ebuchman even repeating the suggested correct sequence of still fails
```shell
$ tendermint unsafe_reset_all
$ tendermint init
$ tendermint node --proxy_app=dummy
ERROR: Failed to create node: Couldn't read GenesisDoc file: open /Users/emmanuelodeke/.tendermint/genesis.json: no such file or directory
``` 
If you haven't already, could you please try with the latest release which seems to be `0.14.0-88f5f21`?

**Comment by melekes** [comment]
Can't replicate this.

**Comment by melekes** [comment]
> Lol ok. We could clearly improve this. The correct sequence of events is:

if you're removing ~/.tendermint by hand, you don't need `unsafe_reset_all`.

**Comment by odeke-em** [comment]
@melekes offline suggested for output
```shell
$ ls -alh ~/.tendermint; tendermint unsafe_reset_all
ls: /Users/emmanuelodeke/.tendermint: No such file or directory
$
$ ls -alh ~/.tendermint; tendermint init
total 16
drwx------   4 emmanuelodeke  staff   136B 19 Dec 16:59 .
drwxr-xr-x+ 99 emmanuelodeke  staff   3.3K 19 Dec 16:59 ..
-rw-r--r--   1 emmanuelodeke  staff   329B 19 Dec 16:59 config.toml
-rw-------   1 emmanuelodeke  staff   392B 19 Dec 16:59 priv_validator.json
$
$ ls -alh ~/.tendermint; tendermint node --proxy_app=dummy
total 16
drwx------   5 emmanuelodeke  staff   170B 19 Dec 16:59 .
drwxr-xr-x+ 99 emmanuelodeke  staff   3.3K 19 Dec 16:59 ..
-rw-r--r--   1 emmanuelodeke  staff   329B 19 Dec 16:59 config.toml
drwx------   2 emmanuelodeke  staff    68B 19 Dec 16:59 data
-rw-------   1 emmanuelodeke  staff   392B 19 Dec 16:59 priv_validator.json
ERROR: Failed to create node: Couldn't read GenesisDoc file: open /Users/emmanuelodeke/.tendermint/genesis.json: no such file or directory
$
$ ls -alh ~/.tendermint
total 16
drwx------   5 emmanuelodeke  staff   170B 19 Dec 16:59 .
drwxr-xr-x+ 99 emmanuelodeke  staff   3.3K 19 Dec 16:59 ..
-rw-r--r--   1 emmanuelodeke  staff   329B 19 Dec 16:59 config.toml
drwx------   4 emmanuelodeke  staff   136B 19 Dec 16:59 data
-rw-------   1 emmanuelodeke  staff   392B 19 Dec 16:59 priv_validator.json
```

Alright, after the sherman dance offline, @ebuchman narrowed this down to
```shell
rm -rf ~/.tendermint
tendermint init
tendermint node --proxy_app=dummy
```
and it seems like the problem here is that we test for the existence of either the `priv_validators.json` or `config.toml` files or `data` dir already but not the `config.json` file itself which is the difference between the files when we have a successful start.

**Comment by odeke-em** [comment]
And the hunch seems right, the code in

https://github.com/tendermint/tendermint/blob/652d1e3de8a3f216299ca66c595cc66504930d28/cmd/tendermint/commands/init.go#L21-L40

then links to 
https://github.com/tendermint/tendermint/blob/88f5f21dbbf55589680d5e832647f5869f4fda1a/config/config.go#L140-L142

which then links to 

https://github.com/tendermint/tendermint/blob/88f5f21dbbf55589680d5e832647f5869f4fda1a/config/config.go#L454-L459

so if the `priv_validator.json` file already exists, we skip creating a GenesisDoc serialized file `genesis.json`.

Thank you @melekes and @ebuchman!
