### ISSUE TITLE
never set "Node.ABCIProtocol" on e2e test

### ISSUE THREAD

**Issue by tnasu** [tendermint/tendermint#9894]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

1a5d5ed63b510d303f7f64671c4fcdb06da4a96a

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

(none)

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

(all)

**What happened**:

`abci_protocol` for each node is not set correctly. All are `builtin`.

`ci.toml` seems to set `abci_protocol` for each node:
* https://github.com/tendermint/tendermint/blob/1a5d5ed63b510d303f7f64671c4fcdb06da4a96a/test/e2e/networks/ci.toml#L44
* https://github.com/tendermint/tendermint/blob/1a5d5ed63b510d303f7f64671c4fcdb06da4a96a/test/e2e/networks/ci.toml#L62

But, `LoadTestnet` never loads/sets into `ABCIProtocol` since it depends on `Testnet.ABCIProtocol` and `ci.toml` doesn't define `abci_protocol` in the section of `testnet`:
* https://github.com/tendermint/tendermint/blob/1a5d5ed63b510d303f7f64671c4fcdb06da4a96a/test/e2e/pkg/testnet.go#L188
* https://github.com/tendermint/tendermint/blob/1a5d5ed63b510d303f7f64671c4fcdb06da4a96a/test/e2e/pkg/testnet.go#L136
* https://github.com/tendermint/tendermint/blob/1a5d5ed63b510d303f7f64671c4fcdb06da4a96a/test/e2e/networks/ci.toml#L4-L10

**What you expected to happen**:

If `abci_protocol` should be set for each node, `LoadTestnet` function should modify.

**Have you tried the latest version**: yes/no

yes

**How to reproduce it** (as minimally and precisely as possible):

```
git clone git@github.com:tendermint/tendermint.git
cd tendermint/test/e2e
make runner
./build/runner -f ./networks/ci.toml setup
```

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
# cat ./networks/ci/validator02/config/app.toml
chain_id = "ci"
check_tx_delay = "0s"
dir = "data/app"
key_type = "ed25519"
mode = "validator"
persist_interval = 0
prepare_proposal_delay = "100ms"
privval_key = "config/priv_validator_key.json"
privval_server = "tcp://0.0.0.0:27559"
privval_state = "data/priv_validator_state.json"
process_proposal_delay = "100ms"
protocol = "builtin"
proxy_port = 5707
retain_blocks = 0
snapshot_interval = 0
sync_app = false
```

**Config (you can paste only the changes you've made)**:

**node command runtime flags**:

**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**

**Anything else we need to know**:

**Comment by thanethomson** [comment]
This was changed in #7078, but it doesn't look like the corresponding changes in the `ci.toml` file were made. We'll fix the `ci.toml` file accordingly, thanks for bringing it up!

In essence, how often will a single app chain be running nodes using different ABCI protocols on the same network? In our estimation, it's very unlikely.
