### ISSUE TITLE
Add new (separate-from-eviction) mempool metrics for purged transactions

### ISSUE THREAD

**Issue by BrendanChou** [tendermint/tendermint#9898]
## Summary

Add new mempool metrics for purged transactions

## Problem Definition

Right now the mempool metric for evicted transactions is re-used for purged transactions regardless of whether they are purged due to time or due to block height changes. This doesn't allow for full visibility into the behavior of the mempool. Instead, new, separate metrics should be used to record both kinds of purging.

## Proposal

Instead of using the `EvictedTxs` metrics 3 separate places in the code, introduce two new metrics: `PurgedDurationTxs` and `PurgedNumBlocksTxs` to track purging of transactions due to duration and number of blocks, respectively.

**Comment by thanethomson** [comment]
For clarity, this problem only relates to the priority (v1) mempool, right?

**Comment by BrendanChou** [comment]
I am a bit new to understanding the behavior difference between the v0 and v1 mempools but as far as I understand, yes
