### ISSUE TITLE
Add return values to transaction receipt?

### ISSUE THREAD

**Issue by dennismckinnon** [tendermint/tendermint#99]
I know that due to the time it takes to confirm a transaction into a block that there is no guarantee that the return data would be correct. But it would be helpful If I could get the return value of a transaction returned with the receipt.

For reference. BroadcastTx returns a result of a receipt type:
https://github.com/tendermint/tendermint/blob/develop/rpc/core_client/client_methods.go#L85

In essence I would like the fields from ResponseCall:
https://github.com/tendermint/tendermint/blob/develop/rpc/core/types/responses.go#L14-L18

Included with the Receipt:
https://github.com/tendermint/tendermint/blob/develop/rpc/core/types/responses.go#L45-L49

**Comment by ebuchman** [comment]
impossible because calls dont run until they are included in a block.
