### ISSUE TITLE
Multiple chains under a single node

### ISSUE THREAD

**Issue by paralin** [tendermint/tendermint#990]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

I'm interested if there has been any discussion around running multiple block-chains from a single Tendermint node. This could go hand-in-hand with using libp2p as our networking layer - with that in place, multiple "Node" objects in-proc can share a common communications bus and not wastefully consume more port bindings than necessary.

Could there be some optimizations that could be done by having a common node identity between multiple chains (priv_validator.json with multiple genesis) and the awareness in the protocol that multiple chains exist? Could there be some sort of ease-of-use in the API for this? It seems wasteful to run a separate llvm db for every chain as well, although it might be necessary.

**Comment by melekes** [comment]
There was a discussion about running different apps on top of the same TM core instance (https://github.com/tendermint/tendermint/issues/452, https://github.com/tendermint/abci/issues/74).

**Comment by GrapeBaBa** [comment]
We may also meet this issue when we plan introduce tendermint to hyperledger fabric. I created a jira task in fabric community https://jira.hyperledger.org/browse/FAB-8643, hope you guys  could also give      more suggestion

**Comment by zmanian** [comment]
@paralin We have done some work on shared security cosmos zones that we can hopefully publish soon.

There are a variety of reasons why I think multiple chains in the same TM process is a bad design and bad for throughput.

But we can pretty clearly extend IBC packets to enable other tendermint zones to follow the staking of a leader zone.

There can also be byzantine punishment from the follower zones to enable punishment on the leader zone.

**Comment by GrapeBaBa** [comment]
@zmanian can you share more detail? I would like to see if your approach can meet fabric

**Comment by zmanian** [comment]
@GrapeBaBa There will be more detail shortly.

The Fabric orderer api only has two calls if I remember correctly. SubmitTX and getBlock(height) 

It seems pretty easy to design a ABCI api and a facade similar to how Fabric does for Kafka.

If you want to be able to use Fabric to change the validator set, it gets more complicated.

**Comment by GrapeBaBa** [comment]
@zmanian how it support multiple channels?

**Comment by zmanian** [comment]
In Fabric, all the channels still share 1 chain or at least that was true when i last looked at Fabric

**Comment by GrapeBaBa** [comment]
What do you mean one chain? AFAIK, they use different Kafka partitions for different channels, all these channels are ordered separately.

**Comment by GrapeBaBa** [comment]
@zmanian did you in fabric rocketchat or tendermint roitchat, we can have a quick talk

**Comment by GrapeBaBa** [comment]
@jaekwon @ebuchman can you guys give us some suggestions? We plan to start integrate tendermint to fabric ASAP.

**Comment by zmanian** [comment]
Does fabric actually require channels to be on separate chains or is that just a performance optimization?

**Comment by GrapeBaBa** [comment]
that should be first i think

**Comment by dt665m** [comment]
any updates on this or has this discussion moved somewhere that remains public to view?

**Comment by zmanian** [comment]
I don't see this as being a priority for Tendermint Inc for the next 6 months at least. Too many other things to do.

**Comment by ebuchman** [comment]
> I don't see this as being a priority for Tendermint Inc for the next 6 months at least. Too many other things to do.

Agreed. If someone in the community wanted to take on writing up a design overview with requirements and how this would impact existing code, that would be super cool, though we might not have time to review it thoroughly for a few months

**Comment by jackzampolin** [comment]
Bumping here, is this still a feature folks are interested in? cc @hendrikhofstadt @ValarDragon

**Comment by hendrikhofstadt** [comment]
I think there's no justification for increasing the complexity of tendermint where one could also easily run 2 processes. Tendermint is not very heavy.

**Comment by paralin** [comment]
> I think there's no justification for increasing the complexity of tendermint where one could also easily run 2 processes. Tendermint is not very heavy.

To say this indicates a fundamental difference in understanding of the purpose of a blockchain and/or a software framework.

**Comment by hendrikhofstadt** [comment]
@paralin could you please elaborate where this would make sense in your opinion.

**Comment by jackzampolin** [comment]
Going to go ahead and close this issue as I happen to agree strongly with @hendrikhofstadt here.
