### ISSUE TITLE
TendermintCore will soon be an archive repo.

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#9972]
From hereon, we will encourage forks of new distinct names, to create their variations of TendermintCore.
From various reports I understand that version 0.34.xx is the latest stable version of TendermintCore. (which is what cosmoshub-4 uses).

Bug fixes to 0.34.xx (and further enlightenment on the 0.35+ situation) are welcome,
but first we will organize a discussion where everyone is invited. 

In addition, I am advocating and executing on creating an interbranch development team to be managed by the Decentralists DAO that will help create better refactoring of our code (and security/improvement patches upstream) to best manage all major derivations/branches of Tendermint, including Tendermint2, and the name that Informal chooses. 

For non-gardeners, the benefits of pruning can be non-intuitive, but I believe in the long run can be best for everyone. So I hope we take this as an opportunity to create more diverse teams and begin to use our DAO systems to coordinate among them, all partially funded in the future by governance of the hub.

Please make a PR here: https://github.com/tendermint/ecosystem

**Comment by kungla** [comment]
More detailed explanation can be found here:
https://docs.google.com/forms/d/e/1FAIpQLSeAZ4ILjJL39Fk_LIZD0L5qvFt4mqONVPaQ-ODuFSF0-dx4hw/viewform

**Comment by thanethomson** [comment]
The Informal Systems team that was working on Tendermint Core until 22 December 2022 will continue working on a fork of Tendermint Core called CometBFT: https://github.com/cometbft/cometbft

The official announcement from Informal Systems: https://twitter.com/informalinc/status/1620825636213526528

More details can be found in this blog post: https://informal.systems/blog/cosmos-meet-cometbft

**Comment by nyetwurk** [comment]
The readme should be updated with this front and center.

https://github.com/tendermint/tendermint/issues/10172
