### ISSUE TITLE
Unknown revision v0.34.26

### ISSUE THREAD

**Issue by Kunjan-Shah** [tendermint/tendermint#9997]
On running:
go get github.com/cosmos/cosmos-sdk/crypto/hd
I am getting the following error: 
go: github.com/tendermint/tendermint@v0.34.26: reading github.com/tendermint/tendermint/go.mod at revision v0.34.26: unknown revision v0.34.26

**Comment by Kunjan-Shah** [comment]
The issue seems to be that the path it is looking for is github.com/tendermint/tendermint/go.mod but actually the path is github.com/tendermint/tendermint/blob/main/go.mod

**Comment by lasarojc** [comment]
Tag v0.34.26 exists in the Informal's fork of tendermint, here: https://github.com/informalsystems/tendermint/tree/v0.34.26
If you have any issues using the SDK, you should open an issue on cosmos-sdk project: https://github.com/cosmos/cosmos-sdk/issues
